{
  "abstract": [
    {
      "text": "The APIs for working with the framework’s Metadata Identifier Services and Metadata Data Type Registry.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CMMetadata APIs"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Core Media framework provides two services: Metadata Identifier Services and the Metadata Data Type Registry.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Metadata Identifier Services provide a means of encoding the metadata identifying tuple (four-byte key namespace and N-byte key value) into ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfstring",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and back again.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The Metadata Data Type Registry allows a process to register metadata data types that conform to a base data type and (optionally) other registered data types. The registry simplifies the process of creating format descriptions for nontrivial metadata values and allowing clients to indicate how to interpret metadata.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataCreateIdentifierForKeyAndKeySpace(allocator:key:keySpace:identifierOut:)": {
      "abstract": [
        {
          "text": "Creates a URL-like string identifier that represents a key or keyspace tuple.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMetadataCreateIdentifierForKeyAndKeySpace"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "key"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "keySpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identifierOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataCreateIdentifierForKeyAndKeySpace(allocator:key:keySpace:identifierOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMetadataCreateIdentifierForKeyAndKeySpace"
        }
      ],
      "role": "symbol",
      "title": "CMMetadataCreateIdentifierForKeyAndKeySpace(allocator:key:keySpace:identifierOut:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadatacreateidentifierforkeyandkeyspace(allocator:key:keyspace:identifierout:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataCreateKeyFromIdentifier(allocator:identifier:keyOut:)": {
      "abstract": [
        {
          "text": "Creates a copy of the key by using an identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMetadataCreateKeyFromIdentifier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "keyOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataCreateKeyFromIdentifier(allocator:identifier:keyOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMetadataCreateKeyFromIdentifier"
        }
      ],
      "role": "symbol",
      "title": "CMMetadataCreateKeyFromIdentifier(allocator:identifier:keyOut:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadatacreatekeyfromidentifier(allocator:identifier:keyout:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataCreateKeyFromIdentifierAsCFData(allocator:identifier:keyOut:)": {
      "abstract": [
        {
          "text": "Creates a copy of the key by using an identifier, and results in a core foundation data object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMetadataCreateKeyFromIdentifierAsCFData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "keyOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataCreateKeyFromIdentifierAsCFData(allocator:identifier:keyOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMetadataCreateKeyFromIdentifierAsCFData"
        }
      ],
      "role": "symbol",
      "title": "CMMetadataCreateKeyFromIdentifierAsCFData(allocator:identifier:keyOut:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadatacreatekeyfromidentifierascfdata(allocator:identifier:keyout:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataCreateKeySpaceFromIdentifier(allocator:identifier:keySpaceOut:)": {
      "abstract": [
        {
          "text": "Creates a copy of the keyspace by using an identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMetadataCreateKeySpaceFromIdentifier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "keySpaceOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?>) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataCreateKeySpaceFromIdentifier(allocator:identifier:keySpaceOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMetadataCreateKeySpaceFromIdentifier"
        }
      ],
      "role": "symbol",
      "title": "CMMetadataCreateKeySpaceFromIdentifier(allocator:identifier:keySpaceOut:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadatacreatekeyspacefromidentifier(allocator:identifier:keyspaceout:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryDataTypeConformsToDataType(_:conformsTo:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a data type conforms to another data type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMetadataDataTypeRegistryDataTypeConformsToDataType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "conformsTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryDataTypeConformsToDataType(_:conformsTo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMetadataDataTypeRegistryDataTypeConformsToDataType"
        }
      ],
      "role": "symbol",
      "title": "CMMetadataDataTypeRegistryDataTypeConformsToDataType(_:conformsTo:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadatadatatyperegistrydatatypeconformstodatatype(_:conformsto:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryDataTypeIsBaseDataType(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a data type identifier represents a base data type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMetadataDataTypeRegistryDataTypeIsBaseDataType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryDataTypeIsBaseDataType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMetadataDataTypeRegistryDataTypeIsBaseDataType"
        }
      ],
      "role": "symbol",
      "title": "CMMetadataDataTypeRegistryDataTypeIsBaseDataType(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadatadatatyperegistrydatatypeisbasedatatype(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryDataTypeIsRegistered(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates the registration status of a data type identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMetadataDataTypeRegistryDataTypeIsRegistered"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryDataTypeIsRegistered(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMetadataDataTypeRegistryDataTypeIsRegistered"
        }
      ],
      "role": "symbol",
      "title": "CMMetadataDataTypeRegistryDataTypeIsRegistered(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadatadatatyperegistrydatatypeisregistered(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryGetBaseDataTypeForConformingDataType(_:)": {
      "abstract": [
        {
          "text": "Returns the base data type identifier that a data type conforms to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMetadataDataTypeRegistryGetBaseDataTypeForConformingDataType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryGetBaseDataTypeForConformingDataType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMetadataDataTypeRegistryGetBaseDataTypeForConformingDataType"
        }
      ],
      "role": "symbol",
      "title": "CMMetadataDataTypeRegistryGetBaseDataTypeForConformingDataType(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadatadatatyperegistrygetbasedatatypeforconformingdatatype(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryGetBaseDataTypes()": {
      "abstract": [
        {
          "text": "Returns an array of base data type identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMetadataDataTypeRegistryGetBaseDataTypes"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryGetBaseDataTypes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMetadataDataTypeRegistryGetBaseDataTypes"
        }
      ],
      "role": "symbol",
      "title": "CMMetadataDataTypeRegistryGetBaseDataTypes()",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadatadatatyperegistrygetbasedatatypes()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryGetConformingDataTypes(_:)": {
      "abstract": [
        {
          "text": "Returns the conforming data types for the data type, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMetadataDataTypeRegistryGetConformingDataTypes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryGetConformingDataTypes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMetadataDataTypeRegistryGetConformingDataTypes"
        }
      ],
      "role": "symbol",
      "title": "CMMetadataDataTypeRegistryGetConformingDataTypes(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadatadatatyperegistrygetconformingdatatypes(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryGetDataTypeDescription(_:)": {
      "abstract": [
        {
          "text": "Returns the data type description if it exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMetadataDataTypeRegistryGetDataTypeDescription"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryGetDataTypeDescription(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMetadataDataTypeRegistryGetDataTypeDescription"
        }
      ],
      "role": "symbol",
      "title": "CMMetadataDataTypeRegistryGetDataTypeDescription(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadatadatatyperegistrygetdatatypedescription(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryRegisterDataType(_:description:conformingDataTypes:)": {
      "abstract": [
        {
          "text": "Register a data type with the data type registry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMetadataDataTypeRegistryRegisterDataType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "description"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "conformingDataTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryRegisterDataType(_:description:conformingDataTypes:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMetadataDataTypeRegistryRegisterDataType"
        }
      ],
      "role": "symbol",
      "title": "CMMetadataDataTypeRegistryRegisterDataType(_:description:conformingDataTypes:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadatadatatyperegistryregisterdatatype(_:description:conformingdatatypes:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType": {
      "abstract": [
        {
          "text": "The type of packing within each video frame, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMPackingType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMPackingType"
        }
      ],
      "role": "symbol",
      "title": "CMPackingType",
      "type": "topic",
      "url": "/documentation/coremedia/cmpackingtype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType": {
      "abstract": [
        {
          "text": "Constants describing the projection surface information in a 3D video buffer or channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMProjectionType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMProjectionType"
        }
      ],
      "role": "symbol",
      "title": "CMProjectionType",
      "type": "topic",
      "url": "/documentation/coremedia/cmprojectiontype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents": {
      "abstract": [
        {
          "text": "Constants describing the stereo views contained within a buffer or channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMStereoViewComponents"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMStereoViewComponents"
        }
      ],
      "role": "symbol",
      "title": "CMStereoViewComponents",
      "type": "topic",
      "url": "/documentation/coremedia/cmstereoviewcomponents"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions": {
      "abstract": [
        {
          "text": "Create a set of stereo view interpretation options from a constant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMStereoViewInterpretationOptions"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMStereoViewInterpretationOptions"
        }
      ],
      "role": "symbol",
      "title": "CMStereoViewInterpretationOptions",
      "type": "topic",
      "url": "/documentation/coremedia/cmstereoviewinterpretationoptions"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class": {
      "abstract": [
        {
          "text": "A tag to set additional metadata on media buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "role": "symbol",
      "title": "CMTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag": {
      "abstract": [
        {
          "text": "A tag to set additional metadata on media buffers, with an associated Swift type for its value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTypedTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTypedTag"
        }
      ],
      "role": "symbol",
      "title": "CMTypedTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtypedtag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api": {
      "abstract": [
        {
          "text": "Types and interfaces for working with Core Media tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTag APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection": {
      "abstract": [
        {
          "text": "Objective-C types and interfaces for working with Core Media tag collections.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTagCollection APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollection"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types": {
      "abstract": [
        {
          "text": "Constants that describe metadata base data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Base Data Types",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-base-data-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types": {
      "abstract": [
        {
          "text": "Constants that describe metadata data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Data Types",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-data-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors": {
      "abstract": [
        {
          "text": "Error codes that indicate metadata identifier errors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Identifier Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-identifier-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces": {
      "abstract": [
        {
          "text": "Constants that describe metadata identifier keyspaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Identifier Keyspaces",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-identifier-keyspaces"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers": {
      "abstract": [
        {
          "text": "Constants that describe metadata identifiers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Identifiers",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-identifiers"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors": {
      "abstract": [
        {
          "text": "Error codes that indicate metadata registry errors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Registry Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-registry-errors"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfstring": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Metadata",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType"
      ],
      "title": "Metadata"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Metadata-Identifiers",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataCreateIdentifierForKeyAndKeySpace(allocator:key:keySpace:identifierOut:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataCreateKeyFromIdentifier(allocator:identifier:keyOut:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataCreateKeyFromIdentifierAsCFData(allocator:identifier:keyOut:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataCreateKeySpaceFromIdentifier(allocator:identifier:keySpaceOut:)"
      ],
      "title": "Creating Metadata Identifiers"
    },
    {
      "anchor": "Registering-Metadata",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryRegisterDataType(_:description:conformingDataTypes:)"
      ],
      "title": "Registering Metadata"
    },
    {
      "anchor": "Inspecting-Metadata",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryDataTypeIsRegistered(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryGetDataTypeDescription(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryGetConformingDataTypes(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryDataTypeConformsToDataType(_:conformsTo:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryDataTypeIsBaseDataType(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryGetBaseDataTypeForConformingDataType(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryGetBaseDataTypes()"
      ],
      "title": "Inspecting Metadata"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Metadata-Identifiers",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataCreateIdentifierForKeyAndKeySpace(allocator:key:keySpace:identifierOut:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataCreateKeyFromIdentifier(allocator:identifier:keyOut:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataCreateKeyFromIdentifierAsCFData(allocator:identifier:keyOut:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataCreateKeySpaceFromIdentifier(allocator:identifier:keySpaceOut:)"
              ],
              "title": "Creating Metadata Identifiers"
            },
            {
              "anchor": "Registering-Metadata",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryRegisterDataType(_:description:conformingDataTypes:)"
              ],
              "title": "Registering Metadata"
            },
            {
              "anchor": "Inspecting-Metadata",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryDataTypeIsRegistered(_:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryGetDataTypeDescription(_:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryGetConformingDataTypes(_:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryDataTypeConformsToDataType(_:conformsTo:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryDataTypeIsBaseDataType(_:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryGetBaseDataTypeForConformingDataType(_:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataDataTypeRegistryGetBaseDataTypes()"
              ],
              "title": "Inspecting Metadata"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Metadata",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType"
              ],
              "title": "Metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMProjectionType/title",
          "value": "CMProjectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMProjectionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMProjectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMProjectionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMProjectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewComponents/title",
          "value": "CMStereoViewComponents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewComponents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewComponents/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataCreateKeyFromIdentifier(allocator:identifier:keyOut:)/title",
          "value": "CMMetadataCreateKeyFromIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataCreateKeyFromIdentifier(allocator:identifier:keyOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataCreateKeyFromIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataCreateIdentifierForKeyAndKeySpace(allocator:key:keySpace:identifierOut:)/title",
          "value": "CMMetadataCreateIdentifierForKeyAndKeySpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataCreateIdentifierForKeyAndKeySpace(allocator:key:keySpace:identifierOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataCreateIdentifierForKeyAndKeySpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataCreateKeySpaceFromIdentifier(allocator:identifier:keySpaceOut:)/title",
          "value": "CMMetadataCreateKeySpaceFromIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataCreateKeySpaceFromIdentifier(allocator:identifier:keySpaceOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataCreateKeySpaceFromIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataDataTypeRegistryGetConformingDataTypes(_:)/title",
          "value": "CMMetadataDataTypeRegistryGetConformingDataTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataDataTypeRegistryGetConformingDataTypes(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataDataTypeRegistryGetConformingDataTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataDataTypeRegistryDataTypeConformsToDataType(_:conformsTo:)/title",
          "value": "CMMetadataDataTypeRegistryDataTypeConformsToDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataDataTypeRegistryDataTypeConformsToDataType(_:conformsTo:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataDataTypeRegistryDataTypeConformsToDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataDataTypeRegistryDataTypeIsRegistered(_:)/title",
          "value": "CMMetadataDataTypeRegistryDataTypeIsRegistered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataDataTypeRegistryDataTypeIsRegistered(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataDataTypeRegistryDataTypeIsRegistered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataDataTypeRegistryGetBaseDataTypes()/title",
          "value": "CMMetadataDataTypeRegistryGetBaseDataTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataDataTypeRegistryGetBaseDataTypes()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataDataTypeRegistryGetBaseDataTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfstring/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType/title",
          "value": "CMPackingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPackingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPackingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataDataTypeRegistryRegisterDataType(_:description:conformingDataTypes:)/title",
          "value": "CMMetadataDataTypeRegistryRegisterDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataDataTypeRegistryRegisterDataType(_:description:conformingDataTypes:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataDataTypeRegistryRegisterDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataDataTypeRegistryGetDataTypeDescription(_:)/title",
          "value": "CMMetadataDataTypeRegistryGetDataTypeDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataDataTypeRegistryGetDataTypeDescription(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataDataTypeRegistryGetDataTypeDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataCreateKeyFromIdentifierAsCFData(allocator:identifier:keyOut:)/title",
          "value": "CMMetadataCreateKeyFromIdentifierAsCFData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataCreateKeyFromIdentifierAsCFData(allocator:identifier:keyOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataCreateKeyFromIdentifierAsCFData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataDataTypeRegistryDataTypeIsBaseDataType(_:)/title",
          "value": "CMMetadataDataTypeRegistryDataTypeIsBaseDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataDataTypeRegistryDataTypeIsBaseDataType(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataDataTypeRegistryDataTypeIsBaseDataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions/title",
          "value": "CMStereoViewInterpretationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewInterpretationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewInterpretationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataDataTypeRegistryGetBaseDataTypeForConformingDataType(_:)/title",
          "value": "CMMetadataDataTypeRegistryGetBaseDataTypeForConformingDataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataDataTypeRegistryGetBaseDataTypeForConformingDataType(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataDataTypeRegistryGetBaseDataTypeForConformingDataType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmmetadata"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmmetadata"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
