{
  "abstract": [
    {
      "text": "The type of packing within each video frame, if any.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CMPackingType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMPackingType"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMPackingType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CMPackingType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMPackingType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Frame-packed video contains both the left and right eye images on a single video track. With frame-packed video, use the appropriate Frame Arrangement.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType": {
      "abstract": [
        {
          "text": "The type of packing within each video frame, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMPackingType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMPackingType"
        }
      ],
      "role": "symbol",
      "title": "CMPackingType",
      "type": "topic",
      "url": "/documentation/coremedia/cmpackingtype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmpackingtype/init(rawvalue:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType/none": {
      "abstract": [
        {
          "text": "Each frame contains only a single image, and isn’t frame-packed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPackingType_None"
        }
      ],
      "role": "symbol",
      "title": "CMPackingType.none",
      "type": "topic",
      "url": "/documentation/coremedia/cmpackingtype/none"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType/overUnder": {
      "abstract": [
        {
          "text": "The video contains packed frames that have a left eye image on the top and right eye image on the bottom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overUnder"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType/overUnder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPackingType_OverUnder"
        }
      ],
      "role": "symbol",
      "title": "CMPackingType.overUnder",
      "type": "topic",
      "url": "/documentation/coremedia/cmpackingtype/overunder"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType/sideBySide": {
      "abstract": [
        {
          "text": "The video contains packed frames that have a left eye image on the left and right eye image on the right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sideBySide"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType/sideBySide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPackingType_SideBySide"
        }
      ],
      "role": "symbol",
      "title": "CMPackingType.sideBySide",
      "type": "topic",
      "url": "/documentation/coremedia/cmpackingtype/sidebyside"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType": {
      "abstract": [
        {
          "text": "Constants describing the projection surface information in a 3D video buffer or channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMProjectionType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMProjectionType"
        }
      ],
      "role": "symbol",
      "title": "CMProjectionType",
      "type": "topic",
      "url": "/documentation/coremedia/cmprojectiontype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents": {
      "abstract": [
        {
          "text": "Constants describing the stereo views contained within a buffer or channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMStereoViewComponents"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMStereoViewComponents"
        }
      ],
      "role": "symbol",
      "title": "CMStereoViewComponents",
      "type": "topic",
      "url": "/documentation/coremedia/cmstereoviewcomponents"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions": {
      "abstract": [
        {
          "text": "Create a set of stereo view interpretation options from a constant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMStereoViewInterpretationOptions"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMStereoViewInterpretationOptions"
        }
      ],
      "role": "symbol",
      "title": "CMStereoViewInterpretationOptions",
      "type": "topic",
      "url": "/documentation/coremedia/cmstereoviewinterpretationoptions"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class": {
      "abstract": [
        {
          "text": "A tag to set additional metadata on media buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "role": "symbol",
      "title": "CMTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag": {
      "abstract": [
        {
          "text": "A tag to set additional metadata on media buffers, with an associated Swift type for its value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTypedTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTypedTag"
        }
      ],
      "role": "symbol",
      "title": "CMTypedTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtypedtag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata": {
      "abstract": [
        {
          "text": "The APIs for working with the framework’s Metadata Identifier Services and Metadata Data Type Registry.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMMetadata APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api": {
      "abstract": [
        {
          "text": "Types and interfaces for working with Core Media tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTag APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection": {
      "abstract": [
        {
          "text": "Objective-C types and interfaces for working with Core Media tag collections.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTagCollection APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@uint64_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uint64_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint64_t",
      "type": "topic",
      "url": "/documentation/kernel/uint64_t"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Metadata",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions"
      ],
      "title": "Metadata"
    }
  ],
  "topicSections": [
    {
      "anchor": "Frame-Arrangement",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType/none",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType/sideBySide",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType/overUnder"
      ],
      "title": "Frame Arrangement"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMPackingType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPackingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPackingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Frame-Arrangement",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType/none",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType/sideBySide",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType/overUnder"
              ],
              "title": "Frame Arrangement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Metadata",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions"
              ],
              "title": "Metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMPackingType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@uint64_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint64_t",
                    "text": "uint64_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType~1none/title",
          "value": "kCMPackingType_None"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPackingType_None"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType/title",
          "value": "CMPackingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPackingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPackingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMProjectionType/title",
          "value": "CMProjectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMProjectionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMProjectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMProjectionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMProjectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewComponents/title",
          "value": "CMStereoViewComponents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewComponents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewComponents/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions/title",
          "value": "CMStereoViewInterpretationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewInterpretationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewInterpretationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType~1overUnder/title",
          "value": "kCMPackingType_OverUnder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType~1overUnder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPackingType_OverUnder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType~1sideBySide/title",
          "value": "kCMPackingType_SideBySide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType~1sideBySide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPackingType_SideBySide"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmpackingtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmpackingtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
