{
  "abstract": [
    {
      "text": "A pixel format type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMPixelFormatType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CMPixelFormatType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMPixelFormatType"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMPixelFormatType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "CMPixelFormatType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMPixelFormatType"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@FourCharCode",
              "text": "FourCharCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Only some codec types are pixel formats.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatType": {
      "abstract": [
        {
          "text": "A closed caption format type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMClosedCaptionFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMClosedCaptionFormatType"
        }
      ],
      "role": "symbol",
      "title": "CMClosedCaptionFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmclosedcaptionformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataFormatType": {
      "abstract": [
        {
          "text": "A metadata format type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMetadataFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMetadataFormatType"
        }
      ],
      "role": "symbol",
      "title": "CMMetadataFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadataformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMPixelFormatType": {
      "abstract": [
        {
          "text": "A pixel format type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMPixelFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMPixelFormatType"
        }
      ],
      "role": "symbol",
      "title": "CMPixelFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmpixelformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSubtitleFormatType": {
      "abstract": [
        {
          "text": "A type that represents a text subtitle format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSubtitleFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSubtitleFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSubtitleFormatType"
        }
      ],
      "role": "symbol",
      "title": "CMSubtitleFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmsubtitleformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTextFormatType": {
      "abstract": [
        {
          "text": "A text format type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTextFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTextFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTextFormatType"
        }
      ],
      "role": "symbol",
      "title": "CMTextFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmtextformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatType": {
      "abstract": [
        {
          "text": "A time code format type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeCodeFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeCodeFormatType"
        }
      ],
      "role": "symbol",
      "title": "CMTimeCodeFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimecodeformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16BE555": {
      "abstract": [
        {
          "text": "A type that describes 16-bit big-endian 5-5-5.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_16BE555"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16BE555",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_16BE555"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_16BE555",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_16be555"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16BE565": {
      "abstract": [
        {
          "text": "A type that describes 16-bit big-endian 5-6-5.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_16BE565"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16BE565",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_16BE565"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_16BE565",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_16be565"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE555": {
      "abstract": [
        {
          "text": "A type that describes 16-bit little-endian 5-5-5.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_16LE555"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE555",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_16LE555"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_16LE555",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_16le555"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE5551": {
      "abstract": [
        {
          "text": "A type that describes 16-bit little-endian 5-5-5-1.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_16LE5551"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE5551",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_16LE5551"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_16LE5551",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_16le5551"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE565": {
      "abstract": [
        {
          "text": "A type that describes 16-bit little-endian 5-6-5.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_16LE565"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE565",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_16LE565"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_16LE565",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_16le565"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_24RGB": {
      "abstract": [
        {
          "text": "A type that describes 24-bit RGB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_24RGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_24RGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_24RGB"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_24RGB",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_24rgb"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_32ARGB": {
      "abstract": [
        {
          "text": "A type that describes 32-bit ARGB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_32ARGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_32ARGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_32ARGB"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_32ARGB",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_32argb"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_32BGRA": {
      "abstract": [
        {
          "text": "A type that describes 32-bit BGRA.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_32BGRA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_32BGRA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_32BGRA"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_32BGRA",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_32bgra"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr10": {
      "abstract": [
        {
          "text": "A type that describes component Y’CbCr 10-bit 4:2:2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_422YpCbCr10"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr10",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_422YpCbCr10"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_422YpCbCr10",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_422ypcbcr10"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr16": {
      "abstract": [
        {
          "text": "A type that describes component Y’CbCr 10,12,14,16-bit 4:2:2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_422YpCbCr16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_422YpCbCr16"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_422YpCbCr16",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_422ypcbcr16"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr8": {
      "abstract": [
        {
          "text": "A type that describes component Y’CbCr 8-bit 4:2:2 ordered Cb Y’0 Cr Y’1.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_422YpCbCr8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_422YpCbCr8"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_422YpCbCr8",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_422ypcbcr8"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr8_yuvs": {
      "abstract": [
        {
          "text": "A type that describes component Y’CbCr 8-bit 4:2:2 ordered Y’0 Cb Y’1 Cr.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_422YpCbCr8_yuvs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr8_yuvs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_422YpCbCr8_yuvs"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_422YpCbCr8_yuvs",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_422ypcbcr8_yuvs"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_4444YpCbCrA8": {
      "abstract": [
        {
          "text": "A type that describes component Y’CbCrA 8-bit 4:4:4:4.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_4444YpCbCrA8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_4444YpCbCrA8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_4444YpCbCrA8"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_4444YpCbCrA8",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_4444ypcbcra8"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_444YpCbCr10": {
      "abstract": [
        {
          "text": "A type that describes component Y’CbCr 10-bit 4:4:4",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_444YpCbCr10"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_444YpCbCr10",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_444YpCbCr10"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_444YpCbCr10",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_444ypcbcr10"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_444YpCbCr8": {
      "abstract": [
        {
          "text": "A type that describes component Y’CbCr 8-bit 4:4:4.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_444YpCbCr8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_444YpCbCr8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_444YpCbCr8"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_444YpCbCr8",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_444ypcbcr8"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_8IndexedGray_WhiteIsZero": {
      "abstract": [
        {
          "text": "A type that describes 8-bit indexed gray, white is zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_8IndexedGray_WhiteIsZero"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_8IndexedGray_WhiteIsZero",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_8IndexedGray_WhiteIsZero"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_8IndexedGray_WhiteIsZero",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_8indexedgray_whiteiszero"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-types": {
      "abstract": [
        {
          "text": "Constants that represent media format types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Format Types",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-format-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/subtitle-format-types": {
      "abstract": [
        {
          "text": "Constants that represent subtitle format types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/subtitle-format-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Subtitle Format Types",
      "type": "topic",
      "url": "/documentation/coremedia/subtitle-format-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/tagged-buffergroup-format-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/tagged-buffergroup-format-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Tagged Buffer Group Format Types",
      "type": "topic",
      "url": "/documentation/coremedia/tagged-buffergroup-format-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/time-code-formats": {
      "abstract": [
        {
          "text": "Constants that represent time code format types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/time-code-formats",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Time Code Formats",
      "type": "topic",
      "url": "/documentation/coremedia/time-code-formats"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Format-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataFormatType",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-types",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSubtitleFormatType",
        "doc://com.apple.coremedia/documentation/CoreMedia/subtitle-format-types",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatType",
        "doc://com.apple.coremedia/documentation/CoreMedia/time-code-formats",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTextFormatType",
        "doc://com.apple.coremedia/documentation/CoreMedia/tagged-buffergroup-format-types"
      ],
      "title": "Format Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_32ARGB",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_32BGRA",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_24RGB",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16BE555",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16BE565",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE555",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE565",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE5551",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr8",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr8_yuvs",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_444YpCbCr8",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_4444YpCbCrA8",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr16",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr10",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_444YpCbCr10",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_8IndexedGray_WhiteIsZero"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMPixelFormatType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPixelFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPixelFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_32ARGB",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_32BGRA",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_24RGB",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16BE555",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16BE565",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE555",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE565",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE5551",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr8",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr8_yuvs",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_444YpCbCr8",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_4444YpCbCrA8",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr16",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr10",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_444YpCbCr10",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_8IndexedGray_WhiteIsZero"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Format-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataFormatType",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-types",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMSubtitleFormatType",
                "doc://com.apple.coremedia/documentation/CoreMedia/subtitle-format-types",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatType",
                "doc://com.apple.coremedia/documentation/CoreMedia/time-code-formats",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTextFormatType",
                "doc://com.apple.coremedia/documentation/CoreMedia/tagged-buffergroup-format-types"
              ],
              "title": "Format Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@FourCharCode",
                    "text": "FourCharCode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMPixelFormatType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_16BE555/title",
          "value": "kCMPixelFormat_16BE555"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_16BE555/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_16BE555"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeCodeFormatType/title",
          "value": "CMTimeCodeFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeCodeFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeCodeFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeCodeFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeCodeFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_4444YpCbCrA8/title",
          "value": "kCMPixelFormat_4444YpCbCrA8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_4444YpCbCrA8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_4444YpCbCrA8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextFormatType/title",
          "value": "CMTextFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_444YpCbCr10/title",
          "value": "kCMPixelFormat_444YpCbCr10"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_444YpCbCr10/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_444YpCbCr10"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_422YpCbCr8/title",
          "value": "kCMPixelFormat_422YpCbCr8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_422YpCbCr8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_422YpCbCr8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_444YpCbCr8/title",
          "value": "kCMPixelFormat_444YpCbCr8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_444YpCbCr8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_444YpCbCr8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_24RGB/title",
          "value": "kCMPixelFormat_24RGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_24RGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_24RGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_16LE5551/title",
          "value": "kCMPixelFormat_16LE5551"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_16LE5551/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_16LE5551"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_422YpCbCr16/title",
          "value": "kCMPixelFormat_422YpCbCr16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_422YpCbCr16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_422YpCbCr16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSubtitleFormatType/title",
          "value": "CMSubtitleFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSubtitleFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSubtitleFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSubtitleFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSubtitleFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_422YpCbCr8_yuvs/title",
          "value": "kCMPixelFormat_422YpCbCr8_yuvs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_422YpCbCr8_yuvs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_422YpCbCr8_yuvs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_8IndexedGray_WhiteIsZero/title",
          "value": "kCMPixelFormat_8IndexedGray_WhiteIsZero"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_8IndexedGray_WhiteIsZero/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_8IndexedGray_WhiteIsZero"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClosedCaptionFormatType/title",
          "value": "CMClosedCaptionFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClosedCaptionFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClosedCaptionFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClosedCaptionFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClosedCaptionFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPixelFormatType/title",
          "value": "CMPixelFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPixelFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPixelFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPixelFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPixelFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_16LE555/title",
          "value": "kCMPixelFormat_16LE555"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_16LE555/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_16LE555"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataFormatType/title",
          "value": "CMMetadataFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_16LE565/title",
          "value": "kCMPixelFormat_16LE565"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_16LE565/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_16LE565"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_16BE565/title",
          "value": "kCMPixelFormat_16BE565"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_16BE565/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_16BE565"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_422YpCbCr10/title",
          "value": "kCMPixelFormat_422YpCbCr10"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_422YpCbCr10/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_422YpCbCr10"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_32BGRA/title",
          "value": "kCMPixelFormat_32BGRA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_32BGRA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_32BGRA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_32ARGB/title",
          "value": "kCMPixelFormat_32ARGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_32ARGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_32ARGB"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmpixelformattype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmpixelformattype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
