{
  "abstract": [
    {
      "text": "A reference to a buffer of media data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CMSampleBufferRef",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMSampleBuffer"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMSampleBuffer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CMSampleBuffer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMSampleBuffer"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A sample buffer is a Core Foundation object that contains zero or more media samples of a particular type (audio, video, muxed, and so on).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentBearerProtocol": {
      "abstract": [
        {
          "text": "A protocol for objects that can carry attachments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMAttachmentBearerProtocol"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentBearerProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMAttachmentBearerProtocol"
        }
      ],
      "role": "symbol",
      "title": "CMAttachmentBearerProtocol",
      "type": "topic",
      "url": "/documentation/coremedia/cmattachmentbearerprotocol"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBuffer": {
      "abstract": [
        {
          "text": "A reference to a buffer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBuffer"
        }
      ],
      "role": "symbol",
      "title": "CMBuffer",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetSizeCallback": {
      "abstract": [
        {
          "text": "A client callback that returns a size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferGetSizeCallback"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetSizeCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferGetSizeCallback"
        }
      ],
      "role": "symbol",
      "title": "CMBufferGetSizeCallback",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffergetsizecallback"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount": {
      "abstract": [
        {
          "text": "A datatype that represents an item count.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMItemCount"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMItemCount"
        }
      ],
      "role": "symbol",
      "title": "CMItemCount",
      "type": "topic",
      "url": "/documentation/coremedia/cmitemcount"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMItemIndex": {
      "abstract": [
        {
          "text": "A datatype that represents an item index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMItemIndex"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMItemIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMItemIndex"
        }
      ],
      "role": "symbol",
      "title": "CMItemIndex",
      "type": "topic",
      "url": "/documentation/coremedia/cmitemindex"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedStreamType": {
      "abstract": [
        {
          "text": "A datatype that represents a muxed stream of data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMuxedStreamType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedStreamType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMuxedStreamType"
        }
      ],
      "role": "symbol",
      "title": "CMMuxedStreamType",
      "type": "topic",
      "url": "/documentation/coremedia/cmmuxedstreamtype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMPersistentTrackID": {
      "abstract": [
        {
          "text": "A datatype that represents a persistent track identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMPersistentTrackID"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMPersistentTrackID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMPersistentTrackID"
        }
      ],
      "role": "symbol",
      "title": "CMPersistentTrackID",
      "type": "topic",
      "url": "/documentation/coremedia/cmpersistenttrackid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer": {
      "abstract": [
        {
          "text": "A reference to a buffer of media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSampleBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSampleBuffer"
        }
      ],
      "role": "symbol",
      "title": "CMSampleBuffer",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/AttachmentKey": {
      "abstract": [
        {
          "text": "Keys that identify sample buffer attachments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AttachmentKey"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/AttachmentKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AttachmentKey"
        }
      ],
      "role": "symbol",
      "title": "CMSampleBuffer.AttachmentKey",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/attachmentkey"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/DataReadiness-swift.enum": {
      "abstract": [
        {
          "text": "Constants that indicate the readiness of a sample buffer’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DataReadiness"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/DataReadiness-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DataReadiness"
        }
      ],
      "role": "symbol",
      "title": "CMSampleBuffer.DataReadiness",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/datareadiness-swift.enum"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error": {
      "abstract": [
        {
          "text": "A structure that defines errors that occur during framework operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "role": "symbol",
      "title": "CMSampleBuffer.Error",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/error"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Flags": {
      "abstract": [
        {
          "text": "Flags that customize the behavior of framework operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Flags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Flags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Flags"
        }
      ],
      "role": "symbol",
      "title": "CMSampleBuffer.Flags",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/flags"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/NotificationKey": {
      "abstract": [
        {
          "text": "A key for sample buffer notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NotificationKey"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/NotificationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NotificationKey"
        }
      ],
      "role": "symbol",
      "title": "CMSampleBuffer.NotificationKey",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/notificationkey"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/PerSampleAttachmentsDictionary": {
      "abstract": [
        {
          "text": "A structure that defines keys to identify per-sample attachments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PerSampleAttachmentsDictionary"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/PerSampleAttachmentsDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PerSampleAttachmentsDictionary"
        }
      ],
      "role": "symbol",
      "title": "CMSampleBuffer.PerSampleAttachmentsDictionary",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/persampleattachmentsdictionary"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/SampleAttachmentsArray": {
      "abstract": [
        {
          "text": "A structure that defines an array of sample attachments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SampleAttachmentsArray"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/SampleAttachmentsArray",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SampleAttachmentsArray"
        }
      ],
      "role": "symbol",
      "title": "CMSampleBuffer.SampleAttachmentsArray",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/sampleattachmentsarray"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/SingleSampleBuffers": {
      "abstract": [
        {
          "text": "A structure that holds all samples in a sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SingleSampleBuffers"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/SingleSampleBuffers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SingleSampleBuffers"
        }
      ],
      "role": "symbol",
      "title": "CMSampleBuffer.SingleSampleBuffers",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/singlesamplebuffers"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/audioStreamPacketDescriptions()": {
      "abstract": [
        {
          "text": "Creates an array of audio stream packet descriptions for the variable bytes per packet or variable frames per packet audio data in a sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioStreamPacketDescriptions"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioStreamPacketDescription",
          "text": "AudioStreamPacketDescription"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/audioStreamPacketDescriptions()",
      "kind": "symbol",
      "role": "symbol",
      "title": "audioStreamPacketDescriptions()",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/audiostreampacketdescriptions()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/copyPCMData(fromRange:into:)": {
      "abstract": [
        {
          "text": "Copies PCM audio data from a sample buffer into a prepopulated audio buffer list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyPCMData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "fromRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sn",
          "text": "Range"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "into"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioBufferList",
          "text": "AudioBufferList"
        },
        {
          "kind": "text",
          "text": ">) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/copyPCMData(fromRange:into:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "copyPCMData(fromRange:into:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/copypcmdata(fromrange:into:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/dataBecameReady": {
      "abstract": [
        {
          "text": "A notification the system posts when a sample buffer’s data becomes ready.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataBecameReady"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/dataBecameReady",
      "kind": "symbol",
      "role": "symbol",
      "title": "dataBecameReady",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/databecameready"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/dataBuffer": {
      "abstract": [
        {
          "text": "A block buffer that contains the media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/dataBuffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "dataBuffer",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/databuffer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/dataFailed": {
      "abstract": [
        {
          "text": "A notification the system posts when a sample buffer fails to load its data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/dataFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "dataFailed",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/datafailed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/dataReadiness-swift.property": {
      "abstract": [
        {
          "text": "A value that indicates the status of the data the sample buffer contains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataReadiness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So17CMSampleBufferRefa9CoreMediaE13DataReadinessO",
          "text": "DataReadiness"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/dataReadiness-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "dataReadiness",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/datareadiness-swift.property"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/decodeTimeStamp": {
      "abstract": [
        {
          "text": "The decode timestamp of the first sample in the buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decodeTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/decodeTimeStamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "decodeTimeStamp",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/decodetimestamp"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/duration": {
      "abstract": [
        {
          "text": "The total duration of a sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/duration",
      "kind": "symbol",
      "role": "symbol",
      "title": "duration",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/duration"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/formatDescription": {
      "abstract": [
        {
          "text": "An object that describes the details of the media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/formatDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "formatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/formatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/imageBuffer": {
      "abstract": [
        {
          "text": "An image buffer that contains the media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVImageBufferRef",
          "text": "CVImageBuffer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/imageBuffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageBuffer",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/imagebuffer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/invalidate()": {
      "abstract": [
        {
          "text": "Invalidates a sample buffer by calling its invalidation handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidate"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/invalidate()",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidate()",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/invalidate()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/isValid": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the sample buffer is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isValid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/isValid",
      "kind": "symbol",
      "role": "symbol",
      "title": "isValid",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/isvalid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/makeDataReady()": {
      "abstract": [
        {
          "text": "Makes the sample buffer’s data ready for use by calling its handler closure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeDataReady"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/makeDataReady()",
      "kind": "symbol",
      "role": "symbol",
      "title": "makeDataReady()",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/makedataready()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/numSamples": {
      "abstract": [
        {
          "text": "The number of media samples the buffer contains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numSamples"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/numSamples",
      "kind": "symbol",
      "role": "symbol",
      "title": "numSamples",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/numsamples"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/outputDecodeTimeStamp": {
      "abstract": [
        {
          "text": "The output decode timestamp for a sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputDecodeTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/outputDecodeTimeStamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "outputDecodeTimeStamp",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/outputdecodetimestamp"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/outputDuration": {
      "abstract": [
        {
          "text": "The output duration of the sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/outputDuration",
      "kind": "symbol",
      "role": "symbol",
      "title": "outputDuration",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/outputduration"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/outputPresentationTimeStamp": {
      "abstract": [
        {
          "text": "The output presentation timestamp of a sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputPresentationTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/outputPresentationTimeStamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "outputPresentationTimeStamp",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/outputpresentationtimestamp"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/outputSampleTimingInfos()": {
      "abstract": [
        {
          "text": "Retrieves an array of output sample timing information structures that represents each sample in a sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputSampleTimingInfos"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMSampleTimingInfo",
          "text": "CMSampleTimingInfo"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/outputSampleTimingInfos()",
      "kind": "symbol",
      "role": "symbol",
      "title": "outputSampleTimingInfos()",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/outputsampletiminginfos()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/presentationTimeStamp": {
      "abstract": [
        {
          "text": "The sample presentation timestamp that’s the earliest numerically in the sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentationTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/presentationTimeStamp",
      "kind": "symbol",
      "role": "symbol",
      "title": "presentationTimeStamp",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/presentationtimestamp"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/sampleAttachments": {
      "abstract": [
        {
          "text": "An array of sample attachments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampleAttachments"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So17CMSampleBufferRefa9CoreMediaE22SampleAttachmentsArrayV",
          "text": "SampleAttachmentsArray"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/sampleAttachments",
      "kind": "symbol",
      "role": "symbol",
      "title": "sampleAttachments",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/sampleattachments"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/sampleSize(at:)": {
      "abstract": [
        {
          "text": "Returns the size of a sample in bytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampleSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/sampleSize(at:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "sampleSize(at:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/samplesize(at:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/sampleSizes()": {
      "abstract": [
        {
          "text": "Retrieves an array of sample sizes that represents each sample in a sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampleSizes"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/sampleSizes()",
      "kind": "symbol",
      "role": "symbol",
      "title": "sampleSizes()",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/samplesizes()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/sampleTimingInfo(at:)": {
      "abstract": [
        {
          "text": "Returns sample timing information for a sample at the specified index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampleTimingInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMItemIndex",
          "text": "CMItemIndex"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMSampleTimingInfo",
          "text": "CMSampleTimingInfo"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/sampleTimingInfo(at:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "sampleTimingInfo(at:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/sampletiminginfo(at:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/sampleTimingInfos()": {
      "abstract": [
        {
          "text": "Retrieves an array of sample timing information structures that represents each sample in a sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampleTimingInfos"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMSampleTimingInfo",
          "text": "CMSampleTimingInfo"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/sampleTimingInfos()",
      "kind": "symbol",
      "role": "symbol",
      "title": "sampleTimingInfos()",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/sampletiminginfos()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/setDataBuffer(_:)": {
      "abstract": [
        {
          "text": "Associates a block buffer of media data with a sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDataBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/setDataBuffer(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setDataBuffer(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/setdatabuffer(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/setDataBuffer(fromAudioBufferList:blockBufferMemoryAllocator:flags:)": {
      "abstract": [
        {
          "text": "Creates a block buffer that contains a copy of the data from an audio buffer list, and sets it as the sample buffer’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDataBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "fromAudioBufferList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioBufferList",
          "text": "AudioBufferList"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "blockBufferMemoryAllocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So17CMSampleBufferRefa9CoreMediaE5FlagsV",
          "text": "Flags"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/setDataBuffer(fromAudioBufferList:blockBufferMemoryAllocator:flags:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setDataBuffer(fromAudioBufferList:blockBufferMemoryAllocator:flags:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/setdatabuffer(fromaudiobufferlist:blockbuffermemoryallocator:flags:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/setDataReadiness(_:)": {
      "abstract": [
        {
          "text": "Sets the status of the sample buffer’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDataReadiness"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So17CMSampleBufferRefa9CoreMediaE13DataReadinessO",
          "text": "DataReadiness"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/setDataReadiness(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setDataReadiness(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/setdatareadiness(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/setInvalidateHandler(_:)": {
      "abstract": [
        {
          "text": "Sets a closure for the sample buffer to call when it’s invalidated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setInvalidateHandler"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/setInvalidateHandler(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setInvalidateHandler(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/setinvalidatehandler(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/setOutputPresentationTimeStamp(_:)": {
      "abstract": [
        {
          "text": "Sets an output presentation timestamp to use in place of a calculated value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setOutputPresentationTimeStamp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/setOutputPresentationTimeStamp(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setOutputPresentationTimeStamp(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/setoutputpresentationtimestamp(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/singleSampleBuffers()": {
      "abstract": [
        {
          "text": "Returns all samples in a sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "singleSampleBuffers"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So17CMSampleBufferRefa9CoreMediaE19SingleSampleBuffersV",
          "text": "SingleSampleBuffers"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/singleSampleBuffers()",
      "kind": "symbol",
      "role": "symbol",
      "title": "singleSampleBuffers()",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/singlesamplebuffers()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/taggedBuffers": {
      "abstract": [
        {
          "text": "Returns the tagged buffers associated with this buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "taggedBuffers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia14CMTaggedBufferV",
          "text": "CMTaggedBuffer"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/taggedBuffers",
      "kind": "symbol",
      "role": "symbol",
      "title": "taggedBuffers",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/taggedbuffers"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/totalSampleSize": {
      "abstract": [
        {
          "text": "The total size in bytes of sample data in the buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalSampleSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/totalSampleSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "totalSampleSize",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/totalsamplesize"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/trackDataReadiness(_:)": {
      "abstract": [
        {
          "text": "Associates a sample buffer’s data readiness with that of another sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackDataReadiness"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/trackDataReadiness(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "trackDataReadiness(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/trackdatareadiness(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/typeID": {
      "abstract": [
        {
          "text": "Returns the type identifier of sample buffer objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/typeID",
      "kind": "symbol",
      "role": "symbol",
      "title": "typeID",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/typeid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/withAudioBufferList(blockBufferMemoryAllocator:flags:body:)": {
      "abstract": [
        {
          "text": "Calls a closure with an audio buffer list that contains the data from a sample buffer and a block buffer backing the audio buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withAudioBufferList"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "R"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "blockBufferMemoryAllocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So17CMSampleBufferRefa9CoreMediaE5FlagsV",
          "text": "Flags"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "body"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreAudio013UnsafeMutableB17BufferListPointerV",
          "text": "UnsafeMutableAudioBufferListPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBlockBufferRef",
          "text": "CMBlockBuffer"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "R"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "R"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/withAudioBufferList(blockBufferMemoryAllocator:flags:body:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "withAudioBufferList(blockBufferMemoryAllocator:flags:body:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/withaudiobufferlist(blockbuffermemoryallocator:flags:body:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/withUnsafeAudioStreamPacketDescriptions(_:)": {
      "abstract": [
        {
          "text": "Calls a closure with an audio stream packet description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withUnsafeAudioStreamPacketDescriptions"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "R"
        },
        {
          "kind": "text",
          "text": ">(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SR",
          "text": "UnsafeBufferPointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioStreamPacketDescription",
          "text": "AudioStreamPacketDescription"
        },
        {
          "kind": "text",
          "text": ">) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "R"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "R"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/withUnsafeAudioStreamPacketDescriptions(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "withUnsafeAudioStreamPacketDescriptions(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer/withunsafeaudiostreampacketdescriptions(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleTimingInfo": {
      "abstract": [
        {
          "text": "A collection of timing information for a sample in a sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSampleTimingInfo"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleTimingInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSampleTimingInfo"
        }
      ],
      "role": "symbol",
      "title": "CMSampleTimingInfo",
      "type": "topic",
      "url": "/documentation/coremedia/cmsampletiminginfo"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/sample-buffer-flags": {
      "abstract": [
        {
          "text": "Flags that customize the behavior of framework operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/sample-buffer-flags",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sample Buffer Flags",
      "type": "topic",
      "url": "/documentation/coremedia/sample-buffer-flags"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentBearerProtocol",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/sample-buffer-flags",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleTimingInfo",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBuffer",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetSizeCallback",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMItemIndex",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMPersistentTrackID",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedStreamType"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Determining-Readiness",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/dataReadiness-swift.property",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/setDataReadiness(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/DataReadiness-swift.enum",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/makeDataReady()",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/trackDataReadiness(_:)"
      ],
      "title": "Determining Readiness"
    },
    {
      "anchor": "Invalidating-Sample-Buffers",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/isValid",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/setInvalidateHandler(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/invalidate()"
      ],
      "title": "Invalidating Sample Buffers"
    },
    {
      "anchor": "Inspecting-Size-Information",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/numSamples",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/sampleSizes()",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/sampleSize(at:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/totalSampleSize"
      ],
      "title": "Inspecting Size Information"
    },
    {
      "anchor": "Inspecting-Duration-and-Timing",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/duration",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/decodeTimeStamp",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/presentationTimeStamp",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/outputDuration",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/outputDecodeTimeStamp",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/outputPresentationTimeStamp",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/setOutputPresentationTimeStamp(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/sampleTimingInfos()",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/sampleTimingInfo(at:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/outputSampleTimingInfos()"
      ],
      "title": "Inspecting Duration and Timing"
    },
    {
      "anchor": "Accessing-the-Format-Description",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/formatDescription"
      ],
      "title": "Accessing the Format Description"
    },
    {
      "anchor": "Modifying-Sample-Buffers",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/dataBuffer",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/setDataBuffer(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/imageBuffer",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/withAudioBufferList(blockBufferMemoryAllocator:flags:body:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/setDataBuffer(fromAudioBufferList:blockBufferMemoryAllocator:flags:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/copyPCMData(fromRange:into:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/audioStreamPacketDescriptions()",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/withUnsafeAudioStreamPacketDescriptions(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/singleSampleBuffers()",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/SingleSampleBuffers"
      ],
      "title": "Modifying Sample Buffers"
    },
    {
      "anchor": "Managing-Attachments",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/AttachmentKey",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/sampleAttachments",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/SampleAttachmentsArray",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/PerSampleAttachmentsDictionary"
      ],
      "title": "Managing Attachments"
    },
    {
      "anchor": "Accessing-the-Type-Identifier",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/typeID"
      ],
      "title": "Accessing the Type Identifier"
    },
    {
      "anchor": "Accessing-Tagged-Buffers",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/taggedBuffers"
      ],
      "title": "Accessing Tagged Buffers"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Error",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/Flags",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/NotificationKey"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Notifications",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/dataBecameReady",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer/dataFailed"
      ],
      "title": "Notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMSampleBufferRef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSampleBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSampleBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/sample-buffer-flags",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleTimingInfo",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBuffer",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetSizeCallback",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMItemIndex",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMPersistentTrackID",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedStreamType"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@opaqueCMSampleBuffer",
                    "text": "opaqueCMSampleBuffer"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMSampleBufferRef"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPersistentTrackID/title",
          "value": "CMPersistentTrackID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPersistentTrackID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPersistentTrackID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPersistentTrackID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPersistentTrackID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleTimingInfo/title",
          "value": "CMSampleTimingInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleTimingInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSampleTimingInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleTimingInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSampleTimingInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemIndex/title",
          "value": "CMItemIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMItemIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemIndex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMItemIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMuxedStreamType/title",
          "value": "CMMuxedStreamType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMuxedStreamType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMuxedStreamType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMuxedStreamType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMuxedStreamType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBuffer/title",
          "value": "CMBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemCount/title",
          "value": "CMItemCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMItemCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMItemCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetSizeCallback/title",
          "value": "CMBufferGetSizeCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetSizeCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetSizeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetSizeCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetSizeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleBuffer/title",
          "value": "CMSampleBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSampleBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSampleBufferRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmsamplebuffer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmsamplebuffer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
