{
  "abstract": [
    {
      "text": "Sets a dictionary of attachments on an attachment bearer object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMSetAttachments(_:attachments:attachmentMode:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CMSetAttachments",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMSetAttachments"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMAttachmentBearerRef",
        "text": "CMAttachmentBearer"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "attachments"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFDictionaryRef",
        "text": "CFDictionary"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "attachmentMode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMAttachmentMode",
        "text": "CMAttachmentMode"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMSetAttachments"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CMSetAttachments(_:attachments:attachmentMode:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMSetAttachments"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "target"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentBearer",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMAttachmentBearerRef",
              "text": "CMAttachmentBearer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "attachments"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "theAttachments"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFDictionaryRef",
              "text": "CFDictionary"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "attachmentMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMAttachmentMode",
              "text": "CMAttachmentMode"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The target ",
                  "type": "text"
                },
                {
                  "code": "CMAttachmentBearer",
                  "type": "codeVoice"
                },
                {
                  "text": " to set the attachment to.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "target"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The attachments to set, in the form of a Core Foundation dictionary.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "theAttachments"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Specifies the attachment mode for this attachment. A particular attachment key can only exist in a single mode at a time.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "attachmentMode"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "CMSetAttachments",
              "type": "codeVoice"
            },
            {
              "text": " is a convenience call that in turn calls ",
              "type": "text"
            },
            {
              "code": "CMSetAttachment",
              "type": "codeVoice"
            },
            {
              "text": " for each key and value in the given dictionary. All key value pairs must be in the root level of the dictionary.  Given a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreVideo/CVBuffer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "CMSetAttachments",
              "type": "codeVoice"
            },
            {
              "text": " is equivalent to ",
              "type": "text"
            },
            {
              "code": "CVBufferSetAttachments",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentBearer": {
      "abstract": [
        {
          "text": "An object that can carry attachments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMAttachmentBearer"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentBearer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMAttachmentBearer"
        }
      ],
      "role": "symbol",
      "title": "CMAttachmentBearer",
      "type": "topic",
      "url": "/documentation/coremedia/cmattachmentbearer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentMode": {
      "abstract": [
        {
          "text": "The mode to use when propagating attachments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMAttachmentMode"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMAttachmentMode"
        }
      ],
      "role": "symbol",
      "title": "CMAttachmentMode",
      "type": "topic",
      "url": "/documentation/coremedia/cmattachmentmode"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMCopyDictionaryOfAttachments(allocator:target:attachmentMode:)": {
      "abstract": [
        {
          "text": "Returns a dictionary of all attachments for an attachment bearer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMCopyDictionaryOfAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentBearerRef",
          "text": "CMAttachmentBearer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attachmentMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentMode",
          "text": "CMAttachmentMode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMCopyDictionaryOfAttachments(allocator:target:attachmentMode:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMCopyDictionaryOfAttachments"
        }
      ],
      "role": "symbol",
      "title": "CMCopyDictionaryOfAttachments(allocator:target:attachmentMode:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmcopydictionaryofattachments(allocator:target:attachmentmode:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMGetAttachment(_:key:attachmentModeOut:)": {
      "abstract": [
        {
          "text": "Returns an attachment from an attachment bearer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMGetAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentBearerRef",
          "text": "CMAttachmentBearer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "key"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attachmentModeOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentMode",
          "text": "CMAttachmentMode"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMGetAttachment(_:key:attachmentModeOut:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMGetAttachment"
        }
      ],
      "role": "symbol",
      "title": "CMGetAttachment(_:key:attachmentModeOut:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmgetattachment(_:key:attachmentmodeout:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMPropagateAttachments(_:destination:)": {
      "abstract": [
        {
          "text": "Copies all propagable attachments from one attachment bearer object to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMPropagateAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentBearerRef",
          "text": "CMAttachmentBearer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "destination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentBearerRef",
          "text": "CMAttachmentBearer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMPropagateAttachments(_:destination:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMPropagateAttachments"
        }
      ],
      "role": "symbol",
      "title": "CMPropagateAttachments(_:destination:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmpropagateattachments(_:destination:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMRemoveAllAttachments(_:)": {
      "abstract": [
        {
          "text": "Removes all attachments from an attachment bearer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMRemoveAllAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentBearerRef",
          "text": "CMAttachmentBearer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMRemoveAllAttachments(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMRemoveAllAttachments"
        }
      ],
      "role": "symbol",
      "title": "CMRemoveAllAttachments(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmremoveallattachments(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMRemoveAttachment(_:key:)": {
      "abstract": [
        {
          "text": "Removes a specific attachment from an attachment bearer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMRemoveAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentBearerRef",
          "text": "CMAttachmentBearer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "key"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMRemoveAttachment(_:key:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMRemoveAttachment"
        }
      ],
      "role": "symbol",
      "title": "CMRemoveAttachment(_:key:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmremoveattachment(_:key:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSetAttachment(_:key:value:attachmentMode:)": {
      "abstract": [
        {
          "text": "Sets or adds an attachment to an attachment bearer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSetAttachment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentBearerRef",
          "text": "CMAttachmentBearer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "key"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "attachmentMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentMode",
          "text": "CMAttachmentMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSetAttachment(_:key:value:attachmentMode:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSetAttachment"
        }
      ],
      "role": "symbol",
      "title": "CMSetAttachment(_:key:value:attachmentMode:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsetattachment(_:key:value:attachmentmode:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSetAttachments(_:attachments:attachmentMode:)": {
      "abstract": [
        {
          "text": "Sets a dictionary of attachments on an attachment bearer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSetAttachments"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentBearerRef",
          "text": "CMAttachmentBearer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attachments"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "attachmentMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentMode",
          "text": "CMAttachmentMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSetAttachments(_:attachments:attachmentMode:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSetAttachments"
        }
      ],
      "role": "symbol",
      "title": "CMSetAttachments(_:attachments:attachmentMode:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsetattachments(_:attachments:attachmentmode:)"
    },
    "doc://com.apple.documentation/documentation/CoreVideo/CVBuffer": {
      "abstract": [
        {
          "text": "A reference to a Core Video buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVBuffer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreVideo/CVBuffer",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVBuffer",
      "type": "topic",
      "url": "/documentation/CoreVideo/CVBuffer"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef": {
      "abstract": [
        {
          "text": "A reference to an immutable dictionary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFDictionary",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdictionary"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Processing-Attachments",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMGetAttachment(_:key:attachmentModeOut:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMCopyDictionaryOfAttachments(allocator:target:attachmentMode:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSetAttachment(_:key:value:attachmentMode:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMRemoveAttachment(_:key:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMRemoveAllAttachments(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMPropagateAttachments(_:destination:)"
      ],
      "title": "Processing Attachments"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMSetAttachments"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSetAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Processing-Attachments",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMGetAttachment(_:key:attachmentModeOut:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMCopyDictionaryOfAttachments(allocator:target:attachmentMode:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMSetAttachment(_:key:value:attachmentMode:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMRemoveAttachment(_:key:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMRemoveAllAttachments(_:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMPropagateAttachments(_:destination:)"
              ],
              "title": "Processing Attachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMSetAttachments"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentBearer",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMAttachmentBearerRef",
                    "text": "CMAttachmentBearerRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "target"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFDictionaryRef",
                    "text": "CFDictionaryRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "theAttachments"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAttachmentMode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMAttachmentMode",
                    "text": "CMAttachmentMode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "attachmentMode"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The target ",
                        "type": "text"
                      },
                      {
                        "code": "CMAttachmentBearer",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to set the attachment to.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "target"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The attachments to set, in the form of a Core Foundation dictionary.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "theAttachments"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Specifies the attachment mode for this attachment. A particular attachment key can only exist in a single mode at a time.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "attachmentMode"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPropagateAttachments(_:destination:)/title",
          "value": "CMPropagateAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPropagateAttachments(_:destination:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPropagateAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMCopyDictionaryOfAttachments(allocator:target:attachmentMode:)/title",
          "value": "CMCopyDictionaryOfAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMCopyDictionaryOfAttachments(allocator:target:attachmentMode:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMCopyDictionaryOfAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMRemoveAttachment(_:key:)/title",
          "value": "CMRemoveAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMRemoveAttachment(_:key:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMRemoveAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSetAttachment(_:key:value:attachmentMode:)/title",
          "value": "CMSetAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSetAttachment(_:key:value:attachmentMode:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSetAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreVideo~1CVBuffer/title",
          "value": "CVBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreVideo~1CVBuffer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@__CVBuffer",
              "text": "__CVBuffer"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "CVBufferRef"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSetAttachments(_:attachments:attachmentMode:)/title",
          "value": "CMSetAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSetAttachments(_:attachments:attachmentMode:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSetAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFDictionaryRef/title",
          "value": "CFDictionaryRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAttachmentMode/title",
          "value": "CMAttachmentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAttachmentMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAttachmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAttachmentMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAttachmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAttachmentBearer/title",
          "value": "CMAttachmentBearerRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAttachmentBearer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAttachmentBearerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAttachmentBearer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAttachmentBearerRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMGetAttachment(_:key:attachmentModeOut:)/title",
          "value": "CMGetAttachment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMGetAttachment(_:key:attachmentModeOut:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMGetAttachment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMRemoveAllAttachments(_:)/title",
          "value": "CMRemoveAllAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMRemoveAllAttachments(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMRemoveAllAttachments"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmsetattachments(_:attachments:attachmentmode:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmsetattachments(_:attachments:attachmentmode:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
