{
  "abstract": [
    {
      "text": "Create a set of stereo view interpretation options from a constant.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CMStereoViewInterpretationOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMStereoViewInterpretationOptions"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMStereoViewInterpretationOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CMStereoViewInterpretationOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMStereoViewInterpretationOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType": {
      "abstract": [
        {
          "text": "The type of packing within each video frame, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMPackingType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMPackingType"
        }
      ],
      "role": "symbol",
      "title": "CMPackingType",
      "type": "topic",
      "url": "/documentation/coremedia/cmpackingtype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType": {
      "abstract": [
        {
          "text": "Constants describing the projection surface information in a 3D video buffer or channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMProjectionType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMProjectionType"
        }
      ],
      "role": "symbol",
      "title": "CMProjectionType",
      "type": "topic",
      "url": "/documentation/coremedia/cmprojectiontype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents": {
      "abstract": [
        {
          "text": "Constants describing the stereo views contained within a buffer or channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMStereoViewComponents"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMStereoViewComponents"
        }
      ],
      "role": "symbol",
      "title": "CMStereoViewComponents",
      "type": "topic",
      "url": "/documentation/coremedia/cmstereoviewcomponents"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions": {
      "abstract": [
        {
          "text": "Create a set of stereo view interpretation options from a constant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMStereoViewInterpretationOptions"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMStereoViewInterpretationOptions"
        }
      ],
      "role": "symbol",
      "title": "CMStereoViewInterpretationOptions",
      "type": "topic",
      "url": "/documentation/coremedia/cmstereoviewinterpretationoptions"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions/additionalViews": {
      "abstract": [
        {
          "text": "A flag indicating that the video content contains additional views beyond the left or right eye.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "additionalViews"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMStereoViewInterpretationOptions",
          "text": "CMStereoViewInterpretationOptions"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions/additionalViews",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMStereoViewInterpretation_AdditionalViews"
        }
      ],
      "role": "symbol",
      "title": "additionalViews",
      "type": "topic",
      "url": "/documentation/coremedia/cmstereoviewinterpretationoptions/additionalviews"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions/init(rawValue:)": {
      "abstract": [
        {
          "text": "Create a new option set with a given value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmstereoviewinterpretationoptions/init(rawvalue:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions/kCMStereoViewInterpretation_Default": {
      "abstract": [
        {
          "text": "The default options for stereo video views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMStereoViewInterpretation_Default"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions/kCMStereoViewInterpretation_Default",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMStereoViewInterpretation_Default",
      "type": "topic",
      "url": "/documentation/coremedia/cmstereoviewinterpretationoptions/kcmstereoviewinterpretation_default"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions/stereoOrderReversed": {
      "abstract": [
        {
          "text": "Changes the default ordering of eye data, switching it from left-to-right to right-to-left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stereoOrderReversed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMStereoViewInterpretationOptions",
          "text": "CMStereoViewInterpretationOptions"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions/stereoOrderReversed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMStereoViewInterpretation_StereoOrderReversed"
        }
      ],
      "role": "symbol",
      "title": "stereoOrderReversed",
      "type": "topic",
      "url": "/documentation/coremedia/cmstereoviewinterpretationoptions/stereoorderreversed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class": {
      "abstract": [
        {
          "text": "A tag to set additional metadata on media buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "role": "symbol",
      "title": "CMTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag": {
      "abstract": [
        {
          "text": "A tag to set additional metadata on media buffers, with an associated Swift type for its value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTypedTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTypedTag"
        }
      ],
      "role": "symbol",
      "title": "CMTypedTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtypedtag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata": {
      "abstract": [
        {
          "text": "The APIs for working with the framework’s Metadata Identifier Services and Metadata Data Type Registry.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMMetadata APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api": {
      "abstract": [
        {
          "text": "Types and interfaces for working with Core Media tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTag APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection": {
      "abstract": [
        {
          "text": "Objective-C types and interfaces for working with Core Media tag collections.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTagCollection APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@uint64_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uint64_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint64_t",
      "type": "topic",
      "url": "/documentation/kernel/uint64_t"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Metadata",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType"
      ],
      "title": "Metadata"
    }
  ],
  "topicSections": [
    {
      "anchor": "Stereo-View-Options",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions/additionalViews",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions/stereoOrderReversed"
      ],
      "title": "Stereo View Options"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMStereoViewInterpretationOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewInterpretationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewInterpretationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Stereo-View-Options",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions/additionalViews",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions/stereoOrderReversed"
              ],
              "title": "Stereo View Options"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions/kCMStereoViewInterpretation_Default"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Metadata",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType"
              ],
              "title": "Metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMStereoViewInterpretationOptions"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@uint64_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint64_t",
                    "text": "uint64_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMProjectionType/title",
          "value": "CMProjectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMProjectionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMProjectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMProjectionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMProjectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions~1stereoOrderReversed/title",
          "value": "kCMStereoViewInterpretation_StereoOrderReversed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions~1stereoOrderReversed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMStereoViewInterpretation_StereoOrderReversed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions/title",
          "value": "CMStereoViewInterpretationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewInterpretationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewInterpretationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions~1additionalViews/title",
          "value": "kCMStereoViewInterpretation_AdditionalViews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions~1additionalViews/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMStereoViewInterpretation_AdditionalViews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewComponents/title",
          "value": "CMStereoViewComponents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewComponents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewComponents/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType/title",
          "value": "CMPackingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPackingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPackingType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmstereoviewinterpretationoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmstereoviewinterpretationoptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
