{
  "abstract": [
    {
      "text": "A type that provides behavior for syncing time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:9CoreMedia14CMSyncProtocolP",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMSyncProtocol"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMSyncProtocol"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "CMSyncProtocol"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMSyncProtocol"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s8SendableP",
              "text": "Sendable"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMClock": {
      "abstract": [
        {
          "text": "An object that represents a source of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMClock"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMClock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMClock"
        }
      ],
      "role": "symbol",
      "title": "CMClock",
      "type": "topic",
      "url": "/documentation/coremedia/cmclock"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSync": {
      "abstract": [
        {
          "text": "A type that represents time syncing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSync"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSync",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSync"
        }
      ],
      "role": "symbol",
      "title": "CMSync",
      "type": "topic",
      "url": "/documentation/coremedia/cmsync"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol": {
      "abstract": [
        {
          "text": "A type that provides behavior for syncing time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSyncProtocol"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSyncProtocol"
        }
      ],
      "role": "symbol",
      "title": "CMSyncProtocol",
      "type": "topic",
      "url": "/documentation/coremedia/cmsyncprotocol"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol/convertTime(_:to:)": {
      "abstract": [
        {
          "text": "Converts a time from one timebase or clock to another timebase or clock.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertTime"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol/convertTime(_:to:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "convertTime(_:to:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsyncprotocol/converttime(_:to:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol/mightDrift(relativeTo:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether it’s possible for the clock to drift relative to the input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mightDrift"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "relativeTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol/mightDrift(relativeTo:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "mightDrift(relativeTo:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsyncprotocol/mightdrift(relativeto:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol/rate(relativeTo:)": {
      "abstract": [
        {
          "text": "Queries the relative rate of one timebase or clock relative to another timebase or clock.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rate"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "relativeTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol/rate(relativeTo:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "rate(relativeTo:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsyncprotocol/rate(relativeto:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol/rateAndAnchorTime(relativeTo:)": {
      "abstract": [
        {
          "text": "Queries the relative rate of one timebase or clock relative to another timebase or clock, and the times of each timebase or clock at which the relative rate went into effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rateAndAnchorTime"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "relativeTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> (rate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", anchorTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ", referenceTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol/rateAndAnchorTime(relativeTo:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "rateAndAnchorTime(relativeTo:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsyncprotocol/rateandanchortime(relativeto:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol/time": {
      "abstract": [
        {
          "text": "The current time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "time"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol/time",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "time",
      "type": "topic",
      "url": "/documentation/coremedia/cmsyncprotocol/time"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase": {
      "abstract": [
        {
          "text": "A model of a timeline under application control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimebase"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimebase"
        }
      ],
      "role": "symbol",
      "title": "CMTimebase",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMClock",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSync"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-Time",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol/time"
      ],
      "title": "Getting the Time"
    },
    {
      "anchor": "Converting-Time",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol/convertTime(_:to:)"
      ],
      "title": "Converting Time"
    },
    {
      "anchor": "Getting-the-Time-Rate",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol/rate(relativeTo:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol/rateAndAnchorTime(relativeTo:)"
      ],
      "title": "Getting the Time Rate"
    },
    {
      "anchor": "Determining-Time-Drift",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol/mightDrift(relativeTo:)"
      ],
      "title": "Determining Time Drift"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClock/title",
          "value": "CMClockRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClockRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClockRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebase/title",
          "value": "CMTimebaseRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimebaseRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimebaseRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmsyncprotocol"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
