{
  "abstract": [
    {
      "text": "Objective-C types and interfaces for working with Core Media tag collections.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CMTagCollection APIs"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMutableTagCollectionRef": {
      "abstract": [
        {
          "text": "A mutable reference to a tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMMutableTagCollectionRef"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMutableTagCollectionRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMMutableTagCollectionRef",
      "type": "topic",
      "url": "/documentation/coremedia/cmmutabletagcollectionref"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType": {
      "abstract": [
        {
          "text": "The type of packing within each video frame, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMPackingType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMPackingType"
        }
      ],
      "role": "symbol",
      "title": "CMPackingType",
      "type": "topic",
      "url": "/documentation/coremedia/cmpackingtype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType": {
      "abstract": [
        {
          "text": "Constants describing the projection surface information in a 3D video buffer or channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMProjectionType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMProjectionType"
        }
      ],
      "role": "symbol",
      "title": "CMProjectionType",
      "type": "topic",
      "url": "/documentation/coremedia/cmprojectiontype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents": {
      "abstract": [
        {
          "text": "Constants describing the stereo views contained within a buffer or channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMStereoViewComponents"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMStereoViewComponents"
        }
      ],
      "role": "symbol",
      "title": "CMStereoViewComponents",
      "type": "topic",
      "url": "/documentation/coremedia/cmstereoviewcomponents"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions": {
      "abstract": [
        {
          "text": "Create a set of stereo view interpretation options from a constant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMStereoViewInterpretationOptions"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMStereoViewInterpretationOptions"
        }
      ],
      "role": "symbol",
      "title": "CMStereoViewInterpretationOptions",
      "type": "topic",
      "url": "/documentation/coremedia/cmstereoviewinterpretationoptions"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class": {
      "abstract": [
        {
          "text": "A tag to set additional metadata on media buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "role": "symbol",
      "title": "CMTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionAddTag": {
      "abstract": [
        {
          "text": "Adds a new tag to an existing collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionAddTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionAddTag",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionAddTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionaddtag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionAddTagsFromArray": {
      "abstract": [
        {
          "text": "Adds the tags contained in a C-style array to a tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionAddTagsFromArray"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionAddTagsFromArray",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionAddTagsFromArray",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionaddtagsfromarray"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionAddTagsFromCollection": {
      "abstract": [
        {
          "text": "Add the tags contained in one collection to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionAddTagsFromCollection"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionAddTagsFromCollection",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionAddTagsFromCollection",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionaddtagsfromcollection"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionApplierFunction": {
      "abstract": [
        {
          "text": "A type for function application over elements of a tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionApplierFunction"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionApplierFunction",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionApplierFunction",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionapplierfunction"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionApply": {
      "abstract": [
        {
          "text": "Applies a function to all tags in a collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionApply"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionApply",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionApply",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionapply"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionApplyUntil": {
      "abstract": [
        {
          "text": "Applies a Boolean function to tags in a collection, stopping when it returns true.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionApplyUntil"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionApplyUntil",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionApplyUntil",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionapplyuntil"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsCategory": {
      "abstract": [
        {
          "text": "Determines if a tag collection contains tags for a given category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionContainsCategory"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsCategory",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionContainsCategory",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncontainscategory"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsSpecifiedTags": {
      "abstract": [
        {
          "text": "Determines if a tag collection contains a subset of tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionContainsSpecifiedTags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsSpecifiedTags",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionContainsSpecifiedTags",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncontainsspecifiedtags"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsTag": {
      "abstract": [
        {
          "text": "Determines if a tag collection contains a specific tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionContainsTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsTag",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionContainsTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncontainstag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsTagsOfCollection": {
      "abstract": [
        {
          "text": "Determines if one collection of tags contains every tag from another collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionContainsTagsOfCollection"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsTagsOfCollection",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionContainsTagsOfCollection",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncontainstagsofcollection"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCopyAsData": {
      "abstract": [
        {
          "text": "Creates a new Core Foundation data instance from a tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCopyAsData"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCopyAsData",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCopyAsData",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncopyasdata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCopyAsDictionary": {
      "abstract": [
        {
          "text": "Creates a new Core Foundation dictionary from a tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCopyAsDictionary"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCopyAsDictionary",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCopyAsDictionary",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncopyasdictionary"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCopyDescription": {
      "abstract": [
        {
          "text": "Retrieves a copy of the tag collection’s description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCopyDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCopyDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCopyDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncopydescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCopyTagsOfCategories": {
      "abstract": [
        {
          "text": "Creates a new tag collection from an existing collection, copying all tags which match a list of categories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCopyTagsOfCategories"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCopyTagsOfCategories",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCopyTagsOfCategories",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncopytagsofcategories"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCountTagsWithFilterFunction": {
      "abstract": [
        {
          "text": "Counts the number of tags in a collection matching an evaluation function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCountTagsWithFilterFunction"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCountTagsWithFilterFunction",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCountTagsWithFilterFunction",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncounttagswithfilterfunction"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreate": {
      "abstract": [
        {
          "text": "Creates a new tag collection from an existing C-style array of tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreate"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreate",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncreate"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateCopy": {
      "abstract": [
        {
          "text": "Creates a copy of a tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreateCopy"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateCopy",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreateCopy",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncreatecopy"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateDifference": {
      "abstract": [
        {
          "text": "Creates a new tag collection with the difference of two existing collections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreateDifference"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateDifference",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreateDifference",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncreatedifference"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateExclusiveOr": {
      "abstract": [
        {
          "text": "Creates a new tag collection from two existing tag collections, copying elements which are in one collection or the other, but not both.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreateExclusiveOr"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateExclusiveOr",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreateExclusiveOr",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncreateexclusiveor"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateFromData": {
      "abstract": [
        {
          "text": "Creates a new tag collection from an existing Core Foundation data instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreateFromData"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateFromData",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreateFromData",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncreatefromdata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateFromDictionary": {
      "abstract": [
        {
          "text": "Creates a new tag collection from an existing Core Foundation dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreateFromDictionary"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateFromDictionary",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreateFromDictionary",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncreatefromdictionary"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateIntersection": {
      "abstract": [
        {
          "text": "Creates a new tag collection containing only the tags from two existing collections which match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreateIntersection"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateIntersection",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreateIntersection",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncreateintersection"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateMutable": {
      "abstract": [
        {
          "text": "Creates a new, mutable, empty tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreateMutable"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateMutable",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreateMutable",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncreatemutable"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateMutableCopy": {
      "abstract": [
        {
          "text": "Creates a new mutable copy from an existing tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreateMutableCopy"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateMutableCopy",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreateMutableCopy",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncreatemutablecopy"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateUnion": {
      "abstract": [
        {
          "text": "Creates a new tag collection containing all tags from two collections without duplicates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreateUnion"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateUnion",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreateUnion",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncreateunion"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionError": {
      "abstract": [
        {
          "text": "Error codes returned by Core Media when working with tag collections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionError"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionError",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionError",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionerror"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetCount": {
      "abstract": [
        {
          "text": "Gets the number of tags in a tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionGetCount"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionGetCount",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectiongetcount"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetCountOfCategory": {
      "abstract": [
        {
          "text": "Retrieves the number of tags in the collection matching a given category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionGetCountOfCategory"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetCountOfCategory",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionGetCountOfCategory",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectiongetcountofcategory"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTags": {
      "abstract": [
        {
          "text": "Retrieves an arbitrary number of tags from the collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionGetTags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTags",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionGetTags",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectiongettags"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTagsWithCategory": {
      "abstract": [
        {
          "text": "Retrieves a C-style array of tags with a given category from a tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionGetTagsWithCategory"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTagsWithCategory",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionGetTagsWithCategory",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectiongettagswithcategory"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTagsWithFilterFunction": {
      "abstract": [
        {
          "text": "Gets all tags in a collection matching an evaluation function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionGetTagsWithFilterFunction"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTagsWithFilterFunction",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionGetTagsWithFilterFunction",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectiongettagswithfilterfunction"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTypeID": {
      "abstract": [
        {
          "text": "Retrieves the internal type ID for tag collections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionGetTypeID"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTypeID",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionGetTypeID",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectiongettypeid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionIsEmpty": {
      "abstract": [
        {
          "text": "Checks if a tag collection has no elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionIsEmpty"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionIsEmpty",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionIsEmpty",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionisempty"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRef": {
      "abstract": [
        {
          "text": "A reference to a tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionRef"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionRef",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionref"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRemoveAllTags": {
      "abstract": [
        {
          "text": "Removes all tags from a collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionRemoveAllTags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRemoveAllTags",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionRemoveAllTags",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionremovealltags"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRemoveAllTagsOfCategory": {
      "abstract": [
        {
          "text": "Removes all tags of a given category from a collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionRemoveAllTagsOfCategory"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRemoveAllTagsOfCategory",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionRemoveAllTagsOfCategory",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionremovealltagsofcategory"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRemoveTag": {
      "abstract": [
        {
          "text": "Removes a specific tag from a collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionRemoveTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRemoveTag",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionRemoveTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionremovetag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionTagFilterFunction": {
      "abstract": [
        {
          "text": "A type for filtering of tag collections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionTagFilterFunction"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionTagFilterFunction",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionTagFilterFunction",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectiontagfilterfunction"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag": {
      "abstract": [
        {
          "text": "A tag to set additional metadata on media buffers, with an associated Swift type for its value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTypedTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTypedTag"
        }
      ],
      "role": "symbol",
      "title": "CMTypedTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtypedtag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata": {
      "abstract": [
        {
          "text": "The APIs for working with the framework’s Metadata Identifier Services and Metadata Data Type Registry.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMMetadata APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api": {
      "abstract": [
        {
          "text": "Types and interfaces for working with Core Media tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTag APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagCollectionTagsArrayKey": {
      "abstract": [
        {
          "text": "A dictionary key for assigning tag collections to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagCollectionTagsArrayKey"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagCollectionTagsArrayKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagCollectionTagsArrayKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagcollectiontagsarraykey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Metadata",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType"
      ],
      "title": "Metadata"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Collections",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreate",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateMutable",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateFromData",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateFromDictionary"
              ],
              "title": "Creating Collections"
            },
            {
              "anchor": "Converting-to-Other-Types",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCopyAsData",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCopyAsDictionary"
              ],
              "title": "Converting to Other Types"
            },
            {
              "anchor": "Inspecting-Collections",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetCount",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCountTagsWithFilterFunction",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionIsEmpty",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTags",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTagsWithCategory",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTagsWithFilterFunction",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsCategory",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetCountOfCategory",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsTag",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsSpecifiedTags",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsTagsOfCollection",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCopyDescription",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTypeID"
              ],
              "title": "Inspecting Collections"
            },
            {
              "anchor": "Modifying-Collection-Tags",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionAddTag",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionAddTagsFromArray",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionAddTagsFromCollection",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRemoveAllTags",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRemoveAllTagsOfCategory",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRemoveTag"
              ],
              "title": "Modifying Collection Tags"
            },
            {
              "anchor": "Deriving-New-Collections",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateCopy",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateMutableCopy",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCopyTagsOfCategories",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateUnion",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateDifference",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateExclusiveOr",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateIntersection"
              ],
              "title": "Deriving New Collections"
            },
            {
              "anchor": "Iterating-Over-Tags",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionApply",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionApplyUntil"
              ],
              "title": "Iterating Over Tags"
            },
            {
              "anchor": "Types",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRef",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMutableTagCollectionRef",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionApplierFunction",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionTagFilterFunction"
              ],
              "title": "Types"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagCollectionTagsArrayKey"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionError"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Metadata",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType"
              ],
              "title": "Metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions/title",
          "value": "CMStereoViewInterpretationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewInterpretationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewInterpretationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType/title",
          "value": "CMPackingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPackingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPackingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewComponents/title",
          "value": "CMStereoViewComponents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewComponents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewComponents/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMProjectionType/title",
          "value": "CMProjectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMProjectionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMProjectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMProjectionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMProjectionType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtagcollection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmtagcollection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
