{
  "abstract": [
    {
      "text": "Types and interfaces for working with Core Media tags.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CMTag APIs"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType": {
      "abstract": [
        {
          "text": "The type of packing within each video frame, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMPackingType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMPackingType"
        }
      ],
      "role": "symbol",
      "title": "CMPackingType",
      "type": "topic",
      "url": "/documentation/coremedia/cmpackingtype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType": {
      "abstract": [
        {
          "text": "Constants describing the projection surface information in a 3D video buffer or channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMProjectionType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMProjectionType"
        }
      ],
      "role": "symbol",
      "title": "CMProjectionType",
      "type": "topic",
      "url": "/documentation/coremedia/cmprojectiontype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents": {
      "abstract": [
        {
          "text": "Constants describing the stereo views contained within a buffer or channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMStereoViewComponents"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMStereoViewComponents"
        }
      ],
      "role": "symbol",
      "title": "CMStereoViewComponents",
      "type": "topic",
      "url": "/documentation/coremedia/cmstereoviewcomponents"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions": {
      "abstract": [
        {
          "text": "Create a set of stereo view interpretation options from a constant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMStereoViewInterpretationOptions"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMStereoViewInterpretationOptions"
        }
      ],
      "role": "symbol",
      "title": "CMStereoViewInterpretationOptions",
      "type": "topic",
      "url": "/documentation/coremedia/cmstereoviewinterpretationoptions"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-c.struct": {
      "abstract": [
        {
          "text": "A tag representing additional metadata on tagged media buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-c.struct",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-c.struct"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class": {
      "abstract": [
        {
          "text": "A tag to set additional metadata on media buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "role": "symbol",
      "title": "CMTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCategory": {
      "abstract": [
        {
          "text": "A 64-bit representation of a tag’s category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCategory"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCategory",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCategory",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcategory"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCategoryEqualToTagCategory": {
      "abstract": [
        {
          "text": "Compares two tags’s categories for equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCategoryEqualToTagCategory"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCategoryEqualToTagCategory",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCategoryEqualToTagCategory",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcategoryequaltotagcategory"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCategoryValueEqualToValue": {
      "abstract": [
        {
          "text": "Compares two tags’s values for equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCategoryValueEqualToValue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCategoryValueEqualToValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCategoryValueEqualToValue",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcategoryvalueequaltovalue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCompare": {
      "abstract": [
        {
          "text": "Compares two tags in terms of partial equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCompare"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCompare",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCompare",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcompare"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCopyAsDictionary": {
      "abstract": [
        {
          "text": "Copies an existing tag to a new dictionary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCopyAsDictionary"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCopyAsDictionary",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCopyAsDictionary",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcopyasdictionary"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCopyDescription": {
      "abstract": [
        {
          "text": "Copies the description of a tag to a new string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCopyDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCopyDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCopyDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcopydescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagDataType": {
      "abstract": [
        {
          "text": "The data type of a tag’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagDataType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagDataType",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagDataType",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagdatatype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagEqualToTag": {
      "abstract": [
        {
          "text": "Compares two tags for strict equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagEqualToTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagEqualToTag",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagEqualToTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagequaltotag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagError": {
      "abstract": [
        {
          "text": "Core media tagging errors reported by the framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagError"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagError",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagError",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagerror"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetCategory": {
      "abstract": [
        {
          "text": "Retrieves the category of a tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagGetCategory"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetCategory",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagGetCategory",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggetcategory"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetFlagsValue": {
      "abstract": [
        {
          "text": "Retrieves a tag’s value as a 64-bit field flag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagGetFlagsValue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetFlagsValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagGetFlagsValue",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggetflagsvalue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetFloat64Value": {
      "abstract": [
        {
          "text": "Retrieves a tag’s value as a 64-bit floating point number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagGetFloat64Value"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetFloat64Value",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagGetFloat64Value",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggetfloat64value"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetOSTypeValue": {
      "abstract": [
        {
          "text": "Retrieves a tag’s value for use by the operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagGetOSTypeValue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetOSTypeValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagGetOSTypeValue",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggetostypevalue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetSInt64Value": {
      "abstract": [
        {
          "text": "Retrieves a tag’s value as a signed 64-bit integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagGetSInt64Value"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetSInt64Value",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagGetSInt64Value",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggetsint64value"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetValue": {
      "abstract": [
        {
          "text": "Retrieves a tag’s value as an uninterpreted 64-bit wide unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagGetValue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagGetValue",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggetvalue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetValueDataType": {
      "abstract": [
        {
          "text": "Retrieves the data type of a tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagGetValueDataType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetValueDataType",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagGetValueDataType",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggetvaluedatatype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasCategory": {
      "abstract": [
        {
          "text": "Checks if a tag contains a specific category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagHasCategory"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasCategory",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagHasCategory",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaghascategory"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasFlagsValue": {
      "abstract": [
        {
          "text": "Whether a given tag contains a value for a 64-bit flag field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagHasFlagsValue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasFlagsValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagHasFlagsValue",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaghasflagsvalue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasFloat64Value": {
      "abstract": [
        {
          "text": "Whether a given tag contains a value for a 64-bit floating point number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagHasFloat64Value"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasFloat64Value",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagHasFloat64Value",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaghasfloat64value"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasOSTypeValue": {
      "abstract": [
        {
          "text": "Whether a given tag contains a value for use by the operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagHasOSTypeValue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasOSTypeValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagHasOSTypeValue",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaghasostypevalue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasSInt64Value": {
      "abstract": [
        {
          "text": "Whether a given tag contains a value for a signed 64-bit integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagHasSInt64Value"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasSInt64Value",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagHasSInt64Value",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaghassint64value"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHash": {
      "abstract": [
        {
          "text": "Generates a hash identifier for a tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagHash"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHash",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagHash",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaghash"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagIsValid": {
      "abstract": [
        {
          "text": "Whether the provided tag is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagIsValid"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagIsValid",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagIsValid",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagisvalid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagMakeFromDictionary": {
      "abstract": [
        {
          "text": "Create a new tag from a dictionary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagMakeFromDictionary"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagMakeFromDictionary",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagMakeFromDictionary",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagmakefromdictionary"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagMakeWithFlagsValue": {
      "abstract": [
        {
          "text": "Creates a new tag with a given category and a value interpreted as a 64-bit flag field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagMakeWithFlagsValue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagMakeWithFlagsValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagMakeWithFlagsValue",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagmakewithflagsvalue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagMakeWithFloat64Value": {
      "abstract": [
        {
          "text": "Creates a new tag with a given category and a 64-bit floating point value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagMakeWithFloat64Value"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagMakeWithFloat64Value",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagMakeWithFloat64Value",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagmakewithfloat64value"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagMakeWithOSTypeValue": {
      "abstract": [
        {
          "text": "Creates a new tag with a given category and a 64-bit value for use by the framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagMakeWithOSTypeValue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagMakeWithOSTypeValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagMakeWithOSTypeValue",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagmakewithostypevalue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagMakeWithSInt64Value": {
      "abstract": [
        {
          "text": "Creates a new tag with a given category and a 64-bit signed integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagMakeWithSInt64Value"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagMakeWithSInt64Value",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagMakeWithSInt64Value",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagmakewithsint64value"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagValue": {
      "abstract": [
        {
          "text": "The type used to represent tag values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagValue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagValue",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagvalue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag": {
      "abstract": [
        {
          "text": "A tag to set additional metadata on media buffers, with an associated Swift type for its value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTypedTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTypedTag"
        }
      ],
      "role": "symbol",
      "title": "CMTypedTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtypedtag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata": {
      "abstract": [
        {
          "text": "The APIs for working with the framework’s Metadata Identifier Services and Metadata Data Type Registry.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMMetadata APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection": {
      "abstract": [
        {
          "text": "Objective-C types and interfaces for working with Core Media tag collections.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTagCollection APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollection"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagCategoryKey": {
      "abstract": [
        {
          "text": "A constant for use as a key during tag creation from a dictionary, whose value is the tag’s category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagCategoryKey"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagCategoryKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagCategoryKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagcategorykey"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagDataTypeKey": {
      "abstract": [
        {
          "text": "A constant for use as a key during tag creation from a dictionary, whose value is the tag’s data type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagDataTypeKey"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagDataTypeKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagDataTypeKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagdatatypekey"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagInvalid": {
      "abstract": [
        {
          "text": "A constant representing an invalid tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagInvalid"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagInvalid",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtaginvalid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagValueKey": {
      "abstract": [
        {
          "text": "A constant for use as a key during tag creation from a dictionary, whose value is the tag’s contained value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagValueKey"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagValueKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagValueKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagvaluekey"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/tag-values": {
      "abstract": [],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/tag-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Tag Values",
      "type": "topic",
      "url": "/documentation/coremedia/tag-values"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Metadata",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType"
      ],
      "title": "Metadata"
    }
  ],
  "topicSections": [
    {
      "anchor": "Types",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class"
      ],
      "title": "Types"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/tag-values"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Tags",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagMakeFromDictionary",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagMakeWithFlagsValue",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagMakeWithFloat64Value",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagMakeWithOSTypeValue",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagMakeWithSInt64Value"
              ],
              "title": "Creating Tags"
            },
            {
              "anchor": "Tag-Categories",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCategory"
              ],
              "title": "Tag Categories"
            },
            {
              "anchor": "Tag-Data-Types",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagDataType"
              ],
              "title": "Tag Data Types"
            },
            {
              "anchor": "Inspecting-Tags",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCopyDescription",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagIsValid",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetCategory",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetValueDataType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasCategory",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasFlagsValue",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasFloat64Value",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasOSTypeValue",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasSInt64Value"
              ],
              "title": "Inspecting Tags"
            },
            {
              "anchor": "Retrieving-Tag-Values",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCopyAsDictionary",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetFlagsValue",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetFloat64Value",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetOSTypeValue",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetSInt64Value",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetValue"
              ],
              "title": "Retrieving Tag Values"
            },
            {
              "anchor": "Comparison-and-Equality",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagEqualToTag",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCompare",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCategoryEqualToTagCategory",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCategoryValueEqualToValue",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHash"
              ],
              "title": "Comparison and Equality"
            },
            {
              "anchor": "Types",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-c.struct",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagValue"
              ],
              "title": "Types"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagCategoryKey",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagDataTypeKey",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagValueKey",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagInvalid",
                "doc://com.apple.coremedia/documentation/CoreMedia/tag-values"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTagError"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Metadata",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType"
              ],
              "title": "Metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewComponents/title",
          "value": "CMStereoViewComponents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewComponents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewComponents/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMProjectionType/title",
          "value": "CMProjectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMProjectionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMProjectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMProjectionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMProjectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType/title",
          "value": "CMPackingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPackingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPackingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions/title",
          "value": "CMStereoViewInterpretationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewInterpretationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewInterpretationOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtag-api"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmtag-api"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
