{
  "abstract": [
    {
      "text": "Adds the tags contained in a C-style array to a tag collection.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionAddTagsFromArray"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CMTagCollectionAddTagsFromArray",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CMTagCollectionAddTagsFromArray"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMTagCollectionAddTagsFromArray"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CMTagCollectionAddTagsFromArray"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMTagCollectionAddTagsFromArray"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMutableTagCollectionRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMMutableTagCollectionRef",
              "text": "CMMutableTagCollectionRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "tagCollection"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-c.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CMTag",
              "text": "CMTag"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "tags"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMItemCount",
              "text": "CMItemCount"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "tagCount"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The tag collection to add tags to.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tagCollection"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to the start of an array of tags to copy.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tags"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of tags to add from the ",
                  "type": "text"
                },
                {
                  "code": "tags",
                  "type": "codeVoice"
                },
                {
                  "text": " array.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tagCount"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " on success and a value from Tag Collection Error Codes on failure.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Using a value of ",
                  "type": "text"
                },
                {
                  "code": "containedTagCount",
                  "type": "codeVoice"
                },
                {
                  "text": " greater than the number of elements in the array starting from ",
                  "type": "text"
                },
                {
                  "code": "containedTags",
                  "type": "codeVoice"
                },
                {
                  "text": " causes undefined behavior.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Warning",
          "style": "warning",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount": {
      "abstract": [
        {
          "text": "A datatype that represents an item count.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMItemCount"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMItemCount"
        }
      ],
      "role": "symbol",
      "title": "CMItemCount",
      "type": "topic",
      "url": "/documentation/coremedia/cmitemcount"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMutableTagCollectionRef": {
      "abstract": [
        {
          "text": "A mutable reference to a tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMMutableTagCollectionRef"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMutableTagCollectionRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMMutableTagCollectionRef",
      "type": "topic",
      "url": "/documentation/coremedia/cmmutabletagcollectionref"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-c.struct": {
      "abstract": [
        {
          "text": "A tag representing additional metadata on tagged media buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-c.struct",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-c.struct"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionAddTag": {
      "abstract": [
        {
          "text": "Adds a new tag to an existing collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionAddTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionAddTag",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionAddTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionaddtag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionAddTagsFromArray": {
      "abstract": [
        {
          "text": "Adds the tags contained in a C-style array to a tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionAddTagsFromArray"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionAddTagsFromArray",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionAddTagsFromArray",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionaddtagsfromarray"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionAddTagsFromCollection": {
      "abstract": [
        {
          "text": "Add the tags contained in one collection to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionAddTagsFromCollection"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionAddTagsFromCollection",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionAddTagsFromCollection",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionaddtagsfromcollection"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRemoveAllTags": {
      "abstract": [
        {
          "text": "Removes all tags from a collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionRemoveAllTags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRemoveAllTags",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionRemoveAllTags",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionremovealltags"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRemoveAllTagsOfCategory": {
      "abstract": [
        {
          "text": "Removes all tags of a given category from a collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionRemoveAllTagsOfCategory"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRemoveAllTagsOfCategory",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionRemoveAllTagsOfCategory",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionremovealltagsofcategory"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRemoveTag": {
      "abstract": [
        {
          "text": "Removes a specific tag from a collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionRemoveTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRemoveTag",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionRemoveTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionremovetag"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Modifying-Collection-Tags",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionAddTag",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionAddTagsFromCollection",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRemoveAllTags",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRemoveAllTagsOfCategory",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRemoveTag"
      ],
      "title": "Modifying Collection Tags"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemCount/title",
          "value": "CMItemCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMItemCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMItemCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtagcollectionaddtagsfromarray"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
