{
  "abstract": [
    {
      "text": "Copies an existing tag to a new dictionary object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCopyAsDictionary"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CMTagCopyAsDictionary",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CMTagCopyAsDictionary"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMTagCopyAsDictionary"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CMTagCopyAsDictionary"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFDictionaryRef",
              "text": "CFDictionaryRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMTagCopyAsDictionary"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-c.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CMTag",
              "text": "CMTag"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "tag"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFAllocatorRef",
              "text": "CFAllocatorRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "allocator"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The tag to create a new dictionary from.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tag"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The allocator to use for creating a new dictionary. Pass ",
                  "type": "text"
                },
                {
                  "code": "kCFAllocatorDefault",
                  "type": "codeVoice"
                },
                {
                  "text": " to use the default global allocator.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "allocator"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A reference to a new ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdictionary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": " if no dictionary could be created.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The created dictionary contains values for the keys ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagCategoryKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagDataTypeKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagValueKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-c.struct": {
      "abstract": [
        {
          "text": "A tag representing additional metadata on tagged media buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-c.struct",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-c.struct"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCopyAsDictionary": {
      "abstract": [
        {
          "text": "Copies an existing tag to a new dictionary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCopyAsDictionary"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCopyAsDictionary",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCopyAsDictionary",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcopyasdictionary"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetFlagsValue": {
      "abstract": [
        {
          "text": "Retrieves a tag’s value as a 64-bit field flag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagGetFlagsValue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetFlagsValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagGetFlagsValue",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggetflagsvalue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetFloat64Value": {
      "abstract": [
        {
          "text": "Retrieves a tag’s value as a 64-bit floating point number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagGetFloat64Value"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetFloat64Value",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagGetFloat64Value",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggetfloat64value"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetOSTypeValue": {
      "abstract": [
        {
          "text": "Retrieves a tag’s value for use by the operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagGetOSTypeValue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetOSTypeValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagGetOSTypeValue",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggetostypevalue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetSInt64Value": {
      "abstract": [
        {
          "text": "Retrieves a tag’s value as a signed 64-bit integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagGetSInt64Value"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetSInt64Value",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagGetSInt64Value",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggetsint64value"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetValue": {
      "abstract": [
        {
          "text": "Retrieves a tag’s value as an uninterpreted 64-bit wide unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagGetValue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagGetValue",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggetvalue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagCategoryKey": {
      "abstract": [
        {
          "text": "A constant for use as a key during tag creation from a dictionary, whose value is the tag’s category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagCategoryKey"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagCategoryKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagCategoryKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagcategorykey"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagDataTypeKey": {
      "abstract": [
        {
          "text": "A constant for use as a key during tag creation from a dictionary, whose value is the tag’s data type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagDataTypeKey"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagDataTypeKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagDataTypeKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagdatatypekey"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagValueKey": {
      "abstract": [
        {
          "text": "A constant for use as a key during tag creation from a dictionary, whose value is the tag’s contained value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagValueKey"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagValueKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagValueKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagvaluekey"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfdictionary": {
      "abstract": [
        {
          "text": "A reference to an immutable dictionary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfdictionary",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFDictionary",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdictionary"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef": {
      "abstract": [
        {
          "text": "A reference to a CFAllocator object. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFAllocator"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFAllocator",
      "type": "topic",
      "url": "/documentation/corefoundation/cfallocator"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef": {
      "abstract": [
        {
          "text": "A reference to an immutable dictionary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFDictionary",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdictionary"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Retrieving-Tag-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetFlagsValue",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetFloat64Value",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetOSTypeValue",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetSInt64Value",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetValue"
      ],
      "title": "Retrieving Tag Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFDictionaryRef/title",
          "value": "CFDictionaryRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfdictionary/title",
          "value": "CFDictionaryRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFAllocatorRef/title",
          "value": "CFAllocatorRef"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtagcopyasdictionary"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
