{
  "abstract": [
    {
      "text": "Objective-C types and interfaces for working with Core Media tagged buffer groups.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/cmtaggedbuffergroup"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CMTaggedBufferGroup APIs"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBuffer": {
      "abstract": [
        {
          "text": "An instance of a media buffer containing metadata tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTaggedBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTaggedBuffer"
        }
      ],
      "role": "symbol",
      "title": "CMTaggedBuffer",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupCreate": {
      "abstract": [
        {
          "text": "Creates a new tagged buffer group from a pair of buffers and the tags to associate with them.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupCreate"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTaggedBufferGroupCreate",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroupcreate"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupCreateCombined": {
      "abstract": [
        {
          "text": "Creates a new tagged buffer group from an array of existing tagged buffer groups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupCreateCombined"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupCreateCombined",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTaggedBufferGroupCreateCombined",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroupcreatecombined"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupError": {
      "abstract": [
        {
          "text": "Error codes returned by Core Media when working with tagged buffer groups.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupError"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupError",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTaggedBufferGroupError",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergrouperror"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatDescription": {
      "abstract": [
        {
          "text": "A type for tagged buffer format descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMTaggedBufferGroupFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroupformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatDescriptionCreateForTaggedBufferGroup": {
      "abstract": [
        {
          "text": "Creates a new format description for a tagged buffer group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupFormatDescriptionCreateForTaggedBufferGroup"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatDescriptionCreateForTaggedBufferGroup",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTaggedBufferGroupFormatDescriptionCreateForTaggedBufferGroup",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroupformatdescriptioncreatefortaggedbuffergroup"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatDescriptionMatchesTaggedBufferGroup": {
      "abstract": [
        {
          "text": "Checks to see if a tagged buffer group’s format matches an existing format description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupFormatDescriptionMatchesTaggedBufferGroup"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatDescriptionMatchesTaggedBufferGroup",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTaggedBufferGroupFormatDescriptionMatchesTaggedBufferGroup",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroupformatdescriptionmatchestaggedbuffergroup"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatType": {
      "abstract": [
        {
          "text": "A type for tagged buffer format information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupFormatType"
        }
      ],
      "role": "symbol",
      "title": "CMTaggedBufferGroupFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroupformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetCMSampleBufferAtIndex": {
      "abstract": [
        {
          "text": "Gets the sample buffer at a given index in the buffer group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupGetCMSampleBufferAtIndex"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetCMSampleBufferAtIndex",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTaggedBufferGroupGetCMSampleBufferAtIndex",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroupgetcmsamplebufferatindex"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetCMSampleBufferForTag": {
      "abstract": [
        {
          "text": "Gets the single sample buffer in a group which contains a given tag, if present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupGetCMSampleBufferForTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetCMSampleBufferForTag",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTaggedBufferGroupGetCMSampleBufferForTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroupgetcmsamplebufferfortag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetCMSampleBufferForTagCollection": {
      "abstract": [
        {
          "text": "Gets the single sample buffer in a group which contains a given tag collection, if present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupGetCMSampleBufferForTagCollection"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetCMSampleBufferForTagCollection",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTaggedBufferGroupGetCMSampleBufferForTagCollection",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroupgetcmsamplebufferfortagcollection"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetCVPixelBufferAtIndex": {
      "abstract": [
        {
          "text": "Gets the pixel buffer at a given index in the buffer group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupGetCVPixelBufferAtIndex"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetCVPixelBufferAtIndex",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTaggedBufferGroupGetCVPixelBufferAtIndex",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroupgetcvpixelbufferatindex"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetCVPixelBufferForTag": {
      "abstract": [
        {
          "text": "Gets the single pixel buffer in a group which contains a given tag, if present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupGetCVPixelBufferForTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetCVPixelBufferForTag",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTaggedBufferGroupGetCVPixelBufferForTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroupgetcvpixelbufferfortag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetCVPixelBufferForTagCollection": {
      "abstract": [
        {
          "text": "Gets the single pixel buffer in a group which contains a given tag collection, if present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupGetCVPixelBufferForTagCollection"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetCVPixelBufferForTagCollection",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTaggedBufferGroupGetCVPixelBufferForTagCollection",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroupgetcvpixelbufferfortagcollection"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetCount": {
      "abstract": [
        {
          "text": "Gets the number of buffers contained within a tagged buffer group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupGetCount"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTaggedBufferGroupGetCount",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroupgetcount"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetNumberOfMatchesForTagCollection": {
      "abstract": [
        {
          "text": "Gets the number of buffers in the group associated with a given tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupGetNumberOfMatchesForTagCollection"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetNumberOfMatchesForTagCollection",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTaggedBufferGroupGetNumberOfMatchesForTagCollection",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroupgetnumberofmatchesfortagcollection"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetTagCollectionAtIndex": {
      "abstract": [
        {
          "text": "Gets the collection of tags for a buffer at a given index in the group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupGetTagCollectionAtIndex"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetTagCollectionAtIndex",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTaggedBufferGroupGetTagCollectionAtIndex",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroupgettagcollectionatindex"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetTypeID": {
      "abstract": [
        {
          "text": "Gets the internal type ID for a tagged buffer group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupGetTypeID"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetTypeID",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTaggedBufferGroupGetTypeID",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroupgettypeid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupRef": {
      "abstract": [
        {
          "text": "A reference to a tagged buffer group instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupRef"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTaggedBufferGroupRef",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroupref"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmattachment-api": {
      "abstract": [
        {
          "text": "Add supporting metadata to sample buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmattachment-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMAttachment APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmattachment-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmblockbuffer-api": {
      "abstract": [
        {
          "text": "An object the system uses to move blocks of memory through a processing system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmblockbuffer-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMBlockBuffer APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmblockbuffer-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api": {
      "abstract": [
        {
          "text": "A media format descriptor that describes the samples in a sample buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMFormatDescription APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmsamplebuffer-api": {
      "abstract": [
        {
          "text": "An object that contains zero or more media samples of a uniform media type.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmsamplebuffer-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMSampleBuffer APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer-api"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sample-Processing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmsamplebuffer-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmblockbuffer-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBuffer",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmattachment-api"
      ],
      "title": "Sample Processing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Types",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatType"
      ],
      "title": "Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Tagged-Buffer-Groups",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupCreate",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupCreateCombined"
              ],
              "title": "Creating Tagged Buffer Groups"
            },
            {
              "anchor": "Inspecting-Tagged-Buffer-Groups",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetCount",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetNumberOfMatchesForTagCollection",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetTagCollectionAtIndex",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetTypeID"
              ],
              "title": "Inspecting Tagged Buffer Groups"
            },
            {
              "anchor": "Accessing-Sample-Buffers",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetCMSampleBufferAtIndex",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetCMSampleBufferForTag",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetCMSampleBufferForTagCollection"
              ],
              "title": "Accessing Sample Buffers"
            },
            {
              "anchor": "Accessing-Pixel-Buffers",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetCVPixelBufferAtIndex",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetCVPixelBufferForTag",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupGetCVPixelBufferForTagCollection"
              ],
              "title": "Accessing Pixel Buffers"
            },
            {
              "anchor": "Inspecting-Buffer-Format",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatDescriptionCreateForTaggedBufferGroup",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatDescriptionMatchesTaggedBufferGroup"
              ],
              "title": "Inspecting Buffer Format"
            },
            {
              "anchor": "Types",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupRef",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatDescription",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatType"
              ],
              "title": "Types"
            },
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupError"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sample-Processing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/cmsamplebuffer-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmblockbuffer-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmattachment-api"
              ],
              "title": "Sample Processing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTaggedBufferGroupFormatType/title",
          "value": "CMTaggedBufferGroupFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTaggedBufferGroupFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTaggedBufferGroupFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTaggedBufferGroupFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTaggedBufferGroupFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTaggedBufferGroupFormatDescription/title",
          "value": "CMTaggedBufferGroupFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTaggedBufferGroupFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTaggedBufferGroupFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTaggedBufferGroupFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTaggedBufferGroupFormatDescriptionRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtaggedbuffergroup"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmtaggedbuffergroup"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
