{
  "abstract": [
    {
      "text": "Copies the description of a tag to a new string.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCopyDescription"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CMTagCopyDescription",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CMTagCopyDescription"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMTagCopyDescription"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CMTagCopyDescription"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFStringRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMTagCopyDescription"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFAllocatorRef",
              "text": "CFAllocatorRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "allocator"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-c.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CMTag",
              "text": "CMTag"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "tag"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The allocator to use for creating a new string. Pass ",
                  "type": "text"
                },
                {
                  "code": "kCFAllocatorDefault",
                  "type": "codeVoice"
                },
                {
                  "text": " to use the default global allocator.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "allocator"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The tag to copy the description from.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tag"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A reference to a newly allocated ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfstring",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": " if the copy failed.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-c.struct": {
      "abstract": [
        {
          "text": "A tag representing additional metadata on tagged media buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-c.struct",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-c.struct"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCopyDescription": {
      "abstract": [
        {
          "text": "Copies the description of a tag to a new string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCopyDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCopyDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCopyDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcopydescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetCategory": {
      "abstract": [
        {
          "text": "Retrieves the category of a tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagGetCategory"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetCategory",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagGetCategory",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggetcategory"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetValueDataType": {
      "abstract": [
        {
          "text": "Retrieves the data type of a tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagGetValueDataType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetValueDataType",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagGetValueDataType",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggetvaluedatatype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasCategory": {
      "abstract": [
        {
          "text": "Checks if a tag contains a specific category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagHasCategory"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasCategory",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagHasCategory",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaghascategory"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasFlagsValue": {
      "abstract": [
        {
          "text": "Whether a given tag contains a value for a 64-bit flag field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagHasFlagsValue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasFlagsValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagHasFlagsValue",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaghasflagsvalue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasFloat64Value": {
      "abstract": [
        {
          "text": "Whether a given tag contains a value for a 64-bit floating point number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagHasFloat64Value"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasFloat64Value",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagHasFloat64Value",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaghasfloat64value"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasOSTypeValue": {
      "abstract": [
        {
          "text": "Whether a given tag contains a value for use by the operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagHasOSTypeValue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasOSTypeValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagHasOSTypeValue",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaghasostypevalue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasSInt64Value": {
      "abstract": [
        {
          "text": "Whether a given tag contains a value for a signed 64-bit integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagHasSInt64Value"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasSInt64Value",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagHasSInt64Value",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaghassint64value"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagIsValid": {
      "abstract": [
        {
          "text": "Whether the provided tag is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagIsValid"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagIsValid",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagIsValid",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagisvalid"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfstring": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef": {
      "abstract": [
        {
          "text": "A reference to a CFAllocator object. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFAllocator"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFAllocator",
      "type": "topic",
      "url": "/documentation/corefoundation/cfallocator"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-Tags",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagIsValid",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetCategory",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagGetValueDataType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasCategory",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasFlagsValue",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasFloat64Value",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasOSTypeValue",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagHasSInt64Value"
      ],
      "title": "Inspecting Tags"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1corefoundation~1cfstring/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFAllocatorRef/title",
          "value": "CFAllocatorRef"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtagcopydescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
