{
  "abstract": [
    {
      "text": "Gets all tags in a collection matching an evaluation function.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTagsWithFilterFunction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CMTagCollectionGetTagsWithFilterFunction",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CMTagCollectionGetTagsWithFilterFunction"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMTagCollectionGetTagsWithFilterFunction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CMTagCollectionGetTagsWithFilterFunction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMTagCollectionGetTagsWithFilterFunction"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMTagCollectionRef",
              "text": "CMTagCollectionRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "tagCollection"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-c.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CMTag",
              "text": "CMTag"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "tagBuffer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMItemCount",
              "text": "CMItemCount"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "tagBufferCount"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMItemCount",
              "text": "CMItemCount"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "numberOfTagsCopied"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionTagFilterFunction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMTagCollectionTagFilterFunction",
              "text": "CMTagCollectionTagFilterFunction"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "filter"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "context"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The tag collection to retrieve tags from.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tagCollection"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to a pre-allocated C-style array of tags, containing the collection’s matching tags on function return.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tagBuffer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of tags that the ",
                  "type": "text"
                },
                {
                  "code": "tagBuffer",
                  "type": "codeVoice"
                },
                {
                  "text": " array can hold.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tagBufferCount"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The total number of tags copied from the collection to ",
                  "type": "text"
                },
                {
                  "code": "tagBuffer",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "numberOfTagsCopied"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The filter function to apply to the collection. When this function returns ",
                  "type": "text"
                },
                {
                  "code": "true",
                  "type": "codeVoice"
                },
                {
                  "text": ", the tag passed as an argument is added to ",
                  "type": "text"
                },
                {
                  "code": "tagBuffer",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "filter"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer passed to the ",
                  "type": "text"
                },
                {
                  "code": "filter",
                  "type": "codeVoice"
                },
                {
                  "text": " as a parameter on each call.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "context"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " on success and a value from Tag Collection Error Codes on failure.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Using a value for ",
                  "type": "text"
                },
                {
                  "code": "tagBufferCount",
                  "type": "codeVoice"
                },
                {
                  "text": " larger than the number of elements that ",
                  "type": "text"
                },
                {
                  "code": "tagBuffer",
                  "type": "codeVoice"
                },
                {
                  "text": " holds can cause undefined behavior.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Warning",
          "style": "warning",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount": {
      "abstract": [
        {
          "text": "A datatype that represents an item count.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMItemCount"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMItemCount"
        }
      ],
      "role": "symbol",
      "title": "CMItemCount",
      "type": "topic",
      "url": "/documentation/coremedia/cmitemcount"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-c.struct": {
      "abstract": [
        {
          "text": "A tag representing additional metadata on tagged media buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-c.struct",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-c.struct"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsCategory": {
      "abstract": [
        {
          "text": "Determines if a tag collection contains tags for a given category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionContainsCategory"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsCategory",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionContainsCategory",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncontainscategory"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsSpecifiedTags": {
      "abstract": [
        {
          "text": "Determines if a tag collection contains a subset of tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionContainsSpecifiedTags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsSpecifiedTags",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionContainsSpecifiedTags",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncontainsspecifiedtags"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsTag": {
      "abstract": [
        {
          "text": "Determines if a tag collection contains a specific tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionContainsTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsTag",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionContainsTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncontainstag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsTagsOfCollection": {
      "abstract": [
        {
          "text": "Determines if one collection of tags contains every tag from another collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionContainsTagsOfCollection"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsTagsOfCollection",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionContainsTagsOfCollection",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncontainstagsofcollection"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCopyDescription": {
      "abstract": [
        {
          "text": "Retrieves a copy of the tag collection’s description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCopyDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCopyDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCopyDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncopydescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCountTagsWithFilterFunction": {
      "abstract": [
        {
          "text": "Counts the number of tags in a collection matching an evaluation function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCountTagsWithFilterFunction"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCountTagsWithFilterFunction",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCountTagsWithFilterFunction",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncounttagswithfilterfunction"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetCount": {
      "abstract": [
        {
          "text": "Gets the number of tags in a tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionGetCount"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetCount",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionGetCount",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectiongetcount"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetCountOfCategory": {
      "abstract": [
        {
          "text": "Retrieves the number of tags in the collection matching a given category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionGetCountOfCategory"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetCountOfCategory",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionGetCountOfCategory",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectiongetcountofcategory"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTags": {
      "abstract": [
        {
          "text": "Retrieves an arbitrary number of tags from the collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionGetTags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTags",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionGetTags",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectiongettags"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTagsWithCategory": {
      "abstract": [
        {
          "text": "Retrieves a C-style array of tags with a given category from a tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionGetTagsWithCategory"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTagsWithCategory",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionGetTagsWithCategory",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectiongettagswithcategory"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTagsWithFilterFunction": {
      "abstract": [
        {
          "text": "Gets all tags in a collection matching an evaluation function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionGetTagsWithFilterFunction"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTagsWithFilterFunction",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionGetTagsWithFilterFunction",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectiongettagswithfilterfunction"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTypeID": {
      "abstract": [
        {
          "text": "Retrieves the internal type ID for tag collections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionGetTypeID"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTypeID",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionGetTypeID",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectiongettypeid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionIsEmpty": {
      "abstract": [
        {
          "text": "Checks if a tag collection has no elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionIsEmpty"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionIsEmpty",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionIsEmpty",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionisempty"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRef": {
      "abstract": [
        {
          "text": "A reference to a tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionRef"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionRef",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionref"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionTagFilterFunction": {
      "abstract": [
        {
          "text": "A type for filtering of tag collections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionTagFilterFunction"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionTagFilterFunction",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionTagFilterFunction",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectiontagfilterfunction"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-Collections",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetCount",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCountTagsWithFilterFunction",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionIsEmpty",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTags",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTagsWithCategory",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsCategory",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetCountOfCategory",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsTag",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsSpecifiedTags",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionContainsTagsOfCollection",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCopyDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionGetTypeID"
      ],
      "title": "Inspecting Collections"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemCount/title",
          "value": "CMItemCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMItemCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMItemCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtagcollectiongettagswithfilterfunction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
