{
  "abstract": [
    {
      "text": "A tag to set additional metadata on media buffers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:9CoreMedia5CMTagC",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMTag"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMTag"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CMTag"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMTag"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Core Media framework uses tags to describe the properties of media channels. Each tag consists of a category and a value, both of which are 64 bits in size.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Tag data can only contain values that can be safely stored on disk. In particular, ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " values can’t contain a pointer. If you need to refer to another media element or in-memory data as part of a tag, use a buffer index or other constant.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "It’s recommended to use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instances where possible to preserve type safety.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType": {
      "abstract": [
        {
          "text": "The type of packing within each video frame, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMPackingType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMPackingType"
        }
      ],
      "role": "symbol",
      "title": "CMPackingType",
      "type": "topic",
      "url": "/documentation/coremedia/cmpackingtype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType": {
      "abstract": [
        {
          "text": "Constants describing the projection surface information in a 3D video buffer or channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMProjectionType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMProjectionType"
        }
      ],
      "role": "symbol",
      "title": "CMProjectionType",
      "type": "topic",
      "url": "/documentation/coremedia/cmprojectiontype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents": {
      "abstract": [
        {
          "text": "Constants describing the stereo views contained within a buffer or channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMStereoViewComponents"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMStereoViewComponents"
        }
      ],
      "role": "symbol",
      "title": "CMStereoViewComponents",
      "type": "topic",
      "url": "/documentation/coremedia/cmstereoviewcomponents"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions": {
      "abstract": [
        {
          "text": "Create a set of stereo view interpretation options from a constant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMStereoViewInterpretationOptions"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMStereoViewInterpretationOptions"
        }
      ],
      "role": "symbol",
      "title": "CMStereoViewInterpretationOptions",
      "type": "topic",
      "url": "/documentation/coremedia/cmstereoviewinterpretationoptions"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class": {
      "abstract": [
        {
          "text": "A tag to set additional metadata on media buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "role": "symbol",
      "title": "CMTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/RawCategory-swift.typealias": {
      "abstract": [
        {
          "text": "The raw 64-bit representation of a tag’s category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawCategory"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/RawCategory-swift.typealias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RawCategory"
        }
      ],
      "role": "symbol",
      "title": "CMTag.RawCategory",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class/rawcategory-swift.typealias"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/Value": {
      "abstract": [
        {
          "text": "A wrapper type for a value associated with a tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Value"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/Value",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Value"
        }
      ],
      "role": "symbol",
      "title": "CMTag.Value",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class/value"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/channelID(_:)": {
      "abstract": [
        {
          "text": "Creates a new channel ID tag from an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia10CMTypedTagC",
          "text": "CMTypedTag"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/channelID(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "channelID(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class/channelid(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/init(rawCategory:rawTagValue:)": {
      "abstract": [
        {
          "text": "Creates a new tag from a category and value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia5CMTagC",
          "text": "CMTag"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia5CMTagC11RawCategorya",
          "text": "RawCategory"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rawTagValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia5CMTagC",
          "text": "CMTag"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia5CMTagC5ValueO",
          "text": "Value"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/init(rawCategory:rawTagValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawCategory:rawTagValue:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class/init(rawcategory:rawtagvalue:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/mediaSubType(_:)": {
      "abstract": [
        {
          "text": "Creates a tag containing media subtype metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaSubType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE0E7SubTypeV",
          "text": "MediaSubType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia10CMTypedTagC",
          "text": "CMTypedTag"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE0E7SubTypeV",
          "text": "MediaSubType"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/mediaSubType(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "mediaSubType(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class/mediasubtype(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/mediaType(_:)": {
      "abstract": [
        {
          "text": "Creates a tag containing media type metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE0E4TypeV",
          "text": "MediaType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia10CMTypedTagC",
          "text": "CMTypedTag"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So22CMFormatDescriptionRefa9CoreMediaE0E4TypeV",
          "text": "MediaType"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/mediaType(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "mediaType(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class/mediatype(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/packingType(_:)": {
      "abstract": [
        {
          "text": "Creates a tag containing frame-packing information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "packingType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMPackingType",
          "text": "CMPackingType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia10CMTypedTagC",
          "text": "CMTypedTag"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMPackingType",
          "text": "CMPackingType"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/packingType(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "packingType(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class/packingtype(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/pixelFormat(_:)": {
      "abstract": [
        {
          "text": "Creates a tag containing pixel format information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelFormat"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia10CMTypedTagC",
          "text": "CMTypedTag"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/pixelFormat(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "pixelFormat(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class/pixelformat(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/projectionType(_:)": {
      "abstract": [
        {
          "text": "Creates a tag containing projection surface information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "projectionType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMProjectionType",
          "text": "CMProjectionType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia10CMTypedTagC",
          "text": "CMTypedTag"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMProjectionType",
          "text": "CMProjectionType"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/projectionType(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "projectionType(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class/projectiontype(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/rawCategory-swift.property": {
      "abstract": [
        {
          "text": "The raw 64-bit representation of the tag’s category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia5CMTagC",
          "text": "CMTag"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia5CMTagC11RawCategorya",
          "text": "RawCategory"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/rawCategory-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawCategory",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class/rawcategory-swift.property"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/rawTagValue": {
      "abstract": [
        {
          "text": "The tag’s contained value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawTagValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia5CMTagC",
          "text": "CMTag"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia5CMTagC5ValueO",
          "text": "Value"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/rawTagValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawTagValue",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class/rawtagvalue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/stereoView(_:)": {
      "abstract": [
        {
          "text": "Creates a tag containing eye information for 3D video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stereoView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMStereoViewComponents",
          "text": "CMStereoViewComponents"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia10CMTypedTagC",
          "text": "CMTypedTag"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMStereoViewComponents",
          "text": "CMStereoViewComponents"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/stereoView(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "stereoView(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class/stereoview(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/stereoViewInterpretation(_:)": {
      "abstract": [
        {
          "text": "Creates a tag containing information on how to interpret stereo view metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stereoViewInterpretation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMStereoViewInterpretationOptions",
          "text": "CMStereoViewInterpretationOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia10CMTypedTagC",
          "text": "CMTypedTag"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMStereoViewInterpretationOptions",
          "text": "CMStereoViewInterpretationOptions"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/stereoViewInterpretation(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "stereoViewInterpretation(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class/stereoviewinterpretation(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/trackID(_:)": {
      "abstract": [
        {
          "text": "Creates a tag containing a track ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPersistentTrackID",
          "text": "CMPersistentTrackID"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia10CMTypedTagC",
          "text": "CMTypedTag"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPersistentTrackID",
          "text": "CMPersistentTrackID"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/trackID(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "trackID(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class/trackid(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/value(onlyIfMatching:)": {
      "abstract": [
        {
          "text": "Retrieves a tag’s value as a specific type, if and only if it matches a category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "onlyIfMatching"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia10CMTypedTagC",
          "text": "CMTypedTag"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia10CMTypedTagC8CategoryV",
          "text": "Category"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/value(onlyIfMatching:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "value(onlyIfMatching:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class/value(onlyifmatching:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/videoLayerID(_:)": {
      "abstract": [
        {
          "text": "Creates a tag containing a video layer ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoLayerID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia10CMTypedTagC",
          "text": "CMTypedTag"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/videoLayerID(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "videoLayerID(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-swift.class/videolayerid(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag": {
      "abstract": [
        {
          "text": "A tag to set additional metadata on media buffers, with an associated Swift type for its value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTypedTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTypedTag"
        }
      ],
      "role": "symbol",
      "title": "CMTypedTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtypedtag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata": {
      "abstract": [
        {
          "text": "The APIs for working with the framework’s Metadata Identifier Services and Metadata Data Type Registry.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMMetadata APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api": {
      "abstract": [
        {
          "text": "Types and interfaces for working with Core Media tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTag APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection": {
      "abstract": [
        {
          "text": "Objective-C types and interfaces for working with Core Media tag collections.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTagCollection APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Metadata",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTypedTag",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtagcollection",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMProjectionType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewComponents",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMStereoViewInterpretationOptions",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMPackingType"
      ],
      "title": "Metadata"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Tags",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/channelID(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/mediaSubType(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/mediaType(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/packingType(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/pixelFormat(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/projectionType(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/stereoView(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/stereoViewInterpretation(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/trackID(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/videoLayerID(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/init(rawCategory:rawTagValue:)"
      ],
      "title": "Creating Tags"
    },
    {
      "anchor": "Inspecting-Tags",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/rawCategory-swift.property",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/rawTagValue",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/value(onlyIfMatching:)"
      ],
      "title": "Inspecting Tags"
    },
    {
      "anchor": "Wrapped-Values",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/Value"
      ],
      "title": "Wrapped Values"
    },
    {
      "anchor": "Type-Aliases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-swift.class/RawCategory-swift.typealias"
      ],
      "title": "Type Aliases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType/title",
          "value": "CMPackingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPackingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPackingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPackingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions/title",
          "value": "CMStereoViewInterpretationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewInterpretationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewInterpretationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewInterpretationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMProjectionType/title",
          "value": "CMProjectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMProjectionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMProjectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMProjectionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMProjectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewComponents/title",
          "value": "CMStereoViewComponents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewComponents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewComponents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStereoViewComponents/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStereoViewComponents"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtag-swift.class"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
