{
  "abstract": [
    {
      "text": "Creates a new tag collection from an existing collection, copying all tags which match a list of categories.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCopyTagsOfCategories"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CMTagCollectionCopyTagsOfCategories",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CMTagCollectionCopyTagsOfCategories"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMTagCollectionCopyTagsOfCategories"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CMTagCollectionCopyTagsOfCategories"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMTagCollectionCopyTagsOfCategories"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFAllocatorRef",
              "text": "CFAllocatorRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "allocator"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMTagCollectionRef",
              "text": "CMTagCollectionRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "tagCollection"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCategory",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CMTagCategory",
              "text": "CMTagCategory"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "categories"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMItemCount",
              "text": "CMItemCount"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "categoriesCount"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMTagCollectionRef",
              "text": "CMTagCollectionRef"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "collectionWithTagsOfCategories"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The allocator to use for the new tag collection. Pass ",
                  "type": "text"
                },
                {
                  "code": "kCFAllocatorDefault",
                  "type": "codeVoice"
                },
                {
                  "text": " to use the default global allocator.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "allocator"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The tag collection to copy tags from.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tagCollection"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A C-style array containing the categories to match.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "categories"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of categories.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "categoriesCount"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The output destination for the new tag collection.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "collectionWithTagsOfCategories"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " on success and a value from Tag Collection Error Codes on failure.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Using a value of ",
                  "type": "text"
                },
                {
                  "code": "categoriesCount",
                  "type": "codeVoice"
                },
                {
                  "text": " greater than the number of elements in the array starting from ",
                  "type": "text"
                },
                {
                  "code": "categories",
                  "type": "codeVoice"
                },
                {
                  "text": " causes undefined behavior.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Warning",
          "style": "warning",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount": {
      "abstract": [
        {
          "text": "A datatype that represents an item count.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMItemCount"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMItemCount"
        }
      ],
      "role": "symbol",
      "title": "CMItemCount",
      "type": "topic",
      "url": "/documentation/coremedia/cmitemcount"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCategory": {
      "abstract": [
        {
          "text": "A 64-bit representation of a tag’s category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCategory"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCategory",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCategory",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcategory"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCopyTagsOfCategories": {
      "abstract": [
        {
          "text": "Creates a new tag collection from an existing collection, copying all tags which match a list of categories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCopyTagsOfCategories"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCopyTagsOfCategories",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCopyTagsOfCategories",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncopytagsofcategories"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateCopy": {
      "abstract": [
        {
          "text": "Creates a copy of a tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreateCopy"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateCopy",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreateCopy",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncreatecopy"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateDifference": {
      "abstract": [
        {
          "text": "Creates a new tag collection with the difference of two existing collections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreateDifference"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateDifference",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreateDifference",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncreatedifference"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateExclusiveOr": {
      "abstract": [
        {
          "text": "Creates a new tag collection from two existing tag collections, copying elements which are in one collection or the other, but not both.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreateExclusiveOr"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateExclusiveOr",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreateExclusiveOr",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncreateexclusiveor"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateIntersection": {
      "abstract": [
        {
          "text": "Creates a new tag collection containing only the tags from two existing collections which match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreateIntersection"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateIntersection",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreateIntersection",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncreateintersection"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateMutableCopy": {
      "abstract": [
        {
          "text": "Creates a new mutable copy from an existing tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreateMutableCopy"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateMutableCopy",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreateMutableCopy",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncreatemutablecopy"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateUnion": {
      "abstract": [
        {
          "text": "Creates a new tag collection containing all tags from two collections without duplicates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreateUnion"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateUnion",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreateUnion",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncreateunion"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRef": {
      "abstract": [
        {
          "text": "A reference to a tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionRef"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionRef",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionref"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef": {
      "abstract": [
        {
          "text": "A reference to a CFAllocator object. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFAllocator"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFAllocator",
      "type": "topic",
      "url": "/documentation/corefoundation/cfallocator"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deriving-New-Collections",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateCopy",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateMutableCopy",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateUnion",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateDifference",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateExclusiveOr",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateIntersection"
      ],
      "title": "Deriving New Collections"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFAllocatorRef/title",
          "value": "CFAllocatorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemCount/title",
          "value": "CMItemCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMItemCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMItemCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtagcollectioncopytagsofcategories"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
