{
  "abstract": [
    {
      "text": "Creates a new tag collection from an existing C-style array of tags.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CMTagCollectionCreate",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CMTagCollectionCreate"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMTagCollectionCreate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CMTagCollectionCreate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMTagCollectionCreate"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFAllocatorRef",
              "text": "CFAllocatorRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "allocator"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-c.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CMTag",
              "text": "CMTag"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "tags"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMItemCount",
              "text": "CMItemCount"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "tagCount"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMTagCollectionRef",
              "text": "CMTagCollectionRef"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "newCollectionOut"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The allocator to use for the new tag collection. Pass ",
                  "type": "text"
                },
                {
                  "code": "kCFAllocatorDefault",
                  "type": "codeVoice"
                },
                {
                  "text": " to use the default global allocator.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "allocator"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pointer to the first element of the tag array.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tags"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of tags to copy from the array.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "tagCount"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The output destination for the new tag collection.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "newCollectionOut"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " on success and a value from Tag Collection Error Codes on failure.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Using a value of ",
                  "type": "text"
                },
                {
                  "code": "tagCount",
                  "type": "codeVoice"
                },
                {
                  "text": " greater than the number of elements in the array starting from ",
                  "type": "text"
                },
                {
                  "code": "tags",
                  "type": "codeVoice"
                },
                {
                  "text": " causes undefined behavior.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Warning",
          "style": "warning",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount": {
      "abstract": [
        {
          "text": "A datatype that represents an item count.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMItemCount"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMItemCount"
        }
      ],
      "role": "symbol",
      "title": "CMItemCount",
      "type": "topic",
      "url": "/documentation/coremedia/cmitemcount"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-c.struct": {
      "abstract": [
        {
          "text": "A tag representing additional metadata on tagged media buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTag-c.struct",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTag",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-c.struct"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreate": {
      "abstract": [
        {
          "text": "Creates a new tag collection from an existing C-style array of tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreate"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreate",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncreate"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateFromData": {
      "abstract": [
        {
          "text": "Creates a new tag collection from an existing Core Foundation data instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreateFromData"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateFromData",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreateFromData",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncreatefromdata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateFromDictionary": {
      "abstract": [
        {
          "text": "Creates a new tag collection from an existing Core Foundation dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreateFromDictionary"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateFromDictionary",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreateFromDictionary",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncreatefromdictionary"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateMutable": {
      "abstract": [
        {
          "text": "Creates a new, mutable, empty tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreateMutable"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateMutable",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreateMutable",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectioncreatemutable"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRef": {
      "abstract": [
        {
          "text": "A reference to a tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionRef"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionRef",
      "type": "topic",
      "url": "/documentation/coremedia/cmtagcollectionref"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef": {
      "abstract": [
        {
          "text": "A reference to a CFAllocator object. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFAllocator"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFAllocator",
      "type": "topic",
      "url": "/documentation/corefoundation/cfallocator"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Collections",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateMutable",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateFromData",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTagCollectionCreateFromDictionary"
      ],
      "title": "Creating Collections"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFAllocatorRef/title",
          "value": "CFAllocatorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemCount/title",
          "value": "CMItemCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMItemCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMItemCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtagcollectioncreate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
