{
  "abstract": [
    {
      "text": "An integer value that describes the justification modes for text media.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMTextJustificationValue"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CMTextJustificationValue",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMTextJustificationValue"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMTextJustificationValue"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "CMTextJustificationValue"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMTextJustificationValue"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Int8V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Int8V",
              "text": "Int8"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioCodecType": {
      "abstract": [
        {
          "text": "An audio codec type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMAudioCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioCodecType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMAudioCodecType"
        }
      ],
      "role": "symbol",
      "title": "CMAudioCodecType",
      "type": "topic",
      "url": "/documentation/coremedia/cmaudiocodectype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescriptionMask": {
      "abstract": [
        {
          "text": "A type for mask bits that represent parts of an audio format description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMAudioFormatDescriptionMask"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescriptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMAudioFormatDescriptionMask"
        }
      ],
      "role": "symbol",
      "title": "CMAudioFormatDescriptionMask",
      "type": "topic",
      "url": "/documentation/coremedia/cmaudioformatdescriptionmask"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMediaType": {
      "abstract": [
        {
          "text": "Constants that represent media types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMediaType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMediaType"
        }
      ],
      "role": "symbol",
      "title": "CMMediaType",
      "type": "topic",
      "url": "/documentation/coremedia/cmmediatype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTextDisplayFlags": {
      "abstract": [
        {
          "text": "An integer value that describes the display mode flags for text media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTextDisplayFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTextDisplayFlags"
        }
      ],
      "role": "symbol",
      "title": "CMTextDisplayFlags",
      "type": "topic",
      "url": "/documentation/coremedia/cmtextdisplayflags"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTextJustificationValue": {
      "abstract": [
        {
          "text": "An integer value that describes the justification modes for text media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTextJustificationValue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTextJustificationValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTextJustificationValue"
        }
      ],
      "role": "symbol",
      "title": "CMTextJustificationValue",
      "type": "topic",
      "url": "/documentation/coremedia/cmtextjustificationvalue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoCodecType": {
      "abstract": [
        {
          "text": "A video codec type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoCodecType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMVideoCodecType"
        }
      ],
      "role": "symbol",
      "title": "CMVideoCodecType",
      "type": "topic",
      "url": "/documentation/coremedia/cmvideocodectype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoDimensions": {
      "abstract": [
        {
          "text": "A structure that represents video dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMVideoDimensions"
        }
      ],
      "role": "symbol",
      "title": "CMVideoDimensions",
      "type": "topic",
      "url": "/documentation/coremedia/cmvideodimensions"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/audio-codec-types": {
      "abstract": [
        {
          "text": "Constants that represent audio codec types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/audio-codec-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec Types",
      "type": "topic",
      "url": "/documentation/coremedia/audio-codec-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextJustification_bottom_right": {
      "abstract": [
        {
          "text": "A type that describes bottom justification when specified for vertical justification, right justification for horizontal justification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextJustification_bottom_right"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextJustificationValue",
          "text": "CMTextJustificationValue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextJustification_bottom_right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextJustification_bottom_right"
        }
      ],
      "role": "symbol",
      "title": "kCMTextJustification_bottom_right",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextjustification_bottom_right"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextJustification_centered": {
      "abstract": [
        {
          "text": "A type that describes center justification (both horizontal and vertical justification).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextJustification_centered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextJustificationValue",
          "text": "CMTextJustificationValue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextJustification_centered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextJustification_centered"
        }
      ],
      "role": "symbol",
      "title": "kCMTextJustification_centered",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextjustification_centered"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextJustification_left_top": {
      "abstract": [
        {
          "text": "A type that describes left justification when specified for horizontal justification, top justification for vertical justification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextJustification_left_top"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextJustificationValue",
          "text": "CMTextJustificationValue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextJustification_left_top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextJustification_left_top"
        }
      ],
      "role": "symbol",
      "title": "kCMTextJustification_left_top",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextjustification_left_top"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/media-type-constants": {
      "abstract": [
        {
          "text": "Constants that represent media types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/media-type-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media Type Constants",
      "type": "topic",
      "url": "/documentation/coremedia/media-type-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/muxed-stream-types": {
      "abstract": [
        {
          "text": "Constants that represent muxed stream types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/muxed-stream-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Muxed Stream Types",
      "type": "topic",
      "url": "/documentation/coremedia/muxed-stream-types"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s4Int8V": {
      "abstract": [
        {
          "text": "An 8-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Int8V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int8",
      "type": "topic",
      "url": "/documentation/Swift/Int8"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoDimensions",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescriptionMask",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMediaType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioCodecType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoCodecType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTextDisplayFlags",
        "doc://com.apple.coremedia/documentation/CoreMedia/media-type-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/muxed-stream-types",
        "doc://com.apple.coremedia/documentation/CoreMedia/audio-codec-types"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextJustification_left_top",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextJustification_centered",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextJustification_bottom_right"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMTextJustificationValue"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextJustificationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextJustificationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextJustification_left_top",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextJustification_centered",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextJustification_bottom_right"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoDimensions",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescriptionMask",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMediaType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioCodecType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoCodecType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTextDisplayFlags",
                "doc://com.apple.coremedia/documentation/CoreMedia/media-type-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/muxed-stream-types",
                "doc://com.apple.coremedia/documentation/CoreMedia/audio-codec-types"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@int8_t",
                    "text": "int8_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMTextJustificationValue"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioCodecType/title",
          "value": "CMAudioCodecType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioCodecType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioCodecType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextJustification_left_top/title",
          "value": "kCMTextJustification_left_top"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextJustification_left_top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextJustification_left_top"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioFormatDescriptionMask/title",
          "value": "CMAudioFormatDescriptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioFormatDescriptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioFormatDescriptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioFormatDescriptionMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioFormatDescriptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextJustification_bottom_right/title",
          "value": "kCMTextJustification_bottom_right"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextJustification_bottom_right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextJustification_bottom_right"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoDimensions/title",
          "value": "CMVideoDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoDimensions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextJustification_centered/title",
          "value": "kCMTextJustification_centered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextJustification_centered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextJustification_centered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMediaType/title",
          "value": "CMMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMediaType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextJustificationValue/title",
          "value": "CMTextJustificationValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextJustificationValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextJustificationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextJustificationValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextJustificationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextDisplayFlags/title",
          "value": "CMTextDisplayFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextDisplayFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextDisplayFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextDisplayFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextDisplayFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoCodecType/title",
          "value": "CMVideoCodecType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoCodecType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoCodecType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoCodecType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtextjustificationvalue"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmtextjustificationvalue"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
