{
  "abstract": [
    {
      "text": "An integer value that describes the display mode flags for text media.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMTextDisplayFlags"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CMTextDisplayFlags",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMTextDisplayFlags"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMTextDisplayFlags"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "CMTextDisplayFlags"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMTextDisplayFlags"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioCodecType": {
      "abstract": [
        {
          "text": "An audio codec type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMAudioCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioCodecType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMAudioCodecType"
        }
      ],
      "role": "symbol",
      "title": "CMAudioCodecType",
      "type": "topic",
      "url": "/documentation/coremedia/cmaudiocodectype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescriptionMask": {
      "abstract": [
        {
          "text": "A type for mask bits that represent parts of an audio format description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMAudioFormatDescriptionMask"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescriptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMAudioFormatDescriptionMask"
        }
      ],
      "role": "symbol",
      "title": "CMAudioFormatDescriptionMask",
      "type": "topic",
      "url": "/documentation/coremedia/cmaudioformatdescriptionmask"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMediaType": {
      "abstract": [
        {
          "text": "Constants that represent media types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMediaType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMediaType"
        }
      ],
      "role": "symbol",
      "title": "CMMediaType",
      "type": "topic",
      "url": "/documentation/coremedia/cmmediatype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTextDisplayFlags": {
      "abstract": [
        {
          "text": "An integer value that describes the display mode flags for text media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTextDisplayFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTextDisplayFlags"
        }
      ],
      "role": "symbol",
      "title": "CMTextDisplayFlags",
      "type": "topic",
      "url": "/documentation/coremedia/cmtextdisplayflags"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTextJustificationValue": {
      "abstract": [
        {
          "text": "An integer value that describes the justification modes for text media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTextJustificationValue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTextJustificationValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTextJustificationValue"
        }
      ],
      "role": "symbol",
      "title": "CMTextJustificationValue",
      "type": "topic",
      "url": "/documentation/coremedia/cmtextjustificationvalue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoCodecType": {
      "abstract": [
        {
          "text": "A video codec type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoCodecType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMVideoCodecType"
        }
      ],
      "role": "symbol",
      "title": "CMVideoCodecType",
      "type": "topic",
      "url": "/documentation/coremedia/cmvideocodectype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoDimensions": {
      "abstract": [
        {
          "text": "A structure that represents video dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMVideoDimensions"
        }
      ],
      "role": "symbol",
      "title": "CMVideoDimensions",
      "type": "topic",
      "url": "/documentation/coremedia/cmvideodimensions"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/audio-codec-types": {
      "abstract": [
        {
          "text": "Constants that represent audio codec types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/audio-codec-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec Types",
      "type": "topic",
      "url": "/documentation/coremedia/audio-codec-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_allSubtitlesForced": {
      "abstract": [
        {
          "text": "A flag that describes treating all subtitle samples as if they contain forced subtitles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_allSubtitlesForced"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_allSubtitlesForced",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_allSubtitlesForced"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_allSubtitlesForced",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_allsubtitlesforced"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_continuousKaraoke": {
      "abstract": [
        {
          "text": "A flag that describes enabling the continuous karaoke mode where the range of karaoke highlighting extends to include additional ranges rather than the highlighting moves onto the next range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_continuousKaraoke"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_continuousKaraoke",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_continuousKaraoke"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_continuousKaraoke",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_continuouskaraoke"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_fillTextRegion": {
      "abstract": [
        {
          "text": "A flag that describes the subtitle display bounds are to be filled with the color specified by ",
          "type": "text"
        },
        {
          "code": "kCMTextFormatDescriptionExtension_BackgroundColor",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_fillTextRegion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_fillTextRegion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_fillTextRegion"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_fillTextRegion",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_filltextregion"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_forcedSubtitlesPresent": {
      "abstract": [
        {
          "text": "A flag that describes forcing subtitles are present, for example, a subtitle which only displays during foreign language sections of the video. Check individual samples to determine what type of subtitle is contained.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_forcedSubtitlesPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_forcedSubtitlesPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_forcedSubtitlesPresent"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_forcedSubtitlesPresent",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_forcedsubtitlespresent"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirectionMask": {
      "abstract": [
        {
          "text": "A flag that describes the scrolling direction is set by a two-bit field, obtained from displayFlags using kCMTextDisplayFlag_scrollDirectionMask.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirectionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirectionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirectionMask"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_scrollDirectionMask",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_scrolldirectionmask"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_bottomToTop": {
      "abstract": [
        {
          "text": "A flag that describes the text is vertically scrolled up (“credits style”), entering from the bottom and leaving towards the top.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_bottomToTop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_bottomToTop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_bottomToTop"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_scrollDirection_bottomToTop",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_scrolldirection_bottomtotop"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_leftToRight": {
      "abstract": [
        {
          "text": "A flag that describes the text is horizontally scrolled, entering from the left and leaving towards the right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_leftToRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_leftToRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_leftToRight"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_scrollDirection_leftToRight",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_scrolldirection_lefttoright"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_rightToLeft": {
      "abstract": [
        {
          "text": "A flag that describes the text is horizontally scrolled (“marquee style”), entering from the right and leaving towards the left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_rightToLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_rightToLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_rightToLeft"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_scrollDirection_rightToLeft",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_scrolldirection_righttoleft"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_topToBottom": {
      "abstract": [
        {
          "text": "A flag that describes the text is vertically scrolled down, entering from the top and leaving towards the bottom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_topToBottom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_topToBottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_topToBottom"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_scrollDirection_topToBottom",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_scrolldirection_toptobottom"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollIn": {
      "abstract": [
        {
          "text": "A flag that describes the text scrolls into the display region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollIn"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_scrollIn",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_scrollin"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollOut": {
      "abstract": [
        {
          "text": "A flag that describes the text scrolls out of the display region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollOut"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_scrollOut",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_scrollout"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_writeTextVertically": {
      "abstract": [
        {
          "text": "A flag that describes the text renders vertically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_writeTextVertically"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_writeTextVertically",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_writeTextVertically"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_writeTextVertically",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_writetextvertically"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/media-type-constants": {
      "abstract": [
        {
          "text": "Constants that represent media types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/media-type-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media Type Constants",
      "type": "topic",
      "url": "/documentation/coremedia/media-type-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/muxed-stream-types": {
      "abstract": [
        {
          "text": "Constants that represent muxed stream types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/muxed-stream-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Muxed Stream Types",
      "type": "topic",
      "url": "/documentation/coremedia/muxed-stream-types"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@uint32_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint32_t",
      "type": "topic",
      "url": "/documentation/kernel/uint32_t"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoDimensions",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescriptionMask",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMediaType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioCodecType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoCodecType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTextJustificationValue",
        "doc://com.apple.coremedia/documentation/CoreMedia/media-type-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/muxed-stream-types",
        "doc://com.apple.coremedia/documentation/CoreMedia/audio-codec-types"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollIn",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollOut",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirectionMask",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_bottomToTop",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_rightToLeft",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_topToBottom",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_leftToRight",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_continuousKaraoke",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_writeTextVertically",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_fillTextRegion",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_forcedSubtitlesPresent",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_allSubtitlesForced"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMTextDisplayFlags"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextDisplayFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextDisplayFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollIn",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollOut",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirectionMask",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_bottomToTop",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_rightToLeft",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_topToBottom",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_leftToRight",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_continuousKaraoke",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_writeTextVertically",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_fillTextRegion",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_forcedSubtitlesPresent",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_allSubtitlesForced"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoDimensions",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescriptionMask",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMediaType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioCodecType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoCodecType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTextJustificationValue",
                "doc://com.apple.coremedia/documentation/CoreMedia/media-type-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/muxed-stream-types",
                "doc://com.apple.coremedia/documentation/CoreMedia/audio-codec-types"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMTextDisplayFlags"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollOut/title",
          "value": "kCMTextDisplayFlag_scrollOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_scrollOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_rightToLeft/title",
          "value": "kCMTextDisplayFlag_scrollDirection_rightToLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_rightToLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_scrollDirection_rightToLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_continuousKaraoke/title",
          "value": "kCMTextDisplayFlag_continuousKaraoke"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_continuousKaraoke/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_continuousKaraoke"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioCodecType/title",
          "value": "CMAudioCodecType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioCodecType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioCodecType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_forcedSubtitlesPresent/title",
          "value": "kCMTextDisplayFlag_forcedSubtitlesPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_forcedSubtitlesPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_forcedSubtitlesPresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioFormatDescriptionMask/title",
          "value": "CMAudioFormatDescriptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioFormatDescriptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioFormatDescriptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioFormatDescriptionMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioFormatDescriptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollIn/title",
          "value": "kCMTextDisplayFlag_scrollIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_scrollIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoCodecType/title",
          "value": "CMVideoCodecType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoCodecType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoCodecType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_bottomToTop/title",
          "value": "kCMTextDisplayFlag_scrollDirection_bottomToTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_bottomToTop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_scrollDirection_bottomToTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_allSubtitlesForced/title",
          "value": "kCMTextDisplayFlag_allSubtitlesForced"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_allSubtitlesForced/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_allSubtitlesForced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoDimensions/title",
          "value": "CMVideoDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoDimensions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_leftToRight/title",
          "value": "kCMTextDisplayFlag_scrollDirection_leftToRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_leftToRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_scrollDirection_leftToRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMediaType/title",
          "value": "CMMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMediaType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextJustificationValue/title",
          "value": "CMTextJustificationValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextJustificationValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextJustificationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextJustificationValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextJustificationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_writeTextVertically/title",
          "value": "kCMTextDisplayFlag_writeTextVertically"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_writeTextVertically/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_writeTextVertically"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_topToBottom/title",
          "value": "kCMTextDisplayFlag_scrollDirection_topToBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_topToBottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_scrollDirection_topToBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextDisplayFlags/title",
          "value": "CMTextDisplayFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextDisplayFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextDisplayFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextDisplayFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextDisplayFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_fillTextRegion/title",
          "value": "kCMTextDisplayFlag_fillTextRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_fillTextRegion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_fillTextRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirectionMask/title",
          "value": "kCMTextDisplayFlag_scrollDirectionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirectionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_scrollDirectionMask"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtextdisplayflags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmtextdisplayflags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
