{
  "abstract": [
    {
      "text": "A text format type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMTextFormatType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CMTextFormatType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMTextFormatType"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMTextFormatType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "CMTextFormatType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMTextFormatType"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@FourCharCode",
              "text": "FourCharCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatType": {
      "abstract": [
        {
          "text": "A closed caption format type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMClosedCaptionFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMClosedCaptionFormatType"
        }
      ],
      "role": "symbol",
      "title": "CMClosedCaptionFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmclosedcaptionformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataFormatType": {
      "abstract": [
        {
          "text": "A metadata format type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMetadataFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMetadataFormatType"
        }
      ],
      "role": "symbol",
      "title": "CMMetadataFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadataformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMPixelFormatType": {
      "abstract": [
        {
          "text": "A pixel format type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMPixelFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMPixelFormatType"
        }
      ],
      "role": "symbol",
      "title": "CMPixelFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmpixelformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSubtitleFormatType": {
      "abstract": [
        {
          "text": "A type that represents a text subtitle format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSubtitleFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSubtitleFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSubtitleFormatType"
        }
      ],
      "role": "symbol",
      "title": "CMSubtitleFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmsubtitleformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTextFormatType": {
      "abstract": [
        {
          "text": "A text format type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTextFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTextFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTextFormatType"
        }
      ],
      "role": "symbol",
      "title": "CMTextFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmtextformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatType": {
      "abstract": [
        {
          "text": "A time code format type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeCodeFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeCodeFormatType"
        }
      ],
      "role": "symbol",
      "title": "CMTimeCodeFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimecodeformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatType_3GText": {
      "abstract": [
        {
          "text": "A type that describes 3GPP text media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatType_3GText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextFormatType",
          "text": "CMTextFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatType_3GText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatType_3GText"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatType_3GText",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformattype_3gtext"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatType_QTText": {
      "abstract": [
        {
          "text": "A type that describes QuickTime text media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatType_QTText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextFormatType",
          "text": "CMTextFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatType_QTText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatType_QTText"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatType_QTText",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformattype_qttext"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-types": {
      "abstract": [
        {
          "text": "Constants that represent media format types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Format Types",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-format-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/subtitle-format-types": {
      "abstract": [
        {
          "text": "Constants that represent subtitle format types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/subtitle-format-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Subtitle Format Types",
      "type": "topic",
      "url": "/documentation/coremedia/subtitle-format-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/tagged-buffergroup-format-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/tagged-buffergroup-format-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Tagged Buffer Group Format Types",
      "type": "topic",
      "url": "/documentation/coremedia/tagged-buffergroup-format-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/time-code-formats": {
      "abstract": [
        {
          "text": "Constants that represent time code format types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/time-code-formats",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Time Code Formats",
      "type": "topic",
      "url": "/documentation/coremedia/time-code-formats"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Format-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataFormatType",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-types",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSubtitleFormatType",
        "doc://com.apple.coremedia/documentation/CoreMedia/subtitle-format-types",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatType",
        "doc://com.apple.coremedia/documentation/CoreMedia/time-code-formats",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMPixelFormatType",
        "doc://com.apple.coremedia/documentation/CoreMedia/tagged-buffergroup-format-types"
      ],
      "title": "Format Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatType_QTText",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatType_3GText"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMTextFormatType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatType_QTText",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatType_3GText"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Format-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataFormatType",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-types",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMSubtitleFormatType",
                "doc://com.apple.coremedia/documentation/CoreMedia/subtitle-format-types",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatType",
                "doc://com.apple.coremedia/documentation/CoreMedia/time-code-formats",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMPixelFormatType",
                "doc://com.apple.coremedia/documentation/CoreMedia/tagged-buffergroup-format-types"
              ],
              "title": "Format Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@FourCharCode",
                    "text": "FourCharCode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMTextFormatType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextFormatType/title",
          "value": "CMTextFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeCodeFormatType/title",
          "value": "CMTimeCodeFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeCodeFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeCodeFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeCodeFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeCodeFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataFormatType/title",
          "value": "CMMetadataFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatType_QTText/title",
          "value": "kCMTextFormatType_QTText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatType_QTText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatType_QTText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClosedCaptionFormatType/title",
          "value": "CMClosedCaptionFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClosedCaptionFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClosedCaptionFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClosedCaptionFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClosedCaptionFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatType_3GText/title",
          "value": "kCMTextFormatType_3GText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatType_3GText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatType_3GText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSubtitleFormatType/title",
          "value": "CMSubtitleFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSubtitleFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSubtitleFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSubtitleFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSubtitleFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPixelFormatType/title",
          "value": "CMPixelFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPixelFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPixelFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPixelFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPixelFormatType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtextformattype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmtextformattype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
