{
  "abstract": [
    {
      "text": "Attributes that specify text markup in legible media.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/cmtextmarkup"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CMTextMarkup"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Core Media supports legible media streams like subtitles and closed captions. In some cases, apps may need to specify style information to control rendering. In other cases, the framework indicates the text and styling to apply.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_Alignment": {
      "abstract": [
        {
          "text": "The text alignment in the writing direction of the first line of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_Alignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_Alignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_Alignment"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_Alignment",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_alignment"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_BackgroundColorARGB": {
      "abstract": [
        {
          "text": "A background color for the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_BackgroundColorARGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_BackgroundColorARGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_BackgroundColorARGB"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_BackgroundColorARGB",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_backgroundcolorargb"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight": {
      "abstract": [
        {
          "text": "A base font size as a percentage of the video height.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_basefontsizepercentagerelativetovideoheight"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_BoldStyle": {
      "abstract": [
        {
          "text": "A bold font style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_BoldStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_BoldStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_BoldStyle"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_BoldStyle",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_boldstyle"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_CharacterBackgroundColorARGB": {
      "abstract": [
        {
          "text": "A background color for individual text characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_CharacterBackgroundColorARGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_CharacterBackgroundColorARGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_CharacterBackgroundColorARGB"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_CharacterBackgroundColorARGB",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_characterbackgroundcolorargb"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_CharacterEdgeStyle": {
      "abstract": [
        {
          "text": "A style for character edges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_CharacterEdgeStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_CharacterEdgeStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_CharacterEdgeStyle"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_CharacterEdgeStyle",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_characteredgestyle"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_FontFamilyName": {
      "abstract": [
        {
          "text": "A name of a font family.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_FontFamilyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_FontFamilyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_FontFamilyName"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_FontFamilyName",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_fontfamilyname"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_ForegroundColorARGB": {
      "abstract": [
        {
          "text": "A foreground color for the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_ForegroundColorARGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_ForegroundColorARGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_ForegroundColorARGB"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_ForegroundColorARGB",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_foregroundcolorargb"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_GenericFontFamilyName": {
      "abstract": [
        {
          "text": "A generic font family name identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_GenericFontFamilyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_GenericFontFamilyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_GenericFontFamilyName"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_GenericFontFamilyName",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_genericfontfamilyname"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_ItalicStyle": {
      "abstract": [
        {
          "text": "An italic font style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_ItalicStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_ItalicStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_ItalicStyle"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_ItalicStyle",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_italicstyle"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_OrthogonalLinePositionPercentageRelativeToWritingDirection": {
      "abstract": [
        {
          "text": "The placement of the first line in a block of text as a percentage in the direction orthogonal to the writing direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_OrthogonalLinePositionPercentageRelativeToWritingDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_OrthogonalLinePositionPercentageRelativeToWritingDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_OrthogonalLinePositionPercentageRelativeToWritingDirection"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_OrthogonalLinePositionPercentageRelativeToWritingDirection",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_orthogonallinepositionpercentagerelativetowritingdirection"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_RelativeFontSize": {
      "abstract": [
        {
          "text": "A font size as a percentage of the current default font size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_RelativeFontSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_RelativeFontSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_RelativeFontSize"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_RelativeFontSize",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_relativefontsize"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_TextPositionPercentageRelativeToWritingDirection": {
      "abstract": [
        {
          "text": "The placement of the block of text as a percentage in the writing direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_TextPositionPercentageRelativeToWritingDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_TextPositionPercentageRelativeToWritingDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_TextPositionPercentageRelativeToWritingDirection"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_TextPositionPercentageRelativeToWritingDirection",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_textpositionpercentagerelativetowritingdirection"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_UnderlineStyle": {
      "abstract": [
        {
          "text": "An underline font style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_UnderlineStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_UnderlineStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_UnderlineStyle"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_UnderlineStyle",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_underlinestyle"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_VerticalLayout": {
      "abstract": [
        {
          "text": "The vertical layout of a text block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_VerticalLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_VerticalLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_VerticalLayout"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_VerticalLayout",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_verticallayout"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_WritingDirectionSizePercentage": {
      "abstract": [
        {
          "text": "The width or height as a percentage of the bounding box that contains the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_WritingDirectionSizePercentage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_WritingDirectionSizePercentage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_WritingDirectionSizePercentage"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_WritingDirectionSizePercentage",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_writingdirectionsizepercentage"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Fonts",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_FontFamilyName",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_GenericFontFamilyName",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_RelativeFontSize"
      ],
      "title": "Fonts"
    },
    {
      "anchor": "Styles",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_BoldStyle",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_ItalicStyle",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_UnderlineStyle",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_CharacterEdgeStyle"
      ],
      "title": "Styles"
    },
    {
      "anchor": "Colors",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_ForegroundColorARGB",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_BackgroundColorARGB",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_CharacterBackgroundColorARGB"
      ],
      "title": "Colors"
    },
    {
      "anchor": "Layout",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_VerticalLayout",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_Alignment",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_TextPositionPercentageRelativeToWritingDirection",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_OrthogonalLinePositionPercentageRelativeToWritingDirection",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_WritingDirectionSizePercentage"
      ],
      "title": "Layout"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Fonts",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_FontFamilyName",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_GenericFontFamilyName",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_RelativeFontSize"
              ],
              "title": "Fonts"
            },
            {
              "anchor": "Styles",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_BoldStyle",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_ItalicStyle",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_UnderlineStyle",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_CharacterEdgeStyle"
              ],
              "title": "Styles"
            },
            {
              "anchor": "Colors",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_ForegroundColorARGB",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_BackgroundColorARGB",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_CharacterBackgroundColorARGB"
              ],
              "title": "Colors"
            },
            {
              "anchor": "Layout",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_VerticalLayout",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_Alignment",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_TextPositionPercentageRelativeToWritingDirection",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_OrthogonalLinePositionPercentageRelativeToWritingDirection",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_WritingDirectionSizePercentage"
              ],
              "title": "Layout"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_ForegroundColorARGB/title",
          "value": "kCMTextMarkupAttribute_ForegroundColorARGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_ForegroundColorARGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_ForegroundColorARGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_RelativeFontSize/title",
          "value": "kCMTextMarkupAttribute_RelativeFontSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_RelativeFontSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_RelativeFontSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_VerticalLayout/title",
          "value": "kCMTextMarkupAttribute_VerticalLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_VerticalLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_VerticalLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_Alignment/title",
          "value": "kCMTextMarkupAttribute_Alignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_Alignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_Alignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_BoldStyle/title",
          "value": "kCMTextMarkupAttribute_BoldStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_BoldStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_BoldStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_CharacterBackgroundColorARGB/title",
          "value": "kCMTextMarkupAttribute_CharacterBackgroundColorARGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_CharacterBackgroundColorARGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_CharacterBackgroundColorARGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight/title",
          "value": "kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_OrthogonalLinePositionPercentageRelativeToWritingDirection/title",
          "value": "kCMTextMarkupAttribute_OrthogonalLinePositionPercentageRelativeToWritingDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_OrthogonalLinePositionPercentageRelativeToWritingDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_OrthogonalLinePositionPercentageRelativeToWritingDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_CharacterEdgeStyle/title",
          "value": "kCMTextMarkupAttribute_CharacterEdgeStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_CharacterEdgeStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_CharacterEdgeStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_TextPositionPercentageRelativeToWritingDirection/title",
          "value": "kCMTextMarkupAttribute_TextPositionPercentageRelativeToWritingDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_TextPositionPercentageRelativeToWritingDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_TextPositionPercentageRelativeToWritingDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_GenericFontFamilyName/title",
          "value": "kCMTextMarkupAttribute_GenericFontFamilyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_GenericFontFamilyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_GenericFontFamilyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_UnderlineStyle/title",
          "value": "kCMTextMarkupAttribute_UnderlineStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_UnderlineStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_UnderlineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_BackgroundColorARGB/title",
          "value": "kCMTextMarkupAttribute_BackgroundColorARGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_BackgroundColorARGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_BackgroundColorARGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_WritingDirectionSizePercentage/title",
          "value": "kCMTextMarkupAttribute_WritingDirectionSizePercentage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_WritingDirectionSizePercentage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_WritingDirectionSizePercentage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_FontFamilyName/title",
          "value": "kCMTextMarkupAttribute_FontFamilyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_FontFamilyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_FontFamilyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_ItalicStyle/title",
          "value": "kCMTextMarkupAttribute_ItalicStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_ItalicStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_ItalicStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtextmarkup"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmtextmarkup"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
