{
  "abstract": [
    {
      "text": "A model of a timeline under application control.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CMTimebaseRef",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMTimebase"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMTimebase"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CMTimebase"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMTimebase"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSync": {
      "abstract": [
        {
          "text": "A type that represents time syncing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSync"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSync",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSync"
        }
      ],
      "role": "symbol",
      "title": "CMSync",
      "type": "topic",
      "url": "/documentation/coremedia/cmsync"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol": {
      "abstract": [
        {
          "text": "A type that provides behavior for syncing time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSyncProtocol"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSyncProtocol"
        }
      ],
      "role": "symbol",
      "title": "CMSyncProtocol",
      "type": "topic",
      "url": "/documentation/coremedia/cmsyncprotocol"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase": {
      "abstract": [
        {
          "text": "A model of a timeline under application control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimebase"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimebase"
        }
      ],
      "role": "symbol",
      "title": "CMTimebase",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/CMSyncProtocol-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/CMSyncProtocol-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMSyncProtocol Implementations",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/cmsyncprotocol-implementations"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/Error": {
      "abstract": [
        {
          "text": "Constants that describe timebase errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/Error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Error"
        }
      ],
      "role": "symbol",
      "title": "CMTimebase.Error",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/error"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/NotificationKey": {
      "abstract": [
        {
          "text": "Constants that describe notification keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NotificationKey"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/NotificationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NotificationKey"
        }
      ],
      "role": "symbol",
      "title": "CMTimebase.NotificationKey",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/notificationkey"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/addTimer(_:)": {
      "abstract": [
        {
          "text": "Adds the timer dispatch source to the list of timers the timebase manages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addTimer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/addTimer(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "addTimer(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/addtimer(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/addTimer(_:on:)": {
      "abstract": [
        {
          "text": "Adds the timer to the list of timers the timebase manages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addTimer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTimer",
          "text": "Timer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "on"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRunLoop",
          "text": "RunLoop"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/addTimer(_:on:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "addTimer(_:on:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/addtimer(_:on:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/effectiveRate": {
      "abstract": [
        {
          "text": "The effective rate that combines its rate with the rates of all its primary timebases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "effectiveRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/effectiveRate",
      "kind": "symbol",
      "role": "symbol",
      "title": "effectiveRate",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/effectiverate"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/effectiveRateChanged": {
      "abstract": [
        {
          "text": "A notification that posts by a timebase after the effective rate changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "effectiveRateChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/effectiveRateChanged",
      "kind": "symbol",
      "role": "symbol",
      "title": "effectiveRateChanged",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/effectiveratechanged"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/farFuture": {
      "abstract": [
        {
          "text": "A time far into the future that represents the year 2257.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "farFuture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAbsoluteTime",
          "text": "CFAbsoluteTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/farFuture",
      "kind": "symbol",
      "role": "symbol",
      "title": "farFuture",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/farfuture"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/master": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "master"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia14CMSyncProtocolP",
          "text": "CMSyncProtocol"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/master",
      "kind": "symbol",
      "role": "symbol",
      "title": "master",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/master"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/masterClock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "masterClock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockRef",
          "text": "CMClock"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/masterClock",
      "kind": "symbol",
      "role": "symbol",
      "title": "masterClock",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/masterclock"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/masterTimebase": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "masterTimebase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTimebaseRef",
          "text": "CMTimebase"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/masterTimebase",
      "kind": "symbol",
      "role": "symbol",
      "title": "masterTimebase",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/mastertimebase"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/notificationBarrier()": {
      "abstract": [
        {
          "text": "Requests that the timebase wait until it isn’t posting notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationBarrier"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/notificationBarrier()",
      "kind": "symbol",
      "role": "symbol",
      "title": "notificationBarrier()",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/notificationbarrier()"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/rate": {
      "abstract": [
        {
          "text": "The current rate relative to its immediate primary clock or timebase.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/rate",
      "kind": "symbol",
      "role": "symbol",
      "title": "rate",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/rate"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/removeTimer(_:)-448o2": {
      "abstract": [
        {
          "text": "Removes the timer dispatch source from the list of timers the timebase manages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeTimer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/removeTimer(_:)-448o2",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeTimer(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/removetimer(_:)-448o2"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/removeTimer(_:)-4f6re": {
      "abstract": [
        {
          "text": "Removes the timer from the list of timers the timebase manages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeTimer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTimer",
          "text": "Timer"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/removeTimer(_:)-4f6re",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeTimer(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/removetimer(_:)-4f6re"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setAnchorTime(_:referenceTime:)": {
      "abstract": [
        {
          "text": "Sets the time at a particular source time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAnchorTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "referenceTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setAnchorTime(_:referenceTime:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setAnchorTime(_:referenceTime:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/setanchortime(_:referencetime:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setRate(_:)": {
      "abstract": [
        {
          "text": "Sets the rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setRate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setRate(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setRate(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/setrate(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setRateAndAnchorTime(rate:anchorTime:referenceTime:)": {
      "abstract": [
        {
          "text": "Sets the time at a particular primary time, and changes the rate at exactly that time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setRateAndAnchorTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "anchorTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "referenceTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setRateAndAnchorTime(rate:anchorTime:referenceTime:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setRateAndAnchorTime(rate:anchorTime:referenceTime:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/setrateandanchortime(rate:anchortime:referencetime:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setTime(_:)": {
      "abstract": [
        {
          "text": "Sets the current time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setTime(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setTime(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/settime(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setTimerNextFireTime(_:fireTime:)-13hjt": {
      "abstract": [
        {
          "text": "Sets the time on the timebase’s timeline at which the timer should fire next.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTimerNextFireTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTimer",
          "text": "Timer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fireTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setTimerNextFireTime(_:fireTime:)-13hjt",
      "kind": "symbol",
      "role": "symbol",
      "title": "setTimerNextFireTime(_:fireTime:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/settimernextfiretime(_:firetime:)-13hjt"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setTimerNextFireTime(_:fireTime:)-2yvaa": {
      "abstract": [
        {
          "text": "Sets the time on the timebase’s timeline at which the timer dispatch source should fire next.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTimerNextFireTime"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fireTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setTimerNextFireTime(_:fireTime:)-2yvaa",
      "kind": "symbol",
      "role": "symbol",
      "title": "setTimerNextFireTime(_:fireTime:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/settimernextfiretime(_:firetime:)-2yvaa"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setTimerToFireImmediately(_:)-4903g": {
      "abstract": [
        {
          "text": "Sets the timer dispatch source to fire immediately once, overriding any previous calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTimerToFireImmediately"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setTimerToFireImmediately(_:)-4903g",
      "kind": "symbol",
      "role": "symbol",
      "title": "setTimerToFireImmediately(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/settimertofireimmediately(_:)-4903g"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setTimerToFireImmediately(_:)-9t3wi": {
      "abstract": [
        {
          "text": "Sets the timer to fire immediately once, overriding any previous calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTimerToFireImmediately"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTimer",
          "text": "Timer"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setTimerToFireImmediately(_:)-9t3wi",
      "kind": "symbol",
      "role": "symbol",
      "title": "setTimerToFireImmediately(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/settimertofireimmediately(_:)-9t3wi"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/source": {
      "abstract": [
        {
          "text": "The immediate source that represents the clock or timebase.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "source"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9CoreMedia14CMSyncProtocolP",
          "text": "CMSyncProtocol"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/source",
      "kind": "symbol",
      "role": "symbol",
      "title": "source",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/source"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/sourceClock": {
      "abstract": [
        {
          "text": "Returns the immediate source clock, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceClock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockRef",
          "text": "CMClock"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/sourceClock",
      "kind": "symbol",
      "role": "symbol",
      "title": "sourceClock",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/sourceclock"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/sourceTimebase": {
      "abstract": [
        {
          "text": "Returns the immediate source timebase, if any.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceTimebase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTimebaseRef",
          "text": "CMTimebase"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/sourceTimebase",
      "kind": "symbol",
      "role": "symbol",
      "title": "sourceTimebase",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/sourcetimebase"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/time": {
      "abstract": [
        {
          "text": "The current time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "time"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/time",
      "kind": "symbol",
      "role": "symbol",
      "title": "time",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/time"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/time(withTimescale:rounding:)": {
      "abstract": [
        {
          "text": "Returns the current time in the timescale you request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "time"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withTimescale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTimeScale",
          "text": "CMTimeScale"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rounding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CMTimeRoundingMethod",
          "text": "CMTimeRoundingMethod"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/time(withTimescale:rounding:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "time(withTimescale:rounding:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/time(withtimescale:rounding:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/timeAndRate": {
      "abstract": [
        {
          "text": "Returns the current time and rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeAndRate"
        },
        {
          "kind": "text",
          "text": ": (time"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ", rate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/timeAndRate",
      "kind": "symbol",
      "role": "symbol",
      "title": "timeAndRate",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/timeandrate"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/timeJumped": {
      "abstract": [
        {
          "text": "A notification that posts by a timebase after a discontinuous time jump.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeJumped"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/timeJumped",
      "kind": "symbol",
      "role": "symbol",
      "title": "timeJumped",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/timejumped"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/typeID": {
      "abstract": [
        {
          "text": "A Core Foundation type identifier that represents a timebase object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/typeID",
      "kind": "symbol",
      "role": "symbol",
      "title": "typeID",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/typeid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/ultimateMasterClock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ultimateMasterClock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockRef",
          "text": "CMClock"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/ultimateMasterClock",
      "kind": "symbol",
      "role": "symbol",
      "title": "ultimateMasterClock",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/ultimatemasterclock"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/ultimateSourceClock": {
      "abstract": [
        {
          "text": "Returns the source clock that’s the source of all the other source timebases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ultimateSourceClock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMClockRef",
          "text": "CMClock"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/ultimateSourceClock",
      "kind": "symbol",
      "role": "symbol",
      "title": "ultimateSourceClock",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/ultimatesourceclock"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/veryLongTimeInterval": {
      "abstract": [
        {
          "text": "A time far into the future that represents 256 years.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "veryLongTimeInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTimeInterval",
          "text": "CFTimeInterval"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/veryLongTimeInterval",
      "kind": "symbol",
      "role": "symbol",
      "title": "veryLongTimeInterval",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase/verylongtimeinterval"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSync",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSyncProtocol"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Timebases",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/farFuture",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/veryLongTimeInterval"
      ],
      "title": "Timebases"
    },
    {
      "anchor": "Inspecting-Timebases",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/time",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/rate",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/source",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/sourceClock",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/sourceTimebase",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/effectiveRate",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/timeAndRate",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/ultimateSourceClock"
      ],
      "title": "Inspecting Timebases"
    },
    {
      "anchor": "Adding-and-Removing-Timers",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/addTimer(_:on:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/addTimer(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/removeTimer(_:)-4f6re",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/removeTimer(_:)-448o2"
      ],
      "title": "Adding and Removing Timers"
    },
    {
      "anchor": "Getting-and-Setting-Time",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setTime(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/time(withTimescale:rounding:)"
      ],
      "title": "Getting and Setting Time"
    },
    {
      "anchor": "Getting-and-Setting-the-Timebase-Rate",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setRate(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setRateAndAnchorTime(rate:anchorTime:referenceTime:)"
      ],
      "title": "Getting and Setting the Timebase Rate"
    },
    {
      "anchor": "Setting-Timers",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setTimerNextFireTime(_:fireTime:)-13hjt",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setTimerNextFireTime(_:fireTime:)-2yvaa",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setTimerToFireImmediately(_:)-9t3wi",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setTimerToFireImmediately(_:)-4903g"
      ],
      "title": "Setting Timers"
    },
    {
      "anchor": "Pausing-Time-Notifications",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/notificationBarrier()"
      ],
      "title": "Pausing Time Notifications"
    },
    {
      "anchor": "Setting-the-Anchor-Time",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/setAnchorTime(_:referenceTime:)"
      ],
      "title": "Setting the Anchor Time"
    },
    {
      "anchor": "Notifications",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/effectiveRateChanged",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/timeJumped"
      ],
      "title": "Notifications"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/Error",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/NotificationKey",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/typeID"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Deprecations",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/master",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/masterClock",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/masterTimebase",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/ultimateMasterClock"
      ],
      "title": "Deprecations"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase/CMSyncProtocol-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMTimebaseRef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimebaseRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimebaseRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@OpaqueCMTimebase",
                    "text": "OpaqueCMTimebase"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMTimebaseRef"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebase/title",
          "value": "CMTimebaseRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimebaseRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimebaseRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtimebase"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmtimebase"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
