{
  "abstract": [
    {
      "text": "A type you use to interact with time code format descriptions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatDescription"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CMTimeCodeFormatDescriptionRef",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMTimeCodeFormatDescription"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMTimeCodeFormatDescription"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "CMTimeCodeFormatDescription"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMTimeCodeFormatDescription"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
              "text": "CMFormatDescription"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescription": {
      "abstract": [
        {
          "text": "A type you use to interact with audio format descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMAudioFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMAudioFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMAudioFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmaudioformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatDescription": {
      "abstract": [
        {
          "text": "A type you use to interact with closed caption format descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMClosedCaptionFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMClosedCaptionFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMClosedCaptionFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmclosedcaptionformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription": {
      "abstract": [
        {
          "text": "An object that describes a media format descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataFormatDescription": {
      "abstract": [
        {
          "text": "A type you use to interact with metadata format descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMetadataFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMetadataFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMMetadataFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadataformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedFormatDescription": {
      "abstract": [
        {
          "text": "A type you use to interact with muxed format descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMuxedFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMuxedFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMMuxedFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmmuxedformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTextFormatDescription": {
      "abstract": [
        {
          "text": "A type you use to interact with text format descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTextFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTextFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTextFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMTextFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmtextformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatDescription": {
      "abstract": [
        {
          "text": "A type you use to interact with time code format descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeCodeFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeCodeFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMTimeCodeFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimecodeformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoFormatDescription": {
      "abstract": [
        {
          "text": "A type you use to interact with video format descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMVideoFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMVideoFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMVideoFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmvideoformatdescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Format-Description-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataFormatDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedFormatDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTextFormatDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoFormatDescription"
      ],
      "title": "Format Description Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMTimeCodeFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeCodeFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeCodeFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Format-Description-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescription",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatDescription",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataFormatDescription",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedFormatDescription",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTextFormatDescription",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoFormatDescription"
              ],
              "title": "Format Description Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMFormatDescription",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
                    "text": "CMFormatDescriptionRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMTimeCodeFormatDescriptionRef"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextFormatDescription/title",
          "value": "CMTextFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMuxedFormatDescription/title",
          "value": "CMMuxedFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMuxedFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMuxedFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMuxedFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMuxedFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClosedCaptionFormatDescription/title",
          "value": "CMClosedCaptionFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClosedCaptionFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClosedCaptionFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClosedCaptionFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClosedCaptionFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeCodeFormatDescription/title",
          "value": "CMTimeCodeFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeCodeFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeCodeFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeCodeFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeCodeFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMFormatDescription/title",
          "value": "CMFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoFormatDescription/title",
          "value": "CMVideoFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataFormatDescription/title",
          "value": "CMMetadataFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioFormatDescription/title",
          "value": "CMAudioFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioFormatDescriptionRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtimecodeformatdescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmtimecodeformatdescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
