{
  "abstract": [
    {
      "text": "Returns a Boolean value that indicates whether a time range has a duration of zero.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_EMPTY(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:9CoreMedia20CMTIMERANGE_IS_EMPTYySbSo11CMTimeRangeaF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMTIMERANGE_IS_EMPTY"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@CMTimeRange",
        "text": "CMTimeRange"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CMTIMERANGE_IS_EMPTY(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMTIMERANGE_IS_EMPTY"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "range"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CMTimeRange",
              "text": "CMTimeRange"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A time range.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "range"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if ",
              "type": "text"
            },
            {
              "code": "range",
              "type": "codeVoice"
            },
            {
              "text": " has a duration of ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": "; otherwise, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_EMPTY(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a time range has a duration of zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTIMERANGE_IS_EMPTY"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_EMPTY(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTIMERANGE_IS_EMPTY(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimerange_is_empty(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_INDEFINITE(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a time range is indefinite.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTIMERANGE_IS_INDEFINITE"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_INDEFINITE(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTIMERANGE_IS_INDEFINITE(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimerange_is_indefinite(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_INVALID(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a time range is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTIMERANGE_IS_INVALID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_INVALID(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTIMERANGE_IS_INVALID(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimerange_is_invalid(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_VALID(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a time range is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTIMERANGE_IS_VALID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_VALID(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTIMERANGE_IS_VALID(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimerange_is_valid(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRange": {
      "abstract": [
        {
          "text": "A structure that represents a time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeRange"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeRange"
        }
      ],
      "role": "symbol",
      "title": "CMTimeRange",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimerange"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeGetEnd(_:)": {
      "abstract": [
        {
          "text": "Returns a time value that represents the end of a time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeRangeGetEnd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeGetEnd(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeRangeGetEnd"
        }
      ],
      "role": "symbol",
      "title": "CMTimeRangeGetEnd(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimerangegetend(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeGetIntersection(_:otherRange:)": {
      "abstract": [
        {
          "text": "Returns a new time range with the time elements that are common between the input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeRangeGetIntersection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "otherRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeGetIntersection(_:otherRange:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeRangeGetIntersection"
        }
      ],
      "role": "symbol",
      "title": "CMTimeRangeGetIntersection(_:otherRange:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimerangegetintersection(_:otherrange:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeGetUnion(_:otherRange:)": {
      "abstract": [
        {
          "text": "Returns a new time range with the time elements of the input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeRangeGetUnion"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "otherRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeGetUnion(_:otherRange:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeRangeGetUnion"
        }
      ],
      "role": "symbol",
      "title": "CMTimeRangeGetUnion(_:otherRange:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimerangegetunion(_:otherrange:)"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-Time-Ranges",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_INDEFINITE(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_INVALID(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_VALID(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeGetEnd(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeGetIntersection(_:otherRange:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeGetUnion(_:otherRange:)"
      ],
      "title": "Inspecting Time Ranges"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRangeGetUnion(_:otherRange:)/title",
          "value": "CMTimeRangeGetUnion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRangeGetUnion(_:otherRange:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeRangeGetUnion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRangeGetIntersection(_:otherRange:)/title",
          "value": "CMTimeRangeGetIntersection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRangeGetIntersection(_:otherRange:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeRangeGetIntersection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRangeGetEnd(_:)/title",
          "value": "CMTimeRangeGetEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRangeGetEnd(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeRangeGetEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRange/title",
          "value": "CMTimeRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeRange"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtimerange_is_empty(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
