{
  "abstract": [
    {
      "text": "Keys to use when working with dictionary representations of time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Dictionary Keys"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-api": {
      "abstract": [
        {
          "text": "A structure that represents time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTime APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-time": {
      "abstract": [
        {
          "text": "Defined time values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-time",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Time",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime-time"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-timescale": {
      "abstract": [
        {
          "text": "Defined timescale values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-timescale",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Timescale",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime-timescale"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeEpochKey": {
      "abstract": [
        {
          "text": "A dictionary key for a time epoch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTimeEpochKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeEpochKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimeEpochKey"
        }
      ],
      "role": "symbol",
      "title": "kCMTimeEpochKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtimeepochkey"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeFlagsKey": {
      "abstract": [
        {
          "text": "A dictionary key for time flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTimeFlagsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeFlagsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimeFlagsKey"
        }
      ],
      "role": "symbol",
      "title": "kCMTimeFlagsKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtimeflagskey"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeScaleKey": {
      "abstract": [
        {
          "text": "A dictionary key for a timescale.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTimeScaleKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeScaleKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimeScaleKey"
        }
      ],
      "role": "symbol",
      "title": "kCMTimeScaleKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtimescalekey"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeValueKey": {
      "abstract": [
        {
          "text": "A dictionary key for a time value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTimeValueKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeValueKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimeValueKey"
        }
      ],
      "role": "symbol",
      "title": "kCMTimeValueKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtimevaluekey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-time",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-timescale"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeValueKey",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeScaleKey",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeEpochKey",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeFlagsKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeValueKey",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeScaleKey",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeEpochKey",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeFlagsKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-time",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-timescale"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimeValueKey/title",
          "value": "kCMTimeValueKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimeValueKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimeValueKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimeEpochKey/title",
          "value": "kCMTimeEpochKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimeEpochKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimeEpochKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimeFlagsKey/title",
          "value": "kCMTimeFlagsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimeFlagsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimeFlagsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimeScaleKey/title",
          "value": "kCMTimeScaleKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimeScaleKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimeScaleKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtime-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmtime-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
