{
  "abstract": [
    {
      "text": "Constants that represent errors in Core Media timebase operations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/cmtimebase-errors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CMTimebase Error Codes"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-api": {
      "abstract": [
        {
          "text": "A reference clock you use to synchronize applications and devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMClock APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmclock-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-error-codes": {
      "abstract": [
        {
          "text": "Constants that represent the errors in Core Media clock operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMClock Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/cmclock-error-codes"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmsync-error-codes": {
      "abstract": [
        {
          "text": "Constants that represent error codes Core Media sync operations return.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmsync-error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMSync error codes",
      "type": "topic",
      "url": "/documentation/coremedia/cmsync-error-codes"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseError_AllocationFailed": {
      "abstract": [
        {
          "text": "A timebase error that indicates the memory allocation fails.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTimebaseError_AllocationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseError_AllocationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimebaseError_AllocationFailed"
        }
      ],
      "role": "symbol",
      "title": "kCMTimebaseError_AllocationFailed",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtimebaseerror_allocationfailed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseError_InvalidParameter": {
      "abstract": [
        {
          "text": "A timebase error that indicates a parameter isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTimebaseError_InvalidParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseError_InvalidParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimebaseError_InvalidParameter"
        }
      ],
      "role": "symbol",
      "title": "kCMTimebaseError_InvalidParameter",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtimebaseerror_invalidparameter"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseError_MissingRequiredParameter": {
      "abstract": [
        {
          "text": "A timebase error that indicates a parameter is missing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTimebaseError_MissingRequiredParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseError_MissingRequiredParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimebaseError_MissingRequiredParameter"
        }
      ],
      "role": "symbol",
      "title": "kCMTimebaseError_MissingRequiredParameter",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtimebaseerror_missingrequiredparameter"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseError_ReadOnly": {
      "abstract": [
        {
          "text": "A timebase error that indicates the system attempts to modify a read-only timebase.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTimebaseError_ReadOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseError_ReadOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimebaseError_ReadOnly"
        }
      ],
      "role": "symbol",
      "title": "kCMTimebaseError_ReadOnly",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtimebaseerror_readonly"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseError_TimerIntervalTooShort": {
      "abstract": [
        {
          "text": "A timebase error that indicates the time interval is too short.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTimebaseError_TimerIntervalTooShort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseError_TimerIntervalTooShort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimebaseError_TimerIntervalTooShort"
        }
      ],
      "role": "symbol",
      "title": "kCMTimebaseError_TimerIntervalTooShort",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtimebaseerror_timerintervaltooshort"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/timebase-notifications": {
      "abstract": [
        {
          "text": "Keys that represent timebase notifications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/timebase-notifications",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Timebase Notifications",
      "type": "topic",
      "url": "/documentation/coremedia/timebase-notifications"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-error-codes",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmsync-error-codes",
        "doc://com.apple.coremedia/documentation/CoreMedia/timebase-notifications"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseError_MissingRequiredParameter",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseError_InvalidParameter",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseError_AllocationFailed",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseError_TimerIntervalTooShort",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseError_ReadOnly"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseError_MissingRequiredParameter",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseError_InvalidParameter",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseError_AllocationFailed",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseError_TimerIntervalTooShort",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseError_ReadOnly"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-error-codes",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmsync-error-codes",
                "doc://com.apple.coremedia/documentation/CoreMedia/timebase-notifications"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimebaseError_InvalidParameter/title",
          "value": "kCMTimebaseError_InvalidParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimebaseError_InvalidParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimebaseError_InvalidParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimebaseError_TimerIntervalTooShort/title",
          "value": "kCMTimebaseError_TimerIntervalTooShort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimebaseError_TimerIntervalTooShort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimebaseError_TimerIntervalTooShort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimebaseError_ReadOnly/title",
          "value": "kCMTimebaseError_ReadOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimebaseError_ReadOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimebaseError_ReadOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimebaseError_MissingRequiredParameter/title",
          "value": "kCMTimebaseError_MissingRequiredParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimebaseError_MissingRequiredParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimebaseError_MissingRequiredParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimebaseError_AllocationFailed/title",
          "value": "kCMTimebaseError_AllocationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimebaseError_AllocationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimebaseError_AllocationFailed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtimebase-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmtimebase-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
