{
  "abstract": [
    {
      "text": "A structure that maps a segment of a source time range to a target time range.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/cmtimemapping-api"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CMTimeMapping APIs"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMapping": {
      "abstract": [
        {
          "text": "A structure that maps a segment of a source time range to a target time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeMapping"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeMapping"
        }
      ],
      "role": "symbol",
      "title": "CMTimeMapping",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimemapping"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMapping/invalid": {
      "abstract": [
        {
          "text": "An invalid time mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeMapping",
          "text": "CMTimeMapping"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMapping/invalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimeMappingInvalid"
        }
      ],
      "role": "symbol",
      "title": "invalid",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimemapping/invalid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingCopyAsDictionary(_:allocator:)": {
      "abstract": [
        {
          "text": "Returns a dictionary representation of a time mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeMappingCopyAsDictionary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeMapping",
          "text": "CMTimeMapping"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingCopyAsDictionary(_:allocator:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeMappingCopyAsDictionary"
        }
      ],
      "role": "symbol",
      "title": "CMTimeMappingCopyAsDictionary(_:allocator:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimemappingcopyasdictionary(_:allocator:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingCopyDescription(allocator:mapping:)": {
      "abstract": [
        {
          "text": "Copies a string description of a time mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeMappingCopyDescription"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "mapping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeMapping",
          "text": "CMTimeMapping"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingCopyDescription(allocator:mapping:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeMappingCopyDescription"
        }
      ],
      "role": "symbol",
      "title": "CMTimeMappingCopyDescription(allocator:mapping:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimemappingcopydescription(allocator:mapping:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingMake(source:target:)": {
      "abstract": [
        {
          "text": "Creates a time mapping with a source and target time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeMappingMake"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "source"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeMapping",
          "text": "CMTimeMapping"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingMake(source:target:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeMappingMake"
        }
      ],
      "role": "symbol",
      "title": "CMTimeMappingMake(source:target:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimemappingmake(source:target:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingMakeEmpty(target:)": {
      "abstract": [
        {
          "text": "Creates a valid time mapping with an empty source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeMappingMakeEmpty"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeMapping",
          "text": "CMTimeMapping"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingMakeEmpty(target:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeMappingMakeEmpty"
        }
      ],
      "role": "symbol",
      "title": "CMTimeMappingMakeEmpty(target:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimemappingmakeempty(target:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingMakeFromDictionary(_:)": {
      "abstract": [
        {
          "text": "Creates a time mapping from a dictionary representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeMappingMakeFromDictionary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeMapping",
          "text": "CMTimeMapping"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingMakeFromDictionary(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeMappingMakeFromDictionary"
        }
      ],
      "role": "symbol",
      "title": "CMTimeMappingMakeFromDictionary(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimemappingmakefromdictionary(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingShow(_:)": {
      "abstract": [
        {
          "text": "Prints a description of a time mapping to standard output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeMappingShow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeMapping",
          "text": "CMTimeMapping"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingShow(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeMappingShow"
        }
      ],
      "role": "symbol",
      "title": "CMTimeMappingShow(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimemappingshow(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-api": {
      "abstract": [
        {
          "text": "A structure that represents time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTime APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtimerange-api": {
      "abstract": [
        {
          "text": "A structure that represents a range of time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtimerange-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTimeRange APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimerange-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeMappingSourceKey": {
      "abstract": [
        {
          "text": "A dictionary key for a source time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTimeMappingSourceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeMappingSourceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimeMappingSourceKey"
        }
      ],
      "role": "symbol",
      "title": "kCMTimeMappingSourceKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtimemappingsourcekey"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeMappingTargetKey": {
      "abstract": [
        {
          "text": "A dictionary key for a target time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTimeMappingTargetKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeMappingTargetKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimeMappingTargetKey"
        }
      ],
      "role": "symbol",
      "title": "kCMTimeMappingTargetKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtimemappingtargetkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Time-Representation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-api",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtimerange-api"
      ],
      "title": "Time Representation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Time-Mappings",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingMake(source:target:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingMakeEmpty(target:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingMakeFromDictionary(_:)"
      ],
      "title": "Creating Time Mappings"
    },
    {
      "anchor": "Representing-Time-Mappings",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingCopyAsDictionary(_:allocator:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingCopyDescription(allocator:mapping:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingShow(_:)"
      ],
      "title": "Representing Time Mappings"
    },
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMapping"
      ],
      "title": "Data Types"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMapping/invalid",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeMappingSourceKey",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeMappingTargetKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Time-Mappings",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingMake(source:target:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingMakeEmpty(target:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingMakeFromDictionary(_:)"
              ],
              "title": "Creating Time Mappings"
            },
            {
              "anchor": "Representing-Time-Mappings",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingCopyAsDictionary(_:allocator:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingCopyDescription(allocator:mapping:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMappingShow(_:)"
              ],
              "title": "Representing Time Mappings"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMapping"
              ],
              "title": "Data Types"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMapping/invalid",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeMappingSourceKey",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeMappingTargetKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Time-Representation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-api",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtimerange-api"
              ],
              "title": "Time Representation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimeMappingTargetKey/title",
          "value": "kCMTimeMappingTargetKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimeMappingTargetKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimeMappingTargetKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeMappingCopyDescription(allocator:mapping:)/title",
          "value": "CMTimeMappingCopyDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeMappingCopyDescription(allocator:mapping:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeMappingCopyDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeMapping~1invalid/title",
          "value": "kCMTimeMappingInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeMapping~1invalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimeMappingInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeMappingShow(_:)/title",
          "value": "CMTimeMappingShow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeMappingShow(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeMappingShow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeMappingMakeEmpty(target:)/title",
          "value": "CMTimeMappingMakeEmpty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeMappingMakeEmpty(target:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeMappingMakeEmpty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimeMappingSourceKey/title",
          "value": "kCMTimeMappingSourceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimeMappingSourceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimeMappingSourceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeMappingCopyAsDictionary(_:allocator:)/title",
          "value": "CMTimeMappingCopyAsDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeMappingCopyAsDictionary(_:allocator:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeMappingCopyAsDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeMappingMake(source:target:)/title",
          "value": "CMTimeMappingMake"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeMappingMake(source:target:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeMappingMake"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeMappingMakeFromDictionary(_:)/title",
          "value": "CMTimeMappingMakeFromDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeMappingMakeFromDictionary(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeMappingMakeFromDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeMapping/title",
          "value": "CMTimeMapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeMapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeMapping/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeMapping"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtimemapping-api"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmtimemapping-api"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
