{
  "abstract": [
    {
      "text": "Returns a Boolean value that indicates whether a time is indefinite.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_INDEFINITE"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@CMTIME_IS_INDEFINITE",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CMTIME_IS_INDEFINITE"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMTIME_IS_INDEFINITE"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Macro",
    "symbolKind": "macro",
    "title": "CMTIME_IS_INDEFINITE"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "#define"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMTIME_IS_INDEFINITE"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "internalParam",
              "text": "time"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if the time is indefinite; otherwise, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_HAS_BEEN_ROUNDED": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the system rounded the time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTIME_HAS_BEEN_ROUNDED"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_HAS_BEEN_ROUNDED",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTIME_HAS_BEEN_ROUNDED",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime_has_been_rounded"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_INDEFINITE": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a time is indefinite.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTIME_IS_INDEFINITE"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_INDEFINITE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTIME_IS_INDEFINITE",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime_is_indefinite"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_INVALID": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a time is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTIME_IS_INVALID"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_INVALID",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTIME_IS_INVALID",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime_is_invalid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_NEGATIVE_INFINITY": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a time is negative infinity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTIME_IS_NEGATIVE_INFINITY"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_NEGATIVE_INFINITY",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTIME_IS_NEGATIVE_INFINITY",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime_is_negative_infinity"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_NUMERIC": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a time is numeric.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTIME_IS_NUMERIC"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_NUMERIC",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTIME_IS_NUMERIC",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime_is_numeric"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_POSITIVE_INFINITY": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a time is positive infinity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTIME_IS_POSITIVE_INFINITY"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_POSITIVE_INFINITY",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTIME_IS_POSITIVE_INFINITY",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime_is_positive_infinity"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_VALID": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a time is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTIME_IS_VALID"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_VALID",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTIME_IS_VALID",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime_is_valid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeAbsoluteValue(_:)": {
      "abstract": [
        {
          "text": "Returns the absolute value of a time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeAbsoluteValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeAbsoluteValue(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeAbsoluteValue"
        }
      ],
      "role": "symbol",
      "title": "CMTimeAbsoluteValue(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimeabsolutevalue(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeGetSeconds(_:)": {
      "abstract": [
        {
          "text": "Returns a representation of the time in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeGetSeconds"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float64a",
          "text": "Float64"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeGetSeconds(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeGetSeconds"
        }
      ],
      "role": "symbol",
      "title": "CMTimeGetSeconds(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimegetseconds(_:)"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-a-Time",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeGetSeconds(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeAbsoluteValue(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_VALID",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_INVALID",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_POSITIVE_INFINITY",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_NEGATIVE_INFINITY",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_NUMERIC",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_HAS_BEEN_ROUNDED"
      ],
      "title": "Inspecting a Time"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeGetSeconds(_:)/title",
          "value": "CMTimeGetSeconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeGetSeconds(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeGetSeconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeAbsoluteValue(_:)/title",
          "value": "CMTimeAbsoluteValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeAbsoluteValue(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeAbsoluteValue"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtime_is_indefinite"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
