{
  "abstract": [
    {
      "text": "Keys to use when working with dictionary representations of a time range.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtimerange-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/cmtimerange-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Dictionary Keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To convert a ",
              "type": "text"
            },
            {
              "code": "CMTimeRange",
              "type": "codeVoice"
            },
            {
              "text": " to and from a ",
              "type": "text"
            },
            {
              "code": "CFDictionary",
              "type": "codeVoice"
            },
            {
              "text": ", see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeCopyAsDictionary(_:allocator:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeMakeFromDictionary(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeCopyAsDictionary(_:allocator:)": {
      "abstract": [
        {
          "text": "Returns a dictionary representation of a time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeRangeCopyAsDictionary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeCopyAsDictionary(_:allocator:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeRangeCopyAsDictionary"
        }
      ],
      "role": "symbol",
      "title": "CMTimeRangeCopyAsDictionary(_:allocator:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimerangecopyasdictionary(_:allocator:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeMakeFromDictionary(_:)": {
      "abstract": [
        {
          "text": "Creates a time range from a dictionary representation of its fields.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeRangeMakeFromDictionary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeMakeFromDictionary(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeRangeMakeFromDictionary"
        }
      ],
      "role": "symbol",
      "title": "CMTimeRangeMakeFromDictionary(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimerangemakefromdictionary(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtimerange-api": {
      "abstract": [
        {
          "text": "A structure that represents a range of time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtimerange-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTimeRange APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimerange-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeRangeDurationKey": {
      "abstract": [
        {
          "text": "The key for the timescale of a time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTimeRangeDurationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeRangeDurationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimeRangeDurationKey"
        }
      ],
      "role": "symbol",
      "title": "kCMTimeRangeDurationKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtimerangedurationkey"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeRangeStartKey": {
      "abstract": [
        {
          "text": "The key for the start field of a time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTimeRangeStartKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeRangeStartKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimeRangeStartKey"
        }
      ],
      "role": "symbol",
      "title": "kCMTimeRangeStartKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtimerangestartkey"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/pre-specified-time-ranges": {
      "abstract": [
        {
          "text": "Constants that specify zero and invalid time ranges.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/pre-specified-time-ranges",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pre-Specified Time Ranges",
      "type": "topic",
      "url": "/documentation/coremedia/pre-specified-time-ranges"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/pre-specified-time-ranges"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeRangeStartKey",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeRangeDurationKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeRangeStartKey",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimeRangeDurationKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/pre-specified-time-ranges"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRangeCopyAsDictionary(_:allocator:)/title",
          "value": "CMTimeRangeCopyAsDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRangeCopyAsDictionary(_:allocator:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeRangeCopyAsDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimeRangeDurationKey/title",
          "value": "kCMTimeRangeDurationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimeRangeDurationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimeRangeDurationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimeRangeStartKey/title",
          "value": "kCMTimeRangeStartKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimeRangeStartKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimeRangeStartKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRangeMakeFromDictionary(_:)/title",
          "value": "CMTimeRangeMakeFromDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRangeMakeFromDictionary(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeRangeMakeFromDictionary"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtimerange-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmtimerange-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
