{"seeAlsoSections":[{"generated":true,"title":"Inspecting a Time","identifiers":["doc://com.apple.coremedia/documentation/CoreMedia/CMTimeGetSeconds(_:)","doc://com.apple.coremedia/documentation/CoreMedia/CMTimeAbsoluteValue(_:)","doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_INVALID(_:)","doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_POSITIVEINFINITY(_:)","doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_NEGATIVEINFINITY(_:)","doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_INDEFINITE(_:)","doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_NUMERIC(_:)","doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_HAS_BEEN_ROUNDED(_:)"],"anchor":"Inspecting-a-Time"}],"metadata":{"externalID":"s:9CoreMedia15CMTIME_IS_VALIDySbSo6CMTimeaF","role":"symbol","platforms":[{"unavailable":false,"name":"iOS","introducedAt":"4.0","deprecated":false,"beta":false},{"unavailable":false,"name":"iPadOS","introducedAt":"4.0","deprecated":false,"beta":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false},{"unavailable":false,"name":"macOS","introducedAt":"10.7","deprecated":false,"beta":false},{"unavailable":false,"name":"tvOS","introducedAt":"9.0","deprecated":false,"beta":false},{"beta":false,"introducedAt":"1.0","unavailable":false,"deprecated":false,"name":"visionOS"},{"beta":false,"introducedAt":"6.0","unavailable":false,"deprecated":false,"name":"watchOS"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CMTIME_IS_VALID"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@CMTime","text":"CMTime"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"CMTIME_IS_VALID(_:)","roleHeading":"Function","symbolKind":"func","modules":[{"name":"Core Media"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether a given time is valid."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/coremedia/cmtime_is_valid(_:)"]}],"identifier":{"url":"doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_VALID(_:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.coremedia/documentation/CoreMedia"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CMTIME_IS_VALID"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTime","text":"CMTime","preciseIdentifier":"c:@SA@CMTime"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A time value to test.","type":"text"}]}],"name":"time"}],"kind":"parameters"},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true,"type":"reference"},{"text":" if the time is valid; otherwise, ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/swift/false","isActive":true,"type":"reference"},{"text":".","type":"text"}]}],"kind":"content"}],"references":{"doc://com.apple.documentation/documentation/swift/false":{"type":"topic","abstract":[{"type":"text","text":"A false value."}],"role":"symbol","kind":"symbol","title":"false","identifier":"doc://com.apple.documentation/documentation/swift/false","url":"/documentation/swift/false"},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"type":"topic","role":"overview","kind":"technologies","url":"/documentation/technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.coremedia/documentation/CoreMedia/CMTime":{"navigatorTitle":[{"text":"CMTime","kind":"identifier"}],"role":"symbol","title":"CMTime","type":"topic","identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTime","url":"/documentation/coremedia/cmtime","abstract":[{"type":"text","text":"A structure that represents time."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"CMTime","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_VALID(_:)":{"url":"/documentation/coremedia/cmtime_is_valid(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CMTIME_IS_VALID"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CMTime","preciseIdentifier":"c:@SA@CMTime"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_VALID(_:)","kind":"symbol","role":"symbol","title":"CMTIME_IS_VALID(_:)","type":"topic","abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether a given time is valid."}]},"doc://com.apple.coremedia/documentation/CoreMedia":{"url":"/documentation/coremedia","abstract":[{"type":"text","text":"Represent time-based audio-visual assets with essential data types."}],"identifier":"doc://com.apple.coremedia/documentation/CoreMedia","title":"Core Media","role":"collection","type":"topic","kind":"symbol"},"doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_POSITIVEINFINITY(_:)":{"title":"CMTIME_IS_POSITIVEINFINITY(_:)","url":"/documentation/coremedia/cmtime_is_positiveinfinity(_:)","abstract":[{"text":"Returns a Boolean value that indicates whether a given time is positive infinity.","type":"text"}],"type":"topic","identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_POSITIVEINFINITY(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CMTIME_IS_POSITIVEINFINITY","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@SA@CMTime","text":"CMTime","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.apple.coremedia/documentation/CoreMedia/CMTimeAbsoluteValue(_:)":{"kind":"symbol","identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTimeAbsoluteValue(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CMTimeAbsoluteValue","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@SA@CMTime","text":"CMTime","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@SA@CMTime","text":"CMTime","kind":"typeIdentifier"}],"type":"topic","title":"CMTimeAbsoluteValue(_:)","abstract":[{"text":"Returns the absolute value of a time.","type":"text"}],"navigatorTitle":[{"text":"CMTimeAbsoluteValue","kind":"identifier"}],"url":"/documentation/coremedia/cmtimeabsolutevalue(_:)"},"doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_INVALID(_:)":{"kind":"symbol","identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_INVALID(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CMTIME_IS_INVALID","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@SA@CMTime","text":"CMTime","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","title":"CMTIME_IS_INVALID(_:)","abstract":[{"text":"Returns a Boolean value that indicates whether a given time is invalid.","type":"text"}],"url":"/documentation/coremedia/cmtime_is_invalid(_:)"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"url":"/documentation/Swift/Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","role":"symbol"},"doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_NEGATIVEINFINITY(_:)":{"identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_NEGATIVEINFINITY(_:)","role":"symbol","title":"CMTIME_IS_NEGATIVEINFINITY(_:)","kind":"symbol","abstract":[{"text":"Returns a Boolean value that indicates whether a given time is negative infinity.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CMTIME_IS_NEGATIVEINFINITY","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CMTime","preciseIdentifier":"c:@SA@CMTime","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","url":"/documentation/coremedia/cmtime_is_negativeinfinity(_:)"},"doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_HAS_BEEN_ROUNDED(_:)":{"title":"CMTIME_HAS_BEEN_ROUNDED(_:)","url":"/documentation/coremedia/cmtime_has_been_rounded(_:)","abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether the system rounded the time value."}],"type":"topic","identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_HAS_BEEN_ROUNDED(_:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CMTIME_HAS_BEEN_ROUNDED"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CMTime","preciseIdentifier":"c:@SA@CMTime"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_INDEFINITE(_:)":{"type":"topic","abstract":[{"text":"Returns a Boolean value that indicates whether a given time is indefinite.","type":"text"}],"role":"symbol","kind":"symbol","title":"CMTIME_IS_INDEFINITE(_:)","identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_INDEFINITE(_:)","url":"/documentation/coremedia/cmtime_is_indefinite(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CMTIME_IS_INDEFINITE","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@SA@CMTime","text":"CMTime","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.apple.coremedia/documentation/CoreMedia/CMTimeGetSeconds(_:)":{"kind":"symbol","identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTimeGetSeconds(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CMTimeGetSeconds"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@SA@CMTime","kind":"typeIdentifier","text":"CMTime"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s7Float64a","kind":"typeIdentifier","text":"Float64"}],"type":"topic","title":"CMTimeGetSeconds(_:)","abstract":[{"text":"Returns a representation of the time in seconds.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CMTimeGetSeconds"}],"url":"/documentation/coremedia/cmtimegetseconds(_:)"},"doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_NUMERIC(_:)":{"identifier":"doc://com.apple.coremedia/documentation/CoreMedia/CMTIME_IS_NUMERIC(_:)","role":"symbol","title":"CMTIME_IS_NUMERIC(_:)","kind":"symbol","abstract":[{"text":"Returns a Boolean value that indicates whether a given time is numeric.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CMTIME_IS_NUMERIC"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@SA@CMTime","kind":"typeIdentifier","text":"CMTime"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","url":"/documentation/coremedia/cmtime_is_numeric(_:)"},"doc://com.apple.documentation/documentation/swift/true":{"role":"symbol","type":"topic","title":"true","url":"/documentation/swift/true","abstract":[{"text":"A true value.","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/swift/true","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"CMTime","path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime/title"},{"value":[{"text":"CMTime","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime/fragments"},{"value":[{"kind":"identifier","text":"CMTime"}],"op":"replace","path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime/navigatorTitle"},{"value":"CMTimeAbsoluteValue","op":"replace","path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeAbsoluteValue(_:)/title"},{"value":[{"kind":"identifier","text":"CMTimeAbsoluteValue"}],"op":"replace","path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeAbsoluteValue(_:)/fragments"},{"op":"replace","path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeGetSeconds(_:)/title","value":"CMTimeGetSeconds"},{"op":"replace","path":"/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeGetSeconds(_:)/fragments","value":[{"text":"CMTimeGetSeconds","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}