{
  "abstract": [
    {
      "text": "Returns a Boolean value that indicates whether a time range is invalid.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_INVALID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@CMTIMERANGE_IS_INVALID",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CMTIMERANGE_IS_INVALID"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMTIMERANGE_IS_INVALID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Macro",
    "symbolKind": "macro",
    "title": "CMTIMERANGE_IS_INVALID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "#define"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMTIMERANGE_IS_INVALID"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "internalParam",
              "text": "range"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The time range to be tested for invalidity.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "range"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": " if ",
              "type": "text"
            },
            {
              "code": "range",
              "type": "codeVoice"
            },
            {
              "text": " is invalid; otherwise, ",
              "type": "text"
            },
            {
              "code": "false",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_EMPTY": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a time range has a duration of zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTIMERANGE_IS_EMPTY"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_EMPTY",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTIMERANGE_IS_EMPTY",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimerange_is_empty"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_INDEFINITE": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a time range is indefinite.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTIMERANGE_IS_INDEFINITE"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_INDEFINITE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTIMERANGE_IS_INDEFINITE",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimerange_is_indefinite"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_INVALID": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a time range is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTIMERANGE_IS_INVALID"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_INVALID",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTIMERANGE_IS_INVALID",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimerange_is_invalid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_VALID": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether a time range is valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTIMERANGE_IS_VALID"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_VALID",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTIMERANGE_IS_VALID",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimerange_is_valid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeGetEnd(_:)": {
      "abstract": [
        {
          "text": "Returns a time value that represents the end of a time range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeRangeGetEnd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeGetEnd(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeRangeGetEnd"
        }
      ],
      "role": "symbol",
      "title": "CMTimeRangeGetEnd(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimerangegetend(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeGetIntersection(_:otherRange:)": {
      "abstract": [
        {
          "text": "Returns a new time range with the time elements that are common between the input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeRangeGetIntersection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "otherRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeGetIntersection(_:otherRange:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeRangeGetIntersection"
        }
      ],
      "role": "symbol",
      "title": "CMTimeRangeGetIntersection(_:otherRange:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimerangegetintersection(_:otherrange:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeGetUnion(_:otherRange:)": {
      "abstract": [
        {
          "text": "Returns a new time range with the time elements of the input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeRangeGetUnion"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "otherRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeGetUnion(_:otherRange:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeRangeGetUnion"
        }
      ],
      "role": "symbol",
      "title": "CMTimeRangeGetUnion(_:otherRange:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimerangegetunion(_:otherrange:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-Time-Ranges",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_EMPTY",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_INDEFINITE",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMERANGE_IS_VALID",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeGetEnd(_:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeGetIntersection(_:otherRange:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeRangeGetUnion(_:otherRange:)"
      ],
      "title": "Inspecting Time Ranges"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRangeGetEnd(_:)/title",
          "value": "CMTimeRangeGetEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRangeGetEnd(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeRangeGetEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRangeGetIntersection(_:otherRange:)/title",
          "value": "CMTimeRangeGetIntersection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRangeGetIntersection(_:otherRange:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeRangeGetIntersection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRangeGetUnion(_:otherRange:)/title",
          "value": "CMTimeRangeGetUnion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeRangeGetUnion(_:otherRange:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeRangeGetUnion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtimerange_is_invalid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
