{
  "abstract": [
    {
      "text": "Adds the timer to the list of timers the timebase manages.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseAddTimer(_:timer:runloop:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CMTimebaseAddTimer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMTimebaseAddTimer"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMTimebaseRef",
        "text": "CMTimebase"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "timer"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFRunLoopTimerRef",
        "text": "CFRunLoopTimer"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "runloop"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFRunLoopRef",
        "text": "CFRunLoop"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMTimebaseAddTimer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CMTimebaseAddTimer(_:timer:runloop:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMTimebaseAddTimer"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "timebase"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMTimebaseRef",
              "text": "CMTimebase"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "timer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFRunLoopTimerRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFRunLoopTimerRef",
              "text": "CFRunLoopTimer"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "runloop"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFRunLoopRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFRunLoopRef",
              "text": "CFRunLoop"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The timer must be a repeating runloop timer (with a very long interval at least as long as the constant ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseVeryLongCFTimeInterval",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") attached to a runloop. The timebase retains the timer, and maintains its “NextFireDate” according to the ",
              "type": "text"
            },
            {
              "code": "CMTime",
              "type": "codeVoice"
            },
            {
              "text": " set using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseSetTimerNextFireTime(_:timer:fireTime:flags:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Until the first call to ",
              "type": "text"
            },
            {
              "code": "CMTimebaseSetTimerNextFireTime",
              "type": "codeVoice"
            },
            {
              "text": ", the system sets the “NextFireDate” to a future time. The function retains the  runloop you specify, which must be the runloop you attached to the timer when you created it. The system uses the retained runloop to call ",
              "type": "text"
            },
            {
              "code": "CFRunLoopWakeUp",
              "type": "codeVoice"
            },
            {
              "text": "() when the timebase modifies the timer’s fire date.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase": {
      "abstract": [
        {
          "text": "A model of a timeline under application control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimebase"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimebase"
        }
      ],
      "role": "symbol",
      "title": "CMTimebase",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseAddTimer(_:timer:runloop:)": {
      "abstract": [
        {
          "text": "Adds the timer to the list of timers the timebase manages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimebaseAddTimer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTimebaseRef",
          "text": "CMTimebase"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopTimerRef",
          "text": "CFRunLoopTimer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "runloop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopRef",
          "text": "CFRunLoop"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseAddTimer(_:timer:runloop:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimebaseAddTimer"
        }
      ],
      "role": "symbol",
      "title": "CMTimebaseAddTimer(_:timer:runloop:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebaseaddtimer(_:timer:runloop:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseAddTimerDispatchSource(_:timerSource:)": {
      "abstract": [
        {
          "text": "Adds the timer dispatch source to the list of timers the timebase manages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimebaseAddTimerDispatchSource"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTimebaseRef",
          "text": "CMTimebase"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timerSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_source_t",
          "text": "dispatch_source_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseAddTimerDispatchSource(_:timerSource:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimebaseAddTimerDispatchSource"
        }
      ],
      "role": "symbol",
      "title": "CMTimebaseAddTimerDispatchSource(_:timerSource:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebaseaddtimerdispatchsource(_:timersource:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseRemoveTimer(_:timer:)": {
      "abstract": [
        {
          "text": "Removes the timer from the list of timers the timebase manages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimebaseRemoveTimer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTimebaseRef",
          "text": "CMTimebase"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopTimerRef",
          "text": "CFRunLoopTimer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseRemoveTimer(_:timer:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimebaseRemoveTimer"
        }
      ],
      "role": "symbol",
      "title": "CMTimebaseRemoveTimer(_:timer:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebaseremovetimer(_:timer:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseRemoveTimerDispatchSource(_:timerSource:)": {
      "abstract": [
        {
          "text": "Removes the timer dispatch source from the list of timers the timebase manages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimebaseRemoveTimerDispatchSource"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTimebaseRef",
          "text": "CMTimebase"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timerSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_source_t",
          "text": "dispatch_source_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseRemoveTimerDispatchSource(_:timerSource:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimebaseRemoveTimerDispatchSource"
        }
      ],
      "role": "symbol",
      "title": "CMTimebaseRemoveTimerDispatchSource(_:timerSource:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebaseremovetimerdispatchsource(_:timersource:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseSetTimerDispatchSourceNextFireTime(_:timerSource:fireTime:flags:)": {
      "abstract": [
        {
          "text": "Sets the time on the timebase’s timeline at which the timer dispatch source should fire next.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimebaseSetTimerDispatchSourceNextFireTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTimebaseRef",
          "text": "CMTimebase"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timerSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_source_t",
          "text": "dispatch_source_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fireTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseSetTimerDispatchSourceNextFireTime(_:timerSource:fireTime:flags:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimebaseSetTimerDispatchSourceNextFireTime"
        }
      ],
      "role": "symbol",
      "title": "CMTimebaseSetTimerDispatchSourceNextFireTime(_:timerSource:fireTime:flags:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebasesettimerdispatchsourcenextfiretime(_:timersource:firetime:flags:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseSetTimerDispatchSourceToFireImmediately(_:timerSource:)": {
      "abstract": [
        {
          "text": "Sets the timer dispatch source to fire immediately once, overriding any previous timer call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimebaseSetTimerDispatchSourceToFireImmediately"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTimebaseRef",
          "text": "CMTimebase"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timerSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_source_t",
          "text": "dispatch_source_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseSetTimerDispatchSourceToFireImmediately(_:timerSource:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimebaseSetTimerDispatchSourceToFireImmediately"
        }
      ],
      "role": "symbol",
      "title": "CMTimebaseSetTimerDispatchSourceToFireImmediately(_:timerSource:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebasesettimerdispatchsourcetofireimmediately(_:timersource:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseSetTimerNextFireTime(_:timer:fireTime:flags:)": {
      "abstract": [
        {
          "text": "Sets the time on the timebase’s timeline at which the timer should fire next.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimebaseSetTimerNextFireTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTimebaseRef",
          "text": "CMTimebase"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopTimerRef",
          "text": "CFRunLoopTimer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "fireTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseSetTimerNextFireTime(_:timer:fireTime:flags:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimebaseSetTimerNextFireTime"
        }
      ],
      "role": "symbol",
      "title": "CMTimebaseSetTimerNextFireTime(_:timer:fireTime:flags:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebasesettimernextfiretime(_:timer:firetime:flags:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseSetTimerToFireImmediately(_:timer:)": {
      "abstract": [
        {
          "text": "Sets the timer to fire immediately once, overriding any previous timer calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimebaseSetTimerToFireImmediately"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTimebaseRef",
          "text": "CMTimebase"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopTimerRef",
          "text": "CFRunLoopTimer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseSetTimerToFireImmediately(_:timer:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimebaseSetTimerToFireImmediately"
        }
      ],
      "role": "symbol",
      "title": "CMTimebaseSetTimerToFireImmediately(_:timer:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebasesettimertofireimmediately(_:timer:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseVeryLongCFTimeInterval": {
      "abstract": [
        {
          "text": "A constant that defines a very long elapsed time in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTimebaseVeryLongCFTimeInterval"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseVeryLongCFTimeInterval",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTimebaseVeryLongCFTimeInterval",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtimebaseverylongcftimeinterval"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFRunLoopRef": {
      "abstract": [
        {
          "text": "A reference to a run loop object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFRunLoop"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFRunLoopRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFRunLoop",
      "type": "topic",
      "url": "/documentation/corefoundation/cfrunloop"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFRunLoopTimerRef": {
      "abstract": [
        {
          "text": "A reference to a run loop timer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFRunLoopTimer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFRunLoopTimerRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFRunLoopTimer",
      "type": "topic",
      "url": "/documentation/corefoundation/cfrunlooptimer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Interacting-with-Timers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseAddTimerDispatchSource(_:timerSource:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseRemoveTimer(_:timer:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseRemoveTimerDispatchSource(_:timerSource:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseSetTimerNextFireTime(_:timer:fireTime:flags:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseSetTimerToFireImmediately(_:timer:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseSetTimerDispatchSourceNextFireTime(_:timerSource:fireTime:flags:)",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseSetTimerDispatchSourceToFireImmediately(_:timerSource:)"
      ],
      "title": "Interacting with Timers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMTimebaseAddTimer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimebaseAddTimer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Interacting-with-Timers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseAddTimerDispatchSource(_:timerSource:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseRemoveTimer(_:timer:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseRemoveTimerDispatchSource(_:timerSource:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseSetTimerNextFireTime(_:timer:fireTime:flags:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseSetTimerToFireImmediately(_:timer:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseSetTimerDispatchSourceNextFireTime(_:timerSource:fireTime:flags:)",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebaseSetTimerDispatchSourceToFireImmediately(_:timerSource:)"
              ],
              "title": "Interacting with Timers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@OSStatus",
                    "text": "OSStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMTimebaseAddTimer"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimebase",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMTimebaseRef",
                    "text": "CMTimebaseRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "timebase"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFRunLoopTimerRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFRunLoopTimerRef",
                    "text": "CFRunLoopTimerRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "timer"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFRunLoopRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFRunLoopRef",
                    "text": "CFRunLoopRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "runloop"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebaseAddTimer(_:timer:runloop:)/title",
          "value": "CMTimebaseAddTimer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebaseAddTimer(_:timer:runloop:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimebaseAddTimer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebaseRemoveTimerDispatchSource(_:timerSource:)/title",
          "value": "CMTimebaseRemoveTimerDispatchSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebaseRemoveTimerDispatchSource(_:timerSource:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimebaseRemoveTimerDispatchSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebaseSetTimerDispatchSourceNextFireTime(_:timerSource:fireTime:flags:)/title",
          "value": "CMTimebaseSetTimerDispatchSourceNextFireTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebaseSetTimerDispatchSourceNextFireTime(_:timerSource:fireTime:flags:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimebaseSetTimerDispatchSourceNextFireTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebaseSetTimerNextFireTime(_:timer:fireTime:flags:)/title",
          "value": "CMTimebaseSetTimerNextFireTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebaseSetTimerNextFireTime(_:timer:fireTime:flags:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimebaseSetTimerNextFireTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFRunLoopTimerRef/title",
          "value": "CFRunLoopTimerRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebaseSetTimerToFireImmediately(_:timer:)/title",
          "value": "CMTimebaseSetTimerToFireImmediately"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebaseSetTimerToFireImmediately(_:timer:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimebaseSetTimerToFireImmediately"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebase/title",
          "value": "CMTimebaseRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimebaseRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimebaseRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebaseRemoveTimer(_:timer:)/title",
          "value": "CMTimebaseRemoveTimer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebaseRemoveTimer(_:timer:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimebaseRemoveTimer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebaseAddTimerDispatchSource(_:timerSource:)/title",
          "value": "CMTimebaseAddTimerDispatchSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebaseAddTimerDispatchSource(_:timerSource:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimebaseAddTimerDispatchSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebaseSetTimerDispatchSourceToFireImmediately(_:timerSource:)/title",
          "value": "CMTimebaseSetTimerDispatchSourceToFireImmediately"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimebaseSetTimerDispatchSourceToFireImmediately(_:timerSource:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimebaseSetTimerDispatchSourceToFireImmediately"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFRunLoopRef/title",
          "value": "CFRunLoopRef"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtimebaseaddtimer(_:timer:runloop:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmtimebaseaddtimer(_:timer:runloop:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
