{
  "abstract": [
    {
      "text": "Defined time values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-time"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Time"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTime/indefinite": {
      "abstract": [
        {
          "text": "A value that represents an indefinite time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indefinite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTime/indefinite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimeIndefinite"
        }
      ],
      "role": "symbol",
      "title": "indefinite",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime/indefinite"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTime/invalid": {
      "abstract": [
        {
          "text": "A value that represents an invalid time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTime/invalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimeInvalid"
        }
      ],
      "role": "symbol",
      "title": "invalid",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime/invalid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTime/negativeInfinity": {
      "abstract": [
        {
          "text": "A value that represents negative infinity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "negativeInfinity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTime/negativeInfinity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimeNegativeInfinity"
        }
      ],
      "role": "symbol",
      "title": "negativeInfinity",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime/negativeinfinity"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTime/positiveInfinity": {
      "abstract": [
        {
          "text": "A value that represents positive infinity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "positiveInfinity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTime/positiveInfinity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimePositiveInfinity"
        }
      ],
      "role": "symbol",
      "title": "positiveInfinity",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime/positiveinfinity"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTime/zero": {
      "abstract": [
        {
          "text": "A value that represents time zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zero"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTime/zero",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimeZero"
        }
      ],
      "role": "symbol",
      "title": "zero",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime/zero"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-api": {
      "abstract": [
        {
          "text": "A structure that represents time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTime APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-dictionary-keys": {
      "abstract": [
        {
          "text": "Keys to use when working with dictionary representations of time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Dictionary Keys",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime-dictionary-keys"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-timescale": {
      "abstract": [
        {
          "text": "Defined timescale values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-timescale",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Timescale",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime-timescale"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-timescale",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-dictionary-keys"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Defined-Times",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTime/invalid",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTime/indefinite",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTime/positiveInfinity",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTime/negativeInfinity",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTime/zero"
      ],
      "title": "Defined Times"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Defined-Times",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTime/invalid",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTime/indefinite",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTime/positiveInfinity",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTime/negativeInfinity",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTime/zero"
              ],
              "title": "Defined Times"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-timescale",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtime-dictionary-keys"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime~1positiveInfinity/title",
          "value": "kCMTimePositiveInfinity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime~1positiveInfinity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimePositiveInfinity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime~1invalid/title",
          "value": "kCMTimeInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime~1invalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimeInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime~1negativeInfinity/title",
          "value": "kCMTimeNegativeInfinity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime~1negativeInfinity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimeNegativeInfinity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime~1indefinite/title",
          "value": "kCMTimeIndefinite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime~1indefinite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimeIndefinite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime~1zero/title",
          "value": "kCMTimeZero"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime~1zero/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimeZero"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmtime-time"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmtime-time"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
