{
  "abstract": [
    {
      "text": "A video codec type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoCodecType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CMVideoCodecType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CMVideoCodecType"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMVideoCodecType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "CMVideoCodecType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMVideoCodecType"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@FourCharCode",
              "text": "FourCharCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Certain codec types are also pixel formats.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "There is no “kCMVideoCodecType_Raw”; you should use the appropriate pixel format type as the codec type.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioCodecType": {
      "abstract": [
        {
          "text": "An audio codec type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMAudioCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioCodecType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMAudioCodecType"
        }
      ],
      "role": "symbol",
      "title": "CMAudioCodecType",
      "type": "topic",
      "url": "/documentation/coremedia/cmaudiocodectype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescriptionMask": {
      "abstract": [
        {
          "text": "A type for mask bits that represent parts of an audio format description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMAudioFormatDescriptionMask"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescriptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMAudioFormatDescriptionMask"
        }
      ],
      "role": "symbol",
      "title": "CMAudioFormatDescriptionMask",
      "type": "topic",
      "url": "/documentation/coremedia/cmaudioformatdescriptionmask"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMediaType": {
      "abstract": [
        {
          "text": "Constants that represent media types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMediaType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMediaType"
        }
      ],
      "role": "symbol",
      "title": "CMMediaType",
      "type": "topic",
      "url": "/documentation/coremedia/cmmediatype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTextDisplayFlags": {
      "abstract": [
        {
          "text": "An integer value that describes the display mode flags for text media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTextDisplayFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTextDisplayFlags"
        }
      ],
      "role": "symbol",
      "title": "CMTextDisplayFlags",
      "type": "topic",
      "url": "/documentation/coremedia/cmtextdisplayflags"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTextJustificationValue": {
      "abstract": [
        {
          "text": "An integer value that describes the justification modes for text media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTextJustificationValue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTextJustificationValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTextJustificationValue"
        }
      ],
      "role": "symbol",
      "title": "CMTextJustificationValue",
      "type": "topic",
      "url": "/documentation/coremedia/cmtextjustificationvalue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoCodecType": {
      "abstract": [
        {
          "text": "A video codec type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoCodecType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMVideoCodecType"
        }
      ],
      "role": "symbol",
      "title": "CMVideoCodecType",
      "type": "topic",
      "url": "/documentation/coremedia/cmvideocodectype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoDimensions": {
      "abstract": [
        {
          "text": "A structure that represents video dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMVideoDimensions"
        }
      ],
      "role": "symbol",
      "title": "CMVideoDimensions",
      "type": "topic",
      "url": "/documentation/coremedia/cmvideodimensions"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/audio-codec-types": {
      "abstract": [
        {
          "text": "Constants that represent audio codec types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/audio-codec-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec Types",
      "type": "topic",
      "url": "/documentation/coremedia/audio-codec-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_422YpCbCr8": {
      "abstract": [
        {
          "text": "A type that identifies a component with the format of Y’CbCr 8-bit 4:2:2 ordered Cb Y’0 Cr Y’1.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_422YpCbCr8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_422YpCbCr8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_422YpCbCr8"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_422YpCbCr8",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_422ypcbcr8"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Animation": {
      "abstract": [
        {
          "text": "A type that identifies the apple animation format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_Animation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Animation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_Animation"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_Animation",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_animation"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Cinepak": {
      "abstract": [
        {
          "text": "A type that identifies the cinepak format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_Cinepak"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Cinepak",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_Cinepak"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_Cinepak",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_cinepak"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCNTSC": {
      "abstract": [
        {
          "text": "A type that identifies the DV NTSC format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCNTSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCNTSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCNTSC"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCNTSC",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcntsc"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPAL": {
      "abstract": [
        {
          "text": "A type that identifies the DV PAL format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPAL"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPAL",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcpal"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i50": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro-HD 1080i50 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080i50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080i50"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPROHD1080i50",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcprohd1080i50"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i60": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro-HD 1080i60 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080i60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080i60"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPROHD1080i60",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcprohd1080i60"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080p25": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro-HD 1080p25 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080p25"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080p25",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080p25"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPROHD1080p25",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcprohd1080p25"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080p30": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro-HD 1080p30 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080p30"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080p30",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080p30"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPROHD1080p30",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcprohd1080p30"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD720p50": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro-HD 720p50 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD720p50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD720p50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD720p50"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPROHD720p50",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcprohd720p50"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD720p60": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro-HD 720p60 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD720p60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD720p60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD720p60"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPROHD720p60",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcprohd720p60"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPro50NTSC": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro-50 NTSC format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPro50NTSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPro50NTSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPro50NTSC"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPro50NTSC",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcpro50ntsc"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPro50PAL": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro-50 PAL format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPro50PAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPro50PAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPro50PAL"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPro50PAL",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcpro50pal"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCProPAL": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro PAL format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCProPAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCProPAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCProPAL"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCProPAL",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcpropal"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H263": {
      "abstract": [
        {
          "text": "A type that identifies the ITU-T H.263 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_H263"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H263",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_H263"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_H263",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_h263"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H264": {
      "abstract": [
        {
          "text": "A type that identifies the ITU-T H.264 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_H264"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H264",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_H264"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_H264",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_h264"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG": {
      "abstract": [
        {
          "text": "A type that identifies the Joint Photographic Experts Group (JPEG) format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_JPEG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_JPEG"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_JPEG",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_jpeg"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG_OpenDML": {
      "abstract": [
        {
          "text": "A type that identifies the JPEG format with Open-DML extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_JPEG_OpenDML"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG_OpenDML",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_JPEG_OpenDML"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_JPEG_OpenDML",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_jpeg_opendml"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG1Video": {
      "abstract": [
        {
          "text": "A type that identifies the MPEG-1 video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_MPEG1Video"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG1Video",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_MPEG1Video"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_MPEG1Video",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_mpeg1video"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG2Video": {
      "abstract": [
        {
          "text": "A type that identifies the MPEG-2 video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_MPEG2Video"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG2Video",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_MPEG2Video"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_MPEG2Video",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_mpeg2video"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG4Video": {
      "abstract": [
        {
          "text": "A type that identifies the Moving Picture Experts Group (MPEG) MPEG-4 Part 2 video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_MPEG4Video"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG4Video",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_MPEG4Video"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_MPEG4Video",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_mpeg4video"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo": {
      "abstract": [
        {
          "text": "A type that identifies the sorenson video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_SorensonVideo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_SorensonVideo"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_SorensonVideo",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_sorensonvideo"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo3": {
      "abstract": [
        {
          "text": "A type that identifies the sorenson 3 video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_SorensonVideo3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_SorensonVideo3"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_SorensonVideo3",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_sorensonvideo3"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/media-type-constants": {
      "abstract": [
        {
          "text": "Constants that represent media types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/media-type-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media Type Constants",
      "type": "topic",
      "url": "/documentation/coremedia/media-type-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/muxed-stream-types": {
      "abstract": [
        {
          "text": "Constants that represent muxed stream types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/muxed-stream-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Muxed Stream Types",
      "type": "topic",
      "url": "/documentation/coremedia/muxed-stream-types"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoDimensions",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescriptionMask",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMediaType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioCodecType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTextDisplayFlags",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTextJustificationValue",
        "doc://com.apple.coremedia/documentation/CoreMedia/media-type-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/muxed-stream-types",
        "doc://com.apple.coremedia/documentation/CoreMedia/audio-codec-types"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_422YpCbCr8",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Animation",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Cinepak",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG_OpenDML",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo3",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H263",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H264",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG4Video",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG2Video",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG1Video",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCNTSC",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPAL",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCProPAL",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPro50NTSC",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPro50PAL",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD720p60",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD720p50",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i60",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i50",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080p30",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080p25"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMVideoCodecType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_422YpCbCr8",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Animation",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Cinepak",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG_OpenDML",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo3",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H263",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H264",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG4Video",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG2Video",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG1Video",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCNTSC",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPAL",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCProPAL",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPro50NTSC",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPro50PAL",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD720p60",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD720p50",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i60",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i50",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080p30",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080p25"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoDimensions",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescriptionMask",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMediaType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioCodecType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTextDisplayFlags",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTextJustificationValue",
                "doc://com.apple.coremedia/documentation/CoreMedia/media-type-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/muxed-stream-types",
                "doc://com.apple.coremedia/documentation/CoreMedia/audio-codec-types"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@FourCharCode",
                    "text": "FourCharCode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CMVideoCodecType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_Cinepak/title",
          "value": "kCMVideoCodecType_Cinepak"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_Cinepak/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_Cinepak"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_JPEG_OpenDML/title",
          "value": "kCMVideoCodecType_JPEG_OpenDML"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_JPEG_OpenDML/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_JPEG_OpenDML"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_SorensonVideo3/title",
          "value": "kCMVideoCodecType_SorensonVideo3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_SorensonVideo3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_SorensonVideo3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD720p60/title",
          "value": "kCMVideoCodecType_DVCPROHD720p60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD720p60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPROHD720p60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080p25/title",
          "value": "kCMVideoCodecType_DVCPROHD1080p25"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080p25/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPROHD1080p25"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoDimensions/title",
          "value": "CMVideoDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoDimensions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMediaType/title",
          "value": "CMMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMediaType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCNTSC/title",
          "value": "kCMVideoCodecType_DVCNTSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCNTSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCNTSC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_MPEG4Video/title",
          "value": "kCMVideoCodecType_MPEG4Video"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_MPEG4Video/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_MPEG4Video"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_SorensonVideo/title",
          "value": "kCMVideoCodecType_SorensonVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_SorensonVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_SorensonVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080p30/title",
          "value": "kCMVideoCodecType_DVCPROHD1080p30"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080p30/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPROHD1080p30"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCProPAL/title",
          "value": "kCMVideoCodecType_DVCProPAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCProPAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCProPAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080i60/title",
          "value": "kCMVideoCodecType_DVCPROHD1080i60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080i60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPROHD1080i60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_H264/title",
          "value": "kCMVideoCodecType_H264"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_H264/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_H264"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextJustificationValue/title",
          "value": "CMTextJustificationValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextJustificationValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextJustificationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextJustificationValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextJustificationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080i50/title",
          "value": "kCMVideoCodecType_DVCPROHD1080i50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080i50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPROHD1080i50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioFormatDescriptionMask/title",
          "value": "CMAudioFormatDescriptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioFormatDescriptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioFormatDescriptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioFormatDescriptionMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioFormatDescriptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPro50PAL/title",
          "value": "kCMVideoCodecType_DVCPro50PAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPro50PAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPro50PAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_Animation/title",
          "value": "kCMVideoCodecType_Animation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_Animation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_Animation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_JPEG/title",
          "value": "kCMVideoCodecType_JPEG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_JPEG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_JPEG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_422YpCbCr8/title",
          "value": "kCMVideoCodecType_422YpCbCr8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_422YpCbCr8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_422YpCbCr8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_MPEG2Video/title",
          "value": "kCMVideoCodecType_MPEG2Video"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_MPEG2Video/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_MPEG2Video"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_MPEG1Video/title",
          "value": "kCMVideoCodecType_MPEG1Video"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_MPEG1Video/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_MPEG1Video"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_H263/title",
          "value": "kCMVideoCodecType_H263"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_H263/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_H263"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoCodecType/title",
          "value": "CMVideoCodecType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoCodecType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoCodecType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPAL/title",
          "value": "kCMVideoCodecType_DVCPAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD720p50/title",
          "value": "kCMVideoCodecType_DVCPROHD720p50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD720p50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPROHD720p50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextDisplayFlags/title",
          "value": "CMTextDisplayFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextDisplayFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextDisplayFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextDisplayFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextDisplayFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPro50NTSC/title",
          "value": "kCMVideoCodecType_DVCPro50NTSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPro50NTSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPro50NTSC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioCodecType/title",
          "value": "CMAudioCodecType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioCodecType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioCodecType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioCodecType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmvideocodectype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmvideocodectype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
