{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMITEMCOUNT_MAX": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMITEMCOUNT_MAX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMITEMCOUNT_MAX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMITEMCOUNT_MAX"
        }
      ],
      "role": "symbol",
      "title": "CMITEMCOUNT_MAX",
      "type": "topic",
      "url": "/documentation/coremedia/cmitemcount_max"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMEBASE_USE_SOURCE_TERMINOLOGY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTIMEBASE_USE_SOURCE_TERMINOLOGY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMEBASE_USE_SOURCE_TERMINOLOGY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTIMEBASE_USE_SOURCE_TERMINOLOGY"
        }
      ],
      "role": "symbol",
      "title": "CMTIMEBASE_USE_SOURCE_TERMINOLOGY",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase_use_source_terminology"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_cmbaseclass_version_is_pointer_aligned"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_BRIDGED_TYPES": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_BRIDGED_TYPES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_BRIDGED_TYPES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_BRIDGED_TYPES"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_DECLARE_BRIDGED_TYPES",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_declare_bridged_types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_NULLABILITY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_NULLABILITY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_NULLABILITY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_NULLABILITY"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_DECLARE_NULLABILITY",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_declare_nullability"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_NULLABILITY_BEGIN_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_NULLABILITY_BEGIN_END"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_NULLABILITY_BEGIN_END",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_NULLABILITY_BEGIN_END"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_DECLARE_NULLABILITY_BEGIN_END",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_declare_nullability_begin_end"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RELEASES_ARGUMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_RELEASES_ARGUMENT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RELEASES_ARGUMENT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_RELEASES_ARGUMENT"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_DECLARE_RELEASES_ARGUMENT",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_declare_releases_argument"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_declare_returns_not_retained_on_parameters"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_RETURNS_RETAINED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_RETURNS_RETAINED"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_DECLARE_RETURNS_RETAINED",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_declare_returns_retained"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_declare_returns_retained_block"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_declare_returns_retained_on_parameters"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_FALSE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_FALSE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_FALSE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_FALSE"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_FALSE",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_false"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_TRUE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_TRUE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_TRUE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_TRUE"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_TRUE",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_true"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_use_aligned_cmbaseclass_version"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_use_derived_enums_for_constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ProjectionKind": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ProjectionKind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ProjectionKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ProjectionKind"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_ProjectionKind",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_projectionkind"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_BRIDGED_TYPES",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_NULLABILITY",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_NULLABILITY_BEGIN_END",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMITEMCOUNT_MAX",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RELEASES_ARGUMENT",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_FALSE",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_TRUE",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMEBASE_USE_SOURCE_TERMINOLOGY",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ProjectionKind"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_BRIDGED_TYPES",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_NULLABILITY",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_NULLABILITY_BEGIN_END",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMITEMCOUNT_MAX",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RELEASES_ARGUMENT",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_FALSE",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_TRUE",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMEBASE_USE_SOURCE_TERMINOLOGY",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ProjectionKind"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED/title",
          "value": "COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS/title",
          "value": "COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK/title",
          "value": "COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_ProjectionKind/title",
          "value": "kCMFormatDescriptionExtension_ProjectionKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_ProjectionKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_ProjectionKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_RELEASES_ARGUMENT/title",
          "value": "COREMEDIA_DECLARE_RELEASES_ARGUMENT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_RELEASES_ARGUMENT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_DECLARE_RELEASES_ARGUMENT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_BRIDGED_TYPES/title",
          "value": "COREMEDIA_DECLARE_BRIDGED_TYPES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_BRIDGED_TYPES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_DECLARE_BRIDGED_TYPES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_RETURNS_RETAINED/title",
          "value": "COREMEDIA_DECLARE_RETURNS_RETAINED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_RETURNS_RETAINED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_DECLARE_RETURNS_RETAINED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_TRUE/title",
          "value": "COREMEDIA_TRUE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_TRUE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_TRUE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION/title",
          "value": "COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTIMEBASE_USE_SOURCE_TERMINOLOGY/title",
          "value": "CMTIMEBASE_USE_SOURCE_TERMINOLOGY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTIMEBASE_USE_SOURCE_TERMINOLOGY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTIMEBASE_USE_SOURCE_TERMINOLOGY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_NULLABILITY_BEGIN_END/title",
          "value": "COREMEDIA_DECLARE_NULLABILITY_BEGIN_END"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_NULLABILITY_BEGIN_END/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_DECLARE_NULLABILITY_BEGIN_END"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_NULLABILITY/title",
          "value": "COREMEDIA_DECLARE_NULLABILITY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_NULLABILITY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_DECLARE_NULLABILITY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMITEMCOUNT_MAX/title",
          "value": "CMITEMCOUNT_MAX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMITEMCOUNT_MAX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMITEMCOUNT_MAX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_FALSE/title",
          "value": "COREMEDIA_FALSE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_FALSE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_FALSE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS/title",
          "value": "COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS/title",
          "value": "COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/coremedia_use_aligned_cmbaseclass_version"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/coremedia_use_aligned_cmbaseclass_version"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
