{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/core-media-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core Media Constants"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This document describes constants defined in the Core Media framework not defined elsewhere in this reference.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBaseClassVersion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBaseClassVersion"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBaseClassVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBaseClassVersion"
        }
      ],
      "role": "symbol",
      "title": "CMBaseClassVersion",
      "type": "topic",
      "url": "/documentation/coremedia/cmbaseclassversion"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMITEMCOUNT_MAX": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMITEMCOUNT_MAX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMITEMCOUNT_MAX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMITEMCOUNT_MAX"
        }
      ],
      "role": "symbol",
      "title": "CMITEMCOUNT_MAX",
      "type": "topic",
      "url": "/documentation/coremedia/cmitemcount_max"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMStructVersion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMStructVersion"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMStructVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMStructVersion"
        }
      ],
      "role": "symbol",
      "title": "CMStructVersion",
      "type": "topic",
      "url": "/documentation/coremedia/cmstructversion"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMEBASE_USE_SOURCE_TERMINOLOGY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTIMEBASE_USE_SOURCE_TERMINOLOGY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMEBASE_USE_SOURCE_TERMINOLOGY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTIMEBASE_USE_SOURCE_TERMINOLOGY"
        }
      ],
      "role": "symbol",
      "title": "CMTIMEBASE_USE_SOURCE_TERMINOLOGY",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase_use_source_terminology"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_cmbaseclass_version_is_pointer_aligned"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_BRIDGED_TYPES": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_BRIDGED_TYPES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_BRIDGED_TYPES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_BRIDGED_TYPES"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_DECLARE_BRIDGED_TYPES",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_declare_bridged_types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_NULLABILITY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_NULLABILITY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_NULLABILITY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_NULLABILITY"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_DECLARE_NULLABILITY",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_declare_nullability"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_NULLABILITY_BEGIN_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_NULLABILITY_BEGIN_END"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_NULLABILITY_BEGIN_END",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_NULLABILITY_BEGIN_END"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_DECLARE_NULLABILITY_BEGIN_END",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_declare_nullability_begin_end"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RELEASES_ARGUMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_RELEASES_ARGUMENT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RELEASES_ARGUMENT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_RELEASES_ARGUMENT"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_DECLARE_RELEASES_ARGUMENT",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_declare_releases_argument"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_declare_returns_not_retained_on_parameters"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_RETURNS_RETAINED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_RETURNS_RETAINED"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_DECLARE_RETURNS_RETAINED",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_declare_returns_retained"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_declare_returns_retained_block"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_declare_returns_retained_on_parameters"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_FALSE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_FALSE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_FALSE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_FALSE"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_FALSE",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_false"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_TRUE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_TRUE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_TRUE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_TRUE"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_TRUE",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_true"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_use_aligned_cmbaseclass_version"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS"
        }
      ],
      "role": "symbol",
      "title": "COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS",
      "type": "topic",
      "url": "/documentation/coremedia/coremedia_use_derived_enums_for_constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/core-media-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/core-media-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Media Functions",
      "type": "topic",
      "url": "/documentation/coremedia/core-media-functions"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/core-media-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/core-media-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Media Macros",
      "type": "topic",
      "url": "/documentation/coremedia/core-media-macros"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/core-media-type-aliases": {
      "abstract": [],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/core-media-type-aliases",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Media Type Aliases",
      "type": "topic",
      "url": "/documentation/coremedia/core-media-type-aliases"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ProjectionKind": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ProjectionKind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ProjectionKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ProjectionKind"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_ProjectionKind",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_projectionkind"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ViewPackingKind": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ViewPackingKind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ViewPackingKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ViewPackingKind"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_ViewPackingKind",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_viewpackingkind"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionLogTransferFunction_AppleLog": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionLogTransferFunction_AppleLog"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionLogTransferFunction_AppleLog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionLogTransferFunction_AppleLog"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionLogTransferFunction_AppleLog",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionlogtransferfunction_applelog"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionProjectionKind_Rectilinear": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionProjectionKind_Rectilinear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionProjectionKind_Rectilinear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionProjectionKind_Rectilinear"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionProjectionKind_Rectilinear",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionprojectionkind_rectilinear"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionViewPackingKind_OverUnder": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionViewPackingKind_OverUnder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionViewPackingKind_OverUnder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionViewPackingKind_OverUnder"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionViewPackingKind_OverUnder",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionviewpackingkind_overunder"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionViewPackingKind_SideBySide": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionViewPackingKind_SideBySide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionViewPackingKind_SideBySide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionViewPackingKind_SideBySide"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionViewPackingKind_SideBySide",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionviewpackingkind_sidebyside"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataType_QuickTimeMetadataMilliLux": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataDataType_QuickTimeMetadataMilliLux"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataType_QuickTimeMetadataMilliLux",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataDataType_QuickTimeMetadataMilliLux"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataDataType_QuickTimeMetadataMilliLux",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatadatatype_quicktimemetadatamillilux"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataType_QuickTimeMetadataUUID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataDataType_QuickTimeMetadataUUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataType_QuickTimeMetadataUUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataDataType_QuickTimeMetadataUUID"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataDataType_QuickTimeMetadataUUID",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatadatatype_quicktimemetadatauuid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataSceneIlluminance": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataSceneIlluminance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataSceneIlluminance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataSceneIlluminance"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifier_QuickTimeMetadataSceneIlluminance",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifier_quicktimemetadatasceneilluminance"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataSegmentIdentifier": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataSegmentIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataSegmentIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataSegmentIdentifier"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifier_QuickTimeMetadataSegmentIdentifier",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifier_quicktimemetadatasegmentidentifier"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HDR10PlusPerFrameData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HDR10PlusPerFrameData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HDR10PlusPerFrameData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HDR10PlusPerFrameData"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_HDR10PlusPerFrameData",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_hdr10plusperframedata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagProjectionTypeHalfEquirectangular": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTagProjectionTypeHalfEquirectangular"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "__CMTag"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagProjectionTypeHalfEquirectangular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTagProjectionTypeHalfEquirectangular"
        }
      ],
      "role": "symbol",
      "title": "kCMTagProjectionTypeHalfEquirectangular",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagprojectiontypehalfequirectangular"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_FontFamilyNameList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_FontFamilyNameList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_FontFamilyNameList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_FontFamilyNameList"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_FontFamilyNameList",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_fontfamilynamelist"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/core-media-functions",
        "doc://com.apple.coremedia/documentation/CoreMedia/core-media-type-aliases"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_BRIDGED_TYPES",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_NULLABILITY",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_NULLABILITY_BEGIN_END",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMITEMCOUNT_MAX",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RELEASES_ARGUMENT",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_FALSE",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_TRUE",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMEBASE_USE_SOURCE_TERMINOLOGY",
        "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ProjectionKind",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ViewPackingKind",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionLogTransferFunction_AppleLog",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionProjectionKind_Rectilinear",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionViewPackingKind_OverUnder",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionViewPackingKind_SideBySide",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataType_QuickTimeMetadataMilliLux",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataType_QuickTimeMetadataUUID",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataSceneIlluminance",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataSegmentIdentifier",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HDR10PlusPerFrameData",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagProjectionTypeHalfEquirectangular",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_FontFamilyNameList"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Type-Aliases",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBaseClassVersion",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMStructVersion"
      ],
      "title": "Type Aliases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_BRIDGED_TYPES",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_NULLABILITY",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_NULLABILITY_BEGIN_END",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMITEMCOUNT_MAX",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RELEASES_ARGUMENT",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_FALSE",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_TRUE",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMEBASE_USE_SOURCE_TERMINOLOGY",
                "doc://com.apple.coremedia/documentation/CoreMedia/COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ProjectionKind",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ViewPackingKind",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionLogTransferFunction_AppleLog",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionProjectionKind_Rectilinear",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionViewPackingKind_OverUnder",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionViewPackingKind_SideBySide",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataType_QuickTimeMetadataMilliLux",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataType_QuickTimeMetadataUUID",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataSceneIlluminance",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataSegmentIdentifier",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HDR10PlusPerFrameData",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagProjectionTypeHalfEquirectangular",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_FontFamilyNameList"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Type-Aliases",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBaseClassVersion",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMStructVersion"
              ],
              "title": "Type Aliases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/core-media-functions",
                "doc://com.apple.coremedia/documentation/CoreMedia/core-media-type-aliases",
                "doc://com.apple.coremedia/documentation/CoreMedia/core-media-macros"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataSegmentIdentifier/title",
          "value": "kCMMetadataIdentifier_QuickTimeMetadataSegmentIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataSegmentIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifier_QuickTimeMetadataSegmentIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionProjectionKind_Rectilinear/title",
          "value": "kCMFormatDescriptionProjectionKind_Rectilinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionProjectionKind_Rectilinear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionProjectionKind_Rectilinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_ProjectionKind/title",
          "value": "kCMFormatDescriptionExtension_ProjectionKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_ProjectionKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_ProjectionKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBaseClassVersion/title",
          "value": "CMBaseClassVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBaseClassVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBaseClassVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBaseClassVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBaseClassVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_TRUE/title",
          "value": "COREMEDIA_TRUE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_TRUE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_TRUE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED/title",
          "value": "COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_RETURNS_RETAINED/title",
          "value": "COREMEDIA_DECLARE_RETURNS_RETAINED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_RETURNS_RETAINED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_DECLARE_RETURNS_RETAINED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION/title",
          "value": "COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTagProjectionTypeHalfEquirectangular/title",
          "value": "kCMTagProjectionTypeHalfEquirectangular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTagProjectionTypeHalfEquirectangular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTagProjectionTypeHalfEquirectangular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_FALSE/title",
          "value": "COREMEDIA_FALSE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_FALSE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_FALSE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS/title",
          "value": "COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_RELEASES_ARGUMENT/title",
          "value": "COREMEDIA_DECLARE_RELEASES_ARGUMENT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_RELEASES_ARGUMENT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_DECLARE_RELEASES_ARGUMENT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTIMEBASE_USE_SOURCE_TERMINOLOGY/title",
          "value": "CMTIMEBASE_USE_SOURCE_TERMINOLOGY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTIMEBASE_USE_SOURCE_TERMINOLOGY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTIMEBASE_USE_SOURCE_TERMINOLOGY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataDataType_QuickTimeMetadataMilliLux/title",
          "value": "kCMMetadataDataType_QuickTimeMetadataMilliLux"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataDataType_QuickTimeMetadataMilliLux/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataDataType_QuickTimeMetadataMilliLux"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_FontFamilyNameList/title",
          "value": "kCMTextMarkupAttribute_FontFamilyNameList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_FontFamilyNameList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_FontFamilyNameList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMITEMCOUNT_MAX/title",
          "value": "CMITEMCOUNT_MAX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMITEMCOUNT_MAX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMITEMCOUNT_MAX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS/title",
          "value": "COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionLogTransferFunction_AppleLog/title",
          "value": "kCMFormatDescriptionLogTransferFunction_AppleLog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionLogTransferFunction_AppleLog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionLogTransferFunction_AppleLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_ViewPackingKind/title",
          "value": "kCMFormatDescriptionExtension_ViewPackingKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_ViewPackingKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_ViewPackingKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_NULLABILITY/title",
          "value": "COREMEDIA_DECLARE_NULLABILITY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_NULLABILITY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_DECLARE_NULLABILITY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS/title",
          "value": "COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataDataType_QuickTimeMetadataUUID/title",
          "value": "kCMMetadataDataType_QuickTimeMetadataUUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataDataType_QuickTimeMetadataUUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataDataType_QuickTimeMetadataUUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataSceneIlluminance/title",
          "value": "kCMMetadataIdentifier_QuickTimeMetadataSceneIlluminance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataSceneIlluminance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifier_QuickTimeMetadataSceneIlluminance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_BRIDGED_TYPES/title",
          "value": "COREMEDIA_DECLARE_BRIDGED_TYPES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_BRIDGED_TYPES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_DECLARE_BRIDGED_TYPES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_NULLABILITY_BEGIN_END/title",
          "value": "COREMEDIA_DECLARE_NULLABILITY_BEGIN_END"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_NULLABILITY_BEGIN_END/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_DECLARE_NULLABILITY_BEGIN_END"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionViewPackingKind_SideBySide/title",
          "value": "kCMFormatDescriptionViewPackingKind_SideBySide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionViewPackingKind_SideBySide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionViewPackingKind_SideBySide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HDR10PlusPerFrameData/title",
          "value": "kCMSampleAttachmentKey_HDR10PlusPerFrameData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HDR10PlusPerFrameData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_HDR10PlusPerFrameData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionViewPackingKind_OverUnder/title",
          "value": "kCMFormatDescriptionViewPackingKind_OverUnder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionViewPackingKind_OverUnder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionViewPackingKind_OverUnder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK/title",
          "value": "COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStructVersion/title",
          "value": "CMStructVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStructVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStructVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMStructVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMStructVersion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/core-media-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/core-media-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
