{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/core-media-functions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core Media Functions"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueCopyHead(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueCopyHead"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferRef",
          "text": "CMBuffer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueCopyHead(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueCopyHead"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueCopyHead(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueuecopyhead(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/core-media-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/core-media-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Media Constants",
      "type": "topic",
      "url": "/documentation/coremedia/core-media-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/core-media-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/core-media-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Media Macros",
      "type": "topic",
      "url": "/documentation/coremedia/core-media-macros"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/core-media-type-aliases": {
      "abstract": [],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/core-media-type-aliases",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Media Type Aliases",
      "type": "topic",
      "url": "/documentation/coremedia/core-media-type-aliases"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/core-media-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/core-media-type-aliases"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueCopyHead(_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueCopyHead(_:)"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/core-media-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/core-media-type-aliases",
                "doc://com.apple.coremedia/documentation/CoreMedia/core-media-macros"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueCopyHead(_:)/title",
          "value": "CMBufferQueueCopyHead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueCopyHead(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueCopyHead"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/core-media-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/core-media-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
