{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/core-media-type-aliases"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core Media Type Aliases"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCompareHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferCompareHandler"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCompareHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferCompareHandler"
        }
      ],
      "role": "symbol",
      "title": "CMBufferCompareHandler",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffercomparehandler"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetBooleanHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferGetBooleanHandler"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetBooleanHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferGetBooleanHandler"
        }
      ],
      "role": "symbol",
      "title": "CMBufferGetBooleanHandler",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffergetbooleanhandler"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetSizeHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferGetSizeHandler"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetSizeHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferGetSizeHandler"
        }
      ],
      "role": "symbol",
      "title": "CMBufferGetSizeHandler",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffergetsizehandler"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetTimeHandler": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferGetTimeHandler"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetTimeHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferGetTimeHandler"
        }
      ],
      "role": "symbol",
      "title": "CMBufferGetTimeHandler",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffergettimehandler"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatDescription": {
      "abstract": [
        {
          "text": "A type for tagged buffer format descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "CMTaggedBufferGroupFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroupformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatType": {
      "abstract": [
        {
          "text": "A type for tagged buffer format information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTaggedBufferGroupFormatType"
        }
      ],
      "role": "symbol",
      "title": "CMTaggedBufferGroupFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmtaggedbuffergroupformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/core-media-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/core-media-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Media Constants",
      "type": "topic",
      "url": "/documentation/coremedia/core-media-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/core-media-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/core-media-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Media Functions",
      "type": "topic",
      "url": "/documentation/coremedia/core-media-functions"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/core-media-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/core-media-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Media Macros",
      "type": "topic",
      "url": "/documentation/coremedia/core-media-macros"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/core-media-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/core-media-functions"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Type-Aliases",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCompareHandler",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetBooleanHandler",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetSizeHandler",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetTimeHandler",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatType"
      ],
      "title": "Type Aliases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Type-Aliases",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferCompareHandler",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetBooleanHandler",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetSizeHandler",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetTimeHandler",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatDescription",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTaggedBufferGroupFormatType"
              ],
              "title": "Type Aliases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/core-media-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/core-media-functions",
                "doc://com.apple.coremedia/documentation/CoreMedia/core-media-macros"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTaggedBufferGroupFormatType/title",
          "value": "CMTaggedBufferGroupFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTaggedBufferGroupFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTaggedBufferGroupFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTaggedBufferGroupFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTaggedBufferGroupFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCompareHandler/title",
          "value": "CMBufferCompareHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCompareHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferCompareHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferCompareHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferCompareHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetTimeHandler/title",
          "value": "CMBufferGetTimeHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetTimeHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetTimeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetTimeHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetTimeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetBooleanHandler/title",
          "value": "CMBufferGetBooleanHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetBooleanHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetBooleanHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetBooleanHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetBooleanHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetSizeHandler/title",
          "value": "CMBufferGetSizeHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetSizeHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetSizeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetSizeHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetSizeHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTaggedBufferGroupFormatDescription/title",
          "value": "CMTaggedBufferGroupFormatDescriptionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTaggedBufferGroupFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTaggedBufferGroupFormatDescriptionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTaggedBufferGroupFormatDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTaggedBufferGroupFormatDescriptionRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/core-media-type-aliases"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/core-media-type-aliases"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
