{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/core-media-macros"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core Media Macros"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatDescriptionGetFormatType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMClosedCaptionFormatDescriptionGetFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatDescriptionGetFormatType",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMClosedCaptionFormatDescriptionGetFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmclosedcaptionformatdescriptiongetformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedFormatDescriptionGetStreamType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMMuxedFormatDescriptionGetStreamType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedFormatDescriptionGetStreamType",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMMuxedFormatDescriptionGetStreamType",
      "type": "topic",
      "url": "/documentation/coremedia/cmmuxedformatdescriptiongetstreamtype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSubtitleFormatDescriptionGetFormatType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMSubtitleFormatDescriptionGetFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSubtitleFormatDescriptionGetFormatType",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMSubtitleFormatDescriptionGetFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmsubtitleformatdescriptiongetformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTAG_IS_INVALID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTAG_IS_INVALID"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTAG_IS_INVALID",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTAG_IS_INVALID",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag_is_invalid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTAG_IS_VALID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTAG_IS_VALID"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTAG_IS_VALID",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTAG_IS_VALID",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag_is_valid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMEMAPPING_IS_EMPTY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTIMEMAPPING_IS_EMPTY"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMEMAPPING_IS_EMPTY",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTIMEMAPPING_IS_EMPTY",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimemapping_is_empty"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMEMAPPING_IS_INVALID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTIMEMAPPING_IS_INVALID"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMEMAPPING_IS_INVALID",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTIMEMAPPING_IS_INVALID",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimemapping_is_invalid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMEMAPPING_IS_VALID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTIMEMAPPING_IS_VALID"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMEMAPPING_IS_VALID",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTIMEMAPPING_IS_VALID",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimemapping_is_valid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatDescriptionGetFormatType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTimeCodeFormatDescriptionGetFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatDescriptionGetFormatType",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTimeCodeFormatDescriptionGetFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimecodeformatdescriptiongetformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoFormatDescriptionGetCodecType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMVideoFormatDescriptionGetCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoFormatDescriptionGetCodecType",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMVideoFormatDescriptionGetCodecType",
      "type": "topic",
      "url": "/documentation/coremedia/cmvideoformatdescriptiongetcodectype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CM_ASSUME_NONNULL_BEGIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CM_ASSUME_NONNULL_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CM_ASSUME_NONNULL_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "CM_ASSUME_NONNULL_BEGIN",
      "type": "topic",
      "url": "/documentation/coremedia/cm_assume_nonnull_begin"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CM_ASSUME_NONNULL_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CM_ASSUME_NONNULL_END"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CM_ASSUME_NONNULL_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "CM_ASSUME_NONNULL_END",
      "type": "topic",
      "url": "/documentation/coremedia/cm_assume_nonnull_end"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CM_BRIDGED_TYPE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CM_BRIDGED_TYPE"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CM_BRIDGED_TYPE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CM_BRIDGED_TYPE",
      "type": "topic",
      "url": "/documentation/coremedia/cm_bridged_type"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CM_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CM_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CM_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "CM_EXPORT",
      "type": "topic",
      "url": "/documentation/coremedia/cm_export"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CM_NONNULL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CM_NONNULL"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CM_NONNULL",
      "kind": "symbol",
      "role": "symbol",
      "title": "CM_NONNULL",
      "type": "topic",
      "url": "/documentation/coremedia/cm_nonnull"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CM_NULLABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CM_NULLABLE"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CM_NULLABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CM_NULLABLE",
      "type": "topic",
      "url": "/documentation/coremedia/cm_nullable"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CM_RELEASES_ARGUMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CM_RELEASES_ARGUMENT"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CM_RELEASES_ARGUMENT",
      "kind": "symbol",
      "role": "symbol",
      "title": "CM_RELEASES_ARGUMENT",
      "type": "topic",
      "url": "/documentation/coremedia/cm_releases_argument"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CM_RETURNS_NOT_RETAINED_PARAMETER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CM_RETURNS_NOT_RETAINED_PARAMETER"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CM_RETURNS_NOT_RETAINED_PARAMETER",
      "kind": "symbol",
      "role": "symbol",
      "title": "CM_RETURNS_NOT_RETAINED_PARAMETER",
      "type": "topic",
      "url": "/documentation/coremedia/cm_returns_not_retained_parameter"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CM_RETURNS_RETAINED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CM_RETURNS_RETAINED"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CM_RETURNS_RETAINED",
      "kind": "symbol",
      "role": "symbol",
      "title": "CM_RETURNS_RETAINED",
      "type": "topic",
      "url": "/documentation/coremedia/cm_returns_retained"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CM_RETURNS_RETAINED_BLOCK": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CM_RETURNS_RETAINED_BLOCK"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CM_RETURNS_RETAINED_BLOCK",
      "kind": "symbol",
      "role": "symbol",
      "title": "CM_RETURNS_RETAINED_BLOCK",
      "type": "topic",
      "url": "/documentation/coremedia/cm_returns_retained_block"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CM_RETURNS_RETAINED_PARAMETER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CM_RETURNS_RETAINED_PARAMETER"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CM_RETURNS_RETAINED_PARAMETER",
      "kind": "symbol",
      "role": "symbol",
      "title": "CM_RETURNS_RETAINED_PARAMETER",
      "type": "topic",
      "url": "/documentation/coremedia/cm_returns_retained_parameter"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/ME_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ME_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/ME_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "ME_EXPORT",
      "type": "topic",
      "url": "/documentation/coremedia/me_export"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/MT_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MT_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/MT_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "MT_EXPORT",
      "type": "topic",
      "url": "/documentation/coremedia/mt_export"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/VT_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "VT_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/VT_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "VT_EXPORT",
      "type": "topic",
      "url": "/documentation/coremedia/vt_export"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/core-media-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/core-media-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Media Constants",
      "type": "topic",
      "url": "/documentation/coremedia/core-media-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/core-media-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/core-media-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Media Functions",
      "type": "topic",
      "url": "/documentation/coremedia/core-media-functions"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/core-media-type-aliases": {
      "abstract": [],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/core-media-type-aliases",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Media Type Aliases",
      "type": "topic",
      "url": "/documentation/coremedia/core-media-type-aliases"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Bottom-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionChromaLocation_Bottom"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Bottom-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionChromaLocation_Bottom",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionchromalocation_bottom-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_BottomLeft-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionChromaLocation_BottomLeft"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_BottomLeft-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionChromaLocation_BottomLeft",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionchromalocation_bottomleft-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Center-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionChromaLocation_Center"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Center-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionChromaLocation_Center",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionchromalocation_center-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_DV420-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionChromaLocation_DV420"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_DV420-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionChromaLocation_DV420",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionchromalocation_dv420-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Left-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionChromaLocation_Left"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Left-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionChromaLocation_Left",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionchromalocation_left-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Top-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionChromaLocation_Top"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Top-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionChromaLocation_Top",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionchromalocation_top-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_TopLeft-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionChromaLocation_TopLeft"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_TopLeft-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionChromaLocation_TopLeft",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionchromalocation_topleft-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionColorPrimaries_EBU_3213-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionColorPrimaries_EBU_3213"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionColorPrimaries_EBU_3213-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionColorPrimaries_EBU_3213",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptioncolorprimaries_ebu_3213-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionColorPrimaries_ITU_R_709_2-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionColorPrimaries_ITU_R_709_2"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionColorPrimaries_ITU_R_709_2-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionColorPrimaries_ITU_R_709_2",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptioncolorprimaries_itu_r_709_2-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionColorPrimaries_SMPTE_C-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionColorPrimaries_SMPTE_C"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionColorPrimaries_SMPTE_C-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionColorPrimaries_SMPTE_C",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptioncolorprimaries_smpte_c-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ChromaLocationBottomField-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ChromaLocationBottomField"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ChromaLocationBottomField-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_ChromaLocationBottomField",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_chromalocationbottomfield-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ChromaLocationTopField-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ChromaLocationTopField"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ChromaLocationTopField-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_ChromaLocationTopField",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_chromalocationtopfield-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_CleanAperture-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_CleanAperture"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_CleanAperture-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_CleanAperture",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_cleanaperture-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ColorPrimaries-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ColorPrimaries"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ColorPrimaries-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_ColorPrimaries",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_colorprimaries-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FieldCount-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_FieldCount"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FieldCount-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_FieldCount",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_fieldcount-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FieldDetail-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_FieldDetail"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FieldDetail-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_FieldDetail",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_fielddetail-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_GammaLevel-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_GammaLevel"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_GammaLevel-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_GammaLevel",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_gammalevel-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_PixelAspectRatio-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_PixelAspectRatio"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_PixelAspectRatio-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_PixelAspectRatio",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_pixelaspectratio-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_TransferFunction-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_TransferFunction"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_TransferFunction-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_TransferFunction",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_transferfunction-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_VerbatimImageDescription-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_VerbatimImageDescription"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_VerbatimImageDescription-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_VerbatimImageDescription",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_verbatimimagedescription-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_YCbCrMatrix-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_YCbCrMatrix"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_YCbCrMatrix-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_YCbCrMatrix",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_ycbcrmatrix-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionFieldDetail_SpatialFirstLineEarly-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionFieldDetail_SpatialFirstLineEarly"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionFieldDetail_SpatialFirstLineEarly-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionFieldDetail_SpatialFirstLineEarly",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionfielddetail_spatialfirstlineearly-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionFieldDetail_SpatialFirstLineLate-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionFieldDetail_SpatialFirstLineLate"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionFieldDetail_SpatialFirstLineLate-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionFieldDetail_SpatialFirstLineLate",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionfielddetail_spatialfirstlinelate-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionFieldDetail_TemporalBottomFirst-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionFieldDetail_TemporalBottomFirst"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionFieldDetail_TemporalBottomFirst-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionFieldDetail_TemporalBottomFirst",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionfielddetail_temporalbottomfirst-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionFieldDetail_TemporalTopFirst-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionFieldDetail_TemporalTopFirst"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionFieldDetail_TemporalTopFirst-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionFieldDetail_TemporalTopFirst",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionfielddetail_temporaltopfirst-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionKey_CleanApertureHeight-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionKey_CleanApertureHeight"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionKey_CleanApertureHeight-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionKey_CleanApertureHeight",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionkey_cleanapertureheight-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionKey_CleanApertureHorizontalOffset-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionKey_CleanApertureHorizontalOffset"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionKey_CleanApertureHorizontalOffset-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionKey_CleanApertureHorizontalOffset",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionkey_cleanaperturehorizontaloffset-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionKey_CleanApertureVerticalOffset-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionKey_CleanApertureVerticalOffset"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionKey_CleanApertureVerticalOffset-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionKey_CleanApertureVerticalOffset",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionkey_cleanapertureverticaloffset-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionKey_CleanApertureWidth-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionKey_CleanApertureWidth"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionKey_CleanApertureWidth-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionKey_CleanApertureWidth",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionkey_cleanaperturewidth-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionKey_PixelAspectRatioHorizontalSpacing-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionKey_PixelAspectRatioHorizontalSpacing"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionKey_PixelAspectRatioHorizontalSpacing-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionKey_PixelAspectRatioHorizontalSpacing",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionkey_pixelaspectratiohorizontalspacing-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionKey_PixelAspectRatioVerticalSpacing-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionKey_PixelAspectRatioVerticalSpacing"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionKey_PixelAspectRatioVerticalSpacing-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionKey_PixelAspectRatioVerticalSpacing",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionkey_pixelaspectratioverticalspacing-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_ITU_R_709_2-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionTransferFunction_ITU_R_709_2"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_ITU_R_709_2-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionTransferFunction_ITU_R_709_2",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptiontransferfunction_itu_r_709_2-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_SMPTE_240M_1995-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionTransferFunction_SMPTE_240M_1995"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_SMPTE_240M_1995-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionTransferFunction_SMPTE_240M_1995",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptiontransferfunction_smpte_240m_1995-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_UseGamma-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionTransferFunction_UseGamma"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_UseGamma-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionTransferFunction_UseGamma",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptiontransferfunction_usegamma-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionYCbCrMatrix_ITU_R_601_4-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionYCbCrMatrix_ITU_R_601_4"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionYCbCrMatrix_ITU_R_601_4-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionYCbCrMatrix_ITU_R_601_4",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionycbcrmatrix_itu_r_601_4-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionYCbCrMatrix_ITU_R_709_2-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionYCbCrMatrix_ITU_R_709_2"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionYCbCrMatrix_ITU_R_709_2-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionYCbCrMatrix_ITU_R_709_2",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionycbcrmatrix_itu_r_709_2-c.macro"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionYCbCrMatrix_SMPTE_240M_1995-c.macro": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionYCbCrMatrix_SMPTE_240M_1995"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionYCbCrMatrix_SMPTE_240M_1995-c.macro",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMFormatDescriptionYCbCrMatrix_SMPTE_240M_1995",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionycbcrmatrix_smpte_240m_1995-c.macro"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatDescriptionGetFormatType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedFormatDescriptionGetStreamType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMSubtitleFormatDescriptionGetFormatType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTAG_IS_INVALID",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTAG_IS_VALID",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMEMAPPING_IS_EMPTY",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMEMAPPING_IS_INVALID",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTIMEMAPPING_IS_VALID",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatDescriptionGetFormatType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoFormatDescriptionGetCodecType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CM_ASSUME_NONNULL_BEGIN",
                "doc://com.apple.coremedia/documentation/CoreMedia/CM_ASSUME_NONNULL_END",
                "doc://com.apple.coremedia/documentation/CoreMedia/CM_BRIDGED_TYPE",
                "doc://com.apple.coremedia/documentation/CoreMedia/CM_EXPORT",
                "doc://com.apple.coremedia/documentation/CoreMedia/CM_NONNULL",
                "doc://com.apple.coremedia/documentation/CoreMedia/CM_NULLABLE",
                "doc://com.apple.coremedia/documentation/CoreMedia/CM_RELEASES_ARGUMENT",
                "doc://com.apple.coremedia/documentation/CoreMedia/CM_RETURNS_NOT_RETAINED_PARAMETER",
                "doc://com.apple.coremedia/documentation/CoreMedia/CM_RETURNS_RETAINED",
                "doc://com.apple.coremedia/documentation/CoreMedia/CM_RETURNS_RETAINED_BLOCK",
                "doc://com.apple.coremedia/documentation/CoreMedia/CM_RETURNS_RETAINED_PARAMETER",
                "doc://com.apple.coremedia/documentation/CoreMedia/ME_EXPORT",
                "doc://com.apple.coremedia/documentation/CoreMedia/MT_EXPORT",
                "doc://com.apple.coremedia/documentation/CoreMedia/VT_EXPORT",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Bottom-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_BottomLeft-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Center-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_DV420-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Left-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_Top-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionChromaLocation_TopLeft-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionColorPrimaries_EBU_3213-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionColorPrimaries_ITU_R_709_2-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionColorPrimaries_SMPTE_C-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ChromaLocationBottomField-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ChromaLocationTopField-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_CleanAperture-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ColorPrimaries-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FieldCount-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FieldDetail-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_GammaLevel-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_PixelAspectRatio-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_TransferFunction-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_VerbatimImageDescription-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_YCbCrMatrix-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionFieldDetail_SpatialFirstLineEarly-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionFieldDetail_SpatialFirstLineLate-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionFieldDetail_TemporalBottomFirst-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionFieldDetail_TemporalTopFirst-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionKey_CleanApertureHeight-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionKey_CleanApertureHorizontalOffset-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionKey_CleanApertureVerticalOffset-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionKey_CleanApertureWidth-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionKey_PixelAspectRatioHorizontalSpacing-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionKey_PixelAspectRatioVerticalSpacing-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_ITU_R_709_2-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_SMPTE_240M_1995-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_UseGamma-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionYCbCrMatrix_ITU_R_601_4-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionYCbCrMatrix_ITU_R_709_2-c.macro",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionYCbCrMatrix_SMPTE_240M_1995-c.macro"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/core-media-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/core-media-functions",
                "doc://com.apple.coremedia/documentation/CoreMedia/core-media-type-aliases"
              ],
              "title": "Reference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/core-media-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/core-media-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
