{
  "abstract": [
    {
      "text": "Constants that identify format descriptions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Format Description Constants"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/audio-format-desc-codes": {
      "abstract": [
        {
          "text": "Mask codes that identify audio formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/audio-format-desc-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Format Description Mask Codes",
      "type": "topic",
      "url": "/documentation/coremedia/audio-format-desc-codes"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify chroma location extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Chroma Location Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/chroma-location-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify clean aperture extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Clean Aperture Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/clean-aperture-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api": {
      "abstract": [
        {
          "text": "A media format descriptor that describes the samples in a sample buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMFormatDescription APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify color primary extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color Primary Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/color-primary-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify field detail extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Field Detail Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/field-detail-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors": {
      "abstract": [
        {
          "text": "Bridge errors the system returns from format description calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Bridge Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-bridge-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors": {
      "abstract": [
        {
          "text": "Errors the system returns from format description calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants": {
      "abstract": [
        {
          "text": "Constants that identify HEVC temporal level information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HEVC Temporal Level Info Constants",
      "type": "topic",
      "url": "/documentation/coremedia/hevc-temporal-level-info-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionalphachannelmode_premultipliedalpha"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionAlphaChannelMode_StraightAlpha": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionAlphaChannelMode_StraightAlpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionAlphaChannelMode_StraightAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionAlphaChannelMode_StraightAlpha"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionAlphaChannelMode_StraightAlpha",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionalphachannelmode_straightalpha"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtensionKey_MetadataKeyTable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtensionKey_MetadataKeyTable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtensionKey_MetadataKeyTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtensionKey_MetadataKeyTable"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtensionKey_MetadataKeyTable",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextensionkey_metadatakeytable"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_AlphaChannelMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_AlphaChannelMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_AlphaChannelMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_AlphaChannelMode"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_AlphaChannelMode",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_alphachannelmode"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_AlternativeTransferCharacteristics": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_AlternativeTransferCharacteristics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_AlternativeTransferCharacteristics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_AlternativeTransferCharacteristics"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_AlternativeTransferCharacteristics",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_alternativetransfercharacteristics"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_AmbientViewingEnvironment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_AmbientViewingEnvironment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_AmbientViewingEnvironment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_AmbientViewingEnvironment"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_AmbientViewingEnvironment",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_ambientviewingenvironment"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_AuxiliaryTypeInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_AuxiliaryTypeInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_AuxiliaryTypeInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_AuxiliaryTypeInfo"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_AuxiliaryTypeInfo",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_auxiliarytypeinfo"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_BitsPerComponent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_BitsPerComponent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_BitsPerComponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_BitsPerComponent"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_BitsPerComponent",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_bitspercomponent"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_BytesPerRow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_BytesPerRow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_BytesPerRow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_BytesPerRow"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_BytesPerRow",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_bytesperrow"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ChromaLocationBottomField-swift.var": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ChromaLocationBottomField"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ChromaLocationBottomField-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ChromaLocationBottomField"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_ChromaLocationBottomField",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_chromalocationbottomfield-swift.var"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ChromaLocationTopField-swift.var": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ChromaLocationTopField"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ChromaLocationTopField-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ChromaLocationTopField"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_ChromaLocationTopField",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_chromalocationtopfield-swift.var"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_CleanAperture-swift.var": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_CleanAperture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_CleanAperture-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_CleanAperture"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_CleanAperture",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_cleanaperture-swift.var"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ColorPrimaries-swift.var": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ColorPrimaries"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ColorPrimaries-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ColorPrimaries"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_ColorPrimaries",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_colorprimaries-swift.var"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ContainsAlphaChannel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ContainsAlphaChannel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ContainsAlphaChannel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ContainsAlphaChannel"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_ContainsAlphaChannel",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_containsalphachannel"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ContentLightLevelInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ContentLightLevelInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ContentLightLevelInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ContentLightLevelInfo"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_ContentLightLevelInfo",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_contentlightlevelinfo"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_Depth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_Depth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_Depth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_Depth"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_Depth",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_depth"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FieldCount-swift.var": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_FieldCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FieldCount-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_FieldCount"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_FieldCount",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_fieldcount-swift.var"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FieldDetail-swift.var": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_FieldDetail"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FieldDetail-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_FieldDetail"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_FieldDetail",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_fielddetail-swift.var"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FormatName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_FormatName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FormatName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_FormatName"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_FormatName",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_formatname"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FullRangeVideo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_FullRangeVideo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FullRangeVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_FullRangeVideo"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_FullRangeVideo",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_fullrangevideo"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_GammaLevel-swift.var": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_GammaLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_GammaLevel-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_GammaLevel"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_GammaLevel",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_gammalevel-swift.var"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_HorizontalFieldOfView": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_HorizontalFieldOfView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_HorizontalFieldOfView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_HorizontalFieldOfView"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_HorizontalFieldOfView",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_horizontalfieldofview"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ICCProfile": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ICCProfile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ICCProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ICCProfile"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_ICCProfile",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_iccprofile"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_MasteringDisplayColorVolume": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_MasteringDisplayColorVolume"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_MasteringDisplayColorVolume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_MasteringDisplayColorVolume"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_MasteringDisplayColorVolume",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_masteringdisplaycolorvolume"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_OriginalCompressionSettings": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_OriginalCompressionSettings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_OriginalCompressionSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_OriginalCompressionSettings"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_OriginalCompressionSettings",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_originalcompressionsettings"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_PixelAspectRatio-swift.var": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_PixelAspectRatio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_PixelAspectRatio-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_PixelAspectRatio"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_PixelAspectRatio",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_pixelaspectratio-swift.var"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ProtectedContentOriginalFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ProtectedContentOriginalFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ProtectedContentOriginalFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_ProtectedContentOriginalFormat"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_ProtectedContentOriginalFormat",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_protectedcontentoriginalformat"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_SampleDescriptionExtensionAtoms": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_SampleDescriptionExtensionAtoms"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_SampleDescriptionExtensionAtoms",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_SampleDescriptionExtensionAtoms"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_SampleDescriptionExtensionAtoms",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_sampledescriptionextensionatoms"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_TransferFunction-swift.var": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_TransferFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_TransferFunction-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_TransferFunction"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_TransferFunction",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_transferfunction-swift.var"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_VerbatimISOSampleEntry": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_VerbatimISOSampleEntry"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_VerbatimISOSampleEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_VerbatimISOSampleEntry"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_VerbatimISOSampleEntry",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_verbatimisosampleentry"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_VerbatimImageDescription-swift.var": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_VerbatimImageDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_VerbatimImageDescription-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_VerbatimImageDescription"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_VerbatimImageDescription",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_verbatimimagedescription-swift.var"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_VerbatimSampleDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_VerbatimSampleDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_VerbatimSampleDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_VerbatimSampleDescription"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_VerbatimSampleDescription",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_verbatimsampledescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_YCbCrMatrix-swift.var": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_YCbCrMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_YCbCrMatrix-swift.var",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_YCbCrMatrix"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_YCbCrMatrix",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_ycbcrmatrix-swift.var"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptiontransferfunction_itu_r_2100_hlg"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_Linear": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionTransferFunction_Linear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_Linear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionTransferFunction_Linear"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionTransferFunction_Linear",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptiontransferfunction_linear"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptiontransferfunction_smpte_st_2084_pq"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_sRGB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionTransferFunction_sRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_sRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionTransferFunction_sRGB"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionTransferFunction_sRGB",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptiontransferfunction_srgb"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify metadata format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats": {
      "abstract": [
        {
          "text": "Constants that identify MPEG-2 formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MPEG-2-conformant Formats",
      "type": "topic",
      "url": "/documentation/coremedia/mpeg-2-conformant-formats"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify pixel aspect ratio extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pixel Aspect Ratio Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/pixel-aspect-ratio-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify text format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/text-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify time code format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Time Code Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/time-code-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify transfer function extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Transfer Function Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/transfer-function-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify YCbCrMatrix extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "YCbCrMatrix Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/ycbcrmatrix-extension-constants"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
        "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/audio-format-desc-codes"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Description-Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionAlphaChannelMode_StraightAlpha",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_Linear",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_sRGB"
      ],
      "title": "Description Constants"
    },
    {
      "anchor": "Description-Extension-Keys",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtensionKey_MetadataKeyTable"
      ],
      "title": "Description Extension Keys"
    },
    {
      "anchor": "Description-Extension-Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_AlphaChannelMode",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_AlternativeTransferCharacteristics",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_AmbientViewingEnvironment",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_AuxiliaryTypeInfo",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_BitsPerComponent",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_BytesPerRow",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ChromaLocationBottomField-swift.var",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ChromaLocationTopField-swift.var",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_CleanAperture-swift.var",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ColorPrimaries-swift.var",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ContainsAlphaChannel",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ContentLightLevelInfo",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_Depth",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FieldCount-swift.var",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FieldDetail-swift.var",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FormatName",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FullRangeVideo",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_GammaLevel-swift.var",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_HorizontalFieldOfView",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ICCProfile",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_MasteringDisplayColorVolume",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_OriginalCompressionSettings",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_PixelAspectRatio-swift.var",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ProtectedContentOriginalFormat",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_SampleDescriptionExtensionAtoms",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_TransferFunction-swift.var",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_VerbatimISOSampleEntry",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_VerbatimImageDescription-swift.var",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_VerbatimSampleDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_YCbCrMatrix-swift.var"
      ],
      "title": "Description Extension Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Description-Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionAlphaChannelMode_StraightAlpha",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_Linear",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_sRGB"
              ],
              "title": "Description Constants"
            },
            {
              "anchor": "Description-Extension-Keys",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtensionKey_MetadataKeyTable"
              ],
              "title": "Description Extension Keys"
            },
            {
              "anchor": "Description-Extension-Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_AlphaChannelMode",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_AlternativeTransferCharacteristics",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_AmbientViewingEnvironment",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_AuxiliaryTypeInfo",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_BitsPerComponent",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_BytesPerRow",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ChromaLocationBottomField-swift.var",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ChromaLocationTopField-swift.var",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_CleanAperture-swift.var",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ColorPrimaries-swift.var",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ContainsAlphaChannel",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ContentLightLevelInfo",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_Depth",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FieldCount-swift.var",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FieldDetail-swift.var",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FormatName",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_FullRangeVideo",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_GammaLevel-swift.var",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_HorizontalFieldOfView",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ICCProfile",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_MasteringDisplayColorVolume",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_OriginalCompressionSettings",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_PixelAspectRatio-swift.var",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_ProtectedContentOriginalFormat",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_SampleDescriptionExtensionAtoms",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_TransferFunction-swift.var",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_VerbatimISOSampleEntry",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_VerbatimImageDescription-swift.var",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_VerbatimSampleDescription",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_YCbCrMatrix-swift.var"
              ],
              "title": "Description Extension Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
                "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/audio-format-desc-codes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_CleanAperture-swift.var/title",
          "value": "kCMFormatDescriptionExtension_CleanAperture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_CleanAperture-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_CleanAperture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_AmbientViewingEnvironment/title",
          "value": "kCMFormatDescriptionExtension_AmbientViewingEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_AmbientViewingEnvironment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_AmbientViewingEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_FormatName/title",
          "value": "kCMFormatDescriptionExtension_FormatName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_FormatName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_FormatName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG/title",
          "value": "kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_BytesPerRow/title",
          "value": "kCMFormatDescriptionExtension_BytesPerRow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_BytesPerRow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_BytesPerRow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_SampleDescriptionExtensionAtoms/title",
          "value": "kCMFormatDescriptionExtension_SampleDescriptionExtensionAtoms"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_SampleDescriptionExtensionAtoms/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_SampleDescriptionExtensionAtoms"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_ContainsAlphaChannel/title",
          "value": "kCMFormatDescriptionExtension_ContainsAlphaChannel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_ContainsAlphaChannel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_ContainsAlphaChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtensionKey_MetadataKeyTable/title",
          "value": "kCMFormatDescriptionExtensionKey_MetadataKeyTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtensionKey_MetadataKeyTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtensionKey_MetadataKeyTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_FieldCount-swift.var/title",
          "value": "kCMFormatDescriptionExtension_FieldCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_FieldCount-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_FieldCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_Depth/title",
          "value": "kCMFormatDescriptionExtension_Depth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_Depth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_Depth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_HorizontalFieldOfView/title",
          "value": "kCMFormatDescriptionExtension_HorizontalFieldOfView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_HorizontalFieldOfView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_HorizontalFieldOfView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionTransferFunction_sRGB/title",
          "value": "kCMFormatDescriptionTransferFunction_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionTransferFunction_sRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionTransferFunction_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_ContentLightLevelInfo/title",
          "value": "kCMFormatDescriptionExtension_ContentLightLevelInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_ContentLightLevelInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_ContentLightLevelInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_FieldDetail-swift.var/title",
          "value": "kCMFormatDescriptionExtension_FieldDetail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_FieldDetail-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_FieldDetail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_VerbatimSampleDescription/title",
          "value": "kCMFormatDescriptionExtension_VerbatimSampleDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_VerbatimSampleDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_VerbatimSampleDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_BitsPerComponent/title",
          "value": "kCMFormatDescriptionExtension_BitsPerComponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_BitsPerComponent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_BitsPerComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_VerbatimISOSampleEntry/title",
          "value": "kCMFormatDescriptionExtension_VerbatimISOSampleEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_VerbatimISOSampleEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_VerbatimISOSampleEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_OriginalCompressionSettings/title",
          "value": "kCMFormatDescriptionExtension_OriginalCompressionSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_OriginalCompressionSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_OriginalCompressionSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_ChromaLocationBottomField-swift.var/title",
          "value": "kCMFormatDescriptionExtension_ChromaLocationBottomField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_ChromaLocationBottomField-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_ChromaLocationBottomField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionAlphaChannelMode_StraightAlpha/title",
          "value": "kCMFormatDescriptionAlphaChannelMode_StraightAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionAlphaChannelMode_StraightAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionAlphaChannelMode_StraightAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_ChromaLocationTopField-swift.var/title",
          "value": "kCMFormatDescriptionExtension_ChromaLocationTopField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_ChromaLocationTopField-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_ChromaLocationTopField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha/title",
          "value": "kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_ProtectedContentOriginalFormat/title",
          "value": "kCMFormatDescriptionExtension_ProtectedContentOriginalFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_ProtectedContentOriginalFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_ProtectedContentOriginalFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_ColorPrimaries-swift.var/title",
          "value": "kCMFormatDescriptionExtension_ColorPrimaries"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_ColorPrimaries-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_ColorPrimaries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_TransferFunction-swift.var/title",
          "value": "kCMFormatDescriptionExtension_TransferFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_TransferFunction-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_TransferFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_GammaLevel-swift.var/title",
          "value": "kCMFormatDescriptionExtension_GammaLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_GammaLevel-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_GammaLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_VerbatimImageDescription-swift.var/title",
          "value": "kCMFormatDescriptionExtension_VerbatimImageDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_VerbatimImageDescription-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_VerbatimImageDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionTransferFunction_Linear/title",
          "value": "kCMFormatDescriptionTransferFunction_Linear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionTransferFunction_Linear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionTransferFunction_Linear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_AuxiliaryTypeInfo/title",
          "value": "kCMFormatDescriptionExtension_AuxiliaryTypeInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_AuxiliaryTypeInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_AuxiliaryTypeInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_FullRangeVideo/title",
          "value": "kCMFormatDescriptionExtension_FullRangeVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_FullRangeVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_FullRangeVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_AlternativeTransferCharacteristics/title",
          "value": "kCMFormatDescriptionExtension_AlternativeTransferCharacteristics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_AlternativeTransferCharacteristics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_AlternativeTransferCharacteristics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ/title",
          "value": "kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_MasteringDisplayColorVolume/title",
          "value": "kCMFormatDescriptionExtension_MasteringDisplayColorVolume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_MasteringDisplayColorVolume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_MasteringDisplayColorVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_PixelAspectRatio-swift.var/title",
          "value": "kCMFormatDescriptionExtension_PixelAspectRatio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_PixelAspectRatio-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_PixelAspectRatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_YCbCrMatrix-swift.var/title",
          "value": "kCMFormatDescriptionExtension_YCbCrMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_YCbCrMatrix-swift.var/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_YCbCrMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_ICCProfile/title",
          "value": "kCMFormatDescriptionExtension_ICCProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_ICCProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_ICCProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_AlphaChannelMode/title",
          "value": "kCMFormatDescriptionExtension_AlphaChannelMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_AlphaChannelMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_AlphaChannelMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/format-description-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/format-description-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
