{
  "abstract": [
    {
      "text": "A mask that represents the audio stream description.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMAudioFormatDescriptionMask_StreamBasicDescription"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMAudioFormatDescriptionMask_StreamBasicDescription@kCMAudioFormatDescriptionMask_StreamBasicDescription",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMAudioFormatDescriptionMask_StreamBasicDescription"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMAudioFormatDescriptionMask",
        "text": "CMAudioFormatDescriptionMask"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMAudioFormatDescriptionMask_StreamBasicDescription"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMAudioFormatDescriptionMask_StreamBasicDescription"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMAudioFormatDescriptionMask_StreamBasicDescription"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescriptionMask",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMAudioFormatDescriptionMask",
              "text": "CMAudioFormatDescriptionMask"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescriptionMask": {
      "abstract": [
        {
          "text": "A type for mask bits that represent parts of an audio format description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMAudioFormatDescriptionMask"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescriptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMAudioFormatDescriptionMask"
        }
      ],
      "role": "symbol",
      "title": "CMAudioFormatDescriptionMask",
      "type": "topic",
      "url": "/documentation/coremedia/cmaudioformatdescriptionmask"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMAudioFormatDescriptionMask_All": {
      "abstract": [
        {
          "text": "A mask that represents all parts of an audio format description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMAudioFormatDescriptionMask_All"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAudioFormatDescriptionMask",
          "text": "CMAudioFormatDescriptionMask"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMAudioFormatDescriptionMask_All",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMAudioFormatDescriptionMask_All"
        }
      ],
      "role": "symbol",
      "title": "kCMAudioFormatDescriptionMask_All",
      "type": "topic",
      "url": "/documentation/coremedia/kcmaudioformatdescriptionmask_all"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMAudioFormatDescriptionMask_ChannelLayout": {
      "abstract": [
        {
          "text": "A mask that represents the audio channel layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMAudioFormatDescriptionMask_ChannelLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAudioFormatDescriptionMask",
          "text": "CMAudioFormatDescriptionMask"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMAudioFormatDescriptionMask_ChannelLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMAudioFormatDescriptionMask_ChannelLayout"
        }
      ],
      "role": "symbol",
      "title": "kCMAudioFormatDescriptionMask_ChannelLayout",
      "type": "topic",
      "url": "/documentation/coremedia/kcmaudioformatdescriptionmask_channellayout"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMAudioFormatDescriptionMask_Extensions": {
      "abstract": [
        {
          "text": "A mask that represents the format description extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMAudioFormatDescriptionMask_Extensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAudioFormatDescriptionMask",
          "text": "CMAudioFormatDescriptionMask"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMAudioFormatDescriptionMask_Extensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMAudioFormatDescriptionMask_Extensions"
        }
      ],
      "role": "symbol",
      "title": "kCMAudioFormatDescriptionMask_Extensions",
      "type": "topic",
      "url": "/documentation/coremedia/kcmaudioformatdescriptionmask_extensions"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMAudioFormatDescriptionMask_MagicCookie": {
      "abstract": [
        {
          "text": "A mask that represents the magic cookie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMAudioFormatDescriptionMask_MagicCookie"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAudioFormatDescriptionMask",
          "text": "CMAudioFormatDescriptionMask"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMAudioFormatDescriptionMask_MagicCookie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMAudioFormatDescriptionMask_MagicCookie"
        }
      ],
      "role": "symbol",
      "title": "kCMAudioFormatDescriptionMask_MagicCookie",
      "type": "topic",
      "url": "/documentation/coremedia/kcmaudioformatdescriptionmask_magiccookie"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMAudioFormatDescriptionMask_StreamBasicDescription": {
      "abstract": [
        {
          "text": "A mask that represents the audio stream description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMAudioFormatDescriptionMask_StreamBasicDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAudioFormatDescriptionMask",
          "text": "CMAudioFormatDescriptionMask"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMAudioFormatDescriptionMask_StreamBasicDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMAudioFormatDescriptionMask_StreamBasicDescription"
        }
      ],
      "role": "symbol",
      "title": "kCMAudioFormatDescriptionMask_StreamBasicDescription",
      "type": "topic",
      "url": "/documentation/coremedia/kcmaudioformatdescriptionmask_streambasicdescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMAudioFormatDescriptionMask_All",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMAudioFormatDescriptionMask_ChannelLayout",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMAudioFormatDescriptionMask_Extensions",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMAudioFormatDescriptionMask_MagicCookie"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMAudioFormatDescriptionMask_StreamBasicDescription"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMAudioFormatDescriptionMask_StreamBasicDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMAudioFormatDescriptionMask_All",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMAudioFormatDescriptionMask_ChannelLayout",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMAudioFormatDescriptionMask_Extensions",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMAudioFormatDescriptionMask_MagicCookie"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMAudioFormatDescriptionMask_StreamBasicDescription"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMAudioFormatDescriptionMask_All/title",
          "value": "kCMAudioFormatDescriptionMask_All"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMAudioFormatDescriptionMask_All/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMAudioFormatDescriptionMask_All"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMAudioFormatDescriptionMask_MagicCookie/title",
          "value": "kCMAudioFormatDescriptionMask_MagicCookie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMAudioFormatDescriptionMask_MagicCookie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMAudioFormatDescriptionMask_MagicCookie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMAudioFormatDescriptionMask_StreamBasicDescription/title",
          "value": "kCMAudioFormatDescriptionMask_StreamBasicDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMAudioFormatDescriptionMask_StreamBasicDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMAudioFormatDescriptionMask_StreamBasicDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioFormatDescriptionMask/title",
          "value": "CMAudioFormatDescriptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioFormatDescriptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioFormatDescriptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioFormatDescriptionMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioFormatDescriptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMAudioFormatDescriptionMask_ChannelLayout/title",
          "value": "kCMAudioFormatDescriptionMask_ChannelLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMAudioFormatDescriptionMask_ChannelLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMAudioFormatDescriptionMask_ChannelLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMAudioFormatDescriptionMask_Extensions/title",
          "value": "kCMAudioFormatDescriptionMask_Extensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMAudioFormatDescriptionMask_Extensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMAudioFormatDescriptionMask_Extensions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmaudioformatdescriptionmask_streambasicdescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmaudioformatdescriptionmask_streambasicdescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
