{
  "abstract": [
    {
      "text": "A code that indicates the system successfully created a block buffer with no errors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferNoErr"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMBlockBufferNoErr@kCMBlockBufferNoErr",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMBlockBufferNoErr"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMBlockBufferNoErr"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMBlockBufferNoErr"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMBlockBufferNoErr"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferBadCustomBlockSourceErr": {
      "abstract": [
        {
          "text": "An error code that indicates the custom block source is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBlockBufferBadCustomBlockSourceErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferBadCustomBlockSourceErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBlockBufferBadCustomBlockSourceErr"
        }
      ],
      "role": "symbol",
      "title": "kCMBlockBufferBadCustomBlockSourceErr",
      "type": "topic",
      "url": "/documentation/coremedia/kcmblockbufferbadcustomblocksourceerr"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferBadLengthParameterErr": {
      "abstract": [
        {
          "text": "An error code that indicates the block length is zero or doesn’t equal the size of the memory block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBlockBufferBadLengthParameterErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferBadLengthParameterErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBlockBufferBadLengthParameterErr"
        }
      ],
      "role": "symbol",
      "title": "kCMBlockBufferBadLengthParameterErr",
      "type": "topic",
      "url": "/documentation/coremedia/kcmblockbufferbadlengthparametererr"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferBadOffsetParameterErr": {
      "abstract": [
        {
          "text": "An error code that indicates the offset doesn’t point to the location of data in the memory block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBlockBufferBadOffsetParameterErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferBadOffsetParameterErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBlockBufferBadOffsetParameterErr"
        }
      ],
      "role": "symbol",
      "title": "kCMBlockBufferBadOffsetParameterErr",
      "type": "topic",
      "url": "/documentation/coremedia/kcmblockbufferbadoffsetparametererr"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferBadPointerParameterErr": {
      "abstract": [
        {
          "text": "An error code that indicates the block buffer reference is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBlockBufferBadPointerParameterErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferBadPointerParameterErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBlockBufferBadPointerParameterErr"
        }
      ],
      "role": "symbol",
      "title": "kCMBlockBufferBadPointerParameterErr",
      "type": "topic",
      "url": "/documentation/coremedia/kcmblockbufferbadpointerparametererr"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferBlockAllocationFailedErr": {
      "abstract": [
        {
          "text": "An error code that indicates the block allocator failed to allocate a memory block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBlockBufferBlockAllocationFailedErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferBlockAllocationFailedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBlockBufferBlockAllocationFailedErr"
        }
      ],
      "role": "symbol",
      "title": "kCMBlockBufferBlockAllocationFailedErr",
      "type": "topic",
      "url": "/documentation/coremedia/kcmblockbufferblockallocationfailederr"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferEmptyBBufErr": {
      "abstract": [
        {
          "text": "An error code that indicates the block buffer is empty.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBlockBufferEmptyBBufErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferEmptyBBufErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBlockBufferEmptyBBufErr"
        }
      ],
      "role": "symbol",
      "title": "kCMBlockBufferEmptyBBufErr",
      "type": "topic",
      "url": "/documentation/coremedia/kcmblockbufferemptybbuferr"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferInsufficientSpaceErr": {
      "abstract": [
        {
          "text": "An error code that indicates the system failed to create a new buffer because of insufficient space at the buffer out location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBlockBufferInsufficientSpaceErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferInsufficientSpaceErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBlockBufferInsufficientSpaceErr"
        }
      ],
      "role": "symbol",
      "title": "kCMBlockBufferInsufficientSpaceErr",
      "type": "topic",
      "url": "/documentation/coremedia/kcmblockbufferinsufficientspaceerr"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferNoErr": {
      "abstract": [
        {
          "text": "A code that indicates the system successfully created a block buffer with no errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBlockBufferNoErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferNoErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBlockBufferNoErr"
        }
      ],
      "role": "symbol",
      "title": "kCMBlockBufferNoErr",
      "type": "topic",
      "url": "/documentation/coremedia/kcmblockbuffernoerr"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferStructureAllocationFailedErr": {
      "abstract": [
        {
          "text": "An error code that indicates the structure allocator failed to allocate a block buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBlockBufferStructureAllocationFailedErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferStructureAllocationFailedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBlockBufferStructureAllocationFailedErr"
        }
      ],
      "role": "symbol",
      "title": "kCMBlockBufferStructureAllocationFailedErr",
      "type": "topic",
      "url": "/documentation/coremedia/kcmblockbufferstructureallocationfailederr"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferUnallocatedBlockErr": {
      "abstract": [
        {
          "text": "An error code that indicates the system encountered an unallocated memory block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBlockBufferUnallocatedBlockErr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferUnallocatedBlockErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBlockBufferUnallocatedBlockErr"
        }
      ],
      "role": "symbol",
      "title": "kCMBlockBufferUnallocatedBlockErr",
      "type": "topic",
      "url": "/documentation/coremedia/kcmblockbufferunallocatedblockerr"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferBadCustomBlockSourceErr",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferBadLengthParameterErr",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferBadOffsetParameterErr",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferBadPointerParameterErr",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferBlockAllocationFailedErr",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferEmptyBBufErr",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferInsufficientSpaceErr",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferStructureAllocationFailedErr",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferUnallocatedBlockErr"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMBlockBufferNoErr"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBlockBufferNoErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferBadCustomBlockSourceErr",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferBadLengthParameterErr",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferBadOffsetParameterErr",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferBadPointerParameterErr",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferBlockAllocationFailedErr",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferEmptyBBufErr",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferInsufficientSpaceErr",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferStructureAllocationFailedErr",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBlockBufferUnallocatedBlockErr"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMBlockBufferNoErr"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferBadOffsetParameterErr/title",
          "value": "kCMBlockBufferBadOffsetParameterErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferBadOffsetParameterErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBlockBufferBadOffsetParameterErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferBlockAllocationFailedErr/title",
          "value": "kCMBlockBufferBlockAllocationFailedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferBlockAllocationFailedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBlockBufferBlockAllocationFailedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferInsufficientSpaceErr/title",
          "value": "kCMBlockBufferInsufficientSpaceErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferInsufficientSpaceErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBlockBufferInsufficientSpaceErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferBadPointerParameterErr/title",
          "value": "kCMBlockBufferBadPointerParameterErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferBadPointerParameterErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBlockBufferBadPointerParameterErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferBadCustomBlockSourceErr/title",
          "value": "kCMBlockBufferBadCustomBlockSourceErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferBadCustomBlockSourceErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBlockBufferBadCustomBlockSourceErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferUnallocatedBlockErr/title",
          "value": "kCMBlockBufferUnallocatedBlockErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferUnallocatedBlockErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBlockBufferUnallocatedBlockErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferEmptyBBufErr/title",
          "value": "kCMBlockBufferEmptyBBufErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferEmptyBBufErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBlockBufferEmptyBBufErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferNoErr/title",
          "value": "kCMBlockBufferNoErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferNoErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBlockBufferNoErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferBadLengthParameterErr/title",
          "value": "kCMBlockBufferBadLengthParameterErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferBadLengthParameterErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBlockBufferBadLengthParameterErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferStructureAllocationFailedErr/title",
          "value": "kCMBlockBufferStructureAllocationFailedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBlockBufferStructureAllocationFailedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBlockBufferStructureAllocationFailedErr"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmblockbuffernoerr"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmblockbuffernoerr"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
