{
  "abstract": [
    {
      "text": "Trigger fires when queue duration becomes greater than the specified duration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDurationBecomesGreaterThan"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMBufferQueueTrigger_WhenDurationBecomesLessThan@kCMBufferQueueTrigger_WhenDurationBecomesGreaterThan",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThan"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMBufferQueueTriggerCondition",
        "text": "CMBufferQueueTriggerCondition"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThan"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThan"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThan"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueTriggerCondition",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMBufferQueueTriggerCondition",
              "text": "CMBufferQueueTriggerCondition"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueDequeueIfDataReady(_:)": {
      "abstract": [
        {
          "text": "Dequeues a buffer from a queue, if it’s ready.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueDequeueIfDataReady"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueRef",
          "text": "CMBufferQueue"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferRef",
          "text": "CMBuffer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueDequeueIfDataReady(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueDequeueIfDataReadyAndRetain"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueDequeueIfDataReady(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueuedequeueifdataready(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueTriggerCondition": {
      "abstract": [
        {
          "text": "A type to specify conditions to associate with a buffer queue trigger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferQueueTriggerCondition"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueTriggerCondition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferQueueTriggerCondition"
        }
      ],
      "role": "symbol",
      "title": "CMBufferQueueTriggerCondition",
      "type": "topic",
      "url": "/documentation/coremedia/cmbufferqueuetriggercondition"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenBufferCountBecomesGreaterThan": {
      "abstract": [
        {
          "text": "Trigger fires when buffer count becomes > the specified threshold number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenBufferCountBecomesGreaterThan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueTriggerCondition",
          "text": "CMBufferQueueTriggerCondition"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenBufferCountBecomesGreaterThan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenBufferCountBecomesGreaterThan"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueTrigger_WhenBufferCountBecomesGreaterThan",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueuetrigger_whenbuffercountbecomesgreaterthan"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenBufferCountBecomesLessThan": {
      "abstract": [
        {
          "text": "Trigger fires when buffer count becomes less than the specified threshold number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenBufferCountBecomesLessThan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueTriggerCondition",
          "text": "CMBufferQueueTriggerCondition"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenBufferCountBecomesLessThan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenBufferCountBecomesLessThan"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueTrigger_WhenBufferCountBecomesLessThan",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueuetrigger_whenbuffercountbecomeslessthan"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDataBecomesReady": {
      "abstract": [
        {
          "text": "Trigger fires when next dequeueable buffer becomes ready (that is, ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferQueueDequeueIfDataReady(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " will now succeed).  (triggerDuration is ignored.)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenDataBecomesReady"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueTriggerCondition",
          "text": "CMBufferQueueTriggerCondition"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDataBecomesReady",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenDataBecomesReady"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueTrigger_WhenDataBecomesReady",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueuetrigger_whendatabecomesready"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDurationBecomesGreaterThan": {
      "abstract": [
        {
          "text": "Trigger fires when queue duration becomes greater than the specified duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueTriggerCondition",
          "text": "CMBufferQueueTriggerCondition"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDurationBecomesGreaterThan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThan"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThan",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueuetrigger_whendurationbecomesgreaterthan"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualTo": {
      "abstract": [
        {
          "text": "Trigger fires when queue duration becomes greater than or equal to the specified duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueTriggerCondition",
          "text": "CMBufferQueueTriggerCondition"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualTo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualTo"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualTo",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueuetrigger_whendurationbecomesgreaterthanorequalto"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualToAndBufferCountBecomesGreaterThan": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualToAndBufferCountBecomesGreaterThan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueTriggerCondition",
          "text": "CMBufferQueueTriggerCondition"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualToAndBufferCountBecomesGreaterThan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualToAndBufferCountBecomesGreaterThan"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualToAndBufferCountBecomesGreaterThan",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueuetrigger_whendurationbecomesgreaterthanorequaltoandbuffercountbecomesgreaterthan"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDurationBecomesLessThan": {
      "abstract": [
        {
          "text": "Trigger fires when queue duration becomes less than the specified duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenDurationBecomesLessThan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueTriggerCondition",
          "text": "CMBufferQueueTriggerCondition"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDurationBecomesLessThan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenDurationBecomesLessThan"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueTrigger_WhenDurationBecomesLessThan",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueuetrigger_whendurationbecomeslessthan"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDurationBecomesLessThanOrEqualTo": {
      "abstract": [
        {
          "text": "Trigger fires when queue duration becomes less than or equal to the specified duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenDurationBecomesLessThanOrEqualTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueTriggerCondition",
          "text": "CMBufferQueueTriggerCondition"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDurationBecomesLessThanOrEqualTo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenDurationBecomesLessThanOrEqualTo"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueTrigger_WhenDurationBecomesLessThanOrEqualTo",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueuetrigger_whendurationbecomeslessthanorequalto"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenEndOfDataReached": {
      "abstract": [
        {
          "text": "Trigger fires when CMBufferQueueIsAtEndOfData’s condition becomes true.  (triggerDuration is ignored.)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenEndOfDataReached"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueTriggerCondition",
          "text": "CMBufferQueueTriggerCondition"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenEndOfDataReached",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenEndOfDataReached"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueTrigger_WhenEndOfDataReached",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueuetrigger_whenendofdatareached"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenMaxPresentationTimeStampChanges": {
      "abstract": [
        {
          "text": "Trigger fires when the maximum presentation timestamp changes (triggerDuration is ignored).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenMaxPresentationTimeStampChanges"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueTriggerCondition",
          "text": "CMBufferQueueTriggerCondition"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenMaxPresentationTimeStampChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenMaxPresentationTimeStampChanges"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueTrigger_WhenMaxPresentationTimeStampChanges",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueuetrigger_whenmaxpresentationtimestampchanges"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenMinPresentationTimeStampChanges": {
      "abstract": [
        {
          "text": "Trigger fires when the minimum presentation timestamp changes (triggerDuration is ignored).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenMinPresentationTimeStampChanges"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueTriggerCondition",
          "text": "CMBufferQueueTriggerCondition"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenMinPresentationTimeStampChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenMinPresentationTimeStampChanges"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueTrigger_WhenMinPresentationTimeStampChanges",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueuetrigger_whenminpresentationtimestampchanges"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenReset": {
      "abstract": [
        {
          "text": "Trigger fires when CMBufferQueueReset called.  (triggerDuration is ignored.)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenReset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMBufferQueueTriggerCondition",
          "text": "CMBufferQueueTriggerCondition"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenReset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueTrigger_WhenReset"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueTrigger_WhenReset",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueuetrigger_whenreset"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDurationBecomesLessThan",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDurationBecomesLessThanOrEqualTo",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualTo",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenMinPresentationTimeStampChanges",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenMaxPresentationTimeStampChanges",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDataBecomesReady",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenEndOfDataReached",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenReset",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenBufferCountBecomesLessThan",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenBufferCountBecomesGreaterThan",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualToAndBufferCountBecomesGreaterThan"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThan"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDurationBecomesLessThan",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDurationBecomesLessThanOrEqualTo",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualTo",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenMinPresentationTimeStampChanges",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenMaxPresentationTimeStampChanges",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDataBecomesReady",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenEndOfDataReached",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenReset",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenBufferCountBecomesLessThan",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenBufferCountBecomesGreaterThan",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualToAndBufferCountBecomesGreaterThan"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThan"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualTo/title",
          "value": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualTo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenDataBecomesReady/title",
          "value": "kCMBufferQueueTrigger_WhenDataBecomesReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenDataBecomesReady/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueTrigger_WhenDataBecomesReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenReset/title",
          "value": "kCMBufferQueueTrigger_WhenReset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenReset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueTrigger_WhenReset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenDurationBecomesLessThanOrEqualTo/title",
          "value": "kCMBufferQueueTrigger_WhenDurationBecomesLessThanOrEqualTo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenDurationBecomesLessThanOrEqualTo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueTrigger_WhenDurationBecomesLessThanOrEqualTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueTriggerCondition/title",
          "value": "CMBufferQueueTriggerCondition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueTriggerCondition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueTriggerCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueTriggerCondition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueTriggerCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenMaxPresentationTimeStampChanges/title",
          "value": "kCMBufferQueueTrigger_WhenMaxPresentationTimeStampChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenMaxPresentationTimeStampChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueTrigger_WhenMaxPresentationTimeStampChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenBufferCountBecomesLessThan/title",
          "value": "kCMBufferQueueTrigger_WhenBufferCountBecomesLessThan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenBufferCountBecomesLessThan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueTrigger_WhenBufferCountBecomesLessThan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenDurationBecomesGreaterThan/title",
          "value": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenDurationBecomesGreaterThan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueDequeueIfDataReady(_:)/title",
          "value": "CMBufferQueueDequeueIfDataReadyAndRetain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferQueueDequeueIfDataReady(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferQueueDequeueIfDataReadyAndRetain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenEndOfDataReached/title",
          "value": "kCMBufferQueueTrigger_WhenEndOfDataReached"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenEndOfDataReached/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueTrigger_WhenEndOfDataReached"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenMinPresentationTimeStampChanges/title",
          "value": "kCMBufferQueueTrigger_WhenMinPresentationTimeStampChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenMinPresentationTimeStampChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueTrigger_WhenMinPresentationTimeStampChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualToAndBufferCountBecomesGreaterThan/title",
          "value": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualToAndBufferCountBecomesGreaterThan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualToAndBufferCountBecomesGreaterThan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueTrigger_WhenDurationBecomesGreaterThanOrEqualToAndBufferCountBecomesGreaterThan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenDurationBecomesLessThan/title",
          "value": "kCMBufferQueueTrigger_WhenDurationBecomesLessThan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenDurationBecomesLessThan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueTrigger_WhenDurationBecomesLessThan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenBufferCountBecomesGreaterThan/title",
          "value": "kCMBufferQueueTrigger_WhenBufferCountBecomesGreaterThan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueTrigger_WhenBufferCountBecomesGreaterThan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueTrigger_WhenBufferCountBecomesGreaterThan"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmbufferqueuetrigger_whendurationbecomesgreaterthan"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmbufferqueuetrigger_whendurationbecomesgreaterthan"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
