{
  "abstract": [
    {
      "text": "A buffer validation callback rejected the buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_InvalidBuffer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMBufferQueueError_AllocationFailed@kCMBufferQueueError_InvalidBuffer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMBufferQueueError_InvalidBuffer"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMBufferQueueError_InvalidBuffer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMBufferQueueError_InvalidBuffer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMBufferQueueError_InvalidBuffer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_AllocationFailed": {
      "abstract": [
        {
          "text": "The system failed to allocate memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueError_AllocationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_AllocationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueError_AllocationFailed"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueError_AllocationFailed",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueueerror_allocationfailed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_BadTriggerDuration": {
      "abstract": [
        {
          "text": "You specified an invalid trigger duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueError_BadTriggerDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_BadTriggerDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueError_BadTriggerDuration"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueError_BadTriggerDuration",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueueerror_badtriggerduration"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_CannotModifyQueueFromTriggerCallback": {
      "abstract": [
        {
          "text": "A trigger callback attempted to modify a queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueError_CannotModifyQueueFromTriggerCallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_CannotModifyQueueFromTriggerCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueError_CannotModifyQueueFromTriggerCallback"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueError_CannotModifyQueueFromTriggerCallback",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueueerror_cannotmodifyqueuefromtriggercallback"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_EnqueueAfterEndOfData": {
      "abstract": [
        {
          "text": "You attempted to enqueue a buffer on a queue that disallows it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueError_EnqueueAfterEndOfData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_EnqueueAfterEndOfData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueError_EnqueueAfterEndOfData"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueError_EnqueueAfterEndOfData",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueueerror_enqueueafterendofdata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_InvalidBuffer": {
      "abstract": [
        {
          "text": "A buffer validation callback rejected the buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueError_InvalidBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_InvalidBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueError_InvalidBuffer"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueError_InvalidBuffer",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueueerror_invalidbuffer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_InvalidCMBufferCallbacksStruct": {
      "abstract": [
        {
          "text": "The format of a callbacks structure isn’t correct.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueError_InvalidCMBufferCallbacksStruct"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_InvalidCMBufferCallbacksStruct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueError_InvalidCMBufferCallbacksStruct"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueError_InvalidCMBufferCallbacksStruct",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueueerror_invalidcmbuffercallbacksstruct"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_InvalidTriggerCondition": {
      "abstract": [
        {
          "text": "You specified an invalid trigger condition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueError_InvalidTriggerCondition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_InvalidTriggerCondition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueError_InvalidTriggerCondition"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueError_InvalidTriggerCondition",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueueerror_invalidtriggercondition"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_InvalidTriggerToken": {
      "abstract": [
        {
          "text": "You specified a trigger token that isn’t a trigger currently associated with this queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueError_InvalidTriggerToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_InvalidTriggerToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueError_InvalidTriggerToken"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueError_InvalidTriggerToken",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueueerror_invalidtriggertoken"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_QueueIsFull": {
      "abstract": [
        {
          "text": "You attempted to enqueue a buffer on a queue that’s full.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueError_QueueIsFull"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_QueueIsFull",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueError_QueueIsFull"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueError_QueueIsFull",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueueerror_queueisfull"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_RequiredParameterMissing": {
      "abstract": [
        {
          "text": "You failed to provide a valid value for a required parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMBufferQueueError_RequiredParameterMissing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_RequiredParameterMissing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMBufferQueueError_RequiredParameterMissing"
        }
      ],
      "role": "symbol",
      "title": "kCMBufferQueueError_RequiredParameterMissing",
      "type": "topic",
      "url": "/documentation/coremedia/kcmbufferqueueerror_requiredparametermissing"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_AllocationFailed",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_RequiredParameterMissing",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_InvalidCMBufferCallbacksStruct",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_EnqueueAfterEndOfData",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_QueueIsFull",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_BadTriggerDuration",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_CannotModifyQueueFromTriggerCallback",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_InvalidTriggerCondition",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_InvalidTriggerToken"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMBufferQueueError_InvalidBuffer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueError_InvalidBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_AllocationFailed",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_RequiredParameterMissing",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_InvalidCMBufferCallbacksStruct",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_EnqueueAfterEndOfData",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_QueueIsFull",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_BadTriggerDuration",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_CannotModifyQueueFromTriggerCallback",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_InvalidTriggerCondition",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMBufferQueueError_InvalidTriggerToken"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMBufferQueueError_InvalidBuffer"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueError_InvalidTriggerToken/title",
          "value": "kCMBufferQueueError_InvalidTriggerToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueError_InvalidTriggerToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueError_InvalidTriggerToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueError_InvalidTriggerCondition/title",
          "value": "kCMBufferQueueError_InvalidTriggerCondition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueError_InvalidTriggerCondition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueError_InvalidTriggerCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueError_InvalidBuffer/title",
          "value": "kCMBufferQueueError_InvalidBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueError_InvalidBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueError_InvalidBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueError_EnqueueAfterEndOfData/title",
          "value": "kCMBufferQueueError_EnqueueAfterEndOfData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueError_EnqueueAfterEndOfData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueError_EnqueueAfterEndOfData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueError_QueueIsFull/title",
          "value": "kCMBufferQueueError_QueueIsFull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueError_QueueIsFull/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueError_QueueIsFull"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueError_RequiredParameterMissing/title",
          "value": "kCMBufferQueueError_RequiredParameterMissing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueError_RequiredParameterMissing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueError_RequiredParameterMissing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueError_CannotModifyQueueFromTriggerCallback/title",
          "value": "kCMBufferQueueError_CannotModifyQueueFromTriggerCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueError_CannotModifyQueueFromTriggerCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueError_CannotModifyQueueFromTriggerCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueError_InvalidCMBufferCallbacksStruct/title",
          "value": "kCMBufferQueueError_InvalidCMBufferCallbacksStruct"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueError_InvalidCMBufferCallbacksStruct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueError_InvalidCMBufferCallbacksStruct"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueError_AllocationFailed/title",
          "value": "kCMBufferQueueError_AllocationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueError_AllocationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueError_AllocationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueError_BadTriggerDuration/title",
          "value": "kCMBufferQueueError_BadTriggerDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMBufferQueueError_BadTriggerDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMBufferQueueError_BadTriggerDuration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmbufferqueueerror_invalidbuffer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmbufferqueueerror_invalidbuffer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
