{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionalphachannelmode_premultipliedalpha"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionAlphaChannelMode_StraightAlpha": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionAlphaChannelMode_StraightAlpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionAlphaChannelMode_StraightAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionAlphaChannelMode_StraightAlpha"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionAlphaChannelMode_StraightAlpha",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionalphachannelmode_straightalpha"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptiontransferfunction_itu_r_2100_hlg"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_Linear": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionTransferFunction_Linear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_Linear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionTransferFunction_Linear"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionTransferFunction_Linear",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptiontransferfunction_linear"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptiontransferfunction_smpte_st_2084_pq"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_sRGB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionTransferFunction_sRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_sRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionTransferFunction_sRGB"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionTransferFunction_sRGB",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptiontransferfunction_srgb"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Description-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionAlphaChannelMode_StraightAlpha",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_Linear",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_sRGB"
      ],
      "title": "Description Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Description-Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionAlphaChannelMode_StraightAlpha",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_Linear",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionTransferFunction_sRGB"
              ],
              "title": "Description Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionAlphaChannelMode_StraightAlpha/title",
          "value": "kCMFormatDescriptionAlphaChannelMode_StraightAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionAlphaChannelMode_StraightAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionAlphaChannelMode_StraightAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ/title",
          "value": "kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionTransferFunction_SMPTE_ST_2084_PQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionTransferFunction_Linear/title",
          "value": "kCMFormatDescriptionTransferFunction_Linear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionTransferFunction_Linear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionTransferFunction_Linear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG/title",
          "value": "kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionTransferFunction_ITU_R_2100_HLG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha/title",
          "value": "kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionAlphaChannelMode_PremultipliedAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionTransferFunction_sRGB/title",
          "value": "kCMFormatDescriptionTransferFunction_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionTransferFunction_sRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionTransferFunction_sRGB"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmformatdescriptiontransferfunction_smpte_st_2084_pq"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmformatdescriptiontransferfunction_smpte_st_2084_pq"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
