{
  "abstract": [
    {
      "text": "A bridge error that indicates the sample isn’t supported for the format flavor you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_UnsupportedSampleDescriptionFlavor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMFormatDescriptionBridgeError_InvalidParameter@kCMFormatDescriptionBridgeError_UnsupportedSampleDescriptionFlavor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMFormatDescriptionBridgeError_UnsupportedSampleDescriptionFlavor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMFormatDescriptionBridgeError_UnsupportedSampleDescriptionFlavor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMFormatDescriptionBridgeError_UnsupportedSampleDescriptionFlavor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionBridgeError_UnsupportedSampleDescriptionFlavor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_AllocationFailed": {
      "abstract": [
        {
          "text": "A bridge error that indicates when an allocation fails.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionBridgeError_AllocationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_AllocationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionBridgeError_AllocationFailed"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionBridgeError_AllocationFailed",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionbridgeerror_allocationfailed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_IncompatibleFormatDescription": {
      "abstract": [
        {
          "text": "A bridge error that indicates the format description has an unknown format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionBridgeError_IncompatibleFormatDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_IncompatibleFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionBridgeError_IncompatibleFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionBridgeError_IncompatibleFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionbridgeerror_incompatibleformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_InvalidFormatDescription": {
      "abstract": [
        {
          "text": "A bridge error that indicates the format description isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionBridgeError_InvalidFormatDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_InvalidFormatDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionBridgeError_InvalidFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionBridgeError_InvalidFormatDescription",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionbridgeerror_invalidformatdescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_InvalidParameter": {
      "abstract": [
        {
          "text": "A bridge error that indicates that the function recieves an empty value for a parameter it requires.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionBridgeError_InvalidParameter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_InvalidParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionBridgeError_InvalidParameter"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionBridgeError_InvalidParameter",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionbridgeerror_invalidparameter"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_InvalidSerializedSampleDescription": {
      "abstract": [
        {
          "text": "A bridge error that indicates that the sample isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionBridgeError_InvalidSerializedSampleDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_InvalidSerializedSampleDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionBridgeError_InvalidSerializedSampleDescription"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionBridgeError_InvalidSerializedSampleDescription",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionbridgeerror_invalidserializedsampledescription"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_InvalidSlice": {
      "abstract": [
        {
          "text": "A bridge error that indicates the slice isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionBridgeError_InvalidSlice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_InvalidSlice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionBridgeError_InvalidSlice"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionBridgeError_InvalidSlice",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionbridgeerror_invalidslice"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_UnsupportedSampleDescriptionFlavor": {
      "abstract": [
        {
          "text": "A bridge error that indicates the sample isn’t supported for the format flavor you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionBridgeError_UnsupportedSampleDescriptionFlavor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_UnsupportedSampleDescriptionFlavor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionBridgeError_UnsupportedSampleDescriptionFlavor"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionBridgeError_UnsupportedSampleDescriptionFlavor",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionbridgeerror_unsupportedsampledescriptionflavor"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_InvalidParameter",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_AllocationFailed",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_IncompatibleFormatDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_InvalidFormatDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_InvalidSerializedSampleDescription",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_InvalidSlice"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMFormatDescriptionBridgeError_UnsupportedSampleDescriptionFlavor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionBridgeError_UnsupportedSampleDescriptionFlavor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_InvalidParameter",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_AllocationFailed",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_IncompatibleFormatDescription",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_InvalidFormatDescription",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_InvalidSerializedSampleDescription",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionBridgeError_InvalidSlice"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMFormatDescriptionBridgeError_UnsupportedSampleDescriptionFlavor"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionBridgeError_IncompatibleFormatDescription/title",
          "value": "kCMFormatDescriptionBridgeError_IncompatibleFormatDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionBridgeError_IncompatibleFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionBridgeError_IncompatibleFormatDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionBridgeError_AllocationFailed/title",
          "value": "kCMFormatDescriptionBridgeError_AllocationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionBridgeError_AllocationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionBridgeError_AllocationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionBridgeError_InvalidParameter/title",
          "value": "kCMFormatDescriptionBridgeError_InvalidParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionBridgeError_InvalidParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionBridgeError_InvalidParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionBridgeError_InvalidSlice/title",
          "value": "kCMFormatDescriptionBridgeError_InvalidSlice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionBridgeError_InvalidSlice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionBridgeError_InvalidSlice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionBridgeError_InvalidSerializedSampleDescription/title",
          "value": "kCMFormatDescriptionBridgeError_InvalidSerializedSampleDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionBridgeError_InvalidSerializedSampleDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionBridgeError_InvalidSerializedSampleDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionBridgeError_UnsupportedSampleDescriptionFlavor/title",
          "value": "kCMFormatDescriptionBridgeError_UnsupportedSampleDescriptionFlavor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionBridgeError_UnsupportedSampleDescriptionFlavor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionBridgeError_UnsupportedSampleDescriptionFlavor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionBridgeError_InvalidFormatDescription/title",
          "value": "kCMFormatDescriptionBridgeError_InvalidFormatDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionBridgeError_InvalidFormatDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionBridgeError_InvalidFormatDescription"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmformatdescriptionbridgeerror_unsupportedsampledescriptionflavor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmformatdescriptionbridgeerror_unsupportedsampledescriptionflavor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
