{
  "abstract": [
    {
      "text": "The value is a number.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_TierFlag"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCMHEVCTemporalLevelInfoKey_TierFlag",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMHEVCTemporalLevelInfoKey_TierFlag"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMHEVCTemporalLevelInfoKey_TierFlag"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMHEVCTemporalLevelInfoKey_TierFlag"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMHEVCTemporalLevelInfoKey_TierFlag"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_ConstraintIndicatorFlags": {
      "abstract": [
        {
          "text": "The value is a 6 byte data value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMHEVCTemporalLevelInfoKey_ConstraintIndicatorFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_ConstraintIndicatorFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMHEVCTemporalLevelInfoKey_ConstraintIndicatorFlags"
        }
      ],
      "role": "symbol",
      "title": "kCMHEVCTemporalLevelInfoKey_ConstraintIndicatorFlags",
      "type": "topic",
      "url": "/documentation/coremedia/kcmhevctemporallevelinfokey_constraintindicatorflags"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_LevelIndex": {
      "abstract": [
        {
          "text": "The value is a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMHEVCTemporalLevelInfoKey_LevelIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_LevelIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMHEVCTemporalLevelInfoKey_LevelIndex"
        }
      ],
      "role": "symbol",
      "title": "kCMHEVCTemporalLevelInfoKey_LevelIndex",
      "type": "topic",
      "url": "/documentation/coremedia/kcmhevctemporallevelinfokey_levelindex"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_ProfileCompatibilityFlags": {
      "abstract": [
        {
          "text": "The value is a 4 byte data value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMHEVCTemporalLevelInfoKey_ProfileCompatibilityFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_ProfileCompatibilityFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMHEVCTemporalLevelInfoKey_ProfileCompatibilityFlags"
        }
      ],
      "role": "symbol",
      "title": "kCMHEVCTemporalLevelInfoKey_ProfileCompatibilityFlags",
      "type": "topic",
      "url": "/documentation/coremedia/kcmhevctemporallevelinfokey_profilecompatibilityflags"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_ProfileIndex": {
      "abstract": [
        {
          "text": "The value is a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMHEVCTemporalLevelInfoKey_ProfileIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_ProfileIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMHEVCTemporalLevelInfoKey_ProfileIndex"
        }
      ],
      "role": "symbol",
      "title": "kCMHEVCTemporalLevelInfoKey_ProfileIndex",
      "type": "topic",
      "url": "/documentation/coremedia/kcmhevctemporallevelinfokey_profileindex"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_ProfileSpace": {
      "abstract": [
        {
          "text": "The value is a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMHEVCTemporalLevelInfoKey_ProfileSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_ProfileSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMHEVCTemporalLevelInfoKey_ProfileSpace"
        }
      ],
      "role": "symbol",
      "title": "kCMHEVCTemporalLevelInfoKey_ProfileSpace",
      "type": "topic",
      "url": "/documentation/coremedia/kcmhevctemporallevelinfokey_profilespace"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_TemporalLevel": {
      "abstract": [
        {
          "text": "The value is a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMHEVCTemporalLevelInfoKey_TemporalLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_TemporalLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMHEVCTemporalLevelInfoKey_TemporalLevel"
        }
      ],
      "role": "symbol",
      "title": "kCMHEVCTemporalLevelInfoKey_TemporalLevel",
      "type": "topic",
      "url": "/documentation/coremedia/kcmhevctemporallevelinfokey_temporallevel"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_TierFlag": {
      "abstract": [
        {
          "text": "The value is a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMHEVCTemporalLevelInfoKey_TierFlag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_TierFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMHEVCTemporalLevelInfoKey_TierFlag"
        }
      ],
      "role": "symbol",
      "title": "kCMHEVCTemporalLevelInfoKey_TierFlag",
      "type": "topic",
      "url": "/documentation/coremedia/kcmhevctemporallevelinfokey_tierflag"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_ConstraintIndicatorFlags",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_LevelIndex",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_ProfileCompatibilityFlags",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_ProfileIndex",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_ProfileSpace",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_TemporalLevel"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMHEVCTemporalLevelInfoKey_TierFlag"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMHEVCTemporalLevelInfoKey_TierFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_ConstraintIndicatorFlags",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_LevelIndex",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_ProfileCompatibilityFlags",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_ProfileIndex",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_ProfileSpace",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMHEVCTemporalLevelInfoKey_TemporalLevel"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCMHEVCTemporalLevelInfoKey_TierFlag"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMHEVCTemporalLevelInfoKey_ProfileIndex/title",
          "value": "kCMHEVCTemporalLevelInfoKey_ProfileIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMHEVCTemporalLevelInfoKey_ProfileIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMHEVCTemporalLevelInfoKey_ProfileIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMHEVCTemporalLevelInfoKey_TemporalLevel/title",
          "value": "kCMHEVCTemporalLevelInfoKey_TemporalLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMHEVCTemporalLevelInfoKey_TemporalLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMHEVCTemporalLevelInfoKey_TemporalLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMHEVCTemporalLevelInfoKey_TierFlag/title",
          "value": "kCMHEVCTemporalLevelInfoKey_TierFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMHEVCTemporalLevelInfoKey_TierFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMHEVCTemporalLevelInfoKey_TierFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMHEVCTemporalLevelInfoKey_ProfileSpace/title",
          "value": "kCMHEVCTemporalLevelInfoKey_ProfileSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMHEVCTemporalLevelInfoKey_ProfileSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMHEVCTemporalLevelInfoKey_ProfileSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMHEVCTemporalLevelInfoKey_ProfileCompatibilityFlags/title",
          "value": "kCMHEVCTemporalLevelInfoKey_ProfileCompatibilityFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMHEVCTemporalLevelInfoKey_ProfileCompatibilityFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMHEVCTemporalLevelInfoKey_ProfileCompatibilityFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMHEVCTemporalLevelInfoKey_LevelIndex/title",
          "value": "kCMHEVCTemporalLevelInfoKey_LevelIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMHEVCTemporalLevelInfoKey_LevelIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMHEVCTemporalLevelInfoKey_LevelIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMHEVCTemporalLevelInfoKey_ConstraintIndicatorFlags/title",
          "value": "kCMHEVCTemporalLevelInfoKey_ConstraintIndicatorFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMHEVCTemporalLevelInfoKey_ConstraintIndicatorFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMHEVCTemporalLevelInfoKey_ConstraintIndicatorFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmhevctemporallevelinfokey_tierflag"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmhevctemporallevelinfokey_tierflag"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
