{
  "abstract": [
    {
      "text": "DV stream.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_DV"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMMuxedStreamType_MPEG1System@kCMMuxedStreamType_DV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMMuxedStreamType_DV"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMMuxedStreamType",
        "text": "CMMuxedStreamType"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMMuxedStreamType_DV"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMMuxedStreamType_DV"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMMuxedStreamType_DV"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedStreamType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMMuxedStreamType",
              "text": "CMMuxedStreamType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedStreamType": {
      "abstract": [
        {
          "text": "A datatype that represents a muxed stream of data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMuxedStreamType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedStreamType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMuxedStreamType"
        }
      ],
      "role": "symbol",
      "title": "CMMuxedStreamType",
      "type": "topic",
      "url": "/documentation/coremedia/cmmuxedstreamtype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_DV": {
      "abstract": [
        {
          "text": "DV stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMuxedStreamType_DV"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMuxedStreamType",
          "text": "CMMuxedStreamType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_DV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMuxedStreamType_DV"
        }
      ],
      "role": "symbol",
      "title": "kCMMuxedStreamType_DV",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmuxedstreamtype_dv"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_EmbeddedDeviceScreenRecording": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMuxedStreamType_EmbeddedDeviceScreenRecording"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMuxedStreamType",
          "text": "CMMuxedStreamType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_EmbeddedDeviceScreenRecording",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMuxedStreamType_EmbeddedDeviceScreenRecording"
        }
      ],
      "role": "symbol",
      "title": "kCMMuxedStreamType_EmbeddedDeviceScreenRecording",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmuxedstreamtype_embeddeddevicescreenrecording"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG1System": {
      "abstract": [
        {
          "text": "MPEG-1 System stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMuxedStreamType_MPEG1System"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMuxedStreamType",
          "text": "CMMuxedStreamType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG1System",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMuxedStreamType_MPEG1System"
        }
      ],
      "role": "symbol",
      "title": "kCMMuxedStreamType_MPEG1System",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmuxedstreamtype_mpeg1system"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG2Program": {
      "abstract": [
        {
          "text": "MPEG-2 Program stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMuxedStreamType_MPEG2Program"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMuxedStreamType",
          "text": "CMMuxedStreamType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG2Program",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMuxedStreamType_MPEG2Program"
        }
      ],
      "role": "symbol",
      "title": "kCMMuxedStreamType_MPEG2Program",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmuxedstreamtype_mpeg2program"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG2Transport": {
      "abstract": [
        {
          "text": "MPEG-2 Transport stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMuxedStreamType_MPEG2Transport"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMuxedStreamType",
          "text": "CMMuxedStreamType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG2Transport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMuxedStreamType_MPEG2Transport"
        }
      ],
      "role": "symbol",
      "title": "kCMMuxedStreamType_MPEG2Transport",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmuxedstreamtype_mpeg2transport"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG1System",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG2Program",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG2Transport",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_EmbeddedDeviceScreenRecording"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMMuxedStreamType_DV"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMuxedStreamType_DV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG1System",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG2Program",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG2Transport",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_EmbeddedDeviceScreenRecording"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMMuxedStreamType_DV"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMuxedStreamType_MPEG2Transport/title",
          "value": "kCMMuxedStreamType_MPEG2Transport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMuxedStreamType_MPEG2Transport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMuxedStreamType_MPEG2Transport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMuxedStreamType_EmbeddedDeviceScreenRecording/title",
          "value": "kCMMuxedStreamType_EmbeddedDeviceScreenRecording"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMuxedStreamType_EmbeddedDeviceScreenRecording/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMuxedStreamType_EmbeddedDeviceScreenRecording"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMuxedStreamType/title",
          "value": "CMMuxedStreamType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMuxedStreamType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMuxedStreamType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMuxedStreamType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMuxedStreamType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMuxedStreamType_DV/title",
          "value": "kCMMuxedStreamType_DV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMuxedStreamType_DV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMuxedStreamType_DV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMuxedStreamType_MPEG1System/title",
          "value": "kCMMuxedStreamType_MPEG1System"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMuxedStreamType_MPEG1System/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMuxedStreamType_MPEG1System"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMuxedStreamType_MPEG2Program/title",
          "value": "kCMMuxedStreamType_MPEG2Program"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMuxedStreamType_MPEG2Program/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMuxedStreamType_MPEG2Program"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmmuxedstreamtype_dv"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmmuxedstreamtype_dv"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
