{
  "abstract": [
    {
      "text": "A profile that represents the XDCAM HD 1080i60 video HQ format with 35 Mbps bit rate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMMPEG2VideoProfile_HDV_720p30@kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080i50": {
      "abstract": [
        {
          "text": "A profile that represents the Apple Intermediate Codec HDV 1080i50 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_1080i50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080i50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_1080i50"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_HDV_1080i50",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_hdv_1080i50"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080i60": {
      "abstract": [
        {
          "text": "A profile that represents the Apple Intermediate Codec HDV 1080i60 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_1080i60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080i60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_1080i60"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_HDV_1080i60",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_hdv_1080i60"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p24": {
      "abstract": [
        {
          "text": "A profile that represents the Apple ProRes 422 codec HDV 1080p24 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_1080p24"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p24",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_1080p24"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_HDV_1080p24",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_hdv_1080p24"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p25": {
      "abstract": [
        {
          "text": "A profile that represents the HDV 1080p25 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_1080p25"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p25",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_1080p25"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_HDV_1080p25",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_hdv_1080p25"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p30": {
      "abstract": [
        {
          "text": "A profile that represents the HDV 1080p30 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_1080p30"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p30",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_1080p30"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_HDV_1080p30",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_hdv_1080p30"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p24": {
      "abstract": [
        {
          "text": "A profile that represents the HDV 720p24 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_720p24"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p24",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_720p24"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_HDV_720p24",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_hdv_720p24"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p25": {
      "abstract": [
        {
          "text": "A profile that represents the HDV_720p25 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_720p25"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p25",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_720p25"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_HDV_720p25",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_hdv_720p25"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p30": {
      "abstract": [
        {
          "text": "A profile that represents the Apple Intermediate Codec HDV 720p30 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_720p30"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p30",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_720p30"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_HDV_720p30",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_hdv_720p30"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p50": {
      "abstract": [
        {
          "text": "A profile that represents the HDV 720p50 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_720p50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_720p50"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_HDV_720p50",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_hdv_720p50"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p60": {
      "abstract": [
        {
          "text": "A profile that represents the HDV 720p60 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_720p60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_720p60"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_HDV_720p60",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_hdv_720p60"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM EX 720p24 video HQ format with 35 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_ex_720p24_vbr35"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM HD 1080i50 video HQ format with 35 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd_1080i50_vbr35"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM HD 1080i60 video HQ format with 35 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd_1080i60_vbr35"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM HD 1080p24 video HQ format with 35 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd_1080p24_vbr35"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM HD 1080p25 video HQ format with 35 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd_1080p25_vbr35"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35": {
      "abstract": [
        {
          "text": "A profile that represents the DCAM HD 1080p30 video HQ format with 35 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd_1080p30_vbr35"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p30",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080i60",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080i50",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p24",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p25",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p24",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p25",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p30",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p60",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p50",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p30",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080i60",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080i50",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p24",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p25",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p24",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p25",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p30",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p60",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p50",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_1080p24/title",
          "value": "kCMMPEG2VideoProfile_HDV_1080p24"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_1080p24/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_HDV_1080p24"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_720p50/title",
          "value": "kCMMPEG2VideoProfile_HDV_720p50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_720p50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_HDV_720p50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_1080p30/title",
          "value": "kCMMPEG2VideoProfile_HDV_1080p30"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_1080p30/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_HDV_1080p30"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_1080i60/title",
          "value": "kCMMPEG2VideoProfile_HDV_1080i60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_1080i60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_HDV_1080i60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_720p60/title",
          "value": "kCMMPEG2VideoProfile_HDV_720p60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_720p60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_HDV_720p60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_720p24/title",
          "value": "kCMMPEG2VideoProfile_HDV_720p24"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_720p24/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_HDV_720p24"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_720p25/title",
          "value": "kCMMPEG2VideoProfile_HDV_720p25"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_720p25/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_HDV_720p25"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_720p30/title",
          "value": "kCMMPEG2VideoProfile_HDV_720p30"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_720p30/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_HDV_720p30"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_1080p25/title",
          "value": "kCMMPEG2VideoProfile_HDV_1080p25"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_1080p25/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_HDV_1080p25"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_1080i50/title",
          "value": "kCMMPEG2VideoProfile_HDV_1080i50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_1080i50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_HDV_1080i50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd_1080i60_vbr35"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd_1080i60_vbr35"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
