{
  "abstract": [
    {
      "text": "Direction the observer is facing.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing": {
      "abstract": [
        {
          "text": "Direction the observer is facing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifier_quicktimemetadatadirection_facing"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform": {
      "abstract": [
        {
          "text": "A perspective transform you use to adjust a Live Photo still image to match the Live Photo movie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifier_quicktimemetadatalivephotostillimagetransform"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions": {
      "abstract": [
        {
          "text": "The dimensions of the live photo still image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifier_quicktimemetadatalivephotostillimagetransformreferencedimensions"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709": {
      "abstract": [
        {
          "text": "Location information in ISO-6709 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifier_quicktimemetadatalocation_iso6709"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform": {
      "abstract": [
        {
          "text": "An affine transform to be applied to a video track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifier_quicktimemetadatapreferredaffinetransform"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation": {
      "abstract": [
        {
          "text": "Video orientation as defined by TIFF/EXIF.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifier_quicktimemetadatavideoorientation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform/title",
          "value": "kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation/title",
          "value": "kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing/title",
          "value": "kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions/title",
          "value": "kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709/title",
          "value": "kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform/title",
          "value": "kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmmetadataidentifier_quicktimemetadatadirection_facing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmmetadataidentifier_quicktimemetadatadirection_facing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
