{
  "abstract": [
    {
      "text": "A key that identifies the local identifier.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_LocalID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCMMetadataFormatDescriptionKey_LocalID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMMetadataFormatDescriptionKey_LocalID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMMetadataFormatDescriptionKey_LocalID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMMetadataFormatDescriptionKey_LocalID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionKey_LocalID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_AffineTransformF64": {
      "abstract": [
        {
          "text": "A type that identifies a 3x3 matrix of 64-bit big endian floating point numbers in a row-major order that specify an affine transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_AffineTransformF64"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_AffineTransformF64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_AffineTransformF64"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_AffineTransformF64",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_affinetransformf64"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_ConformingDataTypes": {
      "abstract": [
        {
          "text": "A key that identifies the conforming data types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_ConformingDataTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_ConformingDataTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_ConformingDataTypes"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionKey_ConformingDataTypes",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionkey_conformingdatatypes"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_DataType": {
      "abstract": [
        {
          "text": "A key that identifies the data type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_DataType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_DataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_DataType"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionKey_DataType",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionkey_datatype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_DataTypeNamespace": {
      "abstract": [
        {
          "text": "A key that identifies the data type namespace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_DataTypeNamespace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_DataTypeNamespace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_DataTypeNamespace"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionKey_DataTypeNamespace",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionkey_datatypenamespace"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_LanguageTag": {
      "abstract": [
        {
          "text": "A key that identifies the language tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_LanguageTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_LanguageTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_LanguageTag"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionKey_LanguageTag",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionkey_languagetag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_LocalID": {
      "abstract": [
        {
          "text": "A key that identifies the local identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_LocalID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_LocalID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_LocalID"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionKey_LocalID",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionkey_localid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_Namespace": {
      "abstract": [
        {
          "text": "A key that identifies the namespace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_Namespace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_Namespace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_Namespace"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionKey_Namespace",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionkey_namespace"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_SetupData": {
      "abstract": [
        {
          "text": "A key that identifies setup data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_SetupData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_SetupData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_SetupData"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionKey_SetupData",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionkey_setupdata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_StructuralDependency": {
      "abstract": [
        {
          "text": "A key that identifies the structural dependency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_StructuralDependency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_StructuralDependency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_StructuralDependency"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionKey_StructuralDependency",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionkey_structuraldependency"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_Value": {
      "abstract": [
        {
          "text": "A key that identifies the value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_Value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_Value",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_Value"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionKey_Value",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionkey_value"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType": {
      "abstract": [
        {
          "text": "A specification key that identifies the data type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionmetadataspecificationkey_datatype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag": {
      "abstract": [
        {
          "text": "A specification key that identifies the extended language tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionmetadataspecificationkey_extendedlanguagetag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier": {
      "abstract": [
        {
          "text": "A specification key that identifies the identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionmetadataspecificationkey_identifier"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData": {
      "abstract": [
        {
          "text": "A specification key that identifies the setup data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionmetadataspecificationkey_setupdata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency": {
      "abstract": [
        {
          "text": "A specification key that identifies dependencies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionmetadataspecificationkey_structuraldependency"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag": {
      "abstract": [
        {
          "text": "A specification key that identifies the depencency isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescription_structuraldependencykey_dependencyisinvalidflag"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_AffineTransformF64",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_ConformingDataTypes",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_DataType",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_DataTypeNamespace",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_LanguageTag",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_Namespace",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_SetupData",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_StructuralDependency",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_Value",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMMetadataFormatDescriptionKey_LocalID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionKey_LocalID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_AffineTransformF64",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_ConformingDataTypes",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_DataType",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_DataTypeNamespace",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_LanguageTag",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_Namespace",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_SetupData",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_StructuralDependency",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_Value",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCMMetadataFormatDescriptionKey_LocalID"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_SetupData/title",
          "value": "kCMMetadataFormatDescriptionKey_SetupData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_SetupData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionKey_SetupData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_StructuralDependency/title",
          "value": "kCMMetadataFormatDescriptionKey_StructuralDependency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_StructuralDependency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionKey_StructuralDependency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier/title",
          "value": "kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_AffineTransformF64/title",
          "value": "kCMMetadataBaseDataType_AffineTransformF64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_AffineTransformF64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_AffineTransformF64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_LocalID/title",
          "value": "kCMMetadataFormatDescriptionKey_LocalID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_LocalID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionKey_LocalID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_LanguageTag/title",
          "value": "kCMMetadataFormatDescriptionKey_LanguageTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_LanguageTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionKey_LanguageTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency/title",
          "value": "kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_ConformingDataTypes/title",
          "value": "kCMMetadataFormatDescriptionKey_ConformingDataTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_ConformingDataTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionKey_ConformingDataTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_DataType/title",
          "value": "kCMMetadataFormatDescriptionKey_DataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_DataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionKey_DataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_Namespace/title",
          "value": "kCMMetadataFormatDescriptionKey_Namespace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_Namespace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionKey_Namespace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_Value/title",
          "value": "kCMMetadataFormatDescriptionKey_Value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_Value/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionKey_Value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_DataTypeNamespace/title",
          "value": "kCMMetadataFormatDescriptionKey_DataTypeNamespace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_DataTypeNamespace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionKey_DataTypeNamespace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType/title",
          "value": "kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag/title",
          "value": "kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag/title",
          "value": "kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData/title",
          "value": "kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmmetadataformatdescriptionkey_localid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmmetadataformatdescriptionkey_localid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
