{
  "abstract": [
    {
      "text": "An error that indicates an allocation fails.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_AllocationFailed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMMetadataIdentifierError_AllocationFailed@kCMMetadataIdentifierError_AllocationFailed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMMetadataIdentifierError_AllocationFailed"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMMetadataIdentifierError_AllocationFailed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMMetadataIdentifierError_AllocationFailed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifierError_AllocationFailed"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_AllocationFailed": {
      "abstract": [
        {
          "text": "An error that indicates an allocation fails.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_AllocationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_AllocationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_AllocationFailed"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifierError_AllocationFailed",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifiererror_allocationfailed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadIdentifier": {
      "abstract": [
        {
          "text": "An error that indicates the identifier isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadIdentifier"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifierError_BadIdentifier",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifiererror_badidentifier"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKey": {
      "abstract": [
        {
          "text": "An error that indicates a key isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadKey"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifierError_BadKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifiererror_badkey"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeyLength": {
      "abstract": [
        {
          "text": "An error that indicates that a key doesn’t have the correct length.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadKeyLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeyLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadKeyLength"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifierError_BadKeyLength",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifiererror_badkeylength"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeySpace": {
      "abstract": [
        {
          "text": "An error that indicates the keyspace isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadKeySpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeySpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadKeySpace"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifierError_BadKeySpace",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifiererror_badkeyspace"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeyType": {
      "abstract": [
        {
          "text": "An error that indicates a key has a bad type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadKeyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadKeyType"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifierError_BadKeyType",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifiererror_badkeytype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadNumberKey": {
      "abstract": [
        {
          "text": "An error that indicates the number for a key isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadNumberKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadNumberKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadNumberKey"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifierError_BadNumberKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifiererror_badnumberkey"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_NoKeyValueAvailable": {
      "abstract": [
        {
          "text": "An error that indicates a request for a key value in the anonymous keyspace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_NoKeyValueAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_NoKeyValueAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_NoKeyValueAvailable"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifierError_NoKeyValueAvailable",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifiererror_nokeyvalueavailable"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_RequiredParameterMissing": {
      "abstract": [
        {
          "text": "An error that indicates a parameter the function requires is empty.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_RequiredParameterMissing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_RequiredParameterMissing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_RequiredParameterMissing"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifierError_RequiredParameterMissing",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifiererror_requiredparametermissing"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadIdentifier",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKey",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeyLength",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeySpace",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeyType",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadNumberKey",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_NoKeyValueAvailable",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_RequiredParameterMissing"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMMetadataIdentifierError_AllocationFailed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifierError_AllocationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadIdentifier",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKey",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeyLength",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeySpace",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeyType",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadNumberKey",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_NoKeyValueAvailable",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_RequiredParameterMissing"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMMetadataIdentifierError_AllocationFailed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadKeySpace/title",
          "value": "kCMMetadataIdentifierError_BadKeySpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadKeySpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifierError_BadKeySpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_AllocationFailed/title",
          "value": "kCMMetadataIdentifierError_AllocationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_AllocationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifierError_AllocationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_NoKeyValueAvailable/title",
          "value": "kCMMetadataIdentifierError_NoKeyValueAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_NoKeyValueAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifierError_NoKeyValueAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadKeyType/title",
          "value": "kCMMetadataIdentifierError_BadKeyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadKeyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifierError_BadKeyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadIdentifier/title",
          "value": "kCMMetadataIdentifierError_BadIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifierError_BadIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadKeyLength/title",
          "value": "kCMMetadataIdentifierError_BadKeyLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadKeyLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifierError_BadKeyLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_RequiredParameterMissing/title",
          "value": "kCMMetadataIdentifierError_RequiredParameterMissing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_RequiredParameterMissing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifierError_RequiredParameterMissing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadNumberKey/title",
          "value": "kCMMetadataIdentifierError_BadNumberKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadNumberKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifierError_BadNumberKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadKey/title",
          "value": "kCMMetadataIdentifierError_BadKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifierError_BadKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmmetadataidentifiererror_allocationfailed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmmetadataidentifiererror_allocationfailed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
