{
  "abstract": [
    {
      "text": "64-bit big endian unsigned integer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt64"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCMMetadataBaseDataType_UInt64",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMMetadataBaseDataType_UInt64"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMMetadataBaseDataType_UInt64"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMMetadataBaseDataType_UInt64"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_UInt64"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_BMP": {
      "abstract": [
        {
          "text": "BMP image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_BMP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_BMP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_BMP"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_BMP",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_bmp"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_Float32": {
      "abstract": [
        {
          "text": "32-bit big endian floating point number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_Float32"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_Float32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_Float32"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_Float32",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_float32"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_Float64": {
      "abstract": [
        {
          "text": "64-bit big endian floating point number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_Float64"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_Float64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_Float64"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_Float64",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_float64"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_GIF": {
      "abstract": [
        {
          "text": "GIF image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_GIF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_GIF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_GIF"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_GIF",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_gif"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_JPEG": {
      "abstract": [
        {
          "text": "JPEG image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_JPEG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_JPEG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_JPEG"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_JPEG",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_jpeg"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PNG": {
      "abstract": [
        {
          "text": "PNG image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_PNG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PNG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_PNG"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_PNG",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_png"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_RawData": {
      "abstract": [
        {
          "text": "A sequence of bytes whose interpretation based upon an agreement between the reader and the writer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_RawData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_RawData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_RawData"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_RawData",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_rawdata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt16": {
      "abstract": [
        {
          "text": "16-bit big endian signed integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_SInt16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_SInt16"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_SInt16",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_sint16"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt32": {
      "abstract": [
        {
          "text": "32-bit big endian signed integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_SInt32"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_SInt32"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_SInt32",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_sint32"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt64": {
      "abstract": [
        {
          "text": "64-bit big endian signed integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_SInt64"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_SInt64"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_SInt64",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_sint64"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt8": {
      "abstract": [
        {
          "text": "8-bit signed integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_SInt8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_SInt8"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_SInt8",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_sint8"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt16": {
      "abstract": [
        {
          "text": "16-bit big endian unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UInt16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UInt16"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_UInt16",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_uint16"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt64": {
      "abstract": [
        {
          "text": "64-bit big endian unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UInt64"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UInt64"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_UInt64",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_uint64"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt8": {
      "abstract": [
        {
          "text": "8-bit unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UInt8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UInt8"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_UInt8",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_uint8"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UTF16": {
      "abstract": [
        {
          "text": "UTF-16 string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UTF16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UTF16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UTF16"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_UTF16",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_utf16"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UTF8": {
      "abstract": [
        {
          "text": "UTF-8 string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UTF8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UTF8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UTF8"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_UTF8",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_utf8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_RawData",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UTF8",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UTF16",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_GIF",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_JPEG",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PNG",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_BMP",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_Float32",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_Float64",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt8",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt16",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt32",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt64",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt8",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt16"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMMetadataBaseDataType_UInt64"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_UInt64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_RawData",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UTF8",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UTF16",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_GIF",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_JPEG",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PNG",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_BMP",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_Float32",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_Float64",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt8",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt16",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt32",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt64",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt8",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt16"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCMMetadataBaseDataType_UInt64"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_SInt64/title",
          "value": "kCMMetadataBaseDataType_SInt64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_SInt64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_SInt64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_JPEG/title",
          "value": "kCMMetadataBaseDataType_JPEG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_JPEG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_JPEG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UInt8/title",
          "value": "kCMMetadataBaseDataType_UInt8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UInt8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_UInt8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UInt64/title",
          "value": "kCMMetadataBaseDataType_UInt64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UInt64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_UInt64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_RawData/title",
          "value": "kCMMetadataBaseDataType_RawData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_RawData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_RawData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UTF16/title",
          "value": "kCMMetadataBaseDataType_UTF16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UTF16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_UTF16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UInt16/title",
          "value": "kCMMetadataBaseDataType_UInt16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UInt16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_UInt16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_GIF/title",
          "value": "kCMMetadataBaseDataType_GIF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_GIF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_GIF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_SInt8/title",
          "value": "kCMMetadataBaseDataType_SInt8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_SInt8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_SInt8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_Float32/title",
          "value": "kCMMetadataBaseDataType_Float32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_Float32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_Float32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UTF8/title",
          "value": "kCMMetadataBaseDataType_UTF8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UTF8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_UTF8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_SInt32/title",
          "value": "kCMMetadataBaseDataType_SInt32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_SInt32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_SInt32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_PNG/title",
          "value": "kCMMetadataBaseDataType_PNG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_PNG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_PNG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_SInt16/title",
          "value": "kCMMetadataBaseDataType_SInt16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_SInt16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_SInt16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_Float64/title",
          "value": "kCMMetadataBaseDataType_Float64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_Float64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_Float64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_BMP/title",
          "value": "kCMMetadataBaseDataType_BMP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_BMP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_BMP"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmmetadatabasedatatype_uint64"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmmetadatabasedatatype_uint64"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
