{
  "abstract": [
    {
      "text": "Meta data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Metadata"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMMediaType_Video@kCMMediaType_Metadata",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMMediaType_Metadata"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMMediaType",
        "text": "CMMediaType"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMMediaType_Metadata"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMMediaType_Metadata"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMMediaType_Metadata"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMediaType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMMediaType",
              "text": "CMMediaType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMediaType": {
      "abstract": [
        {
          "text": "Constants that represent media types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMediaType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMediaType"
        }
      ],
      "role": "symbol",
      "title": "CMMediaType",
      "type": "topic",
      "url": "/documentation/coremedia/cmmediatype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Audio": {
      "abstract": [
        {
          "text": "Audio media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMediaType_Audio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMediaType",
          "text": "CMMediaType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Audio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMediaType_Audio"
        }
      ],
      "role": "symbol",
      "title": "kCMMediaType_Audio",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmediatype_audio"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_AuxiliaryPicture": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMediaType_AuxiliaryPicture"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMediaType",
          "text": "CMMediaType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_AuxiliaryPicture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMediaType_AuxiliaryPicture"
        }
      ],
      "role": "symbol",
      "title": "kCMMediaType_AuxiliaryPicture",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmediatype_auxiliarypicture"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_ClosedCaption": {
      "abstract": [
        {
          "text": "Closed-caption media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMediaType_ClosedCaption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMediaType",
          "text": "CMMediaType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_ClosedCaption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMediaType_ClosedCaption"
        }
      ],
      "role": "symbol",
      "title": "kCMMediaType_ClosedCaption",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmediatype_closedcaption"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Metadata": {
      "abstract": [
        {
          "text": "Meta data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMediaType_Metadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMediaType",
          "text": "CMMediaType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Metadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMediaType_Metadata"
        }
      ],
      "role": "symbol",
      "title": "kCMMediaType_Metadata",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmediatype_metadata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Muxed": {
      "abstract": [
        {
          "text": "Muxed media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMediaType_Muxed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMediaType",
          "text": "CMMediaType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Muxed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMediaType_Muxed"
        }
      ],
      "role": "symbol",
      "title": "kCMMediaType_Muxed",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmediatype_muxed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Subtitle": {
      "abstract": [
        {
          "text": "Subtitle media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMediaType_Subtitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMediaType",
          "text": "CMMediaType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Subtitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMediaType_Subtitle"
        }
      ],
      "role": "symbol",
      "title": "kCMMediaType_Subtitle",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmediatype_subtitle"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_TaggedBufferGroup": {
      "abstract": [
        {
          "text": "Media containing a tagged buffer group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMediaType_TaggedBufferGroup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMediaType",
          "text": "CMMediaType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_TaggedBufferGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMediaType_TaggedBufferGroup"
        }
      ],
      "role": "symbol",
      "title": "kCMMediaType_TaggedBufferGroup",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmediatype_taggedbuffergroup"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Text": {
      "abstract": [
        {
          "text": "Text media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMediaType_Text"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMediaType",
          "text": "CMMediaType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Text",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMediaType_Text"
        }
      ],
      "role": "symbol",
      "title": "kCMMediaType_Text",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmediatype_text"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_TimeCode": {
      "abstract": [
        {
          "text": "Time code media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMediaType_TimeCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMediaType",
          "text": "CMMediaType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_TimeCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMediaType_TimeCode"
        }
      ],
      "role": "symbol",
      "title": "kCMMediaType_TimeCode",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmediatype_timecode"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Video": {
      "abstract": [
        {
          "text": "Video media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMediaType_Video"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMediaType",
          "text": "CMMediaType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Video",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMediaType_Video"
        }
      ],
      "role": "symbol",
      "title": "kCMMediaType_Video",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmediatype_video"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Audio",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_AuxiliaryPicture",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_ClosedCaption",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Muxed",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Subtitle",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Text",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_TimeCode",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Video",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_TaggedBufferGroup"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMMediaType_Metadata"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMediaType_Metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Audio",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_AuxiliaryPicture",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_ClosedCaption",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Muxed",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Subtitle",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Text",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_TimeCode",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_Video",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMediaType_TaggedBufferGroup"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMMediaType_Metadata"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMediaType_Video/title",
          "value": "kCMMediaType_Video"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMediaType_Video/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMediaType_Video"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMediaType_AuxiliaryPicture/title",
          "value": "kCMMediaType_AuxiliaryPicture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMediaType_AuxiliaryPicture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMediaType_AuxiliaryPicture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMediaType_Audio/title",
          "value": "kCMMediaType_Audio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMediaType_Audio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMediaType_Audio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMediaType_Text/title",
          "value": "kCMMediaType_Text"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMediaType_Text/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMediaType_Text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMediaType_TaggedBufferGroup/title",
          "value": "kCMMediaType_TaggedBufferGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMediaType_TaggedBufferGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMediaType_TaggedBufferGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMediaType_ClosedCaption/title",
          "value": "kCMMediaType_ClosedCaption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMediaType_ClosedCaption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMediaType_ClosedCaption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMediaType/title",
          "value": "CMMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMediaType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMediaType_Subtitle/title",
          "value": "kCMMediaType_Subtitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMediaType_Subtitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMediaType_Subtitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMediaType_Muxed/title",
          "value": "kCMMediaType_Muxed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMediaType_Muxed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMediaType_Muxed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMediaType_TimeCode/title",
          "value": "kCMMediaType_TimeCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMediaType_TimeCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMediaType_TimeCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMediaType_Metadata/title",
          "value": "kCMMediaType_Metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMediaType_Metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMediaType_Metadata"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmmediatype_metadata"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmmediatype_metadata"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
