{
  "abstract": [
    {
      "text": "The duration that should be removed at the end of the sample buffer, after decoding.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_TrimDurationAtEnd"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCMSampleBufferAttachmentKey_TrimDurationAtEnd",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMSampleBufferAttachmentKey_TrimDurationAtEnd"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMSampleBufferAttachmentKey_TrimDurationAtEnd"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMSampleBufferAttachmentKey_TrimDurationAtEnd"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_TrimDurationAtEnd"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If this attachment is not present, the trim duration is zero (nothing removed).        This is a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTime",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in Core Foundation dictionary format as made by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCopyAsDictionary(_:allocator:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ";         use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMakeFromDictionary(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to convert to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTime",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTime": {
      "abstract": [
        {
          "text": "A structure that represents time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTime"
        }
      ],
      "role": "symbol",
      "title": "CMTime",
      "type": "topic",
      "url": "/documentation/coremedia/cmtime"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCopyAsDictionary(_:allocator:)": {
      "abstract": [
        {
          "text": "Creates a dictionary representation of the time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeCopyAsDictionary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAllocatorRef",
          "text": "CFAllocator"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCopyAsDictionary(_:allocator:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeCopyAsDictionary"
        }
      ],
      "role": "symbol",
      "title": "CMTimeCopyAsDictionary(_:allocator:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimecopyasdictionary(_:allocator:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMakeFromDictionary(_:)": {
      "abstract": [
        {
          "text": "Creates a time from a dictionary representation of its fields.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeMakeFromDictionary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMakeFromDictionary(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeMakeFromDictionary"
        }
      ],
      "role": "symbol",
      "title": "CMTimeMakeFromDictionary(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimemakefromdictionary(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately": {
      "abstract": [
        {
          "text": "Tells that the empty marker should be dequeued immediately regardless of its timestamp (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_displayemptymediaimmediately"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DrainAfterDecoding": {
      "abstract": [
        {
          "text": "Indicates whether the sample buffer should be drained after decoding type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_DrainAfterDecoding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DrainAfterDecoding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_DrainAfterDecoding"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_DrainAfterDecoding",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_drainafterdecoding"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DroppedFrameReason": {
      "abstract": [
        {
          "text": "Indicates the reason the current video frame was dropped (type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_DroppedFrameReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DroppedFrameReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_DroppedFrameReason"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_DroppedFrameReason",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_droppedframereason"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo": {
      "abstract": [
        {
          "text": "Indicates additional information regarding the dropped video frame (type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_droppedframereasoninfo"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_EmptyMedia": {
      "abstract": [
        {
          "text": "Marks an intentionally empty interval in the sequence of samples (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_EmptyMedia"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_EmptyMedia",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_EmptyMedia"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_EmptyMedia",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_emptymedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration": {
      "abstract": [
        {
          "text": "Indicates that sample buffer’s decode timestamp may be used to define the previous sample buffer’s duration (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_endsprevioussampleduration"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence": {
      "abstract": [
        {
          "text": "Fill the difference between discontiguous sample buffers with silence (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_filldiscontinuitieswithsilence"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_ForceKeyFrame": {
      "abstract": [
        {
          "text": "Indicates that the current or next video sample buffer should be forced to be encoded as a key frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_ForceKeyFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_ForceKeyFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_ForceKeyFrame"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_ForceKeyFrame",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_forcekeyframe"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_GradualDecoderRefresh": {
      "abstract": [
        {
          "text": "Indicates the decoder refresh count (type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_GradualDecoderRefresh"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_GradualDecoderRefresh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_GradualDecoderRefresh"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_GradualDecoderRefresh",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_gradualdecoderrefresh"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_PermanentEmptyMedia": {
      "abstract": [
        {
          "text": "Marks the end of the sequence of samples (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_PermanentEmptyMedia"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_PermanentEmptyMedia",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_PermanentEmptyMedia"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_PermanentEmptyMedia",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_permanentemptymedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed": {
      "abstract": [
        {
          "text": "If present, indicates that decode pipelines should post a notification when consuming the sample buffer(type ",
          "type": "text"
        },
        {
          "code": "CFDictionary",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_postnotificationwhenconsumed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_TrimDurationAtEnd": {
      "abstract": [
        {
          "text": "The duration that should be removed at the end of the sample buffer, after decoding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_TrimDurationAtEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_TrimDurationAtEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_TrimDurationAtEnd"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_TrimDurationAtEnd",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_trimdurationatend"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch": {
      "abstract": [
        {
          "text": "A discontinuity was caused by a camera mode switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferdroppedframereasoninfo_cameramodeswitch"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_Discontinuity": {
      "abstract": [
        {
          "text": "An unknown number of frames were dropped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferDroppedFrameReason_Discontinuity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_Discontinuity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferDroppedFrameReason_Discontinuity"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferDroppedFrameReason_Discontinuity",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferdroppedframereason_discontinuity"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_FrameWasLate": {
      "abstract": [
        {
          "text": "The frame was dropped because it was late.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferDroppedFrameReason_FrameWasLate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_FrameWasLate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferDroppedFrameReason_FrameWasLate"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferDroppedFrameReason_FrameWasLate",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferdroppedframereason_framewaslate"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_OutOfBuffers": {
      "abstract": [
        {
          "text": "The frame was dropped because the module providing frames is out of buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferDroppedFrameReason_OutOfBuffers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_OutOfBuffers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferDroppedFrameReason_OutOfBuffers"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferDroppedFrameReason_OutOfBuffers",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferdroppedframereason_outofbuffers"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sample-Buffer-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DrainAfterDecoding",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DroppedFrameReason",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_FrameWasLate",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_OutOfBuffers",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_Discontinuity",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_EmptyMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_ForceKeyFrame",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_GradualDecoderRefresh",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_PermanentEmptyMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed"
      ],
      "title": "Sample Buffer Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMSampleBufferAttachmentKey_TrimDurationAtEnd"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_TrimDurationAtEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sample-Buffer-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DrainAfterDecoding",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DroppedFrameReason",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_FrameWasLate",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_OutOfBuffers",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_Discontinuity",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_EmptyMedia",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_ForceKeyFrame",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_GradualDecoderRefresh",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_PermanentEmptyMedia",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed"
              ],
              "title": "Sample Buffer Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCMSampleBufferAttachmentKey_TrimDurationAtEnd"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferDroppedFrameReason_Discontinuity/title",
          "value": "kCMSampleBufferDroppedFrameReason_Discontinuity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferDroppedFrameReason_Discontinuity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferDroppedFrameReason_Discontinuity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeMakeFromDictionary(_:)/title",
          "value": "CMTimeMakeFromDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeMakeFromDictionary(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeMakeFromDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_ForceKeyFrame/title",
          "value": "kCMSampleBufferAttachmentKey_ForceKeyFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_ForceKeyFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_ForceKeyFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferDroppedFrameReason_FrameWasLate/title",
          "value": "kCMSampleBufferDroppedFrameReason_FrameWasLate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferDroppedFrameReason_FrameWasLate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferDroppedFrameReason_FrameWasLate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence/title",
          "value": "kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_DroppedFrameReason/title",
          "value": "kCMSampleBufferAttachmentKey_DroppedFrameReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_DroppedFrameReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_DroppedFrameReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_PermanentEmptyMedia/title",
          "value": "kCMSampleBufferAttachmentKey_PermanentEmptyMedia"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_PermanentEmptyMedia/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_PermanentEmptyMedia"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed/title",
          "value": "kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch/title",
          "value": "kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferDroppedFrameReason_OutOfBuffers/title",
          "value": "kCMSampleBufferDroppedFrameReason_OutOfBuffers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferDroppedFrameReason_OutOfBuffers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferDroppedFrameReason_OutOfBuffers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration/title",
          "value": "kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo/title",
          "value": "kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_DrainAfterDecoding/title",
          "value": "kCMSampleBufferAttachmentKey_DrainAfterDecoding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_DrainAfterDecoding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_DrainAfterDecoding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime/title",
          "value": "CMTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTime/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately/title",
          "value": "kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_TrimDurationAtEnd/title",
          "value": "kCMSampleBufferAttachmentKey_TrimDurationAtEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_TrimDurationAtEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_TrimDurationAtEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_EmptyMedia/title",
          "value": "kCMSampleBufferAttachmentKey_EmptyMedia"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_EmptyMedia/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_EmptyMedia"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_GradualDecoderRefresh/title",
          "value": "kCMSampleBufferAttachmentKey_GradualDecoderRefresh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_GradualDecoderRefresh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_GradualDecoderRefresh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeCopyAsDictionary(_:allocator:)/title",
          "value": "CMTimeCopyAsDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeCopyAsDictionary(_:allocator:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeCopyAsDictionary"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmsamplebufferattachmentkey_trimdurationatend"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmsamplebufferattachmentkey_trimdurationatend"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
