{
  "abstract": [
    {
      "text": "An error code that indicates a sample buffer failed to load its data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_DataFailed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMSampleBufferError_AllocationFailed@kCMSampleBufferError_DataFailed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMSampleBufferError_DataFailed"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@OSStatus",
        "text": "OSStatus"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMSampleBufferError_DataFailed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMSampleBufferError_DataFailed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMSampleBufferError_DataFailed"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_AllocationFailed": {
      "abstract": [
        {
          "text": "An error code that indicates the system failed to allocate memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_AllocationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_AllocationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_AllocationFailed"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferError_AllocationFailed",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebuffererror_allocationfailed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_AlreadyHasDataBuffer": {
      "abstract": [
        {
          "text": "An error code that indicates an attempt to set data on a sample buffer failed because that buffer already contains media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_AlreadyHasDataBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_AlreadyHasDataBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_AlreadyHasDataBuffer"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferError_AlreadyHasDataBuffer",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebuffererror_alreadyhasdatabuffer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_ArrayTooSmall": {
      "abstract": [
        {
          "text": "An error code that indicates the output array isn’t large enough to hold the requested array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_ArrayTooSmall"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_ArrayTooSmall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_ArrayTooSmall"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferError_ArrayTooSmall",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebuffererror_arraytoosmall"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_BufferHasNoSampleSizes": {
      "abstract": [
        {
          "text": "An error code that indicates a request for sample sizes on a buffer failed because the buffer doesn’t provide that information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_BufferHasNoSampleSizes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_BufferHasNoSampleSizes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_BufferHasNoSampleSizes"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferError_BufferHasNoSampleSizes",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebuffererror_bufferhasnosamplesizes"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_BufferHasNoSampleTimingInfo": {
      "abstract": [
        {
          "text": "An error code that indicates a request for sample timing on a buffer failed because the buffer doesn’t contain that information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_BufferHasNoSampleTimingInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_BufferHasNoSampleTimingInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_BufferHasNoSampleTimingInfo"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferError_BufferHasNoSampleTimingInfo",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebuffererror_bufferhasnosampletiminginfo"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_BufferNotReady": {
      "abstract": [
        {
          "text": "An error code that indicates the system can’t make the buffer’s data ready for use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_BufferNotReady"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_BufferNotReady",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_BufferNotReady"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferError_BufferNotReady",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebuffererror_buffernotready"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_CannotSubdivide": {
      "abstract": [
        {
          "text": "An error code that indicates a sample buffer doesn’t contain sample sizes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_CannotSubdivide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_CannotSubdivide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_CannotSubdivide"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferError_CannotSubdivide",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebuffererror_cannotsubdivide"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_DataCanceled": {
      "abstract": [
        {
          "text": "An error code that indicates a sample buffer canceled its data-loading operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_DataCanceled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_DataCanceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_DataCanceled"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferError_DataCanceled",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebuffererror_datacanceled"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_DataFailed": {
      "abstract": [
        {
          "text": "An error code that indicates a sample buffer failed to load its data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_DataFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_DataFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_DataFailed"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferError_DataFailed",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebuffererror_datafailed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_InvalidEntryCount": {
      "abstract": [
        {
          "text": "An error code that indicates a timing or size value isn’t within the allowed range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_InvalidEntryCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_InvalidEntryCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_InvalidEntryCount"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferError_InvalidEntryCount",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebuffererror_invalidentrycount"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_InvalidMediaFormat": {
      "abstract": [
        {
          "text": "An error code that indicates the media format doesn’t match the sample buffer’s format description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_InvalidMediaFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_InvalidMediaFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_InvalidMediaFormat"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferError_InvalidMediaFormat",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebuffererror_invalidmediaformat"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_InvalidMediaTypeForOperation": {
      "abstract": [
        {
          "text": "An error code that indicates the media type that the format description defines isn’t a value for the requested operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_InvalidMediaTypeForOperation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_InvalidMediaTypeForOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_InvalidMediaTypeForOperation"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferError_InvalidMediaTypeForOperation",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebuffererror_invalidmediatypeforoperation"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_InvalidSampleData": {
      "abstract": [
        {
          "text": "An error code that indicates the sample buffer contains bad data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_InvalidSampleData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_InvalidSampleData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_InvalidSampleData"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferError_InvalidSampleData",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebuffererror_invalidsampledata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_Invalidated": {
      "abstract": [
        {
          "text": "An error code that indicates a sample buffer invalidated its data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_Invalidated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_Invalidated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_Invalidated"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferError_Invalidated",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebuffererror_invalidated"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_RequiredParameterMissing": {
      "abstract": [
        {
          "text": "An error code that indicates a required parameter’s value is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_RequiredParameterMissing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_RequiredParameterMissing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_RequiredParameterMissing"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferError_RequiredParameterMissing",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebuffererror_requiredparametermissing"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_SampleIndexOutOfRange": {
      "abstract": [
        {
          "text": "An error code that indicates the sample index is outside the range of samples that the buffer contains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_SampleIndexOutOfRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_SampleIndexOutOfRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferError_SampleIndexOutOfRange"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferError_SampleIndexOutOfRange",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebuffererror_sampleindexoutofrange"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_AllocationFailed",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_AlreadyHasDataBuffer",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_ArrayTooSmall",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_BufferHasNoSampleSizes",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_BufferHasNoSampleTimingInfo",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_BufferNotReady",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_CannotSubdivide",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_DataCanceled",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_InvalidEntryCount",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_InvalidMediaFormat",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_InvalidMediaTypeForOperation",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_InvalidSampleData",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_Invalidated",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_RequiredParameterMissing",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_SampleIndexOutOfRange"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMSampleBufferError_DataFailed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferError_DataFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_AllocationFailed",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_AlreadyHasDataBuffer",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_ArrayTooSmall",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_BufferHasNoSampleSizes",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_BufferHasNoSampleTimingInfo",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_BufferNotReady",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_CannotSubdivide",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_DataCanceled",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_InvalidEntryCount",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_InvalidMediaFormat",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_InvalidMediaTypeForOperation",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_InvalidSampleData",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_Invalidated",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_RequiredParameterMissing",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferError_SampleIndexOutOfRange"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMSampleBufferError_DataFailed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_BufferNotReady/title",
          "value": "kCMSampleBufferError_BufferNotReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_BufferNotReady/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferError_BufferNotReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_SampleIndexOutOfRange/title",
          "value": "kCMSampleBufferError_SampleIndexOutOfRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_SampleIndexOutOfRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferError_SampleIndexOutOfRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_AllocationFailed/title",
          "value": "kCMSampleBufferError_AllocationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_AllocationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferError_AllocationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_BufferHasNoSampleTimingInfo/title",
          "value": "kCMSampleBufferError_BufferHasNoSampleTimingInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_BufferHasNoSampleTimingInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferError_BufferHasNoSampleTimingInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_InvalidMediaTypeForOperation/title",
          "value": "kCMSampleBufferError_InvalidMediaTypeForOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_InvalidMediaTypeForOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferError_InvalidMediaTypeForOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_AlreadyHasDataBuffer/title",
          "value": "kCMSampleBufferError_AlreadyHasDataBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_AlreadyHasDataBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferError_AlreadyHasDataBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_InvalidSampleData/title",
          "value": "kCMSampleBufferError_InvalidSampleData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_InvalidSampleData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferError_InvalidSampleData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_CannotSubdivide/title",
          "value": "kCMSampleBufferError_CannotSubdivide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_CannotSubdivide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferError_CannotSubdivide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_DataCanceled/title",
          "value": "kCMSampleBufferError_DataCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_DataCanceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferError_DataCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_DataFailed/title",
          "value": "kCMSampleBufferError_DataFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_DataFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferError_DataFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_InvalidEntryCount/title",
          "value": "kCMSampleBufferError_InvalidEntryCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_InvalidEntryCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferError_InvalidEntryCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_ArrayTooSmall/title",
          "value": "kCMSampleBufferError_ArrayTooSmall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_ArrayTooSmall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferError_ArrayTooSmall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_RequiredParameterMissing/title",
          "value": "kCMSampleBufferError_RequiredParameterMissing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_RequiredParameterMissing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferError_RequiredParameterMissing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_BufferHasNoSampleSizes/title",
          "value": "kCMSampleBufferError_BufferHasNoSampleSizes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_BufferHasNoSampleSizes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferError_BufferHasNoSampleSizes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_InvalidMediaFormat/title",
          "value": "kCMSampleBufferError_InvalidMediaFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_InvalidMediaFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferError_InvalidMediaFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_Invalidated/title",
          "value": "kCMSampleBufferError_Invalidated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferError_Invalidated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferError_Invalidated"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmsamplebuffererror_datafailed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmsamplebuffererror_datafailed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
