{
  "abstract": [
    {
      "text": "Indicates whether the sample is a sync sample (type ",
      "type": "text"
    },
    {
      "code": "CFBoolean",
      "type": "codeVoice"
    },
    {
      "text": ", default false).",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_NotSync"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCMSampleAttachmentKey_NotSync",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMSampleAttachmentKey_NotSync"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMSampleAttachmentKey_NotSync"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMSampleAttachmentKey_NotSync"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_NotSync"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A sync sample, also known as a key frame or IDR (Instantaneous Decoding Refresh), can be decoded without requiring any previous samples to have been decoded. Samples following a sync sample also do not require samples prior to the sync sample to have been decoded. Samples are assumed to be sync samples by default — set the value for this key to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for samples which should not be treated as sync samples.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This attachment is read from and written to media files.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DependsOnOthers": {
      "abstract": [
        {
          "text": "Indicates whether the sample depends on other samples for decoding (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_DependsOnOthers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DependsOnOthers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_DependsOnOthers"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_DependsOnOthers",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_dependsonothers"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DisplayImmediately": {
      "abstract": [
        {
          "text": "Indicates whether the sample should be displayed immediately (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_DisplayImmediately"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DisplayImmediately",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_DisplayImmediately"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_DisplayImmediately",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_displayimmediately"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DoNotDisplay": {
      "abstract": [
        {
          "text": "Indicates whether the sample should be decoded but not displayed (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_DoNotDisplay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DoNotDisplay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_DoNotDisplay"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_DoNotDisplay",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_donotdisplay"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_EarlierDisplayTimesAllowed": {
      "abstract": [
        {
          "text": "Indicates whether later samples may have earlier display times (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_EarlierDisplayTimesAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_EarlierDisplayTimesAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_EarlierDisplayTimesAllowed"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_EarlierDisplayTimesAllowed",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_earlierdisplaytimesallowed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HasRedundantCoding": {
      "abstract": [
        {
          "text": "Indicates whether the sample has redundant coding (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HasRedundantCoding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HasRedundantCoding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HasRedundantCoding"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_HasRedundantCoding",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_hasredundantcoding"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_IsDependedOnByOthers": {
      "abstract": [
        {
          "text": "Indicates whether other samples depend on this sample for decoding (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_IsDependedOnByOthers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_IsDependedOnByOthers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_IsDependedOnByOthers"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_IsDependedOnByOthers",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_isdependedonbyothers"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_NotSync": {
      "abstract": [
        {
          "text": "Indicates whether the sample is a sync sample (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_NotSync"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_NotSync",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_NotSync"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_NotSync",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_notsync"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_PartialSync": {
      "abstract": [
        {
          "text": "Indicates whether the sample is a partial sync sample (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_PartialSync"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_PartialSync",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_PartialSync"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_PartialSync",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_partialsync"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_PostDecodeProcessingMetadata": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_PostDecodeProcessingMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_PostDecodeProcessingMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_PostDecodeProcessingMetadata"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_PostDecodeProcessingMetadata",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_postdecodeprocessingmetadata"
    },
    "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue": {
      "abstract": [
        {
          "text": "Boolean true value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCFBooleanTrue"
        },
        {
          "kind": "text",
          "text": ": CFBoolean!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/kcfbooleantrue",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCFBooleanTrue",
      "type": "topic",
      "url": "/documentation/corefoundation/kcfbooleantrue"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sample-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_PartialSync",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DependsOnOthers",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_IsDependedOnByOthers",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DisplayImmediately",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DoNotDisplay",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_EarlierDisplayTimesAllowed",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HasRedundantCoding",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_PostDecodeProcessingMetadata"
      ],
      "title": "Sample Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMSampleAttachmentKey_NotSync"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_NotSync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sample-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_PartialSync",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DependsOnOthers",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_IsDependedOnByOthers",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DisplayImmediately",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DoNotDisplay",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_EarlierDisplayTimesAllowed",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HasRedundantCoding",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_PostDecodeProcessingMetadata"
              ],
              "title": "Sample Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCMSampleAttachmentKey_NotSync"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_EarlierDisplayTimesAllowed/title",
          "value": "kCMSampleAttachmentKey_EarlierDisplayTimesAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_EarlierDisplayTimesAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_EarlierDisplayTimesAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_PartialSync/title",
          "value": "kCMSampleAttachmentKey_PartialSync"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_PartialSync/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_PartialSync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_PostDecodeProcessingMetadata/title",
          "value": "kCMSampleAttachmentKey_PostDecodeProcessingMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_PostDecodeProcessingMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_PostDecodeProcessingMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_DoNotDisplay/title",
          "value": "kCMSampleAttachmentKey_DoNotDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_DoNotDisplay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_DoNotDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_DependsOnOthers/title",
          "value": "kCMSampleAttachmentKey_DependsOnOthers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_DependsOnOthers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_DependsOnOthers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_DisplayImmediately/title",
          "value": "kCMSampleAttachmentKey_DisplayImmediately"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_DisplayImmediately/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_DisplayImmediately"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HasRedundantCoding/title",
          "value": "kCMSampleAttachmentKey_HasRedundantCoding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HasRedundantCoding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_HasRedundantCoding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_NotSync/title",
          "value": "kCMSampleAttachmentKey_NotSync"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_NotSync/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_NotSync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_IsDependedOnByOthers/title",
          "value": "kCMSampleAttachmentKey_IsDependedOnByOthers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_IsDependedOnByOthers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_IsDependedOnByOthers"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmsampleattachmentkey_notsync"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmsampleattachmentkey_notsync"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
