{
  "abstract": [
    {
      "text": "An attachment that’s only present if the audio sample is an independent frame or immediate playout frame.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMAttachmentMode_ShouldNotPropagate": {
      "abstract": [
        {
          "text": "A mode that doesn’t propagate attachments to another object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMAttachmentMode_ShouldNotPropagate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentMode",
          "text": "CMAttachmentMode"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMAttachmentMode_ShouldNotPropagate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMAttachmentMode_ShouldNotPropagate"
        }
      ],
      "role": "symbol",
      "title": "kCMAttachmentMode_ShouldNotPropagate",
      "type": "topic",
      "url": "/documentation/coremedia/kcmattachmentmode_shouldnotpropagate"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMAttachmentMode_ShouldPropagate": {
      "abstract": [
        {
          "text": "A mode that propagates attachments to another object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMAttachmentMode_ShouldPropagate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMAttachmentMode",
          "text": "CMAttachmentMode"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMAttachmentMode_ShouldPropagate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMAttachmentMode_ShouldPropagate"
        }
      ],
      "role": "symbol",
      "title": "kCMAttachmentMode_ShouldPropagate",
      "type": "topic",
      "url": "/documentation/coremedia/kcmattachmentmode_shouldpropagate"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount": {
      "abstract": [
        {
          "text": "An attachment that’s only present if the audio sample is an independent frame or immediate playout frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_audioindependentsampledecoderrefreshcount"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData": {
      "abstract": [
        {
          "text": "An attachment that describes the ranges of protected and unprotected data within a protected sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_cryptorsubsampleauxiliarydata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess": {
      "abstract": [
        {
          "text": "An attachment that indicates a step-wise temporal sublayer access (STSA) sample grouping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_hevcstepwisetemporalsublayeraccess"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType": {
      "abstract": [
        {
          "text": "An attachment that indicates a sync sample NAL unit type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_hevcsyncsamplenalunittype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCTemporalLevelInfo": {
      "abstract": [
        {
          "text": "An attachment that indicates a video frame’s level within a hierarchical frame dependency structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HEVCTemporalLevelInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCTemporalLevelInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HEVCTemporalLevelInfo"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_HEVCTemporalLevelInfo",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_hevctemporallevelinfo"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess": {
      "abstract": [
        {
          "text": "An attachment that indicates a temporal sublayer access grouping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_hevctemporalsublayeraccess"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix": {
      "abstract": [
        {
          "text": "An attachment that indicates a 3x3 camera intrinsic matrix to apply to the current sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_cameraintrinsicmatrix"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMAttachmentMode_ShouldNotPropagate",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMAttachmentMode_ShouldPropagate",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCTemporalLevelInfo",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMAttachmentMode_ShouldNotPropagate",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMAttachmentMode_ShouldPropagate",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCTemporalLevelInfo",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix/title",
          "value": "kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_CameraIntrinsicMatrix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess/title",
          "value": "kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_HEVCStepwiseTemporalSubLayerAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount/title",
          "value": "kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_AudioIndependentSampleDecoderRefreshCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData/title",
          "value": "kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_CryptorSubsampleAuxiliaryData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HEVCTemporalLevelInfo/title",
          "value": "kCMSampleAttachmentKey_HEVCTemporalLevelInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HEVCTemporalLevelInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_HEVCTemporalLevelInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType/title",
          "value": "kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_HEVCSyncSampleNALUnitType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMAttachmentMode_ShouldPropagate/title",
          "value": "kCMAttachmentMode_ShouldPropagate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMAttachmentMode_ShouldPropagate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMAttachmentMode_ShouldPropagate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess/title",
          "value": "kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_HEVCTemporalSubLayerAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMAttachmentMode_ShouldNotPropagate/title",
          "value": "kCMAttachmentMode_ShouldNotPropagate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMAttachmentMode_ShouldNotPropagate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMAttachmentMode_ShouldNotPropagate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmsampleattachmentkey_audioindependentsampledecoderrefreshcount"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmsampleattachmentkey_audioindependentsampledecoderrefreshcount"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
