{
  "abstract": [
    {
      "text": "Specifies the minimum presentation timestamp of upcoming output samples (type ",
      "type": "text"
    },
    {
      "code": "CFDictionary",
      "type": "codeVoice"
    },
    {
      "text": ").",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This key may be present in the ",
              "type": "text"
            },
            {
              "code": "userInfo",
              "type": "codeVoice"
            },
            {
              "text": " dictionary for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " notification in cases where upcoming frames may have earlier timestamps than those previously provided. Its value is the ",
              "type": "text"
            },
            {
              "code": "CFDictionary",
              "type": "codeVoice"
            },
            {
              "text": " representation of a ",
              "type": "text"
            },
            {
              "code": "CMTime",
              "type": "codeVoice"
            },
            {
              "text": " object (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMakeFromDictionary(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Either this key or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " may be omitted to leave the range open-ended.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMakeFromDictionary(_:)": {
      "abstract": [
        {
          "text": "Creates a time from a dictionary representation of its fields.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeMakeFromDictionary"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeMakeFromDictionary(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeMakeFromDictionary"
        }
      ],
      "role": "symbol",
      "title": "CMTimeMakeFromDictionary(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimemakefromdictionary(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS": {
      "abstract": [
        {
          "text": "Specifies the maximum presentation timestamp of upcoming output samples (type ",
          "type": "text"
        },
        {
          "code": "CFDictionary",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferconduitnotificationparameter_maxupcomingoutputpts"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS": {
      "abstract": [
        {
          "text": "Specifies the minimum presentation timestamp of upcoming output samples (type ",
          "type": "text"
        },
        {
          "code": "CFDictionary",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferconduitnotificationparameter_minupcomingoutputpts"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_ResumeTag": {
      "abstract": [
        {
          "text": "Specifies a tag to be attached to the first sample buffer following a discontinuity (type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotificationParameter_ResumeTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_ResumeTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotificationParameter_ResumeTag"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferConduitNotificationParameter_ResumeTag",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferconduitnotificationparameter_resumetag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange": {
      "abstract": [
        {
          "text": "Indicates that the presentation timestamps of upcoming output samples may overlap those of samples queued for output (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferconduitnotificationparameter_upcomingoutputptsrangemayoverlapqueuedoutputptsrange"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_InhibitOutputUntil": {
      "abstract": [
        {
          "text": "Posted on a conduit of sample buffers to announce a coming discontinuity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotification_InhibitOutputUntil"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_InhibitOutputUntil",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotification_InhibitOutputUntil"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferConduitNotification_InhibitOutputUntil",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferconduitnotification_inhibitoutputuntil"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_ResetOutput": {
      "abstract": [
        {
          "text": "Posted on a conduit of sample buffers to request invalidation of pending output data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotification_ResetOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_ResetOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotification_ResetOutput"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferConduitNotification_ResetOutput",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferconduitnotification_resetoutput"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged": {
      "abstract": [
        {
          "text": "Posted on a conduit of video sample buffers to report information about the range of upcoming output presentation timestamps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferconduitnotification_upcomingoutputptsrangechanged"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sample-Buffer-Conduit-Notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_ResetOutput",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_InhibitOutputUntil",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_ResumeTag"
      ],
      "title": "Sample Buffer Conduit Notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sample-Buffer-Conduit-Notifications",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_ResetOutput",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_InhibitOutputUntil",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_ResumeTag"
              ],
              "title": "Sample Buffer Conduit Notifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange/title",
          "value": "kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeMakeFromDictionary(_:)/title",
          "value": "CMTimeMakeFromDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeMakeFromDictionary(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeMakeFromDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged/title",
          "value": "kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotificationParameter_ResumeTag/title",
          "value": "kCMSampleBufferConduitNotificationParameter_ResumeTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotificationParameter_ResumeTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferConduitNotificationParameter_ResumeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS/title",
          "value": "kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS/title",
          "value": "kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotification_ResetOutput/title",
          "value": "kCMSampleBufferConduitNotification_ResetOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotification_ResetOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferConduitNotification_ResetOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotification_InhibitOutputUntil/title",
          "value": "kCMSampleBufferConduitNotification_InhibitOutputUntil"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotification_InhibitOutputUntil/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferConduitNotification_InhibitOutputUntil"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmsamplebufferconduitnotificationparameter_minupcomingoutputpts"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmsamplebufferconduitnotificationparameter_minupcomingoutputpts"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
