{
  "abstract": [
    {
      "text": "A generic font family name identifier.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_GenericFontFamilyName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCMTextMarkupAttribute_GenericFontFamilyName",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMTextMarkupAttribute_GenericFontFamilyName"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMTextMarkupAttribute_GenericFontFamilyName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMTextMarkupAttribute_GenericFontFamilyName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_GenericFontFamilyName"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This attribute’s value must be one of the constants listed below. You need to map generic fonts to the family name of an installed font before rendering and/or measuring text (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MediaAccessibility",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When the system specifies legible output, an attributed string has at most one of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_FontFamilyName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_GenericFontFamilyName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " associated with each character.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight": {
      "abstract": [
        {
          "text": "A base font size as a percentage of the video height.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_basefontsizepercentagerelativetovideoheight"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_FontFamilyName": {
      "abstract": [
        {
          "text": "A name of a font family.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_FontFamilyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_FontFamilyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_FontFamilyName"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_FontFamilyName",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_fontfamilyname"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_GenericFontFamilyName": {
      "abstract": [
        {
          "text": "A generic font family name identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_GenericFontFamilyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_GenericFontFamilyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_GenericFontFamilyName"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_GenericFontFamilyName",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_genericfontfamilyname"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_RelativeFontSize": {
      "abstract": [
        {
          "text": "A font size as a percentage of the current default font size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_RelativeFontSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_RelativeFontSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_RelativeFontSize"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_RelativeFontSize",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_relativefontsize"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Casual": {
      "abstract": [
        {
          "text": "A casual font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_Casual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Casual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_Casual"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupGenericFontName_Casual",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupgenericfontname_casual"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Cursive": {
      "abstract": [
        {
          "text": "A cursive font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_Cursive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Cursive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_Cursive"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupGenericFontName_Cursive",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupgenericfontname_cursive"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Default": {
      "abstract": [
        {
          "text": "The default font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_Default"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_Default"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupGenericFontName_Default",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupgenericfontname_default"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Fantasy": {
      "abstract": [
        {
          "text": "A fantasy font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_Fantasy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Fantasy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_Fantasy"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupGenericFontName_Fantasy",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupgenericfontname_fantasy"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Monospace": {
      "abstract": [
        {
          "text": "A monospaced font with or without serifs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_Monospace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Monospace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_Monospace"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupGenericFontName_Monospace",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupgenericfontname_monospace"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_MonospaceSansSerif": {
      "abstract": [
        {
          "text": "A monospaced font without serifs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_MonospaceSansSerif"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_MonospaceSansSerif",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_MonospaceSansSerif"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupGenericFontName_MonospaceSansSerif",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupgenericfontname_monospacesansserif"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_MonospaceSerif": {
      "abstract": [
        {
          "text": "A monospaced font with serifs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_MonospaceSerif"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_MonospaceSerif",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_MonospaceSerif"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupGenericFontName_MonospaceSerif",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupgenericfontname_monospaceserif"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_ProportionalSansSerif": {
      "abstract": [
        {
          "text": "A proportional font without serifs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_ProportionalSansSerif"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_ProportionalSansSerif",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_ProportionalSansSerif"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupGenericFontName_ProportionalSansSerif",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupgenericfontname_proportionalsansserif"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_ProportionalSerif": {
      "abstract": [
        {
          "text": "A proportional font with serifs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_ProportionalSerif"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_ProportionalSerif",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_ProportionalSerif"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupGenericFontName_ProportionalSerif",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupgenericfontname_proportionalserif"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_SansSerif": {
      "abstract": [
        {
          "text": "A font without serifs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_SansSerif"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_SansSerif",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_SansSerif"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupGenericFontName_SansSerif",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupgenericfontname_sansserif"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Serif": {
      "abstract": [
        {
          "text": "A font with serifs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_Serif"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Serif",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_Serif"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupGenericFontName_Serif",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupgenericfontname_serif"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_SmallCapital": {
      "abstract": [
        {
          "text": "A font with lowercase letters set as small capital letters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_SmallCapital"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_SmallCapital",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupGenericFontName_SmallCapital"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupGenericFontName_SmallCapital",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupgenericfontname_smallcapital"
    },
    "doc://com.apple.documentation/documentation/MediaAccessibility": {
      "abstract": [
        {
          "text": "Make your app’s media more accessible by supporting people’s systemwide preferences for video and audio content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MediaAccessibility",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Accessibility",
      "type": "topic",
      "url": "/documentation/MediaAccessibility"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Fonts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_FontFamilyName",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_RelativeFontSize"
      ],
      "title": "Fonts"
    }
  ],
  "topicSections": [
    {
      "anchor": "Font-Names",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Default",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Serif",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_SansSerif",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Monospace",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_MonospaceSerif",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_MonospaceSansSerif",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_ProportionalSerif",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_ProportionalSansSerif",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_SmallCapital",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Casual",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Cursive",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Fantasy"
      ],
      "title": "Font Names"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMTextMarkupAttribute_GenericFontFamilyName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_GenericFontFamilyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Font-Names",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Default",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Serif",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_SansSerif",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Monospace",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_MonospaceSerif",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_MonospaceSansSerif",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_ProportionalSerif",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_ProportionalSansSerif",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_SmallCapital",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Casual",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Cursive",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupGenericFontName_Fantasy"
              ],
              "title": "Font Names"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Fonts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_FontFamilyName",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_RelativeFontSize"
              ],
              "title": "Fonts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCMTextMarkupAttribute_GenericFontFamilyName"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_ProportionalSansSerif/title",
          "value": "kCMTextMarkupGenericFontName_ProportionalSansSerif"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_ProportionalSansSerif/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupGenericFontName_ProportionalSansSerif"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_Casual/title",
          "value": "kCMTextMarkupGenericFontName_Casual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_Casual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupGenericFontName_Casual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_GenericFontFamilyName/title",
          "value": "kCMTextMarkupAttribute_GenericFontFamilyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_GenericFontFamilyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_GenericFontFamilyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_SansSerif/title",
          "value": "kCMTextMarkupGenericFontName_SansSerif"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_SansSerif/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupGenericFontName_SansSerif"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_MonospaceSerif/title",
          "value": "kCMTextMarkupGenericFontName_MonospaceSerif"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_MonospaceSerif/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupGenericFontName_MonospaceSerif"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_SmallCapital/title",
          "value": "kCMTextMarkupGenericFontName_SmallCapital"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_SmallCapital/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupGenericFontName_SmallCapital"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_Fantasy/title",
          "value": "kCMTextMarkupGenericFontName_Fantasy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_Fantasy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupGenericFontName_Fantasy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_ProportionalSerif/title",
          "value": "kCMTextMarkupGenericFontName_ProportionalSerif"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_ProportionalSerif/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupGenericFontName_ProportionalSerif"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_Cursive/title",
          "value": "kCMTextMarkupGenericFontName_Cursive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_Cursive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupGenericFontName_Cursive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_Monospace/title",
          "value": "kCMTextMarkupGenericFontName_Monospace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_Monospace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupGenericFontName_Monospace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_Default/title",
          "value": "kCMTextMarkupGenericFontName_Default"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_Default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupGenericFontName_Default"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight/title",
          "value": "kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_FontFamilyName/title",
          "value": "kCMTextMarkupAttribute_FontFamilyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_FontFamilyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_FontFamilyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_MonospaceSansSerif/title",
          "value": "kCMTextMarkupGenericFontName_MonospaceSansSerif"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_MonospaceSansSerif/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupGenericFontName_MonospaceSansSerif"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_RelativeFontSize/title",
          "value": "kCMTextMarkupAttribute_RelativeFontSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_RelativeFontSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_RelativeFontSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_Serif/title",
          "value": "kCMTextMarkupGenericFontName_Serif"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupGenericFontName_Serif/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupGenericFontName_Serif"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmtextmarkupattribute_genericfontfamilyname"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmtextmarkupattribute_genericfontfamilyname"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
