{
  "abstract": [
    {
      "text": "A flag that describes treating all subtitle samples as if they contain forced subtitles.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_allSubtitlesForced"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMTextDisplayFlag_scrollIn@kCMTextDisplayFlag_allSubtitlesForced",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMTextDisplayFlag_allSubtitlesForced"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMTextDisplayFlags",
        "text": "CMTextDisplayFlags"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMTextDisplayFlag_allSubtitlesForced"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMTextDisplayFlag_allSubtitlesForced"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_allSubtitlesForced"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTextDisplayFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMTextDisplayFlags",
              "text": "CMTextDisplayFlags"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTextDisplayFlags": {
      "abstract": [
        {
          "text": "An integer value that describes the display mode flags for text media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTextDisplayFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTextDisplayFlags"
        }
      ],
      "role": "symbol",
      "title": "CMTextDisplayFlags",
      "type": "topic",
      "url": "/documentation/coremedia/cmtextdisplayflags"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_allSubtitlesForced": {
      "abstract": [
        {
          "text": "A flag that describes treating all subtitle samples as if they contain forced subtitles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_allSubtitlesForced"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_allSubtitlesForced",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_allSubtitlesForced"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_allSubtitlesForced",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_allsubtitlesforced"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_continuousKaraoke": {
      "abstract": [
        {
          "text": "A flag that describes enabling the continuous karaoke mode where the range of karaoke highlighting extends to include additional ranges rather than the highlighting moves onto the next range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_continuousKaraoke"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_continuousKaraoke",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_continuousKaraoke"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_continuousKaraoke",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_continuouskaraoke"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_fillTextRegion": {
      "abstract": [
        {
          "text": "A flag that describes the subtitle display bounds are to be filled with the color specified by ",
          "type": "text"
        },
        {
          "code": "kCMTextFormatDescriptionExtension_BackgroundColor",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_fillTextRegion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_fillTextRegion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_fillTextRegion"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_fillTextRegion",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_filltextregion"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_forcedSubtitlesPresent": {
      "abstract": [
        {
          "text": "A flag that describes forcing subtitles are present, for example, a subtitle which only displays during foreign language sections of the video. Check individual samples to determine what type of subtitle is contained.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_forcedSubtitlesPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_forcedSubtitlesPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_forcedSubtitlesPresent"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_forcedSubtitlesPresent",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_forcedsubtitlespresent"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirectionMask": {
      "abstract": [
        {
          "text": "A flag that describes the scrolling direction is set by a two-bit field, obtained from displayFlags using kCMTextDisplayFlag_scrollDirectionMask.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirectionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirectionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirectionMask"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_scrollDirectionMask",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_scrolldirectionmask"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_bottomToTop": {
      "abstract": [
        {
          "text": "A flag that describes the text is vertically scrolled up (“credits style”), entering from the bottom and leaving towards the top.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_bottomToTop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_bottomToTop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_bottomToTop"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_scrollDirection_bottomToTop",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_scrolldirection_bottomtotop"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_leftToRight": {
      "abstract": [
        {
          "text": "A flag that describes the text is horizontally scrolled, entering from the left and leaving towards the right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_leftToRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_leftToRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_leftToRight"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_scrollDirection_leftToRight",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_scrolldirection_lefttoright"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_rightToLeft": {
      "abstract": [
        {
          "text": "A flag that describes the text is horizontally scrolled (“marquee style”), entering from the right and leaving towards the left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_rightToLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_rightToLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_rightToLeft"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_scrollDirection_rightToLeft",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_scrolldirection_righttoleft"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_topToBottom": {
      "abstract": [
        {
          "text": "A flag that describes the text is vertically scrolled down, entering from the top and leaving towards the bottom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_topToBottom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_topToBottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_topToBottom"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_scrollDirection_topToBottom",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_scrolldirection_toptobottom"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollIn": {
      "abstract": [
        {
          "text": "A flag that describes the text scrolls into the display region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollIn"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_scrollIn",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_scrollin"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollOut": {
      "abstract": [
        {
          "text": "A flag that describes the text scrolls out of the display region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollOut"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_scrollOut",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_scrollout"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_writeTextVertically": {
      "abstract": [
        {
          "text": "A flag that describes the text renders vertically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_writeTextVertically"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_writeTextVertically",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_writeTextVertically"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_writeTextVertically",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_writetextvertically"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollIn",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollOut",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirectionMask",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_bottomToTop",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_rightToLeft",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_topToBottom",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_leftToRight",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_continuousKaraoke",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_writeTextVertically",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_fillTextRegion",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_forcedSubtitlesPresent"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMTextDisplayFlag_allSubtitlesForced"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_allSubtitlesForced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollIn",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollOut",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirectionMask",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_bottomToTop",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_rightToLeft",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_topToBottom",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_leftToRight",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_continuousKaraoke",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_writeTextVertically",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_fillTextRegion",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_forcedSubtitlesPresent"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMTextDisplayFlag_allSubtitlesForced"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_bottomToTop/title",
          "value": "kCMTextDisplayFlag_scrollDirection_bottomToTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_bottomToTop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_scrollDirection_bottomToTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollIn/title",
          "value": "kCMTextDisplayFlag_scrollIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_scrollIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_forcedSubtitlesPresent/title",
          "value": "kCMTextDisplayFlag_forcedSubtitlesPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_forcedSubtitlesPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_forcedSubtitlesPresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_fillTextRegion/title",
          "value": "kCMTextDisplayFlag_fillTextRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_fillTextRegion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_fillTextRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextDisplayFlags/title",
          "value": "CMTextDisplayFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextDisplayFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextDisplayFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextDisplayFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextDisplayFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_rightToLeft/title",
          "value": "kCMTextDisplayFlag_scrollDirection_rightToLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_rightToLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_scrollDirection_rightToLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirectionMask/title",
          "value": "kCMTextDisplayFlag_scrollDirectionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirectionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_scrollDirectionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_allSubtitlesForced/title",
          "value": "kCMTextDisplayFlag_allSubtitlesForced"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_allSubtitlesForced/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_allSubtitlesForced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_leftToRight/title",
          "value": "kCMTextDisplayFlag_scrollDirection_leftToRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_leftToRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_scrollDirection_leftToRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_writeTextVertically/title",
          "value": "kCMTextDisplayFlag_writeTextVertically"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_writeTextVertically/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_writeTextVertically"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollOut/title",
          "value": "kCMTextDisplayFlag_scrollOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_scrollOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_continuousKaraoke/title",
          "value": "kCMTextDisplayFlag_continuousKaraoke"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_continuousKaraoke/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_continuousKaraoke"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_topToBottom/title",
          "value": "kCMTextDisplayFlag_scrollDirection_topToBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_topToBottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_scrollDirection_topToBottom"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmtextdisplayflag_allsubtitlesforced"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmtextdisplayflag_allsubtitlesforced"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
