{
  "abstract": [
    {
      "text": "The extension flag that represents the default font name.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultFontName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCMTextFormatDescriptionExtension_DefaultFontName",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMTextFormatDescriptionExtension_DefaultFontName"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMTextFormatDescriptionExtension_DefaultFontName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMTextFormatDescriptionExtension_DefaultFontName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionExtension_DefaultFontName"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_BackgroundColor": {
      "abstract": [
        {
          "text": "The extension flag that represents the background color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_BackgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_BackgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_BackgroundColor"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionExtension_BackgroundColor",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionextension_backgroundcolor"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultFontName": {
      "abstract": [
        {
          "text": "The extension flag that represents the default font name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_DefaultFontName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultFontName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_DefaultFontName"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionExtension_DefaultFontName",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionextension_defaultfontname"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultStyle": {
      "abstract": [
        {
          "text": "The extension flag that represents the default style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_DefaultStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_DefaultStyle"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionExtension_DefaultStyle",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionextension_defaultstyle"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultTextBox": {
      "abstract": [
        {
          "text": "The extension flag that represents the default text box.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_DefaultTextBox"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultTextBox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_DefaultTextBox"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionExtension_DefaultTextBox",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionextension_defaulttextbox"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DisplayFlags": {
      "abstract": [
        {
          "text": "The extension flag that represents the display flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_DisplayFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DisplayFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_DisplayFlags"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionExtension_DisplayFlags",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionextension_displayflags"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_FontTable": {
      "abstract": [
        {
          "text": "The extension flag that represents the font table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_FontTable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_FontTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_FontTable"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionExtension_FontTable",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionextension_fonttable"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_HorizontalJustification": {
      "abstract": [
        {
          "text": "The extension flag that represents the horizontal justification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_HorizontalJustification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_HorizontalJustification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_HorizontalJustification"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionExtension_HorizontalJustification",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionextension_horizontaljustification"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_TextJustification": {
      "abstract": [
        {
          "text": "The extension flag that represents the text justification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_TextJustification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_TextJustification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_TextJustification"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionExtension_TextJustification",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionextension_textjustification"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_VerticalJustification": {
      "abstract": [
        {
          "text": "The extension flag that represents the vertical justification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_VerticalJustification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_VerticalJustification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_VerticalJustification"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionExtension_VerticalJustification",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionextension_verticaljustification"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Description-Extension-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DisplayFlags",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_BackgroundColor",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultTextBox",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultStyle",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_HorizontalJustification",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_VerticalJustification",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_FontTable",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_TextJustification"
      ],
      "title": "Description Extension Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMTextFormatDescriptionExtension_DefaultFontName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionExtension_DefaultFontName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Description-Extension-Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DisplayFlags",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_BackgroundColor",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultTextBox",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultStyle",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_HorizontalJustification",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_VerticalJustification",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_FontTable",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_TextJustification"
              ],
              "title": "Description Extension Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCMTextFormatDescriptionExtension_DefaultFontName"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_DefaultFontName/title",
          "value": "kCMTextFormatDescriptionExtension_DefaultFontName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_DefaultFontName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionExtension_DefaultFontName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_BackgroundColor/title",
          "value": "kCMTextFormatDescriptionExtension_BackgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_BackgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionExtension_BackgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_FontTable/title",
          "value": "kCMTextFormatDescriptionExtension_FontTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_FontTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionExtension_FontTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_HorizontalJustification/title",
          "value": "kCMTextFormatDescriptionExtension_HorizontalJustification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_HorizontalJustification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionExtension_HorizontalJustification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_TextJustification/title",
          "value": "kCMTextFormatDescriptionExtension_TextJustification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_TextJustification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionExtension_TextJustification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_VerticalJustification/title",
          "value": "kCMTextFormatDescriptionExtension_VerticalJustification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_VerticalJustification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionExtension_VerticalJustification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_DisplayFlags/title",
          "value": "kCMTextFormatDescriptionExtension_DisplayFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_DisplayFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionExtension_DisplayFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_DefaultTextBox/title",
          "value": "kCMTextFormatDescriptionExtension_DefaultTextBox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_DefaultTextBox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionExtension_DefaultTextBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_DefaultStyle/title",
          "value": "kCMTextFormatDescriptionExtension_DefaultStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_DefaultStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionExtension_DefaultStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmtextformatdescriptionextension_defaultfontname"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmtextformatdescriptionextension_defaultfontname"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
