{
  "abstract": [
    {
      "text": "A style for character edges.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_CharacterEdgeStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCMTextMarkupAttribute_CharacterEdgeStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMTextMarkupAttribute_CharacterEdgeStyle"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMTextMarkupAttribute_CharacterEdgeStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMTextMarkupAttribute_CharacterEdgeStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_CharacterEdgeStyle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This attribute’s value must be one of the constants listed below that control the shape of the edges of drawn characters. The default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupCharacterEdgeStyle_None",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_BoldStyle": {
      "abstract": [
        {
          "text": "A bold font style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_BoldStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_BoldStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_BoldStyle"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_BoldStyle",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_boldstyle"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_CharacterEdgeStyle": {
      "abstract": [
        {
          "text": "A style for character edges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_CharacterEdgeStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_CharacterEdgeStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_CharacterEdgeStyle"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_CharacterEdgeStyle",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_characteredgestyle"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_ItalicStyle": {
      "abstract": [
        {
          "text": "An italic font style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_ItalicStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_ItalicStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_ItalicStyle"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_ItalicStyle",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_italicstyle"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_UnderlineStyle": {
      "abstract": [
        {
          "text": "An underline font style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_UnderlineStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_UnderlineStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupAttribute_UnderlineStyle"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupAttribute_UnderlineStyle",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupattribute_underlinestyle"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupCharacterEdgeStyle_Depressed": {
      "abstract": [
        {
          "text": "A depressed edge style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupCharacterEdgeStyle_Depressed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupCharacterEdgeStyle_Depressed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupCharacterEdgeStyle_Depressed"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupCharacterEdgeStyle_Depressed",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupcharacteredgestyle_depressed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupCharacterEdgeStyle_DropShadow": {
      "abstract": [
        {
          "text": "A drop shadow style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupCharacterEdgeStyle_DropShadow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupCharacterEdgeStyle_DropShadow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupCharacterEdgeStyle_DropShadow"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupCharacterEdgeStyle_DropShadow",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupcharacteredgestyle_dropshadow"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupCharacterEdgeStyle_None": {
      "abstract": [
        {
          "text": "No edge style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupCharacterEdgeStyle_None"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupCharacterEdgeStyle_None",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupCharacterEdgeStyle_None"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupCharacterEdgeStyle_None",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupcharacteredgestyle_none"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupCharacterEdgeStyle_Raised": {
      "abstract": [
        {
          "text": "A raised edge style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupCharacterEdgeStyle_Raised"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupCharacterEdgeStyle_Raised",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupCharacterEdgeStyle_Raised"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupCharacterEdgeStyle_Raised",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupcharacteredgestyle_raised"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupCharacterEdgeStyle_Uniform": {
      "abstract": [
        {
          "text": "A uniform border style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextMarkupCharacterEdgeStyle_Uniform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupCharacterEdgeStyle_Uniform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextMarkupCharacterEdgeStyle_Uniform"
        }
      ],
      "role": "symbol",
      "title": "kCMTextMarkupCharacterEdgeStyle_Uniform",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextmarkupcharacteredgestyle_uniform"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_BoldStyle",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_ItalicStyle",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_UnderlineStyle"
      ],
      "title": "Styles"
    }
  ],
  "topicSections": [
    {
      "anchor": "Edge-Styles",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupCharacterEdgeStyle_None",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupCharacterEdgeStyle_Raised",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupCharacterEdgeStyle_Depressed",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupCharacterEdgeStyle_Uniform",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupCharacterEdgeStyle_DropShadow"
      ],
      "title": "Edge Styles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMTextMarkupAttribute_CharacterEdgeStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_CharacterEdgeStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Edge-Styles",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupCharacterEdgeStyle_None",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupCharacterEdgeStyle_Raised",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupCharacterEdgeStyle_Depressed",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupCharacterEdgeStyle_Uniform",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupCharacterEdgeStyle_DropShadow"
              ],
              "title": "Edge Styles"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Styles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_BoldStyle",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_ItalicStyle",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextMarkupAttribute_UnderlineStyle"
              ],
              "title": "Styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCMTextMarkupAttribute_CharacterEdgeStyle"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupCharacterEdgeStyle_Depressed/title",
          "value": "kCMTextMarkupCharacterEdgeStyle_Depressed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupCharacterEdgeStyle_Depressed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupCharacterEdgeStyle_Depressed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_BoldStyle/title",
          "value": "kCMTextMarkupAttribute_BoldStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_BoldStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_BoldStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_CharacterEdgeStyle/title",
          "value": "kCMTextMarkupAttribute_CharacterEdgeStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_CharacterEdgeStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_CharacterEdgeStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupCharacterEdgeStyle_DropShadow/title",
          "value": "kCMTextMarkupCharacterEdgeStyle_DropShadow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupCharacterEdgeStyle_DropShadow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupCharacterEdgeStyle_DropShadow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_UnderlineStyle/title",
          "value": "kCMTextMarkupAttribute_UnderlineStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_UnderlineStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_UnderlineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupCharacterEdgeStyle_Uniform/title",
          "value": "kCMTextMarkupCharacterEdgeStyle_Uniform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupCharacterEdgeStyle_Uniform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupCharacterEdgeStyle_Uniform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupCharacterEdgeStyle_Raised/title",
          "value": "kCMTextMarkupCharacterEdgeStyle_Raised"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupCharacterEdgeStyle_Raised/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupCharacterEdgeStyle_Raised"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_ItalicStyle/title",
          "value": "kCMTextMarkupAttribute_ItalicStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupAttribute_ItalicStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupAttribute_ItalicStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupCharacterEdgeStyle_None/title",
          "value": "kCMTextMarkupCharacterEdgeStyle_None"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextMarkupCharacterEdgeStyle_None/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextMarkupCharacterEdgeStyle_None"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmtextmarkupattribute_characteredgestyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmtextmarkupattribute_characteredgestyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
