{
  "abstract": [
    {
      "text": "The right value for the rect as a 16-bit number.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Right"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCMTextFormatDescriptionRect_Right",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMTextFormatDescriptionRect_Right"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMTextFormatDescriptionRect_Right"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMTextFormatDescriptionRect_Right"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionRect_Right"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Alpha": {
      "abstract": [
        {
          "text": "The color value for the alpha is a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionColor_Alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Alpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionColor_Alpha"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionColor_Alpha",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptioncolor_alpha"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Blue": {
      "abstract": [
        {
          "text": "The color value for blue is a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionColor_Blue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Blue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionColor_Blue"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionColor_Blue",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptioncolor_blue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Green": {
      "abstract": [
        {
          "text": "The color value for green is a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionColor_Green"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Green",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionColor_Green"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionColor_Green",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptioncolor_green"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Red": {
      "abstract": [
        {
          "text": "The color value for red is a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionColor_Red"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Red",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionColor_Red"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionColor_Red",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptioncolor_red"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Bottom": {
      "abstract": [
        {
          "text": "The bottom value for the rect as a 16-bit number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionRect_Bottom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionRect_Bottom"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionRect_Bottom",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionrect_bottom"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Left": {
      "abstract": [
        {
          "text": "The left value for the rect as a 16-bit number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionRect_Left"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionRect_Left"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionRect_Left",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionrect_left"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Right": {
      "abstract": [
        {
          "text": "The right value for the rect as a 16-bit number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionRect_Right"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionRect_Right"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionRect_Right",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionrect_right"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Top": {
      "abstract": [
        {
          "text": "The top value for the rect as a 16-bit number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionRect_Top"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionRect_Top"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionRect_Top",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionrect_top"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Ascent": {
      "abstract": [
        {
          "text": "The style value for the ascent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_Ascent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Ascent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_Ascent"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionStyle_Ascent",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionstyle_ascent"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_EndChar": {
      "abstract": [
        {
          "text": "The style value for the ending character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_EndChar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_EndChar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_EndChar"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionStyle_EndChar",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionstyle_endchar"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Font": {
      "abstract": [
        {
          "text": "The style value for font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_Font"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Font",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_Font"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionStyle_Font",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionstyle_font"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_FontFace": {
      "abstract": [
        {
          "text": "The style value for font face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_FontFace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_FontFace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_FontFace"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionStyle_FontFace",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionstyle_fontface"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_FontSize": {
      "abstract": [
        {
          "text": "The style value for the font size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_FontSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_FontSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_FontSize"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionStyle_FontSize",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionstyle_fontsize"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_ForegroundColor": {
      "abstract": [
        {
          "text": "The style value for foreground color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_ForegroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_ForegroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_ForegroundColor"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionStyle_ForegroundColor",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionstyle_foregroundcolor"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Height": {
      "abstract": [
        {
          "text": "The style value for the height.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_Height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Height",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_Height"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionStyle_Height",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionstyle_height"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_StartChar": {
      "abstract": [
        {
          "text": "The style value for the starting character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_StartChar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_StartChar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_StartChar"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionStyle_StartChar",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionstyle_startchar"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Description-Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Red",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Green",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Blue",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Alpha",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Top",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Left",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Bottom",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_StartChar",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Font",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_FontFace",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_ForegroundColor",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_EndChar",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Height",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Ascent",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_FontSize"
      ],
      "title": "Description Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMTextFormatDescriptionRect_Right"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionRect_Right"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Description-Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Red",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Green",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Blue",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Alpha",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Top",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Left",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Bottom",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_StartChar",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Font",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_FontFace",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_ForegroundColor",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_EndChar",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Height",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Ascent",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_FontSize"
              ],
              "title": "Description Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCMTextFormatDescriptionRect_Right"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_Ascent/title",
          "value": "kCMTextFormatDescriptionStyle_Ascent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_Ascent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionStyle_Ascent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionColor_Alpha/title",
          "value": "kCMTextFormatDescriptionColor_Alpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionColor_Alpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionColor_Alpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionRect_Bottom/title",
          "value": "kCMTextFormatDescriptionRect_Bottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionRect_Bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionRect_Bottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionRect_Left/title",
          "value": "kCMTextFormatDescriptionRect_Left"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionRect_Left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionRect_Left"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_ForegroundColor/title",
          "value": "kCMTextFormatDescriptionStyle_ForegroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_ForegroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionStyle_ForegroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_FontFace/title",
          "value": "kCMTextFormatDescriptionStyle_FontFace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_FontFace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionStyle_FontFace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionColor_Red/title",
          "value": "kCMTextFormatDescriptionColor_Red"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionColor_Red/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionColor_Red"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_Height/title",
          "value": "kCMTextFormatDescriptionStyle_Height"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_Height/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionStyle_Height"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionRect_Top/title",
          "value": "kCMTextFormatDescriptionRect_Top"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionRect_Top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionRect_Top"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_StartChar/title",
          "value": "kCMTextFormatDescriptionStyle_StartChar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_StartChar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionStyle_StartChar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_Font/title",
          "value": "kCMTextFormatDescriptionStyle_Font"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_Font/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionStyle_Font"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionRect_Right/title",
          "value": "kCMTextFormatDescriptionRect_Right"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionRect_Right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionRect_Right"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionColor_Green/title",
          "value": "kCMTextFormatDescriptionColor_Green"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionColor_Green/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionColor_Green"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_EndChar/title",
          "value": "kCMTextFormatDescriptionStyle_EndChar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_EndChar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionStyle_EndChar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_FontSize/title",
          "value": "kCMTextFormatDescriptionStyle_FontSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_FontSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionStyle_FontSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionColor_Blue/title",
          "value": "kCMTextFormatDescriptionColor_Blue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionColor_Blue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionColor_Blue"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmtextformatdescriptionrect_right"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmtextformatdescriptionrect_right"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
