{
  "abstract": [
    {
      "text": "A type that identifies the Apple ProRes 4444 format.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes4444"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMVideoCodecType_422YpCbCr8@kCMVideoCodecType_AppleProRes4444",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMVideoCodecType_AppleProRes4444"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMVideoCodecType",
        "text": "CMVideoCodecType"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMVideoCodecType_AppleProRes4444"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMVideoCodecType_AppleProRes4444"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_AppleProRes4444"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoCodecType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMVideoCodecType",
              "text": "CMVideoCodecType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoCodecType": {
      "abstract": [
        {
          "text": "A video codec type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoCodecType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMVideoCodecType"
        }
      ],
      "role": "symbol",
      "title": "CMVideoCodecType",
      "type": "topic",
      "url": "/documentation/coremedia/cmvideocodectype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_422YpCbCr8": {
      "abstract": [
        {
          "text": "A type that identifies a component with the format of Y’CbCr 8-bit 4:2:2 ordered Cb Y’0 Cr Y’1.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_422YpCbCr8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_422YpCbCr8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_422YpCbCr8"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_422YpCbCr8",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_422ypcbcr8"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Animation": {
      "abstract": [
        {
          "text": "A type that identifies the apple animation format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_Animation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Animation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_Animation"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_Animation",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_animation"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422": {
      "abstract": [
        {
          "text": "A type that identifies the Apple ProRes 422 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes422"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes422"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_AppleProRes422",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_appleprores422"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422HQ": {
      "abstract": [
        {
          "text": "A type that identifies the Apple ProRes 422 HQ format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes422HQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422HQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes422HQ"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_AppleProRes422HQ",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_appleprores422hq"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422LT": {
      "abstract": [
        {
          "text": "A type that identifies the Apple ProRes 422 LT format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes422LT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422LT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes422LT"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_AppleProRes422LT",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_appleprores422lt"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422Proxy": {
      "abstract": [
        {
          "text": "A type that identifies the Apple ProRes 422 proxy format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes422Proxy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422Proxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes422Proxy"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_AppleProRes422Proxy",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_appleprores422proxy"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes4444": {
      "abstract": [
        {
          "text": "A type that identifies the Apple ProRes 4444 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes4444"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes4444",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes4444"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_AppleProRes4444",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_appleprores4444"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes4444XQ": {
      "abstract": [
        {
          "text": "A type that identifies the Apple ProRes 4444 XQ format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes4444XQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes4444XQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes4444XQ"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_AppleProRes4444XQ",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_appleprores4444xq"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProResRAW": {
      "abstract": [
        {
          "text": "A type that identifies the Apple ProRes RAW format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProResRAW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProResRAW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProResRAW"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_AppleProResRAW",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_appleproresraw"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProResRAWHQ": {
      "abstract": [
        {
          "text": "A type that identifies the Apple ProRes RAW HQ format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProResRAWHQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProResRAWHQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProResRAWHQ"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_AppleProResRAWHQ",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_appleproresrawhq"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Cinepak": {
      "abstract": [
        {
          "text": "A type that identifies the cinepak format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_Cinepak"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Cinepak",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_Cinepak"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_Cinepak",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_cinepak"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCNTSC": {
      "abstract": [
        {
          "text": "A type that identifies the DV NTSC format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCNTSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCNTSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCNTSC"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCNTSC",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcntsc"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPAL": {
      "abstract": [
        {
          "text": "A type that identifies the DV PAL format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPAL"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPAL",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcpal"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i50": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro-HD 1080i50 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080i50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080i50"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPROHD1080i50",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcprohd1080i50"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i60": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro-HD 1080i60 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080i60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080i60"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPROHD1080i60",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcprohd1080i60"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080p25": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro-HD 1080p25 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080p25"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080p25",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080p25"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPROHD1080p25",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcprohd1080p25"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_422YpCbCr8",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Animation",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422HQ",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422LT",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422Proxy",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes4444XQ",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProResRAW",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProResRAWHQ",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Cinepak",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCNTSC",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPAL",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i50",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i60",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080p25"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMVideoCodecType_AppleProRes4444"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_AppleProRes4444"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_422YpCbCr8",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Animation",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422HQ",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422LT",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422Proxy",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes4444XQ",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProResRAW",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProResRAWHQ",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Cinepak",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCNTSC",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPAL",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i50",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i60",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080p25"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMVideoCodecType_AppleProRes4444"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes4444/title",
          "value": "kCMVideoCodecType_AppleProRes4444"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes4444/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_AppleProRes4444"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_Animation/title",
          "value": "kCMVideoCodecType_Animation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_Animation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_Animation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes422HQ/title",
          "value": "kCMVideoCodecType_AppleProRes422HQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes422HQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_AppleProRes422HQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_Cinepak/title",
          "value": "kCMVideoCodecType_Cinepak"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_Cinepak/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_Cinepak"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_422YpCbCr8/title",
          "value": "kCMVideoCodecType_422YpCbCr8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_422YpCbCr8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_422YpCbCr8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080i50/title",
          "value": "kCMVideoCodecType_DVCPROHD1080i50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080i50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPROHD1080i50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes422LT/title",
          "value": "kCMVideoCodecType_AppleProRes422LT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes422LT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_AppleProRes422LT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoCodecType/title",
          "value": "CMVideoCodecType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoCodecType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoCodecType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProResRAW/title",
          "value": "kCMVideoCodecType_AppleProResRAW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProResRAW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_AppleProResRAW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080i60/title",
          "value": "kCMVideoCodecType_DVCPROHD1080i60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080i60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPROHD1080i60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080p25/title",
          "value": "kCMVideoCodecType_DVCPROHD1080p25"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080p25/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPROHD1080p25"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes422/title",
          "value": "kCMVideoCodecType_AppleProRes422"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes422/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_AppleProRes422"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes4444XQ/title",
          "value": "kCMVideoCodecType_AppleProRes4444XQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes4444XQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_AppleProRes4444XQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCNTSC/title",
          "value": "kCMVideoCodecType_DVCNTSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCNTSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCNTSC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProResRAWHQ/title",
          "value": "kCMVideoCodecType_AppleProResRAWHQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProResRAWHQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_AppleProResRAWHQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes422Proxy/title",
          "value": "kCMVideoCodecType_AppleProRes422Proxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes422Proxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_AppleProRes422Proxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPAL/title",
          "value": "kCMVideoCodecType_DVCPAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPAL"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmvideocodectype_appleprores4444"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmvideocodectype_appleprores4444"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
