{
  "abstract": [
    {
      "text": "A type that identifies the Panasonic DVCPro-50 NTSC format.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPro50NTSC"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCMVideoCodecType_422YpCbCr8@kCMVideoCodecType_DVCPro50NTSC",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCMVideoCodecType_DVCPro50NTSC"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMVideoCodecType",
        "text": "CMVideoCodecType"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMVideoCodecType_DVCPro50NTSC"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCMVideoCodecType_DVCPro50NTSC"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPro50NTSC"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoCodecType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMVideoCodecType",
              "text": "CMVideoCodecType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoCodecType": {
      "abstract": [
        {
          "text": "A video codec type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoCodecType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMVideoCodecType"
        }
      ],
      "role": "symbol",
      "title": "CMVideoCodecType",
      "type": "topic",
      "url": "/documentation/coremedia/cmvideocodectype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_422YpCbCr8": {
      "abstract": [
        {
          "text": "A type that identifies a component with the format of Y’CbCr 8-bit 4:2:2 ordered Cb Y’0 Cr Y’1.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_422YpCbCr8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_422YpCbCr8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_422YpCbCr8"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_422YpCbCr8",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_422ypcbcr8"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Animation": {
      "abstract": [
        {
          "text": "A type that identifies the apple animation format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_Animation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Animation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_Animation"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_Animation",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_animation"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Cinepak": {
      "abstract": [
        {
          "text": "A type that identifies the cinepak format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_Cinepak"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Cinepak",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_Cinepak"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_Cinepak",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_cinepak"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCNTSC": {
      "abstract": [
        {
          "text": "A type that identifies the DV NTSC format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCNTSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCNTSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCNTSC"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCNTSC",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcntsc"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPAL": {
      "abstract": [
        {
          "text": "A type that identifies the DV PAL format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPAL"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPAL",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcpal"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPro50NTSC": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro-50 NTSC format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPro50NTSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPro50NTSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPro50NTSC"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPro50NTSC",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcpro50ntsc"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCProPAL": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro PAL format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCProPAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCProPAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCProPAL"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCProPAL",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcpropal"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H263": {
      "abstract": [
        {
          "text": "A type that identifies the ITU-T H.263 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_H263"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H263",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_H263"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_H263",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_h263"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H264": {
      "abstract": [
        {
          "text": "A type that identifies the ITU-T H.264 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_H264"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H264",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_H264"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_H264",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_h264"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG": {
      "abstract": [
        {
          "text": "A type that identifies the Joint Photographic Experts Group (JPEG) format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_JPEG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_JPEG"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_JPEG",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_jpeg"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG_OpenDML": {
      "abstract": [
        {
          "text": "A type that identifies the JPEG format with Open-DML extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_JPEG_OpenDML"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG_OpenDML",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_JPEG_OpenDML"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_JPEG_OpenDML",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_jpeg_opendml"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG1Video": {
      "abstract": [
        {
          "text": "A type that identifies the MPEG-1 video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_MPEG1Video"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG1Video",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_MPEG1Video"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_MPEG1Video",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_mpeg1video"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG2Video": {
      "abstract": [
        {
          "text": "A type that identifies the MPEG-2 video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_MPEG2Video"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG2Video",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_MPEG2Video"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_MPEG2Video",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_mpeg2video"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG4Video": {
      "abstract": [
        {
          "text": "A type that identifies the Moving Picture Experts Group (MPEG) MPEG-4 Part 2 video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_MPEG4Video"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG4Video",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_MPEG4Video"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_MPEG4Video",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_mpeg4video"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo": {
      "abstract": [
        {
          "text": "A type that identifies the sorenson video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_SorensonVideo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_SorensonVideo"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_SorensonVideo",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_sorensonvideo"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo3": {
      "abstract": [
        {
          "text": "A type that identifies the sorenson 3 video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_SorensonVideo3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_SorensonVideo3"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_SorensonVideo3",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_sorensonvideo3"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_422YpCbCr8",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Animation",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Cinepak",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG_OpenDML",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo3",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H263",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H264",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG4Video",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG2Video",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG1Video",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCNTSC",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPAL",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCProPAL"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMVideoCodecType_DVCPro50NTSC"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPro50NTSC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_422YpCbCr8",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Animation",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Cinepak",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG_OpenDML",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo3",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H263",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H264",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG4Video",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG2Video",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG1Video",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCNTSC",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPAL",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCProPAL"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCMVideoCodecType_DVCPro50NTSC"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPro50NTSC/title",
          "value": "kCMVideoCodecType_DVCPro50NTSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPro50NTSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPro50NTSC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_422YpCbCr8/title",
          "value": "kCMVideoCodecType_422YpCbCr8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_422YpCbCr8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_422YpCbCr8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_JPEG_OpenDML/title",
          "value": "kCMVideoCodecType_JPEG_OpenDML"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_JPEG_OpenDML/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_JPEG_OpenDML"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoCodecType/title",
          "value": "CMVideoCodecType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoCodecType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoCodecType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_SorensonVideo3/title",
          "value": "kCMVideoCodecType_SorensonVideo3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_SorensonVideo3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_SorensonVideo3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_JPEG/title",
          "value": "kCMVideoCodecType_JPEG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_JPEG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_JPEG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPAL/title",
          "value": "kCMVideoCodecType_DVCPAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_Cinepak/title",
          "value": "kCMVideoCodecType_Cinepak"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_Cinepak/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_Cinepak"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_H264/title",
          "value": "kCMVideoCodecType_H264"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_H264/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_H264"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCProPAL/title",
          "value": "kCMVideoCodecType_DVCProPAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCProPAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCProPAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_Animation/title",
          "value": "kCMVideoCodecType_Animation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_Animation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_Animation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCNTSC/title",
          "value": "kCMVideoCodecType_DVCNTSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCNTSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCNTSC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_H263/title",
          "value": "kCMVideoCodecType_H263"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_H263/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_H263"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_MPEG1Video/title",
          "value": "kCMVideoCodecType_MPEG1Video"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_MPEG1Video/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_MPEG1Video"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_MPEG2Video/title",
          "value": "kCMVideoCodecType_MPEG2Video"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_MPEG2Video/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_MPEG2Video"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_MPEG4Video/title",
          "value": "kCMVideoCodecType_MPEG4Video"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_MPEG4Video/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_MPEG4Video"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_SorensonVideo/title",
          "value": "kCMVideoCodecType_SorensonVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_SorensonVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_SorensonVideo"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/kcmvideocodectype_dvcpro50ntsc"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/kcmvideocodectype_dvcpro50ntsc"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
