{
  "abstract": [
    {
      "text": "Constants that describe metadata identifiers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Metadata Identifiers"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata": {
      "abstract": [
        {
          "text": "The APIs for working with the framework’s Metadata Identifier Services and Metadata Data Type Registry.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMMetadata APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing": {
      "abstract": [
        {
          "text": "Direction the observer is facing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifier_quicktimemetadatadirection_facing"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform": {
      "abstract": [
        {
          "text": "A perspective transform you use to adjust a Live Photo still image to match the Live Photo movie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifier_quicktimemetadatalivephotostillimagetransform"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions": {
      "abstract": [
        {
          "text": "The dimensions of the live photo still image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifier_quicktimemetadatalivephotostillimagetransformreferencedimensions"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709": {
      "abstract": [
        {
          "text": "Location information in ISO-6709 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifier_quicktimemetadatalocation_iso6709"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform": {
      "abstract": [
        {
          "text": "An affine transform to be applied to a video track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifier_quicktimemetadatapreferredaffinetransform"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation": {
      "abstract": [
        {
          "text": "Video orientation as defined by TIFF/EXIF.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifier_quicktimemetadatavideoorientation"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types": {
      "abstract": [
        {
          "text": "Constants that describe metadata base data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Base Data Types",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-base-data-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types": {
      "abstract": [
        {
          "text": "Constants that describe metadata data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Data Types",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-data-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors": {
      "abstract": [
        {
          "text": "Error codes that indicate metadata identifier errors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Identifier Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-identifier-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces": {
      "abstract": [
        {
          "text": "Constants that describe metadata identifier keyspaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Identifier Keyspaces",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-identifier-keyspaces"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors": {
      "abstract": [
        {
          "text": "Error codes that indicate metadata registry errors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Registry Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-registry-errors"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions/title",
          "value": "kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransformReferenceDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform/title",
          "value": "kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifier_QuickTimeMetadataLivePhotoStillImageTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing/title",
          "value": "kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform/title",
          "value": "kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709/title",
          "value": "kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation/title",
          "value": "kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/metadata-identifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/metadata-identifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
