{
  "abstract": [
    {
      "text": "Constants that describe metadata data types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Metadata Data Types"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata": {
      "abstract": [
        {
          "text": "The APIs for working with the framework’s Metadata Identifier Services and Metadata Data Type Registry.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMMetadata APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataType_QuickTimeMetadataDirection": {
      "abstract": [
        {
          "text": "A string supplying degrees offset from magnetic North.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataDataType_QuickTimeMetadataDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataType_QuickTimeMetadataDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataDataType_QuickTimeMetadataDirection"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataDataType_QuickTimeMetadataDirection",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatadatatype_quicktimemetadatadirection"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataType_QuickTimeMetadataLocation_ISO6709": {
      "abstract": [
        {
          "text": "A string supplying location information in ISO-6709 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataDataType_QuickTimeMetadataLocation_ISO6709"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataType_QuickTimeMetadataLocation_ISO6709",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataDataType_QuickTimeMetadataLocation_ISO6709"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataDataType_QuickTimeMetadataLocation_ISO6709",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatadatatype_quicktimemetadatalocation_iso6709"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types": {
      "abstract": [
        {
          "text": "Constants that describe metadata base data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Base Data Types",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-base-data-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors": {
      "abstract": [
        {
          "text": "Error codes that indicate metadata identifier errors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Identifier Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-identifier-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces": {
      "abstract": [
        {
          "text": "Constants that describe metadata identifier keyspaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Identifier Keyspaces",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-identifier-keyspaces"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers": {
      "abstract": [
        {
          "text": "Constants that describe metadata identifiers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Identifiers",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-identifiers"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors": {
      "abstract": [
        {
          "text": "Error codes that indicate metadata registry errors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Registry Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-registry-errors"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataType_QuickTimeMetadataLocation_ISO6709",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataType_QuickTimeMetadataDirection"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataType_QuickTimeMetadataLocation_ISO6709",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataType_QuickTimeMetadataDirection"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataDataType_QuickTimeMetadataLocation_ISO6709/title",
          "value": "kCMMetadataDataType_QuickTimeMetadataLocation_ISO6709"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataDataType_QuickTimeMetadataLocation_ISO6709/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataDataType_QuickTimeMetadataLocation_ISO6709"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataDataType_QuickTimeMetadataDirection/title",
          "value": "kCMMetadataDataType_QuickTimeMetadataDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataDataType_QuickTimeMetadataDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataDataType_QuickTimeMetadataDirection"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/metadata-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/metadata-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
