{
  "abstract": [
    {
      "text": "Error codes that indicate metadata registry errors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Metadata Registry Error Codes"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata": {
      "abstract": [
        {
          "text": "The APIs for working with the framework’s Metadata Identifier Services and Metadata Data Type Registry.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMMetadata APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_AllocationFailed": {
      "abstract": [
        {
          "text": "An error that indicates the allocation fails.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataDataTypeRegistryError_AllocationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_AllocationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataDataTypeRegistryError_AllocationFailed"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataDataTypeRegistryError_AllocationFailed",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatadatatyperegistryerror_allocationfailed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_BadDataTypeIdentifier": {
      "abstract": [
        {
          "text": "An error that indicates a bad datatype identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataDataTypeRegistryError_BadDataTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_BadDataTypeIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataDataTypeRegistryError_BadDataTypeIdentifier"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataDataTypeRegistryError_BadDataTypeIdentifier",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatadatatyperegistryerror_baddatatypeidentifier"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_DataTypeAlreadyRegistered": {
      "abstract": [
        {
          "text": "An error that indicates the datatype is in a registered state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataDataTypeRegistryError_DataTypeAlreadyRegistered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_DataTypeAlreadyRegistered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataDataTypeRegistryError_DataTypeAlreadyRegistered"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataDataTypeRegistryError_DataTypeAlreadyRegistered",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatadatatyperegistryerror_datatypealreadyregistered"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_MultipleConformingBaseTypes": {
      "abstract": [
        {
          "text": "An error that indicates that type you provide has more than one base data type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataDataTypeRegistryError_MultipleConformingBaseTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_MultipleConformingBaseTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataDataTypeRegistryError_MultipleConformingBaseTypes"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataDataTypeRegistryError_MultipleConformingBaseTypes",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatadatatyperegistryerror_multipleconformingbasetypes"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_RequiredParameterMissing": {
      "abstract": [
        {
          "text": "An error that indicates a parameter the function requires is empty.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataDataTypeRegistryError_RequiredParameterMissing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_RequiredParameterMissing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataDataTypeRegistryError_RequiredParameterMissing"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataDataTypeRegistryError_RequiredParameterMissing",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatadatatyperegistryerror_requiredparametermissing"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_RequiresConformingBaseType": {
      "abstract": [
        {
          "text": "An error that indicates the data type you specify requires a conforming data type that resolves to a base data type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataDataTypeRegistryError_RequiresConformingBaseType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_RequiresConformingBaseType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataDataTypeRegistryError_RequiresConformingBaseType"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataDataTypeRegistryError_RequiresConformingBaseType",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatadatatyperegistryerror_requiresconformingbasetype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types": {
      "abstract": [
        {
          "text": "Constants that describe metadata base data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Base Data Types",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-base-data-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types": {
      "abstract": [
        {
          "text": "Constants that describe metadata data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Data Types",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-data-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors": {
      "abstract": [
        {
          "text": "Error codes that indicate metadata identifier errors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Identifier Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-identifier-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces": {
      "abstract": [
        {
          "text": "Constants that describe metadata identifier keyspaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Identifier Keyspaces",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-identifier-keyspaces"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers": {
      "abstract": [
        {
          "text": "Constants that describe metadata identifiers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Identifiers",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-identifiers"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_AllocationFailed",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_BadDataTypeIdentifier",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_DataTypeAlreadyRegistered",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_MultipleConformingBaseTypes",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_RequiredParameterMissing",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_RequiresConformingBaseType"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_AllocationFailed",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_BadDataTypeIdentifier",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_DataTypeAlreadyRegistered",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_MultipleConformingBaseTypes",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_RequiredParameterMissing",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataDataTypeRegistryError_RequiresConformingBaseType"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataDataTypeRegistryError_RequiredParameterMissing/title",
          "value": "kCMMetadataDataTypeRegistryError_RequiredParameterMissing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataDataTypeRegistryError_RequiredParameterMissing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataDataTypeRegistryError_RequiredParameterMissing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataDataTypeRegistryError_RequiresConformingBaseType/title",
          "value": "kCMMetadataDataTypeRegistryError_RequiresConformingBaseType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataDataTypeRegistryError_RequiresConformingBaseType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataDataTypeRegistryError_RequiresConformingBaseType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataDataTypeRegistryError_AllocationFailed/title",
          "value": "kCMMetadataDataTypeRegistryError_AllocationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataDataTypeRegistryError_AllocationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataDataTypeRegistryError_AllocationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataDataTypeRegistryError_DataTypeAlreadyRegistered/title",
          "value": "kCMMetadataDataTypeRegistryError_DataTypeAlreadyRegistered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataDataTypeRegistryError_DataTypeAlreadyRegistered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataDataTypeRegistryError_DataTypeAlreadyRegistered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataDataTypeRegistryError_MultipleConformingBaseTypes/title",
          "value": "kCMMetadataDataTypeRegistryError_MultipleConformingBaseTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataDataTypeRegistryError_MultipleConformingBaseTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataDataTypeRegistryError_MultipleConformingBaseTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataDataTypeRegistryError_BadDataTypeIdentifier/title",
          "value": "kCMMetadataDataTypeRegistryError_BadDataTypeIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataDataTypeRegistryError_BadDataTypeIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataDataTypeRegistryError_BadDataTypeIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/metadata-registry-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/metadata-registry-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
