{
  "abstract": [
    {
      "text": "Error codes that indicate metadata identifier errors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Metadata Identifier Error Codes"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata": {
      "abstract": [
        {
          "text": "The APIs for working with the framework’s Metadata Identifier Services and Metadata Data Type Registry.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMMetadata APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_AllocationFailed": {
      "abstract": [
        {
          "text": "An error that indicates an allocation fails.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_AllocationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_AllocationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_AllocationFailed"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifierError_AllocationFailed",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifiererror_allocationfailed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadIdentifier": {
      "abstract": [
        {
          "text": "An error that indicates the identifier isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadIdentifier"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifierError_BadIdentifier",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifiererror_badidentifier"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKey": {
      "abstract": [
        {
          "text": "An error that indicates a key isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadKey"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifierError_BadKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifiererror_badkey"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeyLength": {
      "abstract": [
        {
          "text": "An error that indicates that a key doesn’t have the correct length.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadKeyLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeyLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadKeyLength"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifierError_BadKeyLength",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifiererror_badkeylength"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeySpace": {
      "abstract": [
        {
          "text": "An error that indicates the keyspace isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadKeySpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeySpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadKeySpace"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifierError_BadKeySpace",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifiererror_badkeyspace"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeyType": {
      "abstract": [
        {
          "text": "An error that indicates a key has a bad type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadKeyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadKeyType"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifierError_BadKeyType",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifiererror_badkeytype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadNumberKey": {
      "abstract": [
        {
          "text": "An error that indicates the number for a key isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadNumberKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadNumberKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_BadNumberKey"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifierError_BadNumberKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifiererror_badnumberkey"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_NoKeyValueAvailable": {
      "abstract": [
        {
          "text": "An error that indicates a request for a key value in the anonymous keyspace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_NoKeyValueAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_NoKeyValueAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_NoKeyValueAvailable"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifierError_NoKeyValueAvailable",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifiererror_nokeyvalueavailable"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_RequiredParameterMissing": {
      "abstract": [
        {
          "text": "An error that indicates a parameter the function requires is empty.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_RequiredParameterMissing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_RequiredParameterMissing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataIdentifierError_RequiredParameterMissing"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataIdentifierError_RequiredParameterMissing",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataidentifiererror_requiredparametermissing"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types": {
      "abstract": [
        {
          "text": "Constants that describe metadata base data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Base Data Types",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-base-data-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types": {
      "abstract": [
        {
          "text": "Constants that describe metadata data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Data Types",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-data-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces": {
      "abstract": [
        {
          "text": "Constants that describe metadata identifier keyspaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Identifier Keyspaces",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-identifier-keyspaces"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers": {
      "abstract": [
        {
          "text": "Constants that describe metadata identifiers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Identifiers",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-identifiers"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors": {
      "abstract": [
        {
          "text": "Error codes that indicate metadata registry errors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Registry Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-registry-errors"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_AllocationFailed",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadIdentifier",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKey",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeyLength",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeySpace",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeyType",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadNumberKey",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_NoKeyValueAvailable",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_RequiredParameterMissing"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_AllocationFailed",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadIdentifier",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKey",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeyLength",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeySpace",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadKeyType",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_BadNumberKey",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_NoKeyValueAvailable",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataIdentifierError_RequiredParameterMissing"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadIdentifier/title",
          "value": "kCMMetadataIdentifierError_BadIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifierError_BadIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadKeyLength/title",
          "value": "kCMMetadataIdentifierError_BadKeyLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadKeyLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifierError_BadKeyLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadKey/title",
          "value": "kCMMetadataIdentifierError_BadKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifierError_BadKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadNumberKey/title",
          "value": "kCMMetadataIdentifierError_BadNumberKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadNumberKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifierError_BadNumberKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadKeyType/title",
          "value": "kCMMetadataIdentifierError_BadKeyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadKeyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifierError_BadKeyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_RequiredParameterMissing/title",
          "value": "kCMMetadataIdentifierError_RequiredParameterMissing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_RequiredParameterMissing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifierError_RequiredParameterMissing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadKeySpace/title",
          "value": "kCMMetadataIdentifierError_BadKeySpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_BadKeySpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifierError_BadKeySpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_AllocationFailed/title",
          "value": "kCMMetadataIdentifierError_AllocationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_AllocationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifierError_AllocationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_NoKeyValueAvailable/title",
          "value": "kCMMetadataIdentifierError_NoKeyValueAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataIdentifierError_NoKeyValueAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataIdentifierError_NoKeyValueAvailable"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/metadata-identifier-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/metadata-identifier-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
