{
  "abstract": [
    {
      "text": "Constants that describe metadata base data types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Metadata Base Data Types"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata": {
      "abstract": [
        {
          "text": "The APIs for working with the framework’s Metadata Identifier Services and Metadata Data Type Registry.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMMetadata APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_AffineTransformF64": {
      "abstract": [
        {
          "text": "A type that identifies a 3x3 matrix of 64-bit big endian floating point numbers in a row-major order that specify an affine transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_AffineTransformF64"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_AffineTransformF64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_AffineTransformF64"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_AffineTransformF64",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_affinetransformf64"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_BMP": {
      "abstract": [
        {
          "text": "BMP image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_BMP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_BMP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_BMP"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_BMP",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_bmp"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_DimensionsF32": {
      "abstract": [
        {
          "text": "Consists of a 32-bit big endian floating point x value followed by a 32-bit floating point y value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_DimensionsF32"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_DimensionsF32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_DimensionsF32"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_DimensionsF32",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_dimensionsf32"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_Float32": {
      "abstract": [
        {
          "text": "32-bit big endian floating point number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_Float32"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_Float32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_Float32"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_Float32",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_float32"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_Float64": {
      "abstract": [
        {
          "text": "64-bit big endian floating point number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_Float64"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_Float64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_Float64"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_Float64",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_float64"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_GIF": {
      "abstract": [
        {
          "text": "GIF image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_GIF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_GIF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_GIF"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_GIF",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_gif"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_JPEG": {
      "abstract": [
        {
          "text": "JPEG image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_JPEG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_JPEG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_JPEG"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_JPEG",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_jpeg"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_JSON": {
      "abstract": [
        {
          "text": "UTF-8 encoded JSON data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_JSON"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_JSON",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_JSON"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_JSON",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_json"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PNG": {
      "abstract": [
        {
          "text": "PNG image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_PNG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PNG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_PNG"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_PNG",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_png"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PerspectiveTransformF64": {
      "abstract": [
        {
          "text": "A 3x3 matrix of 64-bit big endian floating point numbers the system stores in row-major order that specify a perspective transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_PerspectiveTransformF64"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PerspectiveTransformF64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_PerspectiveTransformF64"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_PerspectiveTransformF64",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_perspectivetransformf64"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PointF32": {
      "abstract": [
        {
          "text": "Consists of two 32-bit big endian floating point values, the x and y values, respectively.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_PointF32"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PointF32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_PointF32"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_PointF32",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_pointf32"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PolygonF32": {
      "abstract": [
        {
          "text": "Three or more pairs of 32-bit floating point numbers (x and y values) that define the vertices of a polygon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_PolygonF32"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PolygonF32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_PolygonF32"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_PolygonF32",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_polygonf32"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PolylineF32": {
      "abstract": [
        {
          "text": "Two or more pairs of 32-bit floating point numbers (x and y values) that define a multi-segmented line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_PolylineF32"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PolylineF32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_PolylineF32"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_PolylineF32",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_polylinef32"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_RawData": {
      "abstract": [
        {
          "text": "A sequence of bytes whose interpretation based upon an agreement between the reader and the writer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_RawData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_RawData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_RawData"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_RawData",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_rawdata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_RectF32": {
      "abstract": [
        {
          "text": "Consists of four 32-bit big endian floating point values, the origin’s x, origin’s y, width and height values, respectively. May also be interpreted as a 32-bit floating point origin followed by a 32-bit floating point dimension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_RectF32"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_RectF32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_RectF32"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_RectF32",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_rectf32"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt16": {
      "abstract": [
        {
          "text": "16-bit big endian signed integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_SInt16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_SInt16"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_SInt16",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_sint16"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt32": {
      "abstract": [
        {
          "text": "32-bit big endian signed integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_SInt32"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_SInt32"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_SInt32",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_sint32"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt64": {
      "abstract": [
        {
          "text": "64-bit big endian signed integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_SInt64"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_SInt64"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_SInt64",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_sint64"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt8": {
      "abstract": [
        {
          "text": "8-bit signed integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_SInt8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_SInt8"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_SInt8",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_sint8"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt16": {
      "abstract": [
        {
          "text": "16-bit big endian unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UInt16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UInt16"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_UInt16",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_uint16"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt32": {
      "abstract": [
        {
          "text": "32-bit big endian unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UInt32"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UInt32"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_UInt32",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_uint32"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt64": {
      "abstract": [
        {
          "text": "64-bit big endian unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UInt64"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UInt64"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_UInt64",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_uint64"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt8": {
      "abstract": [
        {
          "text": "8-bit unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UInt8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UInt8"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_UInt8",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_uint8"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UTF16": {
      "abstract": [
        {
          "text": "UTF-16 string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UTF16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UTF16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UTF16"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_UTF16",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_utf16"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UTF8": {
      "abstract": [
        {
          "text": "UTF-8 string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UTF8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UTF8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_UTF8"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_UTF8",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_utf8"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types": {
      "abstract": [
        {
          "text": "Constants that describe metadata data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Data Types",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-data-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors": {
      "abstract": [
        {
          "text": "Error codes that indicate metadata identifier errors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Identifier Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-identifier-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces": {
      "abstract": [
        {
          "text": "Constants that describe metadata identifier keyspaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Identifier Keyspaces",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-identifier-keyspaces"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers": {
      "abstract": [
        {
          "text": "Constants that describe metadata identifiers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Identifiers",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-identifiers"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors": {
      "abstract": [
        {
          "text": "Error codes that indicate metadata registry errors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Registry Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-registry-errors"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_RawData",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UTF8",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UTF16",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_GIF",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_JPEG",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PNG",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_BMP",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_Float32",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_Float64",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt8",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt16",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt32",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt64",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt8",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt16",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt32",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt64",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PointF32",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_DimensionsF32",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_RectF32",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_AffineTransformF64",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PerspectiveTransformF64",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PolygonF32",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PolylineF32",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_JSON"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_RawData",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UTF8",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UTF16",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_GIF",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_JPEG",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PNG",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_BMP",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_Float32",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_Float64",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt8",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt16",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt32",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_SInt64",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt8",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt16",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt32",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_UInt64",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PointF32",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_DimensionsF32",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_RectF32",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_AffineTransformF64",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PerspectiveTransformF64",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PolygonF32",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_PolylineF32",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_JSON"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_DimensionsF32/title",
          "value": "kCMMetadataBaseDataType_DimensionsF32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_DimensionsF32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_DimensionsF32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_Float32/title",
          "value": "kCMMetadataBaseDataType_Float32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_Float32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_Float32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_SInt16/title",
          "value": "kCMMetadataBaseDataType_SInt16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_SInt16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_SInt16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UInt32/title",
          "value": "kCMMetadataBaseDataType_UInt32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UInt32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_UInt32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UInt8/title",
          "value": "kCMMetadataBaseDataType_UInt8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UInt8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_UInt8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_SInt8/title",
          "value": "kCMMetadataBaseDataType_SInt8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_SInt8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_SInt8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_RectF32/title",
          "value": "kCMMetadataBaseDataType_RectF32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_RectF32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_RectF32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_AffineTransformF64/title",
          "value": "kCMMetadataBaseDataType_AffineTransformF64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_AffineTransformF64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_AffineTransformF64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_SInt32/title",
          "value": "kCMMetadataBaseDataType_SInt32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_SInt32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_SInt32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UTF8/title",
          "value": "kCMMetadataBaseDataType_UTF8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UTF8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_UTF8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_PointF32/title",
          "value": "kCMMetadataBaseDataType_PointF32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_PointF32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_PointF32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UTF16/title",
          "value": "kCMMetadataBaseDataType_UTF16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UTF16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_UTF16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_PolygonF32/title",
          "value": "kCMMetadataBaseDataType_PolygonF32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_PolygonF32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_PolygonF32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_BMP/title",
          "value": "kCMMetadataBaseDataType_BMP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_BMP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_BMP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UInt64/title",
          "value": "kCMMetadataBaseDataType_UInt64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UInt64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_UInt64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_PerspectiveTransformF64/title",
          "value": "kCMMetadataBaseDataType_PerspectiveTransformF64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_PerspectiveTransformF64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_PerspectiveTransformF64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_GIF/title",
          "value": "kCMMetadataBaseDataType_GIF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_GIF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_GIF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_RawData/title",
          "value": "kCMMetadataBaseDataType_RawData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_RawData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_RawData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_JSON/title",
          "value": "kCMMetadataBaseDataType_JSON"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_JSON/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_JSON"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_PNG/title",
          "value": "kCMMetadataBaseDataType_PNG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_PNG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_PNG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_SInt64/title",
          "value": "kCMMetadataBaseDataType_SInt64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_SInt64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_SInt64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_PolylineF32/title",
          "value": "kCMMetadataBaseDataType_PolylineF32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_PolylineF32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_PolylineF32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UInt16/title",
          "value": "kCMMetadataBaseDataType_UInt16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_UInt16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_UInt16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_Float64/title",
          "value": "kCMMetadataBaseDataType_Float64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_Float64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_Float64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_JPEG/title",
          "value": "kCMMetadataBaseDataType_JPEG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_JPEG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_JPEG"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/metadata-base-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/metadata-base-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
