{
  "abstract": [
    {
      "text": "Constants that describe metadata identifier keyspaces.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-keyspaces"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Metadata Identifier Keyspaces"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata": {
      "abstract": [
        {
          "text": "The APIs for working with the framework’s Metadata Identifier Services and Metadata Data Type Registry.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmmetadata",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMMetadata APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_HLSDateRange": {
      "abstract": [
        {
          "text": "Metadata keyspace for HLS DateRange tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataKeySpace_HLSDateRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_HLSDateRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataKeySpace_HLSDateRange"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataKeySpace_HLSDateRange",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatakeyspace_hlsdaterange"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_ID3": {
      "abstract": [
        {
          "text": "Metadata keyspace for ID3 keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataKeySpace_ID3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_ID3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataKeySpace_ID3"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataKeySpace_ID3",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatakeyspace_id3"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_ISOUserData": {
      "abstract": [
        {
          "text": "Metadata keyspace for MPEG-4 User Data keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataKeySpace_ISOUserData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_ISOUserData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataKeySpace_ISOUserData"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataKeySpace_ISOUserData",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatakeyspace_isouserdata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_Icy": {
      "abstract": [
        {
          "text": "Metadata keyspace for ShoutCast keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataKeySpace_Icy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_Icy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataKeySpace_Icy"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataKeySpace_Icy",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatakeyspace_icy"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_QuickTimeMetadata": {
      "abstract": [
        {
          "text": "Metadata keyspace for QuickTime Metadata keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataKeySpace_QuickTimeMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_QuickTimeMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataKeySpace_QuickTimeMetadata"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataKeySpace_QuickTimeMetadata",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatakeyspace_quicktimemetadata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_QuickTimeUserData": {
      "abstract": [
        {
          "text": "Metadata keyspace for QuickTime User Data keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataKeySpace_QuickTimeUserData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_QuickTimeUserData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataKeySpace_QuickTimeUserData"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataKeySpace_QuickTimeUserData",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatakeyspace_quicktimeuserdata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_iTunes": {
      "abstract": [
        {
          "text": "Metadata keyspace for iTunes keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataKeySpace_iTunes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_iTunes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataKeySpace_iTunes"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataKeySpace_iTunes",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatakeyspace_itunes"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types": {
      "abstract": [
        {
          "text": "Constants that describe metadata base data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Base Data Types",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-base-data-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types": {
      "abstract": [
        {
          "text": "Constants that describe metadata data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Data Types",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-data-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors": {
      "abstract": [
        {
          "text": "Error codes that indicate metadata identifier errors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Identifier Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-identifier-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers": {
      "abstract": [
        {
          "text": "Constants that describe metadata identifiers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Identifiers",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-identifiers"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors": {
      "abstract": [
        {
          "text": "Error codes that indicate metadata registry errors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Registry Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-registry-errors"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_QuickTimeUserData",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_ISOUserData",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_QuickTimeMetadata",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_iTunes",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_ID3",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_Icy",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_HLSDateRange"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_QuickTimeUserData",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_ISOUserData",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_QuickTimeMetadata",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_iTunes",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_ID3",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_Icy",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataKeySpace_HLSDateRange"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifier-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-registry-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-identifiers",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-base-data-types",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-data-types"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataKeySpace_HLSDateRange/title",
          "value": "kCMMetadataKeySpace_HLSDateRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataKeySpace_HLSDateRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataKeySpace_HLSDateRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataKeySpace_QuickTimeMetadata/title",
          "value": "kCMMetadataKeySpace_QuickTimeMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataKeySpace_QuickTimeMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataKeySpace_QuickTimeMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataKeySpace_ISOUserData/title",
          "value": "kCMMetadataKeySpace_ISOUserData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataKeySpace_ISOUserData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataKeySpace_ISOUserData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataKeySpace_Icy/title",
          "value": "kCMMetadataKeySpace_Icy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataKeySpace_Icy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataKeySpace_Icy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataKeySpace_iTunes/title",
          "value": "kCMMetadataKeySpace_iTunes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataKeySpace_iTunes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataKeySpace_iTunes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataKeySpace_ID3/title",
          "value": "kCMMetadataKeySpace_ID3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataKeySpace_ID3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataKeySpace_ID3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataKeySpace_QuickTimeUserData/title",
          "value": "kCMMetadataKeySpace_QuickTimeUserData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataKeySpace_QuickTimeUserData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataKeySpace_QuickTimeUserData"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/metadata-identifier-keyspaces"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/metadata-identifier-keyspaces"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
