{
  "abstract": [
    {
      "text": "Constants that identify metadata format descriptions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Metadata Format Description Constants"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/audio-format-desc-codes": {
      "abstract": [
        {
          "text": "Mask codes that identify audio formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/audio-format-desc-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Format Description Mask Codes",
      "type": "topic",
      "url": "/documentation/coremedia/audio-format-desc-codes"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify chroma location extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Chroma Location Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/chroma-location-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify clean aperture extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Clean Aperture Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/clean-aperture-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api": {
      "abstract": [
        {
          "text": "A media format descriptor that describes the samples in a sample buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMFormatDescription APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify color primary extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color Primary Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/color-primary-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify field detail extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Field Detail Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/field-detail-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors": {
      "abstract": [
        {
          "text": "Bridge errors the system returns from format description calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Bridge Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-bridge-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors": {
      "abstract": [
        {
          "text": "Errors the system returns from format description calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants": {
      "abstract": [
        {
          "text": "Constants that identify HEVC temporal level information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HEVC Temporal Level Info Constants",
      "type": "topic",
      "url": "/documentation/coremedia/hevc-temporal-level-info-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_AffineTransformF64": {
      "abstract": [
        {
          "text": "A type that identifies a 3x3 matrix of 64-bit big endian floating point numbers in a row-major order that specify an affine transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_AffineTransformF64"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_AffineTransformF64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataBaseDataType_AffineTransformF64"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataBaseDataType_AffineTransformF64",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadatabasedatatype_affinetransformf64"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_ConformingDataTypes": {
      "abstract": [
        {
          "text": "A key that identifies the conforming data types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_ConformingDataTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_ConformingDataTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_ConformingDataTypes"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionKey_ConformingDataTypes",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionkey_conformingdatatypes"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_DataType": {
      "abstract": [
        {
          "text": "A key that identifies the data type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_DataType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_DataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_DataType"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionKey_DataType",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionkey_datatype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_DataTypeNamespace": {
      "abstract": [
        {
          "text": "A key that identifies the data type namespace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_DataTypeNamespace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_DataTypeNamespace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_DataTypeNamespace"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionKey_DataTypeNamespace",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionkey_datatypenamespace"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_LanguageTag": {
      "abstract": [
        {
          "text": "A key that identifies the language tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_LanguageTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_LanguageTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_LanguageTag"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionKey_LanguageTag",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionkey_languagetag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_LocalID": {
      "abstract": [
        {
          "text": "A key that identifies the local identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_LocalID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_LocalID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_LocalID"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionKey_LocalID",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionkey_localid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_Namespace": {
      "abstract": [
        {
          "text": "A key that identifies the namespace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_Namespace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_Namespace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_Namespace"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionKey_Namespace",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionkey_namespace"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_SetupData": {
      "abstract": [
        {
          "text": "A key that identifies setup data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_SetupData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_SetupData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_SetupData"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionKey_SetupData",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionkey_setupdata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_StructuralDependency": {
      "abstract": [
        {
          "text": "A key that identifies the structural dependency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_StructuralDependency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_StructuralDependency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_StructuralDependency"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionKey_StructuralDependency",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionkey_structuraldependency"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_Value": {
      "abstract": [
        {
          "text": "A key that identifies the value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_Value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_Value",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionKey_Value"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionKey_Value",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionkey_value"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType": {
      "abstract": [
        {
          "text": "A specification key that identifies the data type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionmetadataspecificationkey_datatype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag": {
      "abstract": [
        {
          "text": "A specification key that identifies the extended language tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionmetadataspecificationkey_extendedlanguagetag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier": {
      "abstract": [
        {
          "text": "A specification key that identifies the identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionmetadataspecificationkey_identifier"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData": {
      "abstract": [
        {
          "text": "A specification key that identifies the setup data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionmetadataspecificationkey_setupdata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency": {
      "abstract": [
        {
          "text": "A specification key that identifies dependencies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescriptionmetadataspecificationkey_structuraldependency"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag": {
      "abstract": [
        {
          "text": "A specification key that identifies the depencency isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag"
        }
      ],
      "role": "symbol",
      "title": "kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmetadataformatdescription_structuraldependencykey_dependencyisinvalidflag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats": {
      "abstract": [
        {
          "text": "Constants that identify MPEG-2 formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MPEG-2-conformant Formats",
      "type": "topic",
      "url": "/documentation/coremedia/mpeg-2-conformant-formats"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify pixel aspect ratio extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pixel Aspect Ratio Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/pixel-aspect-ratio-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify text format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/text-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify time code format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Time Code Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/time-code-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify transfer function extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Transfer Function Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/transfer-function-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify YCbCrMatrix extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "YCbCrMatrix Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/ycbcrmatrix-extension-constants"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
        "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/audio-format-desc-codes"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_AffineTransformF64",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_ConformingDataTypes",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_DataType",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_DataTypeNamespace",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_LanguageTag",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_LocalID",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_Namespace",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_SetupData",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_StructuralDependency",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_Value",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataBaseDataType_AffineTransformF64",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_ConformingDataTypes",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_DataType",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_DataTypeNamespace",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_LanguageTag",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_LocalID",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_Namespace",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_SetupData",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_StructuralDependency",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionKey_Value",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
                "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/audio-format-desc-codes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_ConformingDataTypes/title",
          "value": "kCMMetadataFormatDescriptionKey_ConformingDataTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_ConformingDataTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionKey_ConformingDataTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_StructuralDependency/title",
          "value": "kCMMetadataFormatDescriptionKey_StructuralDependency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_StructuralDependency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionKey_StructuralDependency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency/title",
          "value": "kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_LanguageTag/title",
          "value": "kCMMetadataFormatDescriptionKey_LanguageTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_LanguageTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionKey_LanguageTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier/title",
          "value": "kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag/title",
          "value": "kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_DataTypeNamespace/title",
          "value": "kCMMetadataFormatDescriptionKey_DataTypeNamespace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_DataTypeNamespace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionKey_DataTypeNamespace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_DataType/title",
          "value": "kCMMetadataFormatDescriptionKey_DataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_DataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionKey_DataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_Value/title",
          "value": "kCMMetadataFormatDescriptionKey_Value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_Value/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionKey_Value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_AffineTransformF64/title",
          "value": "kCMMetadataBaseDataType_AffineTransformF64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataBaseDataType_AffineTransformF64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataBaseDataType_AffineTransformF64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag/title",
          "value": "kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_Namespace/title",
          "value": "kCMMetadataFormatDescriptionKey_Namespace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_Namespace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionKey_Namespace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData/title",
          "value": "kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType/title",
          "value": "kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_LocalID/title",
          "value": "kCMMetadataFormatDescriptionKey_LocalID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_LocalID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionKey_LocalID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_SetupData/title",
          "value": "kCMMetadataFormatDescriptionKey_SetupData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMetadataFormatDescriptionKey_SetupData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMetadataFormatDescriptionKey_SetupData"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/metadata-format-description-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/metadata-format-description-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
