{
  "abstract": [
    {
      "text": "Constants that identify MPEG-2 formats.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "MPEG-2-conformant Formats"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/audio-format-desc-codes": {
      "abstract": [
        {
          "text": "Mask codes that identify audio formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/audio-format-desc-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Format Description Mask Codes",
      "type": "topic",
      "url": "/documentation/coremedia/audio-format-desc-codes"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify chroma location extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Chroma Location Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/chroma-location-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify clean aperture extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Clean Aperture Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/clean-aperture-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api": {
      "abstract": [
        {
          "text": "A media format descriptor that describes the samples in a sample buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMFormatDescription APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify color primary extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color Primary Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/color-primary-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify field detail extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Field Detail Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/field-detail-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors": {
      "abstract": [
        {
          "text": "Bridge errors the system returns from format description calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Bridge Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-bridge-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors": {
      "abstract": [
        {
          "text": "Errors the system returns from format description calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants": {
      "abstract": [
        {
          "text": "Constants that identify HEVC temporal level information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HEVC Temporal Level Info Constants",
      "type": "topic",
      "url": "/documentation/coremedia/hevc-temporal-level-info-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionConformsToMPEG2VideoProfile": {
      "abstract": [
        {
          "text": "The value is a number that specifies the MPEG2 video profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionConformsToMPEG2VideoProfile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionConformsToMPEG2VideoProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionConformsToMPEG2VideoProfile"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionConformsToMPEG2VideoProfile",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionconformstompeg2videoprofile"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_RevisionLevel": {
      "abstract": [
        {
          "text": "The value is a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_RevisionLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_RevisionLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_RevisionLevel"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_RevisionLevel",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_revisionlevel"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_SpatialQuality": {
      "abstract": [
        {
          "text": "The value is a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_SpatialQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_SpatialQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_SpatialQuality"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_SpatialQuality",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_spatialquality"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_TemporalQuality": {
      "abstract": [
        {
          "text": "The value is a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_TemporalQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_TemporalQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_TemporalQuality"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_TemporalQuality",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_temporalquality"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_Vendor": {
      "abstract": [
        {
          "text": "The value is a string of four character codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_Vendor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_Vendor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_Vendor"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_Vendor",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_vendor"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_Version": {
      "abstract": [
        {
          "text": "The value is a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_Version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_Version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionExtension_Version"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionExtension_Version",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionextension_version"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionVendor_Apple": {
      "abstract": [
        {
          "text": "A string that speicifies Apple as the vendor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionVendor_Apple"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionVendor_Apple",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMFormatDescriptionVendor_Apple"
        }
      ],
      "role": "symbol",
      "title": "kCMFormatDescriptionVendor_Apple",
      "type": "topic",
      "url": "/documentation/coremedia/kcmformatdescriptionvendor_apple"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify metadata format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify pixel aspect ratio extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pixel Aspect Ratio Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/pixel-aspect-ratio-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify text format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/text-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify time code format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Time Code Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/time-code-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify transfer function extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Transfer Function Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/transfer-function-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify YCbCrMatrix extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "YCbCrMatrix Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/ycbcrmatrix-extension-constants"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/audio-format-desc-codes"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionConformsToMPEG2VideoProfile",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_TemporalQuality",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_SpatialQuality",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_Version",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_RevisionLevel",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_Vendor",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionVendor_Apple"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionConformsToMPEG2VideoProfile",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_TemporalQuality",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_SpatialQuality",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_Version",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_RevisionLevel",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionExtension_Vendor",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMFormatDescriptionVendor_Apple"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/audio-format-desc-codes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_TemporalQuality/title",
          "value": "kCMFormatDescriptionExtension_TemporalQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_TemporalQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_TemporalQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_SpatialQuality/title",
          "value": "kCMFormatDescriptionExtension_SpatialQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_SpatialQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_SpatialQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_RevisionLevel/title",
          "value": "kCMFormatDescriptionExtension_RevisionLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_RevisionLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_RevisionLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_Vendor/title",
          "value": "kCMFormatDescriptionExtension_Vendor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_Vendor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_Vendor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_Version/title",
          "value": "kCMFormatDescriptionExtension_Version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionExtension_Version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionExtension_Version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionVendor_Apple/title",
          "value": "kCMFormatDescriptionVendor_Apple"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionVendor_Apple/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionVendor_Apple"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionConformsToMPEG2VideoProfile/title",
          "value": "kCMFormatDescriptionConformsToMPEG2VideoProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMFormatDescriptionConformsToMPEG2VideoProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMFormatDescriptionConformsToMPEG2VideoProfile"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/mpeg-2-conformant-formats"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/mpeg-2-conformant-formats"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
