{
  "abstract": [
    {
      "text": "Constants that represent muxed stream types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/muxed-stream-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Muxed Stream Types"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioCodecType": {
      "abstract": [
        {
          "text": "An audio codec type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMAudioCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioCodecType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMAudioCodecType"
        }
      ],
      "role": "symbol",
      "title": "CMAudioCodecType",
      "type": "topic",
      "url": "/documentation/coremedia/cmaudiocodectype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescriptionMask": {
      "abstract": [
        {
          "text": "A type for mask bits that represent parts of an audio format description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMAudioFormatDescriptionMask"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescriptionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMAudioFormatDescriptionMask"
        }
      ],
      "role": "symbol",
      "title": "CMAudioFormatDescriptionMask",
      "type": "topic",
      "url": "/documentation/coremedia/cmaudioformatdescriptionmask"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMediaType": {
      "abstract": [
        {
          "text": "Constants that represent media types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMediaType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMediaType"
        }
      ],
      "role": "symbol",
      "title": "CMMediaType",
      "type": "topic",
      "url": "/documentation/coremedia/cmmediatype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTextDisplayFlags": {
      "abstract": [
        {
          "text": "An integer value that describes the display mode flags for text media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTextDisplayFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTextDisplayFlags"
        }
      ],
      "role": "symbol",
      "title": "CMTextDisplayFlags",
      "type": "topic",
      "url": "/documentation/coremedia/cmtextdisplayflags"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTextJustificationValue": {
      "abstract": [
        {
          "text": "An integer value that describes the justification modes for text media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTextJustificationValue"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTextJustificationValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTextJustificationValue"
        }
      ],
      "role": "symbol",
      "title": "CMTextJustificationValue",
      "type": "topic",
      "url": "/documentation/coremedia/cmtextjustificationvalue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoCodecType": {
      "abstract": [
        {
          "text": "A video codec type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoCodecType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMVideoCodecType"
        }
      ],
      "role": "symbol",
      "title": "CMVideoCodecType",
      "type": "topic",
      "url": "/documentation/coremedia/cmvideocodectype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoDimensions": {
      "abstract": [
        {
          "text": "A structure that represents video dimensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMVideoDimensions"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoDimensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMVideoDimensions"
        }
      ],
      "role": "symbol",
      "title": "CMVideoDimensions",
      "type": "topic",
      "url": "/documentation/coremedia/cmvideodimensions"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/audio-codec-types": {
      "abstract": [
        {
          "text": "Constants that represent audio codec types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/audio-codec-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Codec Types",
      "type": "topic",
      "url": "/documentation/coremedia/audio-codec-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api": {
      "abstract": [
        {
          "text": "A media format descriptor that describes the samples in a sample buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMFormatDescription APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_DV": {
      "abstract": [
        {
          "text": "DV stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMuxedStreamType_DV"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMuxedStreamType",
          "text": "CMMuxedStreamType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_DV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMuxedStreamType_DV"
        }
      ],
      "role": "symbol",
      "title": "kCMMuxedStreamType_DV",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmuxedstreamtype_dv"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_EmbeddedDeviceScreenRecording": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMuxedStreamType_EmbeddedDeviceScreenRecording"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMuxedStreamType",
          "text": "CMMuxedStreamType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_EmbeddedDeviceScreenRecording",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMuxedStreamType_EmbeddedDeviceScreenRecording"
        }
      ],
      "role": "symbol",
      "title": "kCMMuxedStreamType_EmbeddedDeviceScreenRecording",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmuxedstreamtype_embeddeddevicescreenrecording"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG1System": {
      "abstract": [
        {
          "text": "MPEG-1 System stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMuxedStreamType_MPEG1System"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMuxedStreamType",
          "text": "CMMuxedStreamType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG1System",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMuxedStreamType_MPEG1System"
        }
      ],
      "role": "symbol",
      "title": "kCMMuxedStreamType_MPEG1System",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmuxedstreamtype_mpeg1system"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG2Program": {
      "abstract": [
        {
          "text": "MPEG-2 Program stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMuxedStreamType_MPEG2Program"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMuxedStreamType",
          "text": "CMMuxedStreamType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG2Program",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMuxedStreamType_MPEG2Program"
        }
      ],
      "role": "symbol",
      "title": "kCMMuxedStreamType_MPEG2Program",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmuxedstreamtype_mpeg2program"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG2Transport": {
      "abstract": [
        {
          "text": "MPEG-2 Transport stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMuxedStreamType_MPEG2Transport"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMMuxedStreamType",
          "text": "CMMuxedStreamType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG2Transport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMuxedStreamType_MPEG2Transport"
        }
      ],
      "role": "symbol",
      "title": "kCMMuxedStreamType_MPEG2Transport",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmuxedstreamtype_mpeg2transport"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/media-type-constants": {
      "abstract": [
        {
          "text": "Constants that represent media types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/media-type-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media Type Constants",
      "type": "topic",
      "url": "/documentation/coremedia/media-type-constants"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoDimensions",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescriptionMask",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMediaType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioCodecType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoCodecType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTextDisplayFlags",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTextJustificationValue",
        "doc://com.apple.coremedia/documentation/CoreMedia/media-type-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/audio-codec-types"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_DV",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG1System",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG2Program",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG2Transport",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_EmbeddedDeviceScreenRecording"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_DV",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG1System",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG2Program",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_MPEG2Transport",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMuxedStreamType_EmbeddedDeviceScreenRecording"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoDimensions",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioFormatDescriptionMask",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMediaType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMAudioCodecType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMVideoCodecType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTextDisplayFlags",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTextJustificationValue",
                "doc://com.apple.coremedia/documentation/CoreMedia/media-type-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/audio-codec-types"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMuxedStreamType_MPEG2Transport/title",
          "value": "kCMMuxedStreamType_MPEG2Transport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMuxedStreamType_MPEG2Transport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMuxedStreamType_MPEG2Transport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextJustificationValue/title",
          "value": "CMTextJustificationValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextJustificationValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextJustificationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextJustificationValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextJustificationValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMuxedStreamType_MPEG1System/title",
          "value": "kCMMuxedStreamType_MPEG1System"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMuxedStreamType_MPEG1System/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMuxedStreamType_MPEG1System"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMuxedStreamType_EmbeddedDeviceScreenRecording/title",
          "value": "kCMMuxedStreamType_EmbeddedDeviceScreenRecording"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMuxedStreamType_EmbeddedDeviceScreenRecording/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMuxedStreamType_EmbeddedDeviceScreenRecording"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoDimensions/title",
          "value": "CMVideoDimensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoDimensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoDimensions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoDimensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioFormatDescriptionMask/title",
          "value": "CMAudioFormatDescriptionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioFormatDescriptionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioFormatDescriptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioFormatDescriptionMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioFormatDescriptionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMediaType/title",
          "value": "CMMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMediaType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoCodecType/title",
          "value": "CMVideoCodecType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoCodecType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMVideoCodecType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMVideoCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextDisplayFlags/title",
          "value": "CMTextDisplayFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextDisplayFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextDisplayFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextDisplayFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextDisplayFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMuxedStreamType_MPEG2Program/title",
          "value": "kCMMuxedStreamType_MPEG2Program"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMuxedStreamType_MPEG2Program/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMuxedStreamType_MPEG2Program"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMuxedStreamType_DV/title",
          "value": "kCMMuxedStreamType_DV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMuxedStreamType_DV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMuxedStreamType_DV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioCodecType/title",
          "value": "CMAudioCodecType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioCodecType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMAudioCodecType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMAudioCodecType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/muxed-stream-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/muxed-stream-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
