{
  "abstract": [
    {
      "text": "Keys that specify attachments to individual samples in a buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmsamplebuffer-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/sample-attachment-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Sample Attachment Keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can get and set sample-level attachments in a sample buffer using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBufferGetSampleAttachmentsArray(_:createIfNecessary:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBufferGetSampleAttachmentsArray(_:createIfNecessary:)": {
      "abstract": [
        {
          "text": "Retrieves an array of sample attachment dictionaries that represents each sample in a sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSampleBufferGetSampleAttachmentsArray"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "createIfNecessary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBufferGetSampleAttachmentsArray(_:createIfNecessary:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSampleBufferGetSampleAttachmentsArray"
        }
      ],
      "role": "symbol",
      "title": "CMSampleBufferGetSampleAttachmentsArray(_:createIfNecessary:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffergetsampleattachmentsarray(_:createifnecessary:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmsamplebuffer-api": {
      "abstract": [
        {
          "text": "An object that contains zero or more media samples of a uniform media type.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmsamplebuffer-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMSampleBuffer APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DependsOnOthers": {
      "abstract": [
        {
          "text": "Indicates whether the sample depends on other samples for decoding (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_DependsOnOthers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DependsOnOthers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_DependsOnOthers"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_DependsOnOthers",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_dependsonothers"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DisplayImmediately": {
      "abstract": [
        {
          "text": "Indicates whether the sample should be displayed immediately (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_DisplayImmediately"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DisplayImmediately",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_DisplayImmediately"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_DisplayImmediately",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_displayimmediately"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DoNotDisplay": {
      "abstract": [
        {
          "text": "Indicates whether the sample should be decoded but not displayed (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_DoNotDisplay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DoNotDisplay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_DoNotDisplay"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_DoNotDisplay",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_donotdisplay"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_EarlierDisplayTimesAllowed": {
      "abstract": [
        {
          "text": "Indicates whether later samples may have earlier display times (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_EarlierDisplayTimesAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_EarlierDisplayTimesAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_EarlierDisplayTimesAllowed"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_EarlierDisplayTimesAllowed",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_earlierdisplaytimesallowed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HasRedundantCoding": {
      "abstract": [
        {
          "text": "Indicates whether the sample has redundant coding (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HasRedundantCoding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HasRedundantCoding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_HasRedundantCoding"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_HasRedundantCoding",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_hasredundantcoding"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_IsDependedOnByOthers": {
      "abstract": [
        {
          "text": "Indicates whether other samples depend on this sample for decoding (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_IsDependedOnByOthers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_IsDependedOnByOthers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_IsDependedOnByOthers"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_IsDependedOnByOthers",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_isdependedonbyothers"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_NotSync": {
      "abstract": [
        {
          "text": "Indicates whether the sample is a sync sample (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_NotSync"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_NotSync",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_NotSync"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_NotSync",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_notsync"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_PartialSync": {
      "abstract": [
        {
          "text": "Indicates whether the sample is a partial sync sample (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_PartialSync"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_PartialSync",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_PartialSync"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_PartialSync",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_partialsync"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_PostDecodeProcessingMetadata": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_PostDecodeProcessingMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_PostDecodeProcessingMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleAttachmentKey_PostDecodeProcessingMetadata"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleAttachmentKey_PostDecodeProcessingMetadata",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsampleattachmentkey_postdecodeprocessingmetadata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately": {
      "abstract": [
        {
          "text": "Tells that the empty marker should be dequeued immediately regardless of its timestamp (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_displayemptymediaimmediately"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DrainAfterDecoding": {
      "abstract": [
        {
          "text": "Indicates whether the sample buffer should be drained after decoding type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_DrainAfterDecoding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DrainAfterDecoding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_DrainAfterDecoding"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_DrainAfterDecoding",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_drainafterdecoding"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DroppedFrameReason": {
      "abstract": [
        {
          "text": "Indicates the reason the current video frame was dropped (type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_DroppedFrameReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DroppedFrameReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_DroppedFrameReason"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_DroppedFrameReason",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_droppedframereason"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo": {
      "abstract": [
        {
          "text": "Indicates additional information regarding the dropped video frame (type ",
          "type": "text"
        },
        {
          "code": "CFString",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_droppedframereasoninfo"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_EmptyMedia": {
      "abstract": [
        {
          "text": "Marks an intentionally empty interval in the sequence of samples (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_EmptyMedia"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_EmptyMedia",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_EmptyMedia"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_EmptyMedia",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_emptymedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration": {
      "abstract": [
        {
          "text": "Indicates that sample buffer’s decode timestamp may be used to define the previous sample buffer’s duration (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_endsprevioussampleduration"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence": {
      "abstract": [
        {
          "text": "Fill the difference between discontiguous sample buffers with silence (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_filldiscontinuitieswithsilence"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_ForceKeyFrame": {
      "abstract": [
        {
          "text": "Indicates that the current or next video sample buffer should be forced to be encoded as a key frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_ForceKeyFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_ForceKeyFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_ForceKeyFrame"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_ForceKeyFrame",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_forcekeyframe"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_GradualDecoderRefresh": {
      "abstract": [
        {
          "text": "Indicates the decoder refresh count (type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_GradualDecoderRefresh"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_GradualDecoderRefresh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_GradualDecoderRefresh"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_GradualDecoderRefresh",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_gradualdecoderrefresh"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_PermanentEmptyMedia": {
      "abstract": [
        {
          "text": "Marks the end of the sequence of samples (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_PermanentEmptyMedia"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_PermanentEmptyMedia",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_PermanentEmptyMedia"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_PermanentEmptyMedia",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_permanentemptymedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed": {
      "abstract": [
        {
          "text": "If present, indicates that decode pipelines should post a notification when consuming the sample buffer(type ",
          "type": "text"
        },
        {
          "code": "CFDictionary",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_postnotificationwhenconsumed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_ResetDecoderBeforeDecoding": {
      "abstract": [
        {
          "text": "Indicates whether the sample buffer should be reset before decoding (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_ResetDecoderBeforeDecoding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_ResetDecoderBeforeDecoding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_ResetDecoderBeforeDecoding"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_ResetDecoderBeforeDecoding",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_resetdecoderbeforedecoding"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_ResumeOutput": {
      "abstract": [
        {
          "text": "If present, indicates that output should be resumed following a discontinuity ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_ResumeOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_ResumeOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_ResumeOutput"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_ResumeOutput",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_resumeoutput"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_Reverse": {
      "abstract": [
        {
          "text": "Indicates that the decoded contents of the sample buffer should be reversed (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ", default false).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_Reverse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_Reverse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_Reverse"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_Reverse",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_reverse"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_SampleReferenceByteOffset": {
      "abstract": [
        {
          "text": "Indicates the byte offset at which the sample data begins (type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_SampleReferenceByteOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_SampleReferenceByteOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_SampleReferenceByteOffset"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_SampleReferenceByteOffset",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_samplereferencebyteoffset"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_SampleReferenceURL": {
      "abstract": [
        {
          "text": "Indicates the URL where the sample data is (type ",
          "type": "text"
        },
        {
          "code": "CFURL",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_SampleReferenceURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_SampleReferenceURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_SampleReferenceURL"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_SampleReferenceURL",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_samplereferenceurl"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_SpeedMultiplier": {
      "abstract": [
        {
          "text": "The factor by which the sample buffer’s presentation should be accelerated (type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": ", default 1.0).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_SpeedMultiplier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_SpeedMultiplier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_SpeedMultiplier"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_SpeedMultiplier",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_speedmultiplier"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_StillImageLensStabilizationInfo": {
      "abstract": [
        {
          "text": "Indicates information about the lens stabilization applied to the current still image buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_StillImageLensStabilizationInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_StillImageLensStabilizationInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_StillImageLensStabilizationInfo"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_StillImageLensStabilizationInfo",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_stillimagelensstabilizationinfo"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_TransitionID": {
      "abstract": [
        {
          "text": "Marks a transition from one source of buffers to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_TransitionID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_TransitionID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_TransitionID"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_TransitionID",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_transitionid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_TrimDurationAtEnd": {
      "abstract": [
        {
          "text": "The duration that should be removed at the end of the sample buffer, after decoding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_TrimDurationAtEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_TrimDurationAtEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_TrimDurationAtEnd"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_TrimDurationAtEnd",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_trimdurationatend"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_TrimDurationAtStart": {
      "abstract": [
        {
          "text": "The duration that should be removed at the beginning of the sample buffer, after decoding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_TrimDurationAtStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_TrimDurationAtStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferAttachmentKey_TrimDurationAtStart"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferAttachmentKey_TrimDurationAtStart",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferattachmentkey_trimdurationatstart"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch": {
      "abstract": [
        {
          "text": "A discontinuity was caused by a camera mode switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferdroppedframereasoninfo_cameramodeswitch"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_Discontinuity": {
      "abstract": [
        {
          "text": "An unknown number of frames were dropped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferDroppedFrameReason_Discontinuity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_Discontinuity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferDroppedFrameReason_Discontinuity"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferDroppedFrameReason_Discontinuity",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferdroppedframereason_discontinuity"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_FrameWasLate": {
      "abstract": [
        {
          "text": "The frame was dropped because it was late.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferDroppedFrameReason_FrameWasLate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_FrameWasLate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferDroppedFrameReason_FrameWasLate"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferDroppedFrameReason_FrameWasLate",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferdroppedframereason_framewaslate"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_OutOfBuffers": {
      "abstract": [
        {
          "text": "The frame was dropped because the module providing frames is out of buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferDroppedFrameReason_OutOfBuffers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_OutOfBuffers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferDroppedFrameReason_OutOfBuffers"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferDroppedFrameReason_OutOfBuffers",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferdroppedframereason_outofbuffers"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferLensStabilizationInfo_Active": {
      "abstract": [
        {
          "text": "The lens stabilization module was active for the duration this buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferLensStabilizationInfo_Active"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferLensStabilizationInfo_Active",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferLensStabilizationInfo_Active"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferLensStabilizationInfo_Active",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferlensstabilizationinfo_active"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferLensStabilizationInfo_Off": {
      "abstract": [
        {
          "text": "The lens stabilization module was not used during this capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferLensStabilizationInfo_Off"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferLensStabilizationInfo_Off",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferLensStabilizationInfo_Off"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferLensStabilizationInfo_Off",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferlensstabilizationinfo_off"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferLensStabilizationInfo_OutOfRange": {
      "abstract": [
        {
          "text": "The motion of the device or duration of the capture was outside of what the stabilization mechanism could support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferLensStabilizationInfo_OutOfRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferLensStabilizationInfo_OutOfRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferLensStabilizationInfo_OutOfRange"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferLensStabilizationInfo_OutOfRange",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferlensstabilizationinfo_outofrange"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferLensStabilizationInfo_Unavailable": {
      "abstract": [
        {
          "text": "The lens stabilization module was unavailable for use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferLensStabilizationInfo_Unavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferLensStabilizationInfo_Unavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferLensStabilizationInfo_Unavailable"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferLensStabilizationInfo_Unavailable",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferlensstabilizationinfo_unavailable"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Attachments",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBufferGetSampleAttachmentsArray(_:createIfNecessary:)"
      ],
      "title": "Managing Attachments"
    }
  ],
  "topicSections": [
    {
      "anchor": "Sample-Keys",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_NotSync",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_PartialSync",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DependsOnOthers",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_IsDependedOnByOthers",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DisplayImmediately",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DoNotDisplay",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_EarlierDisplayTimesAllowed",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HasRedundantCoding",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_PostDecodeProcessingMetadata"
      ],
      "title": "Sample Keys"
    },
    {
      "anchor": "Sample-Buffer-Keys",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DrainAfterDecoding",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DroppedFrameReason",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_FrameWasLate",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_OutOfBuffers",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_Discontinuity",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_EmptyMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_ForceKeyFrame",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_GradualDecoderRefresh",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_PermanentEmptyMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_ResetDecoderBeforeDecoding",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_ResumeOutput",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_Reverse",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_SampleReferenceByteOffset",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_SampleReferenceURL",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_SpeedMultiplier",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_StillImageLensStabilizationInfo",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferLensStabilizationInfo_Active",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferLensStabilizationInfo_OutOfRange",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferLensStabilizationInfo_Unavailable",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferLensStabilizationInfo_Off",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_TransitionID",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_TrimDurationAtEnd",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_TrimDurationAtStart"
      ],
      "title": "Sample Buffer Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Sample-Keys",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_NotSync",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_PartialSync",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DependsOnOthers",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_IsDependedOnByOthers",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DisplayImmediately",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_DoNotDisplay",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_EarlierDisplayTimesAllowed",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_HasRedundantCoding",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleAttachmentKey_PostDecodeProcessingMetadata"
              ],
              "title": "Sample Keys"
            },
            {
              "anchor": "Sample-Buffer-Keys",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DrainAfterDecoding",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DroppedFrameReason",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_FrameWasLate",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_OutOfBuffers",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReason_Discontinuity",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_EmptyMedia",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_ForceKeyFrame",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_GradualDecoderRefresh",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_PermanentEmptyMedia",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_ResetDecoderBeforeDecoding",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_ResumeOutput",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_Reverse",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_SampleReferenceByteOffset",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_SampleReferenceURL",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_SpeedMultiplier",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_StillImageLensStabilizationInfo",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferLensStabilizationInfo_Active",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferLensStabilizationInfo_OutOfRange",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferLensStabilizationInfo_Unavailable",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferLensStabilizationInfo_Off",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_TransitionID",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_TrimDurationAtEnd",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferAttachmentKey_TrimDurationAtStart"
              ],
              "title": "Sample Buffer Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Attachments",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBufferGetSampleAttachmentsArray(_:createIfNecessary:)"
              ],
              "title": "Managing Attachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_ResetDecoderBeforeDecoding/title",
          "value": "kCMSampleBufferAttachmentKey_ResetDecoderBeforeDecoding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_ResetDecoderBeforeDecoding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_ResetDecoderBeforeDecoding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_EmptyMedia/title",
          "value": "kCMSampleBufferAttachmentKey_EmptyMedia"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_EmptyMedia/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_EmptyMedia"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed/title",
          "value": "kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_EarlierDisplayTimesAllowed/title",
          "value": "kCMSampleAttachmentKey_EarlierDisplayTimesAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_EarlierDisplayTimesAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_EarlierDisplayTimesAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferDroppedFrameReason_Discontinuity/title",
          "value": "kCMSampleBufferDroppedFrameReason_Discontinuity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferDroppedFrameReason_Discontinuity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferDroppedFrameReason_Discontinuity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_GradualDecoderRefresh/title",
          "value": "kCMSampleBufferAttachmentKey_GradualDecoderRefresh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_GradualDecoderRefresh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_GradualDecoderRefresh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_PostDecodeProcessingMetadata/title",
          "value": "kCMSampleAttachmentKey_PostDecodeProcessingMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_PostDecodeProcessingMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_PostDecodeProcessingMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_PartialSync/title",
          "value": "kCMSampleAttachmentKey_PartialSync"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_PartialSync/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_PartialSync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_TrimDurationAtStart/title",
          "value": "kCMSampleBufferAttachmentKey_TrimDurationAtStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_TrimDurationAtStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_TrimDurationAtStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_SampleReferenceByteOffset/title",
          "value": "kCMSampleBufferAttachmentKey_SampleReferenceByteOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_SampleReferenceByteOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_SampleReferenceByteOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately/title",
          "value": "kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration/title",
          "value": "kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferLensStabilizationInfo_Unavailable/title",
          "value": "kCMSampleBufferLensStabilizationInfo_Unavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferLensStabilizationInfo_Unavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferLensStabilizationInfo_Unavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_PermanentEmptyMedia/title",
          "value": "kCMSampleBufferAttachmentKey_PermanentEmptyMedia"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_PermanentEmptyMedia/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_PermanentEmptyMedia"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_SpeedMultiplier/title",
          "value": "kCMSampleBufferAttachmentKey_SpeedMultiplier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_SpeedMultiplier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_SpeedMultiplier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence/title",
          "value": "kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_ForceKeyFrame/title",
          "value": "kCMSampleBufferAttachmentKey_ForceKeyFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_ForceKeyFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_ForceKeyFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferLensStabilizationInfo_Off/title",
          "value": "kCMSampleBufferLensStabilizationInfo_Off"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferLensStabilizationInfo_Off/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferLensStabilizationInfo_Off"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_SampleReferenceURL/title",
          "value": "kCMSampleBufferAttachmentKey_SampleReferenceURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_SampleReferenceURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_SampleReferenceURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_StillImageLensStabilizationInfo/title",
          "value": "kCMSampleBufferAttachmentKey_StillImageLensStabilizationInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_StillImageLensStabilizationInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_StillImageLensStabilizationInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_DisplayImmediately/title",
          "value": "kCMSampleAttachmentKey_DisplayImmediately"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_DisplayImmediately/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_DisplayImmediately"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferDroppedFrameReason_OutOfBuffers/title",
          "value": "kCMSampleBufferDroppedFrameReason_OutOfBuffers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferDroppedFrameReason_OutOfBuffers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferDroppedFrameReason_OutOfBuffers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_TrimDurationAtEnd/title",
          "value": "kCMSampleBufferAttachmentKey_TrimDurationAtEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_TrimDurationAtEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_TrimDurationAtEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_DroppedFrameReason/title",
          "value": "kCMSampleBufferAttachmentKey_DroppedFrameReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_DroppedFrameReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_DroppedFrameReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo/title",
          "value": "kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_DependsOnOthers/title",
          "value": "kCMSampleAttachmentKey_DependsOnOthers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_DependsOnOthers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_DependsOnOthers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_ResumeOutput/title",
          "value": "kCMSampleBufferAttachmentKey_ResumeOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_ResumeOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_ResumeOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_Reverse/title",
          "value": "kCMSampleBufferAttachmentKey_Reverse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_Reverse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_Reverse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleBufferGetSampleAttachmentsArray(_:createIfNecessary:)/title",
          "value": "CMSampleBufferGetSampleAttachmentsArray"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleBufferGetSampleAttachmentsArray(_:createIfNecessary:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSampleBufferGetSampleAttachmentsArray"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch/title",
          "value": "kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferDroppedFrameReason_FrameWasLate/title",
          "value": "kCMSampleBufferDroppedFrameReason_FrameWasLate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferDroppedFrameReason_FrameWasLate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferDroppedFrameReason_FrameWasLate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_NotSync/title",
          "value": "kCMSampleAttachmentKey_NotSync"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_NotSync/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_NotSync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferLensStabilizationInfo_Active/title",
          "value": "kCMSampleBufferLensStabilizationInfo_Active"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferLensStabilizationInfo_Active/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferLensStabilizationInfo_Active"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_TransitionID/title",
          "value": "kCMSampleBufferAttachmentKey_TransitionID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_TransitionID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_TransitionID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_IsDependedOnByOthers/title",
          "value": "kCMSampleAttachmentKey_IsDependedOnByOthers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_IsDependedOnByOthers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_IsDependedOnByOthers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_DoNotDisplay/title",
          "value": "kCMSampleAttachmentKey_DoNotDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_DoNotDisplay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_DoNotDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferLensStabilizationInfo_OutOfRange/title",
          "value": "kCMSampleBufferLensStabilizationInfo_OutOfRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferLensStabilizationInfo_OutOfRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferLensStabilizationInfo_OutOfRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_DrainAfterDecoding/title",
          "value": "kCMSampleBufferAttachmentKey_DrainAfterDecoding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferAttachmentKey_DrainAfterDecoding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferAttachmentKey_DrainAfterDecoding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HasRedundantCoding/title",
          "value": "kCMSampleAttachmentKey_HasRedundantCoding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleAttachmentKey_HasRedundantCoding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleAttachmentKey_HasRedundantCoding"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/sample-attachment-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/sample-attachment-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
