{
  "abstract": [
    {
      "text": "Flags that customize the behavior of framework operations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmsamplebuffer-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/sample-buffer-flags"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Sample Buffer Flags"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBuffer": {
      "abstract": [
        {
          "text": "A reference to a buffer object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBuffer"
        }
      ],
      "role": "symbol",
      "title": "CMBuffer",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetSizeCallback": {
      "abstract": [
        {
          "text": "A client callback that returns a size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMBufferGetSizeCallback"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetSizeCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMBufferGetSizeCallback"
        }
      ],
      "role": "symbol",
      "title": "CMBufferGetSizeCallback",
      "type": "topic",
      "url": "/documentation/coremedia/cmbuffergetsizecallback"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount": {
      "abstract": [
        {
          "text": "A datatype that represents an item count.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMItemCount"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMItemCount"
        }
      ],
      "role": "symbol",
      "title": "CMItemCount",
      "type": "topic",
      "url": "/documentation/coremedia/cmitemcount"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMItemIndex": {
      "abstract": [
        {
          "text": "A datatype that represents an item index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMItemIndex"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMItemIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMItemIndex"
        }
      ],
      "role": "symbol",
      "title": "CMItemIndex",
      "type": "topic",
      "url": "/documentation/coremedia/cmitemindex"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedStreamType": {
      "abstract": [
        {
          "text": "A datatype that represents a muxed stream of data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMuxedStreamType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedStreamType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMuxedStreamType"
        }
      ],
      "role": "symbol",
      "title": "CMMuxedStreamType",
      "type": "topic",
      "url": "/documentation/coremedia/cmmuxedstreamtype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMPersistentTrackID": {
      "abstract": [
        {
          "text": "A datatype that represents a persistent track identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMPersistentTrackID"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMPersistentTrackID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMPersistentTrackID"
        }
      ],
      "role": "symbol",
      "title": "CMPersistentTrackID",
      "type": "topic",
      "url": "/documentation/coremedia/cmpersistenttrackid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer": {
      "abstract": [
        {
          "text": "A reference to a buffer of media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSampleBuffer"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSampleBuffer"
        }
      ],
      "role": "symbol",
      "title": "CMSampleBuffer",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleTimingInfo": {
      "abstract": [
        {
          "text": "A collection of timing information for a sample in a sample buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSampleTimingInfo"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleTimingInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSampleTimingInfo"
        }
      ],
      "role": "symbol",
      "title": "CMSampleTimingInfo",
      "type": "topic",
      "url": "/documentation/coremedia/cmsampletiminginfo"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmsamplebuffer-api": {
      "abstract": [
        {
          "text": "An object that contains zero or more media samples of a uniform media type.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmsamplebuffer-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMSampleBuffer APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferFlag_AudioBufferList_Assure16ByteAlignment": {
      "abstract": [
        {
          "text": "Indicates that memory involved in audio buffer lists is 16-byte aligned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferFlag_AudioBufferList_Assure16ByteAlignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferFlag_AudioBufferList_Assure16ByteAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferFlag_AudioBufferList_Assure16ByteAlignment"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferFlag_AudioBufferList_Assure16ByteAlignment",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferflag_audiobufferlist_assure16bytealignment"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleTimingInfo",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBuffer",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetSizeCallback",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMItemIndex",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMPersistentTrackID",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedStreamType"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferFlag_AudioBufferList_Assure16ByteAlignment"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferFlag_AudioBufferList_Assure16ByteAlignment"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBuffer",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleTimingInfo",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBuffer",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMBufferGetSizeCallback",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMItemIndex",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMItemCount",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMPersistentTrackID",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMuxedStreamType"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemCount/title",
          "value": "CMItemCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMItemCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMItemCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleBuffer/title",
          "value": "CMSampleBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSampleBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSampleBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetSizeCallback/title",
          "value": "CMBufferGetSizeCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetSizeCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetSizeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBufferGetSizeCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferGetSizeCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMuxedStreamType/title",
          "value": "CMMuxedStreamType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMuxedStreamType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMuxedStreamType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMuxedStreamType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMuxedStreamType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleTimingInfo/title",
          "value": "CMSampleTimingInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleTimingInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSampleTimingInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleTimingInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSampleTimingInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemIndex/title",
          "value": "CMItemIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMItemIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMItemIndex/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMItemIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBuffer/title",
          "value": "CMBufferRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMBufferRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPersistentTrackID/title",
          "value": "CMPersistentTrackID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPersistentTrackID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPersistentTrackID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPersistentTrackID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPersistentTrackID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferFlag_AudioBufferList_Assure16ByteAlignment/title",
          "value": "kCMSampleBufferFlag_AudioBufferList_Assure16ByteAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferFlag_AudioBufferList_Assure16ByteAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferFlag_AudioBufferList_Assure16ByteAlignment"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/sample-buffer-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/sample-buffer-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
