{
  "abstract": [
    {
      "text": "Notifications the system posts when processing sample buffer objects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmsamplebuffer-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/sample-buffer-notifications"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Sample Buffer Notifications"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBufferSetDataReady(_:)": {
      "abstract": [
        {
          "text": "Marks a sample buffer’s data as ready for use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSampleBufferSetDataReady"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBufferSetDataReady(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSampleBufferSetDataReady"
        }
      ],
      "role": "symbol",
      "title": "CMSampleBufferSetDataReady(_:)",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffersetdataready(_:)"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmsamplebuffer-api": {
      "abstract": [
        {
          "text": "An object that contains zero or more media samples of a uniform media type.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmsamplebuffer-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMSampleBuffer APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmsamplebuffer-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS": {
      "abstract": [
        {
          "text": "Specifies the maximum presentation timestamp of upcoming output samples (type ",
          "type": "text"
        },
        {
          "code": "CFDictionary",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferconduitnotificationparameter_maxupcomingoutputpts"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS": {
      "abstract": [
        {
          "text": "Specifies the minimum presentation timestamp of upcoming output samples (type ",
          "type": "text"
        },
        {
          "code": "CFDictionary",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferconduitnotificationparameter_minupcomingoutputpts"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_ResumeTag": {
      "abstract": [
        {
          "text": "Specifies a tag to be attached to the first sample buffer following a discontinuity (type ",
          "type": "text"
        },
        {
          "code": "CFNumber",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotificationParameter_ResumeTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_ResumeTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotificationParameter_ResumeTag"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferConduitNotificationParameter_ResumeTag",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferconduitnotificationparameter_resumetag"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange": {
      "abstract": [
        {
          "text": "Indicates that the presentation timestamps of upcoming output samples may overlap those of samples queued for output (type ",
          "type": "text"
        },
        {
          "code": "CFBoolean",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferconduitnotificationparameter_upcomingoutputptsrangemayoverlapqueuedoutputptsrange"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_InhibitOutputUntil": {
      "abstract": [
        {
          "text": "Posted on a conduit of sample buffers to announce a coming discontinuity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotification_InhibitOutputUntil"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_InhibitOutputUntil",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotification_InhibitOutputUntil"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferConduitNotification_InhibitOutputUntil",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferconduitnotification_inhibitoutputuntil"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_ResetOutput": {
      "abstract": [
        {
          "text": "Posted on a conduit of sample buffers to request invalidation of pending output data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotification_ResetOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_ResetOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotification_ResetOutput"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferConduitNotification_ResetOutput",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferconduitnotification_resetoutput"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged": {
      "abstract": [
        {
          "text": "Posted on a conduit of video sample buffers to report information about the range of upcoming output presentation timestamps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferconduitnotification_upcomingoutputptsrangechanged"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConsumerNotification_BufferConsumed": {
      "abstract": [
        {
          "text": "Optionally posted when a sample buffer is consumed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConsumerNotification_BufferConsumed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConsumerNotification_BufferConsumed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferConsumerNotification_BufferConsumed"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferConsumerNotification_BufferConsumed",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebufferconsumernotification_bufferconsumed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferNotificationParameter_OSStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferNotificationParameter_OSStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferNotificationParameter_OSStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferNotificationParameter_OSStatus"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferNotificationParameter_OSStatus",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebuffernotificationparameter_osstatus"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferNotification_DataBecameReady": {
      "abstract": [
        {
          "text": "Posted on a sample buffer by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSampleBufferSetDataReady(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function when the buffer becomes ready.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferNotification_DataBecameReady"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferNotification_DataBecameReady",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferNotification_DataBecameReady"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferNotification_DataBecameReady",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebuffernotification_databecameready"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferNotification_DataFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSampleBufferNotification_DataFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferNotification_DataFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSampleBufferNotification_DataFailed"
        }
      ],
      "role": "symbol",
      "title": "kCMSampleBufferNotification_DataFailed",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsamplebuffernotification_datafailed"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Sample-Buffer-Notifications",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferNotification_DataBecameReady",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferNotification_DataFailed",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferNotificationParameter_OSStatus",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConsumerNotification_BufferConsumed"
      ],
      "title": "Sample Buffer Notifications"
    },
    {
      "anchor": "Sample-Buffer-Conduit-Notifications",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_ResetOutput",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_InhibitOutputUntil",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_ResumeTag"
      ],
      "title": "Sample Buffer Conduit Notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Sample-Buffer-Notifications",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferNotification_DataBecameReady",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferNotification_DataFailed",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferNotificationParameter_OSStatus",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConsumerNotification_BufferConsumed"
              ],
              "title": "Sample Buffer Notifications"
            },
            {
              "anchor": "Sample-Buffer-Conduit-Notifications",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_ResetOutput",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_InhibitOutputUntil",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSampleBufferConduitNotificationParameter_ResumeTag"
              ],
              "title": "Sample Buffer Conduit Notifications"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange/title",
          "value": "kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS/title",
          "value": "kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotification_InhibitOutputUntil/title",
          "value": "kCMSampleBufferConduitNotification_InhibitOutputUntil"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotification_InhibitOutputUntil/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferConduitNotification_InhibitOutputUntil"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConsumerNotification_BufferConsumed/title",
          "value": "kCMSampleBufferConsumerNotification_BufferConsumed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConsumerNotification_BufferConsumed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferConsumerNotification_BufferConsumed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotification_ResetOutput/title",
          "value": "kCMSampleBufferConduitNotification_ResetOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotification_ResetOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferConduitNotification_ResetOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged/title",
          "value": "kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS/title",
          "value": "kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleBufferSetDataReady(_:)/title",
          "value": "CMSampleBufferSetDataReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSampleBufferSetDataReady(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSampleBufferSetDataReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferNotificationParameter_OSStatus/title",
          "value": "kCMSampleBufferNotificationParameter_OSStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferNotificationParameter_OSStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferNotificationParameter_OSStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferNotification_DataFailed/title",
          "value": "kCMSampleBufferNotification_DataFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferNotification_DataFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferNotification_DataFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotificationParameter_ResumeTag/title",
          "value": "kCMSampleBufferConduitNotificationParameter_ResumeTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferConduitNotificationParameter_ResumeTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferConduitNotificationParameter_ResumeTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferNotification_DataBecameReady/title",
          "value": "kCMSampleBufferNotification_DataBecameReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSampleBufferNotification_DataBecameReady/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSampleBufferNotification_DataBecameReady"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/sample-buffer-notifications"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/sample-buffer-notifications"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
