{
  "abstract": [
    {
      "text": "Error codes that simple queue operations generate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmsimplequeue-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/simple-queue-errors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Simple Queue Error Codes"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmsimplequeue-api": {
      "abstract": [
        {
          "text": "A simple, lockless FIFO queue of elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmsimplequeue-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMSimpleQueue APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmsimplequeue-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSimpleQueueError_AllocationFailed": {
      "abstract": [
        {
          "text": "The system failed to allocate memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSimpleQueueError_AllocationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSimpleQueueError_AllocationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSimpleQueueError_AllocationFailed"
        }
      ],
      "role": "symbol",
      "title": "kCMSimpleQueueError_AllocationFailed",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsimplequeueerror_allocationfailed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSimpleQueueError_ParameterOutOfRange": {
      "abstract": [
        {
          "text": "You passed a parameter to a function that’s outside the range of allowed values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSimpleQueueError_ParameterOutOfRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSimpleQueueError_ParameterOutOfRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSimpleQueueError_ParameterOutOfRange"
        }
      ],
      "role": "symbol",
      "title": "kCMSimpleQueueError_ParameterOutOfRange",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsimplequeueerror_parameteroutofrange"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSimpleQueueError_QueueIsFull": {
      "abstract": [
        {
          "text": "An operation failed because the queue is full.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSimpleQueueError_QueueIsFull"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSimpleQueueError_QueueIsFull",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSimpleQueueError_QueueIsFull"
        }
      ],
      "role": "symbol",
      "title": "kCMSimpleQueueError_QueueIsFull",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsimplequeueerror_queueisfull"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMSimpleQueueError_RequiredParameterMissing": {
      "abstract": [
        {
          "text": "You failed to pass a required parameter to a function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMSimpleQueueError_RequiredParameterMissing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMSimpleQueueError_RequiredParameterMissing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMSimpleQueueError_RequiredParameterMissing"
        }
      ],
      "role": "symbol",
      "title": "kCMSimpleQueueError_RequiredParameterMissing",
      "type": "topic",
      "url": "/documentation/coremedia/kcmsimplequeueerror_requiredparametermissing"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSimpleQueueError_AllocationFailed",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSimpleQueueError_QueueIsFull",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSimpleQueueError_ParameterOutOfRange",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMSimpleQueueError_RequiredParameterMissing"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSimpleQueueError_AllocationFailed",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSimpleQueueError_QueueIsFull",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSimpleQueueError_ParameterOutOfRange",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMSimpleQueueError_RequiredParameterMissing"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSimpleQueueError_QueueIsFull/title",
          "value": "kCMSimpleQueueError_QueueIsFull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSimpleQueueError_QueueIsFull/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSimpleQueueError_QueueIsFull"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSimpleQueueError_ParameterOutOfRange/title",
          "value": "kCMSimpleQueueError_ParameterOutOfRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSimpleQueueError_ParameterOutOfRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSimpleQueueError_ParameterOutOfRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSimpleQueueError_AllocationFailed/title",
          "value": "kCMSimpleQueueError_AllocationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSimpleQueueError_AllocationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSimpleQueueError_AllocationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSimpleQueueError_RequiredParameterMissing/title",
          "value": "kCMSimpleQueueError_RequiredParameterMissing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMSimpleQueueError_RequiredParameterMissing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMSimpleQueueError_RequiredParameterMissing"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/simple-queue-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/simple-queue-errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
