{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/tag-values"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Tag Values"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api": {
      "abstract": [
        {
          "text": "Types and interfaces for working with Core Media tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtag-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTag APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmtag-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagCategoryKey": {
      "abstract": [
        {
          "text": "A constant for use as a key during tag creation from a dictionary, whose value is the tag’s category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagCategoryKey"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagCategoryKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagCategoryKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagcategorykey"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagDataTypeKey": {
      "abstract": [
        {
          "text": "A constant for use as a key during tag creation from a dictionary, whose value is the tag’s data type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagDataTypeKey"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagDataTypeKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagDataTypeKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagdatatypekey"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagInvalid": {
      "abstract": [
        {
          "text": "A constant representing an invalid tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagInvalid"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagInvalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagInvalid",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtaginvalid"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagMediaSubTypeMebx": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagMediaSubTypeMebx"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagMediaSubTypeMebx",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagMediaSubTypeMebx",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagmediasubtypemebx"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagMediaTypeAudio": {
      "abstract": [
        {
          "text": "A value for associating a tag’s media type with audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagMediaTypeAudio"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagMediaTypeAudio",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagMediaTypeAudio",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagmediatypeaudio"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagMediaTypeMetadata": {
      "abstract": [
        {
          "text": "A value for associating a tag’s media type with metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagMediaTypeMetadata"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagMediaTypeMetadata",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagMediaTypeMetadata",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagmediatypemetadata"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagMediaTypeVideo": {
      "abstract": [
        {
          "text": "A value for associating a tag’s media type with video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagMediaTypeVideo"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagMediaTypeVideo",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagMediaTypeVideo",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagmediatypevideo"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagPackingTypeNone": {
      "abstract": [
        {
          "text": "A frame-packing tag value for video without packed frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagPackingTypeNone"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagPackingTypeNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagPackingTypeNone",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagpackingtypenone"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagPackingTypeOverUnder": {
      "abstract": [
        {
          "text": "A tag stating that associated video has packed frames with a left eye image on the top and right eye image on the bottom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagPackingTypeOverUnder"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagPackingTypeOverUnder",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagPackingTypeOverUnder",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagpackingtypeoverunder"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagPackingTypeSideBySide": {
      "abstract": [
        {
          "text": "A tag stating that associated video has packed frames with a left eye image on the left and right eye image on the right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagPackingTypeSideBySide"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagPackingTypeSideBySide",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagPackingTypeSideBySide",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagpackingtypesidebyside"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagProjectionTypeEquirectangular": {
      "abstract": [
        {
          "text": "A value for projection tags indicating that display is on a 360 degree equirectangular projection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagProjectionTypeEquirectangular"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagProjectionTypeEquirectangular",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagProjectionTypeEquirectangular",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagprojectiontypeequirectangular"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagProjectionTypeFisheye": {
      "abstract": [
        {
          "text": "Video content displays as a fisheye projection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagProjectionTypeFisheye"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagProjectionTypeFisheye",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagProjectionTypeFisheye",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagprojectiontypefisheye"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagProjectionTypeRectangular": {
      "abstract": [
        {
          "text": "A value for projection tags indicating that display is on a flat rectangular surface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagProjectionTypeRectangular"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagProjectionTypeRectangular",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagProjectionTypeRectangular",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagprojectiontyperectangular"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagStereoInterpretationOrderReversed": {
      "abstract": [
        {
          "text": "A value for a stereo interpretation tag indicating the video data for the left and right eyes are reversed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagStereoInterpretationOrderReversed"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagStereoInterpretationOrderReversed",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagStereoInterpretationOrderReversed",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagstereointerpretationorderreversed"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagStereoLeftAndRightEye": {
      "abstract": [
        {
          "text": "A value for a stereo tag indicating the video track has left and right eye layers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagStereoLeftAndRightEye"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagStereoLeftAndRightEye",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagStereoLeftAndRightEye",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagstereoleftandrighteye"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagStereoLeftEye": {
      "abstract": [
        {
          "text": "A value for a stereo tag indicating the video track has a left eye layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagStereoLeftEye"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagStereoLeftEye",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagStereoLeftEye",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagstereolefteye"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagStereoNone": {
      "abstract": [
        {
          "text": "A value for a stereo tag indicating the video track has no eye layer data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagStereoNone"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagStereoNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagStereoNone",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagstereonone"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagStereoRightEye": {
      "abstract": [
        {
          "text": "A value for a stereo tag indicating the video track has a right eye layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagStereoRightEye"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagStereoRightEye",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagStereoRightEye",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagstereorighteye"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagValueKey": {
      "abstract": [
        {
          "text": "A constant for use as a key during tag creation from a dictionary, whose value is the tag’s contained value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTagValueKey"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagValueKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTagValueKey",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtagvaluekey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "abstract": [
                {
                  "text": "Values for use with the tag media type category.",
                  "type": "text"
                }
              ],
              "anchor": "Media-Type",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagMediaTypeVideo",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagMediaTypeAudio",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagMediaTypeMetadata"
              ],
              "title": "Media Type"
            },
            {
              "abstract": [
                {
                  "text": "Values for use with the tag media subtype category.",
                  "type": "text"
                }
              ],
              "anchor": "Media-Subtype",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagMediaSubTypeMebx"
              ],
              "title": "Media Subtype"
            },
            {
              "abstract": [
                {
                  "text": "Values for use with the tag frame-packing information category.",
                  "type": "text"
                }
              ],
              "anchor": "Frame-Arrangements",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagPackingTypeNone",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagPackingTypeSideBySide",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagPackingTypeOverUnder"
              ],
              "title": "Frame Arrangements"
            },
            {
              "abstract": [
                {
                  "text": "Values for use with the tag projection type category.",
                  "type": "text"
                }
              ],
              "anchor": "Projection-Surfaces",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagProjectionTypeRectangular",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagProjectionTypeEquirectangular",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagProjectionTypeFisheye"
              ],
              "title": "Projection Surfaces"
            },
            {
              "abstract": [
                {
                  "text": "Values for use with the tag categories that provide stereo video metadata.",
                  "type": "text"
                }
              ],
              "anchor": "3D-Video-Data",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagStereoInterpretationOrderReversed",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagStereoLeftAndRightEye",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagStereoLeftEye",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagStereoRightEye",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagStereoNone"
              ],
              "title": "3D Video Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagCategoryKey",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagDataTypeKey",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagValueKey",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTagInvalid"
              ],
              "title": "Constants"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/tag-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/tag-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
