{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/tagged-buffergroup-format-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Tagged Buffer Group Format Types"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatType": {
      "abstract": [
        {
          "text": "A closed caption format type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMClosedCaptionFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMClosedCaptionFormatType"
        }
      ],
      "role": "symbol",
      "title": "CMClosedCaptionFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmclosedcaptionformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataFormatType": {
      "abstract": [
        {
          "text": "A metadata format type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMMetadataFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMMetadataFormatType"
        }
      ],
      "role": "symbol",
      "title": "CMMetadataFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmmetadataformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMPixelFormatType": {
      "abstract": [
        {
          "text": "A pixel format type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMPixelFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMPixelFormatType"
        }
      ],
      "role": "symbol",
      "title": "CMPixelFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmpixelformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMSubtitleFormatType": {
      "abstract": [
        {
          "text": "A type that represents a text subtitle format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMSubtitleFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMSubtitleFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMSubtitleFormatType"
        }
      ],
      "role": "symbol",
      "title": "CMSubtitleFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmsubtitleformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTextFormatType": {
      "abstract": [
        {
          "text": "A text format type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTextFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTextFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTextFormatType"
        }
      ],
      "role": "symbol",
      "title": "CMTextFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmtextformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatType": {
      "abstract": [
        {
          "text": "A time code format type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTimeCodeFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMTimeCodeFormatType"
        }
      ],
      "role": "symbol",
      "title": "CMTimeCodeFormatType",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimecodeformattype"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api": {
      "abstract": [
        {
          "text": "A media format descriptor that describes the samples in a sample buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMFormatDescription APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTaggedBufferGroupFormatType_TaggedBufferGroup": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCMTaggedBufferGroupFormatType_TaggedBufferGroup"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTaggedBufferGroupFormatType_TaggedBufferGroup",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCMTaggedBufferGroupFormatType_TaggedBufferGroup",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtaggedbuffergroupformattype_taggedbuffergroup"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-types": {
      "abstract": [
        {
          "text": "Constants that represent media format types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Format Types",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-format-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/subtitle-format-types": {
      "abstract": [
        {
          "text": "Constants that represent subtitle format types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/subtitle-format-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Subtitle Format Types",
      "type": "topic",
      "url": "/documentation/coremedia/subtitle-format-types"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/time-code-formats": {
      "abstract": [
        {
          "text": "Constants that represent time code format types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/time-code-formats",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Time Code Formats",
      "type": "topic",
      "url": "/documentation/coremedia/time-code-formats"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Format-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataFormatType",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-types",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMSubtitleFormatType",
        "doc://com.apple.coremedia/documentation/CoreMedia/subtitle-format-types",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatType",
        "doc://com.apple.coremedia/documentation/CoreMedia/time-code-formats",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMTextFormatType",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMPixelFormatType"
      ],
      "title": "Format Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTaggedBufferGroupFormatType_TaggedBufferGroup"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Format-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/CMClosedCaptionFormatType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMMetadataFormatType",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-types",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMSubtitleFormatType",
                "doc://com.apple.coremedia/documentation/CoreMedia/subtitle-format-types",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTimeCodeFormatType",
                "doc://com.apple.coremedia/documentation/CoreMedia/time-code-formats",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMTextFormatType",
                "doc://com.apple.coremedia/documentation/CoreMedia/CMPixelFormatType"
              ],
              "title": "Format Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSubtitleFormatType/title",
          "value": "CMSubtitleFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSubtitleFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSubtitleFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMSubtitleFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMSubtitleFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextFormatType/title",
          "value": "CMTextFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTextFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTextFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClosedCaptionFormatType/title",
          "value": "CMClosedCaptionFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClosedCaptionFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClosedCaptionFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMClosedCaptionFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMClosedCaptionFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataFormatType/title",
          "value": "CMMetadataFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMMetadataFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMMetadataFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeCodeFormatType/title",
          "value": "CMTimeCodeFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeCodeFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeCodeFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMTimeCodeFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMTimeCodeFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPixelFormatType/title",
          "value": "CMPixelFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPixelFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPixelFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMPixelFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMPixelFormatType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/tagged-buffergroup-format-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/tagged-buffergroup-format-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
