{
  "abstract": [
    {
      "text": "Flags that identify text display methods.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/text-display-flags"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Text Display Flags"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify chroma location extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Chroma Location Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/chroma-location-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify clean aperture extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Clean Aperture Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/clean-aperture-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api": {
      "abstract": [
        {
          "text": "A media format descriptor that describes the samples in a sample buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMFormatDescription APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify color primary extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color Primary Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/color-primary-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify field detail extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Field Detail Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/field-detail-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors": {
      "abstract": [
        {
          "text": "Bridge errors the system returns from format description calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Bridge Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-bridge-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors": {
      "abstract": [
        {
          "text": "Errors the system returns from format description calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants": {
      "abstract": [
        {
          "text": "Constants that identify HEVC temporal level information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HEVC Temporal Level Info Constants",
      "type": "topic",
      "url": "/documentation/coremedia/hevc-temporal-level-info-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_allSubtitlesForced": {
      "abstract": [
        {
          "text": "A flag that describes treating all subtitle samples as if they contain forced subtitles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_allSubtitlesForced"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_allSubtitlesForced",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_allSubtitlesForced"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_allSubtitlesForced",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_allsubtitlesforced"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_continuousKaraoke": {
      "abstract": [
        {
          "text": "A flag that describes enabling the continuous karaoke mode where the range of karaoke highlighting extends to include additional ranges rather than the highlighting moves onto the next range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_continuousKaraoke"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_continuousKaraoke",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_continuousKaraoke"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_continuousKaraoke",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_continuouskaraoke"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_fillTextRegion": {
      "abstract": [
        {
          "text": "A flag that describes the subtitle display bounds are to be filled with the color specified by ",
          "type": "text"
        },
        {
          "code": "kCMTextFormatDescriptionExtension_BackgroundColor",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_fillTextRegion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_fillTextRegion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_fillTextRegion"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_fillTextRegion",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_filltextregion"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_forcedSubtitlesPresent": {
      "abstract": [
        {
          "text": "A flag that describes forcing subtitles are present, for example, a subtitle which only displays during foreign language sections of the video. Check individual samples to determine what type of subtitle is contained.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_forcedSubtitlesPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_forcedSubtitlesPresent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_forcedSubtitlesPresent"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_forcedSubtitlesPresent",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_forcedsubtitlespresent"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_obeySubtitleFormatting": {
      "abstract": [
        {
          "text": "A flag that describes using the subtitle display bounds to determine if the system places the subtitltes near the top or bottom of the video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_obeySubtitleFormatting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_obeySubtitleFormatting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_obeySubtitleFormatting"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_obeySubtitleFormatting",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_obeysubtitleformatting"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirectionMask": {
      "abstract": [
        {
          "text": "A flag that describes the scrolling direction is set by a two-bit field, obtained from displayFlags using kCMTextDisplayFlag_scrollDirectionMask.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirectionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirectionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirectionMask"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_scrollDirectionMask",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_scrolldirectionmask"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_bottomToTop": {
      "abstract": [
        {
          "text": "A flag that describes the text is vertically scrolled up (“credits style”), entering from the bottom and leaving towards the top.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_bottomToTop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_bottomToTop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_bottomToTop"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_scrollDirection_bottomToTop",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_scrolldirection_bottomtotop"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_leftToRight": {
      "abstract": [
        {
          "text": "A flag that describes the text is horizontally scrolled, entering from the left and leaving towards the right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_leftToRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_leftToRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_leftToRight"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_scrollDirection_leftToRight",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_scrolldirection_lefttoright"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_rightToLeft": {
      "abstract": [
        {
          "text": "A flag that describes the text is horizontally scrolled (“marquee style”), entering from the right and leaving towards the left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_rightToLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_rightToLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_rightToLeft"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_scrollDirection_rightToLeft",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_scrolldirection_righttoleft"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_topToBottom": {
      "abstract": [
        {
          "text": "A flag that describes the text is vertically scrolled down, entering from the top and leaving towards the bottom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_topToBottom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_topToBottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollDirection_topToBottom"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_scrollDirection_topToBottom",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_scrolldirection_toptobottom"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollIn": {
      "abstract": [
        {
          "text": "A flag that describes the text scrolls into the display region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollIn"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_scrollIn",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_scrollin"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollOut": {
      "abstract": [
        {
          "text": "A flag that describes the text scrolls out of the display region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_scrollOut"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_scrollOut",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_scrollout"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_writeTextVertically": {
      "abstract": [
        {
          "text": "A flag that describes the text renders vertically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_writeTextVertically"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTextDisplayFlags",
          "text": "CMTextDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_writeTextVertically",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextDisplayFlag_writeTextVertically"
        }
      ],
      "role": "symbol",
      "title": "kCMTextDisplayFlag_writeTextVertically",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextdisplayflag_writetextvertically"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify metadata format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats": {
      "abstract": [
        {
          "text": "Constants that identify MPEG-2 formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MPEG-2-conformant Formats",
      "type": "topic",
      "url": "/documentation/coremedia/mpeg-2-conformant-formats"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify pixel aspect ratio extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pixel Aspect Ratio Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/pixel-aspect-ratio-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify text format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/text-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify time code format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Time Code Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/time-code-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify transfer function extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Transfer Function Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/transfer-function-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify YCbCrMatrix extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "YCbCrMatrix Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/ycbcrmatrix-extension-constants"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
        "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_allSubtitlesForced",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_continuousKaraoke",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_fillTextRegion",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_forcedSubtitlesPresent",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_obeySubtitleFormatting",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirectionMask",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_bottomToTop",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_leftToRight",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_rightToLeft",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_topToBottom",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollIn",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollOut",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_writeTextVertically"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_allSubtitlesForced",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_continuousKaraoke",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_fillTextRegion",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_forcedSubtitlesPresent",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_obeySubtitleFormatting",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirectionMask",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_bottomToTop",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_leftToRight",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_rightToLeft",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollDirection_topToBottom",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollIn",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_scrollOut",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextDisplayFlag_writeTextVertically"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
                "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_continuousKaraoke/title",
          "value": "kCMTextDisplayFlag_continuousKaraoke"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_continuousKaraoke/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_continuousKaraoke"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_rightToLeft/title",
          "value": "kCMTextDisplayFlag_scrollDirection_rightToLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_rightToLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_scrollDirection_rightToLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_bottomToTop/title",
          "value": "kCMTextDisplayFlag_scrollDirection_bottomToTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_bottomToTop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_scrollDirection_bottomToTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_writeTextVertically/title",
          "value": "kCMTextDisplayFlag_writeTextVertically"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_writeTextVertically/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_writeTextVertically"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_forcedSubtitlesPresent/title",
          "value": "kCMTextDisplayFlag_forcedSubtitlesPresent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_forcedSubtitlesPresent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_forcedSubtitlesPresent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollIn/title",
          "value": "kCMTextDisplayFlag_scrollIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_scrollIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_allSubtitlesForced/title",
          "value": "kCMTextDisplayFlag_allSubtitlesForced"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_allSubtitlesForced/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_allSubtitlesForced"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_fillTextRegion/title",
          "value": "kCMTextDisplayFlag_fillTextRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_fillTextRegion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_fillTextRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_topToBottom/title",
          "value": "kCMTextDisplayFlag_scrollDirection_topToBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_topToBottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_scrollDirection_topToBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_obeySubtitleFormatting/title",
          "value": "kCMTextDisplayFlag_obeySubtitleFormatting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_obeySubtitleFormatting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_obeySubtitleFormatting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_leftToRight/title",
          "value": "kCMTextDisplayFlag_scrollDirection_leftToRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirection_leftToRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_scrollDirection_leftToRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirectionMask/title",
          "value": "kCMTextDisplayFlag_scrollDirectionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollDirectionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_scrollDirectionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollOut/title",
          "value": "kCMTextDisplayFlag_scrollOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextDisplayFlag_scrollOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextDisplayFlag_scrollOut"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/text-display-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/text-display-flags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
