{
  "abstract": [
    {
      "text": "Constants that identify text format descriptions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Text Format Description Constants"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/audio-format-desc-codes": {
      "abstract": [
        {
          "text": "Mask codes that identify audio formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/audio-format-desc-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio Format Description Mask Codes",
      "type": "topic",
      "url": "/documentation/coremedia/audio-format-desc-codes"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify chroma location extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Chroma Location Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/chroma-location-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify clean aperture extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Clean Aperture Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/clean-aperture-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api": {
      "abstract": [
        {
          "text": "A media format descriptor that describes the samples in a sample buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMFormatDescription APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify color primary extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color Primary Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/color-primary-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify field detail extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Field Detail Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/field-detail-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors": {
      "abstract": [
        {
          "text": "Bridge errors the system returns from format description calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Bridge Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-bridge-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors": {
      "abstract": [
        {
          "text": "Errors the system returns from format description calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants": {
      "abstract": [
        {
          "text": "Constants that identify HEVC temporal level information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HEVC Temporal Level Info Constants",
      "type": "topic",
      "url": "/documentation/coremedia/hevc-temporal-level-info-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Alpha": {
      "abstract": [
        {
          "text": "The color value for the alpha is a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionColor_Alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Alpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionColor_Alpha"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionColor_Alpha",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptioncolor_alpha"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Blue": {
      "abstract": [
        {
          "text": "The color value for blue is a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionColor_Blue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Blue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionColor_Blue"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionColor_Blue",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptioncolor_blue"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Green": {
      "abstract": [
        {
          "text": "The color value for green is a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionColor_Green"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Green",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionColor_Green"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionColor_Green",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptioncolor_green"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Red": {
      "abstract": [
        {
          "text": "The color value for red is a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionColor_Red"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Red",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionColor_Red"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionColor_Red",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptioncolor_red"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_BackgroundColor": {
      "abstract": [
        {
          "text": "The extension flag that represents the background color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_BackgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_BackgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_BackgroundColor"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionExtension_BackgroundColor",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionextension_backgroundcolor"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultFontName": {
      "abstract": [
        {
          "text": "The extension flag that represents the default font name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_DefaultFontName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultFontName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_DefaultFontName"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionExtension_DefaultFontName",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionextension_defaultfontname"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultStyle": {
      "abstract": [
        {
          "text": "The extension flag that represents the default style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_DefaultStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_DefaultStyle"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionExtension_DefaultStyle",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionextension_defaultstyle"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultTextBox": {
      "abstract": [
        {
          "text": "The extension flag that represents the default text box.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_DefaultTextBox"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultTextBox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_DefaultTextBox"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionExtension_DefaultTextBox",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionextension_defaulttextbox"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DisplayFlags": {
      "abstract": [
        {
          "text": "The extension flag that represents the display flags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_DisplayFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DisplayFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_DisplayFlags"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionExtension_DisplayFlags",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionextension_displayflags"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_FontTable": {
      "abstract": [
        {
          "text": "The extension flag that represents the font table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_FontTable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_FontTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_FontTable"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionExtension_FontTable",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionextension_fonttable"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_HorizontalJustification": {
      "abstract": [
        {
          "text": "The extension flag that represents the horizontal justification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_HorizontalJustification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_HorizontalJustification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_HorizontalJustification"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionExtension_HorizontalJustification",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionextension_horizontaljustification"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_TextJustification": {
      "abstract": [
        {
          "text": "The extension flag that represents the text justification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_TextJustification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_TextJustification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_TextJustification"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionExtension_TextJustification",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionextension_textjustification"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_VerticalJustification": {
      "abstract": [
        {
          "text": "The extension flag that represents the vertical justification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_VerticalJustification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_VerticalJustification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionExtension_VerticalJustification"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionExtension_VerticalJustification",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionextension_verticaljustification"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Bottom": {
      "abstract": [
        {
          "text": "The bottom value for the rect as a 16-bit number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionRect_Bottom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionRect_Bottom"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionRect_Bottom",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionrect_bottom"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Left": {
      "abstract": [
        {
          "text": "The left value for the rect as a 16-bit number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionRect_Left"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionRect_Left"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionRect_Left",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionrect_left"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Right": {
      "abstract": [
        {
          "text": "The right value for the rect as a 16-bit number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionRect_Right"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionRect_Right"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionRect_Right",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionrect_right"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Top": {
      "abstract": [
        {
          "text": "The top value for the rect as a 16-bit number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionRect_Top"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionRect_Top"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionRect_Top",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionrect_top"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Ascent": {
      "abstract": [
        {
          "text": "The style value for the ascent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_Ascent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Ascent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_Ascent"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionStyle_Ascent",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionstyle_ascent"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_EndChar": {
      "abstract": [
        {
          "text": "The style value for the ending character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_EndChar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_EndChar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_EndChar"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionStyle_EndChar",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionstyle_endchar"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Font": {
      "abstract": [
        {
          "text": "The style value for font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_Font"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Font",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_Font"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionStyle_Font",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionstyle_font"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_FontFace": {
      "abstract": [
        {
          "text": "The style value for font face.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_FontFace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_FontFace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_FontFace"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionStyle_FontFace",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionstyle_fontface"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_FontSize": {
      "abstract": [
        {
          "text": "The style value for the font size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_FontSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_FontSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_FontSize"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionStyle_FontSize",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionstyle_fontsize"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_ForegroundColor": {
      "abstract": [
        {
          "text": "The style value for foreground color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_ForegroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_ForegroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_ForegroundColor"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionStyle_ForegroundColor",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionstyle_foregroundcolor"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Height": {
      "abstract": [
        {
          "text": "The style value for the height.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_Height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Height",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_Height"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionStyle_Height",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionstyle_height"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_StartChar": {
      "abstract": [
        {
          "text": "The style value for the starting character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_StartChar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_StartChar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTextFormatDescriptionStyle_StartChar"
        }
      ],
      "role": "symbol",
      "title": "kCMTextFormatDescriptionStyle_StartChar",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtextformatdescriptionstyle_startchar"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify metadata format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats": {
      "abstract": [
        {
          "text": "Constants that identify MPEG-2 formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MPEG-2-conformant Formats",
      "type": "topic",
      "url": "/documentation/coremedia/mpeg-2-conformant-formats"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify pixel aspect ratio extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pixel Aspect Ratio Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/pixel-aspect-ratio-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify time code format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Time Code Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/time-code-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify transfer function extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Transfer Function Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/transfer-function-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify YCbCrMatrix extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "YCbCrMatrix Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/ycbcrmatrix-extension-constants"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
        "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/audio-format-desc-codes"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Description-Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Red",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Green",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Blue",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Alpha",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Top",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Left",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Bottom",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Right",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_StartChar",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Font",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_FontFace",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_ForegroundColor",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_EndChar",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Height",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Ascent",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_FontSize"
      ],
      "title": "Description Constants"
    },
    {
      "anchor": "Description-Extension-Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DisplayFlags",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_BackgroundColor",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultTextBox",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultStyle",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_HorizontalJustification",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_VerticalJustification",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_FontTable",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_TextJustification",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultFontName"
      ],
      "title": "Description Extension Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Description-Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Red",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Green",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Blue",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionColor_Alpha",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Top",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Left",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Bottom",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionRect_Right",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_StartChar",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Font",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_FontFace",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_ForegroundColor",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_EndChar",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Height",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_Ascent",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionStyle_FontSize"
              ],
              "title": "Description Constants"
            },
            {
              "anchor": "Description-Extension-Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DisplayFlags",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_BackgroundColor",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultTextBox",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultStyle",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_HorizontalJustification",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_VerticalJustification",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_FontTable",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_TextJustification",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTextFormatDescriptionExtension_DefaultFontName"
              ],
              "title": "Description Extension Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
                "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/audio-format-desc-codes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_BackgroundColor/title",
          "value": "kCMTextFormatDescriptionExtension_BackgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_BackgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionExtension_BackgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_Ascent/title",
          "value": "kCMTextFormatDescriptionStyle_Ascent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_Ascent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionStyle_Ascent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_StartChar/title",
          "value": "kCMTextFormatDescriptionStyle_StartChar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_StartChar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionStyle_StartChar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionRect_Right/title",
          "value": "kCMTextFormatDescriptionRect_Right"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionRect_Right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionRect_Right"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_Height/title",
          "value": "kCMTextFormatDescriptionStyle_Height"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_Height/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionStyle_Height"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionColor_Blue/title",
          "value": "kCMTextFormatDescriptionColor_Blue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionColor_Blue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionColor_Blue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_DefaultFontName/title",
          "value": "kCMTextFormatDescriptionExtension_DefaultFontName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_DefaultFontName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionExtension_DefaultFontName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionColor_Red/title",
          "value": "kCMTextFormatDescriptionColor_Red"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionColor_Red/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionColor_Red"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_DefaultTextBox/title",
          "value": "kCMTextFormatDescriptionExtension_DefaultTextBox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_DefaultTextBox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionExtension_DefaultTextBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_FontTable/title",
          "value": "kCMTextFormatDescriptionExtension_FontTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_FontTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionExtension_FontTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_FontSize/title",
          "value": "kCMTextFormatDescriptionStyle_FontSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_FontSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionStyle_FontSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionRect_Top/title",
          "value": "kCMTextFormatDescriptionRect_Top"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionRect_Top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionRect_Top"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_HorizontalJustification/title",
          "value": "kCMTextFormatDescriptionExtension_HorizontalJustification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_HorizontalJustification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionExtension_HorizontalJustification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_ForegroundColor/title",
          "value": "kCMTextFormatDescriptionStyle_ForegroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_ForegroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionStyle_ForegroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionRect_Bottom/title",
          "value": "kCMTextFormatDescriptionRect_Bottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionRect_Bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionRect_Bottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_VerticalJustification/title",
          "value": "kCMTextFormatDescriptionExtension_VerticalJustification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_VerticalJustification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionExtension_VerticalJustification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_EndChar/title",
          "value": "kCMTextFormatDescriptionStyle_EndChar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_EndChar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionStyle_EndChar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionColor_Alpha/title",
          "value": "kCMTextFormatDescriptionColor_Alpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionColor_Alpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionColor_Alpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_FontFace/title",
          "value": "kCMTextFormatDescriptionStyle_FontFace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_FontFace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionStyle_FontFace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionColor_Green/title",
          "value": "kCMTextFormatDescriptionColor_Green"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionColor_Green/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionColor_Green"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_TextJustification/title",
          "value": "kCMTextFormatDescriptionExtension_TextJustification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_TextJustification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionExtension_TextJustification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_DefaultStyle/title",
          "value": "kCMTextFormatDescriptionExtension_DefaultStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_DefaultStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionExtension_DefaultStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionRect_Left/title",
          "value": "kCMTextFormatDescriptionRect_Left"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionRect_Left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionRect_Left"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_Font/title",
          "value": "kCMTextFormatDescriptionStyle_Font"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionStyle_Font/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionStyle_Font"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_DisplayFlags/title",
          "value": "kCMTextFormatDescriptionExtension_DisplayFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTextFormatDescriptionExtension_DisplayFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTextFormatDescriptionExtension_DisplayFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/text-format-description-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/text-format-description-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
