{
  "abstract": [
    {
      "text": "Keys that represent timebase notifications.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/timebase-notifications"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Timebase Notifications"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-api": {
      "abstract": [
        {
          "text": "A reference clock you use to synchronize applications and devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMClock APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmclock-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-error-codes": {
      "abstract": [
        {
          "text": "Constants that represent the errors in Core Media clock operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMClock Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/cmclock-error-codes"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmsync-error-codes": {
      "abstract": [
        {
          "text": "Constants that represent error codes Core Media sync operations return.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmsync-error-codes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMSync error codes",
      "type": "topic",
      "url": "/documentation/coremedia/cmsync-error-codes"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmtimebase-errors": {
      "abstract": [
        {
          "text": "Constants that represent errors in Core Media timebase operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmtimebase-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMTimebase Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/cmtimebase-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseNotification_EffectiveRateChanged": {
      "abstract": [
        {
          "text": "A notification that posts by a timebase after a change in effective rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTimebaseNotification_EffectiveRateChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseNotification_EffectiveRateChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimebaseNotification_EffectiveRateChanged"
        }
      ],
      "role": "symbol",
      "title": "kCMTimebaseNotification_EffectiveRateChanged",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtimebasenotification_effectiveratechanged"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseNotification_TimeJumped": {
      "abstract": [
        {
          "text": "A notification that posts by a timebase after a discontinuous time jump.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMTimebaseNotification_TimeJumped"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseNotification_TimeJumped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMTimebaseNotification_TimeJumped"
        }
      ],
      "role": "symbol",
      "title": "kCMTimebaseNotification_TimeJumped",
      "type": "topic",
      "url": "/documentation/coremedia/kcmtimebasenotification_timejumped"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-error-codes",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmtimebase-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmsync-error-codes"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseNotification_EffectiveRateChanged",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseNotification_TimeJumped"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseNotification_EffectiveRateChanged",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMTimebaseNotification_TimeJumped"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/cmclock-error-codes",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmtimebase-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/cmsync-error-codes"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimebaseNotification_TimeJumped/title",
          "value": "kCMTimebaseNotification_TimeJumped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimebaseNotification_TimeJumped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimebaseNotification_TimeJumped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimebaseNotification_EffectiveRateChanged/title",
          "value": "kCMTimebaseNotification_EffectiveRateChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMTimebaseNotification_EffectiveRateChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMTimebaseNotification_EffectiveRateChanged"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/timebase-notifications"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/timebase-notifications"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
