{
  "abstract": [
    {
      "text": "Constants that identify video pixel formats.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/video-pixel-formats"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Video Pixel Formats"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify chroma location extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Chroma Location Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/chroma-location-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify clean aperture extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Clean Aperture Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/clean-aperture-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api": {
      "abstract": [
        {
          "text": "A media format descriptor that describes the samples in a sample buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMFormatDescription APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify color primary extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color Primary Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/color-primary-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify field detail extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Field Detail Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/field-detail-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors": {
      "abstract": [
        {
          "text": "Bridge errors the system returns from format description calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Bridge Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-bridge-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors": {
      "abstract": [
        {
          "text": "Errors the system returns from format description calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants": {
      "abstract": [
        {
          "text": "Constants that identify HEVC temporal level information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HEVC Temporal Level Info Constants",
      "type": "topic",
      "url": "/documentation/coremedia/hevc-temporal-level-info-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16BE555": {
      "abstract": [
        {
          "text": "A type that describes 16-bit big-endian 5-5-5.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_16BE555"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16BE555",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_16BE555"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_16BE555",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_16be555"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16BE565": {
      "abstract": [
        {
          "text": "A type that describes 16-bit big-endian 5-6-5.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_16BE565"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16BE565",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_16BE565"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_16BE565",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_16be565"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE555": {
      "abstract": [
        {
          "text": "A type that describes 16-bit little-endian 5-5-5.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_16LE555"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE555",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_16LE555"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_16LE555",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_16le555"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE5551": {
      "abstract": [
        {
          "text": "A type that describes 16-bit little-endian 5-5-5-1.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_16LE5551"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE5551",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_16LE5551"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_16LE5551",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_16le5551"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE565": {
      "abstract": [
        {
          "text": "A type that describes 16-bit little-endian 5-6-5.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_16LE565"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE565",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_16LE565"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_16LE565",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_16le565"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_24RGB": {
      "abstract": [
        {
          "text": "A type that describes 24-bit RGB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_24RGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_24RGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_24RGB"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_24RGB",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_24rgb"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_32ARGB": {
      "abstract": [
        {
          "text": "A type that describes 32-bit ARGB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_32ARGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_32ARGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_32ARGB"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_32ARGB",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_32argb"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_32BGRA": {
      "abstract": [
        {
          "text": "A type that describes 32-bit BGRA.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_32BGRA"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_32BGRA",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_32BGRA"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_32BGRA",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_32bgra"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr10": {
      "abstract": [
        {
          "text": "A type that describes component Y’CbCr 10-bit 4:2:2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_422YpCbCr10"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr10",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_422YpCbCr10"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_422YpCbCr10",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_422ypcbcr10"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr16": {
      "abstract": [
        {
          "text": "A type that describes component Y’CbCr 10,12,14,16-bit 4:2:2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_422YpCbCr16"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_422YpCbCr16"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_422YpCbCr16",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_422ypcbcr16"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr8": {
      "abstract": [
        {
          "text": "A type that describes component Y’CbCr 8-bit 4:2:2 ordered Cb Y’0 Cr Y’1.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_422YpCbCr8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_422YpCbCr8"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_422YpCbCr8",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_422ypcbcr8"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr8_yuvs": {
      "abstract": [
        {
          "text": "A type that describes component Y’CbCr 8-bit 4:2:2 ordered Y’0 Cb Y’1 Cr.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_422YpCbCr8_yuvs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr8_yuvs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_422YpCbCr8_yuvs"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_422YpCbCr8_yuvs",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_422ypcbcr8_yuvs"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_4444YpCbCrA8": {
      "abstract": [
        {
          "text": "A type that describes component Y’CbCrA 8-bit 4:4:4:4.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_4444YpCbCrA8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_4444YpCbCrA8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_4444YpCbCrA8"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_4444YpCbCrA8",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_4444ypcbcra8"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_444YpCbCr10": {
      "abstract": [
        {
          "text": "A type that describes component Y’CbCr 10-bit 4:4:4",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_444YpCbCr10"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_444YpCbCr10",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_444YpCbCr10"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_444YpCbCr10",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_444ypcbcr10"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_444YpCbCr8": {
      "abstract": [
        {
          "text": "A type that describes component Y’CbCr 8-bit 4:4:4.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_444YpCbCr8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_444YpCbCr8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_444YpCbCr8"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_444YpCbCr8",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_444ypcbcr8"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_8IndexedGray_WhiteIsZero": {
      "abstract": [
        {
          "text": "A type that describes 8-bit indexed gray, white is zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_8IndexedGray_WhiteIsZero"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPixelFormatType",
          "text": "CMPixelFormatType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_8IndexedGray_WhiteIsZero",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMPixelFormat_8IndexedGray_WhiteIsZero"
        }
      ],
      "role": "symbol",
      "title": "kCMPixelFormat_8IndexedGray_WhiteIsZero",
      "type": "topic",
      "url": "/documentation/coremedia/kcmpixelformat_8indexedgray_whiteiszero"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify metadata format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats": {
      "abstract": [
        {
          "text": "Constants that identify MPEG-2 formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MPEG-2-conformant Formats",
      "type": "topic",
      "url": "/documentation/coremedia/mpeg-2-conformant-formats"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify pixel aspect ratio extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pixel Aspect Ratio Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/pixel-aspect-ratio-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify text format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/text-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify time code format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Time Code Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/time-code-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify transfer function extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Transfer Function Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/transfer-function-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify YCbCrMatrix extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "YCbCrMatrix Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/ycbcrmatrix-extension-constants"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
        "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16BE555",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16BE565",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE555",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE5551",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE565",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_24RGB",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_32ARGB",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_32BGRA",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr10",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr16",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr8",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr8_yuvs",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_4444YpCbCrA8",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_444YpCbCr10",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_444YpCbCr8",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_8IndexedGray_WhiteIsZero"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16BE555",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16BE565",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE555",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE5551",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_16LE565",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_24RGB",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_32ARGB",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_32BGRA",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr10",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr16",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr8",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_422YpCbCr8_yuvs",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_4444YpCbCrA8",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_444YpCbCr10",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_444YpCbCr8",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMPixelFormat_8IndexedGray_WhiteIsZero"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
                "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_32ARGB/title",
          "value": "kCMPixelFormat_32ARGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_32ARGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_32ARGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_16BE565/title",
          "value": "kCMPixelFormat_16BE565"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_16BE565/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_16BE565"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_32BGRA/title",
          "value": "kCMPixelFormat_32BGRA"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_32BGRA/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_32BGRA"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_4444YpCbCrA8/title",
          "value": "kCMPixelFormat_4444YpCbCrA8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_4444YpCbCrA8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_4444YpCbCrA8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_24RGB/title",
          "value": "kCMPixelFormat_24RGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_24RGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_24RGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_16LE5551/title",
          "value": "kCMPixelFormat_16LE5551"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_16LE5551/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_16LE5551"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_444YpCbCr8/title",
          "value": "kCMPixelFormat_444YpCbCr8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_444YpCbCr8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_444YpCbCr8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_422YpCbCr8/title",
          "value": "kCMPixelFormat_422YpCbCr8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_422YpCbCr8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_422YpCbCr8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_16BE555/title",
          "value": "kCMPixelFormat_16BE555"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_16BE555/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_16BE555"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_422YpCbCr8_yuvs/title",
          "value": "kCMPixelFormat_422YpCbCr8_yuvs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_422YpCbCr8_yuvs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_422YpCbCr8_yuvs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_16LE555/title",
          "value": "kCMPixelFormat_16LE555"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_16LE555/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_16LE555"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_444YpCbCr10/title",
          "value": "kCMPixelFormat_444YpCbCr10"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_444YpCbCr10/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_444YpCbCr10"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_16LE565/title",
          "value": "kCMPixelFormat_16LE565"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_16LE565/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_16LE565"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_8IndexedGray_WhiteIsZero/title",
          "value": "kCMPixelFormat_8IndexedGray_WhiteIsZero"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_8IndexedGray_WhiteIsZero/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_8IndexedGray_WhiteIsZero"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_422YpCbCr16/title",
          "value": "kCMPixelFormat_422YpCbCr16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_422YpCbCr16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_422YpCbCr16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_422YpCbCr10/title",
          "value": "kCMPixelFormat_422YpCbCr10"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMPixelFormat_422YpCbCr10/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMPixelFormat_422YpCbCr10"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/video-pixel-formats"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/video-pixel-formats"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
