{
  "abstract": [
    {
      "text": "Types that identify video codecs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/video-codec-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Video Codec Constants"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify chroma location extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Chroma Location Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/chroma-location-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify clean aperture extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Clean Aperture Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/clean-aperture-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api": {
      "abstract": [
        {
          "text": "A media format descriptor that describes the samples in a sample buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMFormatDescription APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify color primary extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color Primary Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/color-primary-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify field detail extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Field Detail Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/field-detail-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors": {
      "abstract": [
        {
          "text": "Bridge errors the system returns from format description calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Bridge Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-bridge-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors": {
      "abstract": [
        {
          "text": "Errors the system returns from format description calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants": {
      "abstract": [
        {
          "text": "Constants that identify HEVC temporal level information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HEVC Temporal Level Info Constants",
      "type": "topic",
      "url": "/documentation/coremedia/hevc-temporal-level-info-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_422YpCbCr8": {
      "abstract": [
        {
          "text": "A type that identifies a component with the format of Y’CbCr 8-bit 4:2:2 ordered Cb Y’0 Cr Y’1.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_422YpCbCr8"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_422YpCbCr8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_422YpCbCr8"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_422YpCbCr8",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_422ypcbcr8"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AV1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AV1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AV1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AV1"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_AV1",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_av1"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Animation": {
      "abstract": [
        {
          "text": "A type that identifies the apple animation format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_Animation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Animation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_Animation"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_Animation",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_animation"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422": {
      "abstract": [
        {
          "text": "A type that identifies the Apple ProRes 422 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes422"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes422"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_AppleProRes422",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_appleprores422"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422HQ": {
      "abstract": [
        {
          "text": "A type that identifies the Apple ProRes 422 HQ format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes422HQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422HQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes422HQ"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_AppleProRes422HQ",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_appleprores422hq"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422LT": {
      "abstract": [
        {
          "text": "A type that identifies the Apple ProRes 422 LT format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes422LT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422LT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes422LT"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_AppleProRes422LT",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_appleprores422lt"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422Proxy": {
      "abstract": [
        {
          "text": "A type that identifies the Apple ProRes 422 proxy format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes422Proxy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422Proxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes422Proxy"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_AppleProRes422Proxy",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_appleprores422proxy"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes4444": {
      "abstract": [
        {
          "text": "A type that identifies the Apple ProRes 4444 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes4444"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes4444",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes4444"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_AppleProRes4444",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_appleprores4444"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes4444XQ": {
      "abstract": [
        {
          "text": "A type that identifies the Apple ProRes 4444 XQ format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes4444XQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes4444XQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProRes4444XQ"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_AppleProRes4444XQ",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_appleprores4444xq"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProResRAW": {
      "abstract": [
        {
          "text": "A type that identifies the Apple ProRes RAW format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProResRAW"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProResRAW",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProResRAW"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_AppleProResRAW",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_appleproresraw"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProResRAWHQ": {
      "abstract": [
        {
          "text": "A type that identifies the Apple ProRes RAW HQ format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProResRAWHQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProResRAWHQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_AppleProResRAWHQ"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_AppleProResRAWHQ",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_appleproresrawhq"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Cinepak": {
      "abstract": [
        {
          "text": "A type that identifies the cinepak format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_Cinepak"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Cinepak",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_Cinepak"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_Cinepak",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_cinepak"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCNTSC": {
      "abstract": [
        {
          "text": "A type that identifies the DV NTSC format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCNTSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCNTSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCNTSC"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCNTSC",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcntsc"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPAL": {
      "abstract": [
        {
          "text": "A type that identifies the DV PAL format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPAL"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPAL",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcpal"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i50": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro-HD 1080i50 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080i50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080i50"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPROHD1080i50",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcprohd1080i50"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i60": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro-HD 1080i60 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080i60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080i60"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPROHD1080i60",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcprohd1080i60"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080p25": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro-HD 1080p25 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080p25"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080p25",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080p25"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPROHD1080p25",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcprohd1080p25"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080p30": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro-HD 1080p30 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080p30"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080p30",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD1080p30"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPROHD1080p30",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcprohd1080p30"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD720p50": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro-HD 720p50 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD720p50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD720p50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD720p50"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPROHD720p50",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcprohd720p50"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD720p60": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro-HD 720p60 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD720p60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD720p60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPROHD720p60"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPROHD720p60",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcprohd720p60"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPro50NTSC": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro-50 NTSC format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPro50NTSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPro50NTSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPro50NTSC"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPro50NTSC",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcpro50ntsc"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPro50PAL": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro-50 PAL format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPro50PAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPro50PAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCPro50PAL"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCPro50PAL",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcpro50pal"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCProPAL": {
      "abstract": [
        {
          "text": "A type that identifies the Panasonic DVCPro PAL format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCProPAL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCProPAL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DVCProPAL"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DVCProPAL",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dvcpropal"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DepthHEVC": {
      "abstract": [
        {
          "text": "A type that identifies the depth HEVC format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DepthHEVC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DepthHEVC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DepthHEVC"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DepthHEVC",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_depthhevc"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DisparityHEVC": {
      "abstract": [
        {
          "text": "A type that identifies the disparity HEVC format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DisparityHEVC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DisparityHEVC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DisparityHEVC"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DisparityHEVC",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_disparityhevc"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DolbyVisionHEVC": {
      "abstract": [
        {
          "text": "A type that identifies the Dolby Vision HEVC format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DolbyVisionHEVC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DolbyVisionHEVC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_DolbyVisionHEVC"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_DolbyVisionHEVC",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_dolbyvisionhevc"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H263": {
      "abstract": [
        {
          "text": "A type that identifies the ITU-T H.263 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_H263"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H263",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_H263"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_H263",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_h263"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H264": {
      "abstract": [
        {
          "text": "A type that identifies the ITU-T H.264 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_H264"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H264",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_H264"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_H264",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_h264"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_HEVC": {
      "abstract": [
        {
          "text": "A type that identifies the ITU-T HEVC format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_HEVC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_HEVC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_HEVC"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_HEVC",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_hevc"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_HEVCWithAlpha": {
      "abstract": [
        {
          "text": "A type that identifies the HEVC format with alpha support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_HEVCWithAlpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_HEVCWithAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_HEVCWithAlpha"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_HEVCWithAlpha",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_hevcwithalpha"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG": {
      "abstract": [
        {
          "text": "A type that identifies the Joint Photographic Experts Group (JPEG) format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_JPEG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_JPEG"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_JPEG",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_jpeg"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG_OpenDML": {
      "abstract": [
        {
          "text": "A type that identifies the JPEG format with Open-DML extensions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_JPEG_OpenDML"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG_OpenDML",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_JPEG_OpenDML"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_JPEG_OpenDML",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_jpeg_opendml"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG_XL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_JPEG_XL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG_XL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_JPEG_XL"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_JPEG_XL",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_jpeg_xl"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG1Video": {
      "abstract": [
        {
          "text": "A type that identifies the MPEG-1 video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_MPEG1Video"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG1Video",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_MPEG1Video"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_MPEG1Video",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_mpeg1video"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG2Video": {
      "abstract": [
        {
          "text": "A type that identifies the MPEG-2 video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_MPEG2Video"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG2Video",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_MPEG2Video"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_MPEG2Video",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_mpeg2video"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG4Video": {
      "abstract": [
        {
          "text": "A type that identifies the Moving Picture Experts Group (MPEG) MPEG-4 Part 2 video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_MPEG4Video"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG4Video",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_MPEG4Video"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_MPEG4Video",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_mpeg4video"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo": {
      "abstract": [
        {
          "text": "A type that identifies the sorenson video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_SorensonVideo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_SorensonVideo"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_SorensonVideo",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_sorensonvideo"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo3": {
      "abstract": [
        {
          "text": "A type that identifies the sorenson 3 video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_SorensonVideo3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_SorensonVideo3"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_SorensonVideo3",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_sorensonvideo3"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_VP9": {
      "abstract": [
        {
          "text": "A type that identifies the VP9 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_VP9"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMVideoCodecType",
          "text": "CMVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_VP9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMVideoCodecType_VP9"
        }
      ],
      "role": "symbol",
      "title": "kCMVideoCodecType_VP9",
      "type": "topic",
      "url": "/documentation/coremedia/kcmvideocodectype_vp9"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify metadata format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats": {
      "abstract": [
        {
          "text": "Constants that identify MPEG-2 formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MPEG-2-conformant Formats",
      "type": "topic",
      "url": "/documentation/coremedia/mpeg-2-conformant-formats"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify pixel aspect ratio extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pixel Aspect Ratio Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/pixel-aspect-ratio-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify text format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/text-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify time code format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Time Code Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/time-code-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify transfer function extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Transfer Function Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/transfer-function-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify YCbCrMatrix extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "YCbCrMatrix Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/ycbcrmatrix-extension-constants"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
        "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_422YpCbCr8",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Animation",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422HQ",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422LT",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422Proxy",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes4444",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes4444XQ",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProResRAW",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProResRAWHQ",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Cinepak",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCNTSC",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPAL",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i50",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i60",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080p25",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080p30",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD720p50",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD720p60",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPro50NTSC",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPro50PAL",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCProPAL",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H263",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H264",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_HEVC",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_HEVCWithAlpha",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG_OpenDML",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG_XL",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG1Video",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG2Video",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG4Video",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo3",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DepthHEVC",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DisparityHEVC",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DolbyVisionHEVC",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_VP9",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AV1"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_422YpCbCr8",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Animation",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422HQ",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422LT",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes422Proxy",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes4444",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProRes4444XQ",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProResRAW",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AppleProResRAWHQ",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_Cinepak",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCNTSC",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPAL",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i50",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080i60",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080p25",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD1080p30",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD720p50",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPROHD720p60",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPro50NTSC",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCPro50PAL",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DVCProPAL",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H263",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_H264",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_HEVC",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_HEVCWithAlpha",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG_OpenDML",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_JPEG_XL",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG1Video",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG2Video",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_MPEG4Video",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_SorensonVideo3",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DepthHEVC",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DisparityHEVC",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_DolbyVisionHEVC",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_VP9",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMVideoCodecType_AV1"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
                "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_VP9/title",
          "value": "kCMVideoCodecType_VP9"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_VP9/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_VP9"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_JPEG_XL/title",
          "value": "kCMVideoCodecType_JPEG_XL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_JPEG_XL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_JPEG_XL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_MPEG2Video/title",
          "value": "kCMVideoCodecType_MPEG2Video"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_MPEG2Video/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_MPEG2Video"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPro50PAL/title",
          "value": "kCMVideoCodecType_DVCPro50PAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPro50PAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPro50PAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes422HQ/title",
          "value": "kCMVideoCodecType_AppleProRes422HQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes422HQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_AppleProRes422HQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_H263/title",
          "value": "kCMVideoCodecType_H263"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_H263/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_H263"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DepthHEVC/title",
          "value": "kCMVideoCodecType_DepthHEVC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DepthHEVC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DepthHEVC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_SorensonVideo3/title",
          "value": "kCMVideoCodecType_SorensonVideo3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_SorensonVideo3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_SorensonVideo3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes422/title",
          "value": "kCMVideoCodecType_AppleProRes422"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes422/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_AppleProRes422"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080i60/title",
          "value": "kCMVideoCodecType_DVCPROHD1080i60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080i60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPROHD1080i60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD720p50/title",
          "value": "kCMVideoCodecType_DVCPROHD720p50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD720p50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPROHD720p50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCNTSC/title",
          "value": "kCMVideoCodecType_DVCNTSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCNTSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCNTSC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD720p60/title",
          "value": "kCMVideoCodecType_DVCPROHD720p60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD720p60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPROHD720p60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_MPEG1Video/title",
          "value": "kCMVideoCodecType_MPEG1Video"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_MPEG1Video/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_MPEG1Video"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_JPEG/title",
          "value": "kCMVideoCodecType_JPEG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_JPEG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_JPEG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes4444/title",
          "value": "kCMVideoCodecType_AppleProRes4444"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes4444/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_AppleProRes4444"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_Cinepak/title",
          "value": "kCMVideoCodecType_Cinepak"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_Cinepak/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_Cinepak"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DisparityHEVC/title",
          "value": "kCMVideoCodecType_DisparityHEVC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DisparityHEVC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DisparityHEVC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPAL/title",
          "value": "kCMVideoCodecType_DVCPAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080p25/title",
          "value": "kCMVideoCodecType_DVCPROHD1080p25"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080p25/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPROHD1080p25"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_MPEG4Video/title",
          "value": "kCMVideoCodecType_MPEG4Video"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_MPEG4Video/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_MPEG4Video"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_SorensonVideo/title",
          "value": "kCMVideoCodecType_SorensonVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_SorensonVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_SorensonVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_H264/title",
          "value": "kCMVideoCodecType_H264"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_H264/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_H264"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080p30/title",
          "value": "kCMVideoCodecType_DVCPROHD1080p30"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080p30/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPROHD1080p30"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes4444XQ/title",
          "value": "kCMVideoCodecType_AppleProRes4444XQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes4444XQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_AppleProRes4444XQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes422Proxy/title",
          "value": "kCMVideoCodecType_AppleProRes422Proxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes422Proxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_AppleProRes422Proxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_HEVCWithAlpha/title",
          "value": "kCMVideoCodecType_HEVCWithAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_HEVCWithAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_HEVCWithAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_JPEG_OpenDML/title",
          "value": "kCMVideoCodecType_JPEG_OpenDML"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_JPEG_OpenDML/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_JPEG_OpenDML"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProResRAW/title",
          "value": "kCMVideoCodecType_AppleProResRAW"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProResRAW/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_AppleProResRAW"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCProPAL/title",
          "value": "kCMVideoCodecType_DVCProPAL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCProPAL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCProPAL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_Animation/title",
          "value": "kCMVideoCodecType_Animation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_Animation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_Animation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080i50/title",
          "value": "kCMVideoCodecType_DVCPROHD1080i50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPROHD1080i50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPROHD1080i50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AV1/title",
          "value": "kCMVideoCodecType_AV1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AV1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_AV1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes422LT/title",
          "value": "kCMVideoCodecType_AppleProRes422LT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProRes422LT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_AppleProRes422LT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProResRAWHQ/title",
          "value": "kCMVideoCodecType_AppleProResRAWHQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_AppleProResRAWHQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_AppleProResRAWHQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DolbyVisionHEVC/title",
          "value": "kCMVideoCodecType_DolbyVisionHEVC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DolbyVisionHEVC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DolbyVisionHEVC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_422YpCbCr8/title",
          "value": "kCMVideoCodecType_422YpCbCr8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_422YpCbCr8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_422YpCbCr8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_HEVC/title",
          "value": "kCMVideoCodecType_HEVC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_HEVC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_HEVC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPro50NTSC/title",
          "value": "kCMVideoCodecType_DVCPro50NTSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMVideoCodecType_DVCPro50NTSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMVideoCodecType_DVCPro50NTSC"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/video-codec-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/video-codec-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
