{
  "abstract": [
    {
      "text": "Constants that identify video profiles.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/video-profile-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Video Profile Constants"
  },
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify chroma location extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Chroma Location Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/chroma-location-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify clean aperture extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Clean Aperture Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/clean-aperture-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api": {
      "abstract": [
        {
          "text": "A media format descriptor that describes the samples in a sample buffer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/cmformatdescription-api",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CMFormatDescription APIs",
      "type": "topic",
      "url": "/documentation/coremedia/cmformatdescription-api"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify color primary extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color Primary Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/color-primary-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify field detail extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Field Detail Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/field-detail-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors": {
      "abstract": [
        {
          "text": "Bridge errors the system returns from format description calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Bridge Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-bridge-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors": {
      "abstract": [
        {
          "text": "Errors the system returns from format description calls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Description Error Codes",
      "type": "topic",
      "url": "/documentation/coremedia/format-description-errors"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants": {
      "abstract": [
        {
          "text": "Constants that identify HEVC temporal level information.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "HEVC Temporal Level Info Constants",
      "type": "topic",
      "url": "/documentation/coremedia/hevc-temporal-level-info-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080i50": {
      "abstract": [
        {
          "text": "A profile that represents the Apple Intermediate Codec HDV 1080i50 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_1080i50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080i50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_1080i50"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_HDV_1080i50",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_hdv_1080i50"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080i60": {
      "abstract": [
        {
          "text": "A profile that represents the Apple Intermediate Codec HDV 1080i60 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_1080i60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080i60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_1080i60"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_HDV_1080i60",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_hdv_1080i60"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p24": {
      "abstract": [
        {
          "text": "A profile that represents the Apple ProRes 422 codec HDV 1080p24 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_1080p24"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p24",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_1080p24"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_HDV_1080p24",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_hdv_1080p24"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p25": {
      "abstract": [
        {
          "text": "A profile that represents the HDV 1080p25 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_1080p25"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p25",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_1080p25"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_HDV_1080p25",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_hdv_1080p25"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p30": {
      "abstract": [
        {
          "text": "A profile that represents the HDV 1080p30 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_1080p30"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p30",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_1080p30"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_HDV_1080p30",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_hdv_1080p30"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p24": {
      "abstract": [
        {
          "text": "A profile that represents the HDV 720p24 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_720p24"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p24",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_720p24"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_HDV_720p24",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_hdv_720p24"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p25": {
      "abstract": [
        {
          "text": "A profile that represents the HDV_720p25 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_720p25"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p25",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_720p25"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_HDV_720p25",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_hdv_720p25"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p30": {
      "abstract": [
        {
          "text": "A profile that represents the Apple Intermediate Codec HDV 720p30 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_720p30"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p30",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_720p30"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_HDV_720p30",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_hdv_720p30"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p50": {
      "abstract": [
        {
          "text": "A profile that represents the HDV 720p50 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_720p50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_720p50"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_HDV_720p50",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_hdv_720p50"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p60": {
      "abstract": [
        {
          "text": "A profile that represents the HDV 720p60 format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_720p60"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p60",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_HDV_720p60"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_HDV_720p60",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_hdv_720p60"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_1080i50_VBR35": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM EX 1080i50 HQ video format with HQ 35 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_1080i50_VBR35"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_1080i50_VBR35",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_1080i50_VBR35"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_EX_1080i50_VBR35",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_ex_1080i50_vbr35"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_1080i60_VBR35": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM EX 1080i60 HQ video format with 35 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_1080i60_VBR35"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_1080i60_VBR35",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_1080i60_VBR35"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_EX_1080i60_VBR35",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_ex_1080i60_vbr35"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_1080p24_VBR35": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM EX 1080p24 HQ video format with HQ 35 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_1080p24_VBR35"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_1080p24_VBR35",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_1080p24_VBR35"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_EX_1080p24_VBR35",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_ex_1080p24_vbr35"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_1080p25_VBR35": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM EX 1080p25 HQ video format with 35 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_1080p25_VBR35"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_1080p25_VBR35",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_1080p25_VBR35"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_EX_1080p25_VBR35",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_ex_1080p25_vbr35"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_1080p30_VBR35": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM EX 1080p30 HQ video format with 35 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_1080p30_VBR35"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_1080p30_VBR35",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_1080p30_VBR35"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_EX_1080p30_VBR35",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_ex_1080p30_vbr35"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM EX 720p24 video HQ format with 35 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_ex_720p24_vbr35"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p25_VBR35": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM EX 720p25 video HQ format with 35 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_720p25_VBR35"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p25_VBR35",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_720p25_VBR35"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_EX_720p25_VBR35",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_ex_720p25_vbr35"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p30_VBR35": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM EX 720p30 video HQ format with 35 Mbps bit rate .",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_720p30_VBR35"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p30_VBR35",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_720p30_VBR35"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_EX_720p30_VBR35",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_ex_720p30_vbr35"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p50_VBR35": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM EX 720p50 HQ video format with 35 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_720p50_VBR35"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p50_VBR35",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_720p50_VBR35"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_EX_720p50_VBR35",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_ex_720p50_vbr35"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p60_VBR35": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM EX 720p60 HQ video format with 35 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_720p60_VBR35"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p60_VBR35",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_EX_720p60_VBR35"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_EX_720p60_VBR35",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_ex_720p60_vbr35"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_1080i50_CBR50": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM HD422 1080i50 video format with 50 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_1080i50_CBR50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_1080i50_CBR50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_1080i50_CBR50"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD422_1080i50_CBR50",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd422_1080i50_cbr50"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_1080i60_CBR50": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM HD422 1080i60 video format with 50 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_1080i60_CBR50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_1080i60_CBR50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_1080i60_CBR50"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD422_1080i60_CBR50",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd422_1080i60_cbr50"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_1080p24_CBR50": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM HD422 1080p24 video format with 50 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_1080p24_CBR50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_1080p24_CBR50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_1080p24_CBR50"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD422_1080p24_CBR50",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd422_1080p24_cbr50"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_1080p25_CBR50": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM HD422 1080p25 video format with 50 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_1080p25_CBR50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_1080p25_CBR50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_1080p25_CBR50"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD422_1080p25_CBR50",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd422_1080p25_cbr50"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_1080p30_CBR50": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM HD422 1080p30 video format with 50 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_1080p30_CBR50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_1080p30_CBR50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_1080p30_CBR50"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD422_1080p30_CBR50",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd422_1080p30_cbr50"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_540p": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM HD422 540 video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_540p"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_540p",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_540p"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD422_540p",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd422_540p"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_720p24_CBR50": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM HD 422 720p24 video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_720p24_CBR50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_720p24_CBR50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_720p24_CBR50"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD422_720p24_CBR50",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd422_720p24_cbr50"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_720p25_CBR50": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM HD 422 720p25 video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_720p25_CBR50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_720p25_CBR50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_720p25_CBR50"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD422_720p25_CBR50",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd422_720p25_cbr50"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_720p30_CBR50": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM HD 422 720p30 video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_720p30_CBR50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_720p30_CBR50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_720p30_CBR50"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD422_720p30_CBR50",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd422_720p30_cbr50"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_720p50_CBR50": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM HD422 720p50 video format with 50 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_720p50_CBR50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_720p50_CBR50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_720p50_CBR50"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD422_720p50_CBR50",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd422_720p50_cbr50"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_720p60_CBR50": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM HD422 720p60 video format with 50 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_720p60_CBR50"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_720p60_CBR50",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD422_720p60_CBR50"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD422_720p60_CBR50",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd422_720p60_cbr50"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM HD 1080i50 video HQ format with 35 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd_1080i50_vbr35"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM HD 1080i60 video HQ format with 35 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd_1080i60_vbr35"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM HD 1080p24 video HQ format with 35 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd_1080p24_vbr35"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM HD 1080p25 video HQ format with 35 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd_1080p25_vbr35"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35": {
      "abstract": [
        {
          "text": "A profile that represents the DCAM HD 1080p30 video HQ format with 35 Mbps bit rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd_1080p30_vbr35"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_540p": {
      "abstract": [
        {
          "text": "A profile that represents the XDCAM HD 540p video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_540p"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_540p",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XDCAM_HD_540p"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XDCAM_HD_540p",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xdcam_hd_540p"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XF": {
      "abstract": [
        {
          "text": "A profile that represents the XF video format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMMPEG2VideoProfile_XF"
        }
      ],
      "role": "symbol",
      "title": "kCMMPEG2VideoProfile_XF",
      "type": "topic",
      "url": "/documentation/coremedia/kcmmpeg2videoprofile_xf"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify metadata format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/metadata-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats": {
      "abstract": [
        {
          "text": "Constants that identify MPEG-2 formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
      "kind": "article",
      "role": "collectionGroup",
      "title": "MPEG-2-conformant Formats",
      "type": "topic",
      "url": "/documentation/coremedia/mpeg-2-conformant-formats"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify pixel aspect ratio extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pixel Aspect Ratio Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/pixel-aspect-ratio-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify text format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/text-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants": {
      "abstract": [
        {
          "text": "Constants that identify time code format descriptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Time Code Format Description Constants",
      "type": "topic",
      "url": "/documentation/coremedia/time-code-format-description-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify transfer function extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Transfer Function Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/transfer-function-extension-constants"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants": {
      "abstract": [
        {
          "text": "Constants that identify YCbCrMatrix extensions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "YCbCrMatrix Extension Constants",
      "type": "topic",
      "url": "/documentation/coremedia/ycbcrmatrix-extension-constants"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
        "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
        "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
        "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p30",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080i60",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080i50",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p24",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p25",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p24",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p25",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p30",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p60",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p50",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p25_VBR35",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p30_VBR35",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p50_VBR35",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p60_VBR35",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_1080i60_VBR35",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_1080i50_VBR35",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_1080p24_VBR35",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_1080p25_VBR35",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_1080p30_VBR35",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_720p50_CBR50",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_720p60_CBR50",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_1080i60_CBR50",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_1080i50_CBR50",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_1080p24_CBR50",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_1080p25_CBR50",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_1080p30_CBR50",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_540p",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_540p",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_720p24_CBR50",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_720p25_CBR50",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_720p30_CBR50",
        "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XF"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p30",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080i60",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080i50",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p24",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p25",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p24",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p25",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_1080p30",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p60",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_HDV_720p50",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p25_VBR35",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p30_VBR35",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p50_VBR35",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_720p60_VBR35",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_1080i60_VBR35",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_1080i50_VBR35",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_1080p24_VBR35",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_1080p25_VBR35",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_EX_1080p30_VBR35",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_720p50_CBR50",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_720p60_CBR50",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_1080i60_CBR50",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_1080i50_CBR50",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_1080p24_CBR50",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_1080p25_CBR50",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_1080p30_CBR50",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD_540p",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_540p",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_720p24_CBR50",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_720p25_CBR50",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XDCAM_HD422_720p30_CBR50",
                "doc://com.apple.coremedia/documentation/CoreMedia/kCMMPEG2VideoProfile_XF"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-bridge-errors",
                "doc://com.apple.coremedia/documentation/CoreMedia/format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/text-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/metadata-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/time-code-format-description-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/pixel-aspect-ratio-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/chroma-location-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/clean-aperture-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/color-primary-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/field-detail-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/transfer-function-extension-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/mpeg-2-conformant-formats",
                "doc://com.apple.coremedia/documentation/CoreMedia/hevc-temporal-level-info-constants",
                "doc://com.apple.coremedia/documentation/CoreMedia/ycbcrmatrix-extension-constants"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_1080p25_VBR35/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_EX_1080p25_VBR35"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_1080p25_VBR35/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_EX_1080p25_VBR35"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_720p60/title",
          "value": "kCMMPEG2VideoProfile_HDV_720p60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_720p60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_HDV_720p60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_1080p24_CBR50/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD422_1080p24_CBR50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_1080p24_CBR50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD422_1080p24_CBR50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_1080i50_VBR35/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_EX_1080i50_VBR35"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_1080i50_VBR35/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_EX_1080i50_VBR35"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_720p30/title",
          "value": "kCMMPEG2VideoProfile_HDV_720p30"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_720p30/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_HDV_720p30"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_1080i50_CBR50/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD422_1080i50_CBR50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_1080i50_CBR50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD422_1080i50_CBR50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_720p50_CBR50/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD422_720p50_CBR50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_720p50_CBR50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD422_720p50_CBR50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_540p/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD422_540p"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_540p/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD422_540p"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_1080p30_CBR50/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD422_1080p30_CBR50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_1080p30_CBR50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD422_1080p30_CBR50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_1080i60_VBR35/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_EX_1080i60_VBR35"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_1080i60_VBR35/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_EX_1080i60_VBR35"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_1080i60_CBR50/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD422_1080i60_CBR50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_1080i60_CBR50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD422_1080i60_CBR50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_1080p24/title",
          "value": "kCMMPEG2VideoProfile_HDV_1080p24"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_1080p24/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_HDV_1080p24"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_1080p25/title",
          "value": "kCMMPEG2VideoProfile_HDV_1080p25"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_1080p25/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_HDV_1080p25"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_720p30_VBR35/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_EX_720p30_VBR35"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_720p30_VBR35/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_EX_720p30_VBR35"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080p25_VBR35"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080p30_VBR35"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_EX_720p24_VBR35"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_720p50/title",
          "value": "kCMMPEG2VideoProfile_HDV_720p50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_720p50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_HDV_720p50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_1080p24_VBR35/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_EX_1080p24_VBR35"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_1080p24_VBR35/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_EX_1080p24_VBR35"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_1080i50/title",
          "value": "kCMMPEG2VideoProfile_HDV_1080i50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_1080i50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_HDV_1080i50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080p24_VBR35"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080i50_VBR35"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_720p25_CBR50/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD422_720p25_CBR50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_720p25_CBR50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD422_720p25_CBR50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_720p25/title",
          "value": "kCMMPEG2VideoProfile_HDV_720p25"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_720p25/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_HDV_720p25"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_540p/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD_540p"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_540p/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD_540p"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XF/title",
          "value": "kCMMPEG2VideoProfile_XF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_1080p25_CBR50/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD422_1080p25_CBR50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_1080p25_CBR50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD422_1080p25_CBR50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_720p60_CBR50/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD422_720p60_CBR50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_720p60_CBR50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD422_720p60_CBR50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_1080p30/title",
          "value": "kCMMPEG2VideoProfile_HDV_1080p30"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_1080p30/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_HDV_1080p30"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD_1080i60_VBR35"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_720p30_CBR50/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD422_720p30_CBR50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_720p30_CBR50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD422_720p30_CBR50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_720p50_VBR35/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_EX_720p50_VBR35"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_720p50_VBR35/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_EX_720p50_VBR35"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_1080i60/title",
          "value": "kCMMPEG2VideoProfile_HDV_1080i60"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_1080i60/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_HDV_1080i60"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_720p60_VBR35/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_EX_720p60_VBR35"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_720p60_VBR35/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_EX_720p60_VBR35"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_1080p30_VBR35/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_EX_1080p30_VBR35"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_1080p30_VBR35/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_EX_1080p30_VBR35"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_720p24/title",
          "value": "kCMMPEG2VideoProfile_HDV_720p24"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_HDV_720p24/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_HDV_720p24"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_720p24_CBR50/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_HD422_720p24_CBR50"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_HD422_720p24_CBR50/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_HD422_720p24_CBR50"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_720p25_VBR35/title",
          "value": "kCMMPEG2VideoProfile_XDCAM_EX_720p25_VBR35"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1kCMMPEG2VideoProfile_XDCAM_EX_720p25_VBR35/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMMPEG2VideoProfile_XDCAM_EX_720p25_VBR35"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/video-profile-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/video-profile-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
