{
  "abstract": [
    {
      "text": "The duration of the audio buffer the request sends to the underlying sound classifier for each prediction.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis",
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest/windowDuration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SNClassifySoundRequest(py)windowDuration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "windowDuration"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@CMTime",
        "text": "CMTime"
      }
    ],
    "modules": [
      {
        "name": "Sound Analysis"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "windowDuration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "windowDuration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "windowDuration"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMTime",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CMTime",
              "text": "CMTime"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Configure the window duration with a value that satisfies the request’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest/windowDurationConstraint-5no60",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The request sends larger audio buffer windows less frequently, which can make the classifications more accurate, but less precise in indicating when they occur. Requests with smaller buffer window durations sharpen the time resolution of each prediction, but send smaller audio buffers to the sound classifier.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis": {
      "abstract": [
        {
          "text": "Classify various sounds by analyzing audio files or streams.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis",
      "kind": "symbol",
      "role": "collection",
      "title": "Sound Analysis",
      "type": "topic",
      "url": "/documentation/soundanalysis"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest": {
      "abstract": [
        {
          "text": "A request that classifies sound using a Core ML model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SNClassifySoundRequest"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SNClassifySoundRequest"
        }
      ],
      "role": "symbol",
      "title": "SNClassifySoundRequest",
      "type": "topic",
      "url": "/documentation/soundanalysis/snclassifysoundrequest"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest/overlapFactor": {
      "abstract": [
        {
          "text": "The amount of overlap between successive analysis windows when the model operates on a fixed-size audio block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overlapFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest/overlapFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "overlapFactor"
        }
      ],
      "role": "symbol",
      "title": "overlapFactor",
      "type": "topic",
      "url": "/documentation/soundanalysis/snclassifysoundrequest/overlapfactor"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest/windowDuration": {
      "abstract": [
        {
          "text": "The duration of the audio buffer the request sends to the underlying sound classifier for each prediction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windowDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest/windowDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "windowDuration"
        }
      ],
      "role": "symbol",
      "title": "windowDuration",
      "type": "topic",
      "url": "/documentation/soundanalysis/snclassifysoundrequest/windowduration"
    },
    "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest/windowDurationConstraint-5no60": {
      "abstract": [
        {
          "text": "A range or list of sound duration times the request’s underlying sound classifier supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windowDurationConstraint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:13SoundAnalysis24SNTimeDurationConstraintO",
          "text": "SNTimeDurationConstraint"
        }
      ],
      "identifier": "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest/windowDurationConstraint-5no60",
      "kind": "symbol",
      "role": "symbol",
      "title": "windowDurationConstraint",
      "type": "topic",
      "url": "/documentation/soundanalysis/snclassifysoundrequest/windowdurationconstraint-5no60"
    },
    "doc://com.externally.resolved.symbol/c:@SA@CMTime": {
      "abstract": [
        {
          "text": "A structure that represents time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMTime",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTime",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMTime"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-a-Request",
      "generated": true,
      "identifiers": [
        "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest/overlapFactor"
      ],
      "title": "Configuring a Request"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "windowDuration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "windowDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis",
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-a-Request",
              "generated": true,
              "identifiers": [
                "doc://com.apple.soundanalysis/documentation/SoundAnalysis/SNClassifySoundRequest/overlapFactor"
              ],
              "title": "Configuring a Request"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readwrite"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMTime",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@CMTime",
                    "text": "CMTime"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "windowDuration"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifySoundRequest/title",
          "value": "SNClassifySoundRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifySoundRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SNClassifySoundRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifySoundRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SNClassifySoundRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifySoundRequest~1overlapFactor/title",
          "value": "overlapFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifySoundRequest~1overlapFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "overlapFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@SA@CMTime/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " { ... } "
            },
            {
              "kind": "identifier",
              "text": "CMTime"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifySoundRequest~1windowDuration/title",
          "value": "windowDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.soundanalysis~1documentation~1SoundAnalysis~1SNClassifySoundRequest~1windowDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "windowDuration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/soundanalysis/snclassifysoundrequest/windowduration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/soundanalysis/snclassifysoundrequest/windowduration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
