{
  "abstract": [
    {
      "text": "Initiates a specific pattern of haptic feedback to the user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackPerformer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackPerformer/perform(_:performanceTime:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSHapticFeedbackPerformer(im)performFeedbackPattern:performanceTime:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "perform"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSHapticFeedbackManager",
        "text": "NSHapticFeedbackManager"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSHapticFeedbackPattern",
        "text": "FeedbackPattern"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "performanceTime"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSHapticFeedbackManager",
        "text": "NSHapticFeedbackManager"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSHapticFeedbackPerformanceTime",
        "text": "PerformanceTime"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "performFeedbackPattern:performanceTime:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "perform(_:performanceTime:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "perform"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "pattern"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSHapticFeedbackManager",
              "text": "NSHapticFeedbackManager"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/FeedbackPattern",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSHapticFeedbackPattern",
              "text": "FeedbackPattern"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "performanceTime"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSHapticFeedbackManager",
              "text": "NSHapticFeedbackManager"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSHapticFeedbackPerformanceTime",
              "text": "PerformanceTime"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A pattern of feedback to be provided to the user. For possible values, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/FeedbackPattern",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "pattern"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The time when the feedback should be provided to the user. For possible values, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "performanceTime"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In some cases, the system may override a call to this method. For example, a Force Touch trackpad won’t provide haptic feedback if the user isn’t touching the trackpad.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Call this method only in response to user-initiated actions. Ideally, visual feedback, such as a highlight or appearance of an alignment guide, should accompany the feedback.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager": {
      "abstract": [
        {
          "text": "An object that provides access to the haptic feedback management attributes on a system with a Force Touch trackpad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHapticFeedbackManager"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHapticFeedbackManager"
        }
      ],
      "role": "symbol",
      "title": "NSHapticFeedbackManager",
      "type": "topic",
      "url": "/documentation/appkit/nshapticfeedbackmanager"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/FeedbackPattern": {
      "abstract": [
        {
          "text": "A pattern of haptic feedback to be provided to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FeedbackPattern"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/FeedbackPattern",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FeedbackPattern"
        }
      ],
      "role": "symbol",
      "title": "NSHapticFeedbackManager.FeedbackPattern",
      "type": "topic",
      "url": "/documentation/appkit/nshapticfeedbackmanager/feedbackpattern"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime": {
      "abstract": [
        {
          "text": "A time at which to provide haptic feedback to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PerformanceTime"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PerformanceTime"
        }
      ],
      "role": "symbol",
      "title": "NSHapticFeedbackManager.PerformanceTime",
      "type": "topic",
      "url": "/documentation/appkit/nshapticfeedbackmanager/performancetime"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackPerformer": {
      "abstract": [
        {
          "text": "A set of methods and constants that a haptic feedback performer implements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHapticFeedbackPerformer"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackPerformer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHapticFeedbackPerformer"
        }
      ],
      "role": "symbol",
      "title": "NSHapticFeedbackPerformer",
      "type": "topic",
      "url": "/documentation/appkit/nshapticfeedbackperformer"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackPerformer/perform(_:performanceTime:)": {
      "abstract": [
        {
          "text": "Initiates a specific pattern of haptic feedback to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSHapticFeedbackManager",
          "text": "NSHapticFeedbackManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSHapticFeedbackPattern",
          "text": "FeedbackPattern"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "performanceTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSHapticFeedbackManager",
          "text": "NSHapticFeedbackManager"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSHapticFeedbackPerformanceTime",
          "text": "PerformanceTime"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackPerformer/perform(_:performanceTime:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performFeedbackPattern:performanceTime:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "perform(_:performanceTime:)",
      "type": "topic",
      "url": "/documentation/appkit/nshapticfeedbackperformer/perform(_:performancetime:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime",
        "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager",
        "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/FeedbackPattern"
      ],
      "title": "Related Documentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "performFeedbackPattern:performanceTime:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performFeedbackPattern:performanceTime:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackPerformer"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime",
                "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager",
                "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/FeedbackPattern"
              ],
              "title": "Related Documentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "performFeedbackPattern:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/FeedbackPattern",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSHapticFeedbackPattern",
                    "text": "NSHapticFeedbackPattern"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "pattern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "performanceTime:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSHapticFeedbackPerformanceTime",
                    "text": "NSHapticFeedbackPerformanceTime"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "performanceTime"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A pattern of feedback to be provided to the user. For possible values, see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/FeedbackPattern",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "pattern"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The time when the feedback should be provided to the user. For possible values, see ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHapticFeedbackManager/PerformanceTime",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "performanceTime"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackPerformer/title",
          "value": "NSHapticFeedbackPerformer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackPerformer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHapticFeedbackPerformer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackPerformer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHapticFeedbackPerformer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackManager~1PerformanceTime/title",
          "value": "NSHapticFeedbackPerformanceTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackManager~1PerformanceTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHapticFeedbackPerformanceTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackManager~1PerformanceTime/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHapticFeedbackPerformanceTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackManager/title",
          "value": "NSHapticFeedbackManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHapticFeedbackManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHapticFeedbackManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackManager~1FeedbackPattern/title",
          "value": "NSHapticFeedbackPattern"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackManager~1FeedbackPattern/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHapticFeedbackPattern"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackManager~1FeedbackPattern/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSHapticFeedbackPattern"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackPerformer~1perform(_:performanceTime:)/title",
          "value": "performFeedbackPattern:performanceTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSHapticFeedbackPerformer~1perform(_:performanceTime:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performFeedbackPattern:performanceTime:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nshapticfeedbackperformer/perform(_:performancetime:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nshapticfeedbackperformer/perform(_:performancetime:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
