{
  "abstract": [
    {
      "text": "Creates an ",
      "type": "text"
    },
    {
      "inlineContent": [
        {
          "text": "Add to Siri",
          "type": "text"
        }
      ],
      "type": "emphasis"
    },
    {
      "text": " button with the specified style.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/IntentsUI",
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButton"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButton/init(style:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INUIAddVoiceShortcutButton(im)initWithStyle:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "style"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@INUIAddVoiceShortcutButtonStyle",
        "text": "INUIAddVoiceShortcutButtonStyle"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "IntentsUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithStyle:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(style:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "style"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButtonStyle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@INUIAddVoiceShortcutButtonStyle",
              "text": "INUIAddVoiceShortcutButtonStyle"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The style of the button.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "style"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A button initialized with the specified style.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI": {
      "abstract": [
        {
          "text": "Customize content in the interface for Siri and Maps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IntentsUI",
      "type": "topic",
      "url": "/documentation/intentsui"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButton": {
      "abstract": [
        {
          "text": "A button that allows the user to add or edit a shortcut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUIAddVoiceShortcutButton"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIAddVoiceShortcutButton"
        }
      ],
      "role": "symbol",
      "title": "INUIAddVoiceShortcutButton",
      "type": "topic",
      "url": "/documentation/intentsui/inuiaddvoiceshortcutbutton"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButton/init(style:)": {
      "abstract": [
        {
          "text": "Creates an ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Add to Siri",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " button with the specified style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INUIAddVoiceShortcutButtonStyle",
          "text": "INUIAddVoiceShortcutButtonStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButton/init(style:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithStyle:"
        }
      ],
      "role": "symbol",
      "title": "init(style:)",
      "type": "topic",
      "url": "/documentation/intentsui/inuiaddvoiceshortcutbutton/init(style:)"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButtonStyle": {
      "abstract": [
        {
          "text": "The styles for the ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Add to Siri",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": " button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUIAddVoiceShortcutButtonStyle"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButtonStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIAddVoiceShortcutButtonStyle"
        }
      ],
      "role": "symbol",
      "title": "INUIAddVoiceShortcutButtonStyle",
      "type": "topic",
      "url": "/documentation/intentsui/inuiaddvoiceshortcutbuttonstyle"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Shortcut-Button",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButtonStyle"
      ],
      "title": "Creating a Shortcut Button"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithStyle:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithStyle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/IntentsUI",
                "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButton"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Shortcut-Button",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButtonStyle"
              ],
              "title": "Creating a Shortcut Button"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithStyle:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIAddVoiceShortcutButtonStyle",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@INUIAddVoiceShortcutButtonStyle",
                    "text": "INUIAddVoiceShortcutButtonStyle"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "style"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The style of the button.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "style"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A button initialized with the specified style.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButton/title",
          "value": "INUIAddVoiceShortcutButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIAddVoiceShortcutButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIAddVoiceShortcutButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButton~1init(style:)/title",
          "value": "initWithStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButton~1init(style:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithStyle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButtonStyle/title",
          "value": "INUIAddVoiceShortcutButtonStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButtonStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIAddVoiceShortcutButtonStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIAddVoiceShortcutButtonStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIAddVoiceShortcutButtonStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intentsui/inuiaddvoiceshortcutbutton/init(style:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intentsui/inuiaddvoiceshortcutbutton/init(style:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
