{
  "abstract": [
    {
      "text": "The permission option the system uses to control whether a user can grant read-only or write access.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantPermissionOption"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantPermissionOption/any"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CKSharingParticipantPermissionOption@CKSharingParticipantPermissionOptionAny",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "any"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CKSharingParticipantPermissionOption",
        "text": "CKSharingParticipantPermissionOption"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CKSharingParticipantPermissionOptionAny"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "any"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "any"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantPermissionOption",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CKSharingParticipantPermissionOption",
              "text": "CKSharingParticipantPermissionOption"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantPermissionOption": {
      "abstract": [
        {
          "text": "An object that controls participant permission options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKSharingParticipantPermissionOption"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantPermissionOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSharingParticipantPermissionOption"
        }
      ],
      "role": "symbol",
      "title": "CKSharingParticipantPermissionOption",
      "type": "topic",
      "url": "/documentation/cloudkit/cksharingparticipantpermissionoption"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantPermissionOption/any": {
      "abstract": [
        {
          "text": "The permission option the system uses to control whether a user can grant read-only or write access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "any"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKSharingParticipantPermissionOption",
          "text": "CKSharingParticipantPermissionOption"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantPermissionOption/any",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSharingParticipantPermissionOptionAny"
        }
      ],
      "role": "symbol",
      "title": "any",
      "type": "topic",
      "url": "/documentation/cloudkit/cksharingparticipantpermissionoption/any"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantPermissionOption/readOnly": {
      "abstract": [
        {
          "text": "The permission option the system uses to control whether a user can grant read-only access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKSharingParticipantPermissionOption",
          "text": "CKSharingParticipantPermissionOption"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantPermissionOption/readOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSharingParticipantPermissionOptionReadOnly"
        }
      ],
      "role": "symbol",
      "title": "readOnly",
      "type": "topic",
      "url": "/documentation/cloudkit/cksharingparticipantpermissionoption/readonly"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantPermissionOption/readWrite": {
      "abstract": [
        {
          "text": "The permission option the system uses to control whether a user can grant write access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readWrite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKSharingParticipantPermissionOption",
          "text": "CKSharingParticipantPermissionOption"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantPermissionOption/readWrite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKSharingParticipantPermissionOptionReadWrite"
        }
      ],
      "role": "symbol",
      "title": "readWrite",
      "type": "topic",
      "url": "/documentation/cloudkit/cksharingparticipantpermissionoption/readwrite"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantPermissionOption/readOnly",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantPermissionOption/readWrite"
      ],
      "title": "Configuring the options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CKSharingParticipantPermissionOptionAny"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSharingParticipantPermissionOptionAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantPermissionOption"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantPermissionOption/readOnly",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKSharingParticipantPermissionOption/readWrite"
              ],
              "title": "Configuring the options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CKSharingParticipantPermissionOptionAny"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSharingParticipantPermissionOption~1any/title",
          "value": "CKSharingParticipantPermissionOptionAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSharingParticipantPermissionOption~1any/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSharingParticipantPermissionOptionAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSharingParticipantPermissionOption~1readOnly/title",
          "value": "CKSharingParticipantPermissionOptionReadOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSharingParticipantPermissionOption~1readOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSharingParticipantPermissionOptionReadOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSharingParticipantPermissionOption/title",
          "value": "CKSharingParticipantPermissionOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSharingParticipantPermissionOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSharingParticipantPermissionOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSharingParticipantPermissionOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSharingParticipantPermissionOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSharingParticipantPermissionOption~1readWrite/title",
          "value": "CKSharingParticipantPermissionOptionReadWrite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKSharingParticipantPermissionOption~1readWrite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKSharingParticipantPermissionOptionReadWrite"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/cksharingparticipantpermissionoption/any"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/cksharingparticipantpermissionoption/any"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
