{
  "abstract": [
    {
      "text": "Informs the receiver that the mouse cursor has moved into a cursor rectangle.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSResponder"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSResponder/cursorUpdate(with:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSResponder(im)cursorUpdate:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "cursorUpdate"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "with"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSEvent",
        "text": "NSEvent"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "cursorUpdate:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "cursorUpdate(with:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "cursorUpdate"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "with"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "event"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSEvent",
              "text": "NSEvent"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An object encapsulating information about the cursor-update event (",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursorUpdate",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ").",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "event"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Override this method to set the cursor image. The default implementation uses cursor rectangles, if cursor rectangles are currently valid.  If they are not, it calls ",
              "type": "text"
            },
            {
              "code": "super",
              "type": "codeVoice"
            },
            {
              "text": " to send the message up the responder chain.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the responder implements this method, but decides not to handle a particular event, it should invoke the superclass implementation of this method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursorUpdate": {
      "abstract": [
        {
          "text": "A cursor-update event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCursorUpdate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursorUpdate",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCursorUpdate",
      "type": "topic",
      "url": "/documentation/appkit/nscursorupdate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent": {
      "abstract": [
        {
          "text": "An object that contains information about an input action, such as a mouse click or a key press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "role": "symbol",
      "title": "NSEvent",
      "type": "topic",
      "url": "/documentation/appkit/nsevent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSResponder": {
      "abstract": [
        {
          "text": "An abstract class that forms the basis of event and command processing in AppKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSResponder"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSResponder"
        }
      ],
      "role": "symbol",
      "title": "NSResponder",
      "type": "topic",
      "url": "/documentation/appkit/nsresponder"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSResponder/changeMode(with:)": {
      "abstract": [
        {
          "text": "Informs the responder that performed a double-tap on the side of an Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changeMode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/changeMode(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "changeModeWithEvent:"
        }
      ],
      "role": "symbol",
      "title": "changeMode(with:)",
      "type": "topic",
      "url": "/documentation/appkit/nsresponder/changemode(with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSResponder/cursorUpdate(with:)": {
      "abstract": [
        {
          "text": "Informs the receiver that the mouse cursor has moved into a cursor rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cursorUpdate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/cursorUpdate(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cursorUpdate:"
        }
      ],
      "role": "symbol",
      "title": "cursorUpdate(with:)",
      "type": "topic",
      "url": "/documentation/appkit/nsresponder/cursorupdate(with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSResponder/flagsChanged(with:)": {
      "abstract": [
        {
          "text": "Informs the receiver that the user has pressed or released a modifier key (Shift, Control, and so on).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flagsChanged"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/flagsChanged(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "flagsChanged:"
        }
      ],
      "role": "symbol",
      "title": "flagsChanged(with:)",
      "type": "topic",
      "url": "/documentation/appkit/nsresponder/flagschanged(with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSResponder/helpRequested(_:)": {
      "abstract": [
        {
          "text": "Displays context-sensitive help for the receiver if help has been registered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "helpRequested"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/helpRequested(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "helpRequested:"
        }
      ],
      "role": "symbol",
      "title": "helpRequested(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsresponder/helprequested(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSResponder/quickLook(with:)": {
      "abstract": [
        {
          "text": "Performs a Quick Look on the content at the location specified by the supplied event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quickLook"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/quickLook(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "quickLookWithEvent:"
        }
      ],
      "role": "symbol",
      "title": "quickLook(with:)",
      "type": "topic",
      "url": "/documentation/appkit/nsresponder/quicklook(with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSResponder/scrollWheel(with:)": {
      "abstract": [
        {
          "text": "Informs the receiver that the mouse’s scroll wheel has moved.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollWheel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/scrollWheel(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollWheel:"
        }
      ],
      "role": "symbol",
      "title": "scrollWheel(with:)",
      "type": "topic",
      "url": "/documentation/appkit/nsresponder/scrollwheel(with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletPoint(with:)": {
      "abstract": [
        {
          "text": "Informs the receiver that a tablet-point event has occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabletPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletPoint(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabletPoint:"
        }
      ],
      "role": "symbol",
      "title": "tabletPoint(with:)",
      "type": "topic",
      "url": "/documentation/appkit/nsresponder/tabletpoint(with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletProximity(with:)": {
      "abstract": [
        {
          "text": "Informs the receiver that a tablet-proximity event has occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabletProximity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletProximity(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabletProximity:"
        }
      ],
      "role": "symbol",
      "title": "tabletProximity(with:)",
      "type": "topic",
      "url": "/documentation/appkit/nsresponder/tabletproximity(with:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-Other-Kinds-of-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSResponder/flagsChanged(with:)",
        "doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletPoint(with:)",
        "doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletProximity(with:)",
        "doc://com.apple.appkit/documentation/AppKit/NSResponder/helpRequested(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSResponder/scrollWheel(with:)",
        "doc://com.apple.appkit/documentation/AppKit/NSResponder/quickLook(with:)",
        "doc://com.apple.appkit/documentation/AppKit/NSResponder/changeMode(with:)"
      ],
      "title": "Responding to Other Kinds of Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "cursorUpdate:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cursorUpdate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSResponder"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-Other-Kinds-of-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSResponder/flagsChanged(with:)",
                "doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletPoint(with:)",
                "doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletProximity(with:)",
                "doc://com.apple.appkit/documentation/AppKit/NSResponder/helpRequested(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSResponder/scrollWheel(with:)",
                "doc://com.apple.appkit/documentation/AppKit/NSResponder/quickLook(with:)",
                "doc://com.apple.appkit/documentation/AppKit/NSResponder/changeMode(with:)"
              ],
              "title": "Responding to Other Kinds of Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "cursorUpdate:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSEvent",
                    "text": "NSEvent"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "event"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An object encapsulating information about the cursor-update event (",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursorUpdate",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ").",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "event"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title",
          "value": "NSEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1changeMode(with:)/title",
          "value": "changeModeWithEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1changeMode(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "changeModeWithEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1quickLook(with:)/title",
          "value": "quickLookWithEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1quickLook(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "quickLookWithEvent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1flagsChanged(with:)/title",
          "value": "flagsChanged:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1flagsChanged(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "flagsChanged:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1cursorUpdate(with:)/title",
          "value": "cursorUpdate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1cursorUpdate(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cursorUpdate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1tabletProximity(with:)/title",
          "value": "tabletProximity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1tabletProximity(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tabletProximity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1scrollWheel(with:)/title",
          "value": "scrollWheel:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1scrollWheel(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scrollWheel:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/title",
          "value": "NSResponder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1tabletPoint(with:)/title",
          "value": "tabletPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1tabletPoint(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tabletPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1helpRequested(_:)/title",
          "value": "helpRequested:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1helpRequested(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "helpRequested:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsresponder/cursorupdate(with:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsresponder/cursorupdate(with:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
