{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSResponder"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSResponder/encodeRestorableState(with:backgroundQueue:)"},"kind":"symbol","abstract":[{"type":"text","text":"Saves the interface-related state of the responder to a keyed archiver either synchronously or asynchronously on the given operation queue."}],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSResponder/allowedClasses(forRestorableStateKeyPath:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/encodeRestorableState(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/restoreState(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/restorableStateKeyPaths","doc://com.apple.appkit/documentation/AppKit/NSResponder/invalidateRestorableState()"],"generated":true,"title":"Handling Window Restoration","anchor":"Handling-Window-Restoration"}],"metadata":{"title":"encodeRestorableState(with:backgroundQueue:)","modules":[{"name":"AppKit"}],"role":"symbol","externalID":"c:objc(cs)NSResponder(im)encodeRestorableStateWithCoder:backgroundQueue:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeRestorableState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"kind":"text","text":", "},{"kind":"externalParam","text":"backgroundQueue"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSOperationQueue","kind":"typeIdentifier","text":"OperationQueue"},{"kind":"text","text":")"}],"platforms":[{"unavailable":false,"beta":false,"deprecated":false,"name":"macOS","introducedAt":"10.13"}],"roleHeading":"Instance Method","symbolKind":"method","extendedModule":"AppKit","navigatorTitle":[{"kind":"identifier","text":"encodeRestorableStateWithCoder:backgroundQueue:"}]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeRestorableState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"coder"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSCoder","text":"NSCoder"},{"kind":"text","text":", "},{"kind":"externalParam","text":"backgroundQueue"},{"kind":"text","text":" "},{"kind":"internalParam","text":"queue"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSOperationQueue","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSOperationQueue","text":"OperationQueue"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"name":"coder","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A thread-safe keyed archiver to write restorable state into."}]}]},{"name":"queue","content":[{"inlineContent":[{"type":"text","text":"A serial background operation queue to perform asynchronous encoding work on."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"anchor":"Discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Don’t call this method directly. The system calls this method on the main thread. The receiver may synchronously encode state to "},{"type":"codeVoice","code":"coder"},{"type":"text","text":" or may enqueue asynchronous work to encode additional restorable state using the provided serial background "},{"identifier":"doc://com.apple.documentation/documentation/foundation/operationqueue","type":"reference","isActive":true},{"type":"text","text":", if it can safely access and encode that information. The encoding process finishes when the enqueued operations complete."}],"type":"paragraph"},{"inlineContent":[{"text":"If you override this method, call the super implementation.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsresponder/encoderestorablestate(with:backgroundqueue:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsresponder/encoderestorablestate(with:backgroundqueue:)"]}],"references":{"doc://com.apple.documentation/documentation/foundation/operationqueue":{"type":"topic","title":"OperationQueue","identifier":"doc://com.apple.documentation/documentation/foundation/operationqueue","kind":"symbol","role":"symbol","url":"/documentation/foundation/operationqueue","fragments":[{"text":"class ","kind":"text"},{"text":"OperationQueue","kind":"identifier"}],"abstract":[{"text":"A queue that regulates the execution of operations.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSResponder/restoreState(with:)":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"restoreStateWithCoder:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"restoreState","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"kind":"text","text":")"}],"url":"/documentation/appkit/nsresponder/restorestate(with:)","abstract":[{"text":"Restores the interface-related state of the responder.","type":"text"}],"title":"restoreState(with:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/restoreState(with:)"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/encodeRestorableState(with:backgroundQueue:)":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"encodeRestorableStateWithCoder:backgroundQueue:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"encodeRestorableState","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"kind":"text","text":", "},{"kind":"externalParam","text":"backgroundQueue"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSOperationQueue","text":"OperationQueue","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/appkit/nsresponder/encoderestorablestate(with:backgroundqueue:)","abstract":[{"text":"Saves the interface-related state of the responder to a keyed archiver either synchronously or asynchronously on the given operation queue.","type":"text"}],"title":"encodeRestorableState(with:backgroundQueue:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/encodeRestorableState(with:backgroundQueue:)"},"doc://com.externally.resolved.symbol/c:objc(cs)NSOperationQueue":{"abstract":[{"text":"A queue that regulates the execution of operations.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSOperationQueue","url":"/documentation/foundation/operationqueue","kind":"symbol","role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"OperationQueue","kind":"identifier"}],"title":"OperationQueue","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/allowedClasses(forRestorableStateKeyPath:)":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"allowedClassesForRestorableStateKeyPath:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowedClasses"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forRestorableStateKeyPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"s:s8AnyClassa","text":"AnyClass","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"/documentation/appkit/nsresponder/allowedclasses(forrestorablestatekeypath:)","abstract":[{"type":"text","text":"Returns the classes that support secure coding."}],"title":"allowedClasses(forRestorableStateKeyPath:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/allowedClasses(forRestorableStateKeyPath:)"},"doc://com.apple.appkit/documentation/AppKit/NSResponder":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder","abstract":[{"text":"An abstract class that forms the basis of event and command processing in AppKit.","type":"text"}],"navigatorTitle":[{"text":"NSResponder","kind":"identifier"}],"url":"/documentation/appkit/nsresponder","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSResponder","kind":"identifier"}],"type":"topic","title":"NSResponder"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/invalidateRestorableState()":{"title":"invalidateRestorableState()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"invalidateRestorableState"}],"type":"topic","url":"/documentation/appkit/nsresponder/invalidaterestorablestate()","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/invalidateRestorableState()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidateRestorableState"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Marks the responder’s interface-related state as dirty."}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSCoder":{"type":"topic","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSCoder"}],"url":"/documentation/foundation/nscoder","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSCoder","role":"symbol","title":"NSCoder","kind":"symbol","abstract":[{"type":"text","text":"An abstract class that serves as the basis for objects that enable archiving and distribution of other objects."}]},"doc://com.apple.appkit/documentation/AppKit/NSResponder/encodeRestorableState(with:)":{"type":"topic","url":"/documentation/appkit/nsresponder/encoderestorablestate(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeRestorableState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/encodeRestorableState(with:)","abstract":[{"text":"Saves the interface-related state of the responder.","type":"text"}],"kind":"symbol","title":"encodeRestorableState(with:)","navigatorTitle":[{"kind":"identifier","text":"encodeRestorableStateWithCoder:"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/restorableStateKeyPaths":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"restorableStateKeyPaths"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"restorableStateKeyPaths","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"url":"/documentation/appkit/nsresponder/restorablestatekeypaths","abstract":[{"text":"Returns an array of key paths representing the restorable attributes of the responder.","type":"text"}],"title":"restorableStateKeyPaths","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/restorableStateKeyPaths"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"unavailable":false,"introducedAt":"10.13","deprecated":false,"name":"macOS"}],"op":"replace","path":"/metadata/platforms"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"encodeRestorableStateWithCoder:backgroundQueue:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"encodeRestorableStateWithCoder:backgroundQueue:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSResponder"]]},"op":"replace"},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Handling-Window-Restoration","title":"Handling Window Restoration","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSResponder/allowedClasses(forRestorableStateKeyPath:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/encodeRestorableState(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/restoreState(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/restorableStateKeyPaths","doc://com.apple.appkit/documentation/AppKit/NSResponder/invalidateRestorableState()"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"encodeRestorableStateWithCoder:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSCoder","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":" *) ","kind":"text"},{"text":"coder","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"backgroundQueue:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSOperationQueue","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSOperationQueue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSOperationQueue"},{"text":" *) ","kind":"text"},{"text":"queue","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"A thread-safe keyed archiver to write restorable state into.","type":"text"}],"type":"paragraph"}],"name":"coder"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A serial background operation queue to perform asynchronous encoding work on.","type":"text"}]}],"name":"queue"}]}},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1operationqueue/title","op":"replace","value":"NSOperationQueue"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1restoreState(with:)/title","op":"replace","value":"restoreStateWithCoder:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1restoreState(with:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"restoreStateWithCoder:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1encodeRestorableState(with:backgroundQueue:)/title","op":"replace","value":"encodeRestorableStateWithCoder:backgroundQueue:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1encodeRestorableState(with:backgroundQueue:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"encodeRestorableStateWithCoder:backgroundQueue:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSOperationQueue/title","op":"replace","value":"NSOperationQueue"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1allowedClasses(forRestorableStateKeyPath:)/title","op":"replace","value":"allowedClassesForRestorableStateKeyPath:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1allowedClasses(forRestorableStateKeyPath:)/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"allowedClassesForRestorableStateKeyPath:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/title","op":"replace","value":"NSResponder"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/fragments","op":"replace","value":[{"text":"NSResponder","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSResponder"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1invalidateRestorableState()/title","op":"replace","value":"invalidateRestorableState"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1invalidateRestorableState()/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"invalidateRestorableState"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1encodeRestorableState(with:)/title","op":"replace","value":"encodeRestorableStateWithCoder:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1encodeRestorableState(with:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"encodeRestorableStateWithCoder:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1restorableStateKeyPaths/title","op":"replace","value":"restorableStateKeyPaths"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1restorableStateKeyPaths/fragments","value":[{"kind":"identifier","text":"restorableStateKeyPaths"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}