{"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSResponder/flagsChanged(with:)","interfaceLanguage":"swift"},"seeAlsoSections":[{"anchor":"Responding-to-Other-Kinds-of-Events","generated":true,"title":"Responding to Other Kinds of Events","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSResponder/cursorUpdate(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletPoint(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletProximity(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/helpRequested(_:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/scrollWheel(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/quickLook(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/changeMode(with:)"]}],"abstract":[{"text":"Informs the receiver that the user has pressed or released a modifier key (Shift, Control, and so on).","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSResponder"]]},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"flagsChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object encapsulating information about the modifier-key event."}]}],"name":"event"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"Discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The default implementation simply passes this message to the next responder."}]}]}],"variants":[{"paths":["/documentation/appkit/nsresponder/flagschanged(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsresponder/flagschanged(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"AppKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"flagsChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSEvent","kind":"typeIdentifier","text":"NSEvent"},{"kind":"text","text":")"}],"externalID":"c:objc(cs)NSResponder(im)flagsChanged:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"flagsChanged:"}],"title":"flagsChanged(with:)","role":"symbol","platforms":[{"name":"macOS","deprecated":false,"beta":false,"unavailable":false}],"roleHeading":"Instance Method"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSResponder/changeMode(with:)":{"role":"symbol","url":"/documentation/appkit/nsresponder/changemode(with:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/changeMode(with:)","title":"changeMode(with:)","abstract":[{"type":"text","text":"Informs the responder that performed a double-tap on the side of an Apple Pencil."}],"type":"topic","navigatorTitle":[{"text":"changeModeWithEvent:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"changeMode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletPoint(with:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tabletPoint:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletPoint(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabletPoint"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent"},{"kind":"text","text":")"}],"kind":"symbol","url":"/documentation/appkit/nsresponder/tabletpoint(with:)","abstract":[{"text":"Informs the receiver that a tablet-point event has occurred.","type":"text"}],"title":"tabletPoint(with:)"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/flagsChanged(with:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"flagsChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":")","kind":"text"}],"url":"/documentation/appkit/nsresponder/flagschanged(with:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"flagsChanged:","kind":"identifier"}],"title":"flagsChanged(with:)","abstract":[{"text":"Informs the receiver that the user has pressed or released a modifier key (Shift, Control, and so on).","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/flagsChanged(with:)"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/cursorUpdate(with:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/cursorUpdate(with:)","role":"symbol","type":"topic","url":"/documentation/appkit/nsresponder/cursorupdate(with:)","navigatorTitle":[{"text":"cursorUpdate:","kind":"identifier"}],"abstract":[{"text":"Informs the receiver that the mouse cursor has moved into a cursor rectangle.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cursorUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"cursorUpdate(with:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/scrollWheel(with:)":{"role":"symbol","url":"/documentation/appkit/nsresponder/scrollwheel(with:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/scrollWheel(with:)","title":"scrollWheel(with:)","abstract":[{"text":"Informs the receiver that the mouse’s scroll wheel has moved.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"scrollWheel:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollWheel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":")","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletProximity(with:)":{"type":"topic","role":"symbol","title":"tabletProximity(with:)","url":"/documentation/appkit/nsresponder/tabletproximity(with:)","navigatorTitle":[{"text":"tabletProximity:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletProximity(with:)","kind":"symbol","abstract":[{"type":"text","text":"Informs the receiver that a tablet-proximity event has occurred."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tabletProximity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSEvent"}],"role":"symbol","type":"topic","title":"NSEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSEvent"}],"abstract":[{"type":"text","text":"An object that contains information about an input action, such as a mouse click or a key press."}],"url":"/documentation/appkit/nsevent"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/quickLook(with:)":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/quickLook(with:)","url":"/documentation/appkit/nsresponder/quicklook(with:)","abstract":[{"type":"text","text":"Performs a Quick Look on the content at the location specified by the supplied event."}],"kind":"symbol","title":"quickLook(with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"quickLook","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"quickLookWithEvent:","kind":"identifier"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSResponder":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder","abstract":[{"text":"An abstract class that forms the basis of event and command processing in AppKit.","type":"text"}],"navigatorTitle":[{"text":"NSResponder","kind":"identifier"}],"url":"/documentation/appkit/nsresponder","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSResponder","kind":"identifier"}],"type":"topic","title":"NSResponder"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/helpRequested(_:)":{"role":"symbol","type":"topic","title":"helpRequested(_:)","url":"/documentation/appkit/nsresponder/helprequested(_:)","navigatorTitle":[{"text":"helpRequested:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/helpRequested(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpRequested","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":")","kind":"text"}],"abstract":[{"text":"Displays context-sensitive help for the receiver if help has been registered.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"beta":false,"name":"macOS","unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"flagsChanged:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"flagsChanged:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSResponder"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"anchor":"Responding-to-Other-Kinds-of-Events","title":"Responding to Other Kinds of Events","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSResponder/cursorUpdate(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletPoint(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletProximity(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/helpRequested(_:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/scrollWheel(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/quickLook(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/changeMode(with:)"]}],"path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"flagsChanged:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"event","content":[{"inlineContent":[{"text":"An object encapsulating information about the modifier-key event.","type":"text"}],"type":"paragraph"}]}]},"path":"/primaryContentSections/1"},{"value":"changeModeWithEvent:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1changeMode(with:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeModeWithEvent:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1changeMode(with:)/fragments","op":"replace"},{"value":"tabletPoint:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1tabletPoint(with:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tabletPoint:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1tabletPoint(with:)/fragments","op":"replace"},{"value":"flagsChanged:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1flagsChanged(with:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"flagsChanged:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1flagsChanged(with:)/fragments","op":"replace"},{"value":"cursorUpdate:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1cursorUpdate(with:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cursorUpdate:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1cursorUpdate(with:)/fragments","op":"replace"},{"value":"scrollWheel:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1scrollWheel(with:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollWheel:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1scrollWheel(with:)/fragments","op":"replace"},{"value":"tabletProximity:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1tabletProximity(with:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"tabletProximity:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1tabletProximity(with:)/fragments","op":"replace"},{"value":"NSEvent","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSEvent"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments","op":"replace"},{"value":[{"text":"NSEvent","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle","op":"replace"},{"value":"quickLookWithEvent:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1quickLook(with:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"quickLookWithEvent:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1quickLook(with:)/fragments","op":"replace"},{"value":"NSResponder","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSResponder"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/fragments","op":"replace"},{"value":[{"text":"NSResponder","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/navigatorTitle","op":"replace"},{"value":"helpRequested:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1helpRequested(_:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"helpRequested:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1helpRequested(_:)/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}