{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"platforms":[{"unavailable":false,"deprecated":false,"name":"macOS","beta":false}],"title":"mouseExited(with:)","role":"symbol","externalID":"c:objc(cs)NSResponder(im)mouseExited:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mouseExited"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","modules":[{"name":"AppKit"}],"navigatorTitle":[{"kind":"identifier","text":"mouseExited:"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSResponder"]]},"seeAlsoSections":[{"title":"Responding to Mouse Events","generated":true,"anchor":"Responding-to-Mouse-Events","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseDown(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseDragged(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseUp(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseMoved(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseEntered(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseDown(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseDragged(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseUp(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseDown(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseDragged(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseUp(with:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseExited(with:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseExited","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent"},{"text":")","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"},{"parameters":[{"name":"event","content":[{"type":"paragraph","inlineContent":[{"text":"An object encapsulating information about the mouse-exited event.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"anchor":"Discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"The default implementation simply passes this message to the next responder.","type":"text"}]}],"kind":"content"}],"kind":"symbol","abstract":[{"type":"text","text":"Informs the receiver that the cursor has exited a tracking rectangle."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsresponder/mouseexited(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsresponder/mouseexited(with:)"]}],"sections":[],"references":{"doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseUp(with:)":{"role":"symbol","type":"topic","title":"rightMouseUp(with:)","url":"/documentation/appkit/nsresponder/rightmouseup(with:)","navigatorTitle":[{"kind":"identifier","text":"rightMouseUp:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseUp(with:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightMouseUp"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSEvent","kind":"typeIdentifier","text":"NSEvent"},{"kind":"text","text":")"}],"abstract":[{"text":"Informs the receiver that the user has released the right mouse button.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSEvent":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSEvent"}],"role":"symbol","type":"topic","title":"NSEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSEvent"}],"abstract":[{"type":"text","text":"An object that contains information about an input action, such as a mouse click or a key press."}],"url":"/documentation/appkit/nsevent"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseDragged(with:)":{"title":"mouseDragged(with:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseDragged(with:)","url":"/documentation/appkit/nsresponder/mousedragged(with:)","navigatorTitle":[{"kind":"identifier","text":"mouseDragged:"}],"abstract":[{"text":"Informs the receiver that the user has moved the mouse with the left button pressed.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mouseDragged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent"},{"kind":"text","text":")"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseUp(with:)":{"role":"symbol","type":"topic","title":"otherMouseUp(with:)","url":"/documentation/appkit/nsresponder/othermouseup(with:)","navigatorTitle":[{"kind":"identifier","text":"otherMouseUp:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseUp(with:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"otherMouseUp"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent"},{"kind":"text","text":")"}],"abstract":[{"text":"Informs the receiver that the user has released a mouse button other than the left or right button.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseDown(with:)":{"role":"symbol","url":"/documentation/appkit/nsresponder/rightmousedown(with:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseDown(with:)","title":"rightMouseDown(with:)","abstract":[{"text":"Informs the receiver that the user has pressed the right mouse button.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"rightMouseDown:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightMouseDown","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":")","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseDragged(with:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseDragged(with:)","navigatorTitle":[{"kind":"identifier","text":"rightMouseDragged:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightMouseDragged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSEvent","kind":"typeIdentifier","text":"NSEvent"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"text":"Informs the receiver that the user has moved the mouse with the right button pressed.","type":"text"}],"type":"topic","title":"rightMouseDragged(with:)","role":"symbol","url":"/documentation/appkit/nsresponder/rightmousedragged(with:)"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseDown(with:)":{"title":"otherMouseDown(with:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseDown(with:)","url":"/documentation/appkit/nsresponder/othermousedown(with:)","navigatorTitle":[{"text":"otherMouseDown:","kind":"identifier"}],"abstract":[{"text":"Informs the receiver that the user has pressed a mouse button other than the left or right one.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"otherMouseDown","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseDragged(with:)":{"url":"/documentation/appkit/nsresponder/othermousedragged(with:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"otherMouseDragged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent"},{"kind":"text","text":")"}],"title":"otherMouseDragged(with:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseDragged(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"otherMouseDragged:"}],"abstract":[{"text":"Informs the receiver that the user has moved the mouse with a button other than the left or right button pressed.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseExited(with:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseExited","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":")","kind":"text"}],"url":"/documentation/appkit/nsresponder/mouseexited(with:)","title":"mouseExited(with:)","abstract":[{"text":"Informs the receiver that the cursor has exited a tracking rectangle.","type":"text"}],"navigatorTitle":[{"text":"mouseExited:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseExited(with:)","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseMoved(with:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseMoved(with:)","role":"symbol","type":"topic","url":"/documentation/appkit/nsresponder/mousemoved(with:)","navigatorTitle":[{"text":"mouseMoved:","kind":"identifier"}],"abstract":[{"text":"Informs the receiver that the mouse has moved.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseMoved","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"mouseMoved(with:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSResponder":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder","abstract":[{"text":"An abstract class that forms the basis of event and command processing in AppKit.","type":"text"}],"navigatorTitle":[{"text":"NSResponder","kind":"identifier"}],"url":"/documentation/appkit/nsresponder","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSResponder","kind":"identifier"}],"type":"topic","title":"NSResponder"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseEntered(with:)":{"abstract":[{"text":"Informs the receiver that the cursor has entered a tracking rectangle.","type":"text"}],"navigatorTitle":[{"text":"mouseEntered:","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseEntered(with:)","url":"/documentation/appkit/nsresponder/mouseentered(with:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseEntered","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"mouseEntered(with:)"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseUp(with:)":{"role":"symbol","url":"/documentation/appkit/nsresponder/mouseup(with:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseUp(with:)","title":"mouseUp(with:)","abstract":[{"text":"Informs the receiver that the user has released the left mouse button.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"mouseUp:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseUp","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":")","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseDown(with:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseDown","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseDown(with:)","abstract":[{"text":"Informs the receiver that the user has pressed the left mouse button.","type":"text"}],"type":"topic","title":"mouseDown(with:)","kind":"symbol","navigatorTitle":[{"text":"mouseDown:","kind":"identifier"}],"url":"/documentation/appkit/nsresponder/mousedown(with:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"name":"macOS","deprecated":false,"beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"mouseExited:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"mouseExited:","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSResponder"]]}},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Responding-to-Mouse-Events","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseDown(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseDragged(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseUp(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseMoved(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseEntered(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseDown(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseDragged(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseUp(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseDown(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseDragged(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseUp(with:)"],"title":"Responding to Mouse Events"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"mouseExited:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":{"parameters":[{"name":"event","content":[{"inlineContent":[{"type":"text","text":"An object encapsulating information about the mouse-exited event."}],"type":"paragraph"}]}],"kind":"parameters"},"path":"/primaryContentSections/1"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1rightMouseUp(with:)/title","value":"rightMouseUp:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1rightMouseUp(with:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rightMouseUp:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title","value":"NSEvent","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments","value":[{"text":"NSEvent","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle","value":[{"kind":"identifier","text":"NSEvent"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseDragged(with:)/title","value":"mouseDragged:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseDragged(with:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"mouseDragged:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1otherMouseUp(with:)/title","value":"otherMouseUp:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1otherMouseUp(with:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"otherMouseUp:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1rightMouseDown(with:)/title","value":"rightMouseDown:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1rightMouseDown(with:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rightMouseDown:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1rightMouseDragged(with:)/title","value":"rightMouseDragged:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1rightMouseDragged(with:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"rightMouseDragged:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1otherMouseDown(with:)/title","value":"otherMouseDown:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1otherMouseDown(with:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"otherMouseDown:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1otherMouseDragged(with:)/title","value":"otherMouseDragged:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1otherMouseDragged(with:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"otherMouseDragged:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseExited(with:)/title","value":"mouseExited:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseExited(with:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mouseExited:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseMoved(with:)/title","value":"mouseMoved:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseMoved(with:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"mouseMoved:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/title","value":"NSResponder","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/fragments","value":[{"kind":"identifier","text":"NSResponder"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/navigatorTitle","value":[{"text":"NSResponder","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseEntered(with:)/title","value":"mouseEntered:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseEntered(with:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mouseEntered:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseUp(with:)/title","value":"mouseUp:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseUp(with:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"mouseUp:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseDown(with:)/title","value":"mouseDown:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseDown(with:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mouseDown:"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}