{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSResponder"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSResponder/restoreState(with:)"},"seeAlsoSections":[{"generated":true,"title":"Handling Window Restoration","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSResponder/allowedClasses(forRestorableStateKeyPath:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/encodeRestorableState(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/encodeRestorableState(with:backgroundQueue:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/restorableStateKeyPaths","doc://com.apple.appkit/documentation/AppKit/NSResponder/invalidateRestorableState()"],"anchor":"Handling-Window-Restoration"}],"abstract":[{"text":"Restores the interface-related state of the responder.","type":"text"}],"kind":"symbol","metadata":{"externalID":"c:objc(cs)NSResponder(im)restoreStateWithCoder:","symbolKind":"method","modules":[{"name":"AppKit"}],"roleHeading":"Instance Method","title":"restoreState(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"restoreState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"platforms":[{"name":"macOS","introducedAt":"10.7","deprecated":false,"beta":false,"unavailable":false}],"navigatorTitle":[{"kind":"identifier","text":"restoreStateWithCoder:"}],"role":"symbol","extendedModule":"AppKit"},"variants":[{"paths":["/documentation/appkit/nsresponder/restorestate(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsresponder/restorestate(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"restoreState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSCoder","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The coder object to use to restore the responder’s interface-related state.","type":"text"}]}],"name":"coder"}]},{"content":[{"text":"Discussion","level":2,"anchor":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"This method is part of the window restoration system and is called at launch time to restore the visual state of your responder object. The default implementation does nothing but specific subclasses (such as ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","type":"reference"},{"text":" and ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","type":"reference"},{"text":") override it and save important state information. Therefore, if you override this method, you should always call ","type":"text"},{"code":"super","type":"codeVoice"},{"text":" at some point in your implementation.","type":"text"}]},{"inlineContent":[{"type":"text","text":"Subclasses can override this method and use it to restore any information that was saved in the "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/encodeRestorableState(with:)","type":"reference","isActive":true},{"type":"text","text":" method. You can also use this method to reconfigure the responder to its previous appearance."}],"type":"paragraph"},{"name":"Note","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"If the user’s computer is configured to close all windows when an app quits, the system automatically removes any preserved state as part of that process. As a result, the system doesn’t call ","type":"text"},{"code":"restoreState(with:)","type":"codeVoice"},{"text":" the next time your app launches.","type":"text"}]}],"style":"note","type":"aside"},{"inlineContent":[{"text":"For information about using a coder object to read data from an archive, see ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"references":{"doc://com.apple.appkit/documentation/AppKit/NSResponder/restorableStateKeyPaths":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"restorableStateKeyPaths"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"restorableStateKeyPaths","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"url":"/documentation/appkit/nsresponder/restorablestatekeypaths","abstract":[{"text":"Returns an array of key paths representing the restorable attributes of the responder.","type":"text"}],"title":"restorableStateKeyPaths","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/restorableStateKeyPaths"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSResponder":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder","abstract":[{"text":"An abstract class that forms the basis of event and command processing in AppKit.","type":"text"}],"navigatorTitle":[{"text":"NSResponder","kind":"identifier"}],"url":"/documentation/appkit/nsresponder","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSResponder","kind":"identifier"}],"type":"topic","title":"NSResponder"},"doc://com.externally.resolved.symbol/c:objc(cs)NSCoder":{"type":"topic","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSCoder"}],"url":"/documentation/foundation/nscoder","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSCoder","role":"symbol","title":"NSCoder","kind":"symbol","abstract":[{"type":"text","text":"An abstract class that serves as the basis for objects that enable archiving and distribution of other objects."}]},"doc://com.apple.appkit/documentation/AppKit/NSResponder/invalidateRestorableState()":{"title":"invalidateRestorableState()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"invalidateRestorableState"}],"type":"topic","url":"/documentation/appkit/nsresponder/invalidaterestorablestate()","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/invalidateRestorableState()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidateRestorableState"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Marks the responder’s interface-related state as dirty."}]},"doc://com.apple.appkit/documentation/AppKit/NSResponder/allowedClasses(forRestorableStateKeyPath:)":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"allowedClassesForRestorableStateKeyPath:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowedClasses"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forRestorableStateKeyPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"s:s8AnyClassa","text":"AnyClass","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"/documentation/appkit/nsresponder/allowedclasses(forrestorablestatekeypath:)","abstract":[{"type":"text","text":"Returns the classes that support secure coding."}],"title":"allowedClasses(forRestorableStateKeyPath:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/allowedClasses(forRestorableStateKeyPath:)"},"doc://com.apple.documentation/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types":{"abstract":[{"type":"text","text":"Make your data types encodable and decodable for compatibility with external representations such as JSON."}],"type":"topic","title":"Encoding and Decoding Custom Types","kind":"article","identifier":"doc://com.apple.documentation/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types","role":"article","url":"/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/encodeRestorableState(with:)":{"type":"topic","url":"/documentation/appkit/nsresponder/encoderestorablestate(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeRestorableState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/encodeRestorableState(with:)","abstract":[{"text":"Saves the interface-related state of the responder.","type":"text"}],"kind":"symbol","title":"encodeRestorableState(with:)","navigatorTitle":[{"kind":"identifier","text":"encodeRestorableStateWithCoder:"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/restoreState(with:)":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"restoreStateWithCoder:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"restoreState","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"kind":"text","text":")"}],"url":"/documentation/appkit/nsresponder/restorestate(with:)","abstract":[{"text":"Restores the interface-related state of the responder.","type":"text"}],"title":"restoreState(with:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/restoreState(with:)"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSView":{"abstract":[{"text":"The infrastructure for drawing, printing, and handling events in an app.","type":"text"}],"url":"/documentation/appkit/nsview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSView"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","title":"NSView","navigatorTitle":[{"kind":"identifier","text":"NSView"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/encodeRestorableState(with:backgroundQueue:)":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"encodeRestorableStateWithCoder:backgroundQueue:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"encodeRestorableState","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"kind":"text","text":", "},{"kind":"externalParam","text":"backgroundQueue"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSOperationQueue","text":"OperationQueue","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/appkit/nsresponder/encoderestorablestate(with:backgroundqueue:)","abstract":[{"text":"Saves the interface-related state of the responder to a keyed archiver either synchronously or asynchronously on the given operation queue.","type":"text"}],"title":"encodeRestorableState(with:backgroundQueue:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/encodeRestorableState(with:backgroundQueue:)"},"doc://com.apple.appkit/documentation/AppKit/NSWindow":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSWindow"}],"url":"/documentation/appkit/nswindow","title":"NSWindow","identifier":"doc://com.apple.appkit/documentation/AppKit/NSWindow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSWindow"}],"abstract":[{"type":"text","text":"A window that an app displays on the screen."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"beta":false,"name":"macOS","introducedAt":"10.7","unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"restoreStateWithCoder:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"restoreStateWithCoder:"}],"path":"/metadata/fragments","op":"replace"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSResponder"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSResponder/allowedClasses(forRestorableStateKeyPath:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/encodeRestorableState(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/encodeRestorableState(with:backgroundQueue:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/restorableStateKeyPaths","doc://com.apple.appkit/documentation/AppKit/NSResponder/invalidateRestorableState()"],"generated":true,"anchor":"Handling-Window-Restoration","title":"Handling Window Restoration"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"restoreStateWithCoder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSCoder","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"coder"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","op":"replace","value":{"parameters":[{"name":"coder","content":[{"inlineContent":[{"type":"text","text":"The coder object to use to restore the responder’s interface-related state."}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","value":"restorableStateKeyPaths","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1restorableStateKeyPaths/title"},{"op":"replace","value":[{"kind":"identifier","text":"restorableStateKeyPaths"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1restorableStateKeyPaths/fragments"},{"op":"replace","value":"NSResponder","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/title"},{"op":"replace","value":[{"text":"NSResponder","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSResponder"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/navigatorTitle"},{"op":"replace","value":"invalidateRestorableState","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1invalidateRestorableState()/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"invalidateRestorableState","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1invalidateRestorableState()/fragments"},{"op":"replace","value":"allowedClassesForRestorableStateKeyPath:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1allowedClasses(forRestorableStateKeyPath:)/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"allowedClassesForRestorableStateKeyPath:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1allowedClasses(forRestorableStateKeyPath:)/fragments"},{"op":"replace","value":"encodeRestorableStateWithCoder:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1encodeRestorableState(with:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"encodeRestorableStateWithCoder:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1encodeRestorableState(with:)/fragments"},{"op":"replace","value":"restoreStateWithCoder:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1restoreState(with:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"restoreStateWithCoder:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1restoreState(with:)/fragments"},{"op":"replace","value":"NSView","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSView"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments"},{"op":"replace","value":[{"text":"NSView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle"},{"op":"replace","value":"encodeRestorableStateWithCoder:backgroundQueue:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1encodeRestorableState(with:backgroundQueue:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"encodeRestorableStateWithCoder:backgroundQueue:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1encodeRestorableState(with:backgroundQueue:)/fragments"},{"op":"replace","value":"NSWindow","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/title"},{"op":"replace","value":[{"text":"NSWindow","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSWindow"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}