{"variants":[{"paths":["/documentation/appkit/nsresponder/rightmouseup(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsresponder/rightmouseup(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","seeAlsoSections":[{"title":"Responding to Mouse Events","anchor":"Responding-to-Mouse-Events","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseDown(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseDragged(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseUp(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseMoved(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseEntered(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseExited(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseDown(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseDragged(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseDown(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseDragged(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseUp(with:)"],"generated":true}],"metadata":{"platforms":[{"unavailable":false,"deprecated":false,"name":"macOS","beta":false}],"modules":[{"name":"AppKit"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:objc(cs)NSResponder(im)rightMouseUp:","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightMouseUp","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent"},{"kind":"text","text":")"}],"title":"rightMouseUp(with:)","navigatorTitle":[{"kind":"identifier","text":"rightMouseUp:"}]},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseUp(with:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSResponder"]]},"sections":[],"abstract":[{"text":"Informs the receiver that the user has released the right mouse button.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightMouseUp"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"event","content":[{"inlineContent":[{"type":"text","text":"An object encapsulating information about the mouse-up event."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"The default implementation simply passes this message to the next responder.","type":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseExited(with:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseExited","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":")","kind":"text"}],"url":"/documentation/appkit/nsresponder/mouseexited(with:)","title":"mouseExited(with:)","abstract":[{"text":"Informs the receiver that the cursor has exited a tracking rectangle.","type":"text"}],"navigatorTitle":[{"text":"mouseExited:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseExited(with:)","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseDown(with:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseDown","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseDown(with:)","abstract":[{"text":"Informs the receiver that the user has pressed the left mouse button.","type":"text"}],"type":"topic","title":"mouseDown(with:)","kind":"symbol","navigatorTitle":[{"text":"mouseDown:","kind":"identifier"}],"url":"/documentation/appkit/nsresponder/mousedown(with:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSEvent":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSEvent"}],"role":"symbol","type":"topic","title":"NSEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSEvent"}],"abstract":[{"type":"text","text":"An object that contains information about an input action, such as a mouse click or a key press."}],"url":"/documentation/appkit/nsevent"},"doc://com.apple.appkit/documentation/AppKit/NSResponder":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder","abstract":[{"text":"An abstract class that forms the basis of event and command processing in AppKit.","type":"text"}],"navigatorTitle":[{"text":"NSResponder","kind":"identifier"}],"url":"/documentation/appkit/nsresponder","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSResponder","kind":"identifier"}],"type":"topic","title":"NSResponder"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseUp(with:)":{"role":"symbol","url":"/documentation/appkit/nsresponder/mouseup(with:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseUp(with:)","title":"mouseUp(with:)","abstract":[{"text":"Informs the receiver that the user has released the left mouse button.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"mouseUp:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseUp","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":")","kind":"text"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseDown(with:)":{"role":"symbol","url":"/documentation/appkit/nsresponder/rightmousedown(with:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseDown(with:)","title":"rightMouseDown(with:)","abstract":[{"text":"Informs the receiver that the user has pressed the right mouse button.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"rightMouseDown:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightMouseDown","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":")","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseDragged(with:)":{"url":"/documentation/appkit/nsresponder/othermousedragged(with:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"otherMouseDragged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent"},{"kind":"text","text":")"}],"title":"otherMouseDragged(with:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseDragged(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"otherMouseDragged:"}],"abstract":[{"text":"Informs the receiver that the user has moved the mouse with a button other than the left or right button pressed.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseEntered(with:)":{"abstract":[{"text":"Informs the receiver that the cursor has entered a tracking rectangle.","type":"text"}],"navigatorTitle":[{"text":"mouseEntered:","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseEntered(with:)","url":"/documentation/appkit/nsresponder/mouseentered(with:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseEntered","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"mouseEntered(with:)"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseMoved(with:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseMoved(with:)","role":"symbol","type":"topic","url":"/documentation/appkit/nsresponder/mousemoved(with:)","navigatorTitle":[{"text":"mouseMoved:","kind":"identifier"}],"abstract":[{"text":"Informs the receiver that the mouse has moved.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseMoved","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"mouseMoved(with:)","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseUp(with:)":{"role":"symbol","type":"topic","title":"rightMouseUp(with:)","url":"/documentation/appkit/nsresponder/rightmouseup(with:)","navigatorTitle":[{"kind":"identifier","text":"rightMouseUp:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseUp(with:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightMouseUp"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSEvent","kind":"typeIdentifier","text":"NSEvent"},{"kind":"text","text":")"}],"abstract":[{"text":"Informs the receiver that the user has released the right mouse button.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseUp(with:)":{"role":"symbol","type":"topic","title":"otherMouseUp(with:)","url":"/documentation/appkit/nsresponder/othermouseup(with:)","navigatorTitle":[{"kind":"identifier","text":"otherMouseUp:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseUp(with:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"otherMouseUp"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent"},{"kind":"text","text":")"}],"abstract":[{"text":"Informs the receiver that the user has released a mouse button other than the left or right button.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseDragged(with:)":{"title":"mouseDragged(with:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseDragged(with:)","url":"/documentation/appkit/nsresponder/mousedragged(with:)","navigatorTitle":[{"kind":"identifier","text":"mouseDragged:"}],"abstract":[{"text":"Informs the receiver that the user has moved the mouse with the left button pressed.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mouseDragged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent"},{"kind":"text","text":")"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseDown(with:)":{"title":"otherMouseDown(with:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseDown(with:)","url":"/documentation/appkit/nsresponder/othermousedown(with:)","navigatorTitle":[{"text":"otherMouseDown:","kind":"identifier"}],"abstract":[{"text":"Informs the receiver that the user has pressed a mouse button other than the left or right one.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"otherMouseDown","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseDragged(with:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseDragged(with:)","navigatorTitle":[{"kind":"identifier","text":"rightMouseDragged:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightMouseDragged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSEvent","kind":"typeIdentifier","text":"NSEvent"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"text":"Informs the receiver that the user has moved the mouse with the right button pressed.","type":"text"}],"type":"topic","title":"rightMouseDragged(with:)","role":"symbol","url":"/documentation/appkit/nsresponder/rightmousedragged(with:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"macOS","unavailable":false,"deprecated":false,"beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"rightMouseUp:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rightMouseUp:"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSResponder"]]},"path":"/hierarchy","op":"replace"},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"anchor":"Responding-to-Mouse-Events","title":"Responding to Mouse Events","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseDown(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseDragged(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseUp(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseMoved(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseEntered(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/mouseExited(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseDown(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/rightMouseDragged(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseDown(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseDragged(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/otherMouseUp(with:)"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"rightMouseUp:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"event"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":{"parameters":[{"name":"event","content":[{"inlineContent":[{"type":"text","text":"An object encapsulating information about the mouse-up event."}],"type":"paragraph"}]}],"kind":"parameters"},"path":"/primaryContentSections/1"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseExited(with:)/title","op":"replace","value":"mouseExited:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseExited(with:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mouseExited:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseDown(with:)/title","op":"replace","value":"mouseDown:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseDown(with:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"mouseDown:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title","op":"replace","value":"NSEvent"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments","op":"replace","value":[{"kind":"identifier","text":"NSEvent"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSEvent"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/title","op":"replace","value":"NSResponder"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/fragments","op":"replace","value":[{"text":"NSResponder","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/navigatorTitle","op":"replace","value":[{"text":"NSResponder","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseUp(with:)/title","op":"replace","value":"mouseUp:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseUp(with:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mouseUp:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1rightMouseDown(with:)/title","op":"replace","value":"rightMouseDown:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1rightMouseDown(with:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"rightMouseDown:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1otherMouseDragged(with:)/title","value":"otherMouseDragged:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1otherMouseDragged(with:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"otherMouseDragged:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseEntered(with:)/title","value":"mouseEntered:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseEntered(with:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"mouseEntered:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseMoved(with:)/title","value":"mouseMoved:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseMoved(with:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mouseMoved:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1rightMouseUp(with:)/title","op":"replace","value":"rightMouseUp:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1rightMouseUp(with:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rightMouseUp:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1otherMouseUp(with:)/title","op":"replace","value":"otherMouseUp:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1otherMouseUp(with:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"otherMouseUp:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseDragged(with:)/title","op":"replace","value":"mouseDragged:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1mouseDragged(with:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mouseDragged:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1otherMouseDown(with:)/title","op":"replace","value":"otherMouseDown:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1otherMouseDown(with:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"otherMouseDown:"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1rightMouseDragged(with:)/title","op":"replace","value":"rightMouseDragged:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1rightMouseDragged(with:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rightMouseDragged:"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}