{"sections":[],"abstract":[{"text":"Finds a target for an action method.","type":"text"}],"metadata":{"platforms":[{"name":"macOS","introducedAt":"10.7","deprecated":false,"unavailable":false,"beta":false}],"modules":[{"name":"AppKit"}],"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supplementalTarget","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forAction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Selector","kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"text":", ","kind":"text"},{"text":"sender","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"supplementalTargetForAction:sender:"}],"externalID":"c:objc(cs)NSResponder(im)supplementalTargetForAction:sender:","role":"symbol","title":"supplementalTarget(forAction:sender:)"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding","doc://com.apple.appkit/documentation/AppKit/action-messages"],"anchor":"Responding-to-Action-Messages","title":"Responding to Action Messages","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSResponder/supplementalTarget(forAction:sender:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supplementalTarget","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forAction","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"action","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Selector","identifier":"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV","preciseIdentifier":"s:10ObjectiveC8SelectorV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sender","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"},{"parameters":[{"name":"action","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The requested action."}]}]},{"name":"sender","content":[{"inlineContent":[{"text":"The message sender.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"An object which responds to the action, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"anchor":"Discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"text":"If this ","type":"text"},{"type":"codeVoice","code":"NSResponder"},{"text":" instance does not itself ","type":"text"},{"type":"codeVoice","code":"respondsToSelector:"},{"text":", then ","type":"text"},{"type":"codeVoice","code":"supplementalTargetForAction:sender:"},{"text":" is called.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"This method should return an object which responds to the action; if this responder does not have a supplemental object that does that, the implementation of this method should call ","type":"text"},{"type":"codeVoice","code":"super"},{"text":"’s ","type":"text"},{"type":"codeVoice","code":"supplementalTargetForAction:sender:"},{"text":".","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"NSResponder’s implementation returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}]}],"variants":[{"paths":["/documentation/appkit/nsresponder/supplementaltarget(foraction:sender:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsresponder/supplementaltarget(foraction:sender:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSResponder"]]},"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSResponder":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder","abstract":[{"text":"An abstract class that forms the basis of event and command processing in AppKit.","type":"text"}],"navigatorTitle":[{"text":"NSResponder","kind":"identifier"}],"url":"/documentation/appkit/nsresponder","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSResponder","kind":"identifier"}],"type":"topic","title":"NSResponder"},"doc://com.externally.resolved.symbol/c:@T@SEL":{"identifier":"doc://com.externally.resolved.symbol/c:@T@SEL","type":"topic","abstract":[{"type":"text","text":"Defines an opaque type that represents a method selector."}],"url":"/documentation/objectivec/sel","title":"SEL","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding","abstract":[{"text":"Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSStandardKeyBindingResponding","kind":"identifier"}],"title":"NSStandardKeyBindingResponding","kind":"symbol","url":"/documentation/appkit/nsstandardkeybindingresponding","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/action-messages":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/action-messages","url":"/documentation/appkit/action-messages","kind":"article","role":"collectionGroup","title":"Action Messages","abstract":[{"type":"text","text":"Implement action messages in your first responders to handle common tasks."}]},"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV":{"type":"topic","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"Selector"}],"url":"/documentation/objectivec/selector","title":"Selector","abstract":[{"type":"text","text":""}],"identifier":"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/supplementalTarget(forAction:sender:)":{"title":"supplementalTarget(forAction:sender:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"supplementalTargetForAction:sender:"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/supplementalTarget(forAction:sender:)","url":"/documentation/appkit/nsresponder/supplementaltarget(foraction:sender:)","abstract":[{"type":"text","text":"Finds a target for an action method."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"supplementalTarget"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"beta":false,"deprecated":false,"introducedAt":"10.7","name":"macOS","unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"supplementalTargetForAction:sender:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"supplementalTargetForAction:sender:"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSResponder"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSStandardKeyBindingResponding","doc://com.apple.appkit/documentation/AppKit/action-messages"],"anchor":"Responding-to-Action-Messages","title":"Responding to Action Messages","generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"supplementalTargetForAction:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@SEL","text":"SEL","identifier":"doc://com.externally.resolved.symbol/c:@T@SEL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"action"},{"kind":"text","text":" "},{"kind":"identifier","text":"sender:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}],"kind":"declarations"}},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The requested action."}]}],"name":"action"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The message sender."}]}],"name":"sender"}]},"path":"/primaryContentSections/1"},{"path":"/primaryContentSections/2","op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"An object which responds to the action, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}]}]}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/title","op":"replace","value":"NSResponder"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/fragments","op":"replace","value":[{"text":"NSResponder","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/navigatorTitle","op":"replace","value":[{"text":"NSResponder","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/title","op":"replace","value":"NSStandardKeyBindingResponding"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/fragments","op":"replace","value":[{"kind":"identifier","text":"NSStandardKeyBindingResponding"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSStandardKeyBindingResponding/navigatorTitle","op":"replace","value":[{"text":"NSStandardKeyBindingResponding","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1supplementalTarget(forAction:sender:)/title","op":"replace","value":"supplementalTargetForAction:sender:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1supplementalTarget(forAction:sender:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"supplementalTargetForAction:sender:","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}