{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSResponder"]]},"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSResponder/cursorUpdate(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/flagsChanged(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletProximity(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/helpRequested(_:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/scrollWheel(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/quickLook(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/changeMode(with:)"],"generated":true,"title":"Responding to Other Kinds of Events","anchor":"Responding-to-Other-Kinds-of-Events"}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletPoint(with:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nsresponder/tabletpoint(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nsresponder/tabletpoint(with:)"]}],"abstract":[{"text":"Informs the receiver that a tablet-point event has occurred.","type":"text"}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","externalID":"c:objc(cs)NSResponder(im)tabletPoint:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabletPoint"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSEvent","kind":"typeIdentifier","text":"NSEvent"},{"kind":"text","text":")"}],"platforms":[{"unavailable":false,"deprecated":false,"name":"macOS","beta":false}],"navigatorTitle":[{"kind":"identifier","text":"tabletPoint:"}],"title":"tabletPoint(with:)","modules":[{"name":"AppKit"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tabletPoint","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"event","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent"},{"kind":"text","text":")"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"event","content":[{"inlineContent":[{"type":"text","text":"An object encapsulating information about the tablet-point event."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Tablet events are represented by "},{"type":"codeVoice","code":"NSEvent"},{"type":"text","text":" objects of type "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSTabletPoint","isActive":true},{"type":"text","text":". They describe the current state of a transducer (that is, a pointing device) that is in proximity to its tablet, reflecting changes such as location, pressure, tilt, and rotation. See the "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","isActive":true},{"type":"text","text":" reference for the methods that allow you to extract this and other information from "},{"type":"codeVoice","code":"event"},{"type":"text","text":". The default implementation of "},{"type":"codeVoice","code":"NSResponder"},{"type":"text","text":" passes the message to the next responder."}]}],"kind":"content"}],"sections":[],"kind":"symbol","references":{"doc://com.apple.appkit/documentation/AppKit/NSResponder/cursorUpdate(with:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/cursorUpdate(with:)","role":"symbol","type":"topic","url":"/documentation/appkit/nsresponder/cursorupdate(with:)","navigatorTitle":[{"text":"cursorUpdate:","kind":"identifier"}],"abstract":[{"text":"Informs the receiver that the mouse cursor has moved into a cursor rectangle.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cursorUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"cursorUpdate(with:)","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/scrollWheel(with:)":{"role":"symbol","url":"/documentation/appkit/nsresponder/scrollwheel(with:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/scrollWheel(with:)","title":"scrollWheel(with:)","abstract":[{"text":"Informs the receiver that the mouse’s scroll wheel has moved.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"scrollWheel:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollWheel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":")","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSResponder/flagsChanged(with:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"flagsChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":")","kind":"text"}],"url":"/documentation/appkit/nsresponder/flagschanged(with:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"flagsChanged:","kind":"identifier"}],"title":"flagsChanged(with:)","abstract":[{"text":"Informs the receiver that the user has pressed or released a modifier key (Shift, Control, and so on).","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/flagsChanged(with:)"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/changeMode(with:)":{"role":"symbol","url":"/documentation/appkit/nsresponder/changemode(with:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/changeMode(with:)","title":"changeMode(with:)","abstract":[{"type":"text","text":"Informs the responder that performed a double-tap on the side of an Apple Pencil."}],"type":"topic","navigatorTitle":[{"text":"changeModeWithEvent:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"changeMode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSResponder/quickLook(with:)":{"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/quickLook(with:)","url":"/documentation/appkit/nsresponder/quicklook(with:)","abstract":[{"type":"text","text":"Performs a Quick Look on the content at the location specified by the supplied event."}],"kind":"symbol","title":"quickLook(with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"quickLook","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"quickLookWithEvent:","kind":"identifier"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletPoint(with:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tabletPoint:"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletPoint(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tabletPoint"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent"},{"kind":"text","text":")"}],"kind":"symbol","url":"/documentation/appkit/nsresponder/tabletpoint(with:)","abstract":[{"text":"Informs the receiver that a tablet-point event has occurred.","type":"text"}],"title":"tabletPoint(with:)"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/helpRequested(_:)":{"role":"symbol","type":"topic","title":"helpRequested(_:)","url":"/documentation/appkit/nsresponder/helprequested(_:)","navigatorTitle":[{"text":"helpRequested:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/helpRequested(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpRequested","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":")","kind":"text"}],"abstract":[{"text":"Displays context-sensitive help for the receiver if help has been registered.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSTabletPoint":{"kind":"symbol","url":"/documentation/appkit/nstabletpoint","abstract":[{"text":"An event representing the current state of a tablet pointing device, including its location, pressure, and tilt.","type":"text"}],"type":"topic","title":"NSTabletPoint","role":"symbol","fragments":[{"kind":"identifier","text":"NSTabletPoint"}],"deprecated":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSTabletPoint"},"doc://com.apple.appkit/documentation/AppKit/NSEvent":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSEvent"}],"role":"symbol","type":"topic","title":"NSEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSEvent"}],"abstract":[{"type":"text","text":"An object that contains information about an input action, such as a mouse click or a key press."}],"url":"/documentation/appkit/nsevent"},"doc://com.apple.appkit/documentation/AppKit/NSResponder":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder","abstract":[{"text":"An abstract class that forms the basis of event and command processing in AppKit.","type":"text"}],"navigatorTitle":[{"text":"NSResponder","kind":"identifier"}],"url":"/documentation/appkit/nsresponder","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSResponder","kind":"identifier"}],"type":"topic","title":"NSResponder"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletProximity(with:)":{"type":"topic","role":"symbol","title":"tabletProximity(with:)","url":"/documentation/appkit/nsresponder/tabletproximity(with:)","navigatorTitle":[{"text":"tabletProximity:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletProximity(with:)","kind":"symbol","abstract":[{"type":"text","text":"Informs the receiver that a tablet-proximity event has occurred."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tabletProximity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSEvent","text":"NSEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"beta":false,"name":"macOS","unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"tabletPoint:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"tabletPoint:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSResponder"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"anchor":"Responding-to-Other-Kinds-of-Events","title":"Responding to Other Kinds of Events","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSResponder/cursorUpdate(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/flagsChanged(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/tabletProximity(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/helpRequested(_:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/scrollWheel(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/quickLook(with:)","doc://com.apple.appkit/documentation/AppKit/NSResponder/changeMode(with:)"],"generated":true}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"tabletPoint:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSEvent","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"event"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}]},"op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"event","content":[{"inlineContent":[{"type":"text","text":"An object encapsulating information about the tablet-point event."}],"type":"paragraph"}]}]},"path":"/primaryContentSections/1"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1cursorUpdate(with:)/title","value":"cursorUpdate:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1cursorUpdate(with:)/fragments","value":[{"kind":"text","text":"- "},{"text":"cursorUpdate:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1scrollWheel(with:)/title","value":"scrollWheel:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1scrollWheel(with:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scrollWheel:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1flagsChanged(with:)/title","value":"flagsChanged:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1flagsChanged(with:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"flagsChanged:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1changeMode(with:)/title","value":"changeModeWithEvent:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1changeMode(with:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeModeWithEvent:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1quickLook(with:)/title","value":"quickLookWithEvent:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"quickLookWithEvent:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1quickLook(with:)/fragments"},{"op":"replace","value":"tabletPoint:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1tabletPoint(with:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tabletPoint:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1tabletPoint(with:)/fragments"},{"op":"replace","value":"helpRequested:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1helpRequested(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"helpRequested:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1helpRequested(_:)/fragments"},{"op":"replace","value":"NSEvent","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSEvent"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSEvent"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle"},{"op":"replace","value":"NSResponder","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSResponder"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/fragments"},{"op":"replace","value":[{"text":"NSResponder","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder/navigatorTitle"},{"op":"replace","value":"tabletProximity:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1tabletProximity(with:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tabletProximity:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSResponder~1tabletProximity(with:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}