{
  "abstract": [
    {
      "text": "A standard play/pause button.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI",
        "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionMediaPlayPauseButtonType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionMediaPlayPauseButtonType/default"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UNNotificationContentExtensionMediaPlayPauseButtonType@UNNotificationContentExtensionMediaPlayPauseButtonTypeDefault",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "`default`"
      }
    ],
    "modules": [
      {
        "name": "User Notifications UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UNNotificationContentExtensionMediaPlayPauseButtonTypeDefault"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UNNotificationContentExtensionMediaPlayPauseButtonType.default"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "`default`"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This button is always visible. When tapped, its appearance changes",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "between the play and pause icons and triggers the appropriate play and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "pause actions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI": {
      "abstract": [
        {
          "text": "Customize the interface that displays local and remote notifications.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI",
      "kind": "symbol",
      "role": "collection",
      "title": "User Notifications UI",
      "type": "topic",
      "url": "/documentation/usernotificationsui"
    },
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionMediaPlayPauseButtonType": {
      "abstract": [
        {
          "text": "Constants indicating the type of media button to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNNotificationContentExtensionMediaPlayPauseButtonType"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionMediaPlayPauseButtonType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationContentExtensionMediaPlayPauseButtonType"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationContentExtensionMediaPlayPauseButtonType",
      "type": "topic",
      "url": "/documentation/usernotificationsui/unnotificationcontentextensionmediaplaypausebuttontype"
    },
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionMediaPlayPauseButtonType/default": {
      "abstract": [
        {
          "text": "A standard play/pause button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionMediaPlayPauseButtonType/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationContentExtensionMediaPlayPauseButtonTypeDefault"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationContentExtensionMediaPlayPauseButtonType.default",
      "type": "topic",
      "url": "/documentation/usernotificationsui/unnotificationcontentextensionmediaplaypausebuttontype/default"
    },
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionMediaPlayPauseButtonType/none": {
      "abstract": [
        {
          "text": "No media button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionMediaPlayPauseButtonType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationContentExtensionMediaPlayPauseButtonTypeNone"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationContentExtensionMediaPlayPauseButtonType.none",
      "type": "topic",
      "url": "/documentation/usernotificationsui/unnotificationcontentextensionmediaplaypausebuttontype/none"
    },
    "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionMediaPlayPauseButtonType/overlay": {
      "abstract": [
        {
          "text": "A partially transparent play/pause button that is layered on top of your",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "media content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overlay"
        }
      ],
      "identifier": "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionMediaPlayPauseButtonType/overlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNNotificationContentExtensionMediaPlayPauseButtonTypeOverlay"
        }
      ],
      "role": "symbol",
      "title": "UNNotificationContentExtensionMediaPlayPauseButtonType.overlay",
      "type": "topic",
      "url": "/documentation/usernotificationsui/unnotificationcontentextensionmediaplaypausebuttontype/overlay"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Button-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionMediaPlayPauseButtonType/none",
        "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionMediaPlayPauseButtonType/overlay"
      ],
      "title": "Button Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UNNotificationContentExtensionMediaPlayPauseButtonTypeDefault"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContentExtensionMediaPlayPauseButtonTypeDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI",
                "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionMediaPlayPauseButtonType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Button-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionMediaPlayPauseButtonType/none",
                "doc://com.apple.User-Notifications-UI/documentation/UserNotificationsUI/UNNotificationContentExtensionMediaPlayPauseButtonType/overlay"
              ],
              "title": "Button Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UNNotificationContentExtensionMediaPlayPauseButtonTypeDefault"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtensionMediaPlayPauseButtonType~1none/title",
          "value": "UNNotificationContentExtensionMediaPlayPauseButtonTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtensionMediaPlayPauseButtonType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContentExtensionMediaPlayPauseButtonTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtensionMediaPlayPauseButtonType~1overlay/title",
          "value": "UNNotificationContentExtensionMediaPlayPauseButtonTypeOverlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtensionMediaPlayPauseButtonType~1overlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContentExtensionMediaPlayPauseButtonTypeOverlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtensionMediaPlayPauseButtonType~1default/title",
          "value": "UNNotificationContentExtensionMediaPlayPauseButtonTypeDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtensionMediaPlayPauseButtonType~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContentExtensionMediaPlayPauseButtonTypeDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtensionMediaPlayPauseButtonType/title",
          "value": "UNNotificationContentExtensionMediaPlayPauseButtonType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtensionMediaPlayPauseButtonType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContentExtensionMediaPlayPauseButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.User-Notifications-UI~1documentation~1UserNotificationsUI~1UNNotificationContentExtensionMediaPlayPauseButtonType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNNotificationContentExtensionMediaPlayPauseButtonType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/usernotificationsui/unnotificationcontentextensionmediaplaypausebuttontype/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/usernotificationsui/unnotificationcontentextensionmediaplaypausebuttontype/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
