{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessory/AccessoryState"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessory",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessory/AccessoryState"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessoryEvent",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessory",
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessory/AccessoryState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessory/AccessoryState/RawRepresentable-Implementations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AccessorySetupKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "RawRepresentable Implementations"
  },
  "references": {
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit": {
      "abstract": [
        {
          "text": "Enable privacy-preserving discovery and configuration of accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AccessorySetupKit",
      "type": "topic",
      "url": "/documentation/accessorysetupkit"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessory": {
      "abstract": [
        {
          "text": "An accessory discovered by the accessory session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAccessory"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAccessory"
        }
      ],
      "role": "symbol",
      "title": "ASAccessory",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asaccessory"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessory/AccessoryState": {
      "abstract": [
        {
          "text": "An enumeration of possible authorization states of an accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccessoryState"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessory/AccessoryState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccessoryState"
        }
      ],
      "role": "symbol",
      "title": "ASAccessory.AccessoryState",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asaccessory/accessorystate"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessory/AccessoryState/hash(into:)": {
      "abstract": [],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Self",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "Hashable",
            "type": "codeVoice"
          },
          {
            "text": " and ",
            "type": "text"
          },
          {
            "code": "RawValue",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "Hashable",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hash"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "into"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6HasherV",
          "text": "Hasher"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessory/AccessoryState/hash(into:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "hash(into:)",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asaccessory/accessorystate/hash(into:)"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessory/AccessoryState/hashValue": {
      "abstract": [],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Self",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "Hashable",
            "type": "codeVoice"
          },
          {
            "text": " and ",
            "type": "text"
          },
          {
            "code": "RawValue",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "Hashable",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hashValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessory/AccessoryState/hashValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "hashValue",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asaccessory/accessorystate/hashvalue"
    },
    "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessoryEvent": {
      "abstract": [
        {
          "text": "Properties of an event encountered during accessory discovery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAccessoryEvent"
        }
      ],
      "identifier": "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessoryEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAccessoryEvent"
        }
      ],
      "role": "symbol",
      "title": "ASAccessoryEvent",
      "type": "topic",
      "url": "/documentation/accessorysetupkit/asaccessoryevent"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessory/AccessoryState/hashValue"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.AccessorySetupKit/documentation/AccessorySetupKit/ASAccessory/AccessoryState/hash(into:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASAccessoryEvent/title",
          "value": "ASAccessoryEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASAccessoryEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAccessoryEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASAccessoryEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAccessoryEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASAccessory/title",
          "value": "ASAccessory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASAccessory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASAccessory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASAccessory~1AccessoryState/title",
          "value": "ASAccessoryState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASAccessory~1AccessoryState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAccessoryState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AccessorySetupKit~1documentation~1AccessorySetupKit~1ASAccessory~1AccessoryState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAccessoryState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accessorysetupkit/asaccessory/accessorystate/rawrepresentable-implementations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
