{
  "abstract": [
    {
      "text": "No scaling occurs. Use ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/overscanCompensationInsets",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " to get the insets required to avoid clipping.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum/none"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIScreenOverscanCompensation@UIScreenOverscanCompensationNone",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "none"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIScreenOverscanCompensationNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIScreen.OverscanCompensation.none"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "none"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen": {
      "abstract": [
        {
          "text": "An object that defines the properties associated with a hardware-based display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIScreen"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreen"
        }
      ],
      "role": "symbol",
      "title": "UIScreen",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum": {
      "abstract": [
        {
          "text": "Describes different techniques for compensating for pixel loss at the edge of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OverscanCompensation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OverscanCompensation"
        }
      ],
      "role": "symbol",
      "title": "UIScreen.OverscanCompensation",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/overscancompensation-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum/insetApplicationFrame": {
      "abstract": [
        {
          "text": "The application frame is reduced in size to compensate for overscan. Content drawn outside the application frame may be clipped.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insetApplicationFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScreen",
          "text": "UIScreen"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIScreenOverscanCompensation",
          "text": "OverscanCompensation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum/insetApplicationFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreenOverscanCompensationInsetApplicationFrame"
        }
      ],
      "role": "symbol",
      "title": "insetApplicationFrame",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/overscancompensation-swift.enum/insetapplicationframe"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum/insetBounds": {
      "abstract": [
        {
          "text": "The screen bounds are reduced in size so that all pixels in the framebuffer are visible on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insetBounds"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum/insetBounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreenOverscanCompensationInsetBounds"
        }
      ],
      "role": "symbol",
      "title": "UIScreen.OverscanCompensation.insetBounds",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/overscancompensation-swift.enum/insetbounds"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum/none": {
      "abstract": [
        {
          "text": "No scaling occurs. Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/overscanCompensationInsets",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to get the insets required to avoid clipping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreenOverscanCompensationNone"
        }
      ],
      "role": "symbol",
      "title": "UIScreen.OverscanCompensation.none",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/overscancompensation-swift.enum/none"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum/scale": {
      "abstract": [
        {
          "text": "The final composited framebuffer for the screen is scaled so that all pixels lie in the area visible on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scale"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum/scale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreenOverscanCompensationScale"
        }
      ],
      "role": "symbol",
      "title": "UIScreen.OverscanCompensation.scale",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/overscancompensation-swift.enum/scale"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/overscanCompensationInsets": {
      "abstract": [
        {
          "text": "The edge inset values needed to avoid clipping the rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overscanCompensationInsets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIEdgeInsets",
          "text": "UIEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/overscanCompensationInsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "overscanCompensationInsets"
        }
      ],
      "role": "symbol",
      "title": "overscanCompensationInsets",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/overscancompensationinsets"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum/scale",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum/insetBounds",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum/insetApplicationFrame"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIScreenOverscanCompensationNone"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenOverscanCompensationNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum/scale",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum/insetBounds",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum/insetApplicationFrame"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIScreenOverscanCompensationNone"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1overscanCompensationInsets/title",
          "value": "overscanCompensationInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1overscanCompensationInsets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "overscanCompensationInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1OverscanCompensation-swift.enum~1none/title",
          "value": "UIScreenOverscanCompensationNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1OverscanCompensation-swift.enum~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenOverscanCompensationNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1OverscanCompensation-swift.enum~1insetBounds/title",
          "value": "UIScreenOverscanCompensationInsetBounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1OverscanCompensation-swift.enum~1insetBounds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenOverscanCompensationInsetBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1OverscanCompensation-swift.enum~1scale/title",
          "value": "UIScreenOverscanCompensationScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1OverscanCompensation-swift.enum~1scale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenOverscanCompensationScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1OverscanCompensation-swift.enum/title",
          "value": "UIScreenOverscanCompensation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1OverscanCompensation-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenOverscanCompensation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1OverscanCompensation-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenOverscanCompensation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1OverscanCompensation-swift.enum~1insetApplicationFrame/title",
          "value": "UIScreenOverscanCompensationInsetApplicationFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1OverscanCompensation-swift.enum~1insetApplicationFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenOverscanCompensationInsetApplicationFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen/title",
          "value": "UIScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreen"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiscreen/overscancompensation-swift.enum/none"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiscreen/overscancompensation-swift.enum/none"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
