{
  "abstract": [
    {
      "text": "A signpost that marks the start of a time interval of interest in your code.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.os/documentation/os",
        "doc://com.apple.os/documentation/os/OSSignpostType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.os/documentation/os/OSSignpostType/begin"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "os",
    "externalID": "s:So18os_signpost_type_ta0A0E5beginABvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "begin"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@os_signpost_type_t",
        "text": "OSSignpostType"
      }
    ],
    "modules": [
      {
        "name": "os"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "begin"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "begin"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.os/documentation/os/OSSignpostType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@os_signpost_type_t",
              "text": "OSSignpostType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.os/documentation/os": {
      "abstract": [
        {
          "text": "Coordinate the scheduling and synchronization of your app’s tasks, and log information to the console to diagnose issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os",
      "kind": "symbol",
      "role": "collection",
      "title": "os",
      "type": "topic",
      "url": "/documentation/os"
    },
    "doc://com.apple.os/documentation/os/OSSignpostType": {
      "abstract": [
        {
          "text": "The different kinds of signpost.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSSignpostType"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSSignpostType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSignpostType"
        }
      ],
      "role": "symbol",
      "title": "OSSignpostType",
      "type": "topic",
      "url": "/documentation/os/ossignposttype"
    },
    "doc://com.apple.os/documentation/os/OSSignpostType/begin": {
      "abstract": [
        {
          "text": "A signpost that marks the start of a time interval of interest in your code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "begin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@os_signpost_type_t",
          "text": "OSSignpostType"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSSignpostType/begin",
      "kind": "symbol",
      "role": "symbol",
      "title": "begin",
      "type": "topic",
      "url": "/documentation/os/ossignposttype/begin"
    },
    "doc://com.apple.os/documentation/os/OSSignpostType/end": {
      "abstract": [
        {
          "text": "A signpost that marks the end of a time interval of interest in your code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "end"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@os_signpost_type_t",
          "text": "OSSignpostType"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSSignpostType/end",
      "kind": "symbol",
      "role": "symbol",
      "title": "end",
      "type": "topic",
      "url": "/documentation/os/ossignposttype/end"
    },
    "doc://com.apple.os/documentation/os/OSSignpostType/event": {
      "abstract": [
        {
          "text": "A signpost that marks an event in your code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "event"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@os_signpost_type_t",
          "text": "OSSignpostType"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSSignpostType/event",
      "kind": "symbol",
      "role": "symbol",
      "title": "event",
      "type": "topic",
      "url": "/documentation/os/ossignposttype/event"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Signpost-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.os/documentation/os/OSSignpostType/end",
        "doc://com.apple.os/documentation/os/OSSignpostType/event"
      ],
      "title": "Specifying Signpost Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSSignpostType/title",
          "value": "os_signpost_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSSignpostType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_signpost_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSSignpostType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "os_signpost_type_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/os/ossignposttype/begin"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
