{
  "abstract": [
    {
      "text": "The image has been rotated 90° clockwise and flipped horizontally from the orientation of its original pixel data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIImage",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/leftMirrored"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIImageOrientation@UIImageOrientationLeftMirrored",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "leftMirrored"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIImageOrientationLeftMirrored"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIImage.Orientation.leftMirrored"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "leftMirrored"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If an image is encoded with this orientation, then displayed by software unaware of orientation metadata, the image appears to be horizontally mirrored, then rotated 90° counter-clockwise. (That is, to present the image in its intended orientation, you can rotate it 90° clockwise, then flip horizontally.)",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2948307",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/ImageIO/CGImagePropertyOrientation/leftMirrored": {
      "abstract": [
        {
          "text": "The encoded image data is horizontally flipped and rotated 90° counter-clockwise from the image’s intended display orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftMirrored"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ImageIO/CGImagePropertyOrientation/leftMirrored",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGImagePropertyOrientation.leftMirrored",
      "type": "topic",
      "url": "/documentation/ImageIO/CGImagePropertyOrientation/leftMirrored"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage": {
      "abstract": [
        {
          "text": "An object that manages image data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "role": "symbol",
      "title": "UIImage",
      "type": "topic",
      "url": "/documentation/uikit/uiimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation": {
      "abstract": [
        {
          "text": "Constants that specify the intended display orientation for an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Orientation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Orientation"
        }
      ],
      "role": "symbol",
      "title": "UIImage.Orientation",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/orientation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/down": {
      "abstract": [
        {
          "text": "The image has been rotated 180° from the orientation of its original pixel data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "down"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/down",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageOrientationDown"
        }
      ],
      "role": "symbol",
      "title": "UIImage.Orientation.down",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/orientation/down"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/downMirrored": {
      "abstract": [
        {
          "text": "The image has been vertically flipped from the orientation of its original pixel data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downMirrored"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/downMirrored",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageOrientationDownMirrored"
        }
      ],
      "role": "symbol",
      "title": "UIImage.Orientation.downMirrored",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/orientation/downmirrored"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/left": {
      "abstract": [
        {
          "text": "The image has been rotated 90° counterclockwise from the orientation of its original pixel data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageOrientationLeft"
        }
      ],
      "role": "symbol",
      "title": "UIImage.Orientation.left",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/orientation/left"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/leftMirrored": {
      "abstract": [
        {
          "text": "The image has been rotated 90° clockwise and flipped horizontally from the orientation of its original pixel data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftMirrored"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/leftMirrored",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageOrientationLeftMirrored"
        }
      ],
      "role": "symbol",
      "title": "UIImage.Orientation.leftMirrored",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/orientation/leftmirrored"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/right": {
      "abstract": [
        {
          "text": "The image has been rotated 90° clockwise from the orientation of its original pixel data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageOrientationRight"
        }
      ],
      "role": "symbol",
      "title": "UIImage.Orientation.right",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/orientation/right"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/rightMirrored": {
      "abstract": [
        {
          "text": "The image has been rotated 90° counterclockwise and flipped horizontally from the orientation of its original pixel data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightMirrored"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/rightMirrored",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageOrientationRightMirrored"
        }
      ],
      "role": "symbol",
      "title": "UIImage.Orientation.rightMirrored",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/orientation/rightmirrored"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/up": {
      "abstract": [
        {
          "text": "The original pixel data matches the image’s intended display orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "up"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/up",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageOrientationUp"
        }
      ],
      "role": "symbol",
      "title": "UIImage.Orientation.up",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/orientation/up"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/upMirrored": {
      "abstract": [
        {
          "text": "The image has been horizontally flipped from the orientation of its original pixel data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "upMirrored"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/upMirrored",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageOrientationUpMirrored"
        }
      ],
      "role": "symbol",
      "title": "UIImage.Orientation.upMirrored",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/orientation/upmirrored"
    },
    "media-2948307": {
      "alt": "To correct an image with leftMirrored orientation for display, rotate it 90° clockwise then flip it horizontally.",
      "identifier": "media-2948307",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/bf391771539de275dc52041df5856db2/media-2948307.png"
        },
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed7462784881f7d23e39b968a2ecefff/media-2948307@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.documentation/documentation/ImageIO/CGImagePropertyOrientation/leftMirrored"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Image-orientations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/up",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/down",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/left",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/right",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/upMirrored",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/downMirrored",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/rightMirrored"
      ],
      "title": "Image orientations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIImageOrientationLeftMirrored"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageOrientationLeftMirrored"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.documentation/documentation/ImageIO/CGImagePropertyOrientation/leftMirrored"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Image-orientations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/up",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/down",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/left",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/right",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/upMirrored",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/downMirrored",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/rightMirrored"
              ],
              "title": "Image orientations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIImageOrientationLeftMirrored"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1upMirrored/title",
          "value": "UIImageOrientationUpMirrored"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1upMirrored/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageOrientationUpMirrored"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1rightMirrored/title",
          "value": "UIImageOrientationRightMirrored"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1rightMirrored/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageOrientationRightMirrored"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation/title",
          "value": "UIImageOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1right/title",
          "value": "UIImageOrientationRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageOrientationRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1up/title",
          "value": "UIImageOrientationUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1up/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageOrientationUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1leftMirrored/title",
          "value": "UIImageOrientationLeftMirrored"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1leftMirrored/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageOrientationLeftMirrored"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ImageIO~1CGImagePropertyOrientation~1leftMirrored/title",
          "value": "kCGImagePropertyOrientationLeftMirrored"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1ImageIO~1CGImagePropertyOrientation~1leftMirrored/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCGImagePropertyOrientationLeftMirrored"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title",
          "value": "UIImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1down/title",
          "value": "UIImageOrientationDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1down/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageOrientationDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1downMirrored/title",
          "value": "UIImageOrientationDownMirrored"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1downMirrored/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageOrientationDownMirrored"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1left/title",
          "value": "UIImageOrientationLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageOrientationLeft"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiimage/orientation/leftmirrored"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiimage/orientation/leftmirrored"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
