{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/right"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"The image has been rotated 90° clockwise from the orientation of its original pixel data.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"UIImageOrientationRight","kind":"identifier"}],"roleHeading":"Case","title":"UIImage.Orientation.right","externalID":"c:@E@UIImageOrientation@UIImageOrientationRight","modules":[{"name":"UIKit"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"}],"platforms":[{"unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"unavailable":false,"beta":false,"name":"iPadOS","deprecated":false},{"name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false},{"name":"tvOS","beta":false,"deprecated":false,"unavailable":false},{"name":"visionOS","beta":false,"deprecated":false,"unavailable":false},{"name":"watchOS","introducedAt":"2.0","beta":false,"deprecated":false,"unavailable":false}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"}],"languages":["swift"]}]},{"content":[{"anchor":"Discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"text":"If an image is encoded with this orientation, then displayed by software unaware of orientation metadata, the image appears to be rotated 90° counter-clockwise. (That is, to present the image in its intended orientation, you must rotate it 90° clockwise.)","type":"text"}],"type":"paragraph"},{"inlineContent":[{"identifier":"media-2948303","type":"image"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","variants":[{"paths":["/documentation/uikit/uiimage/orientation/right"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiimage/orientation/right"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIImage","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation"]]},"seeAlsoSections":[{"identifiers":["doc://com.apple.documentation/documentation/ImageIO/CGImagePropertyOrientation/right"],"anchor":"Related-Documentation","title":"Related Documentation"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/up","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/down","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/left","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/upMirrored","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/downMirrored","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/leftMirrored","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/rightMirrored"],"generated":true,"anchor":"Image-orientations","title":"Image orientations"}],"references":{"media-2948303":{"variants":[{"url":"https://docs-assets.developer.apple.com/published/5f85393673d69bff25539fb1abf634d9/media-2948303.png","traits":["1x","light"]},{"url":"https://docs-assets.developer.apple.com/published/a4de8a358cbf9a76800cc595fceb8892/media-2948303@2x.png","traits":["2x","light"]}],"identifier":"media-2948303","type":"image","alt":"To correct an image with right orientation for display, rotate it 90° clockwise."},"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/down":{"title":"UIImage.Orientation.down","abstract":[{"text":"The image has been rotated 180° from the orientation of its original pixel data.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/down","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"down","kind":"identifier"}],"navigatorTitle":[{"text":"UIImageOrientationDown","kind":"identifier"}],"url":"/documentation/uikit/uiimage/orientation/down","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/upMirrored":{"title":"UIImage.Orientation.upMirrored","abstract":[{"type":"text","text":"The image has been horizontally flipped from the orientation of its original pixel data."}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/upMirrored","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"upMirrored"}],"navigatorTitle":[{"kind":"identifier","text":"UIImageOrientationUpMirrored"}],"url":"/documentation/uikit/uiimage/orientation/upmirrored","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/right":{"title":"UIImage.Orientation.right","abstract":[{"type":"text","text":"The image has been rotated 90° clockwise from the orientation of its original pixel data."}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/right","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"}],"navigatorTitle":[{"kind":"identifier","text":"UIImageOrientationRight"}],"url":"/documentation/uikit/uiimage/orientation/right","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/rightMirrored":{"title":"UIImage.Orientation.rightMirrored","abstract":[{"text":"The image has been rotated 90° counterclockwise and flipped horizontally from the orientation of its original pixel data.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/rightMirrored","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightMirrored","kind":"identifier"}],"navigatorTitle":[{"text":"UIImageOrientationRightMirrored","kind":"identifier"}],"url":"/documentation/uikit/uiimage/orientation/rightmirrored","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/up":{"title":"UIImage.Orientation.up","abstract":[{"text":"The original pixel data matches the image’s intended display orientation.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/up","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"up","kind":"identifier"}],"navigatorTitle":[{"text":"UIImageOrientationUp","kind":"identifier"}],"url":"/documentation/uikit/uiimage/orientation/up","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.documentation/documentation/ImageIO/CGImagePropertyOrientation/right":{"identifier":"doc://com.apple.documentation/documentation/ImageIO/CGImagePropertyOrientation/right","abstract":[{"type":"text","text":"The encoded image data is rotated 90° clockwise from the image’s intended display orientation."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","title":"CGImagePropertyOrientation.right","url":"/documentation/ImageIO/CGImagePropertyOrientation/right"},"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation":{"role":"symbol","abstract":[{"type":"text","text":"Constants that specify the intended display orientation for an image."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Orientation"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation","title":"UIImage.Orientation","navigatorTitle":[{"kind":"identifier","text":"Orientation"}],"type":"topic","kind":"symbol","url":"/documentation/uikit/uiimage/orientation"},"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/left":{"title":"UIImage.Orientation.left","abstract":[{"type":"text","text":"The image has been rotated 90° counterclockwise from the orientation of its original pixel data."}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/left","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"}],"navigatorTitle":[{"kind":"identifier","text":"UIImageOrientationLeft"}],"url":"/documentation/uikit/uiimage/orientation/left","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/leftMirrored":{"title":"UIImage.Orientation.leftMirrored","abstract":[{"type":"text","text":"The image has been rotated 90° clockwise and flipped horizontally from the orientation of its original pixel data."}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/leftMirrored","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftMirrored"}],"navigatorTitle":[{"kind":"identifier","text":"UIImageOrientationLeftMirrored"}],"url":"/documentation/uikit/uiimage/orientation/leftmirrored","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage":{"kind":"symbol","role":"symbol","title":"UIImage","navigatorTitle":[{"text":"UIImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIImage","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","url":"/documentation/uikit/uiimage","abstract":[{"type":"text","text":"An object that manages image data in your app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/downMirrored":{"title":"UIImage.Orientation.downMirrored","abstract":[{"type":"text","text":"The image has been vertically flipped from the orientation of its original pixel data."}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/downMirrored","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"downMirrored"}],"navigatorTitle":[{"kind":"identifier","text":"UIImageOrientationDownMirrored"}],"url":"/documentation/uikit/uiimage/orientation/downmirrored","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"beta":false,"unavailable":false,"name":"iOS"},{"deprecated":false,"beta":false,"unavailable":false,"name":"iPadOS"},{"deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst"},{"deprecated":false,"beta":false,"unavailable":false,"name":"tvOS"},{"deprecated":false,"beta":false,"unavailable":false,"name":"visionOS"},{"deprecated":false,"introducedAt":"2.0","beta":false,"unavailable":false,"name":"watchOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"UIImageOrientationRight","op":"replace","path":"/metadata/title"},{"value":"case","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"UIImageOrientationRight"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc://com.apple.documentation/documentation/ImageIO/CGImagePropertyOrientation/right"]},{"title":"Image orientations","anchor":"Image-orientations","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/up","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/down","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/left","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/upMirrored","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/downMirrored","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/leftMirrored","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/rightMirrored"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"UIImageOrientationRight"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"UIImageOrientationDown","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1down/title"},{"value":[{"text":"UIImageOrientationDown","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1down/fragments"},{"value":"UIImageOrientationUpMirrored","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1upMirrored/title"},{"value":[{"kind":"identifier","text":"UIImageOrientationUpMirrored"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1upMirrored/fragments"},{"value":"UIImageOrientationRight","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1right/title"},{"value":[{"text":"UIImageOrientationRight","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1right/fragments"},{"value":"UIImageOrientationRightMirrored","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1rightMirrored/title"},{"value":[{"text":"UIImageOrientationRightMirrored","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1rightMirrored/fragments"},{"value":"UIImageOrientationUp","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1up/title"},{"value":[{"text":"UIImageOrientationUp","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1up/fragments"},{"value":"kCGImagePropertyOrientationRight","op":"replace","path":"/references/doc:~1~1com.apple.documentation~1documentation~1ImageIO~1CGImagePropertyOrientation~1right/title"},{"value":[{"kind":"identifier","text":"kCGImagePropertyOrientationRight"}],"op":"replace","path":"/references/doc:~1~1com.apple.documentation~1documentation~1ImageIO~1CGImagePropertyOrientation~1right/fragments"},{"value":"UIImageOrientation","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation/title"},{"value":[{"text":"UIImageOrientation","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation/fragments"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation/navigatorTitle","value":[{"kind":"identifier","text":"UIImageOrientation"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1left/title","value":"UIImageOrientationLeft","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1left/fragments","value":[{"text":"UIImageOrientationLeft","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1leftMirrored/title","value":"UIImageOrientationLeftMirrored","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1leftMirrored/fragments","value":[{"kind":"identifier","text":"UIImageOrientationLeftMirrored"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title","value":"UIImage","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments","value":[{"text":"UIImage","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle","value":[{"text":"UIImage","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1downMirrored/title","value":"UIImageOrientationDownMirrored","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1downMirrored/fragments","value":[{"text":"UIImageOrientationDownMirrored","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}