{
  "abstract": [
    {
      "text": "The identifier of the command that the user invoked.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xcodekit/documentation/XcodeKit",
        "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandInvocation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandInvocation/commandIdentifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)XCSourceEditorCommandInvocation(py)commandIdentifier",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "commandIdentifier"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "XcodeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "commandIdentifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "commandIdentifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "commandIdentifier"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit": {
      "abstract": [
        {
          "text": "Create extensions to add commands to the Xcode source editor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "XcodeKit",
      "type": "topic",
      "url": "/documentation/xcodekit"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandInvocation": {
      "abstract": [
        {
          "text": "An object that identifies the command issued to your extension and provides the contents of the active source editor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCSourceEditorCommandInvocation"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandInvocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCSourceEditorCommandInvocation"
        }
      ],
      "role": "symbol",
      "title": "XCSourceEditorCommandInvocation",
      "type": "topic",
      "url": "/documentation/xcodekit/xcsourceeditorcommandinvocation"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandInvocation/buffer": {
      "abstract": [
        {
          "text": "The buffer of source text upon which the command can operate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCSourceTextBuffer",
          "text": "XCSourceTextBuffer"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandInvocation/buffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buffer"
        }
      ],
      "role": "symbol",
      "title": "buffer",
      "type": "topic",
      "url": "/documentation/xcodekit/xcsourceeditorcommandinvocation/buffer"
    },
    "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandInvocation/commandIdentifier": {
      "abstract": [
        {
          "text": "The identifier of the command that the user invoked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commandIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandInvocation/commandIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "commandIdentifier"
        }
      ],
      "role": "symbol",
      "title": "commandIdentifier",
      "type": "topic",
      "url": "/documentation/xcodekit/xcsourceeditorcommandinvocation/commandidentifier"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-Commands",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandInvocation/buffer"
      ],
      "title": "Responding to Commands"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "commandIdentifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "commandIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xcodekit/documentation/XcodeKit",
                "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandInvocation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-Commands",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xcodekit/documentation/XcodeKit/XCSourceEditorCommandInvocation/buffer"
              ],
              "title": "Responding to Commands"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "commandIdentifier"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommandInvocation~1buffer/title",
          "value": "buffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommandInvocation~1buffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "buffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommandInvocation~1commandIdentifier/title",
          "value": "commandIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommandInvocation~1commandIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "commandIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommandInvocation/title",
          "value": "XCSourceEditorCommandInvocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommandInvocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceEditorCommandInvocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcodekit~1documentation~1XcodeKit~1XCSourceEditorCommandInvocation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCSourceEditorCommandInvocation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xcodekit/xcsourceeditorcommandinvocation/commandidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xcodekit/xcsourceeditorcommandinvocation/commandidentifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
