{
  "abstract": [
    {
      "text": "An array of ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEEvaluateConnectionRule",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " objects",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleEvaluateConnection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleEvaluateConnection/connectionRules"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NEOnDemandRuleEvaluateConnection(py)connectionRules",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "connectionRules"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NEEvaluateConnectionRule",
        "text": "NEEvaluateConnectionRule"
      },
      {
        "kind": "text",
        "text": "]?"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "connectionRules"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "connectionRules"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "connectionRules"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEEvaluateConnectionRule",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NEEvaluateConnectionRule",
              "text": "NEEvaluateConnectionRule"
            },
            {
              "kind": "text",
              "text": "]? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each ",
              "type": "text"
            },
            {
              "code": "NEEvaluateConnectionRule",
              "type": "codeVoice"
            },
            {
              "text": " object defines a behavior to take for connections that match the domain of the rule. Each rule is evaluated in order against the properties of a network connection being established. An example configuration has two connection rules: a rule matching ",
              "type": "text"
            },
            {
              "code": "myserver.example.com",
              "type": "codeVoice"
            },
            {
              "text": " with the domain action ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEEvaluateConnectionRuleAction/neverConnect",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", followed by a rule matching ",
              "type": "text"
            },
            {
              "code": "example.com",
              "type": "codeVoice"
            },
            {
              "text": " with the domain action ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEEvaluateConnectionRuleAction/connectIfNeeded",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This configuration would cause all connections to hostnames in ",
              "type": "text"
            },
            {
              "code": "example.com",
              "type": "codeVoice"
            },
            {
              "text": " that do not resolve on the current network to trigger the VPN, except for ",
              "type": "text"
            },
            {
              "code": "myserver.example.com",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEEvaluateConnectionRule": {
      "abstract": [
        {
          "code": "NEEvaluateConnectionRule",
          "type": "codeVoice"
        },
        {
          "text": " associates properties of network connections with an action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEEvaluateConnectionRule"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEEvaluateConnectionRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEEvaluateConnectionRule"
        }
      ],
      "role": "symbol",
      "title": "NEEvaluateConnectionRule",
      "type": "topic",
      "url": "/documentation/networkextension/neevaluateconnectionrule"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEEvaluateConnectionRuleAction/connectIfNeeded": {
      "abstract": [
        {
          "text": "Start the VPN if connections to the matching hostname cannot be resolved.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectIfNeeded"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEEvaluateConnectionRuleAction/connectIfNeeded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEEvaluateConnectionRuleActionConnectIfNeeded"
        }
      ],
      "role": "symbol",
      "title": "NEEvaluateConnectionRuleAction.connectIfNeeded",
      "type": "topic",
      "url": "/documentation/networkextension/neevaluateconnectionruleaction/connectifneeded"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEEvaluateConnectionRuleAction/neverConnect": {
      "abstract": [
        {
          "text": "Do not start the VPN.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "neverConnect"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEEvaluateConnectionRuleAction/neverConnect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEEvaluateConnectionRuleActionNeverConnect"
        }
      ],
      "role": "symbol",
      "title": "NEEvaluateConnectionRuleAction.neverConnect",
      "type": "topic",
      "url": "/documentation/networkextension/neevaluateconnectionruleaction/neverconnect"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleEvaluateConnection": {
      "abstract": [
        {
          "text": "A VPN On Demand rule that evaluate the app’s connection to determine whether to run its action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEOnDemandRuleEvaluateConnection"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleEvaluateConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEOnDemandRuleEvaluateConnection"
        }
      ],
      "role": "symbol",
      "title": "NEOnDemandRuleEvaluateConnection",
      "type": "topic",
      "url": "/documentation/networkextension/neondemandruleevaluateconnection"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleEvaluateConnection/connectionRules": {
      "abstract": [
        {
          "text": "An array of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEEvaluateConnectionRule",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " objects",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "connectionRules"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEEvaluateConnectionRule",
          "text": "NEEvaluateConnectionRule"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleEvaluateConnection/connectionRules",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "connectionRules"
        }
      ],
      "role": "symbol",
      "title": "connectionRules",
      "type": "topic",
      "url": "/documentation/networkextension/neondemandruleevaluateconnection/connectionrules"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-connection-rules",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEEvaluateConnectionRule"
      ],
      "title": "Accessing connection rules"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "connectionRules"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "connectionRules"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEOnDemandRuleEvaluateConnection"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-connection-rules",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEEvaluateConnectionRule"
              ],
              "title": "Accessing connection rules"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NEEvaluateConnectionRule *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "connectionRules"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEEvaluateConnectionRuleAction~1neverConnect/title",
          "value": "NEEvaluateConnectionRuleActionNeverConnect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEEvaluateConnectionRuleAction~1neverConnect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEEvaluateConnectionRuleActionNeverConnect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleEvaluateConnection~1connectionRules/title",
          "value": "connectionRules"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleEvaluateConnection~1connectionRules/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "connectionRules"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEEvaluateConnectionRuleAction~1connectIfNeeded/title",
          "value": "NEEvaluateConnectionRuleActionConnectIfNeeded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEEvaluateConnectionRuleAction~1connectIfNeeded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEEvaluateConnectionRuleActionConnectIfNeeded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleEvaluateConnection/title",
          "value": "NEOnDemandRuleEvaluateConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleEvaluateConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEOnDemandRuleEvaluateConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEOnDemandRuleEvaluateConnection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEOnDemandRuleEvaluateConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEEvaluateConnectionRule/title",
          "value": "NEEvaluateConnectionRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEEvaluateConnectionRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEEvaluateConnectionRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEEvaluateConnectionRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEEvaluateConnectionRule"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/neondemandruleevaluateconnection/connectionrules"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/neondemandruleevaluateconnection/connectionrules"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
