{"seeAlsoSections":[{"anchor":"Fetching-Assets","title":"Fetching Assets","generated":true,"identifiers":["doc://com.apple.photokit/documentation/PhotoKit/fetching-assets","doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(with:options:)","doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withLocalIdentifiers:options:)","doc://com.apple.photokit/documentation/Photos/PHAsset/fetchKeyAssets(in:options:)","doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(with:)","doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withBurstIdentifier:options:)","doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withALAssetURLs:options:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/photos/phasset/fetchassets(in:options:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/photos/phasset/fetchassets(in:options:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchAssets"},{"kind":"text","text":"("},{"text":"in","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"assetCollection","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.photokit/documentation/Photos/PHAssetCollection","text":"PHAssetCollection","preciseIdentifier":"c:objc(cs)PHAssetCollection","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchOptions","text":"PHFetchOptions","preciseIdentifier":"c:objc(cs)PHFetchOptions","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchResult","text":"PHFetchResult","preciseIdentifier":"c:objc(cs)PHFetchResult","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset","text":"PHAsset","preciseIdentifier":"c:objc(cs)PHAsset","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The asset collection from which to fetch assets."}]}],"name":"assetCollection"},{"content":[{"inlineContent":[{"text":"Options that specify a filter predicate and sort order for the fetched assets, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" to use default options. For details, see ","type":"text"},{"identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchOptions","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"options"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"A fetch result that contains the requested ","type":"text"},{"type":"reference","identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset","isActive":true},{"text":" objects, or an empty fetch result if no objects match the request.","type":"text"}]}]},{"mentions":["doc://com.apple.photokit/documentation/PhotoKit/fetching-assets"],"kind":"mentions"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"By default, the returned ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchResult","type":"reference"},{"text":" object contains all assets in the specified collection. To retrieve a more specific set of assets, provide a ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchOptions","type":"reference"},{"text":" object containing a filter predicate.","type":"text"}]}]}],"metadata":{"externalID":"c:objc(cs)PHAsset(cm)fetchAssetsInAssetCollection:options:","platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"iOS","introducedAt":"8.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS","introducedAt":"8.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"deprecated":false,"introducedAt":"10.13","name":"macOS","beta":false,"unavailable":false},{"deprecated":false,"introducedAt":"10.0","name":"tvOS","beta":false,"unavailable":false},{"deprecated":false,"introducedAt":"1.0","name":"visionOS","beta":false,"unavailable":false}],"navigatorTitle":[{"text":"fetchAssetsInAssetCollection:options:","kind":"identifier"}],"roleHeading":"Type Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchAssets","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PHAssetCollection","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHAssetCollection"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHFetchOptions","text":"PHFetchOptions","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHFetchResult","text":"PHFetchResult","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHAsset","text":"PHAsset","kind":"typeIdentifier"},{"text":">","kind":"text"}],"modules":[{"name":"Photos"}],"title":"fetchAssets(in:options:)","role":"symbol"},"sections":[],"kind":"symbol","abstract":[{"text":"Retrieves assets from the specified asset collection.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.photokit/documentation/Photos","doc://com.apple.photokit/documentation/Photos/PHAsset"]]},"identifier":{"url":"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(in:options:)","interfaceLanguage":"swift"},"references":{"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(with:options:)":{"abstract":[{"text":"Retrieves assets with the specified media type.","type":"text"}],"type":"topic","identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(with:options:)","role":"symbol","navigatorTitle":[{"text":"fetchAssetsWithMediaType:options:","kind":"identifier"}],"title":"fetchAssets(with:options:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchAssets","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PHAssetMediaType","kind":"typeIdentifier","preciseIdentifier":"c:@E@PHAssetMediaType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchOptions","text":"PHFetchOptions"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:objc(cs)PHFetchResult","text":"PHFetchResult","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHAsset","text":"PHAsset","kind":"typeIdentifier"},{"text":">","kind":"text"}],"kind":"symbol","url":"/documentation/photos/phasset/fetchassets(with:options:)"},"doc://com.apple.photokit/documentation/Photos/PHAsset":{"abstract":[{"text":"A representation of an image, video, or Live Photo in the Photos library.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PHAsset"}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset","url":"/documentation/photos/phasset","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PHAsset"}],"type":"topic","title":"PHAsset","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","kind":"technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","url":"/documentation/technologies"},"doc://com.apple.photokit/documentation/PhotoKit/fetching-assets":{"role":"article","abstract":[{"type":"text","text":"Retrieve asset metadata or request full asset content."}],"kind":"article","title":"Fetching Assets","url":"/documentation/photokit/fetching-assets","type":"topic","identifier":"doc://com.apple.photokit/documentation/PhotoKit/fetching-assets"},"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withBurstIdentifier:options:)":{"title":"fetchAssets(withBurstIdentifier:options:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fetchAssets"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withBurstIdentifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PHFetchOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchOptions"},{"text":"?) -> ","kind":"text"},{"text":"PHFetchResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchResult"},{"text":"<","kind":"text"},{"text":"PHAsset","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHAsset"},{"text":">","kind":"text"}],"type":"topic","abstract":[{"text":"Retrieves assets with the specified burst photo sequence identifier.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withBurstIdentifier:options:)","role":"symbol","navigatorTitle":[{"text":"fetchAssetsWithBurstIdentifier:options:","kind":"identifier"}],"url":"/documentation/photos/phasset/fetchassets(withburstidentifier:options:)"},"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(in:options:)":{"kind":"symbol","role":"symbol","title":"fetchAssets(in:options:)","url":"/documentation/photos/phasset/fetchassets(in:options:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchAssets"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)PHAssetCollection","kind":"typeIdentifier","text":"PHAssetCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)PHFetchOptions","kind":"typeIdentifier","text":"PHFetchOptions"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:objc(cs)PHFetchResult","kind":"typeIdentifier","text":"PHFetchResult"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)PHAsset","kind":"typeIdentifier","text":"PHAsset"},{"kind":"text","text":">"}],"type":"topic","identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(in:options:)","abstract":[{"text":"Retrieves assets from the specified asset collection.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"fetchAssetsInAssetCollection:options:"}]},"doc://com.apple.photokit/documentation/Photos/PHFetchResult":{"type":"topic","identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PHFetchResult","kind":"identifier"}],"role":"symbol","title":"PHFetchResult","abstract":[{"text":"An ordered list of assets or collections returned from a Photos fetch method.","type":"text"}],"url":"/documentation/photos/phfetchresult","kind":"symbol","navigatorTitle":[{"text":"PHFetchResult","kind":"identifier"}]},"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchKeyAssets(in:options:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchKeyAssets","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHAssetCollection","text":"PHAssetCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchOptions","text":"PHFetchOptions"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHFetchResult","text":"PHFetchResult","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHAsset","text":"PHAsset","kind":"typeIdentifier"},{"text":">?","kind":"text"}],"navigatorTitle":[{"text":"fetchKeyAssetsInAssetCollection:options:","kind":"identifier"}],"role":"symbol","url":"/documentation/photos/phasset/fetchkeyassets(in:options:)","abstract":[{"text":"Retrieves assets marked as key assets in the specified asset collection.","type":"text"}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchKeyAssets(in:options:)","kind":"symbol","type":"topic","title":"fetchKeyAssets(in:options:)"},"doc://com.apple.photokit/documentation/Photos":{"title":"Photos","role":"collection","kind":"symbol","identifier":"doc://com.apple.photokit/documentation/Photos","abstract":[{"type":"text","text":"Work with image and video assets that the Photos app manages, including those from iCloud Photos and Live Photos."}],"type":"topic","url":"/documentation/photos"},"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withALAssetURLs:options:)":{"deprecated":true,"role":"symbol","abstract":[{"type":"text","text":"Retrieves assets using URLs provided by the Assets Library framework."}],"kind":"symbol","title":"fetchAssets(withALAssetURLs:options:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchAssets"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withALAssetURLs"},{"text":": [","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"], ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHFetchOptions","text":"PHFetchOptions","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHFetchResult","text":"PHFetchResult","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHAsset","text":"PHAsset","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"/documentation/photos/phasset/fetchassets(withalasseturls:options:)","type":"topic","identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withALAssetURLs:options:)","navigatorTitle":[{"text":"fetchAssetsWithALAssetURLs:options:","kind":"identifier"}]},"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withLocalIdentifiers:options:)":{"type":"topic","kind":"symbol","role":"symbol","title":"fetchAssets(withLocalIdentifiers:options:)","abstract":[{"type":"text","text":"Retrieves assets with the specified local-device-specific unique identifiers."}],"url":"/documentation/photos/phasset/fetchassets(withlocalidentifiers:options:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchAssets","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withLocalIdentifiers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PHFetchOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchOptions"},{"text":"?) -> ","kind":"text"},{"text":"PHFetchResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchResult"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHAsset","text":"PHAsset","kind":"typeIdentifier"},{"text":">","kind":"text"}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withLocalIdentifiers:options:)","navigatorTitle":[{"text":"fetchAssetsWithLocalIdentifiers:options:","kind":"identifier"}]},"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(with:)":{"abstract":[{"text":"Retrieves all assets matching the specified options.","type":"text"}],"type":"topic","identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(with:)","role":"symbol","navigatorTitle":[{"text":"fetchAssetsWithOptions:","kind":"identifier"}],"title":"fetchAssets(with:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchAssets","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PHFetchOptions","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchOptions"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHFetchResult","text":"PHFetchResult"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PHAsset","text":"PHAsset"},{"kind":"text","text":">"}],"kind":"symbol","url":"/documentation/photos/phasset/fetchassets(with:)"},"doc://com.apple.photokit/documentation/Photos/PHAssetCollection":{"role":"symbol","url":"/documentation/photos/phassetcollection","type":"topic","abstract":[{"type":"text","text":"A representation of a Photos asset grouping, such as a moment, user-created album, or smart album."}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHAssetCollection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PHAssetCollection"}],"title":"PHAssetCollection","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PHAssetCollection"}]},"doc://com.apple.photokit/documentation/Photos/PHFetchOptions":{"navigatorTitle":[{"kind":"identifier","text":"PHFetchOptions"}],"url":"/documentation/photos/phfetchoptions","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PHFetchOptions"}],"identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchOptions","role":"symbol","abstract":[{"type":"text","text":"A set of options that affect the filtering, sorting, and management of results that Photos returns when you fetch asset or collection objects."}],"title":"PHFetchOptions"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"introducedAt":"8.0","unavailable":false,"deprecated":false,"name":"iOS","beta":false},{"deprecated":false,"introducedAt":"8.0","name":"iPadOS","beta":false,"unavailable":false},{"deprecated":false,"introducedAt":"13.1","name":"Mac Catalyst","beta":false,"unavailable":false},{"deprecated":false,"introducedAt":"10.13","name":"macOS","beta":false,"unavailable":false},{"deprecated":false,"introducedAt":"10.0","name":"tvOS","beta":false,"unavailable":false},{"introducedAt":"1.0","unavailable":false,"beta":false,"name":"visionOS","deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Type Method","path":"/metadata/roleHeading","op":"replace"},{"value":"fetchAssetsInAssetCollection:options:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fetchAssetsInAssetCollection:options:"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.photokit/documentation/Photos","doc://com.apple.photokit/documentation/Photos/PHAsset"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(with:options:)","doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withLocalIdentifiers:options:)","doc://com.apple.photokit/documentation/Photos/PHAsset/fetchKeyAssets(in:options:)","doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(with:)","doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withBurstIdentifier:options:)","doc://com.apple.photokit/documentation/Photos/PHAsset/fetchAssets(withALAssetURLs:options:)"],"generated":true,"anchor":"Fetching-Assets","title":"Fetching Assets"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"PHFetchResult<PHAsset *>","preciseIdentifier":"c:Q$objc(cs)PHFetchResult","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fetchAssetsInAssetCollection:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.photokit/documentation/Photos/PHAssetCollection","text":"PHAssetCollection","preciseIdentifier":"c:objc(cs)PHAssetCollection","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"assetCollection","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"options:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)PHFetchOptions","text":"PHFetchOptions","identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchOptions","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"op":"replace","path":"/primaryContentSections/1","value":{"parameters":[{"name":"assetCollection","content":[{"type":"paragraph","inlineContent":[{"text":"The asset collection from which to fetch assets.","type":"text"}]}]},{"name":"options","content":[{"inlineContent":[{"text":"Options that specify a filter predicate and sort order for the fetched assets, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" to use default options. For details, see ","type":"text"},{"identifier":"doc://com.apple.photokit/documentation/Photos/PHFetchOptions","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","path":"/primaryContentSections/2","value":{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"A fetch result that contains the requested ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.photokit/documentation/Photos/PHAsset","type":"reference"},{"text":" objects, or an empty fetch result if no objects match the request.","type":"text"}]}],"kind":"content"}},{"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(with:options:)/title","value":"fetchAssetsWithMediaType:options:"},{"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(with:options:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fetchAssetsWithMediaType:options:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/title","value":"PHAsset"},{"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/fragments","value":[{"kind":"identifier","text":"PHAsset"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset/navigatorTitle","value":[{"text":"PHAsset","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(withBurstIdentifier:options:)/title","value":"fetchAssetsWithBurstIdentifier:options:"},{"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(withBurstIdentifier:options:)/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fetchAssetsWithBurstIdentifier:options:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(in:options:)/title","value":"fetchAssetsInAssetCollection:options:"},{"value":[{"text":"+ ","kind":"text"},{"text":"fetchAssetsInAssetCollection:options:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(in:options:)/fragments"},{"value":"PHFetchResult","op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResult/title"},{"value":[{"text":"PHFetchResult","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResult/fragments"},{"value":[{"text":"PHFetchResult","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchResult/navigatorTitle"},{"value":"fetchKeyAssetsInAssetCollection:options:","op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchKeyAssets(in:options:)/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fetchKeyAssetsInAssetCollection:options:"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchKeyAssets(in:options:)/fragments"},{"value":"fetchAssetsWithALAssetURLs:options:","op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(withALAssetURLs:options:)/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"fetchAssetsWithALAssetURLs:options:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(withALAssetURLs:options:)/fragments"},{"value":"fetchAssetsWithLocalIdentifiers:options:","op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(withLocalIdentifiers:options:)/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"fetchAssetsWithLocalIdentifiers:options:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(withLocalIdentifiers:options:)/fragments"},{"value":"fetchAssetsWithOptions:","op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(with:)/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fetchAssetsWithOptions:"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAsset~1fetchAssets(with:)/fragments"},{"value":"PHAssetCollection","op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection/title"},{"value":[{"text":"PHAssetCollection","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection/fragments"},{"value":[{"text":"PHAssetCollection","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHAssetCollection/navigatorTitle"},{"value":"PHFetchOptions","op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchOptions/title"},{"value":[{"text":"PHFetchOptions","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchOptions/fragments"},{"value":[{"kind":"identifier","text":"PHFetchOptions"}],"op":"replace","path":"/references/doc:~1~1com.apple.photokit~1documentation~1Photos~1PHFetchOptions/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}