{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopped"}],"platforms":["Mac Catalyst","macOS"]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.screencapturekit/documentation/ScreenCaptureKit","doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/stopped","interfaceLanguage":"swift"},"seeAlsoSections":[{"title":"Status values","generated":true,"identifiers":["doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/complete","doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/idle","doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/blank","doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/started","doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/suspended"],"anchor":"Status-values"}],"variants":[{"paths":["/documentation/screencapturekit/scframestatus/stopped"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/screencapturekit/scframestatus/stopped"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"A status that indicates the frame is in a stopped state."}],"metadata":{"role":"symbol","title":"SCFrameStatus.stopped","externalID":"c:@E@SCFrameStatus@SCFrameStatusStopped","navigatorTitle":[{"text":"SCFrameStatusStopped","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"ScreenCaptureKit"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopped","kind":"identifier"}],"platforms":[{"introducedAt":"18.2","unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"},{"introducedAt":"12.3","unavailable":false,"beta":false,"deprecated":false,"name":"macOS"}]},"references":{"doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/complete":{"role":"symbol","abstract":[{"type":"text","text":"A status that indicates the system successfully generated a new frame."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"complete"}],"navigatorTitle":[{"kind":"identifier","text":"SCFrameStatusComplete"}],"identifier":"doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/complete","title":"SCFrameStatus.complete","url":"/documentation/screencapturekit/scframestatus/complete"},"doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/stopped":{"url":"/documentation/screencapturekit/scframestatus/stopped","kind":"symbol","type":"topic","identifier":"doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/stopped","title":"SCFrameStatus.stopped","abstract":[{"type":"text","text":"A status that indicates the frame is in a stopped state."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopped"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SCFrameStatusStopped"}]},"doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/started":{"url":"/documentation/screencapturekit/scframestatus/started","kind":"symbol","type":"topic","identifier":"doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/started","title":"SCFrameStatus.started","abstract":[{"type":"text","text":"A status that indicates the frame is the first one sent after the stream starts."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"started"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SCFrameStatusStarted"}]},"doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/blank":{"navigatorTitle":[{"kind":"identifier","text":"SCFrameStatusBlank"}],"title":"SCFrameStatus.blank","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"blank"}],"role":"symbol","identifier":"doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/blank","url":"/documentation/screencapturekit/scframestatus/blank","kind":"symbol","type":"topic","abstract":[{"text":"A status that indicates the system didn’t generate a new frame because the display is blank.","type":"text"}]},"doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus":{"identifier":"doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus","type":"topic","title":"SCFrameStatus","url":"/documentation/screencapturekit/scframestatus","abstract":[{"type":"text","text":"Status values for a frame from a stream."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SCFrameStatus","kind":"identifier"}],"navigatorTitle":[{"text":"SCFrameStatus","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/idle":{"url":"/documentation/screencapturekit/scframestatus/idle","kind":"symbol","type":"topic","identifier":"doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/idle","title":"SCFrameStatus.idle","abstract":[{"type":"text","text":"A status that indicates the system didn’t generate a new frame because the display didn’t change."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"idle"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SCFrameStatusIdle"}]},"doc://com.apple.screencapturekit/documentation/ScreenCaptureKit":{"identifier":"doc://com.apple.screencapturekit/documentation/ScreenCaptureKit","url":"/documentation/screencapturekit","abstract":[{"text":"Filter and select screen content and stream it to your app.","type":"text"}],"role":"collection","title":"ScreenCaptureKit","type":"topic","kind":"symbol"},"doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/suspended":{"navigatorTitle":[{"kind":"identifier","text":"SCFrameStatusSuspended"}],"title":"SCFrameStatus.suspended","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"suspended"}],"role":"symbol","identifier":"doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/suspended","url":"/documentation/screencapturekit/scframestatus/suspended","kind":"symbol","type":"topic","abstract":[{"text":"A status that indicates the system didn’t generate a new frame because you suspended updates.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"role":"overview","title":"Technologies","type":"topic","kind":"technologies"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"unavailable":false,"introducedAt":"18.2","deprecated":false,"name":"Mac Catalyst"},{"beta":false,"unavailable":false,"introducedAt":"12.3","deprecated":false,"name":"macOS"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"/metadata/title","value":"SCFrameStatusStopped"},{"op":"replace","path":"/metadata/symbolKind","value":"case"},{"op":"replace","value":[{"text":"SCFrameStatusStopped","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.screencapturekit/documentation/ScreenCaptureKit","doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"generated":true,"title":"Status values","anchor":"Status-values","identifiers":["doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/complete","doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/idle","doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/blank","doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/started","doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/suspended"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"text":"SCFrameStatusStopped","kind":"identifier"}]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","path":"/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1complete/title","value":"SCFrameStatusComplete"},{"op":"replace","path":"/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1complete/fragments","value":[{"text":"SCFrameStatusComplete","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1stopped/title","value":"SCFrameStatusStopped"},{"path":"/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1stopped/fragments","value":[{"kind":"identifier","text":"SCFrameStatusStopped"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1started/title","value":"SCFrameStatusStarted","op":"replace"},{"path":"/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1started/fragments","value":[{"kind":"identifier","text":"SCFrameStatusStarted"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1blank/title","value":"SCFrameStatusBlank","op":"replace"},{"path":"/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1blank/fragments","value":[{"kind":"identifier","text":"SCFrameStatusBlank"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus/title","value":"SCFrameStatus","op":"replace"},{"path":"/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus/fragments","value":[{"text":"SCFrameStatus","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus/navigatorTitle","value":[{"kind":"identifier","text":"SCFrameStatus"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1idle/title","value":"SCFrameStatusIdle","op":"replace"},{"path":"/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1idle/fragments","value":[{"text":"SCFrameStatusIdle","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1suspended/title","value":"SCFrameStatusSuspended","op":"replace"},{"path":"/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1suspended/fragments","value":[{"kind":"identifier","text":"SCFrameStatusSuspended"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}