{
  "abstract": [
    {
      "text": "A status that indicates the system didn’t generate a new frame because you suspended updates.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/suspended"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SCFrameStatus@SCFrameStatusSuspended",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "suspended"
      }
    ],
    "modules": [
      {
        "name": "ScreenCaptureKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCFrameStatusSuspended"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SCFrameStatus.suspended"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "suspended"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit": {
      "abstract": [
        {
          "text": "Filter and select screen content and stream it to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ScreenCaptureKit",
      "type": "topic",
      "url": "/documentation/screencapturekit"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus": {
      "abstract": [
        {
          "text": "Status values for a frame from a stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCFrameStatus"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCFrameStatus"
        }
      ],
      "role": "symbol",
      "title": "SCFrameStatus",
      "type": "topic",
      "url": "/documentation/screencapturekit/scframestatus"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/blank": {
      "abstract": [
        {
          "text": "A status that indicates the system didn’t generate a new frame because the display is blank.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blank"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/blank",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCFrameStatusBlank"
        }
      ],
      "role": "symbol",
      "title": "SCFrameStatus.blank",
      "type": "topic",
      "url": "/documentation/screencapturekit/scframestatus/blank"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/complete": {
      "abstract": [
        {
          "text": "A status that indicates the system successfully generated a new frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "complete"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/complete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCFrameStatusComplete"
        }
      ],
      "role": "symbol",
      "title": "SCFrameStatus.complete",
      "type": "topic",
      "url": "/documentation/screencapturekit/scframestatus/complete"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/idle": {
      "abstract": [
        {
          "text": "A status that indicates the system didn’t generate a new frame because the display didn’t change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "idle"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/idle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCFrameStatusIdle"
        }
      ],
      "role": "symbol",
      "title": "SCFrameStatus.idle",
      "type": "topic",
      "url": "/documentation/screencapturekit/scframestatus/idle"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/started": {
      "abstract": [
        {
          "text": "A status that indicates the frame is the first one sent after the stream starts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "started"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/started",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCFrameStatusStarted"
        }
      ],
      "role": "symbol",
      "title": "SCFrameStatus.started",
      "type": "topic",
      "url": "/documentation/screencapturekit/scframestatus/started"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/stopped": {
      "abstract": [
        {
          "text": "A status that indicates the frame is in a stopped state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopped"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/stopped",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCFrameStatusStopped"
        }
      ],
      "role": "symbol",
      "title": "SCFrameStatus.stopped",
      "type": "topic",
      "url": "/documentation/screencapturekit/scframestatus/stopped"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/suspended": {
      "abstract": [
        {
          "text": "A status that indicates the system didn’t generate a new frame because you suspended updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suspended"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/suspended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCFrameStatusSuspended"
        }
      ],
      "role": "symbol",
      "title": "SCFrameStatus.suspended",
      "type": "topic",
      "url": "/documentation/screencapturekit/scframestatus/suspended"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Status-values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/complete",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/idle",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/blank",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/started",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/stopped"
      ],
      "title": "Status values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCFrameStatusSuspended"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCFrameStatusSuspended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Status-values",
              "generated": true,
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/complete",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/idle",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/blank",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/started",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCFrameStatus/stopped"
              ],
              "title": "Status values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SCFrameStatusSuspended"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus/title",
          "value": "SCFrameStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCFrameStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCFrameStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1suspended/title",
          "value": "SCFrameStatusSuspended"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1suspended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCFrameStatusSuspended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1idle/title",
          "value": "SCFrameStatusIdle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1idle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCFrameStatusIdle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1started/title",
          "value": "SCFrameStatusStarted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1started/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCFrameStatusStarted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1blank/title",
          "value": "SCFrameStatusBlank"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1blank/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCFrameStatusBlank"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1stopped/title",
          "value": "SCFrameStatusStopped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1stopped/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCFrameStatusStopped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1complete/title",
          "value": "SCFrameStatusComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCFrameStatus~1complete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCFrameStatusComplete"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/screencapturekit/scframestatus/suspended"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/screencapturekit/scframestatus/suspended"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
