{
  "abstract": [
    {
      "text": "The reason the app was terminated as a human-readable string.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metrickit/documentation/MetricKit",
        "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/terminationReason"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MXCrashDiagnostic(py)terminationReason",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "terminationReason"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "MetricKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "terminationReason"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "terminationReason"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "terminationReason"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metrickit/documentation/MetricKit": {
      "abstract": [
        {
          "text": "Aggregate and analyze per-device reports on exception and crash diagnostics and on power and performance metrics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetricKit",
      "type": "topic",
      "url": "/documentation/metrickit"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic": {
      "abstract": [
        {
          "text": "An object representing a diagnostic report for an app crash.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MXCrashDiagnostic"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MXCrashDiagnostic"
        }
      ],
      "role": "symbol",
      "title": "MXCrashDiagnostic",
      "type": "topic",
      "url": "/documentation/metrickit/mxcrashdiagnostic"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionCode": {
      "abstract": [
        {
          "text": "The encoded processor-specific information for the crash.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exceptionCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exceptionCode"
        }
      ],
      "role": "symbol",
      "title": "exceptionCode",
      "type": "topic",
      "url": "/documentation/metrickit/mxcrashdiagnostic/exceptioncode"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionReason": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exceptionReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MXCrashDiagnosticObjectiveCExceptionReason",
          "text": "MXCrashDiagnosticObjectiveCExceptionReason"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exceptionReason"
        }
      ],
      "role": "symbol",
      "title": "exceptionReason",
      "type": "topic",
      "url": "/documentation/metrickit/mxcrashdiagnostic/exceptionreason"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionType": {
      "abstract": [
        {
          "text": "The Mach exception type of the crash.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exceptionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exceptionType"
        }
      ],
      "role": "symbol",
      "title": "exceptionType",
      "type": "topic",
      "url": "/documentation/metrickit/mxcrashdiagnostic/exceptiontype"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/signal": {
      "abstract": [
        {
          "text": "The signal associated with the crash.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "signal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/signal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "signal"
        }
      ],
      "role": "symbol",
      "title": "signal",
      "type": "topic",
      "url": "/documentation/metrickit/mxcrashdiagnostic/signal"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/terminationReason": {
      "abstract": [
        {
          "text": "The reason the app was terminated as a human-readable string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "terminationReason"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/terminationReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "terminationReason"
        }
      ],
      "role": "symbol",
      "title": "terminationReason",
      "type": "topic",
      "url": "/documentation/metrickit/mxcrashdiagnostic/terminationreason"
    },
    "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/virtualMemoryRegionInfo": {
      "abstract": [
        {
          "text": "Information about the region of memory an app accessed incorrectly, resulting in a bad-access crash.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "virtualMemoryRegionInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/virtualMemoryRegionInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "virtualMemoryRegionInfo"
        }
      ],
      "role": "symbol",
      "title": "virtualMemoryRegionInfo",
      "type": "topic",
      "url": "/documentation/metrickit/mxcrashdiagnostic/virtualmemoryregioninfo"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Viewing-exception-details",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionType",
        "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionCode",
        "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/signal",
        "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionReason",
        "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/virtualMemoryRegionInfo"
      ],
      "title": "Viewing exception details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "terminationReason"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "terminationReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metrickit/documentation/MetricKit",
                "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Viewing-exception-details",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionType",
                "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionCode",
                "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/signal",
                "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/exceptionReason",
                "doc://com.apple.metrickit/documentation/MetricKit/MXCrashDiagnostic/virtualMemoryRegionInfo"
              ],
              "title": "Viewing exception details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "terminationReason"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic/title",
          "value": "MXCrashDiagnostic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCrashDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MXCrashDiagnostic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1exceptionReason/title",
          "value": "exceptionReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1exceptionReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exceptionReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1signal/title",
          "value": "signal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1signal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "signal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1exceptionCode/title",
          "value": "exceptionCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1exceptionCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exceptionCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1virtualMemoryRegionInfo/title",
          "value": "virtualMemoryRegionInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1virtualMemoryRegionInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "virtualMemoryRegionInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1exceptionType/title",
          "value": "exceptionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1exceptionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exceptionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1terminationReason/title",
          "value": "terminationReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metrickit~1documentation~1MetricKit~1MXCrashDiagnostic~1terminationReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "terminationReason"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metrickit/mxcrashdiagnostic/terminationreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metrickit/mxcrashdiagnostic/terminationreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
