{
  "abstract": [
    {
      "text": "A discriminator value the system uses to generate pointer authentication codes for just-in-time compilation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_JIT_WRITE_PROTECT_TAG"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@BE_JIT_WRITE_PROTECT_TAG",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BE_JIT_WRITE_PROTECT_TAG"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "BrowserEngineCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BE_JIT_WRITE_PROTECT_TAG"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "BE_JIT_WRITE_PROTECT_TAG"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BE_JIT_WRITE_PROTECT_TAG"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore": {
      "abstract": [
        {
          "text": "Integrate an alternative browser engine into your web browser app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore",
      "kind": "symbol",
      "role": "collection",
      "title": "BrowserEngineCore",
      "type": "topic",
      "url": "/documentation/browserenginecore"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_JIT_WRITE_PROTECT_TAG": {
      "abstract": [
        {
          "text": "A discriminator value the system uses to generate pointer authentication codes for just-in-time compilation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BE_JIT_WRITE_PROTECT_TAG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_JIT_WRITE_PROTECT_TAG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BE_JIT_WRITE_PROTECT_TAG"
        }
      ],
      "role": "symbol",
      "title": "BE_JIT_WRITE_PROTECT_TAG",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_jit_write_protect_tag"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_rwx_to_rw_with_witness": {
      "abstract": [
        {
          "text": "Makes a region of memory writable for use in just-in-time (JIT) compilation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "be_memory_inline_jit_restrict_rwx_to_rw_with_witness"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_rwx_to_rw_with_witness",
      "kind": "symbol",
      "role": "symbol",
      "title": "be_memory_inline_jit_restrict_rwx_to_rw_with_witness",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_memory_inline_jit_restrict_rwx_to_rw_with_witness"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_rwx_to_rx_with_witness": {
      "abstract": [
        {
          "text": "Makes a region of memory executable for use in just-in-time (JIT) compilation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "be_memory_inline_jit_restrict_rwx_to_rx_with_witness"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_rwx_to_rx_with_witness",
      "kind": "symbol",
      "role": "symbol",
      "title": "be_memory_inline_jit_restrict_rwx_to_rx_with_witness",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_memory_inline_jit_restrict_rwx_to_rx_with_witness"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_with_witness_supported": {
      "abstract": [
        {
          "text": "Reports whether write protection for just-in-time (JIT) compilation is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "be_memory_inline_jit_restrict_with_witness_supported"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_with_witness_supported",
      "kind": "symbol",
      "role": "symbol",
      "title": "be_memory_inline_jit_restrict_with_witness_supported",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_memory_inline_jit_restrict_with_witness_supported"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BE_JIT_WRITE_PROTECT_TAG"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BE_JIT_WRITE_PROTECT_TAG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "JIT-compilation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_with_witness_supported",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_rwx_to_rw_with_witness",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_memory_inline_jit_restrict_rwx_to_rx_with_witness"
              ],
              "title": "JIT compilation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "BE_JIT_WRITE_PROTECT_TAG"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1BE_JIT_WRITE_PROTECT_TAG/title",
          "value": "BE_JIT_WRITE_PROTECT_TAG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1BE_JIT_WRITE_PROTECT_TAG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BE_JIT_WRITE_PROTECT_TAG"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/browserenginecore/be_jit_write_protect_tag"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/browserenginecore/be_jit_write_protect_tag"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
