{
  "abstract": [
    {
      "text": "Indicates that a request to receive kernel events needs to return without waiting for events.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "beta": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.3 beta 1",
        "16.3 beta 2"
      ]
    },
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_RETURN_IMMEDIATELY"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@BE_KEVENT_RETURN_IMMEDIATELY",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BE_KEVENT_RETURN_IMMEDIATELY"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "BrowserEngineCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BE_KEVENT_RETURN_IMMEDIATELY"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.4",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "BE_KEVENT_RETURN_IMMEDIATELY"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BE_KEVENT_RETURN_IMMEDIATELY"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this constant in the ",
              "type": "text"
            },
            {
              "code": "be_flags",
              "type": "codeVoice"
            },
            {
              "text": " parameter of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent(_:_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or the ",
              "type": "text"
            },
            {
              "code": "flags",
              "type": "codeVoice"
            },
            {
              "text": " parameter of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent64(_:_:_:_:_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", to poll for kernel events.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore": {
      "abstract": [
        {
          "text": "Integrate an alternative browser engine into your web browser app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore",
      "kind": "symbol",
      "role": "collection",
      "title": "BrowserEngineCore",
      "type": "topic",
      "url": "/documentation/browserenginecore"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_NO_FLAGS": {
      "abstract": [
        {
          "text": "Indicates that no flags are set in a request to receive kernel events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BE_KEVENT_NO_FLAGS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_NO_FLAGS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BE_KEVENT_NO_FLAGS"
        }
      ],
      "role": "symbol",
      "title": "BE_KEVENT_NO_FLAGS",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_kevent_no_flags"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_RETURN_IMMEDIATELY": {
      "abstract": [
        {
          "text": "Indicates that a request to receive kernel events needs to return without waiting for events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BE_KEVENT_RETURN_IMMEDIATELY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_RETURN_IMMEDIATELY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BE_KEVENT_RETURN_IMMEDIATELY"
        }
      ],
      "role": "symbol",
      "title": "BE_KEVENT_RETURN_IMMEDIATELY",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_kevent_return_immediately"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers for kernel events on the specified queue, and returns events that are pending on the queue, using 32-bit data types.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "be_kevent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@kevent",
          "text": "kevent"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@kevent",
          "text": "kevent"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "be_kevent"
        }
      ],
      "role": "symbol",
      "title": "be_kevent(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_kevent(_:_:_:_:_:_:)"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent64(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers for kernel events on the specified queue, and returns events that are pending on the queue, using 64-bit data types.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "be_kevent64"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@kevent64_s",
          "text": "kevent64_s"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@kevent64_s",
          "text": "kevent64_s"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent64(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "be_kevent64"
        }
      ],
      "role": "symbol",
      "title": "be_kevent64(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_kevent64(_:_:_:_:_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Kernel-events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent(_:_:_:_:_:_:)",
        "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent64(_:_:_:_:_:_:)",
        "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_NO_FLAGS"
      ],
      "title": "Kernel events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.4",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BE_KEVENT_RETURN_IMMEDIATELY"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BE_KEVENT_RETURN_IMMEDIATELY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Kernel-events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent(_:_:_:_:_:_:)",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent64(_:_:_:_:_:_:)",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_NO_FLAGS"
              ],
              "title": "Kernel events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "BE_KEVENT_RETURN_IMMEDIATELY"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1BE_KEVENT_NO_FLAGS/title",
          "value": "BE_KEVENT_NO_FLAGS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1BE_KEVENT_NO_FLAGS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BE_KEVENT_NO_FLAGS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1be_kevent64(_:_:_:_:_:_:)/title",
          "value": "be_kevent64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1be_kevent64(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "be_kevent64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1BE_KEVENT_RETURN_IMMEDIATELY/title",
          "value": "BE_KEVENT_RETURN_IMMEDIATELY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1BE_KEVENT_RETURN_IMMEDIATELY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BE_KEVENT_RETURN_IMMEDIATELY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1be_kevent(_:_:_:_:_:_:)/title",
          "value": "be_kevent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1be_kevent(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "be_kevent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/browserenginecore/be_kevent_return_immediately"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/browserenginecore/be_kevent_return_immediately"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
