{
  "abstract": [
    {
      "text": "Registers for kernel events on the specified queue, and returns events that are pending on the queue, using 32-bit data types.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent(_:_:_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@be_kevent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "be_kevent"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@kevent",
        "text": "kevent"
      },
      {
        "kind": "text",
        "text": ">!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@kevent",
        "text": "kevent"
      },
      {
        "kind": "text",
        "text": ">!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "BrowserEngineCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "be_kevent"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "be_kevent(_:_:_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "be_kevent"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "kq"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "changelist"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@kevent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@kevent",
              "text": "kevent"
            },
            {
              "kind": "text",
              "text": ">!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "nchanges"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "eventlist"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@kevent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@kevent",
              "text": "kevent"
            },
            {
              "kind": "text",
              "text": ">!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "nevents"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "be_flags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A file descriptor that identifies a kernel queue.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "kq"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of changes to make to the kernel queue.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "changelist"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of items in the ",
                  "type": "text"
                },
                {
                  "code": "changelist",
                  "type": "codeVoice"
                },
                {
                  "text": " array.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "nchanges"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of kernel events that this function fills on return, if any matching events are on the queue.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "eventlist"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of items in the ",
                  "type": "text"
                },
                {
                  "code": "eventlist",
                  "type": "codeVoice"
                },
                {
                  "text": " array.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "nevents"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Configuration flags that control how ",
                  "type": "text"
                },
                {
                  "code": "be_kevent",
                  "type": "codeVoice"
                },
                {
                  "text": " waits for kernel events.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "be_flags"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The number of events or errors that the function places in ",
              "type": "text"
            },
            {
              "code": "eventlist",
              "type": "codeVoice"
            },
            {
              "text": ", up to ",
              "type": "text"
            },
            {
              "code": "nevents",
              "type": "codeVoice"
            },
            {
              "text": ". If an error occurs and there isn’t space in ",
              "type": "text"
            },
            {
              "code": "eventlist",
              "type": "codeVoice"
            },
            {
              "text": " to write the error, ",
              "type": "text"
            },
            {
              "code": "be_kevent",
              "type": "codeVoice"
            },
            {
              "text": " returns ",
              "type": "text"
            },
            {
              "code": "-1",
              "type": "codeVoice"
            },
            {
              "text": " and sets ",
              "type": "text"
            },
            {
              "code": "errno",
              "type": "codeVoice"
            },
            {
              "text": " to indicate the error.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "To use 64-bit data types, call ",
                  "type": "text"
                },
                {
                  "code": "be_kevent64",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Call ",
              "type": "text"
            },
            {
              "code": "kqueue()",
              "type": "codeVoice"
            },
            {
              "text": " to create a kernel queue file descriptor that you pass to this function in the ",
              "type": "text"
            },
            {
              "code": "kq",
              "type": "codeVoice"
            },
            {
              "text": " parameter. ",
              "type": "text"
            },
            {
              "code": "kqueue()",
              "type": "codeVoice"
            },
            {
              "text": " returns a file descriptor on success; otherwise, it returns ",
              "type": "text"
            },
            {
              "code": "-1",
              "type": "codeVoice"
            },
            {
              "text": " and sets ",
              "type": "text"
            },
            {
              "code": "errno",
              "type": "codeVoice"
            },
            {
              "text": " to indicate the error.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "code": "EV_SET",
              "type": "codeVoice"
            },
            {
              "text": " macro to fill out ",
              "type": "text"
            },
            {
              "code": "struct kevent",
              "type": "codeVoice"
            },
            {
              "text": " structures with information about the events you want to receive, and store these structures in the ",
              "type": "text"
            },
            {
              "code": "changelist",
              "type": "codeVoice"
            },
            {
              "text": " array.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If ",
              "type": "text"
            },
            {
              "code": "be_kevent",
              "type": "codeVoice"
            },
            {
              "text": " encounters an error when there are fewer than ",
              "type": "text"
            },
            {
              "code": "nevents",
              "type": "codeVoice"
            },
            {
              "text": " events written to the ",
              "type": "text"
            },
            {
              "code": "eventlist",
              "type": "codeVoice"
            },
            {
              "text": " array, it adds an event that has the ",
              "type": "text"
            },
            {
              "code": "EV_ERROR",
              "type": "codeVoice"
            },
            {
              "text": " flag set in its ",
              "type": "text"
            },
            {
              "code": "flags",
              "type": "codeVoice"
            },
            {
              "text": " field, and the error information in its ",
              "type": "text"
            },
            {
              "code": "data",
              "type": "codeVoice"
            },
            {
              "text": " field. The ",
              "type": "text"
            },
            {
              "code": "be_kevent",
              "type": "codeVoice"
            },
            {
              "text": " function only returns ",
              "type": "text"
            },
            {
              "code": "-1",
              "type": "codeVoice"
            },
            {
              "text": " if it encounters an error that there isn’t space for it to record in ",
              "type": "text"
            },
            {
              "code": "eventlist",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can poll for events on ",
              "type": "text"
            },
            {
              "code": "kq",
              "type": "codeVoice"
            },
            {
              "text": " by passing ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_RETURN_IMMEDIATELY",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in the ",
              "type": "text"
            },
            {
              "code": "be_flags",
              "type": "codeVoice"
            },
            {
              "text": " argument. Otherwise, ",
              "type": "text"
            },
            {
              "code": "be_kevent64",
              "type": "codeVoice"
            },
            {
              "text": " waits until ",
              "type": "text"
            },
            {
              "code": "nevents",
              "type": "codeVoice"
            },
            {
              "text": " matching events occur on the queue.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore": {
      "abstract": [
        {
          "text": "Integrate an alternative browser engine into your web browser app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore",
      "kind": "symbol",
      "role": "collection",
      "title": "BrowserEngineCore",
      "type": "topic",
      "url": "/documentation/browserenginecore"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_NO_FLAGS": {
      "abstract": [
        {
          "text": "Indicates that no flags are set in a request to receive kernel events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BE_KEVENT_NO_FLAGS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_NO_FLAGS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BE_KEVENT_NO_FLAGS"
        }
      ],
      "role": "symbol",
      "title": "BE_KEVENT_NO_FLAGS",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_kevent_no_flags"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_RETURN_IMMEDIATELY": {
      "abstract": [
        {
          "text": "Indicates that a request to receive kernel events needs to return without waiting for events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BE_KEVENT_RETURN_IMMEDIATELY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_RETURN_IMMEDIATELY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BE_KEVENT_RETURN_IMMEDIATELY"
        }
      ],
      "role": "symbol",
      "title": "BE_KEVENT_RETURN_IMMEDIATELY",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_kevent_return_immediately"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers for kernel events on the specified queue, and returns events that are pending on the queue, using 32-bit data types.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "be_kevent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@kevent",
          "text": "kevent"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@kevent",
          "text": "kevent"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "be_kevent"
        }
      ],
      "role": "symbol",
      "title": "be_kevent(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_kevent(_:_:_:_:_:_:)"
    },
    "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent64(_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Registers for kernel events on the specified queue, and returns events that are pending on the queue, using 64-bit data types.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "be_kevent64"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@kevent64_s",
          "text": "kevent64_s"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@kevent64_s",
          "text": "kevent64_s"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent64(_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "be_kevent64"
        }
      ],
      "role": "symbol",
      "title": "be_kevent64(_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/browserenginecore/be_kevent64(_:_:_:_:_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@S@kevent": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@kevent",
      "kind": "symbol",
      "role": "symbol",
      "title": "kevent",
      "type": "topic",
      "url": "/documentation/kernel/kevent"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Kernel-events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent64(_:_:_:_:_:_:)",
        "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_NO_FLAGS",
        "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_RETURN_IMMEDIATELY"
      ],
      "title": "Kernel events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "be_kevent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "be_kevent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Kernel-events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/be_kevent64(_:_:_:_:_:_:)",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_NO_FLAGS",
                "doc://com.apple.BrowserEngineCore/documentation/BrowserEngineCore/BE_KEVENT_RETURN_IMMEDIATELY"
              ],
              "title": "Kernel events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:I",
                    "text": "int"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "be_kevent"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:I",
                    "text": "int"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "kq"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@kevent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@kevent",
                    "text": "kevent"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "changelist"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:I",
                    "text": "int"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "nchanges"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@kevent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@kevent",
                    "text": "kevent"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "eventlist"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:I",
                    "text": "int"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "nevents"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:i",
                    "text": "unsigned int"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "be_flags"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A file descriptor that identifies a kernel queue.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "kq"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of changes to make to the kernel queue.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "changelist"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The number of items in the ",
                        "type": "text"
                      },
                      {
                        "code": "changelist",
                        "type": "codeVoice"
                      },
                      {
                        "text": " array.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "nchanges"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of kernel events that this function fills on return, if any matching events are on the queue.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "eventlist"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The number of items in the ",
                        "type": "text"
                      },
                      {
                        "code": "eventlist",
                        "type": "codeVoice"
                      },
                      {
                        "text": " array.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "nevents"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Configuration flags that control how ",
                        "type": "text"
                      },
                      {
                        "code": "be_kevent",
                        "type": "codeVoice"
                      },
                      {
                        "text": " waits for kernel events.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "be_flags"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The number of events or errors that the function places in ",
                    "type": "text"
                  },
                  {
                    "code": "eventlist",
                    "type": "codeVoice"
                  },
                  {
                    "text": ", up to ",
                    "type": "text"
                  },
                  {
                    "code": "nevents",
                    "type": "codeVoice"
                  },
                  {
                    "text": ". If an error occurs and there isn’t space in ",
                    "type": "text"
                  },
                  {
                    "code": "eventlist",
                    "type": "codeVoice"
                  },
                  {
                    "text": " to write the error, ",
                    "type": "text"
                  },
                  {
                    "code": "be_kevent",
                    "type": "codeVoice"
                  },
                  {
                    "text": " returns ",
                    "type": "text"
                  },
                  {
                    "code": "-1",
                    "type": "codeVoice"
                  },
                  {
                    "text": " and sets ",
                    "type": "text"
                  },
                  {
                    "code": "errno",
                    "type": "codeVoice"
                  },
                  {
                    "text": " to indicate the error.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1BE_KEVENT_RETURN_IMMEDIATELY/title",
          "value": "BE_KEVENT_RETURN_IMMEDIATELY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1BE_KEVENT_RETURN_IMMEDIATELY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BE_KEVENT_RETURN_IMMEDIATELY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1BE_KEVENT_NO_FLAGS/title",
          "value": "BE_KEVENT_NO_FLAGS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1BE_KEVENT_NO_FLAGS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BE_KEVENT_NO_FLAGS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1be_kevent64(_:_:_:_:_:_:)/title",
          "value": "be_kevent64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1be_kevent64(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "be_kevent64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1be_kevent(_:_:_:_:_:_:)/title",
          "value": "be_kevent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.BrowserEngineCore~1documentation~1BrowserEngineCore~1be_kevent(_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "be_kevent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/browserenginecore/be_kevent(_:_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/browserenginecore/be_kevent(_:_:_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
