{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIReceiveBandwidth"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@BluetoothHCIReceiveBandwidth",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BluetoothHCIReceiveBandwidth"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BluetoothHCIReceiveBandwidth"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "BluetoothHCIReceiveBandwidth"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BluetoothHCIReceiveBandwidth"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAFHMode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAFHMode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAFHMode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothafhmode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAirMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAirMode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAirMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAirMode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAirMode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothairmode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAllowRoleSwitch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAllowRoleSwitch"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAllowRoleSwitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAllowRoleSwitch"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAllowRoleSwitch",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothallowroleswitch"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirements": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirements"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirements"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAuthenticationRequirements",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothauthenticationrequirements"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAuthenticationRequirementsValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothauthenticationrequirementsvalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothClassOfDevice"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothClassOfDevice"
        }
      ],
      "role": "symbol",
      "title": "BluetoothClassOfDevice",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothclassofdevice"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothClockOffset"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothClockOffset"
        }
      ],
      "role": "symbol",
      "title": "BluetoothClockOffset",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothclockoffset"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "role": "symbol",
      "title": "BluetoothCompanyIdentifers",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothcompanyidentifers"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothConnectionHandle"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothConnectionHandle"
        }
      ],
      "role": "symbol",
      "title": "BluetoothConnectionHandle",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothconnectionhandle"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothDeviceClassMajor"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothDeviceClassMajor"
        }
      ],
      "role": "symbol",
      "title": "BluetoothDeviceClassMajor",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothdeviceclassmajor"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothDeviceClassMinor"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothDeviceClassMinor"
        }
      ],
      "role": "symbol",
      "title": "BluetoothDeviceClassMinor",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothdeviceclassminor"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothDeviceName"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothDeviceName"
        }
      ],
      "role": "symbol",
      "title": "BluetoothDeviceName",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothdevicename"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEncryptionEnable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothEncryptionEnable"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEncryptionEnable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothEncryptionEnable"
        }
      ],
      "role": "symbol",
      "title": "BluetoothEncryptionEnable",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothencryptionenable"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothFeatureBits"
        }
      ],
      "role": "symbol",
      "title": "BluetoothFeatureBits",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothfeaturebits"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIACLDataByteCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIACLDataByteCount"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIACLDataByteCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIACLDataByteCount"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIACLDataByteCount",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhciacldatabytecount"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIReceiveBandwidth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIReceiveBandwidth"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIReceiveBandwidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIReceiveBandwidth"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIReceiveBandwidth",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcireceivebandwidth"
    },
    "doc://com.externally.resolved.symbol/c:@T@uint32_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint32_t",
      "type": "topic",
      "url": "/documentation/kernel/uint32_t"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHMode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAirMode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAllowRoleSwitch",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirements",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEncryptionEnable",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIACLDataByteCount"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BluetoothHCIReceiveBandwidth"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIReceiveBandwidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIReceiveBandwidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHMode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAirMode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAllowRoleSwitch",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirements",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEncryptionEnable",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIACLDataByteCount"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "BluetoothHCIReceiveBandwidth"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEncryptionEnable/title",
          "value": "BluetoothEncryptionEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEncryptionEnable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothEncryptionEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEncryptionEnable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothEncryptionEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClockOffset/title",
          "value": "BluetoothClockOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClockOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothClockOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClockOffset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothClockOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAirMode/title",
          "value": "BluetoothAirMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAirMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAirMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAirMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAirMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/title",
          "value": "BluetoothAuthenticationRequirementsValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirementsValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirementsValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHMode/title",
          "value": "BluetoothAFHMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAFHMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAFHMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIReceiveBandwidth/title",
          "value": "BluetoothHCIReceiveBandwidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIReceiveBandwidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIReceiveBandwidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIReceiveBandwidth/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIReceiveBandwidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAllowRoleSwitch/title",
          "value": "BluetoothAllowRoleSwitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAllowRoleSwitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAllowRoleSwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAllowRoleSwitch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAllowRoleSwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/title",
          "value": "BluetoothCompanyIdentifers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothCompanyIdentifers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothCompanyIdentifers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIACLDataByteCount/title",
          "value": "BluetoothHCIACLDataByteCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIACLDataByteCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIACLDataByteCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIACLDataByteCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIACLDataByteCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMinor/title",
          "value": "BluetoothDeviceClassMinor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMinor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceClassMinor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMinor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceClassMinor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirements/title",
          "value": "BluetoothAuthenticationRequirements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/title",
          "value": "BluetoothConnectionHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothConnectionHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothConnectionHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/title",
          "value": "BluetoothFeatureBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothFeatureBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothFeatureBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMajor/title",
          "value": "BluetoothDeviceClassMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceClassMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMajor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceClassMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClassOfDevice/title",
          "value": "BluetoothClassOfDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClassOfDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothClassOfDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClassOfDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothClassOfDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceName/title",
          "value": "BluetoothDeviceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothhcireceivebandwidth"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothhcireceivebandwidth"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
