{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingTypeDiscoverableUndirected"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BluetoothLEAdvertisingType@BluetoothLEAdvertisingTypeDiscoverableUndirected",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BluetoothLEAdvertisingTypeDiscoverableUndirected"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@BluetoothLEAdvertisingType",
        "text": "BluetoothLEAdvertisingType"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BluetoothLEAdvertisingTypeDiscoverableUndirected"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "BluetoothLEAdvertisingTypeDiscoverableUndirected"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BluetoothLEAdvertisingTypeDiscoverableUndirected"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@BluetoothLEAdvertisingType",
              "text": "BluetoothLEAdvertisingType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothLEAdvertisingType"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothLEAdvertisingType"
        }
      ],
      "role": "symbol",
      "title": "BluetoothLEAdvertisingType",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothleadvertisingtype"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingTypeConnectableDirected": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothLEAdvertisingTypeConnectableDirected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLEAdvertisingType",
          "text": "BluetoothLEAdvertisingType"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingTypeConnectableDirected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothLEAdvertisingTypeConnectableDirected"
        }
      ],
      "role": "symbol",
      "title": "BluetoothLEAdvertisingTypeConnectableDirected",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothleadvertisingtypeconnectabledirected"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingTypeConnectableUndirected": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothLEAdvertisingTypeConnectableUndirected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLEAdvertisingType",
          "text": "BluetoothLEAdvertisingType"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingTypeConnectableUndirected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothLEAdvertisingTypeConnectableUndirected"
        }
      ],
      "role": "symbol",
      "title": "BluetoothLEAdvertisingTypeConnectableUndirected",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothleadvertisingtypeconnectableundirected"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingTypeDiscoverableUndirected": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothLEAdvertisingTypeDiscoverableUndirected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLEAdvertisingType",
          "text": "BluetoothLEAdvertisingType"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingTypeDiscoverableUndirected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothLEAdvertisingTypeDiscoverableUndirected"
        }
      ],
      "role": "symbol",
      "title": "BluetoothLEAdvertisingTypeDiscoverableUndirected",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothleadvertisingtypediscoverableundirected"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingTypeNonConnectableUndirected": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothLEAdvertisingTypeNonConnectableUndirected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLEAdvertisingType",
          "text": "BluetoothLEAdvertisingType"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingTypeNonConnectableUndirected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothLEAdvertisingTypeNonConnectableUndirected"
        }
      ],
      "role": "symbol",
      "title": "BluetoothLEAdvertisingTypeNonConnectableUndirected",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothleadvertisingtypenonconnectableundirected"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingTypeScanResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothLEAdvertisingTypeScanResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLEAdvertisingType",
          "text": "BluetoothLEAdvertisingType"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingTypeScanResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothLEAdvertisingTypeScanResponse"
        }
      ],
      "role": "symbol",
      "title": "BluetoothLEAdvertisingTypeScanResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothleadvertisingtypescanresponse"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingTypeConnectableDirected",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingTypeConnectableUndirected",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingTypeNonConnectableUndirected",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingTypeScanResponse"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BluetoothLEAdvertisingTypeDiscoverableUndirected"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLEAdvertisingTypeDiscoverableUndirected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingTypeConnectableDirected",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingTypeConnectableUndirected",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingTypeNonConnectableUndirected",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEAdvertisingTypeScanResponse"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "BluetoothLEAdvertisingTypeDiscoverableUndirected"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLEAdvertisingTypeNonConnectableUndirected/title",
          "value": "BluetoothLEAdvertisingTypeNonConnectableUndirected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLEAdvertisingTypeNonConnectableUndirected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLEAdvertisingTypeNonConnectableUndirected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLEAdvertisingTypeScanResponse/title",
          "value": "BluetoothLEAdvertisingTypeScanResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLEAdvertisingTypeScanResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLEAdvertisingTypeScanResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLEAdvertisingTypeDiscoverableUndirected/title",
          "value": "BluetoothLEAdvertisingTypeDiscoverableUndirected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLEAdvertisingTypeDiscoverableUndirected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLEAdvertisingTypeDiscoverableUndirected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLEAdvertisingTypeConnectableDirected/title",
          "value": "BluetoothLEAdvertisingTypeConnectableDirected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLEAdvertisingTypeConnectableDirected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLEAdvertisingTypeConnectableDirected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLEAdvertisingTypeConnectableUndirected/title",
          "value": "BluetoothLEAdvertisingTypeConnectableUndirected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLEAdvertisingTypeConnectableUndirected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLEAdvertisingTypeConnectableUndirected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLEAdvertisingType/title",
          "value": "BluetoothLEAdvertisingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLEAdvertisingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLEAdvertisingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLEAdvertisingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLEAdvertisingType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothleadvertisingtypediscoverableundirected"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothleadvertisingtypediscoverableundirected"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
