{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothGAPAppearance-constants-2lmnv"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "BluetoothGAPAppearance constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPCommandRejectReason"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPCommandRejectReason"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPCommandRejectReason",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampcommandrejectreason"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPCreatePhysicalLinkResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampcreatephysicallinkresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPDisconnectPhysicalLinkResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampdisconnectphysicallinkresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPDiscoverResponseControllerStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampdiscoverresponsecontrollerstatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetAssocResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetAssocResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPGetAssocResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampgetassocresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetInfoResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetInfoResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPGetInfoResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampgetinforesponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPManagerCode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampmanagercode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIPowerState"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIPowerState"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIPowerState",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcipowerstate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPCommandCode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capcommandcode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandRejectReason"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandRejectReason"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPCommandRejectReason",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capcommandrejectreason"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationOption"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationOption"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConfigurationOption",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconfigurationoption"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationResult"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConfigurationResult",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconfigurationresult"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconfigurationretransmissionandflowcontrolflags"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConnectionResult",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconnectionresult"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConnectionStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconnectionstatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Enumerations",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-enumerations"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericBarcodeScanner": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericBarcodeScanner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericBarcodeScanner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericBarcodeScanner"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericBarcodeScanner",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericbarcodescanner"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericBloodPressure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericBloodPressure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericBloodPressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericBloodPressure"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericBloodPressure",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericbloodpressure"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericClock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericClock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericClock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericClock"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericClock",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericclock"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericComputer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericComputer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericComputer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericComputer"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericComputer",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericcomputer"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericCycling": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericCycling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericCycling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericCycling"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericCycling",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericcycling"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericDisplay": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericDisplay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericDisplay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericDisplay"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericDisplay",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericdisplay"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericEyeGlasses": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericEyeGlasses"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericEyeGlasses",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericEyeGlasses"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericEyeGlasses",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericeyeglasses"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericGlucoseMeter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericGlucoseMeter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericGlucoseMeter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericGlucoseMeter"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericGlucoseMeter",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericglucosemeter"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericHeartrateSensor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericHeartrateSensor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericHeartrateSensor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericHeartrateSensor"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericHeartrateSensor",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericheartratesensor"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericHumanInterfaceDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericHumanInterfaceDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericHumanInterfaceDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericHumanInterfaceDevice"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericHumanInterfaceDevice",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenerichumaninterfacedevice"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericKeyring": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericKeyring"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericKeyring",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericKeyring"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericKeyring",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenerickeyring"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericMediaPlayer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericMediaPlayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericMediaPlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericMediaPlayer"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericMediaPlayer",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericmediaplayer"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericPhone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericPhone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericPhone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericPhone"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericPhone",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericphone"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericRemoteControl": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericRemoteControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericRemoteControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericRemoteControl"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericRemoteControl",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericremotecontrol"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericRunningWalkingSensor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericRunningWalkingSensor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericRunningWalkingSensor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericRunningWalkingSensor"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericRunningWalkingSensor",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericrunningwalkingsensor"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericTag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericTag"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericTag",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenerictag"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericThermometer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericThermometer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericThermometer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericThermometer"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericThermometer",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericthermometer"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericWatch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericWatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericWatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericWatch"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericWatch",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericwatch"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceBarcodeScanner": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceBarcodeScanner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceBarcodeScanner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceBarcodeScanner"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceHumanInterfaceDeviceBarcodeScanner",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancehumaninterfacedevicebarcodescanner"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceCardReader": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceCardReader"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceCardReader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceCardReader"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceHumanInterfaceDeviceCardReader",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancehumaninterfacedevicecardreader"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceDigitalPen": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceDigitalPen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceDigitalPen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceDigitalPen"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceHumanInterfaceDeviceDigitalPen",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancehumaninterfacedevicedigitalpen"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceDigitizerTablet": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceDigitizerTablet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceDigitizerTablet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceDigitizerTablet"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceHumanInterfaceDeviceDigitizerTablet",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancehumaninterfacedevicedigitizertablet"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceGamepad": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceGamepad"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceGamepad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceGamepad"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceHumanInterfaceDeviceGamepad",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancehumaninterfacedevicegamepad"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceJoystick": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceJoystick"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceJoystick",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceJoystick"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceHumanInterfaceDeviceJoystick",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancehumaninterfacedevicejoystick"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceKeyboard": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceKeyboard"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceKeyboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceKeyboard"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceHumanInterfaceDeviceKeyboard",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancehumaninterfacedevicekeyboard"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceMouse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceMouse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceMouse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceMouse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceHumanInterfaceDeviceMouse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancehumaninterfacedevicemouse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceUnknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceUnknown"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceUnknown",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearanceunknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericBarcodeScanner",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericBloodPressure",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericClock",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericComputer",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericCycling",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericDisplay",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericEyeGlasses",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericGlucoseMeter",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericHeartrateSensor",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericHumanInterfaceDevice",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericKeyring",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericMediaPlayer",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericPhone",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericRemoteControl",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericRunningWalkingSensor",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericTag",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericThermometer",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericWatch",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceBarcodeScanner",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceCardReader",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceDigitalPen",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceDigitizerTablet",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceGamepad",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceJoystick",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceKeyboard",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceMouse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceUnknown"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericBarcodeScanner",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericBloodPressure",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericClock",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericComputer",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericCycling",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericDisplay",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericEyeGlasses",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericGlucoseMeter",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericHeartrateSensor",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericHumanInterfaceDevice",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericKeyring",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericMediaPlayer",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericPhone",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericRemoteControl",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericRunningWalkingSensor",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericTag",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericThermometer",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericWatch",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceBarcodeScanner",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceCardReader",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceDigitalPen",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceDigitizerTablet",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceGamepad",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceJoystick",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceKeyboard",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceHumanInterfaceDeviceMouse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceUnknown"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/title",
          "value": "BluetoothAMPManagerCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPManagerCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPManagerCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionStatus/title",
          "value": "BluetoothL2CAPConnectionStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericBarcodeScanner/title",
          "value": "kBluetoothGAPAppearanceGenericBarcodeScanner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericBarcodeScanner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericBarcodeScanner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceHumanInterfaceDeviceBarcodeScanner/title",
          "value": "kBluetoothGAPAppearanceHumanInterfaceDeviceBarcodeScanner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceHumanInterfaceDeviceBarcodeScanner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceBarcodeScanner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPowerState/title",
          "value": "BluetoothHCIPowerState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPowerState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIPowerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPowerState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIPowerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceHumanInterfaceDeviceDigitizerTablet/title",
          "value": "kBluetoothGAPAppearanceHumanInterfaceDeviceDigitizerTablet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceHumanInterfaceDeviceDigitizerTablet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceDigitizerTablet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandCode/title",
          "value": "BluetoothL2CAPCommandCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/title",
          "value": "BluetoothAMPDiscoverResponseControllerStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDiscoverResponseControllerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDiscoverResponseControllerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/title",
          "value": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericClock/title",
          "value": "kBluetoothGAPAppearanceGenericClock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericClock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericClock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericPhone/title",
          "value": "kBluetoothGAPAppearanceGenericPhone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericPhone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericPhone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericDisplay/title",
          "value": "kBluetoothGAPAppearanceGenericDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericDisplay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericComputer/title",
          "value": "kBluetoothGAPAppearanceGenericComputer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericComputer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericComputer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionResult/title",
          "value": "BluetoothL2CAPConnectionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericWatch/title",
          "value": "kBluetoothGAPAppearanceGenericWatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericWatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericWatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericHumanInterfaceDevice/title",
          "value": "kBluetoothGAPAppearanceGenericHumanInterfaceDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericHumanInterfaceDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericHumanInterfaceDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericMediaPlayer/title",
          "value": "kBluetoothGAPAppearanceGenericMediaPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericMediaPlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericMediaPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericRunningWalkingSensor/title",
          "value": "kBluetoothGAPAppearanceGenericRunningWalkingSensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericRunningWalkingSensor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericRunningWalkingSensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericBloodPressure/title",
          "value": "kBluetoothGAPAppearanceGenericBloodPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericBloodPressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericBloodPressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/title",
          "value": "BluetoothAMPCommandRejectReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceHumanInterfaceDeviceGamepad/title",
          "value": "kBluetoothGAPAppearanceHumanInterfaceDeviceGamepad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceHumanInterfaceDeviceGamepad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceGamepad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericEyeGlasses/title",
          "value": "kBluetoothGAPAppearanceGenericEyeGlasses"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericEyeGlasses/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericEyeGlasses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceHumanInterfaceDeviceDigitalPen/title",
          "value": "kBluetoothGAPAppearanceHumanInterfaceDeviceDigitalPen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceHumanInterfaceDeviceDigitalPen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceDigitalPen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericCycling/title",
          "value": "kBluetoothGAPAppearanceGenericCycling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericCycling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericCycling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/title",
          "value": "BluetoothAMPGetAssocResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetAssocResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetAssocResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericHeartrateSensor/title",
          "value": "kBluetoothGAPAppearanceGenericHeartrateSensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericHeartrateSensor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericHeartrateSensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceHumanInterfaceDeviceKeyboard/title",
          "value": "kBluetoothGAPAppearanceHumanInterfaceDeviceKeyboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceHumanInterfaceDeviceKeyboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceKeyboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceHumanInterfaceDeviceCardReader/title",
          "value": "kBluetoothGAPAppearanceHumanInterfaceDeviceCardReader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceHumanInterfaceDeviceCardReader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceCardReader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationOption/title",
          "value": "BluetoothL2CAPConfigurationOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceUnknown/title",
          "value": "kBluetoothGAPAppearanceUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags/title",
          "value": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericRemoteControl/title",
          "value": "kBluetoothGAPAppearanceGenericRemoteControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericRemoteControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericRemoteControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericTag/title",
          "value": "kBluetoothGAPAppearanceGenericTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceHumanInterfaceDeviceJoystick/title",
          "value": "kBluetoothGAPAppearanceHumanInterfaceDeviceJoystick"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceHumanInterfaceDeviceJoystick/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceJoystick"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/title",
          "value": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationResult/title",
          "value": "BluetoothL2CAPConfigurationResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericKeyring/title",
          "value": "kBluetoothGAPAppearanceGenericKeyring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericKeyring/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericKeyring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/title",
          "value": "BluetoothAMPGetInfoResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetInfoResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetInfoResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceHumanInterfaceDeviceMouse/title",
          "value": "kBluetoothGAPAppearanceHumanInterfaceDeviceMouse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceHumanInterfaceDeviceMouse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceHumanInterfaceDeviceMouse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericGlucoseMeter/title",
          "value": "kBluetoothGAPAppearanceGenericGlucoseMeter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericGlucoseMeter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericGlucoseMeter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericThermometer/title",
          "value": "kBluetoothGAPAppearanceGenericThermometer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericThermometer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericThermometer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandRejectReason/title",
          "value": "BluetoothL2CAPCommandRejectReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandRejectReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandRejectReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandRejectReason"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothgapappearance-constants-2lmnv"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothgapappearance-constants-2lmnv"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
