{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@BluetoothHCIRequestCallbackInfo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BluetoothHCIRequestCallbackInfo"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BluetoothHCIRequestCallbackInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "BluetoothHCIRequestCallbackInfo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BluetoothHCIRequestCallbackInfo"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHHostChannelClassification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAFHHostChannelClassification"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHHostChannelClassification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAFHHostChannelClassification"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAFHHostChannelClassification",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothafhhostchannelclassification"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHResults": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAFHResults"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHResults",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAFHResults"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAFHResults",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothafhresults"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPCommandRejectReason"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPCommandRejectReason"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPCommandRejectReason",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampcommandrejectreason"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPCreatePhysicalLinkResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampcreatephysicallinkresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPDisconnectPhysicalLinkResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampdisconnectphysicallinkresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPDiscoverResponseControllerStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampdiscoverresponsecontrollerstatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetAssocResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetAssocResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPGetAssocResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampgetassocresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetInfoResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetInfoResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPGetInfoResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampgetinforesponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPManagerCode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampmanagercode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAuthenticationRequirementsValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothauthenticationrequirementsvalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "role": "symbol",
      "title": "BluetoothCompanyIdentifers",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothcompanyidentifers"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothDeviceAddress"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothDeviceAddress"
        }
      ],
      "role": "symbol",
      "title": "BluetoothDeviceAddress",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothdeviceaddress"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEnhancedSynchronousConnectionInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothEnhancedSynchronousConnectionInfo"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEnhancedSynchronousConnectionInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothEnhancedSynchronousConnectionInfo"
        }
      ],
      "role": "symbol",
      "title": "BluetoothEnhancedSynchronousConnectionInfo",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEventFilterCondition": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothEventFilterCondition"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEventFilterCondition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothEventFilterCondition"
        }
      ],
      "role": "symbol",
      "title": "BluetoothEventFilterCondition",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetootheventfiltercondition"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothFeatureBits"
        }
      ],
      "role": "symbol",
      "title": "BluetoothFeatureBits",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothfeaturebits"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIRequestCallbackInfo"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIRequestCallbackInfo"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIRequestCallbackInfo",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcirequestcallbackinfo"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/asyncIDRefCon": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "asyncIDRefCon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@mach_vm_address_t",
          "text": "mach_vm_address_t"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/asyncIDRefCon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "asyncIDRefCon"
        }
      ],
      "role": "symbol",
      "title": "asyncIDRefCon",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcirequestcallbackinfo/asyncidrefcon"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcirequestcallbackinfo/init()"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/init(userCallback:userRefCon:internalRefCon:asyncIDRefCon:reserved:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "userCallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@mach_vm_address_t",
          "text": "mach_vm_address_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userRefCon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@mach_vm_address_t",
          "text": "mach_vm_address_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "internalRefCon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@mach_vm_address_t",
          "text": "mach_vm_address_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "asyncIDRefCon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@mach_vm_address_t",
          "text": "mach_vm_address_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@mach_vm_address_t",
          "text": "mach_vm_address_t"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/init(userCallback:userRefCon:internalRefCon:asyncIDRefCon:reserved:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(userCallback:userRefCon:internalRefCon:asyncIDRefCon:reserved:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcirequestcallbackinfo/init(usercallback:userrefcon:internalrefcon:asyncidrefcon:reserved:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/internalRefCon": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalRefCon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@mach_vm_address_t",
          "text": "mach_vm_address_t"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/internalRefCon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "internalRefCon"
        }
      ],
      "role": "symbol",
      "title": "internalRefCon",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcirequestcallbackinfo/internalrefcon"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@mach_vm_address_t",
          "text": "mach_vm_address_t"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reserved"
        }
      ],
      "role": "symbol",
      "title": "reserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcirequestcallbackinfo/reserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/userCallback": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userCallback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@mach_vm_address_t",
          "text": "mach_vm_address_t"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/userCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userCallback"
        }
      ],
      "role": "symbol",
      "title": "userCallback",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcirequestcallbackinfo/usercallback"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/userRefCon": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userRefCon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@mach_vm_address_t",
          "text": "mach_vm_address_t"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/userRefCon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userRefCon"
        }
      ],
      "role": "symbol",
      "title": "userRefCon",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcirequestcallbackinfo/userrefcon"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHHostChannelClassification",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHResults",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceAddress",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEnhancedSynchronousConnectionInfo",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEventFilterCondition",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits"
      ],
      "title": "Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/init()",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/init(userCallback:userRefCon:internalRefCon:asyncIDRefCon:reserved:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/asyncIDRefCon",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/internalRefCon",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/reserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/userCallback",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/userRefCon"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BluetoothHCIRequestCallbackInfo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIRequestCallbackInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIRequestCallbackInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/asyncIDRefCon",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/internalRefCon",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/reserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/userCallback",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIRequestCallbackInfo/userRefCon"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHHostChannelClassification",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHResults",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceAddress",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEnhancedSynchronousConnectionInfo",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEventFilterCondition",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "BluetoothHCIRequestCallbackInfo"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/title",
          "value": "BluetoothFeatureBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothFeatureBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothFeatureBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceAddress/title",
          "value": "BluetoothDeviceAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIRequestCallbackInfo/title",
          "value": "BluetoothHCIRequestCallbackInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIRequestCallbackInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIRequestCallbackInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIRequestCallbackInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIRequestCallbackInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/title",
          "value": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIRequestCallbackInfo~1reserved/title",
          "value": "reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIRequestCallbackInfo~1reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIRequestCallbackInfo~1userRefCon/title",
          "value": "userRefCon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIRequestCallbackInfo~1userRefCon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userRefCon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEventFilterCondition/title",
          "value": "BluetoothEventFilterCondition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEventFilterCondition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothEventFilterCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEventFilterCondition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothEventFilterCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIRequestCallbackInfo~1internalRefCon/title",
          "value": "internalRefCon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIRequestCallbackInfo~1internalRefCon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "internalRefCon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEnhancedSynchronousConnectionInfo/title",
          "value": "BluetoothEnhancedSynchronousConnectionInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEnhancedSynchronousConnectionInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothEnhancedSynchronousConnectionInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEnhancedSynchronousConnectionInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothEnhancedSynchronousConnectionInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/title",
          "value": "BluetoothAMPDiscoverResponseControllerStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDiscoverResponseControllerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDiscoverResponseControllerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHHostChannelClassification/title",
          "value": "BluetoothAFHHostChannelClassification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHHostChannelClassification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAFHHostChannelClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHHostChannelClassification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAFHHostChannelClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIRequestCallbackInfo~1userCallback/title",
          "value": "userCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIRequestCallbackInfo~1userCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/title",
          "value": "BluetoothAMPManagerCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPManagerCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPManagerCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/title",
          "value": "BluetoothAMPCommandRejectReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/title",
          "value": "BluetoothCompanyIdentifers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothCompanyIdentifers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothCompanyIdentifers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/title",
          "value": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIRequestCallbackInfo~1asyncIDRefCon/title",
          "value": "asyncIDRefCon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIRequestCallbackInfo~1asyncIDRefCon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "asyncIDRefCon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHResults/title",
          "value": "BluetoothAFHResults"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHResults/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAFHResults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHResults/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAFHResults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/title",
          "value": "BluetoothAMPGetAssocResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetAssocResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetAssocResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/title",
          "value": "BluetoothAMPGetInfoResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetInfoResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetInfoResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/title",
          "value": "BluetoothAuthenticationRequirementsValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirementsValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirementsValues"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothhcirequestcallbackinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothhcirequestcallbackinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
