{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@BluetoothHCIEnhancedSetupSynchronousConnectionParams",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BluetoothHCIEnhancedSetupSynchronousConnectionParams"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BluetoothHCIEnhancedSetupSynchronousConnectionParams"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "BluetoothHCIEnhancedSetupSynchronousConnectionParams"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BluetoothHCIEnhancedSetupSynchronousConnectionParams"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHHostChannelClassification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAFHHostChannelClassification"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHHostChannelClassification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAFHHostChannelClassification"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAFHHostChannelClassification",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothafhhostchannelclassification"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHResults": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAFHResults"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHResults",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAFHResults"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAFHResults",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothafhresults"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPCommandRejectReason"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPCommandRejectReason"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPCommandRejectReason",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampcommandrejectreason"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPCreatePhysicalLinkResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampcreatephysicallinkresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPDisconnectPhysicalLinkResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampdisconnectphysicallinkresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPDiscoverResponseControllerStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampdiscoverresponsecontrollerstatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetAssocResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetAssocResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPGetAssocResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampgetassocresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetInfoResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetInfoResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPGetInfoResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampgetinforesponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPManagerCode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampmanagercode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAuthenticationRequirementsValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothauthenticationrequirementsvalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "role": "symbol",
      "title": "BluetoothCompanyIdentifers",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothcompanyidentifers"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothDeviceAddress"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothDeviceAddress"
        }
      ],
      "role": "symbol",
      "title": "BluetoothDeviceAddress",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothdeviceaddress"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEnhancedSynchronousConnectionInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothEnhancedSynchronousConnectionInfo"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEnhancedSynchronousConnectionInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothEnhancedSynchronousConnectionInfo"
        }
      ],
      "role": "symbol",
      "title": "BluetoothEnhancedSynchronousConnectionInfo",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEventFilterCondition": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothEventFilterCondition"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEventFilterCondition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothEventFilterCondition"
        }
      ],
      "role": "symbol",
      "title": "BluetoothEventFilterCondition",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetootheventfiltercondition"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothFeatureBits"
        }
      ],
      "role": "symbol",
      "title": "BluetoothFeatureBits",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothfeaturebits"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIEnhancedSetupSynchronousConnectionParams"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIEnhancedSetupSynchronousConnectionParams"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIEnhancedSetupSynchronousConnectionParams",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/init()"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/init(transmitBandwidth:receiveBandwidth:transmitCodingFormat:receiveCodingFormat:transmitCodecFrameSize:receiveCodecFrameSize:inputBandwidth:outputBandwidth:inputCodingFormat:outputCodingFormat:inputCodedDataSize:outputCodedDataSize:inputPCMDataFormat:outputPCMDataFormat:inputPCMSamplePayloadMSBPosition:outputPCMSamplePayloadMSBPosition:inputDataPath:outputDataPath:inputTransportUnitSize:outputTransportUnitSize:maxLatency:packetType:retransmissionEffort:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "transmitBandwidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "receiveBandwidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "transmitCodingFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "receiveCodingFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "transmitCodecFrameSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "receiveCodecFrameSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inputBandwidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "outputBandwidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inputCodingFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "outputCodingFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inputCodedDataSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "outputCodedDataSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inputPCMDataFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "outputPCMDataFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inputPCMSamplePayloadMSBPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "outputPCMSamplePayloadMSBPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inputDataPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "outputDataPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inputTransportUnitSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "outputTransportUnitSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "maxLatency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "packetType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "retransmissionEffort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/init(transmitBandwidth:receiveBandwidth:transmitCodingFormat:receiveCodingFormat:transmitCodecFrameSize:receiveCodecFrameSize:inputBandwidth:outputBandwidth:inputCodingFormat:outputCodingFormat:inputCodedDataSize:outputCodedDataSize:inputPCMDataFormat:outputPCMDataFormat:inputPCMSamplePayloadMSBPosition:outputPCMSamplePayloadMSBPosition:inputDataPath:outputDataPath:inputTransportUnitSize:outputTransportUnitSize:maxLatency:packetType:retransmissionEffort:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(transmitBandwidth:receiveBandwidth:transmitCodingFormat:receiveCodingFormat:transmitCodecFrameSize:receiveCodecFrameSize:inputBandwidth:outputBandwidth:inputCodingFormat:outputCodingFormat:inputCodedDataSize:outputCodedDataSize:inputPCMDataFormat:outputPCMDataFormat:inputPCMSamplePayloadMSBPosition:outputPCMSamplePayloadMSBPosition:inputDataPath:outputDataPath:inputTransportUnitSize:outputTransportUnitSize:maxLatency:packetType:retransmissionEffort:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/init(transmitbandwidth:receivebandwidth:transmitcodingformat:receivecodingformat:transmitcodecframesize:receivecodecframesize:inputbandwidth:outputbandwidth:inputcodingformat:outputcodingformat:inputcodeddatasize:outputcodeddatasize:inputpc-4r4o8"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputBandwidth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputBandwidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputBandwidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputBandwidth"
        }
      ],
      "role": "symbol",
      "title": "inputBandwidth",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/inputbandwidth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputCodedDataSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputCodedDataSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputCodedDataSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputCodedDataSize"
        }
      ],
      "role": "symbol",
      "title": "inputCodedDataSize",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/inputcodeddatasize"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputCodingFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputCodingFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputCodingFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputCodingFormat"
        }
      ],
      "role": "symbol",
      "title": "inputCodingFormat",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/inputcodingformat"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputDataPath": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputDataPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputDataPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputDataPath"
        }
      ],
      "role": "symbol",
      "title": "inputDataPath",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/inputdatapath"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputPCMDataFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputPCMDataFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputPCMDataFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputPCMDataFormat"
        }
      ],
      "role": "symbol",
      "title": "inputPCMDataFormat",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/inputpcmdataformat"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputPCMSamplePayloadMSBPosition": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputPCMSamplePayloadMSBPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputPCMSamplePayloadMSBPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputPCMSamplePayloadMSBPosition"
        }
      ],
      "role": "symbol",
      "title": "inputPCMSamplePayloadMSBPosition",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/inputpcmsamplepayloadmsbposition"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputTransportUnitSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputTransportUnitSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputTransportUnitSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputTransportUnitSize"
        }
      ],
      "role": "symbol",
      "title": "inputTransportUnitSize",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/inputtransportunitsize"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/maxLatency": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxLatency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/maxLatency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxLatency"
        }
      ],
      "role": "symbol",
      "title": "maxLatency",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/maxlatency"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputBandwidth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputBandwidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputBandwidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputBandwidth"
        }
      ],
      "role": "symbol",
      "title": "outputBandwidth",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/outputbandwidth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputCodedDataSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputCodedDataSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputCodedDataSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputCodedDataSize"
        }
      ],
      "role": "symbol",
      "title": "outputCodedDataSize",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/outputcodeddatasize"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputCodingFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputCodingFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputCodingFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputCodingFormat"
        }
      ],
      "role": "symbol",
      "title": "outputCodingFormat",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/outputcodingformat"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputDataPath": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputDataPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputDataPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputDataPath"
        }
      ],
      "role": "symbol",
      "title": "outputDataPath",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/outputdatapath"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputPCMDataFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputPCMDataFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputPCMDataFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputPCMDataFormat"
        }
      ],
      "role": "symbol",
      "title": "outputPCMDataFormat",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/outputpcmdataformat"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputPCMSamplePayloadMSBPosition": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputPCMSamplePayloadMSBPosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputPCMSamplePayloadMSBPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputPCMSamplePayloadMSBPosition"
        }
      ],
      "role": "symbol",
      "title": "outputPCMSamplePayloadMSBPosition",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/outputpcmsamplepayloadmsbposition"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputTransportUnitSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputTransportUnitSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputTransportUnitSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputTransportUnitSize"
        }
      ],
      "role": "symbol",
      "title": "outputTransportUnitSize",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/outputtransportunitsize"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/packetType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "packetType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/packetType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "packetType"
        }
      ],
      "role": "symbol",
      "title": "packetType",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/packettype"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/receiveBandwidth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "receiveBandwidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/receiveBandwidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "receiveBandwidth"
        }
      ],
      "role": "symbol",
      "title": "receiveBandwidth",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/receivebandwidth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/receiveCodecFrameSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "receiveCodecFrameSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/receiveCodecFrameSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "receiveCodecFrameSize"
        }
      ],
      "role": "symbol",
      "title": "receiveCodecFrameSize",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/receivecodecframesize"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/receiveCodingFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "receiveCodingFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/receiveCodingFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "receiveCodingFormat"
        }
      ],
      "role": "symbol",
      "title": "receiveCodingFormat",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/receivecodingformat"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/retransmissionEffort": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "retransmissionEffort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/retransmissionEffort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "retransmissionEffort"
        }
      ],
      "role": "symbol",
      "title": "retransmissionEffort",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/retransmissioneffort"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/transmitBandwidth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transmitBandwidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/transmitBandwidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transmitBandwidth"
        }
      ],
      "role": "symbol",
      "title": "transmitBandwidth",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/transmitbandwidth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/transmitCodecFrameSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transmitCodecFrameSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/transmitCodecFrameSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transmitCodecFrameSize"
        }
      ],
      "role": "symbol",
      "title": "transmitCodecFrameSize",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/transmitcodecframesize"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/transmitCodingFormat": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transmitCodingFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/transmitCodingFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transmitCodingFormat"
        }
      ],
      "role": "symbol",
      "title": "transmitCodingFormat",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams/transmitcodingformat"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHHostChannelClassification",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHResults",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceAddress",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEnhancedSynchronousConnectionInfo",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEventFilterCondition",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits"
      ],
      "title": "Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/init()",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/init(transmitBandwidth:receiveBandwidth:transmitCodingFormat:receiveCodingFormat:transmitCodecFrameSize:receiveCodecFrameSize:inputBandwidth:outputBandwidth:inputCodingFormat:outputCodingFormat:inputCodedDataSize:outputCodedDataSize:inputPCMDataFormat:outputPCMDataFormat:inputPCMSamplePayloadMSBPosition:outputPCMSamplePayloadMSBPosition:inputDataPath:outputDataPath:inputTransportUnitSize:outputTransportUnitSize:maxLatency:packetType:retransmissionEffort:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputBandwidth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputCodedDataSize",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputCodingFormat",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputDataPath",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputPCMDataFormat",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputPCMSamplePayloadMSBPosition",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputTransportUnitSize",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/maxLatency",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputBandwidth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputCodedDataSize",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputCodingFormat",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputDataPath",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputPCMDataFormat",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputPCMSamplePayloadMSBPosition",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputTransportUnitSize",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/packetType",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/receiveBandwidth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/receiveCodecFrameSize",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/receiveCodingFormat",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/retransmissionEffort",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/transmitBandwidth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/transmitCodecFrameSize",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/transmitCodingFormat"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BluetoothHCIEnhancedSetupSynchronousConnectionParams"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIEnhancedSetupSynchronousConnectionParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIEnhancedSetupSynchronousConnectionParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputBandwidth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputCodedDataSize",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputCodingFormat",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputDataPath",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputPCMDataFormat",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputPCMSamplePayloadMSBPosition",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/inputTransportUnitSize",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/maxLatency",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputBandwidth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputCodedDataSize",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputCodingFormat",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputDataPath",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputPCMDataFormat",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputPCMSamplePayloadMSBPosition",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/outputTransportUnitSize",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/packetType",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/receiveBandwidth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/receiveCodecFrameSize",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/receiveCodingFormat",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/retransmissionEffort",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/transmitBandwidth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/transmitCodecFrameSize",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEnhancedSetupSynchronousConnectionParams/transmitCodingFormat"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHHostChannelClassification",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHResults",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceAddress",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEnhancedSynchronousConnectionInfo",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEventFilterCondition",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "BluetoothHCIEnhancedSetupSynchronousConnectionParams"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1transmitBandwidth/title",
          "value": "transmitBandwidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1transmitBandwidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transmitBandwidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/title",
          "value": "BluetoothFeatureBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothFeatureBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothFeatureBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1inputDataPath/title",
          "value": "inputDataPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1inputDataPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputDataPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1outputBandwidth/title",
          "value": "outputBandwidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1outputBandwidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputBandwidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams/title",
          "value": "BluetoothHCIEnhancedSetupSynchronousConnectionParams"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIEnhancedSetupSynchronousConnectionParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIEnhancedSetupSynchronousConnectionParams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1inputPCMSamplePayloadMSBPosition/title",
          "value": "inputPCMSamplePayloadMSBPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1inputPCMSamplePayloadMSBPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputPCMSamplePayloadMSBPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1packetType/title",
          "value": "packetType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1packetType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "packetType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/title",
          "value": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHResults/title",
          "value": "BluetoothAFHResults"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHResults/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAFHResults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHResults/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAFHResults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1outputPCMSamplePayloadMSBPosition/title",
          "value": "outputPCMSamplePayloadMSBPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1outputPCMSamplePayloadMSBPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputPCMSamplePayloadMSBPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/title",
          "value": "BluetoothAMPManagerCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPManagerCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPManagerCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/title",
          "value": "BluetoothAMPGetAssocResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetAssocResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetAssocResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEventFilterCondition/title",
          "value": "BluetoothEventFilterCondition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEventFilterCondition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothEventFilterCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEventFilterCondition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothEventFilterCondition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/title",
          "value": "BluetoothCompanyIdentifers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothCompanyIdentifers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothCompanyIdentifers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1receiveCodecFrameSize/title",
          "value": "receiveCodecFrameSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1receiveCodecFrameSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "receiveCodecFrameSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1maxLatency/title",
          "value": "maxLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1maxLatency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1inputTransportUnitSize/title",
          "value": "inputTransportUnitSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1inputTransportUnitSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputTransportUnitSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1inputCodedDataSize/title",
          "value": "inputCodedDataSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1inputCodedDataSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputCodedDataSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1outputTransportUnitSize/title",
          "value": "outputTransportUnitSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1outputTransportUnitSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputTransportUnitSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1outputCodingFormat/title",
          "value": "outputCodingFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1outputCodingFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputCodingFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/title",
          "value": "BluetoothAMPCommandRejectReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEnhancedSynchronousConnectionInfo/title",
          "value": "BluetoothEnhancedSynchronousConnectionInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEnhancedSynchronousConnectionInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothEnhancedSynchronousConnectionInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEnhancedSynchronousConnectionInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothEnhancedSynchronousConnectionInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1inputPCMDataFormat/title",
          "value": "inputPCMDataFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1inputPCMDataFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputPCMDataFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1outputPCMDataFormat/title",
          "value": "outputPCMDataFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1outputPCMDataFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputPCMDataFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceAddress/title",
          "value": "BluetoothDeviceAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1outputCodedDataSize/title",
          "value": "outputCodedDataSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1outputCodedDataSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputCodedDataSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/title",
          "value": "BluetoothAuthenticationRequirementsValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirementsValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirementsValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1retransmissionEffort/title",
          "value": "retransmissionEffort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1retransmissionEffort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "retransmissionEffort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1inputBandwidth/title",
          "value": "inputBandwidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1inputBandwidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputBandwidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/title",
          "value": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/title",
          "value": "BluetoothAMPDiscoverResponseControllerStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDiscoverResponseControllerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDiscoverResponseControllerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1outputDataPath/title",
          "value": "outputDataPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1outputDataPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputDataPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1receiveBandwidth/title",
          "value": "receiveBandwidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1receiveBandwidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "receiveBandwidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1inputCodingFormat/title",
          "value": "inputCodingFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1inputCodingFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputCodingFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1receiveCodingFormat/title",
          "value": "receiveCodingFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1receiveCodingFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "receiveCodingFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/title",
          "value": "BluetoothAMPGetInfoResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetInfoResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetInfoResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHHostChannelClassification/title",
          "value": "BluetoothAFHHostChannelClassification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHHostChannelClassification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAFHHostChannelClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHHostChannelClassification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAFHHostChannelClassification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1transmitCodecFrameSize/title",
          "value": "transmitCodecFrameSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1transmitCodecFrameSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transmitCodecFrameSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1transmitCodingFormat/title",
          "value": "transmitCodingFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEnhancedSetupSynchronousConnectionParams~1transmitCodingFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transmitCodingFormat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothhcienhancedsetupsynchronousconnectionparams"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
