{
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BluetoothL2CAPCommandCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BluetoothL2CAPCommandCode"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BluetoothL2CAPCommandCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "BluetoothL2CAPCommandCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPCommandRejectReason"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPCommandRejectReason"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPCommandRejectReason",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampcommandrejectreason"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPCreatePhysicalLinkResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampcreatephysicallinkresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPDisconnectPhysicalLinkResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampdisconnectphysicallinkresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPDiscoverResponseControllerStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampdiscoverresponsecontrollerstatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetAssocResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetAssocResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPGetAssocResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampgetassocresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetInfoResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetInfoResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPGetInfoResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampgetinforesponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPManagerCode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampmanagercode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIPowerState"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIPowerState"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIPowerState",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcipowerstate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPCommandCode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capcommandcode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capcommandcode/init(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capcommandcode/init(rawvalue:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode/rawValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capcommandcode/rawvalue"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandRejectReason"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandRejectReason"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPCommandRejectReason",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capcommandrejectreason"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationOption"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationOption"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConfigurationOption",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconfigurationoption"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationResult"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConfigurationResult",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconfigurationresult"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconfigurationretransmissionandflowcontrolflags"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConnectionResult",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconnectionresult"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConnectionStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconnectionstatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPInformationExtendedFeaturesMask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPInformationExtendedFeaturesMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPInformationExtendedFeaturesMask",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capinformationextendedfeaturesmask"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCommandReject": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeCommandReject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCommandReject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeCommandReject"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeCommandReject",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodecommandreject"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConfigureRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConfigureRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConfigureRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConfigureRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeConfigureRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodeconfigurerequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConfigureResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConfigureResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConfigureResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConfigureResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeConfigureResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodeconfigureresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodeconnectionparameterupdaterequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodeconnectionparameterupdateresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConnectionRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConnectionRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeConnectionRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodeconnectionrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConnectionResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConnectionResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeConnectionResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodeconnectionresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCreateChannelRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeCreateChannelRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCreateChannelRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeCreateChannelRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeCreateChannelRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodecreatechannelrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCreateChannelResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeCreateChannelResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCreateChannelResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeCreateChannelResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeCreateChannelResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodecreatechannelresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeDisconnectionRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeDisconnectionRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeDisconnectionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeDisconnectionRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeDisconnectionRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodedisconnectionrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeDisconnectionResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeDisconnectionResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeDisconnectionResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeDisconnectionResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeDisconnectionResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodedisconnectionresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeEchoRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeEchoRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeEchoRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeEchoRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeEchoRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodeechorequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeEchoResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeEchoResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeEchoResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeEchoResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeEchoResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodeechoresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeInformationRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeInformationRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeInformationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeInformationRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeInformationRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodeinformationrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeInformationResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeInformationResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeInformationResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeInformationResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeInformationResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodeinformationresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodelecreditbasedconnectionrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeLECreditBasedConnectionResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeLECreditBasedConnectionResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeLECreditBasedConnectionResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeLECreditBasedConnectionResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeLECreditBasedConnectionResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodelecreditbasedconnectionresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeLEFlowControlCredit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeLEFlowControlCredit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeLEFlowControlCredit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeLEFlowControlCredit"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeLEFlowControlCredit",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodeleflowcontrolcredit"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeMoveChannelConfirmation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeMoveChannelConfirmation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeMoveChannelConfirmation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeMoveChannelConfirmation"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeMoveChannelConfirmation",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodemovechannelconfirmation"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeMoveChannelConfirmationResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeMoveChannelConfirmationResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeMoveChannelConfirmationResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeMoveChannelConfirmationResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeMoveChannelConfirmationResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodemovechannelconfirmationresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeMoveChannelRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeMoveChannelRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeMoveChannelRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeMoveChannelRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeMoveChannelRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodemovechannelrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeMoveChannelResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeMoveChannelResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeMoveChannelResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeMoveChannelResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeMoveChannelResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodemovechannelresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeReserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeReserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeReserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeReserved"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeReserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodereserved"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPInformationExtendedFeaturesMask"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCommandReject",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConfigureRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConfigureResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCreateChannelRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCreateChannelResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeDisconnectionRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeDisconnectionResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeEchoRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeEchoResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeInformationRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeInformationResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeLECreditBasedConnectionResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeLEFlowControlCredit",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeMoveChannelConfirmation",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeMoveChannelConfirmationResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeMoveChannelRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeMoveChannelResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeReserved"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode/init(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode/rawValue"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BluetoothL2CAPCommandCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCommandReject",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConfigureRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConfigureResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCreateChannelRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCreateChannelResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeDisconnectionRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeDisconnectionResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeEchoRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeEchoResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeInformationRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeInformationResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeLECreditBasedConnectionResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeLEFlowControlCredit",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeMoveChannelConfirmation",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeMoveChannelConfirmationResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeMoveChannelRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeMoveChannelResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeReserved"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPInformationExtendedFeaturesMask"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "BluetoothL2CAPCommandCode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags/title",
          "value": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeCommandReject/title",
          "value": "kBluetoothL2CAPCommandCodeCommandReject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeCommandReject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeCommandReject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationOption/title",
          "value": "BluetoothL2CAPConfigurationOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest/title",
          "value": "kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeInformationResponse/title",
          "value": "kBluetoothL2CAPCommandCodeInformationResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeInformationResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeInformationResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/title",
          "value": "BluetoothAMPManagerCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPManagerCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPManagerCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/title",
          "value": "BluetoothAMPCommandRejectReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionResult/title",
          "value": "BluetoothL2CAPConnectionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPowerState/title",
          "value": "BluetoothHCIPowerState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPowerState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIPowerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPowerState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIPowerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeDisconnectionRequest/title",
          "value": "kBluetoothL2CAPCommandCodeDisconnectionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeDisconnectionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeDisconnectionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest/title",
          "value": "kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeInformationRequest/title",
          "value": "kBluetoothL2CAPCommandCodeInformationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeInformationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeInformationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConfigureResponse/title",
          "value": "kBluetoothL2CAPCommandCodeConfigureResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConfigureResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeConfigureResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/title",
          "value": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeEchoRequest/title",
          "value": "kBluetoothL2CAPCommandCodeEchoRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeEchoRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeEchoRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeCreateChannelRequest/title",
          "value": "kBluetoothL2CAPCommandCodeCreateChannelRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeCreateChannelRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeCreateChannelRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeEchoResponse/title",
          "value": "kBluetoothL2CAPCommandCodeEchoResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeEchoResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeEchoResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/title",
          "value": "BluetoothAMPDiscoverResponseControllerStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDiscoverResponseControllerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDiscoverResponseControllerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/title",
          "value": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConnectionRequest/title",
          "value": "kBluetoothL2CAPCommandCodeConnectionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConnectionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeConnectionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/title",
          "value": "BluetoothAMPGetAssocResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetAssocResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetAssocResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeMoveChannelConfirmationResponse/title",
          "value": "kBluetoothL2CAPCommandCodeMoveChannelConfirmationResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeMoveChannelConfirmationResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeMoveChannelConfirmationResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationResult/title",
          "value": "BluetoothL2CAPConfigurationResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeCreateChannelResponse/title",
          "value": "kBluetoothL2CAPCommandCodeCreateChannelResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeCreateChannelResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeCreateChannelResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConfigureRequest/title",
          "value": "kBluetoothL2CAPCommandCodeConfigureRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConfigureRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeConfigureRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeMoveChannelConfirmation/title",
          "value": "kBluetoothL2CAPCommandCodeMoveChannelConfirmation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeMoveChannelConfirmation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeMoveChannelConfirmation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeDisconnectionResponse/title",
          "value": "kBluetoothL2CAPCommandCodeDisconnectionResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeDisconnectionResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeDisconnectionResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandCode/title",
          "value": "BluetoothL2CAPCommandCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeMoveChannelRequest/title",
          "value": "kBluetoothL2CAPCommandCodeMoveChannelRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeMoveChannelRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeMoveChannelRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandRejectReason/title",
          "value": "BluetoothL2CAPCommandRejectReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandRejectReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandRejectReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse/title",
          "value": "kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeMoveChannelResponse/title",
          "value": "kBluetoothL2CAPCommandCodeMoveChannelResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeMoveChannelResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeMoveChannelResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConnectionResponse/title",
          "value": "kBluetoothL2CAPCommandCodeConnectionResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConnectionResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeConnectionResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeLECreditBasedConnectionResponse/title",
          "value": "kBluetoothL2CAPCommandCodeLECreditBasedConnectionResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeLECreditBasedConnectionResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeLECreditBasedConnectionResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeReserved/title",
          "value": "kBluetoothL2CAPCommandCodeReserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeReserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeReserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeLEFlowControlCredit/title",
          "value": "kBluetoothL2CAPCommandCodeLEFlowControlCredit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeLEFlowControlCredit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeLEFlowControlCredit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPInformationExtendedFeaturesMask/title",
          "value": "BluetoothL2CAPInformationExtendedFeaturesMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPInformationExtendedFeaturesMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPInformationExtendedFeaturesMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionStatus/title",
          "value": "BluetoothL2CAPConnectionStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/title",
          "value": "BluetoothAMPGetInfoResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetInfoResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetInfoResponseStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothl2capcommandcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothl2capcommandcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
