{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor-constants-8xnan"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "BluetoothDeviceClassMajor constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPCommandRejectReason"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPCommandRejectReason"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPCommandRejectReason",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampcommandrejectreason"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPCreatePhysicalLinkResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampcreatephysicallinkresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPDisconnectPhysicalLinkResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampdisconnectphysicallinkresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPDiscoverResponseControllerStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampdiscoverresponsecontrollerstatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetAssocResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetAssocResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPGetAssocResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampgetassocresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetInfoResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetInfoResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPGetInfoResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampgetinforesponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPManagerCode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampmanagercode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIPowerState"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIPowerState"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIPowerState",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcipowerstate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPCommandCode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capcommandcode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandRejectReason"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandRejectReason"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPCommandRejectReason",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capcommandrejectreason"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationOption"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationOption"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConfigurationOption",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconfigurationoption"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationResult"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConfigurationResult",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconfigurationresult"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconfigurationretransmissionandflowcontrolflags"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConnectionResult",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconnectionresult"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConnectionStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconnectionstatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Enumerations",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-enumerations"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorAny": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorAny"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorAny",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorAny"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorAny",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajorany"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorAudio": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorAudio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorAudio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorAudio"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorAudio",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajoraudio"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorComputer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorComputer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorComputer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorComputer"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorComputer",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajorcomputer"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorEnd"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajorend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorHealth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorHealth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorHealth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorHealth"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorHealth",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajorhealth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorImaging": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorImaging"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorImaging",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorImaging"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorImaging",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajorimaging"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorLANAccessPoint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorLANAccessPoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorLANAccessPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorLANAccessPoint"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorLANAccessPoint",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajorlanaccesspoint"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorMiscellaneous": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorMiscellaneous"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorMiscellaneous",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorMiscellaneous"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorMiscellaneous",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajormiscellaneous"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorNone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorNone"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorNone",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajornone"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorPeripheral": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorPeripheral"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorPeripheral",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorPeripheral"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorPeripheral",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajorperipheral"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorPhone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorPhone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorPhone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorPhone"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorPhone",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajorphone"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorToy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorToy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorToy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorToy"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorToy",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajortoy"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorUnclassified": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorUnclassified"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorUnclassified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorUnclassified"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorUnclassified",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajorunclassified"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorWearable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorWearable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorWearable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorWearable"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorWearable",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajorwearable"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorAny",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorAudio",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorComputer",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorEnd",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorHealth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorImaging",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorLANAccessPoint",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorMiscellaneous",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorNone",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorPeripheral",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorPhone",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorToy",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorUnclassified",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorWearable"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorAny",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorAudio",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorComputer",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorEnd",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorHealth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorImaging",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorLANAccessPoint",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorMiscellaneous",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorNone",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorPeripheral",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorPhone",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorToy",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorUnclassified",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorWearable"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorAny/title",
          "value": "kBluetoothDeviceClassMajorAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorAny/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/title",
          "value": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorHealth/title",
          "value": "kBluetoothDeviceClassMajorHealth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorHealth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorHealth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandRejectReason/title",
          "value": "BluetoothL2CAPCommandRejectReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandRejectReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandRejectReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags/title",
          "value": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorEnd/title",
          "value": "kBluetoothDeviceClassMajorEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorComputer/title",
          "value": "kBluetoothDeviceClassMajorComputer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorComputer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorComputer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorAudio/title",
          "value": "kBluetoothDeviceClassMajorAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorAudio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorLANAccessPoint/title",
          "value": "kBluetoothDeviceClassMajorLANAccessPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorLANAccessPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorLANAccessPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationResult/title",
          "value": "BluetoothL2CAPConfigurationResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionResult/title",
          "value": "BluetoothL2CAPConnectionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorUnclassified/title",
          "value": "kBluetoothDeviceClassMajorUnclassified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorUnclassified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorUnclassified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/title",
          "value": "BluetoothAMPManagerCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPManagerCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPManagerCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/title",
          "value": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorToy/title",
          "value": "kBluetoothDeviceClassMajorToy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorToy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorToy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionStatus/title",
          "value": "BluetoothL2CAPConnectionStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandCode/title",
          "value": "BluetoothL2CAPCommandCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorNone/title",
          "value": "kBluetoothDeviceClassMajorNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorMiscellaneous/title",
          "value": "kBluetoothDeviceClassMajorMiscellaneous"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorMiscellaneous/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorMiscellaneous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorWearable/title",
          "value": "kBluetoothDeviceClassMajorWearable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorWearable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorWearable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPowerState/title",
          "value": "BluetoothHCIPowerState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPowerState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIPowerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPowerState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIPowerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationOption/title",
          "value": "BluetoothL2CAPConfigurationOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorPhone/title",
          "value": "kBluetoothDeviceClassMajorPhone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorPhone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorPhone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/title",
          "value": "BluetoothAMPGetInfoResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetInfoResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetInfoResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/title",
          "value": "BluetoothAMPGetAssocResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetAssocResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetAssocResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/title",
          "value": "BluetoothAMPDiscoverResponseControllerStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDiscoverResponseControllerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDiscoverResponseControllerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorPeripheral/title",
          "value": "kBluetoothDeviceClassMajorPeripheral"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorPeripheral/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorPeripheral"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorImaging/title",
          "value": "kBluetoothDeviceClassMajorImaging"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorImaging/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorImaging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/title",
          "value": "BluetoothAMPCommandRejectReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCommandRejectReason"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothdeviceclassmajor-constants-8xnan"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothdeviceclassmajor-constants-8xnan"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
