{
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BluetoothAMPManagerCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BluetoothAMPManagerCode"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BluetoothAMPManagerCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "BluetoothAMPManagerCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BluetoothAMPManagerCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPCommandRejectReason"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPCommandRejectReason"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPCommandRejectReason",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampcommandrejectreason"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPCreatePhysicalLinkResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampcreatephysicallinkresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPDisconnectPhysicalLinkResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampdisconnectphysicallinkresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPDiscoverResponseControllerStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampdiscoverresponsecontrollerstatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetAssocResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetAssocResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPGetAssocResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampgetassocresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetInfoResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetInfoResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPGetInfoResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampgetinforesponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPManagerCode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampmanagercode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampmanagercode/init(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampmanagercode/init(rawvalue:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode/rawValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampmanagercode/rawvalue"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIPowerState"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIPowerState"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIPowerState",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcipowerstate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPCommandCode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capcommandcode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandRejectReason"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandRejectReason"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPCommandRejectReason",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capcommandrejectreason"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationOption"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationOption"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConfigurationOption",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconfigurationoption"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationResult"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConfigurationResult",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconfigurationresult"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconfigurationretransmissionandflowcontrolflags"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConnectionResult",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconnectionresult"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConnectionStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconnectionstatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPInformationExtendedFeaturesMask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPInformationExtendedFeaturesMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPInformationExtendedFeaturesMask",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capinformationextendedfeaturesmask"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPChangeNotify": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPChangeNotify"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPChangeNotify",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPChangeNotify"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPChangeNotify",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampchangenotify"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPChangeResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPChangeResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPChangeResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPChangeResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPChangeResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampchangeresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCommandReject": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPCommandReject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCommandReject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPCommandReject"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPCommandReject",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampcommandreject"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampcreatephysicallinkrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampcreatephysicallinkresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampdisconnectphysicallinkrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampdisconnectphysicallinkresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDiscoverRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPDiscoverRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDiscoverRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPDiscoverRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPDiscoverRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampdiscoverrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDiscoverResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPDiscoverResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDiscoverResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPDiscoverResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPDiscoverResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampdiscoverresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetAssocRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPGetAssocRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetAssocRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPGetAssocRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPGetAssocRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampgetassocrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetAssocResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPGetAssocResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetAssocResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPGetAssocResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPGetAssocResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampgetassocresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetInfoRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPGetInfoRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetInfoRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPGetInfoRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPGetInfoRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampgetinforequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetInfoResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPGetInfoResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetInfoResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPGetInfoResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPGetInfoResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampgetinforesponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeReserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeReserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeReserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeReserved"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeReserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodereserved"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPInformationExtendedFeaturesMask"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPChangeNotify",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPChangeResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCommandReject",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDiscoverRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDiscoverResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetAssocRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetAssocResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetInfoRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetInfoResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeReserved"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode/init(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode/rawValue"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BluetoothAMPManagerCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPManagerCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPManagerCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPChangeNotify",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPChangeResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCommandReject",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDiscoverRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDiscoverResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetAssocRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetAssocResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetInfoRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetInfoResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeReserved"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPInformationExtendedFeaturesMask"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "BluetoothAMPManagerCode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationOption/title",
          "value": "BluetoothL2CAPConfigurationOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/title",
          "value": "BluetoothAMPCommandRejectReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionResult/title",
          "value": "BluetoothL2CAPConnectionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest/title",
          "value": "kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse/title",
          "value": "kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPInformationExtendedFeaturesMask/title",
          "value": "BluetoothL2CAPInformationExtendedFeaturesMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPInformationExtendedFeaturesMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPInformationExtendedFeaturesMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPDiscoverRequest/title",
          "value": "kBluetoothAMPManagerCodeAMPDiscoverRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPDiscoverRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPDiscoverRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandCode/title",
          "value": "BluetoothL2CAPCommandCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/title",
          "value": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeReserved/title",
          "value": "kBluetoothAMPManagerCodeReserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeReserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeReserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPGetAssocResponse/title",
          "value": "kBluetoothAMPManagerCodeAMPGetAssocResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPGetAssocResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPGetAssocResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationResult/title",
          "value": "BluetoothL2CAPConfigurationResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/title",
          "value": "BluetoothAMPGetInfoResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetInfoResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetInfoResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPChangeNotify/title",
          "value": "kBluetoothAMPManagerCodeAMPChangeNotify"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPChangeNotify/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPChangeNotify"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/title",
          "value": "BluetoothAMPGetAssocResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetAssocResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetAssocResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPGetInfoRequest/title",
          "value": "kBluetoothAMPManagerCodeAMPGetInfoRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPGetInfoRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPGetInfoRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest/title",
          "value": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags/title",
          "value": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionStatus/title",
          "value": "BluetoothL2CAPConnectionStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandRejectReason/title",
          "value": "BluetoothL2CAPCommandRejectReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandRejectReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandRejectReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPDiscoverResponse/title",
          "value": "kBluetoothAMPManagerCodeAMPDiscoverResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPDiscoverResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPDiscoverResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/title",
          "value": "BluetoothAMPManagerCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPManagerCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPManagerCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPowerState/title",
          "value": "BluetoothHCIPowerState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPowerState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIPowerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPowerState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIPowerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/title",
          "value": "BluetoothAMPDiscoverResponseControllerStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDiscoverResponseControllerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDiscoverResponseControllerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPGetAssocRequest/title",
          "value": "kBluetoothAMPManagerCodeAMPGetAssocRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPGetAssocRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPGetAssocRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPGetInfoResponse/title",
          "value": "kBluetoothAMPManagerCodeAMPGetInfoResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPGetInfoResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPGetInfoResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPChangeResponse/title",
          "value": "kBluetoothAMPManagerCodeAMPChangeResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPChangeResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPChangeResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/title",
          "value": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse/title",
          "value": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPCommandReject/title",
          "value": "kBluetoothAMPManagerCodeAMPCommandReject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPCommandReject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPCommandReject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothampmanagercode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothampmanagercode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
