{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothSDPErrorCode-constants-70sy7"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "BluetoothSDPErrorCode constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPCommandRejectReason"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPCommandRejectReason"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPCommandRejectReason",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampcommandrejectreason"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPCreatePhysicalLinkResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampcreatephysicallinkresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPDisconnectPhysicalLinkResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampdisconnectphysicallinkresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPDiscoverResponseControllerStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampdiscoverresponsecontrollerstatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetAssocResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetAssocResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPGetAssocResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampgetassocresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetInfoResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetInfoResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPGetInfoResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampgetinforesponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPManagerCode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampmanagercode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIPowerState"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIPowerState"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIPowerState",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcipowerstate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPCommandCode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capcommandcode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandRejectReason"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandRejectReason"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPCommandRejectReason",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capcommandrejectreason"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationOption"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationOption"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConfigurationOption",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconfigurationoption"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationResult"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConfigurationResult",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconfigurationresult"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconfigurationretransmissionandflowcontrolflags"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConnectionResult",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconnectionresult"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConnectionStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconnectionstatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Enumerations",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-enumerations"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInsufficientResources": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInsufficientResources"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInsufficientResources",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInsufficientResources"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPErrorCodeInsufficientResources",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdperrorcodeinsufficientresources"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidContinuationState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInvalidContinuationState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidContinuationState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInvalidContinuationState"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPErrorCodeInvalidContinuationState",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdperrorcodeinvalidcontinuationstate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidPDUSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInvalidPDUSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidPDUSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInvalidPDUSize"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPErrorCodeInvalidPDUSize",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdperrorcodeinvalidpdusize"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidRequestSyntax": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInvalidRequestSyntax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidRequestSyntax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInvalidRequestSyntax"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPErrorCodeInvalidRequestSyntax",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdperrorcodeinvalidrequestsyntax"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidSDPVersion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInvalidSDPVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidSDPVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInvalidSDPVersion"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPErrorCodeInvalidSDPVersion",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdperrorcodeinvalidsdpversion"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidServiceRecordHandle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInvalidServiceRecordHandle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidServiceRecordHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInvalidServiceRecordHandle"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPErrorCodeInvalidServiceRecordHandle",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdperrorcodeinvalidservicerecordhandle"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeReserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeReserved"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPErrorCodeReserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdperrorcodereserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReservedEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeReservedEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReservedEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeReservedEnd"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPErrorCodeReservedEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdperrorcodereservedend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReservedStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeReservedStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReservedStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeReservedStart"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPErrorCodeReservedStart",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdperrorcodereservedstart"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeSuccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeSuccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeSuccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPErrorCodeSuccess",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdperrorcodesuccess"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInsufficientResources",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidContinuationState",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidPDUSize",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidRequestSyntax",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidSDPVersion",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidServiceRecordHandle",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReservedEnd",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReservedStart",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeSuccess"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInsufficientResources",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidContinuationState",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidPDUSize",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidRequestSyntax",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidSDPVersion",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidServiceRecordHandle",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReservedEnd",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReservedStart",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeSuccess"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags/title",
          "value": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInvalidServiceRecordHandle/title",
          "value": "kBluetoothSDPErrorCodeInvalidServiceRecordHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInvalidServiceRecordHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeInvalidServiceRecordHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeReservedStart/title",
          "value": "kBluetoothSDPErrorCodeReservedStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeReservedStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeReservedStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeReservedEnd/title",
          "value": "kBluetoothSDPErrorCodeReservedEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeReservedEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeReservedEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionStatus/title",
          "value": "BluetoothL2CAPConnectionStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationResult/title",
          "value": "BluetoothL2CAPConfigurationResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandCode/title",
          "value": "BluetoothL2CAPCommandCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInvalidPDUSize/title",
          "value": "kBluetoothSDPErrorCodeInvalidPDUSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInvalidPDUSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeInvalidPDUSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInvalidRequestSyntax/title",
          "value": "kBluetoothSDPErrorCodeInvalidRequestSyntax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInvalidRequestSyntax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeInvalidRequestSyntax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/title",
          "value": "BluetoothAMPGetAssocResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetAssocResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetAssocResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/title",
          "value": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeSuccess/title",
          "value": "kBluetoothSDPErrorCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeSuccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/title",
          "value": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInvalidSDPVersion/title",
          "value": "kBluetoothSDPErrorCodeInvalidSDPVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInvalidSDPVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeInvalidSDPVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/title",
          "value": "BluetoothAMPGetInfoResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetInfoResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetInfoResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInsufficientResources/title",
          "value": "kBluetoothSDPErrorCodeInsufficientResources"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInsufficientResources/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeInsufficientResources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/title",
          "value": "BluetoothAMPCommandRejectReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/title",
          "value": "BluetoothAMPDiscoverResponseControllerStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDiscoverResponseControllerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDiscoverResponseControllerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationOption/title",
          "value": "BluetoothL2CAPConfigurationOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPowerState/title",
          "value": "BluetoothHCIPowerState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPowerState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIPowerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPowerState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIPowerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInvalidContinuationState/title",
          "value": "kBluetoothSDPErrorCodeInvalidContinuationState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInvalidContinuationState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeInvalidContinuationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeReserved/title",
          "value": "kBluetoothSDPErrorCodeReserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeReserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeReserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionResult/title",
          "value": "BluetoothL2CAPConnectionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/title",
          "value": "BluetoothAMPManagerCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPManagerCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPManagerCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandRejectReason/title",
          "value": "BluetoothL2CAPCommandRejectReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandRejectReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandRejectReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandRejectReason"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothsdperrorcode-constants-70sy7"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothsdperrorcode-constants-70sy7"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
