{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPTCICommand-constants-6uh3g"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "BluetoothL2CAPTCICommand constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPCommandRejectReason"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPCommandRejectReason"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPCommandRejectReason",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampcommandrejectreason"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPCreatePhysicalLinkResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampcreatephysicallinkresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPDisconnectPhysicalLinkResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampdisconnectphysicallinkresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPDiscoverResponseControllerStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampdiscoverresponsecontrollerstatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetAssocResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetAssocResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPGetAssocResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampgetassocresponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetInfoResponseStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPGetInfoResponseStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPGetInfoResponseStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampgetinforesponsestatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPManagerCode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampmanagercode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIPowerState"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIPowerState"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIPowerState",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcipowerstate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPCommandCode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capcommandcode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandRejectReason"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandRejectReason"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPCommandRejectReason",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capcommandrejectreason"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationOption"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationOption"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConfigurationOption",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconfigurationoption"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationResult"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConfigurationResult",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconfigurationresult"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconfigurationretransmissionandflowcontrolflags"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConnectionResult",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconnectionresult"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConnectionStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconnectionstatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Enumerations",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-enumerations"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConfigReq": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_ConfigReq"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConfigReq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_ConfigReq"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_ConfigReq",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_configreq"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConfigResp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_ConfigResp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConfigResp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_ConfigResp"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_ConfigResp",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_configresp"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConnectReq": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_ConnectReq"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConnectReq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_ConnectReq"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_ConnectReq",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_connectreq"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConnectResp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_ConnectResp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConnectResp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_ConnectResp"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_ConnectResp",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_connectresp"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisableCLT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_DisableCLT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisableCLT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_DisableCLT"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_DisableCLT",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_disableclt"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisconnectReq": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_DisconnectReq"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisconnectReq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_DisconnectReq"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_DisconnectReq",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_disconnectreq"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisconnectResp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_DisconnectResp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisconnectResp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_DisconnectResp"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_DisconnectResp",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_disconnectresp"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_EnableCLT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_EnableCLT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_EnableCLT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_EnableCLT"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_EnableCLT",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_enableclt"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GetInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GetInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GetInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GetInfo"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_GetInfo",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_getinfo"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupAddMember": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GroupAddMember"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupAddMember",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GroupAddMember"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_GroupAddMember",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_groupaddmember"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupClose": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GroupClose"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupClose",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GroupClose"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_GroupClose",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_groupclose"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupCreate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GroupCreate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupCreate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GroupCreate"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_GroupCreate",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_groupcreate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupMembership": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GroupMembership"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupMembership",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GroupMembership"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_GroupMembership",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_groupmembership"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_groupremovemember"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_Ping": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_Ping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_Ping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_Ping"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_Ping",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_ping"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ReadData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_ReadData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ReadData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_ReadData"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_ReadData",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_readdata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_Reserved1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_Reserved1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_Reserved1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_Reserved1"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_Reserved1",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_reserved1"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_Reserved2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_Reserved2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_Reserved2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_Reserved2"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_Reserved2",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_reserved2"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_WriteData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_WriteData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_WriteData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_WriteData"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_WriteData",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_writedata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandReserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandReserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandReserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandReserved"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandReserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandreserved"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConfigReq",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConfigResp",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConnectReq",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConnectResp",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisableCLT",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisconnectReq",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisconnectResp",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_EnableCLT",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GetInfo",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupAddMember",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupClose",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupCreate",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupMembership",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_Ping",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ReadData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_Reserved1",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_Reserved2",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_WriteData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandReserved"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConfigReq",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConfigResp",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConnectReq",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConnectResp",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisableCLT",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisconnectReq",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisconnectResp",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_EnableCLT",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GetInfo",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupAddMember",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupClose",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupCreate",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupMembership",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_Ping",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ReadData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_Reserved1",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_Reserved2",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_WriteData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandReserved"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCommandRejectReason",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPCreatePhysicalLinkResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDisconnectPhysicalLinkResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetAssocResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPGetInfoResponseStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIPowerState",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandRejectReason",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationResult",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionStatus"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_ReadData/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_ReadData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_ReadData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_ReadData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GroupAddMember/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_GroupAddMember"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GroupAddMember/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_GroupAddMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GroupMembership/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_GroupMembership"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GroupMembership/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_GroupMembership"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_WriteData/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_WriteData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_WriteData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_WriteData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_ConfigReq/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_ConfigReq"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_ConfigReq/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_ConfigReq"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPowerState/title",
          "value": "BluetoothHCIPowerState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPowerState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIPowerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIPowerState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIPowerState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags/title",
          "value": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationRetransmissionAndFlowControlFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_DisconnectReq/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_DisconnectReq"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_DisconnectReq/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_DisconnectReq"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationResult/title",
          "value": "BluetoothL2CAPConfigurationResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/title",
          "value": "BluetoothAMPCommandRejectReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCommandRejectReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GroupCreate/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_GroupCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GroupCreate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_GroupCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_Reserved2/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_Reserved2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_Reserved2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_Reserved2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/title",
          "value": "BluetoothAMPCreatePhysicalLinkResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPCreatePhysicalLinkResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPCreatePhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_ConnectResp/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_ConnectResp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_ConnectResp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_ConnectResp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/title",
          "value": "BluetoothAMPGetAssocResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetAssocResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetAssocResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetAssocResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionResult/title",
          "value": "BluetoothL2CAPConnectionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionStatus/title",
          "value": "BluetoothL2CAPConnectionStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/title",
          "value": "BluetoothAMPGetInfoResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetInfoResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPGetInfoResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPGetInfoResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandRejectReason/title",
          "value": "BluetoothL2CAPCommandRejectReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandRejectReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandRejectReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandRejectReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/title",
          "value": "BluetoothAMPDiscoverResponseControllerStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDiscoverResponseControllerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDiscoverResponseControllerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/title",
          "value": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDisconnectPhysicalLinkResponseStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDisconnectPhysicalLinkResponseStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationOption/title",
          "value": "BluetoothL2CAPConfigurationOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandReserved/title",
          "value": "kBluetoothL2CAPTCICommandReserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandReserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandReserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_EnableCLT/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_EnableCLT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_EnableCLT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_EnableCLT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_Ping/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_Ping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_Ping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_Ping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandCode/title",
          "value": "BluetoothL2CAPCommandCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_ConfigResp/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_ConfigResp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_ConfigResp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_ConfigResp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_ConnectReq/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_ConnectReq"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_ConnectReq/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_ConnectReq"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_DisableCLT/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_DisableCLT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_DisableCLT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_DisableCLT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_Reserved1/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_Reserved1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_Reserved1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_Reserved1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GetInfo/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_GetInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GetInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_GetInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_DisconnectResp/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_DisconnectResp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_DisconnectResp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_DisconnectResp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GroupClose/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_GroupClose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GroupClose/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_GroupClose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/title",
          "value": "BluetoothAMPManagerCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPManagerCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPManagerCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothl2captcicommand-constants-6uh3g"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothl2captcicommand-constants-6uh3g"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
