{
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEFeatureBits"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@BluetoothLEFeatureBits",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BluetoothLEFeatureBits"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BluetoothLEFeatureBits"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "BluetoothLEFeatureBits"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BluetoothLEFeatureBits"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAFHMode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAFHMode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAFHMode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothafhmode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAirMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAirMode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAirMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAirMode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAirMode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothairmode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAllowRoleSwitch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAllowRoleSwitch"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAllowRoleSwitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAllowRoleSwitch"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAllowRoleSwitch",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothallowroleswitch"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirements": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirements"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirements"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAuthenticationRequirements",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothauthenticationrequirements"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAuthenticationRequirementsValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothauthenticationrequirementsvalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothClassOfDevice"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothClassOfDevice"
        }
      ],
      "role": "symbol",
      "title": "BluetoothClassOfDevice",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothclassofdevice"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothClockOffset"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothClockOffset"
        }
      ],
      "role": "symbol",
      "title": "BluetoothClockOffset",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothclockoffset"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "role": "symbol",
      "title": "BluetoothCompanyIdentifers",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothcompanyidentifers"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothConnectionHandle"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothConnectionHandle"
        }
      ],
      "role": "symbol",
      "title": "BluetoothConnectionHandle",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothconnectionhandle"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothDeviceClassMajor"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothDeviceClassMajor"
        }
      ],
      "role": "symbol",
      "title": "BluetoothDeviceClassMajor",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothdeviceclassmajor"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothDeviceClassMinor"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothDeviceClassMinor"
        }
      ],
      "role": "symbol",
      "title": "BluetoothDeviceClassMinor",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothdeviceclassminor"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothDeviceName"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothDeviceName"
        }
      ],
      "role": "symbol",
      "title": "BluetoothDeviceName",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothdevicename"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEncryptionEnable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothEncryptionEnable"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEncryptionEnable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothEncryptionEnable"
        }
      ],
      "role": "symbol",
      "title": "BluetoothEncryptionEnable",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothencryptionenable"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothFeatureBits"
        }
      ],
      "role": "symbol",
      "title": "BluetoothFeatureBits",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothfeaturebits"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIACLDataByteCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIACLDataByteCount"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIACLDataByteCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIACLDataByteCount"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIACLDataByteCount",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhciacldatabytecount"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEFeatureBits": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothLEFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEFeatureBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothLEFeatureBits"
        }
      ],
      "role": "symbol",
      "title": "BluetoothLEFeatureBits",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothlefeaturebits"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEFeatureBits/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEFeatureBits/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothlefeaturebits/init(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEFeatureBits/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEFeatureBits/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothlefeaturebits/init(rawvalue:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEFeatureBits/rawValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEFeatureBits/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothlefeaturebits/rawvalue"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureConnectionParamsRequestProcedure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLEFeatureConnectionParamsRequestProcedure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothLEFeatureBits",
          "text": "BluetoothLEFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureConnectionParamsRequestProcedure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLEFeatureConnectionParamsRequestProcedure"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLEFeatureConnectionParamsRequestProcedure",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlefeatureconnectionparamsrequestprocedure"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureExtendedRejectIndication": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLEFeatureExtendedRejectIndication"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothLEFeatureBits",
          "text": "BluetoothLEFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureExtendedRejectIndication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLEFeatureExtendedRejectIndication"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLEFeatureExtendedRejectIndication",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlefeatureextendedrejectindication"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureExtendedScannerFilterPolicies": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLEFeatureExtendedScannerFilterPolicies"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothLEFeatureBits",
          "text": "BluetoothLEFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureExtendedScannerFilterPolicies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLEFeatureExtendedScannerFilterPolicies"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLEFeatureExtendedScannerFilterPolicies",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlefeatureextendedscannerfilterpolicies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureLEDataPacketLengthExtension": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLEFeatureLEDataPacketLengthExtension"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothLEFeatureBits",
          "text": "BluetoothLEFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureLEDataPacketLengthExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLEFeatureLEDataPacketLengthExtension"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLEFeatureLEDataPacketLengthExtension",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlefeatureledatapacketlengthextension"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureLEEncryption": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLEFeatureLEEncryption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothLEFeatureBits",
          "text": "BluetoothLEFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureLEEncryption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLEFeatureLEEncryption"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLEFeatureLEEncryption",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlefeatureleencryption"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureLEPing": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLEFeatureLEPing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothLEFeatureBits",
          "text": "BluetoothLEFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureLEPing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLEFeatureLEPing"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLEFeatureLEPing",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlefeatureleping"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureLLPrivacy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLEFeatureLLPrivacy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothLEFeatureBits",
          "text": "BluetoothLEFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureLLPrivacy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLEFeatureLLPrivacy"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLEFeatureLLPrivacy",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlefeaturellprivacy"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeaturePeripheralInitiatedFeaturesExchange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLEFeaturePeripheralInitiatedFeaturesExchange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothLEFeatureBits",
          "text": "BluetoothLEFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeaturePeripheralInitiatedFeaturesExchange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLEFeaturePeripheralInitiatedFeaturesExchange"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLEFeaturePeripheralInitiatedFeaturesExchange",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlefeatureperipheralinitiatedfeaturesexchange"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureSlaveInitiatedFeaturesExchange": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLEFeatureSlaveInitiatedFeaturesExchange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothLEFeatureBits",
          "text": "BluetoothLEFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureSlaveInitiatedFeaturesExchange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLEFeatureSlaveInitiatedFeaturesExchange"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLEFeatureSlaveInitiatedFeaturesExchange",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlefeatureslaveinitiatedfeaturesexchange"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHMode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAirMode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAllowRoleSwitch",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirements",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEncryptionEnable",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIACLDataByteCount"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureConnectionParamsRequestProcedure",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureExtendedRejectIndication",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureExtendedScannerFilterPolicies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureLEDataPacketLengthExtension",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureLEEncryption",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureLEPing",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureLLPrivacy",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureSlaveInitiatedFeaturesExchange",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeaturePeripheralInitiatedFeaturesExchange"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEFeatureBits/init(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEFeatureBits/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLEFeatureBits/rawValue"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "BluetoothLEFeatureBits"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLEFeatureBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLEFeatureBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureConnectionParamsRequestProcedure",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureExtendedRejectIndication",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureExtendedScannerFilterPolicies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureLEDataPacketLengthExtension",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureLEEncryption",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureLEPing",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureLLPrivacy",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeatureSlaveInitiatedFeaturesExchange",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLEFeaturePeripheralInitiatedFeaturesExchange"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHMode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAirMode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAllowRoleSwitch",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirements",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEncryptionEnable",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIACLDataByteCount"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "BluetoothLEFeatureBits"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:i",
                    "text": "unsigned int"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLEFeaturePeripheralInitiatedFeaturesExchange/title",
          "value": "kBluetoothLEFeaturePeripheralInitiatedFeaturesExchange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLEFeaturePeripheralInitiatedFeaturesExchange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLEFeaturePeripheralInitiatedFeaturesExchange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLEFeatureLEDataPacketLengthExtension/title",
          "value": "kBluetoothLEFeatureLEDataPacketLengthExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLEFeatureLEDataPacketLengthExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLEFeatureLEDataPacketLengthExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLEFeatureConnectionParamsRequestProcedure/title",
          "value": "kBluetoothLEFeatureConnectionParamsRequestProcedure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLEFeatureConnectionParamsRequestProcedure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLEFeatureConnectionParamsRequestProcedure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClockOffset/title",
          "value": "BluetoothClockOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClockOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothClockOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClockOffset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothClockOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHMode/title",
          "value": "BluetoothAFHMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAFHMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAFHMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLEFeatureLLPrivacy/title",
          "value": "kBluetoothLEFeatureLLPrivacy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLEFeatureLLPrivacy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLEFeatureLLPrivacy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/title",
          "value": "BluetoothAuthenticationRequirementsValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirementsValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirementsValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceName/title",
          "value": "BluetoothDeviceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAirMode/title",
          "value": "BluetoothAirMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAirMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAirMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAirMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAirMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/title",
          "value": "BluetoothConnectionHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothConnectionHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothConnectionHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/title",
          "value": "BluetoothCompanyIdentifers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothCompanyIdentifers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothCompanyIdentifers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClassOfDevice/title",
          "value": "BluetoothClassOfDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClassOfDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothClassOfDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClassOfDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothClassOfDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/title",
          "value": "BluetoothFeatureBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothFeatureBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothFeatureBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLEFeatureBits/title",
          "value": "BluetoothLEFeatureBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLEFeatureBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLEFeatureBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLEFeatureBits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLEFeatureBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAllowRoleSwitch/title",
          "value": "BluetoothAllowRoleSwitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAllowRoleSwitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAllowRoleSwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAllowRoleSwitch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAllowRoleSwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMajor/title",
          "value": "BluetoothDeviceClassMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceClassMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMajor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceClassMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLEFeatureExtendedScannerFilterPolicies/title",
          "value": "kBluetoothLEFeatureExtendedScannerFilterPolicies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLEFeatureExtendedScannerFilterPolicies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLEFeatureExtendedScannerFilterPolicies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMinor/title",
          "value": "BluetoothDeviceClassMinor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMinor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceClassMinor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMinor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceClassMinor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLEFeatureLEEncryption/title",
          "value": "kBluetoothLEFeatureLEEncryption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLEFeatureLEEncryption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLEFeatureLEEncryption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIACLDataByteCount/title",
          "value": "BluetoothHCIACLDataByteCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIACLDataByteCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIACLDataByteCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIACLDataByteCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIACLDataByteCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLEFeatureSlaveInitiatedFeaturesExchange/title",
          "value": "kBluetoothLEFeatureSlaveInitiatedFeaturesExchange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLEFeatureSlaveInitiatedFeaturesExchange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLEFeatureSlaveInitiatedFeaturesExchange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEncryptionEnable/title",
          "value": "BluetoothEncryptionEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEncryptionEnable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothEncryptionEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEncryptionEnable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothEncryptionEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLEFeatureLEPing/title",
          "value": "kBluetoothLEFeatureLEPing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLEFeatureLEPing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLEFeatureLEPing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirements/title",
          "value": "BluetoothAuthenticationRequirements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLEFeatureExtendedRejectIndication/title",
          "value": "kBluetoothLEFeatureExtendedRejectIndication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLEFeatureExtendedRejectIndication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLEFeatureExtendedRejectIndication"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothlefeaturebits"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothlefeaturebits"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
