{
  "abstract": [
    {
      "text": "Convenience Macros for working with OBEX Header Identifiers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/GET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@GET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT",
    "fragments": [
      {
        "kind": "identifier",
        "text": "GET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "GET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Macro",
    "symbolKind": "macro",
    "title": "GET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "#define"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "GET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "internalParam",
              "text": "HEADER_ID"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The API should shield you from using these, they are included here to completeness.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/GET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT": {
      "abstract": [
        {
          "text": "Convenience Macros for working with OBEX Header Identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/GET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT",
      "kind": "symbol",
      "role": "symbol",
      "title": "GET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT",
      "type": "topic",
      "url": "/documentation/iobluetooth/get_header_id_is_null_terminated_unicode_text"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddApplicationParameterHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add bytes representing an application parameter to a dictionary of OBEX headers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddApplicationParameterHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddApplicationParameterHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddApplicationParameterHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddApplicationParameterHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddapplicationparameterheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddAuthorizationChallengeHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add an authorization challenge header to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddAuthorizationChallengeHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddAuthorizationChallengeHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddAuthorizationChallengeHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddAuthorizationChallengeHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddauthorizationchallengeheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddAuthorizationResponseHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add an authorization Response header to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddAuthorizationResponseHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddAuthorizationResponseHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddAuthorizationResponseHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddAuthorizationResponseHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddauthorizationresponseheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddBodyHeader(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Add bytes of data to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddBodyHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddBodyHeader(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddBodyHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddBodyHeader(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddbodyheader(_:_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddByteSequenceHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add a byte sequence header to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddByteSequenceHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddByteSequenceHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddByteSequenceHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddByteSequenceHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddbytesequenceheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddConnectionIDHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add bytes representing a connection ID to a dictionary of OBEX headers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddConnectionIDHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddConnectionIDHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddConnectionIDHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddConnectionIDHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddconnectionidheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddCountHeader(_:_:)": {
      "abstract": [
        {
          "text": "Add a CFStringRef to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddCountHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddCountHeader(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddCountHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddCountHeader(_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddcountheader(_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddDescriptionHeader(_:_:)": {
      "abstract": [
        {
          "text": "Add a CFStringRef to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddDescriptionHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddDescriptionHeader(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddDescriptionHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddDescriptionHeader(_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexadddescriptionheader(_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddHTTPHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add bytes of data to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddHTTPHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddHTTPHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddHTTPHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddHTTPHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddhttpheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddLengthHeader(_:_:)": {
      "abstract": [
        {
          "text": "Add a CFStringRef to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddLengthHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddLengthHeader(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddLengthHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddLengthHeader(_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddlengthheader(_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddNameHeader(_:_:)": {
      "abstract": [
        {
          "text": "Add a CFStringRef to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddNameHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddNameHeader(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddNameHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddNameHeader(_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddnameheader(_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddObjectClassHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add an object class header to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddObjectClassHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddObjectClassHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddObjectClassHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddObjectClassHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddobjectclassheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTargetHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add bytes of data to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddTargetHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTargetHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddTargetHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddTargetHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddtargetheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTime4ByteHeader(_:_:)": {
      "abstract": [
        {
          "text": "Add a CFStringRef to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddTime4ByteHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTime4ByteHeader(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddTime4ByteHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddTime4ByteHeader(_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddtime4byteheader(_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTimeISOHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add bytes to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddTimeISOHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTimeISOHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddTimeISOHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddTimeISOHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddtimeisoheader(_:_:_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Miscellaneous",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddApplicationParameterHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddAuthorizationChallengeHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddAuthorizationResponseHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddBodyHeader(_:_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddByteSequenceHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddConnectionIDHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddCountHeader(_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddDescriptionHeader(_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddHTTPHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddLengthHeader(_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddNameHeader(_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddObjectClassHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTargetHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTime4ByteHeader(_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTimeISOHeader(_:_:_:)"
      ],
      "title": "Miscellaneous"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddLengthHeader(_:_:)/title",
          "value": "OBEXAddLengthHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddLengthHeader(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddLengthHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddBodyHeader(_:_:_:_:)/title",
          "value": "OBEXAddBodyHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddBodyHeader(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddBodyHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddTargetHeader(_:_:_:)/title",
          "value": "OBEXAddTargetHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddTargetHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddTargetHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddConnectionIDHeader(_:_:_:)/title",
          "value": "OBEXAddConnectionIDHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddConnectionIDHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddConnectionIDHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddNameHeader(_:_:)/title",
          "value": "OBEXAddNameHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddNameHeader(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddNameHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddAuthorizationChallengeHeader(_:_:_:)/title",
          "value": "OBEXAddAuthorizationChallengeHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddAuthorizationChallengeHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddAuthorizationChallengeHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddCountHeader(_:_:)/title",
          "value": "OBEXAddCountHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddCountHeader(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddCountHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddAuthorizationResponseHeader(_:_:_:)/title",
          "value": "OBEXAddAuthorizationResponseHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddAuthorizationResponseHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddAuthorizationResponseHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddObjectClassHeader(_:_:_:)/title",
          "value": "OBEXAddObjectClassHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddObjectClassHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddObjectClassHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddDescriptionHeader(_:_:)/title",
          "value": "OBEXAddDescriptionHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddDescriptionHeader(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddDescriptionHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddApplicationParameterHeader(_:_:_:)/title",
          "value": "OBEXAddApplicationParameterHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddApplicationParameterHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddApplicationParameterHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddHTTPHeader(_:_:_:)/title",
          "value": "OBEXAddHTTPHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddHTTPHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddHTTPHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddTimeISOHeader(_:_:_:)/title",
          "value": "OBEXAddTimeISOHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddTimeISOHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddTimeISOHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddByteSequenceHeader(_:_:_:)/title",
          "value": "OBEXAddByteSequenceHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddByteSequenceHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddByteSequenceHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddTime4ByteHeader(_:_:)/title",
          "value": "OBEXAddTime4ByteHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddTime4ByteHeader(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddTime4ByteHeader"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/get_header_id_is_null_terminated_unicode_text"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
