{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexfiletransferservices-h"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/global-variables"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Global Variables"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSListingNameKey": {
      "abstract": [
        {
          "text": "NSString value. This key is used with the array of NSDictionary’s returned through the delegate method fileTransferServicesGetListingComplete: after calling getFolderListing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFTSListingNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSListingNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFTSListingNameKey"
        }
      ],
      "role": "symbol",
      "title": "kFTSListingNameKey",
      "type": "topic",
      "url": "/documentation/iobluetooth/kftslistingnamekey"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSListingSizeKey": {
      "abstract": [
        {
          "text": "Int value. This key is used with the array of NSDictionary’s returned through the delegate method fileTransferServicesGetListingComplete: after calling getFolderListing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFTSListingSizeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSListingSizeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFTSListingSizeKey"
        }
      ],
      "role": "symbol",
      "title": "kFTSListingSizeKey",
      "type": "topic",
      "url": "/documentation/iobluetooth/kftslistingsizekey"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSListingTypeKey": {
      "abstract": [
        {
          "text": "FTSFileType value. This key is used with the array of NSDictionary’s returned through the delegate method fileTransferServicesGetListingComplete: after calling getFolderListing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFTSListingTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSListingTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFTSListingTypeKey"
        }
      ],
      "role": "symbol",
      "title": "kFTSListingTypeKey",
      "type": "topic",
      "url": "/documentation/iobluetooth/kftslistingtypekey"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressBytesTotalKey": {
      "abstract": [
        {
          "text": "NSNumber integer value. This key is used with the NSDictionary returned from the fileTransferServicesPutProgress: and fileTransferServicesGetProgress: delegate methods",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFTSProgressBytesTotalKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressBytesTotalKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFTSProgressBytesTotalKey"
        }
      ],
      "role": "symbol",
      "title": "kFTSProgressBytesTotalKey",
      "type": "topic",
      "url": "/documentation/iobluetooth/kftsprogressbytestotalkey"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressBytesTransferredKey": {
      "abstract": [
        {
          "text": "NSNumber integer value. This key is used with the NSDictionary returned from the fileTransferServicesPutProgress: and fileTransferServicesGetProgress: delegate methods",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFTSProgressBytesTransferredKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressBytesTransferredKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFTSProgressBytesTransferredKey"
        }
      ],
      "role": "symbol",
      "title": "kFTSProgressBytesTransferredKey",
      "type": "topic",
      "url": "/documentation/iobluetooth/kftsprogressbytestransferredkey"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressEstimatedTimeKey": {
      "abstract": [
        {
          "text": "NSNumber double value. This key is used with the NSDictionary returned from the fileTransferServicesPutProgress: and fileTransferServicesGetProgress: delegate methods",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFTSProgressEstimatedTimeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressEstimatedTimeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFTSProgressEstimatedTimeKey"
        }
      ],
      "role": "symbol",
      "title": "kFTSProgressEstimatedTimeKey",
      "type": "topic",
      "url": "/documentation/iobluetooth/kftsprogressestimatedtimekey"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressPercentageKey": {
      "abstract": [
        {
          "text": "NSNumber float value. This key is used with the NSDictionary returned from the fileTransferServicesPutProgress: and fileTransferServicesGetProgress: delegate methods",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFTSProgressPercentageKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressPercentageKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFTSProgressPercentageKey"
        }
      ],
      "role": "symbol",
      "title": "kFTSProgressPercentageKey",
      "type": "topic",
      "url": "/documentation/iobluetooth/kftsprogresspercentagekey"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressTimeElapsedKey": {
      "abstract": [
        {
          "text": "NSNumber int value. This key is used with the NSDictionary returned from the fileTransferServicesPutProgress: and fileTransferServicesGetProgress: delegate methods",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFTSProgressTimeElapsedKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressTimeElapsedKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFTSProgressTimeElapsedKey"
        }
      ],
      "role": "symbol",
      "title": "kFTSProgressTimeElapsedKey",
      "type": "topic",
      "url": "/documentation/iobluetooth/kftsprogresstimeelapsedkey"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressTransferRateKey": {
      "abstract": [
        {
          "text": "NSNumber float value. This key is used with the NSDictionary returned from the fileTransferServicesPutProgress: and fileTransferServicesGetProgress: delegate methods",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFTSProgressTransferRateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressTransferRateKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFTSProgressTransferRateKey"
        }
      ],
      "role": "symbol",
      "title": "kFTSProgressTransferRateKey",
      "type": "topic",
      "url": "/documentation/iobluetooth/kftsprogresstransferratekey"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexfiletransferservices-h": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexfiletransferservices-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OBEXFileTransferServices.h",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexfiletransferservices-h"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSListingNameKey",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSListingSizeKey",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSListingTypeKey",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressBytesTotalKey",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressBytesTransferredKey",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressEstimatedTimeKey",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressPercentageKey",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressTimeElapsedKey",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressTransferRateKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSListingNameKey",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSListingSizeKey",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSListingTypeKey",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressBytesTotalKey",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressBytesTransferredKey",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressEstimatedTimeKey",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressPercentageKey",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressTimeElapsedKey",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressTransferRateKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kFTSProgressBytesTransferredKey/title",
          "value": "kFTSProgressBytesTransferredKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kFTSProgressBytesTransferredKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFTSProgressBytesTransferredKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kFTSListingSizeKey/title",
          "value": "kFTSListingSizeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kFTSListingSizeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFTSListingSizeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kFTSProgressBytesTotalKey/title",
          "value": "kFTSProgressBytesTotalKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kFTSProgressBytesTotalKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFTSProgressBytesTotalKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kFTSProgressTransferRateKey/title",
          "value": "kFTSProgressTransferRateKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kFTSProgressTransferRateKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFTSProgressTransferRateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kFTSListingNameKey/title",
          "value": "kFTSListingNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kFTSListingNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFTSListingNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kFTSProgressPercentageKey/title",
          "value": "kFTSProgressPercentageKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kFTSProgressPercentageKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFTSProgressPercentageKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kFTSListingTypeKey/title",
          "value": "kFTSListingTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kFTSListingTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFTSListingTypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kFTSProgressTimeElapsedKey/title",
          "value": "kFTSProgressTimeElapsedKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kFTSProgressTimeElapsedKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFTSProgressTimeElapsedKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kFTSProgressEstimatedTimeKey/title",
          "value": "kFTSProgressEstimatedTimeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kFTSProgressEstimatedTimeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFTSProgressEstimatedTimeKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/global-variables"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/global-variables"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
