{
  "abstract": [
    {
      "text": "Create an OBEX session with a device ref and an RFCOMM channel ID. This allows you to bypass the browser if you already know the SDP information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothOBEXSessionCreateWithIOBluetoothDeviceRefAndChannelNumber"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@IOBluetoothOBEXSessionCreateWithIOBluetoothDeviceRefAndChannelNumber",
    "fragments": [
      {
        "kind": "identifier",
        "text": "IOBluetoothOBEXSessionCreateWithIOBluetoothDeviceRefAndChannelNumber"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOBluetoothOBEXSessionCreateWithIOBluetoothDeviceRefAndChannelNumber"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.6",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "IOBluetoothOBEXSessionCreateWithIOBluetoothDeviceRefAndChannelNumber"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OBEXError",
              "text": "OBEXError"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOBluetoothOBEXSessionCreateWithIOBluetoothDeviceRefAndChannelNumber"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@IOBluetoothDeviceRef",
              "text": "IOBluetoothDeviceRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inDeviceRef"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothRFCOMMChannelID",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BluetoothRFCOMMChannelID",
              "text": "BluetoothRFCOMMChannelID"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inChannelID"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OBEXSessionRef",
              "text": "OBEXSessionRef"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "outSessionRef"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A valid IOBluetoothDeviceRef reference.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inDeviceRef"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A valid RFCOMM channel ID on the target device.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inChannelID"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A valid ptr to an IOBluetoothOBEXSessionRef; will contain the newly created session if return value is kOBEXSuccess.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "outSessionRef"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An error code value. 0 if successful.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You will use a session reference to do all OBEX interaction to a specific device. This method DOES NOT create a connection to the device of any kind.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "*** DEPRECATED IN BLUETOOTH 2.2 (OS X 10.6) *** You should transition your code to Objective-C equivalents. *** This API may be removed any time in the future.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothRFCOMMChannelID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothRFCOMMChannelID"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothRFCOMMChannelID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothRFCOMMChannelID"
        }
      ],
      "role": "symbol",
      "title": "BluetoothRFCOMMChannelID",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothrfcommchannelid"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceRef": {
      "abstract": [
        {
          "text": "An object that represents a Bluetooth I/O device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceRef"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceRef"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothDeviceRef",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdeviceref"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothOBEXSessionCreateWithIOBluetoothDeviceRefAndChannelNumber": {
      "abstract": [
        {
          "text": "Create an OBEX session with a device ref and an RFCOMM channel ID. This allows you to bypass the browser if you already know the SDP information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOBluetoothOBEXSessionCreateWithIOBluetoothDeviceRefAndChannelNumber"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothOBEXSessionCreateWithIOBluetoothDeviceRefAndChannelNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOBluetoothOBEXSessionCreateWithIOBluetoothDeviceRefAndChannelNumber",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothobexsessioncreatewithiobluetoothdevicerefandchannelnumber"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothOBEXSessionCreateWithIOBluetoothSDPServiceRecordRef": {
      "abstract": [
        {
          "text": "Create an OBEX session with a service ref, usually obtained from the device browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOBluetoothOBEXSessionCreateWithIOBluetoothSDPServiceRecordRef"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothOBEXSessionCreateWithIOBluetoothSDPServiceRecordRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOBluetoothOBEXSessionCreateWithIOBluetoothSDPServiceRecordRef",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothobexsessioncreatewithiobluetoothsdpservicerecordref"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothOBEXSessionCreateWithIncomingIOBluetoothRFCOMMChannel": {
      "abstract": [
        {
          "text": "Create an OBEX session with an IOBluetoothRFCOMMchannel. This implies you are creating a OBEX SERVER session that will dole out info to remote Bluetooth clients.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOBluetoothOBEXSessionCreateWithIncomingIOBluetoothRFCOMMChannel"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothOBEXSessionCreateWithIncomingIOBluetoothRFCOMMChannel",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOBluetoothOBEXSessionCreateWithIncomingIOBluetoothRFCOMMChannel",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothobexsessioncreatewithincomingiobluetoothrfcommchannel"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothOBEXSessionOpenTransportConnection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOBluetoothOBEXSessionOpenTransportConnection"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothOBEXSessionOpenTransportConnection",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOBluetoothOBEXSessionOpenTransportConnection",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothobexsessionopentransportconnection"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXError": {
      "abstract": [
        {
          "text": "Codes for OBEX errors. If the return value was not in the following range, then it is most likely resulting from kernel code/IOKit, and you should consult IOReturn.h for those codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXError"
        }
      ],
      "role": "symbol",
      "title": "OBEXError",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexerror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXSessionRef"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXSessionRef"
        }
      ],
      "role": "symbol",
      "title": "OBEXSessionRef",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexsessionref"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Miscellaneous",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothOBEXSessionCreateWithIncomingIOBluetoothRFCOMMChannel",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothOBEXSessionCreateWithIOBluetoothSDPServiceRecordRef",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothOBEXSessionOpenTransportConnection"
      ],
      "title": "Miscellaneous"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceRef/title",
          "value": "IOBluetoothDeviceRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionRef/title",
          "value": "OBEXSessionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSessionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXError/title",
          "value": "OBEXError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothRFCOMMChannelID/title",
          "value": "BluetoothRFCOMMChannelID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothRFCOMMChannelID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothRFCOMMChannelID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothRFCOMMChannelID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothRFCOMMChannelID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/iobluetoothobexsessioncreatewithiobluetoothdevicerefandchannelnumber"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
