{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)IOBluetoothL2CAPChannelDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOBluetoothL2CAPChannelDelegate"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOBluetoothL2CAPChannelDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "IOBluetoothL2CAPChannelDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOBluetoothL2CAPChannelDelegate"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceAsyncCallbacks": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceAsyncCallbacks"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceAsyncCallbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceAsyncCallbacks"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothDeviceAsyncCallbacks",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdeviceasynccallbacks"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceInquiryDelegate": {
      "abstract": [
        {
          "text": "This category on NSObject describes the delegate methods for the IOBluetoothDeviceInquiry object. All methods are optional, but it is highly recommended you implement them all. Do NOT invoke remote name requests on found IOBluetoothDevice objects unless the inquiry object has been stopped. Doing so may deadlock your process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceInquiryDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceInquiryDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceInquiryDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothDeviceInquiryDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdeviceinquirydelegate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothDevicePairDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothDevicePairDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothDevicePairDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdevicepairdelegate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGatewayDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods for receiving information about status changes for a connected Bluetooth hands-free phone or headset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeAudioGatewayDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGatewayDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeAudioGatewayDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeAudioGatewayDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreeaudiogatewaydelegate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreedelegate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods for receiving status change updates and information about a connected Bluetooth hands-free phone or headset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeDeviceDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeDeviceDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeDeviceDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreedevicedelegate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothL2CAPChannelDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothL2CAPChannelDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothL2CAPChannelDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothl2capchanneldelegate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelClosed(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "l2capChannelClosed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothL2CAPChannel",
          "text": "IOBluetoothL2CAPChannel"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelClosed(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "l2capChannelClosed:"
        }
      ],
      "role": "symbol",
      "title": "l2capChannelClosed(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothl2capchanneldelegate/l2capchannelclosed(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelData(_:data:length:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "l2capChannelData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothL2CAPChannel",
          "text": "IOBluetoothL2CAPChannel"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "length"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelData(_:data:length:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "l2capChannelData:data:length:"
        }
      ],
      "role": "symbol",
      "title": "l2capChannelData(_:data:length:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothl2capchanneldelegate/l2capchanneldata(_:data:length:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelOpenComplete(_:status:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "l2capChannelOpenComplete"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothL2CAPChannel",
          "text": "IOBluetoothL2CAPChannel"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOReturn",
          "text": "IOReturn"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelOpenComplete(_:status:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "l2capChannelOpenComplete:status:"
        }
      ],
      "role": "symbol",
      "title": "l2capChannelOpenComplete(_:status:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothl2capchanneldelegate/l2capchannelopencomplete(_:status:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelQueueSpaceAvailable(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "l2capChannelQueueSpaceAvailable"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothL2CAPChannel",
          "text": "IOBluetoothL2CAPChannel"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelQueueSpaceAvailable(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "l2capChannelQueueSpaceAvailable:"
        }
      ],
      "role": "symbol",
      "title": "l2capChannelQueueSpaceAvailable(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothl2capchanneldelegate/l2capchannelqueuespaceavailable(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelReconfigured(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "l2capChannelReconfigured"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothL2CAPChannel",
          "text": "IOBluetoothL2CAPChannel"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelReconfigured(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "l2capChannelReconfigured:"
        }
      ],
      "role": "symbol",
      "title": "l2capChannelReconfigured(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothl2capchanneldelegate/l2capchannelreconfigured(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelWriteComplete(_:refcon:status:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "l2capChannelWriteComplete"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothL2CAPChannel",
          "text": "IOBluetoothL2CAPChannel"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "refcon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOReturn",
          "text": "IOReturn"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelWriteComplete(_:refcon:status:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "l2capChannelWriteComplete:refcon:status:"
        }
      ],
      "role": "symbol",
      "title": "l2capChannelWriteComplete(_:refcon:status:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothl2capchanneldelegate/l2capchannelwritecomplete(_:refcon:status:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothRFCOMMChannelDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothRFCOMMChannelDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothRFCOMMChannelDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothrfcommchanneldelegate"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceAsyncCallbacks",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceInquiryDelegate",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGatewayDelegate",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDelegate",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate"
      ],
      "title": "Protocols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelClosed(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelData(_:data:length:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelOpenComplete(_:status:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelQueueSpaceAvailable(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelReconfigured(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelWriteComplete(_:refcon:status:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOBluetoothL2CAPChannelDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothL2CAPChannelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothL2CAPChannelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelClosed(_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelData(_:data:length:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelOpenComplete(_:status:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelQueueSpaceAvailable(_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelReconfigured(_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate/l2capChannelWriteComplete(_:refcon:status:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceAsyncCallbacks",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceInquiryDelegate",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGatewayDelegate",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDelegate",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate"
              ],
              "title": "Protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOBluetoothL2CAPChannelDelegate"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDelegate/title",
          "value": "IOBluetoothHandsFreeDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelDelegate~1l2capChannelWriteComplete(_:refcon:status:)/title",
          "value": "l2capChannelWriteComplete:refcon:status:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelDelegate~1l2capChannelWriteComplete(_:refcon:status:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "l2capChannelWriteComplete:refcon:status:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelDelegate~1l2capChannelQueueSpaceAvailable(_:)/title",
          "value": "l2capChannelQueueSpaceAvailable:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelDelegate~1l2capChannelQueueSpaceAvailable(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "l2capChannelQueueSpaceAvailable:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate/title",
          "value": "IOBluetoothDevicePairDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDevicePairDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDevicePairDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate/title",
          "value": "IOBluetoothRFCOMMChannelDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothRFCOMMChannelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothRFCOMMChannelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceAsyncCallbacks/title",
          "value": "IOBluetoothDeviceAsyncCallbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceAsyncCallbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceAsyncCallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceAsyncCallbacks/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceAsyncCallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelDelegate~1l2capChannelClosed(_:)/title",
          "value": "l2capChannelClosed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelDelegate~1l2capChannelClosed(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "l2capChannelClosed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeAudioGatewayDelegate/title",
          "value": "IOBluetoothHandsFreeAudioGatewayDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeAudioGatewayDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeAudioGatewayDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeAudioGatewayDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeAudioGatewayDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelDelegate~1l2capChannelReconfigured(_:)/title",
          "value": "l2capChannelReconfigured:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelDelegate~1l2capChannelReconfigured(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "l2capChannelReconfigured:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate/title",
          "value": "IOBluetoothHandsFreeDeviceDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceInquiryDelegate/title",
          "value": "IOBluetoothDeviceInquiryDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceInquiryDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceInquiryDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceInquiryDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceInquiryDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelDelegate~1l2capChannelOpenComplete(_:status:)/title",
          "value": "l2capChannelOpenComplete:status:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelDelegate~1l2capChannelOpenComplete(_:status:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "l2capChannelOpenComplete:status:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelDelegate~1l2capChannelData(_:data:length:)/title",
          "value": "l2capChannelData:data:length:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelDelegate~1l2capChannelData(_:data:length:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "l2capChannelData:data:length:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelDelegate/title",
          "value": "IOBluetoothL2CAPChannelDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothL2CAPChannelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothL2CAPChannelDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/iobluetoothl2capchanneldelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/iobluetoothl2capchanneldelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
