{
  "abstract": [
    {
      "text": "Public Interfaces for Apple’s implementation of Bluetooth technology.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothuserlib-h"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "IOBluetoothUserLib.h"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "There is an accompanying header to this, “Bluetooth.h”, which contains all technology-specific typedefs and information. This header relies heavily on it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Included-Headers",
          "level": 3,
          "text": "Included Headers",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<IOKit/IOKitLib.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<CoreFoundation/CFMachPort.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<IOBluetooth/Bluetooth.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<Foundation/Foundation.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothAddSCOAudioDevice": {
      "abstract": [
        {
          "text": "Creates a persistent audio driver that will route audio data to/from the specified device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOBluetoothAddSCOAudioDevice"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothAddSCOAudioDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOBluetoothAddSCOAudioDevice",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothaddscoaudiodevice"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchAttributes": {
      "abstract": [
        {
          "text": "Structure used to search for particular devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceSearchAttributes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceSearchAttributes"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothDeviceSearchAttributes",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdevicesearchattributes"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchDeviceAttributes": {
      "abstract": [
        {
          "text": "Structure used to search for particular devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceSearchDeviceAttributes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchDeviceAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceSearchDeviceAttributes"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothDeviceSearchDeviceAttributes",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdevicesearchdeviceattributes"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceSearchOptions"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceSearchOptions"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothDeviceSearchOptions",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdevicesearchoptions"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchTypesBits": {
      "abstract": [
        {
          "text": "Bits to determine what Bluetooth devices to search for",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceSearchTypesBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchTypesBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceSearchTypesBits"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothDeviceSearchTypesBits",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdevicesearchtypesbits"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothIgnoreHIDDevice(_:)": {
      "abstract": [
        {
          "text": "Hints that the macOS Bluetooth software should ignore a HID device that connects up.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothIgnoreHIDDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOBluetoothDeviceRef",
          "text": "IOBluetoothDeviceRef"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothIgnoreHIDDevice(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothIgnoreHIDDevice"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothIgnoreHIDDevice(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothignorehiddevice(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelRegisterForChannelCloseNotification(_:_:_:)": {
      "abstract": [
        {
          "text": "Allows a client to register for a channel close notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothL2CAPChannelRegisterForChannelCloseNotification"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOBluetoothL2CAPChannelRef",
          "text": "IOBluetoothL2CAPChannelRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOBluetoothUserNotificationCallback",
          "text": "IOBluetoothUserNotificationCallback"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOBluetoothUserNotificationRef",
          "text": "IOBluetoothUserNotificationRef"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelRegisterForChannelCloseNotification(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothL2CAPChannelRegisterForChannelCloseNotification"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothL2CAPChannelRegisterForChannelCloseNotification(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothl2capchannelregisterforchannelclosenotification(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRemoveIgnoredHIDDevice(_:)": {
      "abstract": [
        {
          "text": "The counterpart to the above IOBluetoothIgnoreHIDDevice() API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothRemoveIgnoredHIDDevice"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOBluetoothDeviceRef",
          "text": "IOBluetoothDeviceRef"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRemoveIgnoredHIDDevice(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothRemoveIgnoredHIDDevice"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothRemoveIgnoredHIDDevice(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothremoveignoredhiddevice(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRemoveSCOAudioDevice": {
      "abstract": [
        {
          "text": "Removes a persistent audio driver for a device that had already been added using IOBluetoothAddAudioDevice().",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOBluetoothRemoveSCOAudioDevice"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRemoveSCOAudioDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOBluetoothRemoveSCOAudioDevice",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothremovescoaudiodevice"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothUserNotificationCallback": {
      "abstract": [
        {
          "text": "Callback function definition for user notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothUserNotificationCallback"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothUserNotificationCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothUserNotificationCallback"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothUserNotificationCallback",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothusernotificationcallback"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothUserNotificationUnregister(_:)": {
      "abstract": [
        {
          "text": "Unregisters the target notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothUserNotificationUnregister"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOBluetoothUserNotificationRef",
          "text": "IOBluetoothUserNotificationRef"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothUserNotificationUnregister(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothUserNotificationUnregister"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothUserNotificationUnregister(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothusernotificationunregister(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/bluetooth-h-user-space": {
      "abstract": [
        {
          "text": "Bluetooth wireless technology",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/bluetooth-h-user-space",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Bluetooth.h User-Space",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetooth-h-user-space"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Constants",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-constants"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Data Types",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-data-types"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Enumerations",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-enumerations"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Functions",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-functions"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Structures",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-structures"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothutilities-h": {
      "abstract": [
        {
          "text": "See the Overview section above for header-level documentation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothutilities-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetoothUtilities.h",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothutilities-h"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/obex-h": {
      "abstract": [
        {
          "text": "Public OBEX technology interfaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/obex-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OBEX.h",
      "type": "topic",
      "url": "/documentation/iobluetooth/obex-h"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexbluetooth-h": {
      "abstract": [
        {
          "text": "Object Exchange over Bluetooth.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexbluetooth-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OBEXBluetooth.h",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexbluetooth-h"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexfiletransferservices-h": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexfiletransferservices-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OBEXFileTransferServices.h",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexfiletransferservices-h"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/bluetooth-h-user-space",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothutilities-h",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/obex-h",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexbluetooth-h",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexfiletransferservices-h",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-structures",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-constants",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-functions",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Miscellaneous",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothIgnoreHIDDevice(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelRegisterForChannelCloseNotification(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRemoveIgnoredHIDDevice(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothUserNotificationUnregister(_:)"
      ],
      "title": "Miscellaneous"
    },
    {
      "abstract": [
        {
          "text": "See the Overview for header-level documentation.",
          "type": "text"
        }
      ],
      "anchor": "Callbacks",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothUserNotificationCallback"
      ],
      "title": "Callbacks"
    },
    {
      "abstract": [
        {
          "text": "See the Overview for header-level documentation.",
          "type": "text"
        }
      ],
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchOptions",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchAttributes",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchDeviceAttributes"
      ],
      "title": "Data Types"
    },
    {
      "abstract": [
        {
          "text": "See the Overview for header-level documentation.",
          "type": "text"
        }
      ],
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchDeviceAttributes",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchTypesBits"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Miscellaneous",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothAddSCOAudioDevice",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothIgnoreHIDDevice(_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelRegisterForChannelCloseNotification(_:_:_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRemoveIgnoredHIDDevice(_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRemoveSCOAudioDevice",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothUserNotificationUnregister(_:)"
              ],
              "title": "Miscellaneous"
            },
            {
              "abstract": [
                {
                  "text": "See the Overview for header-level documentation.",
                  "type": "text"
                }
              ],
              "anchor": "Callbacks",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothUserNotificationCallback"
              ],
              "title": "Callbacks"
            },
            {
              "abstract": [
                {
                  "text": "See the Overview for header-level documentation.",
                  "type": "text"
                }
              ],
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchOptions",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchAttributes",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchDeviceAttributes"
              ],
              "title": "Data Types"
            },
            {
              "abstract": [
                {
                  "text": "See the Overview for header-level documentation.",
                  "type": "text"
                }
              ],
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchDeviceAttributes",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchTypesBits"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/bluetooth-h-user-space",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothutilities-h",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/obex-h",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexbluetooth-h",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexfiletransferservices-h",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-structures",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-constants",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-functions",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceSearchOptions/title",
          "value": "IOBluetoothDeviceSearchOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceSearchOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSearchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceSearchOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSearchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothUserNotificationUnregister(_:)/title",
          "value": "IOBluetoothUserNotificationUnregister"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothUserNotificationUnregister(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothUserNotificationUnregister"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothIgnoreHIDDevice(_:)/title",
          "value": "IOBluetoothIgnoreHIDDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothIgnoreHIDDevice(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothIgnoreHIDDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothUserNotificationCallback/title",
          "value": "IOBluetoothUserNotificationCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothUserNotificationCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothUserNotificationCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothUserNotificationCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothUserNotificationCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRemoveIgnoredHIDDevice(_:)/title",
          "value": "IOBluetoothRemoveIgnoredHIDDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRemoveIgnoredHIDDevice(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothRemoveIgnoredHIDDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceSearchAttributes/title",
          "value": "IOBluetoothDeviceSearchAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceSearchAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSearchAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceSearchAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSearchAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceSearchTypesBits/title",
          "value": "IOBluetoothDeviceSearchTypesBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceSearchTypesBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSearchTypesBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceSearchTypesBits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSearchTypesBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelRegisterForChannelCloseNotification(_:_:_:)/title",
          "value": "IOBluetoothL2CAPChannelRegisterForChannelCloseNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelRegisterForChannelCloseNotification(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothL2CAPChannelRegisterForChannelCloseNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceSearchDeviceAttributes/title",
          "value": "IOBluetoothDeviceSearchDeviceAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceSearchDeviceAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSearchDeviceAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceSearchDeviceAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSearchDeviceAttributes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/iobluetoothuserlib-h"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/iobluetoothuserlib-h"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
