{
  "abstract": [
    {
      "text": "See the Overview section above for header-level documentation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothutilities-h"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "IOBluetoothUtilities.h"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Included-Headers",
          "level": 4,
          "text": "Included Headers",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<stdio.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<stdlib.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<string.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<sysexits.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<sys/errno.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<unistd.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<IOBluetooth/Bluetooth.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<IOKit/IOReturn.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<IOBluetooth/IOBluetoothUserLib.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothFindNumberOfRegistryEntriesOfClassName(_:)": {
      "abstract": [
        {
          "text": "The number of registry entries with a device classname.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothFindNumberOfRegistryEntriesOfClassName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothFindNumberOfRegistryEntriesOfClassName(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothFindNumberOfRegistryEntriesOfClassName"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothFindNumberOfRegistryEntriesOfClassName(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothfindnumberofregistryentriesofclassname(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothGetUniqueFileNameAndPath(_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothGetUniqueFileNameAndPath"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothGetUniqueFileNameAndPath(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothGetUniqueFileNameAndPath"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothGetUniqueFileNameAndPath(_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothgetuniquefilenameandpath(_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothIsFileAppleDesignatedPIMData(_:)": {
      "abstract": [
        {
          "text": "Apple designated PIM data is classified as: .vcard, .vcal, .vcf, .vnote, .vmsg, .vcs",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothIsFileAppleDesignatedPIMData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothIsFileAppleDesignatedPIMData(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothIsFileAppleDesignatedPIMData"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothIsFileAppleDesignatedPIMData(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothisfileappledesignatedpimdata(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNSStringFromDeviceAddress(_:)": {
      "abstract": [
        {
          "text": "Convenience routine to take a device address structure and create an NSString.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothNSStringFromDeviceAddress"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothDeviceAddress",
          "text": "BluetoothDeviceAddress"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNSStringFromDeviceAddress(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothNSStringFromDeviceAddress"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothNSStringFromDeviceAddress(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothnsstringfromdeviceaddress(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNSStringToDeviceAddress(_:_:)": {
      "abstract": [
        {
          "text": "Convenience routine to take an NSString and turn it into a BluetoothDeviceAddress structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothNSStringToDeviceAddress"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothDeviceAddress",
          "text": "BluetoothDeviceAddress"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOReturn",
          "text": "IOReturn"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNSStringToDeviceAddress(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothNSStringToDeviceAddress"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothNSStringToDeviceAddress(_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothnsstringtodeviceaddress(_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNumberOfAvailableHIDDevices()": {
      "abstract": [
        {
          "text": "Returns total number of HID devices on the system (Bluetooth + USB)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothNumberOfAvailableHIDDevices"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNumberOfAvailableHIDDevices()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothNumberOfAvailableHIDDevices"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothNumberOfAvailableHIDDevices()",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothnumberofavailablehiddevices()"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNumberOfKeyboardHIDDevices()": {
      "abstract": [
        {
          "text": "Returns number of keyboard HID devices on the system (Bluetooth + USB)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothNumberOfKeyboardHIDDevices"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNumberOfKeyboardHIDDevices()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothNumberOfKeyboardHIDDevices"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothNumberOfKeyboardHIDDevices()",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothnumberofkeyboardhiddevices()"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNumberOfPointingHIDDevices()": {
      "abstract": [
        {
          "text": "Returns number of “pointing” HID devices on the system (Bluetooth + USB)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothNumberOfPointingHIDDevices"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNumberOfPointingHIDDevices()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothNumberOfPointingHIDDevices"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothNumberOfPointingHIDDevices()",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothnumberofpointinghiddevices()"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNumberOfTabletHIDDevices()": {
      "abstract": [
        {
          "text": "Returns number of “Tablet” HID devices on the system (Bluetooth + USB)",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothNumberOfTabletHIDDevices"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNumberOfTabletHIDDevices()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothNumberOfTabletHIDDevices"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothNumberOfTabletHIDDevices()",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothnumberoftablethiddevices()"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPackData": {
      "abstract": [
        {
          "text": "Packs a variable amount of parameters into a buffer according to a printf-style format string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOBluetoothPackData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPackData",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOBluetoothPackData",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothpackdata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothUnpackData": {
      "abstract": [
        {
          "text": "Unpacks a variable amount of data from a buffer into a variable number of parameters according to a printf-style format string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOBluetoothUnpackData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothUnpackData",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOBluetoothUnpackData",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothunpackdata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/bluetooth-h-user-space": {
      "abstract": [
        {
          "text": "Bluetooth wireless technology",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/bluetooth-h-user-space",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Bluetooth.h User-Space",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetooth-h-user-space"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Constants",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-constants"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Data Types",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-data-types"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Enumerations",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-enumerations"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Functions",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-functions"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Structures",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-structures"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothuserlib-h": {
      "abstract": [
        {
          "text": "Public Interfaces for Apple’s implementation of Bluetooth technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothuserlib-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetoothUserLib.h",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothuserlib-h"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/obex-h": {
      "abstract": [
        {
          "text": "Public OBEX technology interfaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/obex-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OBEX.h",
      "type": "topic",
      "url": "/documentation/iobluetooth/obex-h"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexbluetooth-h": {
      "abstract": [
        {
          "text": "Object Exchange over Bluetooth.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexbluetooth-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OBEXBluetooth.h",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexbluetooth-h"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexfiletransferservices-h": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexfiletransferservices-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OBEXFileTransferServices.h",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexfiletransferservices-h"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/bluetooth-h-user-space",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothuserlib-h",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/obex-h",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexbluetooth-h",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexfiletransferservices-h",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-structures",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-constants",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-functions",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Miscellaneous",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothFindNumberOfRegistryEntriesOfClassName(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothGetUniqueFileNameAndPath(_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothIsFileAppleDesignatedPIMData(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNSStringFromDeviceAddress(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNSStringToDeviceAddress(_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNumberOfAvailableHIDDevices()",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNumberOfKeyboardHIDDevices()",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNumberOfPointingHIDDevices()",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNumberOfTabletHIDDevices()"
      ],
      "title": "Miscellaneous"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Miscellaneous",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothFindNumberOfRegistryEntriesOfClassName(_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothGetUniqueFileNameAndPath(_:_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothIsFileAppleDesignatedPIMData(_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNSStringFromDeviceAddress(_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNSStringToDeviceAddress(_:_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNumberOfAvailableHIDDevices()",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNumberOfKeyboardHIDDevices()",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNumberOfPointingHIDDevices()",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNumberOfTabletHIDDevices()",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPackData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothUnpackData"
              ],
              "title": "Miscellaneous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/bluetooth-h-user-space",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothuserlib-h",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/obex-h",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexbluetooth-h",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexfiletransferservices-h",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-structures",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-constants",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-functions",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothFindNumberOfRegistryEntriesOfClassName(_:)/title",
          "value": "IOBluetoothFindNumberOfRegistryEntriesOfClassName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothFindNumberOfRegistryEntriesOfClassName(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothFindNumberOfRegistryEntriesOfClassName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothNumberOfPointingHIDDevices()/title",
          "value": "IOBluetoothNumberOfPointingHIDDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothNumberOfPointingHIDDevices()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothNumberOfPointingHIDDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothNSStringFromDeviceAddress(_:)/title",
          "value": "IOBluetoothNSStringFromDeviceAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothNSStringFromDeviceAddress(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothNSStringFromDeviceAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothNumberOfKeyboardHIDDevices()/title",
          "value": "IOBluetoothNumberOfKeyboardHIDDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothNumberOfKeyboardHIDDevices()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothNumberOfKeyboardHIDDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothGetUniqueFileNameAndPath(_:_:)/title",
          "value": "IOBluetoothGetUniqueFileNameAndPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothGetUniqueFileNameAndPath(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothGetUniqueFileNameAndPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothIsFileAppleDesignatedPIMData(_:)/title",
          "value": "IOBluetoothIsFileAppleDesignatedPIMData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothIsFileAppleDesignatedPIMData(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothIsFileAppleDesignatedPIMData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothNSStringToDeviceAddress(_:_:)/title",
          "value": "IOBluetoothNSStringToDeviceAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothNSStringToDeviceAddress(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothNSStringToDeviceAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothNumberOfAvailableHIDDevices()/title",
          "value": "IOBluetoothNumberOfAvailableHIDDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothNumberOfAvailableHIDDevices()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothNumberOfAvailableHIDDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothNumberOfTabletHIDDevices()/title",
          "value": "IOBluetoothNumberOfTabletHIDDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothNumberOfTabletHIDDevices()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothNumberOfTabletHIDDevices"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/iobluetoothutilities-h"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/iobluetoothutilities-h"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
