{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)IOBluetoothRFCOMMChannelDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOBluetoothRFCOMMChannelDelegate"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOBluetoothRFCOMMChannelDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "IOBluetoothRFCOMMChannelDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOBluetoothRFCOMMChannelDelegate"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceAsyncCallbacks": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceAsyncCallbacks"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceAsyncCallbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceAsyncCallbacks"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothDeviceAsyncCallbacks",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdeviceasynccallbacks"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceInquiryDelegate": {
      "abstract": [
        {
          "text": "This category on NSObject describes the delegate methods for the IOBluetoothDeviceInquiry object. All methods are optional, but it is highly recommended you implement them all. Do NOT invoke remote name requests on found IOBluetoothDevice objects unless the inquiry object has been stopped. Doing so may deadlock your process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceInquiryDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceInquiryDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceInquiryDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothDeviceInquiryDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdeviceinquirydelegate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothDevicePairDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothDevicePairDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothDevicePairDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdevicepairdelegate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGatewayDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods for receiving information about status changes for a connected Bluetooth hands-free phone or headset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeAudioGatewayDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGatewayDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeAudioGatewayDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeAudioGatewayDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreeaudiogatewaydelegate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreedelegate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods for receiving status change updates and information about a connected Bluetooth hands-free phone or headset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeDeviceDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeDeviceDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeDeviceDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreedevicedelegate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothL2CAPChannelDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothL2CAPChannelDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothL2CAPChannelDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothl2capchanneldelegate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothOBEXSession": {
      "abstract": [
        {
          "text": "An OBEX Session with a Bluetooth RFCOMM channel as the transport.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothOBEXSession"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothOBEXSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothOBEXSession"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothOBEXSession",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothobexsession"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothRFCOMMChannelDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothRFCOMMChannelDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothRFCOMMChannelDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothrfcommchanneldelegate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelClosed(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rfcommChannelClosed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothRFCOMMChannel",
          "text": "IOBluetoothRFCOMMChannel"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelClosed(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rfcommChannelClosed:"
        }
      ],
      "role": "symbol",
      "title": "rfcommChannelClosed(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothrfcommchanneldelegate/rfcommchannelclosed(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelControlSignalsChanged(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rfcommChannelControlSignalsChanged"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothRFCOMMChannel",
          "text": "IOBluetoothRFCOMMChannel"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelControlSignalsChanged(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rfcommChannelControlSignalsChanged:"
        }
      ],
      "role": "symbol",
      "title": "rfcommChannelControlSignalsChanged(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothrfcommchanneldelegate/rfcommchannelcontrolsignalschanged(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelData(_:data:length:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rfcommChannelData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothRFCOMMChannel",
          "text": "IOBluetoothRFCOMMChannel"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "length"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelData(_:data:length:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rfcommChannelData:data:length:"
        }
      ],
      "role": "symbol",
      "title": "rfcommChannelData(_:data:length:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothrfcommchanneldelegate/rfcommchanneldata(_:data:length:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelFlowControlChanged(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rfcommChannelFlowControlChanged"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothRFCOMMChannel",
          "text": "IOBluetoothRFCOMMChannel"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelFlowControlChanged(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rfcommChannelFlowControlChanged:"
        }
      ],
      "role": "symbol",
      "title": "rfcommChannelFlowControlChanged(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothrfcommchanneldelegate/rfcommchannelflowcontrolchanged(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelOpenComplete(_:status:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rfcommChannelOpenComplete"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothRFCOMMChannel",
          "text": "IOBluetoothRFCOMMChannel"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOReturn",
          "text": "IOReturn"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelOpenComplete(_:status:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rfcommChannelOpenComplete:status:"
        }
      ],
      "role": "symbol",
      "title": "rfcommChannelOpenComplete(_:status:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothrfcommchanneldelegate/rfcommchannelopencomplete(_:status:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelQueueSpaceAvailable(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rfcommChannelQueueSpaceAvailable"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothRFCOMMChannel",
          "text": "IOBluetoothRFCOMMChannel"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelQueueSpaceAvailable(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rfcommChannelQueueSpaceAvailable:"
        }
      ],
      "role": "symbol",
      "title": "rfcommChannelQueueSpaceAvailable(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothrfcommchanneldelegate/rfcommchannelqueuespaceavailable(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelWriteComplete(_:refcon:status:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rfcommChannelWriteComplete"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothRFCOMMChannel",
          "text": "IOBluetoothRFCOMMChannel"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "refcon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOReturn",
          "text": "IOReturn"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelWriteComplete(_:refcon:status:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rfcommChannelWriteComplete:refcon:status:"
        }
      ],
      "role": "symbol",
      "title": "rfcommChannelWriteComplete(_:refcon:status:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothrfcommchanneldelegate/rfcommchannelwritecomplete(_:refcon:status:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelWriteComplete(_:refcon:status:bytesWritten:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rfcommChannelWriteComplete"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothRFCOMMChannel",
          "text": "IOBluetoothRFCOMMChannel"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "refcon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOReturn",
          "text": "IOReturn"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "bytesWritten"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelWriteComplete(_:refcon:status:bytesWritten:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rfcommChannelWriteComplete:refcon:status:bytesWritten:"
        }
      ],
      "role": "symbol",
      "title": "rfcommChannelWriteComplete(_:refcon:status:bytesWritten:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothrfcommchanneldelegate/rfcommchannelwritecomplete(_:refcon:status:byteswritten:)"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothOBEXSession"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceAsyncCallbacks",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceInquiryDelegate",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGatewayDelegate",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDelegate",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate"
      ],
      "title": "Protocols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelClosed(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelControlSignalsChanged(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelData(_:data:length:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelFlowControlChanged(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelOpenComplete(_:status:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelQueueSpaceAvailable(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelWriteComplete(_:refcon:status:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelWriteComplete(_:refcon:status:bytesWritten:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOBluetoothRFCOMMChannelDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothRFCOMMChannelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothRFCOMMChannelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelClosed(_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelControlSignalsChanged(_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelData(_:data:length:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelFlowControlChanged(_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelOpenComplete(_:status:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelQueueSpaceAvailable(_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelWriteComplete(_:refcon:status:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate/rfcommChannelWriteComplete(_:refcon:status:bytesWritten:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothOBEXSession"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceAsyncCallbacks",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceInquiryDelegate",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGatewayDelegate",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDelegate",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate"
              ],
              "title": "Protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOBluetoothRFCOMMChannelDelegate"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate~1rfcommChannelData(_:data:length:)/title",
          "value": "rfcommChannelData:data:length:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate~1rfcommChannelData(_:data:length:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rfcommChannelData:data:length:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDelegate/title",
          "value": "IOBluetoothHandsFreeDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate~1rfcommChannelWriteComplete(_:refcon:status:bytesWritten:)/title",
          "value": "rfcommChannelWriteComplete:refcon:status:bytesWritten:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate~1rfcommChannelWriteComplete(_:refcon:status:bytesWritten:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rfcommChannelWriteComplete:refcon:status:bytesWritten:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate~1rfcommChannelFlowControlChanged(_:)/title",
          "value": "rfcommChannelFlowControlChanged:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate~1rfcommChannelFlowControlChanged(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rfcommChannelFlowControlChanged:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate/title",
          "value": "IOBluetoothRFCOMMChannelDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothRFCOMMChannelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothRFCOMMChannelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothOBEXSession/title",
          "value": "IOBluetoothOBEXSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothOBEXSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothOBEXSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothOBEXSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothOBEXSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate/title",
          "value": "IOBluetoothHandsFreeDeviceDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate~1rfcommChannelQueueSpaceAvailable(_:)/title",
          "value": "rfcommChannelQueueSpaceAvailable:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate~1rfcommChannelQueueSpaceAvailable(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rfcommChannelQueueSpaceAvailable:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceInquiryDelegate/title",
          "value": "IOBluetoothDeviceInquiryDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceInquiryDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceInquiryDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceInquiryDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceInquiryDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeAudioGatewayDelegate/title",
          "value": "IOBluetoothHandsFreeAudioGatewayDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeAudioGatewayDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeAudioGatewayDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeAudioGatewayDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeAudioGatewayDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceAsyncCallbacks/title",
          "value": "IOBluetoothDeviceAsyncCallbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceAsyncCallbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceAsyncCallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceAsyncCallbacks/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceAsyncCallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate/title",
          "value": "IOBluetoothDevicePairDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDevicePairDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDevicePairDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate~1rfcommChannelClosed(_:)/title",
          "value": "rfcommChannelClosed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate~1rfcommChannelClosed(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rfcommChannelClosed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelDelegate/title",
          "value": "IOBluetoothL2CAPChannelDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothL2CAPChannelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothL2CAPChannelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate~1rfcommChannelOpenComplete(_:status:)/title",
          "value": "rfcommChannelOpenComplete:status:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate~1rfcommChannelOpenComplete(_:status:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rfcommChannelOpenComplete:status:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate~1rfcommChannelWriteComplete(_:refcon:status:)/title",
          "value": "rfcommChannelWriteComplete:refcon:status:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate~1rfcommChannelWriteComplete(_:refcon:status:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rfcommChannelWriteComplete:refcon:status:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate~1rfcommChannelControlSignalsChanged(_:)/title",
          "value": "rfcommChannelControlSignalsChanged:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate~1rfcommChannelControlSignalsChanged(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rfcommChannelControlSignalsChanged:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/iobluetoothrfcommchanneldelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/iobluetoothrfcommchanneldelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
