{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-functions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "IOBluetooth Functions"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNSStringFromDeviceAddressColon(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothNSStringFromDeviceAddressColon"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothDeviceAddress",
          "text": "BluetoothDeviceAddress"
        },
        {
          "kind": "text",
          "text": ">!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNSStringFromDeviceAddressColon(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothNSStringFromDeviceAddressColon"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothNSStringFromDeviceAddressColon(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothnsstringfromdeviceaddresscolon(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPackDataList(_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothPackDataList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s14CVaListPointerV",
          "text": "CVaListPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPackDataList(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothPackDataList"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothPackDataList(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothpackdatalist(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothUnpackDataList(_:_:_:_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothUnpackDataList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s14CVaListPointerV",
          "text": "CVaListPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothUnpackDataList(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothUnpackDataList"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothUnpackDataList(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothunpackdatalist(_:_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionGetAvailableCommandPayloadLength": {
      "abstract": [
        {
          "text": "Gets space available for your data for a particular command response you are trying to send.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OBEXSessionGetAvailableCommandPayloadLength"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionGetAvailableCommandPayloadLength",
      "kind": "symbol",
      "role": "symbol",
      "title": "OBEXSessionGetAvailableCommandPayloadLength",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexsessiongetavailablecommandpayloadlength"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/bluetooth-h-user-space": {
      "abstract": [
        {
          "text": "Bluetooth wireless technology",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/bluetooth-h-user-space",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Bluetooth.h User-Space",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetooth-h-user-space"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Constants",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-constants"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Data Types",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-data-types"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Enumerations",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-enumerations"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Structures",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-structures"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothuserlib-h": {
      "abstract": [
        {
          "text": "Public Interfaces for Apple’s implementation of Bluetooth technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothuserlib-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetoothUserLib.h",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothuserlib-h"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothutilities-h": {
      "abstract": [
        {
          "text": "See the Overview section above for header-level documentation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothutilities-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetoothUtilities.h",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothutilities-h"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/obex-h": {
      "abstract": [
        {
          "text": "Public OBEX technology interfaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/obex-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OBEX.h",
      "type": "topic",
      "url": "/documentation/iobluetooth/obex-h"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexbluetooth-h": {
      "abstract": [
        {
          "text": "Object Exchange over Bluetooth.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexbluetooth-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OBEXBluetooth.h",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexbluetooth-h"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexfiletransferservices-h": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexfiletransferservices-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OBEXFileTransferServices.h",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexfiletransferservices-h"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/bluetooth-h-user-space",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothuserlib-h",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothutilities-h",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/obex-h",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexbluetooth-h",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexfiletransferservices-h",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-structures",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-constants",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNSStringFromDeviceAddressColon(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPackDataList(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothUnpackDataList(_:_:_:_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothNSStringFromDeviceAddressColon(_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPackDataList(_:_:_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothUnpackDataList(_:_:_:_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionGetAvailableCommandPayloadLength"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/bluetooth-h-user-space",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothuserlib-h",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothutilities-h",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/obex-h",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexbluetooth-h",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexfiletransferservices-h",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-structures",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-constants",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothNSStringFromDeviceAddressColon(_:)/title",
          "value": "IOBluetoothNSStringFromDeviceAddressColon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothNSStringFromDeviceAddressColon(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothNSStringFromDeviceAddressColon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothPackDataList(_:_:_:)/title",
          "value": "IOBluetoothPackDataList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothPackDataList(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPackDataList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothUnpackDataList(_:_:_:_:)/title",
          "value": "IOBluetoothUnpackDataList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothUnpackDataList(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothUnpackDataList"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/iobluetooth-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/iobluetooth-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
