{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)IOBluetoothDevicePairDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "IOBluetoothDevicePairDelegate"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IOBluetoothDevicePairDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "IOBluetoothDevicePairDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IOBluetoothDevicePairDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceAsyncCallbacks": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceAsyncCallbacks"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceAsyncCallbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceAsyncCallbacks"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothDeviceAsyncCallbacks",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdeviceasynccallbacks"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceInquiryDelegate": {
      "abstract": [
        {
          "text": "This category on NSObject describes the delegate methods for the IOBluetoothDeviceInquiry object. All methods are optional, but it is highly recommended you implement them all. Do NOT invoke remote name requests on found IOBluetoothDevice objects unless the inquiry object has been stopped. Doing so may deadlock your process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceInquiryDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceInquiryDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceInquiryDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothDeviceInquiryDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdeviceinquirydelegate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothDevicePairDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothDevicePairDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothDevicePairDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdevicepairdelegate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingConnected(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "devicePairingConnected"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingConnected(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "devicePairingConnected:"
        }
      ],
      "role": "symbol",
      "title": "devicePairingConnected(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdevicepairdelegate/devicepairingconnected(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingConnecting(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "devicePairingConnecting"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingConnecting(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "devicePairingConnecting:"
        }
      ],
      "role": "symbol",
      "title": "devicePairingConnecting(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdevicepairdelegate/devicepairingconnecting(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingFinished(_:error:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "devicePairingFinished"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@IOReturn",
          "text": "IOReturn"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingFinished(_:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "devicePairingFinished:error:"
        }
      ],
      "role": "symbol",
      "title": "devicePairingFinished(_:error:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdevicepairdelegate/devicepairingfinished(_:error:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingPINCodeRequest(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "devicePairingPINCodeRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingPINCodeRequest(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "devicePairingPINCodeRequest:"
        }
      ],
      "role": "symbol",
      "title": "devicePairingPINCodeRequest(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdevicepairdelegate/devicepairingpincoderequest(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingStarted(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "devicePairingStarted"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingStarted(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "devicePairingStarted:"
        }
      ],
      "role": "symbol",
      "title": "devicePairingStarted(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdevicepairdelegate/devicepairingstarted(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingUserConfirmationRequest(_:numericValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "devicePairingUserConfirmationRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "numericValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BluetoothNumericValue",
          "text": "BluetoothNumericValue"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingUserConfirmationRequest(_:numericValue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "devicePairingUserConfirmationRequest:numericValue:"
        }
      ],
      "role": "symbol",
      "title": "devicePairingUserConfirmationRequest(_:numericValue:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdevicepairdelegate/devicepairinguserconfirmationrequest(_:numericvalue:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingUserPasskeyNotification(_:passkey:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "devicePairingUserPasskeyNotification"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "passkey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BluetoothPasskey",
          "text": "BluetoothPasskey"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingUserPasskeyNotification(_:passkey:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "devicePairingUserPasskeyNotification:passkey:"
        }
      ],
      "role": "symbol",
      "title": "devicePairingUserPasskeyNotification(_:passkey:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdevicepairdelegate/devicepairinguserpasskeynotification(_:passkey:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/deviceSimplePairingComplete(_:status:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceSimplePairingComplete"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BluetoothHCIEventStatus",
          "text": "BluetoothHCIEventStatus"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/deviceSimplePairingComplete(_:status:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceSimplePairingComplete:status:"
        }
      ],
      "role": "symbol",
      "title": "deviceSimplePairingComplete(_:status:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdevicepairdelegate/devicesimplepairingcomplete(_:status:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGatewayDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods for receiving information about status changes for a connected Bluetooth hands-free phone or headset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeAudioGatewayDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGatewayDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeAudioGatewayDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeAudioGatewayDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreeaudiogatewaydelegate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreedelegate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods for receiving status change updates and information about a connected Bluetooth hands-free phone or headset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeDeviceDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeDeviceDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeDeviceDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreedevicedelegate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothL2CAPChannelDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothL2CAPChannelDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothL2CAPChannelDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothl2capchanneldelegate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothRFCOMMChannelDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothRFCOMMChannelDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothRFCOMMChannelDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothrfcommchanneldelegate"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceAsyncCallbacks",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceInquiryDelegate",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGatewayDelegate",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDelegate",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate"
      ],
      "title": "Protocols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingConnected(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingConnecting(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingFinished(_:error:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingPINCodeRequest(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingStarted(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingUserConfirmationRequest(_:numericValue:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingUserPasskeyNotification(_:passkey:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/deviceSimplePairingComplete(_:status:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "IOBluetoothDevicePairDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDevicePairDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDevicePairDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingConnected(_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingConnecting(_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingFinished(_:error:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingPINCodeRequest(_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingStarted(_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingUserConfirmationRequest(_:numericValue:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/devicePairingUserPasskeyNotification(_:passkey:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDevicePairDelegate/deviceSimplePairingComplete(_:status:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceAsyncCallbacks",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceInquiryDelegate",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGatewayDelegate",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDelegate",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelDelegate",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothRFCOMMChannelDelegate"
              ],
              "title": "Protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "IOBluetoothDevicePairDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate/title",
          "value": "IOBluetoothDevicePairDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDevicePairDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDevicePairDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate/title",
          "value": "IOBluetoothHandsFreeDeviceDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate~1devicePairingUserPasskeyNotification(_:passkey:)/title",
          "value": "devicePairingUserPasskeyNotification:passkey:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate~1devicePairingUserPasskeyNotification(_:passkey:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "devicePairingUserPasskeyNotification:passkey:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate~1devicePairingPINCodeRequest(_:)/title",
          "value": "devicePairingPINCodeRequest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate~1devicePairingPINCodeRequest(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "devicePairingPINCodeRequest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelDelegate/title",
          "value": "IOBluetoothL2CAPChannelDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothL2CAPChannelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothL2CAPChannelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate~1devicePairingConnecting(_:)/title",
          "value": "devicePairingConnecting:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate~1devicePairingConnecting(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "devicePairingConnecting:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate/title",
          "value": "IOBluetoothRFCOMMChannelDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothRFCOMMChannelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothRFCOMMChannelDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothRFCOMMChannelDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate~1devicePairingFinished(_:error:)/title",
          "value": "devicePairingFinished:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate~1devicePairingFinished(_:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "devicePairingFinished:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate~1devicePairingConnected(_:)/title",
          "value": "devicePairingConnected:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate~1devicePairingConnected(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "devicePairingConnected:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate~1deviceSimplePairingComplete(_:status:)/title",
          "value": "deviceSimplePairingComplete:status:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate~1deviceSimplePairingComplete(_:status:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deviceSimplePairingComplete:status:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate~1devicePairingStarted(_:)/title",
          "value": "devicePairingStarted:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate~1devicePairingStarted(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "devicePairingStarted:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceAsyncCallbacks/title",
          "value": "IOBluetoothDeviceAsyncCallbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceAsyncCallbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceAsyncCallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceAsyncCallbacks/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceAsyncCallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDelegate/title",
          "value": "IOBluetoothHandsFreeDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceInquiryDelegate/title",
          "value": "IOBluetoothDeviceInquiryDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceInquiryDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceInquiryDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceInquiryDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceInquiryDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeAudioGatewayDelegate/title",
          "value": "IOBluetoothHandsFreeAudioGatewayDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeAudioGatewayDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeAudioGatewayDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeAudioGatewayDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeAudioGatewayDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate~1devicePairingUserConfirmationRequest(_:numericValue:)/title",
          "value": "devicePairingUserConfirmationRequest:numericValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDevicePairDelegate~1devicePairingUserConfirmationRequest(_:numericValue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "devicePairingUserConfirmationRequest:numericValue:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/iobluetoothdevicepairdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/iobluetoothdevicepairdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
