{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeDebugCombination"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kBluetoothKeyTypeCombination@kBluetoothKeyTypeDebugCombination",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothKeyTypeDebugCombination"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothKeyTypeDebugCombination"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothKeyTypeDebugCombination"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothKeyTypeDebugCombination"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeAuthenticatedCombination": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothKeyTypeAuthenticatedCombination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeAuthenticatedCombination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothKeyTypeAuthenticatedCombination"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothKeyTypeAuthenticatedCombination",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothkeytypeauthenticatedcombination"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeAuthenticatedCombinationP256": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothKeyTypeAuthenticatedCombinationP256"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeAuthenticatedCombinationP256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothKeyTypeAuthenticatedCombinationP256"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothKeyTypeAuthenticatedCombinationP256",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothkeytypeauthenticatedcombinationp256"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeChangedCombination": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothKeyTypeChangedCombination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeChangedCombination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothKeyTypeChangedCombination"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothKeyTypeChangedCombination",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothkeytypechangedcombination"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeCombination": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothKeyTypeCombination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeCombination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothKeyTypeCombination"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothKeyTypeCombination",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothkeytypecombination"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeDebugCombination": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothKeyTypeDebugCombination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeDebugCombination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothKeyTypeDebugCombination"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothKeyTypeDebugCombination",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothkeytypedebugcombination"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeLocalUnit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothKeyTypeLocalUnit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeLocalUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothKeyTypeLocalUnit"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothKeyTypeLocalUnit",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothkeytypelocalunit"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeRemoteUnit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothKeyTypeRemoteUnit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeRemoteUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothKeyTypeRemoteUnit"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothKeyTypeRemoteUnit",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothkeytyperemoteunit"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeUnauthenticatedCombination": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothKeyTypeUnauthenticatedCombination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeUnauthenticatedCombination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothKeyTypeUnauthenticatedCombination"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothKeyTypeUnauthenticatedCombination",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothkeytypeunauthenticatedcombination"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeUnauthenticatedCombinationP256": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothKeyTypeUnauthenticatedCombinationP256"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeUnauthenticatedCombinationP256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothKeyTypeUnauthenticatedCombinationP256"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothKeyTypeUnauthenticatedCombinationP256",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothkeytypeunauthenticatedcombinationp256"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeAuthenticatedCombination",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeChangedCombination",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeCombination",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeLocalUnit",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeRemoteUnit",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeUnauthenticatedCombination",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeAuthenticatedCombinationP256",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeUnauthenticatedCombinationP256"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothKeyTypeDebugCombination"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothKeyTypeDebugCombination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeAuthenticatedCombination",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeChangedCombination",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeCombination",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeLocalUnit",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeRemoteUnit",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeUnauthenticatedCombination",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeAuthenticatedCombinationP256",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeyTypeUnauthenticatedCombinationP256"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothKeyTypeDebugCombination"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeyTypeRemoteUnit/title",
          "value": "kBluetoothKeyTypeRemoteUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeyTypeRemoteUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothKeyTypeRemoteUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeyTypeLocalUnit/title",
          "value": "kBluetoothKeyTypeLocalUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeyTypeLocalUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothKeyTypeLocalUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeyTypeAuthenticatedCombinationP256/title",
          "value": "kBluetoothKeyTypeAuthenticatedCombinationP256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeyTypeAuthenticatedCombinationP256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothKeyTypeAuthenticatedCombinationP256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeyTypeCombination/title",
          "value": "kBluetoothKeyTypeCombination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeyTypeCombination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothKeyTypeCombination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeyTypeUnauthenticatedCombinationP256/title",
          "value": "kBluetoothKeyTypeUnauthenticatedCombinationP256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeyTypeUnauthenticatedCombinationP256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothKeyTypeUnauthenticatedCombinationP256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeyTypeChangedCombination/title",
          "value": "kBluetoothKeyTypeChangedCombination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeyTypeChangedCombination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothKeyTypeChangedCombination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeyTypeDebugCombination/title",
          "value": "kBluetoothKeyTypeDebugCombination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeyTypeDebugCombination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothKeyTypeDebugCombination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeyTypeUnauthenticatedCombination/title",
          "value": "kBluetoothKeyTypeUnauthenticatedCombination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeyTypeUnauthenticatedCombination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothKeyTypeUnauthenticatedCombination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeyTypeAuthenticatedCombination/title",
          "value": "kBluetoothKeyTypeAuthenticatedCombination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeyTypeAuthenticatedCombination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothKeyTypeAuthenticatedCombination"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothkeytypedebugcombination"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothkeytypedebugcombination"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
