{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityNoInputNoOutput"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BluetoothLESecurityManagerIOCapability@kBluetoothLESecurityManagerIOCapabilityNoInputNoOutput",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothLESecurityManagerIOCapabilityNoInputNoOutput"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerIOCapability",
        "text": "BluetoothLESecurityManagerIOCapability"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothLESecurityManagerIOCapabilityNoInputNoOutput"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothLESecurityManagerIOCapabilityNoInputNoOutput"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerIOCapabilityNoInputNoOutput"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLESecurityManagerIOCapability",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerIOCapability",
              "text": "BluetoothLESecurityManagerIOCapability"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLESecurityManagerIOCapability": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothLESecurityManagerIOCapability"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLESecurityManagerIOCapability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothLESecurityManagerIOCapability"
        }
      ],
      "role": "symbol",
      "title": "BluetoothLESecurityManagerIOCapability",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothlesecuritymanageriocapability"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityDisplayOnly": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerIOCapabilityDisplayOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerIOCapability",
          "text": "BluetoothLESecurityManagerIOCapability"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityDisplayOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerIOCapabilityDisplayOnly"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerIOCapabilityDisplayOnly",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanageriocapabilitydisplayonly"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityDisplayYesNo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerIOCapabilityDisplayYesNo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerIOCapability",
          "text": "BluetoothLESecurityManagerIOCapability"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityDisplayYesNo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerIOCapabilityDisplayYesNo"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerIOCapabilityDisplayYesNo",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanageriocapabilitydisplayyesno"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityKeyboardDisplay": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerIOCapabilityKeyboardDisplay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerIOCapability",
          "text": "BluetoothLESecurityManagerIOCapability"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityKeyboardDisplay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerIOCapabilityKeyboardDisplay"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerIOCapabilityKeyboardDisplay",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanageriocapabilitykeyboarddisplay"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityKeyboardOnly": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerIOCapabilityKeyboardOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerIOCapability",
          "text": "BluetoothLESecurityManagerIOCapability"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityKeyboardOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerIOCapabilityKeyboardOnly"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerIOCapabilityKeyboardOnly",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanageriocapabilitykeyboardonly"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityNoInputNoOutput": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerIOCapabilityNoInputNoOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerIOCapability",
          "text": "BluetoothLESecurityManagerIOCapability"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityNoInputNoOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerIOCapabilityNoInputNoOutput"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerIOCapabilityNoInputNoOutput",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanageriocapabilitynoinputnooutput"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityReservedEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerIOCapabilityReservedEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerIOCapability",
          "text": "BluetoothLESecurityManagerIOCapability"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityReservedEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerIOCapabilityReservedEnd"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerIOCapabilityReservedEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanageriocapabilityreservedend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityReservedStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerIOCapabilityReservedStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerIOCapability",
          "text": "BluetoothLESecurityManagerIOCapability"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityReservedStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerIOCapabilityReservedStart"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerIOCapabilityReservedStart",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanageriocapabilityreservedstart"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityDisplayOnly",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityDisplayYesNo",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityKeyboardDisplay",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityKeyboardOnly",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityReservedEnd",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityReservedStart"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothLESecurityManagerIOCapabilityNoInputNoOutput"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerIOCapabilityNoInputNoOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLESecurityManagerIOCapability"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityDisplayOnly",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityDisplayYesNo",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityKeyboardDisplay",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityKeyboardOnly",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityReservedEnd",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerIOCapabilityReservedStart"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothLESecurityManagerIOCapabilityNoInputNoOutput"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerIOCapabilityNoInputNoOutput/title",
          "value": "kBluetoothLESecurityManagerIOCapabilityNoInputNoOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerIOCapabilityNoInputNoOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerIOCapabilityNoInputNoOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLESecurityManagerIOCapability/title",
          "value": "BluetoothLESecurityManagerIOCapability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLESecurityManagerIOCapability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLESecurityManagerIOCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLESecurityManagerIOCapability/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLESecurityManagerIOCapability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerIOCapabilityKeyboardOnly/title",
          "value": "kBluetoothLESecurityManagerIOCapabilityKeyboardOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerIOCapabilityKeyboardOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerIOCapabilityKeyboardOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerIOCapabilityReservedEnd/title",
          "value": "kBluetoothLESecurityManagerIOCapabilityReservedEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerIOCapabilityReservedEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerIOCapabilityReservedEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerIOCapabilityReservedStart/title",
          "value": "kBluetoothLESecurityManagerIOCapabilityReservedStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerIOCapabilityReservedStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerIOCapabilityReservedStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerIOCapabilityKeyboardDisplay/title",
          "value": "kBluetoothLESecurityManagerIOCapabilityKeyboardDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerIOCapabilityKeyboardDisplay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerIOCapabilityKeyboardDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerIOCapabilityDisplayOnly/title",
          "value": "kBluetoothLESecurityManagerIOCapabilityDisplayOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerIOCapabilityDisplayOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerIOCapabilityDisplayOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerIOCapabilityDisplayYesNo/title",
          "value": "kBluetoothLESecurityManagerIOCapabilityDisplayYesNo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerIOCapabilityDisplayYesNo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerIOCapabilityDisplayYesNo"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothlesecuritymanageriocapabilitynoinputnooutput"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothlesecuritymanageriocapabilitynoinputnooutput"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
