{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeHV2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kBluetoothPacketTypeReserved1@kBluetoothPacketTypeHV2",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothPacketTypeHV2"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothPacketTypeHV2"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothPacketTypeHV2"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothPacketTypeHV2"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType2DH1Omit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothPacketType2DH1Omit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType2DH1Omit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothPacketType2DH1Omit"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothPacketType2DH1Omit",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothpackettype2dh1omit"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType2DH3Omit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothPacketType2DH3Omit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType2DH3Omit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothPacketType2DH3Omit"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothPacketType2DH3Omit",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothpackettype2dh3omit"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType2DH5Omit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothPacketType2DH5Omit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType2DH5Omit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothPacketType2DH5Omit"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothPacketType2DH5Omit",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothpackettype2dh5omit"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType3DH1Omit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothPacketType3DH1Omit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType3DH1Omit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothPacketType3DH1Omit"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothPacketType3DH1Omit",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothpackettype3dh1omit"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType3DH3Omit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothPacketType3DH3Omit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType3DH3Omit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothPacketType3DH3Omit"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothPacketType3DH3Omit",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothpackettype3dh3omit"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType3DM5Omit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothPacketType3DM5Omit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType3DM5Omit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothPacketType3DM5Omit"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothPacketType3DM5Omit",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothpackettype3dm5omit"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeAUX": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothPacketTypeAUX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeAUX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothPacketTypeAUX"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothPacketTypeAUX",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothpackettypeaux"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDH1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothPacketTypeDH1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDH1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothPacketTypeDH1"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothPacketTypeDH1",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothpackettypedh1"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDH3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothPacketTypeDH3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDH3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothPacketTypeDH3"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothPacketTypeDH3",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothpackettypedh3"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDH5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothPacketTypeDH5"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDH5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothPacketTypeDH5"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothPacketTypeDH5",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothpackettypedh5"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDM1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothPacketTypeDM1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDM1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothPacketTypeDM1"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothPacketTypeDM1",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothpackettypedm1"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDM3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothPacketTypeDM3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDM3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothPacketTypeDM3"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothPacketTypeDM3",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothpackettypedm3"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDM5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothPacketTypeDM5"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDM5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothPacketTypeDM5"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothPacketTypeDM5",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothpackettypedm5"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDV": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothPacketTypeDV"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothPacketTypeDV"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothPacketTypeDV",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothpackettypedv"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothPacketTypeEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothPacketTypeEnd"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothPacketTypeEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothpackettypeend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeHV2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothPacketTypeHV2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeHV2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothPacketTypeHV2"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothPacketTypeHV2",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothpackettypehv2"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType2DH1Omit",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType2DH3Omit",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType2DH5Omit",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType3DH1Omit",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType3DH3Omit",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType3DM5Omit",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeAUX",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDH1",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDH3",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDH5",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDM1",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDM3",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDM5",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDV",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeEnd"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothPacketTypeHV2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothPacketTypeHV2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType2DH1Omit",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType2DH3Omit",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType2DH5Omit",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType3DH1Omit",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType3DH3Omit",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketType3DM5Omit",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeAUX",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDH1",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDH3",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDH5",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDM1",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDM3",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDM5",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeDV",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothPacketTypeEnd"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothPacketTypeHV2"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketTypeDM1/title",
          "value": "kBluetoothPacketTypeDM1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketTypeDM1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothPacketTypeDM1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketType2DH5Omit/title",
          "value": "kBluetoothPacketType2DH5Omit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketType2DH5Omit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothPacketType2DH5Omit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketType2DH1Omit/title",
          "value": "kBluetoothPacketType2DH1Omit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketType2DH1Omit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothPacketType2DH1Omit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketTypeDH1/title",
          "value": "kBluetoothPacketTypeDH1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketTypeDH1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothPacketTypeDH1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketTypeEnd/title",
          "value": "kBluetoothPacketTypeEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketTypeEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothPacketTypeEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketTypeDM5/title",
          "value": "kBluetoothPacketTypeDM5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketTypeDM5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothPacketTypeDM5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketTypeDV/title",
          "value": "kBluetoothPacketTypeDV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketTypeDV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothPacketTypeDV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketType3DH1Omit/title",
          "value": "kBluetoothPacketType3DH1Omit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketType3DH1Omit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothPacketType3DH1Omit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketType3DH3Omit/title",
          "value": "kBluetoothPacketType3DH3Omit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketType3DH3Omit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothPacketType3DH3Omit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketTypeHV2/title",
          "value": "kBluetoothPacketTypeHV2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketTypeHV2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothPacketTypeHV2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketTypeDM3/title",
          "value": "kBluetoothPacketTypeDM3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketTypeDM3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothPacketTypeDM3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketType2DH3Omit/title",
          "value": "kBluetoothPacketType2DH3Omit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketType2DH3Omit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothPacketType2DH3Omit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketTypeAUX/title",
          "value": "kBluetoothPacketTypeAUX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketTypeAUX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothPacketTypeAUX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketTypeDH3/title",
          "value": "kBluetoothPacketTypeDH3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketTypeDH3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothPacketTypeDH3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketType3DM5Omit/title",
          "value": "kBluetoothPacketType3DM5Omit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketType3DM5Omit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothPacketType3DM5Omit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketTypeDH5/title",
          "value": "kBluetoothPacketTypeDH5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothPacketTypeDH5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothPacketTypeDH5"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothpackettypehv2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothpackettypehv2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
