{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidContinuationState"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kBluetoothSDPErrorCodeSuccess@kBluetoothSDPErrorCodeInvalidContinuationState",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothSDPErrorCodeInvalidContinuationState"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothSDPErrorCodeInvalidContinuationState"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothSDPErrorCodeInvalidContinuationState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeInvalidContinuationState"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInsufficientResources": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInsufficientResources"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInsufficientResources",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInsufficientResources"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPErrorCodeInsufficientResources",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdperrorcodeinsufficientresources"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidContinuationState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInvalidContinuationState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidContinuationState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInvalidContinuationState"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPErrorCodeInvalidContinuationState",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdperrorcodeinvalidcontinuationstate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidPDUSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInvalidPDUSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidPDUSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInvalidPDUSize"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPErrorCodeInvalidPDUSize",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdperrorcodeinvalidpdusize"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidRequestSyntax": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInvalidRequestSyntax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidRequestSyntax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInvalidRequestSyntax"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPErrorCodeInvalidRequestSyntax",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdperrorcodeinvalidrequestsyntax"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidSDPVersion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInvalidSDPVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidSDPVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInvalidSDPVersion"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPErrorCodeInvalidSDPVersion",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdperrorcodeinvalidsdpversion"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidServiceRecordHandle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInvalidServiceRecordHandle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidServiceRecordHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeInvalidServiceRecordHandle"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPErrorCodeInvalidServiceRecordHandle",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdperrorcodeinvalidservicerecordhandle"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeReserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeReserved"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPErrorCodeReserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdperrorcodereserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReservedEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeReservedEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReservedEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeReservedEnd"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPErrorCodeReservedEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdperrorcodereservedend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReservedStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeReservedStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReservedStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeReservedStart"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPErrorCodeReservedStart",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdperrorcodereservedstart"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeSuccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeSuccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeSuccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPErrorCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPErrorCodeSuccess",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdperrorcodesuccess"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInsufficientResources",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidPDUSize",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidRequestSyntax",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidSDPVersion",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidServiceRecordHandle",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReservedEnd",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReservedStart",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeSuccess"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothSDPErrorCodeInvalidContinuationState"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeInvalidContinuationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInsufficientResources",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidPDUSize",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidRequestSyntax",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidSDPVersion",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeInvalidServiceRecordHandle",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReservedEnd",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeReservedStart",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPErrorCodeSuccess"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothSDPErrorCodeInvalidContinuationState"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInvalidPDUSize/title",
          "value": "kBluetoothSDPErrorCodeInvalidPDUSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInvalidPDUSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeInvalidPDUSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeReservedEnd/title",
          "value": "kBluetoothSDPErrorCodeReservedEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeReservedEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeReservedEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInvalidServiceRecordHandle/title",
          "value": "kBluetoothSDPErrorCodeInvalidServiceRecordHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInvalidServiceRecordHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeInvalidServiceRecordHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeReservedStart/title",
          "value": "kBluetoothSDPErrorCodeReservedStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeReservedStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeReservedStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInvalidSDPVersion/title",
          "value": "kBluetoothSDPErrorCodeInvalidSDPVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInvalidSDPVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeInvalidSDPVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInvalidRequestSyntax/title",
          "value": "kBluetoothSDPErrorCodeInvalidRequestSyntax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInvalidRequestSyntax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeInvalidRequestSyntax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInsufficientResources/title",
          "value": "kBluetoothSDPErrorCodeInsufficientResources"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInsufficientResources/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeInsufficientResources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeReserved/title",
          "value": "kBluetoothSDPErrorCodeReserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeReserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeReserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInvalidContinuationState/title",
          "value": "kBluetoothSDPErrorCodeInvalidContinuationState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeInvalidContinuationState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeInvalidContinuationState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeSuccess/title",
          "value": "kBluetoothSDPErrorCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPErrorCodeSuccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPErrorCodeSuccess"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothsdperrorcodeinvalidcontinuationstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothsdperrorcodeinvalidcontinuationstate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
