{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeature3SlotEnhancedDataRateACLPackets"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@BluetoothFeatureBits@kBluetoothFeature3SlotEnhancedDataRateACLPackets",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothFeature3SlotEnhancedDataRateACLPackets"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@BluetoothFeatureBits",
        "text": "BluetoothFeatureBits"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothFeature3SlotEnhancedDataRateACLPackets"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothFeature3SlotEnhancedDataRateACLPackets"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothFeature3SlotEnhancedDataRateACLPackets"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@BluetoothFeatureBits",
              "text": "BluetoothFeatureBits"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothFeatureBits"
        }
      ],
      "role": "symbol",
      "title": "BluetoothFeatureBits",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothfeaturebits"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeature3SlotEnhancedDataRateACLPackets": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothFeature3SlotEnhancedDataRateACLPackets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothFeatureBits",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeature3SlotEnhancedDataRateACLPackets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothFeature3SlotEnhancedDataRateACLPackets"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothFeature3SlotEnhancedDataRateACLPackets",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothfeature3slotenhanceddatarateaclpackets"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeature3SlotEnhancedDataRateeSCOPackets": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothFeature3SlotEnhancedDataRateeSCOPackets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothFeatureBits",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeature3SlotEnhancedDataRateeSCOPackets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothFeature3SlotEnhancedDataRateeSCOPackets"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothFeature3SlotEnhancedDataRateeSCOPackets",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothfeature3slotenhanceddatarateescopackets"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeature5SlotEnhancedDataRateACLPackets": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothFeature5SlotEnhancedDataRateACLPackets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothFeatureBits",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeature5SlotEnhancedDataRateACLPackets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothFeature5SlotEnhancedDataRateACLPackets"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothFeature5SlotEnhancedDataRateACLPackets",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothfeature5slotenhanceddatarateaclpackets"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAFHCapableMaster": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureAFHCapableMaster"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothFeatureBits",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAFHCapableMaster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureAFHCapableMaster"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothFeatureAFHCapableMaster",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothfeatureafhcapablemaster"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAFHCapableSlave": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureAFHCapableSlave"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothFeatureBits",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAFHCapableSlave",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureAFHCapableSlave"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothFeatureAFHCapableSlave",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothfeatureafhcapableslave"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAFHClassificationMaster": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureAFHClassificationMaster"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothFeatureBits",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAFHClassificationMaster",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureAFHClassificationMaster"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothFeatureAFHClassificationMaster",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothfeatureafhclassificationmaster"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAFHClassificationSlave": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureAFHClassificationSlave"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothFeatureBits",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAFHClassificationSlave",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureAFHClassificationSlave"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothFeatureAFHClassificationSlave",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothfeatureafhclassificationslave"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureALawLog": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureALawLog"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothFeatureBits",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureALawLog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureALawLog"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothFeatureALawLog",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothfeaturealawlog"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAbsenceMasks": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureAbsenceMasks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothFeatureBits",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAbsenceMasks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureAbsenceMasks"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothFeatureAbsenceMasks",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothfeatureabsencemasks"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAliasAuhentication": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureAliasAuhentication"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothFeatureBits",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAliasAuhentication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureAliasAuhentication"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothFeatureAliasAuhentication",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothfeaturealiasauhentication"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureBroadcastEncryption": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureBroadcastEncryption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothFeatureBits",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureBroadcastEncryption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureBroadcastEncryption"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothFeatureBroadcastEncryption",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothfeaturebroadcastencryption"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureCVSD": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureCVSD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothFeatureBits",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureCVSD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureCVSD"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothFeatureCVSD",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothfeaturecvsd"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureChannelQuality": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureChannelQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothFeatureBits",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureChannelQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureChannelQuality"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothFeatureChannelQuality",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothfeaturechannelquality"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureEV4Packets": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureEV4Packets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothFeatureBits",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureEV4Packets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureEV4Packets"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothFeatureEV4Packets",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothfeatureev4packets"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureEV5Packets": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureEV5Packets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothFeatureBits",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureEV5Packets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureEV5Packets"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothFeatureEV5Packets",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothfeatureev5packets"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureEncapsulatedPDU": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureEncapsulatedPDU"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothFeatureBits",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureEncapsulatedPDU",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothFeatureEncapsulatedPDU"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothFeatureEncapsulatedPDU",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothfeatureencapsulatedpdu"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeature3SlotEnhancedDataRateeSCOPackets",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeature5SlotEnhancedDataRateACLPackets",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAFHCapableMaster",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAFHCapableSlave",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAFHClassificationMaster",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAFHClassificationSlave",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureALawLog",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAbsenceMasks",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAliasAuhentication",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureBroadcastEncryption",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureCVSD",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureChannelQuality",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureEV4Packets",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureEV5Packets",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureEncapsulatedPDU"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothFeature3SlotEnhancedDataRateACLPackets"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothFeature3SlotEnhancedDataRateACLPackets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeature3SlotEnhancedDataRateeSCOPackets",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeature5SlotEnhancedDataRateACLPackets",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAFHCapableMaster",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAFHCapableSlave",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAFHClassificationMaster",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAFHClassificationSlave",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureALawLog",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAbsenceMasks",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureAliasAuhentication",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureBroadcastEncryption",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureCVSD",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureChannelQuality",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureEV4Packets",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureEV5Packets",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothFeatureEncapsulatedPDU"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothFeature3SlotEnhancedDataRateACLPackets"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureEV4Packets/title",
          "value": "kBluetoothFeatureEV4Packets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureEV4Packets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothFeatureEV4Packets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureEncapsulatedPDU/title",
          "value": "kBluetoothFeatureEncapsulatedPDU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureEncapsulatedPDU/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothFeatureEncapsulatedPDU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeature3SlotEnhancedDataRateACLPackets/title",
          "value": "kBluetoothFeature3SlotEnhancedDataRateACLPackets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeature3SlotEnhancedDataRateACLPackets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothFeature3SlotEnhancedDataRateACLPackets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureAbsenceMasks/title",
          "value": "kBluetoothFeatureAbsenceMasks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureAbsenceMasks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothFeatureAbsenceMasks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureCVSD/title",
          "value": "kBluetoothFeatureCVSD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureCVSD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothFeatureCVSD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureAFHClassificationMaster/title",
          "value": "kBluetoothFeatureAFHClassificationMaster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureAFHClassificationMaster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothFeatureAFHClassificationMaster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureEV5Packets/title",
          "value": "kBluetoothFeatureEV5Packets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureEV5Packets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothFeatureEV5Packets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureAFHCapableSlave/title",
          "value": "kBluetoothFeatureAFHCapableSlave"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureAFHCapableSlave/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothFeatureAFHCapableSlave"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureAFHClassificationSlave/title",
          "value": "kBluetoothFeatureAFHClassificationSlave"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureAFHClassificationSlave/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothFeatureAFHClassificationSlave"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureChannelQuality/title",
          "value": "kBluetoothFeatureChannelQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureChannelQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothFeatureChannelQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureBroadcastEncryption/title",
          "value": "kBluetoothFeatureBroadcastEncryption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureBroadcastEncryption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothFeatureBroadcastEncryption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeature5SlotEnhancedDataRateACLPackets/title",
          "value": "kBluetoothFeature5SlotEnhancedDataRateACLPackets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeature5SlotEnhancedDataRateACLPackets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothFeature5SlotEnhancedDataRateACLPackets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeature3SlotEnhancedDataRateeSCOPackets/title",
          "value": "kBluetoothFeature3SlotEnhancedDataRateeSCOPackets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeature3SlotEnhancedDataRateeSCOPackets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothFeature3SlotEnhancedDataRateeSCOPackets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureAliasAuhentication/title",
          "value": "kBluetoothFeatureAliasAuhentication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureAliasAuhentication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothFeatureAliasAuhentication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/title",
          "value": "BluetoothFeatureBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothFeatureBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothFeatureBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureAFHCapableMaster/title",
          "value": "kBluetoothFeatureAFHCapableMaster"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureAFHCapableMaster/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothFeatureAFHCapableMaster"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureALawLog/title",
          "value": "kBluetoothFeatureALawLog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothFeatureALawLog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothFeatureALawLog"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothfeature3slotenhanceddatarateaclpackets"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothfeature3slotenhanceddatarateaclpackets"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
