{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16OBEX"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kBluetoothSDPUUID16Base@kBluetoothSDPUUID16OBEX",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothSDPUUID16OBEX"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothSDPUUID16OBEX"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothSDPUUID16OBEX"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16OBEX"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16AVCTP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16AVCTP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16AVCTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16AVCTP"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16AVCTP",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16avctp"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16AVDTP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16AVDTP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16AVDTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16AVDTP"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16AVDTP",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16avdtp"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16BNEP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16BNEP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16BNEP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16BNEP"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16BNEP",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16bnep"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16Base": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16Base"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16Base",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16Base"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16Base",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16base"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16CMPT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16CMPT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16CMPT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16CMPT"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16CMPT",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16cmpt"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16FTP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16FTP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16FTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16FTP"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16FTP",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16ftp"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16HIDP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16HIDP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16HIDP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16HIDP"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16HIDP",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16hidp"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16HTTP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16HTTP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16HTTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16HTTP"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16HTTP",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16http"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16HardcopyControlChannel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16HardcopyControlChannel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16HardcopyControlChannel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16HardcopyControlChannel"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16HardcopyControlChannel",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16hardcopycontrolchannel"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16HardcopyDataChannel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16HardcopyDataChannel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16HardcopyDataChannel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16HardcopyDataChannel"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16HardcopyDataChannel",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16hardcopydatachannel"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16HardcopyNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16HardcopyNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16HardcopyNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16HardcopyNotification"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16HardcopyNotification",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16hardcopynotification"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16IP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16IP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16IP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16IP"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16IP",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16ip"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16L2CAP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16L2CAP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16L2CAP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16L2CAP"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16L2CAP",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16l2cap"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16MCAPControlChannel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16MCAPControlChannel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16MCAPControlChannel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16MCAPControlChannel"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16MCAPControlChannel",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16mcapcontrolchannel"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16MCAPDataChannel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16MCAPDataChannel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16MCAPDataChannel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16MCAPDataChannel"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16MCAPDataChannel",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16mcapdatachannel"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16OBEX": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16OBEX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16OBEX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16OBEX"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16OBEX",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16obex"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16AVCTP",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16AVDTP",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16BNEP",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16Base",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16CMPT",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16FTP",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16HIDP",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16HTTP",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16HardcopyControlChannel",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16HardcopyDataChannel",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16HardcopyNotification",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16IP",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16L2CAP",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16MCAPControlChannel",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16MCAPDataChannel"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothSDPUUID16OBEX"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16OBEX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16AVCTP",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16AVDTP",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16BNEP",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16Base",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16CMPT",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16FTP",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16HIDP",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16HTTP",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16HardcopyControlChannel",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16HardcopyDataChannel",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16HardcopyNotification",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16IP",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16L2CAP",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16MCAPControlChannel",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16MCAPDataChannel"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothSDPUUID16OBEX"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16AVDTP/title",
          "value": "kBluetoothSDPUUID16AVDTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16AVDTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16AVDTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16HardcopyDataChannel/title",
          "value": "kBluetoothSDPUUID16HardcopyDataChannel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16HardcopyDataChannel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16HardcopyDataChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16Base/title",
          "value": "kBluetoothSDPUUID16Base"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16Base/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16Base"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16IP/title",
          "value": "kBluetoothSDPUUID16IP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16IP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16IP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16HardcopyNotification/title",
          "value": "kBluetoothSDPUUID16HardcopyNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16HardcopyNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16HardcopyNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16L2CAP/title",
          "value": "kBluetoothSDPUUID16L2CAP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16L2CAP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16L2CAP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16AVCTP/title",
          "value": "kBluetoothSDPUUID16AVCTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16AVCTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16AVCTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16MCAPDataChannel/title",
          "value": "kBluetoothSDPUUID16MCAPDataChannel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16MCAPDataChannel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16MCAPDataChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16MCAPControlChannel/title",
          "value": "kBluetoothSDPUUID16MCAPControlChannel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16MCAPControlChannel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16MCAPControlChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16HTTP/title",
          "value": "kBluetoothSDPUUID16HTTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16HTTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16HTTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16BNEP/title",
          "value": "kBluetoothSDPUUID16BNEP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16BNEP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16BNEP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16FTP/title",
          "value": "kBluetoothSDPUUID16FTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16FTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16FTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16HardcopyControlChannel/title",
          "value": "kBluetoothSDPUUID16HardcopyControlChannel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16HardcopyControlChannel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16HardcopyControlChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16OBEX/title",
          "value": "kBluetoothSDPUUID16OBEX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16OBEX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16OBEX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16CMPT/title",
          "value": "kBluetoothSDPUUID16CMPT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16CMPT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16CMPT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16HIDP/title",
          "value": "kBluetoothSDPUUID16HIDP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16HIDP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16HIDP"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothsdpuuid16obex"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothsdpuuid16obex"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
