{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorObjectTransfer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kBluetoothServiceClassMajorLimitedDiscoverableMode@kBluetoothServiceClassMajorObjectTransfer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothServiceClassMajorObjectTransfer"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothServiceClassMajorObjectTransfer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothServiceClassMajorObjectTransfer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothServiceClassMajorObjectTransfer"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorAny": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorAny"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorAny",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorAny"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothServiceClassMajorAny",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothserviceclassmajorany"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorAudio": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorAudio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorAudio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorAudio"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothServiceClassMajorAudio",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothserviceclassmajoraudio"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorCapturing": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorCapturing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorCapturing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorCapturing"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothServiceClassMajorCapturing",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothserviceclassmajorcapturing"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorEnd"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothServiceClassMajorEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothserviceclassmajorend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorInformation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorInformation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorInformation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorInformation"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothServiceClassMajorInformation",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothserviceclassmajorinformation"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorLimitedDiscoverableMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorLimitedDiscoverableMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorLimitedDiscoverableMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorLimitedDiscoverableMode"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothServiceClassMajorLimitedDiscoverableMode",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothserviceclassmajorlimiteddiscoverablemode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorNetworking": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorNetworking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorNetworking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorNetworking"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothServiceClassMajorNetworking",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothserviceclassmajornetworking"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorNone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorNone"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothServiceClassMajorNone",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothserviceclassmajornone"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorObjectTransfer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorObjectTransfer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorObjectTransfer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorObjectTransfer"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothServiceClassMajorObjectTransfer",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothserviceclassmajorobjecttransfer"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorPositioning": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorPositioning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorPositioning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorPositioning"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothServiceClassMajorPositioning",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothserviceclassmajorpositioning"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorRendering": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorRendering"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorRendering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorRendering"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothServiceClassMajorRendering",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothserviceclassmajorrendering"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorReserved1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorReserved1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorReserved1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorReserved1"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothServiceClassMajorReserved1",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothserviceclassmajorreserved1"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorReserved2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorReserved2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorReserved2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorReserved2"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothServiceClassMajorReserved2",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothserviceclassmajorreserved2"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorTelephony": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorTelephony"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorTelephony",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothServiceClassMajorTelephony"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothServiceClassMajorTelephony",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothserviceclassmajortelephony"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorAny",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorAudio",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorCapturing",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorEnd",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorInformation",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorLimitedDiscoverableMode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorNetworking",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorNone",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorPositioning",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorRendering",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorReserved1",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorReserved2",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorTelephony"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothServiceClassMajorObjectTransfer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothServiceClassMajorObjectTransfer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorAny",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorAudio",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorCapturing",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorEnd",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorInformation",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorLimitedDiscoverableMode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorNetworking",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorNone",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorPositioning",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorRendering",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorReserved1",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorReserved2",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothServiceClassMajorTelephony"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothServiceClassMajorObjectTransfer"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorCapturing/title",
          "value": "kBluetoothServiceClassMajorCapturing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorCapturing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothServiceClassMajorCapturing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorInformation/title",
          "value": "kBluetoothServiceClassMajorInformation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorInformation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothServiceClassMajorInformation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorRendering/title",
          "value": "kBluetoothServiceClassMajorRendering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorRendering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothServiceClassMajorRendering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorLimitedDiscoverableMode/title",
          "value": "kBluetoothServiceClassMajorLimitedDiscoverableMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorLimitedDiscoverableMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothServiceClassMajorLimitedDiscoverableMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorReserved1/title",
          "value": "kBluetoothServiceClassMajorReserved1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorReserved1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothServiceClassMajorReserved1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorNone/title",
          "value": "kBluetoothServiceClassMajorNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothServiceClassMajorNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorPositioning/title",
          "value": "kBluetoothServiceClassMajorPositioning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorPositioning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothServiceClassMajorPositioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorEnd/title",
          "value": "kBluetoothServiceClassMajorEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothServiceClassMajorEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorTelephony/title",
          "value": "kBluetoothServiceClassMajorTelephony"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorTelephony/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothServiceClassMajorTelephony"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorObjectTransfer/title",
          "value": "kBluetoothServiceClassMajorObjectTransfer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorObjectTransfer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothServiceClassMajorObjectTransfer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorReserved2/title",
          "value": "kBluetoothServiceClassMajorReserved2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorReserved2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothServiceClassMajorReserved2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorAny/title",
          "value": "kBluetoothServiceClassMajorAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorAny/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothServiceClassMajorAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorNetworking/title",
          "value": "kBluetoothServiceClassMajorNetworking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorNetworking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothServiceClassMajorNetworking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorAudio/title",
          "value": "kBluetoothServiceClassMajorAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothServiceClassMajorAudio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothServiceClassMajorAudio"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothserviceclassmajorobjecttransfer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothserviceclassmajorobjecttransfer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
