{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConfigureRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BluetoothL2CAPCommandCode@kBluetoothL2CAPCommandCodeConfigureRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothL2CAPCommandCodeConfigureRequest"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
        "text": "BluetoothL2CAPCommandCode"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothL2CAPCommandCodeConfigureRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothL2CAPCommandCodeConfigureRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeConfigureRequest"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
              "text": "BluetoothL2CAPCommandCode"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPCommandCode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capcommandcode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCommandReject": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeCommandReject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCommandReject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeCommandReject"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeCommandReject",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodecommandreject"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConfigureRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConfigureRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConfigureRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConfigureRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeConfigureRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodeconfigurerequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConfigureResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConfigureResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConfigureResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConfigureResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeConfigureResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodeconfigureresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodeconnectionparameterupdaterequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodeconnectionparameterupdateresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConnectionRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConnectionRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeConnectionRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodeconnectionrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConnectionResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeConnectionResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeConnectionResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodeconnectionresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCreateChannelRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeCreateChannelRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCreateChannelRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeCreateChannelRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeCreateChannelRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodecreatechannelrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCreateChannelResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeCreateChannelResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCreateChannelResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeCreateChannelResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeCreateChannelResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodecreatechannelresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeDisconnectionRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeDisconnectionRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeDisconnectionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeDisconnectionRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeDisconnectionRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodedisconnectionrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeDisconnectionResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeDisconnectionResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeDisconnectionResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeDisconnectionResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeDisconnectionResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodedisconnectionresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeEchoRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeEchoRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeEchoRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeEchoRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeEchoRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodeechorequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeEchoResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeEchoResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeEchoResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeEchoResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeEchoResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodeechoresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeInformationRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeInformationRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeInformationRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeInformationRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeInformationRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodeinformationrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeInformationResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeInformationResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeInformationResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeInformationResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeInformationResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodeinformationresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPCommandCode",
          "text": "BluetoothL2CAPCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capcommandcodelecreditbasedconnectionrequest"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCommandReject",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConfigureResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCreateChannelRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCreateChannelResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeDisconnectionRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeDisconnectionResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeEchoRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeEchoResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeInformationRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeInformationResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothL2CAPCommandCodeConfigureRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeConfigureRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPCommandCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCommandReject",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConfigureResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeConnectionResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCreateChannelRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeCreateChannelResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeDisconnectionRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeDisconnectionResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeEchoRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeEchoResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeInformationRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeInformationResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothL2CAPCommandCodeConfigureRequest"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConnectionResponse/title",
          "value": "kBluetoothL2CAPCommandCodeConnectionResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConnectionResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeConnectionResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeCommandReject/title",
          "value": "kBluetoothL2CAPCommandCodeCommandReject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeCommandReject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeCommandReject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest/title",
          "value": "kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeConnectionParameterUpdateRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandCode/title",
          "value": "BluetoothL2CAPCommandCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPCommandCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPCommandCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeEchoResponse/title",
          "value": "kBluetoothL2CAPCommandCodeEchoResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeEchoResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeEchoResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeCreateChannelResponse/title",
          "value": "kBluetoothL2CAPCommandCodeCreateChannelResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeCreateChannelResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeCreateChannelResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeEchoRequest/title",
          "value": "kBluetoothL2CAPCommandCodeEchoRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeEchoRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeEchoRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeDisconnectionResponse/title",
          "value": "kBluetoothL2CAPCommandCodeDisconnectionResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeDisconnectionResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeDisconnectionResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConnectionRequest/title",
          "value": "kBluetoothL2CAPCommandCodeConnectionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConnectionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeConnectionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConfigureRequest/title",
          "value": "kBluetoothL2CAPCommandCodeConfigureRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConfigureRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeConfigureRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse/title",
          "value": "kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeConnectionParameterUpdateResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeInformationResponse/title",
          "value": "kBluetoothL2CAPCommandCodeInformationResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeInformationResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeInformationResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeInformationRequest/title",
          "value": "kBluetoothL2CAPCommandCodeInformationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeInformationRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeInformationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeCreateChannelRequest/title",
          "value": "kBluetoothL2CAPCommandCodeCreateChannelRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeCreateChannelRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeCreateChannelRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeDisconnectionRequest/title",
          "value": "kBluetoothL2CAPCommandCodeDisconnectionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeDisconnectionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeDisconnectionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest/title",
          "value": "kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeLECreditBasedConnectionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConfigureResponse/title",
          "value": "kBluetoothL2CAPCommandCodeConfigureResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPCommandCodeConfigureResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPCommandCodeConfigureResponse"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothl2capcommandcodeconfigurerequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothl2capcommandcodeconfigurerequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
