{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeTransportDiscoveryData"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@BluetoothHCIExtendedInquiryResponseDataTypes@kBluetoothHCIExtendedInquiryResponseDataTypeTransportDiscoveryData",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothHCIExtendedInquiryResponseDataTypeTransportDiscoveryData"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@BluetoothHCIExtendedInquiryResponseDataTypes",
        "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothHCIExtendedInquiryResponseDataTypeTransportDiscoveryData"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothHCIExtendedInquiryResponseDataTypeTransportDiscoveryData"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothHCIExtendedInquiryResponseDataTypeTransportDiscoveryData"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIExtendedInquiryResponseDataTypes",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@BluetoothHCIExtendedInquiryResponseDataTypes",
              "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIExtendedInquiryResponseDataTypes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIExtendedInquiryResponseDataTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIExtendedInquiryResponseDataTypes",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhciextendedinquiryresponsedatatypes"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsCompleteList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsCompleteList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCIExtendedInquiryResponseDataTypes",
          "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsCompleteList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsCompleteList"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsCompleteList",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhciextendedinquiryresponsedatatype128bitserviceclassuuidscompletelist"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsWithMoreAvailable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsWithMoreAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCIExtendedInquiryResponseDataTypes",
          "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsWithMoreAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsWithMoreAvailable"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsWithMoreAvailable",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhciextendedinquiryresponsedatatype128bitserviceclassuuidswithmoreavailable"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsCompleteList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsCompleteList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCIExtendedInquiryResponseDataTypes",
          "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsCompleteList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsCompleteList"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsCompleteList",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhciextendedinquiryresponsedatatype16bitserviceclassuuidscompletelist"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsWithMoreAvailable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsWithMoreAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCIExtendedInquiryResponseDataTypes",
          "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsWithMoreAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsWithMoreAvailable"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsWithMoreAvailable",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhciextendedinquiryresponsedatatype16bitserviceclassuuidswithmoreavailable"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsCompleteList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsCompleteList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCIExtendedInquiryResponseDataTypes",
          "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsCompleteList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsCompleteList"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsCompleteList",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhciextendedinquiryresponsedatatype32bitserviceclassuuidscompletelist"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsWithMoreAvailable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsWithMoreAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCIExtendedInquiryResponseDataTypes",
          "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsWithMoreAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsWithMoreAvailable"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsWithMoreAvailable",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhciextendedinquiryresponsedatatype32bitserviceclassuuidswithmoreavailable"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeAppearance": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataTypeAppearance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCIExtendedInquiryResponseDataTypes",
          "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataTypeAppearance"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIExtendedInquiryResponseDataTypeAppearance",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhciextendedinquiryresponsedatatypeappearance"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeCompleteLocalName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataTypeCompleteLocalName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCIExtendedInquiryResponseDataTypes",
          "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeCompleteLocalName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataTypeCompleteLocalName"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIExtendedInquiryResponseDataTypeCompleteLocalName",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhciextendedinquiryresponsedatatypecompletelocalname"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeDeviceID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataTypeDeviceID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCIExtendedInquiryResponseDataTypes",
          "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeDeviceID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataTypeDeviceID"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIExtendedInquiryResponseDataTypeDeviceID",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhciextendedinquiryresponsedatatypedeviceid"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeFlags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataTypeFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCIExtendedInquiryResponseDataTypes",
          "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataTypeFlags"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIExtendedInquiryResponseDataTypeFlags",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhciextendedinquiryresponsedatatypeflags"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeManufacturerSpecificData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataTypeManufacturerSpecificData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCIExtendedInquiryResponseDataTypes",
          "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeManufacturerSpecificData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataTypeManufacturerSpecificData"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIExtendedInquiryResponseDataTypeManufacturerSpecificData",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhciextendedinquiryresponsedatatypemanufacturerspecificdata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypePublicTargetAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataTypePublicTargetAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCIExtendedInquiryResponseDataTypes",
          "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypePublicTargetAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataTypePublicTargetAddress"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIExtendedInquiryResponseDataTypePublicTargetAddress",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhciextendedinquiryresponsedatatypepublictargetaddress"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeRandomTargetAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataTypeRandomTargetAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCIExtendedInquiryResponseDataTypes",
          "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeRandomTargetAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataTypeRandomTargetAddress"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIExtendedInquiryResponseDataTypeRandomTargetAddress",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhciextendedinquiryresponsedatatyperandomtargetaddress"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBClassOfDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBClassOfDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCIExtendedInquiryResponseDataTypes",
          "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBClassOfDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBClassOfDevice"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBClassOfDevice",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhciextendedinquiryresponsedatatypesspoobclassofdevice"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBSimplePairingHashC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBSimplePairingHashC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCIExtendedInquiryResponseDataTypes",
          "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBSimplePairingHashC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBSimplePairingHashC"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBSimplePairingHashC",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhciextendedinquiryresponsedatatypesspoobsimplepairinghashc"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeTransportDiscoveryData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataTypeTransportDiscoveryData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCIExtendedInquiryResponseDataTypes",
          "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeTransportDiscoveryData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIExtendedInquiryResponseDataTypeTransportDiscoveryData"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIExtendedInquiryResponseDataTypeTransportDiscoveryData",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhciextendedinquiryresponsedatatypetransportdiscoverydata"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsCompleteList",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsWithMoreAvailable",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsCompleteList",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsWithMoreAvailable",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsCompleteList",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsWithMoreAvailable",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeAppearance",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeCompleteLocalName",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeDeviceID",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeFlags",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeManufacturerSpecificData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypePublicTargetAddress",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeRandomTargetAddress",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBClassOfDevice",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBSimplePairingHashC"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothHCIExtendedInquiryResponseDataTypeTransportDiscoveryData"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIExtendedInquiryResponseDataTypeTransportDiscoveryData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIExtendedInquiryResponseDataTypes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsCompleteList",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsWithMoreAvailable",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsCompleteList",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsWithMoreAvailable",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsCompleteList",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsWithMoreAvailable",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeAppearance",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeCompleteLocalName",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeDeviceID",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeFlags",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeManufacturerSpecificData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypePublicTargetAddress",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeRandomTargetAddress",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBClassOfDevice",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBSimplePairingHashC"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothHCIExtendedInquiryResponseDataTypeTransportDiscoveryData"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsCompleteList/title",
          "value": "kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsCompleteList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsCompleteList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsCompleteList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataTypeManufacturerSpecificData/title",
          "value": "kBluetoothHCIExtendedInquiryResponseDataTypeManufacturerSpecificData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataTypeManufacturerSpecificData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIExtendedInquiryResponseDataTypeManufacturerSpecificData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsWithMoreAvailable/title",
          "value": "kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsWithMoreAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsWithMoreAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsWithMoreAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBSimplePairingHashC/title",
          "value": "kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBSimplePairingHashC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBSimplePairingHashC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBSimplePairingHashC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBClassOfDevice/title",
          "value": "kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBClassOfDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBClassOfDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBClassOfDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataTypeRandomTargetAddress/title",
          "value": "kBluetoothHCIExtendedInquiryResponseDataTypeRandomTargetAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataTypeRandomTargetAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIExtendedInquiryResponseDataTypeRandomTargetAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsWithMoreAvailable/title",
          "value": "kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsWithMoreAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsWithMoreAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsWithMoreAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataTypeTransportDiscoveryData/title",
          "value": "kBluetoothHCIExtendedInquiryResponseDataTypeTransportDiscoveryData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataTypeTransportDiscoveryData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIExtendedInquiryResponseDataTypeTransportDiscoveryData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataTypeDeviceID/title",
          "value": "kBluetoothHCIExtendedInquiryResponseDataTypeDeviceID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataTypeDeviceID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIExtendedInquiryResponseDataTypeDeviceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsCompleteList/title",
          "value": "kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsCompleteList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsCompleteList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsCompleteList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataTypeCompleteLocalName/title",
          "value": "kBluetoothHCIExtendedInquiryResponseDataTypeCompleteLocalName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataTypeCompleteLocalName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIExtendedInquiryResponseDataTypeCompleteLocalName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsCompleteList/title",
          "value": "kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsCompleteList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsCompleteList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsCompleteList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsWithMoreAvailable/title",
          "value": "kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsWithMoreAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsWithMoreAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsWithMoreAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataTypePublicTargetAddress/title",
          "value": "kBluetoothHCIExtendedInquiryResponseDataTypePublicTargetAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataTypePublicTargetAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIExtendedInquiryResponseDataTypePublicTargetAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataTypeAppearance/title",
          "value": "kBluetoothHCIExtendedInquiryResponseDataTypeAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataTypeAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIExtendedInquiryResponseDataTypeAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIExtendedInquiryResponseDataTypes/title",
          "value": "BluetoothHCIExtendedInquiryResponseDataTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIExtendedInquiryResponseDataTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIExtendedInquiryResponseDataTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIExtendedInquiryResponseDataTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataTypeFlags/title",
          "value": "kBluetoothHCIExtendedInquiryResponseDataTypeFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIExtendedInquiryResponseDataTypeFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIExtendedInquiryResponseDataTypeFlags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothhciextendedinquiryresponsedatatypetransportdiscoverydata"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothhciextendedinquiryresponsedatatypetransportdiscoverydata"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
