{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorWearableGlasses"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kBluetoothDeviceClassMinorComputerUnclassified@kBluetoothDeviceClassMinorWearableGlasses",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothDeviceClassMinorWearableGlasses"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothDeviceClassMinorWearableGlasses"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothDeviceClassMinorWearableGlasses"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMinorWearableGlasses"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAny": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAny"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAny",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAny"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMinorAny",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassminorany"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioCamcorder": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioCamcorder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioCamcorder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioCamcorder"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMinorAudioCamcorder",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassminoraudiocamcorder"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioCar": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioCar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioCar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioCar"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMinorAudioCar",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassminoraudiocar"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioGamingToy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioGamingToy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioGamingToy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioGamingToy"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMinorAudioGamingToy",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassminoraudiogamingtoy"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioHandsFree": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioHandsFree"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioHandsFree",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioHandsFree"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMinorAudioHandsFree",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassminoraudiohandsfree"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioHeadphones": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioHeadphones"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioHeadphones",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioHeadphones"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMinorAudioHeadphones",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassminoraudioheadphones"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioHeadset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioHeadset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioHeadset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioHeadset"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMinorAudioHeadset",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassminoraudioheadset"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioHiFi": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioHiFi"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioHiFi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioHiFi"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMinorAudioHiFi",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassminoraudiohifi"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioLoudspeaker": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioLoudspeaker"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioLoudspeaker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioLoudspeaker"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMinorAudioLoudspeaker",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassminoraudioloudspeaker"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioMicrophone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioMicrophone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioMicrophone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioMicrophone"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMinorAudioMicrophone",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassminoraudiomicrophone"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioPortable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioPortable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioPortable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioPortable"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMinorAudioPortable",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassminoraudioportable"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioReserved1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioReserved1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioReserved1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioReserved1"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMinorAudioReserved1",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassminoraudioreserved1"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioReserved2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioReserved2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioReserved2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioReserved2"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMinorAudioReserved2",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassminoraudioreserved2"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioSetTopBox": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioSetTopBox"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioSetTopBox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioSetTopBox"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMinorAudioSetTopBox",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassminoraudiosettopbox"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioUnclassified": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioUnclassified"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioUnclassified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorAudioUnclassified"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMinorAudioUnclassified",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassminoraudiounclassified"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorWearableGlasses": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorWearableGlasses"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorWearableGlasses",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMinorWearableGlasses"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMinorWearableGlasses",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassminorwearableglasses"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAny",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioCamcorder",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioCar",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioGamingToy",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioHandsFree",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioHeadphones",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioHeadset",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioHiFi",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioLoudspeaker",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioMicrophone",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioPortable",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioReserved1",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioReserved2",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioSetTopBox",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioUnclassified"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothDeviceClassMinorWearableGlasses"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMinorWearableGlasses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAny",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioCamcorder",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioCar",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioGamingToy",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioHandsFree",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioHeadphones",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioHeadset",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioHiFi",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioLoudspeaker",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioMicrophone",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioPortable",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioReserved1",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioReserved2",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioSetTopBox",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMinorAudioUnclassified"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothDeviceClassMinorWearableGlasses"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioSetTopBox/title",
          "value": "kBluetoothDeviceClassMinorAudioSetTopBox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioSetTopBox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMinorAudioSetTopBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioGamingToy/title",
          "value": "kBluetoothDeviceClassMinorAudioGamingToy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioGamingToy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMinorAudioGamingToy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioMicrophone/title",
          "value": "kBluetoothDeviceClassMinorAudioMicrophone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioMicrophone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMinorAudioMicrophone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioReserved1/title",
          "value": "kBluetoothDeviceClassMinorAudioReserved1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioReserved1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMinorAudioReserved1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioHandsFree/title",
          "value": "kBluetoothDeviceClassMinorAudioHandsFree"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioHandsFree/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMinorAudioHandsFree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioHeadphones/title",
          "value": "kBluetoothDeviceClassMinorAudioHeadphones"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioHeadphones/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMinorAudioHeadphones"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioHeadset/title",
          "value": "kBluetoothDeviceClassMinorAudioHeadset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioHeadset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMinorAudioHeadset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioHiFi/title",
          "value": "kBluetoothDeviceClassMinorAudioHiFi"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioHiFi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMinorAudioHiFi"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioReserved2/title",
          "value": "kBluetoothDeviceClassMinorAudioReserved2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioReserved2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMinorAudioReserved2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioPortable/title",
          "value": "kBluetoothDeviceClassMinorAudioPortable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioPortable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMinorAudioPortable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAny/title",
          "value": "kBluetoothDeviceClassMinorAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAny/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMinorAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioLoudspeaker/title",
          "value": "kBluetoothDeviceClassMinorAudioLoudspeaker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioLoudspeaker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMinorAudioLoudspeaker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioCamcorder/title",
          "value": "kBluetoothDeviceClassMinorAudioCamcorder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioCamcorder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMinorAudioCamcorder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorWearableGlasses/title",
          "value": "kBluetoothDeviceClassMinorWearableGlasses"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorWearableGlasses/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMinorWearableGlasses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioUnclassified/title",
          "value": "kBluetoothDeviceClassMinorAudioUnclassified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioUnclassified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMinorAudioUnclassified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioCar/title",
          "value": "kBluetoothDeviceClassMinorAudioCar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMinorAudioCar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMinorAudioCar"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothdeviceclassminorwearableglasses"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothdeviceclassminorwearableglasses"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
