{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeSigningInfo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BluetoothLESecurityManagerCommandCode@kBluetoothLESecurityManagerCommandCodeSigningInfo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothLESecurityManagerCommandCodeSigningInfo"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerCommandCode",
        "text": "BluetoothLESecurityManagerCommandCode"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothLESecurityManagerCommandCodeSigningInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothLESecurityManagerCommandCodeSigningInfo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerCommandCodeSigningInfo"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLESecurityManagerCommandCode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerCommandCode",
              "text": "BluetoothLESecurityManagerCommandCode"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLESecurityManagerCommandCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothLESecurityManagerCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLESecurityManagerCommandCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothLESecurityManagerCommandCode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothLESecurityManagerCommandCode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothlesecuritymanagercommandcode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeEncryptionInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodeEncryptionInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerCommandCode",
          "text": "BluetoothLESecurityManagerCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeEncryptionInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodeEncryptionInfo"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerCommandCodeEncryptionInfo",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagercommandcodeencryptioninfo"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeIdentityAddressInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodeIdentityAddressInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerCommandCode",
          "text": "BluetoothLESecurityManagerCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeIdentityAddressInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodeIdentityAddressInfo"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerCommandCodeIdentityAddressInfo",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagercommandcodeidentityaddressinfo"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeIdentityInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodeIdentityInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerCommandCode",
          "text": "BluetoothLESecurityManagerCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeIdentityInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodeIdentityInfo"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerCommandCodeIdentityInfo",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagercommandcodeidentityinfo"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeMasterIdentification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodeMasterIdentification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerCommandCode",
          "text": "BluetoothLESecurityManagerCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeMasterIdentification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodeMasterIdentification"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerCommandCodeMasterIdentification",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagercommandcodemasteridentification"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingConfirm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodePairingConfirm"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerCommandCode",
          "text": "BluetoothLESecurityManagerCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingConfirm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodePairingConfirm"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerCommandCodePairingConfirm",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagercommandcodepairingconfirm"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingDHKeyCheck": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodePairingDHKeyCheck"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerCommandCode",
          "text": "BluetoothLESecurityManagerCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingDHKeyCheck",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodePairingDHKeyCheck"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerCommandCodePairingDHKeyCheck",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagercommandcodepairingdhkeycheck"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodePairingFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerCommandCode",
          "text": "BluetoothLESecurityManagerCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodePairingFailed"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerCommandCodePairingFailed",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagercommandcodepairingfailed"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingKeypressNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodePairingKeypressNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerCommandCode",
          "text": "BluetoothLESecurityManagerCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingKeypressNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodePairingKeypressNotification"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerCommandCodePairingKeypressNotification",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagercommandcodepairingkeypressnotification"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingPublicKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodePairingPublicKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerCommandCode",
          "text": "BluetoothLESecurityManagerCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingPublicKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodePairingPublicKey"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerCommandCodePairingPublicKey",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagercommandcodepairingpublickey"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingRandom": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodePairingRandom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerCommandCode",
          "text": "BluetoothLESecurityManagerCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingRandom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodePairingRandom"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerCommandCodePairingRandom",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagercommandcodepairingrandom"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodePairingRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerCommandCode",
          "text": "BluetoothLESecurityManagerCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodePairingRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerCommandCodePairingRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagercommandcodepairingrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodePairingResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerCommandCode",
          "text": "BluetoothLESecurityManagerCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodePairingResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerCommandCodePairingResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagercommandcodepairingresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeReserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodeReserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerCommandCode",
          "text": "BluetoothLESecurityManagerCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeReserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodeReserved"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerCommandCodeReserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagercommandcodereserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeReservedEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodeReservedEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerCommandCode",
          "text": "BluetoothLESecurityManagerCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeReservedEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodeReservedEnd"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerCommandCodeReservedEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagercommandcodereservedend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeReservedStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodeReservedStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerCommandCode",
          "text": "BluetoothLESecurityManagerCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeReservedStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodeReservedStart"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerCommandCodeReservedStart",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagercommandcodereservedstart"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeSigningInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodeSigningInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerCommandCode",
          "text": "BluetoothLESecurityManagerCommandCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeSigningInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerCommandCodeSigningInfo"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerCommandCodeSigningInfo",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagercommandcodesigninginfo"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeEncryptionInfo",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeIdentityAddressInfo",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeIdentityInfo",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeMasterIdentification",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingConfirm",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingDHKeyCheck",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingFailed",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingKeypressNotification",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingPublicKey",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingRandom",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeReserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeReservedEnd",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeReservedStart"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothLESecurityManagerCommandCodeSigningInfo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerCommandCodeSigningInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLESecurityManagerCommandCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeEncryptionInfo",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeIdentityAddressInfo",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeIdentityInfo",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeMasterIdentification",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingConfirm",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingDHKeyCheck",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingFailed",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingKeypressNotification",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingPublicKey",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingRandom",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodePairingResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeReserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeReservedEnd",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerCommandCodeReservedStart"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothLESecurityManagerCommandCodeSigningInfo"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodeSigningInfo/title",
          "value": "kBluetoothLESecurityManagerCommandCodeSigningInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodeSigningInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerCommandCodeSigningInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodePairingKeypressNotification/title",
          "value": "kBluetoothLESecurityManagerCommandCodePairingKeypressNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodePairingKeypressNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerCommandCodePairingKeypressNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodeReserved/title",
          "value": "kBluetoothLESecurityManagerCommandCodeReserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodeReserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerCommandCodeReserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodeReservedEnd/title",
          "value": "kBluetoothLESecurityManagerCommandCodeReservedEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodeReservedEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerCommandCodeReservedEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodePairingPublicKey/title",
          "value": "kBluetoothLESecurityManagerCommandCodePairingPublicKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodePairingPublicKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerCommandCodePairingPublicKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLESecurityManagerCommandCode/title",
          "value": "BluetoothLESecurityManagerCommandCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLESecurityManagerCommandCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLESecurityManagerCommandCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLESecurityManagerCommandCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLESecurityManagerCommandCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodeReservedStart/title",
          "value": "kBluetoothLESecurityManagerCommandCodeReservedStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodeReservedStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerCommandCodeReservedStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodeIdentityAddressInfo/title",
          "value": "kBluetoothLESecurityManagerCommandCodeIdentityAddressInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodeIdentityAddressInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerCommandCodeIdentityAddressInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodeIdentityInfo/title",
          "value": "kBluetoothLESecurityManagerCommandCodeIdentityInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodeIdentityInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerCommandCodeIdentityInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodePairingResponse/title",
          "value": "kBluetoothLESecurityManagerCommandCodePairingResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodePairingResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerCommandCodePairingResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodePairingRandom/title",
          "value": "kBluetoothLESecurityManagerCommandCodePairingRandom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodePairingRandom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerCommandCodePairingRandom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodePairingDHKeyCheck/title",
          "value": "kBluetoothLESecurityManagerCommandCodePairingDHKeyCheck"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodePairingDHKeyCheck/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerCommandCodePairingDHKeyCheck"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodePairingRequest/title",
          "value": "kBluetoothLESecurityManagerCommandCodePairingRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodePairingRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerCommandCodePairingRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodeMasterIdentification/title",
          "value": "kBluetoothLESecurityManagerCommandCodeMasterIdentification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodeMasterIdentification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerCommandCodeMasterIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodeEncryptionInfo/title",
          "value": "kBluetoothLESecurityManagerCommandCodeEncryptionInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodeEncryptionInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerCommandCodeEncryptionInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodePairingFailed/title",
          "value": "kBluetoothLESecurityManagerCommandCodePairingFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodePairingFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerCommandCodePairingFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodePairingConfirm/title",
          "value": "kBluetoothLESecurityManagerCommandCodePairingConfirm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerCommandCodePairingConfirm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerCommandCodePairingConfirm"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothlesecuritymanagercommandcodesigninginfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothlesecuritymanagercommandcodesigninginfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
