{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierSpecificationID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SDPAttributeDeviceIdentificationRecord@kBluetoothSDPAttributeDeviceIdentifierSpecificationID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothSDPAttributeDeviceIdentifierSpecificationID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SDPAttributeDeviceIdentificationRecord",
        "text": "SDPAttributeDeviceIdentificationRecord"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothSDPAttributeDeviceIdentifierSpecificationID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothSDPAttributeDeviceIdentifierSpecificationID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeDeviceIdentifierSpecificationID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/SDPAttributeDeviceIdentificationRecord",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SDPAttributeDeviceIdentificationRecord",
              "text": "SDPAttributeDeviceIdentificationRecord"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/SDPAttributeDeviceIdentificationRecord": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SDPAttributeDeviceIdentificationRecord"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/SDPAttributeDeviceIdentificationRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SDPAttributeDeviceIdentificationRecord"
        }
      ],
      "role": "symbol",
      "title": "SDPAttributeDeviceIdentificationRecord",
      "type": "topic",
      "url": "/documentation/iobluetooth/sdpattributedeviceidentificationrecord"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierClientExecutableURL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierClientExecutableURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeDeviceIdentificationRecord",
          "text": "SDPAttributeDeviceIdentificationRecord"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierClientExecutableURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierClientExecutableURL"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeDeviceIdentifierClientExecutableURL",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributedeviceidentifierclientexecutableurl"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierDocumentationURL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierDocumentationURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeDeviceIdentificationRecord",
          "text": "SDPAttributeDeviceIdentificationRecord"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierDocumentationURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierDocumentationURL"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeDeviceIdentifierDocumentationURL",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributedeviceidentifierdocumentationurl"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierPrimaryRecord": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierPrimaryRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeDeviceIdentificationRecord",
          "text": "SDPAttributeDeviceIdentificationRecord"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierPrimaryRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierPrimaryRecord"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeDeviceIdentifierPrimaryRecord",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributedeviceidentifierprimaryrecord"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierProductID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierProductID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeDeviceIdentificationRecord",
          "text": "SDPAttributeDeviceIdentificationRecord"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierProductID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierProductID"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeDeviceIdentifierProductID",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributedeviceidentifierproductid"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierReservedRangeEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierReservedRangeEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeDeviceIdentificationRecord",
          "text": "SDPAttributeDeviceIdentificationRecord"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierReservedRangeEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierReservedRangeEnd"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeDeviceIdentifierReservedRangeEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributedeviceidentifierreservedrangeend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierReservedRangeStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierReservedRangeStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeDeviceIdentificationRecord",
          "text": "SDPAttributeDeviceIdentificationRecord"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierReservedRangeStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierReservedRangeStart"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeDeviceIdentifierReservedRangeStart",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributedeviceidentifierreservedrangestart"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierServiceDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierServiceDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeDeviceIdentificationRecord",
          "text": "SDPAttributeDeviceIdentificationRecord"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierServiceDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierServiceDescription"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeDeviceIdentifierServiceDescription",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributedeviceidentifierservicedescription"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierSpecificationID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierSpecificationID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeDeviceIdentificationRecord",
          "text": "SDPAttributeDeviceIdentificationRecord"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierSpecificationID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierSpecificationID"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeDeviceIdentifierSpecificationID",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributedeviceidentifierspecificationid"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierVendorID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierVendorID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeDeviceIdentificationRecord",
          "text": "SDPAttributeDeviceIdentificationRecord"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierVendorID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierVendorID"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeDeviceIdentifierVendorID",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributedeviceidentifiervendorid"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierVendorIDSource": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierVendorIDSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeDeviceIdentificationRecord",
          "text": "SDPAttributeDeviceIdentificationRecord"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierVendorIDSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierVendorIDSource"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeDeviceIdentifierVendorIDSource",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributedeviceidentifiervendoridsource"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierVersion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeDeviceIdentificationRecord",
          "text": "SDPAttributeDeviceIdentificationRecord"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeDeviceIdentifierVersion"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeDeviceIdentifierVersion",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributedeviceidentifierversion"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierClientExecutableURL",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierDocumentationURL",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierPrimaryRecord",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierProductID",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierReservedRangeEnd",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierReservedRangeStart",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierServiceDescription",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierVendorID",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierVendorIDSource",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierVersion"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothSDPAttributeDeviceIdentifierSpecificationID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeDeviceIdentifierSpecificationID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/SDPAttributeDeviceIdentificationRecord"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierClientExecutableURL",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierDocumentationURL",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierPrimaryRecord",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierProductID",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierReservedRangeEnd",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierReservedRangeStart",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierServiceDescription",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierVendorID",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierVendorIDSource",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeDeviceIdentifierVersion"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothSDPAttributeDeviceIdentifierSpecificationID"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierVendorID/title",
          "value": "kBluetoothSDPAttributeDeviceIdentifierVendorID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierVendorID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeDeviceIdentifierVendorID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierVendorIDSource/title",
          "value": "kBluetoothSDPAttributeDeviceIdentifierVendorIDSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierVendorIDSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeDeviceIdentifierVendorIDSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierServiceDescription/title",
          "value": "kBluetoothSDPAttributeDeviceIdentifierServiceDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierServiceDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeDeviceIdentifierServiceDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierPrimaryRecord/title",
          "value": "kBluetoothSDPAttributeDeviceIdentifierPrimaryRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierPrimaryRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeDeviceIdentifierPrimaryRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierClientExecutableURL/title",
          "value": "kBluetoothSDPAttributeDeviceIdentifierClientExecutableURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierClientExecutableURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeDeviceIdentifierClientExecutableURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierReservedRangeStart/title",
          "value": "kBluetoothSDPAttributeDeviceIdentifierReservedRangeStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierReservedRangeStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeDeviceIdentifierReservedRangeStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierProductID/title",
          "value": "kBluetoothSDPAttributeDeviceIdentifierProductID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierProductID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeDeviceIdentifierProductID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierSpecificationID/title",
          "value": "kBluetoothSDPAttributeDeviceIdentifierSpecificationID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierSpecificationID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeDeviceIdentifierSpecificationID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1SDPAttributeDeviceIdentificationRecord/title",
          "value": "SDPAttributeDeviceIdentificationRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1SDPAttributeDeviceIdentificationRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SDPAttributeDeviceIdentificationRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1SDPAttributeDeviceIdentificationRecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SDPAttributeDeviceIdentificationRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierVersion/title",
          "value": "kBluetoothSDPAttributeDeviceIdentifierVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeDeviceIdentifierVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierReservedRangeEnd/title",
          "value": "kBluetoothSDPAttributeDeviceIdentifierReservedRangeEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierReservedRangeEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeDeviceIdentifierReservedRangeEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierDocumentationURL/title",
          "value": "kBluetoothSDPAttributeDeviceIdentifierDocumentationURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeDeviceIdentifierDocumentationURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeDeviceIdentifierDocumentationURL"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothsdpattributedeviceidentifierspecificationid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothsdpattributedeviceidentifierspecificationid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
