{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceSearchAttributeRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kBluetoothSDPPDUIDReserved@kBluetoothSDPPDUIDServiceSearchAttributeRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothSDPPDUIDServiceSearchAttributeRequest"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothSDPPDUIDServiceSearchAttributeRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothSDPPDUIDServiceSearchAttributeRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothSDPPDUIDServiceSearchAttributeRequest"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDErrorResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPPDUIDErrorResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDErrorResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPPDUIDErrorResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPPDUIDErrorResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdppduiderrorresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDReserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPPDUIDReserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDReserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPPDUIDReserved"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPPDUIDReserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdppduidreserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceAttributeRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPPDUIDServiceAttributeRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceAttributeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPPDUIDServiceAttributeRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPPDUIDServiceAttributeRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdppduidserviceattributerequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceAttributeResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPPDUIDServiceAttributeResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceAttributeResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPPDUIDServiceAttributeResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPPDUIDServiceAttributeResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdppduidserviceattributeresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceSearchAttributeRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPPDUIDServiceSearchAttributeRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceSearchAttributeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPPDUIDServiceSearchAttributeRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPPDUIDServiceSearchAttributeRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdppduidservicesearchattributerequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceSearchAttributeResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPPDUIDServiceSearchAttributeResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceSearchAttributeResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPPDUIDServiceSearchAttributeResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPPDUIDServiceSearchAttributeResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdppduidservicesearchattributeresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceSearchRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPPDUIDServiceSearchRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceSearchRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPPDUIDServiceSearchRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPPDUIDServiceSearchRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdppduidservicesearchrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceSearchResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPPDUIDServiceSearchResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceSearchResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPPDUIDServiceSearchResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPPDUIDServiceSearchResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdppduidservicesearchresponse"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDErrorResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDReserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceAttributeRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceAttributeResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceSearchAttributeResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceSearchRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceSearchResponse"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothSDPPDUIDServiceSearchAttributeRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPPDUIDServiceSearchAttributeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDErrorResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDReserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceAttributeRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceAttributeResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceSearchAttributeResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceSearchRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPPDUIDServiceSearchResponse"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothSDPPDUIDServiceSearchAttributeRequest"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPPDUIDServiceSearchAttributeResponse/title",
          "value": "kBluetoothSDPPDUIDServiceSearchAttributeResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPPDUIDServiceSearchAttributeResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPPDUIDServiceSearchAttributeResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPPDUIDServiceSearchAttributeRequest/title",
          "value": "kBluetoothSDPPDUIDServiceSearchAttributeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPPDUIDServiceSearchAttributeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPPDUIDServiceSearchAttributeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPPDUIDServiceAttributeRequest/title",
          "value": "kBluetoothSDPPDUIDServiceAttributeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPPDUIDServiceAttributeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPPDUIDServiceAttributeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPPDUIDErrorResponse/title",
          "value": "kBluetoothSDPPDUIDErrorResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPPDUIDErrorResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPPDUIDErrorResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPPDUIDServiceAttributeResponse/title",
          "value": "kBluetoothSDPPDUIDServiceAttributeResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPPDUIDServiceAttributeResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPPDUIDServiceAttributeResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPPDUIDServiceSearchRequest/title",
          "value": "kBluetoothSDPPDUIDServiceSearchRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPPDUIDServiceSearchRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPPDUIDServiceSearchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPPDUIDServiceSearchResponse/title",
          "value": "kBluetoothSDPPDUIDServiceSearchResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPPDUIDServiceSearchResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPPDUIDServiceSearchResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPPDUIDReserved/title",
          "value": "kBluetoothSDPPDUIDReserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPPDUIDReserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPPDUIDReserved"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothsdppduidservicesearchattributerequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothsdppduidservicesearchattributerequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
