{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterBNEPSupportedNetworkPacketTypeList"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ProtocolParameters@kBluetoothSDPProtocolParameterBNEPSupportedNetworkPacketTypeList",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothSDPProtocolParameterBNEPSupportedNetworkPacketTypeList"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@ProtocolParameters",
        "text": "ProtocolParameters"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothSDPProtocolParameterBNEPSupportedNetworkPacketTypeList"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothSDPProtocolParameterBNEPSupportedNetworkPacketTypeList"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothSDPProtocolParameterBNEPSupportedNetworkPacketTypeList"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/ProtocolParameters",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ProtocolParameters",
              "text": "ProtocolParameters"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/ProtocolParameters": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ProtocolParameters"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/ProtocolParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ProtocolParameters"
        }
      ],
      "role": "symbol",
      "title": "ProtocolParameters",
      "type": "topic",
      "url": "/documentation/iobluetooth/protocolparameters"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterBNEPSupportedNetworkPacketTypeList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPProtocolParameterBNEPSupportedNetworkPacketTypeList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ProtocolParameters",
          "text": "ProtocolParameters"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterBNEPSupportedNetworkPacketTypeList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPProtocolParameterBNEPSupportedNetworkPacketTypeList"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPProtocolParameterBNEPSupportedNetworkPacketTypeList",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpprotocolparameterbnepsupportednetworkpackettypelist"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterBNEPVersion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPProtocolParameterBNEPVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ProtocolParameters",
          "text": "ProtocolParameters"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterBNEPVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPProtocolParameterBNEPVersion"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPProtocolParameterBNEPVersion",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpprotocolparameterbnepversion"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterL2CAPPSM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPProtocolParameterL2CAPPSM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ProtocolParameters",
          "text": "ProtocolParameters"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterL2CAPPSM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPProtocolParameterL2CAPPSM"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPProtocolParameterL2CAPPSM",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpprotocolparameterl2cappsm"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterRFCOMMChannel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPProtocolParameterRFCOMMChannel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ProtocolParameters",
          "text": "ProtocolParameters"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterRFCOMMChannel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPProtocolParameterRFCOMMChannel"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPProtocolParameterRFCOMMChannel",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpprotocolparameterrfcommchannel"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterTCPPort": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPProtocolParameterTCPPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ProtocolParameters",
          "text": "ProtocolParameters"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterTCPPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPProtocolParameterTCPPort"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPProtocolParameterTCPPort",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpprotocolparametertcpport"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterUDPPort": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPProtocolParameterUDPPort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ProtocolParameters",
          "text": "ProtocolParameters"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterUDPPort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPProtocolParameterUDPPort"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPProtocolParameterUDPPort",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpprotocolparameterudpport"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterBNEPVersion",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterL2CAPPSM",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterRFCOMMChannel",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterTCPPort",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterUDPPort"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothSDPProtocolParameterBNEPSupportedNetworkPacketTypeList"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPProtocolParameterBNEPSupportedNetworkPacketTypeList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/ProtocolParameters"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterBNEPVersion",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterL2CAPPSM",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterRFCOMMChannel",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterTCPPort",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPProtocolParameterUDPPort"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothSDPProtocolParameterBNEPSupportedNetworkPacketTypeList"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPProtocolParameterL2CAPPSM/title",
          "value": "kBluetoothSDPProtocolParameterL2CAPPSM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPProtocolParameterL2CAPPSM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPProtocolParameterL2CAPPSM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPProtocolParameterRFCOMMChannel/title",
          "value": "kBluetoothSDPProtocolParameterRFCOMMChannel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPProtocolParameterRFCOMMChannel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPProtocolParameterRFCOMMChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPProtocolParameterBNEPVersion/title",
          "value": "kBluetoothSDPProtocolParameterBNEPVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPProtocolParameterBNEPVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPProtocolParameterBNEPVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPProtocolParameterUDPPort/title",
          "value": "kBluetoothSDPProtocolParameterUDPPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPProtocolParameterUDPPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPProtocolParameterUDPPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1ProtocolParameters/title",
          "value": "ProtocolParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1ProtocolParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ProtocolParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1ProtocolParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ProtocolParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPProtocolParameterTCPPort/title",
          "value": "kBluetoothSDPProtocolParameterTCPPort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPProtocolParameterTCPPort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPProtocolParameterTCPPort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPProtocolParameterBNEPSupportedNetworkPacketTypeList/title",
          "value": "kBluetoothSDPProtocolParameterBNEPSupportedNetworkPacketTypeList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPProtocolParameterBNEPSupportedNetworkPacketTypeList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPProtocolParameterBNEPSupportedNetworkPacketTypeList"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothsdpprotocolparameterbnepsupportednetworkpackettypelist"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothsdpprotocolparameterbnepsupportednetworkpackettypelist"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
