{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierAdditionalProtocolsDescriptorList"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SDPAttributeIdentifierCodes@kBluetoothSDPAttributeIdentifierAdditionalProtocolsDescriptorList",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothSDPAttributeIdentifierAdditionalProtocolsDescriptorList"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SDPAttributeIdentifierCodes",
        "text": "SDPAttributeIdentifierCodes"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothSDPAttributeIdentifierAdditionalProtocolsDescriptorList"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothSDPAttributeIdentifierAdditionalProtocolsDescriptorList"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeIdentifierAdditionalProtocolsDescriptorList"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/SDPAttributeIdentifierCodes",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SDPAttributeIdentifierCodes",
              "text": "SDPAttributeIdentifierCodes"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/SDPAttributeIdentifierCodes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SDPAttributeIdentifierCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/SDPAttributeIdentifierCodes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SDPAttributeIdentifierCodes"
        }
      ],
      "role": "symbol",
      "title": "SDPAttributeIdentifierCodes",
      "type": "topic",
      "url": "/documentation/iobluetooth/sdpattributeidentifiercodes"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierAdditionalProtocolsDescriptorList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierAdditionalProtocolsDescriptorList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeIdentifierCodes",
          "text": "SDPAttributeIdentifierCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierAdditionalProtocolsDescriptorList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierAdditionalProtocolsDescriptorList"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeIdentifierAdditionalProtocolsDescriptorList",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributeidentifieradditionalprotocolsdescriptorlist"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierAudioFeedbackSupport": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierAudioFeedbackSupport"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeIdentifierCodes",
          "text": "SDPAttributeIdentifierCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierAudioFeedbackSupport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierAudioFeedbackSupport"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeIdentifierAudioFeedbackSupport",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributeidentifieraudiofeedbacksupport"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierBluetoothProfileDescriptorList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierBluetoothProfileDescriptorList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeIdentifierCodes",
          "text": "SDPAttributeIdentifierCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierBluetoothProfileDescriptorList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierBluetoothProfileDescriptorList"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeIdentifierBluetoothProfileDescriptorList",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributeidentifierbluetoothprofiledescriptorlist"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierBrowseGroupList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierBrowseGroupList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeIdentifierCodes",
          "text": "SDPAttributeIdentifierCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierBrowseGroupList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierBrowseGroupList"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeIdentifierBrowseGroupList",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributeidentifierbrowsegrouplist"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierClientExecutableURL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierClientExecutableURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeIdentifierCodes",
          "text": "SDPAttributeIdentifierCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierClientExecutableURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierClientExecutableURL"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeIdentifierClientExecutableURL",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributeidentifierclientexecutableurl"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierDocumentationURL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierDocumentationURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeIdentifierCodes",
          "text": "SDPAttributeIdentifierCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierDocumentationURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierDocumentationURL"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeIdentifierDocumentationURL",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributeidentifierdocumentationurl"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierExternalNetwork": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierExternalNetwork"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeIdentifierCodes",
          "text": "SDPAttributeIdentifierCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierExternalNetwork",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierExternalNetwork"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeIdentifierExternalNetwork",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributeidentifierexternalnetwork"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierFaxClass1Support": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierFaxClass1Support"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeIdentifierCodes",
          "text": "SDPAttributeIdentifierCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierFaxClass1Support",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierFaxClass1Support"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeIdentifierFaxClass1Support",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributeidentifierfaxclass1support"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierFaxClass2Support": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierFaxClass2Support"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeIdentifierCodes",
          "text": "SDPAttributeIdentifierCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierFaxClass2Support",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierFaxClass2Support"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeIdentifierFaxClass2Support",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributeidentifierfaxclass2support"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierFaxClass2_0Support": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierFaxClass2_0Support"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeIdentifierCodes",
          "text": "SDPAttributeIdentifierCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierFaxClass2_0Support",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierFaxClass2_0Support"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeIdentifierFaxClass2_0Support",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributeidentifierfaxclass2_0support"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierGroupID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierGroupID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeIdentifierCodes",
          "text": "SDPAttributeIdentifierCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierGroupID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierGroupID"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeIdentifierGroupID",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributeidentifiergroupid"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierHIDBatteryPower": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierHIDBatteryPower"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeIdentifierCodes",
          "text": "SDPAttributeIdentifierCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierHIDBatteryPower",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierHIDBatteryPower"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeIdentifierHIDBatteryPower",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributeidentifierhidbatterypower"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierHIDBootDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierHIDBootDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeIdentifierCodes",
          "text": "SDPAttributeIdentifierCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierHIDBootDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierHIDBootDevice"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeIdentifierHIDBootDevice",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributeidentifierhidbootdevice"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierHIDCountryCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierHIDCountryCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeIdentifierCodes",
          "text": "SDPAttributeIdentifierCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierHIDCountryCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierHIDCountryCode"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeIdentifierHIDCountryCode",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributeidentifierhidcountrycode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierHIDDescriptorList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierHIDDescriptorList"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeIdentifierCodes",
          "text": "SDPAttributeIdentifierCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierHIDDescriptorList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierHIDDescriptorList"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeIdentifierHIDDescriptorList",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributeidentifierhiddescriptorlist"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierHIDDeviceSubclass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierHIDDeviceSubclass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPAttributeIdentifierCodes",
          "text": "SDPAttributeIdentifierCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierHIDDeviceSubclass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPAttributeIdentifierHIDDeviceSubclass"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPAttributeIdentifierHIDDeviceSubclass",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpattributeidentifierhiddevicesubclass"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierAudioFeedbackSupport",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierBluetoothProfileDescriptorList",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierBrowseGroupList",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierClientExecutableURL",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierDocumentationURL",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierExternalNetwork",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierFaxClass1Support",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierFaxClass2Support",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierFaxClass2_0Support",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierGroupID",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierHIDBatteryPower",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierHIDBootDevice",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierHIDCountryCode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierHIDDescriptorList",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierHIDDeviceSubclass"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothSDPAttributeIdentifierAdditionalProtocolsDescriptorList"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeIdentifierAdditionalProtocolsDescriptorList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/SDPAttributeIdentifierCodes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierAudioFeedbackSupport",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierBluetoothProfileDescriptorList",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierBrowseGroupList",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierClientExecutableURL",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierDocumentationURL",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierExternalNetwork",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierFaxClass1Support",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierFaxClass2Support",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierFaxClass2_0Support",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierGroupID",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierHIDBatteryPower",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierHIDBootDevice",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierHIDCountryCode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierHIDDescriptorList",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPAttributeIdentifierHIDDeviceSubclass"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothSDPAttributeIdentifierAdditionalProtocolsDescriptorList"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierBrowseGroupList/title",
          "value": "kBluetoothSDPAttributeIdentifierBrowseGroupList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierBrowseGroupList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeIdentifierBrowseGroupList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierHIDDescriptorList/title",
          "value": "kBluetoothSDPAttributeIdentifierHIDDescriptorList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierHIDDescriptorList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeIdentifierHIDDescriptorList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierFaxClass1Support/title",
          "value": "kBluetoothSDPAttributeIdentifierFaxClass1Support"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierFaxClass1Support/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeIdentifierFaxClass1Support"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierFaxClass2Support/title",
          "value": "kBluetoothSDPAttributeIdentifierFaxClass2Support"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierFaxClass2Support/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeIdentifierFaxClass2Support"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierHIDBootDevice/title",
          "value": "kBluetoothSDPAttributeIdentifierHIDBootDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierHIDBootDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeIdentifierHIDBootDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierGroupID/title",
          "value": "kBluetoothSDPAttributeIdentifierGroupID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierGroupID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeIdentifierGroupID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierClientExecutableURL/title",
          "value": "kBluetoothSDPAttributeIdentifierClientExecutableURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierClientExecutableURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeIdentifierClientExecutableURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierExternalNetwork/title",
          "value": "kBluetoothSDPAttributeIdentifierExternalNetwork"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierExternalNetwork/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeIdentifierExternalNetwork"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierFaxClass2_0Support/title",
          "value": "kBluetoothSDPAttributeIdentifierFaxClass2_0Support"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierFaxClass2_0Support/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeIdentifierFaxClass2_0Support"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierAudioFeedbackSupport/title",
          "value": "kBluetoothSDPAttributeIdentifierAudioFeedbackSupport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierAudioFeedbackSupport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeIdentifierAudioFeedbackSupport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierBluetoothProfileDescriptorList/title",
          "value": "kBluetoothSDPAttributeIdentifierBluetoothProfileDescriptorList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierBluetoothProfileDescriptorList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeIdentifierBluetoothProfileDescriptorList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierHIDBatteryPower/title",
          "value": "kBluetoothSDPAttributeIdentifierHIDBatteryPower"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierHIDBatteryPower/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeIdentifierHIDBatteryPower"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierHIDCountryCode/title",
          "value": "kBluetoothSDPAttributeIdentifierHIDCountryCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierHIDCountryCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeIdentifierHIDCountryCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1SDPAttributeIdentifierCodes/title",
          "value": "SDPAttributeIdentifierCodes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1SDPAttributeIdentifierCodes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SDPAttributeIdentifierCodes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1SDPAttributeIdentifierCodes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SDPAttributeIdentifierCodes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierAdditionalProtocolsDescriptorList/title",
          "value": "kBluetoothSDPAttributeIdentifierAdditionalProtocolsDescriptorList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierAdditionalProtocolsDescriptorList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeIdentifierAdditionalProtocolsDescriptorList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierDocumentationURL/title",
          "value": "kBluetoothSDPAttributeIdentifierDocumentationURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierDocumentationURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeIdentifierDocumentationURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierHIDDeviceSubclass/title",
          "value": "kBluetoothSDPAttributeIdentifierHIDDeviceSubclass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPAttributeIdentifierHIDDeviceSubclass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPAttributeIdentifierHIDDeviceSubclass"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothsdpattributeidentifieradditionalprotocolsdescriptorlist"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothsdpattributeidentifieradditionalprotocolsdescriptorlist"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
