{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMTCS_BIN_Cordless"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kBluetoothL2CAPPSMSDP@kBluetoothL2CAPPSMTCS_BIN_Cordless",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothL2CAPPSMTCS_BIN_Cordless"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothL2CAPPSMTCS_BIN_Cordless"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothL2CAPPSMTCS_BIN_Cordless"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPPSMTCS_BIN_Cordless"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMATT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMATT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMATT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMATT"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPPSMATT",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2cappsmatt"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMAVCTP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMAVCTP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMAVCTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMAVCTP"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPPSMAVCTP",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2cappsmavctp"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMAVCTP_Browsing": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMAVCTP_Browsing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMAVCTP_Browsing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMAVCTP_Browsing"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPPSMAVCTP_Browsing",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2cappsmavctp_browsing"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMAVDTP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMAVDTP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMAVDTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMAVDTP"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPPSMAVDTP",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2cappsmavdtp"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMBNEP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMBNEP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMBNEP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMBNEP"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPPSMBNEP",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2cappsmbnep"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMD2D": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMD2D"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMD2D",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMD2D"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPPSMD2D",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2cappsmd2d"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMDynamicEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMDynamicEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMDynamicEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMDynamicEnd"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPPSMDynamicEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2cappsmdynamicend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMDynamicStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMDynamicStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMDynamicStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMDynamicStart"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPPSMDynamicStart",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2cappsmdynamicstart"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMHIDControl": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMHIDControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMHIDControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMHIDControl"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPPSMHIDControl",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2cappsmhidcontrol"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMHIDInterrupt": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMHIDInterrupt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMHIDInterrupt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMHIDInterrupt"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPPSMHIDInterrupt",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2cappsmhidinterrupt"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMNone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMNone"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPPSMNone",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2cappsmnone"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMRFCOMM": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMRFCOMM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMRFCOMM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMRFCOMM"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPPSMRFCOMM",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2cappsmrfcomm"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMReservedEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMReservedEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMReservedEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMReservedEnd"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPPSMReservedEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2cappsmreservedend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMReservedStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMReservedStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMReservedStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMReservedStart"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPPSMReservedStart",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2cappsmreservedstart"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMSDP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMSDP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMSDP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMSDP"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPPSMSDP",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2cappsmsdp"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMTCS_BIN_Cordless": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMTCS_BIN_Cordless"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMTCS_BIN_Cordless",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPPSMTCS_BIN_Cordless"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPPSMTCS_BIN_Cordless",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2cappsmtcs_bin_cordless"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMATT",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMAVCTP",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMAVCTP_Browsing",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMAVDTP",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMBNEP",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMD2D",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMDynamicEnd",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMDynamicStart",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMHIDControl",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMHIDInterrupt",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMNone",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMRFCOMM",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMReservedEnd",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMReservedStart",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMSDP"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothL2CAPPSMTCS_BIN_Cordless"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPPSMTCS_BIN_Cordless"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMATT",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMAVCTP",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMAVCTP_Browsing",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMAVDTP",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMBNEP",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMD2D",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMDynamicEnd",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMDynamicStart",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMHIDControl",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMHIDInterrupt",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMNone",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMRFCOMM",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMReservedEnd",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMReservedStart",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPPSMSDP"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothL2CAPPSMTCS_BIN_Cordless"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMBNEP/title",
          "value": "kBluetoothL2CAPPSMBNEP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMBNEP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPPSMBNEP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMATT/title",
          "value": "kBluetoothL2CAPPSMATT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMATT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPPSMATT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMAVCTP/title",
          "value": "kBluetoothL2CAPPSMAVCTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMAVCTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPPSMAVCTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMAVCTP_Browsing/title",
          "value": "kBluetoothL2CAPPSMAVCTP_Browsing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMAVCTP_Browsing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPPSMAVCTP_Browsing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMReservedEnd/title",
          "value": "kBluetoothL2CAPPSMReservedEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMReservedEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPPSMReservedEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMReservedStart/title",
          "value": "kBluetoothL2CAPPSMReservedStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMReservedStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPPSMReservedStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMDynamicStart/title",
          "value": "kBluetoothL2CAPPSMDynamicStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMDynamicStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPPSMDynamicStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMNone/title",
          "value": "kBluetoothL2CAPPSMNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPPSMNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMHIDControl/title",
          "value": "kBluetoothL2CAPPSMHIDControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMHIDControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPPSMHIDControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMD2D/title",
          "value": "kBluetoothL2CAPPSMD2D"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMD2D/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPPSMD2D"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMSDP/title",
          "value": "kBluetoothL2CAPPSMSDP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMSDP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPPSMSDP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMHIDInterrupt/title",
          "value": "kBluetoothL2CAPPSMHIDInterrupt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMHIDInterrupt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPPSMHIDInterrupt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMDynamicEnd/title",
          "value": "kBluetoothL2CAPPSMDynamicEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMDynamicEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPPSMDynamicEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMRFCOMM/title",
          "value": "kBluetoothL2CAPPSMRFCOMM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMRFCOMM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPPSMRFCOMM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMAVDTP/title",
          "value": "kBluetoothL2CAPPSMAVDTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMAVDTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPPSMAVDTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMTCS_BIN_Cordless/title",
          "value": "kBluetoothL2CAPPSMTCS_BIN_Cordless"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPPSMTCS_BIN_Cordless/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPPSMTCS_BIN_Cordless"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothl2cappsmtcs_bin_cordless"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothl2cappsmtcs_bin_cordless"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
