{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodePasskeyEntryFailed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BluetoothLESecurityManagerPairingFailedReasonCode@kBluetoothLESecurityManagerReasonCodePasskeyEntryFailed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothLESecurityManagerReasonCodePasskeyEntryFailed"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerPairingFailedReasonCode",
        "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothLESecurityManagerReasonCodePasskeyEntryFailed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothLESecurityManagerReasonCodePasskeyEntryFailed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerReasonCodePasskeyEntryFailed"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLESecurityManagerPairingFailedReasonCode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerPairingFailedReasonCode",
              "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLESecurityManagerPairingFailedReasonCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLESecurityManagerPairingFailedReasonCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothLESecurityManagerPairingFailedReasonCode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothlesecuritymanagerpairingfailedreasoncode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeAuthenticationRequirements": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeAuthenticationRequirements"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerPairingFailedReasonCode",
          "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeAuthenticationRequirements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeAuthenticationRequirements"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerReasonCodeAuthenticationRequirements",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagerreasoncodeauthenticationrequirements"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeBREDRPairingInProgress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeBREDRPairingInProgress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerPairingFailedReasonCode",
          "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeBREDRPairingInProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeBREDRPairingInProgress"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerReasonCodeBREDRPairingInProgress",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagerreasoncodebredrpairinginprogress"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeCommandNotSupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeCommandNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerPairingFailedReasonCode",
          "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeCommandNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeCommandNotSupported"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerReasonCodeCommandNotSupported",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagerreasoncodecommandnotsupported"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeConfirmValueFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeConfirmValueFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerPairingFailedReasonCode",
          "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeConfirmValueFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeConfirmValueFailed"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerReasonCodeConfirmValueFailed",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagerreasoncodeconfirmvaluefailed"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeCrossTransportKeyDerivationGenerationNotAllowed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeCrossTransportKeyDerivationGenerationNotAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerPairingFailedReasonCode",
          "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeCrossTransportKeyDerivationGenerationNotAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeCrossTransportKeyDerivationGenerationNotAllowed"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerReasonCodeCrossTransportKeyDerivationGenerationNotAllowed",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagerreasoncodecrosstransportkeyderivationgenerationnotallowed"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeDHKeyCheckFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeDHKeyCheckFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerPairingFailedReasonCode",
          "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeDHKeyCheckFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeDHKeyCheckFailed"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerReasonCodeDHKeyCheckFailed",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagerreasoncodedhkeycheckfailed"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeEncryptionKeySize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeEncryptionKeySize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerPairingFailedReasonCode",
          "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeEncryptionKeySize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeEncryptionKeySize"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerReasonCodeEncryptionKeySize",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagerreasoncodeencryptionkeysize"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeInvalidParameters": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeInvalidParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerPairingFailedReasonCode",
          "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeInvalidParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeInvalidParameters"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerReasonCodeInvalidParameters",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagerreasoncodeinvalidparameters"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeNumericComparisonFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeNumericComparisonFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerPairingFailedReasonCode",
          "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeNumericComparisonFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeNumericComparisonFailed"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerReasonCodeNumericComparisonFailed",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagerreasoncodenumericcomparisonfailed"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeOOBNotAvailbale": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeOOBNotAvailbale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerPairingFailedReasonCode",
          "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeOOBNotAvailbale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeOOBNotAvailbale"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerReasonCodeOOBNotAvailbale",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagerreasoncodeoobnotavailbale"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodePairingNotSupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodePairingNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerPairingFailedReasonCode",
          "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodePairingNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodePairingNotSupported"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerReasonCodePairingNotSupported",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagerreasoncodepairingnotsupported"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodePasskeyEntryFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodePasskeyEntryFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerPairingFailedReasonCode",
          "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodePasskeyEntryFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodePasskeyEntryFailed"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerReasonCodePasskeyEntryFailed",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagerreasoncodepasskeyentryfailed"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeRepeatedAttempts": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeRepeatedAttempts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerPairingFailedReasonCode",
          "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeRepeatedAttempts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeRepeatedAttempts"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerReasonCodeRepeatedAttempts",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagerreasoncoderepeatedattempts"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeReserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeReserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerPairingFailedReasonCode",
          "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeReserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeReserved"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerReasonCodeReserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagerreasoncodereserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeReservedEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeReservedEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerPairingFailedReasonCode",
          "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeReservedEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeReservedEnd"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerReasonCodeReservedEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagerreasoncodereservedend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeReservedStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeReservedStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothLESecurityManagerPairingFailedReasonCode",
          "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeReservedStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLESecurityManagerReasonCodeReservedStart"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLESecurityManagerReasonCodeReservedStart",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlesecuritymanagerreasoncodereservedstart"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeAuthenticationRequirements",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeBREDRPairingInProgress",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeCommandNotSupported",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeConfirmValueFailed",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeCrossTransportKeyDerivationGenerationNotAllowed",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeDHKeyCheckFailed",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeEncryptionKeySize",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeInvalidParameters",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeNumericComparisonFailed",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeOOBNotAvailbale",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodePairingNotSupported",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeRepeatedAttempts",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeReserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeReservedEnd",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeReservedStart"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothLESecurityManagerReasonCodePasskeyEntryFailed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerReasonCodePasskeyEntryFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLESecurityManagerPairingFailedReasonCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeAuthenticationRequirements",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeBREDRPairingInProgress",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeCommandNotSupported",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeConfirmValueFailed",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeCrossTransportKeyDerivationGenerationNotAllowed",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeDHKeyCheckFailed",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeEncryptionKeySize",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeInvalidParameters",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeNumericComparisonFailed",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeOOBNotAvailbale",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodePairingNotSupported",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeRepeatedAttempts",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeReserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeReservedEnd",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLESecurityManagerReasonCodeReservedStart"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothLESecurityManagerReasonCodePasskeyEntryFailed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeConfirmValueFailed/title",
          "value": "kBluetoothLESecurityManagerReasonCodeConfirmValueFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeConfirmValueFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerReasonCodeConfirmValueFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeRepeatedAttempts/title",
          "value": "kBluetoothLESecurityManagerReasonCodeRepeatedAttempts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeRepeatedAttempts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerReasonCodeRepeatedAttempts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeCommandNotSupported/title",
          "value": "kBluetoothLESecurityManagerReasonCodeCommandNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeCommandNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerReasonCodeCommandNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeReservedEnd/title",
          "value": "kBluetoothLESecurityManagerReasonCodeReservedEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeReservedEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerReasonCodeReservedEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeReservedStart/title",
          "value": "kBluetoothLESecurityManagerReasonCodeReservedStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeReservedStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerReasonCodeReservedStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeReserved/title",
          "value": "kBluetoothLESecurityManagerReasonCodeReserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeReserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerReasonCodeReserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeCrossTransportKeyDerivationGenerationNotAllowed/title",
          "value": "kBluetoothLESecurityManagerReasonCodeCrossTransportKeyDerivationGenerationNotAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeCrossTransportKeyDerivationGenerationNotAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerReasonCodeCrossTransportKeyDerivationGenerationNotAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLESecurityManagerPairingFailedReasonCode/title",
          "value": "BluetoothLESecurityManagerPairingFailedReasonCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLESecurityManagerPairingFailedReasonCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLESecurityManagerPairingFailedReasonCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLESecurityManagerPairingFailedReasonCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeInvalidParameters/title",
          "value": "kBluetoothLESecurityManagerReasonCodeInvalidParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeInvalidParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerReasonCodeInvalidParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeEncryptionKeySize/title",
          "value": "kBluetoothLESecurityManagerReasonCodeEncryptionKeySize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeEncryptionKeySize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerReasonCodeEncryptionKeySize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodePairingNotSupported/title",
          "value": "kBluetoothLESecurityManagerReasonCodePairingNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodePairingNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerReasonCodePairingNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeAuthenticationRequirements/title",
          "value": "kBluetoothLESecurityManagerReasonCodeAuthenticationRequirements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeAuthenticationRequirements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerReasonCodeAuthenticationRequirements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeDHKeyCheckFailed/title",
          "value": "kBluetoothLESecurityManagerReasonCodeDHKeyCheckFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeDHKeyCheckFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerReasonCodeDHKeyCheckFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeBREDRPairingInProgress/title",
          "value": "kBluetoothLESecurityManagerReasonCodeBREDRPairingInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeBREDRPairingInProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerReasonCodeBREDRPairingInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodePasskeyEntryFailed/title",
          "value": "kBluetoothLESecurityManagerReasonCodePasskeyEntryFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodePasskeyEntryFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerReasonCodePasskeyEntryFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeOOBNotAvailbale/title",
          "value": "kBluetoothLESecurityManagerReasonCodeOOBNotAvailbale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeOOBNotAvailbale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerReasonCodeOOBNotAvailbale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeNumericComparisonFailed/title",
          "value": "kBluetoothLESecurityManagerReasonCodeNumericComparisonFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLESecurityManagerReasonCodeNumericComparisonFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLESecurityManagerReasonCodeNumericComparisonFailed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothlesecuritymanagerreasoncodepasskeyentryfailed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothlesecuritymanagerreasoncodepasskeyentryfailed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
