{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskReadRemoteVersionInformationComplete"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kBluetoothHCIEventMaskNone@kBluetoothHCIEventMaskReadRemoteVersionInformationComplete",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothHCIEventMaskReadRemoteVersionInformationComplete"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothHCIEventMaskReadRemoteVersionInformationComplete"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothHCIEventMaskReadRemoteVersionInformationComplete"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventMaskReadRemoteVersionInformationComplete"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskAll": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskAll"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskAll",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskAll"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventMaskAll",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventmaskall"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskAuthenticationComplete": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskAuthenticationComplete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskAuthenticationComplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskAuthenticationComplete"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventMaskAuthenticationComplete",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventmaskauthenticationcomplete"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskChangeConnectionLinkKeyComplete": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskChangeConnectionLinkKeyComplete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskChangeConnectionLinkKeyComplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskChangeConnectionLinkKeyComplete"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventMaskChangeConnectionLinkKeyComplete",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventmaskchangeconnectionlinkkeycomplete"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskCommandComplete": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskCommandComplete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskCommandComplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskCommandComplete"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventMaskCommandComplete",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventmaskcommandcomplete"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskCommandStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskCommandStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskCommandStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskCommandStatus"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventMaskCommandStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventmaskcommandstatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskConnectionComplete": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskConnectionComplete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskConnectionComplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskConnectionComplete"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventMaskConnectionComplete",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventmaskconnectioncomplete"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskConnectionPacketTypeChanged": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskConnectionPacketTypeChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskConnectionPacketTypeChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskConnectionPacketTypeChanged"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventMaskConnectionPacketTypeChanged",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventmaskconnectionpackettypechanged"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskConnectionRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskConnectionRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskConnectionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskConnectionRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventMaskConnectionRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventmaskconnectionrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskDataBufferOverflow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskDataBufferOverflow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskDataBufferOverflow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskDataBufferOverflow"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventMaskDataBufferOverflow",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventmaskdatabufferoverflow"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskDefault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskDefault"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventMaskDefault",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventmaskdefault"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskDisconnectionComplete": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskDisconnectionComplete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskDisconnectionComplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskDisconnectionComplete"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventMaskDisconnectionComplete",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventmaskdisconnectioncomplete"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskEncryptionChange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskEncryptionChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskEncryptionChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskEncryptionChange"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventMaskEncryptionChange",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventmaskencryptionchange"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskFlushOccurred": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskFlushOccurred"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskFlushOccurred",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskFlushOccurred"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventMaskFlushOccurred",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventmaskflushoccurred"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskHardwareError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskHardwareError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskHardwareError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskHardwareError"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventMaskHardwareError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventmaskhardwareerror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskInquiryComplete": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskInquiryComplete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskInquiryComplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskInquiryComplete"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventMaskInquiryComplete",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventmaskinquirycomplete"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskReadRemoteVersionInformationComplete": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskReadRemoteVersionInformationComplete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskReadRemoteVersionInformationComplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventMaskReadRemoteVersionInformationComplete"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventMaskReadRemoteVersionInformationComplete",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventmaskreadremoteversioninformationcomplete"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskAll",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskAuthenticationComplete",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskChangeConnectionLinkKeyComplete",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskCommandComplete",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskCommandStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskConnectionComplete",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskConnectionPacketTypeChanged",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskConnectionRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskDataBufferOverflow",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskDefault",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskDisconnectionComplete",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskEncryptionChange",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskFlushOccurred",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskHardwareError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskInquiryComplete"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothHCIEventMaskReadRemoteVersionInformationComplete"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventMaskReadRemoteVersionInformationComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskAll",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskAuthenticationComplete",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskChangeConnectionLinkKeyComplete",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskCommandComplete",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskCommandStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskConnectionComplete",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskConnectionPacketTypeChanged",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskConnectionRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskDataBufferOverflow",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskDefault",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskDisconnectionComplete",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskEncryptionChange",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskFlushOccurred",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskHardwareError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventMaskInquiryComplete"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothHCIEventMaskReadRemoteVersionInformationComplete"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskHardwareError/title",
          "value": "kBluetoothHCIEventMaskHardwareError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskHardwareError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventMaskHardwareError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskEncryptionChange/title",
          "value": "kBluetoothHCIEventMaskEncryptionChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskEncryptionChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventMaskEncryptionChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskChangeConnectionLinkKeyComplete/title",
          "value": "kBluetoothHCIEventMaskChangeConnectionLinkKeyComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskChangeConnectionLinkKeyComplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventMaskChangeConnectionLinkKeyComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskCommandComplete/title",
          "value": "kBluetoothHCIEventMaskCommandComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskCommandComplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventMaskCommandComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskDataBufferOverflow/title",
          "value": "kBluetoothHCIEventMaskDataBufferOverflow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskDataBufferOverflow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventMaskDataBufferOverflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskConnectionPacketTypeChanged/title",
          "value": "kBluetoothHCIEventMaskConnectionPacketTypeChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskConnectionPacketTypeChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventMaskConnectionPacketTypeChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskAuthenticationComplete/title",
          "value": "kBluetoothHCIEventMaskAuthenticationComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskAuthenticationComplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventMaskAuthenticationComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskFlushOccurred/title",
          "value": "kBluetoothHCIEventMaskFlushOccurred"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskFlushOccurred/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventMaskFlushOccurred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskConnectionRequest/title",
          "value": "kBluetoothHCIEventMaskConnectionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskConnectionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventMaskConnectionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskConnectionComplete/title",
          "value": "kBluetoothHCIEventMaskConnectionComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskConnectionComplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventMaskConnectionComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskReadRemoteVersionInformationComplete/title",
          "value": "kBluetoothHCIEventMaskReadRemoteVersionInformationComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskReadRemoteVersionInformationComplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventMaskReadRemoteVersionInformationComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskAll/title",
          "value": "kBluetoothHCIEventMaskAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskAll/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventMaskAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskDisconnectionComplete/title",
          "value": "kBluetoothHCIEventMaskDisconnectionComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskDisconnectionComplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventMaskDisconnectionComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskCommandStatus/title",
          "value": "kBluetoothHCIEventMaskCommandStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskCommandStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventMaskCommandStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskDefault/title",
          "value": "kBluetoothHCIEventMaskDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventMaskDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskInquiryComplete/title",
          "value": "kBluetoothHCIEventMaskInquiryComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventMaskInquiryComplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventMaskInquiryComplete"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothhcieventmaskreadremoteversioninformationcomplete"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothhcieventmaskreadremoteversioninformationcomplete"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
