{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorLMPErrorTransactionCollision"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kBluetoothHCIErrorSuccess@kBluetoothHCIErrorLMPErrorTransactionCollision",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothHCIErrorLMPErrorTransactionCollision"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothHCIErrorLMPErrorTransactionCollision"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothHCIErrorLMPErrorTransactionCollision"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothHCIErrorLMPErrorTransactionCollision"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorACLConnectionAlreadyExists": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorACLConnectionAlreadyExists"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorACLConnectionAlreadyExists",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorACLConnectionAlreadyExists"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIErrorACLConnectionAlreadyExists",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcierroraclconnectionalreadyexists"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorAuthenticationFailure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorAuthenticationFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorAuthenticationFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorAuthenticationFailure"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIErrorAuthenticationFailure",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcierrorauthenticationfailure"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorChannelClassificationNotSupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorChannelClassificationNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorChannelClassificationNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorChannelClassificationNotSupported"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIErrorChannelClassificationNotSupported",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcierrorchannelclassificationnotsupported"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorCommandDisallowed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorCommandDisallowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorCommandDisallowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorCommandDisallowed"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIErrorCommandDisallowed",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcierrorcommanddisallowed"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorConnectionFailedToBeEstablished": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorConnectionFailedToBeEstablished"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorConnectionFailedToBeEstablished",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorConnectionFailedToBeEstablished"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIErrorConnectionFailedToBeEstablished",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcierrorconnectionfailedtobeestablished"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorConnectionRejectedDueToNoSuitableChannelFound": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorConnectionRejectedDueToNoSuitableChannelFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorConnectionRejectedDueToNoSuitableChannelFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorConnectionRejectedDueToNoSuitableChannelFound"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIErrorConnectionRejectedDueToNoSuitableChannelFound",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcierrorconnectionrejectedduetonosuitablechannelfound"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorConnectionTerminatedByLocalHost": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorConnectionTerminatedByLocalHost"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorConnectionTerminatedByLocalHost",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorConnectionTerminatedByLocalHost"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIErrorConnectionTerminatedByLocalHost",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcierrorconnectionterminatedbylocalhost"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorConnectionTerminatedDueToMICFailure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorConnectionTerminatedDueToMICFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorConnectionTerminatedDueToMICFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorConnectionTerminatedDueToMICFailure"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIErrorConnectionTerminatedDueToMICFailure",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcierrorconnectionterminatedduetomicfailure"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorConnectionTimeout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorConnectionTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorConnectionTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorConnectionTimeout"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIErrorConnectionTimeout",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcierrorconnectiontimeout"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorControllerBusy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorControllerBusy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorControllerBusy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorControllerBusy"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIErrorControllerBusy",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcierrorcontrollerbusy"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorDifferentTransactionCollision": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorDifferentTransactionCollision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorDifferentTransactionCollision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorDifferentTransactionCollision"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIErrorDifferentTransactionCollision",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcierrordifferenttransactioncollision"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorDirectedAdvertisingTimeout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorDirectedAdvertisingTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorDirectedAdvertisingTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorDirectedAdvertisingTimeout"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIErrorDirectedAdvertisingTimeout",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcierrordirectedadvertisingtimeout"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorEncryptionModeNotAcceptable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorEncryptionModeNotAcceptable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorEncryptionModeNotAcceptable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorEncryptionModeNotAcceptable"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIErrorEncryptionModeNotAcceptable",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcierrorencryptionmodenotacceptable"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorExtendedInquiryResponseTooLarge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorExtendedInquiryResponseTooLarge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorExtendedInquiryResponseTooLarge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorExtendedInquiryResponseTooLarge"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIErrorExtendedInquiryResponseTooLarge",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcierrorextendedinquiryresponsetoolarge"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorHardwareFailure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorHardwareFailure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorHardwareFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorHardwareFailure"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIErrorHardwareFailure",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcierrorhardwarefailure"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorLMPErrorTransactionCollision": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorLMPErrorTransactionCollision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorLMPErrorTransactionCollision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIErrorLMPErrorTransactionCollision"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIErrorLMPErrorTransactionCollision",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcierrorlmperrortransactioncollision"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorACLConnectionAlreadyExists",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorAuthenticationFailure",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorChannelClassificationNotSupported",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorCommandDisallowed",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorConnectionFailedToBeEstablished",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorConnectionRejectedDueToNoSuitableChannelFound",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorConnectionTerminatedByLocalHost",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorConnectionTerminatedDueToMICFailure",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorConnectionTimeout",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorControllerBusy",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorDifferentTransactionCollision",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorDirectedAdvertisingTimeout",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorEncryptionModeNotAcceptable",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorExtendedInquiryResponseTooLarge",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorHardwareFailure"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothHCIErrorLMPErrorTransactionCollision"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIErrorLMPErrorTransactionCollision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorACLConnectionAlreadyExists",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorAuthenticationFailure",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorChannelClassificationNotSupported",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorCommandDisallowed",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorConnectionFailedToBeEstablished",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorConnectionRejectedDueToNoSuitableChannelFound",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorConnectionTerminatedByLocalHost",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorConnectionTerminatedDueToMICFailure",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorConnectionTimeout",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorControllerBusy",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorDifferentTransactionCollision",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorDirectedAdvertisingTimeout",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorEncryptionModeNotAcceptable",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorExtendedInquiryResponseTooLarge",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIErrorHardwareFailure"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothHCIErrorLMPErrorTransactionCollision"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorAuthenticationFailure/title",
          "value": "kBluetoothHCIErrorAuthenticationFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorAuthenticationFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIErrorAuthenticationFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorConnectionRejectedDueToNoSuitableChannelFound/title",
          "value": "kBluetoothHCIErrorConnectionRejectedDueToNoSuitableChannelFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorConnectionRejectedDueToNoSuitableChannelFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIErrorConnectionRejectedDueToNoSuitableChannelFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorACLConnectionAlreadyExists/title",
          "value": "kBluetoothHCIErrorACLConnectionAlreadyExists"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorACLConnectionAlreadyExists/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIErrorACLConnectionAlreadyExists"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorChannelClassificationNotSupported/title",
          "value": "kBluetoothHCIErrorChannelClassificationNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorChannelClassificationNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIErrorChannelClassificationNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorLMPErrorTransactionCollision/title",
          "value": "kBluetoothHCIErrorLMPErrorTransactionCollision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorLMPErrorTransactionCollision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIErrorLMPErrorTransactionCollision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorDirectedAdvertisingTimeout/title",
          "value": "kBluetoothHCIErrorDirectedAdvertisingTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorDirectedAdvertisingTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIErrorDirectedAdvertisingTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorDifferentTransactionCollision/title",
          "value": "kBluetoothHCIErrorDifferentTransactionCollision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorDifferentTransactionCollision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIErrorDifferentTransactionCollision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorConnectionTerminatedByLocalHost/title",
          "value": "kBluetoothHCIErrorConnectionTerminatedByLocalHost"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorConnectionTerminatedByLocalHost/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIErrorConnectionTerminatedByLocalHost"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorConnectionTimeout/title",
          "value": "kBluetoothHCIErrorConnectionTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorConnectionTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIErrorConnectionTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorCommandDisallowed/title",
          "value": "kBluetoothHCIErrorCommandDisallowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorCommandDisallowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIErrorCommandDisallowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorControllerBusy/title",
          "value": "kBluetoothHCIErrorControllerBusy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorControllerBusy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIErrorControllerBusy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorEncryptionModeNotAcceptable/title",
          "value": "kBluetoothHCIErrorEncryptionModeNotAcceptable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorEncryptionModeNotAcceptable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIErrorEncryptionModeNotAcceptable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorExtendedInquiryResponseTooLarge/title",
          "value": "kBluetoothHCIErrorExtendedInquiryResponseTooLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorExtendedInquiryResponseTooLarge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIErrorExtendedInquiryResponseTooLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorConnectionTerminatedDueToMICFailure/title",
          "value": "kBluetoothHCIErrorConnectionTerminatedDueToMICFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorConnectionTerminatedDueToMICFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIErrorConnectionTerminatedDueToMICFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorConnectionFailedToBeEstablished/title",
          "value": "kBluetoothHCIErrorConnectionFailedToBeEstablished"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorConnectionFailedToBeEstablished/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIErrorConnectionFailedToBeEstablished"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorHardwareFailure/title",
          "value": "kBluetoothHCIErrorHardwareFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIErrorHardwareFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIErrorHardwareFailure"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothhcierrorlmperrortransactioncollision"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothhcierrorlmperrortransactioncollision"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
