{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionQoSLength"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kBluetoothL2CAPConfigurationOptionMTULength@kBluetoothL2CAPConfigurationOptionQoSLength",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothL2CAPConfigurationOptionQoSLength"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothL2CAPConfigurationOptionQoSLength"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothL2CAPConfigurationOptionQoSLength"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConfigurationOptionQoSLength"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionFlushTimeoutLength": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionFlushTimeoutLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionFlushTimeoutLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionFlushTimeoutLength"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPConfigurationOptionFlushTimeoutLength",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capconfigurationoptionflushtimeoutlength"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionMTULength": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionMTULength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionMTULength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionMTULength"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPConfigurationOptionMTULength",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capconfigurationoptionmtulength"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionQoSLength": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionQoSLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionQoSLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionQoSLength"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPConfigurationOptionQoSLength",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capconfigurationoptionqoslength"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControlLength": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControlLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControlLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControlLength"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControlLength",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capconfigurationoptionretransmissionandflowcontrollength"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionFlushTimeoutLength",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionMTULength",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControlLength"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothL2CAPConfigurationOptionQoSLength"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConfigurationOptionQoSLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionFlushTimeoutLength",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionMTULength",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControlLength"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothL2CAPConfigurationOptionQoSLength"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControlLength/title",
          "value": "kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControlLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControlLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControlLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionQoSLength/title",
          "value": "kBluetoothL2CAPConfigurationOptionQoSLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionQoSLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConfigurationOptionQoSLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionFlushTimeoutLength/title",
          "value": "kBluetoothL2CAPConfigurationOptionFlushTimeoutLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionFlushTimeoutLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConfigurationOptionFlushTimeoutLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionMTULength/title",
          "value": "kBluetoothL2CAPConfigurationOptionMTULength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionMTULength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConfigurationOptionMTULength"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothl2capconfigurationoptionqoslength"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothl2capconfigurationoptionqoslength"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
