{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConnectReq"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kBluetoothL2CAPTCICommandReserved@kBluetoothL2CAPTCICommandL2CA_ConnectReq",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothL2CAPTCICommandL2CA_ConnectReq"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothL2CAPTCICommandL2CA_ConnectReq"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothL2CAPTCICommandL2CA_ConnectReq"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_ConnectReq"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConfigReq": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_ConfigReq"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConfigReq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_ConfigReq"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_ConfigReq",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_configreq"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConfigResp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_ConfigResp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConfigResp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_ConfigResp"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_ConfigResp",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_configresp"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConnectReq": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_ConnectReq"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConnectReq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_ConnectReq"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_ConnectReq",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_connectreq"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConnectResp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_ConnectResp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConnectResp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_ConnectResp"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_ConnectResp",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_connectresp"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisableCLT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_DisableCLT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisableCLT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_DisableCLT"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_DisableCLT",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_disableclt"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisconnectReq": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_DisconnectReq"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisconnectReq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_DisconnectReq"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_DisconnectReq",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_disconnectreq"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisconnectResp": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_DisconnectResp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisconnectResp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_DisconnectResp"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_DisconnectResp",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_disconnectresp"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_EnableCLT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_EnableCLT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_EnableCLT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_EnableCLT"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_EnableCLT",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_enableclt"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GetInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GetInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GetInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GetInfo"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_GetInfo",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_getinfo"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupAddMember": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GroupAddMember"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupAddMember",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GroupAddMember"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_GroupAddMember",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_groupaddmember"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupClose": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GroupClose"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupClose",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GroupClose"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_GroupClose",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_groupclose"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupCreate": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GroupCreate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupCreate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GroupCreate"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_GroupCreate",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_groupcreate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupMembership": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GroupMembership"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupMembership",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GroupMembership"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_GroupMembership",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_groupmembership"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_groupremovemember"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_Ping": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_Ping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_Ping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_Ping"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_Ping",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_ping"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ReadData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_ReadData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ReadData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPTCICommandL2CA_ReadData"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPTCICommandL2CA_ReadData",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_readdata"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConfigReq",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConfigResp",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConnectResp",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisableCLT",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisconnectReq",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisconnectResp",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_EnableCLT",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GetInfo",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupAddMember",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupClose",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupCreate",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupMembership",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_Ping",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ReadData"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_ConnectReq"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_ConnectReq"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConfigReq",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConfigResp",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ConnectResp",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisableCLT",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisconnectReq",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_DisconnectResp",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_EnableCLT",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GetInfo",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupAddMember",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupClose",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupCreate",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupMembership",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_Ping",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPTCICommandL2CA_ReadData"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothL2CAPTCICommandL2CA_ConnectReq"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GroupCreate/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_GroupCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GroupCreate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_GroupCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_GroupRemoveMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_DisconnectResp/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_DisconnectResp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_DisconnectResp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_DisconnectResp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_Ping/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_Ping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_Ping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_Ping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_ConfigResp/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_ConfigResp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_ConfigResp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_ConfigResp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GroupAddMember/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_GroupAddMember"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GroupAddMember/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_GroupAddMember"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GetInfo/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_GetInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GetInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_GetInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GroupClose/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_GroupClose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GroupClose/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_GroupClose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_ConnectResp/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_ConnectResp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_ConnectResp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_ConnectResp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GroupMembership/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_GroupMembership"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_GroupMembership/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_GroupMembership"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_ConnectReq/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_ConnectReq"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_ConnectReq/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_ConnectReq"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_ConfigReq/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_ConfigReq"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_ConfigReq/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_ConfigReq"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_DisableCLT/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_DisableCLT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_DisableCLT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_DisableCLT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_ReadData/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_ReadData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_ReadData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_ReadData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_DisconnectReq/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_DisconnectReq"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_DisconnectReq/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_DisconnectReq"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_EnableCLT/title",
          "value": "kBluetoothL2CAPTCICommandL2CA_EnableCLT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPTCICommandL2CA_EnableCLT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPTCICommandL2CA_EnableCLT"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_connectreq"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothl2captcicommandl2ca_connectreq"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
