{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedSecurityBlock"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BluetoothL2CAPConnectionResult@kBluetoothL2CAPConnectionResultRefusedSecurityBlock",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothL2CAPConnectionResultRefusedSecurityBlock"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@BluetoothL2CAPConnectionResult",
        "text": "BluetoothL2CAPConnectionResult"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothL2CAPConnectionResultRefusedSecurityBlock"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothL2CAPConnectionResultRefusedSecurityBlock"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConnectionResultRefusedSecurityBlock"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@BluetoothL2CAPConnectionResult",
              "text": "BluetoothL2CAPConnectionResult"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConnectionResult",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconnectionresult"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultPending": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConnectionResultPending"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPConnectionResult",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultPending",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConnectionResultPending"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPConnectionResultPending",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capconnectionresultpending"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedInvalidSourceCID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConnectionResultRefusedInvalidSourceCID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPConnectionResult",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedInvalidSourceCID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConnectionResultRefusedInvalidSourceCID"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPConnectionResultRefusedInvalidSourceCID",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capconnectionresultrefusedinvalidsourcecid"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedNoResources": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConnectionResultRefusedNoResources"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPConnectionResult",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedNoResources",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConnectionResultRefusedNoResources"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPConnectionResultRefusedNoResources",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capconnectionresultrefusednoresources"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedPSMNotSupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConnectionResultRefusedPSMNotSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPConnectionResult",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedPSMNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConnectionResultRefusedPSMNotSupported"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPConnectionResultRefusedPSMNotSupported",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capconnectionresultrefusedpsmnotsupported"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedReserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConnectionResultRefusedReserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPConnectionResult",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedReserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConnectionResultRefusedReserved"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPConnectionResultRefusedReserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capconnectionresultrefusedreserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedSecurityBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConnectionResultRefusedSecurityBlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPConnectionResult",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedSecurityBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConnectionResultRefusedSecurityBlock"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPConnectionResultRefusedSecurityBlock",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capconnectionresultrefusedsecurityblock"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedSourceCIDAlreadyAllocated": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConnectionResultRefusedSourceCIDAlreadyAllocated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPConnectionResult",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedSourceCIDAlreadyAllocated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConnectionResultRefusedSourceCIDAlreadyAllocated"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPConnectionResultRefusedSourceCIDAlreadyAllocated",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capconnectionresultrefusedsourcecidalreadyallocated"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultSuccessful": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConnectionResultSuccessful"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPConnectionResult",
          "text": "BluetoothL2CAPConnectionResult"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultSuccessful",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConnectionResultSuccessful"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPConnectionResultSuccessful",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capconnectionresultsuccessful"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultPending",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedNoResources",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedPSMNotSupported",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultSuccessful",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedInvalidSourceCID",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedReserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedSourceCIDAlreadyAllocated"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothL2CAPConnectionResultRefusedSecurityBlock"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConnectionResultRefusedSecurityBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConnectionResult"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultPending",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedNoResources",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedPSMNotSupported",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultSuccessful",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedInvalidSourceCID",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedReserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConnectionResultRefusedSourceCIDAlreadyAllocated"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothL2CAPConnectionResultRefusedSecurityBlock"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConnectionResultRefusedSourceCIDAlreadyAllocated/title",
          "value": "kBluetoothL2CAPConnectionResultRefusedSourceCIDAlreadyAllocated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConnectionResultRefusedSourceCIDAlreadyAllocated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConnectionResultRefusedSourceCIDAlreadyAllocated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConnectionResultSuccessful/title",
          "value": "kBluetoothL2CAPConnectionResultSuccessful"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConnectionResultSuccessful/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConnectionResultSuccessful"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConnectionResultRefusedPSMNotSupported/title",
          "value": "kBluetoothL2CAPConnectionResultRefusedPSMNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConnectionResultRefusedPSMNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConnectionResultRefusedPSMNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConnectionResultPending/title",
          "value": "kBluetoothL2CAPConnectionResultPending"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConnectionResultPending/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConnectionResultPending"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConnectionResultRefusedNoResources/title",
          "value": "kBluetoothL2CAPConnectionResultRefusedNoResources"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConnectionResultRefusedNoResources/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConnectionResultRefusedNoResources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConnectionResultRefusedReserved/title",
          "value": "kBluetoothL2CAPConnectionResultRefusedReserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConnectionResultRefusedReserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConnectionResultRefusedReserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionResult/title",
          "value": "BluetoothL2CAPConnectionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConnectionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConnectionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConnectionResultRefusedSecurityBlock/title",
          "value": "kBluetoothL2CAPConnectionResultRefusedSecurityBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConnectionResultRefusedSecurityBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConnectionResultRefusedSecurityBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConnectionResultRefusedInvalidSourceCID/title",
          "value": "kBluetoothL2CAPConnectionResultRefusedInvalidSourceCID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConnectionResultRefusedInvalidSourceCID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConnectionResultRefusedInvalidSourceCID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothl2capconnectionresultrefusedsecurityblock"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothl2capconnectionresultrefusedsecurityblock"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
