{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventAMPTestEnd"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kBluetoothHCIEventInquiryComplete@kBluetoothHCIEventAMPTestEnd",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothHCIEventAMPTestEnd"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothHCIEventAMPTestEnd"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothHCIEventAMPTestEnd"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventAMPTestEnd"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventAMPReceiverReport": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventAMPReceiverReport"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventAMPReceiverReport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventAMPReceiverReport"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventAMPReceiverReport",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventampreceiverreport"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventAMPStartTest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventAMPStartTest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventAMPStartTest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventAMPStartTest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventAMPStartTest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventampstarttest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventAMPStatusChange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventAMPStatusChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventAMPStatusChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventAMPStatusChange"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventAMPStatusChange",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventampstatuschange"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventAMPTestEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventAMPTestEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventAMPTestEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventAMPTestEnd"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventAMPTestEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventamptestend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventAuthenticationComplete": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventAuthenticationComplete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventAuthenticationComplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventAuthenticationComplete"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventAuthenticationComplete",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventauthenticationcomplete"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventChangeConnectionLinkKeyComplete": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventChangeConnectionLinkKeyComplete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventChangeConnectionLinkKeyComplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventChangeConnectionLinkKeyComplete"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventChangeConnectionLinkKeyComplete",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventchangeconnectionlinkkeycomplete"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventChannelSelected": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventChannelSelected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventChannelSelected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventChannelSelected"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventChannelSelected",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventchannelselected"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventCommandComplete": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventCommandComplete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventCommandComplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventCommandComplete"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventCommandComplete",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventcommandcomplete"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventCommandStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventCommandStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventCommandStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventCommandStatus"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventCommandStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventcommandstatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventConnectionComplete": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventConnectionComplete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventConnectionComplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventConnectionComplete"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventConnectionComplete",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventconnectioncomplete"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventConnectionPacketType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventConnectionPacketType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventConnectionPacketType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventConnectionPacketType"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventConnectionPacketType",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventconnectionpackettype"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventConnectionRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventConnectionRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventConnectionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventConnectionRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventConnectionRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventconnectionrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventDataBufferOverflow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventDataBufferOverflow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventDataBufferOverflow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventDataBufferOverflow"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventDataBufferOverflow",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventdatabufferoverflow"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventDisconnectionComplete": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventDisconnectionComplete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventDisconnectionComplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventDisconnectionComplete"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventDisconnectionComplete",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventdisconnectioncomplete"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventDisconnectionLogicalLinkComplete": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventDisconnectionLogicalLinkComplete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventDisconnectionLogicalLinkComplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventDisconnectionLogicalLinkComplete"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventDisconnectionLogicalLinkComplete",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventdisconnectionlogicallinkcomplete"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventDisconnectionPhysicalLinkComplete": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventDisconnectionPhysicalLinkComplete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventDisconnectionPhysicalLinkComplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventDisconnectionPhysicalLinkComplete"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventDisconnectionPhysicalLinkComplete",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventdisconnectionphysicallinkcomplete"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventAMPReceiverReport",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventAMPStartTest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventAMPStatusChange",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventAuthenticationComplete",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventChangeConnectionLinkKeyComplete",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventChannelSelected",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventCommandComplete",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventCommandStatus",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventConnectionComplete",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventConnectionPacketType",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventConnectionRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventDataBufferOverflow",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventDisconnectionComplete",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventDisconnectionLogicalLinkComplete",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventDisconnectionPhysicalLinkComplete"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothHCIEventAMPTestEnd"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventAMPTestEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventAMPReceiverReport",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventAMPStartTest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventAMPStatusChange",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventAuthenticationComplete",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventChangeConnectionLinkKeyComplete",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventChannelSelected",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventCommandComplete",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventCommandStatus",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventConnectionComplete",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventConnectionPacketType",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventConnectionRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventDataBufferOverflow",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventDisconnectionComplete",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventDisconnectionLogicalLinkComplete",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventDisconnectionPhysicalLinkComplete"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothHCIEventAMPTestEnd"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventDisconnectionComplete/title",
          "value": "kBluetoothHCIEventDisconnectionComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventDisconnectionComplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventDisconnectionComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventConnectionRequest/title",
          "value": "kBluetoothHCIEventConnectionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventConnectionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventConnectionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventDisconnectionLogicalLinkComplete/title",
          "value": "kBluetoothHCIEventDisconnectionLogicalLinkComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventDisconnectionLogicalLinkComplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventDisconnectionLogicalLinkComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventCommandStatus/title",
          "value": "kBluetoothHCIEventCommandStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventCommandStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventCommandStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventAuthenticationComplete/title",
          "value": "kBluetoothHCIEventAuthenticationComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventAuthenticationComplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventAuthenticationComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventChannelSelected/title",
          "value": "kBluetoothHCIEventChannelSelected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventChannelSelected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventChannelSelected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventAMPTestEnd/title",
          "value": "kBluetoothHCIEventAMPTestEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventAMPTestEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventAMPTestEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventAMPReceiverReport/title",
          "value": "kBluetoothHCIEventAMPReceiverReport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventAMPReceiverReport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventAMPReceiverReport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventChangeConnectionLinkKeyComplete/title",
          "value": "kBluetoothHCIEventChangeConnectionLinkKeyComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventChangeConnectionLinkKeyComplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventChangeConnectionLinkKeyComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventAMPStatusChange/title",
          "value": "kBluetoothHCIEventAMPStatusChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventAMPStatusChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventAMPStatusChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventDataBufferOverflow/title",
          "value": "kBluetoothHCIEventDataBufferOverflow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventDataBufferOverflow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventDataBufferOverflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventConnectionPacketType/title",
          "value": "kBluetoothHCIEventConnectionPacketType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventConnectionPacketType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventConnectionPacketType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventCommandComplete/title",
          "value": "kBluetoothHCIEventCommandComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventCommandComplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventCommandComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventDisconnectionPhysicalLinkComplete/title",
          "value": "kBluetoothHCIEventDisconnectionPhysicalLinkComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventDisconnectionPhysicalLinkComplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventDisconnectionPhysicalLinkComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventConnectionComplete/title",
          "value": "kBluetoothHCIEventConnectionComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventConnectionComplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventConnectionComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventAMPStartTest/title",
          "value": "kBluetoothHCIEventAMPStartTest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventAMPStartTest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventAMPStartTest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothhcieventamptestend"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothhcieventamptestend"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
