{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIMaxDataPacketSize"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kBluetoothHCICommandPacketHeaderSize@kBluetoothHCIMaxDataPacketSize",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothHCIMaxDataPacketSize"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothHCIMaxDataPacketSize"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothHCIMaxDataPacketSize"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothHCIMaxDataPacketSize"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandPacketHeaderSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandPacketHeaderSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandPacketHeaderSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandPacketHeaderSize"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCICommandPacketHeaderSize",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcicommandpacketheadersize"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandPacketMaxDataSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandPacketMaxDataSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandPacketMaxDataSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandPacketMaxDataSize"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCICommandPacketMaxDataSize",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcicommandpacketmaxdatasize"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIDataPacketHeaderSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIDataPacketHeaderSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIDataPacketHeaderSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIDataPacketHeaderSize"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIDataPacketHeaderSize",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcidatapacketheadersize"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIDataPacketMaxDataSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIDataPacketMaxDataSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIDataPacketMaxDataSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIDataPacketMaxDataSize"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIDataPacketMaxDataSize",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcidatapacketmaxdatasize"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventPacketHeaderSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventPacketHeaderSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventPacketHeaderSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventPacketHeaderSize"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventPacketHeaderSize",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventpacketheadersize"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventPacketMaxDataSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventPacketMaxDataSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventPacketMaxDataSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIEventPacketMaxDataSize"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIEventPacketMaxDataSize",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcieventpacketmaxdatasize"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIMaxCommandPacketSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIMaxCommandPacketSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIMaxCommandPacketSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIMaxCommandPacketSize"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIMaxCommandPacketSize",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcimaxcommandpacketsize"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIMaxDataPacketSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIMaxDataPacketSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIMaxDataPacketSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIMaxDataPacketSize"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIMaxDataPacketSize",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcimaxdatapacketsize"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIMaxEventPacketSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCIMaxEventPacketSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIMaxEventPacketSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCIMaxEventPacketSize"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCIMaxEventPacketSize",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcimaxeventpacketsize"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandPacketHeaderSize",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandPacketMaxDataSize",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIDataPacketHeaderSize",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIDataPacketMaxDataSize",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventPacketHeaderSize",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventPacketMaxDataSize",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIMaxCommandPacketSize",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIMaxEventPacketSize"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothHCIMaxDataPacketSize"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIMaxDataPacketSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandPacketHeaderSize",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandPacketMaxDataSize",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIDataPacketHeaderSize",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIDataPacketMaxDataSize",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventPacketHeaderSize",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIEventPacketMaxDataSize",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIMaxCommandPacketSize",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCIMaxEventPacketSize"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothHCIMaxDataPacketSize"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandPacketMaxDataSize/title",
          "value": "kBluetoothHCICommandPacketMaxDataSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandPacketMaxDataSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCICommandPacketMaxDataSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIDataPacketMaxDataSize/title",
          "value": "kBluetoothHCIDataPacketMaxDataSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIDataPacketMaxDataSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIDataPacketMaxDataSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventPacketMaxDataSize/title",
          "value": "kBluetoothHCIEventPacketMaxDataSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventPacketMaxDataSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventPacketMaxDataSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIMaxEventPacketSize/title",
          "value": "kBluetoothHCIMaxEventPacketSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIMaxEventPacketSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIMaxEventPacketSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIDataPacketHeaderSize/title",
          "value": "kBluetoothHCIDataPacketHeaderSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIDataPacketHeaderSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIDataPacketHeaderSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIMaxDataPacketSize/title",
          "value": "kBluetoothHCIMaxDataPacketSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIMaxDataPacketSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIMaxDataPacketSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventPacketHeaderSize/title",
          "value": "kBluetoothHCIEventPacketHeaderSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIEventPacketHeaderSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIEventPacketHeaderSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandPacketHeaderSize/title",
          "value": "kBluetoothHCICommandPacketHeaderSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandPacketHeaderSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCICommandPacketHeaderSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIMaxCommandPacketSize/title",
          "value": "kBluetoothHCIMaxCommandPacketSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCIMaxCommandPacketSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCIMaxCommandPacketSize"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothhcimaxdatapacketsize"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothhcimaxdatapacketsize"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
