{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationExtendedWindowSize"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BluetoothL2CAPInformationExtendedFeaturesMask@kBluetoothL2CAPInformationExtendedWindowSize",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothL2CAPInformationExtendedWindowSize"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@BluetoothL2CAPInformationExtendedFeaturesMask",
        "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothL2CAPInformationExtendedWindowSize"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothL2CAPInformationExtendedWindowSize"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPInformationExtendedWindowSize"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPInformationExtendedFeaturesMask",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@BluetoothL2CAPInformationExtendedFeaturesMask",
              "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPInformationExtendedFeaturesMask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPInformationExtendedFeaturesMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPInformationExtendedFeaturesMask",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capinformationextendedfeaturesmask"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationBidirectionalQoS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPInformationBidirectionalQoS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPInformationExtendedFeaturesMask",
          "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationBidirectionalQoS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPInformationBidirectionalQoS"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPInformationBidirectionalQoS",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capinformationbidirectionalqos"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationEnhancedRetransmissionMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPInformationEnhancedRetransmissionMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPInformationExtendedFeaturesMask",
          "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationEnhancedRetransmissionMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPInformationEnhancedRetransmissionMode"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPInformationEnhancedRetransmissionMode",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capinformationenhancedretransmissionmode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationExtendedFlowSpecification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPInformationExtendedFlowSpecification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPInformationExtendedFeaturesMask",
          "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationExtendedFlowSpecification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPInformationExtendedFlowSpecification"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPInformationExtendedFlowSpecification",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capinformationextendedflowspecification"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationExtendedWindowSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPInformationExtendedWindowSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPInformationExtendedFeaturesMask",
          "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationExtendedWindowSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPInformationExtendedWindowSize"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPInformationExtendedWindowSize",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capinformationextendedwindowsize"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationFCSOption": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPInformationFCSOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPInformationExtendedFeaturesMask",
          "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationFCSOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPInformationFCSOption"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPInformationFCSOption",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capinformationfcsoption"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationFixedChannels": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPInformationFixedChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPInformationExtendedFeaturesMask",
          "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationFixedChannels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPInformationFixedChannels"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPInformationFixedChannels",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capinformationfixedchannels"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationFlowControlMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPInformationFlowControlMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPInformationExtendedFeaturesMask",
          "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationFlowControlMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPInformationFlowControlMode"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPInformationFlowControlMode",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capinformationflowcontrolmode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationNoExtendedFeatures": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPInformationNoExtendedFeatures"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPInformationExtendedFeaturesMask",
          "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationNoExtendedFeatures",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPInformationNoExtendedFeatures"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPInformationNoExtendedFeatures",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capinformationnoextendedfeatures"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationRetransmissionMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPInformationRetransmissionMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPInformationExtendedFeaturesMask",
          "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationRetransmissionMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPInformationRetransmissionMode"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPInformationRetransmissionMode",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capinformationretransmissionmode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationStreamingMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPInformationStreamingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPInformationExtendedFeaturesMask",
          "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationStreamingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPInformationStreamingMode"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPInformationStreamingMode",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capinformationstreamingmode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPUnicastConnectionlessDataReception": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPUnicastConnectionlessDataReception"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPInformationExtendedFeaturesMask",
          "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPUnicastConnectionlessDataReception",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPUnicastConnectionlessDataReception"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPUnicastConnectionlessDataReception",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capunicastconnectionlessdatareception"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationBidirectionalQoS",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationEnhancedRetransmissionMode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationExtendedFlowSpecification",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationFCSOption",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationFixedChannels",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationFlowControlMode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationNoExtendedFeatures",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationRetransmissionMode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationStreamingMode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPUnicastConnectionlessDataReception"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothL2CAPInformationExtendedWindowSize"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPInformationExtendedWindowSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPInformationExtendedFeaturesMask"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationBidirectionalQoS",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationEnhancedRetransmissionMode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationExtendedFlowSpecification",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationFCSOption",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationFixedChannels",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationFlowControlMode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationNoExtendedFeatures",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationRetransmissionMode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPInformationStreamingMode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPUnicastConnectionlessDataReception"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothL2CAPInformationExtendedWindowSize"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPInformationExtendedFeaturesMask/title",
          "value": "BluetoothL2CAPInformationExtendedFeaturesMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPInformationExtendedFeaturesMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPInformationExtendedFeaturesMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPInformationExtendedFeaturesMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPInformationFlowControlMode/title",
          "value": "kBluetoothL2CAPInformationFlowControlMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPInformationFlowControlMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPInformationFlowControlMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPInformationNoExtendedFeatures/title",
          "value": "kBluetoothL2CAPInformationNoExtendedFeatures"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPInformationNoExtendedFeatures/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPInformationNoExtendedFeatures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPInformationBidirectionalQoS/title",
          "value": "kBluetoothL2CAPInformationBidirectionalQoS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPInformationBidirectionalQoS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPInformationBidirectionalQoS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPInformationStreamingMode/title",
          "value": "kBluetoothL2CAPInformationStreamingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPInformationStreamingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPInformationStreamingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPInformationRetransmissionMode/title",
          "value": "kBluetoothL2CAPInformationRetransmissionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPInformationRetransmissionMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPInformationRetransmissionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPInformationExtendedWindowSize/title",
          "value": "kBluetoothL2CAPInformationExtendedWindowSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPInformationExtendedWindowSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPInformationExtendedWindowSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPInformationExtendedFlowSpecification/title",
          "value": "kBluetoothL2CAPInformationExtendedFlowSpecification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPInformationExtendedFlowSpecification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPInformationExtendedFlowSpecification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPInformationFixedChannels/title",
          "value": "kBluetoothL2CAPInformationFixedChannels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPInformationFixedChannels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPInformationFixedChannels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPInformationEnhancedRetransmissionMode/title",
          "value": "kBluetoothL2CAPInformationEnhancedRetransmissionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPInformationEnhancedRetransmissionMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPInformationEnhancedRetransmissionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPUnicastConnectionlessDataReception/title",
          "value": "kBluetoothL2CAPUnicastConnectionlessDataReception"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPUnicastConnectionlessDataReception/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPUnicastConnectionlessDataReception"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPInformationFCSOption/title",
          "value": "kBluetoothL2CAPInformationFCSOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPInformationFCSOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPInformationFCSOption"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothl2capinformationextendedwindowsize"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothl2capinformationextendedwindowsize"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
