{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPFlushTimeoutDefault"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kBluetoothL2CAPMTULowEnergyDefault@kBluetoothL2CAPFlushTimeoutDefault",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothL2CAPFlushTimeoutDefault"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothL2CAPFlushTimeoutDefault"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothL2CAPFlushTimeoutDefault"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPFlushTimeoutDefault"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPFlushTimeoutDefault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPFlushTimeoutDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPFlushTimeoutDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPFlushTimeoutDefault"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPFlushTimeoutDefault",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capflushtimeoutdefault"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTUDefault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPMTUDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTUDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPMTUDefault"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPMTUDefault",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capmtudefault"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTULowEnergyDefault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPMTULowEnergyDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTULowEnergyDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPMTULowEnergyDefault"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPMTULowEnergyDefault",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capmtulowenergydefault"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTULowEnergyMax": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPMTULowEnergyMax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTULowEnergyMax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPMTULowEnergyMax"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPMTULowEnergyMax",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capmtulowenergymax"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTUMaximum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPMTUMaximum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTUMaximum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPMTUMaximum"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPMTUMaximum",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capmtumaximum"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTUMinimum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPMTUMinimum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTUMinimum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPMTUMinimum"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPMTUMinimum",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capmtuminimum"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTUSIG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPMTUSIG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTUSIG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPMTUSIG"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPMTUSIG",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capmtusig"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTUStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPMTUStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTUStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPMTUStart"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPMTUStart",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capmtustart"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSDelayVariationDefault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPQoSDelayVariationDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSDelayVariationDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPQoSDelayVariationDefault"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPQoSDelayVariationDefault",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capqosdelayvariationdefault"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSFlagsDefault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPQoSFlagsDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSFlagsDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPQoSFlagsDefault"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPQoSFlagsDefault",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capqosflagsdefault"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSLatencyDefault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPQoSLatencyDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSLatencyDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPQoSLatencyDefault"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPQoSLatencyDefault",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capqoslatencydefault"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSPeakBandwidthDefault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPQoSPeakBandwidthDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSPeakBandwidthDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPQoSPeakBandwidthDefault"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPQoSPeakBandwidthDefault",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capqospeakbandwidthdefault"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSTokenBucketSizeDefault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPQoSTokenBucketSizeDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSTokenBucketSizeDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPQoSTokenBucketSizeDefault"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPQoSTokenBucketSizeDefault",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capqostokenbucketsizedefault"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSTokenRateDefault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPQoSTokenRateDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSTokenRateDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPQoSTokenRateDefault"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPQoSTokenRateDefault",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capqostokenratedefault"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSTypeDefault": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPQoSTypeDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSTypeDefault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPQoSTypeDefault"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPQoSTypeDefault",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capqostypedefault"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTUDefault",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTULowEnergyDefault",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTUMaximum",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTUMinimum",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTUSIG",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTUStart",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSDelayVariationDefault",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSFlagsDefault",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSLatencyDefault",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSPeakBandwidthDefault",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSTokenBucketSizeDefault",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSTokenRateDefault",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSTypeDefault",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTULowEnergyMax"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothL2CAPFlushTimeoutDefault"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPFlushTimeoutDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTUDefault",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTULowEnergyDefault",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTUMaximum",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTUMinimum",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTUSIG",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTUStart",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSDelayVariationDefault",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSFlagsDefault",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSLatencyDefault",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSPeakBandwidthDefault",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSTokenBucketSizeDefault",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSTokenRateDefault",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPQoSTypeDefault",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPMTULowEnergyMax"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothL2CAPFlushTimeoutDefault"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPMTULowEnergyDefault/title",
          "value": "kBluetoothL2CAPMTULowEnergyDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPMTULowEnergyDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPMTULowEnergyDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPQoSTokenRateDefault/title",
          "value": "kBluetoothL2CAPQoSTokenRateDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPQoSTokenRateDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPQoSTokenRateDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPQoSFlagsDefault/title",
          "value": "kBluetoothL2CAPQoSFlagsDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPQoSFlagsDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPQoSFlagsDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPQoSDelayVariationDefault/title",
          "value": "kBluetoothL2CAPQoSDelayVariationDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPQoSDelayVariationDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPQoSDelayVariationDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPMTUSIG/title",
          "value": "kBluetoothL2CAPMTUSIG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPMTUSIG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPMTUSIG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPMTUStart/title",
          "value": "kBluetoothL2CAPMTUStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPMTUStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPMTUStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPQoSTypeDefault/title",
          "value": "kBluetoothL2CAPQoSTypeDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPQoSTypeDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPQoSTypeDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPQoSPeakBandwidthDefault/title",
          "value": "kBluetoothL2CAPQoSPeakBandwidthDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPQoSPeakBandwidthDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPQoSPeakBandwidthDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPMTUDefault/title",
          "value": "kBluetoothL2CAPMTUDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPMTUDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPMTUDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPQoSLatencyDefault/title",
          "value": "kBluetoothL2CAPQoSLatencyDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPQoSLatencyDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPQoSLatencyDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPMTUMaximum/title",
          "value": "kBluetoothL2CAPMTUMaximum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPMTUMaximum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPMTUMaximum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPMTUMinimum/title",
          "value": "kBluetoothL2CAPMTUMinimum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPMTUMinimum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPMTUMinimum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPMTULowEnergyMax/title",
          "value": "kBluetoothL2CAPMTULowEnergyMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPMTULowEnergyMax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPMTULowEnergyMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPQoSTokenBucketSizeDefault/title",
          "value": "kBluetoothL2CAPQoSTokenBucketSizeDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPQoSTokenBucketSizeDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPQoSTokenBucketSizeDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPFlushTimeoutDefault/title",
          "value": "kBluetoothL2CAPFlushTimeoutDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPFlushTimeoutDefault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPFlushTimeoutDefault"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothl2capflushtimeoutdefault"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothl2capflushtimeoutdefault"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
