{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification4_2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@BluetoothLMPVersions@kBluetoothLMPVersionCoreSpecification4_2",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothLMPVersionCoreSpecification4_2"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@BluetoothLMPVersions",
        "text": "BluetoothLMPVersions"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothLMPVersionCoreSpecification4_2"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothLMPVersionCoreSpecification4_2"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothLMPVersionCoreSpecification4_2"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLMPVersions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@BluetoothLMPVersions",
              "text": "BluetoothLMPVersions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLMPVersions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothLMPVersions"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLMPVersions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothLMPVersions"
        }
      ],
      "role": "symbol",
      "title": "BluetoothLMPVersions",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothlmpversions"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification1_0b": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification1_0b"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothLMPVersions",
          "text": "BluetoothLMPVersions"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification1_0b",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification1_0b"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLMPVersionCoreSpecification1_0b",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlmpversioncorespecification1_0b"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification1_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification1_1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothLMPVersions",
          "text": "BluetoothLMPVersions"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification1_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification1_1"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLMPVersionCoreSpecification1_1",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlmpversioncorespecification1_1"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification1_2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification1_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothLMPVersions",
          "text": "BluetoothLMPVersions"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification1_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification1_2"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLMPVersionCoreSpecification1_2",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlmpversioncorespecification1_2"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification2_0EDR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification2_0EDR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothLMPVersions",
          "text": "BluetoothLMPVersions"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification2_0EDR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification2_0EDR"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLMPVersionCoreSpecification2_0EDR",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlmpversioncorespecification2_0edr"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification2_1EDR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification2_1EDR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothLMPVersions",
          "text": "BluetoothLMPVersions"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification2_1EDR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification2_1EDR"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLMPVersionCoreSpecification2_1EDR",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlmpversioncorespecification2_1edr"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification3_0HS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification3_0HS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothLMPVersions",
          "text": "BluetoothLMPVersions"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification3_0HS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification3_0HS"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLMPVersionCoreSpecification3_0HS",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlmpversioncorespecification3_0hs"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification4_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification4_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothLMPVersions",
          "text": "BluetoothLMPVersions"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification4_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification4_0"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLMPVersionCoreSpecification4_0",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlmpversioncorespecification4_0"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification4_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification4_1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothLMPVersions",
          "text": "BluetoothLMPVersions"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification4_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification4_1"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLMPVersionCoreSpecification4_1",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlmpversioncorespecification4_1"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification4_2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification4_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothLMPVersions",
          "text": "BluetoothLMPVersions"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification4_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification4_2"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLMPVersionCoreSpecification4_2",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlmpversioncorespecification4_2"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification5_0": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification5_0"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothLMPVersions",
          "text": "BluetoothLMPVersions"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification5_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification5_0"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLMPVersionCoreSpecification5_0",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlmpversioncorespecification5_0"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification5_1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification5_1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothLMPVersions",
          "text": "BluetoothLMPVersions"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification5_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification5_1"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLMPVersionCoreSpecification5_1",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlmpversioncorespecification5_1"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification5_2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification5_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothLMPVersions",
          "text": "BluetoothLMPVersions"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification5_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothLMPVersionCoreSpecification5_2"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothLMPVersionCoreSpecification5_2",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothlmpversioncorespecification5_2"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification1_0b",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification1_1",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification1_2",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification2_0EDR",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification2_1EDR",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification3_0HS",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification4_0",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification4_1",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification5_0",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification5_1",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification5_2"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothLMPVersionCoreSpecification4_2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLMPVersionCoreSpecification4_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothLMPVersions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification1_0b",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification1_1",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification1_2",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification2_0EDR",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification2_1EDR",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification3_0HS",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification4_0",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification4_1",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification5_0",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification5_1",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothLMPVersionCoreSpecification5_2"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothLMPVersionCoreSpecification4_2"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLMPVersions/title",
          "value": "BluetoothLMPVersions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLMPVersions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLMPVersions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothLMPVersions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothLMPVersions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification2_1EDR/title",
          "value": "kBluetoothLMPVersionCoreSpecification2_1EDR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification2_1EDR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLMPVersionCoreSpecification2_1EDR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification1_0b/title",
          "value": "kBluetoothLMPVersionCoreSpecification1_0b"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification1_0b/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLMPVersionCoreSpecification1_0b"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification5_2/title",
          "value": "kBluetoothLMPVersionCoreSpecification5_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification5_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLMPVersionCoreSpecification5_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification5_1/title",
          "value": "kBluetoothLMPVersionCoreSpecification5_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification5_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLMPVersionCoreSpecification5_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification5_0/title",
          "value": "kBluetoothLMPVersionCoreSpecification5_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification5_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLMPVersionCoreSpecification5_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification2_0EDR/title",
          "value": "kBluetoothLMPVersionCoreSpecification2_0EDR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification2_0EDR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLMPVersionCoreSpecification2_0EDR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification1_1/title",
          "value": "kBluetoothLMPVersionCoreSpecification1_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification1_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLMPVersionCoreSpecification1_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification4_1/title",
          "value": "kBluetoothLMPVersionCoreSpecification4_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification4_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLMPVersionCoreSpecification4_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification4_0/title",
          "value": "kBluetoothLMPVersionCoreSpecification4_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification4_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLMPVersionCoreSpecification4_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification3_0HS/title",
          "value": "kBluetoothLMPVersionCoreSpecification3_0HS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification3_0HS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLMPVersionCoreSpecification3_0HS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification1_2/title",
          "value": "kBluetoothLMPVersionCoreSpecification1_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification1_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLMPVersionCoreSpecification1_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification4_2/title",
          "value": "kBluetoothLMPVersionCoreSpecification4_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothLMPVersionCoreSpecification4_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothLMPVersionCoreSpecification4_2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothlmpversioncorespecification4_2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothlmpversioncorespecification4_2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
