{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredNoBonding"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@BluetoothAuthenticationRequirementsValues@kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredNoBonding",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredNoBonding"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@BluetoothAuthenticationRequirementsValues",
        "text": "BluetoothAuthenticationRequirementsValues"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredNoBonding"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredNoBonding"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredNoBonding"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@BluetoothAuthenticationRequirementsValues",
              "text": "BluetoothAuthenticationRequirementsValues"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAuthenticationRequirementsValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothauthenticationrequirementsvalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionNotRequired": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothAuthenticationRequirementsValues",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionNotRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequired"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequired",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothauthenticationrequirementsmitmprotectionnotrequired"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredDedicatedBonding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredDedicatedBonding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothAuthenticationRequirementsValues",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredDedicatedBonding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredDedicatedBonding"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredDedicatedBonding",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothauthenticationrequirementsmitmprotectionnotrequireddedicatedbonding"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredGeneralBonding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredGeneralBonding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothAuthenticationRequirementsValues",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredGeneralBonding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredGeneralBonding"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredGeneralBonding",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothauthenticationrequirementsmitmprotectionnotrequiredgeneralbonding"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredNoBonding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredNoBonding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothAuthenticationRequirementsValues",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredNoBonding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredNoBonding"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredNoBonding",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothauthenticationrequirementsmitmprotectionnotrequirednobonding"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionRequired": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAuthenticationRequirementsMITMProtectionRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothAuthenticationRequirementsValues",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAuthenticationRequirementsMITMProtectionRequired"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAuthenticationRequirementsMITMProtectionRequired",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothauthenticationrequirementsmitmprotectionrequired"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionRequiredDedicatedBonding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAuthenticationRequirementsMITMProtectionRequiredDedicatedBonding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothAuthenticationRequirementsValues",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionRequiredDedicatedBonding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAuthenticationRequirementsMITMProtectionRequiredDedicatedBonding"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAuthenticationRequirementsMITMProtectionRequiredDedicatedBonding",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothauthenticationrequirementsmitmprotectionrequireddedicatedbonding"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionRequiredGeneralBonding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAuthenticationRequirementsMITMProtectionRequiredGeneralBonding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothAuthenticationRequirementsValues",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionRequiredGeneralBonding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAuthenticationRequirementsMITMProtectionRequiredGeneralBonding"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAuthenticationRequirementsMITMProtectionRequiredGeneralBonding",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothauthenticationrequirementsmitmprotectionrequiredgeneralbonding"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionRequiredNoBonding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAuthenticationRequirementsMITMProtectionRequiredNoBonding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothAuthenticationRequirementsValues",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionRequiredNoBonding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAuthenticationRequirementsMITMProtectionRequiredNoBonding"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAuthenticationRequirementsMITMProtectionRequiredNoBonding",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothauthenticationrequirementsmitmprotectionrequirednobonding"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionNotRequired",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredDedicatedBonding",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredGeneralBonding",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionRequired",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionRequiredDedicatedBonding",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionRequiredGeneralBonding",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionRequiredNoBonding"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredNoBonding"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredNoBonding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionNotRequired",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredDedicatedBonding",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredGeneralBonding",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionRequired",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionRequiredDedicatedBonding",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionRequiredGeneralBonding",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAuthenticationRequirementsMITMProtectionRequiredNoBonding"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredNoBonding"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAuthenticationRequirementsMITMProtectionRequiredNoBonding/title",
          "value": "kBluetoothAuthenticationRequirementsMITMProtectionRequiredNoBonding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAuthenticationRequirementsMITMProtectionRequiredNoBonding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAuthenticationRequirementsMITMProtectionRequiredNoBonding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredDedicatedBonding/title",
          "value": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredDedicatedBonding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredDedicatedBonding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredDedicatedBonding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAuthenticationRequirementsMITMProtectionRequiredDedicatedBonding/title",
          "value": "kBluetoothAuthenticationRequirementsMITMProtectionRequiredDedicatedBonding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAuthenticationRequirementsMITMProtectionRequiredDedicatedBonding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAuthenticationRequirementsMITMProtectionRequiredDedicatedBonding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredNoBonding/title",
          "value": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredNoBonding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredNoBonding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredNoBonding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAuthenticationRequirementsMITMProtectionNotRequired/title",
          "value": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAuthenticationRequirementsMITMProtectionNotRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/title",
          "value": "BluetoothAuthenticationRequirementsValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirementsValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirementsValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAuthenticationRequirementsMITMProtectionRequired/title",
          "value": "kBluetoothAuthenticationRequirementsMITMProtectionRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAuthenticationRequirementsMITMProtectionRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAuthenticationRequirementsMITMProtectionRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAuthenticationRequirementsMITMProtectionRequiredGeneralBonding/title",
          "value": "kBluetoothAuthenticationRequirementsMITMProtectionRequiredGeneralBonding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAuthenticationRequirementsMITMProtectionRequiredGeneralBonding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAuthenticationRequirementsMITMProtectionRequiredGeneralBonding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredGeneralBonding/title",
          "value": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredGeneralBonding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredGeneralBonding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAuthenticationRequirementsMITMProtectionNotRequiredGeneralBonding"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothauthenticationrequirementsmitmprotectionnotrequirednobonding"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothauthenticationrequirementsmitmprotectionnotrequirednobonding"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
