{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorPeripheral"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kBluetoothDeviceClassMajorMiscellaneous@kBluetoothDeviceClassMajorPeripheral",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothDeviceClassMajorPeripheral"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothDeviceClassMajorPeripheral"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothDeviceClassMajorPeripheral"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorPeripheral"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorAny": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorAny"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorAny",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorAny"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorAny",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajorany"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorAudio": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorAudio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorAudio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorAudio"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorAudio",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajoraudio"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorComputer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorComputer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorComputer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorComputer"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorComputer",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajorcomputer"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorEnd"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajorend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorHealth": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorHealth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorHealth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorHealth"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorHealth",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajorhealth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorImaging": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorImaging"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorImaging",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorImaging"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorImaging",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajorimaging"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorLANAccessPoint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorLANAccessPoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorLANAccessPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorLANAccessPoint"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorLANAccessPoint",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajorlanaccesspoint"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorMiscellaneous": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorMiscellaneous"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorMiscellaneous",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorMiscellaneous"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorMiscellaneous",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajormiscellaneous"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorNone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorNone"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorNone",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajornone"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorPeripheral": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorPeripheral"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorPeripheral",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorPeripheral"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorPeripheral",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajorperipheral"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorPhone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorPhone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorPhone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorPhone"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorPhone",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajorphone"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorToy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorToy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorToy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorToy"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorToy",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajortoy"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorUnclassified": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorUnclassified"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorUnclassified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorUnclassified"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorUnclassified",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajorunclassified"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorWearable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorWearable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorWearable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothDeviceClassMajorWearable"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothDeviceClassMajorWearable",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothdeviceclassmajorwearable"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorAny",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorAudio",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorComputer",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorEnd",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorHealth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorImaging",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorLANAccessPoint",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorMiscellaneous",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorNone",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorPhone",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorToy",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorUnclassified",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorWearable"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothDeviceClassMajorPeripheral"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorPeripheral"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorAny",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorAudio",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorComputer",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorEnd",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorHealth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorImaging",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorLANAccessPoint",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorMiscellaneous",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorNone",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorPhone",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorToy",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorUnclassified",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothDeviceClassMajorWearable"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothDeviceClassMajorPeripheral"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorUnclassified/title",
          "value": "kBluetoothDeviceClassMajorUnclassified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorUnclassified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorUnclassified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorComputer/title",
          "value": "kBluetoothDeviceClassMajorComputer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorComputer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorComputer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorMiscellaneous/title",
          "value": "kBluetoothDeviceClassMajorMiscellaneous"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorMiscellaneous/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorMiscellaneous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorEnd/title",
          "value": "kBluetoothDeviceClassMajorEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorLANAccessPoint/title",
          "value": "kBluetoothDeviceClassMajorLANAccessPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorLANAccessPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorLANAccessPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorAny/title",
          "value": "kBluetoothDeviceClassMajorAny"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorAny/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorAny"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorHealth/title",
          "value": "kBluetoothDeviceClassMajorHealth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorHealth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorHealth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorImaging/title",
          "value": "kBluetoothDeviceClassMajorImaging"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorImaging/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorImaging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorPeripheral/title",
          "value": "kBluetoothDeviceClassMajorPeripheral"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorPeripheral/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorPeripheral"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorPhone/title",
          "value": "kBluetoothDeviceClassMajorPhone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorPhone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorPhone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorToy/title",
          "value": "kBluetoothDeviceClassMajorToy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorToy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorToy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorWearable/title",
          "value": "kBluetoothDeviceClassMajorWearable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorWearable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorWearable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorAudio/title",
          "value": "kBluetoothDeviceClassMajorAudio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorAudio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorAudio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorNone/title",
          "value": "kBluetoothDeviceClassMajorNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothDeviceClassMajorNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothDeviceClassMajorNone"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothdeviceclassmajorperipheral"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothdeviceclassmajorperipheral"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
