{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelDynamicEnd"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kBluetoothL2CAPChannelNull@kBluetoothL2CAPChannelDynamicEnd",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothL2CAPChannelDynamicEnd"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothL2CAPChannelDynamicEnd"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothL2CAPChannelDynamicEnd"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPChannelDynamicEnd"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelAMPManagerProtocol": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelAMPManagerProtocol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelAMPManagerProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelAMPManagerProtocol"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPChannelAMPManagerProtocol",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capchannelampmanagerprotocol"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelAttributeProtocol": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelAttributeProtocol"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelAttributeProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelAttributeProtocol"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPChannelAttributeProtocol",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capchannelattributeprotocol"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelConnectionLessData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelConnectionLessData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelConnectionLessData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelConnectionLessData"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPChannelConnectionLessData",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capchannelconnectionlessdata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelDynamicEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelDynamicEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelDynamicEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelDynamicEnd"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPChannelDynamicEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capchanneldynamicend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelDynamicStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelDynamicStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelDynamicStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelDynamicStart"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPChannelDynamicStart",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capchanneldynamicstart"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelEnd"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPChannelEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capchannelend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelLEAP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelLEAP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelLEAP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelLEAP"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPChannelLEAP",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capchannelleap"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelLEAS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelLEAS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelLEAS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelLEAS"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPChannelLEAS",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capchannelleas"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelLESignalling": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelLESignalling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelLESignalling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelLESignalling"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPChannelLESignalling",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capchannellesignalling"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelMagicPairing": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelMagicPairing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelMagicPairing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelMagicPairing"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPChannelMagicPairing",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capchannelmagicpairing"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelMagnet": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelMagnet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelMagnet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelMagnet"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPChannelMagnet",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capchannelmagnet"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelNull": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelNull"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelNull",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelNull"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPChannelNull",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capchannelnull"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelReservedEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelReservedEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelReservedEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelReservedEnd"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPChannelReservedEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capchannelreservedend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelReservedStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelReservedStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelReservedStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelReservedStart"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPChannelReservedStart",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capchannelreservedstart"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelSecurityManager": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelSecurityManager"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelSecurityManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelSecurityManager"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPChannelSecurityManager",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capchannelsecuritymanager"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelSignalling": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelSignalling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelSignalling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPChannelSignalling"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPChannelSignalling",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capchannelsignalling"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelAMPManagerProtocol",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelAttributeProtocol",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelConnectionLessData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelDynamicStart",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelEnd",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelLEAP",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelLEAS",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelLESignalling",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelMagnet",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelNull",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelReservedEnd",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelReservedStart",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelSecurityManager",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelSignalling",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelMagicPairing"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothL2CAPChannelDynamicEnd"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPChannelDynamicEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelAMPManagerProtocol",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelAttributeProtocol",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelConnectionLessData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelDynamicStart",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelEnd",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelLEAP",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelLEAS",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelLESignalling",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelMagnet",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelNull",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelReservedEnd",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelReservedStart",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelSecurityManager",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelSignalling",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPChannelMagicPairing"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothL2CAPChannelDynamicEnd"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelNull/title",
          "value": "kBluetoothL2CAPChannelNull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelNull/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPChannelNull"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelDynamicEnd/title",
          "value": "kBluetoothL2CAPChannelDynamicEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelDynamicEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPChannelDynamicEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelReservedStart/title",
          "value": "kBluetoothL2CAPChannelReservedStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelReservedStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPChannelReservedStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelLEAS/title",
          "value": "kBluetoothL2CAPChannelLEAS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelLEAS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPChannelLEAS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelAMPManagerProtocol/title",
          "value": "kBluetoothL2CAPChannelAMPManagerProtocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelAMPManagerProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPChannelAMPManagerProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelSecurityManager/title",
          "value": "kBluetoothL2CAPChannelSecurityManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelSecurityManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPChannelSecurityManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelConnectionLessData/title",
          "value": "kBluetoothL2CAPChannelConnectionLessData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelConnectionLessData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPChannelConnectionLessData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelMagicPairing/title",
          "value": "kBluetoothL2CAPChannelMagicPairing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelMagicPairing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPChannelMagicPairing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelReservedEnd/title",
          "value": "kBluetoothL2CAPChannelReservedEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelReservedEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPChannelReservedEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelLESignalling/title",
          "value": "kBluetoothL2CAPChannelLESignalling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelLESignalling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPChannelLESignalling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelMagnet/title",
          "value": "kBluetoothL2CAPChannelMagnet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelMagnet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPChannelMagnet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelAttributeProtocol/title",
          "value": "kBluetoothL2CAPChannelAttributeProtocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelAttributeProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPChannelAttributeProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelDynamicStart/title",
          "value": "kBluetoothL2CAPChannelDynamicStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelDynamicStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPChannelDynamicStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelEnd/title",
          "value": "kBluetoothL2CAPChannelEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPChannelEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelSignalling/title",
          "value": "kBluetoothL2CAPChannelSignalling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelSignalling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPChannelSignalling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelLEAP/title",
          "value": "kBluetoothL2CAPChannelLEAP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPChannelLEAP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPChannelLEAP"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothl2capchanneldynamicend"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothl2capchanneldynamicend"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
