{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeypressNotificationTypePasskeyEntryStarted"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@BluetoothKeypressNotificationTypes@kBluetoothKeypressNotificationTypePasskeyEntryStarted",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothKeypressNotificationTypePasskeyEntryStarted"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@BluetoothKeypressNotificationTypes",
        "text": "BluetoothKeypressNotificationTypes"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothKeypressNotificationTypePasskeyEntryStarted"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothKeypressNotificationTypePasskeyEntryStarted"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothKeypressNotificationTypePasskeyEntryStarted"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothKeypressNotificationTypes",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@BluetoothKeypressNotificationTypes",
              "text": "BluetoothKeypressNotificationTypes"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothKeypressNotificationTypes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothKeypressNotificationTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothKeypressNotificationTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothKeypressNotificationTypes"
        }
      ],
      "role": "symbol",
      "title": "BluetoothKeypressNotificationTypes",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothkeypressnotificationtypes"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeypressNotificationTypePasskeyCleared": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothKeypressNotificationTypePasskeyCleared"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothKeypressNotificationTypes",
          "text": "BluetoothKeypressNotificationTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeypressNotificationTypePasskeyCleared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothKeypressNotificationTypePasskeyCleared"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothKeypressNotificationTypePasskeyCleared",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothkeypressnotificationtypepasskeycleared"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeypressNotificationTypePasskeyDigitEntered": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothKeypressNotificationTypePasskeyDigitEntered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothKeypressNotificationTypes",
          "text": "BluetoothKeypressNotificationTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeypressNotificationTypePasskeyDigitEntered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothKeypressNotificationTypePasskeyDigitEntered"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothKeypressNotificationTypePasskeyDigitEntered",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothkeypressnotificationtypepasskeydigitentered"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeypressNotificationTypePasskeyDigitErased": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothKeypressNotificationTypePasskeyDigitErased"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothKeypressNotificationTypes",
          "text": "BluetoothKeypressNotificationTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeypressNotificationTypePasskeyDigitErased",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothKeypressNotificationTypePasskeyDigitErased"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothKeypressNotificationTypePasskeyDigitErased",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothkeypressnotificationtypepasskeydigiterased"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeypressNotificationTypePasskeyEntryCompleted": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothKeypressNotificationTypePasskeyEntryCompleted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothKeypressNotificationTypes",
          "text": "BluetoothKeypressNotificationTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeypressNotificationTypePasskeyEntryCompleted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothKeypressNotificationTypePasskeyEntryCompleted"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothKeypressNotificationTypePasskeyEntryCompleted",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothkeypressnotificationtypepasskeyentrycompleted"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeypressNotificationTypePasskeyEntryStarted": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothKeypressNotificationTypePasskeyEntryStarted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothKeypressNotificationTypes",
          "text": "BluetoothKeypressNotificationTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeypressNotificationTypePasskeyEntryStarted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothKeypressNotificationTypePasskeyEntryStarted"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothKeypressNotificationTypePasskeyEntryStarted",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothkeypressnotificationtypepasskeyentrystarted"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeypressNotificationTypePasskeyCleared",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeypressNotificationTypePasskeyDigitEntered",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeypressNotificationTypePasskeyDigitErased",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeypressNotificationTypePasskeyEntryCompleted"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothKeypressNotificationTypePasskeyEntryStarted"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothKeypressNotificationTypePasskeyEntryStarted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothKeypressNotificationTypes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeypressNotificationTypePasskeyCleared",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeypressNotificationTypePasskeyDigitEntered",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeypressNotificationTypePasskeyDigitErased",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothKeypressNotificationTypePasskeyEntryCompleted"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothKeypressNotificationTypePasskeyEntryStarted"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeypressNotificationTypePasskeyDigitEntered/title",
          "value": "kBluetoothKeypressNotificationTypePasskeyDigitEntered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeypressNotificationTypePasskeyDigitEntered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothKeypressNotificationTypePasskeyDigitEntered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeypressNotificationTypePasskeyCleared/title",
          "value": "kBluetoothKeypressNotificationTypePasskeyCleared"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeypressNotificationTypePasskeyCleared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothKeypressNotificationTypePasskeyCleared"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeypressNotificationTypePasskeyEntryStarted/title",
          "value": "kBluetoothKeypressNotificationTypePasskeyEntryStarted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeypressNotificationTypePasskeyEntryStarted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothKeypressNotificationTypePasskeyEntryStarted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeypressNotificationTypePasskeyDigitErased/title",
          "value": "kBluetoothKeypressNotificationTypePasskeyDigitErased"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeypressNotificationTypePasskeyDigitErased/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothKeypressNotificationTypePasskeyDigitErased"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothKeypressNotificationTypes/title",
          "value": "BluetoothKeypressNotificationTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothKeypressNotificationTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothKeypressNotificationTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothKeypressNotificationTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothKeypressNotificationTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeypressNotificationTypePasskeyEntryCompleted/title",
          "value": "kBluetoothKeypressNotificationTypePasskeyEntryCompleted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothKeypressNotificationTypePasskeyEntryCompleted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothKeypressNotificationTypePasskeyEntryCompleted"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothkeypressnotificationtypepasskeyentrystarted"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothkeypressnotificationtypepasskeyentrystarted"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
