{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeAll"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kBluetoothSynchronousConnectionPacketTypeNone@kBluetoothSynchronousConnectionPacketTypeAll",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothSynchronousConnectionPacketTypeAll"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothSynchronousConnectionPacketTypeAll"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothSynchronousConnectionPacketTypeAll"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothSynchronousConnectionPacketTypeAll"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketType2EV3Omit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketType2EV3Omit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketType2EV3Omit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketType2EV3Omit"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSynchronousConnectionPacketType2EV3Omit",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsynchronousconnectionpackettype2ev3omit"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketType2EV5Omit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketType2EV5Omit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketType2EV5Omit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketType2EV5Omit"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSynchronousConnectionPacketType2EV5Omit",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsynchronousconnectionpackettype2ev5omit"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketType3EV3Omit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketType3EV3Omit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketType3EV3Omit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketType3EV3Omit"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSynchronousConnectionPacketType3EV3Omit",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsynchronousconnectionpackettype3ev3omit"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketType3EV5Omit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketType3EV5Omit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketType3EV5Omit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketType3EV5Omit"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSynchronousConnectionPacketType3EV5Omit",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsynchronousconnectionpackettype3ev5omit"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeAll": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketTypeAll"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeAll",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketTypeAll"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSynchronousConnectionPacketTypeAll",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsynchronousconnectionpackettypeall"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeEV3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketTypeEV3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeEV3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketTypeEV3"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSynchronousConnectionPacketTypeEV3",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsynchronousconnectionpackettypeev3"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeEV4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketTypeEV4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeEV4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketTypeEV4"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSynchronousConnectionPacketTypeEV4",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsynchronousconnectionpackettypeev4"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeEV5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketTypeEV5"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeEV5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketTypeEV5"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSynchronousConnectionPacketTypeEV5",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsynchronousconnectionpackettypeev5"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketTypeEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketTypeEnd"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSynchronousConnectionPacketTypeEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsynchronousconnectionpackettypeend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeFutureUse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketTypeFutureUse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeFutureUse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketTypeFutureUse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSynchronousConnectionPacketTypeFutureUse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsynchronousconnectionpackettypefutureuse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeHV1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketTypeHV1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeHV1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketTypeHV1"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSynchronousConnectionPacketTypeHV1",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsynchronousconnectionpackettypehv1"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeHV2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketTypeHV2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeHV2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketTypeHV2"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSynchronousConnectionPacketTypeHV2",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsynchronousconnectionpackettypehv2"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeHV3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketTypeHV3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeHV3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketTypeHV3"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSynchronousConnectionPacketTypeHV3",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsynchronousconnectionpackettypehv3"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeNone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketTypeNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSynchronousConnectionPacketTypeNone"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSynchronousConnectionPacketTypeNone",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsynchronousconnectionpackettypenone"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketType2EV3Omit",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketType2EV5Omit",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketType3EV3Omit",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketType3EV5Omit",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeEV3",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeEV4",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeEV5",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeEnd",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeFutureUse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeHV1",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeHV2",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeHV3",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeNone"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothSynchronousConnectionPacketTypeAll"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSynchronousConnectionPacketTypeAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketType2EV3Omit",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketType2EV5Omit",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketType3EV3Omit",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketType3EV5Omit",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeEV3",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeEV4",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeEV5",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeEnd",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeFutureUse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeHV1",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeHV2",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeHV3",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSynchronousConnectionPacketTypeNone"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothSynchronousConnectionPacketTypeAll"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketType2EV5Omit/title",
          "value": "kBluetoothSynchronousConnectionPacketType2EV5Omit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketType2EV5Omit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSynchronousConnectionPacketType2EV5Omit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketType2EV3Omit/title",
          "value": "kBluetoothSynchronousConnectionPacketType2EV3Omit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketType2EV3Omit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSynchronousConnectionPacketType2EV3Omit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketTypeHV2/title",
          "value": "kBluetoothSynchronousConnectionPacketTypeHV2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketTypeHV2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSynchronousConnectionPacketTypeHV2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketTypeEnd/title",
          "value": "kBluetoothSynchronousConnectionPacketTypeEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketTypeEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSynchronousConnectionPacketTypeEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketType3EV3Omit/title",
          "value": "kBluetoothSynchronousConnectionPacketType3EV3Omit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketType3EV3Omit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSynchronousConnectionPacketType3EV3Omit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketTypeFutureUse/title",
          "value": "kBluetoothSynchronousConnectionPacketTypeFutureUse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketTypeFutureUse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSynchronousConnectionPacketTypeFutureUse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketTypeHV1/title",
          "value": "kBluetoothSynchronousConnectionPacketTypeHV1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketTypeHV1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSynchronousConnectionPacketTypeHV1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketTypeEV3/title",
          "value": "kBluetoothSynchronousConnectionPacketTypeEV3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketTypeEV3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSynchronousConnectionPacketTypeEV3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketTypeNone/title",
          "value": "kBluetoothSynchronousConnectionPacketTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketTypeNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSynchronousConnectionPacketTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketTypeHV3/title",
          "value": "kBluetoothSynchronousConnectionPacketTypeHV3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketTypeHV3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSynchronousConnectionPacketTypeHV3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketType3EV5Omit/title",
          "value": "kBluetoothSynchronousConnectionPacketType3EV5Omit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketType3EV5Omit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSynchronousConnectionPacketType3EV5Omit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketTypeEV4/title",
          "value": "kBluetoothSynchronousConnectionPacketTypeEV4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketTypeEV4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSynchronousConnectionPacketTypeEV4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketTypeEV5/title",
          "value": "kBluetoothSynchronousConnectionPacketTypeEV5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketTypeEV5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSynchronousConnectionPacketTypeEV5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketTypeAll/title",
          "value": "kBluetoothSynchronousConnectionPacketTypeAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSynchronousConnectionPacketTypeAll/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSynchronousConnectionPacketTypeAll"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothsynchronousconnectionpackettypeall"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothsynchronousconnectionpackettypeall"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
