{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeUUID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kBluetoothSDPDataElementTypeNil@kBluetoothSDPDataElementTypeUUID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothSDPDataElementTypeUUID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothSDPDataElementTypeUUID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothSDPDataElementTypeUUID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothSDPDataElementTypeUUID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeBoolean": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeBoolean"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeBoolean",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeBoolean"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPDataElementTypeBoolean",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpdataelementtypeboolean"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeDataElementAlternative": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeDataElementAlternative"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeDataElementAlternative",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeDataElementAlternative"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPDataElementTypeDataElementAlternative",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpdataelementtypedataelementalternative"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeDataElementSequence": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeDataElementSequence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeDataElementSequence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeDataElementSequence"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPDataElementTypeDataElementSequence",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpdataelementtypedataelementsequence"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeNil": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeNil"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeNil",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeNil"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPDataElementTypeNil",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpdataelementtypenil"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeReservedEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeReservedEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeReservedEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeReservedEnd"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPDataElementTypeReservedEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpdataelementtypereservedend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeReservedStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeReservedStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeReservedStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeReservedStart"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPDataElementTypeReservedStart",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpdataelementtypereservedstart"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeSignedInt": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeSignedInt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeSignedInt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeSignedInt"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPDataElementTypeSignedInt",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpdataelementtypesignedint"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeString"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPDataElementTypeString",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpdataelementtypestring"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeURL": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeURL"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPDataElementTypeURL",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpdataelementtypeurl"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeUUID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeUUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeUUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeUUID"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPDataElementTypeUUID",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpdataelementtypeuuid"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeUnsignedInt": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeUnsignedInt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeUnsignedInt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPDataElementTypeUnsignedInt"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPDataElementTypeUnsignedInt",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpdataelementtypeunsignedint"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeBoolean",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeDataElementAlternative",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeDataElementSequence",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeNil",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeReservedEnd",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeReservedStart",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeSignedInt",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeString",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeURL",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeUnsignedInt"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothSDPDataElementTypeUUID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPDataElementTypeUUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeBoolean",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeDataElementAlternative",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeDataElementSequence",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeNil",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeReservedEnd",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeReservedStart",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeSignedInt",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeString",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeURL",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPDataElementTypeUnsignedInt"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothSDPDataElementTypeUUID"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeUnsignedInt/title",
          "value": "kBluetoothSDPDataElementTypeUnsignedInt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeUnsignedInt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPDataElementTypeUnsignedInt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeDataElementAlternative/title",
          "value": "kBluetoothSDPDataElementTypeDataElementAlternative"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeDataElementAlternative/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPDataElementTypeDataElementAlternative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeDataElementSequence/title",
          "value": "kBluetoothSDPDataElementTypeDataElementSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeDataElementSequence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPDataElementTypeDataElementSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeBoolean/title",
          "value": "kBluetoothSDPDataElementTypeBoolean"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeBoolean/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPDataElementTypeBoolean"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeUUID/title",
          "value": "kBluetoothSDPDataElementTypeUUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeUUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPDataElementTypeUUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeString/title",
          "value": "kBluetoothSDPDataElementTypeString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPDataElementTypeString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeReservedEnd/title",
          "value": "kBluetoothSDPDataElementTypeReservedEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeReservedEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPDataElementTypeReservedEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeNil/title",
          "value": "kBluetoothSDPDataElementTypeNil"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeNil/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPDataElementTypeNil"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeURL/title",
          "value": "kBluetoothSDPDataElementTypeURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPDataElementTypeURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeSignedInt/title",
          "value": "kBluetoothSDPDataElementTypeSignedInt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeSignedInt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPDataElementTypeSignedInt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeReservedStart/title",
          "value": "kBluetoothSDPDataElementTypeReservedStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPDataElementTypeReservedStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPDataElementTypeReservedStart"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothsdpdataelementtypeuuid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothsdpdataelementtypeuuid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
