{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusNoCapacity"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BluetoothAMPDiscoverResponseControllerStatus@kBluetoothAMPManagerDiscoverResponseControllerStatusNoCapacity",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusNoCapacity"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@BluetoothAMPDiscoverResponseControllerStatus",
        "text": "BluetoothAMPDiscoverResponseControllerStatus"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusNoCapacity"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothAMPManagerDiscoverResponseControllerStatusNoCapacity"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusNoCapacity"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@BluetoothAMPDiscoverResponseControllerStatus",
              "text": "BluetoothAMPDiscoverResponseControllerStatus"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPDiscoverResponseControllerStatus",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampdiscoverresponsecontrollerstatus"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusBluetoothOnly": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusBluetoothOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPDiscoverResponseControllerStatus",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusBluetoothOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusBluetoothOnly"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerDiscoverResponseControllerStatusBluetoothOnly",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagerdiscoverresponsecontrollerstatusbluetoothonly"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusFullCapacity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusFullCapacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPDiscoverResponseControllerStatus",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusFullCapacity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusFullCapacity"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerDiscoverResponseControllerStatusFullCapacity",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagerdiscoverresponsecontrollerstatusfullcapacity"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusHighCapacity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusHighCapacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPDiscoverResponseControllerStatus",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusHighCapacity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusHighCapacity"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerDiscoverResponseControllerStatusHighCapacity",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagerdiscoverresponsecontrollerstatushighcapacity"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusLowCapacity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusLowCapacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPDiscoverResponseControllerStatus",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusLowCapacity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusLowCapacity"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerDiscoverResponseControllerStatusLowCapacity",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagerdiscoverresponsecontrollerstatuslowcapacity"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusMediumCapacity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusMediumCapacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPDiscoverResponseControllerStatus",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusMediumCapacity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusMediumCapacity"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerDiscoverResponseControllerStatusMediumCapacity",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagerdiscoverresponsecontrollerstatusmediumcapacity"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusNoCapacity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusNoCapacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPDiscoverResponseControllerStatus",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusNoCapacity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusNoCapacity"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerDiscoverResponseControllerStatusNoCapacity",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagerdiscoverresponsecontrollerstatusnocapacity"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusPoweredDown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusPoweredDown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPDiscoverResponseControllerStatus",
          "text": "BluetoothAMPDiscoverResponseControllerStatus"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusPoweredDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusPoweredDown"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerDiscoverResponseControllerStatusPoweredDown",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagerdiscoverresponsecontrollerstatuspowereddown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusBluetoothOnly",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusFullCapacity",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusHighCapacity",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusLowCapacity",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusMediumCapacity",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusPoweredDown"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothAMPManagerDiscoverResponseControllerStatusNoCapacity"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusNoCapacity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPDiscoverResponseControllerStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusBluetoothOnly",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusFullCapacity",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusHighCapacity",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusLowCapacity",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusMediumCapacity",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerDiscoverResponseControllerStatusPoweredDown"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusNoCapacity"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerDiscoverResponseControllerStatusPoweredDown/title",
          "value": "kBluetoothAMPManagerDiscoverResponseControllerStatusPoweredDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerDiscoverResponseControllerStatusPoweredDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusPoweredDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerDiscoverResponseControllerStatusNoCapacity/title",
          "value": "kBluetoothAMPManagerDiscoverResponseControllerStatusNoCapacity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerDiscoverResponseControllerStatusNoCapacity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusNoCapacity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerDiscoverResponseControllerStatusMediumCapacity/title",
          "value": "kBluetoothAMPManagerDiscoverResponseControllerStatusMediumCapacity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerDiscoverResponseControllerStatusMediumCapacity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusMediumCapacity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerDiscoverResponseControllerStatusBluetoothOnly/title",
          "value": "kBluetoothAMPManagerDiscoverResponseControllerStatusBluetoothOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerDiscoverResponseControllerStatusBluetoothOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusBluetoothOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerDiscoverResponseControllerStatusHighCapacity/title",
          "value": "kBluetoothAMPManagerDiscoverResponseControllerStatusHighCapacity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerDiscoverResponseControllerStatusHighCapacity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusHighCapacity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerDiscoverResponseControllerStatusLowCapacity/title",
          "value": "kBluetoothAMPManagerDiscoverResponseControllerStatusLowCapacity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerDiscoverResponseControllerStatusLowCapacity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusLowCapacity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerDiscoverResponseControllerStatusFullCapacity/title",
          "value": "kBluetoothAMPManagerDiscoverResponseControllerStatusFullCapacity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerDiscoverResponseControllerStatusFullCapacity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerDiscoverResponseControllerStatusFullCapacity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/title",
          "value": "BluetoothAMPDiscoverResponseControllerStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDiscoverResponseControllerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPDiscoverResponseControllerStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPDiscoverResponseControllerStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothampmanagerdiscoverresponsecontrollerstatusnocapacity"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothampmanagerdiscoverresponsecontrollerstatusnocapacity"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
