{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionQoS"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BluetoothL2CAPConfigurationOption@kBluetoothL2CAPConfigurationOptionQoS",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothL2CAPConfigurationOptionQoS"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@BluetoothL2CAPConfigurationOption",
        "text": "BluetoothL2CAPConfigurationOption"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothL2CAPConfigurationOptionQoS"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothL2CAPConfigurationOptionQoS"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConfigurationOptionQoS"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@BluetoothL2CAPConfigurationOption",
              "text": "BluetoothL2CAPConfigurationOption"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationOption"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothL2CAPConfigurationOption"
        }
      ],
      "role": "symbol",
      "title": "BluetoothL2CAPConfigurationOption",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothl2capconfigurationoption"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionExtendedFlowSpecification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionExtendedFlowSpecification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPConfigurationOption",
          "text": "BluetoothL2CAPConfigurationOption"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionExtendedFlowSpecification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionExtendedFlowSpecification"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPConfigurationOptionExtendedFlowSpecification",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capconfigurationoptionextendedflowspecification"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionExtendedWindowSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionExtendedWindowSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPConfigurationOption",
          "text": "BluetoothL2CAPConfigurationOption"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionExtendedWindowSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionExtendedWindowSize"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPConfigurationOptionExtendedWindowSize",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capconfigurationoptionextendedwindowsize"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionFlushTimeout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionFlushTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPConfigurationOption",
          "text": "BluetoothL2CAPConfigurationOption"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionFlushTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionFlushTimeout"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPConfigurationOptionFlushTimeout",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capconfigurationoptionflushtimeout"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionFrameCheckSequence": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionFrameCheckSequence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPConfigurationOption",
          "text": "BluetoothL2CAPConfigurationOption"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionFrameCheckSequence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionFrameCheckSequence"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPConfigurationOptionFrameCheckSequence",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capconfigurationoptionframechecksequence"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionMTU": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionMTU"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPConfigurationOption",
          "text": "BluetoothL2CAPConfigurationOption"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionMTU",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionMTU"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPConfigurationOptionMTU",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capconfigurationoptionmtu"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionQoS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionQoS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPConfigurationOption",
          "text": "BluetoothL2CAPConfigurationOption"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionQoS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionQoS"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPConfigurationOptionQoS",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capconfigurationoptionqos"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControl": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothL2CAPConfigurationOption",
          "text": "BluetoothL2CAPConfigurationOption"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControl"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControl",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothl2capconfigurationoptionretransmissionandflowcontrol"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionExtendedFlowSpecification",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionExtendedWindowSize",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionFlushTimeout",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionFrameCheckSequence",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionMTU",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControl"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothL2CAPConfigurationOptionQoS"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConfigurationOptionQoS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothL2CAPConfigurationOption"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionExtendedFlowSpecification",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionExtendedWindowSize",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionFlushTimeout",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionFrameCheckSequence",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionMTU",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControl"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothL2CAPConfigurationOptionQoS"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionFlushTimeout/title",
          "value": "kBluetoothL2CAPConfigurationOptionFlushTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionFlushTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConfigurationOptionFlushTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionQoS/title",
          "value": "kBluetoothL2CAPConfigurationOptionQoS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionQoS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConfigurationOptionQoS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionMTU/title",
          "value": "kBluetoothL2CAPConfigurationOptionMTU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionMTU/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConfigurationOptionMTU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionExtendedFlowSpecification/title",
          "value": "kBluetoothL2CAPConfigurationOptionExtendedFlowSpecification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionExtendedFlowSpecification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConfigurationOptionExtendedFlowSpecification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionFrameCheckSequence/title",
          "value": "kBluetoothL2CAPConfigurationOptionFrameCheckSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionFrameCheckSequence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConfigurationOptionFrameCheckSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationOption/title",
          "value": "BluetoothL2CAPConfigurationOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothL2CAPConfigurationOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothL2CAPConfigurationOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionExtendedWindowSize/title",
          "value": "kBluetoothL2CAPConfigurationOptionExtendedWindowSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionExtendedWindowSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConfigurationOptionExtendedWindowSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControl/title",
          "value": "kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothL2CAPConfigurationOptionRetransmissionAndFlowControl"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothl2capconfigurationoptionqos"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothl2capconfigurationoptionqos"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
