{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericDisplay"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kBluetoothGAPAppearanceUnknown@kBluetoothGAPAppearanceGenericDisplay",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothGAPAppearanceGenericDisplay"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothGAPAppearanceGenericDisplay"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothGAPAppearanceGenericDisplay"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericDisplay"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericBarcodeScanner": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericBarcodeScanner"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericBarcodeScanner",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericBarcodeScanner"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericBarcodeScanner",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericbarcodescanner"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericBloodPressure": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericBloodPressure"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericBloodPressure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericBloodPressure"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericBloodPressure",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericbloodpressure"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericClock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericClock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericClock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericClock"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericClock",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericclock"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericComputer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericComputer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericComputer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericComputer"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericComputer",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericcomputer"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericCycling": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericCycling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericCycling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericCycling"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericCycling",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericcycling"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericDisplay": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericDisplay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericDisplay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericDisplay"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericDisplay",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericdisplay"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericEyeGlasses": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericEyeGlasses"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericEyeGlasses",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericEyeGlasses"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericEyeGlasses",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericeyeglasses"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericGlucoseMeter": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericGlucoseMeter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericGlucoseMeter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericGlucoseMeter"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericGlucoseMeter",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericglucosemeter"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericHeartrateSensor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericHeartrateSensor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericHeartrateSensor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericHeartrateSensor"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericHeartrateSensor",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericheartratesensor"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericHumanInterfaceDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericHumanInterfaceDevice"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericHumanInterfaceDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericHumanInterfaceDevice"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericHumanInterfaceDevice",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenerichumaninterfacedevice"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericKeyring": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericKeyring"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericKeyring",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericKeyring"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericKeyring",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenerickeyring"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericMediaPlayer": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericMediaPlayer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericMediaPlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericMediaPlayer"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericMediaPlayer",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericmediaplayer"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericPhone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericPhone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericPhone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericPhone"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericPhone",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericphone"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericRemoteControl": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericRemoteControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericRemoteControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericRemoteControl"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericRemoteControl",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericremotecontrol"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericRunningWalkingSensor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericRunningWalkingSensor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericRunningWalkingSensor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericRunningWalkingSensor"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericRunningWalkingSensor",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenericrunningwalkingsensor"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericTag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothGAPAppearanceGenericTag"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothGAPAppearanceGenericTag",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothgapappearancegenerictag"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericBarcodeScanner",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericBloodPressure",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericClock",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericComputer",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericCycling",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericEyeGlasses",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericGlucoseMeter",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericHeartrateSensor",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericHumanInterfaceDevice",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericKeyring",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericMediaPlayer",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericPhone",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericRemoteControl",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericRunningWalkingSensor",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericTag"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothGAPAppearanceGenericDisplay"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericBarcodeScanner",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericBloodPressure",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericClock",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericComputer",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericCycling",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericEyeGlasses",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericGlucoseMeter",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericHeartrateSensor",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericHumanInterfaceDevice",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericKeyring",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericMediaPlayer",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericPhone",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericRemoteControl",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericRunningWalkingSensor",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothGAPAppearanceGenericTag"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothGAPAppearanceGenericDisplay"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericGlucoseMeter/title",
          "value": "kBluetoothGAPAppearanceGenericGlucoseMeter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericGlucoseMeter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericGlucoseMeter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericBarcodeScanner/title",
          "value": "kBluetoothGAPAppearanceGenericBarcodeScanner"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericBarcodeScanner/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericBarcodeScanner"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericCycling/title",
          "value": "kBluetoothGAPAppearanceGenericCycling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericCycling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericCycling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericHeartrateSensor/title",
          "value": "kBluetoothGAPAppearanceGenericHeartrateSensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericHeartrateSensor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericHeartrateSensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericEyeGlasses/title",
          "value": "kBluetoothGAPAppearanceGenericEyeGlasses"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericEyeGlasses/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericEyeGlasses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericKeyring/title",
          "value": "kBluetoothGAPAppearanceGenericKeyring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericKeyring/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericKeyring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericRunningWalkingSensor/title",
          "value": "kBluetoothGAPAppearanceGenericRunningWalkingSensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericRunningWalkingSensor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericRunningWalkingSensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericHumanInterfaceDevice/title",
          "value": "kBluetoothGAPAppearanceGenericHumanInterfaceDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericHumanInterfaceDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericHumanInterfaceDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericComputer/title",
          "value": "kBluetoothGAPAppearanceGenericComputer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericComputer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericComputer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericClock/title",
          "value": "kBluetoothGAPAppearanceGenericClock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericClock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericClock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericMediaPlayer/title",
          "value": "kBluetoothGAPAppearanceGenericMediaPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericMediaPlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericMediaPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericPhone/title",
          "value": "kBluetoothGAPAppearanceGenericPhone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericPhone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericPhone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericBloodPressure/title",
          "value": "kBluetoothGAPAppearanceGenericBloodPressure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericBloodPressure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericBloodPressure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericRemoteControl/title",
          "value": "kBluetoothGAPAppearanceGenericRemoteControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericRemoteControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericRemoteControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericDisplay/title",
          "value": "kBluetoothGAPAppearanceGenericDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericDisplay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericTag/title",
          "value": "kBluetoothGAPAppearanceGenericTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothGAPAppearanceGenericTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothGAPAppearanceGenericTag"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothgapappearancegenericdisplay"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothgapappearancegenericdisplay"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
