{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@BluetoothAMPManagerCode@kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
        "text": "BluetoothAMPManagerCode"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
              "text": "BluetoothAMPManagerCode"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAMPManagerCode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothampmanagercode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPChangeNotify": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPChangeNotify"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPChangeNotify",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPChangeNotify"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPChangeNotify",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampchangenotify"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPChangeResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPChangeResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPChangeResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPChangeResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPChangeResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampchangeresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCommandReject": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPCommandReject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCommandReject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPCommandReject"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPCommandReject",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampcommandreject"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampcreatephysicallinkrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampcreatephysicallinkresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampdisconnectphysicallinkrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampdisconnectphysicallinkresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDiscoverRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPDiscoverRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDiscoverRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPDiscoverRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPDiscoverRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampdiscoverrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDiscoverResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPDiscoverResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDiscoverResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPDiscoverResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPDiscoverResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampdiscoverresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetAssocRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPGetAssocRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetAssocRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPGetAssocRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPGetAssocRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampgetassocrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetAssocResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPGetAssocResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetAssocResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPGetAssocResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPGetAssocResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampgetassocresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetInfoRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPGetInfoRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetInfoRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPGetInfoRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPGetInfoRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampgetinforequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetInfoResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPGetInfoResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetInfoResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeAMPGetInfoResponse"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeAMPGetInfoResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodeampgetinforesponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeReserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeReserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BluetoothAMPManagerCode",
          "text": "BluetoothAMPManagerCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeReserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothAMPManagerCodeReserved"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothAMPManagerCodeReserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothampmanagercodereserved"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPChangeNotify",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPChangeResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCommandReject",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDiscoverRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDiscoverResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetAssocRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetAssocResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetInfoRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetInfoResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeReserved"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAMPManagerCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPChangeNotify",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPChangeResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCommandReject",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDiscoverRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPDiscoverResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetAssocRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetAssocResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetInfoRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeAMPGetInfoResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothAMPManagerCodeReserved"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/title",
          "value": "BluetoothAMPManagerCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPManagerCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAMPManagerCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAMPManagerCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPDiscoverRequest/title",
          "value": "kBluetoothAMPManagerCodeAMPDiscoverRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPDiscoverRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPDiscoverRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPGetAssocResponse/title",
          "value": "kBluetoothAMPManagerCodeAMPGetAssocResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPGetAssocResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPGetAssocResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPChangeResponse/title",
          "value": "kBluetoothAMPManagerCodeAMPChangeResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPChangeResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPChangeResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPGetInfoResponse/title",
          "value": "kBluetoothAMPManagerCodeAMPGetInfoResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPGetInfoResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPGetInfoResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse/title",
          "value": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest/title",
          "value": "kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPCreatePhysicalLinkRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest/title",
          "value": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPDisconnectPhysicalLinkRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPGetInfoRequest/title",
          "value": "kBluetoothAMPManagerCodeAMPGetInfoRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPGetInfoRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPGetInfoRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPChangeNotify/title",
          "value": "kBluetoothAMPManagerCodeAMPChangeNotify"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPChangeNotify/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPChangeNotify"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeReserved/title",
          "value": "kBluetoothAMPManagerCodeReserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeReserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeReserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPGetAssocRequest/title",
          "value": "kBluetoothAMPManagerCodeAMPGetAssocRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPGetAssocRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPGetAssocRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPCommandReject/title",
          "value": "kBluetoothAMPManagerCodeAMPCommandReject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPCommandReject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPCommandReject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse/title",
          "value": "kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPCreatePhysicalLinkResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPDiscoverResponse/title",
          "value": "kBluetoothAMPManagerCodeAMPDiscoverResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothAMPManagerCodeAMPDiscoverResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothAMPManagerCodeAMPDiscoverResponse"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothampmanagercodeampdisconnectphysicallinkrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothampmanagercodeampdisconnectphysicallinkrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
