{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassPhonebookAccess"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SDPServiceClasses@kBluetoothSDPUUID16ServiceClassPhonebookAccess",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothSDPUUID16ServiceClassPhonebookAccess"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SDPServiceClasses",
        "text": "SDPServiceClasses"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothSDPUUID16ServiceClassPhonebookAccess"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothSDPUUID16ServiceClassPhonebookAccess"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16ServiceClassPhonebookAccess"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/SDPServiceClasses",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SDPServiceClasses",
              "text": "SDPServiceClasses"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/SDPServiceClasses": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SDPServiceClasses"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/SDPServiceClasses",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SDPServiceClasses"
        }
      ],
      "role": "symbol",
      "title": "SDPServiceClasses",
      "type": "topic",
      "url": "/documentation/iobluetooth/sdpserviceclasses"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAVRemoteControl": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassAVRemoteControl"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPServiceClasses",
          "text": "SDPServiceClasses"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAVRemoteControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassAVRemoteControl"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16ServiceClassAVRemoteControl",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16serviceclassavremotecontrol"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAVRemoteControlController": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassAVRemoteControlController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPServiceClasses",
          "text": "SDPServiceClasses"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAVRemoteControlController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassAVRemoteControlController"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16ServiceClassAVRemoteControlController",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16serviceclassavremotecontrolcontroller"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAVRemoteControlTarget": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassAVRemoteControlTarget"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPServiceClasses",
          "text": "SDPServiceClasses"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAVRemoteControlTarget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassAVRemoteControlTarget"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16ServiceClassAVRemoteControlTarget",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16serviceclassavremotecontroltarget"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAdvancedAudioDistribution": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassAdvancedAudioDistribution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPServiceClasses",
          "text": "SDPServiceClasses"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAdvancedAudioDistribution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassAdvancedAudioDistribution"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16ServiceClassAdvancedAudioDistribution",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16serviceclassadvancedaudiodistribution"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAudioSink": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassAudioSink"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPServiceClasses",
          "text": "SDPServiceClasses"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAudioSink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassAudioSink"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16ServiceClassAudioSink",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16serviceclassaudiosink"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAudioSource": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassAudioSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPServiceClasses",
          "text": "SDPServiceClasses"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAudioSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassAudioSource"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16ServiceClassAudioSource",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16serviceclassaudiosource"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAudioVideo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassAudioVideo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPServiceClasses",
          "text": "SDPServiceClasses"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAudioVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassAudioVideo"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16ServiceClassAudioVideo",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16serviceclassaudiovideo"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassBasicPrinting": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassBasicPrinting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPServiceClasses",
          "text": "SDPServiceClasses"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassBasicPrinting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassBasicPrinting"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16ServiceClassBasicPrinting",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16serviceclassbasicprinting"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassBrowseGroupDescriptor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassBrowseGroupDescriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPServiceClasses",
          "text": "SDPServiceClasses"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassBrowseGroupDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassBrowseGroupDescriptor"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16ServiceClassBrowseGroupDescriptor",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16serviceclassbrowsegroupdescriptor"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassCommonISDNAccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassCommonISDNAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPServiceClasses",
          "text": "SDPServiceClasses"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassCommonISDNAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassCommonISDNAccess"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16ServiceClassCommonISDNAccess",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16serviceclasscommonisdnaccess"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassCordlessTelephony": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassCordlessTelephony"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPServiceClasses",
          "text": "SDPServiceClasses"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassCordlessTelephony",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassCordlessTelephony"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16ServiceClassCordlessTelephony",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16serviceclasscordlesstelephony"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassDialupNetworking": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassDialupNetworking"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPServiceClasses",
          "text": "SDPServiceClasses"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassDialupNetworking",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassDialupNetworking"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16ServiceClassDialupNetworking",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16serviceclassdialupnetworking"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassDirectPrinting": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassDirectPrinting"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPServiceClasses",
          "text": "SDPServiceClasses"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassDirectPrinting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassDirectPrinting"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16ServiceClassDirectPrinting",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16serviceclassdirectprinting"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassDirectPrintingReferenceObjectsService": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassDirectPrintingReferenceObjectsService"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPServiceClasses",
          "text": "SDPServiceClasses"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassDirectPrintingReferenceObjectsService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassDirectPrintingReferenceObjectsService"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16ServiceClassDirectPrintingReferenceObjectsService",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16serviceclassdirectprintingreferenceobjectsservice"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassFax": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassFax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPServiceClasses",
          "text": "SDPServiceClasses"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassFax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassFax"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16ServiceClassFax",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16serviceclassfax"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassPhonebookAccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassPhonebookAccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SDPServiceClasses",
          "text": "SDPServiceClasses"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassPhonebookAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothSDPUUID16ServiceClassPhonebookAccess"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothSDPUUID16ServiceClassPhonebookAccess",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothsdpuuid16serviceclassphonebookaccess"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAVRemoteControl",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAVRemoteControlController",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAVRemoteControlTarget",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAdvancedAudioDistribution",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAudioSink",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAudioSource",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAudioVideo",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassBasicPrinting",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassBrowseGroupDescriptor",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassCommonISDNAccess",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassCordlessTelephony",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassDialupNetworking",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassDirectPrinting",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassDirectPrintingReferenceObjectsService",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassFax"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothSDPUUID16ServiceClassPhonebookAccess"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16ServiceClassPhonebookAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/SDPServiceClasses"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAVRemoteControl",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAVRemoteControlController",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAVRemoteControlTarget",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAdvancedAudioDistribution",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAudioSink",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAudioSource",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassAudioVideo",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassBasicPrinting",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassBrowseGroupDescriptor",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassCommonISDNAccess",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassCordlessTelephony",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassDialupNetworking",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassDirectPrinting",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassDirectPrintingReferenceObjectsService",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothSDPUUID16ServiceClassFax"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothSDPUUID16ServiceClassPhonebookAccess"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassPhonebookAccess/title",
          "value": "kBluetoothSDPUUID16ServiceClassPhonebookAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassPhonebookAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16ServiceClassPhonebookAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassAudioVideo/title",
          "value": "kBluetoothSDPUUID16ServiceClassAudioVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassAudioVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16ServiceClassAudioVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassCommonISDNAccess/title",
          "value": "kBluetoothSDPUUID16ServiceClassCommonISDNAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassCommonISDNAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16ServiceClassCommonISDNAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassAudioSource/title",
          "value": "kBluetoothSDPUUID16ServiceClassAudioSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassAudioSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16ServiceClassAudioSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassAudioSink/title",
          "value": "kBluetoothSDPUUID16ServiceClassAudioSink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassAudioSink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16ServiceClassAudioSink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1SDPServiceClasses/title",
          "value": "SDPServiceClasses"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1SDPServiceClasses/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SDPServiceClasses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1SDPServiceClasses/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SDPServiceClasses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassFax/title",
          "value": "kBluetoothSDPUUID16ServiceClassFax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassFax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16ServiceClassFax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassBasicPrinting/title",
          "value": "kBluetoothSDPUUID16ServiceClassBasicPrinting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassBasicPrinting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16ServiceClassBasicPrinting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassAVRemoteControlController/title",
          "value": "kBluetoothSDPUUID16ServiceClassAVRemoteControlController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassAVRemoteControlController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16ServiceClassAVRemoteControlController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassAVRemoteControlTarget/title",
          "value": "kBluetoothSDPUUID16ServiceClassAVRemoteControlTarget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassAVRemoteControlTarget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16ServiceClassAVRemoteControlTarget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassAVRemoteControl/title",
          "value": "kBluetoothSDPUUID16ServiceClassAVRemoteControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassAVRemoteControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16ServiceClassAVRemoteControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassBrowseGroupDescriptor/title",
          "value": "kBluetoothSDPUUID16ServiceClassBrowseGroupDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassBrowseGroupDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16ServiceClassBrowseGroupDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassDirectPrinting/title",
          "value": "kBluetoothSDPUUID16ServiceClassDirectPrinting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassDirectPrinting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16ServiceClassDirectPrinting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassCordlessTelephony/title",
          "value": "kBluetoothSDPUUID16ServiceClassCordlessTelephony"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassCordlessTelephony/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16ServiceClassCordlessTelephony"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassDialupNetworking/title",
          "value": "kBluetoothSDPUUID16ServiceClassDialupNetworking"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassDialupNetworking/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16ServiceClassDialupNetworking"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassAdvancedAudioDistribution/title",
          "value": "kBluetoothSDPUUID16ServiceClassAdvancedAudioDistribution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassAdvancedAudioDistribution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16ServiceClassAdvancedAudioDistribution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassDirectPrintingReferenceObjectsService/title",
          "value": "kBluetoothSDPUUID16ServiceClassDirectPrintingReferenceObjectsService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothSDPUUID16ServiceClassDirectPrintingReferenceObjectsService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothSDPUUID16ServiceClassDirectPrintingReferenceObjectsService"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothsdpuuid16serviceclassphonebookaccess"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothsdpuuid16serviceclassphonebookaccess"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
