{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandCreateNewUnitKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kBluetoothHCIOpCodeNoOp@kBluetoothHCICommandCreateNewUnitKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothHCICommandCreateNewUnitKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothHCICommandCreateNewUnitKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothHCICommandCreateNewUnitKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothHCICommandCreateNewUnitKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAMPTest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandAMPTest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAMPTest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandAMPTest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCICommandAMPTest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcicommandamptest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAMPTestEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandAMPTestEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAMPTestEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandAMPTestEnd"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCICommandAMPTestEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcicommandamptestend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAcceptConnectionRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandAcceptConnectionRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAcceptConnectionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandAcceptConnectionRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCICommandAcceptConnectionRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcicommandacceptconnectionrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAcceptSniffRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandAcceptSniffRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAcceptSniffRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandAcceptSniffRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCICommandAcceptSniffRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcicommandacceptsniffrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAcceptSynchronousConnectionRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandAcceptSynchronousConnectionRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAcceptSynchronousConnectionRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandAcceptSynchronousConnectionRequest"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCICommandAcceptSynchronousConnectionRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcicommandacceptsynchronousconnectionrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAddSCOConnection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandAddSCOConnection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAddSCOConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandAddSCOConnection"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCICommandAddSCOConnection",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcicommandaddscoconnection"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAuthenticationRequested": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandAuthenticationRequested"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAuthenticationRequested",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandAuthenticationRequested"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCICommandAuthenticationRequested",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcicommandauthenticationrequested"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandChangeConnectionLinkKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandChangeConnectionLinkKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandChangeConnectionLinkKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandChangeConnectionLinkKey"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCICommandChangeConnectionLinkKey",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcicommandchangeconnectionlinkkey"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandChangeConnectionPacketType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandChangeConnectionPacketType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandChangeConnectionPacketType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandChangeConnectionPacketType"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCICommandChangeConnectionPacketType",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcicommandchangeconnectionpackettype"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandChangeLocalName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandChangeLocalName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandChangeLocalName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandChangeLocalName"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCICommandChangeLocalName",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcicommandchangelocalname"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandCreateConnection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandCreateConnection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandCreateConnection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandCreateConnection"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCICommandCreateConnection",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcicommandcreateconnection"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandCreateConnectionCancel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandCreateConnectionCancel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandCreateConnectionCancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandCreateConnectionCancel"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCICommandCreateConnectionCancel",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcicommandcreateconnectioncancel"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandCreateNewUnitKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandCreateNewUnitKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandCreateNewUnitKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandCreateNewUnitKey"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCICommandCreateNewUnitKey",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcicommandcreatenewunitkey"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandDeleteReservedLTADDR": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandDeleteReservedLTADDR"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandDeleteReservedLTADDR",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandDeleteReservedLTADDR"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCICommandDeleteReservedLTADDR",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcicommanddeletereservedltaddr"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandDeleteStoredLinkKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandDeleteStoredLinkKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandDeleteStoredLinkKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandDeleteStoredLinkKey"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCICommandDeleteStoredLinkKey",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcicommanddeletestoredlinkkey"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandDisconnect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandDisconnect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandDisconnect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothHCICommandDisconnect"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothHCICommandDisconnect",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothhcicommanddisconnect"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAMPTest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAMPTestEnd",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAcceptConnectionRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAcceptSniffRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAcceptSynchronousConnectionRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAddSCOConnection",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAuthenticationRequested",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandChangeConnectionLinkKey",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandChangeConnectionPacketType",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandChangeLocalName",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandCreateConnection",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandCreateConnectionCancel",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandDeleteReservedLTADDR",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandDeleteStoredLinkKey",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandDisconnect"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothHCICommandCreateNewUnitKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCICommandCreateNewUnitKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAMPTest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAMPTestEnd",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAcceptConnectionRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAcceptSniffRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAcceptSynchronousConnectionRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAddSCOConnection",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandAuthenticationRequested",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandChangeConnectionLinkKey",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandChangeConnectionPacketType",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandChangeLocalName",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandCreateConnection",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandCreateConnectionCancel",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandDeleteReservedLTADDR",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandDeleteStoredLinkKey",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothHCICommandDisconnect"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothHCICommandCreateNewUnitKey"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandAddSCOConnection/title",
          "value": "kBluetoothHCICommandAddSCOConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandAddSCOConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCICommandAddSCOConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandCreateConnectionCancel/title",
          "value": "kBluetoothHCICommandCreateConnectionCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandCreateConnectionCancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCICommandCreateConnectionCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandCreateNewUnitKey/title",
          "value": "kBluetoothHCICommandCreateNewUnitKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandCreateNewUnitKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCICommandCreateNewUnitKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandDeleteStoredLinkKey/title",
          "value": "kBluetoothHCICommandDeleteStoredLinkKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandDeleteStoredLinkKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCICommandDeleteStoredLinkKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandChangeConnectionPacketType/title",
          "value": "kBluetoothHCICommandChangeConnectionPacketType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandChangeConnectionPacketType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCICommandChangeConnectionPacketType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandDisconnect/title",
          "value": "kBluetoothHCICommandDisconnect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandDisconnect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCICommandDisconnect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandAMPTest/title",
          "value": "kBluetoothHCICommandAMPTest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandAMPTest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCICommandAMPTest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandAMPTestEnd/title",
          "value": "kBluetoothHCICommandAMPTestEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandAMPTestEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCICommandAMPTestEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandDeleteReservedLTADDR/title",
          "value": "kBluetoothHCICommandDeleteReservedLTADDR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandDeleteReservedLTADDR/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCICommandDeleteReservedLTADDR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandAuthenticationRequested/title",
          "value": "kBluetoothHCICommandAuthenticationRequested"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandAuthenticationRequested/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCICommandAuthenticationRequested"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandAcceptSniffRequest/title",
          "value": "kBluetoothHCICommandAcceptSniffRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandAcceptSniffRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCICommandAcceptSniffRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandCreateConnection/title",
          "value": "kBluetoothHCICommandCreateConnection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandCreateConnection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCICommandCreateConnection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandAcceptConnectionRequest/title",
          "value": "kBluetoothHCICommandAcceptConnectionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandAcceptConnectionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCICommandAcceptConnectionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandAcceptSynchronousConnectionRequest/title",
          "value": "kBluetoothHCICommandAcceptSynchronousConnectionRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandAcceptSynchronousConnectionRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCICommandAcceptSynchronousConnectionRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandChangeConnectionLinkKey/title",
          "value": "kBluetoothHCICommandChangeConnectionLinkKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandChangeConnectionLinkKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCICommandChangeConnectionLinkKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandChangeLocalName/title",
          "value": "kBluetoothHCICommandChangeLocalName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothHCICommandChangeLocalName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothHCICommandChangeLocalName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothhcicommandcreatenewunitkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothhcicommandcreatenewunitkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
