{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferTimeKeepingSystems"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@BluetoothCompanyIdentifers@kBluetoothCompanyIdentiferTimeKeepingSystems",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kBluetoothCompanyIdentiferTimeKeepingSystems"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@BluetoothCompanyIdentifers",
        "text": "BluetoothCompanyIdentifers"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kBluetoothCompanyIdentiferTimeKeepingSystems"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kBluetoothCompanyIdentiferTimeKeepingSystems"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kBluetoothCompanyIdentiferTimeKeepingSystems"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@BluetoothCompanyIdentifers",
              "text": "BluetoothCompanyIdentifers"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "role": "symbol",
      "title": "BluetoothCompanyIdentifers",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothcompanyidentifers"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentifer3Com": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentifer3Com"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothCompanyIdentifers",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentifer3Com",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentifer3Com"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothCompanyIdentifer3Com",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothcompanyidentifer3com"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentifer3DSP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentifer3DSP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothCompanyIdentifers",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentifer3DSP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentifer3DSP"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothCompanyIdentifer3DSP",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothcompanyidentifer3dsp"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentifer3DiJoy": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentifer3DiJoy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothCompanyIdentifers",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentifer3DiJoy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentifer3DiJoy"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothCompanyIdentifer3DiJoy",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothcompanyidentifer3dijoy"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAPT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferAPT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothCompanyIdentifers",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAPT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferAPT"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothCompanyIdentiferAPT",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothcompanyidentiferapt"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAVMBerlin": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferAVMBerlin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothCompanyIdentifers",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAVMBerlin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferAVMBerlin"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothCompanyIdentiferAVMBerlin",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothcompanyidentiferavmberlin"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAccelSemiconductor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferAccelSemiconductor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothCompanyIdentifers",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAccelSemiconductor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferAccelSemiconductor"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothCompanyIdentiferAccelSemiconductor",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothcompanyidentiferaccelsemiconductor"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAlcatel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferAlcatel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothCompanyIdentifers",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAlcatel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferAlcatel"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothCompanyIdentiferAlcatel",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothcompanyidentiferalcatel"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferApple": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferApple"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothCompanyIdentifers",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferApple",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferApple"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothCompanyIdentiferApple",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothcompanyidentiferapple"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAtherosCommunications": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferAtherosCommunications"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothCompanyIdentifers",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAtherosCommunications",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferAtherosCommunications"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothCompanyIdentiferAtherosCommunications",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothcompanyidentiferatheroscommunications"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAtmel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferAtmel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothCompanyIdentifers",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAtmel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferAtmel"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothCompanyIdentiferAtmel",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothcompanyidentiferatmel"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAvagoTechnologies": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferAvagoTechnologies"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothCompanyIdentifers",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAvagoTechnologies",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferAvagoTechnologies"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothCompanyIdentiferAvagoTechnologies",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothcompanyidentiferavagotechnologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferBandspeed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferBandspeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothCompanyIdentifers",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferBandspeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferBandspeed"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothCompanyIdentiferBandspeed",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothcompanyidentiferbandspeed"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferBluegiga": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferBluegiga"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothCompanyIdentifers",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferBluegiga",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferBluegiga"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothCompanyIdentiferBluegiga",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothcompanyidentiferbluegiga"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferBluetoothSIG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferBluetoothSIG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothCompanyIdentifers",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferBluetoothSIG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferBluetoothSIG"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothCompanyIdentiferBluetoothSIG",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothcompanyidentiferbluetoothsig"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferBroadcom": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferBroadcom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothCompanyIdentifers",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferBroadcom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferBroadcom"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothCompanyIdentiferBroadcom",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothcompanyidentiferbroadcom"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferTimeKeepingSystems": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferTimeKeepingSystems"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothCompanyIdentifers",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferTimeKeepingSystems",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBluetoothCompanyIdentiferTimeKeepingSystems"
        }
      ],
      "role": "symbol",
      "title": "kBluetoothCompanyIdentiferTimeKeepingSystems",
      "type": "topic",
      "url": "/documentation/iobluetooth/kbluetoothcompanyidentifertimekeepingsystems"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentifer3Com",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentifer3DSP",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentifer3DiJoy",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAPT",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAVMBerlin",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAccelSemiconductor",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAlcatel",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferApple",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAtherosCommunications",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAtmel",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAvagoTechnologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferBandspeed",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferBluegiga",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferBluetoothSIG",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferBroadcom"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kBluetoothCompanyIdentiferTimeKeepingSystems"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothCompanyIdentiferTimeKeepingSystems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentifer3Com",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentifer3DSP",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentifer3DiJoy",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAPT",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAVMBerlin",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAccelSemiconductor",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAlcatel",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferApple",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAtherosCommunications",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAtmel",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferAvagoTechnologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferBandspeed",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferBluegiga",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferBluetoothSIG",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kBluetoothCompanyIdentiferBroadcom"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kBluetoothCompanyIdentiferTimeKeepingSystems"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentifer3DiJoy/title",
          "value": "kBluetoothCompanyIdentifer3DiJoy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentifer3DiJoy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothCompanyIdentifer3DiJoy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferAlcatel/title",
          "value": "kBluetoothCompanyIdentiferAlcatel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferAlcatel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothCompanyIdentiferAlcatel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferAvagoTechnologies/title",
          "value": "kBluetoothCompanyIdentiferAvagoTechnologies"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferAvagoTechnologies/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothCompanyIdentiferAvagoTechnologies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferAtmel/title",
          "value": "kBluetoothCompanyIdentiferAtmel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferAtmel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothCompanyIdentiferAtmel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferBluetoothSIG/title",
          "value": "kBluetoothCompanyIdentiferBluetoothSIG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferBluetoothSIG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothCompanyIdentiferBluetoothSIG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferBroadcom/title",
          "value": "kBluetoothCompanyIdentiferBroadcom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferBroadcom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothCompanyIdentiferBroadcom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferApple/title",
          "value": "kBluetoothCompanyIdentiferApple"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferApple/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothCompanyIdentiferApple"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/title",
          "value": "BluetoothCompanyIdentifers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothCompanyIdentifers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothCompanyIdentifers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferBandspeed/title",
          "value": "kBluetoothCompanyIdentiferBandspeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferBandspeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothCompanyIdentiferBandspeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferAPT/title",
          "value": "kBluetoothCompanyIdentiferAPT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferAPT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothCompanyIdentiferAPT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferTimeKeepingSystems/title",
          "value": "kBluetoothCompanyIdentiferTimeKeepingSystems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferTimeKeepingSystems/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothCompanyIdentiferTimeKeepingSystems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentifer3DSP/title",
          "value": "kBluetoothCompanyIdentifer3DSP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentifer3DSP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothCompanyIdentifer3DSP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferBluegiga/title",
          "value": "kBluetoothCompanyIdentiferBluegiga"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferBluegiga/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothCompanyIdentiferBluegiga"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferAVMBerlin/title",
          "value": "kBluetoothCompanyIdentiferAVMBerlin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferAVMBerlin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothCompanyIdentiferAVMBerlin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentifer3Com/title",
          "value": "kBluetoothCompanyIdentifer3Com"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentifer3Com/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothCompanyIdentifer3Com"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferAtherosCommunications/title",
          "value": "kBluetoothCompanyIdentiferAtherosCommunications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferAtherosCommunications/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothCompanyIdentiferAtherosCommunications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferAccelSemiconductor/title",
          "value": "kBluetoothCompanyIdentiferAccelSemiconductor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kBluetoothCompanyIdentiferAccelSemiconductor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBluetoothCompanyIdentiferAccelSemiconductor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothcompanyidentifertimekeepingsystems"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kbluetoothcompanyidentifertimekeepingsystems"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
