{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kDisableAllLMModes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@BluetoothHCILinkPolicySettingsValues@kDisableAllLMModes",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kDisableAllLMModes"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@BluetoothHCILinkPolicySettingsValues",
        "text": "BluetoothHCILinkPolicySettingsValues"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kDisableAllLMModes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kDisableAllLMModes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kDisableAllLMModes"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCILinkPolicySettingsValues",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@BluetoothHCILinkPolicySettingsValues",
              "text": "BluetoothHCILinkPolicySettingsValues"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCILinkPolicySettingsValues": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCILinkPolicySettingsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCILinkPolicySettingsValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCILinkPolicySettingsValues"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCILinkPolicySettingsValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcilinkpolicysettingsvalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kDisableAllLMModes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kDisableAllLMModes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCILinkPolicySettingsValues",
          "text": "BluetoothHCILinkPolicySettingsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kDisableAllLMModes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kDisableAllLMModes"
        }
      ],
      "role": "symbol",
      "title": "kDisableAllLMModes",
      "type": "topic",
      "url": "/documentation/iobluetooth/kdisablealllmmodes"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEnableCentralPeripheralSwitch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kEnableCentralPeripheralSwitch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCILinkPolicySettingsValues",
          "text": "BluetoothHCILinkPolicySettingsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEnableCentralPeripheralSwitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kEnableCentralPeripheralSwitch"
        }
      ],
      "role": "symbol",
      "title": "kEnableCentralPeripheralSwitch",
      "type": "topic",
      "url": "/documentation/iobluetooth/kenablecentralperipheralswitch"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEnableHoldMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kEnableHoldMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCILinkPolicySettingsValues",
          "text": "BluetoothHCILinkPolicySettingsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEnableHoldMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kEnableHoldMode"
        }
      ],
      "role": "symbol",
      "title": "kEnableHoldMode",
      "type": "topic",
      "url": "/documentation/iobluetooth/kenableholdmode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEnableMasterSlaveSwitch": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kEnableMasterSlaveSwitch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCILinkPolicySettingsValues",
          "text": "BluetoothHCILinkPolicySettingsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEnableMasterSlaveSwitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kEnableMasterSlaveSwitch"
        }
      ],
      "role": "symbol",
      "title": "kEnableMasterSlaveSwitch",
      "type": "topic",
      "url": "/documentation/iobluetooth/kenablemasterslaveswitch"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEnableParkMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kEnableParkMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCILinkPolicySettingsValues",
          "text": "BluetoothHCILinkPolicySettingsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEnableParkMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kEnableParkMode"
        }
      ],
      "role": "symbol",
      "title": "kEnableParkMode",
      "type": "topic",
      "url": "/documentation/iobluetooth/kenableparkmode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEnableSniffMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kEnableSniffMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCILinkPolicySettingsValues",
          "text": "BluetoothHCILinkPolicySettingsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEnableSniffMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kEnableSniffMode"
        }
      ],
      "role": "symbol",
      "title": "kEnableSniffMode",
      "type": "topic",
      "url": "/documentation/iobluetooth/kenablesniffmode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kReservedForFutureUse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kReservedForFutureUse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCILinkPolicySettingsValues",
          "text": "BluetoothHCILinkPolicySettingsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kReservedForFutureUse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kReservedForFutureUse"
        }
      ],
      "role": "symbol",
      "title": "kReservedForFutureUse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kreservedforfutureuse"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEnableHoldMode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEnableMasterSlaveSwitch",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEnableParkMode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEnableSniffMode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kReservedForFutureUse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEnableCentralPeripheralSwitch"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kDisableAllLMModes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDisableAllLMModes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCILinkPolicySettingsValues"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEnableHoldMode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEnableMasterSlaveSwitch",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEnableParkMode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEnableSniffMode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kReservedForFutureUse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEnableCentralPeripheralSwitch"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kDisableAllLMModes"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kEnableMasterSlaveSwitch/title",
          "value": "kEnableMasterSlaveSwitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kEnableMasterSlaveSwitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kEnableMasterSlaveSwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kDisableAllLMModes/title",
          "value": "kDisableAllLMModes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kDisableAllLMModes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kDisableAllLMModes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCILinkPolicySettingsValues/title",
          "value": "BluetoothHCILinkPolicySettingsValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCILinkPolicySettingsValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCILinkPolicySettingsValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCILinkPolicySettingsValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCILinkPolicySettingsValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kReservedForFutureUse/title",
          "value": "kReservedForFutureUse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kReservedForFutureUse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kReservedForFutureUse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kEnableHoldMode/title",
          "value": "kEnableHoldMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kEnableHoldMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kEnableHoldMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kEnableSniffMode/title",
          "value": "kEnableSniffMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kEnableSniffMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kEnableSniffMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kEnableParkMode/title",
          "value": "kEnableParkMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kEnableParkMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kEnableParkMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kEnableCentralPeripheralSwitch/title",
          "value": "kEnableCentralPeripheralSwitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kEnableCentralPeripheralSwitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kEnableCentralPeripheralSwitch"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kdisablealllmmodes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kdisablealllmmodes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
