{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEncryptionDisabled"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@BluetoothHCIEncryptionModes@kEncryptionDisabled",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kEncryptionDisabled"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@BluetoothHCIEncryptionModes",
        "text": "BluetoothHCIEncryptionModes"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kEncryptionDisabled"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kEncryptionDisabled"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kEncryptionDisabled"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEncryptionModes",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@BluetoothHCIEncryptionModes",
              "text": "BluetoothHCIEncryptionModes"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEncryptionModes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIEncryptionModes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEncryptionModes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIEncryptionModes"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIEncryptionModes",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhciencryptionmodes"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEncryptionDisabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kEncryptionDisabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCIEncryptionModes",
          "text": "BluetoothHCIEncryptionModes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEncryptionDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kEncryptionDisabled"
        }
      ],
      "role": "symbol",
      "title": "kEncryptionDisabled",
      "type": "topic",
      "url": "/documentation/iobluetooth/kencryptiondisabled"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEncryptionForBothPointToPointAndBroadcastPackets": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kEncryptionForBothPointToPointAndBroadcastPackets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCIEncryptionModes",
          "text": "BluetoothHCIEncryptionModes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEncryptionForBothPointToPointAndBroadcastPackets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kEncryptionForBothPointToPointAndBroadcastPackets"
        }
      ],
      "role": "symbol",
      "title": "kEncryptionForBothPointToPointAndBroadcastPackets",
      "type": "topic",
      "url": "/documentation/iobluetooth/kencryptionforbothpointtopointandbroadcastpackets"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEncryptionOnlyForPointToPointPackets": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kEncryptionOnlyForPointToPointPackets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BluetoothHCIEncryptionModes",
          "text": "BluetoothHCIEncryptionModes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEncryptionOnlyForPointToPointPackets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kEncryptionOnlyForPointToPointPackets"
        }
      ],
      "role": "symbol",
      "title": "kEncryptionOnlyForPointToPointPackets",
      "type": "topic",
      "url": "/documentation/iobluetooth/kencryptiononlyforpointtopointpackets"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEncryptionForBothPointToPointAndBroadcastPackets",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEncryptionOnlyForPointToPointPackets"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kEncryptionDisabled"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kEncryptionDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIEncryptionModes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEncryptionForBothPointToPointAndBroadcastPackets",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kEncryptionOnlyForPointToPointPackets"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kEncryptionDisabled"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEncryptionModes/title",
          "value": "BluetoothHCIEncryptionModes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEncryptionModes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIEncryptionModes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIEncryptionModes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIEncryptionModes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kEncryptionOnlyForPointToPointPackets/title",
          "value": "kEncryptionOnlyForPointToPointPackets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kEncryptionOnlyForPointToPointPackets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kEncryptionOnlyForPointToPointPackets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kEncryptionForBothPointToPointAndBroadcastPackets/title",
          "value": "kEncryptionForBothPointToPointAndBroadcastPackets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kEncryptionForBothPointToPointAndBroadcastPackets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kEncryptionForBothPointToPointAndBroadcastPackets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kEncryptionDisabled/title",
          "value": "kEncryptionDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kEncryptionDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kEncryptionDisabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kencryptiondisabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kencryptiondisabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
