{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothDeviceNameChangedNotification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@kIOBluetoothDeviceNameChangedNotification",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kIOBluetoothDeviceNameChangedNotification"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kIOBluetoothDeviceNameChangedNotification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kIOBluetoothDeviceNameChangedNotification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kIOBluetoothDeviceNameChangedNotification"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHostControllerPoweredOffNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHostControllerPoweredOffNotification"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHostControllerPoweredOffNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOBluetoothHostControllerPoweredOffNotification",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhostcontrollerpoweredoffnotification"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHostControllerPoweredOnNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHostControllerPoweredOnNotification"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHostControllerPoweredOnNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOBluetoothHostControllerPoweredOnNotification",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhostcontrollerpoweredonnotification"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelPublishedNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOBluetoothL2CAPChannelPublishedNotification"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelPublishedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOBluetoothL2CAPChannelPublishedNotification",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothl2capchannelpublishednotification"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelTerminatedNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOBluetoothL2CAPChannelTerminatedNotification"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelTerminatedNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOBluetoothL2CAPChannelTerminatedNotification",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothl2capchannelterminatednotification"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressPrecentageKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFTSProgressPrecentageKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressPrecentageKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFTSProgressPrecentageKey"
        }
      ],
      "role": "symbol",
      "title": "kFTSProgressPrecentageKey",
      "type": "topic",
      "url": "/documentation/iobluetooth/kftsprogressprecentagekey"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothDeviceNameChangedNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOBluetoothDeviceNameChangedNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothDeviceNameChangedNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOBluetoothDeviceNameChangedNotification"
        }
      ],
      "role": "symbol",
      "title": "kIOBluetoothDeviceNameChangedNotification",
      "type": "topic",
      "url": "/documentation/iobluetooth/kiobluetoothdevicenamechangednotification"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyAppParameters": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyAppParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyAppParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyAppParameters"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDKeyAppParameters",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidkeyappparameters"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyAuthorizationChallenge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyAuthorizationChallenge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyAuthorizationChallenge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyAuthorizationChallenge"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDKeyAuthorizationChallenge",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidkeyauthorizationchallenge"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyAuthorizationResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyAuthorizationResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyAuthorizationResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyAuthorizationResponse"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDKeyAuthorizationResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidkeyauthorizationresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyBody": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyBody"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyBody"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDKeyBody",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidkeybody"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyByteSequence": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyByteSequence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyByteSequence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyByteSequence"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDKeyByteSequence",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidkeybytesequence"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyConnectionID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyConnectionID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyConnectionID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyConnectionID"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDKeyConnectionID",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidkeyconnectionid"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyCount"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDKeyCount",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidkeycount"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyDescription"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDKeyDescription",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidkeydescription"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyEndOfBody": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyEndOfBody"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyEndOfBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyEndOfBody"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDKeyEndOfBody",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidkeyendofbody"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyHTTP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyHTTP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyHTTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyHTTP"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDKeyHTTP",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidkeyhttp"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyLength": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyLength"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDKeyLength",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidkeylength"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyName"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDKeyName",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidkeyname"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyObjectClass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyObjectClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyObjectClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyObjectClass"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDKeyObjectClass",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidkeyobjectclass"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyTarget": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyTarget"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ">!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyTarget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDKeyTarget"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDKeyTarget",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidkeytarget"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressPrecentageKey",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyAppParameters",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyAuthorizationChallenge",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyAuthorizationResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyBody",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyByteSequence",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyConnectionID",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyCount",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyDescription",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyEndOfBody",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyHTTP",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyLength",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyName",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyObjectClass",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyTarget"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kIOBluetoothDeviceNameChangedNotification"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOBluetoothDeviceNameChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHostControllerPoweredOffNotification",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHostControllerPoweredOnNotification",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelPublishedNotification",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelTerminatedNotification",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kFTSProgressPrecentageKey",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyAppParameters",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyAuthorizationChallenge",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyAuthorizationResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyBody",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyByteSequence",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyConnectionID",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyCount",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyDescription",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyEndOfBody",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDKeyHTTP"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kIOBluetoothDeviceNameChangedNotification"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyCount/title",
          "value": "kOBEXHeaderIDKeyCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDKeyCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyName/title",
          "value": "kOBEXHeaderIDKeyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDKeyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyDescription/title",
          "value": "kOBEXHeaderIDKeyDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDKeyDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kIOBluetoothDeviceNameChangedNotification/title",
          "value": "kIOBluetoothDeviceNameChangedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kIOBluetoothDeviceNameChangedNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOBluetoothDeviceNameChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kFTSProgressPrecentageKey/title",
          "value": "kFTSProgressPrecentageKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kFTSProgressPrecentageKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFTSProgressPrecentageKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyLength/title",
          "value": "kOBEXHeaderIDKeyLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDKeyLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyByteSequence/title",
          "value": "kOBEXHeaderIDKeyByteSequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyByteSequence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDKeyByteSequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyAuthorizationChallenge/title",
          "value": "kOBEXHeaderIDKeyAuthorizationChallenge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyAuthorizationChallenge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDKeyAuthorizationChallenge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyBody/title",
          "value": "kOBEXHeaderIDKeyBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDKeyBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyConnectionID/title",
          "value": "kOBEXHeaderIDKeyConnectionID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyConnectionID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDKeyConnectionID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyTarget/title",
          "value": "kOBEXHeaderIDKeyTarget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyTarget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDKeyTarget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyAppParameters/title",
          "value": "kOBEXHeaderIDKeyAppParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyAppParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDKeyAppParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyObjectClass/title",
          "value": "kOBEXHeaderIDKeyObjectClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyObjectClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDKeyObjectClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyAuthorizationResponse/title",
          "value": "kOBEXHeaderIDKeyAuthorizationResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyAuthorizationResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDKeyAuthorizationResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyHTTP/title",
          "value": "kOBEXHeaderIDKeyHTTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyHTTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDKeyHTTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyEndOfBody/title",
          "value": "kOBEXHeaderIDKeyEndOfBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDKeyEndOfBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDKeyEndOfBody"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kiobluetoothdevicenamechangednotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kiobluetoothdevicenamechangednotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
