{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeQueueSpaceAvailable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@IOBluetoothL2CAPChannelEventType@kIOBluetoothL2CAPChannelEventTypeQueueSpaceAvailable",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kIOBluetoothL2CAPChannelEventTypeQueueSpaceAvailable"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@IOBluetoothL2CAPChannelEventType",
        "text": "IOBluetoothL2CAPChannelEventType"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kIOBluetoothL2CAPChannelEventTypeQueueSpaceAvailable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kIOBluetoothL2CAPChannelEventTypeQueueSpaceAvailable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kIOBluetoothL2CAPChannelEventTypeQueueSpaceAvailable"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelEventType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@IOBluetoothL2CAPChannelEventType",
              "text": "IOBluetoothL2CAPChannelEventType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelEventType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothL2CAPChannelEventType"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelEventType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothL2CAPChannelEventType"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothL2CAPChannelEventType",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothl2capchanneleventtype"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeClosed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOBluetoothL2CAPChannelEventTypeClosed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@IOBluetoothL2CAPChannelEventType",
          "text": "IOBluetoothL2CAPChannelEventType"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeClosed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOBluetoothL2CAPChannelEventTypeClosed"
        }
      ],
      "role": "symbol",
      "title": "kIOBluetoothL2CAPChannelEventTypeClosed",
      "type": "topic",
      "url": "/documentation/iobluetooth/kiobluetoothl2capchanneleventtypeclosed"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOBluetoothL2CAPChannelEventTypeData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@IOBluetoothL2CAPChannelEventType",
          "text": "IOBluetoothL2CAPChannelEventType"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOBluetoothL2CAPChannelEventTypeData"
        }
      ],
      "role": "symbol",
      "title": "kIOBluetoothL2CAPChannelEventTypeData",
      "type": "topic",
      "url": "/documentation/iobluetooth/kiobluetoothl2capchanneleventtypedata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeOpenComplete": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOBluetoothL2CAPChannelEventTypeOpenComplete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@IOBluetoothL2CAPChannelEventType",
          "text": "IOBluetoothL2CAPChannelEventType"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeOpenComplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOBluetoothL2CAPChannelEventTypeOpenComplete"
        }
      ],
      "role": "symbol",
      "title": "kIOBluetoothL2CAPChannelEventTypeOpenComplete",
      "type": "topic",
      "url": "/documentation/iobluetooth/kiobluetoothl2capchanneleventtypeopencomplete"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeQueueSpaceAvailable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOBluetoothL2CAPChannelEventTypeQueueSpaceAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@IOBluetoothL2CAPChannelEventType",
          "text": "IOBluetoothL2CAPChannelEventType"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeQueueSpaceAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOBluetoothL2CAPChannelEventTypeQueueSpaceAvailable"
        }
      ],
      "role": "symbol",
      "title": "kIOBluetoothL2CAPChannelEventTypeQueueSpaceAvailable",
      "type": "topic",
      "url": "/documentation/iobluetooth/kiobluetoothl2capchanneleventtypequeuespaceavailable"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeReconfigured": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOBluetoothL2CAPChannelEventTypeReconfigured"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@IOBluetoothL2CAPChannelEventType",
          "text": "IOBluetoothL2CAPChannelEventType"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeReconfigured",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOBluetoothL2CAPChannelEventTypeReconfigured"
        }
      ],
      "role": "symbol",
      "title": "kIOBluetoothL2CAPChannelEventTypeReconfigured",
      "type": "topic",
      "url": "/documentation/iobluetooth/kiobluetoothl2capchanneleventtypereconfigured"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeWriteComplete": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kIOBluetoothL2CAPChannelEventTypeWriteComplete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@IOBluetoothL2CAPChannelEventType",
          "text": "IOBluetoothL2CAPChannelEventType"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeWriteComplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kIOBluetoothL2CAPChannelEventTypeWriteComplete"
        }
      ],
      "role": "symbol",
      "title": "kIOBluetoothL2CAPChannelEventTypeWriteComplete",
      "type": "topic",
      "url": "/documentation/iobluetooth/kiobluetoothl2capchanneleventtypewritecomplete"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeClosed",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeOpenComplete",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeReconfigured",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeWriteComplete"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kIOBluetoothL2CAPChannelEventTypeQueueSpaceAvailable"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOBluetoothL2CAPChannelEventTypeQueueSpaceAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothL2CAPChannelEventType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeClosed",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeOpenComplete",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeReconfigured",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothL2CAPChannelEventTypeWriteComplete"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kIOBluetoothL2CAPChannelEventTypeQueueSpaceAvailable"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelEventType/title",
          "value": "IOBluetoothL2CAPChannelEventType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelEventType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothL2CAPChannelEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothL2CAPChannelEventType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothL2CAPChannelEventType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kIOBluetoothL2CAPChannelEventTypeQueueSpaceAvailable/title",
          "value": "kIOBluetoothL2CAPChannelEventTypeQueueSpaceAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kIOBluetoothL2CAPChannelEventTypeQueueSpaceAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOBluetoothL2CAPChannelEventTypeQueueSpaceAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kIOBluetoothL2CAPChannelEventTypeOpenComplete/title",
          "value": "kIOBluetoothL2CAPChannelEventTypeOpenComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kIOBluetoothL2CAPChannelEventTypeOpenComplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOBluetoothL2CAPChannelEventTypeOpenComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kIOBluetoothL2CAPChannelEventTypeReconfigured/title",
          "value": "kIOBluetoothL2CAPChannelEventTypeReconfigured"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kIOBluetoothL2CAPChannelEventTypeReconfigured/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOBluetoothL2CAPChannelEventTypeReconfigured"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kIOBluetoothL2CAPChannelEventTypeWriteComplete/title",
          "value": "kIOBluetoothL2CAPChannelEventTypeWriteComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kIOBluetoothL2CAPChannelEventTypeWriteComplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOBluetoothL2CAPChannelEventTypeWriteComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kIOBluetoothL2CAPChannelEventTypeData/title",
          "value": "kIOBluetoothL2CAPChannelEventTypeData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kIOBluetoothL2CAPChannelEventTypeData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOBluetoothL2CAPChannelEventTypeData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kIOBluetoothL2CAPChannelEventTypeClosed/title",
          "value": "kIOBluetoothL2CAPChannelEventTypeClosed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kIOBluetoothL2CAPChannelEventTypeClosed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kIOBluetoothL2CAPChannelEventTypeClosed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kiobluetoothl2capchanneleventtypequeuespaceavailable"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kiobluetoothl2capchanneleventtypequeuespaceavailable"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
