{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMin"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@OBEXErrorCodes@kOBEXErrorRangeMin",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kOBEXErrorRangeMin"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@OBEXErrorCodes",
        "text": "OBEXErrorCodes"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kOBEXErrorRangeMin"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kOBEXErrorRangeMin"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kOBEXErrorRangeMin"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorCodes",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@OBEXErrorCodes",
              "text": "OBEXErrorCodes"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Minimum value in OBEX error range.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorCodes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorCodes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXErrorCodes"
        }
      ],
      "role": "symbol",
      "title": "OBEXErrorCodes",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexerrorcodes"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXBadArgumentError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXBadArgumentError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXBadArgumentError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXBadArgumentError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXBadArgumentError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexbadargumenterror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXBadRequestError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXBadRequestError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXBadRequestError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXBadRequestError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXBadRequestError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexbadrequesterror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXCancelledError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXCancelledError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXCancelledError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXCancelledError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXCancelledError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexcancellederror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConflictError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXConflictError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConflictError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXConflictError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXConflictError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexconflicterror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMax": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXErrorRangeMax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXErrorRangeMax"
        }
      ],
      "role": "symbol",
      "title": "kOBEXErrorRangeMax",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexerrorrangemax"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMin": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXErrorRangeMin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXErrorRangeMin"
        }
      ],
      "role": "symbol",
      "title": "kOBEXErrorRangeMin",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexerrorrangemin"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXForbiddenError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXForbiddenError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXForbiddenError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXForbiddenError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXForbiddenError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexforbiddenerror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXGeneralError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXGeneralError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXGeneralError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXGeneralError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXGeneralError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexgeneralerror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXInternalError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXInternalError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXInternalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXInternalError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXInternalError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexinternalerror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXMethodNotAllowedError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXMethodNotAllowedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXMethodNotAllowedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXMethodNotAllowedError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXMethodNotAllowedError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexmethodnotallowederror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNoResourcesError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXNoResourcesError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNoResourcesError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXNoResourcesError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXNoResourcesError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexnoresourceserror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotAcceptableError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXNotAcceptableError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotAcceptableError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXNotAcceptableError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXNotAcceptableError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexnotacceptableerror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotFoundError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXNotFoundError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotFoundError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXNotFoundError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXNotFoundError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexnotfounderror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotImplementedError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXNotImplementedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotImplementedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXNotImplementedError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXNotImplementedError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexnotimplementederror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPreconditionFailedError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXPreconditionFailedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPreconditionFailedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXPreconditionFailedError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXPreconditionFailedError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexpreconditionfailederror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionAlreadyConnectedError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionAlreadyConnectedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionAlreadyConnectedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionAlreadyConnectedError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionAlreadyConnectedError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessionalreadyconnectederror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXBadArgumentError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXBadRequestError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXCancelledError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConflictError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMax",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXForbiddenError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXGeneralError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXInternalError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXMethodNotAllowedError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNoResourcesError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotAcceptableError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotFoundError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotImplementedError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPreconditionFailedError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionAlreadyConnectedError"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kOBEXErrorRangeMin"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXErrorRangeMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorCodes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXBadArgumentError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXBadRequestError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXCancelledError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConflictError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMax",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXForbiddenError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXGeneralError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXInternalError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXMethodNotAllowedError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNoResourcesError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotAcceptableError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotFoundError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotImplementedError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPreconditionFailedError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionAlreadyConnectedError"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kOBEXErrorRangeMin"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNotAcceptableError/title",
          "value": "kOBEXNotAcceptableError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNotAcceptableError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXNotAcceptableError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXCancelledError/title",
          "value": "kOBEXCancelledError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXCancelledError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXCancelledError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXForbiddenError/title",
          "value": "kOBEXForbiddenError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXForbiddenError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXForbiddenError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXMethodNotAllowedError/title",
          "value": "kOBEXMethodNotAllowedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXMethodNotAllowedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXMethodNotAllowedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNotImplementedError/title",
          "value": "kOBEXNotImplementedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNotImplementedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXNotImplementedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXBadArgumentError/title",
          "value": "kOBEXBadArgumentError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXBadArgumentError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXBadArgumentError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionAlreadyConnectedError/title",
          "value": "kOBEXSessionAlreadyConnectedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionAlreadyConnectedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionAlreadyConnectedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXErrorCodes/title",
          "value": "OBEXErrorCodes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXErrorCodes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXErrorCodes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXErrorCodes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXErrorCodes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXInternalError/title",
          "value": "kOBEXInternalError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXInternalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXInternalError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNoResourcesError/title",
          "value": "kOBEXNoResourcesError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNoResourcesError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXNoResourcesError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConflictError/title",
          "value": "kOBEXConflictError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConflictError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXConflictError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXErrorRangeMax/title",
          "value": "kOBEXErrorRangeMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXErrorRangeMax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXErrorRangeMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNotFoundError/title",
          "value": "kOBEXNotFoundError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNotFoundError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXNotFoundError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXGeneralError/title",
          "value": "kOBEXGeneralError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXGeneralError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXGeneralError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXBadRequestError/title",
          "value": "kOBEXBadRequestError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXBadRequestError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXBadRequestError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPreconditionFailedError/title",
          "value": "kOBEXPreconditionFailedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPreconditionFailedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXPreconditionFailedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXErrorRangeMin/title",
          "value": "kOBEXErrorRangeMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXErrorRangeMin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXErrorRangeMin"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kobexerrorrangemin"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kobexerrorrangemin"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
