{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeUserDefinedStart"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@OBEXOpCodeCommandValues@kOBEXOpCodeUserDefinedStart",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kOBEXOpCodeUserDefinedStart"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@OBEXOpCodeCommandValues",
        "text": "OBEXOpCodeCommandValues"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kOBEXOpCodeUserDefinedStart"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kOBEXOpCodeUserDefinedStart"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kOBEXOpCodeUserDefinedStart"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeCommandValues",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@OBEXOpCodeCommandValues",
              "text": "OBEXOpCodeCommandValues"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeCommandValues": {
      "abstract": [
        {
          "text": "Operation OpCode values for commands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXOpCodeCommandValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeCommandValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXOpCodeCommandValues"
        }
      ],
      "role": "symbol",
      "title": "OBEXOpCodeCommandValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexopcodecommandvalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeAbort": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeAbort"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeCommandValues",
          "text": "OBEXOpCodeCommandValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeAbort",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeAbort"
        }
      ],
      "role": "symbol",
      "title": "kOBEXOpCodeAbort",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexopcodeabort"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeConnect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeConnect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeCommandValues",
          "text": "OBEXOpCodeCommandValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeConnect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeConnect"
        }
      ],
      "role": "symbol",
      "title": "kOBEXOpCodeConnect",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexopcodeconnect"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeDisconnect": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeDisconnect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeCommandValues",
          "text": "OBEXOpCodeCommandValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeDisconnect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeDisconnect"
        }
      ],
      "role": "symbol",
      "title": "kOBEXOpCodeDisconnect",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexopcodedisconnect"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeGet": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeGet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeCommandValues",
          "text": "OBEXOpCodeCommandValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeGet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeGet"
        }
      ],
      "role": "symbol",
      "title": "kOBEXOpCodeGet",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexopcodeget"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeGetWithHighBitSet": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeGetWithHighBitSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeCommandValues",
          "text": "OBEXOpCodeCommandValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeGetWithHighBitSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeGetWithHighBitSet"
        }
      ],
      "role": "symbol",
      "title": "kOBEXOpCodeGetWithHighBitSet",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexopcodegetwithhighbitset"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodePut": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXOpCodePut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeCommandValues",
          "text": "OBEXOpCodeCommandValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodePut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXOpCodePut"
        }
      ],
      "role": "symbol",
      "title": "kOBEXOpCodePut",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexopcodeput"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodePutWithHighBitSet": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXOpCodePutWithHighBitSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeCommandValues",
          "text": "OBEXOpCodeCommandValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodePutWithHighBitSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXOpCodePutWithHighBitSet"
        }
      ],
      "role": "symbol",
      "title": "kOBEXOpCodePutWithHighBitSet",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexopcodeputwithhighbitset"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeReserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeReserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeCommandValues",
          "text": "OBEXOpCodeCommandValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeReserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeReserved"
        }
      ],
      "role": "symbol",
      "title": "kOBEXOpCodeReserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexopcodereserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeReservedRangeEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeReservedRangeEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeCommandValues",
          "text": "OBEXOpCodeCommandValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeReservedRangeEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeReservedRangeEnd"
        }
      ],
      "role": "symbol",
      "title": "kOBEXOpCodeReservedRangeEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexopcodereservedrangeend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeReservedRangeStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeReservedRangeStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeCommandValues",
          "text": "OBEXOpCodeCommandValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeReservedRangeStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeReservedRangeStart"
        }
      ],
      "role": "symbol",
      "title": "kOBEXOpCodeReservedRangeStart",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexopcodereservedrangestart"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeReservedWithHighBitSet": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeReservedWithHighBitSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeCommandValues",
          "text": "OBEXOpCodeCommandValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeReservedWithHighBitSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeReservedWithHighBitSet"
        }
      ],
      "role": "symbol",
      "title": "kOBEXOpCodeReservedWithHighBitSet",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexopcodereservedwithhighbitset"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeSetPath": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeSetPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeCommandValues",
          "text": "OBEXOpCodeCommandValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeSetPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeSetPath"
        }
      ],
      "role": "symbol",
      "title": "kOBEXOpCodeSetPath",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexopcodesetpath"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeUserDefinedEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeUserDefinedEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeCommandValues",
          "text": "OBEXOpCodeCommandValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeUserDefinedEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeUserDefinedEnd"
        }
      ],
      "role": "symbol",
      "title": "kOBEXOpCodeUserDefinedEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexopcodeuserdefinedend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeUserDefinedStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeUserDefinedStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeCommandValues",
          "text": "OBEXOpCodeCommandValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeUserDefinedStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeUserDefinedStart"
        }
      ],
      "role": "symbol",
      "title": "kOBEXOpCodeUserDefinedStart",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexopcodeuserdefinedstart"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeAbort",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeConnect",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeDisconnect",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeGet",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeGetWithHighBitSet",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodePut",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodePutWithHighBitSet",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeReserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeReservedRangeEnd",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeReservedRangeStart",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeReservedWithHighBitSet",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeSetPath",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeUserDefinedEnd"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kOBEXOpCodeUserDefinedStart"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXOpCodeUserDefinedStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeCommandValues"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeAbort",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeConnect",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeDisconnect",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeGet",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeGetWithHighBitSet",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodePut",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodePutWithHighBitSet",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeReserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeReservedRangeEnd",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeReservedRangeStart",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeReservedWithHighBitSet",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeSetPath",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeUserDefinedEnd"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kOBEXOpCodeUserDefinedStart"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeReservedRangeEnd/title",
          "value": "kOBEXOpCodeReservedRangeEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeReservedRangeEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXOpCodeReservedRangeEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodePut/title",
          "value": "kOBEXOpCodePut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodePut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXOpCodePut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeReservedRangeStart/title",
          "value": "kOBEXOpCodeReservedRangeStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeReservedRangeStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXOpCodeReservedRangeStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeSetPath/title",
          "value": "kOBEXOpCodeSetPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeSetPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXOpCodeSetPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodePutWithHighBitSet/title",
          "value": "kOBEXOpCodePutWithHighBitSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodePutWithHighBitSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXOpCodePutWithHighBitSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeGet/title",
          "value": "kOBEXOpCodeGet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeGet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXOpCodeGet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeUserDefinedStart/title",
          "value": "kOBEXOpCodeUserDefinedStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeUserDefinedStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXOpCodeUserDefinedStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeAbort/title",
          "value": "kOBEXOpCodeAbort"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeAbort/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXOpCodeAbort"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeDisconnect/title",
          "value": "kOBEXOpCodeDisconnect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeDisconnect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXOpCodeDisconnect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeReserved/title",
          "value": "kOBEXOpCodeReserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeReserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXOpCodeReserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeReservedWithHighBitSet/title",
          "value": "kOBEXOpCodeReservedWithHighBitSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeReservedWithHighBitSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXOpCodeReservedWithHighBitSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeGetWithHighBitSet/title",
          "value": "kOBEXOpCodeGetWithHighBitSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeGetWithHighBitSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXOpCodeGetWithHighBitSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeUserDefinedEnd/title",
          "value": "kOBEXOpCodeUserDefinedEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeUserDefinedEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXOpCodeUserDefinedEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeConnect/title",
          "value": "kOBEXOpCodeConnect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeConnect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXOpCodeConnect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXOpCodeCommandValues/title",
          "value": "OBEXOpCodeCommandValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXOpCodeCommandValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXOpCodeCommandValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXOpCodeCommandValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXOpCodeCommandValues"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kobexopcodeuserdefinedstart"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kobexopcodeuserdefinedstart"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
