{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeDisconnectCommandReceived"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@OBEXSessionEventTypes@kOBEXSessionEventTypeDisconnectCommandReceived",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kOBEXSessionEventTypeDisconnectCommandReceived"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@OBEXSessionEventTypes",
        "text": "OBEXSessionEventTypes"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kOBEXSessionEventTypeDisconnectCommandReceived"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kOBEXSessionEventTypeDisconnectCommandReceived"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kOBEXSessionEventTypeDisconnectCommandReceived"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEventTypes",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@OBEXSessionEventTypes",
              "text": "OBEXSessionEventTypes"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEventTypes": {
      "abstract": [
        {
          "text": "Type identifiers for OBEX sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXSessionEventTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEventTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXSessionEventTypes"
        }
      ],
      "role": "symbol",
      "title": "OBEXSessionEventTypes",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexsessioneventtypes"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeAbortCommandReceived": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeAbortCommandReceived"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXSessionEventTypes",
          "text": "OBEXSessionEventTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeAbortCommandReceived",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeAbortCommandReceived"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionEventTypeAbortCommandReceived",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessioneventtypeabortcommandreceived"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeAbortCommandResponseReceived": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeAbortCommandResponseReceived"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXSessionEventTypes",
          "text": "OBEXSessionEventTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeAbortCommandResponseReceived",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeAbortCommandResponseReceived"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionEventTypeAbortCommandResponseReceived",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessioneventtypeabortcommandresponsereceived"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeConnectCommandReceived": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeConnectCommandReceived"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXSessionEventTypes",
          "text": "OBEXSessionEventTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeConnectCommandReceived",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeConnectCommandReceived"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionEventTypeConnectCommandReceived",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessioneventtypeconnectcommandreceived"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeConnectCommandResponseReceived": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeConnectCommandResponseReceived"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXSessionEventTypes",
          "text": "OBEXSessionEventTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeConnectCommandResponseReceived",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeConnectCommandResponseReceived"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionEventTypeConnectCommandResponseReceived",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessioneventtypeconnectcommandresponsereceived"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeDisconnectCommandReceived": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeDisconnectCommandReceived"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXSessionEventTypes",
          "text": "OBEXSessionEventTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeDisconnectCommandReceived",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeDisconnectCommandReceived"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionEventTypeDisconnectCommandReceived",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessioneventtypedisconnectcommandreceived"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeDisconnectCommandResponseReceived": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeDisconnectCommandResponseReceived"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXSessionEventTypes",
          "text": "OBEXSessionEventTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeDisconnectCommandResponseReceived",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeDisconnectCommandResponseReceived"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionEventTypeDisconnectCommandResponseReceived",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessioneventtypedisconnectcommandresponsereceived"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXSessionEventTypes",
          "text": "OBEXSessionEventTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionEventTypeError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessioneventtypeerror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeGetCommandReceived": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeGetCommandReceived"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXSessionEventTypes",
          "text": "OBEXSessionEventTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeGetCommandReceived",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeGetCommandReceived"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionEventTypeGetCommandReceived",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessioneventtypegetcommandreceived"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeGetCommandResponseReceived": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeGetCommandResponseReceived"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXSessionEventTypes",
          "text": "OBEXSessionEventTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeGetCommandResponseReceived",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeGetCommandResponseReceived"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionEventTypeGetCommandResponseReceived",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessioneventtypegetcommandresponsereceived"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypePutCommandReceived": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypePutCommandReceived"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXSessionEventTypes",
          "text": "OBEXSessionEventTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypePutCommandReceived",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypePutCommandReceived"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionEventTypePutCommandReceived",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessioneventtypeputcommandreceived"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypePutCommandResponseReceived": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypePutCommandResponseReceived"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXSessionEventTypes",
          "text": "OBEXSessionEventTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypePutCommandResponseReceived",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypePutCommandResponseReceived"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionEventTypePutCommandResponseReceived",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessioneventtypeputcommandresponsereceived"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeSetPathCommandReceived": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeSetPathCommandReceived"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXSessionEventTypes",
          "text": "OBEXSessionEventTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeSetPathCommandReceived",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeSetPathCommandReceived"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionEventTypeSetPathCommandReceived",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessioneventtypesetpathcommandreceived"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeSetPathCommandResponseReceived": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeSetPathCommandResponseReceived"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXSessionEventTypes",
          "text": "OBEXSessionEventTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeSetPathCommandResponseReceived",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionEventTypeSetPathCommandResponseReceived"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionEventTypeSetPathCommandResponseReceived",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessioneventtypesetpathcommandresponsereceived"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeAbortCommandReceived",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeAbortCommandResponseReceived",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeConnectCommandReceived",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeConnectCommandResponseReceived",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeDisconnectCommandResponseReceived",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeGetCommandReceived",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeGetCommandResponseReceived",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypePutCommandReceived",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypePutCommandResponseReceived",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeSetPathCommandReceived",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeSetPathCommandResponseReceived"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kOBEXSessionEventTypeDisconnectCommandReceived"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionEventTypeDisconnectCommandReceived"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEventTypes"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeAbortCommandReceived",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeAbortCommandResponseReceived",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeConnectCommandReceived",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeConnectCommandResponseReceived",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeDisconnectCommandResponseReceived",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeGetCommandReceived",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeGetCommandResponseReceived",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypePutCommandReceived",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypePutCommandResponseReceived",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeSetPathCommandReceived",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionEventTypeSetPathCommandResponseReceived"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kOBEXSessionEventTypeDisconnectCommandReceived"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeError/title",
          "value": "kOBEXSessionEventTypeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionEventTypeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeAbortCommandResponseReceived/title",
          "value": "kOBEXSessionEventTypeAbortCommandResponseReceived"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeAbortCommandResponseReceived/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionEventTypeAbortCommandResponseReceived"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeSetPathCommandResponseReceived/title",
          "value": "kOBEXSessionEventTypeSetPathCommandResponseReceived"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeSetPathCommandResponseReceived/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionEventTypeSetPathCommandResponseReceived"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEventTypes/title",
          "value": "OBEXSessionEventTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEventTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSessionEventTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEventTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSessionEventTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeGetCommandReceived/title",
          "value": "kOBEXSessionEventTypeGetCommandReceived"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeGetCommandReceived/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionEventTypeGetCommandReceived"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeConnectCommandResponseReceived/title",
          "value": "kOBEXSessionEventTypeConnectCommandResponseReceived"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeConnectCommandResponseReceived/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionEventTypeConnectCommandResponseReceived"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeSetPathCommandReceived/title",
          "value": "kOBEXSessionEventTypeSetPathCommandReceived"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeSetPathCommandReceived/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionEventTypeSetPathCommandReceived"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeConnectCommandReceived/title",
          "value": "kOBEXSessionEventTypeConnectCommandReceived"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeConnectCommandReceived/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionEventTypeConnectCommandReceived"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeDisconnectCommandResponseReceived/title",
          "value": "kOBEXSessionEventTypeDisconnectCommandResponseReceived"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeDisconnectCommandResponseReceived/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionEventTypeDisconnectCommandResponseReceived"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeAbortCommandReceived/title",
          "value": "kOBEXSessionEventTypeAbortCommandReceived"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeAbortCommandReceived/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionEventTypeAbortCommandReceived"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeGetCommandResponseReceived/title",
          "value": "kOBEXSessionEventTypeGetCommandResponseReceived"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeGetCommandResponseReceived/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionEventTypeGetCommandResponseReceived"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypePutCommandReceived/title",
          "value": "kOBEXSessionEventTypePutCommandReceived"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypePutCommandReceived/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionEventTypePutCommandReceived"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypePutCommandResponseReceived/title",
          "value": "kOBEXSessionEventTypePutCommandResponseReceived"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypePutCommandResponseReceived/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionEventTypePutCommandResponseReceived"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeDisconnectCommandReceived/title",
          "value": "kOBEXSessionEventTypeDisconnectCommandReceived"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionEventTypeDisconnectCommandReceived/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionEventTypeDisconnectCommandReceived"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kobexsessioneventtypedisconnectcommandreceived"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kobexsessioneventtypedisconnectcommandreceived"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
