{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag2Reserved"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@OBEXPutFlagValues@kOBEXPutFlag2Reserved",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kOBEXPutFlag2Reserved"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@OBEXPutFlagValues",
        "text": "OBEXPutFlagValues"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kOBEXPutFlag2Reserved"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kOBEXPutFlag2Reserved"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kOBEXPutFlag2Reserved"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutFlagValues",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@OBEXPutFlagValues",
              "text": "OBEXPutFlagValues"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutFlagValues": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXPutFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutFlagValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXPutFlagValues"
        }
      ],
      "role": "symbol",
      "title": "OBEXPutFlagValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexputflagvalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag2Reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXPutFlag2Reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXPutFlagValues",
          "text": "OBEXPutFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag2Reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXPutFlag2Reserved"
        }
      ],
      "role": "symbol",
      "title": "kOBEXPutFlag2Reserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexputflag2reserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag3Reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXPutFlag3Reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXPutFlagValues",
          "text": "OBEXPutFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag3Reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXPutFlag3Reserved"
        }
      ],
      "role": "symbol",
      "title": "kOBEXPutFlag3Reserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexputflag3reserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag4Reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXPutFlag4Reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXPutFlagValues",
          "text": "OBEXPutFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag4Reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXPutFlag4Reserved"
        }
      ],
      "role": "symbol",
      "title": "kOBEXPutFlag4Reserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexputflag4reserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag5Reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXPutFlag5Reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXPutFlagValues",
          "text": "OBEXPutFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag5Reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXPutFlag5Reserved"
        }
      ],
      "role": "symbol",
      "title": "kOBEXPutFlag5Reserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexputflag5reserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag6Reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXPutFlag6Reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXPutFlagValues",
          "text": "OBEXPutFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag6Reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXPutFlag6Reserved"
        }
      ],
      "role": "symbol",
      "title": "kOBEXPutFlag6Reserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexputflag6reserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag7Reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXPutFlag7Reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXPutFlagValues",
          "text": "OBEXPutFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag7Reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXPutFlag7Reserved"
        }
      ],
      "role": "symbol",
      "title": "kOBEXPutFlag7Reserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexputflag7reserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagDontCreateDirectory": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXPutFlagDontCreateDirectory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXPutFlagValues",
          "text": "OBEXPutFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagDontCreateDirectory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXPutFlagDontCreateDirectory"
        }
      ],
      "role": "symbol",
      "title": "kOBEXPutFlagDontCreateDirectory",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexputflagdontcreatedirectory"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagGoToParentDirFirst": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXPutFlagGoToParentDirFirst"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXPutFlagValues",
          "text": "OBEXPutFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagGoToParentDirFirst",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXPutFlagGoToParentDirFirst"
        }
      ],
      "role": "symbol",
      "title": "kOBEXPutFlagGoToParentDirFirst",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexputflaggotoparentdirfirst"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagNone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXPutFlagNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXPutFlagValues",
          "text": "OBEXPutFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXPutFlagNone"
        }
      ],
      "role": "symbol",
      "title": "kOBEXPutFlagNone",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexputflagnone"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag3Reserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag4Reserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag5Reserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag6Reserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag7Reserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagDontCreateDirectory",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagGoToParentDirFirst",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagNone"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kOBEXPutFlag2Reserved"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXPutFlag2Reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutFlagValues"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag3Reserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag4Reserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag5Reserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag6Reserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag7Reserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagDontCreateDirectory",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagGoToParentDirFirst",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagNone"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kOBEXPutFlag2Reserved"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag3Reserved/title",
          "value": "kOBEXPutFlag3Reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag3Reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXPutFlag3Reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlagDontCreateDirectory/title",
          "value": "kOBEXPutFlagDontCreateDirectory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlagDontCreateDirectory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXPutFlagDontCreateDirectory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlagGoToParentDirFirst/title",
          "value": "kOBEXPutFlagGoToParentDirFirst"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlagGoToParentDirFirst/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXPutFlagGoToParentDirFirst"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag4Reserved/title",
          "value": "kOBEXPutFlag4Reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag4Reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXPutFlag4Reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag2Reserved/title",
          "value": "kOBEXPutFlag2Reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag2Reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXPutFlag2Reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag7Reserved/title",
          "value": "kOBEXPutFlag7Reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag7Reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXPutFlag7Reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXPutFlagValues/title",
          "value": "OBEXPutFlagValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXPutFlagValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXPutFlagValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXPutFlagValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXPutFlagValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag6Reserved/title",
          "value": "kOBEXPutFlag6Reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag6Reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXPutFlag6Reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlagNone/title",
          "value": "kOBEXPutFlagNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlagNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXPutFlagNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag5Reserved/title",
          "value": "kOBEXPutFlag5Reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag5Reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXPutFlag5Reserved"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kobexputflag2reserved"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kobexputflag2reserved"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
