{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDTime4Byte"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@OBEXHeaderIdentifiers@kOBEXHeaderIDTime4Byte",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kOBEXHeaderIDTime4Byte"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
        "text": "OBEXHeaderIdentifiers"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kOBEXHeaderIDTime4Byte"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kOBEXHeaderIDTime4Byte"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDTime4Byte"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXHeaderIdentifiers",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
              "text": "OBEXHeaderIdentifiers"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Date/time stamp - 4 byte version for compat. only. Seconds since Jan 1, 1970.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXHeaderIdentifiers": {
      "abstract": [
        {
          "text": "Identifiers for OBEX Headers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXHeaderIdentifiers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "role": "symbol",
      "title": "OBEXHeaderIdentifiers",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexheaderidentifiers"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAppParameters": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDAppParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAppParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDAppParameters"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDAppParameters",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidappparameters"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAuthorizationChallenge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDAuthorizationChallenge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAuthorizationChallenge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDAuthorizationChallenge"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDAuthorizationChallenge",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidauthorizationchallenge"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAuthorizationResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDAuthorizationResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAuthorizationResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDAuthorizationResponse"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDAuthorizationResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidauthorizationresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDBody": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDBody"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDBody"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDBody",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidbody"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDConnectionID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDConnectionID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDConnectionID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDConnectionID"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDConnectionID",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidconnectionid"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDCount"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDCount",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidcount"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDDescription"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDDescription",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderiddescription"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDEndOfBody": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDEndOfBody"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDEndOfBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDEndOfBody"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDEndOfBody",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidendofbody"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDHTTP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDHTTP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDHTTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDHTTP"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDHTTP",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidhttp"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDLength": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDLength"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDLength",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidlength"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDName"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDName",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidname"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13CreatorID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDOBEX13CreatorID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13CreatorID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDOBEX13CreatorID"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDOBEX13CreatorID",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidobex13creatorid"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13ObjectClass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDOBEX13ObjectClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13ObjectClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDOBEX13ObjectClass"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDOBEX13ObjectClass",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidobex13objectclass"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13SessionParameters": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDOBEX13SessionParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13SessionParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDOBEX13SessionParameters"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDOBEX13SessionParameters",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidobex13sessionparameters"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13SessionSequenceNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDOBEX13SessionSequenceNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13SessionSequenceNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDOBEX13SessionSequenceNumber"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDOBEX13SessionSequenceNumber",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidobex13sessionsequencenumber"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDTime4Byte": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDTime4Byte"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDTime4Byte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDTime4Byte"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDTime4Byte",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidtime4byte"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAppParameters",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAuthorizationChallenge",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAuthorizationResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDBody",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDConnectionID",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDCount",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDDescription",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDEndOfBody",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDHTTP",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDLength",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDName",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13CreatorID",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13ObjectClass",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13SessionParameters",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13SessionSequenceNumber"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kOBEXHeaderIDTime4Byte"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDTime4Byte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXHeaderIdentifiers"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAppParameters",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAuthorizationChallenge",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAuthorizationResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDBody",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDConnectionID",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDCount",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDDescription",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDEndOfBody",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDHTTP",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDLength",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDName",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13CreatorID",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13ObjectClass",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13SessionParameters",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13SessionSequenceNumber"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kOBEXHeaderIDTime4Byte"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDEndOfBody/title",
          "value": "kOBEXHeaderIDEndOfBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDEndOfBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDEndOfBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDAuthorizationResponse/title",
          "value": "kOBEXHeaderIDAuthorizationResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDAuthorizationResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDAuthorizationResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDTime4Byte/title",
          "value": "kOBEXHeaderIDTime4Byte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDTime4Byte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDTime4Byte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDAuthorizationChallenge/title",
          "value": "kOBEXHeaderIDAuthorizationChallenge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDAuthorizationChallenge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDAuthorizationChallenge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDHTTP/title",
          "value": "kOBEXHeaderIDHTTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDHTTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDHTTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDOBEX13ObjectClass/title",
          "value": "kOBEXHeaderIDOBEX13ObjectClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDOBEX13ObjectClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDOBEX13ObjectClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDOBEX13CreatorID/title",
          "value": "kOBEXHeaderIDOBEX13CreatorID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDOBEX13CreatorID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDOBEX13CreatorID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDLength/title",
          "value": "kOBEXHeaderIDLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDDescription/title",
          "value": "kOBEXHeaderIDDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDBody/title",
          "value": "kOBEXHeaderIDBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDConnectionID/title",
          "value": "kOBEXHeaderIDConnectionID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDConnectionID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDConnectionID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXHeaderIdentifiers/title",
          "value": "OBEXHeaderIdentifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXHeaderIdentifiers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXHeaderIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXHeaderIdentifiers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXHeaderIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDOBEX13SessionSequenceNumber/title",
          "value": "kOBEXHeaderIDOBEX13SessionSequenceNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDOBEX13SessionSequenceNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDOBEX13SessionSequenceNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDOBEX13SessionParameters/title",
          "value": "kOBEXHeaderIDOBEX13SessionParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDOBEX13SessionParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDOBEX13SessionParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDName/title",
          "value": "kOBEXHeaderIDName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDCount/title",
          "value": "kOBEXHeaderIDCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDAppParameters/title",
          "value": "kOBEXHeaderIDAppParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDAppParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDAppParameters"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kobexheaderidtime4byte"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kobexheaderidtime4byte"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
