{"identifier":{"url":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag4Reserved","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kOBEXPutFlag4Reserved","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OBEXPutFlagValues","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutFlagValues","preciseIdentifier":"c:@E@OBEXPutFlagValues","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"navigatorTitle":[{"text":"kOBEXPutFlag4Reserved","kind":"identifier"}],"title":"kOBEXPutFlag4Reserved","symbolKind":"var","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kOBEXPutFlag4Reserved","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OBEXPutFlagValues","kind":"typeIdentifier","preciseIdentifier":"c:@E@OBEXPutFlagValues"}],"platforms":[{"unavailable":false,"name":"macOS","beta":false,"deprecated":false}],"roleHeading":"Global Variable","role":"symbol","modules":[{"name":"IOBluetooth"}],"externalID":"c:@E@OBEXPutFlagValues@kOBEXPutFlag4Reserved"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/iobluetooth/kobexputflag4reserved"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/iobluetooth/kobexputflag4reserved"]}],"seeAlsoSections":[{"identifiers":["doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag2Reserved","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag3Reserved","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag5Reserved","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag6Reserved","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag7Reserved","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagDontCreateDirectory","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagGoToParentDirFirst","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagNone"],"generated":true,"anchor":"Constants","title":"Constants"}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iobluetooth/documentation/IOBluetooth"]]},"references":{"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag7Reserved":{"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag7Reserved","role":"symbol","title":"kOBEXPutFlag7Reserved","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"kOBEXPutFlag7Reserved"}],"kind":"symbol","type":"topic","url":"/documentation/iobluetooth/kobexputflag7reserved","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXPutFlag7Reserved"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXPutFlagValues","kind":"typeIdentifier","text":"OBEXPutFlagValues"}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag3Reserved":{"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag3Reserved","role":"symbol","title":"kOBEXPutFlag3Reserved","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"kOBEXPutFlag3Reserved"}],"kind":"symbol","type":"topic","url":"/documentation/iobluetooth/kobexputflag3reserved","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXPutFlag3Reserved"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXPutFlagValues","kind":"typeIdentifier","text":"OBEXPutFlagValues"}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagDontCreateDirectory":{"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagDontCreateDirectory","role":"symbol","title":"kOBEXPutFlagDontCreateDirectory","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"kOBEXPutFlagDontCreateDirectory"}],"kind":"symbol","type":"topic","url":"/documentation/iobluetooth/kobexputflagdontcreatedirectory","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXPutFlagDontCreateDirectory"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXPutFlagValues","kind":"typeIdentifier","text":"OBEXPutFlagValues"}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagGoToParentDirFirst":{"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagGoToParentDirFirst","role":"symbol","title":"kOBEXPutFlagGoToParentDirFirst","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"kOBEXPutFlagGoToParentDirFirst"}],"kind":"symbol","type":"topic","url":"/documentation/iobluetooth/kobexputflaggotoparentdirfirst","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXPutFlagGoToParentDirFirst"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXPutFlagValues","kind":"typeIdentifier","text":"OBEXPutFlagValues"}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagNone":{"abstract":[],"type":"topic","url":"/documentation/iobluetooth/kobexputflagnone","title":"kOBEXPutFlagNone","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXPutFlagNone"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXPutFlagValues","kind":"typeIdentifier","text":"OBEXPutFlagValues"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kOBEXPutFlagNone"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagNone"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutFlagValues":{"url":"/documentation/iobluetooth/obexputflagvalues","navigatorTitle":[{"kind":"identifier","text":"OBEXPutFlagValues"}],"title":"OBEXPutFlagValues","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBEXPutFlagValues"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutFlagValues","kind":"symbol","abstract":[],"role":"symbol","type":"topic"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag2Reserved":{"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag2Reserved","role":"symbol","title":"kOBEXPutFlag2Reserved","abstract":[],"navigatorTitle":[{"text":"kOBEXPutFlag2Reserved","kind":"identifier"}],"kind":"symbol","type":"topic","url":"/documentation/iobluetooth/kobexputflag2reserved","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kOBEXPutFlag2Reserved","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OBEXPutFlagValues","kind":"typeIdentifier","preciseIdentifier":"c:@E@OBEXPutFlagValues"}]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.iobluetooth/documentation/IOBluetooth":{"kind":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth","abstract":[{"type":"text","text":"Gain user-space access to Bluetooth devices."}],"url":"/documentation/iobluetooth","role":"collection","type":"topic","title":"IOBluetooth"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag5Reserved":{"abstract":[],"type":"topic","url":"/documentation/iobluetooth/kobexputflag5reserved","title":"kOBEXPutFlag5Reserved","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kOBEXPutFlag5Reserved","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OBEXPutFlagValues","kind":"typeIdentifier","preciseIdentifier":"c:@E@OBEXPutFlagValues"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"kOBEXPutFlag5Reserved","kind":"identifier"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag5Reserved"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag6Reserved":{"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag6Reserved","role":"symbol","title":"kOBEXPutFlag6Reserved","abstract":[],"navigatorTitle":[{"text":"kOBEXPutFlag6Reserved","kind":"identifier"}],"kind":"symbol","type":"topic","url":"/documentation/iobluetooth/kobexputflag6reserved","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kOBEXPutFlag6Reserved","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OBEXPutFlagValues","preciseIdentifier":"c:@E@OBEXPutFlagValues","kind":"typeIdentifier"}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag4Reserved":{"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag4Reserved","role":"symbol","title":"kOBEXPutFlag4Reserved","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"kOBEXPutFlag4Reserved"}],"kind":"symbol","type":"topic","url":"/documentation/iobluetooth/kobexputflag4reserved","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kOBEXPutFlag4Reserved"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXPutFlagValues","kind":"typeIdentifier","text":"OBEXPutFlagValues"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"name":"macOS","beta":false,"deprecated":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"kOBEXPutFlag4Reserved","op":"replace","path":"/metadata/title"},{"value":"case","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"kOBEXPutFlag4Reserved","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iobluetooth/documentation/IOBluetooth","doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutFlagValues"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag2Reserved","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag3Reserved","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag5Reserved","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag6Reserved","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlag7Reserved","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagDontCreateDirectory","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagGoToParentDirFirst","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPutFlagNone"],"anchor":"Constants","title":"Constants"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"kOBEXPutFlag4Reserved"}],"platforms":["macOS"],"languages":["occ"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag7Reserved/title","value":"kOBEXPutFlag7Reserved"},{"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag7Reserved/fragments","value":[{"text":"kOBEXPutFlag7Reserved","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag3Reserved/title","value":"kOBEXPutFlag3Reserved"},{"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag3Reserved/fragments","value":[{"text":"kOBEXPutFlag3Reserved","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlagDontCreateDirectory/title","value":"kOBEXPutFlagDontCreateDirectory"},{"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlagDontCreateDirectory/fragments","value":[{"kind":"identifier","text":"kOBEXPutFlagDontCreateDirectory"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlagGoToParentDirFirst/title","value":"kOBEXPutFlagGoToParentDirFirst"},{"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlagGoToParentDirFirst/fragments","value":[{"kind":"identifier","text":"kOBEXPutFlagGoToParentDirFirst"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlagNone/title","value":"kOBEXPutFlagNone"},{"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlagNone/fragments","value":[{"text":"kOBEXPutFlagNone","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXPutFlagValues/title","value":"OBEXPutFlagValues","op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXPutFlagValues/fragments","value":[{"text":"OBEXPutFlagValues","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXPutFlagValues/navigatorTitle","value":[{"kind":"identifier","text":"OBEXPutFlagValues"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag2Reserved/title","value":"kOBEXPutFlag2Reserved","op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag2Reserved/fragments","value":[{"kind":"identifier","text":"kOBEXPutFlag2Reserved"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag5Reserved/title","value":"kOBEXPutFlag5Reserved","op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag5Reserved/fragments","value":[{"text":"kOBEXPutFlag5Reserved","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag6Reserved/title","value":"kOBEXPutFlag6Reserved","op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag6Reserved/fragments","value":[{"text":"kOBEXPutFlag6Reserved","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag4Reserved/title","value":"kOBEXPutFlag4Reserved","op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPutFlag4Reserved/fragments","value":[{"kind":"identifier","text":"kOBEXPutFlag4Reserved"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}