{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagNonce"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@OBEXSessionParameterTags@kOBEXSessionParameterTagNonce",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kOBEXSessionParameterTagNonce"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@OBEXSessionParameterTags",
        "text": "OBEXSessionParameterTags"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kOBEXSessionParameterTagNonce"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kOBEXSessionParameterTagNonce"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kOBEXSessionParameterTagNonce"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionParameterTags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@OBEXSessionParameterTags",
              "text": "OBEXSessionParameterTags"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionParameterTags": {
      "abstract": [
        {
          "text": "Tags for SessionParameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXSessionParameterTags"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionParameterTags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXSessionParameterTags"
        }
      ],
      "role": "symbol",
      "title": "OBEXSessionParameterTags",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexsessionparametertags"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagDeviceAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionParameterTagDeviceAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXSessionParameterTags",
          "text": "OBEXSessionParameterTags"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagDeviceAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionParameterTagDeviceAddress"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionParameterTagDeviceAddress",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessionparametertagdeviceaddress"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagNextSequenceNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionParameterTagNextSequenceNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXSessionParameterTags",
          "text": "OBEXSessionParameterTags"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagNextSequenceNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionParameterTagNextSequenceNumber"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionParameterTagNextSequenceNumber",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessionparametertagnextsequencenumber"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagNonce": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionParameterTagNonce"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXSessionParameterTags",
          "text": "OBEXSessionParameterTags"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagNonce",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionParameterTagNonce"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionParameterTagNonce",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessionparametertagnonce"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagSessionID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionParameterTagSessionID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXSessionParameterTags",
          "text": "OBEXSessionParameterTags"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagSessionID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionParameterTagSessionID"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionParameterTagSessionID",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessionparametertagsessionid"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagSessionOpcode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionParameterTagSessionOpcode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXSessionParameterTags",
          "text": "OBEXSessionParameterTags"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagSessionOpcode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionParameterTagSessionOpcode"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionParameterTagSessionOpcode",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessionparametertagsessionopcode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagTimeout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionParameterTagTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXSessionParameterTags",
          "text": "OBEXSessionParameterTags"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionParameterTagTimeout"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionParameterTagTimeout",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessionparametertagtimeout"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagDeviceAddress",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagNextSequenceNumber",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagSessionID",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagSessionOpcode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagTimeout"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kOBEXSessionParameterTagNonce"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionParameterTagNonce"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionParameterTags"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagDeviceAddress",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagNextSequenceNumber",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagSessionID",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagSessionOpcode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionParameterTagTimeout"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kOBEXSessionParameterTagNonce"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionParameterTagDeviceAddress/title",
          "value": "kOBEXSessionParameterTagDeviceAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionParameterTagDeviceAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionParameterTagDeviceAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionParameterTagNextSequenceNumber/title",
          "value": "kOBEXSessionParameterTagNextSequenceNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionParameterTagNextSequenceNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionParameterTagNextSequenceNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionParameterTagTimeout/title",
          "value": "kOBEXSessionParameterTagTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionParameterTagTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionParameterTagTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionParameterTagSessionOpcode/title",
          "value": "kOBEXSessionParameterTagSessionOpcode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionParameterTagSessionOpcode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionParameterTagSessionOpcode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionParameterTagSessionID/title",
          "value": "kOBEXSessionParameterTagSessionID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionParameterTagSessionID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionParameterTagSessionID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionParameterTagNonce/title",
          "value": "kOBEXSessionParameterTagNonce"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionParameterTagNonce/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionParameterTagNonce"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionParameterTags/title",
          "value": "OBEXSessionParameterTags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionParameterTags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSessionParameterTags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionParameterTags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSessionParameterTags"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kobexsessionparametertagnonce"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kobexsessionparametertagnonce"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
