{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeDatabaseFull"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@OBEXOpCodeResponseValues@kOBEXResponseCodeDatabaseFull",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kOBEXResponseCodeDatabaseFull"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@OBEXOpCodeResponseValues",
        "text": "OBEXOpCodeResponseValues"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kOBEXResponseCodeDatabaseFull"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kOBEXResponseCodeDatabaseFull"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kOBEXResponseCodeDatabaseFull"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeResponseValues",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@OBEXOpCodeResponseValues",
              "text": "OBEXOpCodeResponseValues"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeResponseValues": {
      "abstract": [
        {
          "text": "Response opCode values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXOpCodeResponseValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeResponseValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXOpCodeResponseValues"
        }
      ],
      "role": "symbol",
      "title": "OBEXOpCodeResponseValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexopcoderesponsevalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeAccepted": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeAccepted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeResponseValues",
          "text": "OBEXOpCodeResponseValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeAccepted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeAccepted"
        }
      ],
      "role": "symbol",
      "title": "kOBEXResponseCodeAccepted",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexresponsecodeaccepted"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeAcceptedWithFinalBit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeAcceptedWithFinalBit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeResponseValues",
          "text": "OBEXOpCodeResponseValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeAcceptedWithFinalBit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeAcceptedWithFinalBit"
        }
      ],
      "role": "symbol",
      "title": "kOBEXResponseCodeAcceptedWithFinalBit",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexresponsecodeacceptedwithfinalbit"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeBadGateway": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeBadGateway"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeResponseValues",
          "text": "OBEXOpCodeResponseValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeBadGateway",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeBadGateway"
        }
      ],
      "role": "symbol",
      "title": "kOBEXResponseCodeBadGateway",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexresponsecodebadgateway"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeBadGatewayWithFinalBit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeBadGatewayWithFinalBit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeResponseValues",
          "text": "OBEXOpCodeResponseValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeBadGatewayWithFinalBit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeBadGatewayWithFinalBit"
        }
      ],
      "role": "symbol",
      "title": "kOBEXResponseCodeBadGatewayWithFinalBit",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexresponsecodebadgatewaywithfinalbit"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeBadRequest": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeBadRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeResponseValues",
          "text": "OBEXOpCodeResponseValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeBadRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeBadRequest"
        }
      ],
      "role": "symbol",
      "title": "kOBEXResponseCodeBadRequest",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexresponsecodebadrequest"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeBadRequestWithFinalBit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeBadRequestWithFinalBit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeResponseValues",
          "text": "OBEXOpCodeResponseValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeBadRequestWithFinalBit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeBadRequestWithFinalBit"
        }
      ],
      "role": "symbol",
      "title": "kOBEXResponseCodeBadRequestWithFinalBit",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexresponsecodebadrequestwithfinalbit"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeConflict": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeConflict"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeResponseValues",
          "text": "OBEXOpCodeResponseValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeConflict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeConflict"
        }
      ],
      "role": "symbol",
      "title": "kOBEXResponseCodeConflict",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexresponsecodeconflict"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeConflictWithFinalBit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeConflictWithFinalBit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeResponseValues",
          "text": "OBEXOpCodeResponseValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeConflictWithFinalBit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeConflictWithFinalBit"
        }
      ],
      "role": "symbol",
      "title": "kOBEXResponseCodeConflictWithFinalBit",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexresponsecodeconflictwithfinalbit"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeContinue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeContinue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeResponseValues",
          "text": "OBEXOpCodeResponseValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeContinue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeContinue"
        }
      ],
      "role": "symbol",
      "title": "kOBEXResponseCodeContinue",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexresponsecodecontinue"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeContinueWithFinalBit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeContinueWithFinalBit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeResponseValues",
          "text": "OBEXOpCodeResponseValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeContinueWithFinalBit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeContinueWithFinalBit"
        }
      ],
      "role": "symbol",
      "title": "kOBEXResponseCodeContinueWithFinalBit",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexresponsecodecontinuewithfinalbit"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeCreated": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeCreated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeResponseValues",
          "text": "OBEXOpCodeResponseValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeCreated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeCreated"
        }
      ],
      "role": "symbol",
      "title": "kOBEXResponseCodeCreated",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexresponsecodecreated"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeCreatedWithFinalBit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeCreatedWithFinalBit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeResponseValues",
          "text": "OBEXOpCodeResponseValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeCreatedWithFinalBit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeCreatedWithFinalBit"
        }
      ],
      "role": "symbol",
      "title": "kOBEXResponseCodeCreatedWithFinalBit",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexresponsecodecreatedwithfinalbit"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeDatabaseFull": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeDatabaseFull"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeResponseValues",
          "text": "OBEXOpCodeResponseValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeDatabaseFull",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeDatabaseFull"
        }
      ],
      "role": "symbol",
      "title": "kOBEXResponseCodeDatabaseFull",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexresponsecodedatabasefull"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeDatabaseFullWithFinalBit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeDatabaseFullWithFinalBit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeResponseValues",
          "text": "OBEXOpCodeResponseValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeDatabaseFullWithFinalBit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeDatabaseFullWithFinalBit"
        }
      ],
      "role": "symbol",
      "title": "kOBEXResponseCodeDatabaseFullWithFinalBit",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexresponsecodedatabasefullwithfinalbit"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeDatabaseLocked": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeDatabaseLocked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeResponseValues",
          "text": "OBEXOpCodeResponseValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeDatabaseLocked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeDatabaseLocked"
        }
      ],
      "role": "symbol",
      "title": "kOBEXResponseCodeDatabaseLocked",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexresponsecodedatabaselocked"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeDatabaseLockedWithFinalBit": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeDatabaseLockedWithFinalBit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeResponseValues",
          "text": "OBEXOpCodeResponseValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeDatabaseLockedWithFinalBit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXResponseCodeDatabaseLockedWithFinalBit"
        }
      ],
      "role": "symbol",
      "title": "kOBEXResponseCodeDatabaseLockedWithFinalBit",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexresponsecodedatabaselockedwithfinalbit"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeAccepted",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeAcceptedWithFinalBit",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeBadGateway",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeBadGatewayWithFinalBit",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeBadRequest",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeBadRequestWithFinalBit",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeConflict",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeConflictWithFinalBit",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeContinue",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeContinueWithFinalBit",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeCreated",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeCreatedWithFinalBit",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeDatabaseFullWithFinalBit",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeDatabaseLocked",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeDatabaseLockedWithFinalBit"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kOBEXResponseCodeDatabaseFull"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXResponseCodeDatabaseFull"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeResponseValues"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeAccepted",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeAcceptedWithFinalBit",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeBadGateway",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeBadGatewayWithFinalBit",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeBadRequest",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeBadRequestWithFinalBit",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeConflict",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeConflictWithFinalBit",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeContinue",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeContinueWithFinalBit",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeCreated",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeCreatedWithFinalBit",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeDatabaseFullWithFinalBit",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeDatabaseLocked",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXResponseCodeDatabaseLockedWithFinalBit"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kOBEXResponseCodeDatabaseFull"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeDatabaseFullWithFinalBit/title",
          "value": "kOBEXResponseCodeDatabaseFullWithFinalBit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeDatabaseFullWithFinalBit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXResponseCodeDatabaseFullWithFinalBit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeDatabaseLockedWithFinalBit/title",
          "value": "kOBEXResponseCodeDatabaseLockedWithFinalBit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeDatabaseLockedWithFinalBit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXResponseCodeDatabaseLockedWithFinalBit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeAccepted/title",
          "value": "kOBEXResponseCodeAccepted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeAccepted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXResponseCodeAccepted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeDatabaseLocked/title",
          "value": "kOBEXResponseCodeDatabaseLocked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeDatabaseLocked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXResponseCodeDatabaseLocked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeCreated/title",
          "value": "kOBEXResponseCodeCreated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeCreated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXResponseCodeCreated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeBadRequest/title",
          "value": "kOBEXResponseCodeBadRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeBadRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXResponseCodeBadRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeDatabaseFull/title",
          "value": "kOBEXResponseCodeDatabaseFull"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeDatabaseFull/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXResponseCodeDatabaseFull"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeContinue/title",
          "value": "kOBEXResponseCodeContinue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeContinue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXResponseCodeContinue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeConflict/title",
          "value": "kOBEXResponseCodeConflict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeConflict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXResponseCodeConflict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeConflictWithFinalBit/title",
          "value": "kOBEXResponseCodeConflictWithFinalBit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeConflictWithFinalBit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXResponseCodeConflictWithFinalBit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeBadGateway/title",
          "value": "kOBEXResponseCodeBadGateway"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeBadGateway/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXResponseCodeBadGateway"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeContinueWithFinalBit/title",
          "value": "kOBEXResponseCodeContinueWithFinalBit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeContinueWithFinalBit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXResponseCodeContinueWithFinalBit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXOpCodeResponseValues/title",
          "value": "OBEXOpCodeResponseValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXOpCodeResponseValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXOpCodeResponseValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXOpCodeResponseValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXOpCodeResponseValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeCreatedWithFinalBit/title",
          "value": "kOBEXResponseCodeCreatedWithFinalBit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeCreatedWithFinalBit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXResponseCodeCreatedWithFinalBit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeBadGatewayWithFinalBit/title",
          "value": "kOBEXResponseCodeBadGatewayWithFinalBit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeBadGatewayWithFinalBit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXResponseCodeBadGatewayWithFinalBit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeAcceptedWithFinalBit/title",
          "value": "kOBEXResponseCodeAcceptedWithFinalBit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeAcceptedWithFinalBit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXResponseCodeAcceptedWithFinalBit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeBadRequestWithFinalBit/title",
          "value": "kOBEXResponseCodeBadRequestWithFinalBit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXResponseCodeBadRequestWithFinalBit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXResponseCodeBadRequestWithFinalBit"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kobexresponsecodedatabasefull"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kobexresponsecodedatabasefull"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
