{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeSuspendSession"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@OBEXOpCodeSessionValues@kOBEXOpCodeSuspendSession",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kOBEXOpCodeSuspendSession"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@OBEXOpCodeSessionValues",
        "text": "OBEXOpCodeSessionValues"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kOBEXOpCodeSuspendSession"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kOBEXOpCodeSuspendSession"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kOBEXOpCodeSuspendSession"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeSessionValues",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@OBEXOpCodeSessionValues",
              "text": "OBEXOpCodeSessionValues"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeSessionValues": {
      "abstract": [
        {
          "text": "Operation OpCode values for sessions. From the OBEX 1.3 specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXOpCodeSessionValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeSessionValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXOpCodeSessionValues"
        }
      ],
      "role": "symbol",
      "title": "OBEXOpCodeSessionValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexopcodesessionvalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeCloseSession": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeCloseSession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeSessionValues",
          "text": "OBEXOpCodeSessionValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeCloseSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeCloseSession"
        }
      ],
      "role": "symbol",
      "title": "kOBEXOpCodeCloseSession",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexopcodeclosesession"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeCreateSession": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeCreateSession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeSessionValues",
          "text": "OBEXOpCodeSessionValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeCreateSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeCreateSession"
        }
      ],
      "role": "symbol",
      "title": "kOBEXOpCodeCreateSession",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexopcodecreatesession"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeResumeSession": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeResumeSession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeSessionValues",
          "text": "OBEXOpCodeSessionValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeResumeSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeResumeSession"
        }
      ],
      "role": "symbol",
      "title": "kOBEXOpCodeResumeSession",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexopcoderesumesession"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeSetTimeout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeSetTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeSessionValues",
          "text": "OBEXOpCodeSessionValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeSetTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeSetTimeout"
        }
      ],
      "role": "symbol",
      "title": "kOBEXOpCodeSetTimeout",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexopcodesettimeout"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeSuspendSession": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeSuspendSession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXOpCodeSessionValues",
          "text": "OBEXOpCodeSessionValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeSuspendSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXOpCodeSuspendSession"
        }
      ],
      "role": "symbol",
      "title": "kOBEXOpCodeSuspendSession",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexopcodesuspendsession"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeCloseSession",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeCreateSession",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeResumeSession",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeSetTimeout"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kOBEXOpCodeSuspendSession"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXOpCodeSuspendSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeSessionValues"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeCloseSession",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeCreateSession",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeResumeSession",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXOpCodeSetTimeout"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kOBEXOpCodeSuspendSession"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeSuspendSession/title",
          "value": "kOBEXOpCodeSuspendSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeSuspendSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXOpCodeSuspendSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeResumeSession/title",
          "value": "kOBEXOpCodeResumeSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeResumeSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXOpCodeResumeSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeCloseSession/title",
          "value": "kOBEXOpCodeCloseSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeCloseSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXOpCodeCloseSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeCreateSession/title",
          "value": "kOBEXOpCodeCreateSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeCreateSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXOpCodeCreateSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeSetTimeout/title",
          "value": "kOBEXOpCodeSetTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXOpCodeSetTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXOpCodeSetTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXOpCodeSessionValues/title",
          "value": "OBEXOpCodeSessionValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXOpCodeSessionValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXOpCodeSessionValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXOpCodeSessionValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXOpCodeSessionValues"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kobexopcodesuspendsession"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kobexopcodesuspendsession"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
