{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlagAccessModeReadOnly"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@OBEXNonceFlagValues@kOBEXNonceFlagAccessModeReadOnly",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kOBEXNonceFlagAccessModeReadOnly"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@OBEXNonceFlagValues",
        "text": "OBEXNonceFlagValues"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kOBEXNonceFlagAccessModeReadOnly"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kOBEXNonceFlagAccessModeReadOnly"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kOBEXNonceFlagAccessModeReadOnly"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXNonceFlagValues",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@OBEXNonceFlagValues",
              "text": "OBEXNonceFlagValues"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXNonceFlagValues": {
      "abstract": [
        {
          "text": "Flags for Nonce command during digest challenge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXNonceFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXNonceFlagValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXNonceFlagValues"
        }
      ],
      "role": "symbol",
      "title": "OBEXNonceFlagValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexnonceflagvalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag2Reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXNonceFlag2Reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXNonceFlagValues",
          "text": "OBEXNonceFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag2Reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXNonceFlag2Reserved"
        }
      ],
      "role": "symbol",
      "title": "kOBEXNonceFlag2Reserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexnonceflag2reserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag3Reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXNonceFlag3Reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXNonceFlagValues",
          "text": "OBEXNonceFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag3Reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXNonceFlag3Reserved"
        }
      ],
      "role": "symbol",
      "title": "kOBEXNonceFlag3Reserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexnonceflag3reserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag4Reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXNonceFlag4Reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXNonceFlagValues",
          "text": "OBEXNonceFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag4Reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXNonceFlag4Reserved"
        }
      ],
      "role": "symbol",
      "title": "kOBEXNonceFlag4Reserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexnonceflag4reserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag5Reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXNonceFlag5Reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXNonceFlagValues",
          "text": "OBEXNonceFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag5Reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXNonceFlag5Reserved"
        }
      ],
      "role": "symbol",
      "title": "kOBEXNonceFlag5Reserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexnonceflag5reserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag6Reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXNonceFlag6Reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXNonceFlagValues",
          "text": "OBEXNonceFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag6Reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXNonceFlag6Reserved"
        }
      ],
      "role": "symbol",
      "title": "kOBEXNonceFlag6Reserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexnonceflag6reserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag7Reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXNonceFlag7Reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXNonceFlagValues",
          "text": "OBEXNonceFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag7Reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXNonceFlag7Reserved"
        }
      ],
      "role": "symbol",
      "title": "kOBEXNonceFlag7Reserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexnonceflag7reserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlagAccessModeReadOnly": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXNonceFlagAccessModeReadOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXNonceFlagValues",
          "text": "OBEXNonceFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlagAccessModeReadOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXNonceFlagAccessModeReadOnly"
        }
      ],
      "role": "symbol",
      "title": "kOBEXNonceFlagAccessModeReadOnly",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexnonceflagaccessmodereadonly"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlagNone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXNonceFlagNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXNonceFlagValues",
          "text": "OBEXNonceFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlagNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXNonceFlagNone"
        }
      ],
      "role": "symbol",
      "title": "kOBEXNonceFlagNone",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexnonceflagnone"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlagSendUserIDInResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXNonceFlagSendUserIDInResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXNonceFlagValues",
          "text": "OBEXNonceFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlagSendUserIDInResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXNonceFlagSendUserIDInResponse"
        }
      ],
      "role": "symbol",
      "title": "kOBEXNonceFlagSendUserIDInResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexnonceflagsenduseridinresponse"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag2Reserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag3Reserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag4Reserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag5Reserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag6Reserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag7Reserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlagNone",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlagSendUserIDInResponse"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kOBEXNonceFlagAccessModeReadOnly"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXNonceFlagAccessModeReadOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXNonceFlagValues"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag2Reserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag3Reserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag4Reserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag5Reserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag6Reserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlag7Reserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlagNone",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNonceFlagSendUserIDInResponse"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kOBEXNonceFlagAccessModeReadOnly"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNonceFlagNone/title",
          "value": "kOBEXNonceFlagNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNonceFlagNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXNonceFlagNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNonceFlag7Reserved/title",
          "value": "kOBEXNonceFlag7Reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNonceFlag7Reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXNonceFlag7Reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNonceFlag3Reserved/title",
          "value": "kOBEXNonceFlag3Reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNonceFlag3Reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXNonceFlag3Reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXNonceFlagValues/title",
          "value": "OBEXNonceFlagValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXNonceFlagValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXNonceFlagValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXNonceFlagValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXNonceFlagValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNonceFlagSendUserIDInResponse/title",
          "value": "kOBEXNonceFlagSendUserIDInResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNonceFlagSendUserIDInResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXNonceFlagSendUserIDInResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNonceFlag4Reserved/title",
          "value": "kOBEXNonceFlag4Reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNonceFlag4Reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXNonceFlag4Reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNonceFlagAccessModeReadOnly/title",
          "value": "kOBEXNonceFlagAccessModeReadOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNonceFlagAccessModeReadOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXNonceFlagAccessModeReadOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNonceFlag5Reserved/title",
          "value": "kOBEXNonceFlag5Reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNonceFlag5Reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXNonceFlag5Reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNonceFlag6Reserved/title",
          "value": "kOBEXNonceFlag6Reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNonceFlag6Reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXNonceFlag6Reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNonceFlag2Reserved/title",
          "value": "kOBEXNonceFlag2Reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNonceFlag2Reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXNonceFlag2Reserved"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kobexnonceflagaccessmodereadonly"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kobexnonceflagaccessmodereadonly"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
