{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88592"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@OBEXRealmValues@kOBEXRealmISO88592",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kOBEXRealmISO88592"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@OBEXRealmValues",
        "text": "OBEXRealmValues"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kOBEXRealmISO88592"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kOBEXRealmISO88592"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kOBEXRealmISO88592"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@OBEXRealmValues",
              "text": "OBEXRealmValues"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues": {
      "abstract": [
        {
          "text": "Values for Realm during digest response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXRealmValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXRealmValues"
        }
      ],
      "role": "symbol",
      "title": "OBEXRealmValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexrealmvalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmASCII": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXRealmASCII"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXRealmValues",
          "text": "OBEXRealmValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmASCII",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXRealmASCII"
        }
      ],
      "role": "symbol",
      "title": "kOBEXRealmASCII",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexrealmascii"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88591": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXRealmISO88591"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXRealmValues",
          "text": "OBEXRealmValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88591",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXRealmISO88591"
        }
      ],
      "role": "symbol",
      "title": "kOBEXRealmISO88591",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexrealmiso88591"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88592": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXRealmISO88592"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXRealmValues",
          "text": "OBEXRealmValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88592",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXRealmISO88592"
        }
      ],
      "role": "symbol",
      "title": "kOBEXRealmISO88592",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexrealmiso88592"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88593": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXRealmISO88593"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXRealmValues",
          "text": "OBEXRealmValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88593",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXRealmISO88593"
        }
      ],
      "role": "symbol",
      "title": "kOBEXRealmISO88593",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexrealmiso88593"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88594": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXRealmISO88594"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXRealmValues",
          "text": "OBEXRealmValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88594",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXRealmISO88594"
        }
      ],
      "role": "symbol",
      "title": "kOBEXRealmISO88594",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexrealmiso88594"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88595": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXRealmISO88595"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXRealmValues",
          "text": "OBEXRealmValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88595",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXRealmISO88595"
        }
      ],
      "role": "symbol",
      "title": "kOBEXRealmISO88595",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexrealmiso88595"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88596": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXRealmISO88596"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXRealmValues",
          "text": "OBEXRealmValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88596",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXRealmISO88596"
        }
      ],
      "role": "symbol",
      "title": "kOBEXRealmISO88596",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexrealmiso88596"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88597": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXRealmISO88597"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXRealmValues",
          "text": "OBEXRealmValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88597",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXRealmISO88597"
        }
      ],
      "role": "symbol",
      "title": "kOBEXRealmISO88597",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexrealmiso88597"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88598": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXRealmISO88598"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXRealmValues",
          "text": "OBEXRealmValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88598",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXRealmISO88598"
        }
      ],
      "role": "symbol",
      "title": "kOBEXRealmISO88598",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexrealmiso88598"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88599": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXRealmISO88599"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXRealmValues",
          "text": "OBEXRealmValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88599",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXRealmISO88599"
        }
      ],
      "role": "symbol",
      "title": "kOBEXRealmISO88599",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexrealmiso88599"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmUNICODE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXRealmUNICODE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXRealmValues",
          "text": "OBEXRealmValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmUNICODE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXRealmUNICODE"
        }
      ],
      "role": "symbol",
      "title": "kOBEXRealmUNICODE",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexrealmunicode"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmASCII",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88591",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88593",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88594",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88595",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88596",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88597",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88598",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88599",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmUNICODE"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kOBEXRealmISO88592"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXRealmISO88592"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmASCII",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88591",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88593",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88594",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88595",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88596",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88597",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88598",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88599",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmUNICODE"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kOBEXRealmISO88592"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88591/title",
          "value": "kOBEXRealmISO88591"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88591/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXRealmISO88591"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88594/title",
          "value": "kOBEXRealmISO88594"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88594/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXRealmISO88594"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88592/title",
          "value": "kOBEXRealmISO88592"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88592/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXRealmISO88592"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmASCII/title",
          "value": "kOBEXRealmASCII"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmASCII/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXRealmASCII"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88598/title",
          "value": "kOBEXRealmISO88598"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88598/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXRealmISO88598"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88595/title",
          "value": "kOBEXRealmISO88595"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88595/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXRealmISO88595"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmUNICODE/title",
          "value": "kOBEXRealmUNICODE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmUNICODE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXRealmUNICODE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88597/title",
          "value": "kOBEXRealmISO88597"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88597/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXRealmISO88597"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88599/title",
          "value": "kOBEXRealmISO88599"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88599/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXRealmISO88599"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXRealmValues/title",
          "value": "OBEXRealmValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXRealmValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXRealmValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXRealmValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXRealmValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88596/title",
          "value": "kOBEXRealmISO88596"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88596/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXRealmISO88596"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88593/title",
          "value": "kOBEXRealmISO88593"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88593/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXRealmISO88593"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kobexrealmiso88592"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kobexrealmiso88592"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
