{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag5Reserved"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@OBEXConnectFlagValues@kOBEXConnectFlag5Reserved",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kOBEXConnectFlag5Reserved"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@OBEXConnectFlagValues",
        "text": "OBEXConnectFlagValues"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kOBEXConnectFlag5Reserved"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kOBEXConnectFlag5Reserved"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kOBEXConnectFlag5Reserved"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectFlagValues",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@OBEXConnectFlagValues",
              "text": "OBEXConnectFlagValues"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectFlagValues": {
      "abstract": [
        {
          "text": "Flags for Connect command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXConnectFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectFlagValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXConnectFlagValues"
        }
      ],
      "role": "symbol",
      "title": "OBEXConnectFlagValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexconnectflagvalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag1Reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXConnectFlag1Reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXConnectFlagValues",
          "text": "OBEXConnectFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag1Reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXConnectFlag1Reserved"
        }
      ],
      "role": "symbol",
      "title": "kOBEXConnectFlag1Reserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexconnectflag1reserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag2Reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXConnectFlag2Reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXConnectFlagValues",
          "text": "OBEXConnectFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag2Reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXConnectFlag2Reserved"
        }
      ],
      "role": "symbol",
      "title": "kOBEXConnectFlag2Reserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexconnectflag2reserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag3Reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXConnectFlag3Reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXConnectFlagValues",
          "text": "OBEXConnectFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag3Reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXConnectFlag3Reserved"
        }
      ],
      "role": "symbol",
      "title": "kOBEXConnectFlag3Reserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexconnectflag3reserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag4Reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXConnectFlag4Reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXConnectFlagValues",
          "text": "OBEXConnectFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag4Reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXConnectFlag4Reserved"
        }
      ],
      "role": "symbol",
      "title": "kOBEXConnectFlag4Reserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexconnectflag4reserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag5Reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXConnectFlag5Reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXConnectFlagValues",
          "text": "OBEXConnectFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag5Reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXConnectFlag5Reserved"
        }
      ],
      "role": "symbol",
      "title": "kOBEXConnectFlag5Reserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexconnectflag5reserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag6Reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXConnectFlag6Reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXConnectFlagValues",
          "text": "OBEXConnectFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag6Reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXConnectFlag6Reserved"
        }
      ],
      "role": "symbol",
      "title": "kOBEXConnectFlag6Reserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexconnectflag6reserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag7Reserved": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXConnectFlag7Reserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXConnectFlagValues",
          "text": "OBEXConnectFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag7Reserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXConnectFlag7Reserved"
        }
      ],
      "role": "symbol",
      "title": "kOBEXConnectFlag7Reserved",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexconnectflag7reserved"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlagNone": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXConnectFlagNone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXConnectFlagValues",
          "text": "OBEXConnectFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlagNone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXConnectFlagNone"
        }
      ],
      "role": "symbol",
      "title": "kOBEXConnectFlagNone",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexconnectflagnone"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlagSupportMultipleItLMPConnections": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXConnectFlagSupportMultipleItLMPConnections"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXConnectFlagValues",
          "text": "OBEXConnectFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlagSupportMultipleItLMPConnections",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXConnectFlagSupportMultipleItLMPConnections"
        }
      ],
      "role": "symbol",
      "title": "kOBEXConnectFlagSupportMultipleItLMPConnections",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexconnectflagsupportmultipleitlmpconnections"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag1Reserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag2Reserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag3Reserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag4Reserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag6Reserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag7Reserved",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlagNone",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlagSupportMultipleItLMPConnections"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kOBEXConnectFlag5Reserved"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXConnectFlag5Reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectFlagValues"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag1Reserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag2Reserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag3Reserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag4Reserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag6Reserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlag7Reserved",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlagNone",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConnectFlagSupportMultipleItLMPConnections"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kOBEXConnectFlag5Reserved"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConnectFlag1Reserved/title",
          "value": "kOBEXConnectFlag1Reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConnectFlag1Reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXConnectFlag1Reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConnectFlag7Reserved/title",
          "value": "kOBEXConnectFlag7Reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConnectFlag7Reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXConnectFlag7Reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConnectFlag4Reserved/title",
          "value": "kOBEXConnectFlag4Reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConnectFlag4Reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXConnectFlag4Reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConnectFlag2Reserved/title",
          "value": "kOBEXConnectFlag2Reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConnectFlag2Reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXConnectFlag2Reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConnectFlag3Reserved/title",
          "value": "kOBEXConnectFlag3Reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConnectFlag3Reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXConnectFlag3Reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConnectFlagNone/title",
          "value": "kOBEXConnectFlagNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConnectFlagNone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXConnectFlagNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConnectFlag5Reserved/title",
          "value": "kOBEXConnectFlag5Reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConnectFlag5Reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXConnectFlag5Reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConnectFlagSupportMultipleItLMPConnections/title",
          "value": "kOBEXConnectFlagSupportMultipleItLMPConnections"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConnectFlagSupportMultipleItLMPConnections/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXConnectFlagSupportMultipleItLMPConnections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConnectFlag6Reserved/title",
          "value": "kOBEXConnectFlag6Reserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConnectFlag6Reserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXConnectFlag6Reserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXConnectFlagValues/title",
          "value": "OBEXConnectFlagValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXConnectFlagValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXConnectFlagValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXConnectFlagValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXConnectFlagValues"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/kobexconnectflag5reserved"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/kobexconnectflag5reserved"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
