{"seeAlsoSections":[{"title":"Constants","anchor":"Constants","identifiers":["doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmASCII","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88591","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88592","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88593","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88594","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88595","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88596","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88597","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88598","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmUNICODE"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88599"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iobluetooth/documentation/IOBluetooth"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kOBEXRealmISO88599","kind":"identifier"},{"text":": ","kind":"text"},{"text":"OBEXRealmValues","preciseIdentifier":"c:@E@OBEXRealmValues","kind":"typeIdentifier","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/iobluetooth/kobexrealmiso88599"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/iobluetooth/kobexrealmiso88599"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"kOBEXRealmISO88599"}],"externalID":"c:@E@OBEXRealmValues@kOBEXRealmISO88599","roleHeading":"Global Variable","title":"kOBEXRealmISO88599","modules":[{"name":"IOBluetooth"}],"symbolKind":"var","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXRealmISO88599"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@OBEXRealmValues","text":"OBEXRealmValues"}],"platforms":[{"deprecated":false,"name":"macOS","beta":false,"unavailable":false}]},"sections":[],"references":{"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmASCII":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXRealmASCII"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXRealmValues","kind":"typeIdentifier","text":"OBEXRealmValues"}],"navigatorTitle":[{"kind":"identifier","text":"kOBEXRealmASCII"}],"url":"/documentation/iobluetooth/kobexrealmascii","abstract":[],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmASCII","role":"symbol","type":"topic","title":"kOBEXRealmASCII"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88594":{"navigatorTitle":[{"text":"kOBEXRealmISO88594","kind":"identifier"}],"type":"topic","title":"kOBEXRealmISO88594","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kOBEXRealmISO88594"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXRealmValues","text":"OBEXRealmValues","kind":"typeIdentifier"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88594","url":"/documentation/iobluetooth/kobexrealmiso88594","kind":"symbol","role":"symbol"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88599":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXRealmISO88599"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXRealmValues","kind":"typeIdentifier","text":"OBEXRealmValues"}],"url":"/documentation/iobluetooth/kobexrealmiso88599","role":"symbol","title":"kOBEXRealmISO88599","kind":"symbol","type":"topic","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88599","navigatorTitle":[{"kind":"identifier","text":"kOBEXRealmISO88599"}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88595":{"navigatorTitle":[{"kind":"identifier","text":"kOBEXRealmISO88595"}],"type":"topic","title":"kOBEXRealmISO88595","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXRealmISO88595"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXRealmValues","kind":"typeIdentifier","text":"OBEXRealmValues"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88595","url":"/documentation/iobluetooth/kobexrealmiso88595","kind":"symbol","role":"symbol"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues":{"url":"/documentation/iobluetooth/obexrealmvalues","navigatorTitle":[{"text":"OBEXRealmValues","kind":"identifier"}],"title":"OBEXRealmValues","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBEXRealmValues","kind":"identifier"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues","kind":"symbol","abstract":[{"text":"Values for Realm during digest response.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88597":{"navigatorTitle":[{"kind":"identifier","text":"kOBEXRealmISO88597"}],"type":"topic","title":"kOBEXRealmISO88597","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXRealmISO88597"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXRealmValues","kind":"typeIdentifier","text":"OBEXRealmValues"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88597","url":"/documentation/iobluetooth/kobexrealmiso88597","kind":"symbol","role":"symbol"},"doc://com.apple.iobluetooth/documentation/IOBluetooth":{"kind":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth","abstract":[{"type":"text","text":"Gain user-space access to Bluetooth devices."}],"url":"/documentation/iobluetooth","role":"collection","type":"topic","title":"IOBluetooth"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88598":{"kind":"symbol","title":"kOBEXRealmISO88598","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88598","navigatorTitle":[{"text":"kOBEXRealmISO88598","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXRealmISO88598"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@OBEXRealmValues","text":"OBEXRealmValues","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"/documentation/iobluetooth/kobexrealmiso88598","abstract":[]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88596":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXRealmISO88596"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXRealmValues","kind":"typeIdentifier","text":"OBEXRealmValues"}],"navigatorTitle":[{"kind":"identifier","text":"kOBEXRealmISO88596"}],"url":"/documentation/iobluetooth/kobexrealmiso88596","abstract":[],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88596","role":"symbol","type":"topic","title":"kOBEXRealmISO88596"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmUNICODE":{"navigatorTitle":[{"kind":"identifier","text":"kOBEXRealmUNICODE"}],"type":"topic","title":"kOBEXRealmUNICODE","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kOBEXRealmUNICODE","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXRealmValues","kind":"typeIdentifier","text":"OBEXRealmValues"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmUNICODE","url":"/documentation/iobluetooth/kobexrealmunicode","kind":"symbol","role":"symbol"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88591":{"abstract":[],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88591","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXRealmISO88591"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXRealmValues","kind":"typeIdentifier","text":"OBEXRealmValues"}],"title":"kOBEXRealmISO88591","url":"/documentation/iobluetooth/kobexrealmiso88591","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kOBEXRealmISO88591"}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88592":{"navigatorTitle":[{"kind":"identifier","text":"kOBEXRealmISO88592"}],"type":"topic","title":"kOBEXRealmISO88592","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXRealmISO88592"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXRealmValues","kind":"typeIdentifier","text":"OBEXRealmValues"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88592","url":"/documentation/iobluetooth/kobexrealmiso88592","kind":"symbol","role":"symbol"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88593":{"navigatorTitle":[{"kind":"identifier","text":"kOBEXRealmISO88593"}],"type":"topic","title":"kOBEXRealmISO88593","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXRealmISO88593"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXRealmValues","kind":"typeIdentifier","text":"OBEXRealmValues"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88593","url":"/documentation/iobluetooth/kobexrealmiso88593","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"name":"macOS","unavailable":false,"deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Enumeration Case","path":"/metadata/roleHeading","op":"replace"},{"value":"kOBEXRealmISO88599","path":"/metadata/title","op":"replace"},{"value":"case","path":"/metadata/symbolKind","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"kOBEXRealmISO88599","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iobluetooth/documentation/IOBluetooth","doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmASCII","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88591","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88592","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88593","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88594","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88595","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88596","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88597","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88598","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmUNICODE"],"title":"Constants","anchor":"Constants"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"kOBEXRealmISO88599","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"kOBEXRealmASCII","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmASCII/title"},{"op":"replace","value":[{"kind":"identifier","text":"kOBEXRealmASCII"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmASCII/fragments"},{"op":"replace","value":"kOBEXRealmISO88594","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88594/title"},{"op":"replace","value":[{"text":"kOBEXRealmISO88594","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88594/fragments"},{"op":"replace","value":"kOBEXRealmISO88599","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88599/title"},{"op":"replace","value":[{"text":"kOBEXRealmISO88599","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88599/fragments"},{"op":"replace","value":"kOBEXRealmISO88595","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88595/title"},{"op":"replace","value":[{"kind":"identifier","text":"kOBEXRealmISO88595"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88595/fragments"},{"op":"replace","value":"OBEXRealmValues","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXRealmValues/title"},{"op":"replace","value":[{"kind":"identifier","text":"OBEXRealmValues"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXRealmValues/fragments"},{"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXRealmValues/navigatorTitle","value":[{"text":"OBEXRealmValues","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88597/title","value":"kOBEXRealmISO88597"},{"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88597/fragments","value":[{"kind":"identifier","text":"kOBEXRealmISO88597"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88598/title","value":"kOBEXRealmISO88598"},{"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88598/fragments","value":[{"text":"kOBEXRealmISO88598","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88596/title","value":"kOBEXRealmISO88596"},{"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88596/fragments","value":[{"kind":"identifier","text":"kOBEXRealmISO88596"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmUNICODE/title","value":"kOBEXRealmUNICODE"},{"value":[{"kind":"identifier","text":"kOBEXRealmUNICODE"}],"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmUNICODE/fragments"},{"value":"kOBEXRealmISO88591","op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88591/title"},{"value":[{"kind":"identifier","text":"kOBEXRealmISO88591"}],"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88591/fragments"},{"value":"kOBEXRealmISO88592","op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88592/title"},{"value":[{"text":"kOBEXRealmISO88592","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88592/fragments"},{"value":"kOBEXRealmISO88593","op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88593/title"},{"value":[{"kind":"identifier","text":"kOBEXRealmISO88593"}],"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88593/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}