{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@OBEXSessionEvent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "OBEXSessionEvent"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "OBEXSessionEvent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "OBEXSessionEvent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "OBEXSessionEvent"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When a new session event occurs, your selector (or C callback) will be given an OBEXSessionEvent pointer, and in it will be information you might find interesting so that you can then reply back appropriately. For example, of you receive a kOBEXSessionEventTypeConnectCommandResponseReceived event, you can then parse out the information related to that event, and if all looks well to you, you could them send a “Get” command to get a file off of the OBEX server you just connected to.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAbortCommandData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAbortCommandData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAbortCommandData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAbortCommandData"
        }
      ],
      "role": "symbol",
      "title": "OBEXAbortCommandData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexabortcommanddata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAbortCommandResponseData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAbortCommandResponseData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAbortCommandResponseData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAbortCommandResponseData"
        }
      ],
      "role": "symbol",
      "title": "OBEXAbortCommandResponseData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexabortcommandresponsedata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectCommandData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXConnectCommandData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectCommandData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXConnectCommandData"
        }
      ],
      "role": "symbol",
      "title": "OBEXConnectCommandData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexconnectcommanddata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectCommandResponseData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXConnectCommandResponseData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectCommandResponseData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXConnectCommandResponseData"
        }
      ],
      "role": "symbol",
      "title": "OBEXConnectCommandResponseData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexconnectcommandresponsedata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXDisconnectCommandData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXDisconnectCommandData"
        }
      ],
      "role": "symbol",
      "title": "OBEXDisconnectCommandData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexdisconnectcommanddata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandResponseData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXDisconnectCommandResponseData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandResponseData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXDisconnectCommandResponseData"
        }
      ],
      "role": "symbol",
      "title": "OBEXDisconnectCommandResponseData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexdisconnectcommandresponsedata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXErrorData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXErrorData"
        }
      ],
      "role": "symbol",
      "title": "OBEXErrorData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexerrordata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXGetCommandData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXGetCommandData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXGetCommandData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXGetCommandData"
        }
      ],
      "role": "symbol",
      "title": "OBEXGetCommandData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexgetcommanddata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXGetCommandResponseData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXGetCommandResponseData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXGetCommandResponseData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXGetCommandResponseData"
        }
      ],
      "role": "symbol",
      "title": "OBEXGetCommandResponseData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexgetcommandresponsedata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutCommandData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXPutCommandData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutCommandData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXPutCommandData"
        }
      ],
      "role": "symbol",
      "title": "OBEXPutCommandData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexputcommanddata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutCommandResponseData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXPutCommandResponseData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutCommandResponseData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXPutCommandResponseData"
        }
      ],
      "role": "symbol",
      "title": "OBEXPutCommandResponseData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexputcommandresponsedata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXSessionEvent"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXSessionEvent"
        }
      ],
      "role": "symbol",
      "title": "OBEXSessionEvent",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexsessionevent"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexsessionevent/init()"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/init(type:session:refCon:isEndOfEventData:reserved1:reserved2:u:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXSessionEventType",
          "text": "OBEXSessionEventType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "session"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXSessionRef",
          "text": "OBEXSessionRef"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "refCon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "isEndOfEventData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reserved1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "reserved2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "u"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@OBEXSessionEvent",
          "text": "OBEXSessionEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_union_u"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/init(type:session:refCon:isEndOfEventData:reserved1:reserved2:u:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(type:session:refCon:isEndOfEventData:reserved1:reserved2:u:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexsessionevent/init(type:session:refcon:isendofeventdata:reserved1:reserved2:u:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/isEndOfEventData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEndOfEventData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:6Darwin0A7BooleanV",
          "text": "DarwinBoolean"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/isEndOfEventData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isEndOfEventData"
        }
      ],
      "role": "symbol",
      "title": "isEndOfEventData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexsessionevent/isendofeventdata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/refCon": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "refCon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/refCon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "refCon"
        }
      ],
      "role": "symbol",
      "title": "refCon",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexsessionevent/refcon"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/reserved1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reserved1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/reserved1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reserved1"
        }
      ],
      "role": "symbol",
      "title": "reserved1",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexsessionevent/reserved1"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/reserved2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reserved2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/reserved2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reserved2"
        }
      ],
      "role": "symbol",
      "title": "reserved2",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexsessionevent/reserved2"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/session": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "session"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXSessionRef",
          "text": "OBEXSessionRef"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/session",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "session"
        }
      ],
      "role": "symbol",
      "title": "session",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexsessionevent/session"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/type": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXSessionEventType",
          "text": "OBEXSessionEventType"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexsessionevent/type"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/u": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "u"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@OBEXSessionEvent",
          "text": "OBEXSessionEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_union_u"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/u",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "u"
        }
      ],
      "role": "symbol",
      "title": "u",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexsessionevent/u"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSetPathCommandData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXSetPathCommandData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSetPathCommandData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXSetPathCommandData"
        }
      ],
      "role": "symbol",
      "title": "OBEXSetPathCommandData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexsetpathcommanddata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSetPathCommandResponseData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXSetPathCommandResponseData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSetPathCommandResponseData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXSetPathCommandResponseData"
        }
      ],
      "role": "symbol",
      "title": "OBEXSetPathCommandResponseData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexsetpathcommandresponsedata"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAbortCommandData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAbortCommandResponseData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectCommandData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectCommandResponseData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandResponseData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXGetCommandData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXGetCommandResponseData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutCommandData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutCommandResponseData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSetPathCommandData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSetPathCommandResponseData"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/init()",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/init(type:session:refCon:isEndOfEventData:reserved1:reserved2:u:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/isEndOfEventData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/refCon",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/reserved1",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/reserved2",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/session",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/type",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/u"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "OBEXSessionEvent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSessionEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSessionEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/isEndOfEventData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/refCon",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/reserved1",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/reserved2",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/session",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/type",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent/u"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAbortCommandData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAbortCommandResponseData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectCommandData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectCommandResponseData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandResponseData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXGetCommandData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXGetCommandResponseData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutCommandData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutCommandResponseData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSetPathCommandData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSetPathCommandResponseData"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "OBEXSessionEvent"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEvent~1session/title",
          "value": "session"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEvent~1session/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "session"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEvent~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEvent~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXGetCommandResponseData/title",
          "value": "OBEXGetCommandResponseData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXGetCommandResponseData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXGetCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXGetCommandResponseData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXGetCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEvent~1refCon/title",
          "value": "refCon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEvent~1refCon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "refCon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXPutCommandResponseData/title",
          "value": "OBEXPutCommandResponseData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXPutCommandResponseData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXPutCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXPutCommandResponseData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXPutCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXPutCommandData/title",
          "value": "OBEXPutCommandData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXPutCommandData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXPutCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXPutCommandData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXPutCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSetPathCommandData/title",
          "value": "OBEXSetPathCommandData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSetPathCommandData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSetPathCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSetPathCommandData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSetPathCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEvent~1reserved2/title",
          "value": "reserved2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEvent~1reserved2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reserved2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEvent/title",
          "value": "OBEXSessionEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSessionEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSessionEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEvent~1u/title",
          "value": "u"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEvent~1u/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "u"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEvent~1reserved1/title",
          "value": "reserved1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEvent~1reserved1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reserved1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXConnectCommandResponseData/title",
          "value": "OBEXConnectCommandResponseData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXConnectCommandResponseData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXConnectCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXConnectCommandResponseData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXConnectCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAbortCommandData/title",
          "value": "OBEXAbortCommandData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAbortCommandData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAbortCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAbortCommandData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAbortCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEvent~1isEndOfEventData/title",
          "value": "isEndOfEventData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEvent~1isEndOfEventData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isEndOfEventData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXConnectCommandData/title",
          "value": "OBEXConnectCommandData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXConnectCommandData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXConnectCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXConnectCommandData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXConnectCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAbortCommandResponseData/title",
          "value": "OBEXAbortCommandResponseData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAbortCommandResponseData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAbortCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAbortCommandResponseData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAbortCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSetPathCommandResponseData/title",
          "value": "OBEXSetPathCommandResponseData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSetPathCommandResponseData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSetPathCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSetPathCommandResponseData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSetPathCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXDisconnectCommandData/title",
          "value": "OBEXDisconnectCommandData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXDisconnectCommandData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXDisconnectCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXDisconnectCommandData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXDisconnectCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXGetCommandData/title",
          "value": "OBEXGetCommandData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXGetCommandData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXGetCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXGetCommandData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXGetCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXErrorData/title",
          "value": "OBEXErrorData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXErrorData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXErrorData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXErrorData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXErrorData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXDisconnectCommandResponseData/title",
          "value": "OBEXDisconnectCommandResponseData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXDisconnectCommandResponseData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXDisconnectCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXDisconnectCommandResponseData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXDisconnectCommandResponseData"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/obexsessionevent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/obexsessionevent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
