{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexfiletransferservices-h"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "role": "collectionGroup",
    "title": "OBEXFileTransferServices.h"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Included-Headers",
          "level": 3,
          "text": "Included Headers",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<Foundation/Foundation.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<IOBluetooth/OBEX.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "<IOBluetooth/objc/IOBluetoothOBEXSession.h>",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/bluetooth-h-user-space": {
      "abstract": [
        {
          "text": "Bluetooth wireless technology",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/bluetooth-h-user-space",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Bluetooth.h User-Space",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetooth-h-user-space"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/global-variables": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/global-variables",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Global Variables",
      "type": "topic",
      "url": "/documentation/iobluetooth/global-variables"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Constants",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-constants"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Data Types",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-data-types"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Enumerations",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-enumerations"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Functions",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-functions"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetooth Structures",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth-structures"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothuserlib-h": {
      "abstract": [
        {
          "text": "Public Interfaces for Apple’s implementation of Bluetooth technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothuserlib-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetoothUserLib.h",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothuserlib-h"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothutilities-h": {
      "abstract": [
        {
          "text": "See the Overview section above for header-level documentation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothutilities-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "IOBluetoothUtilities.h",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothutilities-h"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/obex-h": {
      "abstract": [
        {
          "text": "Public OBEX technology interfaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/obex-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OBEX.h",
      "type": "topic",
      "url": "/documentation/iobluetooth/obex-h"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexbluetooth-h": {
      "abstract": [
        {
          "text": "Object Exchange over Bluetooth.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexbluetooth-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OBEXBluetooth.h",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexbluetooth-h"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/bluetooth-h-user-space",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothuserlib-h",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothutilities-h",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/obex-h",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexbluetooth-h",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-structures",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-constants",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-functions",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "abstract": [
        {
          "text": "See the Overview section above for header-level documentation.",
          "type": "text"
        }
      ],
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/global-variables"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "abstract": [
                {
                  "text": "See the Overview section above for header-level documentation.",
                  "type": "text"
                }
              ],
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/global-variables"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/bluetooth-h-user-space",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothuserlib-h",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetoothutilities-h",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/obex-h",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/obexbluetooth-h",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-structures",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-enumerations",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-constants",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-functions",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iobluetooth-data-types"
              ],
              "title": "Reference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/obexfiletransferservices-h"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/obexfiletransferservices-h"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
