{
  "abstract": [
    {
      "text": "Codes for OBEX errors. If the return value was not in the following range, then it is most likely resulting from kernel code/IOKit, and you should consult IOReturn.h for those codes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@OBEXError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "OBEXError"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "OBEXError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "OBEXError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "OBEXError"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectFlagValues": {
      "abstract": [
        {
          "text": "Flags for Connect command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXConnectFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectFlagValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXConnectFlagValues"
        }
      ],
      "role": "symbol",
      "title": "OBEXConnectFlagValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexconnectflagvalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXError": {
      "abstract": [
        {
          "text": "Codes for OBEX errors. If the return value was not in the following range, then it is most likely resulting from kernel code/IOKit, and you should consult IOReturn.h for those codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXError"
        }
      ],
      "role": "symbol",
      "title": "OBEXError",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexerror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXHeaderIdentifiers": {
      "abstract": [
        {
          "text": "Identifiers for OBEX Headers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXHeaderIdentifiers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "role": "symbol",
      "title": "OBEXHeaderIdentifiers",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexheaderidentifiers"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXNonceFlagValues": {
      "abstract": [
        {
          "text": "Flags for Nonce command during digest challenge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXNonceFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXNonceFlagValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXNonceFlagValues"
        }
      ],
      "role": "symbol",
      "title": "OBEXNonceFlagValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexnonceflagvalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeCommandValues": {
      "abstract": [
        {
          "text": "Operation OpCode values for commands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXOpCodeCommandValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeCommandValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXOpCodeCommandValues"
        }
      ],
      "role": "symbol",
      "title": "OBEXOpCodeCommandValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexopcodecommandvalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeResponseValues": {
      "abstract": [
        {
          "text": "Response opCode values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXOpCodeResponseValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeResponseValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXOpCodeResponseValues"
        }
      ],
      "role": "symbol",
      "title": "OBEXOpCodeResponseValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexopcoderesponsevalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeSessionValues": {
      "abstract": [
        {
          "text": "Operation OpCode values for sessions. From the OBEX 1.3 specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXOpCodeSessionValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeSessionValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXOpCodeSessionValues"
        }
      ],
      "role": "symbol",
      "title": "OBEXOpCodeSessionValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexopcodesessionvalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutFlagValues": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXPutFlagValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutFlagValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXPutFlagValues"
        }
      ],
      "role": "symbol",
      "title": "OBEXPutFlagValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexputflagvalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues": {
      "abstract": [
        {
          "text": "Values for Realm during digest response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXRealmValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXRealmValues"
        }
      ],
      "role": "symbol",
      "title": "OBEXRealmValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexrealmvalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEventTypes": {
      "abstract": [
        {
          "text": "Type identifiers for OBEX sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXSessionEventTypes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEventTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXSessionEventTypes"
        }
      ],
      "role": "symbol",
      "title": "OBEXSessionEventTypes",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexsessioneventtypes"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionParameterTags": {
      "abstract": [
        {
          "text": "Tags for SessionParameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXSessionParameterTags"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionParameterTags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXSessionParameterTags"
        }
      ],
      "role": "symbol",
      "title": "OBEXSessionParameterTags",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexsessionparametertags"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXVersions": {
      "abstract": [
        {
          "text": "The available/supported OBEX versions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXVersions"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXVersions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXVersions"
        }
      ],
      "role": "symbol",
      "title": "OBEXVersions",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexversions"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMax": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXErrorRangeMax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXErrorRangeMax"
        }
      ],
      "role": "symbol",
      "title": "kOBEXErrorRangeMax",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexerrorrangemax"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMin": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXErrorRangeMin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXErrorRangeMin"
        }
      ],
      "role": "symbol",
      "title": "kOBEXErrorRangeMin",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexerrorrangemin"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXError"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectFlagValues",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXHeaderIdentifiers",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXNonceFlagValues",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeCommandValues",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeResponseValues",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeSessionValues",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutFlagValues",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEventTypes",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionParameterTags",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXVersions"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMin",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMax"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "OBEXError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMin",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMax"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXError"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectFlagValues",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXHeaderIdentifiers",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXNonceFlagValues",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeCommandValues",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeResponseValues",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXOpCodeSessionValues",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutFlagValues",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEventTypes",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionParameterTags",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXVersions"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@int32_t",
                    "text": "int32_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "OBEXError"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXHeaderIdentifiers/title",
          "value": "OBEXHeaderIdentifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXHeaderIdentifiers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXHeaderIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXHeaderIdentifiers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXHeaderIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXVersions/title",
          "value": "OBEXVersions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXVersions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXVersions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXVersions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXVersions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXPutFlagValues/title",
          "value": "OBEXPutFlagValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXPutFlagValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXPutFlagValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXPutFlagValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXPutFlagValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXConnectFlagValues/title",
          "value": "OBEXConnectFlagValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXConnectFlagValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXConnectFlagValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXConnectFlagValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXConnectFlagValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEventTypes/title",
          "value": "OBEXSessionEventTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEventTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSessionEventTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEventTypes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSessionEventTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXOpCodeResponseValues/title",
          "value": "OBEXOpCodeResponseValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXOpCodeResponseValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXOpCodeResponseValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXOpCodeResponseValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXOpCodeResponseValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXError/title",
          "value": "OBEXError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXOpCodeSessionValues/title",
          "value": "OBEXOpCodeSessionValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXOpCodeSessionValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXOpCodeSessionValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXOpCodeSessionValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXOpCodeSessionValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXNonceFlagValues/title",
          "value": "OBEXNonceFlagValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXNonceFlagValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXNonceFlagValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXNonceFlagValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXNonceFlagValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionParameterTags/title",
          "value": "OBEXSessionParameterTags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionParameterTags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSessionParameterTags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionParameterTags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSessionParameterTags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXRealmValues/title",
          "value": "OBEXRealmValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXRealmValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXRealmValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXRealmValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXRealmValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXErrorRangeMax/title",
          "value": "kOBEXErrorRangeMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXErrorRangeMax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXErrorRangeMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXErrorRangeMin/title",
          "value": "kOBEXErrorRangeMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXErrorRangeMin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXErrorRangeMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXOpCodeCommandValues/title",
          "value": "OBEXOpCodeCommandValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXOpCodeCommandValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXOpCodeCommandValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXOpCodeCommandValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXOpCodeCommandValues"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/obexerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/obexerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
