{
  "abstract": [
    {
      "text": "Take a data blob and looks for OBEX headers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXGetHeaders(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@OBEXGetHeaders",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "OBEXGetHeaders"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SV",
        "text": "UnsafeRawPointer"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFDictionaryRef",
        "text": "CFDictionary"
      },
      {
        "kind": "text",
        "text": "!"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "OBEXGetHeaders"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "OBEXGetHeaders(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "OBEXGetHeaders"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inData"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SV",
              "text": "UnsafeRawPointer"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inDataSize"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFDictionaryRef",
              "text": "CFDictionary"
            },
            {
              "kind": "text",
              "text": "!"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The data chunk with the headers you are interested in.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inData"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The size of the buffer you are passing in.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inDataSize"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A CFDictionary with the headers found in the data blob inside it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You should use this when your callback for PUTs, GETs, etc. give you a data chunk and a size. Pass these params to this function and you will receive a dictionary back full of the parse headers. You can use the CFDictionary calls to get objects out of it, based on the header keys defined above. You are responsible for releasing the CFDictionary returned to you. Example usage:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            " ",
            "   CFDictionaryRef   dictionary = OBEXGetHeaders( data, dataLength );",
            "   if( dictionary )",
            "   {",
            "   \tif( CFDictionaryGetCountOfKey( dictionary, kOBEXHeaderIDKeyName ) > 0 )",
            "   \t{",
            "   \t\tCFStringRef theStringRef;",
            " ",
            "   \t\ttheStringRef = (CFStringRef) CFDictionaryGetValue( dictionary, kOBEXHeaderIDKeyName );",
            "   \t\tif( theStringRef )",
            "   \t\t{",
            "   \t\t\t// Display it, use it as a filename, whatever.",
            "   \t\t}",
            "   \t}",
            " ",
            "   \tif( CFDictionaryGetCountOfKey( dictionary, kOBEXHeaderIDKeyConnectionID ) > 0 )",
            "   \t{",
            "   \t\tCFDataRef theDataRef;",
            " ",
            "   \t\ttheDataRef = (CFDataRef) CFDictionaryGetValue( dictionary, kOBEXHeaderIDKeyConnectionID );",
            "   \t\tif( theDataRef )",
            "   \t\t{",
            "   \t\t\t// now we have data representing the connection ID.",
            "   \t\t}",
            "   \t}",
            " ",
            "   \tCFRelease( dictionary );",
            "   }",
            " "
          ],
          "syntax": "objc",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/GET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT": {
      "abstract": [
        {
          "text": "Convenience Macros for working with OBEX Header Identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/GET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT",
      "kind": "symbol",
      "role": "symbol",
      "title": "GET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT",
      "type": "topic",
      "url": "/documentation/iobluetooth/get_header_id_is_null_terminated_unicode_text"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddApplicationParameterHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add bytes representing an application parameter to a dictionary of OBEX headers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddApplicationParameterHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddApplicationParameterHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddApplicationParameterHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddApplicationParameterHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddapplicationparameterheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddAuthorizationChallengeHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add an authorization challenge header to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddAuthorizationChallengeHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddAuthorizationChallengeHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddAuthorizationChallengeHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddAuthorizationChallengeHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddauthorizationchallengeheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddAuthorizationResponseHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add an authorization Response header to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddAuthorizationResponseHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddAuthorizationResponseHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddAuthorizationResponseHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddAuthorizationResponseHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddauthorizationresponseheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddBodyHeader(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Add bytes of data to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddBodyHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddBodyHeader(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddBodyHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddBodyHeader(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddbodyheader(_:_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddByteSequenceHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add a byte sequence header to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddByteSequenceHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddByteSequenceHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddByteSequenceHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddByteSequenceHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddbytesequenceheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddConnectionIDHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add bytes representing a connection ID to a dictionary of OBEX headers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddConnectionIDHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddConnectionIDHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddConnectionIDHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddConnectionIDHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddconnectionidheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddCountHeader(_:_:)": {
      "abstract": [
        {
          "text": "Add a CFStringRef to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddCountHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddCountHeader(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddCountHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddCountHeader(_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddcountheader(_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddDescriptionHeader(_:_:)": {
      "abstract": [
        {
          "text": "Add a CFStringRef to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddDescriptionHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddDescriptionHeader(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddDescriptionHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddDescriptionHeader(_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexadddescriptionheader(_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddHTTPHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add bytes of data to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddHTTPHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddHTTPHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddHTTPHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddHTTPHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddhttpheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddLengthHeader(_:_:)": {
      "abstract": [
        {
          "text": "Add a CFStringRef to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddLengthHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddLengthHeader(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddLengthHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddLengthHeader(_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddlengthheader(_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddNameHeader(_:_:)": {
      "abstract": [
        {
          "text": "Add a CFStringRef to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddNameHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddNameHeader(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddNameHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddNameHeader(_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddnameheader(_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddObjectClassHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add an object class header to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddObjectClassHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddObjectClassHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddObjectClassHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddObjectClassHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddobjectclassheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTargetHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add bytes of data to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddTargetHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTargetHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddTargetHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddTargetHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddtargetheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTime4ByteHeader(_:_:)": {
      "abstract": [
        {
          "text": "Add a CFStringRef to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddTime4ByteHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTime4ByteHeader(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddTime4ByteHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddTime4ByteHeader(_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddtime4byteheader(_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTimeISOHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add bytes to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddTimeISOHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTimeISOHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddTimeISOHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddTimeISOHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddtimeisoheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXGetHeaders(_:_:)": {
      "abstract": [
        {
          "text": "Take a data blob and looks for OBEX headers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXGetHeaders"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXGetHeaders(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXGetHeaders"
        }
      ],
      "role": "symbol",
      "title": "OBEXGetHeaders(_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexgetheaders(_:_:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef": {
      "abstract": [
        {
          "text": "A reference to an immutable dictionary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFDictionary",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdictionary"
    },
    "doc://com.externally.resolved.symbol/c:@T@size_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@size_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "size_t",
      "type": "topic",
      "url": "/documentation/kernel/size_t"
    },
    "doc://com.externally.resolved.symbol/s:SV": {
      "abstract": [
        {
          "text": "A raw pointer for accessing untyped data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeRawPointer"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SV",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeRawPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeRawPointer"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Miscellaneous",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddApplicationParameterHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddAuthorizationChallengeHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddAuthorizationResponseHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddBodyHeader(_:_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddByteSequenceHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddConnectionIDHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddCountHeader(_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddDescriptionHeader(_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddHTTPHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddLengthHeader(_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddNameHeader(_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddObjectClassHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTargetHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTime4ByteHeader(_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTimeISOHeader(_:_:_:)"
      ],
      "title": "Miscellaneous"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "OBEXGetHeaders"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXGetHeaders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Miscellaneous",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/GET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddApplicationParameterHeader(_:_:_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddAuthorizationChallengeHeader(_:_:_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddAuthorizationResponseHeader(_:_:_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddBodyHeader(_:_:_:_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddByteSequenceHeader(_:_:_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddConnectionIDHeader(_:_:_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddCountHeader(_:_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddDescriptionHeader(_:_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddHTTPHeader(_:_:_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddLengthHeader(_:_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddNameHeader(_:_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddObjectClassHeader(_:_:_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTargetHeader(_:_:_:)",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTime4ByteHeader(_:_:)"
              ],
              "title": "Miscellaneous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFDictionaryRef",
                    "text": "CFDictionaryRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "OBEXGetHeaders"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inData"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@size_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@size_t",
                    "text": "size_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inDataSize"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The data chunk with the headers you are interested in.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inData"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The size of the buffer you are passing in.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inDataSize"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A CFDictionary with the headers found in the data blob inside it.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFDictionaryRef/title",
          "value": "CFDictionaryRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddByteSequenceHeader(_:_:_:)/title",
          "value": "OBEXAddByteSequenceHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddByteSequenceHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddByteSequenceHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddDescriptionHeader(_:_:)/title",
          "value": "OBEXAddDescriptionHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddDescriptionHeader(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddDescriptionHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddTime4ByteHeader(_:_:)/title",
          "value": "OBEXAddTime4ByteHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddTime4ByteHeader(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddTime4ByteHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddBodyHeader(_:_:_:_:)/title",
          "value": "OBEXAddBodyHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddBodyHeader(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddBodyHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddCountHeader(_:_:)/title",
          "value": "OBEXAddCountHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddCountHeader(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddCountHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddHTTPHeader(_:_:_:)/title",
          "value": "OBEXAddHTTPHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddHTTPHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddHTTPHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddAuthorizationChallengeHeader(_:_:_:)/title",
          "value": "OBEXAddAuthorizationChallengeHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddAuthorizationChallengeHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddAuthorizationChallengeHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddConnectionIDHeader(_:_:_:)/title",
          "value": "OBEXAddConnectionIDHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddConnectionIDHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddConnectionIDHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddObjectClassHeader(_:_:_:)/title",
          "value": "OBEXAddObjectClassHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddObjectClassHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddObjectClassHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddTargetHeader(_:_:_:)/title",
          "value": "OBEXAddTargetHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddTargetHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddTargetHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXGetHeaders(_:_:)/title",
          "value": "OBEXGetHeaders"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXGetHeaders(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXGetHeaders"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddApplicationParameterHeader(_:_:_:)/title",
          "value": "OBEXAddApplicationParameterHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddApplicationParameterHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddApplicationParameterHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddLengthHeader(_:_:)/title",
          "value": "OBEXAddLengthHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddLengthHeader(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddLengthHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddNameHeader(_:_:)/title",
          "value": "OBEXAddNameHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddNameHeader(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddNameHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddTimeISOHeader(_:_:_:)/title",
          "value": "OBEXAddTimeISOHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddTimeISOHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddTimeISOHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddAuthorizationResponseHeader(_:_:_:)/title",
          "value": "OBEXAddAuthorizationResponseHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddAuthorizationResponseHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddAuthorizationResponseHeader"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/obexgetheaders(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/obexgetheaders(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
