{
  "abstract": [
    {
      "text": "Identifiers for OBEX Headers.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXHeaderIdentifiers"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@OBEXHeaderIdentifiers",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "OBEXHeaderIdentifiers"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "OBEXHeaderIdentifiers"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "OBEXHeaderIdentifiers"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "OBEXHeaderIdentifiers"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAFHMode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAFHMode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAFHMode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothafhmode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAirMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAirMode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAirMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAirMode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAirMode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothairmode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAllowRoleSwitch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAllowRoleSwitch"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAllowRoleSwitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAllowRoleSwitch"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAllowRoleSwitch",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothallowroleswitch"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirements": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirements"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirements"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAuthenticationRequirements",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothauthenticationrequirements"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAuthenticationRequirementsValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothauthenticationrequirementsvalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothClassOfDevice"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothClassOfDevice"
        }
      ],
      "role": "symbol",
      "title": "BluetoothClassOfDevice",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothclassofdevice"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothClockOffset"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothClockOffset"
        }
      ],
      "role": "symbol",
      "title": "BluetoothClockOffset",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothclockoffset"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "role": "symbol",
      "title": "BluetoothCompanyIdentifers",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothcompanyidentifers"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothConnectionHandle"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothConnectionHandle"
        }
      ],
      "role": "symbol",
      "title": "BluetoothConnectionHandle",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothconnectionhandle"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothDeviceClassMajor"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothDeviceClassMajor"
        }
      ],
      "role": "symbol",
      "title": "BluetoothDeviceClassMajor",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothdeviceclassmajor"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothDeviceClassMinor"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothDeviceClassMinor"
        }
      ],
      "role": "symbol",
      "title": "BluetoothDeviceClassMinor",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothdeviceclassminor"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothDeviceName"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothDeviceName"
        }
      ],
      "role": "symbol",
      "title": "BluetoothDeviceName",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothdevicename"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEncryptionEnable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothEncryptionEnable"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEncryptionEnable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothEncryptionEnable"
        }
      ],
      "role": "symbol",
      "title": "BluetoothEncryptionEnable",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothencryptionenable"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothFeatureBits"
        }
      ],
      "role": "symbol",
      "title": "BluetoothFeatureBits",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothfeaturebits"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIACLDataByteCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIACLDataByteCount"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIACLDataByteCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIACLDataByteCount"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIACLDataByteCount",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhciacldatabytecount"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXHeaderIdentifiers": {
      "abstract": [
        {
          "text": "Identifiers for OBEX Headers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXHeaderIdentifiers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "role": "symbol",
      "title": "OBEXHeaderIdentifiers",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexheaderidentifiers"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXHeaderIdentifiers/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXHeaderIdentifiers/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexheaderidentifiers/init(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXHeaderIdentifiers/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXHeaderIdentifiers/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexheaderidentifiers/init(rawvalue:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXHeaderIdentifiers/rawValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXHeaderIdentifiers/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexheaderidentifiers/rawvalue"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAppParameters": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDAppParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAppParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDAppParameters"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDAppParameters",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidappparameters"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAuthorizationChallenge": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDAuthorizationChallenge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAuthorizationChallenge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDAuthorizationChallenge"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDAuthorizationChallenge",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidauthorizationchallenge"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAuthorizationResponse": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDAuthorizationResponse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAuthorizationResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDAuthorizationResponse"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDAuthorizationResponse",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidauthorizationresponse"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDBody": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDBody"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDBody"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDBody",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidbody"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDConnectionID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDConnectionID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDConnectionID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDConnectionID"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDConnectionID",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidconnectionid"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDCount"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDCount",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidcount"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDDescription"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDDescription",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderiddescription"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDEndOfBody": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDEndOfBody"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDEndOfBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDEndOfBody"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDEndOfBody",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidendofbody"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDHTTP": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDHTTP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDHTTP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDHTTP"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDHTTP",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidhttp"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDLength": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDLength"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDLength",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidlength"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDName"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDName",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidname"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13CreatorID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDOBEX13CreatorID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13CreatorID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDOBEX13CreatorID"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDOBEX13CreatorID",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidobex13creatorid"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13ObjectClass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDOBEX13ObjectClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13ObjectClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDOBEX13ObjectClass"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDOBEX13ObjectClass",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidobex13objectclass"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13SessionParameters": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDOBEX13SessionParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13SessionParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDOBEX13SessionParameters"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDOBEX13SessionParameters",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidobex13sessionparameters"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13SessionSequenceNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDOBEX13SessionSequenceNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13SessionSequenceNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDOBEX13SessionSequenceNumber"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDOBEX13SessionSequenceNumber",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidobex13sessionsequencenumber"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13WANUUID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDOBEX13WANUUID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13WANUUID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDOBEX13WANUUID"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDOBEX13WANUUID",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidobex13wanuuid"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDObjectClass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDObjectClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDObjectClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDObjectClass"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDObjectClass",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidobjectclass"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDReservedRangeEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDReservedRangeEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDReservedRangeEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDReservedRangeEnd"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDReservedRangeEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidreservedrangeend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDReservedRangeStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDReservedRangeStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDReservedRangeStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDReservedRangeStart"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDReservedRangeStart",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidreservedrangestart"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDTarget": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDTarget"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDTarget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDTarget"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDTarget",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidtarget"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDTime4Byte": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDTime4Byte"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDTime4Byte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDTime4Byte"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDTime4Byte",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidtime4byte"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDTimeISO": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDTimeISO"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDTimeISO",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDTimeISO"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDTimeISO",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidtimeiso"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDType"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDType",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidtype"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDUserDefinedRangeEnd": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDUserDefinedRangeEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDUserDefinedRangeEnd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDUserDefinedRangeEnd"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDUserDefinedRangeEnd",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderiduserdefinedrangeend"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDUserDefinedRangeStart": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDUserDefinedRangeStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDUserDefinedRangeStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDUserDefinedRangeStart"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDUserDefinedRangeStart",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderiduserdefinedrangestart"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDWho": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDWho"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXHeaderIdentifiers",
          "text": "OBEXHeaderIdentifiers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDWho",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXHeaderIDWho"
        }
      ],
      "role": "symbol",
      "title": "kOBEXHeaderIDWho",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexheaderidwho"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHMode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAirMode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAllowRoleSwitch",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirements",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEncryptionEnable",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIACLDataByteCount"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAppParameters",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAuthorizationChallenge",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAuthorizationResponse",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDBody",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDConnectionID",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDCount",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDDescription",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDEndOfBody",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDHTTP",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDLength",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDName",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13CreatorID",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13ObjectClass",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13SessionParameters",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13SessionSequenceNumber",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13WANUUID",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDObjectClass",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDReservedRangeEnd",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDReservedRangeStart",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDTarget",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDTime4Byte",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDTimeISO",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDType",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDUserDefinedRangeEnd",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDUserDefinedRangeStart",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDWho"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXHeaderIdentifiers/init(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXHeaderIdentifiers/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXHeaderIdentifiers/rawValue"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "OBEXHeaderIdentifiers"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXHeaderIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXHeaderIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAppParameters",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAuthorizationChallenge",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDAuthorizationResponse",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDBody",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDConnectionID",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDCount",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDDescription",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDEndOfBody",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDHTTP",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDLength",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDName",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13CreatorID",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13ObjectClass",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13SessionParameters",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13SessionSequenceNumber",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDOBEX13WANUUID",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDObjectClass",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDReservedRangeEnd",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDReservedRangeStart",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDTarget",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDTime4Byte",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDTimeISO",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDType",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDUserDefinedRangeEnd",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDUserDefinedRangeStart",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXHeaderIDWho"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHMode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAirMode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAllowRoleSwitch",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirements",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEncryptionEnable",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIACLDataByteCount"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "OBEXHeaderIdentifiers"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:i",
                    "text": "unsigned int"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAirMode/title",
          "value": "BluetoothAirMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAirMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAirMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAirMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAirMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClockOffset/title",
          "value": "BluetoothClockOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClockOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothClockOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClockOffset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothClockOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDType/title",
          "value": "kOBEXHeaderIDType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDConnectionID/title",
          "value": "kOBEXHeaderIDConnectionID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDConnectionID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDConnectionID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIACLDataByteCount/title",
          "value": "BluetoothHCIACLDataByteCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIACLDataByteCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIACLDataByteCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIACLDataByteCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIACLDataByteCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDOBEX13WANUUID/title",
          "value": "kOBEXHeaderIDOBEX13WANUUID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDOBEX13WANUUID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDOBEX13WANUUID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDOBEX13SessionSequenceNumber/title",
          "value": "kOBEXHeaderIDOBEX13SessionSequenceNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDOBEX13SessionSequenceNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDOBEX13SessionSequenceNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDObjectClass/title",
          "value": "kOBEXHeaderIDObjectClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDObjectClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDObjectClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDHTTP/title",
          "value": "kOBEXHeaderIDHTTP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDHTTP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDHTTP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/title",
          "value": "BluetoothAuthenticationRequirementsValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirementsValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirementsValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDBody/title",
          "value": "kOBEXHeaderIDBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDDescription/title",
          "value": "kOBEXHeaderIDDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/title",
          "value": "BluetoothFeatureBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothFeatureBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothFeatureBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDUserDefinedRangeStart/title",
          "value": "kOBEXHeaderIDUserDefinedRangeStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDUserDefinedRangeStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDUserDefinedRangeStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDOBEX13ObjectClass/title",
          "value": "kOBEXHeaderIDOBEX13ObjectClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDOBEX13ObjectClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDOBEX13ObjectClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDAuthorizationResponse/title",
          "value": "kOBEXHeaderIDAuthorizationResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDAuthorizationResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDAuthorizationResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHMode/title",
          "value": "BluetoothAFHMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAFHMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAFHMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMajor/title",
          "value": "BluetoothDeviceClassMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceClassMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMajor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceClassMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDReservedRangeStart/title",
          "value": "kOBEXHeaderIDReservedRangeStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDReservedRangeStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDReservedRangeStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDTime4Byte/title",
          "value": "kOBEXHeaderIDTime4Byte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDTime4Byte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDTime4Byte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXHeaderIdentifiers/title",
          "value": "OBEXHeaderIdentifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXHeaderIdentifiers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXHeaderIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXHeaderIdentifiers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXHeaderIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDReservedRangeEnd/title",
          "value": "kOBEXHeaderIDReservedRangeEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDReservedRangeEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDReservedRangeEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirements/title",
          "value": "BluetoothAuthenticationRequirements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDUserDefinedRangeEnd/title",
          "value": "kOBEXHeaderIDUserDefinedRangeEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDUserDefinedRangeEnd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDUserDefinedRangeEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/title",
          "value": "BluetoothConnectionHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothConnectionHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothConnectionHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDAppParameters/title",
          "value": "kOBEXHeaderIDAppParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDAppParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDAppParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/title",
          "value": "BluetoothCompanyIdentifers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothCompanyIdentifers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothCompanyIdentifers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClassOfDevice/title",
          "value": "BluetoothClassOfDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClassOfDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothClassOfDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClassOfDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothClassOfDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDName/title",
          "value": "kOBEXHeaderIDName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceName/title",
          "value": "BluetoothDeviceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDWho/title",
          "value": "kOBEXHeaderIDWho"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDWho/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDWho"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDLength/title",
          "value": "kOBEXHeaderIDLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDOBEX13SessionParameters/title",
          "value": "kOBEXHeaderIDOBEX13SessionParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDOBEX13SessionParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDOBEX13SessionParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDEndOfBody/title",
          "value": "kOBEXHeaderIDEndOfBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDEndOfBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDEndOfBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDTarget/title",
          "value": "kOBEXHeaderIDTarget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDTarget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDTarget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAllowRoleSwitch/title",
          "value": "BluetoothAllowRoleSwitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAllowRoleSwitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAllowRoleSwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAllowRoleSwitch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAllowRoleSwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMinor/title",
          "value": "BluetoothDeviceClassMinor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMinor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceClassMinor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMinor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceClassMinor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEncryptionEnable/title",
          "value": "BluetoothEncryptionEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEncryptionEnable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothEncryptionEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEncryptionEnable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothEncryptionEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDOBEX13CreatorID/title",
          "value": "kOBEXHeaderIDOBEX13CreatorID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDOBEX13CreatorID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDOBEX13CreatorID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDCount/title",
          "value": "kOBEXHeaderIDCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDAuthorizationChallenge/title",
          "value": "kOBEXHeaderIDAuthorizationChallenge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDAuthorizationChallenge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDAuthorizationChallenge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDTimeISO/title",
          "value": "kOBEXHeaderIDTimeISO"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXHeaderIDTimeISO/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXHeaderIDTimeISO"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/obexheaderidentifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/obexheaderidentifiers"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
