{
  "abstract": [
    {
      "text": "Convenience Macros for working with OBEX Header Identifiers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/obex-h"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/obex-convenience-macros"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "OBEX Convenience Macros"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The API should shield you from using these, they are included here to completeness.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCoDMinorPeripheral1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BluetoothCoDMinorPeripheral1"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCoDMinorPeripheral1",
      "kind": "symbol",
      "role": "symbol",
      "title": "BluetoothCoDMinorPeripheral1",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothcodminorperipheral1"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCoDMinorPeripheral2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BluetoothCoDMinorPeripheral2"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCoDMinorPeripheral2",
      "kind": "symbol",
      "role": "symbol",
      "title": "BluetoothCoDMinorPeripheral2",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothcodminorperipheral2"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothGetDeviceClassMajor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BluetoothGetDeviceClassMajor"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothGetDeviceClassMajor",
      "kind": "symbol",
      "role": "symbol",
      "title": "BluetoothGetDeviceClassMajor",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothgetdeviceclassmajor"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothGetDeviceClassMinor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BluetoothGetDeviceClassMinor"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothGetDeviceClassMinor",
      "kind": "symbol",
      "role": "symbol",
      "title": "BluetoothGetDeviceClassMinor",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothgetdeviceclassminor"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothGetSecondsFromSlots": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BluetoothGetSecondsFromSlots"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothGetSecondsFromSlots",
      "kind": "symbol",
      "role": "symbol",
      "title": "BluetoothGetSecondsFromSlots",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothgetsecondsfromslots"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothGetServiceClassMajor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BluetoothGetServiceClassMajor"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothGetServiceClassMajor",
      "kind": "symbol",
      "role": "symbol",
      "title": "BluetoothGetServiceClassMajor",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothgetserviceclassmajor"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothGetSlotsFromSeconds": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BluetoothGetSlotsFromSeconds"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothGetSlotsFromSeconds",
      "kind": "symbol",
      "role": "symbol",
      "title": "BluetoothGetSlotsFromSeconds",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothgetslotsfromseconds"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIExtractCommandOpCodeCommand": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIExtractCommandOpCodeCommand"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIExtractCommandOpCodeCommand",
      "kind": "symbol",
      "role": "symbol",
      "title": "BluetoothHCIExtractCommandOpCodeCommand",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhciextractcommandopcodecommand"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIExtractCommandOpCodeGroup": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIExtractCommandOpCodeGroup"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIExtractCommandOpCodeGroup",
      "kind": "symbol",
      "role": "symbol",
      "title": "BluetoothHCIExtractCommandOpCodeGroup",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhciextractcommandopcodegroup"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIMakeCommandOpCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIMakeCommandOpCode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIMakeCommandOpCode",
      "kind": "symbol",
      "role": "symbol",
      "title": "BluetoothHCIMakeCommandOpCode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcimakecommandopcode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIMakeCommandOpCodeEndianSwap": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIMakeCommandOpCodeEndianSwap"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIMakeCommandOpCodeEndianSwap",
      "kind": "symbol",
      "role": "symbol",
      "title": "BluetoothHCIMakeCommandOpCodeEndianSwap",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcimakecommandopcodeendianswap"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIMakeCommandOpCodeHostOrder": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIMakeCommandOpCodeHostOrder"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIMakeCommandOpCodeHostOrder",
      "kind": "symbol",
      "role": "symbol",
      "title": "BluetoothHCIMakeCommandOpCodeHostOrder",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcimakecommandopcodehostorder"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothMakeClassOfDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "BluetoothMakeClassOfDevice"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothMakeClassOfDevice",
      "kind": "symbol",
      "role": "symbol",
      "title": "BluetoothMakeClassOfDevice",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothmakeclassofdevice"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/GET_HEADER_ID_IS_1_BYTE_QUANTITY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GET_HEADER_ID_IS_1_BYTE_QUANTITY"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/GET_HEADER_ID_IS_1_BYTE_QUANTITY",
      "kind": "symbol",
      "role": "symbol",
      "title": "GET_HEADER_ID_IS_1_BYTE_QUANTITY",
      "type": "topic",
      "url": "/documentation/iobluetooth/get_header_id_is_1_byte_quantity"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/GET_HEADER_ID_IS_4_BYTE_QUANTITY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GET_HEADER_ID_IS_4_BYTE_QUANTITY"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/GET_HEADER_ID_IS_4_BYTE_QUANTITY",
      "kind": "symbol",
      "role": "symbol",
      "title": "GET_HEADER_ID_IS_4_BYTE_QUANTITY",
      "type": "topic",
      "url": "/documentation/iobluetooth/get_header_id_is_4_byte_quantity"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/GET_HEADER_ID_IS_BYTE_SEQUENCE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GET_HEADER_ID_IS_BYTE_SEQUENCE"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/GET_HEADER_ID_IS_BYTE_SEQUENCE",
      "kind": "symbol",
      "role": "symbol",
      "title": "GET_HEADER_ID_IS_BYTE_SEQUENCE",
      "type": "topic",
      "url": "/documentation/iobluetooth/get_header_id_is_byte_sequence"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBLUETOOTH_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IOBLUETOOTH_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBLUETOOTH_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "IOBLUETOOTH_EXPORT",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetooth_export"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IS_REQUEST_PDU": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IS_REQUEST_PDU"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IS_REQUEST_PDU",
      "kind": "symbol",
      "role": "symbol",
      "title": "IS_REQUEST_PDU",
      "type": "topic",
      "url": "/documentation/iobluetooth/is_request_pdu"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IS_RESPONSE_CODE_FINAL_BIT_SET": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IS_RESPONSE_CODE_FINAL_BIT_SET"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IS_RESPONSE_CODE_FINAL_BIT_SET",
      "kind": "symbol",
      "role": "symbol",
      "title": "IS_RESPONSE_CODE_FINAL_BIT_SET",
      "type": "topic",
      "url": "/documentation/iobluetooth/is_response_code_final_bit_set"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IS_RESPONSE_PDU": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IS_RESPONSE_PDU"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IS_RESPONSE_PDU",
      "kind": "symbol",
      "role": "symbol",
      "title": "IS_RESPONSE_PDU",
      "type": "topic",
      "url": "/documentation/iobluetooth/is_response_pdu"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/RFCOMM_CHANNEL_ID_IS_VALID": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "RFCOMM_CHANNEL_ID_IS_VALID"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/RFCOMM_CHANNEL_ID_IS_VALID",
      "kind": "symbol",
      "role": "symbol",
      "title": "RFCOMM_CHANNEL_ID_IS_VALID",
      "type": "topic",
      "url": "/documentation/iobluetooth/rfcomm_channel_id_is_valid"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/SET_HEADER_ID_IS_1_BYTE_QUANTITY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SET_HEADER_ID_IS_1_BYTE_QUANTITY"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/SET_HEADER_ID_IS_1_BYTE_QUANTITY",
      "kind": "symbol",
      "role": "symbol",
      "title": "SET_HEADER_ID_IS_1_BYTE_QUANTITY",
      "type": "topic",
      "url": "/documentation/iobluetooth/set_header_id_is_1_byte_quantity"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/SET_HEADER_ID_IS_4_BYTE_QUANTITY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SET_HEADER_ID_IS_4_BYTE_QUANTITY"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/SET_HEADER_ID_IS_4_BYTE_QUANTITY",
      "kind": "symbol",
      "role": "symbol",
      "title": "SET_HEADER_ID_IS_4_BYTE_QUANTITY",
      "type": "topic",
      "url": "/documentation/iobluetooth/set_header_id_is_4_byte_quantity"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/SET_HEADER_ID_IS_BYTE_SEQUENCE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SET_HEADER_ID_IS_BYTE_SEQUENCE"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/SET_HEADER_ID_IS_BYTE_SEQUENCE",
      "kind": "symbol",
      "role": "symbol",
      "title": "SET_HEADER_ID_IS_BYTE_SEQUENCE",
      "type": "topic",
      "url": "/documentation/iobluetooth/set_header_id_is_byte_sequence"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/SET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "SET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/SET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT",
      "kind": "symbol",
      "role": "symbol",
      "title": "SET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT",
      "type": "topic",
      "url": "/documentation/iobluetooth/set_header_id_is_null_terminated_unicode_text"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/STRIP_RESPONSE_CODE_FINAL_BIT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "STRIP_RESPONSE_CODE_FINAL_BIT"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/STRIP_RESPONSE_CODE_FINAL_BIT",
      "kind": "symbol",
      "role": "symbol",
      "title": "STRIP_RESPONSE_CODE_FINAL_BIT",
      "type": "topic",
      "url": "/documentation/iobluetooth/strip_response_code_final_bit"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/iokit_bluetooth_err": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "iokit_bluetooth_err"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/iokit_bluetooth_err",
      "kind": "symbol",
      "role": "symbol",
      "title": "iokit_bluetooth_err",
      "type": "topic",
      "url": "/documentation/iobluetooth/iokit_bluetooth_err"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothConnectionAlreadyExists": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kIOBluetoothConnectionAlreadyExists"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothConnectionAlreadyExists",
      "kind": "symbol",
      "role": "symbol",
      "title": "kIOBluetoothConnectionAlreadyExists",
      "type": "topic",
      "url": "/documentation/iobluetooth/kiobluetoothconnectionalreadyexists"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothDeviceResetError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kIOBluetoothDeviceResetError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothDeviceResetError",
      "kind": "symbol",
      "role": "symbol",
      "title": "kIOBluetoothDeviceResetError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kiobluetoothdevicereseterror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothHCIPowerStatesNotSupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kIOBluetoothHCIPowerStatesNotSupported"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothHCIPowerStatesNotSupported",
      "kind": "symbol",
      "role": "symbol",
      "title": "kIOBluetoothHCIPowerStatesNotSupported",
      "type": "topic",
      "url": "/documentation/iobluetooth/kiobluetoothhcipowerstatesnotsupported"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothNoHCIController": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kIOBluetoothNoHCIController"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothNoHCIController",
      "kind": "symbol",
      "role": "symbol",
      "title": "kIOBluetoothNoHCIController",
      "type": "topic",
      "url": "/documentation/iobluetooth/kiobluetoothnohcicontroller"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kNoNotifyProc": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kNoNotifyProc"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kNoNotifyProc",
      "kind": "symbol",
      "role": "symbol",
      "title": "kNoNotifyProc",
      "type": "topic",
      "url": "/documentation/iobluetooth/knonotifyproc"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kNoUserRefCon": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kNoUserRefCon"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kNoUserRefCon",
      "kind": "symbol",
      "role": "symbol",
      "title": "kNoUserRefCon",
      "type": "topic",
      "url": "/documentation/iobluetooth/knouserrefcon"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/obex-h": {
      "abstract": [
        {
          "text": "Public OBEX technology interfaces.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/obex-h",
      "kind": "article",
      "role": "collectionGroup",
      "title": "OBEX.h",
      "type": "topic",
      "url": "/documentation/iobluetooth/obex-h"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCoDMinorPeripheral1",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCoDMinorPeripheral2",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothGetDeviceClassMajor",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothGetDeviceClassMinor",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothGetSecondsFromSlots",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothGetServiceClassMajor",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothGetSlotsFromSeconds",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIExtractCommandOpCodeCommand",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIExtractCommandOpCodeGroup",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIMakeCommandOpCode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIMakeCommandOpCodeEndianSwap",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIMakeCommandOpCodeHostOrder",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothMakeClassOfDevice",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/GET_HEADER_ID_IS_1_BYTE_QUANTITY",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/GET_HEADER_ID_IS_4_BYTE_QUANTITY",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/GET_HEADER_ID_IS_BYTE_SEQUENCE",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBLUETOOTH_EXPORT",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IS_REQUEST_PDU",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IS_RESPONSE_CODE_FINAL_BIT_SET",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IS_RESPONSE_PDU",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/RFCOMM_CHANNEL_ID_IS_VALID",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/SET_HEADER_ID_IS_1_BYTE_QUANTITY",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/SET_HEADER_ID_IS_4_BYTE_QUANTITY",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/SET_HEADER_ID_IS_BYTE_SEQUENCE",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/SET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/STRIP_RESPONSE_CODE_FINAL_BIT",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/iokit_bluetooth_err",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothConnectionAlreadyExists",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothDeviceResetError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothHCIPowerStatesNotSupported",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kIOBluetoothNoHCIController",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kNoNotifyProc",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kNoUserRefCon"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/obex-convenience-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/obex-convenience-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
