{
  "abstract": [
    {
      "text": "Part of the OBEXSessionEvent structure.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandData"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@OBEXDisconnectCommandData",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "OBEXDisconnectCommandData"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "OBEXDisconnectCommandData"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "OBEXDisconnectCommandData"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "OBEXDisconnectCommandData"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Is readable when the event is of type kOBEXSessionEventTypeDisconnectCommandReceived (see OBEXSessionEventTypes).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAbortCommandData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAbortCommandData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAbortCommandData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAbortCommandData"
        }
      ],
      "role": "symbol",
      "title": "OBEXAbortCommandData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexabortcommanddata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAbortCommandResponseData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAbortCommandResponseData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAbortCommandResponseData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAbortCommandResponseData"
        }
      ],
      "role": "symbol",
      "title": "OBEXAbortCommandResponseData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexabortcommandresponsedata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectCommandData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXConnectCommandData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectCommandData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXConnectCommandData"
        }
      ],
      "role": "symbol",
      "title": "OBEXConnectCommandData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexconnectcommanddata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectCommandResponseData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXConnectCommandResponseData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectCommandResponseData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXConnectCommandResponseData"
        }
      ],
      "role": "symbol",
      "title": "OBEXConnectCommandResponseData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexconnectcommandresponsedata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXDisconnectCommandData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXDisconnectCommandData"
        }
      ],
      "role": "symbol",
      "title": "OBEXDisconnectCommandData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexdisconnectcommanddata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandData/headerDataLength": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headerDataLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandData/headerDataLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "headerDataLength"
        }
      ],
      "role": "symbol",
      "title": "headerDataLength",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexdisconnectcommanddata/headerdatalength"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandData/headerDataPtr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headerDataPtr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandData/headerDataPtr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "headerDataPtr"
        }
      ],
      "role": "symbol",
      "title": "headerDataPtr",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexdisconnectcommanddata/headerdataptr"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandData/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandData/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexdisconnectcommanddata/init()"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandData/init(headerDataPtr:headerDataLength:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "headerDataPtr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "headerDataLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandData/init(headerDataPtr:headerDataLength:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(headerDataPtr:headerDataLength:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexdisconnectcommanddata/init(headerdataptr:headerdatalength:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandResponseData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXDisconnectCommandResponseData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandResponseData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXDisconnectCommandResponseData"
        }
      ],
      "role": "symbol",
      "title": "OBEXDisconnectCommandResponseData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexdisconnectcommandresponsedata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXErrorData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXErrorData"
        }
      ],
      "role": "symbol",
      "title": "OBEXErrorData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexerrordata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXGetCommandData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXGetCommandData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXGetCommandData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXGetCommandData"
        }
      ],
      "role": "symbol",
      "title": "OBEXGetCommandData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexgetcommanddata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXGetCommandResponseData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXGetCommandResponseData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXGetCommandResponseData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXGetCommandResponseData"
        }
      ],
      "role": "symbol",
      "title": "OBEXGetCommandResponseData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexgetcommandresponsedata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutCommandData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXPutCommandData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutCommandData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXPutCommandData"
        }
      ],
      "role": "symbol",
      "title": "OBEXPutCommandData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexputcommanddata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutCommandResponseData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXPutCommandResponseData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutCommandResponseData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXPutCommandResponseData"
        }
      ],
      "role": "symbol",
      "title": "OBEXPutCommandResponseData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexputcommandresponsedata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXSessionEvent"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXSessionEvent"
        }
      ],
      "role": "symbol",
      "title": "OBEXSessionEvent",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexsessionevent"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSetPathCommandData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXSetPathCommandData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSetPathCommandData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXSetPathCommandData"
        }
      ],
      "role": "symbol",
      "title": "OBEXSetPathCommandData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexsetpathcommanddata"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSetPathCommandResponseData": {
      "abstract": [
        {
          "text": "Part of the OBEXSessionEvent structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXSetPathCommandResponseData"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSetPathCommandResponseData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXSetPathCommandResponseData"
        }
      ],
      "role": "symbol",
      "title": "OBEXSetPathCommandResponseData",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexsetpathcommandresponsedata"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAbortCommandData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAbortCommandResponseData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectCommandData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectCommandResponseData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandResponseData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXGetCommandData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXGetCommandResponseData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutCommandData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutCommandResponseData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSetPathCommandData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSetPathCommandResponseData"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandData/init()",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandData/init(headerDataPtr:headerDataLength:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandData/headerDataLength",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandData/headerDataPtr"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "OBEXDisconnectCommandData"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXDisconnectCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXDisconnectCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandData/headerDataLength",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandData/headerDataPtr"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSessionEvent",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAbortCommandData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAbortCommandResponseData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectCommandData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXConnectCommandResponseData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXDisconnectCommandResponseData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXGetCommandData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXGetCommandResponseData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutCommandData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXPutCommandResponseData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSetPathCommandData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXSetPathCommandResponseData"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "OBEXDisconnectCommandData"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXPutCommandResponseData/title",
          "value": "OBEXPutCommandResponseData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXPutCommandResponseData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXPutCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXPutCommandResponseData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXPutCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEvent/title",
          "value": "OBEXSessionEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSessionEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSessionEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSessionEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXConnectCommandData/title",
          "value": "OBEXConnectCommandData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXConnectCommandData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXConnectCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXConnectCommandData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXConnectCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXPutCommandData/title",
          "value": "OBEXPutCommandData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXPutCommandData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXPutCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXPutCommandData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXPutCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAbortCommandResponseData/title",
          "value": "OBEXAbortCommandResponseData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAbortCommandResponseData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAbortCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAbortCommandResponseData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAbortCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSetPathCommandData/title",
          "value": "OBEXSetPathCommandData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSetPathCommandData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSetPathCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSetPathCommandData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSetPathCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXDisconnectCommandData/title",
          "value": "OBEXDisconnectCommandData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXDisconnectCommandData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXDisconnectCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXDisconnectCommandData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXDisconnectCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXGetCommandResponseData/title",
          "value": "OBEXGetCommandResponseData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXGetCommandResponseData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXGetCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXGetCommandResponseData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXGetCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXErrorData/title",
          "value": "OBEXErrorData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXErrorData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXErrorData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXErrorData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXErrorData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXDisconnectCommandResponseData/title",
          "value": "OBEXDisconnectCommandResponseData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXDisconnectCommandResponseData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXDisconnectCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXDisconnectCommandResponseData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXDisconnectCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXGetCommandData/title",
          "value": "OBEXGetCommandData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXGetCommandData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXGetCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXGetCommandData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXGetCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSetPathCommandResponseData/title",
          "value": "OBEXSetPathCommandResponseData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSetPathCommandResponseData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSetPathCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXSetPathCommandResponseData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXSetPathCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXDisconnectCommandData~1headerDataPtr/title",
          "value": "headerDataPtr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXDisconnectCommandData~1headerDataPtr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "headerDataPtr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXConnectCommandResponseData/title",
          "value": "OBEXConnectCommandResponseData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXConnectCommandResponseData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXConnectCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXConnectCommandResponseData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXConnectCommandResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAbortCommandData/title",
          "value": "OBEXAbortCommandData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAbortCommandData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAbortCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAbortCommandData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAbortCommandData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXDisconnectCommandData~1headerDataLength/title",
          "value": "headerDataLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXDisconnectCommandData~1headerDataLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "headerDataLength"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/obexdisconnectcommanddata"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/obexdisconnectcommanddata"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
