{
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorCodes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@OBEXErrorCodes",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "OBEXErrorCodes"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "OBEXErrorCodes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "OBEXErrorCodes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "OBEXErrorCodes"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAFHMode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAFHMode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAFHMode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothafhmode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAirMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAirMode"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAirMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAirMode"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAirMode",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothairmode"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAllowRoleSwitch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAllowRoleSwitch"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAllowRoleSwitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAllowRoleSwitch"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAllowRoleSwitch",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothallowroleswitch"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirements": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirements"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirements"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAuthenticationRequirements",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothauthenticationrequirements"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothAuthenticationRequirementsValues"
        }
      ],
      "role": "symbol",
      "title": "BluetoothAuthenticationRequirementsValues",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothauthenticationrequirementsvalues"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothClassOfDevice"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothClassOfDevice"
        }
      ],
      "role": "symbol",
      "title": "BluetoothClassOfDevice",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothclassofdevice"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothClockOffset"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothClockOffset"
        }
      ],
      "role": "symbol",
      "title": "BluetoothClockOffset",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothclockoffset"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothCompanyIdentifers"
        }
      ],
      "role": "symbol",
      "title": "BluetoothCompanyIdentifers",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothcompanyidentifers"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothConnectionHandle"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothConnectionHandle"
        }
      ],
      "role": "symbol",
      "title": "BluetoothConnectionHandle",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothconnectionhandle"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothDeviceClassMajor"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothDeviceClassMajor"
        }
      ],
      "role": "symbol",
      "title": "BluetoothDeviceClassMajor",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothdeviceclassmajor"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothDeviceClassMinor"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothDeviceClassMinor"
        }
      ],
      "role": "symbol",
      "title": "BluetoothDeviceClassMinor",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothdeviceclassminor"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothDeviceName"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothDeviceName"
        }
      ],
      "role": "symbol",
      "title": "BluetoothDeviceName",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothdevicename"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEncryptionEnable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothEncryptionEnable"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEncryptionEnable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothEncryptionEnable"
        }
      ],
      "role": "symbol",
      "title": "BluetoothEncryptionEnable",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothencryptionenable"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothFeatureBits"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothFeatureBits"
        }
      ],
      "role": "symbol",
      "title": "BluetoothFeatureBits",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothfeaturebits"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIACLDataByteCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCIACLDataByteCount"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIACLDataByteCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCIACLDataByteCount"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCIACLDataByteCount",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhciacldatabytecount"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorCodes": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorCodes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXErrorCodes"
        }
      ],
      "role": "symbol",
      "title": "OBEXErrorCodes",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexerrorcodes"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorCodes/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorCodes/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexerrorcodes/init(_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorCodes/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorCodes/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexerrorcodes/init(rawvalue:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorCodes/rawValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorCodes/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexerrorcodes/rawvalue"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXBadArgumentError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXBadArgumentError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXBadArgumentError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXBadArgumentError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXBadArgumentError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexbadargumenterror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXBadRequestError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXBadRequestError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXBadRequestError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXBadRequestError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXBadRequestError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexbadrequesterror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXCancelledError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXCancelledError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXCancelledError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXCancelledError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXCancelledError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexcancellederror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConflictError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXConflictError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConflictError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXConflictError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXConflictError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexconflicterror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMax": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXErrorRangeMax"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXErrorRangeMax"
        }
      ],
      "role": "symbol",
      "title": "kOBEXErrorRangeMax",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexerrorrangemax"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMin": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXErrorRangeMin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXErrorRangeMin"
        }
      ],
      "role": "symbol",
      "title": "kOBEXErrorRangeMin",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexerrorrangemin"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXForbiddenError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXForbiddenError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXForbiddenError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXForbiddenError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXForbiddenError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexforbiddenerror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXGeneralError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXGeneralError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXGeneralError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXGeneralError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXGeneralError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexgeneralerror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXInternalError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXInternalError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXInternalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXInternalError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXInternalError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexinternalerror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXMethodNotAllowedError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXMethodNotAllowedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXMethodNotAllowedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXMethodNotAllowedError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXMethodNotAllowedError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexmethodnotallowederror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNoResourcesError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXNoResourcesError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNoResourcesError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXNoResourcesError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXNoResourcesError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexnoresourceserror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotAcceptableError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXNotAcceptableError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotAcceptableError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXNotAcceptableError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXNotAcceptableError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexnotacceptableerror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotFoundError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXNotFoundError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotFoundError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXNotFoundError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXNotFoundError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexnotfounderror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotImplementedError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXNotImplementedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotImplementedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXNotImplementedError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXNotImplementedError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexnotimplementederror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPreconditionFailedError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXPreconditionFailedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPreconditionFailedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXPreconditionFailedError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXPreconditionFailedError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexpreconditionfailederror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionAlreadyConnectedError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionAlreadyConnectedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionAlreadyConnectedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionAlreadyConnectedError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionAlreadyConnectedError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessionalreadyconnectederror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionBadRequestError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionBadRequestError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionBadRequestError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionBadRequestError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionBadRequestError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessionbadrequesterror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionBadResponseError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionBadResponseError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionBadResponseError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionBadResponseError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionBadResponseError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessionbadresponseerror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionBusyError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionBusyError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionBusyError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionBusyError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionBusyError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessionbusyerror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionNoTransportError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionNoTransportError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionNoTransportError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionNoTransportError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionNoTransportError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessionnotransporterror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionNotConnectedError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionNotConnectedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionNotConnectedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionNotConnectedError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionNotConnectedError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessionnotconnectederror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionTimeoutError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionTimeoutError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionTimeoutError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionTimeoutError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionTimeoutError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessiontimeouterror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionTransportDiedError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSessionTransportDiedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionTransportDiedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSessionTransportDiedError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSessionTransportDiedError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsessiontransportdiederror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSuccess": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXSuccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSuccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXSuccess"
        }
      ],
      "role": "symbol",
      "title": "kOBEXSuccess",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexsuccess"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXTimeoutError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXTimeoutError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXTimeoutError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXTimeoutError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXTimeoutError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobextimeouterror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXUnauthorizedError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXUnauthorizedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXUnauthorizedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXUnauthorizedError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXUnauthorizedError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexunauthorizederror"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXUnsupportedError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kOBEXUnsupportedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@OBEXErrorCodes",
          "text": "OBEXErrorCodes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXUnsupportedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kOBEXUnsupportedError"
        }
      ],
      "role": "symbol",
      "title": "kOBEXUnsupportedError",
      "type": "topic",
      "url": "/documentation/iobluetooth/kobexunsupportederror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHMode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAirMode",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAllowRoleSwitch",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirements",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEncryptionEnable",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIACLDataByteCount"
      ],
      "title": "Data Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXBadArgumentError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXBadRequestError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXCancelledError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConflictError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMax",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMin",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXForbiddenError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXGeneralError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXInternalError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXMethodNotAllowedError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNoResourcesError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotAcceptableError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotFoundError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotImplementedError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPreconditionFailedError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionAlreadyConnectedError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionBadRequestError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionBadResponseError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionBusyError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionNoTransportError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionNotConnectedError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionTimeoutError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionTransportDiedError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSuccess",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXTimeoutError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXUnauthorizedError",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXUnsupportedError"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorCodes/init(_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorCodes/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXErrorCodes/rawValue"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "OBEXErrorCodes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXErrorCodes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXErrorCodes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXBadArgumentError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXBadRequestError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXCancelledError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXConflictError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMax",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXErrorRangeMin",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXForbiddenError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXGeneralError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXInternalError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXMethodNotAllowedError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNoResourcesError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotAcceptableError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotFoundError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXNotImplementedError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXPreconditionFailedError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionAlreadyConnectedError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionBadRequestError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionBadResponseError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionBusyError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionNoTransportError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionNotConnectedError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionTimeoutError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSessionTransportDiedError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXSuccess",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXTimeoutError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXUnauthorizedError",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXUnsupportedError"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHMode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAirMode",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAllowRoleSwitch",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirements",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEncryptionEnable",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIACLDataByteCount"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "OBEXErrorCodes"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:I",
                    "text": "int"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionNotConnectedError/title",
          "value": "kOBEXSessionNotConnectedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionNotConnectedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionNotConnectedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXTimeoutError/title",
          "value": "kOBEXTimeoutError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXTimeoutError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXTimeoutError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSuccess/title",
          "value": "kOBEXSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSuccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXMethodNotAllowedError/title",
          "value": "kOBEXMethodNotAllowedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXMethodNotAllowedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXMethodNotAllowedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXForbiddenError/title",
          "value": "kOBEXForbiddenError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXForbiddenError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXForbiddenError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEncryptionEnable/title",
          "value": "BluetoothEncryptionEnable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEncryptionEnable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothEncryptionEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEncryptionEnable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothEncryptionEnable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClassOfDevice/title",
          "value": "BluetoothClassOfDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClassOfDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothClassOfDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClassOfDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothClassOfDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPreconditionFailedError/title",
          "value": "kOBEXPreconditionFailedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXPreconditionFailedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXPreconditionFailedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/title",
          "value": "BluetoothFeatureBits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothFeatureBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothFeatureBits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionBusyError/title",
          "value": "kOBEXSessionBusyError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionBusyError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionBusyError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirements/title",
          "value": "BluetoothAuthenticationRequirements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirements/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNotAcceptableError/title",
          "value": "kOBEXNotAcceptableError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNotAcceptableError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXNotAcceptableError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionTransportDiedError/title",
          "value": "kOBEXSessionTransportDiedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionTransportDiedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionTransportDiedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXBadRequestError/title",
          "value": "kOBEXBadRequestError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXBadRequestError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXBadRequestError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXInternalError/title",
          "value": "kOBEXInternalError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXInternalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXInternalError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXErrorCodes/title",
          "value": "OBEXErrorCodes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXErrorCodes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXErrorCodes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXErrorCodes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXErrorCodes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNotImplementedError/title",
          "value": "kOBEXNotImplementedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNotImplementedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXNotImplementedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionBadResponseError/title",
          "value": "kOBEXSessionBadResponseError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionBadResponseError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionBadResponseError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNoResourcesError/title",
          "value": "kOBEXNoResourcesError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNoResourcesError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXNoResourcesError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXCancelledError/title",
          "value": "kOBEXCancelledError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXCancelledError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXCancelledError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConflictError/title",
          "value": "kOBEXConflictError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXConflictError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXConflictError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMinor/title",
          "value": "BluetoothDeviceClassMinor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMinor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceClassMinor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMinor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceClassMinor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXErrorRangeMin/title",
          "value": "kOBEXErrorRangeMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXErrorRangeMin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXErrorRangeMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNotFoundError/title",
          "value": "kOBEXNotFoundError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXNotFoundError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXNotFoundError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClockOffset/title",
          "value": "BluetoothClockOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClockOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothClockOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClockOffset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothClockOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/title",
          "value": "BluetoothConnectionHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothConnectionHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothConnectionHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHMode/title",
          "value": "BluetoothAFHMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAFHMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAFHMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXBadArgumentError/title",
          "value": "kOBEXBadArgumentError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXBadArgumentError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXBadArgumentError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionTimeoutError/title",
          "value": "kOBEXSessionTimeoutError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionTimeoutError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionTimeoutError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAllowRoleSwitch/title",
          "value": "BluetoothAllowRoleSwitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAllowRoleSwitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAllowRoleSwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAllowRoleSwitch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAllowRoleSwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/title",
          "value": "BluetoothCompanyIdentifers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothCompanyIdentifers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothCompanyIdentifers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIACLDataByteCount/title",
          "value": "BluetoothHCIACLDataByteCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIACLDataByteCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIACLDataByteCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIACLDataByteCount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCIACLDataByteCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAirMode/title",
          "value": "BluetoothAirMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAirMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAirMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAirMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAirMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXUnauthorizedError/title",
          "value": "kOBEXUnauthorizedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXUnauthorizedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXUnauthorizedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMajor/title",
          "value": "BluetoothDeviceClassMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceClassMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMajor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceClassMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/title",
          "value": "BluetoothAuthenticationRequirementsValues"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirementsValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothAuthenticationRequirementsValues"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXUnsupportedError/title",
          "value": "kOBEXUnsupportedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXUnsupportedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXUnsupportedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXGeneralError/title",
          "value": "kOBEXGeneralError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXGeneralError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXGeneralError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceName/title",
          "value": "BluetoothDeviceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionNoTransportError/title",
          "value": "kOBEXSessionNoTransportError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionNoTransportError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionNoTransportError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXErrorRangeMax/title",
          "value": "kOBEXErrorRangeMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXErrorRangeMax/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXErrorRangeMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionBadRequestError/title",
          "value": "kOBEXSessionBadRequestError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionBadRequestError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionBadRequestError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionAlreadyConnectedError/title",
          "value": "kOBEXSessionAlreadyConnectedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXSessionAlreadyConnectedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kOBEXSessionAlreadyConnectedError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/obexerrorcodes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/obexerrorcodes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
