{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBEXRealmValues"}]}]}],"seeAlsoSections":[{"anchor":"Data-Types","identifiers":["doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHMode","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAirMode","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAllowRoleSwitch","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirements","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEncryptionEnable","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIACLDataByteCount"],"title":"Data Types","generated":true}],"sections":[],"metadata":{"modules":[{"name":"IOBluetooth"}],"navigatorTitle":[{"kind":"identifier","text":"OBEXRealmValues"}],"role":"symbol","platforms":[{"unavailable":false,"deprecated":false,"name":"macOS","beta":false}],"title":"OBEXRealmValues","externalID":"c:@E@OBEXRealmValues","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OBEXRealmValues"}],"roleHeading":"Structure","symbolKind":"struct"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/iobluetooth/obexrealmvalues"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/iobluetooth/obexrealmvalues"]}],"abstract":[{"type":"text","text":"Values for Realm during digest response."}],"kind":"symbol","topicSections":[{"anchor":"Constants","identifiers":["doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmASCII","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88591","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88592","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88593","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88594","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88595","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88596","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88597","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88598","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88599","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmUNICODE"],"title":"Constants"},{"anchor":"Initializers","identifiers":["doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues/init(_:)","doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues/init(rawValue:)"],"title":"Initializers","generated":true},{"anchor":"Instance-Properties","identifiers":["doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues/rawValue"],"title":"Instance Properties","generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iobluetooth/documentation/IOBluetooth"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP"],"title":"Conforms To"}],"references":{"doc://com.externally.resolved.symbol/s:SQ":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","abstract":[{"text":"A type that can be compared for value equality.","type":"text"}],"url":"/documentation/Swift/Equatable","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Equatable"}],"type":"topic","title":"Equatable"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmASCII":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXRealmASCII"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXRealmValues","kind":"typeIdentifier","text":"OBEXRealmValues"}],"navigatorTitle":[{"kind":"identifier","text":"kOBEXRealmASCII"}],"url":"/documentation/iobluetooth/kobexrealmascii","abstract":[],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmASCII","role":"symbol","type":"topic","title":"kOBEXRealmASCII"},"doc://com.externally.resolved.symbol/s:SY":{"type":"topic","identifier":"doc://com.externally.resolved.symbol/s:SY","abstract":[{"type":"text","text":"A type that can be converted to and from an associated raw value."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RawRepresentable"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SY8RawValueQa","kind":"typeIdentifier","text":"RawValue"},{"kind":"text","text":">"}],"role":"symbol","url":"/documentation/Swift/RawRepresentable","title":"RawRepresentable"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice":{"url":"/documentation/iobluetooth/bluetoothclassofdevice","type":"topic","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice","title":"BluetoothClassOfDevice","navigatorTitle":[{"text":"BluetoothClassOfDevice","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BluetoothClassOfDevice","kind":"identifier"}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88595":{"navigatorTitle":[{"kind":"identifier","text":"kOBEXRealmISO88595"}],"type":"topic","title":"kOBEXRealmISO88595","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXRealmISO88595"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXRealmValues","kind":"typeIdentifier","text":"OBEXRealmValues"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88595","url":"/documentation/iobluetooth/kobexrealmiso88595","kind":"symbol","role":"symbol"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues":{"abstract":[],"title":"BluetoothAuthenticationRequirementsValues","navigatorTitle":[{"kind":"identifier","text":"BluetoothAuthenticationRequirementsValues"}],"role":"symbol","url":"/documentation/iobluetooth/bluetoothauthenticationrequirementsvalues","kind":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BluetoothAuthenticationRequirementsValues"}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset":{"url":"/documentation/iobluetooth/bluetoothclockoffset","type":"topic","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset","title":"BluetoothClockOffset","navigatorTitle":[{"text":"BluetoothClockOffset","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BluetoothClockOffset","kind":"identifier"}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88591":{"abstract":[],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88591","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXRealmISO88591"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXRealmValues","kind":"typeIdentifier","text":"OBEXRealmValues"}],"title":"kOBEXRealmISO88591","url":"/documentation/iobluetooth/kobexrealmiso88591","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kOBEXRealmISO88591"}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIACLDataByteCount":{"url":"/documentation/iobluetooth/bluetoothhciacldatabytecount","title":"BluetoothHCIACLDataByteCount","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIACLDataByteCount","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"BluetoothHCIACLDataByteCount"}],"navigatorTitle":[{"kind":"identifier","text":"BluetoothHCIACLDataByteCount"}],"role":"symbol","type":"topic"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88597":{"navigatorTitle":[{"kind":"identifier","text":"kOBEXRealmISO88597"}],"type":"topic","title":"kOBEXRealmISO88597","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXRealmISO88597"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXRealmValues","kind":"typeIdentifier","text":"OBEXRealmValues"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88597","url":"/documentation/iobluetooth/kobexrealmiso88597","kind":"symbol","role":"symbol"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName":{"url":"/documentation/iobluetooth/bluetoothdevicename","title":"BluetoothDeviceName","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"BluetoothDeviceName"}],"navigatorTitle":[{"kind":"identifier","text":"BluetoothDeviceName"}],"role":"symbol","type":"topic"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues":{"url":"/documentation/iobluetooth/obexrealmvalues","navigatorTitle":[{"text":"OBEXRealmValues","kind":"identifier"}],"title":"OBEXRealmValues","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBEXRealmValues","kind":"identifier"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues","kind":"symbol","abstract":[{"text":"Values for Realm during digest response.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88596":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXRealmISO88596"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXRealmValues","kind":"typeIdentifier","text":"OBEXRealmValues"}],"navigatorTitle":[{"kind":"identifier","text":"kOBEXRealmISO88596"}],"url":"/documentation/iobluetooth/kobexrealmiso88596","abstract":[],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88596","role":"symbol","type":"topic","title":"kOBEXRealmISO88596"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues/init(_:)":{"type":"topic","url":"/documentation/iobluetooth/obexrealmvalues/init(_:)","kind":"symbol","abstract":[],"role":"symbol","title":"init(_:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues/init(_:)"},"doc://com.apple.iobluetooth/documentation/IOBluetooth":{"kind":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth","abstract":[{"type":"text","text":"Gain user-space access to Bluetooth devices."}],"url":"/documentation/iobluetooth","role":"collection","type":"topic","title":"IOBluetooth"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88592":{"navigatorTitle":[{"kind":"identifier","text":"kOBEXRealmISO88592"}],"type":"topic","title":"kOBEXRealmISO88592","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXRealmISO88592"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXRealmValues","kind":"typeIdentifier","text":"OBEXRealmValues"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88592","url":"/documentation/iobluetooth/kobexrealmiso88592","kind":"symbol","role":"symbol"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88594":{"navigatorTitle":[{"text":"kOBEXRealmISO88594","kind":"identifier"}],"type":"topic","title":"kOBEXRealmISO88594","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kOBEXRealmISO88594"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXRealmValues","text":"OBEXRealmValues","kind":"typeIdentifier"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88594","url":"/documentation/iobluetooth/kobexrealmiso88594","kind":"symbol","role":"symbol"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers":{"type":"topic","url":"/documentation/iobluetooth/bluetoothcompanyidentifers","navigatorTitle":[{"text":"BluetoothCompanyIdentifers","kind":"identifier"}],"title":"BluetoothCompanyIdentifers","abstract":[],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BluetoothCompanyIdentifers"}],"role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/s:SH":{"type":"topic","identifier":"doc://com.externally.resolved.symbol/s:SH","abstract":[{"text":"A type that can be hashed into a `Hasher` to produce an integer hash value.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hashable"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SQ","kind":"typeIdentifier","text":"Equatable"}],"role":"symbol","url":"/documentation/Swift/Hashable","title":"Hashable"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirements":{"url":"/documentation/iobluetooth/bluetoothauthenticationrequirements","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BluetoothAuthenticationRequirements","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirements","role":"symbol","title":"BluetoothAuthenticationRequirements","navigatorTitle":[{"text":"BluetoothAuthenticationRequirements","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEncryptionEnable":{"url":"/documentation/iobluetooth/bluetoothencryptionenable","type":"topic","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEncryptionEnable","title":"BluetoothEncryptionEnable","navigatorTitle":[{"text":"BluetoothEncryptionEnable","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BluetoothEncryptionEnable","kind":"identifier"}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits":{"kind":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits","abstract":[],"url":"/documentation/iobluetooth/bluetoothfeaturebits","role":"symbol","navigatorTitle":[{"text":"BluetoothFeatureBits","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BluetoothFeatureBits","kind":"identifier"}],"type":"topic","title":"BluetoothFeatureBits"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88599":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXRealmISO88599"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXRealmValues","kind":"typeIdentifier","text":"OBEXRealmValues"}],"url":"/documentation/iobluetooth/kobexrealmiso88599","role":"symbol","title":"kOBEXRealmISO88599","kind":"symbol","type":"topic","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88599","navigatorTitle":[{"kind":"identifier","text":"kOBEXRealmISO88599"}]},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"url":"/documentation/Swift/BitwiseCopyable","identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","kind":"symbol","abstract":[{"type":"text","text":""}],"title":"BitwiseCopyable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BitwiseCopyable","kind":"identifier"},{"text":" : ~Escapable","kind":"text"}],"role":"symbol","type":"topic"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmUNICODE":{"navigatorTitle":[{"kind":"identifier","text":"kOBEXRealmUNICODE"}],"type":"topic","title":"kOBEXRealmUNICODE","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kOBEXRealmUNICODE","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXRealmValues","kind":"typeIdentifier","text":"OBEXRealmValues"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmUNICODE","url":"/documentation/iobluetooth/kobexrealmunicode","kind":"symbol","role":"symbol"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues/init(rawValue:)":{"type":"topic","url":"/documentation/iobluetooth/obexrealmvalues/init(rawvalue:)","kind":"symbol","abstract":[],"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues/init(rawValue:)"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor":{"url":"/documentation/iobluetooth/bluetoothdeviceclassmajor","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"BluetoothDeviceClassMajor"}],"type":"topic","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor","role":"symbol","title":"BluetoothDeviceClassMajor","navigatorTitle":[{"kind":"identifier","text":"BluetoothDeviceClassMajor"}],"kind":"symbol","abstract":[]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88593":{"navigatorTitle":[{"kind":"identifier","text":"kOBEXRealmISO88593"}],"type":"topic","title":"kOBEXRealmISO88593","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXRealmISO88593"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@OBEXRealmValues","kind":"typeIdentifier","text":"OBEXRealmValues"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88593","url":"/documentation/iobluetooth/kobexrealmiso88593","kind":"symbol","role":"symbol"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor":{"type":"topic","url":"/documentation/iobluetooth/bluetoothdeviceclassminor","navigatorTitle":[{"text":"BluetoothDeviceClassMinor","kind":"identifier"}],"title":"BluetoothDeviceClassMinor","abstract":[],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BluetoothDeviceClassMinor","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle":{"url":"/documentation/iobluetooth/bluetoothconnectionhandle","title":"BluetoothConnectionHandle","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle","kind":"symbol","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BluetoothConnectionHandle","kind":"identifier"}],"navigatorTitle":[{"text":"BluetoothConnectionHandle","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"type":"topic","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Sendable"}],"role":"symbol","url":"/documentation/Swift/Sendable","title":"Sendable"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHMode":{"kind":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHMode","abstract":[],"url":"/documentation/iobluetooth/bluetoothafhmode","role":"symbol","navigatorTitle":[{"text":"BluetoothAFHMode","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BluetoothAFHMode","kind":"identifier"}],"type":"topic","title":"BluetoothAFHMode"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAllowRoleSwitch":{"kind":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAllowRoleSwitch","abstract":[],"url":"/documentation/iobluetooth/bluetoothallowroleswitch","role":"symbol","navigatorTitle":[{"text":"BluetoothAllowRoleSwitch","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BluetoothAllowRoleSwitch","kind":"identifier"}],"type":"topic","title":"BluetoothAllowRoleSwitch"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88598":{"kind":"symbol","title":"kOBEXRealmISO88598","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88598","navigatorTitle":[{"text":"kOBEXRealmISO88598","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kOBEXRealmISO88598"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@OBEXRealmValues","text":"OBEXRealmValues","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"/documentation/iobluetooth/kobexrealmiso88598","abstract":[]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues/rawValue":{"type":"topic","url":"/documentation/iobluetooth/obexrealmvalues/rawvalue","kind":"symbol","abstract":[],"role":"symbol","title":"rawValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXRealmValues/rawValue"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAirMode":{"type":"topic","url":"/documentation/iobluetooth/bluetoothairmode","navigatorTitle":[{"text":"BluetoothAirMode","kind":"identifier"}],"title":"BluetoothAirMode","abstract":[],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAirMode","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BluetoothAirMode","kind":"identifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"deprecated":false,"name":"macOS","beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Enumeration","op":"replace","path":"/metadata/roleHeading"},{"value":"OBEXRealmValues","op":"replace","path":"/metadata/title"},{"value":"enum","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"OBEXRealmValues","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"kind":"identifier","text":"OBEXRealmValues"}],"op":"replace","path":"/metadata/navigatorTitle"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iobluetooth/documentation/IOBluetooth"]]},"op":"replace","path":"/hierarchy"},{"value":[{"title":"Constants","identifiers":["doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmASCII","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88591","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88592","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88593","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88594","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88595","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88596","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88597","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88598","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmISO88599","doc://com.apple.iobluetooth/documentation/IOBluetooth/kOBEXRealmUNICODE"],"anchor":"Constants"}],"op":"replace","path":"/topicSections"},{"value":null,"op":"replace","path":"/relationshipsSections"},{"value":[{"generated":true,"title":"Data Types","identifiers":["doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAFHMode","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAirMode","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAllowRoleSwitch","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirements","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothAuthenticationRequirementsValues","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClassOfDevice","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothClockOffset","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothCompanyIdentifers","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothEncryptionEnable","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothFeatureBits","doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCIACLDataByteCount"],"anchor":"Data-Types"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBEXRealmValues","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"unsigned int","preciseIdentifier":"c:i","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"kOBEXRealmASCII","op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmASCII/title"},{"value":[{"kind":"identifier","text":"kOBEXRealmASCII"}],"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmASCII/fragments"},{"value":"BluetoothClassOfDevice","op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClassOfDevice/title"},{"value":[{"text":"BluetoothClassOfDevice","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClassOfDevice/fragments"},{"value":[{"text":"BluetoothClassOfDevice","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClassOfDevice/navigatorTitle"},{"value":"kOBEXRealmISO88595","op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88595/title"},{"value":[{"text":"kOBEXRealmISO88595","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88595/fragments"},{"value":"BluetoothAuthenticationRequirementsValues","op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/title"},{"value":[{"kind":"identifier","text":"BluetoothAuthenticationRequirementsValues"}],"op":"replace","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/fragments"},{"value":[{"text":"BluetoothAuthenticationRequirementsValues","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirementsValues/navigatorTitle","op":"replace"},{"value":"BluetoothClockOffset","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClockOffset/title","op":"replace"},{"value":[{"text":"BluetoothClockOffset","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClockOffset/fragments","op":"replace"},{"value":[{"text":"BluetoothClockOffset","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothClockOffset/navigatorTitle","op":"replace"},{"value":"kOBEXRealmISO88591","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88591/title","op":"replace"},{"value":[{"kind":"identifier","text":"kOBEXRealmISO88591"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88591/fragments","op":"replace"},{"value":"BluetoothHCIACLDataByteCount","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIACLDataByteCount/title","op":"replace"},{"value":[{"kind":"identifier","text":"BluetoothHCIACLDataByteCount"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIACLDataByteCount/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"BluetoothHCIACLDataByteCount"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCIACLDataByteCount/navigatorTitle","op":"replace"},{"value":"kOBEXRealmISO88597","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88597/title","op":"replace"},{"value":[{"kind":"identifier","text":"kOBEXRealmISO88597"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88597/fragments","op":"replace"},{"value":"BluetoothDeviceName","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceName/title","op":"replace"},{"value":[{"text":"BluetoothDeviceName","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceName/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"BluetoothDeviceName"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceName/navigatorTitle","op":"replace"},{"value":"OBEXRealmValues","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXRealmValues/title","op":"replace"},{"value":[{"kind":"identifier","text":"OBEXRealmValues"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXRealmValues/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"OBEXRealmValues"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXRealmValues/navigatorTitle","op":"replace"},{"value":"kOBEXRealmISO88596","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88596/title","op":"replace"},{"value":[{"kind":"identifier","text":"kOBEXRealmISO88596"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88596/fragments","op":"replace"},{"value":"kOBEXRealmISO88592","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88592/title","op":"replace"},{"value":[{"text":"kOBEXRealmISO88592","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88592/fragments","op":"replace"},{"value":"kOBEXRealmISO88594","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88594/title","op":"replace"},{"value":[{"text":"kOBEXRealmISO88594","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88594/fragments","op":"replace"},{"value":"BluetoothCompanyIdentifers","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/title","op":"replace"},{"value":[{"text":"BluetoothCompanyIdentifers","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"BluetoothCompanyIdentifers"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothCompanyIdentifers/navigatorTitle","op":"replace"},{"value":"BluetoothAuthenticationRequirements","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirements/title","op":"replace"},{"value":[{"text":"BluetoothAuthenticationRequirements","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirements/fragments","op":"replace"},{"value":[{"text":"BluetoothAuthenticationRequirements","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAuthenticationRequirements/navigatorTitle","op":"replace"},{"value":"BluetoothEncryptionEnable","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEncryptionEnable/title","op":"replace"},{"value":[{"text":"BluetoothEncryptionEnable","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEncryptionEnable/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"BluetoothEncryptionEnable"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothEncryptionEnable/navigatorTitle","op":"replace"},{"value":"BluetoothFeatureBits","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/title","op":"replace"},{"value":[{"kind":"identifier","text":"BluetoothFeatureBits"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/fragments","op":"replace"},{"value":[{"text":"BluetoothFeatureBits","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothFeatureBits/navigatorTitle","op":"replace"},{"value":"kOBEXRealmISO88599","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88599/title","op":"replace"},{"value":[{"text":"kOBEXRealmISO88599","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88599/fragments","op":"replace"},{"value":"kOBEXRealmUNICODE","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmUNICODE/title","op":"replace"},{"value":[{"kind":"identifier","text":"kOBEXRealmUNICODE"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmUNICODE/fragments","op":"replace"},{"value":"BluetoothDeviceClassMajor","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMajor/title","op":"replace"},{"value":[{"kind":"identifier","text":"BluetoothDeviceClassMajor"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMajor/fragments","op":"replace"},{"value":[{"text":"BluetoothDeviceClassMajor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMajor/navigatorTitle","op":"replace"},{"value":"kOBEXRealmISO88593","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88593/title","op":"replace"},{"value":[{"text":"kOBEXRealmISO88593","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88593/fragments","op":"replace"},{"value":"BluetoothDeviceClassMinor","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMinor/title","op":"replace"},{"value":[{"kind":"identifier","text":"BluetoothDeviceClassMinor"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMinor/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"BluetoothDeviceClassMinor"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMinor/navigatorTitle","op":"replace"},{"value":"BluetoothConnectionHandle","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/title","op":"replace"},{"value":[{"kind":"identifier","text":"BluetoothConnectionHandle"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"BluetoothConnectionHandle"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/navigatorTitle","op":"replace"},{"value":"BluetoothAFHMode","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHMode/title","op":"replace"},{"value":[{"kind":"identifier","text":"BluetoothAFHMode"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHMode/fragments","op":"replace"},{"value":[{"text":"BluetoothAFHMode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAFHMode/navigatorTitle","op":"replace"},{"value":"BluetoothAllowRoleSwitch","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAllowRoleSwitch/title","op":"replace"},{"value":[{"text":"BluetoothAllowRoleSwitch","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAllowRoleSwitch/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"BluetoothAllowRoleSwitch"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAllowRoleSwitch/navigatorTitle","op":"replace"},{"value":"kOBEXRealmISO88598","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88598/title","op":"replace"},{"value":[{"kind":"identifier","text":"kOBEXRealmISO88598"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1kOBEXRealmISO88598/fragments","op":"replace"},{"value":"BluetoothAirMode","path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAirMode/title","op":"replace"},{"value":[{"text":"BluetoothAirMode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAirMode/fragments","op":"replace"},{"value":[{"text":"BluetoothAirMode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothAirMode/navigatorTitle","op":"replace"}]}],"diffAvailability":{"minor":{"change":"modified","platform":"Xcode","versions":["16.2","16.3 beta 2"]}},"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}