{
  "abstract": [
    {
      "text": "Creates a formatted vEvent, ready to be sent over OBEX or whatever. You probably will embed the output in a vCalendar event.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXCreateVEvent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@OBEXCreateVEvent",
    "fragments": [
      {
        "kind": "identifier",
        "text": "OBEXCreateVEvent"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "OBEXCreateVEvent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.6",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "OBEXCreateVEvent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDataRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFDataRef",
              "text": "CFDataRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "OBEXCreateVEvent"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "inCharset"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32_t",
              "text": "uint32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inCharsetLength"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "inEncoding"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32_t",
              "text": "uint32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inEncodingLength"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "inEventStartDate"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32_t",
              "text": "uint32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inEventStartDateLength"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "inEventEndDate"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32_t",
              "text": "uint32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inEventEndDateLength"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "inAlarmDate"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32_t",
              "text": "uint32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inAlarmDateLength"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "inCategory"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32_t",
              "text": "uint32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inCategoryLength"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "inSummary"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32_t",
              "text": "uint32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inSummaryLength"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "inLocation"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32_t",
              "text": "uint32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inLocationLength"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:C",
              "text": "char"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "inXIRMCLUID"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32_t",
              "text": "uint32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inXIRMCLUIDLength"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The Charset the passed data is in. Pass in a #defined charset for ease of use.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inCharset"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The length of the Charset passed data.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inCharsetLength"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The encoding of the summary and location fields.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inEncoding"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Start of event date, in the (ISO8601) format: YYYYMMDDTHHMMSS. e.g. 19960415T083000 = 8:30 am on April 15, 1996. All time values should be in LOCAL time.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inEventStartDate"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "End of event date.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inEventEndDate"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Date of Alarm for event, in the format: YYYYMMDDTHHMMSS.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inAlarmDate"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Category of event, such as “MEETING” or “PHONE CALL”.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inCategory"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Summary of event. Max length is 36 bytes. Longer will result in a bad argument error.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inSummary"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Summary of event. Max length is 20 bytes. Longer will result in a bad argument error.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inLocation"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The IRMC Local Unique Identifier Label, max length 12 bytes. Longer will result in a bad argument error.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inXIRMCLUID"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A valid CFDataRef - nil if we failed.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "All parameters are optional. The CFDataRef returned to you is NOT retained. Retain it if you want to keep it. Be aware that certain devices such as Ericsson phones MUST have certain fields, such as a start and end date.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "*** DEPRECATED IN BLUETOOTH 2.2 (OS X v10.6) *** You should transition your code to Objective-C equivalents. *** This API may be removed any time in the future.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/GET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT": {
      "abstract": [
        {
          "text": "Convenience Macros for working with OBEX Header Identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "GET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/GET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT",
      "kind": "symbol",
      "role": "symbol",
      "title": "GET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT",
      "type": "topic",
      "url": "/documentation/iobluetooth/get_header_id_is_null_terminated_unicode_text"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddApplicationParameterHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add bytes representing an application parameter to a dictionary of OBEX headers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddApplicationParameterHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddApplicationParameterHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddApplicationParameterHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddApplicationParameterHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddapplicationparameterheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddAuthorizationChallengeHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add an authorization challenge header to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddAuthorizationChallengeHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddAuthorizationChallengeHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddAuthorizationChallengeHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddAuthorizationChallengeHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddauthorizationchallengeheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddAuthorizationResponseHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add an authorization Response header to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddAuthorizationResponseHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddAuthorizationResponseHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddAuthorizationResponseHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddAuthorizationResponseHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddauthorizationresponseheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddBodyHeader(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Add bytes of data to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddBodyHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddBodyHeader(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddBodyHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddBodyHeader(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddbodyheader(_:_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddByteSequenceHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add a byte sequence header to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddByteSequenceHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddByteSequenceHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddByteSequenceHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddByteSequenceHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddbytesequenceheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddConnectionIDHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add bytes representing a connection ID to a dictionary of OBEX headers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddConnectionIDHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddConnectionIDHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddConnectionIDHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddConnectionIDHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddconnectionidheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddCountHeader(_:_:)": {
      "abstract": [
        {
          "text": "Add a CFStringRef to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddCountHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddCountHeader(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddCountHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddCountHeader(_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddcountheader(_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddDescriptionHeader(_:_:)": {
      "abstract": [
        {
          "text": "Add a CFStringRef to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddDescriptionHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddDescriptionHeader(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddDescriptionHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddDescriptionHeader(_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexadddescriptionheader(_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddHTTPHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add bytes of data to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddHTTPHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddHTTPHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddHTTPHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddHTTPHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddhttpheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddLengthHeader(_:_:)": {
      "abstract": [
        {
          "text": "Add a CFStringRef to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddLengthHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddLengthHeader(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddLengthHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddLengthHeader(_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddlengthheader(_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddNameHeader(_:_:)": {
      "abstract": [
        {
          "text": "Add a CFStringRef to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddNameHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddNameHeader(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddNameHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddNameHeader(_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddnameheader(_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddObjectClassHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add an object class header to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddObjectClassHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddObjectClassHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddObjectClassHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddObjectClassHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddobjectclassheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTargetHeader(_:_:_:)": {
      "abstract": [
        {
          "text": "Add bytes of data to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddTargetHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTargetHeader(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddTargetHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddTargetHeader(_:_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddtargetheader(_:_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTime4ByteHeader(_:_:)": {
      "abstract": [
        {
          "text": "Add a CFStringRef to a dictionary of OBEXheaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OBEXAddTime4ByteHeader"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFMutableDictionaryRef",
          "text": "CFMutableDictionary"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OBEXError",
          "text": "OBEXError"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTime4ByteHeader(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OBEXAddTime4ByteHeader"
        }
      ],
      "role": "symbol",
      "title": "OBEXAddTime4ByteHeader(_:_:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexaddtime4byteheader(_:_:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXCreateVEvent": {
      "abstract": [
        {
          "text": "Creates a formatted vEvent, ready to be sent over OBEX or whatever. You probably will embed the output in a vCalendar event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OBEXCreateVEvent"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXCreateVEvent",
      "kind": "symbol",
      "role": "symbol",
      "title": "OBEXCreateVEvent",
      "type": "topic",
      "url": "/documentation/iobluetooth/obexcreatevevent"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFDataRef": {
      "abstract": [
        {
          "text": "A reference to an immutable CFData object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFData"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDataRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFData",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdata"
    },
    "doc://com.externally.resolved.symbol/c:@T@uint32_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint32_t",
      "type": "topic",
      "url": "/documentation/kernel/uint32_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Miscellaneous",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/GET_HEADER_ID_IS_NULL_TERMINATED_UNICODE_TEXT",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddApplicationParameterHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddAuthorizationChallengeHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddAuthorizationResponseHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddBodyHeader(_:_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddByteSequenceHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddConnectionIDHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddCountHeader(_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddDescriptionHeader(_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddHTTPHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddLengthHeader(_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddNameHeader(_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddObjectClassHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTargetHeader(_:_:_:)",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXAddTime4ByteHeader(_:_:)"
      ],
      "title": "Miscellaneous"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddBodyHeader(_:_:_:_:)/title",
          "value": "OBEXAddBodyHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddBodyHeader(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddBodyHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddHTTPHeader(_:_:_:)/title",
          "value": "OBEXAddHTTPHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddHTTPHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddHTTPHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddObjectClassHeader(_:_:_:)/title",
          "value": "OBEXAddObjectClassHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddObjectClassHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddObjectClassHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddDescriptionHeader(_:_:)/title",
          "value": "OBEXAddDescriptionHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddDescriptionHeader(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddDescriptionHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFDataRef/title",
          "value": "CFDataRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddByteSequenceHeader(_:_:_:)/title",
          "value": "OBEXAddByteSequenceHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddByteSequenceHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddByteSequenceHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddNameHeader(_:_:)/title",
          "value": "OBEXAddNameHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddNameHeader(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddNameHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddConnectionIDHeader(_:_:_:)/title",
          "value": "OBEXAddConnectionIDHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddConnectionIDHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddConnectionIDHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddCountHeader(_:_:)/title",
          "value": "OBEXAddCountHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddCountHeader(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddCountHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddApplicationParameterHeader(_:_:_:)/title",
          "value": "OBEXAddApplicationParameterHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddApplicationParameterHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddApplicationParameterHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddAuthorizationResponseHeader(_:_:_:)/title",
          "value": "OBEXAddAuthorizationResponseHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddAuthorizationResponseHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddAuthorizationResponseHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddAuthorizationChallengeHeader(_:_:_:)/title",
          "value": "OBEXAddAuthorizationChallengeHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddAuthorizationChallengeHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddAuthorizationChallengeHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddLengthHeader(_:_:)/title",
          "value": "OBEXAddLengthHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddLengthHeader(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddLengthHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddTargetHeader(_:_:_:)/title",
          "value": "OBEXAddTargetHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddTargetHeader(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddTargetHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddTime4ByteHeader(_:_:)/title",
          "value": "OBEXAddTime4ByteHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXAddTime4ByteHeader(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OBEXAddTime4ByteHeader"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/obexcreatevevent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
