{
  "abstract": [
    {
      "text": "Read the parts of an SMS message.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/sms-dictionary-key-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "SMS Dictionary Key Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods for receiving status change updates and information about a connected Bluetooth hands-free phone or headset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeDeviceDelegate"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeDeviceDelegate"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeDeviceDelegate",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreedevicedelegate"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:incomingSMS:)": {
      "abstract": [
        {
          "text": "Tells the delegate there’s an incoming text message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handsFree"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)IOBluetoothHandsFreeDevice",
          "text": "IOBluetoothHandsFreeDevice"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "incomingSMS"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!)"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:incomingSMS:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handsFree:incomingSMS:"
        }
      ],
      "role": "symbol",
      "title": "handsFree(_:incomingSMS:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreedevicedelegate/handsfree(_:incomingsms:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUEncoding": {
      "abstract": [
        {
          "text": "The encoding for the text message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothPDUEncoding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUEncoding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothPDUEncoding"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothPDUEncoding",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothpduencoding"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUOriginatingAddress": {
      "abstract": [
        {
          "text": "The phone number for the sender of the text message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothPDUOriginatingAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUOriginatingAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothPDUOriginatingAddress"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothPDUOriginatingAddress",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothpduoriginatingaddress"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUOriginatingAddressType": {
      "abstract": [
        {
          "text": "The format of the phone number for the sender of the text message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothPDUOriginatingAddressType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUOriginatingAddressType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothPDUOriginatingAddressType"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothPDUOriginatingAddressType",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothpduoriginatingaddresstype"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUProtocolID": {
      "abstract": [
        {
          "text": "The protocol of the text message content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothPDUProtocolID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUProtocolID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothPDUProtocolID"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothPDUProtocolID",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothpduprotocolid"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUServicCenterAddress": {
      "abstract": [
        {
          "text": "The phone number for the service center that stored and then delivered the message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothPDUServicCenterAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUServicCenterAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothPDUServicCenterAddress"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothPDUServicCenterAddress",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothpduserviccenteraddress"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUServiceCenterAddressType": {
      "abstract": [
        {
          "text": "The format of the phone number for the service center.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothPDUServiceCenterAddressType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUServiceCenterAddressType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothPDUServiceCenterAddressType"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothPDUServiceCenterAddressType",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothpduservicecenteraddresstype"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUTimestamp": {
      "abstract": [
        {
          "text": "The time the text message was sent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothPDUTimestamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUTimestamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothPDUTimestamp"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothPDUTimestamp",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothpdutimestamp"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUType": {
      "abstract": [
        {
          "text": "The GSM type of the text message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothPDUType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothPDUType"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothPDUType",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothpdutype"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUUserData": {
      "abstract": [
        {
          "text": "The content of the text message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothPDUUserData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUUserData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothPDUUserData"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothPDUUserData",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothpduuserdata"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Receiving-SMS-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:incomingSMS:)"
      ],
      "title": "Receiving SMS Information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Sender-Information",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUOriginatingAddress",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUOriginatingAddressType",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUServicCenterAddress",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUServiceCenterAddressType"
      ],
      "title": "Sender Information"
    },
    {
      "anchor": "Message-Information",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUProtocolID",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUUserData",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUTimestamp",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUType",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUEncoding"
      ],
      "title": "Message Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Sender-Information",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUOriginatingAddress",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUOriginatingAddressType",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUServicCenterAddress",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUServiceCenterAddressType"
              ],
              "title": "Sender Information"
            },
            {
              "anchor": "Message-Information",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUProtocolID",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUUserData",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUTimestamp",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUType",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothPDUEncoding"
              ],
              "title": "Message Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Receiving-SMS-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeDeviceDelegate/handsFree(_:incomingSMS:)"
              ],
              "title": "Receiving SMS Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothPDUOriginatingAddressType/title",
          "value": "IOBluetoothPDUOriginatingAddressType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothPDUOriginatingAddressType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPDUOriginatingAddressType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothPDUEncoding/title",
          "value": "IOBluetoothPDUEncoding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothPDUEncoding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPDUEncoding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothPDUServiceCenterAddressType/title",
          "value": "IOBluetoothPDUServiceCenterAddressType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothPDUServiceCenterAddressType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPDUServiceCenterAddressType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothPDUServicCenterAddress/title",
          "value": "IOBluetoothPDUServicCenterAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothPDUServicCenterAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPDUServicCenterAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothPDUProtocolID/title",
          "value": "IOBluetoothPDUProtocolID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothPDUProtocolID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPDUProtocolID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothPDUType/title",
          "value": "IOBluetoothPDUType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothPDUType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPDUType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothPDUUserData/title",
          "value": "IOBluetoothPDUUserData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothPDUUserData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPDUUserData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothPDUOriginatingAddress/title",
          "value": "IOBluetoothPDUOriginatingAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothPDUOriginatingAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPDUOriginatingAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate~1handsFree(_:incomingSMS:)/title",
          "value": "handsFree:incomingSMS:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate~1handsFree(_:incomingSMS:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handsFree:incomingSMS:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothPDUTimestamp/title",
          "value": "IOBluetoothPDUTimestamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothPDUTimestamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothPDUTimestamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate/title",
          "value": "IOBluetoothHandsFreeDeviceDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeDeviceDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeDeviceDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeDeviceDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/sms-dictionary-key-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/sms-dictionary-key-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
