{
  "abstract": [
    {
      "text": "Send commands to modify the status indicators of a hands-free Bluetooth device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGateway"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/status-indicator-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Status Indicator Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGateway": {
      "abstract": [
        {
          "text": "An object that sends data to a connected Bluetooth hands-free phone or headset and processes commands from it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeAudioGateway"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGateway",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeAudioGateway"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeAudioGateway",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreeaudiogateway"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGateway/createIndicator(_:min:max:currentValue:)": {
      "abstract": [
        {
          "text": "Sends a request to the Bluetooth device to show or update a status indicator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createIndicator"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "min"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "max"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "currentValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGateway/createIndicator(_:min:max:currentValue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "createIndicator:min:max:currentValue:"
        }
      ],
      "role": "symbol",
      "title": "createIndicator(_:min:max:currentValue:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreeaudiogateway/createindicator(_:min:max:currentvalue:)"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorBattChg": {
      "abstract": [
        {
          "text": "The command string you use to show a battery charge level indicator on a phone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeIndicatorBattChg"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorBattChg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeIndicatorBattChg"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeIndicatorBattChg",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreeindicatorbattchg"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCall": {
      "abstract": [
        {
          "text": "The command string you use to show an active call indicator on a phone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeIndicatorCall"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeIndicatorCall"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeIndicatorCall",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreeindicatorcall"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCallHeld": {
      "abstract": [
        {
          "text": "The command string you use to show a call hold status indicator on a phone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeIndicatorCallHeld"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCallHeld",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeIndicatorCallHeld"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeIndicatorCallHeld",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreeindicatorcallheld"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCallSetup": {
      "abstract": [
        {
          "text": "The command string you use to show a call setup status indicator on a phone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeIndicatorCallSetup"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCallSetup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeIndicatorCallSetup"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeIndicatorCallSetup",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreeindicatorcallsetup"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorRoam": {
      "abstract": [
        {
          "text": "The command string you use to show a roaming status indicator on a phone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeIndicatorRoam"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorRoam",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeIndicatorRoam"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeIndicatorRoam",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreeindicatorroam"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorService": {
      "abstract": [
        {
          "text": "The command string you use to show a carrier network connection indicator on a phone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeIndicatorService"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeIndicatorService"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeIndicatorService",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreeindicatorservice"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorSignal": {
      "abstract": [
        {
          "text": "The command string you use to show a signal strength indicator on a phone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeIndicatorSignal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorSignal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothHandsFreeIndicatorSignal"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothHandsFreeIndicatorSignal",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothhandsfreeindicatorsignal"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Showing-Status-Indicators",
      "generated": true,
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGateway/createIndicator(_:min:max:currentValue:)"
      ],
      "title": "Showing Status Indicators"
    }
  ],
  "topicSections": [
    {
      "anchor": "Call-Status",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCall",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCallHeld",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCallSetup"
      ],
      "title": "Call Status"
    },
    {
      "anchor": "Phone-Network-Connection",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorRoam",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorSignal",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorService"
      ],
      "title": "Phone Network Connection"
    },
    {
      "anchor": "Phone-Status",
      "identifiers": [
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorBattChg"
      ],
      "title": "Phone Status"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Call-Status",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCall",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCallHeld",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorCallSetup"
              ],
              "title": "Call Status"
            },
            {
              "anchor": "Phone-Network-Connection",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorRoam",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorSignal",
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorService"
              ],
              "title": "Phone Network Connection"
            },
            {
              "anchor": "Phone-Status",
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeIndicatorBattChg"
              ],
              "title": "Phone Status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Showing-Status-Indicators",
              "generated": true,
              "identifiers": [
                "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothHandsFreeAudioGateway/createIndicator(_:min:max:currentValue:)"
              ],
              "title": "Showing Status Indicators"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeAudioGateway/title",
          "value": "IOBluetoothHandsFreeAudioGateway"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeAudioGateway/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeAudioGateway"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeAudioGateway/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeAudioGateway"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorRoam/title",
          "value": "IOBluetoothHandsFreeIndicatorRoam"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorRoam/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeIndicatorRoam"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorCall/title",
          "value": "IOBluetoothHandsFreeIndicatorCall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorCall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeIndicatorCall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorService/title",
          "value": "IOBluetoothHandsFreeIndicatorService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeIndicatorService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorCallSetup/title",
          "value": "IOBluetoothHandsFreeIndicatorCallSetup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorCallSetup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeIndicatorCallSetup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeAudioGateway~1createIndicator(_:min:max:currentValue:)/title",
          "value": "createIndicator:min:max:currentValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeAudioGateway~1createIndicator(_:min:max:currentValue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "createIndicator:min:max:currentValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorSignal/title",
          "value": "IOBluetoothHandsFreeIndicatorSignal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorSignal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeIndicatorSignal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorCallHeld/title",
          "value": "IOBluetoothHandsFreeIndicatorCallHeld"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorCallHeld/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeIndicatorCallHeld"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorBattChg/title",
          "value": "IOBluetoothHandsFreeIndicatorBattChg"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothHandsFreeIndicatorBattChg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothHandsFreeIndicatorBattChg"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/status-indicator-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/iobluetooth/status-indicator-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
