{
  "abstract": [
    {
      "text": "A response code that indicates you want to handle the intent in your app instead.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/handleInApp"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INResumeWorkoutIntentResponseCode@INResumeWorkoutIntentResponseCodeHandleInApp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "handleInApp"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INResumeWorkoutIntentResponseCodeHandleInApp"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INResumeWorkoutIntentResponseCode.handleInApp"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "handleInApp"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this code when you want SiriKit to launch your app in the background so that you can handle the intent there. With this code, the user continues to interact with Siri, but your app has an opportunity to update your workout session or any other workout information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode": {
      "abstract": [
        {
          "text": "Constants that indicate the response state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INResumeWorkoutIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INResumeWorkoutIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INResumeWorkoutIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/inresumeworkoutintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/continueInApp": {
      "abstract": [
        {
          "text": "A response code that indicates your app extension is ready to transfer control to the app to start the workout.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continueInApp"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/continueInApp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INResumeWorkoutIntentResponseCodeContinueInApp"
        }
      ],
      "role": "symbol",
      "title": "INResumeWorkoutIntentResponseCode.continueInApp",
      "type": "topic",
      "url": "/documentation/intents/inresumeworkoutintentresponsecode/continueinapp"
    },
    "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/failure": {
      "abstract": [
        {
          "text": "A response code that indicates you were unable to start the specified workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INResumeWorkoutIntentResponseCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INResumeWorkoutIntentResponseCode.failure",
      "type": "topic",
      "url": "/documentation/intents/inresumeworkoutintentresponsecode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/failureNoMatchingWorkout": {
      "abstract": [
        {
          "text": "A response code that indicates you didn’t find the specified workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureNoMatchingWorkout"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/failureNoMatchingWorkout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INResumeWorkoutIntentResponseCodeFailureNoMatchingWorkout"
        }
      ],
      "role": "symbol",
      "title": "INResumeWorkoutIntentResponseCode.failureNoMatchingWorkout",
      "type": "topic",
      "url": "/documentation/intents/inresumeworkoutintentresponsecode/failurenomatchingworkout"
    },
    "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/failureRequiringAppLaunch": {
      "abstract": [
        {
          "text": "A response code that indicates the user must launch your app to start the workout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/failureRequiringAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INResumeWorkoutIntentResponseCodeFailureRequiringAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "INResumeWorkoutIntentResponseCode.failureRequiringAppLaunch",
      "type": "topic",
      "url": "/documentation/intents/inresumeworkoutintentresponsecode/failurerequiringapplaunch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/handleInApp": {
      "abstract": [
        {
          "text": "A response code that indicates you want to handle the intent in your app instead.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handleInApp"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/handleInApp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INResumeWorkoutIntentResponseCodeHandleInApp"
        }
      ],
      "role": "symbol",
      "title": "INResumeWorkoutIntentResponseCode.handleInApp",
      "type": "topic",
      "url": "/documentation/intents/inresumeworkoutintentresponsecode/handleinapp"
    },
    "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/ready": {
      "abstract": [
        {
          "text": "A response code that indicates app readiness.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INResumeWorkoutIntentResponseCodeReady"
        }
      ],
      "role": "symbol",
      "title": "INResumeWorkoutIntentResponseCode.ready",
      "type": "topic",
      "url": "/documentation/intents/inresumeworkoutintentresponsecode/ready"
    },
    "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/success": {
      "abstract": [
        {
          "text": "A response code that indicates your app succeeded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INResumeWorkoutIntentResponseCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "INResumeWorkoutIntentResponseCode.success",
      "type": "topic",
      "url": "/documentation/intents/inresumeworkoutintentresponsecode/success"
    },
    "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/unspecified": {
      "abstract": [
        {
          "text": "A response code that indicates an unknown state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INResumeWorkoutIntentResponseCodeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INResumeWorkoutIntentResponseCode.unspecified",
      "type": "topic",
      "url": "/documentation/intents/inresumeworkoutintentresponsecode/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Response-State",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/unspecified",
        "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/ready",
        "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/continueInApp",
        "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/success",
        "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/failure",
        "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/failureRequiringAppLaunch",
        "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/failureNoMatchingWorkout"
      ],
      "title": "Response State"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INResumeWorkoutIntentResponseCodeHandleInApp"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INResumeWorkoutIntentResponseCodeHandleInApp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Response-State",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/unspecified",
                "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/ready",
                "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/continueInApp",
                "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/success",
                "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/failure",
                "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/failureRequiringAppLaunch",
                "doc://com.apple.sirikit/documentation/Intents/INResumeWorkoutIntentResponseCode/failureNoMatchingWorkout"
              ],
              "title": "Response State"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INResumeWorkoutIntentResponseCodeHandleInApp"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INResumeWorkoutIntentResponseCode~1handleInApp/title",
          "value": "INResumeWorkoutIntentResponseCodeHandleInApp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INResumeWorkoutIntentResponseCode~1handleInApp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INResumeWorkoutIntentResponseCodeHandleInApp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INResumeWorkoutIntentResponseCode~1ready/title",
          "value": "INResumeWorkoutIntentResponseCodeReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INResumeWorkoutIntentResponseCode~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INResumeWorkoutIntentResponseCodeReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INResumeWorkoutIntentResponseCode~1failureNoMatchingWorkout/title",
          "value": "INResumeWorkoutIntentResponseCodeFailureNoMatchingWorkout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INResumeWorkoutIntentResponseCode~1failureNoMatchingWorkout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INResumeWorkoutIntentResponseCodeFailureNoMatchingWorkout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INResumeWorkoutIntentResponseCode/title",
          "value": "INResumeWorkoutIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INResumeWorkoutIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INResumeWorkoutIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INResumeWorkoutIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INResumeWorkoutIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INResumeWorkoutIntentResponseCode~1success/title",
          "value": "INResumeWorkoutIntentResponseCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INResumeWorkoutIntentResponseCode~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INResumeWorkoutIntentResponseCodeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INResumeWorkoutIntentResponseCode~1unspecified/title",
          "value": "INResumeWorkoutIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INResumeWorkoutIntentResponseCode~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INResumeWorkoutIntentResponseCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INResumeWorkoutIntentResponseCode~1failureRequiringAppLaunch/title",
          "value": "INResumeWorkoutIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INResumeWorkoutIntentResponseCode~1failureRequiringAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INResumeWorkoutIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INResumeWorkoutIntentResponseCode~1continueInApp/title",
          "value": "INResumeWorkoutIntentResponseCodeContinueInApp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INResumeWorkoutIntentResponseCode~1continueInApp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INResumeWorkoutIntentResponseCodeContinueInApp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INResumeWorkoutIntentResponseCode~1failure/title",
          "value": "INResumeWorkoutIntentResponseCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INResumeWorkoutIntentResponseCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INResumeWorkoutIntentResponseCodeFailure"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inresumeworkoutintentresponsecode/handleinapp"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inresumeworkoutintentresponsecode/handleinapp"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
