{
  "abstract": [
    {
      "text": "Error codes that indicate why a GPU is unable to finish running a command buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLCommandBufferError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTLCommandBufferError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBuffer": {
      "abstract": [
        {
          "text": "A container that stores a sequence of GPU commands that you encode into it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCommandBuffer"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBuffer"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBuffer",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffer"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferDescriptor": {
      "abstract": [
        {
          "text": "A configuration that customizes the behavior for a new command buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCommandBufferDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbufferdescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-c.enum/MTLCommandBufferErrorAccessRevoked": {
      "abstract": [
        {
          "text": "An error code that indicates the system has revoked the Metal device’s access because it’s responsible for too many timeouts or hangs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorAccessRevoked"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-c.enum/MTLCommandBufferErrorAccessRevoked",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLCommandBufferErrorAccessRevoked",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-c.enum/mtlcommandbuffererroraccessrevoked"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct": {
      "abstract": [
        {
          "text": "The command buffer error codes that indicate why the GPU doesn’t finish executing a command buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCommandBufferError"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferError"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes that indicate why a GPU is unable to finish running a command buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/accessRevoked": {
      "abstract": [
        {
          "text": "An error code that indicates the system has revoked the Metal device’s access because it’s responsible for too many timeouts or hangs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessRevoked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21MTLCommandBufferErrorLeV",
          "text": "MTLCommandBufferError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLCommandBufferError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/accessRevoked",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessRevoked",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/accessrevoked"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/blacklisted": {
      "abstract": [
        {
          "text": "A former error code that indicates the system has revoked the Metal device’s access because it’s responsible for too many timeouts or hangs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blacklisted"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/blacklisted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorBlacklisted"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code.blacklisted",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/blacklisted"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/deviceRemoved": {
      "abstract": [
        {
          "text": "An error code that indicates a person physically removed the GPU device before the command buffer finished running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceRemoved"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/deviceRemoved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorDeviceRemoved"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code.deviceRemoved",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/deviceremoved"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/init(rawvalue:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/internal": {
      "abstract": [
        {
          "text": "An error code that indicates the Metal framework has an internal problem.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`internal`"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/internal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorInternal"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code.internal",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/internal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/invalidResource": {
      "abstract": [
        {
          "text": "An error code that indicates the command buffer has an invalid reference to resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidResource"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/invalidResource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorInvalidResource"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code.invalidResource",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/invalidresource"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/memoryless": {
      "abstract": [
        {
          "text": "An error code that indicates the GPU ran out of one or more of its internal resources that support memoryless render pass attachments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "memoryless"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/memoryless",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorMemoryless"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code.memoryless",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/memoryless"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/none": {
      "abstract": [
        {
          "text": "An error code that represents the absence of any problems.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorNone"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code.none",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/none"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/notPermitted": {
      "abstract": [
        {
          "text": "An error code that indicates a process doesn’t have access to a GPU device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notPermitted"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/notPermitted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorNotPermitted"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code.notPermitted",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/notpermitted"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/outOfMemory": {
      "abstract": [
        {
          "text": "An error code that indicates the GPU device doesn’t have sufficient memory to execute a command buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outOfMemory"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/outOfMemory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorOutOfMemory"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code.outOfMemory",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/outofmemory"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/pageFault": {
      "abstract": [
        {
          "text": "An error code that indicates the command buffer generated a page fault the GPU can’t service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageFault"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/pageFault",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorPageFault"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code.pageFault",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/pagefault"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/stackOverflow": {
      "abstract": [
        {
          "text": "An error code that indicates the GPU terminated the command buffer because a kernel function of tile shader used too many stack frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stackOverflow"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/stackOverflow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorStackOverflow"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code.stackOverflow",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/stackoverflow"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/timeout": {
      "abstract": [
        {
          "text": "An error code that indicates the system interrupted and terminated the command buffer because it took more time to execute than the system allows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeout"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/timeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorTimeout"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code.timeout",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code/timeout"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferErrorDomain": {
      "abstract": [
        {
          "text": "The domain for Metal command buffer errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferErrorDomain",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererrordomain"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandEncoder": {
      "abstract": [
        {
          "text": "An encoder that writes GPU commands into a command buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCommandEncoder"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandEncoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandEncoder"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandEncoder",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandencoder"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandQueue": {
      "abstract": [
        {
          "text": "An instance you use to create, submit, and schedule command buffers to a specific GPU device to run the commands within those buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCommandQueue"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandQueue"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandQueue",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandqueue"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandQueueDescriptor": {
      "abstract": [
        {
          "text": "A configuration that customizes the behavior for a new command queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCommandQueueDescriptor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandQueueDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandQueueDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandQueueDescriptor",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandqueuedescriptor"
    },
    "doc://com.apple.metal/documentation/Metal/setting-up-a-command-structure": {
      "abstract": [
        {
          "text": "Discover how Metal executes commands on a GPU.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/setting-up-a-command-structure",
      "kind": "article",
      "role": "article",
      "title": "Setting Up a Command Structure",
      "type": "topic",
      "url": "/documentation/metal/setting-up-a-command-structure"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/none",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/timeout",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/pageFault",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/notPermitted",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/outOfMemory",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/invalidResource",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/memoryless",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/deviceRemoved",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/stackOverflow",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/accessRevoked",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/internal",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/none",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/timeout",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/pageFault",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/notPermitted",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/outOfMemory",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/invalidResource",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/memoryless",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/deviceRemoved",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/stackOverflow",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/internal"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/blacklisted",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/blacklisted"
      ],
      "title": "Deprecated"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLCommandBufferError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/none",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/timeout",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/pageFault",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/notPermitted",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/outOfMemory",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/invalidResource",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/memoryless",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/deviceRemoved",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/stackOverflow",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/internal",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/none",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/timeout",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/pageFault",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/notPermitted",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/outOfMemory",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/invalidResource",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/memoryless",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/deviceRemoved",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/stackOverflow",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-c.enum/MTLCommandBufferErrorAccessRevoked",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/internal"
              ],
              "title": "Error Codes"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/blacklisted",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code/blacklisted"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Submitting-Work-to-a-GPU",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/setting-up-a-command-structure",
                "doc://com.apple.metal/documentation/Metal/MTLCommandQueue",
                "doc://com.apple.metal/documentation/Metal/MTLCommandQueueDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBuffer",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferDescriptor",
                "doc://com.apple.metal/documentation/Metal/MTLCommandBufferErrorDomain",
                "doc://com.apple.metal/documentation/Metal/MTLCommandEncoder"
              ],
              "title": "Submitting Work to a GPU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTLCommandBufferError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBuffer/title",
          "value": "MTLCommandBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBuffer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1internal/title",
          "value": "MTLCommandBufferErrorInternal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1internal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorInternal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandQueue/title",
          "value": "MTLCommandQueue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandQueue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandQueue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1stackOverflow/title",
          "value": "MTLCommandBufferErrorStackOverflow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1stackOverflow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorStackOverflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1memoryless/title",
          "value": "MTLCommandBufferErrorMemoryless"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1memoryless/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorMemoryless"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code/title",
          "value": "MTLCommandBufferError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1invalidResource/title",
          "value": "MTLCommandBufferErrorInvalidResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1invalidResource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorInvalidResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandEncoder/title",
          "value": "MTLCommandEncoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandEncoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandEncoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1pageFault/title",
          "value": "MTLCommandBufferErrorPageFault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1pageFault/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorPageFault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1blacklisted/title",
          "value": "MTLCommandBufferErrorBlacklisted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1blacklisted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorBlacklisted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1none/title",
          "value": "MTLCommandBufferErrorNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1notPermitted/title",
          "value": "MTLCommandBufferErrorNotPermitted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1notPermitted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorNotPermitted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1deviceRemoved/title",
          "value": "MTLCommandBufferErrorDeviceRemoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1deviceRemoved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorDeviceRemoved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferDescriptor/title",
          "value": "MTLCommandBufferDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferErrorDomain/title",
          "value": "MTLCommandBufferErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1timeout/title",
          "value": "MTLCommandBufferErrorTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1timeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandQueueDescriptor/title",
          "value": "MTLCommandQueueDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandQueueDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandQueueDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandQueueDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandQueueDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1outOfMemory/title",
          "value": "MTLCommandBufferErrorOutOfMemory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code~1outOfMemory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferErrorOutOfMemory"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlcommandbuffererror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlcommandbuffererror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
