{
  "abstract": [
    {
      "text": "An error code that indicates the GPU device doesn’t have sufficient memory to execute a command buffer.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/outOfMemory"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC21MTLCommandBufferErrorLeV11outOfMemorySoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "outOfMemory"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC21MTLCommandBufferErrorLeV",
        "text": "MTLCommandBufferError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MTLCommandBufferError",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "outOfMemory"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "outOfMemory"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC21MTLCommandBufferErrorLeV",
              "text": "MTLCommandBufferError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MTLCommandBufferError",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct": {
      "abstract": [
        {
          "text": "The command buffer error codes that indicate why the GPU doesn’t finish executing a command buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCommandBufferError"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCommandBufferError"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes that indicate why a GPU is unable to finish running a command buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MTLCommandBufferError.Code",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/code"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/accessRevoked": {
      "abstract": [
        {
          "text": "An error code that indicates the system has revoked the Metal device’s access because it’s responsible for too many timeouts or hangs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessRevoked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21MTLCommandBufferErrorLeV",
          "text": "MTLCommandBufferError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLCommandBufferError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/accessRevoked",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessRevoked",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/accessrevoked"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/deviceRemoved": {
      "abstract": [
        {
          "text": "An error code that indicates a person physically removed the GPU device before the command buffer finished running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceRemoved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21MTLCommandBufferErrorLeV",
          "text": "MTLCommandBufferError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLCommandBufferError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/deviceRemoved",
      "kind": "symbol",
      "role": "symbol",
      "title": "deviceRemoved",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/deviceremoved"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/internal": {
      "abstract": [
        {
          "text": "An error code that indicates the Metal framework has an internal problem.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`internal`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21MTLCommandBufferErrorLeV",
          "text": "MTLCommandBufferError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLCommandBufferError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/internal",
      "kind": "symbol",
      "role": "symbol",
      "title": "internal",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/internal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/invalidResource": {
      "abstract": [
        {
          "text": "An error code that indicates the command buffer has an invalid reference to resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidResource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21MTLCommandBufferErrorLeV",
          "text": "MTLCommandBufferError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLCommandBufferError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/invalidResource",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalidResource",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/invalidresource"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/memoryless": {
      "abstract": [
        {
          "text": "An error code that indicates the GPU ran out of one or more of its internal resources that support memoryless render pass attachments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "memoryless"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21MTLCommandBufferErrorLeV",
          "text": "MTLCommandBufferError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLCommandBufferError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/memoryless",
      "kind": "symbol",
      "role": "symbol",
      "title": "memoryless",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/memoryless"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/none": {
      "abstract": [
        {
          "text": "An error code that represents the absence of any problems.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21MTLCommandBufferErrorLeV",
          "text": "MTLCommandBufferError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLCommandBufferError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/none",
      "kind": "symbol",
      "role": "symbol",
      "title": "none",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/none"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/notPermitted": {
      "abstract": [
        {
          "text": "An error code that indicates a process doesn’t have access to a GPU device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notPermitted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21MTLCommandBufferErrorLeV",
          "text": "MTLCommandBufferError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLCommandBufferError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/notPermitted",
      "kind": "symbol",
      "role": "symbol",
      "title": "notPermitted",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/notpermitted"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/outOfMemory": {
      "abstract": [
        {
          "text": "An error code that indicates the GPU device doesn’t have sufficient memory to execute a command buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outOfMemory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21MTLCommandBufferErrorLeV",
          "text": "MTLCommandBufferError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLCommandBufferError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/outOfMemory",
      "kind": "symbol",
      "role": "symbol",
      "title": "outOfMemory",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/outofmemory"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/pageFault": {
      "abstract": [
        {
          "text": "An error code that indicates the command buffer generated a page fault the GPU can’t service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageFault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21MTLCommandBufferErrorLeV",
          "text": "MTLCommandBufferError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLCommandBufferError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/pageFault",
      "kind": "symbol",
      "role": "symbol",
      "title": "pageFault",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/pagefault"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/stackOverflow": {
      "abstract": [
        {
          "text": "An error code that indicates the GPU terminated the command buffer because a kernel function of tile shader used too many stack frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stackOverflow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21MTLCommandBufferErrorLeV",
          "text": "MTLCommandBufferError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLCommandBufferError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/stackOverflow",
      "kind": "symbol",
      "role": "symbol",
      "title": "stackOverflow",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/stackoverflow"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/timeout": {
      "abstract": [
        {
          "text": "An error code that indicates the system interrupted and terminated the command buffer because it took more time to execute than the system allows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC21MTLCommandBufferErrorLeV",
          "text": "MTLCommandBufferError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLCommandBufferError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/timeout",
      "kind": "symbol",
      "role": "symbol",
      "title": "timeout",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandbuffererror-swift.struct/timeout"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/none",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/timeout",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/pageFault",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/notPermitted",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/invalidResource",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/memoryless",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/deviceRemoved",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/stackOverflow",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/accessRevoked",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/internal",
        "doc://com.apple.metal/documentation/Metal/MTLCommandBufferError-swift.struct/Code"
      ],
      "title": "Errors Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code/title",
          "value": "MTLCommandBufferError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandBufferError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCommandBufferError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlcommandbuffererror-swift.struct/outofmemory"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
