{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"relevantDate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DateV"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","seeAlsoSections":[{"anchor":"Reading-Metadata","title":"Reading Metadata","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/issuedDate","doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/expirationDate","doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/recordTypes","doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/sourceType","doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordSourceType","doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/itemNames"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"relevantDate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"platforms":[{"introducedAt":"15.0","beta":false,"name":"iOS","unavailable":false,"deprecated":false},{"introducedAt":"15.0","beta":false,"name":"iPadOS","unavailable":false,"deprecated":false},{"introducedAt":"15.0","beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false},{"introducedAt":"13.0","beta":false,"name":"macOS","unavailable":false,"deprecated":false},{"introducedAt":"1.0","beta":false,"name":"visionOS","unavailable":false,"deprecated":false}],"externalID":"c:objc(cs)HKVerifiableClinicalRecord(py)relevantDate","navigatorTitle":[{"text":"relevantDate","kind":"identifier"}],"symbolKind":"property","role":"symbol","modules":[{"name":"HealthKit"}],"title":"relevantDate"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/healthkit/hkverifiableclinicalrecord/relevantdate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/healthkit/hkverifiableclinicalrecord/relevantdate"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord"]]},"identifier":{"url":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/relevantDate","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"A date relevant to this record, such as when the issuer administered a vaccine or performed a test.","type":"text"}],"references":{"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/issuedDate":{"role":"symbol","title":"issuedDate","url":"/documentation/healthkit/hkverifiableclinicalrecord/issueddate","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/issuedDate","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issuedDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}],"navigatorTitle":[{"text":"issuedDate","kind":"identifier"}],"abstract":[{"text":"The date when the issuer created the card.","type":"text"}],"type":"topic"},"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/relevantDate":{"role":"symbol","title":"relevantDate","url":"/documentation/healthkit/hkverifiableclinicalrecord/relevantdate","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/relevantDate","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"relevantDate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}],"navigatorTitle":[{"text":"relevantDate","kind":"identifier"}],"abstract":[{"text":"A date relevant to this record, such as when the issuer administered a vaccine or performed a test.","type":"text"}],"type":"topic"},"doc://com.externally.resolved.symbol/c:objc(cs)NSDate":{"role":"symbol","kind":"symbol","url":"/documentation/foundation/nsdate","type":"topic","title":"NSDate","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSDate","fragments":[{"kind":"text","text":"class "},{"text":"NSDate","kind":"identifier"}],"abstract":[{"type":"text","text":"A representation of a specific point in time, for use when you need reference semantics or other Foundation-specific behavior."}]},"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKVerifiableClinicalRecord","kind":"identifier"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord","abstract":[{"text":"A sample that represents the contents of a SMART Health Card or EU Digital COVID Certificate.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"HKVerifiableClinicalRecord","kind":"identifier"}],"type":"topic","title":"HKVerifiableClinicalRecord","url":"/documentation/healthkit/hkverifiableclinicalrecord"},"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/expirationDate":{"role":"symbol","title":"expirationDate","url":"/documentation/healthkit/hkverifiableclinicalrecord/expirationdate","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/expirationDate","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expirationDate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"expirationDate"}],"abstract":[{"text":"The date when the card expires.","type":"text"}],"type":"topic"},"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordSourceType":{"title":"HKVerifiableClinicalRecordSourceType","kind":"symbol","url":"/documentation/healthkit/hkverifiableclinicalrecordsourcetype","abstract":[{"text":"The source type for the verifiable clinical record.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordSourceType","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKVerifiableClinicalRecordSourceType","kind":"identifier"}],"navigatorTitle":[{"text":"HKVerifiableClinicalRecordSourceType","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit":{"type":"topic","title":"HealthKit","kind":"symbol","abstract":[{"text":"Access and share health and fitness data while maintaining the user’s privacy and control.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit","role":"collection","url":"/documentation/healthkit"},"doc://com.externally.resolved.symbol/s:10Foundation4DateV":{"role":"symbol","kind":"symbol","url":"/documentation/foundation/date","type":"topic","title":"Date","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DateV","fragments":[{"kind":"text","text":"struct "},{"text":"Date","kind":"identifier"}],"abstract":[{"type":"text","text":"A specific point in time, independent of any calendar or time zone."}]},"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/sourceType":{"title":"sourceType","kind":"symbol","url":"/documentation/healthkit/hkverifiableclinicalrecord/sourcetype","abstract":[{"text":"The source for the verifiable clinical record","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/sourceType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sourceType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HKVerifiableClinicalRecordSourceType","kind":"typeIdentifier","preciseIdentifier":"c:@T@HKVerifiableClinicalRecordSourceType"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"sourceType"}],"type":"topic","role":"symbol"},"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/itemNames":{"role":"symbol","title":"itemNames","url":"/documentation/healthkit/hkverifiableclinicalrecord/itemnames","identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/itemNames","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"itemNames","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"itemNames","kind":"identifier"}],"abstract":[{"text":"A human-readable description of the card’s contents.","type":"text"}],"type":"topic"},"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/recordTypes":{"title":"recordTypes","kind":"symbol","url":"/documentation/healthkit/hkverifiableclinicalrecord/recordtypes","abstract":[{"text":"An array of strings representing the types of records contained in the card.","type":"text"}],"identifier":"doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/recordTypes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recordTypes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"recordTypes"}],"type":"topic","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","role":"overview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"beta":false,"introducedAt":"15.0","name":"iOS","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"15.0","name":"iPadOS","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"15.0","name":"Mac Catalyst","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"13.0","name":"macOS","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"1.0","name":"visionOS","deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"relevantDate"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"relevantDate"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.healthkit/documentation/HealthKit","doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"anchor":"Reading-Metadata","identifiers":["doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/issuedDate","doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/expirationDate","doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/recordTypes","doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/sourceType","doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecordSourceType","doc://com.apple.healthkit/documentation/HealthKit/HKVerifiableClinicalRecord/itemNames"],"title":"Reading Metadata","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS","watchOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSDate"},{"text":" * ","kind":"text"},{"text":"relevantDate","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecord~1issuedDate/title","value":"issuedDate","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecord~1issuedDate/fragments","value":[{"kind":"identifier","text":"issuedDate"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecord~1relevantDate/title","value":"relevantDate","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecord~1relevantDate/fragments","value":[{"text":"relevantDate","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSDate/abstract","value":[{"text":"A representation of a specific point in time, independent of any calendar or time zone.","type":"text"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecord/title","value":"HKVerifiableClinicalRecord","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecord/fragments","value":[{"text":"HKVerifiableClinicalRecord","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecord/navigatorTitle","value":[{"text":"HKVerifiableClinicalRecord","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecord~1expirationDate/title","value":"expirationDate","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecord~1expirationDate/fragments","value":[{"text":"expirationDate","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordSourceType/title","value":"HKVerifiableClinicalRecordSourceType","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordSourceType/fragments","value":[{"kind":"identifier","text":"HKVerifiableClinicalRecordSourceType"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecordSourceType/navigatorTitle","value":[{"kind":"identifier","text":"HKVerifiableClinicalRecordSourceType"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecord~1sourceType/title","value":"sourceType","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecord~1sourceType/fragments","value":[{"text":"sourceType","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecord~1itemNames/title","value":"itemNames","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecord~1itemNames/fragments","value":[{"text":"itemNames","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecord~1recordTypes/title","value":"recordTypes","op":"replace"},{"path":"/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKVerifiableClinicalRecord~1recordTypes/fragments","value":[{"text":"recordTypes","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}