{
  "abstract": [
    {
      "text": "An option for specifying images that should be flipped only to put their origin in the bottom-left corner.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metalkit/documentation/MetalKit",
        "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader",
        "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader/Origin"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader/Origin/bottomLeft"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "MetalKit",
    "externalID": "c:@MTKTextureLoaderOriginBottomLeft",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "bottomLeft"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MTKTextureLoader",
        "text": "MTKTextureLoader"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@MTKTextureLoaderOrigin",
        "text": "Origin"
      }
    ],
    "modules": [
      {
        "name": "MetalKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTKTextureLoaderOriginBottomLeft"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "bottomLeft"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bottomLeft"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MTKTextureLoader",
              "text": "MTKTextureLoader"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader/Origin",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@MTKTextureLoaderOrigin",
              "text": "Origin"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The texture will be flipped vertically if metadata in the file being loaded indicates that the source data starts with the top-left corner of the texture.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metalkit/documentation/MetalKit": {
      "abstract": [
        {
          "text": "Build Metal apps quicker and easier using a common set of utility classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetalKit",
      "type": "topic",
      "url": "/documentation/metalkit"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader": {
      "abstract": [
        {
          "text": "An object that creates textures from existing data in common image formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKTextureLoader"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKTextureLoader"
        }
      ],
      "role": "symbol",
      "title": "MTKTextureLoader",
      "type": "topic",
      "url": "/documentation/metalkit/mtktextureloader"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader/Origin": {
      "abstract": [
        {
          "text": "Options for specifying when to flip the pixel coordinates of the texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Origin"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader/Origin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Origin"
        }
      ],
      "role": "symbol",
      "title": "MTKTextureLoader.Origin",
      "type": "topic",
      "url": "/documentation/metalkit/mtktextureloader/origin"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader/Origin/bottomLeft": {
      "abstract": [
        {
          "text": "An option for specifying images that should be flipped only to put their origin in the bottom-left corner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTKTextureLoader",
          "text": "MTKTextureLoader"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTKTextureLoaderOrigin",
          "text": "Origin"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader/Origin/bottomLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKTextureLoaderOriginBottomLeft"
        }
      ],
      "role": "symbol",
      "title": "bottomLeft",
      "type": "topic",
      "url": "/documentation/metalkit/mtktextureloader/origin/bottomleft"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader/Origin/flippedVertically": {
      "abstract": [
        {
          "text": "An option that specifies that images should always be flipped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flippedVertically"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTKTextureLoader",
          "text": "MTKTextureLoader"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTKTextureLoaderOrigin",
          "text": "Origin"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader/Origin/flippedVertically",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKTextureLoaderOriginFlippedVertically"
        }
      ],
      "role": "symbol",
      "title": "flippedVertically",
      "type": "topic",
      "url": "/documentation/metalkit/mtktextureloader/origin/flippedvertically"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader/Origin/topLeft": {
      "abstract": [
        {
          "text": "An option for specifying images that should be flipped only to put their origin in the top-left corner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTKTextureLoader",
          "text": "MTKTextureLoader"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@MTKTextureLoaderOrigin",
          "text": "Origin"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader/Origin/topLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKTextureLoaderOriginTopLeft"
        }
      ],
      "role": "symbol",
      "title": "topLeft",
      "type": "topic",
      "url": "/documentation/metalkit/mtktextureloader/origin/topleft"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Texture-Origin-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader/Origin/topLeft",
        "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader/Origin/flippedVertically"
      ],
      "title": "Specifying Texture Origin Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTKTextureLoaderOriginBottomLeft"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKTextureLoaderOriginBottomLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metalkit/documentation/MetalKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-Texture-Origin-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader/Origin/topLeft",
                "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader/Origin/flippedVertically"
              ],
              "title": "Specifying Texture Origin Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKTextureLoader/Origin",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@MTKTextureLoaderOrigin",
                    "text": "MTKTextureLoaderOrigin"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTKTextureLoaderOriginBottomLeft"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKTextureLoader~1Origin~1topLeft/title",
          "value": "MTKTextureLoaderOriginTopLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKTextureLoader~1Origin~1topLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKTextureLoaderOriginTopLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKTextureLoader~1Origin~1bottomLeft/title",
          "value": "MTKTextureLoaderOriginBottomLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKTextureLoader~1Origin~1bottomLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKTextureLoaderOriginBottomLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKTextureLoader/title",
          "value": "MTKTextureLoader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKTextureLoader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKTextureLoader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKTextureLoader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKTextureLoader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKTextureLoader~1Origin/title",
          "value": "MTKTextureLoaderOrigin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKTextureLoader~1Origin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKTextureLoaderOrigin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKTextureLoader~1Origin/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKTextureLoaderOrigin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKTextureLoader~1Origin~1flippedVertically/title",
          "value": "MTKTextureLoaderOriginFlippedVertically"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKTextureLoader~1Origin~1flippedVertically/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKTextureLoaderOriginFlippedVertically"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metalkit/mtktextureloader/origin/bottomleft"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metalkit/mtktextureloader/origin/bottomleft"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
