{
  "abstract": [
    {
      "text": "The data store delegate instance.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.classkit/documentation/ClassKit",
        "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore/delegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CLSDataStore(py)delegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "delegate"
      },
      {
        "kind": "text",
        "text": ": (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)CLSDataStoreDelegate",
        "text": "CLSDataStoreDelegate"
      },
      {
        "kind": "text",
        "text": ")?"
      }
    ],
    "modules": [
      {
        "name": "ClassKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "delegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "delegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "weak"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "delegate"
            },
            {
              "kind": "text",
              "text": ": (any "
            },
            {
              "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSDataStoreDelegate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)CLSDataStoreDelegate",
              "text": "CLSDataStoreDelegate"
            },
            {
              "kind": "text",
              "text": ")? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The data store delegate creates contexts when the data store receives a request for a context it doesn’t already have. The data store calls on its delegate to build the missing context.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For privacy reasons, and depending on factors like the user’s role as student, teacher, or unmanaged user, the data store may or may not keep a persistent copy of a context returned by the delegate. As a result, it’s impossible to predict from within your app which context requests might result in a delegate callback. So you should be prepared for any context request that you make of the data store to result in a delegate callback.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.classkit/documentation/ClassKit": {
      "abstract": [
        {
          "text": "Enable teachers to assign activities from your app’s content and to view student progress.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClassKit",
      "type": "topic",
      "url": "/documentation/classkit"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore": {
      "abstract": [
        {
          "text": "A container for all the ClassKit data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSDataStore"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSDataStore"
        }
      ],
      "role": "symbol",
      "title": "CLSDataStore",
      "type": "topic",
      "url": "/documentation/classkit/clsdatastore"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore/delegate": {
      "abstract": [
        {
          "text": "The data store delegate instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CLSDataStoreDelegate",
          "text": "CLSDataStoreDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/classkit/clsdatastore/delegate"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSDataStoreDelegate": {
      "abstract": [
        {
          "text": "An interface the data store uses to request new contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSDataStoreDelegate"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSDataStoreDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSDataStoreDelegate"
        }
      ],
      "role": "symbol",
      "title": "CLSDataStoreDelegate",
      "type": "topic",
      "url": "/documentation/classkit/clsdatastoredelegate"
    },
    "doc://com.apple.classkit/documentation/ClassKit/building-missing-contexts": {
      "abstract": [
        {
          "text": "Create and initialize missing contexts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/building-missing-contexts",
      "kind": "article",
      "role": "article",
      "title": "Building missing contexts",
      "type": "topic",
      "url": "/documentation/classkit/building-missing-contexts"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-delegate",
      "generated": true,
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/building-missing-contexts",
        "doc://com.apple.classkit/documentation/ClassKit/CLSDataStoreDelegate"
      ],
      "title": "Managing the delegate"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.classkit/documentation/ClassKit",
                "doc://com.apple.classkit/documentation/ClassKit/CLSDataStore"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-the-delegate",
              "generated": true,
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/building-missing-contexts",
                "doc://com.apple.classkit/documentation/ClassKit/CLSDataStoreDelegate"
              ],
              "title": "Managing the delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "weak"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)CLSDataStoreDelegate",
                    "text": "id<CLSDataStoreDelegate>"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "delegate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore/title",
          "value": "CLSDataStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSDataStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSDataStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStoreDelegate/title",
          "value": "CLSDataStoreDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStoreDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSDataStoreDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStoreDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSDataStoreDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSDataStore~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/classkit/clsdatastore/delegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/classkit/clsdatastore/delegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
