{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription/indexDescription"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSFetchIndexElementDescription(py)indexDescription",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "indexDescription"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSFetchIndexDescription",
        "text": "NSFetchIndexDescription"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "indexDescription"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "indexDescription"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "unowned(unsafe)"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "indexDescription"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexDescription",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSFetchIndexDescription",
              "text": "NSFetchIndexDescription"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexDescription": {
      "abstract": [
        {
          "text": "The description of the index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFetchIndexDescription"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFetchIndexDescription"
        }
      ],
      "role": "symbol",
      "title": "NSFetchIndexDescription",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchindexdescription"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription": {
      "abstract": [
        {
          "text": "Description of an Index Element",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFetchIndexElementDescription"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFetchIndexElementDescription"
        }
      ],
      "role": "symbol",
      "title": "NSFetchIndexElementDescription",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchindexelementdescription"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription/collationType": {
      "abstract": [
        {
          "text": "The type of collation that the index element uses, either binary or R-tree.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSFetchIndexElementType",
          "text": "NSFetchIndexElementType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription/collationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collationType"
        }
      ],
      "role": "symbol",
      "title": "collationType",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchindexelementdescription/collationtype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription/indexDescription": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFetchIndexDescription",
          "text": "NSFetchIndexDescription"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription/indexDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexDescription"
        }
      ],
      "role": "symbol",
      "title": "indexDescription",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchindexelementdescription/indexdescription"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription/isAscending": {
      "abstract": [
        {
          "text": "A Boolean value that controls whether an index that supports direction is an ascending or descending index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAscending"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription/isAscending",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ascending"
        }
      ],
      "role": "symbol",
      "title": "isAscending",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchindexelementdescription/isascending"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription/property": {
      "abstract": [
        {
          "text": "A property description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "property"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPropertyDescription",
          "text": "NSPropertyDescription"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription/property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "property"
        }
      ],
      "role": "symbol",
      "title": "property",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchindexelementdescription/property"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription/propertyName": {
      "abstract": [
        {
          "text": "The specified name in the property description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "propertyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription/propertyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "propertyName"
        }
      ],
      "role": "symbol",
      "title": "propertyName",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchindexelementdescription/propertyname"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-an-Index-Element-Description",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription/collationType",
        "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription/isAscending",
        "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription/property",
        "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription/propertyName"
      ],
      "title": "Inspecting an Index Element Description"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "indexDescription"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "indexDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData",
                "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-an-Index-Element-Description",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription/collationType",
                "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription/isAscending",
                "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription/property",
                "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexElementDescription/propertyName"
              ],
              "title": "Inspecting an Index Element Description"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchIndexDescription",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSFetchIndexDescription",
                    "text": "NSFetchIndexDescription"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "indexDescription"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchIndexElementDescription~1collationType/title",
          "value": "collationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchIndexElementDescription~1collationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "collationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchIndexElementDescription~1isAscending/title",
          "value": "ascending"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchIndexElementDescription~1isAscending/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ascending"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchIndexElementDescription/title",
          "value": "NSFetchIndexElementDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchIndexElementDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchIndexElementDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchIndexElementDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchIndexElementDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchIndexElementDescription~1propertyName/title",
          "value": "propertyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchIndexElementDescription~1propertyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "propertyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchIndexDescription/title",
          "value": "NSFetchIndexDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchIndexDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchIndexDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchIndexDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchIndexDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchIndexElementDescription~1indexDescription/title",
          "value": "indexDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchIndexElementDescription~1indexDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "indexDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchIndexElementDescription~1property/title",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchIndexElementDescription~1property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "property"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsfetchindexelementdescription/indexdescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nsfetchindexelementdescription/indexdescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
