{
  "abstract": [
    {
      "text": "An optimizer that uses the Adam optimization algorithm.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use the BNNSGraph API instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Accelerate",
    "externalID": "s:10Accelerate4BNNSO13AdamOptimizerV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AdamOptimizer"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AdamOptimizer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": true,
        "message": "Use the BNNSGraph API instead.",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "BNNS.AdamOptimizer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AdamOptimizer"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS": {
      "abstract": [
        {
          "text": "An enumeration that acts as a namespace for Swift overlays to BNNS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNS"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNS"
        }
      ],
      "role": "symbol",
      "title": "BNNS",
      "type": "topic",
      "url": "/documentation/accelerate/bnns"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer": {
      "abstract": [
        {
          "text": "An optimizer that uses the Adam optimization algorithm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AdamOptimizer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AdamOptimizer"
        }
      ],
      "role": "symbol",
      "title": "BNNS.AdamOptimizer",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/adamoptimizer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/accumulatorCountMultiplier": {
      "abstract": [
        {
          "text": "The number of accumulators required for each parameter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accumulatorCountMultiplier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/accumulatorCountMultiplier",
      "kind": "symbol",
      "role": "symbol",
      "title": "accumulatorCountMultiplier",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/adamoptimizer/accumulatorcountmultiplier"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/beta1": {
      "abstract": [
        {
          "text": "A value that specifies the first-moment constant, in the range ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " to ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beta1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/beta1",
      "kind": "symbol",
      "role": "symbol",
      "title": "beta1",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/adamoptimizer/beta1"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/beta2": {
      "abstract": [
        {
          "text": "A value that specifies the second-moment constant, in the range ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " to ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beta2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/beta2",
      "kind": "symbol",
      "role": "symbol",
      "title": "beta2",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/adamoptimizer/beta2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/epsilon": {
      "abstract": [
        {
          "text": "The epsilon value you use to improve numerical stability.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "epsilon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/epsilon",
      "kind": "symbol",
      "role": "symbol",
      "title": "epsilon",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/adamoptimizer/epsilon"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/gradientBounds": {
      "abstract": [
        {
          "text": "The values for the minimum and maximum gradients.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradientBounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SN",
          "text": "ClosedRange"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/gradientBounds",
      "kind": "symbol",
      "role": "symbol",
      "title": "gradientBounds",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/adamoptimizer/gradientbounds"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/gradientClipping": {
      "abstract": [
        {
          "text": "The gradient clipping.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradientClipping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO",
          "text": "BNNS"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO16GradientClippingO",
          "text": "GradientClipping"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/gradientClipping",
      "kind": "symbol",
      "role": "symbol",
      "title": "gradientClipping",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/adamoptimizer/gradientclipping"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/gradientScale": {
      "abstract": [
        {
          "text": "A value that specifies the gradient scaling factor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradientScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/gradientScale",
      "kind": "symbol",
      "role": "symbol",
      "title": "gradientScale",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/adamoptimizer/gradientscale"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/init(learningRate:beta1:beta2:timeStep:epsilon:gradientScale:regularizationScale:clipsGradientsTo:regularizationFunction:)": {
      "abstract": [
        {
          "text": "Returns a new Adam optimizer object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "learningRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "beta1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "beta2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timeStep"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "epsilon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "gradientScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "regularizationScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "clipsGradientsTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SN",
          "text": "ClosedRange"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "externalParam",
          "text": "regularizationFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerRegularizationFunction",
          "text": "BNNSOptimizerRegularizationFunction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/init(learningRate:beta1:beta2:timeStep:epsilon:gradientScale:regularizationScale:clipsGradientsTo:regularizationFunction:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(learningRate:beta1:beta2:timeStep:epsilon:gradientScale:regularizationScale:clipsGradientsTo:regularizationFunction:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/adamoptimizer/init(learningrate:beta1:beta2:timestep:epsilon:gradientscale:regularizationscale:clipsgradientsto:regularizationfunction:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/init(learningRate:beta1:beta2:timeStep:epsilon:gradientScale:regularizationScale:gradientClipping:regularizationFunction:usesAMSGrad:)": {
      "abstract": [
        {
          "text": "Returns a new Adam optimizer object with gradient clipped by value or clipped by norm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "learningRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "beta1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "beta2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timeStep"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "epsilon"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "gradientScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "regularizationScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "gradientClipping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO",
          "text": "BNNS"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO16GradientClippingO",
          "text": "GradientClipping"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "regularizationFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerRegularizationFunction",
          "text": "BNNSOptimizerRegularizationFunction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "usesAMSGrad"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/init(learningRate:beta1:beta2:timeStep:epsilon:gradientScale:regularizationScale:gradientClipping:regularizationFunction:usesAMSGrad:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(learningRate:beta1:beta2:timeStep:epsilon:gradientScale:regularizationScale:gradientClipping:regularizationFunction:usesAMSGrad:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/adamoptimizer/init(learningrate:beta1:beta2:timestep:epsilon:gradientscale:regularizationscale:gradientclipping:regularizationfunction:usesamsgrad:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/learningRate": {
      "abstract": [
        {
          "text": "A value that specifies the learning rate.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "learningRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/learningRate",
      "kind": "symbol",
      "role": "symbol",
      "title": "learningRate",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/adamoptimizer/learningrate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/regularizationFunction": {
      "abstract": [
        {
          "text": "The variable that specifies the regularization function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regularizationFunction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerRegularizationFunction",
          "text": "BNNSOptimizerRegularizationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/regularizationFunction",
      "kind": "symbol",
      "role": "symbol",
      "title": "regularizationFunction",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/adamoptimizer/regularizationfunction"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/regularizationScale": {
      "abstract": [
        {
          "text": "A value that specifies the regularization scaling factor.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regularizationScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/regularizationScale",
      "kind": "symbol",
      "role": "symbol",
      "title": "regularizationScale",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/adamoptimizer/regularizationscale"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/timeStep": {
      "abstract": [
        {
          "text": "A value that’s at least ",
          "type": "text"
        },
        {
          "code": "1",
          "type": "codeVoice"
        },
        {
          "text": " and represents the optimizer’s current time.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeStep"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/timeStep",
      "kind": "symbol",
      "role": "symbol",
      "title": "timeStep",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/adamoptimizer/timestep"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/usesAMSGrad": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether to use the AMSGrad variant.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usesAMSGrad"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/usesAMSGrad",
      "kind": "symbol",
      "role": "symbol",
      "title": "usesAMSGrad",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/adamoptimizer/usesamsgrad"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamWOptimizer": {
      "abstract": [
        {
          "text": "An optimizer that uses the AdamW optimization algorithm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AdamWOptimizer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamWOptimizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AdamWOptimizer"
        }
      ],
      "role": "symbol",
      "title": "BNNS.AdamWOptimizer",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/adamwoptimizer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/GradientClipping": {
      "abstract": [
        {
          "text": "Constants that describe clipping functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GradientClipping"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/GradientClipping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GradientClipping"
        }
      ],
      "role": "symbol",
      "title": "BNNS.GradientClipping",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/gradientclipping"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RMSPropOptimizer": {
      "abstract": [
        {
          "text": "An optimizer that uses the root mean square propagation (RMSProp) optimization method.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RMSPropOptimizer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RMSPropOptimizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RMSPropOptimizer"
        }
      ],
      "role": "symbol",
      "title": "BNNS.RMSPropOptimizer",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/rmspropoptimizer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/SGDMomentumOptimizer": {
      "abstract": [
        {
          "text": "An optimizer that uses the stochastic gradient descent (SGD) with the momentum optimization method.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SGDMomentumOptimizer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/SGDMomentumOptimizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SGDMomentumOptimizer"
        }
      ],
      "role": "symbol",
      "title": "BNNS.SGDMomentumOptimizer",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/sgdmomentumoptimizer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizer": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizer"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizer",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamFields": {
      "abstract": [
        {
          "text": "A structure that contains the fields of an Adam optimizer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerAdamFields"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamFields",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerAdamFields"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerAdamFields",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamfields"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields": {
      "abstract": [
        {
          "text": "A structure that contains the fields of an Adam or AdamW optimizer that optionally clips the gradient by value or by norm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerAdamWithClippingFields"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerAdamWithClippingFields"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerAdamWithClippingFields",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizeradamwithclippingfields"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunction": {
      "abstract": [
        {
          "text": "A structure that contains optimizer functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerFunction"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerFunction",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerfunction"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerRMSPropFields": {
      "abstract": [
        {
          "text": "A structure that contains the fields of a root mean square propagation (RMSProp) optimizer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerRMSPropFields"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerRMSPropFields",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerRMSPropFields"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerRMSPropFields",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerrmspropfields"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerRMSPropWithClippingFields": {
      "abstract": [
        {
          "text": "A structure that contains the fields of a root mean square propagation (RMSProp) optimizer that optionally clips the gradient by value or by norm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerRMSPropWithClippingFields"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerRMSPropWithClippingFields",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerRMSPropWithClippingFields"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerRMSPropWithClippingFields",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerrmspropwithclippingfields"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerRegularizationFunction": {
      "abstract": [
        {
          "text": "A structure that contains optimizer regularization functions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerRegularizationFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerRegularizationFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerRegularizationFunction"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerRegularizationFunction",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerregularizationfunction"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerSGDMomentumFields": {
      "abstract": [
        {
          "text": "A structure that contains the fields of a stochastic gradient descent (SGD) with momentum optimizer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerSGDMomentumFields"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerSGDMomentumFields",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerSGDMomentumFields"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerSGDMomentumFields",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizersgdmomentumfields"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerSGDMomentumVariant": {
      "abstract": [
        {
          "text": "Constants that define SGD momentum variants.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerSGDMomentumVariant"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerSGDMomentumVariant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerSGDMomentumVariant"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerSGDMomentumVariant",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizersgdmomentumvariant"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerSGDMomentumWithClippingFields": {
      "abstract": [
        {
          "text": "A structure that contains the fields of a stochastic gradient descent (SGD) with momentum optimizer that optionally clips the gradient by value or by norm.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerSGDMomentumWithClippingFields"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerSGDMomentumWithClippingFields",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerSGDMomentumWithClippingFields"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerSGDMomentumWithClippingFields",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizersgdmomentumwithclippingfields"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerStep(_:_:_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Applies a single optimization step to one or more parameters.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSOptimizerStep"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSOptimizerFunction",
          "text": "BNNSOptimizerFunction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">>, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">?>?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSFilterParameters",
          "text": "BNNSFilterParameters"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerStep(_:_:_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSOptimizerStep"
        }
      ],
      "role": "symbol",
      "title": "BNNSOptimizerStep(_:_:_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsoptimizerstep(_:_:_:_:_:_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizer"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Optimizers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamWOptimizer",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RMSPropOptimizer",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/SGDMomentumOptimizer",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizer",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerRegularizationFunction",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamFields",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerAdamWithClippingFields",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerRMSPropFields",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerRMSPropWithClippingFields",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerSGDMomentumFields",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerSGDMomentumWithClippingFields",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerSGDMomentumVariant",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerStep(_:_:_:_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSOptimizerFunction"
      ],
      "title": "Optimizers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-Adam-Optimizer",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/init(learningRate:beta1:beta2:timeStep:epsilon:gradientScale:regularizationScale:clipsGradientsTo:regularizationFunction:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/init(learningRate:beta1:beta2:timeStep:epsilon:gradientScale:regularizationScale:gradientClipping:regularizationFunction:usesAMSGrad:)"
      ],
      "title": "Creating an Adam Optimizer"
    },
    {
      "anchor": "Inspecting-the-Properties-of-an-Adam-Optimizer",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/learningRate",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/beta1",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/beta2",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/timeStep",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/epsilon",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/gradientScale",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/regularizationScale",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/gradientBounds",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/gradientClipping",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/regularizationFunction",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/usesAMSGrad",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/AdamOptimizer/accumulatorCountMultiplier",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/GradientClipping"
      ],
      "title": "Inspecting the Properties of an Adam Optimizer"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields/title",
          "value": "BNNSOptimizerAdamWithClippingFields"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerAdamWithClippingFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamWithClippingFields/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerAdamWithClippingFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunction/title",
          "value": "BNNSOptimizerFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerSGDMomentumFields/title",
          "value": "BNNSOptimizerSGDMomentumFields"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerSGDMomentumFields/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerSGDMomentumFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerSGDMomentumFields/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerSGDMomentumFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerRegularizationFunction/title",
          "value": "BNNSOptimizerRegularizationFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerRegularizationFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerRegularizationFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerRegularizationFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerRegularizationFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamFields/title",
          "value": "BNNSOptimizerAdamFields"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamFields/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerAdamFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerAdamFields/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerAdamFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerRMSPropFields/title",
          "value": "BNNSOptimizerRMSPropFields"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerRMSPropFields/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerRMSPropFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerRMSPropFields/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerRMSPropFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerSGDMomentumWithClippingFields/title",
          "value": "BNNSOptimizerSGDMomentumWithClippingFields"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerSGDMomentumWithClippingFields/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerSGDMomentumWithClippingFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerSGDMomentumWithClippingFields/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerSGDMomentumWithClippingFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerStep(_:_:_:_:_:_:_:)/title",
          "value": "BNNSOptimizerStep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerStep(_:_:_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerStep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerRMSPropWithClippingFields/title",
          "value": "BNNSOptimizerRMSPropWithClippingFields"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerRMSPropWithClippingFields/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerRMSPropWithClippingFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerRMSPropWithClippingFields/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerRMSPropWithClippingFields"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerSGDMomentumVariant/title",
          "value": "BNNSOptimizerSGDMomentumVariant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerSGDMomentumVariant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerSGDMomentumVariant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSOptimizerSGDMomentumVariant/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSOptimizerSGDMomentumVariant"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnns/adamoptimizer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
