{
  "abstract": [
    {
      "text": "A layer object that wraps a fully connected filter and manages its deinitialization.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use the BNNSGraph API instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/FullyConnectedLayer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Accelerate",
    "externalID": "s:10Accelerate4BNNSO19FullyConnectedLayerC",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FullyConnectedLayer"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FullyConnectedLayer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": true,
        "message": "Use the BNNSGraph API instead.",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "BNNS.FullyConnectedLayer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FullyConnectedLayer"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS": {
      "abstract": [
        {
          "text": "An enumeration that acts as a namespace for Swift overlays to BNNS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNS"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNS"
        }
      ],
      "role": "symbol",
      "title": "BNNS",
      "type": "topic",
      "url": "/documentation/accelerate/bnns"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/ConvolutionLayer": {
      "abstract": [
        {
          "text": "A layer object that wraps a convolution filter and manages its deinitialization.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ConvolutionLayer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/ConvolutionLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ConvolutionLayer"
        }
      ],
      "role": "symbol",
      "title": "BNNS.ConvolutionLayer",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/convolutionlayer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/FullyConnectedLayer": {
      "abstract": [
        {
          "text": "A layer object that wraps a fully connected filter and manages its deinitialization.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FullyConnectedLayer"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/FullyConnectedLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FullyConnectedLayer"
        }
      ],
      "role": "symbol",
      "title": "BNNS.FullyConnectedLayer",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/fullyconnectedlayer"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/FullyConnectedLayer/init(input:output:weights:bias:activation:filterParameters:)": {
      "abstract": [
        {
          "text": "Returns a new fully connected layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "input"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "output"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "weights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "bias"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "activation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO",
          "text": "BNNS"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO18ActivationFunctionO",
          "text": "ActivationFunction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "filterParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSFilterParameters",
          "text": "BNNSFilterParameters"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/FullyConnectedLayer/init(input:output:weights:bias:activation:filterParameters:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(input:output:weights:bias:activation:filterParameters:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/fullyconnectedlayer/init(input:output:weights:bias:activation:filterparameters:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/FullyConnectedLayer/sparsify(batchSize:inputLayout:inputDenseShape:inputValues:output:sparseParameters:workspace:filterParameters:)": {
      "abstract": [
        {
          "text": "Converts a sparse tensor from a standardized sparse layout to a device-specific sparse layout that Fully Connected uses.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sparsify"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "batchSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inputLayout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO",
          "text": "BNNS"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO12SparseLayoutO",
          "text": "SparseLayout"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inputDenseShape"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inputValues"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "output"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sparseParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO",
          "text": "BNNS"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO16SparseParametersV",
          "text": "SparseParameters"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "workspace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sw",
          "text": "UnsafeMutableRawBufferPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "filterParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSFilterParameters",
          "text": "BNNSFilterParameters"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/FullyConnectedLayer/sparsify(batchSize:inputLayout:inputDenseShape:inputValues:output:sparseParameters:workspace:filterParameters:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "sparsify(batchSize:inputLayout:inputDenseShape:inputValues:output:sparseParameters:workspace:filterParameters:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/fullyconnectedlayer/sparsify(batchsize:inputlayout:inputdenseshape:inputvalues:output:sparseparameters:workspace:filterparameters:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterCreateFullyConnectedLayer(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a fully connected filter, initialized with input, output, layer, and filter parameters.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSFilterCreateFullyConnectedLayer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSVectorDescriptor",
          "text": "BNNSVectorDescriptor"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSVectorDescriptor",
          "text": "BNNSVectorDescriptor"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSFullyConnectedLayerParameters",
          "text": "BNNSFullyConnectedLayerParameters"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSFilterParameters",
          "text": "BNNSFilterParameters"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSFilter",
          "text": "BNNSFilter"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterCreateFullyConnectedLayer(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSFilterCreateFullyConnectedLayer"
        }
      ],
      "role": "symbol",
      "title": "BNNSFilterCreateFullyConnectedLayer(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfiltercreatefullyconnectedlayer(_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterCreateLayerFullyConnected(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new fully connected layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSFilterCreateLayerFullyConnected"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSLayerParametersFullyConnected",
          "text": "BNNSLayerParametersFullyConnected"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSFilterParameters",
          "text": "BNNSFilterParameters"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSFilter",
          "text": "BNNSFilter"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterCreateLayerFullyConnected(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSFilterCreateLayerFullyConnected"
        }
      ],
      "role": "symbol",
      "title": "BNNSFilterCreateLayerFullyConnected(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfiltercreatelayerfullyconnected(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSFullyConnectedLayerParameters": {
      "abstract": [
        {
          "text": "A structure containing fully connected layer parameters.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSFullyConnectedLayerParameters"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSFullyConnectedLayerParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSFullyConnectedLayerParameters"
        }
      ],
      "role": "symbol",
      "title": "BNNSFullyConnectedLayerParameters",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsfullyconnectedlayerparameters"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSLayerParametersFullyConnected": {
      "abstract": [
        {
          "text": "A structure that contains the parameters of a fully connected layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSLayerParametersFullyConnected"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSLayerParametersFullyConnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSLayerParametersFullyConnected"
        }
      ],
      "role": "symbol",
      "title": "BNNSLayerParametersFullyConnected",
      "type": "topic",
      "url": "/documentation/accelerate/bnnslayerparametersfullyconnected"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/ConvolutionLayer"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Fully-connected-layers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFullyConnectedLayerParameters",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterCreateFullyConnectedLayer(_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSLayerParametersFullyConnected",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSFilterCreateLayerFullyConnected(_:_:)"
      ],
      "title": "Fully connected layers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Fully-Connected-Layer",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/FullyConnectedLayer/init(input:output:weights:bias:activation:filterParameters:)"
      ],
      "title": "Creating a Fully Connected Layer"
    },
    {
      "anchor": "Type-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/FullyConnectedLayer/sparsify(batchSize:inputLayout:inputDenseShape:inputValues:output:sparseParameters:workspace:filterParameters:)"
      ],
      "title": "Type Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterCreateLayerFullyConnected(_:_:)/title",
          "value": "BNNSFilterCreateLayerFullyConnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterCreateLayerFullyConnected(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilterCreateLayerFullyConnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterCreateFullyConnectedLayer(_:_:_:_:)/title",
          "value": "BNNSFilterCreateFullyConnectedLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFilterCreateFullyConnectedLayer(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFilterCreateFullyConnectedLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSLayerParametersFullyConnected/title",
          "value": "BNNSLayerParametersFullyConnected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSLayerParametersFullyConnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSLayerParametersFullyConnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSLayerParametersFullyConnected/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSLayerParametersFullyConnected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFullyConnectedLayerParameters/title",
          "value": "BNNSFullyConnectedLayerParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFullyConnectedLayerParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFullyConnectedLayerParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSFullyConnectedLayerParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSFullyConnectedLayerParameters"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnns/fullyconnectedlayer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
