{
  "abstract": [
    {
      "text": "A random number generator.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RandomGenerator"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Accelerate",
    "externalID": "s:10Accelerate4BNNSO15RandomGeneratorC",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "RandomGenerator"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "RandomGenerator"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "BNNS.RandomGenerator"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "RandomGenerator"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS": {
      "abstract": [
        {
          "text": "An enumeration that acts as a namespace for Swift overlays to BNNS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNS"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNS"
        }
      ],
      "role": "symbol",
      "title": "BNNS",
      "type": "topic",
      "url": "/documentation/accelerate/bnns"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RandomGenerator": {
      "abstract": [
        {
          "text": "A random number generator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RandomGenerator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RandomGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RandomGenerator"
        }
      ],
      "role": "symbol",
      "title": "BNNS.RandomGenerator",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/randomgenerator"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RandomGenerator/init(method:seed:filterParameters:)": {
      "abstract": [
        {
          "text": "Returns a new random number generator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "method"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO",
          "text": "BNNS"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO21RandomGeneratorMethodO",
          "text": "RandomGeneratorMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "seed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "filterParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSFilterParameters",
          "text": "BNNSFilterParameters"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RandomGenerator/init(method:seed:filterParameters:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(method:seed:filterParameters:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/randomgenerator/init(method:seed:filterparameters:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RandomGenerator/state": {
      "abstract": [
        {
          "text": "The state of the random number generator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO",
          "text": "BNNS"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO20RandomGeneratorStateC",
          "text": "RandomGeneratorState"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RandomGenerator/state",
      "kind": "symbol",
      "role": "symbol",
      "title": "state",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/randomgenerator/state"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RandomGeneratorMethod": {
      "abstract": [
        {
          "text": "Constants that describe random number generation methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RandomGeneratorMethod"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RandomGeneratorMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RandomGeneratorMethod"
        }
      ],
      "role": "symbol",
      "title": "BNNS.RandomGeneratorMethod",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/randomgeneratormethod"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RandomGeneratorState": {
      "abstract": [
        {
          "text": "An opaque object that contains the state of a random number generator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RandomGeneratorState"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RandomGeneratorState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RandomGeneratorState"
        }
      ],
      "role": "symbol",
      "title": "BNNS.RandomGeneratorState",
      "type": "topic",
      "url": "/documentation/accelerate/bnns/randomgeneratorstate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSCreateRandomGenerator(_:_:)": {
      "abstract": [
        {
          "text": "Returns a new random number generator using an internally generated random seed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSCreateRandomGenerator"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRandomGeneratorMethod",
          "text": "BNNSRandomGeneratorMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSFilterParameters",
          "text": "BNNSFilterParameters"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSRandomGenerator",
          "text": "BNNSRandomGenerator"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSCreateRandomGenerator(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSCreateRandomGenerator"
        }
      ],
      "role": "symbol",
      "title": "BNNSCreateRandomGenerator(_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnscreaterandomgenerator(_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSCreateRandomGeneratorWithSeed(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new random number generator using the specified seed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSCreateRandomGeneratorWithSeed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSRandomGeneratorMethod",
          "text": "BNNSRandomGeneratorMethod"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSFilterParameters",
          "text": "BNNSFilterParameters"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSRandomGenerator",
          "text": "BNNSRandomGenerator"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSCreateRandomGeneratorWithSeed(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSCreateRandomGeneratorWithSeed"
        }
      ],
      "role": "symbol",
      "title": "BNNSCreateRandomGeneratorWithSeed(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnscreaterandomgeneratorwithseed(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSDestroyRandomGenerator(_:)": {
      "abstract": [
        {
          "text": "Destroys a random number generator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSDestroyRandomGenerator"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSRandomGenerator",
          "text": "BNNSRandomGenerator"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSDestroyRandomGenerator(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSDestroyRandomGenerator"
        }
      ],
      "role": "symbol",
      "title": "BNNSDestroyRandomGenerator(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsdestroyrandomgenerator(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSNDArrayDescriptor/allocate(randomIn:using:shape:batchSize:)-3w6ig": {
      "abstract": [
        {
          "text": "Returns a new array descriptor that’s initialized with random values within the specified range, using the given generator as a source for randomness.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allocate"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Generator"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "randomIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SN",
          "text": "ClosedRange"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Generator"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shape"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO",
          "text": "BNNS"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO5ShapeO",
          "text": "Shape"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "batchSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSNDArrayDescriptor/allocate(randomIn:using:shape:batchSize:)-3w6ig",
      "kind": "symbol",
      "role": "symbol",
      "title": "allocate(randomIn:using:shape:batchSize:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsndarraydescriptor/allocate(randomin:using:shape:batchsize:)-3w6ig"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSNDArrayDescriptor/allocate(randomIn:using:shape:batchSize:)-5kbi8": {
      "abstract": [
        {
          "text": "Returns a new array descriptor that’s initialized with random values within the specified range, using the given generator as a source for randomness.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allocate"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Generator"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "randomIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SN",
          "text": "ClosedRange"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Scalar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Generator"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shape"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO",
          "text": "BNNS"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Accelerate4BNNSO5ShapeO",
          "text": "Shape"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "batchSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSNDArrayDescriptor/allocate(randomIn:using:shape:batchSize:)-5kbi8",
      "kind": "symbol",
      "role": "symbol",
      "title": "allocate(randomIn:using:shape:batchSize:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsndarraydescriptor/allocate(randomin:using:shape:batchsize:)-5kbi8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillCategoricalFloat(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Fills the specified tensor with random values from the categorical distributions with the given event probabilities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRandomFillCategoricalFloat"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSRandomGenerator",
          "text": "BNNSRandomGenerator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillCategoricalFloat(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRandomFillCategoricalFloat"
        }
      ],
      "role": "symbol",
      "title": "BNNSRandomFillCategoricalFloat(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomfillcategoricalfloat(_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillNormalFloat(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Fills the specified tensor with random floating-point values mapped to a normal distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRandomFillNormalFloat"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSRandomGenerator",
          "text": "BNNSRandomGenerator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillNormalFloat(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRandomFillNormalFloat"
        }
      ],
      "role": "symbol",
      "title": "BNNSRandomFillNormalFloat(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomfillnormalfloat(_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillUniformFloat(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Fills the specified tensor with random floating-point values from the continuous uniform distribution within a range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRandomFillUniformFloat"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSRandomGenerator",
          "text": "BNNSRandomGenerator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillUniformFloat(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRandomFillUniformFloat"
        }
      ],
      "role": "symbol",
      "title": "BNNSRandomFillUniformFloat(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomfilluniformfloat(_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillUniformInt(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Fills the specified tensor with random integer values from the continuous uniform distribution within a range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRandomFillUniformInt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSRandomGenerator",
          "text": "BNNSRandomGenerator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSNDArrayDescriptor",
          "text": "BNNSNDArrayDescriptor"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillUniformInt(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRandomFillUniformInt"
        }
      ],
      "role": "symbol",
      "title": "BNNSRandomFillUniformInt(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomfilluniformint(_:_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGenerator": {
      "abstract": [
        {
          "text": "A pointer to a random number generator object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRandomGenerator"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRandomGenerator"
        }
      ],
      "role": "symbol",
      "title": "BNNSRandomGenerator",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomgenerator"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorGetState(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the state of a random number generator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRandomGeneratorGetState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSRandomGenerator",
          "text": "BNNSRandomGenerator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorGetState(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRandomGeneratorGetState"
        }
      ],
      "role": "symbol",
      "title": "BNNSRandomGeneratorGetState(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomgeneratorgetstate(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorMethod": {
      "abstract": [
        {
          "text": "Constants that describe random number generation methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRandomGeneratorMethod"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorMethod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRandomGeneratorMethod"
        }
      ],
      "role": "symbol",
      "title": "BNNSRandomGeneratorMethod",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomgeneratormethod"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorSetState(_:_:_:)": {
      "abstract": [
        {
          "text": "Sets the state of a random number generator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRandomGeneratorSetState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSRandomGenerator",
          "text": "BNNSRandomGenerator"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorSetState(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRandomGeneratorSetState"
        }
      ],
      "role": "symbol",
      "title": "BNNSRandomGeneratorSetState(_:_:_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomgeneratorsetstate(_:_:_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorStateSize(_:)": {
      "abstract": [
        {
          "text": "Returns the state size, in bytes, of a random number generator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSRandomGeneratorStateSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BNNSRandomGenerator",
          "text": "BNNSRandomGenerator"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorStateSize(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSRandomGeneratorStateSize"
        }
      ],
      "role": "symbol",
      "title": "BNNSRandomGeneratorStateSize(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/bnnsrandomgeneratorstatesize(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSNDArrayDescriptor/allocate(randomIn:using:shape:batchSize:)-3w6ig",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSNDArrayDescriptor/allocate(randomIn:using:shape:batchSize:)-5kbi8"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Random-number-generation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSCreateRandomGenerator(_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSCreateRandomGeneratorWithSeed(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorMethod",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGenerator",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillUniformInt(_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillUniformFloat(_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillNormalFloat(_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomFillCategoricalFloat(_:_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorStateSize(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorGetState(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSRandomGeneratorSetState(_:_:_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSDestroyRandomGenerator(_:)"
      ],
      "title": "Random number generation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Random-Number-Generator",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RandomGenerator/init(method:seed:filterParameters:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RandomGeneratorMethod"
      ],
      "title": "Creating a Random Number Generator"
    },
    {
      "anchor": "Saving-and-Restoring-a-Randon-Generators-State",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RandomGenerator/state",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNS/RandomGeneratorState"
      ],
      "title": "Saving and Restoring a Randon Generator’s State"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomFillUniformFloat(_:_:_:_:)/title",
          "value": "BNNSRandomFillUniformFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomFillUniformFloat(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomFillUniformFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomFillNormalFloat(_:_:_:_:)/title",
          "value": "BNNSRandomFillNormalFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomFillNormalFloat(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomFillNormalFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDestroyRandomGenerator(_:)/title",
          "value": "BNNSDestroyRandomGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSDestroyRandomGenerator(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSDestroyRandomGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGenerator/title",
          "value": "BNNSRandomGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomFillUniformInt(_:_:_:_:)/title",
          "value": "BNNSRandomFillUniformInt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomFillUniformInt(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomFillUniformInt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGeneratorStateSize(_:)/title",
          "value": "BNNSRandomGeneratorStateSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGeneratorStateSize(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomGeneratorStateSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomFillCategoricalFloat(_:_:_:_:)/title",
          "value": "BNNSRandomFillCategoricalFloat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomFillCategoricalFloat(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomFillCategoricalFloat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGeneratorMethod/title",
          "value": "BNNSRandomGeneratorMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGeneratorMethod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomGeneratorMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGeneratorMethod/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomGeneratorMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGeneratorSetState(_:_:_:)/title",
          "value": "BNNSRandomGeneratorSetState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGeneratorSetState(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomGeneratorSetState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSCreateRandomGenerator(_:_:)/title",
          "value": "BNNSCreateRandomGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSCreateRandomGenerator(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSCreateRandomGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGeneratorGetState(_:_:_:)/title",
          "value": "BNNSRandomGeneratorGetState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSRandomGeneratorGetState(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSRandomGeneratorGetState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSCreateRandomGeneratorWithSeed(_:_:_:)/title",
          "value": "BNNSCreateRandomGeneratorWithSeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSCreateRandomGeneratorWithSeed(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSCreateRandomGeneratorWithSeed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnns/randomgenerator"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
