{
  "abstract": [
    {
      "text": "Review unsupported symbols and their replacements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.os/documentation/os"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.os/documentation/os/deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "os"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated Symbols"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.os/documentation/os": {
      "abstract": [
        {
          "text": "Coordinate the scheduling and synchronization of your app’s tasks, and log information to the console to diagnose issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os",
      "kind": "symbol",
      "role": "collection",
      "title": "os",
      "type": "topic",
      "url": "/documentation/os"
    },
    "doc://com.apple.os/documentation/os/OS_TRACE_TYPE_DEBUG": {
      "abstract": [
        {
          "text": "Trace messages that occur when a debugger is attached.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_TRACE_TYPE_DEBUG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_TRACE_TYPE_DEBUG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_TRACE_TYPE_DEBUG"
        }
      ],
      "role": "symbol",
      "title": "OS_TRACE_TYPE_DEBUG",
      "type": "topic",
      "url": "/documentation/os/os_trace_type_debug"
    },
    "doc://com.apple.os/documentation/os/OS_TRACE_TYPE_INFO": {
      "abstract": [
        {
          "text": "Trace messages that occur when a debugger is attached and additional info is requested.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_TRACE_TYPE_INFO"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_TRACE_TYPE_INFO",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_TRACE_TYPE_INFO"
        }
      ],
      "role": "symbol",
      "title": "OS_TRACE_TYPE_INFO",
      "type": "topic",
      "url": "/documentation/os/os_trace_type_info"
    },
    "doc://com.apple.os/documentation/os/OS_TRACE_TYPE_RELEASE": {
      "abstract": [
        {
          "text": "Trace messages to be captured on your app when instealled on a user’s device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_TRACE_TYPE_RELEASE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_TRACE_TYPE_RELEASE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_TRACE_TYPE_RELEASE"
        }
      ],
      "role": "symbol",
      "title": "OS_TRACE_TYPE_RELEASE",
      "type": "topic",
      "url": "/documentation/os/os_trace_type_release"
    },
    "doc://com.apple.os/documentation/os/os_activity_end": {
      "abstract": [
        {
          "text": "Ends the specified activity on the current thread.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_end"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_end",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_end",
      "type": "topic",
      "url": "/documentation/os/os_activity_end"
    },
    "doc://com.apple.os/documentation/os/os_activity_get_active": {
      "abstract": [
        {
          "text": "Returns the stack of nested activities associated with the current thread.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_get_active"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_get_active",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_get_active",
      "type": "topic",
      "url": "/documentation/os/os_activity_get_active"
    },
    "doc://com.apple.os/documentation/os/os_activity_set_breadcrumb": {
      "abstract": [
        {
          "text": "Flags the current activity as a breadcrumb, to signify an interesting event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_set_breadcrumb"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_set_breadcrumb",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_set_breadcrumb",
      "type": "topic",
      "url": "/documentation/os/os_activity_set_breadcrumb"
    },
    "doc://com.apple.os/documentation/os/os_activity_start": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_start"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_start",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_start",
      "type": "topic",
      "url": "/documentation/os/os_activity_start"
    },
    "doc://com.apple.os/documentation/os/os_breadcrumb_t": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_breadcrumb_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_breadcrumb_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_breadcrumb_t",
      "type": "topic",
      "url": "/documentation/os/os_breadcrumb_t"
    },
    "doc://com.apple.os/documentation/os/os_log_is_debug_enabled": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_is_debug_enabled"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_is_debug_enabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_is_debug_enabled",
      "type": "topic",
      "url": "/documentation/os/os_log_is_debug_enabled"
    },
    "doc://com.apple.os/documentation/os/os_log_is_enabled": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_is_enabled"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_is_enabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_is_enabled",
      "type": "topic",
      "url": "/documentation/os/os_log_is_enabled"
    },
    "doc://com.apple.os/documentation/os/os_trace_debug_enabled()": {
      "abstract": [
        {
          "text": "Returns whether debug level trace information is enabled.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "os_trace_debug_enabled"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_trace_debug_enabled()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "os_trace_debug_enabled"
        }
      ],
      "role": "symbol",
      "title": "os_trace_debug_enabled()",
      "type": "topic",
      "url": "/documentation/os/os_trace_debug_enabled()"
    },
    "doc://com.apple.os/documentation/os/os_trace_info_enabled()": {
      "abstract": [
        {
          "text": "Returns whether info level trace information is enabled.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "os_trace_info_enabled"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_trace_info_enabled()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "os_trace_info_enabled"
        }
      ],
      "role": "symbol",
      "title": "os_trace_info_enabled()",
      "type": "topic",
      "url": "/documentation/os/os_trace_info_enabled()"
    },
    "doc://com.apple.os/documentation/os/os_trace_payload_object_t": {
      "abstract": [
        {
          "text": "A pointer to a trace payload object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "os_trace_payload_object_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_trace_payload_object_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "os_trace_payload_object_t"
        }
      ],
      "role": "symbol",
      "title": "os_trace_payload_object_t",
      "type": "topic",
      "url": "/documentation/os/os_trace_payload_object_t"
    },
    "doc://com.apple.os/documentation/os/os_trace_payload_t": {
      "abstract": [
        {
          "text": "A pointer to a trace payload.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_trace_payload_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_trace_payload_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_trace_payload_t",
      "type": "topic",
      "url": "/documentation/os/os_trace_payload_t"
    },
    "doc://com.apple.os/documentation/os/os_trace_type_enabled(_:)": {
      "abstract": [
        {
          "text": "Returns whether the specified info level trace information is enabled.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "os_trace_type_enabled"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_trace_type_enabled(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "os_trace_type_enabled"
        }
      ],
      "role": "symbol",
      "title": "os_trace_type_enabled(_:)",
      "type": "topic",
      "url": "/documentation/os/os_trace_type_enabled(_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Deprecated-Functions",
      "identifiers": [
        "doc://com.apple.os/documentation/os/os_trace_debug_enabled()",
        "doc://com.apple.os/documentation/os/os_trace_info_enabled()",
        "doc://com.apple.os/documentation/os/os_trace_type_enabled(_:)"
      ],
      "title": "Deprecated Functions"
    },
    {
      "anchor": "Deprecated-Macros",
      "identifiers": [
        "doc://com.apple.os/documentation/os/OS_TRACE_TYPE_DEBUG",
        "doc://com.apple.os/documentation/os/OS_TRACE_TYPE_INFO",
        "doc://com.apple.os/documentation/os/OS_TRACE_TYPE_RELEASE"
      ],
      "title": "Deprecated Macros"
    },
    {
      "anchor": "Deprecated-Type-Aliases",
      "identifiers": [
        "doc://com.apple.os/documentation/os/os_trace_payload_object_t"
      ],
      "title": "Deprecated Type Aliases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Deprecated-Functions",
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_log_is_enabled",
                "doc://com.apple.os/documentation/os/os_log_is_debug_enabled",
                "doc://com.apple.os/documentation/os/os_activity_get_active",
                "doc://com.apple.os/documentation/os/os_activity_end",
                "doc://com.apple.os/documentation/os/os_trace_debug_enabled()",
                "doc://com.apple.os/documentation/os/os_trace_info_enabled()",
                "doc://com.apple.os/documentation/os/os_trace_type_enabled(_:)"
              ],
              "title": "Deprecated Functions"
            },
            {
              "anchor": "Deprecated-Macros",
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_activity_start",
                "doc://com.apple.os/documentation/os/os_activity_set_breadcrumb",
                "doc://com.apple.os/documentation/os/OS_TRACE_TYPE_DEBUG",
                "doc://com.apple.os/documentation/os/OS_TRACE_TYPE_INFO",
                "doc://com.apple.os/documentation/os/OS_TRACE_TYPE_RELEASE"
              ],
              "title": "Deprecated Macros"
            },
            {
              "anchor": "Deprecated-Type-Aliases",
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_breadcrumb_t",
                "doc://com.apple.os/documentation/os/os_trace_payload_t",
                "doc://com.apple.os/documentation/os/os_trace_payload_object_t"
              ],
              "title": "Deprecated Type Aliases"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_TRACE_TYPE_DEBUG/title",
          "value": "OS_TRACE_TYPE_DEBUG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_TRACE_TYPE_DEBUG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_TRACE_TYPE_DEBUG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_trace_info_enabled()/title",
          "value": "os_trace_info_enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_trace_info_enabled()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_trace_info_enabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_trace_type_enabled(_:)/title",
          "value": "os_trace_type_enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_trace_type_enabled(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_trace_type_enabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_trace_debug_enabled()/title",
          "value": "os_trace_debug_enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_trace_debug_enabled()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_trace_debug_enabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_trace_payload_object_t/title",
          "value": "os_trace_payload_object_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_trace_payload_object_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_trace_payload_object_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_trace_payload_object_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "os_trace_payload_object_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_TRACE_TYPE_INFO/title",
          "value": "OS_TRACE_TYPE_INFO"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_TRACE_TYPE_INFO/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_TRACE_TYPE_INFO"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_TRACE_TYPE_RELEASE/title",
          "value": "OS_TRACE_TYPE_RELEASE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_TRACE_TYPE_RELEASE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_TRACE_TYPE_RELEASE"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/os/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/os/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
