{
  "abstract": [
    {
      "text": "Migrate your code away from using these legacy symbols.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.os/documentation/os",
        "doc://com.apple.os/documentation/os/logging"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.os/documentation/os/legacy-logging-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "os"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Legacy Logging Symbols"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.os/documentation/os": {
      "abstract": [
        {
          "text": "Coordinate the scheduling and synchronization of your app’s tasks, and log information to the console to diagnose issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os",
      "kind": "symbol",
      "role": "collection",
      "title": "os",
      "type": "topic",
      "url": "/documentation/os"
    },
    "doc://com.apple.os/documentation/os/OSLogType": {
      "abstract": [
        {
          "text": "The various log levels that the unified logging system provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogType"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogType"
        }
      ],
      "role": "symbol",
      "title": "OSLogType",
      "type": "topic",
      "url": "/documentation/os/oslogtype"
    },
    "doc://com.apple.os/documentation/os/logging": {
      "abstract": [
        {
          "text": "Capture telemetry from your app for debugging and performance analysis using the unified logging system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/logging",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Logging",
      "type": "topic",
      "url": "/documentation/os/logging"
    },
    "doc://com.apple.os/documentation/os/message-argument-formatters": {
      "abstract": [
        {
          "text": "Manage the privacy and presentation of the message’s interpolated values using type-aware formatters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/message-argument-formatters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Message Argument Formatters",
      "type": "topic",
      "url": "/documentation/os/message-argument-formatters"
    },
    "doc://com.apple.os/documentation/os/os-log-t": {
      "abstract": [
        {
          "text": "A log object that you pass to logging functions to send messages to that log.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os-log-t",
      "kind": "article",
      "role": "collectionGroup",
      "title": "os_log_t",
      "type": "topic",
      "url": "/documentation/os/os-log-t"
    },
    "doc://com.apple.os/documentation/os/os_log": {
      "abstract": [
        {
          "text": "Sends a default-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log",
      "type": "topic",
      "url": "/documentation/os/os_log"
    },
    "doc://com.apple.os/documentation/os/os_log(_:)": {
      "abstract": [
        {
          "text": "Adds a new log message to the default subsystem.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "os_log"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:2os12OSLogMessageV",
          "text": "OSLogMessage"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log(_:)",
      "type": "topic",
      "url": "/documentation/os/os_log(_:)"
    },
    "doc://com.apple.os/documentation/os/os_log(_:dso:log:_:_:)": {
      "abstract": [
        {
          "text": "Sends a message to the logging system, optionally specifying a custom log object, log level, and any message-format arguments.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "os_log"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@os_log_type_t",
          "text": "OSLogType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dso"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "log"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_os_log",
          "text": "OSLog"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s12StaticStringV",
          "text": "StaticString"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7CVarArgP",
          "text": "CVarArg"
        },
        {
          "kind": "text",
          "text": "...)"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log(_:dso:log:_:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log(_:dso:log:_:_:)",
      "type": "topic",
      "url": "/documentation/os/os_log(_:dso:log:_:_:)"
    },
    "doc://com.apple.os/documentation/os/os_log(_:dso:log:type:_:)": {
      "abstract": [
        {
          "text": "Sends a message to the logging system, optionally specifying a custom log object, log level, and any message format arguments.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "os_log"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s12StaticStringV",
          "text": "StaticString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dso"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "log"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_os_log",
          "text": "OSLog"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@os_log_type_t",
          "text": "OSLogType"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7CVarArgP",
          "text": "CVarArg"
        },
        {
          "kind": "text",
          "text": "...)"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log(_:dso:log:type:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log(_:dso:log:type:_:)",
      "type": "topic",
      "url": "/documentation/os/os_log(_:dso:log:type:_:)"
    },
    "doc://com.apple.os/documentation/os/os_log(_:log:_:)": {
      "abstract": [
        {
          "text": "Adds a new log message using an optional log object and log level.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "os_log"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@os_log_type_t",
          "text": "OSLogType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "log"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_os_log",
          "text": "OSLog"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:2os12OSLogMessageV",
          "text": "OSLogMessage"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log(_:log:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log(_:log:_:)",
      "type": "topic",
      "url": "/documentation/os/os_log(_:log:_:)"
    },
    "doc://com.apple.os/documentation/os/os_log_debug": {
      "abstract": [
        {
          "text": "Sends a debug-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_debug"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_debug",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_debug",
      "type": "topic",
      "url": "/documentation/os/os_log_debug"
    },
    "doc://com.apple.os/documentation/os/os_log_error": {
      "abstract": [
        {
          "text": "Sends an error-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_error"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_error",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_error",
      "type": "topic",
      "url": "/documentation/os/os_log_error"
    },
    "doc://com.apple.os/documentation/os/os_log_fault": {
      "abstract": [
        {
          "text": "Sends a fault-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_fault"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_fault",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_fault",
      "type": "topic",
      "url": "/documentation/os/os_log_fault"
    },
    "doc://com.apple.os/documentation/os/os_log_info": {
      "abstract": [
        {
          "text": "Sends an info-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_info"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_info",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_info",
      "type": "topic",
      "url": "/documentation/os/os_log_info"
    },
    "doc://com.apple.os/documentation/os/os_log_with_type": {
      "abstract": [
        {
          "text": "Sends a message at a specific logging level, such as default, info, debug, error, or fault, to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_with_type"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_with_type",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_with_type",
      "type": "topic",
      "url": "/documentation/os/os_log_with_type"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Log-Messages",
      "identifiers": [
        "doc://com.apple.os/documentation/os/os_log(_:)",
        "doc://com.apple.os/documentation/os/os_log(_:log:_:)",
        "doc://com.apple.os/documentation/os/os_log(_:dso:log:_:_:)",
        "doc://com.apple.os/documentation/os/os_log(_:dso:log:type:_:)"
      ],
      "title": "Log Messages"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Log-Messages",
              "generated": true,
              "identifiers": [
                "doc://com.apple.os/documentation/os/message-argument-formatters",
                "doc://com.apple.os/documentation/os/os-log-t",
                "doc://com.apple.os/documentation/os/os_log_with_type",
                "doc://com.apple.os/documentation/os/OSLogType",
                "doc://com.apple.os/documentation/os/os_log",
                "doc://com.apple.os/documentation/os/os_log_info",
                "doc://com.apple.os/documentation/os/os_log_debug",
                "doc://com.apple.os/documentation/os/os_log_error",
                "doc://com.apple.os/documentation/os/os_log_fault"
              ],
              "title": "Log Messages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSLogType/title",
          "value": "os_log_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSLogType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_log_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSLogType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "os_log_type_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/os/legacy-logging-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/os/legacy-logging-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
