{
  "abstract": [
    {
      "text": "Manage the privacy and presentation of the message’s interpolated values using type-aware formatters.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.os/documentation/os",
        "doc://com.apple.os/documentation/os/logging"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.os/documentation/os/message-argument-formatters"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "os"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Message Argument Formatters"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.os/documentation/os": {
      "abstract": [
        {
          "text": "Coordinate the scheduling and synchronization of your app’s tasks, and log information to the console to diagnose issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os",
      "kind": "symbol",
      "role": "collection",
      "title": "os",
      "type": "topic",
      "url": "/documentation/os"
    },
    "doc://com.apple.os/documentation/os/Logger": {
      "abstract": [
        {
          "text": "An object for writing interpolated string messages to the unified logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Logger"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/Logger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Logger"
        }
      ],
      "role": "symbol",
      "title": "Logger",
      "type": "topic",
      "url": "/documentation/os/logger"
    },
    "doc://com.apple.os/documentation/os/OSLogBoolFormat": {
      "abstract": [
        {
          "text": "The formatting options for Boolean values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogBoolFormat"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogBoolFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogBoolFormat"
        }
      ],
      "role": "symbol",
      "title": "OSLogBoolFormat",
      "type": "topic",
      "url": "/documentation/os/oslogboolformat"
    },
    "doc://com.apple.os/documentation/os/OSLogFloatFormatting": {
      "abstract": [
        {
          "text": "The formatting options for double and floating-point numbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogFloatFormatting"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogFloatFormatting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogFloatFormatting"
        }
      ],
      "role": "symbol",
      "title": "OSLogFloatFormatting",
      "type": "topic",
      "url": "/documentation/os/oslogfloatformatting"
    },
    "doc://com.apple.os/documentation/os/OSLogInt32ExtendedFormat": {
      "abstract": [
        {
          "text": "The formatting options for 32-bit integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogInt32ExtendedFormat"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogInt32ExtendedFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogInt32ExtendedFormat"
        }
      ],
      "role": "symbol",
      "title": "OSLogInt32ExtendedFormat",
      "type": "topic",
      "url": "/documentation/os/oslogint32extendedformat"
    },
    "doc://com.apple.os/documentation/os/OSLogIntExtendedFormat": {
      "abstract": [
        {
          "text": "Options for expanding bit rate information stored as an int during logging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogIntExtendedFormat"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogIntExtendedFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogIntExtendedFormat"
        }
      ],
      "role": "symbol",
      "title": "OSLogIntExtendedFormat",
      "type": "topic",
      "url": "/documentation/os/oslogintextendedformat"
    },
    "doc://com.apple.os/documentation/os/OSLogIntegerFormatting": {
      "abstract": [
        {
          "text": "The formatting options for integer values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogIntegerFormatting"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogIntegerFormatting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogIntegerFormatting"
        }
      ],
      "role": "symbol",
      "title": "OSLogIntegerFormatting",
      "type": "topic",
      "url": "/documentation/os/oslogintegerformatting"
    },
    "doc://com.apple.os/documentation/os/OSLogInterpolation": {
      "abstract": [
        {
          "text": "A container for the elements of a log message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogInterpolation"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogInterpolation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogInterpolation"
        }
      ],
      "role": "symbol",
      "title": "OSLogInterpolation",
      "type": "topic",
      "url": "/documentation/os/osloginterpolation"
    },
    "doc://com.apple.os/documentation/os/OSLogPointerFormat": {
      "abstract": [
        {
          "text": "The formatting options for pointer data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogPointerFormat"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogPointerFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogPointerFormat"
        }
      ],
      "role": "symbol",
      "title": "OSLogPointerFormat",
      "type": "topic",
      "url": "/documentation/os/oslogpointerformat"
    },
    "doc://com.apple.os/documentation/os/OSLogPrivacy": {
      "abstract": [
        {
          "text": "The privacy options that determine when to redact or display values in log messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogPrivacy"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogPrivacy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogPrivacy"
        }
      ],
      "role": "symbol",
      "title": "OSLogPrivacy",
      "type": "topic",
      "url": "/documentation/os/oslogprivacy"
    },
    "doc://com.apple.os/documentation/os/OSLogStringAlignment": {
      "abstract": [
        {
          "text": "The alignment options for interpolated strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogStringAlignment"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogStringAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogStringAlignment"
        }
      ],
      "role": "symbol",
      "title": "OSLogStringAlignment",
      "type": "topic",
      "url": "/documentation/os/oslogstringalignment"
    },
    "doc://com.apple.os/documentation/os/OSLogType": {
      "abstract": [
        {
          "text": "The various log levels that the unified logging system provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogType"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogType"
        }
      ],
      "role": "symbol",
      "title": "OSLogType",
      "type": "topic",
      "url": "/documentation/os/oslogtype"
    },
    "doc://com.apple.os/documentation/os/legacy-logging-symbols": {
      "abstract": [
        {
          "text": "Migrate your code away from using these legacy symbols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/legacy-logging-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Legacy Logging Symbols",
      "type": "topic",
      "url": "/documentation/os/legacy-logging-symbols"
    },
    "doc://com.apple.os/documentation/os/logging": {
      "abstract": [
        {
          "text": "Capture telemetry from your app for debugging and performance analysis using the unified logging system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/logging",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Logging",
      "type": "topic",
      "url": "/documentation/os/logging"
    },
    "doc://com.apple.os/documentation/os/os-log-t": {
      "abstract": [
        {
          "text": "A log object that you pass to logging functions to send messages to that log.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os-log-t",
      "kind": "article",
      "role": "collectionGroup",
      "title": "os_log_t",
      "type": "topic",
      "url": "/documentation/os/os-log-t"
    },
    "doc://com.apple.os/documentation/os/os_log": {
      "abstract": [
        {
          "text": "Sends a default-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log",
      "type": "topic",
      "url": "/documentation/os/os_log"
    },
    "doc://com.apple.os/documentation/os/os_log_debug": {
      "abstract": [
        {
          "text": "Sends a debug-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_debug"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_debug",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_debug",
      "type": "topic",
      "url": "/documentation/os/os_log_debug"
    },
    "doc://com.apple.os/documentation/os/os_log_error": {
      "abstract": [
        {
          "text": "Sends an error-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_error"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_error",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_error",
      "type": "topic",
      "url": "/documentation/os/os_log_error"
    },
    "doc://com.apple.os/documentation/os/os_log_fault": {
      "abstract": [
        {
          "text": "Sends a fault-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_fault"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_fault",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_fault",
      "type": "topic",
      "url": "/documentation/os/os_log_fault"
    },
    "doc://com.apple.os/documentation/os/os_log_info": {
      "abstract": [
        {
          "text": "Sends an info-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_info"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_info",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_info",
      "type": "topic",
      "url": "/documentation/os/os_log_info"
    },
    "doc://com.apple.os/documentation/os/os_log_with_type": {
      "abstract": [
        {
          "text": "Sends a message at a specific logging level, such as default, info, debug, error, or fault, to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_with_type"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_with_type",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_with_type",
      "type": "topic",
      "url": "/documentation/os/os_log_with_type"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Log-Messages",
      "generated": true,
      "identifiers": [
        "doc://com.apple.os/documentation/os/Logger",
        "doc://com.apple.os/documentation/os/OSLogType"
      ],
      "title": "Log Messages"
    }
  ],
  "topicSections": [
    {
      "anchor": "Privacy-Options",
      "identifiers": [
        "doc://com.apple.os/documentation/os/OSLogPrivacy"
      ],
      "title": "Privacy Options"
    },
    {
      "anchor": "Value-Formatters",
      "identifiers": [
        "doc://com.apple.os/documentation/os/OSLogBoolFormat",
        "doc://com.apple.os/documentation/os/OSLogIntegerFormatting",
        "doc://com.apple.os/documentation/os/OSLogInt32ExtendedFormat",
        "doc://com.apple.os/documentation/os/OSLogFloatFormatting",
        "doc://com.apple.os/documentation/os/OSLogPointerFormat"
      ],
      "title": "Value Formatters"
    },
    {
      "anchor": "Value-Interpolation",
      "identifiers": [
        "doc://com.apple.os/documentation/os/OSLogInterpolation",
        "doc://com.apple.os/documentation/os/OSLogIntExtendedFormat"
      ],
      "title": "Value Interpolation"
    },
    {
      "anchor": "String-Alignment",
      "identifiers": [
        "doc://com.apple.os/documentation/os/OSLogStringAlignment"
      ],
      "title": "String Alignment"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Log-Messages",
              "generated": true,
              "identifiers": [
                "doc://com.apple.os/documentation/os/legacy-logging-symbols",
                "doc://com.apple.os/documentation/os/os-log-t",
                "doc://com.apple.os/documentation/os/os_log_with_type",
                "doc://com.apple.os/documentation/os/OSLogType",
                "doc://com.apple.os/documentation/os/os_log",
                "doc://com.apple.os/documentation/os/os_log_info",
                "doc://com.apple.os/documentation/os/os_log_debug",
                "doc://com.apple.os/documentation/os/os_log_error",
                "doc://com.apple.os/documentation/os/os_log_fault"
              ],
              "title": "Log Messages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSLogType/title",
          "value": "os_log_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSLogType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_log_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSLogType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "os_log_type_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/os/message-argument-formatters"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/os/message-argument-formatters"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
