{
  "abstract": [
    {
      "text": "An object that represents an activity triggered by the user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.os/documentation/os",
        "doc://com.apple.os/documentation/os/logging"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.os/documentation/os/os-activity-t"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "os"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "os_activity_t"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Activity Tracing APIs provide a mechanism for grouping and labeling work that’s done in response to user interactions or other events, so that you can see all log messages related to the triggering action.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.os/documentation/os": {
      "abstract": [
        {
          "text": "Coordinate the scheduling and synchronization of your app’s tasks, and log information to the console to diagnose issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os",
      "kind": "symbol",
      "role": "collection",
      "title": "os",
      "type": "topic",
      "url": "/documentation/os"
    },
    "doc://com.apple.os/documentation/os/collecting-log-messages-in-activities": {
      "abstract": [
        {
          "text": "Find messages related to a specific user action or application event.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/collecting-log-messages-in-activities",
      "kind": "article",
      "role": "article",
      "title": "Collecting Log Messages in Activities",
      "type": "topic",
      "url": "/documentation/os/collecting-log-messages-in-activities"
    },
    "doc://com.apple.os/documentation/os/logging": {
      "abstract": [
        {
          "text": "Capture telemetry from your app for debugging and performance analysis using the unified logging system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/logging",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Logging",
      "type": "topic",
      "url": "/documentation/os/logging"
    },
    "doc://com.apple.os/documentation/os/os_activity_apply": {
      "abstract": [
        {
          "text": "Execute a block using a given activity object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_apply"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_apply",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_apply",
      "type": "topic",
      "url": "/documentation/os/os_activity_apply"
    },
    "doc://com.apple.os/documentation/os/os_activity_apply_f": {
      "abstract": [
        {
          "text": "Execute a function using a given activity object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_apply_f"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_apply_f",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_apply_f",
      "type": "topic",
      "url": "/documentation/os/os_activity_apply_f"
    },
    "doc://com.apple.os/documentation/os/os_activity_create": {
      "abstract": [
        {
          "text": "Creates a new activity object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_create"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_create",
      "type": "topic",
      "url": "/documentation/os/os_activity_create"
    },
    "doc://com.apple.os/documentation/os/os_activity_flag_t": {
      "abstract": [
        {
          "text": "Flags that adjust the behavior when you create an activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_flag_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_flag_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_flag_t",
      "type": "topic",
      "url": "/documentation/os/os_activity_flag_t"
    },
    "doc://com.apple.os/documentation/os/os_activity_get_identifier": {
      "abstract": [
        {
          "text": "Retrieves the identifier for a given activity object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_get_identifier"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_get_identifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_get_identifier",
      "type": "topic",
      "url": "/documentation/os/os_activity_get_identifier"
    },
    "doc://com.apple.os/documentation/os/os_activity_id_t": {
      "abstract": [
        {
          "text": "A number that uniquely identifies an activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_id_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_id_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_id_t",
      "type": "topic",
      "url": "/documentation/os/os_activity_id_t"
    },
    "doc://com.apple.os/documentation/os/os_activity_initiate": {
      "abstract": [
        {
          "text": "Synchronously executes a new activity using the provided block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_initiate"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_initiate",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_initiate",
      "type": "topic",
      "url": "/documentation/os/os_activity_initiate"
    },
    "doc://com.apple.os/documentation/os/os_activity_initiate_f": {
      "abstract": [
        {
          "text": "Synchronously executes a new activity using the provided function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_initiate_f"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_initiate_f",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_initiate_f",
      "type": "topic",
      "url": "/documentation/os/os_activity_initiate_f"
    },
    "doc://com.apple.os/documentation/os/os_activity_label_useraction": {
      "abstract": [
        {
          "text": "Label an activity that is auto-generated by AppKit or UIKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_label_useraction"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_label_useraction",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_label_useraction",
      "type": "topic",
      "url": "/documentation/os/os_activity_label_useraction"
    },
    "doc://com.apple.os/documentation/os/os_activity_scope_enter": {
      "abstract": [
        {
          "text": "Switches the current activity, saving the existing execution context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_scope_enter"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_scope_enter",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_scope_enter",
      "type": "topic",
      "url": "/documentation/os/os_activity_scope_enter"
    },
    "doc://com.apple.os/documentation/os/os_activity_scope_leave": {
      "abstract": [
        {
          "text": "Restores the current activity to a previously saved state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_scope_leave"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_scope_leave",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_scope_leave",
      "type": "topic",
      "url": "/documentation/os/os_activity_scope_leave"
    },
    "doc://com.apple.os/documentation/os/os_activity_scope_state_t": {
      "abstract": [
        {
          "text": "An opaque structure that contains a saved activity-execution context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_scope_state_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_scope_state_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_scope_state_t",
      "type": "topic",
      "url": "/documentation/os/os_activity_scope_state_t"
    },
    "doc://com.apple.os/documentation/os/os_activity_t": {
      "abstract": [
        {
          "text": "An object that represents an activity triggered by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_t",
      "type": "topic",
      "url": "/documentation/os/os_activity_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Activities",
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_activity_initiate",
                "doc://com.apple.os/documentation/os/os_activity_initiate_f",
                "doc://com.apple.os/documentation/os/os_activity_create",
                "doc://com.apple.os/documentation/os/os_activity_label_useraction",
                "doc://com.apple.os/documentation/os/os_activity_flag_t"
              ],
              "title": "Creating Activities"
            },
            {
              "anchor": "Executing-an-Activity",
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_activity_apply",
                "doc://com.apple.os/documentation/os/os_activity_apply_f"
              ],
              "title": "Executing an Activity"
            },
            {
              "anchor": "Retrieving-an-Activity-Identifier",
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_activity_get_identifier",
                "doc://com.apple.os/documentation/os/os_activity_id_t"
              ],
              "title": "Retrieving an Activity Identifier"
            },
            {
              "anchor": "Saving-and-Restoring-Activity-States",
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_activity_scope_enter",
                "doc://com.apple.os/documentation/os/os_activity_scope_leave",
                "doc://com.apple.os/documentation/os/os_activity_scope_state_t"
              ],
              "title": "Saving and Restoring Activity States"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_activity_t"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Trace-Activities",
              "generated": true,
              "identifiers": [
                "doc://com.apple.os/documentation/os/collecting-log-messages-in-activities"
              ],
              "title": "Trace Activities"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/os/os-activity-t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/os/os-activity-t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
