{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.os/documentation/os"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.os/documentation/os/os-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "os"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "os Constants"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.os/documentation/os": {
      "abstract": [
        {
          "text": "Coordinate the scheduling and synchronization of your app’s tasks, and log information to the console to diagnose issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os",
      "kind": "symbol",
      "role": "collection",
      "title": "os",
      "type": "topic",
      "url": "/documentation/os"
    },
    "doc://com.apple.os/documentation/os/OS_ATOMIC_USES_CXX": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_ATOMIC_USES_CXX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_ATOMIC_USES_CXX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_ATOMIC_USES_CXX"
        }
      ],
      "role": "symbol",
      "title": "OS_ATOMIC_USES_CXX",
      "type": "topic",
      "url": "/documentation/os/os_atomic_uses_cxx"
    },
    "doc://com.apple.os/documentation/os/OS_LOG_TARGET_HAS_10_12_FEATURES": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_LOG_TARGET_HAS_10_12_FEATURES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_LOG_TARGET_HAS_10_12_FEATURES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_LOG_TARGET_HAS_10_12_FEATURES"
        }
      ],
      "role": "symbol",
      "title": "OS_LOG_TARGET_HAS_10_12_FEATURES",
      "type": "topic",
      "url": "/documentation/os/os_log_target_has_10_12_features"
    },
    "doc://com.apple.os/documentation/os/OS_LOG_TARGET_HAS_10_13_FEATURES": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_LOG_TARGET_HAS_10_13_FEATURES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_LOG_TARGET_HAS_10_13_FEATURES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_LOG_TARGET_HAS_10_13_FEATURES"
        }
      ],
      "role": "symbol",
      "title": "OS_LOG_TARGET_HAS_10_13_FEATURES",
      "type": "topic",
      "url": "/documentation/os/os_log_target_has_10_13_features"
    },
    "doc://com.apple.os/documentation/os/OS_LOG_TARGET_HAS_10_14_FEATURES": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_LOG_TARGET_HAS_10_14_FEATURES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_LOG_TARGET_HAS_10_14_FEATURES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_LOG_TARGET_HAS_10_14_FEATURES"
        }
      ],
      "role": "symbol",
      "title": "OS_LOG_TARGET_HAS_10_14_FEATURES",
      "type": "topic",
      "url": "/documentation/os/os_log_target_has_10_14_features"
    },
    "doc://com.apple.os/documentation/os/OS_LOG_TARGET_HAS_10_15_FEATURES": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_LOG_TARGET_HAS_10_15_FEATURES"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_LOG_TARGET_HAS_10_15_FEATURES",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_LOG_TARGET_HAS_10_15_FEATURES"
        }
      ],
      "role": "symbol",
      "title": "OS_LOG_TARGET_HAS_10_15_FEATURES",
      "type": "topic",
      "url": "/documentation/os/os_log_target_has_10_15_features"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.os/documentation/os/OS_ATOMIC_USES_CXX",
        "doc://com.apple.os/documentation/os/OS_LOG_TARGET_HAS_10_12_FEATURES",
        "doc://com.apple.os/documentation/os/OS_LOG_TARGET_HAS_10_13_FEATURES",
        "doc://com.apple.os/documentation/os/OS_LOG_TARGET_HAS_10_14_FEATURES",
        "doc://com.apple.os/documentation/os/OS_LOG_TARGET_HAS_10_15_FEATURES"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.os/documentation/os/OS_ATOMIC_USES_CXX",
                "doc://com.apple.os/documentation/os/OS_LOG_TARGET_HAS_10_12_FEATURES",
                "doc://com.apple.os/documentation/os/OS_LOG_TARGET_HAS_10_13_FEATURES",
                "doc://com.apple.os/documentation/os/OS_LOG_TARGET_HAS_10_14_FEATURES",
                "doc://com.apple.os/documentation/os/OS_LOG_TARGET_HAS_10_15_FEATURES"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_LOG_TARGET_HAS_10_14_FEATURES/title",
          "value": "OS_LOG_TARGET_HAS_10_14_FEATURES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_LOG_TARGET_HAS_10_14_FEATURES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_LOG_TARGET_HAS_10_14_FEATURES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_LOG_TARGET_HAS_10_13_FEATURES/title",
          "value": "OS_LOG_TARGET_HAS_10_13_FEATURES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_LOG_TARGET_HAS_10_13_FEATURES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_LOG_TARGET_HAS_10_13_FEATURES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_LOG_TARGET_HAS_10_12_FEATURES/title",
          "value": "OS_LOG_TARGET_HAS_10_12_FEATURES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_LOG_TARGET_HAS_10_12_FEATURES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_LOG_TARGET_HAS_10_12_FEATURES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_LOG_TARGET_HAS_10_15_FEATURES/title",
          "value": "OS_LOG_TARGET_HAS_10_15_FEATURES"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_LOG_TARGET_HAS_10_15_FEATURES/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_LOG_TARGET_HAS_10_15_FEATURES"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_ATOMIC_USES_CXX/title",
          "value": "OS_ATOMIC_USES_CXX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_ATOMIC_USES_CXX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_ATOMIC_USES_CXX"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/os/os-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/os/os-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
