{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.os/documentation/os"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.os/documentation/os/os-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "os"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "os Data Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.os/documentation/os": {
      "abstract": [
        {
          "text": "Coordinate the scheduling and synchronization of your app’s tasks, and log information to the console to diagnose issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os",
      "kind": "symbol",
      "role": "collection",
      "title": "os",
      "type": "topic",
      "url": "/documentation/os"
    },
    "doc://com.apple.os/documentation/os/OS_os_activity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_os_activity"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_os_activity",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_os_activity",
      "type": "topic",
      "url": "/documentation/os/os_os_activity"
    },
    "doc://com.apple.os/documentation/os/OS_os_log": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_os_log"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_os_log",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_os_log",
      "type": "topic",
      "url": "/documentation/os/os_os_log"
    },
    "doc://com.apple.os/documentation/os/os-macros": {
      "abstract": [],
      "identifier": "doc://com.apple.os/documentation/os/os-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "os Macros",
      "type": "topic",
      "url": "/documentation/os/os-macros"
    },
    "doc://com.apple.os/documentation/os/os_activity_scope_state_s": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_scope_state_s"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_scope_state_s",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_scope_state_s",
      "type": "topic",
      "url": "/documentation/os/os_activity_scope_state_s"
    },
    "doc://com.apple.os/documentation/os/os_unfair_lock_s": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_unfair_lock_s"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_unfair_lock_s",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_unfair_lock_s",
      "type": "topic",
      "url": "/documentation/os/os_unfair_lock_s"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_attr_opaque_s": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_attr_opaque_s"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_attr_opaque_s",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_attr_opaque_s",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_attr_opaque_s"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_attr_s": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_attr_s"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_attr_s",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_attr_s",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_attr_s"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_interval_data_opaque_s": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_interval_data_opaque_s"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_interval_data_opaque_s",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_interval_data_opaque_s",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_interval_data_opaque_s"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_interval_data_s": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_interval_data_s"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_interval_data_s",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_interval_data_s",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_interval_data_s"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_join_token_opaque_s": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_join_token_opaque_s"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_join_token_opaque_s",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_join_token_opaque_s",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_join_token_opaque_s"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_join_token_s": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_join_token_s"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_join_token_s",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_join_token_s",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_join_token_s"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_mpt_attr_s": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_mpt_attr_s"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_mpt_attr_s",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_mpt_attr_s",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_mpt_attr_s"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Protocols",
              "identifiers": [
                "doc://com.apple.os/documentation/os/OS_os_activity",
                "doc://com.apple.os/documentation/os/OS_os_log"
              ],
              "title": "Protocols"
            },
            {
              "anchor": "Structures",
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_activity_scope_state_s",
                "doc://com.apple.os/documentation/os/os_unfair_lock_s",
                "doc://com.apple.os/documentation/os/os_workgroup_attr_opaque_s",
                "doc://com.apple.os/documentation/os/os_workgroup_interval_data_opaque_s",
                "doc://com.apple.os/documentation/os/os_workgroup_join_token_opaque_s"
              ],
              "title": "Structures"
            },
            {
              "anchor": "Type-Aliases",
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_workgroup_attr_s",
                "doc://com.apple.os/documentation/os/os_workgroup_interval_data_s",
                "doc://com.apple.os/documentation/os/os_workgroup_join_token_s",
                "doc://com.apple.os/documentation/os/os_workgroup_mpt_attr_s"
              ],
              "title": "Type Aliases"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.os/documentation/os/os-macros"
              ],
              "title": "Reference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/os/os-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/os/os-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
