{
  "abstract": [
    {
      "text": "A log object that you pass to logging functions to send messages to that log.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.os/documentation/os",
        "doc://com.apple.os/documentation/os/logging"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.os/documentation/os/os-log-t"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "os"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "os_log_t"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.os/documentation/os": {
      "abstract": [
        {
          "text": "Coordinate the scheduling and synchronization of your app’s tasks, and log information to the console to diagnose issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os",
      "kind": "symbol",
      "role": "collection",
      "title": "os",
      "type": "topic",
      "url": "/documentation/os"
    },
    "doc://com.apple.os/documentation/os/OSLog/isEnabled(type:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the log can write messages with the specified log type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEnabled"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@os_log_type_t",
          "text": "OSLogType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLog/isEnabled(type:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "os_log_type_enabled"
        }
      ],
      "role": "symbol",
      "title": "isEnabled(type:)",
      "type": "topic",
      "url": "/documentation/os/oslog/isenabled(type:)"
    },
    "doc://com.apple.os/documentation/os/OSLogType": {
      "abstract": [
        {
          "text": "The various log levels that the unified logging system provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogType"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogType"
        }
      ],
      "role": "symbol",
      "title": "OSLogType",
      "type": "topic",
      "url": "/documentation/os/oslogtype"
    },
    "doc://com.apple.os/documentation/os/OS_LOG_DEFAULT": {
      "abstract": [
        {
          "text": "The shared default log.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_LOG_DEFAULT"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_LOG_DEFAULT",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_LOG_DEFAULT",
      "type": "topic",
      "url": "/documentation/os/os_log_default"
    },
    "doc://com.apple.os/documentation/os/OS_LOG_DISABLED": {
      "abstract": [
        {
          "text": "The shared disabled log.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_LOG_DISABLED"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_LOG_DISABLED",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_LOG_DISABLED",
      "type": "topic",
      "url": "/documentation/os/os_log_disabled"
    },
    "doc://com.apple.os/documentation/os/legacy-logging-symbols": {
      "abstract": [
        {
          "text": "Migrate your code away from using these legacy symbols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/legacy-logging-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Legacy Logging Symbols",
      "type": "topic",
      "url": "/documentation/os/legacy-logging-symbols"
    },
    "doc://com.apple.os/documentation/os/logging": {
      "abstract": [
        {
          "text": "Capture telemetry from your app for debugging and performance analysis using the unified logging system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/logging",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Logging",
      "type": "topic",
      "url": "/documentation/os/logging"
    },
    "doc://com.apple.os/documentation/os/message-argument-formatters": {
      "abstract": [
        {
          "text": "Manage the privacy and presentation of the message’s interpolated values using type-aware formatters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/message-argument-formatters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Message Argument Formatters",
      "type": "topic",
      "url": "/documentation/os/message-argument-formatters"
    },
    "doc://com.apple.os/documentation/os/os_log": {
      "abstract": [
        {
          "text": "Sends a default-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log",
      "type": "topic",
      "url": "/documentation/os/os_log"
    },
    "doc://com.apple.os/documentation/os/os_log_create": {
      "abstract": [
        {
          "text": "Creates a custom log object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_create"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_create",
      "type": "topic",
      "url": "/documentation/os/os_log_create"
    },
    "doc://com.apple.os/documentation/os/os_log_debug": {
      "abstract": [
        {
          "text": "Sends a debug-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_debug"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_debug",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_debug",
      "type": "topic",
      "url": "/documentation/os/os_log_debug"
    },
    "doc://com.apple.os/documentation/os/os_log_debug_enabled": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether debug-level logging is in an enabled state for a specified log object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_debug_enabled"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_debug_enabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_debug_enabled",
      "type": "topic",
      "url": "/documentation/os/os_log_debug_enabled"
    },
    "doc://com.apple.os/documentation/os/os_log_error": {
      "abstract": [
        {
          "text": "Sends an error-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_error"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_error",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_error",
      "type": "topic",
      "url": "/documentation/os/os_log_error"
    },
    "doc://com.apple.os/documentation/os/os_log_fault": {
      "abstract": [
        {
          "text": "Sends a fault-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_fault"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_fault",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_fault",
      "type": "topic",
      "url": "/documentation/os/os_log_fault"
    },
    "doc://com.apple.os/documentation/os/os_log_info": {
      "abstract": [
        {
          "text": "Sends an info-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_info"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_info",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_info",
      "type": "topic",
      "url": "/documentation/os/os_log_info"
    },
    "doc://com.apple.os/documentation/os/os_log_info_enabled": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether info-level logging is in an enabled state for a specified log object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_info_enabled"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_info_enabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_info_enabled",
      "type": "topic",
      "url": "/documentation/os/os_log_info_enabled"
    },
    "doc://com.apple.os/documentation/os/os_log_t": {
      "abstract": [
        {
          "text": "A log object that you pass to logging functions to send messages to that log.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_t",
      "type": "topic",
      "url": "/documentation/os/os_log_t"
    },
    "doc://com.apple.os/documentation/os/os_log_with_type": {
      "abstract": [
        {
          "text": "Sends a message at a specific logging level, such as default, info, debug, error, or fault, to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_with_type"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_with_type",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_with_type",
      "type": "topic",
      "url": "/documentation/os/os_log_with_type"
    },
    "doc://com.apple.os/documentation/os/os_signpost_enabled": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether signposts are in an enabled state for the specified log.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_signpost_enabled"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_enabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_signpost_enabled",
      "type": "topic",
      "url": "/documentation/os/os_signpost_enabled"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-Standard-Log-Objects",
              "identifiers": [
                "doc://com.apple.os/documentation/os/OS_LOG_DEFAULT",
                "doc://com.apple.os/documentation/os/OS_LOG_DISABLED"
              ],
              "title": "Getting the Standard Log Objects"
            },
            {
              "anchor": "Creating-a-Log-Object",
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_log_create"
              ],
              "title": "Creating a Log Object"
            },
            {
              "anchor": "Getting-Log-Configuration",
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_log_info_enabled",
                "doc://com.apple.os/documentation/os/os_log_debug_enabled",
                "doc://com.apple.os/documentation/os/OSLog/isEnabled(type:)",
                "doc://com.apple.os/documentation/os/os_signpost_enabled"
              ],
              "title": "Getting Log Configuration"
            },
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_log_t"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Log-Messages",
              "generated": true,
              "identifiers": [
                "doc://com.apple.os/documentation/os/message-argument-formatters",
                "doc://com.apple.os/documentation/os/legacy-logging-symbols",
                "doc://com.apple.os/documentation/os/os_log_with_type",
                "doc://com.apple.os/documentation/os/OSLogType",
                "doc://com.apple.os/documentation/os/os_log",
                "doc://com.apple.os/documentation/os/os_log_info",
                "doc://com.apple.os/documentation/os/os_log_debug",
                "doc://com.apple.os/documentation/os/os_log_error",
                "doc://com.apple.os/documentation/os/os_log_fault"
              ],
              "title": "Log Messages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSLog~1isEnabled(type:)/title",
          "value": "os_log_type_enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSLog~1isEnabled(type:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_log_type_enabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSLogType/title",
          "value": "os_log_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSLogType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_log_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSLogType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "os_log_type_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/os/os-log-t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/os/os-log-t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
