{
  "abstract": [
    {
      "text": "Flags the current activity as a breadcrumb, to signify an interesting event.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.os/documentation/os/os_activity_label_useraction",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.os/documentation/os"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.os/documentation/os/os_activity_set_breadcrumb"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@os_activity_set_breadcrumb",
    "fragments": [
      {
        "kind": "identifier",
        "text": "os_activity_set_breadcrumb"
      }
    ],
    "modules": [
      {
        "name": "os"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "os_activity_set_breadcrumb"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Macro",
    "symbolKind": "macro",
    "title": "os_activity_set_breadcrumb"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "#define"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "os_activity_set_breadcrumb"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "internalParam",
              "text": "name"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A label that describes the breadcrumb.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "name"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use breadcrumbs to track interactions that span across multiple activities. Keep in mind that not all activities are interesting events.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This function can only be called once per activity;  subsequent calls are ignored.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.os/documentation/os": {
      "abstract": [
        {
          "text": "Coordinate the scheduling and synchronization of your app’s tasks, and log information to the console to diagnose issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os",
      "kind": "symbol",
      "role": "collection",
      "title": "os",
      "type": "topic",
      "url": "/documentation/os"
    },
    "doc://com.apple.os/documentation/os/OS_TRACE_TYPE_DEBUG": {
      "abstract": [
        {
          "text": "Trace messages that occur when a debugger is attached.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_TRACE_TYPE_DEBUG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_TRACE_TYPE_DEBUG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_TRACE_TYPE_DEBUG"
        }
      ],
      "role": "symbol",
      "title": "OS_TRACE_TYPE_DEBUG",
      "type": "topic",
      "url": "/documentation/os/os_trace_type_debug"
    },
    "doc://com.apple.os/documentation/os/OS_TRACE_TYPE_INFO": {
      "abstract": [
        {
          "text": "Trace messages that occur when a debugger is attached and additional info is requested.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_TRACE_TYPE_INFO"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_TRACE_TYPE_INFO",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_TRACE_TYPE_INFO"
        }
      ],
      "role": "symbol",
      "title": "OS_TRACE_TYPE_INFO",
      "type": "topic",
      "url": "/documentation/os/os_trace_type_info"
    },
    "doc://com.apple.os/documentation/os/OS_TRACE_TYPE_RELEASE": {
      "abstract": [
        {
          "text": "Trace messages to be captured on your app when instealled on a user’s device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OS_TRACE_TYPE_RELEASE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_TRACE_TYPE_RELEASE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OS_TRACE_TYPE_RELEASE"
        }
      ],
      "role": "symbol",
      "title": "OS_TRACE_TYPE_RELEASE",
      "type": "topic",
      "url": "/documentation/os/os_trace_type_release"
    },
    "doc://com.apple.os/documentation/os/os_activity_label_useraction": {
      "abstract": [
        {
          "text": "Label an activity that is auto-generated by AppKit or UIKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_label_useraction"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_label_useraction",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_label_useraction",
      "type": "topic",
      "url": "/documentation/os/os_activity_label_useraction"
    },
    "doc://com.apple.os/documentation/os/os_activity_set_breadcrumb": {
      "abstract": [
        {
          "text": "Flags the current activity as a breadcrumb, to signify an interesting event.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_set_breadcrumb"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_set_breadcrumb",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_set_breadcrumb",
      "type": "topic",
      "url": "/documentation/os/os_activity_set_breadcrumb"
    },
    "doc://com.apple.os/documentation/os/os_activity_start": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_start"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_start",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_start",
      "type": "topic",
      "url": "/documentation/os/os_activity_start"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Macros",
      "generated": true,
      "identifiers": [
        "doc://com.apple.os/documentation/os/os_activity_start",
        "doc://com.apple.os/documentation/os/OS_TRACE_TYPE_DEBUG",
        "doc://com.apple.os/documentation/os/OS_TRACE_TYPE_INFO",
        "doc://com.apple.os/documentation/os/OS_TRACE_TYPE_RELEASE"
      ],
      "title": "Deprecated Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_TRACE_TYPE_DEBUG/title",
          "value": "OS_TRACE_TYPE_DEBUG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_TRACE_TYPE_DEBUG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_TRACE_TYPE_DEBUG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_TRACE_TYPE_RELEASE/title",
          "value": "OS_TRACE_TYPE_RELEASE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_TRACE_TYPE_RELEASE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_TRACE_TYPE_RELEASE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_TRACE_TYPE_INFO/title",
          "value": "OS_TRACE_TYPE_INFO"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OS_TRACE_TYPE_INFO/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "OS_TRACE_TYPE_INFO"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/os/os_activity_set_breadcrumb"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
