{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Breadcrumbs are deprecated, with no direct replacement. Use logging instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.os/documentation/os"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.os/documentation/os/os_breadcrumb_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@os_breadcrumb_t",
    "fragments": [
      {
        "kind": "identifier",
        "text": "os_breadcrumb_t"
      }
    ],
    "modules": [
      {
        "name": "os"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "os_breadcrumb_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.12",
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "3.0",
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "os_breadcrumb_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint32_t",
              "text": "uint32_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "os_breadcrumb_t"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.os/documentation/os": {
      "abstract": [
        {
          "text": "Coordinate the scheduling and synchronization of your app’s tasks, and log information to the console to diagnose issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os",
      "kind": "symbol",
      "role": "collection",
      "title": "os",
      "type": "topic",
      "url": "/documentation/os"
    },
    "doc://com.apple.os/documentation/os/os_breadcrumb_t": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_breadcrumb_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_breadcrumb_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_breadcrumb_t",
      "type": "topic",
      "url": "/documentation/os/os_breadcrumb_t"
    },
    "doc://com.apple.os/documentation/os/os_trace_payload_object_t": {
      "abstract": [
        {
          "text": "A pointer to a trace payload object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "os_trace_payload_object_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_trace_payload_object_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "os_trace_payload_object_t"
        }
      ],
      "role": "symbol",
      "title": "os_trace_payload_object_t",
      "type": "topic",
      "url": "/documentation/os/os_trace_payload_object_t"
    },
    "doc://com.apple.os/documentation/os/os_trace_payload_t": {
      "abstract": [
        {
          "text": "A pointer to a trace payload.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_trace_payload_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_trace_payload_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_trace_payload_t",
      "type": "topic",
      "url": "/documentation/os/os_trace_payload_t"
    },
    "doc://com.externally.resolved.symbol/c:@T@uint32_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uint32_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint32_t",
      "type": "topic",
      "url": "/documentation/kernel/uint32_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Type-Aliases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.os/documentation/os/os_trace_payload_t",
        "doc://com.apple.os/documentation/os/os_trace_payload_object_t"
      ],
      "title": "Deprecated Type Aliases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_trace_payload_object_t/title",
          "value": "os_trace_payload_object_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_trace_payload_object_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_trace_payload_object_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_trace_payload_object_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "os_trace_payload_object_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/os/os_breadcrumb_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
