{
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.os/documentation/os/os_log_debug_enabled",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.os/documentation/os"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.os/documentation/os/os_log_is_debug_enabled"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@os_log_is_debug_enabled",
    "fragments": [
      {
        "kind": "identifier",
        "text": "os_log_is_debug_enabled"
      }
    ],
    "modules": [
      {
        "name": "os"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "os_log_is_debug_enabled"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.12",
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "3.0",
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "os_log_is_debug_enabled"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:b",
              "text": "bool"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "os_log_is_debug_enabled"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.os/documentation/os/os_log_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@os_log_t",
              "text": "os_log_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "log"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.os/documentation/os": {
      "abstract": [
        {
          "text": "Coordinate the scheduling and synchronization of your app’s tasks, and log information to the console to diagnose issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os",
      "kind": "symbol",
      "role": "collection",
      "title": "os",
      "type": "topic",
      "url": "/documentation/os"
    },
    "doc://com.apple.os/documentation/os/os_activity_end": {
      "abstract": [
        {
          "text": "Ends the specified activity on the current thread.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_end"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_end",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_end",
      "type": "topic",
      "url": "/documentation/os/os_activity_end"
    },
    "doc://com.apple.os/documentation/os/os_activity_get_active": {
      "abstract": [
        {
          "text": "Returns the stack of nested activities associated with the current thread.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_activity_get_active"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_activity_get_active",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_activity_get_active",
      "type": "topic",
      "url": "/documentation/os/os_activity_get_active"
    },
    "doc://com.apple.os/documentation/os/os_log_debug_enabled": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether debug-level logging is in an enabled state for a specified log object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_debug_enabled"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_debug_enabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_debug_enabled",
      "type": "topic",
      "url": "/documentation/os/os_log_debug_enabled"
    },
    "doc://com.apple.os/documentation/os/os_log_is_debug_enabled": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_is_debug_enabled"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_is_debug_enabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_is_debug_enabled",
      "type": "topic",
      "url": "/documentation/os/os_log_is_debug_enabled"
    },
    "doc://com.apple.os/documentation/os/os_log_is_enabled": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_is_enabled"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_is_enabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_is_enabled",
      "type": "topic",
      "url": "/documentation/os/os_log_is_enabled"
    },
    "doc://com.apple.os/documentation/os/os_log_t": {
      "abstract": [
        {
          "text": "A log object that you pass to logging functions to send messages to that log.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_t",
      "type": "topic",
      "url": "/documentation/os/os_log_t"
    },
    "doc://com.apple.os/documentation/os/os_trace_debug_enabled()": {
      "abstract": [
        {
          "text": "Returns whether debug level trace information is enabled.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "os_trace_debug_enabled"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_trace_debug_enabled()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "os_trace_debug_enabled"
        }
      ],
      "role": "symbol",
      "title": "os_trace_debug_enabled()",
      "type": "topic",
      "url": "/documentation/os/os_trace_debug_enabled()"
    },
    "doc://com.apple.os/documentation/os/os_trace_info_enabled()": {
      "abstract": [
        {
          "text": "Returns whether info level trace information is enabled.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "os_trace_info_enabled"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_trace_info_enabled()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "os_trace_info_enabled"
        }
      ],
      "role": "symbol",
      "title": "os_trace_info_enabled()",
      "type": "topic",
      "url": "/documentation/os/os_trace_info_enabled()"
    },
    "doc://com.apple.os/documentation/os/os_trace_type_enabled(_:)": {
      "abstract": [
        {
          "text": "Returns whether the specified info level trace information is enabled.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "os_trace_type_enabled"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_trace_type_enabled(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "os_trace_type_enabled"
        }
      ],
      "role": "symbol",
      "title": "os_trace_type_enabled(_:)",
      "type": "topic",
      "url": "/documentation/os/os_trace_type_enabled(_:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.os/documentation/os/os_log_is_enabled",
        "doc://com.apple.os/documentation/os/os_activity_get_active",
        "doc://com.apple.os/documentation/os/os_activity_end",
        "doc://com.apple.os/documentation/os/os_trace_debug_enabled()",
        "doc://com.apple.os/documentation/os/os_trace_info_enabled()",
        "doc://com.apple.os/documentation/os/os_trace_type_enabled(_:)"
      ],
      "title": "Deprecated Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_trace_info_enabled()/title",
          "value": "os_trace_info_enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_trace_info_enabled()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_trace_info_enabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_trace_type_enabled(_:)/title",
          "value": "os_trace_type_enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_trace_type_enabled(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_trace_type_enabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_trace_debug_enabled()/title",
          "value": "os_trace_debug_enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_trace_debug_enabled()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_trace_debug_enabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/os/os_log_is_debug_enabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
