{
  "abstract": [
    {
      "text": "An identifier you use to distinguish between signposts that have the same name and destination log.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.os/documentation/os"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.os/documentation/os/os_signpost_id_t"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@os_signpost_id_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "os_signpost_id_t"
      }
    ],
    "modules": [
      {
        "name": "os"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "os_signpost_id_t"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "os_signpost_id_t"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "os_signpost_id_t"
            },
            {
              "kind": "text",
              "text": " = "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt64V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt64V",
              "text": "UInt64"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Multiple intervals with matching log objects and interval names can be in-flight simultaneously. In order for data-processing tools to correctly match the beginning and end of an interval, you need to identify each interval with a unique signpost identifier. Use the first strategy in the list below that matches your use case:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you can guarantee that intervals with the same log and name can never overlap in time, specify ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.os/documentation/os/OS_SIGNPOST_ID_EXCLUSIVE",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " as the signpost ID.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you already have your own integer data that can uniquely identify each instance of the task being measured, cast the data from a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/kernel/uint64_t",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " value directly to a ",
                      "type": "text"
                    },
                    {
                      "code": "os_signpost_id_t",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". The value must not match one of the predefined signpost values.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you have a pointer that can uniquely identify begin/end pairs (such as a pointer to a data object used by the code being measured), call ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.os/documentation/os/os_signpost_id_make_with_pointer",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". Don’t use this function for signposts that span process boundaries.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Otherwise, call ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.os/documentation/os/os_signpost_id_generate",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " each time you create a new pair of signposts to generate a unique value for that pair.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/kernel/uint64_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/kernel/uint64_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint64_t",
      "type": "topic",
      "url": "/documentation/kernel/uint64_t"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.os/documentation/os": {
      "abstract": [
        {
          "text": "Coordinate the scheduling and synchronization of your app’s tasks, and log information to the console to diagnose issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os",
      "kind": "symbol",
      "role": "collection",
      "title": "os",
      "type": "topic",
      "url": "/documentation/os"
    },
    "doc://com.apple.os/documentation/os/OSSignpostType": {
      "abstract": [
        {
          "text": "The different kinds of signpost.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSSignpostType"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSSignpostType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSignpostType"
        }
      ],
      "role": "symbol",
      "title": "OSSignpostType",
      "type": "topic",
      "url": "/documentation/os/ossignposttype"
    },
    "doc://com.apple.os/documentation/os/OSSignposter": {
      "abstract": [
        {
          "text": "An object for measuring task performance using the unified logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSSignposter"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSSignposter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSignposter"
        }
      ],
      "role": "symbol",
      "title": "OSSignposter",
      "type": "topic",
      "url": "/documentation/os/ossignposter"
    },
    "doc://com.apple.os/documentation/os/OS_SIGNPOST_ID_EXCLUSIVE": {
      "abstract": [
        {
          "text": "A signpost identifier that indicates no overlap among different signpost time intervals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_SIGNPOST_ID_EXCLUSIVE"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_SIGNPOST_ID_EXCLUSIVE",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_SIGNPOST_ID_EXCLUSIVE",
      "type": "topic",
      "url": "/documentation/os/os_signpost_id_exclusive"
    },
    "doc://com.apple.os/documentation/os/OS_SIGNPOST_ID_INVALID": {
      "abstract": [
        {
          "text": "A signpost identifier that indicates an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_SIGNPOST_ID_INVALID"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_SIGNPOST_ID_INVALID",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_SIGNPOST_ID_INVALID",
      "type": "topic",
      "url": "/documentation/os/os_signpost_id_invalid"
    },
    "doc://com.apple.os/documentation/os/OS_SIGNPOST_ID_NULL": {
      "abstract": [
        {
          "text": "The signpost identifier that represents a disabled signpost.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_SIGNPOST_ID_NULL"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_SIGNPOST_ID_NULL",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_SIGNPOST_ID_NULL",
      "type": "topic",
      "url": "/documentation/os/os_signpost_id_null"
    },
    "doc://com.apple.os/documentation/os/OS_SIGNPOST_TYPE_MASK": {
      "abstract": [
        {
          "text": "A value the system uses to create built-in signpost identifiers; don’t use directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_SIGNPOST_TYPE_MASK"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_SIGNPOST_TYPE_MASK",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_SIGNPOST_TYPE_MASK",
      "type": "topic",
      "url": "/documentation/os/os_signpost_type_mask"
    },
    "doc://com.apple.os/documentation/os/legacy-signpost-symbols": {
      "abstract": [
        {
          "text": "Migrate your code away from using these legacy symbols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/legacy-signpost-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Legacy Signpost Symbols",
      "type": "topic",
      "url": "/documentation/os/legacy-signpost-symbols"
    },
    "doc://com.apple.os/documentation/os/os_signpost_emit_with_type": {
      "abstract": [
        {
          "text": "Logs a point of interest in your code as a time interval or as an event for debugging performance in Instruments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_signpost_emit_with_type"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_emit_with_type",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_signpost_emit_with_type",
      "type": "topic",
      "url": "/documentation/os/os_signpost_emit_with_type"
    },
    "doc://com.apple.os/documentation/os/os_signpost_event_emit": {
      "abstract": [
        {
          "text": "Marks a point of interest in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_signpost_event_emit"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_event_emit",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_signpost_event_emit",
      "type": "topic",
      "url": "/documentation/os/os_signpost_event_emit"
    },
    "doc://com.apple.os/documentation/os/os_signpost_id_generate": {
      "abstract": [
        {
          "text": "Creates a signpost identifier that’s unique among signposts logged to a specified log.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_signpost_id_generate"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_id_generate",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_signpost_id_generate",
      "type": "topic",
      "url": "/documentation/os/os_signpost_id_generate"
    },
    "doc://com.apple.os/documentation/os/os_signpost_id_make_with_pointer": {
      "abstract": [
        {
          "text": "Creates a signpost identifier that’s unique among signposts logging to the specified log, using a pointer value to generate the unique value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_signpost_id_make_with_pointer"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_id_make_with_pointer",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_signpost_id_make_with_pointer",
      "type": "topic",
      "url": "/documentation/os/os_signpost_id_make_with_pointer"
    },
    "doc://com.apple.os/documentation/os/os_signpost_id_t": {
      "abstract": [
        {
          "text": "An identifier you use to distinguish between signposts that have the same name and destination log.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "os_signpost_id_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_id_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "os_signpost_id_t"
        }
      ],
      "role": "symbol",
      "title": "os_signpost_id_t",
      "type": "topic",
      "url": "/documentation/os/os_signpost_id_t"
    },
    "doc://com.apple.os/documentation/os/os_signpost_interval_begin": {
      "abstract": [
        {
          "text": "Marks the start of a time interval in your code using a signpost.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_signpost_interval_begin"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_interval_begin",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_signpost_interval_begin",
      "type": "topic",
      "url": "/documentation/os/os_signpost_interval_begin"
    },
    "doc://com.apple.os/documentation/os/os_signpost_interval_end": {
      "abstract": [
        {
          "text": "Marks the end of a time interval in your code using a signpost.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_signpost_interval_end"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_interval_end",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_signpost_interval_end",
      "type": "topic",
      "url": "/documentation/os/os_signpost_interval_end"
    },
    "doc://com.apple.os/documentation/os/recording-performance-data": {
      "abstract": [
        {
          "text": "Add signposts to record interesting time-based events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/recording-performance-data",
      "kind": "article",
      "role": "article",
      "title": "Recording Performance Data",
      "type": "topic",
      "url": "/documentation/os/recording-performance-data"
    },
    "doc://com.externally.resolved.symbol/c:@T@uint64_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uint64_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint64_t",
      "type": "topic",
      "url": "/documentation/kernel/uint64_t"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt64V": {
      "abstract": [
        {
          "text": "A 64-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt64V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt64",
      "type": "topic",
      "url": "/documentation/Swift/UInt64"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Measure-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.os/documentation/os/recording-performance-data",
        "doc://com.apple.os/documentation/os/OSSignposter",
        "doc://com.apple.os/documentation/os/legacy-signpost-symbols",
        "doc://com.apple.os/documentation/os/OSSignpostType"
      ],
      "title": "Measure Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "os_signpost_id_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_signpost_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "os_signpost_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.os/documentation/os"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Signpost-Identifier",
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_signpost_id_generate",
                "doc://com.apple.os/documentation/os/os_signpost_id_make_with_pointer"
              ],
              "title": "Creating a Signpost Identifier"
            },
            {
              "anchor": "Using-Built-in-Signpost-Identifiers",
              "identifiers": [
                "doc://com.apple.os/documentation/os/OS_SIGNPOST_ID_EXCLUSIVE",
                "doc://com.apple.os/documentation/os/OS_SIGNPOST_ID_INVALID",
                "doc://com.apple.os/documentation/os/OS_SIGNPOST_ID_NULL"
              ],
              "title": "Using Built-in Signpost Identifiers"
            },
            {
              "anchor": "Supporting-Types",
              "identifiers": [
                "doc://com.apple.os/documentation/os/OS_SIGNPOST_TYPE_MASK"
              ],
              "title": "Supporting Types"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Measure-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.os/documentation/os/recording-performance-data",
                "doc://com.apple.os/documentation/os/legacy-signpost-symbols",
                "doc://com.apple.os/documentation/os/os_signpost_emit_with_type",
                "doc://com.apple.os/documentation/os/OSSignpostType",
                "doc://com.apple.os/documentation/os/os_signpost_interval_begin",
                "doc://com.apple.os/documentation/os/os_signpost_interval_end",
                "doc://com.apple.os/documentation/os/os_signpost_event_emit"
              ],
              "title": "Measure Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@uint64_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint64_t",
                    "text": "uint64_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "os_signpost_id_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_signpost_id_t/title",
          "value": "os_signpost_id_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_signpost_id_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_signpost_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_signpost_id_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "os_signpost_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSSignpostType/title",
          "value": "os_signpost_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSSignpostType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_signpost_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSSignpostType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "os_signpost_type_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/os/os_signpost_id_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/os/os_signpost_id_t"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
