{
  "abstract": [
    {
      "text": "Marks a point of interest in time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.os/documentation/os"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.os/documentation/os/os_signpost_event_emit"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@os_signpost_event_emit",
    "fragments": [
      {
        "kind": "identifier",
        "text": "os_signpost_event_emit"
      }
    ],
    "modules": [
      {
        "name": "os"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "os_signpost_event_emit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Macro",
    "symbolKind": "macro",
    "title": "os_signpost_event_emit"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "#define"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "os_signpost_event_emit"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "internalParam",
              "text": "log"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "internalParam",
              "text": "event_id"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "internalParam",
              "text": "name"
            },
            {
              "kind": "text",
              "text": ", ...)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The log that provides the subsystem and category to use. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.os/documentation/os/os_log_create",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "log"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The event’s identifier.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "event_id"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The event’s name.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "name"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An optional format string. If you provide the string, you must follow it with any required arguments in the order that they appear in the string.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "…"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function is equivalent to calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.os/documentation/os/os_signpost_emit_with_type",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with a type of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.os/documentation/os/os_signpost_type_t/OS_SIGNPOST_EVENT",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.os/documentation/os": {
      "abstract": [
        {
          "text": "Coordinate the scheduling and synchronization of your app’s tasks, and log information to the console to diagnose issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os",
      "kind": "symbol",
      "role": "collection",
      "title": "os",
      "type": "topic",
      "url": "/documentation/os"
    },
    "doc://com.apple.os/documentation/os/OSSignpostType": {
      "abstract": [
        {
          "text": "The different kinds of signpost.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSSignpostType"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSSignpostType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSignpostType"
        }
      ],
      "role": "symbol",
      "title": "OSSignpostType",
      "type": "topic",
      "url": "/documentation/os/ossignposttype"
    },
    "doc://com.apple.os/documentation/os/legacy-signpost-symbols": {
      "abstract": [
        {
          "text": "Migrate your code away from using these legacy symbols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/legacy-signpost-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Legacy Signpost Symbols",
      "type": "topic",
      "url": "/documentation/os/legacy-signpost-symbols"
    },
    "doc://com.apple.os/documentation/os/os_log_create": {
      "abstract": [
        {
          "text": "Creates a custom log object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_create"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_create",
      "type": "topic",
      "url": "/documentation/os/os_log_create"
    },
    "doc://com.apple.os/documentation/os/os_signpost_emit_with_type": {
      "abstract": [
        {
          "text": "Logs a point of interest in your code as a time interval or as an event for debugging performance in Instruments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_signpost_emit_with_type"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_emit_with_type",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_signpost_emit_with_type",
      "type": "topic",
      "url": "/documentation/os/os_signpost_emit_with_type"
    },
    "doc://com.apple.os/documentation/os/os_signpost_event_emit": {
      "abstract": [
        {
          "text": "Marks a point of interest in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_signpost_event_emit"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_event_emit",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_signpost_event_emit",
      "type": "topic",
      "url": "/documentation/os/os_signpost_event_emit"
    },
    "doc://com.apple.os/documentation/os/os_signpost_id_t": {
      "abstract": [
        {
          "text": "An identifier you use to distinguish between signposts that have the same name and destination log.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "os_signpost_id_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_id_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "os_signpost_id_t"
        }
      ],
      "role": "symbol",
      "title": "os_signpost_id_t",
      "type": "topic",
      "url": "/documentation/os/os_signpost_id_t"
    },
    "doc://com.apple.os/documentation/os/os_signpost_interval_begin": {
      "abstract": [
        {
          "text": "Marks the start of a time interval in your code using a signpost.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_signpost_interval_begin"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_interval_begin",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_signpost_interval_begin",
      "type": "topic",
      "url": "/documentation/os/os_signpost_interval_begin"
    },
    "doc://com.apple.os/documentation/os/os_signpost_interval_end": {
      "abstract": [
        {
          "text": "Marks the end of a time interval in your code using a signpost.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_signpost_interval_end"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_interval_end",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_signpost_interval_end",
      "type": "topic",
      "url": "/documentation/os/os_signpost_interval_end"
    },
    "doc://com.apple.os/documentation/os/os_signpost_type_t/OS_SIGNPOST_EVENT": {
      "abstract": [
        {
          "text": "A signpost that marks an event in your code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_SIGNPOST_EVENT"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_type_t/OS_SIGNPOST_EVENT",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_SIGNPOST_EVENT",
      "type": "topic",
      "url": "/documentation/os/os_signpost_type_t/os_signpost_event"
    },
    "doc://com.apple.os/documentation/os/recording-performance-data": {
      "abstract": [
        {
          "text": "Add signposts to record interesting time-based events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/recording-performance-data",
      "kind": "article",
      "role": "article",
      "title": "Recording Performance Data",
      "type": "topic",
      "url": "/documentation/os/recording-performance-data"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Measure-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.os/documentation/os/recording-performance-data",
        "doc://com.apple.os/documentation/os/legacy-signpost-symbols",
        "doc://com.apple.os/documentation/os/os_signpost_emit_with_type",
        "doc://com.apple.os/documentation/os/OSSignpostType",
        "doc://com.apple.os/documentation/os/os_signpost_interval_begin",
        "doc://com.apple.os/documentation/os/os_signpost_interval_end",
        "doc://com.apple.os/documentation/os/os_signpost_id_t"
      ],
      "title": "Measure Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_signpost_id_t/title",
          "value": "os_signpost_id_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_signpost_id_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_signpost_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_signpost_id_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "os_signpost_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSSignpostType/title",
          "value": "os_signpost_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSSignpostType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_signpost_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSSignpostType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "os_signpost_type_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/os/os_signpost_event_emit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
