{
  "abstract": [
    {
      "text": "The various log levels that the unified logging system provides.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.os/documentation/os"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.os/documentation/os/OSLogType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@os_log_type_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "OSLogType"
      }
    ],
    "modules": [
      {
        "name": "os"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "OSLogType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "OSLogType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "OSLogType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A log level controls how and when the system writes a message to the unified logging system. To write a message with a specific log level, create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.os/documentation/os/Logger",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and call its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.os/documentation/os/Logger/log(level:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. Alternatively, call the method that corresponds to the desired log level, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.os/documentation/os/Logger/debug(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.os/documentation/os/Logger/fault(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.os/documentation/os": {
      "abstract": [
        {
          "text": "Coordinate the scheduling and synchronization of your app’s tasks, and log information to the console to diagnose issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os",
      "kind": "symbol",
      "role": "collection",
      "title": "os",
      "type": "topic",
      "url": "/documentation/os"
    },
    "doc://com.apple.os/documentation/os/Logger": {
      "abstract": [
        {
          "text": "An object for writing interpolated string messages to the unified logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Logger"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/Logger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Logger"
        }
      ],
      "role": "symbol",
      "title": "Logger",
      "type": "topic",
      "url": "/documentation/os/logger"
    },
    "doc://com.apple.os/documentation/os/Logger/debug(_:)": {
      "abstract": [
        {
          "text": "Writes a debug message to the log.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debug"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:2os12OSLogMessageV",
          "text": "OSLogMessage"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/Logger/debug(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "debug(_:)",
      "type": "topic",
      "url": "/documentation/os/logger/debug(_:)"
    },
    "doc://com.apple.os/documentation/os/Logger/fault(_:)": {
      "abstract": [
        {
          "text": "Writes a message to the log about a bug that occurs when your app executes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fault"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:2os12OSLogMessageV",
          "text": "OSLogMessage"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/Logger/fault(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "fault(_:)",
      "type": "topic",
      "url": "/documentation/os/logger/fault(_:)"
    },
    "doc://com.apple.os/documentation/os/Logger/log(level:_:)": {
      "abstract": [
        {
          "text": "Writes a message to the log using the specified log type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "log"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "level"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@os_log_type_t",
          "text": "OSLogType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:2os12OSLogMessageV",
          "text": "OSLogMessage"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/Logger/log(level:_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "log(level:_:)",
      "type": "topic",
      "url": "/documentation/os/logger/log(level:_:)"
    },
    "doc://com.apple.os/documentation/os/OSLogType": {
      "abstract": [
        {
          "text": "The various log levels that the unified logging system provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSLogType"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSLogType"
        }
      ],
      "role": "symbol",
      "title": "OSLogType",
      "type": "topic",
      "url": "/documentation/os/oslogtype"
    },
    "doc://com.apple.os/documentation/os/OSLogType/debug": {
      "abstract": [
        {
          "text": "The debug log level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debug"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@os_log_type_t",
          "text": "OSLogType"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogType/debug",
      "kind": "symbol",
      "role": "symbol",
      "title": "debug",
      "type": "topic",
      "url": "/documentation/os/oslogtype/debug"
    },
    "doc://com.apple.os/documentation/os/OSLogType/default": {
      "abstract": [
        {
          "text": "The default log level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@os_log_type_t",
          "text": "OSLogType"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogType/default",
      "kind": "symbol",
      "role": "symbol",
      "title": "default",
      "type": "topic",
      "url": "/documentation/os/oslogtype/default"
    },
    "doc://com.apple.os/documentation/os/OSLogType/error": {
      "abstract": [
        {
          "text": "The error log level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@os_log_type_t",
          "text": "OSLogType"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogType/error",
      "kind": "symbol",
      "role": "symbol",
      "title": "error",
      "type": "topic",
      "url": "/documentation/os/oslogtype/error"
    },
    "doc://com.apple.os/documentation/os/OSLogType/fault": {
      "abstract": [
        {
          "text": "The fault log level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@os_log_type_t",
          "text": "OSLogType"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogType/fault",
      "kind": "symbol",
      "role": "symbol",
      "title": "fault",
      "type": "topic",
      "url": "/documentation/os/oslogtype/fault"
    },
    "doc://com.apple.os/documentation/os/OSLogType/info": {
      "abstract": [
        {
          "text": "The informative log level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "info"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@os_log_type_t",
          "text": "OSLogType"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogType/info",
      "kind": "symbol",
      "role": "symbol",
      "title": "info",
      "type": "topic",
      "url": "/documentation/os/oslogtype/info"
    },
    "doc://com.apple.os/documentation/os/OSLogType/init(_:)": {
      "abstract": [
        {
          "text": "Creates a log type from the specified value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogType/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/os/oslogtype/init(_:)"
    },
    "doc://com.apple.os/documentation/os/OSLogType/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a log type from the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/os/oslogtype/init(rawvalue:)"
    },
    "doc://com.apple.os/documentation/os/OSLogType/rawValue": {
      "abstract": [
        {
          "text": "The log type’s raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSLogType/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/os/oslogtype/rawvalue"
    },
    "doc://com.apple.os/documentation/os/legacy-logging-symbols": {
      "abstract": [
        {
          "text": "Migrate your code away from using these legacy symbols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/legacy-logging-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Legacy Logging Symbols",
      "type": "topic",
      "url": "/documentation/os/legacy-logging-symbols"
    },
    "doc://com.apple.os/documentation/os/message-argument-formatters": {
      "abstract": [
        {
          "text": "Manage the privacy and presentation of the message’s interpolated values using type-aware formatters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/message-argument-formatters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Message Argument Formatters",
      "type": "topic",
      "url": "/documentation/os/message-argument-formatters"
    },
    "doc://com.apple.os/documentation/os/os-log-t": {
      "abstract": [
        {
          "text": "A log object that you pass to logging functions to send messages to that log.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os-log-t",
      "kind": "article",
      "role": "collectionGroup",
      "title": "os_log_t",
      "type": "topic",
      "url": "/documentation/os/os-log-t"
    },
    "doc://com.apple.os/documentation/os/os_log": {
      "abstract": [
        {
          "text": "Sends a default-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log",
      "type": "topic",
      "url": "/documentation/os/os_log"
    },
    "doc://com.apple.os/documentation/os/os_log_debug": {
      "abstract": [
        {
          "text": "Sends a debug-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_debug"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_debug",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_debug",
      "type": "topic",
      "url": "/documentation/os/os_log_debug"
    },
    "doc://com.apple.os/documentation/os/os_log_error": {
      "abstract": [
        {
          "text": "Sends an error-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_error"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_error",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_error",
      "type": "topic",
      "url": "/documentation/os/os_log_error"
    },
    "doc://com.apple.os/documentation/os/os_log_fault": {
      "abstract": [
        {
          "text": "Sends a fault-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_fault"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_fault",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_fault",
      "type": "topic",
      "url": "/documentation/os/os_log_fault"
    },
    "doc://com.apple.os/documentation/os/os_log_info": {
      "abstract": [
        {
          "text": "Sends an info-level message to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_info"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_info",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_info",
      "type": "topic",
      "url": "/documentation/os/os_log_info"
    },
    "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_DEBUG": {
      "abstract": [
        {
          "text": "The debug log level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_LOG_TYPE_DEBUG"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_DEBUG",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_LOG_TYPE_DEBUG",
      "type": "topic",
      "url": "/documentation/os/os_log_type_t/os_log_type_debug"
    },
    "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_DEFAULT": {
      "abstract": [
        {
          "text": "The default log level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_LOG_TYPE_DEFAULT"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_DEFAULT",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_LOG_TYPE_DEFAULT",
      "type": "topic",
      "url": "/documentation/os/os_log_type_t/os_log_type_default"
    },
    "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_ERROR": {
      "abstract": [
        {
          "text": "The error log level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_LOG_TYPE_ERROR"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_ERROR",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_LOG_TYPE_ERROR",
      "type": "topic",
      "url": "/documentation/os/os_log_type_t/os_log_type_error"
    },
    "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_FAULT": {
      "abstract": [
        {
          "text": "The fault log level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_LOG_TYPE_FAULT"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_FAULT",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_LOG_TYPE_FAULT",
      "type": "topic",
      "url": "/documentation/os/os_log_type_t/os_log_type_fault"
    },
    "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_INFO": {
      "abstract": [
        {
          "text": "The informational log level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_LOG_TYPE_INFO"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_INFO",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_LOG_TYPE_INFO",
      "type": "topic",
      "url": "/documentation/os/os_log_type_t/os_log_type_info"
    },
    "doc://com.apple.os/documentation/os/os_log_with_type": {
      "abstract": [
        {
          "text": "Sends a message at a specific logging level, such as default, info, debug, error, or fault, to the logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_log_with_type"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_log_with_type",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_log_with_type",
      "type": "topic",
      "url": "/documentation/os/os_log_with_type"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Log-Messages",
      "generated": true,
      "identifiers": [
        "doc://com.apple.os/documentation/os/Logger",
        "doc://com.apple.os/documentation/os/message-argument-formatters"
      ],
      "title": "Log Messages"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-Log-Types",
      "identifiers": [
        "doc://com.apple.os/documentation/os/OSLogType/debug",
        "doc://com.apple.os/documentation/os/OSLogType/info",
        "doc://com.apple.os/documentation/os/OSLogType/default",
        "doc://com.apple.os/documentation/os/OSLogType/error",
        "doc://com.apple.os/documentation/os/OSLogType/fault"
      ],
      "title": "Getting Log Types"
    },
    {
      "anchor": "Creating-a-Log-Type",
      "identifiers": [
        "doc://com.apple.os/documentation/os/OSLogType/init(_:)",
        "doc://com.apple.os/documentation/os/OSLogType/init(rawValue:)"
      ],
      "title": "Creating a Log Type"
    },
    {
      "anchor": "Getting-the-Raw-Value",
      "identifiers": [
        "doc://com.apple.os/documentation/os/OSLogType/rawValue"
      ],
      "title": "Getting the Raw Value"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "os_log_type_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_log_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "os_log_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.os/documentation/os"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_DEBUG",
                "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_DEFAULT",
                "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_ERROR",
                "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_FAULT",
                "doc://com.apple.os/documentation/os/os_log_type_t/OS_LOG_TYPE_INFO"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Log-Messages",
              "generated": true,
              "identifiers": [
                "doc://com.apple.os/documentation/os/message-argument-formatters",
                "doc://com.apple.os/documentation/os/legacy-logging-symbols",
                "doc://com.apple.os/documentation/os/os-log-t",
                "doc://com.apple.os/documentation/os/os_log_with_type",
                "doc://com.apple.os/documentation/os/os_log",
                "doc://com.apple.os/documentation/os/os_log_info",
                "doc://com.apple.os/documentation/os/os_log_debug",
                "doc://com.apple.os/documentation/os/os_log_error",
                "doc://com.apple.os/documentation/os/os_log_fault"
              ],
              "title": "Log Messages"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "os_log_type_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSLogType/title",
          "value": "os_log_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSLogType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_log_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSLogType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "os_log_type_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/os/oslogtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/os/oslogtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
