{
  "abstract": [
    {
      "text": "The different kinds of signpost.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.os/documentation/os/OSSignposter",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.os/documentation/os"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.os/documentation/os/OSSignpostType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@EA@os_signpost_type_t",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "OSSignpostType"
      }
    ],
    "modules": [
      {
        "name": "os"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "OSSignpostType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "OSSignpostType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "OSSignpostType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.os/documentation/os": {
      "abstract": [
        {
          "text": "Coordinate the scheduling and synchronization of your app’s tasks, and log information to the console to diagnose issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os",
      "kind": "symbol",
      "role": "collection",
      "title": "os",
      "type": "topic",
      "url": "/documentation/os"
    },
    "doc://com.apple.os/documentation/os/OSSignpostType": {
      "abstract": [
        {
          "text": "The different kinds of signpost.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSSignpostType"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSSignpostType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSignpostType"
        }
      ],
      "role": "symbol",
      "title": "OSSignpostType",
      "type": "topic",
      "url": "/documentation/os/ossignposttype"
    },
    "doc://com.apple.os/documentation/os/OSSignpostType/begin": {
      "abstract": [
        {
          "text": "A signpost that marks the start of a time interval of interest in your code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "begin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@os_signpost_type_t",
          "text": "OSSignpostType"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSSignpostType/begin",
      "kind": "symbol",
      "role": "symbol",
      "title": "begin",
      "type": "topic",
      "url": "/documentation/os/ossignposttype/begin"
    },
    "doc://com.apple.os/documentation/os/OSSignpostType/end": {
      "abstract": [
        {
          "text": "A signpost that marks the end of a time interval of interest in your code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "end"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@os_signpost_type_t",
          "text": "OSSignpostType"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSSignpostType/end",
      "kind": "symbol",
      "role": "symbol",
      "title": "end",
      "type": "topic",
      "url": "/documentation/os/ossignposttype/end"
    },
    "doc://com.apple.os/documentation/os/OSSignpostType/event": {
      "abstract": [
        {
          "text": "A signpost that marks an event in your code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "event"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@os_signpost_type_t",
          "text": "OSSignpostType"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSSignpostType/event",
      "kind": "symbol",
      "role": "symbol",
      "title": "event",
      "type": "topic",
      "url": "/documentation/os/ossignposttype/event"
    },
    "doc://com.apple.os/documentation/os/OSSignpostType/init(_:)": {
      "abstract": [
        {
          "text": "Creates a signpost from a raw integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSSignpostType/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/os/ossignposttype/init(_:)"
    },
    "doc://com.apple.os/documentation/os/OSSignpostType/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a signpost from a raw integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSSignpostType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/os/ossignposttype/init(rawvalue:)"
    },
    "doc://com.apple.os/documentation/os/OSSignpostType/rawValue": {
      "abstract": [
        {
          "text": "An integer value that represents the role of a signpost.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSSignpostType/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/os/ossignposttype/rawvalue"
    },
    "doc://com.apple.os/documentation/os/OSSignposter": {
      "abstract": [
        {
          "text": "An object for measuring task performance using the unified logging system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OSSignposter"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OSSignposter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OSSignposter"
        }
      ],
      "role": "symbol",
      "title": "OSSignposter",
      "type": "topic",
      "url": "/documentation/os/ossignposter"
    },
    "doc://com.apple.os/documentation/os/legacy-signpost-symbols": {
      "abstract": [
        {
          "text": "Migrate your code away from using these legacy symbols.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/legacy-signpost-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Legacy Signpost Symbols",
      "type": "topic",
      "url": "/documentation/os/legacy-signpost-symbols"
    },
    "doc://com.apple.os/documentation/os/os_signpost_emit_with_type": {
      "abstract": [
        {
          "text": "Logs a point of interest in your code as a time interval or as an event for debugging performance in Instruments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_signpost_emit_with_type"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_emit_with_type",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_signpost_emit_with_type",
      "type": "topic",
      "url": "/documentation/os/os_signpost_emit_with_type"
    },
    "doc://com.apple.os/documentation/os/os_signpost_event_emit": {
      "abstract": [
        {
          "text": "Marks a point of interest in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_signpost_event_emit"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_event_emit",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_signpost_event_emit",
      "type": "topic",
      "url": "/documentation/os/os_signpost_event_emit"
    },
    "doc://com.apple.os/documentation/os/os_signpost_id_t": {
      "abstract": [
        {
          "text": "An identifier you use to distinguish between signposts that have the same name and destination log.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "os_signpost_id_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_id_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "os_signpost_id_t"
        }
      ],
      "role": "symbol",
      "title": "os_signpost_id_t",
      "type": "topic",
      "url": "/documentation/os/os_signpost_id_t"
    },
    "doc://com.apple.os/documentation/os/os_signpost_interval_begin": {
      "abstract": [
        {
          "text": "Marks the start of a time interval in your code using a signpost.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_signpost_interval_begin"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_interval_begin",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_signpost_interval_begin",
      "type": "topic",
      "url": "/documentation/os/os_signpost_interval_begin"
    },
    "doc://com.apple.os/documentation/os/os_signpost_interval_end": {
      "abstract": [
        {
          "text": "Marks the end of a time interval in your code using a signpost.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_signpost_interval_end"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_interval_end",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_signpost_interval_end",
      "type": "topic",
      "url": "/documentation/os/os_signpost_interval_end"
    },
    "doc://com.apple.os/documentation/os/os_signpost_type_t/OS_SIGNPOST_EVENT": {
      "abstract": [
        {
          "text": "A signpost that marks an event in your code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_SIGNPOST_EVENT"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_type_t/OS_SIGNPOST_EVENT",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_SIGNPOST_EVENT",
      "type": "topic",
      "url": "/documentation/os/os_signpost_type_t/os_signpost_event"
    },
    "doc://com.apple.os/documentation/os/os_signpost_type_t/OS_SIGNPOST_INTERVAL_BEGIN": {
      "abstract": [
        {
          "text": "A signpost that marks the start of a time interval of interest in your code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_SIGNPOST_INTERVAL_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_type_t/OS_SIGNPOST_INTERVAL_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_SIGNPOST_INTERVAL_BEGIN",
      "type": "topic",
      "url": "/documentation/os/os_signpost_type_t/os_signpost_interval_begin"
    },
    "doc://com.apple.os/documentation/os/os_signpost_type_t/OS_SIGNPOST_INTERVAL_END": {
      "abstract": [
        {
          "text": "A signpost that marks the end of a time interval of interest in your code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_SIGNPOST_INTERVAL_END"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_signpost_type_t/OS_SIGNPOST_INTERVAL_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_SIGNPOST_INTERVAL_END",
      "type": "topic",
      "url": "/documentation/os/os_signpost_type_t/os_signpost_interval_end"
    },
    "doc://com.apple.os/documentation/os/recording-performance-data": {
      "abstract": [
        {
          "text": "Add signposts to record interesting time-based events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/recording-performance-data",
      "kind": "article",
      "role": "article",
      "title": "Recording Performance Data",
      "type": "topic",
      "url": "/documentation/os/recording-performance-data"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Measure-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.os/documentation/os/recording-performance-data",
        "doc://com.apple.os/documentation/os/OSSignposter",
        "doc://com.apple.os/documentation/os/legacy-signpost-symbols",
        "doc://com.apple.os/documentation/os/os_signpost_id_t"
      ],
      "title": "Measure Events"
    }
  ],
  "topicSections": [
    {
      "anchor": "Specifying-Signpost-Types",
      "identifiers": [
        "doc://com.apple.os/documentation/os/OSSignpostType/begin",
        "doc://com.apple.os/documentation/os/OSSignpostType/end",
        "doc://com.apple.os/documentation/os/OSSignpostType/event"
      ],
      "title": "Specifying Signpost Types"
    },
    {
      "anchor": "Creating-Signpost-Types",
      "identifiers": [
        "doc://com.apple.os/documentation/os/OSSignpostType/init(rawValue:)",
        "doc://com.apple.os/documentation/os/OSSignpostType/init(_:)"
      ],
      "title": "Creating Signpost Types"
    },
    {
      "anchor": "Inspecting-Signpost-Types",
      "identifiers": [
        "doc://com.apple.os/documentation/os/OSSignpostType/rawValue"
      ],
      "title": "Inspecting Signpost Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "os_signpost_type_t"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_signpost_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "os_signpost_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.os/documentation/os"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_signpost_type_t/OS_SIGNPOST_EVENT",
                "doc://com.apple.os/documentation/os/os_signpost_type_t/OS_SIGNPOST_INTERVAL_BEGIN",
                "doc://com.apple.os/documentation/os/os_signpost_type_t/OS_SIGNPOST_INTERVAL_END"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Measure-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.os/documentation/os/recording-performance-data",
                "doc://com.apple.os/documentation/os/legacy-signpost-symbols",
                "doc://com.apple.os/documentation/os/os_signpost_emit_with_type",
                "doc://com.apple.os/documentation/os/os_signpost_interval_begin",
                "doc://com.apple.os/documentation/os/os_signpost_interval_end",
                "doc://com.apple.os/documentation/os/os_signpost_event_emit",
                "doc://com.apple.os/documentation/os/os_signpost_id_t"
              ],
              "title": "Measure Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "os_signpost_type_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.os/documentation/os/OSSignposter",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_signpost_id_t/title",
          "value": "os_signpost_id_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_signpost_id_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_signpost_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1os_signpost_id_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "os_signpost_id_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSSignpostType/title",
          "value": "os_signpost_type_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSSignpostType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "os_signpost_type_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.os~1documentation~1os~1OSSignpostType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "os_signpost_type_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/os/ossignposttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/os/ossignposttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
