{
  "abstract": [
    {
      "text": "Schedule one or more threads to run at regular intervals and before specific deadlines.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.os/documentation/os"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.os/documentation/os/workgroups"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "os"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Workgroups"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A workgroup manages one or more threads that work cooperatively toward a common goal. Use workgroups to coordinate the efforts of threads that handle real-time audio work. Registering threads with a workgroup helps the system direct work to the right system resources, and also helps it manage the competing needs of low-power consumption with maximum rendering output.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Apple-Silicon/porting-your-audio-code-to-apple-silicon": {
      "abstract": [
        {
          "text": "Eliminate issues in your audio-specific code when running on Apple silicon Mac computers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Apple-Silicon/porting-your-audio-code-to-apple-silicon",
      "kind": "article",
      "role": "article",
      "title": "Porting Your Audio Code to Apple Silicon",
      "type": "topic",
      "url": "/documentation/Apple-Silicon/porting-your-audio-code-to-apple-silicon"
    },
    "doc://com.apple.documentation/documentation/Apple-Silicon/tuning-your-code-s-performance-for-apple-silicon": {
      "abstract": [
        {
          "text": "Improve your code to get the best performance from both Apple silicon and Intel-based Mac computers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Apple-Silicon/tuning-your-code-s-performance-for-apple-silicon",
      "kind": "article",
      "role": "article",
      "title": "Tuning Your Code’s Performance for Apple Silicon",
      "type": "topic",
      "url": "/documentation/Apple-Silicon/tuning-your-code-s-performance-for-apple-silicon"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.os/documentation/os": {
      "abstract": [
        {
          "text": "Coordinate the scheduling and synchronization of your app’s tasks, and log information to the console to diagnose issues.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os",
      "kind": "symbol",
      "role": "collection",
      "title": "os",
      "type": "topic",
      "url": "/documentation/os"
    },
    "doc://com.apple.os/documentation/os/OS_object": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_object"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_object",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_object",
      "type": "topic",
      "url": "/documentation/os/os_object"
    },
    "doc://com.apple.os/documentation/os/OS_os_workgroup": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_os_workgroup"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_os_workgroup",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_os_workgroup",
      "type": "topic",
      "url": "/documentation/os/os_os_workgroup"
    },
    "doc://com.apple.os/documentation/os/OS_os_workgroup_interval-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_os_workgroup_interval"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_os_workgroup_interval-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_os_workgroup_interval",
      "type": "topic",
      "url": "/documentation/os/os_os_workgroup_interval-c.class"
    },
    "doc://com.apple.os/documentation/os/OS_os_workgroup_interval-c.protocol": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_os_workgroup_interval"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_os_workgroup_interval-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_os_workgroup_interval",
      "type": "topic",
      "url": "/documentation/os/os_os_workgroup_interval-c.protocol"
    },
    "doc://com.apple.os/documentation/os/OS_os_workgroup_parallel-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_os_workgroup_parallel"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_os_workgroup_parallel-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_os_workgroup_parallel",
      "type": "topic",
      "url": "/documentation/os/os_os_workgroup_parallel-c.class"
    },
    "doc://com.apple.os/documentation/os/OS_os_workgroup_parallel-c.protocol": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "OS_os_workgroup_parallel"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/OS_os_workgroup_parallel-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "OS_os_workgroup_parallel",
      "type": "topic",
      "url": "/documentation/os/os_os_workgroup_parallel-c.protocol"
    },
    "doc://com.apple.os/documentation/os/os_clockid_t": {
      "abstract": [
        {
          "text": "Options for how to specify time-specific values in an interval workgroup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_clockid_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_clockid_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_clockid_t",
      "type": "topic",
      "url": "/documentation/os/os_clockid_t"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_attr_t": {
      "abstract": [
        {
          "text": "An opaque structure for storing workgroup-related attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_attr_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_attr_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_attr_t",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_attr_t"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_cancel": {
      "abstract": [
        {
          "text": "Cancels and invalidates the specified workgroup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_cancel"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_cancel",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_cancel",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_cancel"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_copy_port": {
      "abstract": [
        {
          "text": "Returns the Mach port associated with the workgroup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_copy_port"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_copy_port",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_copy_port",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_copy_port"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_create_with_port": {
      "abstract": [
        {
          "text": "Creates a new workgroup that is bound to the workgroup with the specified Mach port.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_create_with_port"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_create_with_port",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_create_with_port",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_create_with_port"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_create_with_workgroup": {
      "abstract": [
        {
          "text": "Create a new workgroup that is bound to the specified workgroup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_create_with_workgroup"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_create_with_workgroup",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_create_with_workgroup",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_create_with_workgroup"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_get_working_arena": {
      "abstract": [
        {
          "text": "Retrieves the workgroup’s shared data, and the thread-specific index into that data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_get_working_arena"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_get_working_arena",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_get_working_arena",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_get_working_arena"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_index": {
      "abstract": [
        {
          "text": "A unique index that the workgroup assigns to its joined threads.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_index"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_index",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_index",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_index"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_interval_data_t": {
      "abstract": [
        {
          "text": "An opaque structure that contains additional configuration data for the interval workgroup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_interval_data_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_interval_data_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_interval_data_t",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_interval_data_t"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_interval_finish": {
      "abstract": [
        {
          "text": "Stops the current interval-based execution of the workgroup’s threads.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_interval_finish"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_interval_finish",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_interval_finish",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_interval_finish"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_interval_start": {
      "abstract": [
        {
          "text": "Starts the regular execution of the workgroup’s threads at the specified time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_interval_start"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_interval_start",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_interval_start",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_interval_start"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_interval_t": {
      "abstract": [
        {
          "text": "A workgroup object that supports the scheduling of threads on a repeating cadence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_interval_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_interval_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_interval_t",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_interval_t"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_interval_update": {
      "abstract": [
        {
          "text": "Schedules a new deadline for workgroup threads that run at regular intervals.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_interval_update"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_interval_update",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_interval_update",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_interval_update"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_join": {
      "abstract": [
        {
          "text": "Adds the current thread to the specified workgroup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_join"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_join",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_join",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_join"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_join_token_t": {
      "abstract": [
        {
          "text": "An opaque token that represents a connection between a thread and a workgroup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_join_token_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_join_token_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_join_token_t",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_join_token_t"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_leave": {
      "abstract": [
        {
          "text": "Removes the current thread from the workgroup it previously joined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_leave"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_leave",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_leave",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_leave"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_max_parallel_threads": {
      "abstract": [
        {
          "text": "Returns the maximum number of threads that the system recommends you add to the specified workgroup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_max_parallel_threads"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_max_parallel_threads",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_max_parallel_threads",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_max_parallel_threads"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_mpt_attr_t": {
      "abstract": [
        {
          "text": "An opaque structure containing attributes related to a request for the maximum number of parallel threads.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_mpt_attr_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_mpt_attr_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_mpt_attr_t",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_mpt_attr_t"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_parallel_create": {
      "abstract": [
        {
          "text": "Creates a new workgroup that manges threads working on a single task in parallel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_parallel_create"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_parallel_create",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_parallel_create",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_parallel_create"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_parallel_t": {
      "abstract": [
        {
          "text": "A workgroup object that supports the scheduling of threads that work in parallel to complete a task.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_parallel_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_parallel_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_parallel_t",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_parallel_t"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_set_working_arena": {
      "abstract": [
        {
          "text": "Distributes a block of managed memory to the threads of a workgroup.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_set_working_arena"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_set_working_arena",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_set_working_arena",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_set_working_arena"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_t": {
      "abstract": [
        {
          "text": "An opaque object representing a default workgroup in the current process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_t",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_t"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_testcancel": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the workgroup is canceled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_testcancel"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_testcancel",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_testcancel",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_testcancel"
    },
    "doc://com.apple.os/documentation/os/os_workgroup_working_arena_destructor_t": {
      "abstract": [
        {
          "text": "A function that deallocates a workgroup’s currently assigned shared memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "os_workgroup_working_arena_destructor_t"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/os_workgroup_working_arena_destructor_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "os_workgroup_working_arena_destructor_t",
      "type": "topic",
      "url": "/documentation/os/os_workgroup_working_arena_destructor_t"
    },
    "doc://com.apple.os/documentation/os/synchronization": {
      "abstract": [
        {
          "text": "Access low-level synchronization mechanisms to control state across threads.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.os/documentation/os/synchronization",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Synchronization",
      "type": "topic",
      "url": "/documentation/os/synchronization"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.documentation/documentation/Apple-Silicon/tuning-your-code-s-performance-for-apple-silicon"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Interval-Tasks",
      "identifiers": [
        "doc://com.apple.documentation/documentation/Apple-Silicon/porting-your-audio-code-to-apple-silicon"
      ],
      "title": "Interval Tasks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.documentation/documentation/Apple-Silicon/tuning-your-code-s-performance-for-apple-silicon"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Interval-Tasks",
              "identifiers": [
                "doc://com.apple.documentation/documentation/Apple-Silicon/porting-your-audio-code-to-apple-silicon",
                "doc://com.apple.os/documentation/os/os_workgroup_interval_start",
                "doc://com.apple.os/documentation/os/os_workgroup_interval_update",
                "doc://com.apple.os/documentation/os/os_workgroup_interval_finish",
                "doc://com.apple.os/documentation/os/os_workgroup_interval_t",
                "doc://com.apple.os/documentation/os/os_workgroup_interval_data_t",
                "doc://com.apple.os/documentation/os/os_clockid_t"
              ],
              "title": "Interval Tasks"
            },
            {
              "anchor": "Parallel",
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_workgroup_parallel_create",
                "doc://com.apple.os/documentation/os/os_workgroup_parallel_t"
              ],
              "title": "Parallel"
            },
            {
              "anchor": "Thread-Attachment",
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_workgroup_join",
                "doc://com.apple.os/documentation/os/os_workgroup_leave",
                "doc://com.apple.os/documentation/os/os_workgroup_join_token_t"
              ],
              "title": "Thread Attachment"
            },
            {
              "anchor": "Cancellation",
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_workgroup_cancel",
                "doc://com.apple.os/documentation/os/os_workgroup_testcancel"
              ],
              "title": "Cancellation"
            },
            {
              "anchor": "Workgroup-Configuration",
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_workgroup_max_parallel_threads",
                "doc://com.apple.os/documentation/os/os_workgroup_mpt_attr_t",
                "doc://com.apple.os/documentation/os/os_workgroup_set_working_arena",
                "doc://com.apple.os/documentation/os/os_workgroup_get_working_arena",
                "doc://com.apple.os/documentation/os/os_workgroup_index",
                "doc://com.apple.os/documentation/os/os_workgroup_working_arena_destructor_t"
              ],
              "title": "Workgroup Configuration"
            },
            {
              "anchor": "Common-Utilities",
              "identifiers": [
                "doc://com.apple.os/documentation/os/os_workgroup_create_with_workgroup",
                "doc://com.apple.os/documentation/os/os_workgroup_create_with_port",
                "doc://com.apple.os/documentation/os/os_workgroup_copy_port",
                "doc://com.apple.os/documentation/os/os_workgroup_t",
                "doc://com.apple.os/documentation/os/os_workgroup_attr_t"
              ],
              "title": "Common Utilities"
            },
            {
              "anchor": "Objective-C-Support",
              "identifiers": [
                "doc://com.apple.os/documentation/os/OS_os_workgroup_interval-c.class",
                "doc://com.apple.os/documentation/os/OS_os_workgroup_interval-c.protocol",
                "doc://com.apple.os/documentation/os/OS_os_workgroup",
                "doc://com.apple.os/documentation/os/OS_object"
              ],
              "title": "Objective-C Support"
            },
            {
              "anchor": "Internal-Structures",
              "identifiers": [
                "doc://com.apple.os/documentation/os/OS_os_workgroup_parallel-c.class",
                "doc://com.apple.os/documentation/os/OS_os_workgroup_parallel-c.protocol"
              ],
              "title": "Internal Structures"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Task-Management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.os/documentation/os/synchronization"
              ],
              "title": "Task Management"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/os/workgroups"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/os/workgroups"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
