{
  "abstract": [
    {
      "text": "Specifies a known store action to replace the initial ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/unknown",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " value specified for a given stencil attachment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setStencilStoreAction(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)MTLParallelRenderCommandEncoder(im)setStencilStoreAction:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setStencilStoreAction"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MTLStoreAction",
        "text": "MTLStoreAction"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setStencilStoreAction:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setStencilStoreAction(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setStencilStoreAction"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "storeAction"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MTLStoreAction",
              "text": "MTLStoreAction"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The desired store action for the stencil attachment. This value must not be ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/unknown",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "storeAction"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the store action for the given stencil attachment was set to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/unknown",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " when the parallel render command encoder was created, you must call this method to specify another store action before you call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandEncoder/endEncoding()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCommandEncoder/endEncoding()": {
      "abstract": [
        {
          "text": "Declares that all command generation from the encoder is completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endEncoding"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCommandEncoder/endEncoding()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endEncoding"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "endEncoding()",
      "type": "topic",
      "url": "/documentation/metal/mtlcommandencoder/endencoding()"
    },
    "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder": {
      "abstract": [
        {
          "text": "An object that splits up a single render pass so that it can be simultaneously encoded from multiple threads.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLParallelRenderCommandEncoder"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLParallelRenderCommandEncoder"
        }
      ],
      "role": "symbol",
      "title": "MTLParallelRenderCommandEncoder",
      "type": "topic",
      "url": "/documentation/metal/mtlparallelrendercommandencoder"
    },
    "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setColorStoreAction(_:index:)": {
      "abstract": [
        {
          "text": "Specifies a known store action to replace the initial ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/unknown",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " value specified for a given color attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setColorStoreAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLStoreAction",
          "text": "MTLStoreAction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "index"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setColorStoreAction(_:index:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setColorStoreAction:atIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setColorStoreAction(_:index:)",
      "type": "topic",
      "url": "/documentation/metal/mtlparallelrendercommandencoder/setcolorstoreaction(_:index:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setColorStoreActionOptions(_:index:)": {
      "abstract": [
        {
          "text": "Specifies known store action options for a given color attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setColorStoreActionOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLStoreActionOptions",
          "text": "MTLStoreActionOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "index"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setColorStoreActionOptions(_:index:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setColorStoreActionOptions:atIndex:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setColorStoreActionOptions(_:index:)",
      "type": "topic",
      "url": "/documentation/metal/mtlparallelrendercommandencoder/setcolorstoreactionoptions(_:index:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setDepthStoreAction(_:)": {
      "abstract": [
        {
          "text": "Specifies a known store action to replace the initial ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/unknown",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " value specified for a given depth attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDepthStoreAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLStoreAction",
          "text": "MTLStoreAction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setDepthStoreAction(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDepthStoreAction:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setDepthStoreAction(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtlparallelrendercommandencoder/setdepthstoreaction(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setDepthStoreActionOptions(_:)": {
      "abstract": [
        {
          "text": "Specifies known store action options for a given depth attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDepthStoreActionOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLStoreActionOptions",
          "text": "MTLStoreActionOptions"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setDepthStoreActionOptions(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDepthStoreActionOptions:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setDepthStoreActionOptions(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtlparallelrendercommandencoder/setdepthstoreactionoptions(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setStencilStoreAction(_:)": {
      "abstract": [
        {
          "text": "Specifies a known store action to replace the initial ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/unknown",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " value specified for a given stencil attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setStencilStoreAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLStoreAction",
          "text": "MTLStoreAction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setStencilStoreAction(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setStencilStoreAction:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setStencilStoreAction(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtlparallelrendercommandencoder/setstencilstoreaction(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setStencilStoreActionOptions(_:)": {
      "abstract": [
        {
          "text": "Specifies known store action options for a given stencil attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setStencilStoreActionOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLStoreActionOptions",
          "text": "MTLStoreActionOptions"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setStencilStoreActionOptions(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setStencilStoreActionOptions:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setStencilStoreActionOptions(_:)",
      "type": "topic",
      "url": "/documentation/metal/mtlparallelrendercommandencoder/setstencilstoreactionoptions(_:)"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStoreAction": {
      "abstract": [
        {
          "text": "Types of actions performed for an attachment at the end of a rendering pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLStoreAction"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLStoreAction"
        }
      ],
      "role": "symbol",
      "title": "MTLStoreAction",
      "type": "topic",
      "url": "/documentation/metal/mtlstoreaction"
    },
    "doc://com.apple.metal/documentation/Metal/MTLStoreAction/unknown": {
      "abstract": [
        {
          "text": "The app will specify the store action when it encodes the render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLStoreActionUnknown"
        }
      ],
      "role": "symbol",
      "title": "MTLStoreAction.unknown",
      "type": "topic",
      "url": "/documentation/metal/mtlstoreaction/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-Render-Pass-State",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setColorStoreAction(_:index:)",
        "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setColorStoreActionOptions(_:index:)",
        "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setDepthStoreAction(_:)",
        "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setDepthStoreActionOptions(_:)",
        "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setStencilStoreActionOptions(_:)"
      ],
      "title": "Setting Render Pass State"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setStencilStoreAction:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setStencilStoreAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-Render-Pass-State",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setColorStoreAction(_:index:)",
                "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setColorStoreActionOptions(_:index:)",
                "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setDepthStoreAction(_:)",
                "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setDepthStoreActionOptions(_:)",
                "doc://com.apple.metal/documentation/Metal/MTLParallelRenderCommandEncoder/setStencilStoreActionOptions(_:)"
              ],
              "title": "Setting Render Pass State"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setStencilStoreAction:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@MTLStoreAction",
                    "text": "MTLStoreAction"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "storeAction"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The desired store action for the stencil attachment. This value must not be ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.metal/documentation/Metal/MTLStoreAction/unknown",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "storeAction"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLParallelRenderCommandEncoder~1setColorStoreAction(_:index:)/title",
          "value": "setColorStoreAction:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLParallelRenderCommandEncoder~1setColorStoreAction(_:index:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setColorStoreAction:atIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLParallelRenderCommandEncoder~1setDepthStoreActionOptions(_:)/title",
          "value": "setDepthStoreActionOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLParallelRenderCommandEncoder~1setDepthStoreActionOptions(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDepthStoreActionOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLParallelRenderCommandEncoder~1setStencilStoreActionOptions(_:)/title",
          "value": "setStencilStoreActionOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLParallelRenderCommandEncoder~1setStencilStoreActionOptions(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setStencilStoreActionOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction~1unknown/title",
          "value": "MTLStoreActionUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStoreActionUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLParallelRenderCommandEncoder~1setDepthStoreAction(_:)/title",
          "value": "setDepthStoreAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLParallelRenderCommandEncoder~1setDepthStoreAction(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDepthStoreAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLParallelRenderCommandEncoder/title",
          "value": "MTLParallelRenderCommandEncoder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLParallelRenderCommandEncoder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLParallelRenderCommandEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLParallelRenderCommandEncoder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLParallelRenderCommandEncoder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction/title",
          "value": "MTLStoreAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStoreAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLStoreAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLStoreAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandEncoder~1endEncoding()/title",
          "value": "endEncoding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCommandEncoder~1endEncoding()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endEncoding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLParallelRenderCommandEncoder~1setColorStoreActionOptions(_:index:)/title",
          "value": "setColorStoreActionOptions:atIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLParallelRenderCommandEncoder~1setColorStoreActionOptions(_:index:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setColorStoreActionOptions:atIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLParallelRenderCommandEncoder~1setStencilStoreAction(_:)/title",
          "value": "setStencilStoreAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLParallelRenderCommandEncoder~1setStencilStoreAction(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setStencilStoreAction:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlparallelrendercommandencoder/setstencilstoreaction(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlparallelrendercommandencoder/setstencilstoreaction(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
