{
  "abstract": [
    {
      "text": "Inset border.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pdfkit/documentation/PDFKit",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle/inset"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PDFBorderStyle@kPDFBorderStyleInset",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "inset"
      }
    ],
    "modules": [
      {
        "name": "PDFKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kPDFBorderStyleInset"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PDFBorderStyle.inset"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "inset"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit": {
      "abstract": [
        {
          "text": "Display and manipulate PDF documents in your apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PDFKit",
      "type": "topic",
      "url": "/documentation/pdfkit"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle": {
      "abstract": [
        {
          "text": "PDF Kit annotation borders may have the following styles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PDFBorderStyle"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFBorderStyle"
        }
      ],
      "role": "symbol",
      "title": "PDFBorderStyle",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfborderstyle"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle/beveled": {
      "abstract": [
        {
          "text": "Beveled border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beveled"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle/beveled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFBorderStyleBeveled"
        }
      ],
      "role": "symbol",
      "title": "PDFBorderStyle.beveled",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfborderstyle/beveled"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle/dashed": {
      "abstract": [
        {
          "text": "Dashed border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dashed"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle/dashed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFBorderStyleDashed"
        }
      ],
      "role": "symbol",
      "title": "PDFBorderStyle.dashed",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfborderstyle/dashed"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle/inset": {
      "abstract": [
        {
          "text": "Inset border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inset"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle/inset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFBorderStyleInset"
        }
      ],
      "role": "symbol",
      "title": "PDFBorderStyle.inset",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfborderstyle/inset"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle/solid": {
      "abstract": [
        {
          "text": "Solid border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "solid"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle/solid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFBorderStyleSolid"
        }
      ],
      "role": "symbol",
      "title": "PDFBorderStyle.solid",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfborderstyle/solid"
    },
    "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle/underline": {
      "abstract": [
        {
          "text": "Underline border.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "underline"
        }
      ],
      "identifier": "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle/underline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kPDFBorderStyleUnderline"
        }
      ],
      "role": "symbol",
      "title": "PDFBorderStyle.underline",
      "type": "topic",
      "url": "/documentation/pdfkit/pdfborderstyle/underline"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle/solid",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle/dashed",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle/beveled",
        "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle/underline"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kPDFBorderStyleInset"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFBorderStyleInset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pdfkit/documentation/PDFKit",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle/solid",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle/dashed",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle/beveled",
                "doc://com.apple.pdfkit/documentation/PDFKit/PDFBorderStyle/underline"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kPDFBorderStyleInset"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFBorderStyle~1solid/title",
          "value": "kPDFBorderStyleSolid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFBorderStyle~1solid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFBorderStyleSolid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFBorderStyle~1inset/title",
          "value": "kPDFBorderStyleInset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFBorderStyle~1inset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFBorderStyleInset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFBorderStyle/title",
          "value": "PDFBorderStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFBorderStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFBorderStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFBorderStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PDFBorderStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFBorderStyle~1dashed/title",
          "value": "kPDFBorderStyleDashed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFBorderStyle~1dashed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFBorderStyleDashed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFBorderStyle~1beveled/title",
          "value": "kPDFBorderStyleBeveled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFBorderStyle~1beveled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFBorderStyleBeveled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFBorderStyle~1underline/title",
          "value": "kPDFBorderStyleUnderline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pdfkit~1documentation~1PDFKit~1PDFBorderStyle~1underline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kPDFBorderStyleUnderline"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pdfkit/pdfborderstyle/inset"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pdfkit/pdfborderstyle/inset"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
