{
  "abstract": [
    {
      "text": "A set of flags indicating which representations of the time are valid; see ",
      "type": "text"
    },
    {
      "code": "Audio Time Stamp Flags",
      "type": "codeVoice"
    },
    {
      "text": " and ",
      "type": "text"
    },
    {
      "code": "Audio Time Stamp Flag Combination Constant",
      "type": "codeVoice"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mFlags"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@AudioTimeStamp@FI@mFlags",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "mFlags"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AudioTimeStampFlags",
        "text": "AudioTimeStampFlags"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "mFlags"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "mFlags"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mFlags"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AudioTimeStampFlags",
              "text": "AudioTimeStampFlags"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp": {
      "abstract": [
        {
          "text": "A structure that represents a timestamp value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioTimeStamp"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioTimeStamp"
        }
      ],
      "role": "symbol",
      "title": "AudioTimeStamp",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiotimestamp"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mFlags": {
      "abstract": [
        {
          "text": "A set of flags indicating which representations of the time are valid; see ",
          "type": "text"
        },
        {
          "code": "Audio Time Stamp Flags",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "Audio Time Stamp Flag Combination Constant",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AudioTimeStampFlags",
          "text": "AudioTimeStampFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mFlags"
        }
      ],
      "role": "symbol",
      "title": "mFlags",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiotimestamp/mflags"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mHostTime": {
      "abstract": [
        {
          "text": "The host machine’s time base (see ",
          "type": "text"
        },
        {
          "code": "CoreAudio/HostTime.h",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mHostTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mHostTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mHostTime"
        }
      ],
      "role": "symbol",
      "title": "mHostTime",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiotimestamp/mhosttime"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mRateScalar": {
      "abstract": [
        {
          "text": "The ratio of actual host ticks per sample frame to the nominal host ticks per sample frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mRateScalar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float64a",
          "text": "Float64"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mRateScalar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mRateScalar"
        }
      ],
      "role": "symbol",
      "title": "mRateScalar",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiotimestamp/mratescalar"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mReserved": {
      "abstract": [
        {
          "text": "Pads the structure out to force an even 8-byte alignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mReserved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mReserved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mReserved"
        }
      ],
      "role": "symbol",
      "title": "mReserved",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiotimestamp/mreserved"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mSMPTETime": {
      "abstract": [
        {
          "text": "The SMPTE time (see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mSMPTETime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SMPTETime",
          "text": "SMPTETime"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mSMPTETime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mSMPTETime"
        }
      ],
      "role": "symbol",
      "title": "mSMPTETime",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiotimestamp/msmptetime"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mSampleTime": {
      "abstract": [
        {
          "text": "The absolute sample frame time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mSampleTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7Float64a",
          "text": "Float64"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mSampleTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mSampleTime"
        }
      ],
      "role": "symbol",
      "title": "mSampleTime",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiotimestamp/msampletime"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mWordClockTime": {
      "abstract": [
        {
          "text": "The word clock time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mWordClockTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mWordClockTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mWordClockTime"
        }
      ],
      "role": "symbol",
      "title": "mWordClockTime",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiotimestamp/mwordclocktime"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags": {
      "abstract": [
        {
          "text": "A structure that represents flags for a timestamp.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioTimeStampFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioTimeStampFlags"
        }
      ],
      "role": "symbol",
      "title": "AudioTimeStampFlags",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/audiotimestampflags"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime": {
      "abstract": [
        {
          "text": "A structure that defines an SMPTE time value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SMPTETime"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SMPTETime"
        }
      ],
      "role": "symbol",
      "title": "SMPTETime",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetime"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-the-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mHostTime",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mRateScalar",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mReserved",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mSMPTETime",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mSampleTime",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mWordClockTime"
      ],
      "title": "Accessing the Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "mFlags"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-the-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mHostTime",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mRateScalar",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mReserved",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mSMPTETime",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mSampleTime",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStamp/mWordClockTime"
              ],
              "title": "Accessing the Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/AudioTimeStampFlags",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@AudioTimeStampFlags",
                    "text": "AudioTimeStampFlags"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "mFlags"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStamp~1mReserved/title",
          "value": "mReserved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStamp~1mReserved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mReserved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStamp~1mRateScalar/title",
          "value": "mRateScalar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStamp~1mRateScalar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mRateScalar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime/title",
          "value": "SMPTETime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SMPTETime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SMPTETime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStamp~1mSMPTETime/title",
          "value": "mSMPTETime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStamp~1mSMPTETime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mSMPTETime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStamp~1mSampleTime/title",
          "value": "mSampleTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStamp~1mSampleTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mSampleTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStamp~1mWordClockTime/title",
          "value": "mWordClockTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStamp~1mWordClockTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mWordClockTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStampFlags/title",
          "value": "AudioTimeStampFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStampFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioTimeStampFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStampFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioTimeStampFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStamp~1mFlags/title",
          "value": "mFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStamp~1mFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStamp~1mHostTime/title",
          "value": "mHostTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStamp~1mHostTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mHostTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStamp/title",
          "value": "AudioTimeStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioTimeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1AudioTimeStamp/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioTimeStamp"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/audiotimestamp/mflags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/audiotimestamp/mflags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
