{
  "abstract": [
    {
      "text": "A CoreImage filter used to composite the layer and the content behind it. Animatable.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/compositingFilter"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CALayer(py)compositingFilter",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "compositingFilter"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "compositingFilter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "compositingFilter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "compositingFilter"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default value of this property is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ", which causes the layer to use source-over compositing. Although you can use any Core Image filter as a layer’s compositing filter, for best results, use those in the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html#//apple_ref/doc/uid/TP30000136-SW71",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " category.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In macOS, it is possible to modify the filter’s parameters after attaching it to the layer but you must use the layer’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1418139-setvalue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to do so. For example, to change the ",
              "type": "text"
            },
            {
              "code": "inputRadius",
              "type": "codeVoice"
            },
            {
              "text": " parameter of the filter, you could use code similar to the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let layer = CALayer()",
                    "         ",
                    "if let filter = CIFilter(name:\"CIGaussianBlur\") {",
                    "    filter.name = \"myFilter\"",
                    "    layer.backgroundFilters = [filter]",
                    "    layer.setValue(1,",
                    "                   forKeyPath: \"backgroundFilters.myFilter.inputRadius\")",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "CIFilter *filter = ...;",
                    "CALayer *layer = ...;",
                    " ",
                    "layer.compositingFilter = filter;",
                    "[layer setValue:[NSNumber numberWithInt:1] forKeyPath:@\"compositingFilter.inputRadius\"];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "Changing the inputs of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coreimage/cifilter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object directly after it is attached to the layer causes undefined behavior.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code shows how to create two overlapping text layers, background and foreground. Addition compositing is used to composite the foreground over the background.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "view.layer = CALayer()",
            "view.layerUsesCoreImageFilters = true",
            "     ",
            "let background = CATextLayer()",
            "background.string = \"background\"",
            "background.foregroundColor = NSColor.gray.cgColor",
            "background.backgroundColor = NSColor.darkGray.cgColor",
            "background.alignmentMode = kCAAlignmentCenter",
            "background.fontSize = 96",
            "background.frame = CGRect(x: 10, y: 10, width: 640, height: 160)",
            "     ",
            "let foreground = CATextLayer()",
            "foreground.string = \"foreground\"",
            "foreground.foregroundColor = NSColor.lightGray.cgColor",
            "foreground.backgroundColor = NSColor.darkGray.cgColor",
            "foreground.alignmentMode = kCAAlignmentCenter",
            "foreground.fontSize = 48",
            "foreground.opacity = 0.5",
            "foreground.frame = CGRect(x: 20, y: 20, width: 600, height: 60)",
            "foreground.masksToBounds = false",
            "     ",
            "if let compositingFilter = CIFilter(name: \"CIAdditionCompositing\") {",
            "    foreground.compositingFilter = compositingFilter",
            "}",
            "     ",
            "view.layer?.addSublayer(background)",
            "background.addSublayer(foreground)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The following figure shows the result: the identical background colors of the two layers are added together so that a brighter gray is produced where the layers overlap.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2851428",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following figure shows the default result when the foreground layer’s compositing filter is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html#//apple_ref/doc/filter/ci/CISourceOverCompositing",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2851429",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Special-Considerations",
          "level": 3,
          "text": "Special Considerations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property is not supported on layers in iOS.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/coreimage/cifilter": {
      "abstract": [
        {
          "text": "An image processor that produces an image by manipulating one or more input images or by generating new image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CIFilter"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coreimage/cifilter",
      "kind": "symbol",
      "role": "symbol",
      "title": "CIFilter",
      "type": "topic",
      "url": "/documentation/coreimage/cifilter"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1418139-setvalue": {
      "abstract": [
        {
          "text": "Sets the value for the property identified by a given key path to a given value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "setValue"
        },
        {
          "kind": "text",
          "text": "(Any?, "
        },
        {
          "kind": "identifier",
          "text": "forKeyPath"
        },
        {
          "kind": "text",
          "text": ": String)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1418139-setvalue",
      "kind": "symbol",
      "role": "symbol",
      "title": "setValue(_:forKeyPath:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1418139-setvalue"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer": {
      "abstract": [
        {
          "text": "An object that manages image-based content and allows you to perform animations on that content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CALayer"
        }
      ],
      "role": "symbol",
      "title": "CALayer",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/backgroundFilters": {
      "abstract": [
        {
          "text": "An array of Core Image filters to apply to the content immediately behind the layer. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundFilters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/backgroundFilters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundFilters"
        }
      ],
      "role": "symbol",
      "title": "backgroundFilters",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/backgroundfilters"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/compositingFilter": {
      "abstract": [
        {
          "text": "A CoreImage filter used to composite the layer and the content behind it. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compositingFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/compositingFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compositingFilter"
        }
      ],
      "role": "symbol",
      "title": "compositingFilter",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/compositingfilter"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/filters": {
      "abstract": [
        {
          "text": "An array of Core Image filters to apply to the contents of the layer and its sublayers. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/filters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "filters"
        }
      ],
      "role": "symbol",
      "title": "filters",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/filters"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/magnificationFilter": {
      "abstract": [
        {
          "text": "The filter used when increasing the size of the content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "magnificationFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsFilter",
          "text": "CALayerContentsFilter"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/magnificationFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "magnificationFilter"
        }
      ],
      "role": "symbol",
      "title": "magnificationFilter",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/magnificationfilter"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/minificationFilter": {
      "abstract": [
        {
          "text": "The filter used when reducing the size of the content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minificationFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsFilter",
          "text": "CALayerContentsFilter"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/minificationFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minificationFilter"
        }
      ],
      "role": "symbol",
      "title": "minificationFilter",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/minificationfilter"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/minificationFilterBias": {
      "abstract": [
        {
          "text": "The bias factor used by the minification filter to determine the levels of detail.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minificationFilterBias"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/minificationFilterBias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minificationFilterBias"
        }
      ],
      "role": "symbol",
      "title": "minificationFilterBias",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/minificationfilterbias"
    },
    "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html#//apple_ref/doc/filter/ci/CISourceOverCompositing": {
      "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html#//apple_ref/doc/filter/ci/CISourceOverCompositing",
      "title": "CISourceOverCompositing",
      "titleInlineContent": [
        {
          "text": "CISourceOverCompositing",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html#//apple_ref/doc/filter/ci/CISourceOverCompositing"
    },
    "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html#//apple_ref/doc/uid/TP30000136-SW71": {
      "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html#//apple_ref/doc/uid/TP30000136-SW71",
      "title": "CICategoryCompositeOperation",
      "titleInlineContent": [
        {
          "text": "CICategoryCompositeOperation",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html#//apple_ref/doc/uid/TP30000136-SW71"
    },
    "media-2851428": {
      "alt": "Addition compositing filter",
      "identifier": "media-2851428",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ba62dee32ae5c8adc2b876a77ce9cc6a/media-2851428@2x.png"
        }
      ]
    },
    "media-2851429": {
      "alt": "Default compositing filter",
      "identifier": "media-2851429",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/fd131a516078b5fb2eca0d9be9f8cf33/media-2851429@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Layer-Filters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/filters",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/backgroundFilters",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/minificationFilter",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/minificationFilterBias",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/magnificationFilter"
      ],
      "title": "Layer Filters"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "compositingFilter"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compositingFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartzcore/documentation/QuartzCore",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Layer-Filters",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/filters",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/backgroundFilters",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/minificationFilter",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/minificationFilterBias",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/magnificationFilter"
              ],
              "title": "Layer Filters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "compositingFilter"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1magnificationFilter/title",
          "value": "magnificationFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1magnificationFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "magnificationFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11418139-setvalue/title",
          "value": "setValue:forKeyPath:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1backgroundFilters/title",
          "value": "backgroundFilters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1backgroundFilters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundFilters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1minificationFilter/title",
          "value": "minificationFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1minificationFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minificationFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1minificationFilterBias/title",
          "value": "minificationFilterBias"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1minificationFilterBias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minificationFilterBias"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1filters/title",
          "value": "filters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1filters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "filters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1compositingFilter/title",
          "value": "compositingFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1compositingFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compositingFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer/title",
          "value": "CALayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/calayer/compositingfilter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/calayer/compositingfilter"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
