{
  "abstract": [
    {
      "text": "A constant that specifies how the layer’s contents are positioned or scaled within its bounds.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/contentsGravity"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CALayer(py)contentsGravity",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "contentsGravity"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CALayerContentsGravity",
        "text": "CALayerContentsGravity"
      }
    ],
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "contentsGravity"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "contentsGravity"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "contentsGravity"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CALayerContentsGravity",
              "text": "CALayerContentsGravity"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The possible values for this property are listed in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/contents-gravity-values",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The default value of this property is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resize",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The naming of contents gravity constants is based on the direction of the vertical axis.  If you are using gravity constants with a vertical component, e.g. ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/top",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", you should also check the layer’s ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/contentsAreFlipped()",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". When this is ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/swift/true",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/top",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " aligns contents to the bottom of the layer and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottom",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " aligns content to the top of the layer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "The default coordinate system for views in macOS and iOS differ in the orientation of the vertical axis: in macOS, the default coordinate system has its origin at the lower left of the drawing area and positive values extend up from it, and in iOS the default coordinate system has its origin at the upper left of the drawing area and positive values extend down from it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/library/content/documentation/General/Conceptual/Devpedia-CocoaApp/CoordinateSystem.html",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "identifier": "/documentation/quartzcore/calayer/1410872-contentsgravity#2851774",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " shows four examples of the effect of setting different values for a layer’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/contentsGravity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2851774",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Contents gravity is ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resize",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " - the default",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Contents gravity is ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/center",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Contents gravity is ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/contentsAreFlipped()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "?",
                      "type": "codeVoice"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/top",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " : ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottom",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Contents gravity is ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/contentsAreFlipped()",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "?",
                      "type": "codeVoice"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottomLeft",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " : ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/topLeft",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "/documentation/quartzcore/calayer/1410872-contentsgravity#2851774": {
      "identifier": "/documentation/quartzcore/calayer/1410872-contentsgravity#2851774",
      "title": "Figure 1",
      "titleInlineContent": [
        {
          "text": "Figure 1",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "/documentation/quartzcore/calayer/1410872-contentsgravity#2851774"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CACornerMask"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CACornerMask"
        }
      ],
      "role": "symbol",
      "title": "CACornerMask",
      "type": "topic",
      "url": "/documentation/quartzcore/cacornermask"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer": {
      "abstract": [
        {
          "text": "An object that manages image-based content and allows you to perform animations on that content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CALayer"
        }
      ],
      "role": "symbol",
      "title": "CALayer",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/backgroundColor": {
      "abstract": [
        {
          "text": "The background color of the receiver. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorRef",
          "text": "CGColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/backgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundColor"
        }
      ],
      "role": "symbol",
      "title": "backgroundColor",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/backgroundcolor"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderColor": {
      "abstract": [
        {
          "text": "The color of the layer’s border. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "borderColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorRef",
          "text": "CGColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "borderColor"
        }
      ],
      "role": "symbol",
      "title": "borderColor",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/bordercolor"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderWidth": {
      "abstract": [
        {
          "text": "The width of the layer’s border. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "borderWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "borderWidth"
        }
      ],
      "role": "symbol",
      "title": "borderWidth",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/borderwidth"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/contentsAreFlipped()": {
      "abstract": [
        {
          "text": "Returns a Boolean indicating whether the layer content is implicitly flipped when rendered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentsAreFlipped"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/contentsAreFlipped()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentsAreFlipped"
        }
      ],
      "role": "symbol",
      "title": "contentsAreFlipped()",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/contentsareflipped()"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/contentsGravity": {
      "abstract": [
        {
          "text": "A constant that specifies how the layer’s contents are positioned or scaled within its bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentsGravity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/contentsGravity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentsGravity"
        }
      ],
      "role": "symbol",
      "title": "contentsGravity",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/contentsgravity"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/cornerRadius": {
      "abstract": [
        {
          "text": "The radius to use when drawing rounded corners for the layer’s background. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cornerRadius"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/cornerRadius",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cornerRadius"
        }
      ],
      "role": "symbol",
      "title": "cornerRadius",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/cornerradius"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isDoubleSided": {
      "abstract": [
        {
          "text": "A Boolean indicating whether the layer displays its content when facing away from the viewer. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDoubleSided"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isDoubleSided",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "doubleSided"
        }
      ],
      "role": "symbol",
      "title": "isDoubleSided",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/isdoublesided"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isHidden": {
      "abstract": [
        {
          "text": "A Boolean indicating whether the layer is displayed. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hidden"
        }
      ],
      "role": "symbol",
      "title": "isHidden",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/ishidden"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/mask": {
      "abstract": [
        {
          "text": "An optional layer whose alpha channel is used to mask the layer’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CALayer",
          "text": "CALayer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/mask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mask"
        }
      ],
      "role": "symbol",
      "title": "mask",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/mask"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/maskedCorners": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maskedCorners"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CACornerMask",
          "text": "CACornerMask"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/maskedCorners",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maskedCorners"
        }
      ],
      "role": "symbol",
      "title": "maskedCorners",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/maskedcorners"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/masksToBounds": {
      "abstract": [
        {
          "text": "A Boolean indicating whether sublayers are clipped to the layer’s bounds. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "masksToBounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/masksToBounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "masksToBounds"
        }
      ],
      "role": "symbol",
      "title": "masksToBounds",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/maskstobounds"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/opacity": {
      "abstract": [
        {
          "text": "The opacity of the receiver. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "opacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/opacity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "opacity"
        }
      ],
      "role": "symbol",
      "title": "opacity",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/opacity"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOffset": {
      "abstract": [
        {
          "text": "The offset (in points) of the layer’s shadow. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shadowOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shadowOffset"
        }
      ],
      "role": "symbol",
      "title": "shadowOffset",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/shadowoffset"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOpacity": {
      "abstract": [
        {
          "text": "The opacity of the layer’s shadow. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shadowOpacity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOpacity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shadowOpacity"
        }
      ],
      "role": "symbol",
      "title": "shadowOpacity",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/shadowopacity"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowRadius": {
      "abstract": [
        {
          "text": "The blur radius (in points) used to render the layer’s shadow. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shadowRadius"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowRadius",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shadowRadius"
        }
      ],
      "role": "symbol",
      "title": "shadowRadius",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/shadowradius"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CALayerContentsGravity"
        }
      ],
      "role": "symbol",
      "title": "CALayerContentsGravity",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottom": {
      "abstract": [
        {
          "text": "The content is horizontally centered at the bottom-edge of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityBottom"
        }
      ],
      "role": "symbol",
      "title": "bottom",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/bottom"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottomLeft": {
      "abstract": [
        {
          "text": "The content is positioned in the bottom-left corner of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/bottomLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityBottomLeft"
        }
      ],
      "role": "symbol",
      "title": "bottomLeft",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/bottomleft"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/center": {
      "abstract": [
        {
          "text": "The content is horizontally and vertically centered in the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "center"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityCenter"
        }
      ],
      "role": "symbol",
      "title": "center",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/center"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resize": {
      "abstract": [
        {
          "text": "The content is resized to fit the entire bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/resize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityResize"
        }
      ],
      "role": "symbol",
      "title": "resize",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/resize"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/top": {
      "abstract": [
        {
          "text": "The content is horizontally centered at the top-edge of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityTop"
        }
      ],
      "role": "symbol",
      "title": "top",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/top"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/topLeft": {
      "abstract": [
        {
          "text": "The content is positioned in the top-left corner of the bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CALayerContentsGravity",
          "text": "CALayerContentsGravity"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity/topLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCAGravityTopLeft"
        }
      ],
      "role": "symbol",
      "title": "topLeft",
      "type": "topic",
      "url": "/documentation/quartzcore/calayercontentsgravity/topleft"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/contents-gravity-values": {
      "abstract": [
        {
          "text": "The contents gravity constants specify the position of the content object when the layer bounds is larger than the bounds of the content object. They are used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/contentsGravity",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/contents-gravity-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Contents Gravity Values",
      "type": "topic",
      "url": "/documentation/quartzcore/contents-gravity-values"
    },
    "https://developer.apple.com/library/content/documentation/General/Conceptual/Devpedia-CocoaApp/CoordinateSystem.html": {
      "identifier": "https://developer.apple.com/library/content/documentation/General/Conceptual/Devpedia-CocoaApp/CoordinateSystem.html",
      "title": "Coordinate system",
      "titleInlineContent": [
        {
          "text": "Coordinate system",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/content/documentation/General/Conceptual/Devpedia-CocoaApp/CoordinateSystem.html"
    },
    "media-2851774": {
      "alt": "Different effects of setting a layer’s contents gravity",
      "identifier": "media-2851774",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/55a0f37cf74b8a24023604ae6c89ade1/media-2851774@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Modifying-the-Layers-Appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.quartzcore/documentation/QuartzCore/contents-gravity-values",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/opacity",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isHidden",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/masksToBounds",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/mask",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isDoubleSided",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/cornerRadius",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/maskedCorners",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderWidth",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderColor",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/backgroundColor",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOpacity",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowRadius",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOffset"
      ],
      "title": "Modifying the Layer’s Appearance"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "contentsGravity"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentsGravity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartzcore/documentation/QuartzCore",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Modifying-the-Layers-Appearance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.quartzcore/documentation/QuartzCore/contents-gravity-values",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/opacity",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isHidden",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/masksToBounds",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/mask",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/isDoubleSided",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/cornerRadius",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/maskedCorners",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CACornerMask",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderWidth",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/borderColor",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/backgroundColor",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOpacity",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowRadius",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/shadowOffset"
              ],
              "title": "Modifying the Layer’s Appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayerContentsGravity",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CALayerContentsGravity",
                    "text": "CALayerContentsGravity"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "contentsGravity"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1borderWidth/title",
          "value": "borderWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1borderWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "borderWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1shadowOpacity/title",
          "value": "shadowOpacity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1shadowOpacity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shadowOpacity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1maskedCorners/title",
          "value": "maskedCorners"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1maskedCorners/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maskedCorners"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1shadowOffset/title",
          "value": "shadowOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1shadowOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shadowOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1opacity/title",
          "value": "opacity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1opacity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "opacity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1bottom/title",
          "value": "kCAGravityBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1bottomLeft/title",
          "value": "kCAGravityBottomLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1bottomLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityBottomLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1masksToBounds/title",
          "value": "masksToBounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1masksToBounds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "masksToBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CACornerMask/title",
          "value": "CACornerMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CACornerMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CACornerMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CACornerMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CACornerMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1top/title",
          "value": "kCAGravityTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1backgroundColor/title",
          "value": "backgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1backgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1contentsAreFlipped()/title",
          "value": "contentsAreFlipped"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1contentsAreFlipped()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "contentsAreFlipped"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1mask/title",
          "value": "mask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1mask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1isHidden/title",
          "value": "hidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1isHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity/title",
          "value": "CALayerContentsGravity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsGravity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayerContentsGravity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1cornerRadius/title",
          "value": "cornerRadius"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1cornerRadius/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cornerRadius"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1topLeft/title",
          "value": "kCAGravityTopLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1topLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityTopLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1contentsGravity/title",
          "value": "contentsGravity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1contentsGravity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentsGravity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1isDoubleSided/title",
          "value": "doubleSided"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1isDoubleSided/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "doubleSided"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1center/title",
          "value": "kCAGravityCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1resize/title",
          "value": "kCAGravityResize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayerContentsGravity~1resize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCAGravityResize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1shadowRadius/title",
          "value": "shadowRadius"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1shadowRadius/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shadowRadius"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer/title",
          "value": "CALayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CALayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1borderColor/title",
          "value": "borderColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1borderColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "borderColor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/calayer/contentsgravity"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/calayer/contentsgravity"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
