{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Method","title":"layoutIfNeeded()","modules":[{"name":"Core Animation"}],"symbolKind":"method","role":"symbol","platforms":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"2.0","deprecated":false},{"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"2.0","deprecated":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false},{"unavailable":false,"beta":false,"name":"macOS","introducedAt":"10.5","deprecated":false},{"unavailable":false,"beta":false,"name":"tvOS","introducedAt":"9.0","deprecated":false},{"unavailable":false,"beta":false,"name":"visionOS","introducedAt":"1.0","deprecated":false}],"externalID":"c:objc(cs)CALayer(im)layoutIfNeeded","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutIfNeeded"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"layoutIfNeeded"}]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/layoutIfNeeded()"},"variants":[{"paths":["/documentation/quartzcore/calayer/layoutifneeded()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/quartzcore/calayer/layoutifneeded()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"text":"Recalculate the receiver’s layout, if required.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutIfNeeded","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"Discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"When this message is received, the layer’s super layers are traversed until a ancestor layer is found that does not require layout. Then layout is performed on the entire layer-tree beneath that ancestor."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.quartzcore/documentation/QuartzCore","doc://com.apple.quartzcore/documentation/QuartzCore/CALayer"]]},"seeAlsoSections":[{"generated":true,"title":"Managing Layer Resizing and Layout","anchor":"Managing-Layer-Resizing-and-Layout","identifiers":["doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/layoutManager","doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/setNeedsLayout()","doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/layoutSublayers()","doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/needsLayout()","doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/autoresizingMask","doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/resize(withOldSuperlayerSize:)","doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/resizeSublayers(withOldSize:)","doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/preferredFrameSize()"]}],"references":{"doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/preferredFrameSize()":{"type":"topic","title":"preferredFrameSize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredFrameSize"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"identifier":"doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/preferredFrameSize()","navigatorTitle":[{"kind":"identifier","text":"preferredFrameSize"}],"url":"/documentation/quartzcore/calayer/preferredframesize()","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Returns the preferred size of the layer in the coordinate space of its superlayer."}]},"doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/needsLayout()":{"kind":"symbol","identifier":"doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/needsLayout()","navigatorTitle":[{"text":"needsLayout","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Returns a Boolean indicating whether the layer has been marked as needing a layout update."}],"url":"/documentation/quartzcore/calayer/needslayout()","title":"needsLayout()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"needsLayout","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic"},"doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/layoutIfNeeded()":{"title":"layoutIfNeeded()","abstract":[{"text":"Recalculate the receiver’s layout, if required.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutIfNeeded"},{"kind":"text","text":"()"}],"url":"/documentation/quartzcore/calayer/layoutifneeded()","navigatorTitle":[{"kind":"identifier","text":"layoutIfNeeded"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/layoutIfNeeded()"},"doc://com.apple.quartzcore/documentation/QuartzCore":{"abstract":[{"type":"text","text":"Render, compose, and animate visual elements."}],"url":"/documentation/quartzcore","type":"topic","identifier":"doc://com.apple.quartzcore/documentation/QuartzCore","kind":"symbol","title":"Core Animation","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","type":"topic","title":"Technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","url":"/documentation/technologies"},"doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/autoresizingMask":{"navigatorTitle":[{"text":"autoresizingMask","kind":"identifier"}],"title":"autoresizingMask","abstract":[{"text":"A bitmask defining how the layer is resized when the bounds of its superlayer changes.","type":"text"}],"identifier":"doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/autoresizingMask","url":"/documentation/quartzcore/calayer/autoresizingmask","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoresizingMask","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CAAutoresizingMask","kind":"typeIdentifier","preciseIdentifier":"c:@E@CAAutoresizingMask"}],"type":"topic","kind":"symbol"},"doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/layoutSublayers()":{"title":"layoutSublayers()","abstract":[{"type":"text","text":"Tells the layer to update its layout."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSublayers"},{"kind":"text","text":"()"}],"url":"/documentation/quartzcore/calayer/layoutsublayers()","navigatorTitle":[{"kind":"identifier","text":"layoutSublayers"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/layoutSublayers()"},"doc://com.apple.quartzcore/documentation/QuartzCore/CALayer":{"url":"/documentation/quartzcore/calayer","type":"topic","abstract":[{"text":"An object that manages image-based content and allows you to perform animations on that content.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CALayer","kind":"identifier"}],"navigatorTitle":[{"text":"CALayer","kind":"identifier"}],"identifier":"doc://com.apple.quartzcore/documentation/QuartzCore/CALayer","title":"CALayer","kind":"symbol","role":"symbol"},"doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/resizeSublayers(withOldSize:)":{"type":"topic","title":"resizeSublayers(withOldSize:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resizeSublayers"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOldSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/resizeSublayers(withOldSize:)","navigatorTitle":[{"kind":"identifier","text":"resizeSublayersWithOldSize:"}],"url":"/documentation/quartzcore/calayer/resizesublayers(witholdsize:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Informs the receiver’s sublayers that the receiver’s size has changed."}]},"doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/resize(withOldSuperlayerSize:)":{"title":"resize(withOldSuperlayerSize:)","abstract":[{"text":"Informs the receiver that the size of its superlayer changed.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withOldSuperlayerSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":")","kind":"text"}],"url":"/documentation/quartzcore/calayer/resize(witholdsuperlayersize:)","navigatorTitle":[{"text":"resizeWithOldSuperlayerSize:","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/resize(withOldSuperlayerSize:)"},"doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/setNeedsLayout()":{"type":"topic","title":"setNeedsLayout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setNeedsLayout"},{"kind":"text","text":"()"}],"identifier":"doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/setNeedsLayout()","navigatorTitle":[{"kind":"identifier","text":"setNeedsLayout"}],"url":"/documentation/quartzcore/calayer/setneedslayout()","kind":"symbol","role":"symbol","abstract":[{"text":"Invalidates the layer’s layout and marks it as needing an update.","type":"text"}]},"doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/layoutManager":{"kind":"symbol","identifier":"doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/layoutManager","navigatorTitle":[{"kind":"identifier","text":"layoutManager"}],"role":"symbol","abstract":[{"type":"text","text":"The object responsible for laying out the layer’s sublayers."}],"url":"/documentation/quartzcore/calayer/layoutmanager","title":"layoutManager","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutManager","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"CALayoutManager","preciseIdentifier":"c:objc(pl)CALayoutManager","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"2.0","deprecated":false},{"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"2.0","deprecated":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false},{"unavailable":false,"beta":false,"name":"macOS","introducedAt":"10.5","deprecated":false},{"unavailable":false,"beta":false,"name":"tvOS","introducedAt":"9.0","deprecated":false},{"unavailable":false,"beta":false,"name":"visionOS","introducedAt":"1.0","deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"layoutIfNeeded","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutIfNeeded"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.quartzcore/documentation/QuartzCore","doc://com.apple.quartzcore/documentation/QuartzCore/CALayer"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"generated":true,"title":"Managing Layer Resizing and Layout","anchor":"Managing-Layer-Resizing-and-Layout","identifiers":["doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/layoutManager","doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/setNeedsLayout()","doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/layoutSublayers()","doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/needsLayout()","doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/autoresizingMask","doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/resize(withOldSuperlayerSize:)","doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/resizeSublayers(withOldSize:)","doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/preferredFrameSize()"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"layoutIfNeeded","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":"preferredFrameSize","op":"replace","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1preferredFrameSize()/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"preferredFrameSize"}],"op":"replace","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1preferredFrameSize()/fragments"},{"value":"needsLayout","op":"replace","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1needsLayout()/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"needsLayout"}],"op":"replace","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1needsLayout()/fragments"},{"value":"layoutIfNeeded","op":"replace","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1layoutIfNeeded()/title"},{"value":[{"text":"- ","kind":"text"},{"text":"layoutIfNeeded","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1layoutIfNeeded()/fragments"},{"value":"autoresizingMask","op":"replace","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1autoresizingMask/title"},{"value":[{"text":"autoresizingMask","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1autoresizingMask/fragments"},{"value":"layoutSublayers","op":"replace","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1layoutSublayers()/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSublayers"}],"op":"replace","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1layoutSublayers()/fragments"},{"value":"CALayer","op":"replace","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer/title"},{"value":[{"text":"CALayer","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer/fragments"},{"value":[{"kind":"identifier","text":"CALayer"}],"op":"replace","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer/navigatorTitle"},{"value":"resizeSublayersWithOldSize:","op":"replace","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1resizeSublayers(withOldSize:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"resizeSublayersWithOldSize:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1resizeSublayers(withOldSize:)/fragments"},{"value":"resizeWithOldSuperlayerSize:","op":"replace","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1resize(withOldSuperlayerSize:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"resizeWithOldSuperlayerSize:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1resize(withOldSuperlayerSize:)/fragments"},{"value":"setNeedsLayout","op":"replace","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1setNeedsLayout()/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setNeedsLayout"}],"op":"replace","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1setNeedsLayout()/fragments"},{"value":"layoutManager","op":"replace","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1layoutManager/title"},{"value":[{"kind":"identifier","text":"layoutManager"}],"op":"replace","path":"/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1layoutManager/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}