{
  "abstract": [
    {
      "text": "The possible Objective-C states of Camera Assistance.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/algorithm-convergence-status"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Nearby Interaction"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Algorithm Convergence Status"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the app enables Camera Assistance by setting ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyPeerConfiguration/isCameraAssistanceEnabled",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " = ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": ", the framework may require user action before the feature is operational at runtime. This enumeration indicates whether Camera Assistance currently functions as expected on device, and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReason",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " reasons define the recommended user actions to get Camera Assistance operational, if needed.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction": {
      "abstract": [
        {
          "text": "Locate and interact with nearby devices using identifiers, distance, and direction.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
      "kind": "symbol",
      "role": "collection",
      "title": "Nearby Interaction",
      "type": "topic",
      "url": "/documentation/nearbyinteraction"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergence": {
      "abstract": [
        {
          "text": "An object that provides the state and reason for user coaching recommendations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergence"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergence"
        }
      ],
      "role": "symbol",
      "title": "NIAlgorithmConvergence",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergence"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fbmj": {
      "abstract": [
        {
          "text": "Expose algorithm state to make it possible for apps to coach users.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergenceStatus"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fbmj",
      "kind": "symbol",
      "role": "symbol",
      "title": "NIAlgorithmConvergenceStatus",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergencestatus-2fbmj"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve": {
      "abstract": [
        {
          "text": "The possible states of Camera Assistance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergenceStatus"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergenceStatus"
        }
      ],
      "role": "symbol",
      "title": "NIAlgorithmConvergenceStatus",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergencestatus-2fnve"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReason": {
      "abstract": [
        {
          "text": "The possible reasons for the framework’s Camera Assistance status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergenceStatusReason"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReason",
      "kind": "symbol",
      "role": "symbol",
      "title": "NIAlgorithmConvergenceStatusReason",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergencestatusreason"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReasonDescription": {
      "abstract": [
        {
          "text": "A human-readable description for a particular convergence status reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergenceStatusReasonDescription"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReasonDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "NIAlgorithmConvergenceStatusReasonDescription",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergencestatusreasondescription"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReasonInsufficientHorizontalSweep": {
      "abstract": [
        {
          "text": "Indicates that the camera needs to view the user’s environment from different horizontal angles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergenceStatusReasonInsufficientHorizontalSweep"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReasonInsufficientHorizontalSweep",
      "kind": "symbol",
      "role": "symbol",
      "title": "NIAlgorithmConvergenceStatusReasonInsufficientHorizontalSweep",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergencestatusreasoninsufficienthorizontalsweep"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReasonInsufficientLighting": {
      "abstract": [
        {
          "text": "Indicates that the camera needs to view the phsyical environment under better lighting conditions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergenceStatusReasonInsufficientLighting"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReasonInsufficientLighting",
      "kind": "symbol",
      "role": "symbol",
      "title": "NIAlgorithmConvergenceStatusReasonInsufficientLighting",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergencestatusreasoninsufficientlighting"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReasonInsufficientMovement": {
      "abstract": [
        {
          "text": "Indicates that the device needs to move from its current position in the physical environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergenceStatusReasonInsufficientMovement"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReasonInsufficientMovement",
      "kind": "symbol",
      "role": "symbol",
      "title": "NIAlgorithmConvergenceStatusReasonInsufficientMovement",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergencestatusreasoninsufficientmovement"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReasonInsufficientVerticalSweep": {
      "abstract": [
        {
          "text": "Indicates that the camera needs to view the user’s environment from different vertical angles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergenceStatusReasonInsufficientVerticalSweep"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReasonInsufficientVerticalSweep",
      "kind": "symbol",
      "role": "symbol",
      "title": "NIAlgorithmConvergenceStatusReasonInsufficientVerticalSweep",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergencestatusreasoninsufficientverticalsweep"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyPeerConfiguration/isCameraAssistanceEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that combines the spatial awareness of ARKit with Nearby Interaction to improve the accuracy of a nearby object’s position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isCameraAssistanceEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyPeerConfiguration/isCameraAssistanceEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraAssistanceEnabled"
        }
      ],
      "role": "symbol",
      "title": "isCameraAssistanceEnabled",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbypeerconfiguration/iscameraassistanceenabled"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/finding-devices-with-precision": {
      "abstract": [
        {
          "text": "Leverage the spatial awareness of ARKit and Apple Ultra Wideband Chips in your app to guide users to a nearby device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/finding-devices-with-precision",
      "kind": "article",
      "role": "sampleCode",
      "title": "Finding devices with precision",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/finding-devices-with-precision"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Camera-assistance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/finding-devices-with-precision",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergence",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve"
      ],
      "title": "Camera assistance"
    }
  ],
  "topicSections": [
    {
      "anchor": "Status",
      "identifiers": [
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve"
      ],
      "title": "Status"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Coaching-recommendations",
              "identifiers": [
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReasonInsufficientHorizontalSweep",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReasonInsufficientVerticalSweep",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReasonInsufficientMovement",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReasonInsufficientLighting"
              ],
              "title": "Coaching recommendations"
            },
            {
              "anchor": "Reasons",
              "identifiers": [
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReason",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReasonDescription"
              ],
              "title": "Reasons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Camera-assistance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/finding-devices-with-precision",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergence",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fbmj"
              ],
              "title": "Camera assistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyPeerConfiguration~1isCameraAssistanceEnabled/title",
          "value": "cameraAssistanceEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyPeerConfiguration~1isCameraAssistanceEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cameraAssistanceEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIAlgorithmConvergence/title",
          "value": "NIAlgorithmConvergence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIAlgorithmConvergence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIAlgorithmConvergence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIAlgorithmConvergence/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NIAlgorithmConvergence"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/nearbyinteraction/algorithm-convergence-status"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/nearbyinteraction/algorithm-convergence-status"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
