{
  "abstract": [
    {
      "text": "Leverage the spatial awareness of ARKit and Apple Ultra Wideband Chips in your app to guide users to a nearby device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/finding-devices-with-precision"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Nearby Interaction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Finding devices with precision"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This sample code project demonstrates how to use ARKit to find devices equipped with Apple Ultra Wideband (UWB) chips using a technique known as ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "ranging",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ". Ranging estimates the distance between devices using parameters such as signal strength and packet timing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "To use Extended Distance Measurement (EDM) capabilities, you’ll need two iPhone 15 devices or later. In Xcode, set the deployment target for this sample to iOS 17.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "To use the Nearby Interaction framework in your app, it needs to implement the following three processes to use precision device finding:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Check for availability of UWB and specific versions according to iOS releases if your app needs capabilities such as EDM.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Start ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/ARKit",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", begin ranging for peer devices, and respond to changes in their status — this is how your app discovers compatible nearby devices and responds to changes in their availability.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Implement a distance quality estimator function, if your app needs to take advantage of the EDM capabilities of the second generation of UWB chips. This is a function that uses data the Nearby Interaction framework returns to make decisions about signal quality to estimate the distance and direction between devices. This sample code project includes one possible implementation of a distance quality estimator function and it’s use to guide the people using the appropriate UI.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Configure-the-sample-code-project",
          "level": 3,
          "text": "Configure the sample code project",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To run the app:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Install the app on two iPhone 15 devices or later.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Rest one iPhone in portrait orientation as a stationary device.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Run the app. If available, tap “Discuss jetpacks with another visitor” on both devices to run ranging with EDM capabilities (available on devices with second generation UWB chips). Otherwise, tap “Go to next Exhibit” on both devices to run first generation UWB ranging.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "On the first run, accept the request prompts for local network and camera access.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Wait a few moments for the apps to discover each other, then accept the Nearby Interaction access prompt.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "To initialize ARKit, move the nonstationary device from side to side.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "With the stationary device in the immediate vicinity, move the active device up and down until the app displays an arrow.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Move the active device until the arrow points upward in the direction of the stationary device.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "On the active device, the app’s blurred background fades and several virtual spheres display above the stationary device as it appears within the active device’s AR view.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample app doesn’t support Apple Watch and, because Camera Assistance uses ARKit, the app doesn’t support Simulator.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Check-availability",
          "level": 3,
          "text": "Check availability",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Because there are two types of UWB chips, always check to ensure that the peer devices support the mode the app is interested in, as shown in the example below:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "if #available(iOS 17.0, watchOS 10.0, *) {",
            "    guard NISession.deviceCapabilities.supportsExtendedDistanceMeasurement else {",
            "        NSLog(\"This device isn't capable of finding visitors.\")",
            "        return",
            "    }",
            "    ",
            "    guard token.deviceCapabilities.supportsExtendedDistanceMeasurement else {",
            "        NSLog(\"Peer device \\(peer.displayName) isn't capable of finding visitors.\")",
            "        return",
            "    }",
            "    ",
            "    config.isExtendedDistanceMeasurementEnabled = true",
            "    NSLog(\"The Nearby Interaction session uses extended distance measurement.\")",
            "    ",
            "} else {",
            "    NSLog(\"This version of iOS isn't capable of finding visitors.\")",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Start-ARKit-and-ranging-for-peer-devices",
          "level": 3,
          "text": "Start ARKit and ranging for peer devices",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Before the app can start ranging for potential peer devices, it needs to setup ARKit and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MultipeerConnectivity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " frameworks, as shown in this example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func startup() {",
            "    // The initial view.",
            "    Task { @MainActor in",
            "        self.updateViewState(with: nil, quality: .unknown, nearbyObject: nil, worldTransform: nil, showUpDownText: false)",
            "    }",
            "",
            "    // Create the interaction session.",
            "    session = NISession()",
            "    session?.delegateQueue = sessionQueue",
            "    ",
            "    // Set a delegate.",
            "    session?.delegate = self",
            "",
            "    // Because this is a new session, reset the token-shared flag.",
            "    sharedTokenWithPeer = false",
            "    connectedPeer = nil",
            "",
            "    // Start multipeer connectivity (MPC) to discover peers.",
            "    startupMPC()",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Respond-to-changes-in-peer-devices",
          "level": 3,
          "text": "Respond to changes in peer devices",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After the app initializes the Multipeer Connectivity framework, the Nearby Interaction framework provides a protocol for tracking changes to peer devices and provides information necessary to interact with peers it discovers in the environment.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISessionDelegate/session(_:didUpdate:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to track changes to peer connectivity, as shown in the sample below:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func session(_ session: NISession, didUpdate nearbyObjects: [NINearbyObject]) {",
            "    guard let peerToken = peerDiscoveryToken else {",
            "        fatalError(\"don't have peer token\")",
            "    }",
            "",
            "    // Find the right peer.",
            "    let peerObj = nearbyObjects.first { (obj) -> Bool in",
            "        return obj.discoveryToken == peerToken",
            "    }",
            "",
            "    guard let nearbyObjectUpdate = peerObj else {",
            "        return",
            "    }",
            "    ",
            "    // When the session is ranging with its peer, the data connection might",
            "    // drop; after which which you don't need to keep it.",
            "    // Tear down the MPC session after the app initially started ranging with the peer.",
            "    // After the current ranging session stops and is invalidated, the app",
            "    // restarts a new MPC data connection for a new peer.",
            "    if mpc != nil {",
            "        tearDownMpc()",
            "    }",
            "",
            "    // Update and compute with updated `nearbyObject`.",
            "    currentNearbyObject = nearbyObjectUpdate",
            "    computeViewState(with: convergenceContext, nearbyObject: nearbyObjectUpdate)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When peers drop out of range or their session validity (user permissions) changes, the framework announces these changes using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISessionDelegate/session(_:didInvalidateWith:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and the app responds accordingly, as shown here:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func session(_ session: NISession, didInvalidateWith error: Error) {",
            "    // If the app doesn't have approval for Nearby Interaction, present",
            "    // an option to open the Settings app where the they can update the access.",
            "    if #available(iOS 17.0, watchOS 10.0, *) {",
            "        switch error {",
            "        case NIError.userDidNotAllow,",
            "            NIError.invalidARConfiguration,",
            "            NIError.incompatiblePeerDevice,",
            "            NIError.activeSessionsLimitExceeded,",
            "            NIError.activeExtendedDistanceSessionsLimitExceeded:",
            "            return",
            "        default:",
            "            break",
            "        }",
            "    } else {",
            "        switch error {",
            "        case NIError.userDidNotAllow,",
            "            NIError.invalidARConfiguration,",
            "            NIError.activeSessionsLimitExceeded:",
            "            return",
            "        default:",
            "            break",
            "        }",
            "    }",
            "    ",
            "    // Recreate a valid session in other failure cases.",
            "    startup()",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When the app sets ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyPeerConfiguration/isCameraAssistanceEnabled",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": ", the framework provides coaching suggestions through ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISessionDelegate/session(_:didUpdateAlgorithmConvergence:for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", as shown here:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func session(_ session: NISession, didUpdateAlgorithmConvergence convergence: NIAlgorithmConvergence, for object: NINearbyObject?) {",
            "    guard let peerToken = peerDiscoveryToken else {",
            "        fatalError(\"Don't have peer token.\")",
            "    }",
            "",
            "    guard let nearbyObject = object, nearbyObject.discoveryToken == peerToken else {",
            "        return",
            "    }",
            "",
            "    // Update and compute with updated algorithm `convergence` and `nearbyObject`.",
            "    currentNearbyObject = nearbyObject",
            "    convergenceContext = convergence",
            "    computeViewState(with: convergence, nearbyObject: currentNearbyObject)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Define-a-distance-quality-estimator",
          "level": 3,
          "text": "Define a distance quality estimator",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Finally, the key to using EDM is by creating a distance quality estimator function that the app uses to determine which peers to interact with. The specific criteria for such estimators are specific to your app’s use case; the following example is one such implementation:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "class MeasurementQualityEstimator {",
            "",
            "    // Define the criteria that qualify a peer with \"good\" characteristics:",
            "    // these include:",
            "",
            "    // A time window, in seconds.",
            "    let freshnessWindow = TimeInterval(floatLiteral: 2.0)",
            "    // A minimum number of samples in that time window.",
            "    let minSamples: Int = 8",
            "    // A maximim distance, in meters.",
            "    let maxDistance: Float = 50",
            "    // A minimum distance, in meters.",
            "    let closeDistance: Float = 10",
            "    ",
            "    // A buffer to hold the individual quality measurements.",
            "    private var measurements: [TimedNIObject] = []",
            "    ",
            "    // An enumeration that defines levels of peer quality.",
            "    enum MeasurementQuality {",
            "        // The peer fails to meet any of the measurement quality criteria.",
            "        case unknown",
            "",
            "        // The extended distance measurements indicate the peer iPhone or device",
            "        // satisfies the criteria for \"good\" quality and falls inside the",
            "        // minimum and maximum acceptable distance.",
            "        case good",
            "",
            "        // The extended distance measurements indicate the current device",
            "        // satisfies the criteria for being \"close\" to the peer iPhone or device.",
            "        case close",
            "    }",
            "",
            "    // A structure that captures the range of a peer at a specific time.",
            "    struct TimedNIObject {",
            "        let time: TimeInterval",
            "        let distance: Float",
            "    }",
            "",
            "    func estimateQuality(update: NINearbyObject?) -> MeasurementQuality {",
            "        let timeNow = NSDate().timeIntervalSinceReferenceDate",
            "        if let distance = update?.distance {",
            "            if let lastMeasureMent = measurements.last {",
            "                if lastMeasureMent.distance != distance {",
            "                    // Before adding a new measurement to buffers, check",
            "                    // if the reported distance is unique.",
            "                    measurements.append(TimedNIObject(time: timeNow, distance: distance))",
            "                }",
            "            } else {",
            "                // If the buffer is empty, unconditionally add the new measurement.",
            "                measurements.append(TimedNIObject(time: timeNow, distance: distance))",
            "            }",
            "        }",
            "        let validTimestamp = timeNow - freshnessWindow",
            "        measurements.removeAll { $0.time < validTimestamp }",
            "        if measurements.count > minSamples, let lastDistance = measurements.last?.distance {",
            "            if lastDistance <= closeDistance { return .close }",
            "            return lastDistance < maxDistance ? .good : .unknown",
            "        }",
            "        return .unknown",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "07951274a4f9/FindingDevicesWithPrecision.zip": {
      "checksum": "07951274a4f99f30f610918af2aa63e703e7a017a61340eb318b77b3cb3a20657bbba41fafed0014f2ea0a1f2b881c6c1a8e066fd9c55b07748fd1ddb2317292",
      "identifier": "07951274a4f9/FindingDevicesWithPrecision.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/07951274a4f9/FindingDevicesWithPrecision.zip"
    },
    "doc://com.apple.documentation/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/ARKit"
    },
    "doc://com.apple.documentation/documentation/MultipeerConnectivity": {
      "abstract": [
        {
          "text": "Support peer-to-peer connectivity and the discovery of nearby devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MultipeerConnectivity",
      "kind": "symbol",
      "role": "collection",
      "title": "Multipeer Connectivity",
      "type": "topic",
      "url": "/documentation/MultipeerConnectivity"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction": {
      "abstract": [
        {
          "text": "Locate and interact with nearby devices using identifiers, distance, and direction.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
      "kind": "symbol",
      "role": "collection",
      "title": "Nearby Interaction",
      "type": "topic",
      "url": "/documentation/nearbyinteraction"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergence": {
      "abstract": [
        {
          "text": "An object that provides the state and reason for user coaching recommendations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergence"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergence"
        }
      ],
      "role": "symbol",
      "title": "NIAlgorithmConvergence",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergence"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fbmj": {
      "abstract": [
        {
          "text": "Expose algorithm state to make it possible for apps to coach users.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergenceStatus"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fbmj",
      "kind": "symbol",
      "role": "symbol",
      "title": "NIAlgorithmConvergenceStatus",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergencestatus-2fbmj"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve": {
      "abstract": [
        {
          "text": "The possible states of Camera Assistance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergenceStatus"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergenceStatus"
        }
      ],
      "role": "symbol",
      "title": "NIAlgorithmConvergenceStatus",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergencestatus-2fnve"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyPeerConfiguration/isCameraAssistanceEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that combines the spatial awareness of ARKit with Nearby Interaction to improve the accuracy of a nearby object’s position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isCameraAssistanceEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NINearbyPeerConfiguration/isCameraAssistanceEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cameraAssistanceEnabled"
        }
      ],
      "role": "symbol",
      "title": "isCameraAssistanceEnabled",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/ninearbypeerconfiguration/iscameraassistanceenabled"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISessionDelegate/session(_:didInvalidateWith:)": {
      "abstract": [
        {
          "text": "Notifies you of an invalidated session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "session"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NISession",
          "text": "NISession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didInvalidateWith"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISessionDelegate/session(_:didInvalidateWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "session:didInvalidateWithError:"
        }
      ],
      "role": "symbol",
      "title": "session(_:didInvalidateWith:)",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nisessiondelegate/session(_:didinvalidatewith:)"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISessionDelegate/session(_:didUpdate:)": {
      "abstract": [
        {
          "text": "Notifies you when the session updates nearby objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "session"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NISession",
          "text": "NISession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdate"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NINearbyObject",
          "text": "NINearbyObject"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISessionDelegate/session(_:didUpdate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "session:didUpdateNearbyObjects:"
        }
      ],
      "role": "symbol",
      "title": "session(_:didUpdate:)",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nisessiondelegate/session(_:didupdate:)"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISessionDelegate/session(_:didUpdateAlgorithmConvergence:for:)": {
      "abstract": [
        {
          "text": "Provides recommended actions the user can take to facilitate the framework’s Camera Assistance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "session"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NISession",
          "text": "NISession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdateAlgorithmConvergence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NIAlgorithmConvergence",
          "text": "NIAlgorithmConvergence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NINearbyObject",
          "text": "NINearbyObject"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISessionDelegate/session(_:didUpdateAlgorithmConvergence:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "session:didUpdateAlgorithmConvergence:forObject:"
        }
      ],
      "role": "symbol",
      "title": "session(_:didUpdateAlgorithmConvergence:for:)",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nisessiondelegate/session(_:didupdatealgorithmconvergence:for:)"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/algorithm-convergence-status": {
      "abstract": [
        {
          "text": "The possible Objective-C states of Camera Assistance.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/algorithm-convergence-status",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Algorithm Convergence Status",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/algorithm-convergence-status"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "07951274a4f9/FindingDevicesWithPrecision.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Camera-assistance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergence",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fnve",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/algorithm-convergence-status"
      ],
      "title": "Camera assistance"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Camera-assistance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergence",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fbmj",
                "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/algorithm-convergence-status"
              ],
              "title": "Camera assistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NISessionDelegate~1session(_:didInvalidateWith:)/title",
          "value": "session:didInvalidateWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NISessionDelegate~1session(_:didInvalidateWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "session:didInvalidateWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NISessionDelegate~1session(_:didUpdateAlgorithmConvergence:for:)/title",
          "value": "session:didUpdateAlgorithmConvergence:forObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NISessionDelegate~1session(_:didUpdateAlgorithmConvergence:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "session:didUpdateAlgorithmConvergence:forObject:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyPeerConfiguration~1isCameraAssistanceEnabled/title",
          "value": "cameraAssistanceEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NINearbyPeerConfiguration~1isCameraAssistanceEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cameraAssistanceEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIAlgorithmConvergence/title",
          "value": "NIAlgorithmConvergence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIAlgorithmConvergence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIAlgorithmConvergence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIAlgorithmConvergence/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NIAlgorithmConvergence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NISessionDelegate~1session(_:didUpdate:)/title",
          "value": "session:didUpdateNearbyObjects:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NISessionDelegate~1session(_:didUpdate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "session:didUpdateNearbyObjects:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/nearbyinteraction/finding-devices-with-precision"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/nearbyinteraction/finding-devices-with-precision"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
