{
  "abstract": [
    {
      "text": "Expose algorithm state to make it possible for apps to coach users.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fbmj"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NIAlgorithmConvergenceStatus",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NIAlgorithmConvergenceStatus"
      }
    ],
    "modules": [
      {
        "name": "Nearby Interaction"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NIAlgorithmConvergenceStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NIAlgorithmConvergenceStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NIAlgorithmConvergenceStatus"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction": {
      "abstract": [
        {
          "text": "Locate and interact with nearby devices using identifiers, distance, and direction.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
      "kind": "symbol",
      "role": "collection",
      "title": "Nearby Interaction",
      "type": "topic",
      "url": "/documentation/nearbyinteraction"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergence": {
      "abstract": [
        {
          "text": "An object that provides the state and reason for user coaching recommendations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergence"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergence"
        }
      ],
      "role": "symbol",
      "title": "NIAlgorithmConvergence",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergence"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fbmj": {
      "abstract": [
        {
          "text": "Expose algorithm state to make it possible for apps to coach users.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergenceStatus"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fbmj",
      "kind": "symbol",
      "role": "symbol",
      "title": "NIAlgorithmConvergenceStatus",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergencestatus-2fbmj"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fbmj/NIAlgorithmConvergenceStatusConverged": {
      "abstract": [
        {
          "text": "A status that indicates the framework’s Camera Assistance feature is operational.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergenceStatusConverged"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fbmj/NIAlgorithmConvergenceStatusConverged",
      "kind": "symbol",
      "role": "symbol",
      "title": "NIAlgorithmConvergenceStatusConverged",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergencestatus-2fbmj/nialgorithmconvergencestatusconverged"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fbmj/NIAlgorithmConvergenceStatusNotConverged": {
      "abstract": [
        {
          "text": "A status that indicates the framework’s Camera Assistance feature requires action from the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergenceStatusNotConverged"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fbmj/NIAlgorithmConvergenceStatusNotConverged",
      "kind": "symbol",
      "role": "symbol",
      "title": "NIAlgorithmConvergenceStatusNotConverged",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergencestatus-2fbmj/nialgorithmconvergencestatusnotconverged"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fbmj/NIAlgorithmConvergenceStatusUnknown": {
      "abstract": [
        {
          "text": "An indication that the framework is unsure of the Camera Assistance status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergenceStatusUnknown"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fbmj/NIAlgorithmConvergenceStatusUnknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "NIAlgorithmConvergenceStatusUnknown",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergencestatus-2fbmj/nialgorithmconvergencestatusunknown"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/algorithm-convergence-status": {
      "abstract": [
        {
          "text": "The possible Objective-C states of Camera Assistance.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/algorithm-convergence-status",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Algorithm Convergence Status",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/algorithm-convergence-status"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/finding-devices-with-precision": {
      "abstract": [
        {
          "text": "Leverage the spatial awareness of ARKit and Apple Ultra Wideband Chips in your app to guide users to a nearby device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/finding-devices-with-precision",
      "kind": "article",
      "role": "sampleCode",
      "title": "Finding devices with precision",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/finding-devices-with-precision"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Camera-assistance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/finding-devices-with-precision",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergence",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/algorithm-convergence-status"
      ],
      "title": "Camera assistance"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fbmj/NIAlgorithmConvergenceStatusConverged",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fbmj/NIAlgorithmConvergenceStatusNotConverged",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatus-2fbmj/NIAlgorithmConvergenceStatusUnknown"
      ],
      "title": "Enumeration Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIAlgorithmConvergence/title",
          "value": "NIAlgorithmConvergence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIAlgorithmConvergence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NIAlgorithmConvergence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NIAlgorithmConvergence/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NIAlgorithmConvergence"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/nearbyinteraction/nialgorithmconvergencestatus-2fbmj"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
