{
  "abstract": [
    {
      "text": "The possible reasons for the framework’s Camera Assistance status.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReason"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@NIAlgorithmConvergenceStatusReason",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NIAlgorithmConvergenceStatusReason"
      }
    ],
    "modules": [
      {
        "name": "Nearby Interaction"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NIAlgorithmConvergenceStatusReason"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "NIAlgorithmConvergenceStatusReason"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "NIAlgorithmConvergenceStatusReason"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The framework provides the app with one or more reasons for the current convergence status. Reasons detail specific user actions the framework believes will get the Camera Assistance feature operational.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "At runtime, the app needs to check the status in the ",
              "type": "text"
            },
            {
              "code": "convergence",
              "type": "codeVoice"
            },
            {
              "text": " object provided by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISessionDelegate/session(_:didUpdateAlgorithmConvergence:for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". If the status indicates that Camera Assistance requires user intervention, the app needs to coach the user, such as by presenting text that explains what to do, for every value in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergence/reasons",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " field.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction": {
      "abstract": [
        {
          "text": "Locate and interact with nearby devices using identifiers, distance, and direction.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction",
      "kind": "symbol",
      "role": "collection",
      "title": "Nearby Interaction",
      "type": "topic",
      "url": "/documentation/nearbyinteraction"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergence/reasons": {
      "abstract": [
        {
          "text": "An array of reasons that contribute to the convergence status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "reasons"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergence/reasons",
      "kind": "symbol",
      "role": "symbol",
      "title": "reasons",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergence/reasons"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReason": {
      "abstract": [
        {
          "text": "The possible reasons for the framework’s Camera Assistance status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergenceStatusReason"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReason",
      "kind": "symbol",
      "role": "symbol",
      "title": "NIAlgorithmConvergenceStatusReason",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergencestatusreason"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReasonDescription": {
      "abstract": [
        {
          "text": "A human-readable description for a particular convergence status reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NIAlgorithmConvergenceStatusReasonDescription"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReasonDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "NIAlgorithmConvergenceStatusReasonDescription",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nialgorithmconvergencestatusreasondescription"
    },
    "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISessionDelegate/session(_:didUpdateAlgorithmConvergence:for:)": {
      "abstract": [
        {
          "text": "Provides recommended actions the user can take to facilitate the framework’s Camera Assistance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "session"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NISession",
          "text": "NISession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdateAlgorithmConvergence"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NIAlgorithmConvergence",
          "text": "NIAlgorithmConvergence"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NINearbyObject",
          "text": "NINearbyObject"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NISessionDelegate/session(_:didUpdateAlgorithmConvergence:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "session:didUpdateAlgorithmConvergence:forObject:"
        }
      ],
      "role": "symbol",
      "title": "session(_:didUpdateAlgorithmConvergence:for:)",
      "type": "topic",
      "url": "/documentation/nearbyinteraction/nisessiondelegate/session(_:didupdatealgorithmconvergence:for:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reasons",
      "generated": true,
      "identifiers": [
        "doc://com.apple.nearbyinteraction/documentation/NearbyInteraction/NIAlgorithmConvergenceStatusReasonDescription"
      ],
      "title": "Reasons"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NISessionDelegate~1session(_:didUpdateAlgorithmConvergence:for:)/title",
          "value": "session:didUpdateAlgorithmConvergence:forObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.nearbyinteraction~1documentation~1NearbyInteraction~1NISessionDelegate~1session(_:didUpdateAlgorithmConvergence:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "session:didUpdateAlgorithmConvergence:forObject:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/nearbyinteraction/nialgorithmconvergencestatusreason"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
