{
  "abstract": [
    {
      "text": "A type that indicates a participant can simultaneously receive and transmit audio.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pushtotalk/documentation/PushToTalk",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode/fullDuplex"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PTTransmissionMode@PTTransmissionModeFullDuplex",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "fullDuplex"
      }
    ],
    "modules": [
      {
        "name": "Push to Talk"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PTTransmissionModeFullDuplex"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PTTransmissionMode.fullDuplex"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "fullDuplex"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.pushtotalk/documentation/PushToTalk/creating-a-push-to-talk-app"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk": {
      "abstract": [
        {
          "text": "Display the system user interface for your app’s Push to Talk services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk",
      "kind": "symbol",
      "role": "collection",
      "title": "Push to Talk",
      "type": "topic",
      "url": "/documentation/pushtotalk"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode": {
      "abstract": [
        {
          "text": "Identifies the type of audio transmission modes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTTransmissionMode"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTTransmissionMode"
        }
      ],
      "role": "symbol",
      "title": "PTTransmissionMode",
      "type": "topic",
      "url": "/documentation/pushtotalk/pttransmissionmode"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode/fullDuplex": {
      "abstract": [
        {
          "text": "A type that indicates a participant can simultaneously receive and transmit audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullDuplex"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode/fullDuplex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTTransmissionModeFullDuplex"
        }
      ],
      "role": "symbol",
      "title": "PTTransmissionMode.fullDuplex",
      "type": "topic",
      "url": "/documentation/pushtotalk/pttransmissionmode/fullduplex"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode/halfDuplex": {
      "abstract": [
        {
          "text": "A type that indicates a participant can’t simultaneously receive and transmit audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "halfDuplex"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode/halfDuplex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTTransmissionModeHalfDuplex"
        }
      ],
      "role": "symbol",
      "title": "PTTransmissionMode.halfDuplex",
      "type": "topic",
      "url": "/documentation/pushtotalk/pttransmissionmode/halfduplex"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode/listenOnly": {
      "abstract": [
        {
          "text": "A type that indicates a participant can only receive audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "listenOnly"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode/listenOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTTransmissionModeListenOnly"
        }
      ],
      "role": "symbol",
      "title": "PTTransmissionMode.listenOnly",
      "type": "topic",
      "url": "/documentation/pushtotalk/pttransmissionmode/listenonly"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/creating-a-push-to-talk-app": {
      "abstract": [
        {
          "text": "Build a walkie-talkie style app with system user interface controls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/creating-a-push-to-talk-app",
      "kind": "article",
      "role": "article",
      "title": "Creating a Push to Talk app",
      "type": "topic",
      "url": "/documentation/pushtotalk/creating-a-push-to-talk-app"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Modes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode/halfDuplex",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode/listenOnly"
      ],
      "title": "Modes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PTTransmissionModeFullDuplex"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTTransmissionModeFullDuplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.pushtotalk/documentation/PushToTalk",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Modes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode/halfDuplex",
                "doc://com.apple.pushtotalk/documentation/PushToTalk/PTTransmissionMode/listenOnly"
              ],
              "title": "Modes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PTTransmissionModeFullDuplex"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTTransmissionMode/title",
          "value": "PTTransmissionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTTransmissionMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTTransmissionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTTransmissionMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTTransmissionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTTransmissionMode~1listenOnly/title",
          "value": "PTTransmissionModeListenOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTTransmissionMode~1listenOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTTransmissionModeListenOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTTransmissionMode~1fullDuplex/title",
          "value": "PTTransmissionModeFullDuplex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTTransmissionMode~1fullDuplex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTTransmissionModeFullDuplex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTTransmissionMode~1halfDuplex/title",
          "value": "PTTransmissionModeHalfDuplex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTTransmissionMode~1halfDuplex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTTransmissionModeHalfDuplex"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pushtotalk/pttransmissionmode/fullduplex"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/pushtotalk/pttransmissionmode/fullduplex"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
