{
  "abstract": [
    {
      "text": "Medium accuracy.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.vision/documentation/Vision",
        "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest",
        "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum/medium"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@VNGenerateOpticalFlowRequestComputationAccuracy@VNGenerateOpticalFlowRequestComputationAccuracyMedium",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "medium"
      }
    ],
    "modules": [
      {
        "name": "Vision"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "VNGenerateOpticalFlowRequestComputationAccuracyMedium"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "VNGenerateOpticalFlowRequest.ComputationAccuracy.medium"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "medium"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.vision/documentation/Vision": {
      "abstract": [
        {
          "text": "Apply computer vision algorithms to perform a variety of tasks on input images and videos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision",
      "kind": "symbol",
      "role": "collection",
      "title": "Vision",
      "type": "topic",
      "url": "/documentation/vision"
    },
    "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest": {
      "abstract": [
        {
          "text": "An object that generates directional change vectors for each pixel in the targeted image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VNGenerateOpticalFlowRequest"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNGenerateOpticalFlowRequest"
        }
      ],
      "role": "symbol",
      "title": "VNGenerateOpticalFlowRequest",
      "type": "topic",
      "url": "/documentation/vision/vngenerateopticalflowrequest"
    },
    "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum": {
      "abstract": [
        {
          "text": "The supported optical flow accuracy levels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ComputationAccuracy"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ComputationAccuracy"
        }
      ],
      "role": "symbol",
      "title": "VNGenerateOpticalFlowRequest.ComputationAccuracy",
      "type": "topic",
      "url": "/documentation/vision/vngenerateopticalflowrequest/computationaccuracy-swift.enum"
    },
    "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum/high": {
      "abstract": [
        {
          "text": "High accuracy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "high"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum/high",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNGenerateOpticalFlowRequestComputationAccuracyHigh"
        }
      ],
      "role": "symbol",
      "title": "VNGenerateOpticalFlowRequest.ComputationAccuracy.high",
      "type": "topic",
      "url": "/documentation/vision/vngenerateopticalflowrequest/computationaccuracy-swift.enum/high"
    },
    "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum/low": {
      "abstract": [
        {
          "text": "Low accuracy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "low"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum/low",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNGenerateOpticalFlowRequestComputationAccuracyLow"
        }
      ],
      "role": "symbol",
      "title": "VNGenerateOpticalFlowRequest.ComputationAccuracy.low",
      "type": "topic",
      "url": "/documentation/vision/vngenerateopticalflowrequest/computationaccuracy-swift.enum/low"
    },
    "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum/medium": {
      "abstract": [
        {
          "text": "Medium accuracy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medium"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum/medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNGenerateOpticalFlowRequestComputationAccuracyMedium"
        }
      ],
      "role": "symbol",
      "title": "VNGenerateOpticalFlowRequest.ComputationAccuracy.medium",
      "type": "topic",
      "url": "/documentation/vision/vngenerateopticalflowrequest/computationaccuracy-swift.enum/medium"
    },
    "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum/veryHigh": {
      "abstract": [
        {
          "text": "Very high accuracy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "veryHigh"
        }
      ],
      "identifier": "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum/veryHigh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VNGenerateOpticalFlowRequestComputationAccuracyVeryHigh"
        }
      ],
      "role": "symbol",
      "title": "VNGenerateOpticalFlowRequest.ComputationAccuracy.veryHigh",
      "type": "topic",
      "url": "/documentation/vision/vngenerateopticalflowrequest/computationaccuracy-swift.enum/veryhigh"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accuracy-Levels",
      "generated": true,
      "identifiers": [
        "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum/low",
        "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum/high",
        "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum/veryHigh"
      ],
      "title": "Accuracy Levels"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "VNGenerateOpticalFlowRequestComputationAccuracyMedium"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateOpticalFlowRequestComputationAccuracyMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.vision/documentation/Vision",
                "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accuracy-Levels",
              "generated": true,
              "identifiers": [
                "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum/low",
                "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum/high",
                "doc://com.apple.vision/documentation/Vision/VNGenerateOpticalFlowRequest/ComputationAccuracy-swift.enum/veryHigh"
              ],
              "title": "Accuracy Levels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "VNGenerateOpticalFlowRequestComputationAccuracyMedium"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1ComputationAccuracy-swift.enum~1medium/title",
          "value": "VNGenerateOpticalFlowRequestComputationAccuracyMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1ComputationAccuracy-swift.enum~1medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateOpticalFlowRequestComputationAccuracyMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1ComputationAccuracy-swift.enum~1high/title",
          "value": "VNGenerateOpticalFlowRequestComputationAccuracyHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1ComputationAccuracy-swift.enum~1high/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateOpticalFlowRequestComputationAccuracyHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest/title",
          "value": "VNGenerateOpticalFlowRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateOpticalFlowRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateOpticalFlowRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1ComputationAccuracy-swift.enum~1veryHigh/title",
          "value": "VNGenerateOpticalFlowRequestComputationAccuracyVeryHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1ComputationAccuracy-swift.enum~1veryHigh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateOpticalFlowRequestComputationAccuracyVeryHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1ComputationAccuracy-swift.enum/title",
          "value": "VNGenerateOpticalFlowRequestComputationAccuracy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1ComputationAccuracy-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateOpticalFlowRequestComputationAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1ComputationAccuracy-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateOpticalFlowRequestComputationAccuracy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1ComputationAccuracy-swift.enum~1low/title",
          "value": "VNGenerateOpticalFlowRequestComputationAccuracyLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.vision~1documentation~1Vision~1VNGenerateOpticalFlowRequest~1ComputationAccuracy-swift.enum~1low/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VNGenerateOpticalFlowRequestComputationAccuracyLow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/vision/vngenerateopticalflowrequest/computationaccuracy-swift.enum/medium"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/vision/vngenerateopticalflowrequest/computationaccuracy-swift.enum/medium"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
