{"variants":[{"paths":["/documentation/uikit/uinavigationcontroller/viewcontrollers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uinavigationcontroller/viewcontrollers"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The view controllers currently on the navigation stack.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UINavigationController"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewControllers","kind":"identifier"},{"text":": [","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The root view controller is at index ","type":"text"},{"type":"codeVoice","code":"0"},{"text":" in the array, the back view controller is at index ","type":"text"},{"type":"codeVoice","code":"n-2"},{"text":", and the top controller is at index ","type":"text"},{"type":"codeVoice","code":"n-1"},{"text":", where ","type":"text"},{"type":"codeVoice","code":"n"},{"text":" is the number of items in the array.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Assigning a new array of view controllers to this property is equivalent to calling the "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationController/setViewControllers(_:animated:)","type":"reference","isActive":true},{"type":"text","text":" method with the "},{"type":"codeVoice","code":"animated"},{"type":"text","text":" parameter set to "},{"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference","isActive":true},{"type":"text","text":"."}]}]}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UINavigationController/viewControllers","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"viewControllers","platforms":[{"name":"iOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"2.0"},{"name":"iPadOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"2.0"},{"name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"13.1"},{"name":"tvOS","beta":false,"deprecated":false,"unavailable":false},{"name":"visionOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"1.0"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"viewControllers","kind":"identifier"}],"modules":[{"name":"UIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewControllers","kind":"identifier"},{"text":": [","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"]","kind":"text"}],"externalID":"c:objc(cs)UINavigationController(py)viewControllers","roleHeading":"Instance Property"},"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationController/topViewController","doc://com.apple.uikit/documentation/UIKit/UINavigationController/visibleViewController","doc://com.apple.uikit/documentation/UIKit/UINavigationController/setViewControllers(_:animated:)"],"title":"Accessing items on the navigation stack","generated":true,"anchor":"Accessing-items-on-the-navigation-stack"}],"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UINavigationController/visibleViewController":{"navigatorTitle":[{"text":"visibleViewController","kind":"identifier"}],"url":"/documentation/uikit/uinavigationcontroller/visibleviewcontroller","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visibleViewController","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationController/visibleViewController","abstract":[{"text":"The view controller associated with the currently visible view in the navigation interface.","type":"text"}],"title":"visibleViewController","role":"symbol","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UINavigationController/viewControllers":{"navigatorTitle":[{"text":"viewControllers","kind":"identifier"}],"url":"/documentation/uikit/uinavigationcontroller/viewcontrollers","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewControllers","kind":"identifier"},{"text":": [","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"]","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationController/viewControllers","abstract":[{"text":"The view controllers currently on the navigation stack.","type":"text"}],"title":"viewControllers","role":"symbol","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UINavigationController/setViewControllers(_:animated:)":{"navigatorTitle":[{"text":"setViewControllers:animated:","kind":"identifier"}],"url":"/documentation/uikit/uinavigationcontroller/setviewcontrollers(_:animated:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setViewControllers","kind":"identifier"},{"text":"([","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationController/setViewControllers(_:animated:)","abstract":[{"text":"Replaces the view controllers currently managed by the navigation controller with the specified items.","type":"text"}],"title":"setViewControllers(_:animated:)","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/swift/false":{"role":"symbol","url":"/documentation/swift/false","title":"false","identifier":"doc://com.apple.documentation/documentation/swift/false","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UINavigationController/topViewController":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topViewController","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?","kind":"text"}],"abstract":[{"text":"The view controller at the top of the navigation stack.","type":"text"}],"role":"symbol","url":"/documentation/uikit/uinavigationcontroller/topviewcontroller","navigatorTitle":[{"text":"topViewController","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationController/topViewController","title":"topViewController"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIViewController":{"role":"symbol","kind":"symbol","url":"/documentation/uikit/uiviewcontroller","title":"UIViewController","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewController","navigatorTitle":[{"text":"UIViewController","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIViewController","kind":"identifier"}],"abstract":[{"text":"An object that manages a view hierarchy for your UIKit app.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UINavigationController":{"abstract":[{"text":"A container view controller that defines a stack-based scheme for navigating hierarchical content.","type":"text"}],"title":"UINavigationController","url":"/documentation/uikit/uinavigationcontroller","navigatorTitle":[{"kind":"identifier","text":"UINavigationController"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UINavigationController"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"introducedAt":"2.0","deprecated":false,"unavailable":false,"name":"iOS"},{"beta":false,"introducedAt":"2.0","deprecated":false,"unavailable":false,"name":"iPadOS"},{"beta":false,"introducedAt":"13.1","deprecated":false,"unavailable":false,"name":"Mac Catalyst"},{"beta":false,"deprecated":false,"unavailable":false,"name":"tvOS"},{"beta":false,"introducedAt":"1.0","deprecated":false,"unavailable":false,"name":"visionOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"viewControllers","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"viewControllers"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UINavigationController"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"anchor":"Accessing-items-on-the-navigation-stack","title":"Accessing items on the navigation stack","identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationController/topViewController","doc://com.apple.uikit/documentation/UIKit/UINavigationController/visibleViewController","doc://com.apple.uikit/documentation/UIKit/UINavigationController/setViewControllers(_:animated:)"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<__kindof UIViewController *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"viewControllers","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"visibleViewController","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationController~1visibleViewController/title"},{"value":[{"text":"visibleViewController","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationController~1visibleViewController/fragments"},{"value":"viewControllers","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationController~1viewControllers/title"},{"value":[{"kind":"identifier","text":"viewControllers"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationController~1viewControllers/fragments"},{"value":"setViewControllers:animated:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationController~1setViewControllers(_:animated:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setViewControllers:animated:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationController~1setViewControllers(_:animated:)/fragments"},{"value":"topViewController","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationController~1topViewController/title"},{"value":[{"text":"topViewController","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationController~1topViewController/fragments"},{"value":"UIViewController","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/title"},{"value":[{"kind":"identifier","text":"UIViewController"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/fragments"},{"value":[{"text":"UIViewController","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/navigatorTitle"},{"value":"UINavigationController","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationController/title"},{"value":[{"kind":"identifier","text":"UINavigationController"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationController/fragments"},{"value":[{"text":"UINavigationController","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationController/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}