{
  "abstract": [
    {
      "text": "The controller’s effect on a particle property is a function of the particle’s distance from the position of a specified node.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleInputMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleInputMode/overDistance"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SCNParticleInputMode@SCNParticleInputModeOverDistance",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "overDistance"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCNParticleInputModeOverDistance"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SCNParticleInputMode.overDistance"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "overDistance"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticlePropertyController/inputOrigin",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to specify the node to measure distance from, and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticlePropertyController/inputBias",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticlePropertyController/inputScale",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties to refine the relationship between a range of distances into a range of input values for the controller’s animation.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleInputMode": {
      "abstract": [
        {
          "text": "Options for the input value of the property controller’s animation, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticlePropertyController/inputMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNParticleInputMode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleInputMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleInputMode"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleInputMode",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleinputmode"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleInputMode/overDistance": {
      "abstract": [
        {
          "text": "The controller’s effect on a particle property is a function of the particle’s distance from the position of a specified node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overDistance"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleInputMode/overDistance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleInputModeOverDistance"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleInputMode.overDistance",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleinputmode/overdistance"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleInputMode/overLife": {
      "abstract": [
        {
          "text": "The controller’s effect on a particle property is a function of the time since the particle’s birth.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overLife"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleInputMode/overLife",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleInputModeOverLife"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleInputMode.overLife",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleinputmode/overlife"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleInputMode/overOtherProperty": {
      "abstract": [
        {
          "text": "The controller’s effect on a particle property is a function of another of the particle’s properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overOtherProperty"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleInputMode/overOtherProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNParticleInputModeOverOtherProperty"
        }
      ],
      "role": "symbol",
      "title": "SCNParticleInputMode.overOtherProperty",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticleinputmode/overotherproperty"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticlePropertyController/inputBias": {
      "abstract": [
        {
          "text": "An offset to add to the input value of the controller’s animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputBias"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticlePropertyController/inputBias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputBias"
        }
      ],
      "role": "symbol",
      "title": "inputBias",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlepropertycontroller/inputbias"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticlePropertyController/inputMode": {
      "abstract": [
        {
          "text": "The mode that determines input values for the property controller’s animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNParticleInputMode",
          "text": "SCNParticleInputMode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticlePropertyController/inputMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputMode"
        }
      ],
      "role": "symbol",
      "title": "inputMode",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlepropertycontroller/inputmode"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticlePropertyController/inputOrigin": {
      "abstract": [
        {
          "text": "A node whose distance to each particle provides input values for the controller’s animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputOrigin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNNode",
          "text": "SCNNode"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticlePropertyController/inputOrigin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputOrigin"
        }
      ],
      "role": "symbol",
      "title": "inputOrigin",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlepropertycontroller/inputorigin"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNParticlePropertyController/inputScale": {
      "abstract": [
        {
          "text": "A factor for multiplying the input value of the controller’s animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNParticlePropertyController/inputScale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputScale"
        }
      ],
      "role": "symbol",
      "title": "inputScale",
      "type": "topic",
      "url": "/documentation/scenekit/scnparticlepropertycontroller/inputscale"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleInputMode/overLife",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleInputMode/overOtherProperty"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCNParticleInputModeOverDistance"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleInputModeOverDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleInputMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleInputMode/overLife",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNParticleInputMode/overOtherProperty"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SCNParticleInputModeOverDistance"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleInputMode/title",
          "value": "SCNParticleInputMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleInputMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleInputMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleInputMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleInputMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticlePropertyController~1inputOrigin/title",
          "value": "inputOrigin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticlePropertyController~1inputOrigin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputOrigin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticlePropertyController~1inputMode/title",
          "value": "inputMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticlePropertyController~1inputMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleInputMode~1overDistance/title",
          "value": "SCNParticleInputModeOverDistance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleInputMode~1overDistance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleInputModeOverDistance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticlePropertyController~1inputBias/title",
          "value": "inputBias"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticlePropertyController~1inputBias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputBias"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticlePropertyController~1inputScale/title",
          "value": "inputScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticlePropertyController~1inputScale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleInputMode~1overLife/title",
          "value": "SCNParticleInputModeOverLife"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleInputMode~1overLife/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleInputModeOverLife"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleInputMode~1overOtherProperty/title",
          "value": "SCNParticleInputModeOverOtherProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNParticleInputMode~1overOtherProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNParticleInputModeOverOtherProperty"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scnparticleinputmode/overdistance"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scnparticleinputmode/overdistance"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
