{
  "abstract": [
    {
      "text": "The Thread network extended PAN identifier.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/extendedPANID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)THCredentials(py)extendedPANID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "extendedPANID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation4DataV",
        "text": "Data"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "ThreadNetwork"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "extendedPANID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "extendedPANID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "extendedPANID"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DataV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation4DataV",
              "text": "Data"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork": {
      "abstract": [
        {
          "text": "Share credentials and choose a designated network for each home.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork",
      "kind": "symbol",
      "role": "collection",
      "title": "ThreadNetwork",
      "type": "topic",
      "url": "/documentation/threadnetwork"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials": {
      "abstract": [
        {
          "text": "A class that contains credentials for a Thread network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "THCredentials"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "THCredentials"
        }
      ],
      "role": "symbol",
      "title": "THCredentials",
      "type": "topic",
      "url": "/documentation/threadnetwork/thcredentials"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/activeOperationalDataSet": {
      "abstract": [
        {
          "text": "The essential operational parameters for the Thread network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activeOperationalDataSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/activeOperationalDataSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activeOperationalDataSet"
        }
      ],
      "role": "symbol",
      "title": "activeOperationalDataSet",
      "type": "topic",
      "url": "/documentation/threadnetwork/thcredentials/activeoperationaldataset"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/borderAgentID": {
      "abstract": [
        {
          "text": "The identifer of an active Thread network Border Agent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "borderAgentID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/borderAgentID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "borderAgentID"
        }
      ],
      "role": "symbol",
      "title": "borderAgentID",
      "type": "topic",
      "url": "/documentation/threadnetwork/thcredentials/borderagentid"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/channel": {
      "abstract": [
        {
          "text": "The Thread network radio channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/channel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "channel"
        }
      ],
      "role": "symbol",
      "title": "channel",
      "type": "topic",
      "url": "/documentation/threadnetwork/thcredentials/channel"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/extendedPANID": {
      "abstract": [
        {
          "text": "The Thread network extended PAN identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendedPANID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/extendedPANID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extendedPANID"
        }
      ],
      "role": "symbol",
      "title": "extendedPANID",
      "type": "topic",
      "url": "/documentation/threadnetwork/thcredentials/extendedpanid"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/networkKey": {
      "abstract": [
        {
          "text": "The Thread network key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/networkKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "networkKey"
        }
      ],
      "role": "symbol",
      "title": "networkKey",
      "type": "topic",
      "url": "/documentation/threadnetwork/thcredentials/networkkey"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/networkName": {
      "abstract": [
        {
          "text": "The Thread network name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/networkName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "networkName"
        }
      ],
      "role": "symbol",
      "title": "networkName",
      "type": "topic",
      "url": "/documentation/threadnetwork/thcredentials/networkname"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/panID": {
      "abstract": [
        {
          "text": "The Thead network PAN identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "panID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/panID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "panID"
        }
      ],
      "role": "symbol",
      "title": "panID",
      "type": "topic",
      "url": "/documentation/threadnetwork/thcredentials/panid"
    },
    "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/pskc": {
      "abstract": [
        {
          "text": "The Thread network pre-shared key for the Commissioner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pskc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/pskc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PSKC"
        }
      ],
      "role": "symbol",
      "title": "pskc",
      "type": "topic",
      "url": "/documentation/threadnetwork/thcredentials/pskc"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation4DataV": {
      "abstract": [
        {
          "text": "A byte buffer in memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation4DataV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Data",
      "type": "topic",
      "url": "/documentation/foundation/data"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Thread-Parameters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/activeOperationalDataSet",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/borderAgentID",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/channel",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/networkKey",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/networkName",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/panID",
        "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/pskc"
      ],
      "title": "Getting the Thread Parameters"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "extendedPANID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extendedPANID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Thread-Parameters",
              "generated": true,
              "identifiers": [
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/activeOperationalDataSet",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/borderAgentID",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/channel",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/networkKey",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/networkName",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/panID",
                "doc://com.apple.ThreadNetwork/documentation/ThreadNetwork/THCredentials/pskc"
              ],
              "title": "Getting the Thread Parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSData",
                    "text": "NSData"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "extendedPANID"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1borderAgentID/title",
          "value": "borderAgentID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1borderAgentID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "borderAgentID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1extendedPANID/title",
          "value": "extendedPANID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1extendedPANID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extendedPANID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1panID/title",
          "value": "panID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1panID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "panID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1networkKey/title",
          "value": "networkKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1networkKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "networkKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1activeOperationalDataSet/title",
          "value": "activeOperationalDataSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1activeOperationalDataSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activeOperationalDataSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1channel/title",
          "value": "channel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1channel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "channel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials/title",
          "value": "THCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "THCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "THCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1networkName/title",
          "value": "networkName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1networkName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "networkName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1pskc/title",
          "value": "PSKC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ThreadNetwork~1documentation~1ThreadNetwork~1THCredentials~1pskc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PSKC"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/threadnetwork/thcredentials/extendedpanid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/threadnetwork/thcredentials/extendedpanid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
