{
  "abstract": [
    {
      "text": "The set of bezel styles to style buttons in your app.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSButton"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSBezelStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BezelStyle"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BezelStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSButton.BezelStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BezelStyle"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For design guidance on buttons, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/design/human-interface-guidelines/buttons",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton": {
      "abstract": [
        {
          "text": "A control that defines an area on the screen that a user clicks to trigger an action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButton"
        }
      ],
      "role": "symbol",
      "title": "NSButton",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum": {
      "abstract": [
        {
          "text": "The set of bezel styles to style buttons in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BezelStyle"
        }
      ],
      "role": "symbol",
      "title": "NSButton.BezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/accessoryBar": {
      "abstract": [
        {
          "text": "A button style that’s typically used in the context of an accessory toolbar for buttons that narrow the focus of a search or other operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryBar"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/accessoryBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleAccessoryBar"
        }
      ],
      "role": "symbol",
      "title": "NSButton.BezelStyle.accessoryBar",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/accessorybar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/accessoryBarAction": {
      "abstract": [
        {
          "text": "A button style that you use for extra actions in an accessory toolbar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryBarAction"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/accessoryBarAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleAccessoryBarAction"
        }
      ],
      "role": "symbol",
      "title": "NSButton.BezelStyle.accessoryBarAction",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/accessorybaraction"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/automatic": {
      "abstract": [
        {
          "text": "The default button style based on the button’s contents and position within the window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleAutomatic"
        }
      ],
      "role": "symbol",
      "title": "NSButton.BezelStyle.automatic",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/automatic"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/badge": {
      "abstract": [
        {
          "text": "A button style suitable for displaying additional information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badge"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/badge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleBadge"
        }
      ],
      "role": "symbol",
      "title": "NSButton.BezelStyle.badge",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/badge"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/circular": {
      "abstract": [
        {
          "text": "A round button that can contain either a single character or an icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "circular"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/circular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleCircular"
        }
      ],
      "role": "symbol",
      "title": "NSButton.BezelStyle.circular",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/circular"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/disclosure": {
      "abstract": [
        {
          "text": "A bezel style button for use with a disclosure triangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disclosure"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/disclosure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleDisclosure"
        }
      ],
      "role": "symbol",
      "title": "NSButton.BezelStyle.disclosure",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/disclosure"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/flexiblePush": {
      "abstract": [
        {
          "text": "A push button with a flexible height to accommodate longer text labels or an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flexiblePush"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/flexiblePush",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleFlexiblePush"
        }
      ],
      "role": "symbol",
      "title": "NSButton.BezelStyle.flexiblePush",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/flexiblepush"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/helpButton": {
      "abstract": [
        {
          "text": "A round button with a question mark, providing the standard help button look.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "helpButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/helpButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleHelpButton"
        }
      ],
      "role": "symbol",
      "title": "NSButton.BezelStyle.helpButton",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/helpbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/push": {
      "abstract": [
        {
          "text": "A standard push style button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "push"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/push",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStylePush"
        }
      ],
      "role": "symbol",
      "title": "NSButton.BezelStyle.push",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/push"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/pushDisclosure": {
      "abstract": [
        {
          "text": "A bezel style push button with a disclosure triangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pushDisclosure"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/pushDisclosure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStylePushDisclosure"
        }
      ],
      "role": "symbol",
      "title": "NSButton.BezelStyle.pushDisclosure",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/pushdisclosure"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/smallSquare": {
      "abstract": [
        {
          "text": "A simple square bezel style that can scale to any size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "smallSquare"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/smallSquare",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleSmallSquare"
        }
      ],
      "role": "symbol",
      "title": "NSButton.BezelStyle.smallSquare",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/smallsquare"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/toolbar": {
      "abstract": [
        {
          "text": "A button style that’s appropriate for a toolbar item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolbar"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/toolbar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBezelStyleToolbar"
        }
      ],
      "role": "symbol",
      "title": "NSButton.BezelStyle.toolbar",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum/toolbar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType": {
      "abstract": [
        {
          "text": "Button types that you can specify using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/setButtonType(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ButtonType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ButtonType"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType": {
      "abstract": [
        {
          "text": "Specify the gradients used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/gradientType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GradientType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GradientType"
        }
      ],
      "role": "symbol",
      "title": "NSButton.GradientType",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/gradienttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/gradientType": {
      "abstract": [
        {
          "text": "The gradient of the button’s border.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradientType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButton",
          "text": "NSButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSGradientType",
          "text": "GradientType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/gradientType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gradientType"
        }
      ],
      "role": "symbol",
      "title": "gradientType",
      "type": "topic",
      "url": "/documentation/appkit/nsbuttoncell/gradienttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/setButtonType(_:)": {
      "abstract": [
        {
          "text": "Sets how the button highlights while pressed and how it shows its state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setButtonType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButton",
          "text": "NSButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSButtonType",
          "text": "ButtonType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/setButtonType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setButtonType:"
        }
      ],
      "role": "symbol",
      "title": "setButtonType(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsbuttoncell/setbuttontype(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/bezelstyle-deprecated-symbols": {
      "abstract": [],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/bezelstyle-deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Symbols",
      "type": "topic",
      "url": "/documentation/appkit/bezelstyle-deprecated-symbols"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "https://developer.apple.com/design/human-interface-guidelines/buttons": {
      "identifier": "https://developer.apple.com/design/human-interface-guidelines/buttons",
      "title": "Human Interface Guidelines > Buttons",
      "titleInlineContent": [
        {
          "text": "Human Interface Guidelines > Buttons",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/design/human-interface-guidelines/buttons"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Default",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/automatic"
      ],
      "title": "Default"
    },
    {
      "anchor": "Push",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/push",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/flexiblePush"
      ],
      "title": "Push"
    },
    {
      "anchor": "Disclosure",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/disclosure",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/pushDisclosure"
      ],
      "title": "Disclosure"
    },
    {
      "anchor": "Toolbar",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/toolbar",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/accessoryBar",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/accessoryBarAction"
      ],
      "title": "Toolbar"
    },
    {
      "anchor": "Informational",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/helpButton",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/badge",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/circular"
      ],
      "title": "Informational"
    },
    {
      "anchor": "Other",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/smallSquare"
      ],
      "title": "Other"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/bezelstyle-deprecated-symbols"
      ],
      "title": "Deprecated"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSBezelStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Default",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/automatic"
              ],
              "title": "Default"
            },
            {
              "anchor": "Push",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/push",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/flexiblePush"
              ],
              "title": "Push"
            },
            {
              "anchor": "Disclosure",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/disclosure",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/pushDisclosure"
              ],
              "title": "Disclosure"
            },
            {
              "anchor": "Toolbar",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/toolbar",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/accessoryBar",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/accessoryBarAction"
              ],
              "title": "Toolbar"
            },
            {
              "anchor": "Informational",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/helpButton",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/badge",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/circular"
              ],
              "title": "Informational"
            },
            {
              "anchor": "Other",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum/smallSquare"
              ],
              "title": "Other"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/bezelstyle-deprecated-symbols"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSBezelStyle"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/title",
          "value": "NSButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1helpButton/title",
          "value": "NSBezelStyleHelpButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1helpButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleHelpButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType/title",
          "value": "NSButtonType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonCell~1setButtonType(_:)/title",
          "value": "setButtonType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonCell~1setButtonType(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setButtonType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1push/title",
          "value": "NSBezelStylePush"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1push/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStylePush"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1GradientType/title",
          "value": "NSGradientType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1GradientType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGradientType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1GradientType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGradientType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1badge/title",
          "value": "NSBezelStyleBadge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1badge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleBadge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum/title",
          "value": "NSBezelStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1circular/title",
          "value": "NSBezelStyleCircular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1circular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleCircular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1toolbar/title",
          "value": "NSBezelStyleToolbar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1toolbar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleToolbar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonCell~1gradientType/title",
          "value": "gradientType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonCell~1gradientType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gradientType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1accessoryBarAction/title",
          "value": "NSBezelStyleAccessoryBarAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1accessoryBarAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleAccessoryBarAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1disclosure/title",
          "value": "NSBezelStyleDisclosure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1disclosure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleDisclosure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1pushDisclosure/title",
          "value": "NSBezelStylePushDisclosure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1pushDisclosure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStylePushDisclosure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1accessoryBar/title",
          "value": "NSBezelStyleAccessoryBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1accessoryBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleAccessoryBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1automatic/title",
          "value": "NSBezelStyleAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1flexiblePush/title",
          "value": "NSBezelStyleFlexiblePush"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1flexiblePush/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleFlexiblePush"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1smallSquare/title",
          "value": "NSBezelStyleSmallSquare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum~1smallSquare/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyleSmallSquare"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsbutton/bezelstyle-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsbutton/bezelstyle-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
