{
  "abstract": [
    {
      "text": "Button types that you can specify using ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/setButtonType(_:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSButton"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSButtonType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ButtonType"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ButtonType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSButton.ButtonType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ButtonType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For examples of how these types behave, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Button/Button.html#//apple_ref/doc/uid/10000019i",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAcceleratorButton": {
      "abstract": [
        {
          "text": "A button that sends an action when the user first clicks the button and continues sending actions until the user releases pressure entirely.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAcceleratorButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAcceleratorButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAcceleratorButton",
      "type": "topic",
      "url": "/documentation/appkit/nsacceleratorbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton": {
      "abstract": [
        {
          "text": "A control that defines an area on the screen that a user clicks to trigger an action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButton"
        }
      ],
      "role": "symbol",
      "title": "NSButton",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum": {
      "abstract": [
        {
          "text": "The set of bezel styles to style buttons in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BezelStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BezelStyle"
        }
      ],
      "role": "symbol",
      "title": "NSButton.BezelStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/bezelstyle-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType": {
      "abstract": [
        {
          "text": "Button types that you can specify using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/setButtonType(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ButtonType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ButtonType"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/accelerator": {
      "abstract": [
        {
          "text": "A button that sends repeating actions as pressure changes occur.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accelerator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/accelerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTypeAccelerator"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType.accelerator",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/accelerator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryChange": {
      "abstract": [
        {
          "text": "A button that displays its alternate content when clicked and returns to its normal content when the user releases it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "momentaryChange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTypeMomentaryChange"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType.momentaryChange",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/momentarychange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryLight": {
      "abstract": [
        {
          "text": "A button that displays a highlight when the user clicks it and returns to its normal state when the user releases it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "momentaryLight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTypeMomentaryLight"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType.momentaryLight",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/momentarylight"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryPushIn": {
      "abstract": [
        {
          "text": "A button that illuminates when the user clicks it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "momentaryPushIn"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryPushIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTypeMomentaryPushIn"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType.momentaryPushIn",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/momentarypushin"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/multiLevelAccelerator": {
      "abstract": [
        {
          "text": "A button that allows for a configurable number of stepped pressure levels and provides tactile feedback as the user reaches each step.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiLevelAccelerator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/multiLevelAccelerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTypeMultiLevelAccelerator"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType.multiLevelAccelerator",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/multilevelaccelerator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/onOff": {
      "abstract": [
        {
          "text": "A button that switches between a normal and emphasized bezel on each click.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onOff"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/onOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTypeOnOff"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType.onOff",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/onoff"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/pushOnPushOff": {
      "abstract": [
        {
          "text": "A button that switches between on and off states with each click.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pushOnPushOff"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/pushOnPushOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTypePushOnPushOff"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType.pushOnPushOff",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/pushonpushoff"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/radio": {
      "abstract": [
        {
          "text": "A button that displays a single selected value from group of possible choices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "radio"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/radio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTypeRadio"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType.radio",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/radio"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/switch": {
      "abstract": [
        {
          "text": "A standard checkbox button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`switch`"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/switch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTypeSwitch"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType.switch",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/switch"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/toggle": {
      "abstract": [
        {
          "text": "A button that switches between its normal and alternate content on each click.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toggle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/toggle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSButtonTypeToggle"
        }
      ],
      "role": "symbol",
      "title": "NSButton.ButtonType.toggle",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/buttontype/toggle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType": {
      "abstract": [
        {
          "text": "Specify the gradients used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/gradientType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GradientType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GradientType"
        }
      ],
      "role": "symbol",
      "title": "NSButton.GradientType",
      "type": "topic",
      "url": "/documentation/appkit/nsbutton/gradienttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/gradientType": {
      "abstract": [
        {
          "text": "The gradient of the button’s border.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gradientType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButton",
          "text": "NSButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSGradientType",
          "text": "GradientType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/gradientType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "gradientType"
        }
      ],
      "role": "symbol",
      "title": "gradientType",
      "type": "topic",
      "url": "/documentation/appkit/nsbuttoncell/gradienttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/setButtonType(_:)": {
      "abstract": [
        {
          "text": "Sets how the button highlights while pressed and how it shows its state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setButtonType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSButton",
          "text": "NSButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSButtonType",
          "text": "ButtonType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSButtonCell/setButtonType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setButtonType:"
        }
      ],
      "role": "symbol",
      "title": "setButtonType(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsbuttoncell/setbuttontype(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMomentaryChangeButton": {
      "abstract": [
        {
          "text": "When the button is clicked, the alternate (on state) image and alternate title are displayed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMomentaryChangeButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMomentaryChangeButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMomentaryChangeButton",
      "type": "topic",
      "url": "/documentation/appkit/nsmomentarychangebutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMomentaryLight": {
      "abstract": [
        {
          "text": "When the button is clicked (on state), it appears illuminated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMomentaryLight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMomentaryLight",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMomentaryLight",
      "type": "topic",
      "url": "/documentation/appkit/nsmomentarylight"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMomentaryLightButton": {
      "abstract": [
        {
          "text": "When the button is clicked (on state), it appears illuminated. If the button has borders, it may also appear recessed. When the button is released, it returns to its normal (off) state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMomentaryLightButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMomentaryLightButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMomentaryLightButton",
      "type": "topic",
      "url": "/documentation/appkit/nsmomentarylightbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMomentaryPushButton": {
      "abstract": [
        {
          "text": "When the button is clicked (on state), it appears illuminated. If the button has a bordered, it may also appear recessed. When the button is released, it returns to its normal (off) state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMomentaryPushButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMomentaryPushButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMomentaryPushButton",
      "type": "topic",
      "url": "/documentation/appkit/nsmomentarypushbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMomentaryPushInButton": {
      "abstract": [
        {
          "text": "When the user clicks the button (on state), the button appears illuminated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMomentaryPushInButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMomentaryPushInButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMomentaryPushInButton",
      "type": "topic",
      "url": "/documentation/appkit/nsmomentarypushinbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMultiLevelAcceleratorButton": {
      "abstract": [
        {
          "text": "A multilevel accelerator button is a variation of a normal accelerator button that allows for a configurable number of stepped pressure levels. As each one is reached, the user receives light tactile feedback and an action is sent.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMultiLevelAcceleratorButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMultiLevelAcceleratorButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMultiLevelAcceleratorButton",
      "type": "topic",
      "url": "/documentation/appkit/nsmultilevelacceleratorbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSOnOffButton": {
      "abstract": [
        {
          "text": "The first click highlights the button; a second click returns it to the normal (unhighlighted) state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSOnOffButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSOnOffButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSOnOffButton",
      "type": "topic",
      "url": "/documentation/appkit/nsonoffbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPushOnPushOffButton": {
      "abstract": [
        {
          "text": "When the button is clicked (on state), it appears illuminated. If the button has borders, it may also appear recessed. A second click returns it to its normal (off) state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPushOnPushOffButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPushOnPushOffButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPushOnPushOffButton",
      "type": "topic",
      "url": "/documentation/appkit/nspushonpushoffbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRadioButton": {
      "abstract": [
        {
          "text": "This style is similar to ",
          "type": "text"
        },
        {
          "code": "NSSwitchButton",
          "type": "codeVoice"
        },
        {
          "text": ", but it is used to constrain a selection to a single element from several elements.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRadioButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRadioButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRadioButton",
      "type": "topic",
      "url": "/documentation/appkit/nsradiobutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSwitchButton": {
      "abstract": [
        {
          "text": "This style is a variant of ",
          "type": "text"
        },
        {
          "code": "NSToggleButton",
          "type": "codeVoice"
        },
        {
          "text": " that has no border and is typically used to represent a checkbox.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSwitchButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSwitchButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSwitchButton",
      "type": "topic",
      "url": "/documentation/appkit/nsswitchbutton"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSToggleButton": {
      "abstract": [
        {
          "text": "After the first click, the button displays its alternate image or title (on state); a second click returns the button to its normal (off) state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSToggleButton"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSToggleButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSToggleButton",
      "type": "topic",
      "url": "/documentation/appkit/nstogglebutton"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Button/Button.html#//apple_ref/doc/uid/10000019i": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Button/Button.html#//apple_ref/doc/uid/10000019i",
      "title": "Button Programming Topics",
      "titleInlineContent": [
        {
          "text": "Button Programming Topics",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Button/Button.html#//apple_ref/doc/uid/10000019i"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-Button-Behavior",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryPushIn",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryLight",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryChange",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/pushOnPushOff",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/onOff",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/toggle",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/switch",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/radio",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/accelerator",
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/multiLevelAccelerator"
      ],
      "title": "Configuring Button Behavior"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSButtonType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-Button-Behavior",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryPushIn",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryLight",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/momentaryChange",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/pushOnPushOff",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/onOff",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/toggle",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/switch",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/radio",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/accelerator",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/ButtonType/multiLevelAccelerator"
              ],
              "title": "Configuring Button Behavior"
            },
            {
              "anchor": "Deprecated-Button-Types",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSMomentaryLightButton",
                "doc://com.apple.appkit/documentation/AppKit/NSPushOnPushOffButton",
                "doc://com.apple.appkit/documentation/AppKit/NSToggleButton",
                "doc://com.apple.appkit/documentation/AppKit/NSSwitchButton",
                "doc://com.apple.appkit/documentation/AppKit/NSRadioButton",
                "doc://com.apple.appkit/documentation/AppKit/NSMomentaryChangeButton",
                "doc://com.apple.appkit/documentation/AppKit/NSOnOffButton",
                "doc://com.apple.appkit/documentation/AppKit/NSAcceleratorButton",
                "doc://com.apple.appkit/documentation/AppKit/NSMultiLevelAcceleratorButton",
                "doc://com.apple.appkit/documentation/AppKit/NSMomentaryPushInButton",
                "doc://com.apple.appkit/documentation/AppKit/NSMomentaryPushButton",
                "doc://com.apple.appkit/documentation/AppKit/NSMomentaryLight"
              ],
              "title": "Deprecated Button Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSButton/BezelStyle-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSButton/GradientType"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSButtonType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/title",
          "value": "NSButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1momentaryPushIn/title",
          "value": "NSButtonTypeMomentaryPushIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1momentaryPushIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypeMomentaryPushIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1radio/title",
          "value": "NSButtonTypeRadio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1radio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypeRadio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1switch/title",
          "value": "NSButtonTypeSwitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1switch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypeSwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1pushOnPushOff/title",
          "value": "NSButtonTypePushOnPushOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1pushOnPushOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypePushOnPushOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1toggle/title",
          "value": "NSButtonTypeToggle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1toggle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypeToggle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1multiLevelAccelerator/title",
          "value": "NSButtonTypeMultiLevelAccelerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1multiLevelAccelerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypeMultiLevelAccelerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonCell~1setButtonType(_:)/title",
          "value": "setButtonType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonCell~1setButtonType(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setButtonType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1accelerator/title",
          "value": "NSButtonTypeAccelerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1accelerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypeAccelerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1GradientType/title",
          "value": "NSGradientType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1GradientType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGradientType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1GradientType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSGradientType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1momentaryLight/title",
          "value": "NSButtonTypeMomentaryLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1momentaryLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypeMomentaryLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonCell~1gradientType/title",
          "value": "gradientType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButtonCell~1gradientType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "gradientType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1onOff/title",
          "value": "NSButtonTypeOnOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1onOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypeOnOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1momentaryChange/title",
          "value": "NSButtonTypeMomentaryChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType~1momentaryChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonTypeMomentaryChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType/title",
          "value": "NSButtonType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1ButtonType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum/title",
          "value": "NSBezelStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSButton~1BezelStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBezelStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsbutton/buttontype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsbutton/buttontype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
