{
  "abstract": [
    {
      "text": "Values that control how the framework emphasizes map features.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "MapKit",
    "externalID": "c:@E@MKStandardMapEmphasisStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "EmphasisStyle"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EmphasisStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MKStandardMapConfiguration.EmphasisStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "EmphasisStyle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapConfiguration/ElevationStyle-swift.enum": {
      "abstract": [
        {
          "text": "Values that control the map’s elevation style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ElevationStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapConfiguration/ElevationStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ElevationStyle"
        }
      ],
      "role": "symbol",
      "title": "MKMapConfiguration.ElevationStyle",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapconfiguration/elevationstyle-swift.enum"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration": {
      "abstract": [
        {
          "text": "The class that represents the default map presentation, which is a street map that shows the position of all roads and some road names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKStandardMapConfiguration"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKStandardMapConfiguration"
        }
      ],
      "role": "symbol",
      "title": "MKStandardMapConfiguration",
      "type": "topic",
      "url": "/documentation/mapkit/mkstandardmapconfiguration"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum": {
      "abstract": [
        {
          "text": "Values that control how the framework emphasizes map features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EmphasisStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EmphasisStyle"
        }
      ],
      "role": "symbol",
      "title": "MKStandardMapConfiguration.EmphasisStyle",
      "type": "topic",
      "url": "/documentation/mapkit/mkstandardmapconfiguration/emphasisstyle-swift.enum"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum/default": {
      "abstract": [
        {
          "text": "The default level of emphasis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKStandardMapEmphasisStyleDefault"
        }
      ],
      "role": "symbol",
      "title": "MKStandardMapConfiguration.EmphasisStyle.default",
      "type": "topic",
      "url": "/documentation/mapkit/mkstandardmapconfiguration/emphasisstyle-swift.enum/default"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkstandardmapconfiguration/emphasisstyle-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum/muted": {
      "abstract": [
        {
          "text": "The muted level of emphasis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "muted"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum/muted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKStandardMapEmphasisStyleMuted"
        }
      ],
      "role": "symbol",
      "title": "MKStandardMapConfiguration.EmphasisStyle.muted",
      "type": "topic",
      "url": "/documentation/mapkit/mkstandardmapconfiguration/emphasisstyle-swift.enum/muted"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init()": {
      "abstract": [
        {
          "text": "Creates a new standard map configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/mapkit/mkstandardmapconfiguration/init()"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(elevationStyle:)": {
      "abstract": [
        {
          "text": "Creates a new standard map configuration with the specified elevation style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "elevationStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapConfiguration",
          "text": "MKMapConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKMapElevationStyle",
          "text": "ElevationStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(elevationStyle:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithElevationStyle:"
        }
      ],
      "role": "symbol",
      "title": "init(elevationStyle:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkstandardmapconfiguration/init(elevationstyle:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(elevationStyle:emphasisStyle:)": {
      "abstract": [
        {
          "text": "Creates a standard map configuration with the specified elevation and emphasis styles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "elevationStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapConfiguration",
          "text": "MKMapConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKMapElevationStyle",
          "text": "ElevationStyle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "emphasisStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKStandardMapConfiguration",
          "text": "MKStandardMapConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKStandardMapEmphasisStyle",
          "text": "EmphasisStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(elevationStyle:emphasisStyle:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithElevationStyle:emphasisStyle:"
        }
      ],
      "role": "symbol",
      "title": "init(elevationStyle:emphasisStyle:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkstandardmapconfiguration/init(elevationstyle:emphasisstyle:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(emphasisStyle:)": {
      "abstract": [
        {
          "text": "Creates a standard map configuration with the specified emphasis style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "emphasisStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKStandardMapConfiguration",
          "text": "MKStandardMapConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKStandardMapEmphasisStyle",
          "text": "EmphasisStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(emphasisStyle:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithEmphasisStyle:"
        }
      ],
      "role": "symbol",
      "title": "init(emphasisStyle:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkstandardmapconfiguration/init(emphasisstyle:)"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-standard-map-configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init()",
        "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(elevationStyle:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(elevationStyle:emphasisStyle:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(emphasisStyle:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapConfiguration/ElevationStyle-swift.enum"
      ],
      "title": "Creating a standard map configuration"
    }
  ],
  "topicSections": [
    {
      "anchor": "Controlling-the-maps-emphasis",
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum/default",
        "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum/muted",
        "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum/default",
        "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum/muted"
      ],
      "title": "Controlling the map’s emphasis"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MKStandardMapEmphasisStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKStandardMapEmphasisStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKStandardMapEmphasisStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Controlling-the-maps-emphasis",
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum/default",
                "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum/muted",
                "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum/default",
                "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum/muted"
              ],
              "title": "Controlling the map’s emphasis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-standard-map-configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init()",
                "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(elevationStyle:)",
                "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(elevationStyle:emphasisStyle:)",
                "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(emphasisStyle:)",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapConfiguration/ElevationStyle-swift.enum"
              ],
              "title": "Creating a standard map configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MKStandardMapEmphasisStyle"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1EmphasisStyle-swift.enum~1muted/title",
          "value": "MKStandardMapEmphasisStyleMuted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1EmphasisStyle-swift.enum~1muted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKStandardMapEmphasisStyleMuted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1init(elevationStyle:emphasisStyle:)/title",
          "value": "initWithElevationStyle:emphasisStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1init(elevationStyle:emphasisStyle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithElevationStyle:emphasisStyle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration/title",
          "value": "MKStandardMapConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKStandardMapConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKStandardMapConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1init(emphasisStyle:)/title",
          "value": "initWithEmphasisStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1init(emphasisStyle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithEmphasisStyle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapConfiguration~1ElevationStyle-swift.enum/title",
          "value": "MKMapElevationStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapConfiguration~1ElevationStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapElevationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapConfiguration~1ElevationStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapElevationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1init(elevationStyle:)/title",
          "value": "initWithElevationStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1init(elevationStyle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithElevationStyle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1EmphasisStyle-swift.enum~1default/title",
          "value": "MKStandardMapEmphasisStyleDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1EmphasisStyle-swift.enum~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKStandardMapEmphasisStyleDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1EmphasisStyle-swift.enum/title",
          "value": "MKStandardMapEmphasisStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1EmphasisStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKStandardMapEmphasisStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1EmphasisStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKStandardMapEmphasisStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkstandardmapconfiguration/emphasisstyle-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkstandardmapconfiguration/emphasisstyle-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
