{
  "abstract": [
    {
      "text": "Creates a new standard map configuration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MKStandardMapConfiguration(im)init",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "()"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "init"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "()"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKMapConfiguration/ElevationStyle-swift.enum": {
      "abstract": [
        {
          "text": "Values that control the map’s elevation style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ElevationStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKMapConfiguration/ElevationStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ElevationStyle"
        }
      ],
      "role": "symbol",
      "title": "MKMapConfiguration.ElevationStyle",
      "type": "topic",
      "url": "/documentation/mapkit/mkmapconfiguration/elevationstyle-swift.enum"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration": {
      "abstract": [
        {
          "text": "The class that represents the default map presentation, which is a street map that shows the position of all roads and some road names.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKStandardMapConfiguration"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKStandardMapConfiguration"
        }
      ],
      "role": "symbol",
      "title": "MKStandardMapConfiguration",
      "type": "topic",
      "url": "/documentation/mapkit/mkstandardmapconfiguration"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum": {
      "abstract": [
        {
          "text": "Values that control how the framework emphasizes map features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EmphasisStyle"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EmphasisStyle"
        }
      ],
      "role": "symbol",
      "title": "MKStandardMapConfiguration.EmphasisStyle",
      "type": "topic",
      "url": "/documentation/mapkit/mkstandardmapconfiguration/emphasisstyle-swift.enum"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init()": {
      "abstract": [
        {
          "text": "Creates a new standard map configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/mapkit/mkstandardmapconfiguration/init()"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(elevationStyle:)": {
      "abstract": [
        {
          "text": "Creates a new standard map configuration with the specified elevation style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "elevationStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapConfiguration",
          "text": "MKMapConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKMapElevationStyle",
          "text": "ElevationStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(elevationStyle:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithElevationStyle:"
        }
      ],
      "role": "symbol",
      "title": "init(elevationStyle:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkstandardmapconfiguration/init(elevationstyle:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(elevationStyle:emphasisStyle:)": {
      "abstract": [
        {
          "text": "Creates a standard map configuration with the specified elevation and emphasis styles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "elevationStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapConfiguration",
          "text": "MKMapConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKMapElevationStyle",
          "text": "ElevationStyle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "emphasisStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKStandardMapConfiguration",
          "text": "MKStandardMapConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKStandardMapEmphasisStyle",
          "text": "EmphasisStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(elevationStyle:emphasisStyle:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithElevationStyle:emphasisStyle:"
        }
      ],
      "role": "symbol",
      "title": "init(elevationStyle:emphasisStyle:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkstandardmapconfiguration/init(elevationstyle:emphasisstyle:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(emphasisStyle:)": {
      "abstract": [
        {
          "text": "Creates a standard map configuration with the specified emphasis style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "emphasisStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKStandardMapConfiguration",
          "text": "MKStandardMapConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKStandardMapEmphasisStyle",
          "text": "EmphasisStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(emphasisStyle:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithEmphasisStyle:"
        }
      ],
      "role": "symbol",
      "title": "init(emphasisStyle:)",
      "type": "topic",
      "url": "/documentation/mapkit/mkstandardmapconfiguration/init(emphasisstyle:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-standard-map-configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(elevationStyle:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(elevationStyle:emphasisStyle:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(emphasisStyle:)",
        "doc://com.apple.mapkit/documentation/MapKit/MKMapConfiguration/ElevationStyle-swift.enum",
        "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum"
      ],
      "title": "Creating a standard map configuration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit",
                "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-standard-map-configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(elevationStyle:)",
                "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(elevationStyle:emphasisStyle:)",
                "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/init(emphasisStyle:)",
                "doc://com.apple.mapkit/documentation/MapKit/MKMapConfiguration/ElevationStyle-swift.enum",
                "doc://com.apple.mapkit/documentation/MapKit/MKStandardMapConfiguration/EmphasisStyle-swift.enum"
              ],
              "title": "Creating a standard map configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "init"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1init(emphasisStyle:)/title",
          "value": "initWithEmphasisStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1init(emphasisStyle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithEmphasisStyle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapConfiguration~1ElevationStyle-swift.enum/title",
          "value": "MKMapElevationStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapConfiguration~1ElevationStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapElevationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapConfiguration~1ElevationStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKMapElevationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1EmphasisStyle-swift.enum/title",
          "value": "MKStandardMapEmphasisStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1EmphasisStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKStandardMapEmphasisStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1EmphasisStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKStandardMapEmphasisStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1init(elevationStyle:)/title",
          "value": "initWithElevationStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1init(elevationStyle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithElevationStyle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration/title",
          "value": "MKStandardMapConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKStandardMapConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKStandardMapConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1init(elevationStyle:emphasisStyle:)/title",
          "value": "initWithElevationStyle:emphasisStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStandardMapConfiguration~1init(elevationStyle:emphasisStyle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithElevationStyle:emphasisStyle:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mkstandardmapconfiguration/init()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mkstandardmapconfiguration/init()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
