{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"exclusive","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","identifier":"doc://com.externally.resolved.symbol/s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["macOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true"},{"type":"text","text":" to deactivate any other color wells; "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false"},{"type":"text","text":" to keep them active. If a color panel is active with "},{"code":"exclusive","type":"codeVoice"},{"type":"text","text":" set to "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true"},{"type":"text","text":" and another is subsequently activated with "},{"code":"exclusive","type":"codeVoice"},{"type":"text","text":" set to "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false"},{"type":"text","text":", the exclusive setting of the first panel is ignored."}]}],"name":"exclusive"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When you call this method, the color well displays the standard color panel and sets the panel’s current color to the value in the color well. When someone changes the color in the color panel, the color well updates its selected color to match. If the color well’s "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorWell/isBordered","type":"reference","isActive":true},{"type":"text","text":" property is "},{"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference","isActive":true},{"type":"text","text":", the color well highlights that border while it’s active."}]}]}],"abstract":[{"text":"Activates the color well, displays the color panel, and synchronizes the two UI elements.","type":"text"}],"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"activate:"}],"modules":[{"name":"AppKit"}],"platforms":[{"name":"macOS","unavailable":false,"deprecated":false,"beta":false}],"title":"activate(_:)","externalID":"c:objc(cs)NSColorWell(im)activate:"},"seeAlsoSections":[{"title":"Activating and Deactivating Color Wells","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSColorWell/isActive","doc://com.apple.appkit/documentation/AppKit/NSColorWell/deactivate()"],"anchor":"Activating-and-Deactivating-Color-Wells","generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nscolorwell/activate(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nscolorwell/activate(_:)"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSColorWell"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSColorWell/activate(_:)"},"kind":"symbol","references":{"doc://com.apple.appkit/documentation/AppKit/NSColorWell/deactivate()":{"abstract":[{"type":"text","text":"Deactivates the color well."}],"role":"symbol","type":"topic","title":"deactivate()","url":"/documentation/appkit/nscolorwell/deactivate()","navigatorTitle":[{"text":"deactivate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deactivate"},{"kind":"text","text":"()"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorWell/deactivate()","kind":"symbol"},"doc://com.apple.documentation/documentation/swift/false":{"title":"false","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/false","role":"symbol","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","url":"/documentation/swift/false"},"doc://com.apple.appkit/documentation/AppKit/NSColorWell":{"url":"/documentation/appkit/nscolorwell","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSColorWell"}],"title":"NSColorWell","identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorWell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSColorWell"}],"abstract":[{"text":"A control that displays a color value and lets the user change that color value.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.apple.appkit/documentation/AppKit/NSColorWell/isActive":{"abstract":[{"type":"text","text":"A Boolean value that indicates whether the color well is currently active."}],"role":"symbol","type":"topic","title":"isActive","url":"/documentation/appkit/nscolorwell/isactive","navigatorTitle":[{"kind":"identifier","text":"active"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isActive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorWell/isActive","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSColorWell/isBordered":{"role":"symbol","deprecated":true,"type":"topic","kind":"symbol","abstract":[{"text":"A Boolean value that determines whether the color well has a border.","type":"text"}],"title":"isBordered","identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorWell/isBordered","url":"/documentation/appkit/nscolorwell/isbordered","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isBordered"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"bordered"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSColorWell/activate(_:)":{"abstract":[{"type":"text","text":"Activates the color well, displays the color panel, and synchronizes the two UI elements."}],"role":"symbol","type":"topic","title":"activate(_:)","url":"/documentation/appkit/nscolorwell/activate(_:)","navigatorTitle":[{"text":"activate:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"activate"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorWell/activate(_:)","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"beta":false,"name":"macOS","unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"activate:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"activate:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSColorWell"]]},"path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSColorWell/isActive","doc://com.apple.appkit/documentation/AppKit/NSColorWell/deactivate()"],"anchor":"Activating-and-Deactivating-Color-Wells","title":"Activating and Deactivating Color Wells"}],"op":"replace","path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"activate:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"exclusive"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"value":{"parameters":[{"name":"exclusive","content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true},{"type":"text","text":" to deactivate any other color wells; "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false","isActive":true},{"type":"text","text":" to keep them active. If a color panel is active with "},{"type":"codeVoice","code":"exclusive"},{"type":"text","text":" set to "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true},{"type":"text","text":" and another is subsequently activated with "},{"type":"codeVoice","code":"exclusive"},{"type":"text","text":" set to "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false"},{"type":"text","text":", the exclusive setting of the first panel is ignored."}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"/primaryContentSections/1"},{"op":"replace","value":"deactivate","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell~1deactivate()/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deactivate"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell~1deactivate()/fragments"},{"op":"replace","value":"NSColorWell","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSColorWell"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSColorWell"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell/navigatorTitle"},{"op":"replace","value":"active","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell~1isActive/title"},{"op":"replace","value":[{"kind":"identifier","text":"active"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell~1isActive/fragments"},{"op":"replace","value":"bordered","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell~1isBordered/title"},{"op":"replace","value":[{"kind":"identifier","text":"bordered"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell~1isBordered/fragments"},{"value":"activate:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell~1activate(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"activate:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell~1activate(_:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}