{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"drawWell"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inside"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","text":"NSRect"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","title":"drawWell(inside:)","navigatorTitle":[{"kind":"identifier","text":"drawWellInside:"}],"platforms":[{"unavailable":false,"beta":false,"name":"macOS","deprecated":false}],"externalID":"c:objc(cs)NSColorWell(im)drawWellInside:","role":"symbol","symbolKind":"method","modules":[{"name":"AppKit"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSColorWell"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSColorWell/drawWell(inside:)"},"kind":"symbol","abstract":[{"text":"Draws the area inside the color well at the specified location without drawing borders.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drawWell","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inside","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"insideRect","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSRect","text":"NSRect","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The rectangle specifying the area within which to draw."}]}],"name":"insideRect"}],"kind":"parameters"}],"variants":[{"paths":["/documentation/appkit/nscolorwell/drawwell(inside:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nscolorwell/drawwell(inside:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSColorWell/drawWell(inside:)":{"title":"drawWell(inside:)","role":"symbol","url":"/documentation/appkit/nscolorwell/drawwell(inside:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorWell/drawWell(inside:)","abstract":[{"type":"text","text":"Draws the area inside the color well at the specified location without drawing borders."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"drawWell","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inside","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRect","text":"NSRect"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"drawWellInside:"}]},"doc://com.apple.appkit/documentation/AppKit/NSColorWell":{"url":"/documentation/appkit/nscolorwell","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSColorWell"}],"title":"NSColorWell","identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorWell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSColorWell"}],"abstract":[{"text":"A control that displays a color value and lets the user change that color value.","type":"text"}]},"doc://com.externally.resolved.symbol/c:@T@NSRect":{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","role":"symbol","type":"topic","url":"/documentation/foundation/nsrect","abstract":[{"text":"A rectangle.","type":"text"}],"fragments":[{"text":"typealias ","kind":"text"},{"text":"NSRect","kind":"identifier"}],"title":"NSRect","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"macOS","deprecated":false,"beta":false,"unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"drawWellInside:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"drawWellInside:"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSColorWell"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"add","value":null},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"drawWellInside:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSRect","identifier":"doc://com.externally.resolved.symbol/c:@T@NSRect","preciseIdentifier":"c:@T@NSRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"insideRect"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}]}},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The rectangle specifying the area within which to draw."}],"type":"paragraph"}],"name":"insideRect"}],"kind":"parameters"},"path":"/primaryContentSections/1","op":"replace"},{"value":"drawWellInside:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell~1drawWell(inside:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"drawWellInside:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell~1drawWell(inside:)/fragments","op":"replace"},{"value":"NSColorWell","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell/title","op":"replace"},{"value":[{"text":"NSColorWell","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell/fragments","op":"replace"},{"value":[{"text":"NSColorWell","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell/navigatorTitle","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}