{"sections":[],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSColorWell/init(style:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"init","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSColorWell","kind":"typeIdentifier","text":"NSColorWell"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSColorWellStyle","kind":"typeIdentifier","text":"Style"},{"kind":"text","text":")"}],"roleHeading":"Initializer","externalID":"c:objc(cs)NSColorWell(cm)colorWellWithStyle:","title":"init(style:)","modules":[{"name":"AppKit"}],"navigatorTitle":[{"kind":"identifier","text":"colorWellWithStyle:"}],"platforms":[{"beta":false,"deprecated":false,"unavailable":false,"name":"macOS","introducedAt":"13.0"}],"role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSColorWell"]]},"abstract":[{"type":"text","text":"Creates a color well that adopts the specified appearance style."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorWell","preciseIdentifier":"c:objc(cs)NSColorWell","kind":"typeIdentifier","text":"NSColorWell"},{"kind":"text","text":"."},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorWell/Style","preciseIdentifier":"c:@E@NSColorWellStyle","kind":"typeIdentifier","text":"Style"},{"kind":"text","text":")"}],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"name":"style","content":[{"type":"paragraph","inlineContent":[{"text":"The style to use to configure the color well control. For a list of possible values, see ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorWell/Style","isActive":true,"type":"reference"},{"text":".","type":"text"}]}]}]},{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"text":"A color well configured with the specified style.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nscolorwell/init(style:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nscolorwell/init(style:)"]}],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSColorWell":{"url":"/documentation/appkit/nscolorwell","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSColorWell"}],"title":"NSColorWell","identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorWell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSColorWell"}],"abstract":[{"text":"A control that displays a color value and lets the user change that color value.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSColorWell/init(style:)":{"abstract":[{"type":"text","text":"Creates a color well that adopts the specified appearance style."}],"fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSColorWell","preciseIdentifier":"c:objc(cs)NSColorWell"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSColorWellStyle","kind":"typeIdentifier","text":"Style"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorWell/init(style:)","url":"/documentation/appkit/nscolorwell/init(style:)","title":"init(style:)","navigatorTitle":[{"kind":"identifier","text":"colorWellWithStyle:"}],"role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSColorWell/Style":{"url":"/documentation/appkit/nscolorwell/style","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Style"}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Style"}],"title":"NSColorWell.Style","identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorWell/Style","abstract":[{"text":"Constants that specify the appearance and interaction modes for a color well.","type":"text"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"macOS","deprecated":false,"introducedAt":"13.0","beta":false,"unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Type Method","path":"/metadata/roleHeading","op":"replace"},{"value":"colorWellWithStyle:","path":"/metadata/title","op":"replace"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"+ ","kind":"text"},{"text":"colorWellWithStyle:","kind":"identifier"}]},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSColorWell"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"colorWellWithStyle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSColorWellStyle","identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorWell/Style","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSColorWellStyle"},{"text":") ","kind":"text"},{"text":"style","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"style","content":[{"inlineContent":[{"text":"The style to use to configure the color well control. For a list of possible values, see ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorWell/Style"},{"text":".","type":"text"}],"type":"paragraph"}]}]},"op":"replace"},{"op":"replace","path":"/primaryContentSections/2","value":{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A color well configured with the specified style."}]}],"kind":"content"}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell/title","value":"NSColorWell","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell/fragments","value":[{"text":"NSColorWell","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell/navigatorTitle","value":[{"text":"NSColorWell","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell~1init(style:)/title","value":"colorWellWithStyle:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell~1init(style:)/fragments","value":[{"text":"+ ","kind":"text"},{"text":"colorWellWithStyle:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell~1Style/title","value":"NSColorWellStyle","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell~1Style/fragments","value":[{"text":"NSColorWellStyle","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell~1Style/navigatorTitle","value":[{"text":"NSColorWellStyle","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}