{"variants":[{"paths":["/documentation/appkit/nscolorwell/takecolorfrom(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nscolorwell/takecolorfrom(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"title":"Managing the Selected Color","anchor":"Managing-the-Selected-Color","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSColorWell/color","doc://com.apple.appkit/documentation/AppKit/NSColorWell/supportsAlpha"],"generated":true}],"abstract":[{"text":"Changes the currently selected color to the color of the specified object.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"takeColorFrom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"sender","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"sender","content":[{"inlineContent":[{"text":"The object from which to take the new color.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"This method attempts to access a property or accessor method named ","type":"text"},{"type":"codeVoice","code":"color"},{"text":". If the object doesn’t implement a ","type":"text"},{"type":"codeVoice","code":"color"},{"text":" accessor, this method does nothing.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSColorWell/takeColorFrom(_:)","interfaceLanguage":"swift"},"metadata":{"title":"takeColorFrom(_:)","navigatorTitle":[{"kind":"identifier","text":"takeColorFrom:"}],"externalID":"c:objc(cs)NSColorWell(im)takeColorFrom:","modules":[{"name":"AppKit"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"takeColorFrom"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS"}]},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSColorWell"]]},"sections":[],"references":{"doc://com.apple.appkit/documentation/AppKit/NSColorWell/color":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"color"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSColor","kind":"typeIdentifier","text":"NSColor"}],"type":"topic","abstract":[{"type":"text","text":"The currently selected color for the color well."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"color"}],"url":"/documentation/appkit/nscolorwell/color","role":"symbol","title":"color","identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorWell/color"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSColorWell/supportsAlpha":{"type":"topic","navigatorTitle":[{"text":"supportsAlpha","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"supportsAlpha","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"/documentation/appkit/nscolorwell/supportsalpha","identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorWell/supportsAlpha","title":"supportsAlpha","abstract":[{"text":"A Boolean value that determines whether the color picker supports alpha values.","type":"text"}],"kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSColorWell/takeColorFrom(_:)":{"url":"/documentation/appkit/nscolorwell/takecolorfrom(_:)","kind":"symbol","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorWell/takeColorFrom(_:)","abstract":[{"text":"Changes the currently selected color to the color of the specified object.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"takeColorFrom:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"takeColorFrom"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"title":"takeColorFrom(_:)"},"doc://com.apple.appkit/documentation/AppKit/NSColorWell":{"url":"/documentation/appkit/nscolorwell","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSColorWell"}],"title":"NSColorWell","identifier":"doc://com.apple.appkit/documentation/AppKit/NSColorWell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSColorWell"}],"abstract":[{"text":"A control that displays a color value and lets the user change that color value.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"beta":false,"deprecated":false,"name":"macOS","unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"value":"takeColorFrom:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"takeColorFrom:"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSColorWell"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"anchor":"Managing-the-Selected-Color","title":"Managing the Selected Color","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSColorWell/color","doc://com.apple.appkit/documentation/AppKit/NSColorWell/supportsAlpha"]}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"takeColorFrom:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"sender"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"]}]}},{"value":{"kind":"parameters","parameters":[{"name":"sender","content":[{"inlineContent":[{"type":"text","text":"The object from which to take the new color."}],"type":"paragraph"}]}]},"op":"replace","path":"/primaryContentSections/1"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell~1color/title","op":"replace","value":"color"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell~1color/fragments","op":"replace","value":[{"kind":"identifier","text":"color"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell~1supportsAlpha/title","op":"replace","value":"supportsAlpha"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell~1supportsAlpha/fragments","op":"replace","value":[{"kind":"identifier","text":"supportsAlpha"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell~1takeColorFrom(_:)/title","op":"replace","value":"takeColorFrom:"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell~1takeColorFrom(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"takeColorFrom:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell/title","op":"replace","value":"NSColorWell"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell/fragments","op":"replace","value":[{"kind":"identifier","text":"NSColorWell"}]},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSColorWell/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSColorWell"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}