{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UICollectionView/allowsMultipleSelection"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uicollectionview/allowsmultipleselection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uicollectionview/allowsmultipleselection"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsMultipleSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"mentions":["doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app"],"kind":"mentions"},{"kind":"content","content":[{"anchor":"Discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This property controls whether multiple items can be selected simultaneously. The default value of this property is "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false","isActive":true},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the value of this property is "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true"},{"type":"text","text":", tapping a cell adds it to the current selection (assuming the delegate permits the cell to be selected). Tapping the cell again removes it from the selection."}]}]}],"abstract":[{"type":"text","text":"A Boolean value that determines whether users can select more than one item in the collection view."}],"metadata":{"title":"allowsMultipleSelection","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"UIKit"}],"externalID":"c:objc(cs)UICollectionView(py)allowsMultipleSelection","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowsMultipleSelection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":[{"beta":false,"name":"iOS","unavailable":false,"introducedAt":"6.0","deprecated":false},{"beta":false,"name":"iPadOS","unavailable":false,"introducedAt":"6.0","deprecated":false},{"beta":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1","deprecated":false},{"beta":false,"name":"tvOS","unavailable":false,"deprecated":false},{"beta":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0","deprecated":false}],"navigatorTitle":[{"text":"allowsMultipleSelection","kind":"identifier"}]},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UICollectionView"]]},"seeAlsoSections":[{"anchor":"Selecting-cells","identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionView/indexPathsForSelectedItems","doc://com.apple.uikit/documentation/UIKit/UICollectionView/selectItem(at:animated:scrollPosition:)","doc://com.apple.uikit/documentation/UIKit/UICollectionView/deselectItem(at:animated:)","doc://com.apple.uikit/documentation/UIKit/UICollectionView/allowsSelection","doc://com.apple.uikit/documentation/UIKit/UICollectionView/allowsSelectionDuringEditing","doc://com.apple.uikit/documentation/UIKit/UICollectionView/allowsMultipleSelectionDuringEditing","doc://com.apple.uikit/documentation/UIKit/UICollectionView/selectionFollowsFocus"],"generated":true,"title":"Selecting cells"}],"sections":[],"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICollectionView/deselectItem(at:animated:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deselectItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"text":", ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"deselectItem(at:animated:)","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView/deselectItem(at:animated:)","role":"symbol","navigatorTitle":[{"text":"deselectItemAtIndexPath:animated:","kind":"identifier"}],"url":"/documentation/uikit/uicollectionview/deselectitem(at:animated:)","type":"topic","abstract":[{"type":"text","text":"Deselects the item at the specified index."}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionView/allowsMultipleSelection":{"title":"allowsMultipleSelection","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView/allowsMultipleSelection","abstract":[{"type":"text","text":"A Boolean value that determines whether users can select more than one item in the collection view."}],"role":"symbol","type":"topic","url":"/documentation/uikit/uicollectionview/allowsmultipleselection","kind":"symbol","navigatorTitle":[{"text":"allowsMultipleSelection","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowsMultipleSelection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionView/selectionFollowsFocus":{"role":"symbol","url":"/documentation/uikit/uicollectionview/selectionfollowsfocus","abstract":[{"type":"text","text":"A Boolean value that triggers an automatic selection when focus moves to a cell."}],"title":"selectionFollowsFocus","type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView/selectionFollowsFocus","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"selectionFollowsFocus","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"selectionFollowsFocus","kind":"identifier"}]},"doc://com.apple.documentation/documentation/swift/false":{"role":"symbol","url":"/documentation/swift/false","title":"false","identifier":"doc://com.apple.documentation/documentation/swift/false","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","url":"/documentation/Swift/Bool","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"title":"Bool"},"doc://com.apple.uikit/documentation/UIKit/UICollectionView/selectItem(at:animated:scrollPosition:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":"?, ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"scrollPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":".","kind":"text"},{"text":"ScrollPosition","kind":"typeIdentifier","preciseIdentifier":"c:@E@UICollectionViewScrollPosition"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Selects the item at the specified index path and optionally scrolls it into view."}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView/selectItem(at:animated:scrollPosition:)","navigatorTitle":[{"text":"selectItemAtIndexPath:animated:scrollPosition:","kind":"identifier"}],"title":"selectItem(at:animated:scrollPosition:)","kind":"symbol","type":"topic","url":"/documentation/uikit/uicollectionview/selectitem(at:animated:scrollposition:)"},"doc://com.apple.documentation/documentation/swift/true":{"abstract":[{"text":"A true value.","type":"text"}],"role":"symbol","url":"/documentation/swift/true","identifier":"doc://com.apple.documentation/documentation/swift/true","type":"topic","title":"true","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UICollectionView/allowsMultipleSelectionDuringEditing":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsMultipleSelectionDuringEditing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"allowsMultipleSelectionDuringEditing"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView/allowsMultipleSelectionDuringEditing","role":"symbol","type":"topic","url":"/documentation/uikit/uicollectionview/allowsmultipleselectionduringediting","title":"allowsMultipleSelectionDuringEditing","abstract":[{"text":"A Boolean value that controls whether users can select more than one cell simultaneously in editing mode.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionView/allowsSelectionDuringEditing":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsSelectionDuringEditing"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"allowsSelectionDuringEditing","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView/allowsSelectionDuringEditing","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"allowsSelectionDuringEditing"}],"url":"/documentation/uikit/uicollectionview/allowsselectionduringediting","type":"topic","abstract":[{"type":"text","text":"A Boolean value that determines whether users can select cells while the collection view is in editing mode."}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionView":{"navigatorTitle":[{"text":"UICollectionView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionView","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/uicollectionview","title":"UICollectionView","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An object that manages an ordered collection of data items and presents them using customizable layouts."}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionView/allowsSelection":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"allowsSelection"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView/allowsSelection","role":"symbol","type":"topic","url":"/documentation/uikit/uicollectionview/allowsselection","title":"allowsSelection","abstract":[{"text":"A Boolean value that indicates whether users can select items in the collection view.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app":{"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app","abstract":[{"text":"Optimize your iPad app’s user experience by adopting desktop-class enhancements for multitasking with Stage Manager, document interactions, text editing, search, and more in iPadOS 16.","type":"text"}],"kind":"article","url":"/documentation/uikit/building-a-desktop-class-ipad-app","title":"Building a desktop-class iPad app","role":"article"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"abstract":[{"text":"Type to represent a Boolean value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","url":"/documentation/objectivec/bool","kind":"symbol","type":"topic","title":"BOOL"},"doc://com.apple.uikit/documentation/UIKit/UICollectionView/indexPathsForSelectedItems":{"role":"symbol","type":"topic","abstract":[{"text":"The index paths for the selected items.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"indexPathsForSelectedItems"}],"title":"indexPathsForSelectedItems","url":"/documentation/uikit/uicollectionview/indexpathsforselecteditems","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPathsForSelectedItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":"]?"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView/indexPathsForSelectedItems"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"introducedAt":"6.0","name":"iOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"6.0","name":"iPadOS","beta":false,"deprecated":false,"unavailable":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1"},{"unavailable":false,"beta":false,"name":"tvOS","deprecated":false},{"unavailable":false,"beta":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","value":"allowsMultipleSelection","op":"replace"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"allowsMultipleSelection"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UICollectionView"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"title":"Selecting cells","identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionView/indexPathsForSelectedItems","doc://com.apple.uikit/documentation/UIKit/UICollectionView/selectItem(at:animated:scrollPosition:)","doc://com.apple.uikit/documentation/UIKit/UICollectionView/deselectItem(at:animated:)","doc://com.apple.uikit/documentation/UIKit/UICollectionView/allowsSelection","doc://com.apple.uikit/documentation/UIKit/UICollectionView/allowsSelectionDuringEditing","doc://com.apple.uikit/documentation/UIKit/UICollectionView/allowsMultipleSelectionDuringEditing","doc://com.apple.uikit/documentation/UIKit/UICollectionView/selectionFollowsFocus"],"anchor":"Selecting-cells"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsMultipleSelection"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":"deselectItemAtIndexPath:animated:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1deselectItem(at:animated:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"deselectItemAtIndexPath:animated:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1deselectItem(at:animated:)/fragments"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1allowsMultipleSelection/title","op":"replace","value":"allowsMultipleSelection"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1allowsMultipleSelection/fragments","op":"replace","value":[{"text":"allowsMultipleSelection","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1selectionFollowsFocus/title","op":"replace","value":"selectionFollowsFocus"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1selectionFollowsFocus/fragments","op":"replace","value":[{"kind":"identifier","text":"selectionFollowsFocus"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1selectItem(at:animated:scrollPosition:)/title","op":"replace","value":"selectItemAtIndexPath:animated:scrollPosition:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1selectItem(at:animated:scrollPosition:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"selectItemAtIndexPath:animated:scrollPosition:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1allowsMultipleSelectionDuringEditing/title","op":"replace","value":"allowsMultipleSelectionDuringEditing"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1allowsMultipleSelectionDuringEditing/fragments","op":"replace","value":[{"kind":"identifier","text":"allowsMultipleSelectionDuringEditing"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1allowsSelectionDuringEditing/title","op":"replace","value":"allowsSelectionDuringEditing"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1allowsSelectionDuringEditing/fragments","op":"replace","value":[{"text":"allowsSelectionDuringEditing","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/title","op":"replace","value":"UICollectionView"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/fragments","op":"replace","value":[{"kind":"identifier","text":"UICollectionView"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UICollectionView"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1allowsSelection/title","op":"replace","value":"allowsSelection"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1allowsSelection/fragments","op":"replace","value":[{"kind":"identifier","text":"allowsSelection"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1indexPathsForSelectedItems/title","op":"replace","value":"indexPathsForSelectedItems"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1indexPathsForSelectedItems/fragments","op":"replace","value":[{"text":"indexPathsForSelectedItems","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}