{"metadata":{"platforms":[{"beta":false,"name":"iOS","unavailable":false,"introducedAt":"6.0","deprecated":false},{"beta":false,"name":"iPadOS","unavailable":false,"introducedAt":"6.0","deprecated":false},{"beta":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1","deprecated":false},{"beta":false,"name":"tvOS","unavailable":false,"deprecated":false},{"beta":false,"name":"visionOS","unavailable":false,"introducedAt":"1.0","deprecated":false}],"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"UIKit"}],"title":"cellForItem(at:)","externalID":"c:objc(cs)UICollectionView(im)cellForItemAtIndexPath:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellForItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":") -> ","kind":"text"},{"text":"UICollectionViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewCell"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"cellForItemAtIndexPath:","kind":"identifier"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UICollectionView"]]},"seeAlsoSections":[{"anchor":"Locating-items-and-views-in-the-collection-view","title":"Locating items and views in the collection view","identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionView/indexPathForItem(at:)","doc://com.apple.uikit/documentation/UIKit/UICollectionView/indexPathsForVisibleItems","doc://com.apple.uikit/documentation/UIKit/UICollectionView/indexPath(for:)","doc://com.apple.uikit/documentation/UIKit/UICollectionView/indexPathsForVisibleSupplementaryElements(ofKind:)","doc://com.apple.uikit/documentation/UIKit/UICollectionView/supplementaryView(forElementKind:at:)","doc://com.apple.uikit/documentation/UIKit/UICollectionView/visibleSupplementaryViews(ofKind:)"],"generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellForItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:10Foundation9IndexPathV"},{"text":") -> ","kind":"text"},{"text":"UICollectionViewCell","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"},{"text":"?","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The index path that specifies the section and item number of the cell.","type":"text"}],"type":"paragraph"}],"name":"indexPath"}]},{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The cell object at the corresponding index path. In versions of iOS earlier than iOS 15, this method returns ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if the cell isn’t visible or if ","type":"text"},{"code":"indexPath","type":"codeVoice"},{"text":" is out of range. In iOS 15 and later, this method returns a non-","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" cell if the collection view retains a prepared cell at the specified index path, even if the cell isn’t currently visible.","type":"text"}]}],"kind":"content"},{"content":[{"type":"heading","text":"Discussion","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"In iOS 15 and later, the collection view retains a prepared cell in the following situations:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Cells that the collection view prefetches and retains in its cache of prepared cells, but that aren’t visible because the collection view hasn’t displayed them yet."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Cells that the collection view finishes displaying and continues to retain in its cache of prepared cells because they remain near the visible region and might scroll back into view."}]}]},{"content":[{"inlineContent":[{"text":"The cell that contains the first responder.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The cell that has focus.","type":"text"}],"type":"paragraph"}]}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Gets the cell object at the index path you specify."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UICollectionView/cellForItem(at:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uicollectionview/cellforitem(at:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uicollectionview/cellforitem(at:)"]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell":{"kind":"symbol","title":"UICollectionViewCell","abstract":[{"type":"text","text":"A single data item when that item is within the collection view’s visible bounds."}],"url":"/documentation/uikit/uicollectionviewcell","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UICollectionViewCell"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UICollectionViewCell"}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionView/indexPathForItem(at:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPathForItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Gets the index path of the item at the specified point in the collection view."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView/indexPathForItem(at:)","role":"symbol","url":"/documentation/uikit/uicollectionview/indexpathforitem(at:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"indexPathForItemAtPoint:"}],"type":"topic","title":"indexPathForItem(at:)"},"doc://com.apple.uikit/documentation/UIKit/UICollectionView/visibleSupplementaryViews(ofKind:)":{"role":"symbol","url":"/documentation/uikit/uicollectionview/visiblesupplementaryviews(ofkind:)","abstract":[{"text":"Gets an array of the visible supplementary views of the specified kind.","type":"text"}],"type":"topic","title":"visibleSupplementaryViews(ofKind:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visibleSupplementaryViews","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ofKind","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionReusableView","text":"UICollectionReusableView","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"visibleSupplementaryViewsOfKind:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView/visibleSupplementaryViews(ofKind:)","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UICollectionView":{"navigatorTitle":[{"text":"UICollectionView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionView","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/uicollectionview","title":"UICollectionView","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An object that manages an ordered collection of data items and presents them using customizable layouts."}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionView/cellForItem(at:)":{"title":"cellForItem(at:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cellForItemAtIndexPath:"}],"abstract":[{"type":"text","text":"Gets the cell object at the index path you specify."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView/cellForItem(at:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellForItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UICollectionViewCell","kind":"typeIdentifier","text":"UICollectionViewCell"},{"kind":"text","text":"?"}],"kind":"symbol","url":"/documentation/uikit/uicollectionview/cellforitem(at:)"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UICollectionView/supplementaryView(forElementKind:at:)":{"abstract":[{"type":"text","text":"Gets the supplementary view at the specified index path."}],"type":"topic","title":"supplementaryView(forElementKind:at:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"supplementaryViewForElementKind:atIndexPath:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"supplementaryView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forElementKind"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionReusableView","text":"UICollectionReusableView"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView/supplementaryView(forElementKind:at:)","url":"/documentation/uikit/uicollectionview/supplementaryview(forelementkind:at:)","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UICollectionView/indexPathsForVisibleSupplementaryElements(ofKind:)":{"navigatorTitle":[{"text":"indexPathsForVisibleSupplementaryElementsOfKind:","kind":"identifier"}],"title":"indexPathsForVisibleSupplementaryElements(ofKind:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexPathsForVisibleSupplementaryElements","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ofKind","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"Gets the index paths of all visible supplementary views of the specified type."}],"url":"/documentation/uikit/uicollectionview/indexpathsforvisiblesupplementaryelements(ofkind:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView/indexPathsForVisibleSupplementaryElements(ofKind:)"},"doc://com.apple.uikit/documentation/UIKit/UICollectionView/indexPathsForVisibleItems":{"abstract":[{"text":"An array of the visible items in the collection view.","type":"text"}],"url":"/documentation/uikit/uicollectionview/indexpathsforvisibleitems","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView/indexPathsForVisibleItems","title":"indexPathsForVisibleItems","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexPathsForVisibleItems","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"indexPathsForVisibleItems","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/s:10Foundation9IndexPathV":{"role":"symbol","url":"/documentation/foundation/indexpath","abstract":[{"type":"text","text":"A list of indexes that together represent the path to a specific location in a tree of nested arrays. "}],"type":"topic","title":"IndexPath","fragments":[{"text":"struct ","kind":"text"},{"text":"IndexPath","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:10Foundation9IndexPathV","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UICollectionView/indexPath(for:)":{"navigatorTitle":[{"kind":"identifier","text":"indexPathForCell:"}],"title":"indexPath(for:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UICollectionViewCell","kind":"typeIdentifier","text":"UICollectionViewCell"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Gets the index path of the specified cell."}],"url":"/documentation/uikit/uicollectionview/indexpath(for:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView/indexPath(for:)"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/c:objc(cs)NSIndexPath":{"abstract":[{"type":"text","text":"An object containing a list of indexes that bridges to ; use  when you need reference semantics or other Foundation-specific behavior."}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSIndexPath","url":"/documentation/foundation/nsindexpath","kind":"symbol","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSIndexPath"}],"role":"symbol","title":"NSIndexPath","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"beta":false,"unavailable":false,"name":"iOS","introducedAt":"6.0"},{"deprecated":false,"beta":false,"unavailable":false,"name":"iPadOS","introducedAt":"6.0"},{"deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"deprecated":false,"beta":false,"unavailable":false,"name":"tvOS"},{"deprecated":false,"beta":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"path":"/metadata/title","value":"cellForItemAtIndexPath:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"cellForItemAtIndexPath:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UICollectionView"]]},"op":"replace"},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionView/indexPathForItem(at:)","doc://com.apple.uikit/documentation/UIKit/UICollectionView/indexPathsForVisibleItems","doc://com.apple.uikit/documentation/UIKit/UICollectionView/indexPath(for:)","doc://com.apple.uikit/documentation/UIKit/UICollectionView/indexPathsForVisibleSupplementaryElements(ofKind:)","doc://com.apple.uikit/documentation/UIKit/UICollectionView/supplementaryView(forElementKind:at:)","doc://com.apple.uikit/documentation/UIKit/UICollectionView/visibleSupplementaryViews(ofKind:)"],"anchor":"Locating-items-and-views-in-the-collection-view","title":"Locating items and views in the collection view"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionViewCell","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell","text":"UICollectionViewCell","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cellForItemAtIndexPath:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSIndexPath","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSIndexPath","text":"NSIndexPath","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}]}},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The index path that specifies the section and item number of the cell.","type":"text"}],"type":"paragraph"}],"name":"indexPath"}]},"path":"/primaryContentSections/1"},{"path":"/primaryContentSections/2","op":"replace","value":{"content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"The cell object at the corresponding index path. In versions of iOS earlier than iOS 15, this method returns ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if the cell isn’t visible or if ","type":"text"},{"code":"indexPath","type":"codeVoice"},{"text":" is out of range. In iOS 15 and later, this method returns a non-","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" cell if the collection view retains a prepared cell at the specified index path, even if the cell isn’t currently visible.","type":"text"}],"type":"paragraph"}],"kind":"content"}},{"op":"replace","value":"UICollectionViewCell","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCell/title"},{"op":"replace","value":[{"text":"UICollectionViewCell","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCell/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UICollectionViewCell"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCell/navigatorTitle"},{"op":"replace","value":"indexPathForItemAtPoint:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1indexPathForItem(at:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexPathForItemAtPoint:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1indexPathForItem(at:)/fragments"},{"op":"replace","value":"visibleSupplementaryViewsOfKind:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1visibleSupplementaryViews(ofKind:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"visibleSupplementaryViewsOfKind:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1visibleSupplementaryViews(ofKind:)/fragments"},{"op":"replace","value":"UICollectionView","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/title"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/fragments","value":[{"kind":"identifier","text":"UICollectionView"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/navigatorTitle","value":[{"kind":"identifier","text":"UICollectionView"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1cellForItem(at:)/title","value":"cellForItemAtIndexPath:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1cellForItem(at:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"cellForItemAtIndexPath:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1supplementaryView(forElementKind:at:)/title","value":"supplementaryViewForElementKind:atIndexPath:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1supplementaryView(forElementKind:at:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"supplementaryViewForElementKind:atIndexPath:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1indexPathsForVisibleSupplementaryElements(ofKind:)/title","value":"indexPathsForVisibleSupplementaryElementsOfKind:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1indexPathsForVisibleSupplementaryElements(ofKind:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"indexPathsForVisibleSupplementaryElementsOfKind:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1indexPathsForVisibleItems/title","value":"indexPathsForVisibleItems"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1indexPathsForVisibleItems/fragments","value":[{"text":"indexPathsForVisibleItems","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1indexPath(for:)/title","value":"indexPathForCell:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1indexPath(for:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"indexPathForCell:"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSIndexPath/abstract","value":[{"text":"A list of indexes that together represent the path to a specific location in a tree of nested arrays.","type":"text"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}