{
  "abstract": [
    {
      "text": "An event type for switching portamento on or off.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/portamento"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVMIDIControlChangeMessageType@AVMIDIControlChangeMessageTypePortamento",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "portamento"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVMIDIControlChangeMessageTypePortamento"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AVMIDIControlChangeEvent.MessageType.portamento"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "portamento"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent": {
      "abstract": [
        {
          "text": "An object that represents a MIDI control change message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeEvent"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum": {
      "abstract": [
        {
          "text": "Constants that represents control change event types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MessageType"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MessageType"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/balance": {
      "abstract": [
        {
          "text": "An event type for controlling the left and right channel balance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "balance"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/balance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeBalance"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.balance",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/balance"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/bankSelect": {
      "abstract": [
        {
          "text": "An event type for switching bank selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bankSelect"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/bankSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeBankSelect"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.bankSelect",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/bankselect"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/breath": {
      "abstract": [
        {
          "text": "An event type for a breath controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "breath"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/breath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeBreath"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.breath",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/breath"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/dataEntry": {
      "abstract": [
        {
          "text": "An event type for controlling the data entry parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataEntry"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/dataEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeDataEntry"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.dataEntry",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/dataentry"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/expression": {
      "abstract": [
        {
          "text": "An event type that represents an expression controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expression"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/expression",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeExpression"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.expression",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/expression"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/foot": {
      "abstract": [
        {
          "text": "An event type for sending continuous stream of values when using a foot controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "foot"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/foot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeFoot"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.foot",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/foot"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/hold2Pedal": {
      "abstract": [
        {
          "text": "An event type for holding notes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hold2Pedal"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/hold2Pedal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeHold2Pedal"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.hold2Pedal",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/hold2pedal"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/legatoPedal": {
      "abstract": [
        {
          "text": "An event type for switching the legato pedal on or off.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "legatoPedal"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/legatoPedal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeLegatoPedal"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.legatoPedal",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/legatopedal"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/modWheel": {
      "abstract": [
        {
          "text": "An event type for modulating a vibrato effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modWheel"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/modWheel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeModWheel"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.modWheel",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/modwheel"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/pan": {
      "abstract": [
        {
          "text": "An event type for controlling the left and right channel pan.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pan"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/pan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypePan"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.pan",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/pan"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/portamento": {
      "abstract": [
        {
          "text": "An event type for switching portamento on or off.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "portamento"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/portamento",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypePortamento"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.portamento",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/portamento"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/portamentoTime": {
      "abstract": [
        {
          "text": "An event type for controlling the portamento rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "portamentoTime"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/portamentoTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypePortamentoTime"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.portamentoTime",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/portamentotime"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/soft": {
      "abstract": [
        {
          "text": "An event type for lowering the volume of the notes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "soft"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/soft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeSoft"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.soft",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/soft"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/sostenuto": {
      "abstract": [
        {
          "text": "An event type for switching sostenuto on or off.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sostenuto"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/sostenuto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeSostenuto"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.sostenuto",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/sostenuto"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/sustain": {
      "abstract": [
        {
          "text": "An event type for switching a damper pedal on or off.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sustain"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/sustain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeSustain"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.sustain",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/sustain"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/volume": {
      "abstract": [
        {
          "text": "An event type for controlling the channel volume.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "volume"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/volume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeVolume"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.volume",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/volume"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Event-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/bankSelect",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/modWheel",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/breath",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/foot",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/portamentoTime",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/dataEntry",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/volume",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/balance",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/pan",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/expression",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/sustain",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/sostenuto",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/soft",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/legatoPedal",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/hold2Pedal"
      ],
      "title": "Event Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVMIDIControlChangeMessageTypePortamento"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypePortamento"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Event-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/bankSelect",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/modWheel",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/breath",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/foot",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/portamentoTime",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/dataEntry",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/volume",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/balance",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/pan",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/expression",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/sustain",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/sostenuto",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/soft",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/legatoPedal",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/hold2Pedal"
              ],
              "title": "Event Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVMIDIControlChangeMessageTypePortamento"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum/title",
          "value": "AVMIDIControlChangeMessageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1breath/title",
          "value": "AVMIDIControlChangeMessageTypeBreath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1breath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeBreath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1dataEntry/title",
          "value": "AVMIDIControlChangeMessageTypeDataEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1dataEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeDataEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent/title",
          "value": "AVMIDIControlChangeEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1bankSelect/title",
          "value": "AVMIDIControlChangeMessageTypeBankSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1bankSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeBankSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1portamentoTime/title",
          "value": "AVMIDIControlChangeMessageTypePortamentoTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1portamentoTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypePortamentoTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1expression/title",
          "value": "AVMIDIControlChangeMessageTypeExpression"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1expression/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeExpression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1legatoPedal/title",
          "value": "AVMIDIControlChangeMessageTypeLegatoPedal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1legatoPedal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeLegatoPedal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1volume/title",
          "value": "AVMIDIControlChangeMessageTypeVolume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1volume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1hold2Pedal/title",
          "value": "AVMIDIControlChangeMessageTypeHold2Pedal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1hold2Pedal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeHold2Pedal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1pan/title",
          "value": "AVMIDIControlChangeMessageTypePan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1pan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypePan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1balance/title",
          "value": "AVMIDIControlChangeMessageTypeBalance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1balance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeBalance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1soft/title",
          "value": "AVMIDIControlChangeMessageTypeSoft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1soft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeSoft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1modWheel/title",
          "value": "AVMIDIControlChangeMessageTypeModWheel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1modWheel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeModWheel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1sostenuto/title",
          "value": "AVMIDIControlChangeMessageTypeSostenuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1sostenuto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeSostenuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1sustain/title",
          "value": "AVMIDIControlChangeMessageTypeSustain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1sustain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeSustain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1foot/title",
          "value": "AVMIDIControlChangeMessageTypeFoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1foot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeFoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1portamento/title",
          "value": "AVMIDIControlChangeMessageTypePortamento"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1portamento/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypePortamento"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/portamento"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/portamento"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
