{
  "abstract": [
    {
      "text": "A successfully processed transaction.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use PurchaseResult from Product.purchase(confirmIn:options:)",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekit/documentation/StoreKit",
        "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/purchased"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKPaymentTransactionState@SKPaymentTransactionStatePurchased",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "purchased"
      }
    ],
    "modules": [
      {
        "name": "StoreKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKPaymentTransactionStatePurchased"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "3.0",
        "message": "Use PurchaseResult from Product.purchase(confirmIn:options:)",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "3.0",
        "message": "Use PurchaseResult from Product.purchase(confirmIn:options:)",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "introducedAt": "13.1",
        "message": "Use PurchaseResult from Product.purchase(confirmIn:options:)",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.7",
        "message": "Use PurchaseResult from Product.purchase(confirmIn:options:)",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.0",
        "message": "Use PurchaseResult from Product.purchase(confirmIn:options:)",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "2.0",
        "introducedAt": "1.0",
        "message": "Use PurchaseResult from Product.purchase(confirmIn:options:)",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "6.2",
        "message": "Use PurchaseResult from Product.purchase(confirmIn:options:)",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SKPaymentTransactionState.purchased"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "purchased"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.storekit/documentation/StoreKit/testing-in-app-purchases-in-xcode",
        "doc://com.apple.storekit/documentation/StoreKit/testing-an-interrupted-purchase",
        "doc://com.apple.storekit/documentation/StoreKit/implementing-offer-codes-in-your-app",
        "doc://com.apple.storekit/documentation/StoreKit/testing-a-successful-transaction",
        "doc://com.apple.storekit/documentation/StoreKit/testing-resubscribing-from-the-subscriptions-page",
        "doc://com.apple.storekit/documentation/StoreKit/implementing-promotional-offers-in-your-app",
        "doc://com.apple.storekit/documentation/StoreKit/processing-a-transaction",
        "doc://com.apple.storekit/documentation/StoreKit/supporting-family-sharing-in-your-app"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Your application should provide the content the user purchased.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekit/documentation/StoreKit": {
      "abstract": [
        {
          "text": "Support In-App Purchases and interactions with the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit",
      "type": "topic",
      "url": "/documentation/storekit"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState": {
      "abstract": [
        {
          "text": "Values representing the state of a transaction.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKPaymentTransactionState"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPaymentTransactionState"
        }
      ],
      "role": "symbol",
      "title": "SKPaymentTransactionState",
      "type": "topic",
      "url": "/documentation/storekit/skpaymenttransactionstate"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/deferred": {
      "abstract": [
        {
          "text": "A transaction that is in the queue, but its final status is pending external action such as Ask to Buy.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deferred"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/deferred",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPaymentTransactionStateDeferred"
        }
      ],
      "role": "symbol",
      "title": "SKPaymentTransactionState.deferred",
      "type": "topic",
      "url": "/documentation/storekit/skpaymenttransactionstate/deferred"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/failed": {
      "abstract": [
        {
          "text": "A failed transaction.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failed"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/failed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPaymentTransactionStateFailed"
        }
      ],
      "role": "symbol",
      "title": "SKPaymentTransactionState.failed",
      "type": "topic",
      "url": "/documentation/storekit/skpaymenttransactionstate/failed"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/purchased": {
      "abstract": [
        {
          "text": "A successfully processed transaction.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "purchased"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/purchased",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPaymentTransactionStatePurchased"
        }
      ],
      "role": "symbol",
      "title": "SKPaymentTransactionState.purchased",
      "type": "topic",
      "url": "/documentation/storekit/skpaymenttransactionstate/purchased"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/purchasing": {
      "abstract": [
        {
          "text": "A transaction that is being processed by the App Store.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "purchasing"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/purchasing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPaymentTransactionStatePurchasing"
        }
      ],
      "role": "symbol",
      "title": "SKPaymentTransactionState.purchasing",
      "type": "topic",
      "url": "/documentation/storekit/skpaymenttransactionstate/purchasing"
    },
    "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/restored": {
      "abstract": [
        {
          "text": "A transaction that restores content previously purchased by the user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restored"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/restored",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKPaymentTransactionStateRestored"
        }
      ],
      "role": "symbol",
      "title": "SKPaymentTransactionState.restored",
      "type": "topic",
      "url": "/documentation/storekit/skpaymenttransactionstate/restored"
    },
    "doc://com.apple.storekit/documentation/StoreKit/implementing-offer-codes-in-your-app": {
      "abstract": [
        {
          "text": "Provide subscription service for customers who redeem offer codes through the App Store or within an app that uses receipts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/implementing-offer-codes-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Implementing offer codes in your app",
      "type": "topic",
      "url": "/documentation/storekit/implementing-offer-codes-in-your-app"
    },
    "doc://com.apple.storekit/documentation/StoreKit/implementing-promotional-offers-in-your-app": {
      "abstract": [
        {
          "text": "Offer discounted pricing for auto-renewable subscription products to eligible subscribers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/implementing-promotional-offers-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Implementing promotional offers in your app",
      "type": "topic",
      "url": "/documentation/storekit/implementing-promotional-offers-in-your-app"
    },
    "doc://com.apple.storekit/documentation/StoreKit/processing-a-transaction": {
      "abstract": [
        {
          "text": "Register a transaction queue observer to get and handle transaction updates from the App Store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/processing-a-transaction",
      "kind": "article",
      "role": "article",
      "title": "Processing a transaction",
      "type": "topic",
      "url": "/documentation/storekit/processing-a-transaction"
    },
    "doc://com.apple.storekit/documentation/StoreKit/supporting-family-sharing-in-your-app": {
      "abstract": [
        {
          "text": "Provide service to share subscriptions and non-consumable products to family members.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/supporting-family-sharing-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Supporting Family Sharing in your app",
      "type": "topic",
      "url": "/documentation/storekit/supporting-family-sharing-in-your-app"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-a-successful-transaction": {
      "abstract": [
        {
          "text": "Confirm that your app can make a successful transaction in the sandbox environment by inspecting the transaction.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-a-successful-transaction",
      "kind": "article",
      "role": "article",
      "title": "Testing a successful transaction",
      "type": "topic",
      "url": "/documentation/storekit/testing-a-successful-transaction"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-an-interrupted-purchase": {
      "abstract": [
        {
          "text": "Verify that your app handles an interrupted purchase by inspecting and invoking payment transactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-an-interrupted-purchase",
      "kind": "article",
      "role": "article",
      "title": "Testing an interrupted purchase",
      "type": "topic",
      "url": "/documentation/storekit/testing-an-interrupted-purchase"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-in-app-purchases-in-xcode": {
      "abstract": [
        {
          "text": "Use locally configured product data to test and debug your In-App Purchases implementation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-in-app-purchases-in-xcode",
      "kind": "article",
      "role": "article",
      "title": "Testing In-App Purchases in Xcode",
      "type": "topic",
      "url": "/documentation/storekit/testing-in-app-purchases-in-xcode"
    },
    "doc://com.apple.storekit/documentation/StoreKit/testing-resubscribing-from-the-subscriptions-page": {
      "abstract": [
        {
          "text": "Verify that your app can reactivate an expired subscription by receiving a transaction callback or inspecting an updated receipt.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekit/documentation/StoreKit/testing-resubscribing-from-the-subscriptions-page",
      "kind": "article",
      "role": "article",
      "title": "Testing resubscribing from the subscriptions page",
      "type": "topic",
      "url": "/documentation/storekit/testing-resubscribing-from-the-subscriptions-page"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/purchasing",
        "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/failed",
        "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/restored",
        "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/deferred"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "2.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "6.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKPaymentTransactionStatePurchased"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentTransactionStatePurchased"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekit/documentation/StoreKit",
                "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/purchasing",
                "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/failed",
                "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/restored",
                "doc://com.apple.storekit/documentation/StoreKit/SKPaymentTransactionState/deferred"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SKPaymentTransactionStatePurchased"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use PurchaseResult from Product.purchase(confirmIn:options:)",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1purchasing/title",
          "value": "SKPaymentTransactionStatePurchasing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1purchasing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentTransactionStatePurchasing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1purchased/title",
          "value": "SKPaymentTransactionStatePurchased"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1purchased/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentTransactionStatePurchased"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1deferred/title",
          "value": "SKPaymentTransactionStateDeferred"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1deferred/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentTransactionStateDeferred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1restored/title",
          "value": "SKPaymentTransactionStateRestored"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1restored/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentTransactionStateRestored"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState/title",
          "value": "SKPaymentTransactionState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentTransactionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentTransactionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1failed/title",
          "value": "SKPaymentTransactionStateFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekit~1documentation~1StoreKit~1SKPaymentTransactionState~1failed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKPaymentTransactionStateFailed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekit/skpaymenttransactionstate/purchased"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekit/skpaymenttransactionstate/purchased"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
