{
  "abstract": [
    {
      "text": "Provides debugging information about the element.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/debugDescription"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)XCUIElement(py)debugDescription",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "debugDescription"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "XCUIAutomation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "debugDescription"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.3",
        "name": "Xcode",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "debugDescription"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "debugDescription"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The data in the string varies based on the time at which it’s captured, but it may include any of the following, as well as additional data:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Values for the element’s attributes",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The entire tree of descendants rooted at the element",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The element’s query",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Use this data for debugging only. Depending on any of the data as part of a test is unsupported.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation": {
      "abstract": [
        {
          "text": "Replicate sequences of interactions and make sure that your app’s user interface behaves as intended.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation",
      "kind": "symbol",
      "role": "collection",
      "title": "XCUIAutomation",
      "type": "topic",
      "url": "/documentation/xcuiautomation"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement": {
      "abstract": [
        {
          "text": "A UI element in an application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "XCUIElement"
        }
      ],
      "role": "symbol",
      "title": "XCUIElement",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/debugDescription": {
      "abstract": [
        {
          "text": "Provides debugging information about the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debugDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/debugDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "debugDescription"
        }
      ],
      "role": "symbol",
      "title": "debugDescription",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/debugdescription"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/exists": {
      "abstract": [
        {
          "text": "Determines if the element exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exists"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/exists",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exists"
        }
      ],
      "role": "symbol",
      "title": "exists",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/exists"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/isHittable": {
      "abstract": [
        {
          "text": "Determines if the system can compute a hit point for the element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isHittable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/isHittable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hittable"
        }
      ],
      "role": "symbol",
      "title": "isHittable",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/ishittable"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/wait(for:toEqual:timeout:)": {
      "abstract": [
        {
          "text": "Waits a specified amount of time for a property value to equal a specified value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wait"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s7KeyPathC",
          "text": "KeyPath"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)XCUIElement",
          "text": "XCUIElement"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "toEqual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/wait(for:toEqual:timeout:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "wait(for:toEqual:timeout:)",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/wait(for:toequal:timeout:)"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/waitForExistence(timeout:)": {
      "abstract": [
        {
          "text": "Waits the specified amount of time for an element to exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "waitForExistence"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "timeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/waitForExistence(timeout:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "waitForExistenceWithTimeout:"
        }
      ],
      "role": "symbol",
      "title": "waitForExistence(timeout:)",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/waitforexistence(timeout:)"
    },
    "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/waitForNonExistence(timeout:)": {
      "abstract": [
        {
          "text": "Waits the specified amount of time for an element to no longer exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "waitForNonExistence"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "timeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/waitForNonExistence(timeout:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "waitForNonExistenceWithTimeout:"
        }
      ],
      "role": "symbol",
      "title": "waitForNonExistence(timeout:)",
      "type": "topic",
      "url": "/documentation/xcuiautomation/xcuielement/waitfornonexistence(timeout:)"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Querying-element-state",
      "generated": true,
      "identifiers": [
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/waitForExistence(timeout:)",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/waitForNonExistence(timeout:)",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/wait(for:toEqual:timeout:)",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/exists",
        "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/isHittable"
      ],
      "title": "Querying element state"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.3",
              "name": "Xcode",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "debugDescription"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "debugDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Querying-element-state",
              "generated": true,
              "identifiers": [
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/waitForExistence(timeout:)",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/waitForNonExistence(timeout:)",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/exists",
                "doc://com.apple.xcuiautomation/documentation/XCUIAutomation/XCUIElement/isHittable"
              ],
              "title": "Querying element state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "debugDescription"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1debugDescription/title",
          "value": "debugDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1debugDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "debugDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement/title",
          "value": "XCUIElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "XCUIElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1exists/title",
          "value": "exists"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1exists/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exists"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1waitForNonExistence(timeout:)/title",
          "value": "waitForNonExistenceWithTimeout:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1waitForNonExistence(timeout:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "waitForNonExistenceWithTimeout:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1isHittable/title",
          "value": "hittable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1isHittable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hittable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1waitForExistence(timeout:)/title",
          "value": "waitForExistenceWithTimeout:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.xcuiautomation~1documentation~1XCUIAutomation~1XCUIElement~1waitForExistence(timeout:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "waitForExistenceWithTimeout:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/xcuiautomation/xcuielement/debugdescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/xcuiautomation/xcuielement/debugdescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
