{
  "abstract": [
    {
      "text": "Creates a convolution layer with the weights, biases, and descriptor you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionLayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionLayer/init(weights:biases:descriptor:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLCConvolutionLayer(cm)layerWithWeights:biases:descriptor:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "?("
      },
      {
        "kind": "externalParam",
        "text": "weights"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MLCTensor",
        "text": "MLCTensor"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "biases"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MLCTensor",
        "text": "MLCTensor"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "descriptor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MLCConvolutionDescriptor",
        "text": "MLCConvolutionDescriptor"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "layerWithWeights:biases:descriptor:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(weights:biases:descriptor:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "?("
            },
            {
              "kind": "externalParam",
              "text": "weights"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MLCTensor",
              "text": "MLCTensor"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "biases"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MLCTensor",
              "text": "MLCTensor"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "descriptor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionDescriptor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MLCConvolutionDescriptor",
              "text": "MLCConvolutionDescriptor"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The weights tensor.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "weights"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The weights tensor.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "biases"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An object you use to configure the multi-head attention layer.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "descriptor"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionDescriptor": {
      "abstract": [
        {
          "text": "A configuration object you use to create a convolution or fully connected layer.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCConvolutionDescriptor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCConvolutionDescriptor"
        }
      ],
      "role": "symbol",
      "title": "MLCConvolutionDescriptor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcconvolutiondescriptor"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionLayer": {
      "abstract": [
        {
          "text": "A layer that applies a convolution over a signal.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCConvolutionLayer"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCConvolutionLayer"
        }
      ],
      "role": "symbol",
      "title": "MLCConvolutionLayer",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcconvolutionlayer"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionLayer/init(weights:biases:descriptor:)": {
      "abstract": [
        {
          "text": "Creates a convolution layer with the weights, biases, and descriptor you specify.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "weights"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "biases"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCTensor",
          "text": "MLCTensor"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "descriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLCConvolutionDescriptor",
          "text": "MLCConvolutionDescriptor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionLayer/init(weights:biases:descriptor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layerWithWeights:biases:descriptor:"
        }
      ],
      "role": "symbol",
      "title": "init(weights:biases:descriptor:)",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcconvolutionlayer/init(weights:biases:descriptor:)"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor": {
      "abstract": [
        {
          "text": "The data object you use throughout the framework.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCTensor"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCTensor"
        }
      ],
      "role": "symbol",
      "title": "MLCTensor",
      "type": "topic",
      "url": "/documentation/mlcompute/mlctensor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Convolution-Layers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionDescriptor"
      ],
      "title": "Creating Convolution Layers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.3",
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.4",
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "layerWithWeights:biases:descriptor:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "layerWithWeights:biases:descriptor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionLayer"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-Convolution-Layers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionDescriptor"
              ],
              "title": "Creating Convolution Layers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "layerWithWeights:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MLCTensor",
                    "text": "MLCTensor"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "weights"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "biases:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCTensor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MLCTensor",
                    "text": "MLCTensor"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "biases"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "descriptor:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCConvolutionDescriptor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MLCConvolutionDescriptor",
                    "text": "MLCConvolutionDescriptor"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "descriptor"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The weights tensor.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "weights"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The weights tensor.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "biases"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An object you use to configure the multi-head attention layer.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "descriptor"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConvolutionDescriptor/title",
          "value": "MLCConvolutionDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConvolutionDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCConvolutionDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConvolutionDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCConvolutionDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConvolutionLayer/title",
          "value": "MLCConvolutionLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConvolutionLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCConvolutionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConvolutionLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCConvolutionLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConvolutionLayer~1init(weights:biases:descriptor:)/title",
          "value": "layerWithWeights:biases:descriptor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCConvolutionLayer~1init(weights:biases:descriptor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "layerWithWeights:biases:descriptor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor/title",
          "value": "MLCTensor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCTensor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCTensor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcconvolutionlayer/init(weights:biases:descriptor:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlcconvolutionlayer/init(weights:biases:descriptor:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
