{
  "abstract": [
    {
      "text": "A display mode for a button that composes an icon and a textual label.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteControl",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/DisplayMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/DisplayMode/iconAndLabel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIPasteControlDisplayMode@UIPasteControlDisplayModeIconAndLabel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "iconAndLabel"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIPasteControlDisplayModeIconAndLabel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIPasteControl.DisplayMode.iconAndLabel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "iconAndLabel"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The icon looks like a sheet of paper above a clipboard, and the label’s text reads “Paste”.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The value you set for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/Configuration-swift.class/baseForegroundColor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " colors the icon and text.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteControl": {
      "abstract": [
        {
          "text": "A button that a person taps to place pasteboard contents in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPasteControl"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPasteControl"
        }
      ],
      "role": "symbol",
      "title": "UIPasteControl",
      "type": "topic",
      "url": "/documentation/uikit/uipastecontrol"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/Configuration-swift.class/baseForegroundColor": {
      "abstract": [
        {
          "text": "A color for the paste button’s icon and text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "baseForegroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/Configuration-swift.class/baseForegroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "baseForegroundColor"
        }
      ],
      "role": "symbol",
      "title": "baseForegroundColor",
      "type": "topic",
      "url": "/documentation/uikit/uipastecontrol/configuration-swift.class/baseforegroundcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/DisplayMode": {
      "abstract": [
        {
          "text": "Options that determine whether a paste button composes an icon, textual label, or both.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DisplayMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/DisplayMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DisplayMode"
        }
      ],
      "role": "symbol",
      "title": "UIPasteControl.DisplayMode",
      "type": "topic",
      "url": "/documentation/uikit/uipastecontrol/displaymode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/DisplayMode/iconAndLabel": {
      "abstract": [
        {
          "text": "A display mode for a button that composes an icon and a textual label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iconAndLabel"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/DisplayMode/iconAndLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPasteControlDisplayModeIconAndLabel"
        }
      ],
      "role": "symbol",
      "title": "UIPasteControl.DisplayMode.iconAndLabel",
      "type": "topic",
      "url": "/documentation/uikit/uipastecontrol/displaymode/iconandlabel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/DisplayMode/iconOnly": {
      "abstract": [
        {
          "text": "A display mode for an icon button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iconOnly"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/DisplayMode/iconOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPasteControlDisplayModeIconOnly"
        }
      ],
      "role": "symbol",
      "title": "UIPasteControl.DisplayMode.iconOnly",
      "type": "topic",
      "url": "/documentation/uikit/uipastecontrol/displaymode/icononly"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/DisplayMode/labelOnly": {
      "abstract": [
        {
          "text": "A display mode for a textual label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "labelOnly"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/DisplayMode/labelOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPasteControlDisplayModeLabelOnly"
        }
      ],
      "role": "symbol",
      "title": "UIPasteControl.DisplayMode.labelOnly",
      "type": "topic",
      "url": "/documentation/uikit/uipastecontrol/displaymode/labelonly"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Choosing-a-display-mode",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/DisplayMode/iconOnly",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/DisplayMode/labelOnly"
      ],
      "title": "Choosing a display mode"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIPasteControlDisplayModeIconAndLabel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteControlDisplayModeIconAndLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/DisplayMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Choosing-a-display-mode",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/DisplayMode/iconOnly",
                "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/DisplayMode/labelOnly"
              ],
              "title": "Choosing a display mode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIPasteControlDisplayModeIconAndLabel"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl/title",
          "value": "UIPasteControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl~1DisplayMode~1labelOnly/title",
          "value": "UIPasteControlDisplayModeLabelOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl~1DisplayMode~1labelOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteControlDisplayModeLabelOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl~1DisplayMode~1iconOnly/title",
          "value": "UIPasteControlDisplayModeIconOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl~1DisplayMode~1iconOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteControlDisplayModeIconOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl~1DisplayMode/title",
          "value": "UIPasteControlDisplayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl~1DisplayMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteControlDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl~1DisplayMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteControlDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl~1DisplayMode~1iconAndLabel/title",
          "value": "UIPasteControlDisplayModeIconAndLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl~1DisplayMode~1iconAndLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteControlDisplayModeIconAndLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl~1Configuration-swift.class~1baseForegroundColor/title",
          "value": "baseForegroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl~1Configuration-swift.class~1baseForegroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "baseForegroundColor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uipastecontrol/displaymode/iconandlabel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uipastecontrol/displaymode/iconandlabel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
