{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImpactFeedbackGenerator","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator","text":"UIImpactFeedbackGenerator"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UIImpactFeedbackStyle","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator/FeedbackStyle","text":"FeedbackStyle"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"style","content":[{"type":"paragraph","inlineContent":[{"text":"A value representing the mass of the colliding objects. For a list of valid feedback styles, see the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator/FeedbackStyle","type":"reference"},{"text":" enumeration.","type":"text"}]}]}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"text":"A newly initialized feedback generator.","type":"text"}],"type":"paragraph"}]},{"content":[{"anchor":"Discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"For more information on using feedback generators, see "},{"type":"codeVoice","code":"Using feedback generators"},{"type":"text","text":"."}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator/init(style:)"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImpactFeedbackGenerator","preciseIdentifier":"c:objc(cs)UIImpactFeedbackGenerator"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"FeedbackStyle","preciseIdentifier":"c:@E@UIImpactFeedbackStyle"},{"kind":"text","text":")"}],"roleHeading":"Initializer","symbolKind":"init","role":"symbol","title":"init(style:)","modules":[{"name":"UIKit"}],"platforms":[{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"10.0","name":"iOS","deprecatedAt":"18.4"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"10.0","name":"iPadOS","deprecatedAt":"18.4"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"13.1","name":"Mac Catalyst"}],"externalID":"c:objc(cs)UIImpactFeedbackGenerator(im)initWithStyle:","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:"}]},"abstract":[{"type":"text","text":"Creates an impact feedback generator with the specified style."}],"kind":"symbol","deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use "},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator/init(style:view:)","type":"reference"},{"type":"text","text":" instead."}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiimpactfeedbackgenerator/init(style:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiimpactfeedbackgenerator/init(style:)"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator"]]},"references":{"doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator":{"title":"UIImpactFeedbackGenerator","url":"/documentation/uikit/uiimpactfeedbackgenerator","type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator","navigatorTitle":[{"kind":"identifier","text":"UIImpactFeedbackGenerator"}],"abstract":[{"text":"A concrete feedback generator subclass that creates haptics to simulate physical impacts.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIImpactFeedbackGenerator"}]},"doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator/FeedbackStyle":{"role":"symbol","url":"/documentation/uikit/uiimpactfeedbackgenerator/feedbackstyle","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator/FeedbackStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeedbackStyle"}],"navigatorTitle":[{"kind":"identifier","text":"FeedbackStyle"}],"kind":"symbol","title":"UIImpactFeedbackGenerator.FeedbackStyle","abstract":[{"type":"text","text":"The mass of the objects in the collision simulated by an impact feedback generator object."}]},"doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator/init(style:view:)":{"url":"/documentation/uikit/uiimpactfeedbackgenerator/init(style:view:)","title":"init(style:view:)","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImpactFeedbackGenerator","preciseIdentifier":"c:objc(cs)UIImpactFeedbackGenerator"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"FeedbackStyle","preciseIdentifier":"c:@E@UIImpactFeedbackStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Creates an impact feedback generator with the specified style and view."}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator/init(style:view:)","role":"symbol","navigatorTitle":[{"text":"feedbackGeneratorWithStyle:forView:","kind":"identifier"}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator/init(style:)":{"deprecated":true,"url":"/documentation/uikit/uiimpactfeedbackgenerator/init(style:)","title":"init(style:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImpactFeedbackGenerator","kind":"typeIdentifier","text":"UIImpactFeedbackGenerator"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"FeedbackStyle","preciseIdentifier":"c:@E@UIImpactFeedbackStyle"},{"kind":"text","text":")"}],"abstract":[{"text":"Creates an impact feedback generator with the specified style.","type":"text"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator/init(style:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"iOS","introducedAt":"10.0","beta":false,"deprecated":false,"deprecatedAt":"18.4","unavailable":false},{"name":"iPadOS","introducedAt":"10.0","beta":false,"deprecated":false,"deprecatedAt":"18.4","unavailable":false},{"name":"Mac Catalyst","introducedAt":"13.1","beta":false,"deprecated":false,"unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"initWithStyle:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":null,"op":"add","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithStyle:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator/FeedbackStyle","text":"UIImpactFeedbackStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIImpactFeedbackStyle"},{"text":") ","kind":"text"},{"text":"style","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},"op":"replace","path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"A value representing the mass of the colliding objects. For a list of valid feedback styles, see the ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator/FeedbackStyle","type":"reference","isActive":true},{"text":" enumeration.","type":"text"}],"type":"paragraph"}],"name":"style"}]}},{"value":{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"text":"A newly initialized feedback generator.","type":"text"}],"type":"paragraph"}]},"op":"replace","path":"/primaryContentSections/2"},{"path":"/deprecationSummary","op":"replace","value":[{"inlineContent":[{"type":"text","text":"Use "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator/init(style:view:)","type":"reference","isActive":true},{"type":"text","text":" instead."}],"type":"paragraph"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImpactFeedbackGenerator/title","op":"replace","value":"UIImpactFeedbackGenerator"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImpactFeedbackGenerator/fragments","op":"replace","value":[{"kind":"identifier","text":"UIImpactFeedbackGenerator"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImpactFeedbackGenerator/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIImpactFeedbackGenerator"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImpactFeedbackGenerator~1FeedbackStyle/title","op":"replace","value":"UIImpactFeedbackStyle"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImpactFeedbackGenerator~1FeedbackStyle/fragments","op":"replace","value":[{"kind":"identifier","text":"UIImpactFeedbackStyle"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImpactFeedbackGenerator~1FeedbackStyle/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIImpactFeedbackStyle"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImpactFeedbackGenerator~1init(style:view:)/title","op":"replace","value":"feedbackGeneratorWithStyle:forView:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImpactFeedbackGenerator~1init(style:view:)/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"feedbackGeneratorWithStyle:forView:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImpactFeedbackGenerator~1init(style:)/title","op":"replace","value":"initWithStyle:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImpactFeedbackGenerator~1init(style:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"diffAvailability":{"minor":{"change":"modified","platform":"Xcode","versions":["16.2","16.3 beta 2"]},"major":{"change":"modified","platform":"Xcode","versions":["16.0","16.3 beta 2"]}},"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}