{
  "abstract": [
    {
      "text": "Specifies that intersectors should treat the instance as non-opaque.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions/nonOpaque"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLAccelerationStructureInstanceOptions@MTLAccelerationStructureInstanceOptionNonOpaque",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "nonOpaque"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MTLAccelerationStructureInstanceOptions",
        "text": "MTLAccelerationStructureInstanceOptions"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLAccelerationStructureInstanceOptionNonOpaque"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "nonOpaque"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "nonOpaque"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MTLAccelerationStructureInstanceOptions",
              "text": "MTLAccelerationStructureInstanceOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions": {
      "abstract": [
        {
          "text": "Options for adjusting the behavior of an instanced acceleration structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureInstanceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureInstanceOptions"
        }
      ],
      "role": "symbol",
      "title": "MTLAccelerationStructureInstanceOptions",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructureinstanceoptions"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions/MTLAccelerationStructureInstanceOptionNone": {
      "abstract": [
        {
          "text": "Specifies the default behavior for resulting acceleration structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureInstanceOptionNone"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions/MTLAccelerationStructureInstanceOptionNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLAccelerationStructureInstanceOptionNone",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructureinstanceoptions/mtlaccelerationstructureinstanceoptionnone"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions/disableTriangleCulling": {
      "abstract": [
        {
          "text": "An option that turns off culling for this instance if ray intersector has culling enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disableTriangleCulling"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLAccelerationStructureInstanceOptions",
          "text": "MTLAccelerationStructureInstanceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions/disableTriangleCulling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureInstanceOptionDisableTriangleCulling"
        }
      ],
      "role": "symbol",
      "title": "disableTriangleCulling",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructureinstanceoptions/disabletriangleculling"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions/nonOpaque": {
      "abstract": [
        {
          "text": "Specifies that intersectors should treat the instance as non-opaque.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nonOpaque"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLAccelerationStructureInstanceOptions",
          "text": "MTLAccelerationStructureInstanceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions/nonOpaque",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureInstanceOptionNonOpaque"
        }
      ],
      "role": "symbol",
      "title": "nonOpaque",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructureinstanceoptions/nonopaque"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions/opaque": {
      "abstract": [
        {
          "text": "Specifies that intersectors should treat the instance as opaque.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "opaque"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLAccelerationStructureInstanceOptions",
          "text": "MTLAccelerationStructureInstanceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions/opaque",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureInstanceOptionOpaque"
        }
      ],
      "role": "symbol",
      "title": "opaque",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructureinstanceoptions/opaque"
    },
    "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions/triangleFrontFacingWindingCounterClockwise": {
      "abstract": [
        {
          "text": "Specifies that the instance specifies front facing triangles in counter-clockwise order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "triangleFrontFacingWindingCounterClockwise"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLAccelerationStructureInstanceOptions",
          "text": "MTLAccelerationStructureInstanceOptions"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions/triangleFrontFacingWindingCounterClockwise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLAccelerationStructureInstanceOptionTriangleFrontFacingWindingCounterClockwise"
        }
      ],
      "role": "symbol",
      "title": "triangleFrontFacingWindingCounterClockwise",
      "type": "topic",
      "url": "/documentation/metal/mtlaccelerationstructureinstanceoptions/trianglefrontfacingwindingcounterclockwise"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Usage-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions/disableTriangleCulling",
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions/triangleFrontFacingWindingCounterClockwise",
        "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions/opaque"
      ],
      "title": "Usage Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLAccelerationStructureInstanceOptionNonOpaque"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureInstanceOptionNonOpaque"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Usage-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions/MTLAccelerationStructureInstanceOptionNone",
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions/disableTriangleCulling",
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions/triangleFrontFacingWindingCounterClockwise",
                "doc://com.apple.metal/documentation/Metal/MTLAccelerationStructureInstanceOptions/opaque"
              ],
              "title": "Usage Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLAccelerationStructureInstanceOptionNonOpaque"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceOptions/title",
          "value": "MTLAccelerationStructureInstanceOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureInstanceOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureInstanceOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceOptions~1opaque/title",
          "value": "MTLAccelerationStructureInstanceOptionOpaque"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceOptions~1opaque/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureInstanceOptionOpaque"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceOptions~1nonOpaque/title",
          "value": "MTLAccelerationStructureInstanceOptionNonOpaque"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceOptions~1nonOpaque/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureInstanceOptionNonOpaque"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceOptions~1disableTriangleCulling/title",
          "value": "MTLAccelerationStructureInstanceOptionDisableTriangleCulling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceOptions~1disableTriangleCulling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureInstanceOptionDisableTriangleCulling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceOptions~1triangleFrontFacingWindingCounterClockwise/title",
          "value": "MTLAccelerationStructureInstanceOptionTriangleFrontFacingWindingCounterClockwise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLAccelerationStructureInstanceOptions~1triangleFrontFacingWindingCounterClockwise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLAccelerationStructureInstanceOptionTriangleFrontFacingWindingCounterClockwise"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlaccelerationstructureinstanceoptions/nonopaque"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlaccelerationstructureinstanceoptions/nonopaque"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
