{
  "abstract": [
    {
      "text": "The light source should illuminate a scene evenly regardless of position or direction.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO",
        "doc://com.apple.modelio/documentation/ModelIO/MDLLightType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/ambient"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MDLLightType@MDLLightTypeAmbient",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ambient"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MDLLightTypeAmbient"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MDLLightType.ambient"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ambient"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLight/lightType": {
      "abstract": [
        {
          "text": "The type of the light.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lightType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLLightType",
          "text": "MDLLightType"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLight/lightType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lightType"
        }
      ],
      "role": "symbol",
      "title": "lightType",
      "type": "topic",
      "url": "/documentation/modelio/mdllight/lighttype"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLightType": {
      "abstract": [
        {
          "text": "Options for the shape and style of illumination provided by a light, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLight/lightType",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLLightType"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLightType"
        }
      ],
      "role": "symbol",
      "title": "MDLLightType",
      "type": "topic",
      "url": "/documentation/modelio/mdllighttype"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/ambient": {
      "abstract": [
        {
          "text": "The light source should illuminate a scene evenly regardless of position or direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ambient"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/ambient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLightTypeAmbient"
        }
      ],
      "role": "symbol",
      "title": "MDLLightType.ambient",
      "type": "topic",
      "url": "/documentation/modelio/mdllighttype/ambient"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/directional": {
      "abstract": [
        {
          "text": "The light source illuminates a scene from a uniform direction regardless of its position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "directional"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/directional",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLightTypeDirectional"
        }
      ],
      "role": "symbol",
      "title": "MDLLightType.directional",
      "type": "topic",
      "url": "/documentation/modelio/mdllighttype/directional"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/discArea": {
      "abstract": [
        {
          "text": "The light source illuminates a scene in all directions from an area in the shape of a disc.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "discArea"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/discArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLightTypeDiscArea"
        }
      ],
      "role": "symbol",
      "title": "MDLLightType.discArea",
      "type": "topic",
      "url": "/documentation/modelio/mdllighttype/discarea"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/environment": {
      "abstract": [
        {
          "text": "The illumination from the light is determined by texture images representing a sample of the surrounding environment for a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "environment"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/environment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLightTypeEnvironment"
        }
      ],
      "role": "symbol",
      "title": "MDLLightType.environment",
      "type": "topic",
      "url": "/documentation/modelio/mdllighttype/environment"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/linear": {
      "abstract": [
        {
          "text": "The light source illuminates a scene in all directions from an area in the shape of a line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linear"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/linear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLightTypeLinear"
        }
      ],
      "role": "symbol",
      "title": "MDLLightType.linear",
      "type": "topic",
      "url": "/documentation/modelio/mdllighttype/linear"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/photometric": {
      "abstract": [
        {
          "text": "The illumination from the light is determined by a photometric profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photometric"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/photometric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLightTypePhotometric"
        }
      ],
      "role": "symbol",
      "title": "MDLLightType.photometric",
      "type": "topic",
      "url": "/documentation/modelio/mdllighttype/photometric"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/point": {
      "abstract": [
        {
          "text": "The light source illuminates a scene in all directions from a specific position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "point"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/point",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLightTypePoint"
        }
      ],
      "role": "symbol",
      "title": "MDLLightType.point",
      "type": "topic",
      "url": "/documentation/modelio/mdllighttype/point"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/probe": {
      "abstract": [
        {
          "text": "The illumination from the light is determined by texture images representing a sample of a scene at a specific point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "probe"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/probe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLightTypeProbe"
        }
      ],
      "role": "symbol",
      "title": "MDLLightType.probe",
      "type": "topic",
      "url": "/documentation/modelio/mdllighttype/probe"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/rectangularArea": {
      "abstract": [
        {
          "text": "The light source illuminates a scene in all directions from an area in the shape of a rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rectangularArea"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/rectangularArea",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLightTypeRectangularArea"
        }
      ],
      "role": "symbol",
      "title": "MDLLightType.rectangularArea",
      "type": "topic",
      "url": "/documentation/modelio/mdllighttype/rectangulararea"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/spot": {
      "abstract": [
        {
          "text": "The light source illuminates a scene from a specific position and direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spot"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/spot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLightTypeSpot"
        }
      ],
      "role": "symbol",
      "title": "MDLLightType.spot",
      "type": "topic",
      "url": "/documentation/modelio/mdllighttype/spot"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/superElliptical": {
      "abstract": [
        {
          "text": "The light source illuminates a scene in all directions from an area in the shape of a superellipse.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "superElliptical"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/superElliptical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLightTypeSuperElliptical"
        }
      ],
      "role": "symbol",
      "title": "MDLLightType.superElliptical",
      "type": "topic",
      "url": "/documentation/modelio/mdllighttype/superelliptical"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/unknown": {
      "abstract": [
        {
          "text": "The type of the light is unknown or has not been initialized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLLightTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "MDLLightType.unknown",
      "type": "topic",
      "url": "/documentation/modelio/mdllighttype/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/unknown",
        "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/directional",
        "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/spot",
        "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/point",
        "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/linear",
        "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/discArea",
        "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/rectangularArea",
        "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/superElliptical",
        "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/photometric",
        "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/probe",
        "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/environment"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MDLLightTypeAmbient"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightTypeAmbient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO",
                "doc://com.apple.modelio/documentation/ModelIO/MDLLightType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/unknown",
                "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/directional",
                "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/spot",
                "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/point",
                "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/linear",
                "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/discArea",
                "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/rectangularArea",
                "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/superElliptical",
                "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/photometric",
                "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/probe",
                "doc://com.apple.modelio/documentation/ModelIO/MDLLightType/environment"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MDLLightTypeAmbient"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1environment/title",
          "value": "MDLLightTypeEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1environment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightTypeEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1point/title",
          "value": "MDLLightTypePoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1point/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightTypePoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1ambient/title",
          "value": "MDLLightTypeAmbient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1ambient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightTypeAmbient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLight~1lightType/title",
          "value": "lightType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLight~1lightType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lightType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1unknown/title",
          "value": "MDLLightTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1photometric/title",
          "value": "MDLLightTypePhotometric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1photometric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightTypePhotometric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1spot/title",
          "value": "MDLLightTypeSpot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1spot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightTypeSpot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1directional/title",
          "value": "MDLLightTypeDirectional"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1directional/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightTypeDirectional"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1superElliptical/title",
          "value": "MDLLightTypeSuperElliptical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1superElliptical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightTypeSuperElliptical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1rectangularArea/title",
          "value": "MDLLightTypeRectangularArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1rectangularArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightTypeRectangularArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1linear/title",
          "value": "MDLLightTypeLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1linear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightTypeLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1probe/title",
          "value": "MDLLightTypeProbe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1probe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightTypeProbe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1discArea/title",
          "value": "MDLLightTypeDiscArea"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType~1discArea/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightTypeDiscArea"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType/title",
          "value": "MDLLightType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLLightType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLLightType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdllighttype/ambient"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdllighttype/ambient"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
