{
  "abstract": [
    {
      "text": "The app accepts notifications that start the downloading of issue assets for Newsstand apps.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Register for user notification settings using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerUserNotificationSettings(_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/newsstandContentAvailability"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIRemoteNotificationType@UIRemoteNotificationTypeNewsstandContentAvailability",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "newsstandContentAvailability"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UIRemoteNotificationType",
        "text": "UIRemoteNotificationType"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIRemoteNotificationTypeNewsstandContentAvailability"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.0",
        "introducedAt": "3.0",
        "message": "Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.0",
        "introducedAt": "3.0",
        "message": "Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "newsstandContentAvailability"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "newsstandContentAvailability"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIRemoteNotificationType",
              "text": "UIRemoteNotificationType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerUserNotificationSettings(_:)": {
      "abstract": [
        {
          "text": "Registers your preferred options for notifying the user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerUserNotificationSettings"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUserNotificationSettings",
          "text": "UIUserNotificationSettings"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerUserNotificationSettings(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerUserNotificationSettings:"
        }
      ],
      "role": "symbol",
      "title": "registerUserNotificationSettings(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/registerusernotificationsettings(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType": {
      "abstract": [
        {
          "text": "Constants indicating the types of notifications the app may display to the user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIRemoteNotificationType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRemoteNotificationType"
        }
      ],
      "role": "symbol",
      "title": "UIRemoteNotificationType",
      "type": "topic",
      "url": "/documentation/uikit/uiremotenotificationtype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/UIRemoteNotificationTypeNone": {
      "abstract": [
        {
          "text": "The app accepts no notifications.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIRemoteNotificationTypeNone"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/UIRemoteNotificationTypeNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIRemoteNotificationTypeNone",
      "type": "topic",
      "url": "/documentation/uikit/uiremotenotificationtype/uiremotenotificationtypenone"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/alert": {
      "abstract": [
        {
          "text": "The app accepts alert messages as notifications.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alert"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIRemoteNotificationType",
          "text": "UIRemoteNotificationType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/alert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRemoteNotificationTypeAlert"
        }
      ],
      "role": "symbol",
      "title": "alert",
      "type": "topic",
      "url": "/documentation/uikit/uiremotenotificationtype/alert"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/badge": {
      "abstract": [
        {
          "text": "The app accepts notifications that badge the app icon.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIRemoteNotificationType",
          "text": "UIRemoteNotificationType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/badge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRemoteNotificationTypeBadge"
        }
      ],
      "role": "symbol",
      "title": "badge",
      "type": "topic",
      "url": "/documentation/uikit/uiremotenotificationtype/badge"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/newsstandContentAvailability": {
      "abstract": [
        {
          "text": "The app accepts notifications that start the downloading of issue assets for Newsstand apps.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newsstandContentAvailability"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIRemoteNotificationType",
          "text": "UIRemoteNotificationType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/newsstandContentAvailability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRemoteNotificationTypeNewsstandContentAvailability"
        }
      ],
      "role": "symbol",
      "title": "newsstandContentAvailability",
      "type": "topic",
      "url": "/documentation/uikit/uiremotenotificationtype/newsstandcontentavailability"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/sound": {
      "abstract": [
        {
          "text": "The app accepts alert sounds as notifications.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIRemoteNotificationType",
          "text": "UIRemoteNotificationType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/sound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRemoteNotificationTypeSound"
        }
      ],
      "role": "symbol",
      "title": "sound",
      "type": "topic",
      "url": "/documentation/uikit/uiremotenotificationtype/sound"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/badge",
        "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/sound",
        "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/alert"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "8.0",
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "8.0",
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIRemoteNotificationTypeNewsstandContentAvailability"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRemoteNotificationTypeNewsstandContentAvailability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/UIRemoteNotificationTypeNone",
                "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/badge",
                "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/sound",
                "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/alert"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIRemoteNotificationTypeNewsstandContentAvailability"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Register for user notification settings using the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerUserNotificationSettings(_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " method instead",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType/title",
          "value": "UIRemoteNotificationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRemoteNotificationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRemoteNotificationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1registerUserNotificationSettings(_:)/title",
          "value": "registerUserNotificationSettings:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1registerUserNotificationSettings(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "registerUserNotificationSettings:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType~1alert/title",
          "value": "UIRemoteNotificationTypeAlert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType~1alert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRemoteNotificationTypeAlert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType~1badge/title",
          "value": "UIRemoteNotificationTypeBadge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType~1badge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRemoteNotificationTypeBadge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType~1newsstandContentAvailability/title",
          "value": "UIRemoteNotificationTypeNewsstandContentAvailability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType~1newsstandContentAvailability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRemoteNotificationTypeNewsstandContentAvailability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType~1sound/title",
          "value": "UIRemoteNotificationTypeSound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType~1sound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRemoteNotificationTypeSound"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiremotenotificationtype/newsstandcontentavailability"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiremotenotificationtype/newsstandcontentavailability"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
