{
  "abstract": [
    {
      "text": "Text is visually left-aligned.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/left"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTTextAlignment@kCTTextAlignmentLeft",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "left"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTTextAlignmentLeft"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CTTextAlignment.left"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "left"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment": {
      "abstract": [
        {
          "text": "Constants that specify text alignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTTextAlignment"
        }
      ],
      "role": "symbol",
      "title": "CTTextAlignment",
      "type": "topic",
      "url": "/documentation/coretext/cttextalignment"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/center": {
      "abstract": [
        {
          "text": "Text is visually center-aligned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "center"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTTextAlignmentCenter"
        }
      ],
      "role": "symbol",
      "title": "CTTextAlignment.center",
      "type": "topic",
      "url": "/documentation/coretext/cttextalignment/center"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/justified": {
      "abstract": [
        {
          "text": "Text is fully justified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "justified"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/justified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTTextAlignmentJustified"
        }
      ],
      "role": "symbol",
      "title": "CTTextAlignment.justified",
      "type": "topic",
      "url": "/documentation/coretext/cttextalignment/justified"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/left": {
      "abstract": [
        {
          "text": "Text is visually left-aligned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTTextAlignmentLeft"
        }
      ],
      "role": "symbol",
      "title": "CTTextAlignment.left",
      "type": "topic",
      "url": "/documentation/coretext/cttextalignment/left"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/natural": {
      "abstract": [
        {
          "text": "Text uses the natural alignment of the text’s script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "natural"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/natural",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTTextAlignmentNatural"
        }
      ],
      "role": "symbol",
      "title": "CTTextAlignment.natural",
      "type": "topic",
      "url": "/documentation/coretext/cttextalignment/natural"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/right": {
      "abstract": [
        {
          "text": "Text is visually right-aligned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTTextAlignmentRight"
        }
      ],
      "role": "symbol",
      "title": "CTTextAlignment.right",
      "type": "topic",
      "url": "/documentation/coretext/cttextalignment/right"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/right",
        "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/center",
        "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/justified",
        "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/natural"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTTextAlignmentLeft"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTTextAlignmentLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText",
                "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/right",
                "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/center",
                "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/justified",
                "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/natural"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCTTextAlignmentLeft"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1center/title",
          "value": "kCTTextAlignmentCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTTextAlignmentCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1natural/title",
          "value": "kCTTextAlignmentNatural"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1natural/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTTextAlignmentNatural"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1left/title",
          "value": "kCTTextAlignmentLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTTextAlignmentLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1right/title",
          "value": "kCTTextAlignmentRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTTextAlignmentRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1justified/title",
          "value": "kCTTextAlignmentJustified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1justified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTTextAlignmentJustified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment/title",
          "value": "CTTextAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTextAlignment"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/cttextalignment/left"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/cttextalignment/left"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
