{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether dither is on.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/dither"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVAudioConverter(py)dither",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "dither"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dither"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "dither"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dither"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property defaults to ",
              "type": "text"
            },
            {
              "code": "false",
              "type": "codeVoice"
            },
            {
              "text": ". When ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": ", the framework determines whether dithering makes sense for the formats and settings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter": {
      "abstract": [
        {
          "text": "An object that converts streams of audio between formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioConverter"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioConverter"
        }
      ],
      "role": "symbol",
      "title": "AVAudioConverter",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioconverter"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/channelMap": {
      "abstract": [
        {
          "text": "An array of integers that indicates which input to derive each output from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelMap"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/channelMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "channelMap"
        }
      ],
      "role": "symbol",
      "title": "channelMap",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioconverter/channelmap"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/dither": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether dither is on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dither"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/dither",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dither"
        }
      ],
      "role": "symbol",
      "title": "dither",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioconverter/dither"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/downmix": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the framework mixes the channels instead of remapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downmix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/downmix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "downmix"
        }
      ],
      "role": "symbol",
      "title": "downmix",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioconverter/downmix"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/inputFormat": {
      "abstract": [
        {
          "text": "The format of the input audio stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioFormat",
          "text": "AVAudioFormat"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/inputFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputFormat"
        }
      ],
      "role": "symbol",
      "title": "inputFormat",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioconverter/inputformat"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/magicCookie": {
      "abstract": [
        {
          "text": "An object that contains metadata for encoders and decoders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "magicCookie"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/magicCookie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "magicCookie"
        }
      ],
      "role": "symbol",
      "title": "magicCookie",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioconverter/magiccookie"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/maximumOutputPacketSize": {
      "abstract": [
        {
          "text": "The maximum size of an output packet, in bytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumOutputPacketSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/maximumOutputPacketSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumOutputPacketSize"
        }
      ],
      "role": "symbol",
      "title": "maximumOutputPacketSize",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioconverter/maximumoutputpacketsize"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/outputFormat": {
      "abstract": [
        {
          "text": "The format of the output audio stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioFormat",
          "text": "AVAudioFormat"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/outputFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputFormat"
        }
      ],
      "role": "symbol",
      "title": "outputFormat",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudioconverter/outputformat"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Audio-Converter-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/channelMap",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/downmix",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/inputFormat",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/outputFormat",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/magicCookie",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/maximumOutputPacketSize"
      ],
      "title": "Getting Audio Converter Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "dither"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dither"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Audio-Converter-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/channelMap",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/downmix",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/inputFormat",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/outputFormat",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/magicCookie",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioConverter/maximumOutputPacketSize"
              ],
              "title": "Getting Audio Converter Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "dither"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioConverter~1maximumOutputPacketSize/title",
          "value": "maximumOutputPacketSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioConverter~1maximumOutputPacketSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumOutputPacketSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioConverter~1channelMap/title",
          "value": "channelMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioConverter~1channelMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "channelMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioConverter~1outputFormat/title",
          "value": "outputFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioConverter~1outputFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioConverter/title",
          "value": "AVAudioConverter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioConverter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioConverter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioConverter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioConverter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioConverter~1magicCookie/title",
          "value": "magicCookie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioConverter~1magicCookie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "magicCookie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioConverter~1dither/title",
          "value": "dither"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioConverter~1dither/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dither"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioConverter~1downmix/title",
          "value": "downmix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioConverter~1downmix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "downmix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioConverter~1inputFormat/title",
          "value": "inputFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioConverter~1inputFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputFormat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudioconverter/dither"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudioconverter/dither"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
