{
  "abstract": [
    {
      "text": "The requested command couldn’t execute because no Now Playing item is available.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/noActionableNowPlayingItem"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MPRemoteCommandHandlerStatus@MPRemoteCommandHandlerStatusNoActionableNowPlayingItem",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "noActionableNowPlayingItem"
      }
    ],
    "modules": [
      {
        "name": "Media Player"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MPRemoteCommandHandlerStatusNoActionableNowPlayingItem"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MPRemoteCommandHandlerStatus.noActionableNowPlayingItem"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "noActionableNowPlayingItem"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer": {
      "abstract": [
        {
          "text": "Find and play songs, audio podcasts, audio books, and more from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Player",
      "type": "topic",
      "url": "/documentation/mediaplayer"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus": {
      "abstract": [
        {
          "text": "Constants indicating the status of a command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPRemoteCommandHandlerStatus"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRemoteCommandHandlerStatus"
        }
      ],
      "role": "symbol",
      "title": "MPRemoteCommandHandlerStatus",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandhandlerstatus"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/commandFailed": {
      "abstract": [
        {
          "text": "The requested command failed to execute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commandFailed"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/commandFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRemoteCommandHandlerStatusCommandFailed"
        }
      ],
      "role": "symbol",
      "title": "MPRemoteCommandHandlerStatus.commandFailed",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandhandlerstatus/commandfailed"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/deviceNotFound": {
      "abstract": [
        {
          "text": "The requested command couldn’t execute because a required device isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceNotFound"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/deviceNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRemoteCommandHandlerStatusDeviceNotFound"
        }
      ],
      "role": "symbol",
      "title": "MPRemoteCommandHandlerStatus.deviceNotFound",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandhandlerstatus/devicenotfound"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/noActionableNowPlayingItem": {
      "abstract": [
        {
          "text": "The requested command couldn’t execute because no Now Playing item is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noActionableNowPlayingItem"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/noActionableNowPlayingItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRemoteCommandHandlerStatusNoActionableNowPlayingItem"
        }
      ],
      "role": "symbol",
      "title": "MPRemoteCommandHandlerStatus.noActionableNowPlayingItem",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandhandlerstatus/noactionablenowplayingitem"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/noSuchContent": {
      "abstract": [
        {
          "text": "The requested command couldn’t execute because its required content isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noSuchContent"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/noSuchContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRemoteCommandHandlerStatusNoSuchContent"
        }
      ],
      "role": "symbol",
      "title": "MPRemoteCommandHandlerStatus.noSuchContent",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandhandlerstatus/nosuchcontent"
    },
    "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/success": {
      "abstract": [
        {
          "text": "The requested command executed successfully.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MPRemoteCommandHandlerStatusSuccess"
        }
      ],
      "role": "symbol",
      "title": "MPRemoteCommandHandlerStatus.success",
      "type": "topic",
      "url": "/documentation/mediaplayer/mpremotecommandhandlerstatus/success"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/success",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/noSuchContent",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/deviceNotFound",
        "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/commandFailed"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12.2",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MPRemoteCommandHandlerStatusNoActionableNowPlayingItem"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandHandlerStatusNoActionableNowPlayingItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/success",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/noSuchContent",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/deviceNotFound",
                "doc://com.apple.mediaplayer/documentation/MediaPlayer/MPRemoteCommandHandlerStatus/commandFailed"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MPRemoteCommandHandlerStatusNoActionableNowPlayingItem"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus~1noSuchContent/title",
          "value": "MPRemoteCommandHandlerStatusNoSuchContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus~1noSuchContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandHandlerStatusNoSuchContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus~1success/title",
          "value": "MPRemoteCommandHandlerStatusSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandHandlerStatusSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus/title",
          "value": "MPRemoteCommandHandlerStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandHandlerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandHandlerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus~1noActionableNowPlayingItem/title",
          "value": "MPRemoteCommandHandlerStatusNoActionableNowPlayingItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus~1noActionableNowPlayingItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandHandlerStatusNoActionableNowPlayingItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus~1commandFailed/title",
          "value": "MPRemoteCommandHandlerStatusCommandFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus~1commandFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandHandlerStatusCommandFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus~1deviceNotFound/title",
          "value": "MPRemoteCommandHandlerStatusDeviceNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediaplayer~1documentation~1MediaPlayer~1MPRemoteCommandHandlerStatus~1deviceNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MPRemoteCommandHandlerStatusDeviceNotFound"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediaplayer/mpremotecommandhandlerstatus/noactionablenowplayingitem"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediaplayer/mpremotecommandhandlerstatus/noactionablenowplayingitem"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
