{
  "abstract": [
    {
      "text": "The drawable to use for the current frame.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metalkit/documentation/MetalKit",
        "doc://com.apple.metalkit/documentation/MetalKit/MTKView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metalkit/documentation/MetalKit/MTKView/currentDrawable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MTKView(py)currentDrawable",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "currentDrawable"
      },
      {
        "kind": "text",
        "text": ": (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)CAMetalDrawable",
        "text": "CAMetalDrawable"
      },
      {
        "kind": "text",
        "text": ")?"
      }
    ],
    "modules": [
      {
        "name": "MetalKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "currentDrawable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "currentDrawable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "currentDrawable"
            },
            {
              "kind": "text",
              "text": ": (any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)CAMetalDrawable",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)CAMetalDrawable",
              "text": "CAMetalDrawable"
            },
            {
              "kind": "text",
              "text": ")? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If all drawable objects are in use, the value of this property is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ". Your app should check that ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKView/currentDrawable",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " isn’t ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " before attempting to draw. The view changes the value of this property only after returning from a drawing function, either ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIView/draw(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " from a subclassed instance of the view, or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKViewDelegate/draw(in:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " from the view’s delegate.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Metal/MTLRenderCommandEncoder",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to render into the drawable’s texture and present it for display (typically registered using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Metal/MTLCommandBuffer/present(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of a command buffer). Try to minimize the time between when you fetch the drawable and when you submit the command buffer that uses it. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/QuartzCore/CAMetalLayer#3385893",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Metal/MTLCommandBuffer/present(_:)": {
      "abstract": [
        {
          "text": "Presents a drawable as early as possible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "present"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "drawable"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDrawable",
          "text": "MTLDrawable"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLCommandBuffer/present(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "present(_:)",
      "type": "topic",
      "url": "/documentation/Metal/MTLCommandBuffer/present(_:)"
    },
    "doc://com.apple.documentation/documentation/Metal/MTLRenderCommandEncoder": {
      "abstract": [
        {
          "text": "An interface that encodes a render pass into a command buffer, including all its draw calls and configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLRenderCommandEncoder"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLCommandEncoder",
          "text": "MTLCommandEncoder"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLRenderCommandEncoder",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLRenderCommandEncoder",
      "type": "topic",
      "url": "/documentation/Metal/MTLRenderCommandEncoder"
    },
    "doc://com.apple.documentation/documentation/QuartzCore/CAMetalLayer#3385893": {
      "abstract": [
        {
          "text": "A Core Animation layer that Metal can render into, typically displayed onscreen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMetalLayer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/QuartzCore/CAMetalLayer#3385893",
      "kind": "symbol",
      "role": "symbol",
      "title": "CAMetalLayer",
      "type": "topic",
      "url": "/documentation/QuartzCore/CAMetalLayer"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIView/draw(_:)": {
      "abstract": [
        {
          "text": "Draws the view’s image within the passed-in rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draw"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "rect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIView/draw(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "draw(_:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIView/draw(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metalkit/documentation/MetalKit": {
      "abstract": [
        {
          "text": "Build Metal apps quicker and easier using a common set of utility classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MetalKit",
      "type": "topic",
      "url": "/documentation/metalkit"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKView": {
      "abstract": [
        {
          "text": "A specialized view that creates, configures, and displays Metal objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTKView"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTKView"
        }
      ],
      "role": "symbol",
      "title": "MTKView",
      "type": "topic",
      "url": "/documentation/metalkit/mtkview"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKView/currentDrawable": {
      "abstract": [
        {
          "text": "The drawable to use for the current frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentDrawable"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CAMetalDrawable",
          "text": "CAMetalDrawable"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKView/currentDrawable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentDrawable"
        }
      ],
      "role": "symbol",
      "title": "currentDrawable",
      "type": "topic",
      "url": "/documentation/metalkit/mtkview/currentdrawable"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKView/currentRenderPassDescriptor": {
      "abstract": [
        {
          "text": "A render pass descriptor to draw into the current drawable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentRenderPassDescriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTLRenderPassDescriptor",
          "text": "MTLRenderPassDescriptor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKView/currentRenderPassDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentRenderPassDescriptor"
        }
      ],
      "role": "symbol",
      "title": "currentRenderPassDescriptor",
      "type": "topic",
      "url": "/documentation/metalkit/mtkview/currentrenderpassdescriptor"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKView/depthStencilStorageMode": {
      "abstract": [
        {
          "text": "The storage mode that the packed depth and stencil texture use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depthStencilStorageMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLStorageMode",
          "text": "MTLStorageMode"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKView/depthStencilStorageMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "depthStencilStorageMode"
        }
      ],
      "role": "symbol",
      "title": "depthStencilStorageMode",
      "type": "topic",
      "url": "/documentation/metalkit/mtkview/depthstencilstoragemode"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKView/depthStencilTexture": {
      "abstract": [
        {
          "text": "A packed depth and stencil texture associated with the current drawable object’s texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depthStencilTexture"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKView/depthStencilTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "depthStencilTexture"
        }
      ],
      "role": "symbol",
      "title": "depthStencilTexture",
      "type": "topic",
      "url": "/documentation/metalkit/mtkview/depthstenciltexture"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKView/multisampleColorTexture": {
      "abstract": [
        {
          "text": "The multisample color sample texture to render into.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multisampleColorTexture"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKView/multisampleColorTexture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "multisampleColorTexture"
        }
      ],
      "role": "symbol",
      "title": "multisampleColorTexture",
      "type": "topic",
      "url": "/documentation/metalkit/mtkview/multisamplecolortexture"
    },
    "doc://com.apple.metalkit/documentation/MetalKit/MTKViewDelegate/draw(in:)": {
      "abstract": [
        {
          "text": "Draws the view’s contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draw"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MTKView",
          "text": "MTKView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metalkit/documentation/MetalKit/MTKViewDelegate/draw(in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawInMTKView:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "draw(in:)",
      "type": "topic",
      "url": "/documentation/metalkit/mtkviewdelegate/draw(in:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)CAMetalDrawable": {
      "abstract": [
        {
          "text": "A Metal drawable associated with a Core Animation layer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CAMetalDrawable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLDrawable",
          "text": "MTLDrawable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)CAMetalDrawable",
      "kind": "symbol",
      "role": "symbol",
      "title": "CAMetalDrawable",
      "type": "topic",
      "url": "/documentation/QuartzCore/CAMetalDrawable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Retrieving-Render-Target-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metalkit/documentation/MetalKit/MTKView/currentRenderPassDescriptor",
        "doc://com.apple.metalkit/documentation/MetalKit/MTKView/depthStencilTexture",
        "doc://com.apple.metalkit/documentation/MetalKit/MTKView/depthStencilStorageMode",
        "doc://com.apple.metalkit/documentation/MetalKit/MTKView/multisampleColorTexture"
      ],
      "title": "Retrieving Render Target Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "currentDrawable"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentDrawable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metalkit/documentation/MetalKit",
                "doc://com.apple.metalkit/documentation/MetalKit/MTKView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Retrieving-Render-Target-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metalkit/documentation/MetalKit/MTKView/currentRenderPassDescriptor",
                "doc://com.apple.metalkit/documentation/MetalKit/MTKView/depthStencilTexture",
                "doc://com.apple.metalkit/documentation/MetalKit/MTKView/depthStencilStorageMode",
                "doc://com.apple.metalkit/documentation/MetalKit/MTKView/multisampleColorTexture"
              ],
              "title": "Retrieving Render Target Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)CAMetalDrawable",
                    "text": "id<CAMetalDrawable>"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "currentDrawable"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKView~1currentDrawable/title",
          "value": "currentDrawable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKView~1currentDrawable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentDrawable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIView~1draw(_:)/title",
          "value": "drawRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIView~1draw(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "drawRect:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGRect",
              "text": "CGRect"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "rect"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)CAMetalDrawable/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CAMetalDrawable"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLDrawable",
              "text": "MTLDrawable"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLRenderCommandEncoder/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLRenderCommandEncoder"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLCommandEncoder",
              "text": "MTLCommandEncoder"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKView~1depthStencilStorageMode/title",
          "value": "depthStencilStorageMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKView~1depthStencilStorageMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "depthStencilStorageMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1QuartzCore~1CAMetalLayer#3385893/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CAMetalLayer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CALayer",
              "text": "CALayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKView~1depthStencilTexture/title",
          "value": "depthStencilTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKView~1depthStencilTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "depthStencilTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLCommandBuffer~1present(_:)/title",
          "value": "presentDrawable:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLCommandBuffer~1present(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "presentDrawable:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Qoobjc(pl)MTLDrawable",
              "text": "id<MTLDrawable>"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "drawable"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKView~1currentRenderPassDescriptor/title",
          "value": "currentRenderPassDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKView~1currentRenderPassDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentRenderPassDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKViewDelegate~1draw(in:)/title",
          "value": "drawInMTKView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKViewDelegate~1draw(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawInMTKView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKView~1multisampleColorTexture/title",
          "value": "multisampleColorTexture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKView~1multisampleColorTexture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "multisampleColorTexture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKView/title",
          "value": "MTKView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metalkit~1documentation~1MetalKit~1MTKView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTKView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metalkit/mtkview/currentdrawable"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metalkit/mtkview/currentdrawable"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
