{
  "abstract": [
    {
      "text": "A call routed to the user’s voicemail.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/voicemail"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INCallDestinationType@INCallDestinationTypeVoicemail",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "voicemail"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INCallDestinationTypeVoicemail"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INCallDestinationType.voicemail"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "voicemail"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType": {
      "abstract": [
        {
          "text": "Constants describing the destination of a call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCallDestinationType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallDestinationType"
        }
      ],
      "role": "symbol",
      "title": "INCallDestinationType",
      "type": "topic",
      "url": "/documentation/intents/incalldestinationtype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/callBack": {
      "abstract": [
        {
          "text": "A call that was the result of a call back.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callBack"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/callBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallDestinationTypeCallBack"
        }
      ],
      "role": "symbol",
      "title": "INCallDestinationType.callBack",
      "type": "topic",
      "url": "/documentation/intents/incalldestinationtype/callback"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/emergency": {
      "abstract": [
        {
          "text": "A call routed to an emergency number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emergency"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/emergency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallDestinationTypeEmergency"
        }
      ],
      "role": "symbol",
      "title": "INCallDestinationType.emergency",
      "type": "topic",
      "url": "/documentation/intents/incalldestinationtype/emergency"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/emergencyDestination": {
      "abstract": [
        {
          "text": "A call routed to an emergency number.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emergencyDestination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INCallDestinationType",
          "text": "INCallDestinationType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/emergencyDestination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallDestinationTypeEmergencyDestination"
        }
      ],
      "role": "symbol",
      "title": "emergencyDestination",
      "type": "topic",
      "url": "/documentation/intents/incalldestinationtype/emergencydestination"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/normal": {
      "abstract": [
        {
          "text": "A call routed to its expected destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normal"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/normal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallDestinationTypeNormal"
        }
      ],
      "role": "symbol",
      "title": "INCallDestinationType.normal",
      "type": "topic",
      "url": "/documentation/intents/incalldestinationtype/normal"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/normalDestination": {
      "abstract": [
        {
          "text": "A call routed to its expected destination.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normalDestination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INCallDestinationType",
          "text": "INCallDestinationType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/normalDestination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallDestinationTypeNormalDestination"
        }
      ],
      "role": "symbol",
      "title": "normalDestination",
      "type": "topic",
      "url": "/documentation/intents/incalldestinationtype/normaldestination"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/redial": {
      "abstract": [
        {
          "text": "A call that was the result of redialing a previous call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "redial"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/redial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallDestinationTypeRedial"
        }
      ],
      "role": "symbol",
      "title": "INCallDestinationType.redial",
      "type": "topic",
      "url": "/documentation/intents/incalldestinationtype/redial"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/redialDestination": {
      "abstract": [
        {
          "text": "A call that was the result of redialing a previous call.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "redialDestination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INCallDestinationType",
          "text": "INCallDestinationType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/redialDestination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallDestinationTypeRedialDestination"
        }
      ],
      "role": "symbol",
      "title": "redialDestination",
      "type": "topic",
      "url": "/documentation/intents/incalldestinationtype/redialdestination"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/unknown": {
      "abstract": [
        {
          "text": "An unknown call destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallDestinationTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "INCallDestinationType.unknown",
      "type": "topic",
      "url": "/documentation/intents/incalldestinationtype/unknown"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/voicemail": {
      "abstract": [
        {
          "text": "A call routed to the user’s voicemail.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voicemail"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/voicemail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallDestinationTypeVoicemail"
        }
      ],
      "role": "symbol",
      "title": "INCallDestinationType.voicemail",
      "type": "topic",
      "url": "/documentation/intents/incalldestinationtype/voicemail"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/voicemailDestination": {
      "abstract": [
        {
          "text": "A call routed to the user’s voicemail.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voicemailDestination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INCallDestinationType",
          "text": "INCallDestinationType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/voicemailDestination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallDestinationTypeVoicemailDestination"
        }
      ],
      "role": "symbol",
      "title": "voicemailDestination",
      "type": "topic",
      "url": "/documentation/intents/incalldestinationtype/voicemaildestination"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/unknown",
        "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/normal",
        "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/emergency",
        "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/redial",
        "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/callBack",
        "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/normalDestination",
        "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/emergencyDestination",
        "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/voicemailDestination",
        "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/redialDestination"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INCallDestinationTypeVoicemail"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallDestinationTypeVoicemail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/unknown",
                "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/normal",
                "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/emergency",
                "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/redial",
                "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/callBack",
                "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/normalDestination",
                "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/emergencyDestination",
                "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/voicemailDestination",
                "doc://com.apple.sirikit/documentation/Intents/INCallDestinationType/redialDestination"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INCallDestinationTypeVoicemail"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType~1redialDestination/title",
          "value": "INCallDestinationTypeRedialDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType~1redialDestination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallDestinationTypeRedialDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType~1emergency/title",
          "value": "INCallDestinationTypeEmergency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType~1emergency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallDestinationTypeEmergency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType/title",
          "value": "INCallDestinationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallDestinationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallDestinationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType~1voicemailDestination/title",
          "value": "INCallDestinationTypeVoicemailDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType~1voicemailDestination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallDestinationTypeVoicemailDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType~1normal/title",
          "value": "INCallDestinationTypeNormal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType~1normal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallDestinationTypeNormal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType~1emergencyDestination/title",
          "value": "INCallDestinationTypeEmergencyDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType~1emergencyDestination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallDestinationTypeEmergencyDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType~1redial/title",
          "value": "INCallDestinationTypeRedial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType~1redial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallDestinationTypeRedial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType~1voicemail/title",
          "value": "INCallDestinationTypeVoicemail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType~1voicemail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallDestinationTypeVoicemail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType~1normalDestination/title",
          "value": "INCallDestinationTypeNormalDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType~1normalDestination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallDestinationTypeNormalDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType~1unknown/title",
          "value": "INCallDestinationTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallDestinationTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType~1callBack/title",
          "value": "INCallDestinationTypeCallBack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallDestinationType~1callBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallDestinationTypeCallBack"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/incalldestinationtype/voicemail"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/incalldestinationtype/voicemail"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
