{
  "abstract": [
    {
      "text": "An array of architectures that the audio unit supports.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/availableArchitectures"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVAudioUnitComponent(py)availableArchitectures",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "availableArchitectures"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSNumber",
        "text": "NSNumber"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "availableArchitectures"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "availableArchitectures"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "availableArchitectures"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": "] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This is an ",
              "type": "text"
            },
            {
              "code": "NSArray",
              "type": "codeVoice"
            },
            {
              "text": " of ",
              "type": "text"
            },
            {
              "code": "NSNumbers",
              "type": "codeVoice"
            },
            {
              "text": " where each entry corresponds to one of the constants in Mach-O Architecture in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/bundle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent": {
      "abstract": [
        {
          "text": "An object that provides details about an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioUnitComponent"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioUnitComponent"
        }
      ],
      "role": "symbol",
      "title": "AVAudioUnitComponent",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/audioComponentDescription": {
      "abstract": [
        {
          "text": "The audio component description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioComponentDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AudioComponentDescription",
          "text": "AudioComponentDescription"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/audioComponentDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audioComponentDescription"
        }
      ],
      "role": "symbol",
      "title": "audioComponentDescription",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/audiocomponentdescription"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/availableArchitectures": {
      "abstract": [
        {
          "text": "An array of architectures that the audio unit supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableArchitectures"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/availableArchitectures",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availableArchitectures"
        }
      ],
      "role": "symbol",
      "title": "availableArchitectures",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/availablearchitectures"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/componentURL": {
      "abstract": [
        {
          "text": "The URL of the audio unit component.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "componentURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/componentURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "componentURL"
        }
      ],
      "role": "symbol",
      "title": "componentURL",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/componenturl"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/configurationDictionary": {
      "abstract": [
        {
          "text": "The audio unit component’s configuration dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationDictionary"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/configurationDictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "configurationDictionary"
        }
      ],
      "role": "symbol",
      "title": "configurationDictionary",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/configurationdictionary"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasCustomView": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the audio unit component has a custom view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasCustomView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasCustomView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasCustomView"
        }
      ],
      "role": "symbol",
      "title": "hasCustomView",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/hascustomview"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasMIDIInput": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the audio unit component has MIDI input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasMIDIInput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasMIDIInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasMIDIInput"
        }
      ],
      "role": "symbol",
      "title": "hasMIDIInput",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/hasmidiinput"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasMIDIOutput": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the audio unit component has MIDI output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasMIDIOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasMIDIOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasMIDIOutput"
        }
      ],
      "role": "symbol",
      "title": "hasMIDIOutput",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/hasmidioutput"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/isSandboxSafe": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the audio unit component is safe for sandboxing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSandboxSafe"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/isSandboxSafe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sandboxSafe"
        }
      ],
      "role": "symbol",
      "title": "isSandboxSafe",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/issandboxsafe"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/manufacturerName": {
      "abstract": [
        {
          "text": "The name of the manufacturer of the audio unit component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "manufacturerName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/manufacturerName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "manufacturerName"
        }
      ],
      "role": "symbol",
      "title": "manufacturerName",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/manufacturername"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/name": {
      "abstract": [
        {
          "text": "The name of the audio unit component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/name"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/passesAUVal": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the audio unit component passes the validation tests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passesAUVal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/passesAUVal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "passesAUVal"
        }
      ],
      "role": "symbol",
      "title": "passesAUVal",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/passesauval"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/supportsNumberInputChannels(_:outputChannels:)": {
      "abstract": [
        {
          "text": "Gets a Boolean value that indicates whether the audio unit component supports the specified number of input and output channels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsNumberInputChannels"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "outputChannels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/supportsNumberInputChannels(_:outputChannels:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsNumberInputChannels:outputChannels:"
        }
      ],
      "role": "symbol",
      "title": "supportsNumberInputChannels(_:outputChannels:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/supportsnumberinputchannels(_:outputchannels:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/typeName": {
      "abstract": [
        {
          "text": "The audio unit component type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "typeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/typeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "typeName"
        }
      ],
      "role": "symbol",
      "title": "typeName",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/typename"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/version": {
      "abstract": [
        {
          "text": "The audio unit component version number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/version"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/versionString": {
      "abstract": [
        {
          "text": "A string that represents the audio unit component version number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "versionString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/versionString",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "versionString"
        }
      ],
      "role": "symbol",
      "title": "versionString",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiounitcomponent/versionstring"
    },
    "doc://com.apple.documentation/documentation/foundation/bundle": {
      "abstract": [
        {
          "text": "A representation of the code and resources stored in a bundle directory on disk. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "Bundle"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/bundle",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bundle",
      "type": "topic",
      "url": "/documentation/foundation/bundle"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-audio-unit-component-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/audioComponentDescription",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/configurationDictionary",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasCustomView",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasMIDIInput",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasMIDIOutput",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/manufacturerName",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/name",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/passesAUVal",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/isSandboxSafe",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/supportsNumberInputChannels(_:outputChannels:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/typeName",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/version",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/versionString",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/componentURL"
      ],
      "title": "Getting audio unit component information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "availableArchitectures"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "availableArchitectures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-audio-unit-component-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/audioComponentDescription",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/configurationDictionary",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasCustomView",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasMIDIInput",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/hasMIDIOutput",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/manufacturerName",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/name",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/passesAUVal",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/isSandboxSafe",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/supportsNumberInputChannels(_:outputChannels:)",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/typeName",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/version",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/versionString",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioUnitComponent/componentURL"
              ],
              "title": "Getting audio unit component information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSNumber *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "availableArchitectures"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1bundle/title",
          "value": "NSBundle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1supportsNumberInputChannels(_:outputChannels:)/title",
          "value": "supportsNumberInputChannels:outputChannels:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1supportsNumberInputChannels(_:outputChannels:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "supportsNumberInputChannels:outputChannels:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1isSandboxSafe/title",
          "value": "sandboxSafe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1isSandboxSafe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sandboxSafe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1hasCustomView/title",
          "value": "hasCustomView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1hasCustomView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasCustomView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1componentURL/title",
          "value": "componentURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1componentURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "componentURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1manufacturerName/title",
          "value": "manufacturerName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1manufacturerName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "manufacturerName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1configurationDictionary/title",
          "value": "configurationDictionary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1configurationDictionary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "configurationDictionary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1passesAUVal/title",
          "value": "passesAUVal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1passesAUVal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "passesAUVal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1typeName/title",
          "value": "typeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1typeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "typeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1availableArchitectures/title",
          "value": "availableArchitectures"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1availableArchitectures/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "availableArchitectures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent/title",
          "value": "AVAudioUnitComponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioUnitComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1hasMIDIOutput/title",
          "value": "hasMIDIOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1hasMIDIOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasMIDIOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1audioComponentDescription/title",
          "value": "audioComponentDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1audioComponentDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "audioComponentDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1versionString/title",
          "value": "versionString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1versionString/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "versionString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1hasMIDIInput/title",
          "value": "hasMIDIInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioUnitComponent~1hasMIDIInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasMIDIInput"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiounitcomponent/availablearchitectures"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiounitcomponent/availablearchitectures"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
