{
  "abstract": [
    {
      "text": "Indicates whether an address book has changes that have not been saved to the Address Book database.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbook/documentation/AddressBook",
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/hasUnsavedChanges()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ABAddressBook(im)hasUnsavedChanges",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "hasUnsavedChanges"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "Address Book"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "hasUnsavedChanges"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "hasUnsavedChanges()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "hasUnsavedChanges"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": " if there are unsaved changes; otherwise, ",
              "type": "text"
            },
            {
              "code": "false",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The unsaved changes flag is set automatically whenever changes are made.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbook/documentation/AddressBook": {
      "abstract": [
        {
          "text": "Access the centralized database for storing users’ contacts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book",
      "type": "topic",
      "url": "/documentation/addressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook": {
      "abstract": [
        {
          "text": "The main object you use to access the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABAddressBook"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABAddressBook"
        }
      ],
      "role": "symbol",
      "title": "ABAddressBook",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/hasUnsavedChanges()": {
      "abstract": [
        {
          "text": "Indicates whether an address book has changes that have not been saved to the Address Book database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasUnsavedChanges"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/hasUnsavedChanges()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasUnsavedChanges"
        }
      ],
      "role": "symbol",
      "title": "hasUnsavedChanges()",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/hasunsavedchanges()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/save()": {
      "abstract": [
        {
          "text": "Saves all the changes made since the last save.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "save"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/save()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "save"
        }
      ],
      "role": "symbol",
      "title": "save()",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/save()"
    },
    "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/saveAndReturnError()": {
      "abstract": [
        {
          "text": "Saves all the changes made since the last save.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saveAndReturnError"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/saveAndReturnError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveAndReturnError:"
        }
      ],
      "role": "symbol",
      "title": "saveAndReturnError()",
      "type": "topic",
      "url": "/documentation/addressbook/abaddressbook/saveandreturnerror()"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Saving-and-Detecting-Changes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/save()",
        "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/saveAndReturnError()"
      ],
      "title": "Saving and Detecting Changes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "hasUnsavedChanges"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "hasUnsavedChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbook/documentation/AddressBook",
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Saving-and-Detecting-Changes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/save()",
                "doc://com.apple.addressbook/documentation/AddressBook/ABAddressBook/saveAndReturnError()"
              ],
              "title": "Saving and Detecting Changes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "hasUnsavedChanges"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "code": "true",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if there are unsaved changes; otherwise, ",
                    "type": "text"
                  },
                  {
                    "code": "false",
                    "type": "codeVoice"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1save()/title",
          "value": "save"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1save()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "save"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1saveAndReturnError()/title",
          "value": "saveAndReturnError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1saveAndReturnError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveAndReturnError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook/title",
          "value": "ABAddressBook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABAddressBook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1hasUnsavedChanges()/title",
          "value": "hasUnsavedChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbook~1documentation~1AddressBook~1ABAddressBook~1hasUnsavedChanges()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "hasUnsavedChanges"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbook/abaddressbook/hasunsavedchanges()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbook/abaddressbook/hasunsavedchanges()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
