{
  "abstract": [
    {
      "text": "The convention that uses a clockwise winding order and positions the leading pixel at the bottom-left corner of the view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.compositorservices/documentation/CompositorServices",
        "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention/rightDownForward"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@cp_axis_direction_convention@cp_axis_direction_convention_right_down_forward",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "rightDownForward"
      }
    ],
    "modules": [
      {
        "name": "Compositor Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "cp_axis_direction_convention_right_down_forward"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AxisDirectionConvention.rightDownForward"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "rightDownForward"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This convention positions the left-most pixel  at the left edge of the view and the top-most pixel at the bottom edge of the view, and the system renders with a clockwise winding order.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.compositorservices/documentation/CompositorServices": {
      "abstract": [
        {
          "text": "Take control of the drawing environment and render your own content using Metal.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Compositor Services",
      "type": "topic",
      "url": "/documentation/compositorservices"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention": {
      "abstract": [
        {
          "text": "Constants that indicate the axis and direction to use for a perspective projection matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AxisDirectionConvention"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AxisDirectionConvention"
        }
      ],
      "role": "symbol",
      "title": "AxisDirectionConvention",
      "type": "topic",
      "url": "/documentation/compositorservices/axisdirectionconvention"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention/rightDownBack": {
      "abstract": [
        {
          "text": "The convention that uses a counterclockwise winding order and positions the leading pixel at the bottom-left corner of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightDownBack"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention/rightDownBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cp_axis_direction_convention_right_down_back"
        }
      ],
      "role": "symbol",
      "title": "AxisDirectionConvention.rightDownBack",
      "type": "topic",
      "url": "/documentation/compositorservices/axisdirectionconvention/rightdownback"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention/rightDownForward": {
      "abstract": [
        {
          "text": "The convention that uses a clockwise winding order and positions the leading pixel at the bottom-left corner of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightDownForward"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention/rightDownForward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cp_axis_direction_convention_right_down_forward"
        }
      ],
      "role": "symbol",
      "title": "AxisDirectionConvention.rightDownForward",
      "type": "topic",
      "url": "/documentation/compositorservices/axisdirectionconvention/rightdownforward"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention/rightUpBack": {
      "abstract": [
        {
          "text": "The convention that uses a counterclockwise winding order and positions the leading pixel at the top-left corner of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightUpBack"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention/rightUpBack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cp_axis_direction_convention_right_up_back"
        }
      ],
      "role": "symbol",
      "title": "AxisDirectionConvention.rightUpBack",
      "type": "topic",
      "url": "/documentation/compositorservices/axisdirectionconvention/rightupback"
    },
    "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention/rightUpForward": {
      "abstract": [
        {
          "text": "The convention that uses a clockwise winding order and positions the leading pixel at the top-left corner of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightUpForward"
        }
      ],
      "identifier": "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention/rightUpForward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cp_axis_direction_convention_right_up_forward"
        }
      ],
      "role": "symbol",
      "title": "AxisDirectionConvention.rightUpForward",
      "type": "topic",
      "url": "/documentation/compositorservices/axisdirectionconvention/rightupforward"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-axis-directions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention/rightUpBack",
        "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention/rightUpForward",
        "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention/rightDownBack"
      ],
      "title": "Getting the axis directions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "cp_axis_direction_convention_right_down_forward"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_axis_direction_convention_right_down_forward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.compositorservices/documentation/CompositorServices",
                "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-axis-directions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention/rightUpBack",
                "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention/rightUpForward",
                "doc://com.apple.compositorservices/documentation/CompositorServices/AxisDirectionConvention/rightDownBack"
              ],
              "title": "Getting the axis directions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "cp_axis_direction_convention_right_down_forward"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1AxisDirectionConvention/title",
          "value": "cp_axis_direction_convention"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1AxisDirectionConvention/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_axis_direction_convention"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1AxisDirectionConvention/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_axis_direction_convention"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1AxisDirectionConvention~1rightUpBack/title",
          "value": "cp_axis_direction_convention_right_up_back"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1AxisDirectionConvention~1rightUpBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_axis_direction_convention_right_up_back"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1AxisDirectionConvention~1rightUpForward/title",
          "value": "cp_axis_direction_convention_right_up_forward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1AxisDirectionConvention~1rightUpForward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_axis_direction_convention_right_up_forward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1AxisDirectionConvention~1rightDownBack/title",
          "value": "cp_axis_direction_convention_right_down_back"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1AxisDirectionConvention~1rightDownBack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_axis_direction_convention_right_down_back"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1AxisDirectionConvention~1rightDownForward/title",
          "value": "cp_axis_direction_convention_right_down_forward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.compositorservices~1documentation~1CompositorServices~1AxisDirectionConvention~1rightDownForward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cp_axis_direction_convention_right_down_forward"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/compositorservices/axisdirectionconvention/rightdownforward"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/compositorservices/axisdirectionconvention/rightdownforward"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
