{
  "abstract": [
    {
      "text": "The object you use to request, manage, and store the user’s account information.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use appropriate non-Apple SDK corresponding to the type of account you want to reference instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accounts/documentation/Accounts"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ACAccountStore",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ACAccountStore"
      }
    ],
    "modules": [
      {
        "name": "Accounts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ACAccountStore"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "6.0",
        "message": "Use appropriate non-Apple SDK corresponding to the type of account you want to reference instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "6.0",
        "message": "Use appropriate non-Apple SDK corresponding to the type of account you want to reference instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "message": "Use appropriate non-Apple SDK corresponding to the type of account you want to reference instead",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.8",
        "message": "Use appropriate non-Apple SDK corresponding to the type of account you want to reference instead",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ACAccountStore"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ACAccountStore"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class provides an interface for accessing, managing, and storing accounts. To create and retrieve accounts from the Accounts database, you must create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. Each ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccount",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object belongs to a single account store object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accounts/documentation/Accounts": {
      "abstract": [
        {
          "text": "Help users access and manage their external accounts from within your app, without requiring them to enter login credentials.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.accounts/documentation/Accounts",
      "kind": "symbol",
      "role": "collection",
      "title": "Accounts",
      "type": "topic",
      "url": "/documentation/accounts"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccount": {
      "abstract": [
        {
          "text": "The information associated with one of the user’s accounts.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccount"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccount"
        }
      ],
      "role": "symbol",
      "title": "ACAccount",
      "type": "topic",
      "url": "/documentation/accounts/acaccount"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountCredential": {
      "abstract": [
        {
          "text": "A credential object that encapsulates the information needed to authenticate a user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountCredential"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountCredential",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountCredential"
        }
      ],
      "role": "symbol",
      "title": "ACAccountCredential",
      "type": "topic",
      "url": "/documentation/accounts/acaccountcredential"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult": {
      "abstract": [
        {
          "text": "Status codes of credential renewal requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountCredentialRenewResult"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountCredentialRenewResult"
        }
      ],
      "role": "symbol",
      "title": "ACAccountCredentialRenewResult",
      "type": "topic",
      "url": "/documentation/accounts/acaccountcredentialrenewresult"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStore": {
      "abstract": [
        {
          "text": "The object you use to request, manage, and store the user’s account information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountStore"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountStore"
        }
      ],
      "role": "symbol",
      "title": "ACAccountStore",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstore"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/account(withIdentifier:)": {
      "abstract": [
        {
          "text": "Returns the account with the specified identifier.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "account"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ACAccount",
          "text": "ACAccount"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/account(withIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accountWithIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "account(withIdentifier:)",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstore/account(withidentifier:)"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/accountType(withAccountTypeIdentifier:)": {
      "abstract": [
        {
          "text": "Returns an account type that matches the specified identifier.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accountType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withAccountTypeIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ACAccountType",
          "text": "ACAccountType"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/accountType(withAccountTypeIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accountTypeWithAccountTypeIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "accountType(withAccountTypeIdentifier:)",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstore/accounttype(withaccounttypeidentifier:)"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/accounts": {
      "abstract": [
        {
          "text": "The accounts managed by this account store.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accounts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSArray",
          "text": "NSArray"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/accounts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accounts"
        }
      ],
      "role": "symbol",
      "title": "accounts",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstore/accounts"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/accounts(with:)": {
      "abstract": [
        {
          "text": "Returns all accounts of the specified type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accounts"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ACAccountType",
          "text": "ACAccountType"
        },
        {
          "kind": "text",
          "text": "!) -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/accounts(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accountsWithAccountType:"
        }
      ],
      "role": "symbol",
      "title": "accounts(with:)",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstore/accounts(with:)"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/removeAccount(_:withCompletionHandler:)": {
      "abstract": [
        {
          "text": "Removes an account from the account store.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAccount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ACAccount",
          "text": "ACAccount"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "withCompletionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ACAccountStoreRemoveCompletionHandler",
          "text": "ACAccountStoreRemoveCompletionHandler"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/removeAccount(_:withCompletionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAccount:withCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "removeAccount(_:withCompletionHandler:)",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstore/removeaccount(_:withcompletionhandler:)"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/renewCredentials(for:completion:)": {
      "abstract": [
        {
          "text": "Renews account credentials when the credentials are no longer valid.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "renewCredentials"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ACAccount",
          "text": "ACAccount"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ACAccountStoreCredentialRenewalHandler",
          "text": "ACAccountStoreCredentialRenewalHandler"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/renewCredentials(for:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "renewCredentialsForAccount:completion:"
        }
      ],
      "role": "symbol",
      "title": "renewCredentials(for:completion:)",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstore/renewcredentials(for:completion:)"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/requestAccessToAccounts(with:options:completion:)": {
      "abstract": [
        {
          "text": "Obtains permission to access protected user properties.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestAccessToAccounts"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ACAccountType",
          "text": "ACAccountType"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ACAccountStoreRequestAccessCompletionHandler",
          "text": "ACAccountStoreRequestAccessCompletionHandler"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/requestAccessToAccounts(with:options:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestAccessToAccountsWithType:options:completion:"
        }
      ],
      "role": "symbol",
      "title": "requestAccessToAccounts(with:options:completion:)",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstore/requestaccesstoaccounts(with:options:completion:)"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/requestAccessToAccountsWithType:withCompletionHandler:": {
      "abstract": [
        {
          "text": "Requests access to accounts of the specified type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "requestAccessToAccountsWithType:withCompletionHandler:"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/requestAccessToAccountsWithType:withCompletionHandler:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestAccessToAccountsWithType:withCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestAccessToAccountsWithType:withCompletionHandler:",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstore/requestaccesstoaccountswithtype:withcompletionhandler:"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/saveAccount(_:withCompletionHandler:)": {
      "abstract": [
        {
          "text": "Saves an account to the Accounts database.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saveAccount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ACAccount",
          "text": "ACAccount"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "withCompletionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ACAccountStoreSaveCompletionHandler",
          "text": "ACAccountStoreSaveCompletionHandler"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/saveAccount(_:withCompletionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveAccount:withCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "saveAccount(_:withCompletionHandler:)",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstore/saveaccount(_:withcompletionhandler:)"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreCredentialRenewalHandler": {
      "abstract": [
        {
          "text": "Specifies a handler to call when credentials are renewed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountStoreCredentialRenewalHandler"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreCredentialRenewalHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountStoreCredentialRenewalHandler"
        }
      ],
      "role": "symbol",
      "title": "ACAccountStoreCredentialRenewalHandler",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstorecredentialrenewalhandler"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreDidChangeNotification": {
      "abstract": [
        {
          "text": "Posted when the accounts managed by this account store changed in the database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "ACAccountStoreDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "ACAccountStoreDidChangeNotification",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstoredidchangenotification"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreRemoveCompletionHandler": {
      "abstract": [
        {
          "text": "Specifies a handler to call when an account is removed from the store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountStoreRemoveCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreRemoveCompletionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountStoreRemoveCompletionHandler"
        }
      ],
      "role": "symbol",
      "title": "ACAccountStoreRemoveCompletionHandler",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstoreremovecompletionhandler"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreRequestAccessCompletionHandler": {
      "abstract": [
        {
          "text": "Specifies a handler to call when access is granted or denied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountStoreRequestAccessCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreRequestAccessCompletionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountStoreRequestAccessCompletionHandler"
        }
      ],
      "role": "symbol",
      "title": "ACAccountStoreRequestAccessCompletionHandler",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstorerequestaccesscompletionhandler"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreSaveCompletionHandler": {
      "abstract": [
        {
          "text": "Specifies a handler to call when an Accounts database operation is complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountStoreSaveCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreSaveCompletionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountStoreSaveCompletionHandler"
        }
      ],
      "role": "symbol",
      "title": "ACAccountStoreSaveCompletionHandler",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstoresavecompletionhandler"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Account-Management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/ACAccount",
        "doc://com.apple.accounts/documentation/Accounts/ACAccountCredential"
      ],
      "title": "Account Management"
    }
  ],
  "topicSections": [
    {
      "anchor": "Requesting-Access",
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/requestAccessToAccounts(with:options:completion:)",
        "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreRequestAccessCompletionHandler"
      ],
      "title": "Requesting Access"
    },
    {
      "anchor": "Getting-Accounts",
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/accounts",
        "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/account(withIdentifier:)",
        "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/accounts(with:)"
      ],
      "title": "Getting Accounts"
    },
    {
      "anchor": "Getting-Account-Types",
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/accountType(withAccountTypeIdentifier:)"
      ],
      "title": "Getting Account Types"
    },
    {
      "anchor": "Saving-Accounts",
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/saveAccount(_:withCompletionHandler:)",
        "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreSaveCompletionHandler"
      ],
      "title": "Saving Accounts"
    },
    {
      "anchor": "Renewing-Account-Credentials",
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/renewCredentials(for:completion:)",
        "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreCredentialRenewalHandler",
        "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult"
      ],
      "title": "Renewing Account Credentials"
    },
    {
      "anchor": "Removing-Accounts",
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/removeAccount(_:withCompletionHandler:)",
        "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreRemoveCompletionHandler"
      ],
      "title": "Removing Accounts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ACAccountStore"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accounts/documentation/Accounts"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Requesting-Access",
              "identifiers": [
                "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/requestAccessToAccountsWithType:withCompletionHandler:",
                "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/requestAccessToAccounts(with:options:completion:)",
                "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreRequestAccessCompletionHandler"
              ],
              "title": "Requesting Access"
            },
            {
              "anchor": "Getting-Accounts",
              "identifiers": [
                "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/accounts",
                "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/account(withIdentifier:)",
                "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/accounts(with:)"
              ],
              "title": "Getting Accounts"
            },
            {
              "anchor": "Getting-Account-Types",
              "identifiers": [
                "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/accountType(withAccountTypeIdentifier:)"
              ],
              "title": "Getting Account Types"
            },
            {
              "anchor": "Saving-Accounts",
              "identifiers": [
                "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/saveAccount(_:withCompletionHandler:)",
                "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreSaveCompletionHandler"
              ],
              "title": "Saving Accounts"
            },
            {
              "anchor": "Renewing-Account-Credentials",
              "identifiers": [
                "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/renewCredentials(for:completion:)",
                "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreCredentialRenewalHandler",
                "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult"
              ],
              "title": "Renewing Account Credentials"
            },
            {
              "anchor": "Removing-Accounts",
              "identifiers": [
                "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/removeAccount(_:withCompletionHandler:)",
                "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreRemoveCompletionHandler"
              ],
              "title": "Removing Accounts"
            },
            {
              "anchor": "Responding-to-Changes",
              "identifiers": [
                "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreDidChangeNotification"
              ],
              "title": "Responding to Changes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Account-Management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accounts/documentation/Accounts/ACAccount",
                "doc://com.apple.accounts/documentation/Accounts/ACAccountCredential"
              ],
              "title": "Account Management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ACAccountStore"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use appropriate non-Apple SDK corresponding to the type of account you want to reference instead",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1account(withIdentifier:)/title",
          "value": "accountWithIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1account(withIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accountWithIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1accountType(withAccountTypeIdentifier:)/title",
          "value": "accountTypeWithAccountTypeIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1accountType(withAccountTypeIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accountTypeWithAccountTypeIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountCredentialRenewResult/title",
          "value": "ACAccountCredentialRenewResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountCredentialRenewResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountCredentialRenewResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountCredentialRenewResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountCredentialRenewResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1renewCredentials(for:completion:)/title",
          "value": "renewCredentialsForAccount:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1renewCredentials(for:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "renewCredentialsForAccount:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStoreSaveCompletionHandler/title",
          "value": "ACAccountStoreSaveCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStoreSaveCompletionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStoreSaveCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStoreSaveCompletionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStoreSaveCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStoreRemoveCompletionHandler/title",
          "value": "ACAccountStoreRemoveCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStoreRemoveCompletionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStoreRemoveCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStoreRemoveCompletionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStoreRemoveCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore/title",
          "value": "ACAccountStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountCredential/title",
          "value": "ACAccountCredential"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountCredential/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountCredential/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountCredential"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStoreCredentialRenewalHandler/title",
          "value": "ACAccountStoreCredentialRenewalHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStoreCredentialRenewalHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStoreCredentialRenewalHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStoreCredentialRenewalHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStoreCredentialRenewalHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1accounts/title",
          "value": "accounts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1accounts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accounts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1removeAccount(_:withCompletionHandler:)/title",
          "value": "removeAccount:withCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1removeAccount(_:withCompletionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAccount:withCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1requestAccessToAccounts(with:options:completion:)/title",
          "value": "requestAccessToAccountsWithType:options:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1requestAccessToAccounts(with:options:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestAccessToAccountsWithType:options:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStoreRequestAccessCompletionHandler/title",
          "value": "ACAccountStoreRequestAccessCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStoreRequestAccessCompletionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStoreRequestAccessCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStoreRequestAccessCompletionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStoreRequestAccessCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1accounts(with:)/title",
          "value": "accountsWithAccountType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1accounts(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accountsWithAccountType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1saveAccount(_:withCompletionHandler:)/title",
          "value": "saveAccount:withCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1saveAccount(_:withCompletionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveAccount:withCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccount/title",
          "value": "ACAccount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accounts/acaccountstore"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accounts/acaccountstore"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
