{
  "abstract": [
    {
      "text": "Status codes of credential renewal requests.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accounts/documentation/Accounts"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ACAccountCredentialRenewResult",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ACAccountCredentialRenewResult"
      }
    ],
    "modules": [
      {
        "name": "Accounts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ACAccountCredentialRenewResult"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "ACAccountCredentialRenewResult"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ACAccountCredentialRenewResult"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accounts/documentation/Accounts": {
      "abstract": [
        {
          "text": "Help users access and manage their external accounts from within your app, without requiring them to enter login credentials.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.accounts/documentation/Accounts",
      "kind": "symbol",
      "role": "collection",
      "title": "Accounts",
      "type": "topic",
      "url": "/documentation/accounts"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult": {
      "abstract": [
        {
          "text": "Status codes of credential renewal requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountCredentialRenewResult"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountCredentialRenewResult"
        }
      ],
      "role": "symbol",
      "title": "ACAccountCredentialRenewResult",
      "type": "topic",
      "url": "/documentation/accounts/acaccountcredentialrenewresult"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult/failed": {
      "abstract": [
        {
          "text": "A non-user-initiated cancel of the prompt.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failed"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult/failed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountCredentialRenewResultFailed"
        }
      ],
      "role": "symbol",
      "title": "ACAccountCredentialRenewResult.failed",
      "type": "topic",
      "url": "/documentation/accounts/acaccountcredentialrenewresult/failed"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accounts/acaccountcredentialrenewresult/init(rawvalue:)"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult/rejected": {
      "abstract": [
        {
          "text": "Renewal failed because the user revoked your access to their account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rejected"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult/rejected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountCredentialRenewResultRejected"
        }
      ],
      "role": "symbol",
      "title": "ACAccountCredentialRenewResult.rejected",
      "type": "topic",
      "url": "/documentation/accounts/acaccountcredentialrenewresult/rejected"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult/renewed": {
      "abstract": [
        {
          "text": "The account’s credentials have been renewed and are now associated with the account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "renewed"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult/renewed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountCredentialRenewResultRenewed"
        }
      ],
      "role": "symbol",
      "title": "ACAccountCredentialRenewResult.renewed",
      "type": "topic",
      "url": "/documentation/accounts/acaccountcredentialrenewresult/renewed"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/renewCredentials(for:completion:)": {
      "abstract": [
        {
          "text": "Renews account credentials when the credentials are no longer valid.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "renewCredentials"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ACAccount",
          "text": "ACAccount"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ACAccountStoreCredentialRenewalHandler",
          "text": "ACAccountStoreCredentialRenewalHandler"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/renewCredentials(for:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "renewCredentialsForAccount:completion:"
        }
      ],
      "role": "symbol",
      "title": "renewCredentials(for:completion:)",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstore/renewcredentials(for:completion:)"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreCredentialRenewalHandler": {
      "abstract": [
        {
          "text": "Specifies a handler to call when credentials are renewed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountStoreCredentialRenewalHandler"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreCredentialRenewalHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountStoreCredentialRenewalHandler"
        }
      ],
      "role": "symbol",
      "title": "ACAccountStoreCredentialRenewalHandler",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstorecredentialrenewalhandler"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Renewing-Account-Credentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/renewCredentials(for:completion:)",
        "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreCredentialRenewalHandler"
      ],
      "title": "Renewing Account Credentials"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult/renewed",
        "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult/rejected",
        "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult/failed"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ACAccountCredentialRenewResult"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountCredentialRenewResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountCredentialRenewResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accounts/documentation/Accounts"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult/renewed",
                "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult/rejected",
                "doc://com.apple.accounts/documentation/Accounts/ACAccountCredentialRenewResult/failed"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Renewing-Account-Credentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/renewCredentials(for:completion:)",
                "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreCredentialRenewalHandler"
              ],
              "title": "Renewing Account Credentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ACAccountCredentialRenewResult"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1renewCredentials(for:completion:)/title",
          "value": "renewCredentialsForAccount:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1renewCredentials(for:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "renewCredentialsForAccount:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStoreCredentialRenewalHandler/title",
          "value": "ACAccountStoreCredentialRenewalHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStoreCredentialRenewalHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStoreCredentialRenewalHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStoreCredentialRenewalHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStoreCredentialRenewalHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountCredentialRenewResult~1failed/title",
          "value": "ACAccountCredentialRenewResultFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountCredentialRenewResult~1failed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountCredentialRenewResultFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountCredentialRenewResult/title",
          "value": "ACAccountCredentialRenewResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountCredentialRenewResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountCredentialRenewResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountCredentialRenewResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountCredentialRenewResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountCredentialRenewResult~1renewed/title",
          "value": "ACAccountCredentialRenewResultRenewed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountCredentialRenewResult~1renewed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountCredentialRenewResultRenewed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountCredentialRenewResult~1rejected/title",
          "value": "ACAccountCredentialRenewResultRejected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountCredentialRenewResult~1rejected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountCredentialRenewResultRejected"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accounts/acaccountcredentialrenewresult"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accounts/acaccountcredentialrenewresult"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
