{
  "abstract": [
    {
      "text": "Codes for errors that may occur.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accounts/documentation/Accounts"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accounts/documentation/Accounts/ACErrorCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ACErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ACErrorCode"
      }
    ],
    "modules": [
      {
        "name": "Accounts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ACErrorCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "ACErrorCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ACErrorCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accounts/documentation/Accounts": {
      "abstract": [
        {
          "text": "Help users access and manage their external accounts from within your app, without requiring them to enter login credentials.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.accounts/documentation/Accounts",
      "kind": "symbol",
      "role": "collection",
      "title": "Accounts",
      "type": "topic",
      "url": "/documentation/accounts"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorAccessDeniedByProtectionPolicy": {
      "abstract": [
        {
          "text": "Error code that indicates due to the current protection policy, the credentials couldn’t be fetched.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorAccessDeniedByProtectionPolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorAccessDeniedByProtectionPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorAccessDeniedByProtectionPolicy"
        }
      ],
      "role": "symbol",
      "title": "ACErrorAccessDeniedByProtectionPolicy",
      "type": "topic",
      "url": "/documentation/accounts/acerroraccessdeniedbyprotectionpolicy"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorAccessInfoInvalid": {
      "abstract": [
        {
          "text": "Error code that indicates the client’s access info dictionary has incorrect or missing values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorAccessInfoInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorAccessInfoInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorAccessInfoInvalid"
        }
      ],
      "role": "symbol",
      "title": "ACErrorAccessInfoInvalid",
      "type": "topic",
      "url": "/documentation/accounts/acerroraccessinfoinvalid"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorAccountAlreadyExists": {
      "abstract": [
        {
          "text": "Error code that indicates an account wasn’t added because it already exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorAccountAlreadyExists"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorAccountAlreadyExists",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorAccountAlreadyExists"
        }
      ],
      "role": "symbol",
      "title": "ACErrorAccountAlreadyExists",
      "type": "topic",
      "url": "/documentation/accounts/acerroraccountalreadyexists"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorAccountAuthenticationFailed": {
      "abstract": [
        {
          "text": "Error code that indicates an account wasn’t saved because authentication of its credential failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorAccountAuthenticationFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorAccountAuthenticationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorAccountAuthenticationFailed"
        }
      ],
      "role": "symbol",
      "title": "ACErrorAccountAuthenticationFailed",
      "type": "topic",
      "url": "/documentation/accounts/acerroraccountauthenticationfailed"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorAccountMissingRequiredProperty": {
      "abstract": [
        {
          "text": "Error code that indicates an account wasn’t saved because a required property is missing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorAccountMissingRequiredProperty"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorAccountMissingRequiredProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorAccountMissingRequiredProperty"
        }
      ],
      "role": "symbol",
      "title": "ACErrorAccountMissingRequiredProperty",
      "type": "topic",
      "url": "/documentation/accounts/acerroraccountmissingrequiredproperty"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorAccountNotFound": {
      "abstract": [
        {
          "text": "Error code that indicates an account wasn’t deleted because it couldn’t be found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorAccountNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorAccountNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorAccountNotFound"
        }
      ],
      "role": "symbol",
      "title": "ACErrorAccountNotFound",
      "type": "topic",
      "url": "/documentation/accounts/acerroraccountnotfound"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorAccountTypeInvalid": {
      "abstract": [
        {
          "text": "Error code that indicates an account wasn’t saved because its account type is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorAccountTypeInvalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorAccountTypeInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorAccountTypeInvalid"
        }
      ],
      "role": "symbol",
      "title": "ACErrorAccountTypeInvalid",
      "type": "topic",
      "url": "/documentation/accounts/acerroraccounttypeinvalid"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorClientPermissionDenied": {
      "abstract": [
        {
          "text": "Error code that indicates the client doesn’t have access to the requested data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorClientPermissionDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorClientPermissionDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorClientPermissionDenied"
        }
      ],
      "role": "symbol",
      "title": "ACErrorClientPermissionDenied",
      "type": "topic",
      "url": "/documentation/accounts/acerrorclientpermissiondenied"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorCode": {
      "abstract": [
        {
          "text": "Codes for errors that may occur.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorCode"
        }
      ],
      "role": "symbol",
      "title": "ACErrorCode",
      "type": "topic",
      "url": "/documentation/accounts/acerrorcode"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorCode/init(_:)": {
      "abstract": [
        {
          "text": "Initializes a new error code structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorCode/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/accounts/acerrorcode/init(_:)"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorCode/init(rawValue:)": {
      "abstract": [
        {
          "text": "Initializes a new error code structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorCode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accounts/acerrorcode/init(rawvalue:)"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorCode/rawValue": {
      "abstract": [
        {
          "text": "The raw integer value of the error code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorCode/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/accounts/acerrorcode/rawvalue"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorCoreDataSaveFailed": {
      "abstract": [
        {
          "text": "Error code that indicates an error occurred while trying to save to a Core Data store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorCoreDataSaveFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorCoreDataSaveFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorCoreDataSaveFailed"
        }
      ],
      "role": "symbol",
      "title": "ACErrorCoreDataSaveFailed",
      "type": "topic",
      "url": "/documentation/accounts/acerrorcoredatasavefailed"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorCredentialItemNotExpired": {
      "abstract": [
        {
          "text": "Error code that indicates a credential item wasn’t removed because it hasn’t yet expired.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorCredentialItemNotExpired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorCredentialItemNotExpired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorCredentialItemNotExpired"
        }
      ],
      "role": "symbol",
      "title": "ACErrorCredentialItemNotExpired",
      "type": "topic",
      "url": "/documentation/accounts/acerrorcredentialitemnotexpired"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorCredentialItemNotFound": {
      "abstract": [
        {
          "text": "Error code that indicates a credential item wasn’t saved because it couldn’t be found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorCredentialItemNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorCredentialItemNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorCredentialItemNotFound"
        }
      ],
      "role": "symbol",
      "title": "ACErrorCredentialItemNotFound",
      "type": "topic",
      "url": "/documentation/accounts/acerrorcredentialitemnotfound"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorCredentialNotFound": {
      "abstract": [
        {
          "text": "Error code that indicates no credentials were found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorCredentialNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorCredentialNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorCredentialNotFound"
        }
      ],
      "role": "symbol",
      "title": "ACErrorCredentialNotFound",
      "type": "topic",
      "url": "/documentation/accounts/acerrorcredentialnotfound"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorDeniedByPlugin": {
      "abstract": [
        {
          "text": "Error code that indicates a plugin prevented the expected action from occurring.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorDeniedByPlugin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorDeniedByPlugin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorDeniedByPlugin"
        }
      ],
      "role": "symbol",
      "title": "ACErrorDeniedByPlugin",
      "type": "topic",
      "url": "/documentation/accounts/acerrordeniedbyplugin"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorDomain": {
      "abstract": [
        {
          "text": "The error domain for the Accounts framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "ACErrorDomain",
      "type": "topic",
      "url": "/documentation/accounts/acerrordomain"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorFailedSerializingAccountInfo": {
      "abstract": [
        {
          "text": "Error code that indicates an account’s information couldn’t be serialized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorFailedSerializingAccountInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorFailedSerializingAccountInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorFailedSerializingAccountInfo"
        }
      ],
      "role": "symbol",
      "title": "ACErrorFailedSerializingAccountInfo",
      "type": "topic",
      "url": "/documentation/accounts/acerrorfailedserializingaccountinfo"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorFetchCredentialFailed": {
      "abstract": [
        {
          "text": "Error code that indicates the credentials couldn’t be fetched from Keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorFetchCredentialFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorFetchCredentialFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorFetchCredentialFailed"
        }
      ],
      "role": "symbol",
      "title": "ACErrorFetchCredentialFailed",
      "type": "topic",
      "url": "/documentation/accounts/acerrorfetchcredentialfailed"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorInvalidClientBundleID": {
      "abstract": [
        {
          "text": "Error code that indicates the client making the request doesn’t have a valid bundle ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorInvalidClientBundleID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorInvalidClientBundleID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorInvalidClientBundleID"
        }
      ],
      "role": "symbol",
      "title": "ACErrorInvalidClientBundleID",
      "type": "topic",
      "url": "/documentation/accounts/acerrorinvalidclientbundleid"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorInvalidCommand": {
      "abstract": [
        {
          "text": "Error code that indicates an invalid command was attempted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorInvalidCommand"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorInvalidCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorInvalidCommand"
        }
      ],
      "role": "symbol",
      "title": "ACErrorInvalidCommand",
      "type": "topic",
      "url": "/documentation/accounts/acerrorinvalidcommand"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorMissingTransportMessageID": {
      "abstract": [
        {
          "text": "Error code that indicates an expected message identifier wasn’t found while performing a command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorMissingTransportMessageID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorMissingTransportMessageID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorMissingTransportMessageID"
        }
      ],
      "role": "symbol",
      "title": "ACErrorMissingTransportMessageID",
      "type": "topic",
      "url": "/documentation/accounts/acerrormissingtransportmessageid"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorPermissionDenied": {
      "abstract": [
        {
          "text": "Error code that indicates the operation failed because the application doesn’t have permission to perform the operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorPermissionDenied"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorPermissionDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorPermissionDenied"
        }
      ],
      "role": "symbol",
      "title": "ACErrorPermissionDenied",
      "type": "topic",
      "url": "/documentation/accounts/acerrorpermissiondenied"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorRemoveCredentialFailed": {
      "abstract": [
        {
          "text": "Error code that indicates the credentials couldn’t be removed from Keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorRemoveCredentialFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorRemoveCredentialFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorRemoveCredentialFailed"
        }
      ],
      "role": "symbol",
      "title": "ACErrorRemoveCredentialFailed",
      "type": "topic",
      "url": "/documentation/accounts/acerrorremovecredentialfailed"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorStoreCredentialFailed": {
      "abstract": [
        {
          "text": "Error code that indicates the credentials couldn’t be stored in Keychain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorStoreCredentialFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorStoreCredentialFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorStoreCredentialFailed"
        }
      ],
      "role": "symbol",
      "title": "ACErrorStoreCredentialFailed",
      "type": "topic",
      "url": "/documentation/accounts/acerrorstorecredentialfailed"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorUnknown": {
      "abstract": [
        {
          "text": "Error code that indicates an unknown error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorUnknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "ACErrorUnknown",
      "type": "topic",
      "url": "/documentation/accounts/acerrorunknown"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACErrorUpdatingNonexistentAccount": {
      "abstract": [
        {
          "text": "Error code that indicates an account save failed because the account being updated has been removed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACErrorUpdatingNonexistentAccount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ACErrorCode",
          "text": "ACErrorCode"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACErrorUpdatingNonexistentAccount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACErrorUpdatingNonexistentAccount"
        }
      ],
      "role": "symbol",
      "title": "ACErrorUpdatingNonexistentAccount",
      "type": "topic",
      "url": "/documentation/accounts/acerrorupdatingnonexistentaccount"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/ACErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/ACErrorUnknown",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorAccountMissingRequiredProperty",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorAccountAuthenticationFailed",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorAccountTypeInvalid",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorAccountAlreadyExists",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorAccountNotFound",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorPermissionDenied",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorAccessInfoInvalid",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorClientPermissionDenied",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorAccessDeniedByProtectionPolicy",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorCredentialNotFound",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorFetchCredentialFailed",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorStoreCredentialFailed",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorRemoveCredentialFailed",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorUpdatingNonexistentAccount",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorInvalidClientBundleID",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorDeniedByPlugin",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorCoreDataSaveFailed",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorFailedSerializingAccountInfo",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorInvalidCommand",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorMissingTransportMessageID",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorCredentialItemNotFound",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorCredentialItemNotExpired"
      ],
      "title": "Errors"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/ACErrorCode/init(_:)",
        "doc://com.apple.accounts/documentation/Accounts/ACErrorCode/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/ACErrorCode/rawValue"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ACErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accounts/documentation/Accounts"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.accounts/documentation/Accounts/ACErrorUnknown",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorAccountMissingRequiredProperty",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorAccountAuthenticationFailed",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorAccountTypeInvalid",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorAccountAlreadyExists",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorAccountNotFound",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorPermissionDenied",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorAccessInfoInvalid",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorClientPermissionDenied",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorAccessDeniedByProtectionPolicy",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorCredentialNotFound",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorFetchCredentialFailed",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorStoreCredentialFailed",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorRemoveCredentialFailed",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorUpdatingNonexistentAccount",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorInvalidClientBundleID",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorDeniedByPlugin",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorCoreDataSaveFailed",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorFailedSerializingAccountInfo",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorInvalidCommand",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorMissingTransportMessageID",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorCredentialItemNotFound",
                "doc://com.apple.accounts/documentation/Accounts/ACErrorCredentialItemNotExpired"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accounts/documentation/Accounts/ACErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "ACErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:i",
                    "text": "unsigned int"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "ACErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorRemoveCredentialFailed/title",
          "value": "ACErrorRemoveCredentialFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorRemoveCredentialFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorRemoveCredentialFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorCode/title",
          "value": "ACErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorCoreDataSaveFailed/title",
          "value": "ACErrorCoreDataSaveFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorCoreDataSaveFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorCoreDataSaveFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorAccountNotFound/title",
          "value": "ACErrorAccountNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorAccountNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorAccountNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorPermissionDenied/title",
          "value": "ACErrorPermissionDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorPermissionDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorPermissionDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorCredentialItemNotFound/title",
          "value": "ACErrorCredentialItemNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorCredentialItemNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorCredentialItemNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorMissingTransportMessageID/title",
          "value": "ACErrorMissingTransportMessageID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorMissingTransportMessageID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorMissingTransportMessageID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorAccountMissingRequiredProperty/title",
          "value": "ACErrorAccountMissingRequiredProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorAccountMissingRequiredProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorAccountMissingRequiredProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorInvalidClientBundleID/title",
          "value": "ACErrorInvalidClientBundleID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorInvalidClientBundleID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorInvalidClientBundleID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorCredentialItemNotExpired/title",
          "value": "ACErrorCredentialItemNotExpired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorCredentialItemNotExpired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorCredentialItemNotExpired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorFailedSerializingAccountInfo/title",
          "value": "ACErrorFailedSerializingAccountInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorFailedSerializingAccountInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorFailedSerializingAccountInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorUpdatingNonexistentAccount/title",
          "value": "ACErrorUpdatingNonexistentAccount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorUpdatingNonexistentAccount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorUpdatingNonexistentAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorInvalidCommand/title",
          "value": "ACErrorInvalidCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorInvalidCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorInvalidCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorDeniedByPlugin/title",
          "value": "ACErrorDeniedByPlugin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorDeniedByPlugin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorDeniedByPlugin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorFetchCredentialFailed/title",
          "value": "ACErrorFetchCredentialFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorFetchCredentialFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorFetchCredentialFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorDomain/title",
          "value": "ACErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorAccessDeniedByProtectionPolicy/title",
          "value": "ACErrorAccessDeniedByProtectionPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorAccessDeniedByProtectionPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorAccessDeniedByProtectionPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorAccountTypeInvalid/title",
          "value": "ACErrorAccountTypeInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorAccountTypeInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorAccountTypeInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorAccessInfoInvalid/title",
          "value": "ACErrorAccessInfoInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorAccessInfoInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorAccessInfoInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorClientPermissionDenied/title",
          "value": "ACErrorClientPermissionDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorClientPermissionDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorClientPermissionDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorUnknown/title",
          "value": "ACErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorAccountAuthenticationFailed/title",
          "value": "ACErrorAccountAuthenticationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorAccountAuthenticationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorAccountAuthenticationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorAccountAlreadyExists/title",
          "value": "ACErrorAccountAlreadyExists"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorAccountAlreadyExists/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorAccountAlreadyExists"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorStoreCredentialFailed/title",
          "value": "ACErrorStoreCredentialFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorStoreCredentialFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorStoreCredentialFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorCredentialNotFound/title",
          "value": "ACErrorCredentialNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACErrorCredentialNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACErrorCredentialNotFound"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accounts/acerrorcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accounts/acerrorcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
