{
  "abstract": [
    {
      "text": "Avoid using deprecated symbols in your apps.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accounts/documentation/Accounts"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accounts/documentation/Accounts/deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accounts"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated Symbols"
  },
  "references": {
    "doc://com.apple.accounts/documentation/Accounts": {
      "abstract": [
        {
          "text": "Help users access and manage their external accounts from within your app, without requiring them to enter login credentials.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.accounts/documentation/Accounts",
      "kind": "symbol",
      "role": "collection",
      "title": "Accounts",
      "type": "topic",
      "url": "/documentation/accounts"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountTypeIdentifierFacebook": {
      "abstract": [
        {
          "text": "Identifier for the Facebook account type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountTypeIdentifierFacebook"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountTypeIdentifierFacebook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountTypeIdentifierFacebook"
        }
      ],
      "role": "symbol",
      "title": "ACAccountTypeIdentifierFacebook",
      "type": "topic",
      "url": "/documentation/accounts/acaccounttypeidentifierfacebook"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountTypeIdentifierLinkedIn": {
      "abstract": [
        {
          "text": "Identifier for the LinkedIn account type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountTypeIdentifierLinkedIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountTypeIdentifierLinkedIn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountTypeIdentifierLinkedIn"
        }
      ],
      "role": "symbol",
      "title": "ACAccountTypeIdentifierLinkedIn",
      "type": "topic",
      "url": "/documentation/accounts/acaccounttypeidentifierlinkedin"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountTypeIdentifierSinaWeibo": {
      "abstract": [
        {
          "text": "Identifier for the Sina Weibo account type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountTypeIdentifierSinaWeibo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountTypeIdentifierSinaWeibo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountTypeIdentifierSinaWeibo"
        }
      ],
      "role": "symbol",
      "title": "ACAccountTypeIdentifierSinaWeibo",
      "type": "topic",
      "url": "/documentation/accounts/acaccounttypeidentifiersinaweibo"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountTypeIdentifierTencentWeibo": {
      "abstract": [
        {
          "text": "Identifier for the Tencent Weibo account type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountTypeIdentifierTencentWeibo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountTypeIdentifierTencentWeibo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountTypeIdentifierTencentWeibo"
        }
      ],
      "role": "symbol",
      "title": "ACAccountTypeIdentifierTencentWeibo",
      "type": "topic",
      "url": "/documentation/accounts/acaccounttypeidentifiertencentweibo"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountTypeIdentifierTwitter": {
      "abstract": [
        {
          "text": "Identifier for the Twitter account type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountTypeIdentifierTwitter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountTypeIdentifierTwitter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountTypeIdentifierTwitter"
        }
      ],
      "role": "symbol",
      "title": "ACAccountTypeIdentifierTwitter",
      "type": "topic",
      "url": "/documentation/accounts/acaccounttypeidentifiertwitter"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACFacebookAppIdKey": {
      "abstract": [
        {
          "text": "The Facebook App ID, as it appears on the Facebook website.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACFacebookAppIdKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACFacebookAppIdKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACFacebookAppIdKey"
        }
      ],
      "role": "symbol",
      "title": "ACFacebookAppIdKey",
      "type": "topic",
      "url": "/documentation/accounts/acfacebookappidkey"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACFacebookAudienceEveryone": {
      "abstract": [
        {
          "text": "Posts are visible to everyone.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACFacebookAudienceEveryone"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACFacebookAudienceEveryone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACFacebookAudienceEveryone"
        }
      ],
      "role": "symbol",
      "title": "ACFacebookAudienceEveryone",
      "type": "topic",
      "url": "/documentation/accounts/acfacebookaudienceeveryone"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACFacebookAudienceFriends": {
      "abstract": [
        {
          "text": "Posts are visible only to friends.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACFacebookAudienceFriends"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACFacebookAudienceFriends",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACFacebookAudienceFriends"
        }
      ],
      "role": "symbol",
      "title": "ACFacebookAudienceFriends",
      "type": "topic",
      "url": "/documentation/accounts/acfacebookaudiencefriends"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACFacebookAudienceKey": {
      "abstract": [
        {
          "text": "Only required when posting permissions are requested.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACFacebookAudienceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACFacebookAudienceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACFacebookAudienceKey"
        }
      ],
      "role": "symbol",
      "title": "ACFacebookAudienceKey",
      "type": "topic",
      "url": "/documentation/accounts/acfacebookaudiencekey"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACFacebookAudienceOnlyMe": {
      "abstract": [
        {
          "text": "Posts are visible to the user only.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACFacebookAudienceOnlyMe"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACFacebookAudienceOnlyMe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACFacebookAudienceOnlyMe"
        }
      ],
      "role": "symbol",
      "title": "ACFacebookAudienceOnlyMe",
      "type": "topic",
      "url": "/documentation/accounts/acfacebookaudienceonlyme"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACFacebookPermissionsKey": {
      "abstract": [
        {
          "text": "The array of strings of permissions to request (for example, ",
          "type": "text"
        },
        {
          "code": "email",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "publish_stream",
          "type": "codeVoice"
        },
        {
          "text": ", and so on).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACFacebookPermissionsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACFacebookPermissionsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACFacebookPermissionsKey"
        }
      ],
      "role": "symbol",
      "title": "ACFacebookPermissionsKey",
      "type": "topic",
      "url": "/documentation/accounts/acfacebookpermissionskey"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACLinkedInAppIdKey": {
      "abstract": [
        {
          "text": "The LinkedIn App ID, as it appears on the LinkedIn website.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACLinkedInAppIdKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACLinkedInAppIdKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACLinkedInAppIdKey"
        }
      ],
      "role": "symbol",
      "title": "ACLinkedInAppIdKey",
      "type": "topic",
      "url": "/documentation/accounts/aclinkedinappidkey"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACLinkedInPermissionsKey": {
      "abstract": [
        {
          "text": "The array of strings of permissions to request.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACLinkedInPermissionsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACLinkedInPermissionsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACLinkedInPermissionsKey"
        }
      ],
      "role": "symbol",
      "title": "ACLinkedInPermissionsKey",
      "type": "topic",
      "url": "/documentation/accounts/aclinkedinpermissionskey"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACTencentWeiboAppIdKey": {
      "abstract": [
        {
          "text": "The Tencent Weibo App ID, as it appears on the Tencent Weibo website.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACTencentWeiboAppIdKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACTencentWeiboAppIdKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACTencentWeiboAppIdKey"
        }
      ],
      "role": "symbol",
      "title": "ACTencentWeiboAppIdKey",
      "type": "topic",
      "url": "/documentation/accounts/actencentweiboappidkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Account-Type-Strings",
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/ACAccountTypeIdentifierFacebook",
        "doc://com.apple.accounts/documentation/Accounts/ACAccountTypeIdentifierLinkedIn",
        "doc://com.apple.accounts/documentation/Accounts/ACAccountTypeIdentifierSinaWeibo",
        "doc://com.apple.accounts/documentation/Accounts/ACAccountTypeIdentifierTencentWeibo",
        "doc://com.apple.accounts/documentation/Accounts/ACAccountTypeIdentifierTwitter"
      ],
      "title": "Account Type Strings"
    },
    {
      "anchor": "Account-Keys",
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/ACFacebookAppIdKey",
        "doc://com.apple.accounts/documentation/Accounts/ACFacebookAudienceEveryone",
        "doc://com.apple.accounts/documentation/Accounts/ACFacebookAudienceFriends",
        "doc://com.apple.accounts/documentation/Accounts/ACFacebookAudienceKey",
        "doc://com.apple.accounts/documentation/Accounts/ACFacebookAudienceOnlyMe",
        "doc://com.apple.accounts/documentation/Accounts/ACFacebookPermissionsKey",
        "doc://com.apple.accounts/documentation/Accounts/ACLinkedInAppIdKey",
        "doc://com.apple.accounts/documentation/Accounts/ACLinkedInPermissionsKey",
        "doc://com.apple.accounts/documentation/Accounts/ACTencentWeiboAppIdKey"
      ],
      "title": "Account Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Account-Type-Strings",
              "identifiers": [
                "doc://com.apple.accounts/documentation/Accounts/ACAccountTypeIdentifierFacebook",
                "doc://com.apple.accounts/documentation/Accounts/ACAccountTypeIdentifierLinkedIn",
                "doc://com.apple.accounts/documentation/Accounts/ACAccountTypeIdentifierSinaWeibo",
                "doc://com.apple.accounts/documentation/Accounts/ACAccountTypeIdentifierTencentWeibo",
                "doc://com.apple.accounts/documentation/Accounts/ACAccountTypeIdentifierTwitter"
              ],
              "title": "Account Type Strings"
            },
            {
              "anchor": "Account-Keys",
              "identifiers": [
                "doc://com.apple.accounts/documentation/Accounts/ACFacebookAppIdKey",
                "doc://com.apple.accounts/documentation/Accounts/ACFacebookAudienceEveryone",
                "doc://com.apple.accounts/documentation/Accounts/ACFacebookAudienceFriends",
                "doc://com.apple.accounts/documentation/Accounts/ACFacebookAudienceKey",
                "doc://com.apple.accounts/documentation/Accounts/ACFacebookAudienceOnlyMe",
                "doc://com.apple.accounts/documentation/Accounts/ACFacebookPermissionsKey",
                "doc://com.apple.accounts/documentation/Accounts/ACLinkedInAppIdKey",
                "doc://com.apple.accounts/documentation/Accounts/ACLinkedInPermissionsKey",
                "doc://com.apple.accounts/documentation/Accounts/ACTencentWeiboAppIdKey"
              ],
              "title": "Account Keys"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACTencentWeiboAppIdKey/title",
          "value": "ACTencentWeiboAppIdKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACTencentWeiboAppIdKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACTencentWeiboAppIdKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountTypeIdentifierLinkedIn/title",
          "value": "ACAccountTypeIdentifierLinkedIn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountTypeIdentifierLinkedIn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountTypeIdentifierLinkedIn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACFacebookAppIdKey/title",
          "value": "ACFacebookAppIdKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACFacebookAppIdKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACFacebookAppIdKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACFacebookAudienceEveryone/title",
          "value": "ACFacebookAudienceEveryone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACFacebookAudienceEveryone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACFacebookAudienceEveryone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACFacebookAudienceOnlyMe/title",
          "value": "ACFacebookAudienceOnlyMe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACFacebookAudienceOnlyMe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACFacebookAudienceOnlyMe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountTypeIdentifierTwitter/title",
          "value": "ACAccountTypeIdentifierTwitter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountTypeIdentifierTwitter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountTypeIdentifierTwitter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountTypeIdentifierTencentWeibo/title",
          "value": "ACAccountTypeIdentifierTencentWeibo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountTypeIdentifierTencentWeibo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountTypeIdentifierTencentWeibo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACFacebookAudienceFriends/title",
          "value": "ACFacebookAudienceFriends"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACFacebookAudienceFriends/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACFacebookAudienceFriends"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACLinkedInPermissionsKey/title",
          "value": "ACLinkedInPermissionsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACLinkedInPermissionsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACLinkedInPermissionsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountTypeIdentifierSinaWeibo/title",
          "value": "ACAccountTypeIdentifierSinaWeibo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountTypeIdentifierSinaWeibo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountTypeIdentifierSinaWeibo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACFacebookAudienceKey/title",
          "value": "ACFacebookAudienceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACFacebookAudienceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACFacebookAudienceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountTypeIdentifierFacebook/title",
          "value": "ACAccountTypeIdentifierFacebook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountTypeIdentifierFacebook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountTypeIdentifierFacebook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACLinkedInAppIdKey/title",
          "value": "ACLinkedInAppIdKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACLinkedInAppIdKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACLinkedInAppIdKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACFacebookPermissionsKey/title",
          "value": "ACFacebookPermissionsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACFacebookPermissionsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACFacebookPermissionsKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accounts/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accounts/deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
