{
  "abstract": [
    {
      "text": "An error code that indicates the manager hasn’t loaded the app push configuration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct/Code/configurationNotLoaded"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEAppPushManagerError@NEAppPushManagerErrorConfigurationNotLoaded",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "configurationNotLoaded"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEAppPushManagerErrorConfigurationNotLoaded"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NEAppPushManagerError.Code.configurationNotLoaded"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "configurationNotLoaded"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct": {
      "abstract": [
        {
          "text": "An error that the push manager encounters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEAppPushManagerError"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppPushManagerError"
        }
      ],
      "role": "symbol",
      "title": "NEAppPushManagerError",
      "type": "topic",
      "url": "/documentation/networkextension/neapppushmanagererror-swift.struct"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes that the local push API declares.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "NEAppPushManagerError.Code",
      "type": "topic",
      "url": "/documentation/networkextension/neapppushmanagererror-swift.struct/code"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct/Code/configurationInvalid": {
      "abstract": [
        {
          "text": "An error code that indicates the app push configuration is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationInvalid"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct/Code/configurationInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppPushManagerErrorConfigurationInvalid"
        }
      ],
      "role": "symbol",
      "title": "NEAppPushManagerError.Code.configurationInvalid",
      "type": "topic",
      "url": "/documentation/networkextension/neapppushmanagererror-swift.struct/code/configurationinvalid"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct/Code/configurationNotLoaded": {
      "abstract": [
        {
          "text": "An error code that indicates the manager hasn’t loaded the app push configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationNotLoaded"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct/Code/configurationNotLoaded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppPushManagerErrorConfigurationNotLoaded"
        }
      ],
      "role": "symbol",
      "title": "NEAppPushManagerError.Code.configurationNotLoaded",
      "type": "topic",
      "url": "/documentation/networkextension/neapppushmanagererror-swift.struct/code/configurationnotloaded"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct/Code/inactiveSession": {
      "abstract": [
        {
          "text": "An error code that indicates an invalid attempt to perform an operation on an inactive session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inactiveSession"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct/Code/inactiveSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppPushManagerErrorInactiveSession"
        }
      ],
      "role": "symbol",
      "title": "NEAppPushManagerError.Code.inactiveSession",
      "type": "topic",
      "url": "/documentation/networkextension/neapppushmanagererror-swift.struct/code/inactivesession"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct/Code/internalError": {
      "abstract": [
        {
          "text": "An error code that indicates an internal error in the local push connectivity framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct/Code/internalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEAppPushManagerErrorInternalError"
        }
      ],
      "role": "symbol",
      "title": "NEAppPushManagerError.Code.internalError",
      "type": "topic",
      "url": "/documentation/networkextension/neapppushmanagererror-swift.struct/code/internalerror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct/Code/configurationInvalid",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct/Code/inactiveSession",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct/Code/internalError"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEAppPushManagerErrorConfigurationNotLoaded"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppPushManagerErrorConfigurationNotLoaded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct/Code/configurationInvalid",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct/Code/inactiveSession",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEAppPushManagerError-swift.struct/Code/internalError"
              ],
              "title": "Error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NEAppPushManagerErrorConfigurationNotLoaded"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppPushManagerError-swift.struct~1Code~1configurationInvalid/title",
          "value": "NEAppPushManagerErrorConfigurationInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppPushManagerError-swift.struct~1Code~1configurationInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppPushManagerErrorConfigurationInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppPushManagerError-swift.struct~1Code~1inactiveSession/title",
          "value": "NEAppPushManagerErrorInactiveSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppPushManagerError-swift.struct~1Code~1inactiveSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppPushManagerErrorInactiveSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppPushManagerError-swift.struct~1Code/title",
          "value": "NEAppPushManagerError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppPushManagerError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppPushManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppPushManagerError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppPushManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppPushManagerError-swift.struct~1Code~1internalError/title",
          "value": "NEAppPushManagerErrorInternalError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppPushManagerError-swift.struct~1Code~1internalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppPushManagerErrorInternalError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppPushManagerError-swift.struct~1Code~1configurationNotLoaded/title",
          "value": "NEAppPushManagerErrorConfigurationNotLoaded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEAppPushManagerError-swift.struct~1Code~1configurationNotLoaded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEAppPushManagerErrorConfigurationNotLoaded"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/neapppushmanagererror-swift.struct/code/configurationnotloaded"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/neapppushmanagererror-swift.struct/code/configurationnotloaded"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
