{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutput"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutput/recordedDuration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SCRecordingOutput(py)recordedDuration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "recordedDuration"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@CMTime",
        "text": "CMTime"
      }
    ],
    "modules": [
      {
        "name": "ScreenCaptureKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "recordedDuration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "recordedDuration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "recordedDuration"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMTime",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CMTime",
              "text": "CMTime"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit": {
      "abstract": [
        {
          "text": "Filter and select screen content and stream it to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ScreenCaptureKit",
      "type": "topic",
      "url": "/documentation/screencapturekit"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutput": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCRecordingOutput"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCRecordingOutput"
        }
      ],
      "role": "symbol",
      "title": "SCRecordingOutput",
      "type": "topic",
      "url": "/documentation/screencapturekit/screcordingoutput"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutput/recordedDuration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordedDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutput/recordedDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordedDuration"
        }
      ],
      "role": "symbol",
      "title": "recordedDuration",
      "type": "topic",
      "url": "/documentation/screencapturekit/screcordingoutput/recordedduration"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutput/recordedFileSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordedFileSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutput/recordedFileSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordedFileSize"
        }
      ],
      "role": "symbol",
      "title": "recordedFileSize",
      "type": "topic",
      "url": "/documentation/screencapturekit/screcordingoutput/recordedfilesize"
    },
    "doc://com.externally.resolved.symbol/c:@SA@CMTime": {
      "abstract": [
        {
          "text": "A structure that represents time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMTime",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTime",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMTime"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-recording-output",
      "generated": true,
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutput/recordedFileSize"
      ],
      "title": "Configuring the recording output"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "recordedDuration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recordedDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutput"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-recording-output",
              "generated": true,
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCRecordingOutput/recordedFileSize"
              ],
              "title": "Configuring the recording output"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@SA@CMTime",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@CMTime",
                    "text": "CMTime"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "recordedDuration"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@SA@CMTime/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " { ... } "
            },
            {
              "kind": "identifier",
              "text": "CMTime"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutput/title",
          "value": "SCRecordingOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCRecordingOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCRecordingOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutput~1recordedFileSize/title",
          "value": "recordedFileSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutput~1recordedFileSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recordedFileSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutput~1recordedDuration/title",
          "value": "recordedDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCRecordingOutput~1recordedDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "recordedDuration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/screencapturekit/screcordingoutput/recordedduration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/screencapturekit/screcordingoutput/recordedduration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
