{
  "abstract": [
    {
      "text": "Information about a Core ML model error.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLModelError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MLModelError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct": {
      "abstract": [
        {
          "text": "Information about a Core ML model error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLModelError"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelError"
        }
      ],
      "role": "symbol",
      "title": "MLModelError",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Information about a Core ML model error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MLModelError.Code",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/code"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/customLayer": {
      "abstract": [
        {
          "text": "An error code for problems related to custom layers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customLayer"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/customLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelErrorCustomLayer"
        }
      ],
      "role": "symbol",
      "title": "MLModelError.Code.customLayer",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/code/customlayer"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/customModel": {
      "abstract": [
        {
          "text": "An error code for problems related to custom models.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customModel"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/customModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelErrorCustomModel"
        }
      ],
      "role": "symbol",
      "title": "MLModelError.Code.customModel",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/code/custommodel"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/featureType": {
      "abstract": [
        {
          "text": "An error code for problems related to model features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "featureType"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/featureType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelErrorFeatureType"
        }
      ],
      "role": "symbol",
      "title": "MLModelError.Code.featureType",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/code/featuretype"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/generic": {
      "abstract": [
        {
          "text": "An error code for runtime issues that don’t apply to the other error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "generic"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/generic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelErrorGeneric"
        }
      ],
      "role": "symbol",
      "title": "MLModelError.Code.generic",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/code/generic"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/code/init(rawvalue:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/io": {
      "abstract": [
        {
          "text": "An error code for problems related to the system’s input or output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "io"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/io",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelErrorIO"
        }
      ],
      "role": "symbol",
      "title": "MLModelError.Code.io",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/code/io"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/modelCollection": {
      "abstract": [
        {
          "text": "An error code for problems related to retrieving a model collection from the deployment system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modelCollection"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/modelCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelErrorModelCollection"
        }
      ],
      "role": "symbol",
      "title": "MLModelError.Code.modelCollection",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/code/modelcollection"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/modelDecryption": {
      "abstract": [
        {
          "text": "An error code for problems related to decrypting models.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modelDecryption"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/modelDecryption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelErrorModelDecryption"
        }
      ],
      "role": "symbol",
      "title": "MLModelError.Code.modelDecryption",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/code/modeldecryption"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/modelDecryptionKeyFetch": {
      "abstract": [
        {
          "text": "An error code for problems related to retrieving a model’s decryption key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modelDecryptionKeyFetch"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/modelDecryptionKeyFetch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelErrorModelDecryptionKeyFetch"
        }
      ],
      "role": "symbol",
      "title": "MLModelError.Code.modelDecryptionKeyFetch",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/code/modeldecryptionkeyfetch"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/parameters": {
      "abstract": [
        {
          "text": "An error code for problems related to model parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parameters"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/parameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelErrorParameters"
        }
      ],
      "role": "symbol",
      "title": "MLModelError.Code.parameters",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/code/parameters"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/predictionCancelled": {
      "abstract": [
        {
          "text": "An error code for problems related to canceling the prediction before it completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predictionCancelled"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/predictionCancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelErrorPredictionCancelled"
        }
      ],
      "role": "symbol",
      "title": "MLModelError.Code.predictionCancelled",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/code/predictioncancelled"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/update": {
      "abstract": [
        {
          "text": "An error code for problems related to on-device model updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "update"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/update",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelErrorUpdate"
        }
      ],
      "role": "symbol",
      "title": "MLModelError.Code.update",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerror-swift.struct/code/update"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelErrorDomain": {
      "abstract": [
        {
          "text": "The domain for Core ML errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLModelErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "MLModelErrorDomain",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelerrordomain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Model-errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct",
        "doc://com.apple.coreml/documentation/CoreML/MLModelErrorDomain"
      ],
      "title": "Model errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-Codes",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/featureType",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/parameters",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/modelCollection",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/modelDecryptionKeyFetch",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/modelDecryption",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/update",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/customLayer",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/customModel",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/io",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/predictionCancelled",
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/generic"
      ],
      "title": "Error Codes"
    },
    {
      "anchor": "Error-Domain",
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLModelErrorDomain"
      ],
      "title": "Error Domain"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLModelError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreml/documentation/CoreML"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/featureType",
                "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/parameters",
                "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/modelCollection",
                "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/modelDecryptionKeyFetch",
                "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/modelDecryption",
                "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/update",
                "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/customLayer",
                "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/customModel",
                "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/io",
                "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/predictionCancelled",
                "doc://com.apple.coreml/documentation/CoreML/MLModelError-swift.struct/Code/generic"
              ],
              "title": "Error Codes"
            },
            {
              "anchor": "Error-Domain",
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLModelErrorDomain"
              ],
              "title": "Error Domain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Model-errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLModelErrorDomain"
              ],
              "title": "Model errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MLModelError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1io/title",
          "value": "MLModelErrorIO"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1io/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelErrorIO"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1generic/title",
          "value": "MLModelErrorGeneric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1generic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelErrorGeneric"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1customModel/title",
          "value": "MLModelErrorCustomModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1customModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelErrorCustomModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1parameters/title",
          "value": "MLModelErrorParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1parameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelErrorParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1modelDecryption/title",
          "value": "MLModelErrorModelDecryption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1modelDecryption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelErrorModelDecryption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1customLayer/title",
          "value": "MLModelErrorCustomLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1customLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelErrorCustomLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1update/title",
          "value": "MLModelErrorUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1update/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelErrorUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelErrorDomain/title",
          "value": "MLModelErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1predictionCancelled/title",
          "value": "MLModelErrorPredictionCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1predictionCancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelErrorPredictionCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1modelDecryptionKeyFetch/title",
          "value": "MLModelErrorModelDecryptionKeyFetch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1modelDecryptionKeyFetch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelErrorModelDecryptionKeyFetch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code/title",
          "value": "MLModelError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1featureType/title",
          "value": "MLModelErrorFeatureType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1featureType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelErrorFeatureType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1modelCollection/title",
          "value": "MLModelErrorModelCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelError-swift.struct~1Code~1modelCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelErrorModelCollection"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/mlmodelerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreml/mlmodelerror-swift.struct/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
