{
  "abstract": [
    {
      "text": "Requests access to accounts of the specified type.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/requestAccessToAccounts(with:options:completion:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accounts/documentation/Accounts",
        "doc://com.apple.accounts/documentation/Accounts/ACAccountStore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/requestAccessToAccountsWithType:withCompletionHandler:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ACAccountStore(im)requestAccessToAccountsWithType:withCompletionHandler:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "requestAccessToAccountsWithType:withCompletionHandler:"
      }
    ],
    "modules": [
      {
        "name": "Accounts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "requestAccessToAccountsWithType:withCompletionHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "6.0",
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "6.0",
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "requestAccessToAccountsWithType:withCompletionHandler:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "requestAccessToAccountsWithType:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ACAccountType",
              "text": "ACAccountType"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "accountType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "withCompletionHandler:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreRequestAccessCompletionHandler",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ACAccountStoreRequestAccessCompletionHandler",
              "text": "ACAccountStoreRequestAccessCompletionHandler"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "handler"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The account type.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "accountType"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The handler to call when access is granted or denied. The handler is called on an arbitrary queue.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "handler"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method displays a dialog to the user confirming whether the application has access to the account. If access is granted, the application has access to protected properties of and operations on all accounts of the specified type.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accounts/documentation/Accounts": {
      "abstract": [
        {
          "text": "Help users access and manage their external accounts from within your app, without requiring them to enter login credentials.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.accounts/documentation/Accounts",
      "kind": "symbol",
      "role": "collection",
      "title": "Accounts",
      "type": "topic",
      "url": "/documentation/accounts"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStore": {
      "abstract": [
        {
          "text": "The object you use to request, manage, and store the user’s account information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountStore"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountStore"
        }
      ],
      "role": "symbol",
      "title": "ACAccountStore",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstore"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/requestAccessToAccounts(with:options:completion:)": {
      "abstract": [
        {
          "text": "Obtains permission to access protected user properties.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestAccessToAccounts"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ACAccountType",
          "text": "ACAccountType"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ACAccountStoreRequestAccessCompletionHandler",
          "text": "ACAccountStoreRequestAccessCompletionHandler"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/requestAccessToAccounts(with:options:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestAccessToAccountsWithType:options:completion:"
        }
      ],
      "role": "symbol",
      "title": "requestAccessToAccounts(with:options:completion:)",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstore/requestaccesstoaccounts(with:options:completion:)"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/requestAccessToAccountsWithType:withCompletionHandler:": {
      "abstract": [
        {
          "text": "Requests access to accounts of the specified type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "requestAccessToAccountsWithType:withCompletionHandler:"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/requestAccessToAccountsWithType:withCompletionHandler:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestAccessToAccountsWithType:withCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestAccessToAccountsWithType:withCompletionHandler:",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstore/requestaccesstoaccountswithtype:withcompletionhandler:"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreRequestAccessCompletionHandler": {
      "abstract": [
        {
          "text": "Specifies a handler to call when access is granted or denied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountStoreRequestAccessCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreRequestAccessCompletionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountStoreRequestAccessCompletionHandler"
        }
      ],
      "role": "symbol",
      "title": "ACAccountStoreRequestAccessCompletionHandler",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstorerequestaccesscompletionhandler"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountType": {
      "abstract": [
        {
          "text": "An object that encapsulates information about all accounts of a particular type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountType"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountType"
        }
      ],
      "role": "symbol",
      "title": "ACAccountType",
      "type": "topic",
      "url": "/documentation/accounts/acaccounttype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Requesting-Access",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/requestAccessToAccounts(with:options:completion:)",
        "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreRequestAccessCompletionHandler"
      ],
      "title": "Requesting Access"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountType/title",
          "value": "ACAccountType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStoreRequestAccessCompletionHandler/title",
          "value": "ACAccountStoreRequestAccessCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStoreRequestAccessCompletionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStoreRequestAccessCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStoreRequestAccessCompletionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStoreRequestAccessCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1requestAccessToAccounts(with:options:completion:)/title",
          "value": "requestAccessToAccountsWithType:options:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1requestAccessToAccounts(with:options:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestAccessToAccountsWithType:options:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore/title",
          "value": "ACAccountStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStore"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accounts/acaccountstore/requestaccesstoaccountswithtype:withcompletionhandler:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
