{
  "abstract": [
    {
      "text": "Saves an account to the Accounts database.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use appropriate non-Apple SDK corresponding to the type of account you want to reference instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accounts/documentation/Accounts",
        "doc://com.apple.accounts/documentation/Accounts/ACAccountStore"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/saveAccount(_:withCompletionHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ACAccountStore(im)saveAccount:withCompletionHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "saveAccount"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ACAccount",
        "text": "ACAccount"
      },
      {
        "kind": "text",
        "text": "!, "
      },
      {
        "kind": "externalParam",
        "text": "withCompletionHandler"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@ACAccountStoreSaveCompletionHandler",
        "text": "ACAccountStoreSaveCompletionHandler"
      },
      {
        "kind": "text",
        "text": "!)"
      }
    ],
    "modules": [
      {
        "name": "Accounts"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "saveAccount:withCompletionHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "6.0",
        "message": "Use appropriate non-Apple SDK corresponding to the type of account you want to reference instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "6.0",
        "message": "Use appropriate non-Apple SDK corresponding to the type of account you want to reference instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "message": "Use appropriate non-Apple SDK corresponding to the type of account you want to reference instead",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "12.0",
        "introducedAt": "10.8",
        "message": "Use appropriate non-Apple SDK corresponding to the type of account you want to reference instead",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "saveAccount(_:withCompletionHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "saveAccount"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "account"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccount",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ACAccount",
              "text": "ACAccount"
            },
            {
              "kind": "text",
              "text": "!, "
            },
            {
              "kind": "externalParam",
              "text": "withCompletionHandler"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreSaveCompletionHandler",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@ACAccountStoreSaveCompletionHandler",
              "text": "ACAccountStoreSaveCompletionHandler"
            },
            {
              "kind": "text",
              "text": "!)"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "saveAccount"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "account"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccount",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ACAccount",
              "text": "ACAccount"
            },
            {
              "kind": "text",
              "text": "!) "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "throws"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The account to save.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "account"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The handler to call when the operation completes. The handler is called on an arbitrary queue.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "completionHandler"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You can call this method from synchronous code using a completion handler, as shown on this page, or you can call it as an asynchronous method that has the following declaration:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "code": [
                "func saveAccount(_ account: ACAccount!) async throws -> Bool"
              ],
              "syntax": "swift",
              "type": "codeListing"
            },
            {
              "inlineContent": [
                {
                  "text": "For information about concurrency and asynchronous code in Swift, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "If the account type supports authentication and the account isn’t authenticated, the account server uses the account’s credentials to authenticate it. If the authentication is successful, the account is saved; otherwise it’s not saved.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accounts/documentation/Accounts": {
      "abstract": [
        {
          "text": "Help users access and manage their external accounts from within your app, without requiring them to enter login credentials.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.accounts/documentation/Accounts",
      "kind": "symbol",
      "role": "collection",
      "title": "Accounts",
      "type": "topic",
      "url": "/documentation/accounts"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccount": {
      "abstract": [
        {
          "text": "The information associated with one of the user’s accounts.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccount"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccount"
        }
      ],
      "role": "symbol",
      "title": "ACAccount",
      "type": "topic",
      "url": "/documentation/accounts/acaccount"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStore": {
      "abstract": [
        {
          "text": "The object you use to request, manage, and store the user’s account information.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountStore"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountStore"
        }
      ],
      "role": "symbol",
      "title": "ACAccountStore",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstore"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/saveAccount(_:withCompletionHandler:)": {
      "abstract": [
        {
          "text": "Saves an account to the Accounts database.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saveAccount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ACAccount",
          "text": "ACAccount"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "withCompletionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ACAccountStoreSaveCompletionHandler",
          "text": "ACAccountStoreSaveCompletionHandler"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStore/saveAccount(_:withCompletionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveAccount:withCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "saveAccount(_:withCompletionHandler:)",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstore/saveaccount(_:withcompletionhandler:)"
    },
    "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreSaveCompletionHandler": {
      "abstract": [
        {
          "text": "Specifies a handler to call when an Accounts database operation is complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ACAccountStoreSaveCompletionHandler"
        }
      ],
      "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreSaveCompletionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ACAccountStoreSaveCompletionHandler"
        }
      ],
      "role": "symbol",
      "title": "ACAccountStoreSaveCompletionHandler",
      "type": "topic",
      "url": "/documentation/accounts/acaccountstoresavecompletionhandler"
    },
    "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously": {
      "abstract": [
        {
          "text": "Learn how functions and methods that take a completion handler are converted to Swift asynchronous functions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/calling-objective-c-apis-asynchronously",
      "kind": "article",
      "role": "article",
      "title": "Calling Objective-C APIs Asynchronously",
      "type": "topic",
      "url": "/documentation/Swift/calling-objective-c-apis-asynchronously"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Saving-Accounts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreSaveCompletionHandler"
      ],
      "title": "Saving Accounts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "12.0",
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "saveAccount:withCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveAccount:withCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accounts/documentation/Accounts",
                "doc://com.apple.accounts/documentation/Accounts/ACAccountStore"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Saving-Accounts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreSaveCompletionHandler"
              ],
              "title": "Saving Accounts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "saveAccount:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccount",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ACAccount",
                    "text": "ACAccount"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "account"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "withCompletionHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.accounts/documentation/Accounts/ACAccountStoreSaveCompletionHandler",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@ACAccountStoreSaveCompletionHandler",
                    "text": "ACAccountStoreSaveCompletionHandler"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completionHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The account to save.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "account"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The handler to call when the operation completes. The handler is called on an arbitrary queue.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "completionHandler"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use appropriate non-Apple SDK corresponding to the type of account you want to reference instead",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStoreSaveCompletionHandler/title",
          "value": "ACAccountStoreSaveCompletionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStoreSaveCompletionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStoreSaveCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStoreSaveCompletionHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStoreSaveCompletionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1saveAccount(_:withCompletionHandler:)/title",
          "value": "saveAccount:withCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore~1saveAccount(_:withCompletionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveAccount:withCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccount/title",
          "value": "ACAccount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore/title",
          "value": "ACAccountStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accounts~1documentation~1Accounts~1ACAccountStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ACAccountStore"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accounts/acaccountstore/saveaccount(_:withcompletionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accounts/acaccountstore/saveaccount(_:withcompletionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
