{
  "abstract": [
    {
      "text": "Returns the group identity with the given POSIX GID in the specified identity authority.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.collaboration/documentation/Collaboration",
        "doc://com.apple.collaboration/documentation/Collaboration/CBGroupIdentity"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.collaboration/documentation/Collaboration/CBGroupIdentity/init(posixGID:authority:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CBGroupIdentity(cm)groupIdentityWithPosixGID:authority:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "?("
      },
      {
        "kind": "externalParam",
        "text": "posixGID"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@gid_t",
        "text": "gid_t"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "authority"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CBIdentityAuthority",
        "text": "CBIdentityAuthority"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Collaboration"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "groupIdentityWithPosixGID:authority:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(posixGID:authority:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "?("
            },
            {
              "kind": "externalParam",
              "text": "posixGID"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "gid"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@gid_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@gid_t",
              "text": "gid_t"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "authority"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CBIdentityAuthority",
              "text": "CBIdentityAuthority"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The GID of the group identity you are searching for.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "gid"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An identity authority in which to search for the group identity.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "authority"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The group identity object with the given GID in the specified identity authority, or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if no identity exists with the specified GID.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.collaboration/documentation/Collaboration": {
      "abstract": [
        {
          "text": "Find and access identities, that is, users and groups. Display the Identity Picker, which lets users create and select identities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration",
      "kind": "symbol",
      "role": "collection",
      "title": "Collaboration",
      "type": "topic",
      "url": "/documentation/collaboration"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBGroupIdentity": {
      "abstract": [
        {
          "text": "An object of the ",
          "type": "text"
        },
        {
          "code": "CBGroupIdentity",
          "type": "codeVoice"
        },
        {
          "text": " class represents a group identity and is used for viewing the attributes of group identities from an identity authority. The principal attributes of a ",
          "type": "text"
        },
        {
          "code": "CBGroupIdentity",
          "type": "codeVoice"
        },
        {
          "text": " object are a POSIX group identifier (GID) and a list of members.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBGroupIdentity"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBGroupIdentity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBGroupIdentity"
        }
      ],
      "role": "symbol",
      "title": "CBGroupIdentity",
      "type": "topic",
      "url": "/documentation/collaboration/cbgroupidentity"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBGroupIdentity/init(posixGID:authority:)": {
      "abstract": [
        {
          "text": "Returns the group identity with the given POSIX GID in the specified identity authority.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "posixGID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@gid_t",
          "text": "gid_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "authority"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CBIdentityAuthority",
          "text": "CBIdentityAuthority"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBGroupIdentity/init(posixGID:authority:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "groupIdentityWithPosixGID:authority:"
        }
      ],
      "role": "symbol",
      "title": "init(posixGID:authority:)",
      "type": "topic",
      "url": "/documentation/collaboration/cbgroupidentity/init(posixgid:authority:)"
    },
    "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority": {
      "abstract": [
        {
          "text": "An identity authority is a database that stores information about identities. The ",
          "type": "text"
        },
        {
          "code": "CBIdentityAuthority",
          "type": "codeVoice"
        },
        {
          "text": " class defines one or more identity authorities. You can search this database for identities in conjunction with the ",
          "type": "text"
        },
        {
          "code": "CBIdentity",
          "type": "codeVoice"
        },
        {
          "text": " class factory methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CBIdentityAuthority"
        }
      ],
      "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CBIdentityAuthority"
        }
      ],
      "role": "symbol",
      "title": "CBIdentityAuthority",
      "type": "topic",
      "url": "/documentation/collaboration/cbidentityauthority"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@gid_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@gid_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "gid_t",
      "type": "topic",
      "url": "/documentation/kernel/gid_t"
    },
    "https://developer.apple.com/library/archive/documentation/Networking/Conceptual/IdentityServices_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004490": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Networking/Conceptual/IdentityServices_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004490",
      "title": "Identity Services Programming Guide",
      "titleInlineContent": [
        {
          "text": "Identity Services Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Networking/Conceptual/IdentityServices_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004490"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "https://developer.apple.com/library/archive/documentation/Networking/Conceptual/IdentityServices_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004490"
      ],
      "title": "Related Documentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "groupIdentityWithPosixGID:authority:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "groupIdentityWithPosixGID:authority:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.collaboration/documentation/Collaboration",
                "doc://com.apple.collaboration/documentation/Collaboration/CBGroupIdentity"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "https://developer.apple.com/library/archive/documentation/Networking/Conceptual/IdentityServices_ProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40004490"
              ],
              "title": "Related Documentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBGroupIdentity",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CBGroupIdentity",
                    "text": "CBGroupIdentity"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "groupIdentityWithPosixGID:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@gid_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@gid_t",
                    "text": "gid_t"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "gid"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "authority:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.collaboration/documentation/Collaboration/CBIdentityAuthority",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CBIdentityAuthority",
                    "text": "CBIdentityAuthority"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "authority"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The GID of the group identity you are searching for.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "gid"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An identity authority in which to search for the group identity.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "authority"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The group identity object with the given GID in the specified identity authority, or ",
                    "type": "text"
                  },
                  {
                    "code": "nil",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if no identity exists with the specified GID.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBGroupIdentity~1init(posixGID:authority:)/title",
          "value": "groupIdentityWithPosixGID:authority:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBGroupIdentity~1init(posixGID:authority:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "groupIdentityWithPosixGID:authority:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBGroupIdentity/title",
          "value": "CBGroupIdentity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBGroupIdentity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBGroupIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBGroupIdentity/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBGroupIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityAuthority/title",
          "value": "CBIdentityAuthority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityAuthority/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CBIdentityAuthority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.collaboration~1documentation~1Collaboration~1CBIdentityAuthority/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CBIdentityAuthority"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/collaboration/cbgroupidentity/init(posixgid:authority:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/collaboration/cbgroupidentity/init(posixgid:authority:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
