{
  "abstract": [
    {
      "text": "The window appears in only one space at a time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWindowCollectionBehavior/NSWindowCollectionBehaviorDefault"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSWindowCollectionBehavior@NSWindowCollectionBehaviorDefault",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSWindowCollectionBehaviorDefault"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSWindowCollectionBehaviorDefault"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "NSWindowCollectionBehaviorDefault"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorDefault"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct": {
      "abstract": [
        {
          "text": "Window collection behaviors related to Mission Control, Spaces, and Stage Manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CollectionBehavior"
        }
      ],
      "role": "symbol",
      "title": "NSWindow.CollectionBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/canJoinAllSpaces": {
      "abstract": [
        {
          "text": "The window can appear in all spaces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canJoinAllSpaces"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/canJoinAllSpaces",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorCanJoinAllSpaces"
        }
      ],
      "role": "symbol",
      "title": "canJoinAllSpaces",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/canjoinallspaces"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/moveToActiveSpace": {
      "abstract": [
        {
          "text": "When the window becomes active, move it to the active space instead of switching spaces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moveToActiveSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowCollectionBehavior",
          "text": "CollectionBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/moveToActiveSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorMoveToActiveSpace"
        }
      ],
      "role": "symbol",
      "title": "moveToActiveSpace",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/collectionbehavior-swift.struct/movetoactivespace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindowCollectionBehavior/NSWindowCollectionBehaviorDefault": {
      "abstract": [
        {
          "text": "The window appears in only one space at a time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSWindowCollectionBehaviorDefault"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindowCollectionBehavior/NSWindowCollectionBehaviorDefault",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWindowCollectionBehaviorDefault",
      "type": "topic",
      "url": "/documentation/appkit/nswindowcollectionbehavior/nswindowcollectionbehaviordefault"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Spaces",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/canJoinAllSpaces",
        "doc://com.apple.appkit/documentation/AppKit/NSWindow/CollectionBehavior-swift.struct/moveToActiveSpace"
      ],
      "title": "Spaces"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct/title",
          "value": "NSWindowCollectionBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1moveToActiveSpace/title",
          "value": "NSWindowCollectionBehaviorMoveToActiveSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1moveToActiveSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorMoveToActiveSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1canJoinAllSpaces/title",
          "value": "NSWindowCollectionBehaviorCanJoinAllSpaces"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1CollectionBehavior-swift.struct~1canJoinAllSpaces/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWindowCollectionBehaviorCanJoinAllSpaces"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nswindowcollectionbehavior/nswindowcollectionbehaviordefault"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
