{
  "abstract": [
    {
      "text": "A channel error that indicates the system can’t perform the action because there’s no active channel with the UUID you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pushtotalk/documentation/PushToTalk",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/channelNotFound"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC14PTChannelErrorLeV15channelNotFoundSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "channelNotFound"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC14PTChannelErrorLeV",
        "text": "PTChannelError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@PTChannelError",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Push to Talk"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "channelNotFound"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "channelNotFound"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC14PTChannelErrorLeV",
              "text": "PTChannelError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@PTChannelError",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk": {
      "abstract": [
        {
          "text": "Display the system user interface for your app’s Push to Talk services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk",
      "kind": "symbol",
      "role": "collection",
      "title": "Push to Talk",
      "type": "topic",
      "url": "/documentation/pushtotalk"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents a channel error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PTChannelError"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PTChannelError"
        }
      ],
      "role": "symbol",
      "title": "PTChannelError",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for channel operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PTChannelError.Code",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/code"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/appNotForeground": {
      "abstract": [
        {
          "text": "A channel error that indicates the operation failed because the app isn’t in the foreground.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appNotForeground"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14PTChannelErrorLeV",
          "text": "PTChannelError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PTChannelError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/appNotForeground",
      "kind": "symbol",
      "role": "symbol",
      "title": "appNotForeground",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/appnotforeground"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/callActive": {
      "abstract": [
        {
          "text": "A channel error that indicates there’s an active call that prevents the channel action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callActive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14PTChannelErrorLeV",
          "text": "PTChannelError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PTChannelError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/callActive",
      "kind": "symbol",
      "role": "symbol",
      "title": "callActive",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/callactive"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/channelLimitReached": {
      "abstract": [
        {
          "text": "A channel error that indicates you reached the maximum of one active channel at a time for the entire device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelLimitReached"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14PTChannelErrorLeV",
          "text": "PTChannelError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PTChannelError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/channelLimitReached",
      "kind": "symbol",
      "role": "symbol",
      "title": "channelLimitReached",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/channellimitreached"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/channelNotFound": {
      "abstract": [
        {
          "text": "A channel error that indicates the system can’t perform the action because there’s no active channel with the UUID you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "channelNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14PTChannelErrorLeV",
          "text": "PTChannelError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PTChannelError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/channelNotFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "channelNotFound",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/channelnotfound"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/deviceManagementRestriction": {
      "abstract": [
        {
          "text": "A channel error that indicates a device-management policy or profile forbids joining the channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceManagementRestriction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14PTChannelErrorLeV",
          "text": "PTChannelError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PTChannelError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/deviceManagementRestriction",
      "kind": "symbol",
      "role": "symbol",
      "title": "deviceManagementRestriction",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/devicemanagementrestriction"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/screenTimeRestriction": {
      "abstract": [
        {
          "text": "A channel error that indicates a Screen Time restriction prevents the action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenTimeRestriction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14PTChannelErrorLeV",
          "text": "PTChannelError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PTChannelError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/screenTimeRestriction",
      "kind": "symbol",
      "role": "symbol",
      "title": "screenTimeRestriction",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/screentimerestriction"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/transmissionInProgress": {
      "abstract": [
        {
          "text": "A channel error that indicates a transmission is already in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transmissionInProgress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14PTChannelErrorLeV",
          "text": "PTChannelError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PTChannelError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/transmissionInProgress",
      "kind": "symbol",
      "role": "symbol",
      "title": "transmissionInProgress",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/transmissioninprogress"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/transmissionNotAllowed": {
      "abstract": [
        {
          "text": "A channel error that indicates the current transmission mode of the channel doesn’t allow the mode you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transmissionNotAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14PTChannelErrorLeV",
          "text": "PTChannelError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PTChannelError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/transmissionNotAllowed",
      "kind": "symbol",
      "role": "symbol",
      "title": "transmissionNotAllowed",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/transmissionnotallowed"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/transmissionNotFound": {
      "abstract": [
        {
          "text": "A channel error that indicates there’s no transmission to stop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transmissionNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14PTChannelErrorLeV",
          "text": "PTChannelError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PTChannelError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/transmissionNotFound",
      "kind": "symbol",
      "role": "symbol",
      "title": "transmissionNotFound",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/transmissionnotfound"
    },
    "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/unknown": {
      "abstract": [
        {
          "text": "A channel error that indicates an unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC14PTChannelErrorLeV",
          "text": "PTChannelError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PTChannelError",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/pushtotalk/ptchannelerror-swift.struct/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/unknown",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/appNotForeground",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/channelLimitReached",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/callActive",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/transmissionInProgress",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/transmissionNotFound",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/deviceManagementRestriction",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/screenTimeRestriction",
        "doc://com.apple.pushtotalk/documentation/PushToTalk/PTChannelError-swift.struct/transmissionNotAllowed"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code/title",
          "value": "PTChannelError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pushtotalk~1documentation~1PushToTalk~1PTChannelError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PTChannelError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pushtotalk/ptchannelerror-swift.struct/channelnotfound"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
