{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudio/documentation/CoreAudio",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction1Over2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AudioLevelControlTransferFunction@kAudioLevelControlTranferFunction1Over2",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "tranferFunction1Over2"
      }
    ],
    "modules": [
      {
        "name": "Core Audio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kAudioLevelControlTranferFunction1Over2"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AudioLevelControlTransferFunction.tranferFunction1Over2"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "tranferFunction1Over2"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudio/documentation/CoreAudio": {
      "abstract": [
        {
          "text": "Use the Core Audio framework to interact with device’s audio hardware.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio",
      "type": "topic",
      "url": "/documentation/coreaudio"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AudioLevelControlTransferFunction"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AudioLevelControlTransferFunction"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction10Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction10Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction10Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction10Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction10Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction10over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction11Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction11Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction11Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction11Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction11Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction11over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction12Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction12Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction12Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction12Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction12Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction12over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction1Over2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction1Over2"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction1Over2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction1Over2"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction1Over2",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction1over2"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction1Over3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction1Over3"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction1Over3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction1Over3"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction1Over3",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction1over3"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction2Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction2Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction2Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction2Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction2Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction2over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction3Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction3Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction3Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction3over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction3Over2"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction3Over2"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction3Over2",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction3over2"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction3Over4"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction3Over4"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction3Over4",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction3over4"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction4Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction4Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction4Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction4Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction4Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction4over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction5Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction5Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction5Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction5Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction5Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction5over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction6Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction6Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction6Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction6Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction6Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction6over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction7Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction7Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction7Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction7Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction7Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction7over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction8Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction8Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction8Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction8Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction8Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction8over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction9Over1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunction9Over1"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction9Over1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunction9Over1"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunction9Over1",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction9over1"
    },
    "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunctionLinear": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tranferFunctionLinear"
        }
      ],
      "identifier": "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunctionLinear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAudioLevelControlTranferFunctionLinear"
        }
      ],
      "role": "symbol",
      "title": "AudioLevelControlTransferFunction.tranferFunctionLinear",
      "type": "topic",
      "url": "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunctionlinear"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction10Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction11Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction12Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction1Over3",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction2Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over2",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over4",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction4Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction5Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction6Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction7Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction8Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction9Over1",
        "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunctionLinear"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kAudioLevelControlTranferFunction1Over2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction1Over2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudio/documentation/CoreAudio",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction10Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction11Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction12Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction1Over3",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction2Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over2",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction3Over4",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction4Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction5Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction6Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction7Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction8Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunction9Over1",
                "doc://com.apple.coreaudio/documentation/CoreAudio/AudioLevelControlTransferFunction/tranferFunctionLinear"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kAudioLevelControlTranferFunction1Over2"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction12Over1/title",
          "value": "kAudioLevelControlTranferFunction12Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction12Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction12Over1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction3Over4/title",
          "value": "kAudioLevelControlTranferFunction3Over4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction3Over4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction3Over4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction2Over1/title",
          "value": "kAudioLevelControlTranferFunction2Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction2Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction2Over1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction1Over2/title",
          "value": "kAudioLevelControlTranferFunction1Over2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction1Over2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction1Over2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction6Over1/title",
          "value": "kAudioLevelControlTranferFunction6Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction6Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction6Over1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction3Over2/title",
          "value": "kAudioLevelControlTranferFunction3Over2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction3Over2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction3Over2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction4Over1/title",
          "value": "kAudioLevelControlTranferFunction4Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction4Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction4Over1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction5Over1/title",
          "value": "kAudioLevelControlTranferFunction5Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction5Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction5Over1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction3Over1/title",
          "value": "kAudioLevelControlTranferFunction3Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction3Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction3Over1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction7Over1/title",
          "value": "kAudioLevelControlTranferFunction7Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction7Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction7Over1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction9Over1/title",
          "value": "kAudioLevelControlTranferFunction9Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction9Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction9Over1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunctionLinear/title",
          "value": "kAudioLevelControlTranferFunctionLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunctionLinear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunctionLinear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction10Over1/title",
          "value": "kAudioLevelControlTranferFunction10Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction10Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction10Over1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction8Over1/title",
          "value": "kAudioLevelControlTranferFunction8Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction8Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction8Over1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction1Over3/title",
          "value": "kAudioLevelControlTranferFunction1Over3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction1Over3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction1Over3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction11Over1/title",
          "value": "kAudioLevelControlTranferFunction11Over1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction~1tranferFunction11Over1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAudioLevelControlTranferFunction11Over1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction/title",
          "value": "AudioLevelControlTransferFunction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioLevelControlTransferFunction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudio~1documentation~1CoreAudio~1AudioLevelControlTransferFunction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AudioLevelControlTransferFunction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction1over2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudio/audiolevelcontroltransferfunction/tranferfunction1over2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
