{
  "abstract": [
    {
      "text": "An option that indicates the interruption by another audio session has ended and the app can resume its audio session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionOptions/shouldResume"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVAudioSessionInterruptionOptions@AVAudioSessionInterruptionOptionShouldResume",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "shouldResume"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AVAudioSession",
        "text": "AVAudioSession"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AVAudioSessionInterruptionOptions",
        "text": "InterruptionOptions"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioSessionInterruptionOptionShouldResume"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "shouldResume"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "shouldResume"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AVAudioSession",
              "text": "AVAudioSession"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AVAudioSessionInterruptionOptions",
              "text": "InterruptionOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the interruption type is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionType/ended",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", check for this value in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionInterruptionOptionKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key in the ",
              "type": "text"
            },
            {
              "code": "userInfo",
              "type": "codeVoice"
            },
            {
              "text": " dictionary of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/interruptionNotification",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " notification. It serves as a hint that it’s appropriate for your app to resume audio playback without waiting for user input.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Apps that don’t require user input to begin audio playback (such as games) can ignore this flag and resume playback when an interruption ends.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession": {
      "abstract": [
        {
          "text": "An object that communicates to the system how you intend to use audio in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionOptions": {
      "abstract": [
        {
          "text": "Constants that indicate the state of an audio session after an interruption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InterruptionOptions"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "InterruptionOptions"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.InterruptionOptions",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/interruptionoptions"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionOptions/shouldResume": {
      "abstract": [
        {
          "text": "An option that indicates the interruption by another audio session has ended and the app can resume its audio session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldResume"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudioSessionInterruptionOptions",
          "text": "InterruptionOptions"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionOptions/shouldResume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionInterruptionOptionShouldResume"
        }
      ],
      "role": "symbol",
      "title": "shouldResume",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/interruptionoptions/shouldresume"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionType/ended": {
      "abstract": [
        {
          "text": "A type that indicates that the operating system ended interrupting the audio session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ended"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionType/ended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionInterruptionTypeEnded"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.InterruptionType.ended",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/interruptiontype/ended"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/interruptionNotification": {
      "abstract": [
        {
          "text": "A notification the system posts when an audio interruption occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interruptionNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/interruptionNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionInterruptionNotification"
        }
      ],
      "role": "symbol",
      "title": "interruptionNotification",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/interruptionnotification"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionInterruptionOptionKey": {
      "abstract": [
        {
          "text": "A user info key to retrieve the interruption option.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSessionInterruptionOptionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionInterruptionOptionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionInterruptionOptionKey"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSessionInterruptionOptionKey",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosessioninterruptionoptionkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioSessionInterruptionOptionShouldResume"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionInterruptionOptionShouldResume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/InterruptionOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVAudioSessionInterruptionOptionShouldResume"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/title",
          "value": "AVAudioSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionOptions~1shouldResume/title",
          "value": "AVAudioSessionInterruptionOptionShouldResume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionOptions~1shouldResume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionInterruptionOptionShouldResume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionType~1ended/title",
          "value": "AVAudioSessionInterruptionTypeEnded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionType~1ended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionInterruptionTypeEnded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSessionInterruptionOptionKey/title",
          "value": "AVAudioSessionInterruptionOptionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSessionInterruptionOptionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionInterruptionOptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1interruptionNotification/title",
          "value": "AVAudioSessionInterruptionNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1interruptionNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionInterruptionNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionOptions/title",
          "value": "AVAudioSessionInterruptionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionInterruptionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1InterruptionOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionInterruptionOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiosession/interruptionoptions/shouldresume"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiosession/interruptionoptions/shouldresume"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
