{
  "abstract": [
    {
      "text": "Train a machine learning model to classify natural language text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.CreateML/documentation/CreateML"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.CreateML/documentation/CreateML/creating-a-text-classifier-model"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Create ML"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Creating a text classifier model"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A text classifier is a machine learning model that’s been trained to recognize patterns",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in natural language text, like the sentiment expressed by a sentence.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "creating-a-text-classifer-model-1",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You train a text classifier by showing it lots of examples of text you’ve already",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "labeled—for example, movie reviews that you’ve already labeled as positive, negative,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "or neutral.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "creating-a-text-classifer-model-2",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Import-your-data",
          "level": 3,
          "text": "Import your data",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Start by gathering textual data and importing it into an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLDataTable",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "instance. You can create a data table from JSON and CSV formats. Or, if your textual",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "data is in a collection of files, you can sort them into folders, using the folder",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "names as labels, similar to the image data source used in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/creating-an-image-classifier-model",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "As an example, consider a JSON file containing movie reviews that you’ve categorized",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "by sentiment. Each entry contains a pair of keys, the ",
              "type": "text"
            },
            {
              "code": "text",
              "type": "codeVoice"
            },
            {
              "text": " and the ",
              "type": "text"
            },
            {
              "code": "label",
              "type": "codeVoice"
            },
            {
              "text": ". The",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "values of those keys are the input samples used to train your model. The JSON snippet",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "below shows three pairs of sentences with their sentiment labels.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// JSON file",
            "[",
            "    {",
            "        \"text\": \"The movie was fantastic!\",",
            "        \"label\": \"positive\"",
            "    }, {",
            "        \"text\": \"Very boring. Fell asleep.\",",
            "        \"label\": \"negative\"",
            "    }, {",
            "        \"text\": \"It was just OK.\",",
            "        \"label\": \"neutral\"",
            "    } ...",
            "]"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In a macOS playground, create a data frame using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/TabularData",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "framework.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import TabularData",
            "",
            "let data = try DataFrame(contentsOfJSONFile: URL(fileURLWithPath: \"<#/path/to/read/data.json#>\"))"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The resulting data frame has two columns, named ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "text",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "label",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", derived from",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the keys in the JSON file. The column names can be anything, as long as they are",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "meaningful to you, because you’ll use them as parameters in other methods.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Prepare-your-data-for-training-and-evaluation",
          "level": 3,
          "text": "Prepare your data for training and evaluation",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The data you use to train your model needs to be different from the data you use to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "evaluate your model. Use the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/TabularData/DataFrameProtocol/stratifiedSplit(on:by:randomSeed:)-9iauf",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "method to split your data into two data frames, one for training and the other for testing. The training data frame",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "contains the majority of your data, and the testing data frame contains the remaining 20 percent.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let (trainingData, testingData) = data.stratifiedSplit(on: \"text\", by: 0.8)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Choose-model-training-parameters",
          "level": 3,
          "text": "Choose model training parameters",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can use model training parameters to control the learning process. Choose a classifier algorithm type by specifying",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/ModelAlgorithmType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " parameter. The",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/ModelAlgorithmType/maxEnt(revision:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " algorithm trains quickly and performs well",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "for a wide variety of data. It’s a good starting point algorithm while you’re exploring your data and models.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can choose a transfer learning algorithm,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/ModelAlgorithmType/transferLearning(_:revision:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".  Transfer learning models",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "use a pre-trained model as a feature extractor, you specify the ",
              "type": "text"
            },
            {
              "code": "MLTextClassifier.FeatureExtractorType",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Transfer learning models can take",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "longer to train, but can improve accuracy because the baseline model has already been trained on a large amount of text",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in a specific language.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your data contains multiple languages, choose either the maximum entropy algorithm",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/ModelAlgorithmType/maxEnt(revision:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the transfer learning algorithm ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/ModelAlgorithmType/transferLearning(_:revision:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and set its ",
              "type": "text"
            },
            {
              "code": "MLTextClassifier.FeatureExtractorType",
              "type": "codeVoice"
            },
            {
              "text": " to the Bidirectional Encoder Representations from",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Transformers (BERT) embedding feature extractor ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType/bertEmbedding",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your data contains a single language, use the conditional random fields algorithm",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/ModelAlgorithmType/crf(revision:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the transfer learning algorithm ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/ModelAlgorithmType/transferLearning(_:revision:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and set",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "its ",
              "type": "text"
            },
            {
              "code": "MLTextClassifier.FeatureExtractorType",
              "type": "codeVoice"
            },
            {
              "text": " to the Embeddings from Language Models (ELMo) embedding feature extractor",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType/elmoEmbedding",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/ModelParameters-swift.struct/ValidationData-swift.enum",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " parameter to specify the evaluation data that’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "held out from training your model. During the training process, use the validation data to estimate your model’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "ability to correctly classify new examples. Depending on the validation accuracy, the classifier algorithm might adjust",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "values within the model — or stop the training process, if the accuracy is high enough. Since the split of your data is",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "random, you might get a different result each time you train your model.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let parameters = MLTextClassifier.ModelParameters(",
            "    validation: .split(strategy: .automatic),",
            "    algorithm: .transferLearning(.bertEmbedding, revision: 1),",
            "    language: .english",
            ")"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Create-and-train-a-text-classifier",
          "level": 3,
          "text": "Create and train a text classifier",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Create an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with your training data frame",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and the column names.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let sentimentClassifier = try MLTextClassifier(",
            "    trainingData: trainingData,",
            "    textColumn: \"text\",",
            "    labelColumn: \"label\",",
            "    parameters: parameters",
            ")"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To measure how accurately the model (",
              "type": "text"
            },
            {
              "code": "sentimentClassifier",
              "type": "codeVoice"
            },
            {
              "text": ") performs on the training and validation data, use",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLClassifierMetrics/classificationError",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties of the model’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/trainingMetrics",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/validationMetrics",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "properties.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Calculate training accuracy as a percentage.",
            "let trainingAccuracy = (1.0 - sentimentClassifier.trainingMetrics.classificationError) * 100",
            "",
            "// Calculate validation accuracy as a percentage.",
            "let validationAccuracy = (1.0 - sentimentClassifier.validationMetrics.classificationError) * 100"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Evaluate-a-classifiers-accuracy",
          "level": 3,
          "text": "Evaluate a classifier’s accuracy",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Next, evaluate your trained model’s performance by testing it against sentences it’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "never seen before. Pass your testing data frame to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/evaluation(on:)-8ch4k",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "method, which returns an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLClassifierMetrics",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let evaluationMetrics = sentimentClassifier.evaluation(on: testingData, textColumn: \"text\", labelColumn: \"label\")"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To get the evaluation accuracy, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLClassifierMetrics/classificationError",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "property of the returned ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLClassifierMetrics",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Calculate evaluation accuracy as a percentage.",
            "let evaluationAccuracy = (1.0 - evaluationMetrics.classificationError) * 100"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If the evaluation performance isn’t good enough, you may need to retrain with more",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "data or make other adjustments. For information about improving model performance,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/improving-your-model-s-accuracy",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Save-a-Core-ML-model",
          "level": 3,
          "text": "Save a Core ML model",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When your model is performing well enough, you’re ready to save it so you can use",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "it in your app. Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/write(to:metadata:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to write the Core ML model file to disk. Provide any information about the model, like its author, version, or",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "description in an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLModelMetadata",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let metadata = MLModelMetadata(author: \"John Appleseed\",",
            "                               shortDescription: \"A model trained to classify movie review sentiment\",",
            "                               version: \"1.0\")",
            "",
            "try sentimentClassifier.write(to: URL(fileURLWithPath: \"<#/path/to/save/SentimentClassifier.mlmodel#>\"),",
            "                              metadata: metadata)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Specify the file name using the ",
              "type": "text"
            },
            {
              "code": "fileURLWithPath:",
              "type": "codeVoice"
            },
            {
              "text": " parameter, in the above code, ",
              "type": "text"
            },
            {
              "code": "SentimentClassifier.mlmodel",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-a-Core-ML-model-to-your-app",
          "level": 3,
          "text": "Add a Core ML model to your app",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "With your app open in Xcode, drag the ",
              "type": "text"
            },
            {
              "code": "SentimentClassifier.mlmodel",
              "type": "codeVoice"
            },
            {
              "text": " file into the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "navigation pane. Xcode compiles the model and generates a ",
              "type": "text"
            },
            {
              "code": "SentimentClassifier",
              "type": "codeVoice"
            },
            {
              "text": " class",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "for use in your app. Select the ",
              "type": "text"
            },
            {
              "code": "SentimentClassifier.mlmodel",
              "type": "codeVoice"
            },
            {
              "text": " file in Xcode to view",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "additional information about the model.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/NaturalLanguage/NLModel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the Natural Language framework from the ",
              "type": "text"
            },
            {
              "code": "SentimentClassifier",
              "type": "codeVoice"
            },
            {
              "text": " to ensure that the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "tokenization is consistent between training and deployment. Then use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/NaturalLanguage/NLModel/predictedLabel(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to generate predictions on new text inputs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "import NaturalLanguage",
            "import CoreML",
            "",
            "let mlModel = try SentimentClassifier(configuration: MLModelConfiguration()).model",
            "",
            "let sentimentPredictor = try NLModel(mlModel: mlModel)",
            "sentimentPredictor.predictedLabel(for: \"It was the best I've ever seen!\")"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "creating-a-text-classifer-model-1": {
      "alt": "Diagram showing how a text string maps to a label.",
      "identifier": "creating-a-text-classifer-model-1",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8b58fe67739dc2f7f3bb472ed54312b3/creating-a-text-classifer-model-1@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/26bce4fdefecd43be4c4ec8ef61fa7f5/creating-a-text-classifer-model-1~dark@2x.png"
        }
      ]
    },
    "creating-a-text-classifer-model-2": {
      "alt": "Diagram showing how you train a text classifier with Create ML using training data.",
      "identifier": "creating-a-text-classifer-model-2",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/928f87b97f9f6bea77d959ecc545107a/creating-a-text-classifer-model-2@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ff4b464c87108741db095ba4e89e9bea/creating-a-text-classifer-model-2~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.CreateML/documentation/CreateML": {
      "abstract": [
        {
          "text": "Create machine learning models for use in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML",
      "kind": "symbol",
      "role": "collection",
      "title": "Create ML",
      "type": "topic",
      "url": "/documentation/createml"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLClassifierMetrics": {
      "abstract": [
        {
          "text": "Metrics you use to evaluate a classifier’s performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLClassifierMetrics"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLClassifierMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLClassifierMetrics"
        }
      ],
      "role": "symbol",
      "title": "MLClassifierMetrics",
      "type": "topic",
      "url": "/documentation/createml/mlclassifiermetrics"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLClassifierMetrics/classificationError": {
      "abstract": [
        {
          "text": "The fraction of incorrectly labeled examples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classificationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLClassifierMetrics/classificationError",
      "kind": "symbol",
      "role": "symbol",
      "title": "classificationError",
      "type": "topic",
      "url": "/documentation/createml/mlclassifiermetrics/classificationerror"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLDataTable": {
      "abstract": [
        {
          "text": "A table of data for training or evaluating a machine learning model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLDataTable"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLDataTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLDataTable"
        }
      ],
      "role": "symbol",
      "title": "MLDataTable",
      "type": "topic",
      "url": "/documentation/createml/mldatatable"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLGazetteer": {
      "abstract": [
        {
          "text": "A collection of terms and their labels, which augments a tagger that analyzes natural language text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLGazetteer"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLGazetteer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLGazetteer"
        }
      ],
      "role": "symbol",
      "title": "MLGazetteer",
      "type": "topic",
      "url": "/documentation/createml/mlgazetteer"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLModelMetadata": {
      "abstract": [
        {
          "text": "Information about a model that’s stored in a Core ML model file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLModelMetadata"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLModelMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelMetadata"
        }
      ],
      "role": "symbol",
      "title": "MLModelMetadata",
      "type": "topic",
      "url": "/documentation/createml/mlmodelmetadata"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier": {
      "abstract": [
        {
          "text": "A model you train to classify natural language text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLTextClassifier"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLTextClassifier"
        }
      ],
      "role": "symbol",
      "title": "MLTextClassifier",
      "type": "topic",
      "url": "/documentation/createml/mltextclassifier"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType/bertEmbedding": {
      "abstract": [
        {
          "text": "A feature extractor that provides BERT contextual word embeddings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bertEmbedding"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType/bertEmbedding",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLTextClassifier.FeatureExtractorType.bertEmbedding",
      "type": "topic",
      "url": "/documentation/createml/mltextclassifier/featureextractortype/bertembedding"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType/elmoEmbedding": {
      "abstract": [
        {
          "text": "A feature extractor that provides ELMo contextual word embeddings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elmoEmbedding"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/FeatureExtractorType/elmoEmbedding",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLTextClassifier.FeatureExtractorType.elmoEmbedding",
      "type": "topic",
      "url": "/documentation/createml/mltextclassifier/featureextractortype/elmoembedding"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/ModelAlgorithmType": {
      "abstract": [
        {
          "text": "The type of algorithm that a text classifier uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ModelAlgorithmType"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/ModelAlgorithmType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ModelAlgorithmType"
        }
      ],
      "role": "symbol",
      "title": "MLTextClassifier.ModelAlgorithmType",
      "type": "topic",
      "url": "/documentation/createml/mltextclassifier/modelalgorithmtype"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/ModelAlgorithmType/crf(revision:)": {
      "abstract": [
        {
          "text": "A text classification algorithm that uses a statistical model of transition probabilities between words.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "crf"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "revision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/ModelAlgorithmType/crf(revision:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLTextClassifier.ModelAlgorithmType.crf(revision:)",
      "type": "topic",
      "url": "/documentation/createml/mltextclassifier/modelalgorithmtype/crf(revision:)"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/ModelAlgorithmType/maxEnt(revision:)": {
      "abstract": [
        {
          "text": "A text classification algorithm that uses multinomial logistic regression based on the frequencies of words, independent of context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxEnt"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "revision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/ModelAlgorithmType/maxEnt(revision:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLTextClassifier.ModelAlgorithmType.maxEnt(revision:)",
      "type": "topic",
      "url": "/documentation/createml/mltextclassifier/modelalgorithmtype/maxent(revision:)"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/ModelAlgorithmType/transferLearning(_:revision:)": {
      "abstract": [
        {
          "text": "A text classification algorithm that uses transfer learning by leveraging a feature extractor to generate embeddings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transferLearning"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML16MLTextClassifierV",
          "text": "MLTextClassifier"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML16MLTextClassifierV20FeatureExtractorTypeO",
          "text": "FeatureExtractorType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "revision"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/ModelAlgorithmType/transferLearning(_:revision:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "MLTextClassifier.ModelAlgorithmType.transferLearning(_:revision:)",
      "type": "topic",
      "url": "/documentation/createml/mltextclassifier/modelalgorithmtype/transferlearning(_:revision:)"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/ModelParameters-swift.struct/ValidationData-swift.enum": {
      "abstract": [
        {
          "text": "The validation data that a text classifier uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ValidationData"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/ModelParameters-swift.struct/ValidationData-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ValidationData"
        }
      ],
      "role": "symbol",
      "title": "MLTextClassifier.ModelParameters.ValidationData",
      "type": "topic",
      "url": "/documentation/createml/mltextclassifier/modelparameters-swift.struct/validationdata-swift.enum"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/evaluation(on:)-8ch4k": {
      "abstract": [
        {
          "text": "Computes evaluation metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "evaluation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "on"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML16MLTextClassifierV",
          "text": "MLTextClassifier"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML16MLTextClassifierV10DataSourceO",
          "text": "DataSource"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML19MLClassifierMetricsV",
          "text": "MLClassifierMetrics"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/evaluation(on:)-8ch4k",
      "kind": "symbol",
      "role": "symbol",
      "title": "evaluation(on:)",
      "type": "topic",
      "url": "/documentation/createml/mltextclassifier/evaluation(on:)-8ch4k"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/trainingMetrics": {
      "abstract": [
        {
          "text": "Measurements of the classifier’s performance on the training data set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trainingMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML19MLClassifierMetricsV",
          "text": "MLClassifierMetrics"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/trainingMetrics",
      "kind": "symbol",
      "role": "symbol",
      "title": "trainingMetrics",
      "type": "topic",
      "url": "/documentation/createml/mltextclassifier/trainingmetrics"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/validationMetrics": {
      "abstract": [
        {
          "text": "Measurements of the classifier’s performance on the validation data set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validationMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML19MLClassifierMetricsV",
          "text": "MLClassifierMetrics"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/validationMetrics",
      "kind": "symbol",
      "role": "symbol",
      "title": "validationMetrics",
      "type": "topic",
      "url": "/documentation/createml/mltextclassifier/validationmetrics"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/write(to:metadata:)": {
      "abstract": [
        {
          "text": "Exports the text classifier as a Core ML model file at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "write"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML15MLModelMetadataV",
          "text": "MLModelMetadata"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier/write(to:metadata:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "write(to:metadata:)",
      "type": "topic",
      "url": "/documentation/createml/mltextclassifier/write(to:metadata:)"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordEmbedding": {
      "abstract": [
        {
          "text": "A map of strings in a vector space that enable your app to find similar",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "strings by looking at a string’s neighbors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLWordEmbedding"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordEmbedding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLWordEmbedding"
        }
      ],
      "role": "symbol",
      "title": "MLWordEmbedding",
      "type": "topic",
      "url": "/documentation/createml/mlwordembedding"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger": {
      "abstract": [
        {
          "text": "A word-tagging model you train to classify natural language text at the word level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLWordTagger"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLWordTagger"
        }
      ],
      "role": "symbol",
      "title": "MLWordTagger",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger"
    },
    "doc://com.apple.CreateML/documentation/CreateML/creating-an-image-classifier-model": {
      "abstract": [
        {
          "text": "Train a machine learning model to classify images, and add it to your Core ML app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/creating-an-image-classifier-model",
      "kind": "article",
      "role": "article",
      "title": "Creating an Image Classifier Model",
      "type": "topic",
      "url": "/documentation/createml/creating-an-image-classifier-model"
    },
    "doc://com.apple.CreateML/documentation/CreateML/improving-your-model-s-accuracy": {
      "abstract": [
        {
          "text": "Use metrics to tune the performance of your machine learning model.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/improving-your-model-s-accuracy",
      "kind": "article",
      "role": "article",
      "title": "Improving Your Model’s Accuracy",
      "type": "topic",
      "url": "/documentation/createml/improving-your-model-s-accuracy"
    },
    "doc://com.apple.documentation/documentation/NaturalLanguage/NLModel": {
      "abstract": [
        {
          "text": "A custom model trained to classify or tag natural language text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLModel"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NaturalLanguage/NLModel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NLModel",
      "type": "topic",
      "url": "/documentation/NaturalLanguage/NLModel"
    },
    "doc://com.apple.documentation/documentation/NaturalLanguage/NLModel/predictedLabel(for:)": {
      "abstract": [
        {
          "text": "Predicts a label for the given input string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predictedLabel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "string"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NaturalLanguage/NLModel/predictedLabel(for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "predictedLabel(for:)",
      "type": "topic",
      "url": "/documentation/NaturalLanguage/NLModel/predictedLabel(for:)"
    },
    "doc://com.apple.documentation/documentation/NaturalLanguage/creating-a-word-tagger-model": {
      "abstract": [
        {
          "text": "Train a machine learning model to tag individual words in natural language text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NaturalLanguage/creating-a-word-tagger-model",
      "kind": "article",
      "role": "article",
      "title": "Creating a word tagger model",
      "type": "topic",
      "url": "/documentation/NaturalLanguage/creating-a-word-tagger-model"
    },
    "doc://com.apple.documentation/documentation/TabularData": {
      "abstract": [
        {
          "text": "Import, organize, and prepare a table of data to train a machine learning model.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/TabularData",
      "kind": "symbol",
      "role": "collection",
      "title": "TabularData",
      "type": "topic",
      "url": "/documentation/TabularData"
    },
    "doc://com.apple.documentation/documentation/TabularData/DataFrameProtocol/stratifiedSplit(on:by:randomSeed:)-9iauf": {
      "abstract": [
        {
          "text": "Generates two data frames by randomly splitting the rows of a column, which you select by its name, into strata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stratifiedSplit"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "on"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "columnName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "by"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "proportion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "randomSeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": "? = nil) -> ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:11TabularData0B5FrameV",
          "text": "DataFrame"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:11TabularData0B5FrameV",
          "text": "DataFrame"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/TabularData/DataFrameProtocol/stratifiedSplit(on:by:randomSeed:)-9iauf",
      "kind": "symbol",
      "role": "symbol",
      "title": "stratifiedSplit(on:by:randomSeed:)",
      "type": "topic",
      "url": "/documentation/TabularData/DataFrameProtocol/stratifiedSplit(on:by:randomSeed:)-9iauf"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text-Models",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/NaturalLanguage/creating-a-word-tagger-model",
        "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger",
        "doc://com.apple.CreateML/documentation/CreateML/MLGazetteer",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordEmbedding"
      ],
      "title": "Text Models"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NaturalLanguage~1NLModel~1predictedLabel(for:)/title",
          "value": "predictedLabelForString:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NaturalLanguage~1NLModel~1predictedLabel(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "predictedLabelForString:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "string"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NaturalLanguage~1NLModel/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NLModel"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/createml/creating-a-text-classifier-model"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
