{
  "abstract": [
    {
      "text": "A word-tagging model you train to classify natural language text at the word level.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.CreateML/documentation/CreateML"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:8CreateML12MLWordTaggerV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MLWordTagger"
      }
    ],
    "modules": [
      {
        "name": "Create ML"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLWordTagger"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "MLWordTagger"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MLWordTagger"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to create a custom word tagger to identify content",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "that’s relevant for your app, like product names and points of interest.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To use your custom word tagger in the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/NaturalLanguage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " framework,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "save it to a model file and import it into an",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/NaturalLanguage/NLModel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Then",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "add your custom",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/NaturalLanguage/NLModel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to an",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/NaturalLanguage/NLTagger",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "its",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/NaturalLanguage/NLTagger/setModels(_:forTagScheme:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.CreateML/documentation/CreateML": {
      "abstract": [
        {
          "text": "Create machine learning models for use in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML",
      "kind": "symbol",
      "role": "collection",
      "title": "Create ML",
      "type": "topic",
      "url": "/documentation/createml"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLGazetteer": {
      "abstract": [
        {
          "text": "A collection of terms and their labels, which augments a tagger that analyzes natural language text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLGazetteer"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLGazetteer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLGazetteer"
        }
      ],
      "role": "symbol",
      "title": "MLGazetteer",
      "type": "topic",
      "url": "/documentation/createml/mlgazetteer"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier": {
      "abstract": [
        {
          "text": "A model you train to classify natural language text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLTextClassifier"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLTextClassifier"
        }
      ],
      "role": "symbol",
      "title": "MLTextClassifier",
      "type": "topic",
      "url": "/documentation/createml/mltextclassifier"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordEmbedding": {
      "abstract": [
        {
          "text": "A map of strings in a vector space that enable your app to find similar",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "strings by looking at a string’s neighbors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLWordEmbedding"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordEmbedding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLWordEmbedding"
        }
      ],
      "role": "symbol",
      "title": "MLWordEmbedding",
      "type": "topic",
      "url": "/documentation/createml/mlwordembedding"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger": {
      "abstract": [
        {
          "text": "A word-tagging model you train to classify natural language text at the word level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLWordTagger"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLWordTagger"
        }
      ],
      "role": "symbol",
      "title": "MLWordTagger",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/CustomDebugStringConvertible-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/CustomDebugStringConvertible-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CustomDebugStringConvertible Implementations",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/customdebugstringconvertible-implementations"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/CustomPlaygroundDisplayConvertible-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/CustomPlaygroundDisplayConvertible-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CustomPlaygroundDisplayConvertible Implementations",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/customplaygrounddisplayconvertible-implementations"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/CustomStringConvertible-Implementations": {
      "abstract": [],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/CustomStringConvertible-Implementations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CustomStringConvertible Implementations",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/customstringconvertible-implementations"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/FeatureExtractorType": {
      "abstract": [
        {
          "text": "The feature extractors that are available to train a word tagger using with the transfer-learning algorithm option.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FeatureExtractorType"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/FeatureExtractorType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FeatureExtractorType"
        }
      ],
      "role": "symbol",
      "title": "MLWordTagger.FeatureExtractorType",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/featureextractortype"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/ModelAlgorithmType": {
      "abstract": [
        {
          "text": "The algorithm type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ModelAlgorithmType"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/ModelAlgorithmType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ModelAlgorithmType"
        }
      ],
      "role": "symbol",
      "title": "MLWordTagger.ModelAlgorithmType",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/modelalgorithmtype"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/ModelParameters-swift.struct": {
      "abstract": [
        {
          "text": "Parameters that specify model training parameters and validation data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ModelParameters"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/ModelParameters-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ModelParameters"
        }
      ],
      "role": "symbol",
      "title": "MLWordTagger.ModelParameters",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/modelparameters-swift.struct"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/Token": {
      "abstract": [
        {
          "text": "The token type of a word tagger, which is a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Token"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/Token",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Token"
        }
      ],
      "role": "symbol",
      "title": "MLWordTagger.Token",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/token"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/debugDescription": {
      "abstract": [
        {
          "text": "A text representation of the word tagger that’s suitable for output",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "during debugging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "debugDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/debugDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "debugDescription",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/debugdescription"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/description": {
      "abstract": [
        {
          "text": "A text representation of the word tagger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "description"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/description",
      "kind": "symbol",
      "role": "symbol",
      "title": "description",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/description"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/evaluation(on:)": {
      "abstract": [
        {
          "text": "Computes evaluation metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "evaluation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "on"
        },
        {
          "kind": "text",
          "text": ": [(tokens"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML12MLWordTaggerV",
          "text": "MLWordTagger"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML12MLWordTaggerV5Tokena",
          "text": "Token"
        },
        {
          "kind": "text",
          "text": "], labels"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "])]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML19MLWordTaggerMetricsV",
          "text": "MLWordTaggerMetrics"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/evaluation(on:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "evaluation(on:)",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/evaluation(on:)"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/evaluation(on:tokenColumn:labelColumn:)-31x1l": {
      "abstract": [
        {
          "text": "Computes evaluation metrics.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "evaluation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "on"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML11MLDataTableV",
          "text": "MLDataTable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "tokenColumn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "labelColumn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML19MLWordTaggerMetricsV",
          "text": "MLWordTaggerMetrics"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/evaluation(on:tokenColumn:labelColumn:)-31x1l",
      "kind": "symbol",
      "role": "symbol",
      "title": "evaluation(on:tokenColumn:labelColumn:)",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/evaluation(on:tokencolumn:labelcolumn:)-31x1l"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/evaluation(on:tokenColumn:labelColumn:)-7jhx7": {
      "abstract": [
        {
          "text": "Computes evaluation metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "evaluation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "on"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:11TabularData0B5FrameV",
          "text": "DataFrame"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "tokenColumn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "labelColumn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML19MLWordTaggerMetricsV",
          "text": "MLWordTaggerMetrics"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/evaluation(on:tokenColumn:labelColumn:)-7jhx7",
      "kind": "symbol",
      "role": "symbol",
      "title": "evaluation(on:tokenColumn:labelColumn:)",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/evaluation(on:tokencolumn:labelcolumn:)-7jhx7"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/init(trainingData:parameters:)": {
      "abstract": [
        {
          "text": "Creates a word tagger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "trainingData"
        },
        {
          "kind": "text",
          "text": ": [(tokens"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML12MLWordTaggerV",
          "text": "MLWordTagger"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML12MLWordTaggerV5Tokena",
          "text": "Token"
        },
        {
          "kind": "text",
          "text": "], labels"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "])], "
        },
        {
          "kind": "externalParam",
          "text": "parameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML12MLWordTaggerV",
          "text": "MLWordTagger"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML12MLWordTaggerV15ModelParametersV",
          "text": "ModelParameters"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/init(trainingData:parameters:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(trainingData:parameters:)",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/init(trainingdata:parameters:)"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/init(trainingData:tokenColumn:labelColumn:parameters:)-97qtg": {
      "abstract": [
        {
          "text": "Creates a word tagger.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "trainingData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML11MLDataTableV",
          "text": "MLDataTable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "tokenColumn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "labelColumn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "parameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML12MLWordTaggerV",
          "text": "MLWordTagger"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML12MLWordTaggerV15ModelParametersV",
          "text": "ModelParameters"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/init(trainingData:tokenColumn:labelColumn:parameters:)-97qtg",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(trainingData:tokenColumn:labelColumn:parameters:)",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/init(trainingdata:tokencolumn:labelcolumn:parameters:)-97qtg"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/init(trainingData:tokenColumn:labelColumn:parameters:)-9fci2": {
      "abstract": [
        {
          "text": "Creates a word tagger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "trainingData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:11TabularData0B5FrameV",
          "text": "DataFrame"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "tokenColumn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "labelColumn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "parameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML12MLWordTaggerV",
          "text": "MLWordTagger"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML12MLWordTaggerV15ModelParametersV",
          "text": "ModelParameters"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/init(trainingData:tokenColumn:labelColumn:parameters:)-9fci2",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(trainingData:tokenColumn:labelColumn:parameters:)",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/init(trainingdata:tokencolumn:labelcolumn:parameters:)-9fci2"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/model": {
      "abstract": [
        {
          "text": "The underlying Core ML model of the word tagger.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "model"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLModel",
          "text": "MLModel"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/model",
      "kind": "symbol",
      "role": "symbol",
      "title": "model",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/model"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/modelParameters-swift.property": {
      "abstract": [
        {
          "text": "The configuration parameters that the word tagger used for training during initialization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modelParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML12MLWordTaggerV",
          "text": "MLWordTagger"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML12MLWordTaggerV15ModelParametersV",
          "text": "ModelParameters"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/modelParameters-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "modelParameters",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/modelparameters-swift.property"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/playgroundDescription": {
      "abstract": [
        {
          "text": "A description of the word tagger in a playground.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playgroundDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/playgroundDescription",
      "kind": "symbol",
      "role": "symbol",
      "title": "playgroundDescription",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/playgrounddescription"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/prediction(from:)-7rqyq": {
      "abstract": [
        {
          "text": "Predicts a tag for each token in the specified array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prediction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML12MLWordTaggerV",
          "text": "MLWordTagger"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML12MLWordTaggerV5Tokena",
          "text": "Token"
        },
        {
          "kind": "text",
          "text": "]) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/prediction(from:)-7rqyq",
      "kind": "symbol",
      "role": "symbol",
      "title": "prediction(from:)",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/prediction(from:)-7rqyq"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/prediction(from:)-r5gb": {
      "abstract": [
        {
          "text": "Predicts a tag for the input string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prediction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/prediction(from:)-r5gb",
      "kind": "symbol",
      "role": "symbol",
      "title": "prediction(from:)",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/prediction(from:)-r5gb"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/predictionWithConfidence(from:)-37coi": {
      "abstract": [
        {
          "text": "Predicts tags and confidence scores for each token in the specified token array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predictionWithConfidence"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML12MLWordTaggerV",
          "text": "MLWordTagger"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML12MLWordTaggerV5Tokena",
          "text": "Token"
        },
        {
          "kind": "text",
          "text": "]) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> [["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "]]"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/predictionWithConfidence(from:)-37coi",
      "kind": "symbol",
      "role": "symbol",
      "title": "predictionWithConfidence(from:)",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/predictionwithconfidence(from:)-37coi"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/predictionWithConfidence(from:)-398qj": {
      "abstract": [
        {
          "text": "Predicts tags and confidence scores for the input string. Predicts tags and confidence scores for the input string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predictionWithConfidence"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> [["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "]]"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/predictionWithConfidence(from:)-398qj",
      "kind": "symbol",
      "role": "symbol",
      "title": "predictionWithConfidence(from:)",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/predictionwithconfidence(from:)-398qj"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/predictions(from:)-12r03": {
      "abstract": [
        {
          "text": "Predicts sequences of labels, token locations, and token lengths from the input strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predictions"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "S"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "S"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:11TabularData0B5FrameV",
          "text": "DataFrame"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/predictions(from:)-12r03",
      "kind": "symbol",
      "role": "symbol",
      "title": "predictions(from:)",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/predictions(from:)-12r03"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/predictions(from:)-22b8d": {
      "abstract": [
        {
          "text": "Predicts sequences of labels, token locations, and token lengths from the input column containing strings.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predictions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML12MLDataColumnV",
          "text": "MLDataColumn"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ">) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML11MLDataTableV",
          "text": "MLDataTable"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/predictions(from:)-22b8d",
      "kind": "symbol",
      "role": "symbol",
      "title": "predictions(from:)",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/predictions(from:)-22b8d"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/trainingMetrics": {
      "abstract": [
        {
          "text": "Measurements of the tagger’s performance on the training data set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trainingMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML19MLWordTaggerMetricsV",
          "text": "MLWordTaggerMetrics"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/trainingMetrics",
      "kind": "symbol",
      "role": "symbol",
      "title": "trainingMetrics",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/trainingmetrics"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/validationMetrics": {
      "abstract": [
        {
          "text": "Measurements of the tagger’s performance on the validation data set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "validationMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML19MLWordTaggerMetricsV",
          "text": "MLWordTaggerMetrics"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/validationMetrics",
      "kind": "symbol",
      "role": "symbol",
      "title": "validationMetrics",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/validationmetrics"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/write(to:metadata:)": {
      "abstract": [
        {
          "text": "Exports the word tagger as a Core ML model file at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "write"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML15MLModelMetadataV",
          "text": "MLModelMetadata"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/write(to:metadata:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "write(to:metadata:)",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/write(to:metadata:)"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/write(toFile:metadata:)": {
      "abstract": [
        {
          "text": "Exports the word tagger as a Core ML model file at the specified file path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "write"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:8CreateML15MLModelMetadataV",
          "text": "MLModelMetadata"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/write(toFile:metadata:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "write(toFile:metadata:)",
      "type": "topic",
      "url": "/documentation/createml/mlwordtagger/write(tofile:metadata:)"
    },
    "doc://com.apple.CreateML/documentation/CreateML/MLWordTaggerMetrics": {
      "abstract": [
        {
          "text": "Metrics you use to evaluate a word tagger’s performance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLWordTaggerMetrics"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/MLWordTaggerMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLWordTaggerMetrics"
        }
      ],
      "role": "symbol",
      "title": "MLWordTaggerMetrics",
      "type": "topic",
      "url": "/documentation/createml/mlwordtaggermetrics"
    },
    "doc://com.apple.CreateML/documentation/CreateML/creating-a-text-classifier-model": {
      "abstract": [
        {
          "text": "Train a machine learning model to classify natural language text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.CreateML/documentation/CreateML/creating-a-text-classifier-model",
      "kind": "article",
      "role": "article",
      "title": "Creating a text classifier model",
      "type": "topic",
      "url": "/documentation/createml/creating-a-text-classifier-model"
    },
    "doc://com.apple.documentation/documentation/NaturalLanguage": {
      "abstract": [
        {
          "text": "Analyze natural language text and deduce its language-specific metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NaturalLanguage",
      "kind": "symbol",
      "role": "collection",
      "title": "Natural Language",
      "type": "topic",
      "url": "/documentation/NaturalLanguage"
    },
    "doc://com.apple.documentation/documentation/NaturalLanguage/NLModel": {
      "abstract": [
        {
          "text": "A custom model trained to classify or tag natural language text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLModel"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NaturalLanguage/NLModel",
      "kind": "symbol",
      "role": "symbol",
      "title": "NLModel",
      "type": "topic",
      "url": "/documentation/NaturalLanguage/NLModel"
    },
    "doc://com.apple.documentation/documentation/NaturalLanguage/NLTagger": {
      "abstract": [
        {
          "text": "A tagger that analyzes natural language text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NLTagger"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NaturalLanguage/NLTagger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NLTagger",
      "type": "topic",
      "url": "/documentation/NaturalLanguage/NLTagger"
    },
    "doc://com.apple.documentation/documentation/NaturalLanguage/NLTagger/setModels(_:forTagScheme:)": {
      "abstract": [
        {
          "text": "Assigns models for a tag scheme.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setModels"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "models"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NLModel",
          "text": "NLModel"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "forTagScheme"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "tagScheme"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NLTagScheme",
          "text": "NLTagScheme"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NaturalLanguage/NLTagger/setModels(_:forTagScheme:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setModels(_:forTagScheme:)",
      "type": "topic",
      "url": "/documentation/NaturalLanguage/NLTagger/setModels(_:forTagScheme:)"
    },
    "doc://com.apple.documentation/documentation/NaturalLanguage/creating-a-word-tagger-model": {
      "abstract": [
        {
          "text": "Train a machine learning model to tag individual words in natural language text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/NaturalLanguage/creating-a-word-tagger-model",
      "kind": "article",
      "role": "article",
      "title": "Creating a word tagger model",
      "type": "topic",
      "url": "/documentation/NaturalLanguage/creating-a-word-tagger-model"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s34CustomPlaygroundDisplayConvertibleP": {
      "abstract": [
        {
          "text": "A type that supplies a custom description for playground logging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomPlaygroundDisplayConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s34CustomPlaygroundDisplayConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomPlaygroundDisplayConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomPlaygroundDisplayConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s34CustomPlaygroundDisplayConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text-Models",
      "generated": true,
      "identifiers": [
        "doc://com.apple.CreateML/documentation/CreateML/creating-a-text-classifier-model",
        "doc://com.apple.documentation/documentation/NaturalLanguage/creating-a-word-tagger-model",
        "doc://com.apple.CreateML/documentation/CreateML/MLTextClassifier",
        "doc://com.apple.CreateML/documentation/CreateML/MLGazetteer",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordEmbedding"
      ],
      "title": "Text Models"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-and-training-a-word-tagger",
      "identifiers": [
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/init(trainingData:parameters:)",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/init(trainingData:tokenColumn:labelColumn:parameters:)-97qtg",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/init(trainingData:tokenColumn:labelColumn:parameters:)-9fci2",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/Token",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/ModelParameters-swift.struct",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/modelParameters-swift.property"
      ],
      "title": "Creating and training a word tagger"
    },
    {
      "anchor": "Assessing-model-accuracy",
      "identifiers": [
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/trainingMetrics",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/validationMetrics",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTaggerMetrics"
      ],
      "title": "Assessing model accuracy"
    },
    {
      "anchor": "Evaluating-a-word-tagger",
      "identifiers": [
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/evaluation(on:tokenColumn:labelColumn:)-31x1l",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/evaluation(on:tokenColumn:labelColumn:)-7jhx7",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/evaluation(on:)"
      ],
      "title": "Evaluating a word tagger"
    },
    {
      "anchor": "Testing-a-word-tagger",
      "identifiers": [
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/predictions(from:)-12r03",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/predictions(from:)-22b8d",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/prediction(from:)-7rqyq",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/prediction(from:)-r5gb",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/predictionWithConfidence(from:)-398qj",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/predictionWithConfidence(from:)-37coi"
      ],
      "title": "Testing a word tagger"
    },
    {
      "anchor": "Saving-a-word-tagger",
      "identifiers": [
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/write(to:metadata:)",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/write(toFile:metadata:)"
      ],
      "title": "Saving a word tagger"
    },
    {
      "anchor": "Describing-a-word-tagger",
      "identifiers": [
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/model",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/description",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/debugDescription",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/playgroundDescription"
      ],
      "title": "Describing a word tagger"
    },
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/FeatureExtractorType",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/ModelAlgorithmType"
      ],
      "title": "Enumerations"
    },
    {
      "anchor": "Default-Implementations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/CustomDebugStringConvertible-Implementations",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/CustomPlaygroundDisplayConvertible-Implementations",
        "doc://com.apple.CreateML/documentation/CreateML/MLWordTagger/CustomStringConvertible-Implementations"
      ],
      "title": "Default Implementations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NaturalLanguage~1NLTagger/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NLTagger"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NaturalLanguage~1NLTagger~1setModels(_:forTagScheme:)/title",
          "value": "setModels:forTagScheme:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NaturalLanguage~1NLTagger~1setModels(_:forTagScheme:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "setModels:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:Q$objc(cs)NSArray",
              "text": "NSArray<NLModel *>"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "models"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "forTagScheme:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NLTagScheme",
              "text": "NLTagScheme"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "tagScheme"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1NaturalLanguage~1NLModel/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NLModel"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/createml/mlwordtagger"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
