{
  "abstract": [
    {
      "text": "Version 3.2 of the Metal shading language.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version3_2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLLanguageVersion@MTLLanguageVersion3_2",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "version3_2"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLLanguageVersion3_2"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLLanguageVersion.version3_2"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "version3_2"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion": {
      "abstract": [
        {
          "text": "Metal shading language versions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLLanguageVersion"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLanguageVersion"
        }
      ],
      "role": "symbol",
      "title": "MTLLanguageVersion",
      "type": "topic",
      "url": "/documentation/metal/mtllanguageversion"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version1_0": {
      "abstract": [
        {
          "text": "Version 1.0 of the Metal shading language.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version1_0"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version1_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLanguageVersion1_0"
        }
      ],
      "role": "symbol",
      "title": "MTLLanguageVersion.version1_0",
      "type": "topic",
      "url": "/documentation/metal/mtllanguageversion/version1_0"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version1_1": {
      "abstract": [
        {
          "text": "Version 1.1 of the Metal shading language.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version1_1"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version1_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLanguageVersion1_1"
        }
      ],
      "role": "symbol",
      "title": "MTLLanguageVersion.version1_1",
      "type": "topic",
      "url": "/documentation/metal/mtllanguageversion/version1_1"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version1_2": {
      "abstract": [
        {
          "text": "Version 1.2 of the Metal shading language.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version1_2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version1_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLanguageVersion1_2"
        }
      ],
      "role": "symbol",
      "title": "MTLLanguageVersion.version1_2",
      "type": "topic",
      "url": "/documentation/metal/mtllanguageversion/version1_2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version2_0": {
      "abstract": [
        {
          "text": "Version 2.0 of the Metal shading language.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version2_0"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version2_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLanguageVersion2_0"
        }
      ],
      "role": "symbol",
      "title": "MTLLanguageVersion.version2_0",
      "type": "topic",
      "url": "/documentation/metal/mtllanguageversion/version2_0"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version2_1": {
      "abstract": [
        {
          "text": "Version 2.1 of the Metal shading language.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version2_1"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version2_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLanguageVersion2_1"
        }
      ],
      "role": "symbol",
      "title": "MTLLanguageVersion.version2_1",
      "type": "topic",
      "url": "/documentation/metal/mtllanguageversion/version2_1"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version2_2": {
      "abstract": [
        {
          "text": "Version 2.2 of the Metal shading language.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version2_2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version2_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLanguageVersion2_2"
        }
      ],
      "role": "symbol",
      "title": "MTLLanguageVersion.version2_2",
      "type": "topic",
      "url": "/documentation/metal/mtllanguageversion/version2_2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version2_3": {
      "abstract": [
        {
          "text": "Version 2.3 of the Metal shading language.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version2_3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version2_3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLanguageVersion2_3"
        }
      ],
      "role": "symbol",
      "title": "MTLLanguageVersion.version2_3",
      "type": "topic",
      "url": "/documentation/metal/mtllanguageversion/version2_3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version2_4": {
      "abstract": [
        {
          "text": "Version 2.4 of the Metal shading language.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version2_4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version2_4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLanguageVersion2_4"
        }
      ],
      "role": "symbol",
      "title": "MTLLanguageVersion.version2_4",
      "type": "topic",
      "url": "/documentation/metal/mtllanguageversion/version2_4"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version3_0": {
      "abstract": [
        {
          "text": "Version 3.0 of the Metal shading language.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version3_0"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version3_0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLanguageVersion3_0"
        }
      ],
      "role": "symbol",
      "title": "MTLLanguageVersion.version3_0",
      "type": "topic",
      "url": "/documentation/metal/mtllanguageversion/version3_0"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version3_1": {
      "abstract": [
        {
          "text": "Version 3.1 of the Metal shading language.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version3_1"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version3_1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLanguageVersion3_1"
        }
      ],
      "role": "symbol",
      "title": "MTLLanguageVersion.version3_1",
      "type": "topic",
      "url": "/documentation/metal/mtllanguageversion/version3_1"
    },
    "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version3_2": {
      "abstract": [
        {
          "text": "Version 3.2 of the Metal shading language.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version3_2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version3_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLLanguageVersion3_2"
        }
      ],
      "role": "symbol",
      "title": "MTLLanguageVersion.version3_2",
      "type": "topic",
      "url": "/documentation/metal/mtllanguageversion/version3_2"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Version-Numbers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version1_1",
        "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version1_2",
        "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version2_0",
        "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version2_1",
        "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version2_2",
        "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version2_3",
        "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version2_4",
        "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version3_0",
        "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version3_1",
        "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version1_0"
      ],
      "title": "Version Numbers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLLanguageVersion3_2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLanguageVersion3_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Version-Numbers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version1_1",
                "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version1_2",
                "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version2_0",
                "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version2_1",
                "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version2_2",
                "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version2_3",
                "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version2_4",
                "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version3_0",
                "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version3_1",
                "doc://com.apple.metal/documentation/Metal/MTLLanguageVersion/version1_0"
              ],
              "title": "Version Numbers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLLanguageVersion3_2"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version3_2/title",
          "value": "MTLLanguageVersion3_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version3_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLanguageVersion3_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version3_0/title",
          "value": "MTLLanguageVersion3_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version3_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLanguageVersion3_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version1_0/title",
          "value": "MTLLanguageVersion1_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version1_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLanguageVersion1_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version2_3/title",
          "value": "MTLLanguageVersion2_3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version2_3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLanguageVersion2_3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version1_2/title",
          "value": "MTLLanguageVersion1_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version1_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLanguageVersion1_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version2_2/title",
          "value": "MTLLanguageVersion2_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version2_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLanguageVersion2_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version1_1/title",
          "value": "MTLLanguageVersion1_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version1_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLanguageVersion1_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version2_1/title",
          "value": "MTLLanguageVersion2_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version2_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLanguageVersion2_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version2_4/title",
          "value": "MTLLanguageVersion2_4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version2_4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLanguageVersion2_4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version2_0/title",
          "value": "MTLLanguageVersion2_0"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version2_0/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLanguageVersion2_0"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version3_1/title",
          "value": "MTLLanguageVersion3_1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion~1version3_1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLanguageVersion3_1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion/title",
          "value": "MTLLanguageVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLanguageVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLLanguageVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLLanguageVersion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtllanguageversion/version3_2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtllanguageversion/version3_2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
