{
  "abstract": [
    {
      "text": "Creates a Look Around preview with an initial scene, navigation, road label, points of interest, and badge position you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/LookAroundPreview"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/LookAroundPreview/init(initialScene:allowsNavigation:showsRoadLabels:pointsOfInterest:badgePosition:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:15_MapKit_SwiftUI17LookAroundPreviewV12initialScene16allowsNavigation15showsRoadLabels16pointsOfInterest13badgePositionACSo06MKLookfI0CSg_S2bAA05PointpQ10CategoriesVSo0tf5BadgeS0Vtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "initialScene"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MKLookAroundScene",
        "text": "MKLookAroundScene"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "allowsNavigation"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "showsRoadLabels"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "pointsOfInterest"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:15_MapKit_SwiftUI25PointOfInterestCategoriesV",
        "text": "PointOfInterestCategories"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "badgePosition"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@MKLookAroundBadgePosition",
        "text": "MKLookAroundBadgePosition"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "MapKit",
        "relatedModules": [
          "SwiftUI"
        ]
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(initialScene:allowsNavigation:showsRoadLabels:pointsOfInterest:badgePosition:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@preconcurrency"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "initialScene"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundScene",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MKLookAroundScene",
              "text": "MKLookAroundScene"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "allowsNavigation"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " = true, "
            },
            {
              "kind": "externalParam",
              "text": "showsRoadLabels"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " = true, "
            },
            {
              "kind": "externalParam",
              "text": "pointsOfInterest"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/PointOfInterestCategories",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:15_MapKit_SwiftUI25PointOfInterestCategoriesV",
              "text": "PointOfInterestCategories"
            },
            {
              "kind": "text",
              "text": " = .all, "
            },
            {
              "kind": "externalParam",
              "text": "badgePosition"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundBadgePosition",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@MKLookAroundBadgePosition",
              "text": "MKLookAroundBadgePosition"
            },
            {
              "kind": "text",
              "text": " = .topLeading)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The Look Around scene to display.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "initialScene"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A Boolean value that indicates whether the Look Around scene allows navigation after the user taps the Look Around preview to enter the full screen Look Around viewer. MapKit never allows navigation on the Look Around preview itself.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "allowsNavigation"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A Boolean value that indicates whether the Look Around scene shows road labels after the user taps the Look Around preview to enter the full screen Look Around viewer. MapKit never shows road labels on the Look Around preview itself.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "showsRoadLabels"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The categories of points of interest to display after the user taps the Look Around preview to enter the full screen Look Around viewer. MapKit never displays points of interest on the Look Around preview itself. By default, MapKit displays all points of interest categories.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "pointsOfInterest"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A value that controls the position of a badge on the Look Around preview.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "badgePosition"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Navigation refers to the ability to tap-to-navigate to a different vantage point in the Look Around scene and what a person can control through the use of the ",
              "type": "text"
            },
            {
              "code": "allowsNavigation",
              "type": "codeVoice"
            },
            {
              "text": " property. The framework refers to the ability to pan and zoom around the Look Around scene is as ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "exploring",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " and you can’t restrict it while in the Look Around viewer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The Look Around viewer isn’t available on macOS and ",
              "type": "text"
            },
            {
              "code": "allowsNavigation",
              "type": "codeVoice"
            },
            {
              "text": " has no effect; in iOS, exploration is always available in the Look Around viewer and you can’t disable it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/LookAroundPreview": {
      "abstract": [
        {
          "text": "A view that provides a Look Around preview for a specific geographic location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LookAroundPreview"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/LookAroundPreview",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LookAroundPreview"
        }
      ],
      "role": "symbol",
      "title": "LookAroundPreview",
      "type": "topic",
      "url": "/documentation/mapkit/lookaroundpreview"
    },
    "doc://com.apple.mapkit/documentation/MapKit/LookAroundPreview/init(initialScene:allowsNavigation:showsRoadLabels:pointsOfInterest:badgePosition:)": {
      "abstract": [
        {
          "text": "Creates a Look Around preview with an initial scene, navigation, road label, points of interest, and badge position you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "initialScene"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKLookAroundScene",
          "text": "MKLookAroundScene"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "allowsNavigation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "showsRoadLabels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "pointsOfInterest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:15_MapKit_SwiftUI25PointOfInterestCategoriesV",
          "text": "PointOfInterestCategories"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "badgePosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKLookAroundBadgePosition",
          "text": "MKLookAroundBadgePosition"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/LookAroundPreview/init(initialScene:allowsNavigation:showsRoadLabels:pointsOfInterest:badgePosition:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(initialScene:allowsNavigation:showsRoadLabels:pointsOfInterest:badgePosition:)",
      "type": "topic",
      "url": "/documentation/mapkit/lookaroundpreview/init(initialscene:allowsnavigation:showsroadlabels:pointsofinterest:badgeposition:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/LookAroundPreview/init(scene:allowsNavigation:showsRoadLabels:pointsOfInterest:badgePosition:)": {
      "abstract": [
        {
          "text": "Creates a Look Around preview with a binding to a scene, navigation, road label, points of interest, and badge position you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "scene"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI7BindingV",
          "text": "Binding"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKLookAroundScene",
          "text": "MKLookAroundScene"
        },
        {
          "kind": "text",
          "text": "?>, "
        },
        {
          "kind": "externalParam",
          "text": "allowsNavigation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "showsRoadLabels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "pointsOfInterest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:15_MapKit_SwiftUI25PointOfInterestCategoriesV",
          "text": "PointOfInterestCategories"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "badgePosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MKLookAroundBadgePosition",
          "text": "MKLookAroundBadgePosition"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/LookAroundPreview/init(scene:allowsNavigation:showsRoadLabels:pointsOfInterest:badgePosition:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(scene:allowsNavigation:showsRoadLabels:pointsOfInterest:badgePosition:)",
      "type": "topic",
      "url": "/documentation/mapkit/lookaroundpreview/init(scene:allowsnavigation:showsroadlabels:pointsofinterest:badgeposition:)"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundBadgePosition": {
      "abstract": [
        {
          "text": "Constants that control the position of badges on LookAround views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLookAroundBadgePosition"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundBadgePosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLookAroundBadgePosition"
        }
      ],
      "role": "symbol",
      "title": "MKLookAroundBadgePosition",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundbadgeposition"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundScene": {
      "abstract": [
        {
          "text": "A utility class that encapsulates information the framework requires to retrieve and display a specific Look Around location’s imagery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLookAroundScene"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLookAroundScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLookAroundScene"
        }
      ],
      "role": "symbol",
      "title": "MKLookAroundScene",
      "type": "topic",
      "url": "/documentation/mapkit/mklookaroundscene"
    },
    "doc://com.apple.mapkit/documentation/MapKit/PointOfInterestCategories": {
      "abstract": [
        {
          "text": "A structure you use to define points of interest to include or exclude on a map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PointOfInterestCategories"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/PointOfInterestCategories",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PointOfInterestCategories"
        }
      ],
      "role": "symbol",
      "title": "PointOfInterestCategories",
      "type": "topic",
      "url": "/documentation/mapkit/pointofinterestcategories"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Look-Around-preview",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/LookAroundPreview/init(scene:allowsNavigation:showsRoadLabels:pointsOfInterest:badgePosition:)"
      ],
      "title": "Creating a Look Around preview"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundScene/title",
          "value": "MKLookAroundScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLookAroundScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundScene/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLookAroundScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundBadgePosition/title",
          "value": "MKLookAroundBadgePosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundBadgePosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLookAroundBadgePosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundBadgePosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLookAroundBadgePosition"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/lookaroundpreview/init(initialscene:allowsnavigation:showsroadlabels:pointsofinterest:badgeposition:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
