{
  "abstract": [
    {
      "text": "The key name of the Kerberos session key type number.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/encryptionKeyTypeKeyName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ASAuthorizationProviderExtensionKerberosMapping(py)encryptionKeyTypeKeyName",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "encryptionKeyTypeKeyName"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Authentication Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "encryptionKeyTypeKeyName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "encryptionKeyTypeKeyName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "encryptionKeyTypeKeyName"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Ensure the value for this key is the correct encryption type for the session key. See section 7 of ",
              "type": "text"
            },
            {
              "identifier": "https://datatracker.ietf.org/doc/html/rfc3962",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices": {
      "abstract": [
        {
          "text": "Make it easy for users to log into apps and services.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
      "kind": "symbol",
      "role": "collection",
      "title": "Authentication Services",
      "type": "topic",
      "url": "/documentation/authenticationservices"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping": {
      "abstract": [
        {
          "text": "A set of Kerberos mappings that the system login process uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASAuthorizationProviderExtensionKerberosMapping"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ASAuthorizationProviderExtensionKerberosMapping"
        }
      ],
      "role": "symbol",
      "title": "ASAuthorizationProviderExtensionKerberosMapping",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationproviderextensionkerberosmapping"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/clientNameKeyName": {
      "abstract": [
        {
          "text": "The key name of the Kerberos client name string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientNameKeyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/clientNameKeyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clientNameKeyName"
        }
      ],
      "role": "symbol",
      "title": "clientNameKeyName",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationproviderextensionkerberosmapping/clientnamekeyname"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/encryptionKeyTypeKeyName": {
      "abstract": [
        {
          "text": "The key name of the Kerberos session key type number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encryptionKeyTypeKeyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/encryptionKeyTypeKeyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "encryptionKeyTypeKeyName"
        }
      ],
      "role": "symbol",
      "title": "encryptionKeyTypeKeyName",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationproviderextensionkerberosmapping/encryptionkeytypekeyname"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/messageBufferKeyName": {
      "abstract": [
        {
          "text": "The key name of the Base 64-encoded Kerberos AS-REP string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "messageBufferKeyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/messageBufferKeyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "messageBufferKeyName"
        }
      ],
      "role": "symbol",
      "title": "messageBufferKeyName",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationproviderextensionkerberosmapping/messagebufferkeyname"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/realmKeyName": {
      "abstract": [
        {
          "text": "The key name of the Kerberos realm string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "realmKeyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/realmKeyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "realmKeyName"
        }
      ],
      "role": "symbol",
      "title": "realmKeyName",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationproviderextensionkerberosmapping/realmkeyname"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/serviceNameKeyName": {
      "abstract": [
        {
          "text": "The key name of the Kerberos service name string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceNameKeyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/serviceNameKeyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serviceNameKeyName"
        }
      ],
      "role": "symbol",
      "title": "serviceNameKeyName",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationproviderextensionkerberosmapping/servicenamekeyname"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/sessionKeyKeyName": {
      "abstract": [
        {
          "text": "The key name of the Kerberos session key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionKeyKeyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/sessionKeyKeyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sessionKeyKeyName"
        }
      ],
      "role": "symbol",
      "title": "sessionKeyKeyName",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationproviderextensionkerberosmapping/sessionkeykeyname"
    },
    "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/ticketKeyPath": {
      "abstract": [
        {
          "text": "The keypath in the response JSON that uses this set of mappings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ticketKeyPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/ticketKeyPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ticketKeyPath"
        }
      ],
      "role": "symbol",
      "title": "ticketKeyPath",
      "type": "topic",
      "url": "/documentation/authenticationservices/asauthorizationproviderextensionkerberosmapping/ticketkeypath"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    },
    "https://datatracker.ietf.org/doc/html/rfc3962": {
      "identifier": "https://datatracker.ietf.org/doc/html/rfc3962",
      "title": "RFC 3962",
      "titleInlineContent": [
        {
          "text": "RFC 3962",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://datatracker.ietf.org/doc/html/rfc3962"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/clientNameKeyName",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/messageBufferKeyName",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/realmKeyName",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/serviceNameKeyName",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/sessionKeyKeyName",
        "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/ticketKeyPath"
      ],
      "title": "Getting the properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "encryptionKeyTypeKeyName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "encryptionKeyTypeKeyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/clientNameKeyName",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/messageBufferKeyName",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/realmKeyName",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/serviceNameKeyName",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/sessionKeyKeyName",
                "doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASAuthorizationProviderExtensionKerberosMapping/ticketKeyPath"
              ],
              "title": "Getting the properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "encryptionKeyTypeKeyName"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionKerberosMapping/title",
          "value": "ASAuthorizationProviderExtensionKerberosMapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionKerberosMapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationProviderExtensionKerberosMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionKerberosMapping/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ASAuthorizationProviderExtensionKerberosMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionKerberosMapping~1ticketKeyPath/title",
          "value": "ticketKeyPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionKerberosMapping~1ticketKeyPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ticketKeyPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionKerberosMapping~1serviceNameKeyName/title",
          "value": "serviceNameKeyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionKerberosMapping~1serviceNameKeyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "serviceNameKeyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionKerberosMapping~1clientNameKeyName/title",
          "value": "clientNameKeyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionKerberosMapping~1clientNameKeyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clientNameKeyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionKerberosMapping~1encryptionKeyTypeKeyName/title",
          "value": "encryptionKeyTypeKeyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionKerberosMapping~1encryptionKeyTypeKeyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "encryptionKeyTypeKeyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionKerberosMapping~1realmKeyName/title",
          "value": "realmKeyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionKerberosMapping~1realmKeyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "realmKeyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionKerberosMapping~1messageBufferKeyName/title",
          "value": "messageBufferKeyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionKerberosMapping~1messageBufferKeyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "messageBufferKeyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionKerberosMapping~1sessionKeyKeyName/title",
          "value": "sessionKeyKeyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASAuthorizationProviderExtensionKerberosMapping~1sessionKeyKeyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sessionKeyKeyName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/authenticationservices/asauthorizationproviderextensionkerberosmapping/encryptionkeytypekeyname"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/authenticationservices/asauthorizationproviderextensionkerberosmapping/encryptionkeytypekeyname"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
