{
  "abstract": [
    {
      "text": "A set containing only the inward resize direction.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSCursor",
        "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizeDirection",
        "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizeDirection/Set"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizeDirection/Set/inward"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So8NSCursorC6AppKitE20FrameResizeDirectionO3SetV6inwardAGvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "inward"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSCursor",
        "text": "NSCursor"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So8NSCursorC6AppKitE20FrameResizeDirectionO",
        "text": "FrameResizeDirection"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:So8NSCursorC6AppKitE20FrameResizeDirectionO3SetV",
        "text": "Set"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "inward"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "inward"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSCursor",
              "text": "NSCursor"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizeDirection",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So8NSCursorC6AppKitE20FrameResizeDirectionO",
              "text": "FrameResizeDirection"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizeDirection/Set",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:So8NSCursorC6AppKitE20FrameResizeDirectionO3SetV",
              "text": "Set"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor": {
      "abstract": [
        {
          "text": "A pointer (also called a cursor).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCursor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCursor"
        }
      ],
      "role": "symbol",
      "title": "NSCursor",
      "type": "topic",
      "url": "/documentation/appkit/nscursor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizeDirection": {
      "abstract": [
        {
          "text": "The direction in which a rectangular frame can be resized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FrameResizeDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizeDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FrameResizeDirection"
        }
      ],
      "role": "symbol",
      "title": "NSCursor.FrameResizeDirection",
      "type": "topic",
      "url": "/documentation/appkit/nscursor/frameresizedirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizeDirection/Set": {
      "abstract": [
        {
          "text": "An efficient set of frame resize directions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Set"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizeDirection/Set",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Set"
        }
      ],
      "role": "symbol",
      "title": "NSCursor.FrameResizeDirection.Set",
      "type": "topic",
      "url": "/documentation/appkit/nscursor/frameresizedirection/set"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizeDirection/Set/inward": {
      "abstract": [
        {
          "text": "A set containing only the inward resize direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inward"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCursor",
          "text": "NSCursor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8NSCursorC6AppKitE20FrameResizeDirectionO",
          "text": "FrameResizeDirection"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8NSCursorC6AppKitE20FrameResizeDirectionO3SetV",
          "text": "Set"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizeDirection/Set/inward",
      "kind": "symbol",
      "role": "symbol",
      "title": "inward",
      "type": "topic",
      "url": "/documentation/appkit/nscursor/frameresizedirection/set/inward"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/title",
          "value": "NSCursor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscursor/frameresizedirection/set/inward"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
