{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/carplay-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "CarPlay Enumerations"
  },
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPInstrumentClusterSetting"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPInstrumentClusterSetting"
        }
      ],
      "role": "symbol",
      "title": "CPInstrumentClusterSetting",
      "type": "topic",
      "url": "/documentation/carplay/cpinstrumentclustersetting"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPJunctionType": {
      "abstract": [
        {
          "text": "Values that represent types of roadway junctions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPJunctionType"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPJunctionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPJunctionType"
        }
      ],
      "role": "symbol",
      "title": "CPJunctionType",
      "type": "topic",
      "url": "/documentation/carplay/cpjunctiontype"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPLaneStatus": {
      "abstract": [
        {
          "text": "Values that describe the status or preferability of a lane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPLaneStatus"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPLaneStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPLaneStatus"
        }
      ],
      "role": "symbol",
      "title": "CPLaneStatus",
      "type": "topic",
      "url": "/documentation/carplay/cplanestatus"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverState": {
      "abstract": [
        {
          "text": "Values that describe the state of a maneuver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPManeuverState"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverState"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverState",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuverstate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType": {
      "abstract": [
        {
          "text": "Values that describe types of navigation maneuvers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPManeuverType"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverType"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverType",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuvertype"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTrafficSide": {
      "abstract": [
        {
          "text": "Values that represent which side of the road the traffic drives on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTrafficSide"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTrafficSide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTrafficSide"
        }
      ],
      "role": "symbol",
      "title": "CPTrafficSide",
      "type": "topic",
      "url": "/documentation/carplay/cptrafficside"
    },
    "doc://com.apple.carplay/documentation/CarPlay/carplay-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/carplay-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "CarPlay Constants",
      "type": "topic",
      "url": "/documentation/carplay/carplay-constants"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/carplay-constants"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting",
        "doc://com.apple.carplay/documentation/CarPlay/CPJunctionType",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverState",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType",
        "doc://com.apple.carplay/documentation/CarPlay/CPLaneStatus",
        "doc://com.apple.carplay/documentation/CarPlay/CPTrafficSide"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting",
                "doc://com.apple.carplay/documentation/CarPlay/CPJunctionType",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverState",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType",
                "doc://com.apple.carplay/documentation/CarPlay/CPLaneStatus",
                "doc://com.apple.carplay/documentation/CarPlay/CPTrafficSide"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/carplay-constants"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType/title",
          "value": "CPManeuverType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPJunctionType/title",
          "value": "CPJunctionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPJunctionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPJunctionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPJunctionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPJunctionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPLaneStatus/title",
          "value": "CPLaneStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPLaneStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPLaneStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPLaneStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPLaneStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTrafficSide/title",
          "value": "CPTrafficSide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTrafficSide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTrafficSide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTrafficSide/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTrafficSide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverState/title",
          "value": "CPManeuverState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting/title",
          "value": "CPInstrumentClusterSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterSetting"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/carplay-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/carplay-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
