{
  "abstract": [
    {
      "text": "The interface for handling CarPlay life-cycle events.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPApplicationDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CPApplicationDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CPApplicationDelegate"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CPApplicationDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.0",
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "CPApplicationDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CPApplicationDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIApplicationDelegate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)UIApplicationDelegate",
              "text": "UIApplicationDelegate"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You must implement ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPApplicationDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on the same object that serves as the delegate to your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPApplicationDelegate": {
      "abstract": [
        {
          "text": "The interface for handling CarPlay life-cycle events.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPApplicationDelegate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPApplicationDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPApplicationDelegate"
        }
      ],
      "role": "symbol",
      "title": "CPApplicationDelegate",
      "type": "topic",
      "url": "/documentation/carplay/cpapplicationdelegate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPApplicationDelegate/application(_:didConnectCarInterfaceController:to:)": {
      "abstract": [
        {
          "text": "Tells the app delegate that the app connected to the CarPlay interface.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didConnectCarInterfaceController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPInterfaceController",
          "text": "CPInterfaceController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPWindow",
          "text": "CPWindow"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPApplicationDelegate/application(_:didConnectCarInterfaceController:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "application:didConnectCarInterfaceController:toWindow:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "application(_:didConnectCarInterfaceController:to:)",
      "type": "topic",
      "url": "/documentation/carplay/cpapplicationdelegate/application(_:didconnectcarinterfacecontroller:to:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPApplicationDelegate/application(_:didDisconnectCarInterfaceController:from:)": {
      "abstract": [
        {
          "text": "Tells the app delegate that the app disconnected from the CarPlay interface.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didDisconnectCarInterfaceController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPInterfaceController",
          "text": "CPInterfaceController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPWindow",
          "text": "CPWindow"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPApplicationDelegate/application(_:didDisconnectCarInterfaceController:from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "application:didDisconnectCarInterfaceController:fromWindow:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "application(_:didDisconnectCarInterfaceController:from:)",
      "type": "topic",
      "url": "/documentation/carplay/cpapplicationdelegate/application(_:diddisconnectcarinterfacecontroller:from:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPApplicationDelegate/application(_:didSelect:)-478jb": {
      "abstract": [
        {
          "text": "Tells the app delegate that the user selected an action from a navigation alert.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNavigationAlert",
          "text": "CPNavigationAlert"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPApplicationDelegate/application(_:didSelect:)-478jb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "application:didSelectNavigationAlert:"
        }
      ],
      "role": "symbol",
      "title": "application(_:didSelect:)",
      "type": "topic",
      "url": "/documentation/carplay/cpapplicationdelegate/application(_:didselect:)-478jb"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPApplicationDelegate/application(_:didSelect:)-6ybyy": {
      "abstract": [
        {
          "text": "Tells the app delegate that the user selected a maneuver.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPManeuver",
          "text": "CPManeuver"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPApplicationDelegate/application(_:didSelect:)-6ybyy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "application:didSelectManeuver:"
        }
      ],
      "role": "symbol",
      "title": "application(_:didSelect:)",
      "type": "topic",
      "url": "/documentation/carplay/cpapplicationdelegate/application(_:didselect:)-6ybyy"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIApplicationDelegate": {
      "abstract": [
        {
          "text": "A set of methods to manage shared behaviors for your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIApplicationDelegate"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIApplicationDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIApplicationDelegate",
      "type": "topic",
      "url": "/documentation/UIKit/UIApplicationDelegate"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIApplicationDelegate"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Connecting-to-the-CarPlay-Interface",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPApplicationDelegate/application(_:didConnectCarInterfaceController:to:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPApplicationDelegate/application(_:didDisconnectCarInterfaceController:from:)"
      ],
      "title": "Connecting to the CarPlay Interface"
    },
    {
      "anchor": "Receiving-the-Selected-Maneuver",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPApplicationDelegate/application(_:didSelect:)-6ybyy"
      ],
      "title": "Receiving the Selected Maneuver"
    },
    {
      "anchor": "Handling-Navigation-Alert-Actions",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPApplicationDelegate/application(_:didSelect:)-478jb"
      ],
      "title": "Handling Navigation Alert Actions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.0",
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CPApplicationDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPApplicationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPApplicationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Connecting-to-the-CarPlay-Interface",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPApplicationDelegate/application(_:didConnectCarInterfaceController:to:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPApplicationDelegate/application(_:didDisconnectCarInterfaceController:from:)"
              ],
              "title": "Connecting to the CarPlay Interface"
            },
            {
              "anchor": "Receiving-the-Selected-Maneuver",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPApplicationDelegate/application(_:didSelect:)-6ybyy"
              ],
              "title": "Receiving the Selected Maneuver"
            },
            {
              "anchor": "Handling-Navigation-Alert-Actions",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPApplicationDelegate/application(_:didSelect:)-478jb"
              ],
              "title": "Handling Navigation Alert Actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)UIApplicationDelegate"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CPApplicationDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIApplicationDelegate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)UIApplicationDelegate",
                    "text": "UIApplicationDelegate"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPApplicationDelegate/title",
          "value": "CPApplicationDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPApplicationDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPApplicationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPApplicationDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPApplicationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPApplicationDelegate~1application(_:didConnectCarInterfaceController:to:)/title",
          "value": "application:didConnectCarInterfaceController:toWindow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPApplicationDelegate~1application(_:didConnectCarInterfaceController:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "application:didConnectCarInterfaceController:toWindow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIApplicationDelegate/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIApplicationDelegate"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPApplicationDelegate~1application(_:didSelect:)-6ybyy/title",
          "value": "application:didSelectManeuver:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPApplicationDelegate~1application(_:didSelect:)-6ybyy/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "application:didSelectManeuver:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPApplicationDelegate~1application(_:didDisconnectCarInterfaceController:from:)/title",
          "value": "application:didDisconnectCarInterfaceController:fromWindow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPApplicationDelegate~1application(_:didDisconnectCarInterfaceController:from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "application:didDisconnectCarInterfaceController:fromWindow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPApplicationDelegate~1application(_:didSelect:)-478jb/title",
          "value": "application:didSelectNavigationAlert:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPApplicationDelegate~1application(_:didSelect:)-478jb/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "application:didSelectNavigationAlert:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpapplicationdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpapplicationdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
