{
  "abstract": [
    {
      "text": "A button for placement in a navigation bar.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPBarButton"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CPBarButton",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CPBarButton"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CPBarButton"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CPBarButton"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CPBarButton"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPBarButton": {
      "abstract": [
        {
          "text": "A button for placement in a navigation bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPBarButton"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPBarButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPBarButton"
        }
      ],
      "role": "symbol",
      "title": "CPBarButton",
      "type": "topic",
      "url": "/documentation/carplay/cpbarbutton"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/Type": {
      "abstract": [
        {
          "text": "Types of bar buttons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Type"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/Type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Type"
        }
      ],
      "role": "symbol",
      "title": "CPBarButton.Type",
      "type": "topic",
      "url": "/documentation/carplay/cpbarbutton/type"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/buttonStyle": {
      "abstract": [
        {
          "text": "The style to use when displaying the button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPBarButtonStyle",
          "text": "CPBarButtonStyle"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/buttonStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttonStyle"
        }
      ],
      "role": "symbol",
      "title": "buttonStyle",
      "type": "topic",
      "url": "/documentation/carplay/cpbarbutton/buttonstyle"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/buttonType": {
      "abstract": [
        {
          "text": "The display type for the bar button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPBarButton",
          "text": "CPBarButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPBarButtonType",
          "text": "Type"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/buttonType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttonType"
        }
      ],
      "role": "symbol",
      "title": "buttonType",
      "type": "topic",
      "url": "/documentation/carplay/cpbarbutton/buttontype"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/image": {
      "abstract": [
        {
          "text": "The image displayed on the bar button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/image",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "image"
        }
      ],
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/carplay/cpbarbutton/image"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/init(coder:)": {
      "abstract": [
        {
          "text": "Creates a \u0013button initialized  from data in the specified coder object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/init(coder:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/carplay/cpbarbutton/init(coder:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/init(image:handler:)": {
      "abstract": [
        {
          "text": "Creates a bar button that displays an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CPBarButtonHandler",
          "text": "CPBarButtonHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/init(image:handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithImage:handler:"
        }
      ],
      "role": "symbol",
      "title": "init(image:handler:)",
      "type": "topic",
      "url": "/documentation/carplay/cpbarbutton/init(image:handler:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/init(title:handler:)": {
      "abstract": [
        {
          "text": "Creates a bar button that displays a text label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CPBarButtonHandler",
          "text": "CPBarButtonHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/init(title:handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTitle:handler:"
        }
      ],
      "role": "symbol",
      "title": "init(title:handler:)",
      "type": "topic",
      "url": "/documentation/carplay/cpbarbutton/init(title:handler:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/init(type:handler:)": {
      "abstract": [
        {
          "text": "Creates a bar button with a type and handler.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPBarButton",
          "text": "CPBarButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPBarButtonType",
          "text": "Type"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CPBarButtonHandler",
          "text": "CPBarButtonHandler"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/init(type:handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithType:handler:"
        }
      ],
      "role": "symbol",
      "title": "init(type:handler:)",
      "type": "topic",
      "url": "/documentation/carplay/cpbarbutton/init(type:handler:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/isEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that enables and disables the bar button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/isEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enabled"
        }
      ],
      "role": "symbol",
      "title": "isEnabled",
      "type": "topic",
      "url": "/documentation/carplay/cpbarbutton/isenabled"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/title": {
      "abstract": [
        {
          "text": "The title displayed on the bar button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/carplay/cpbarbutton/title"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonHandler": {
      "abstract": [
        {
          "text": "A block that CarPlay calls when the user taps a bar button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPBarButtonHandler"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPBarButtonHandler"
        }
      ],
      "role": "symbol",
      "title": "CPBarButtonHandler",
      "type": "topic",
      "url": "/documentation/carplay/cpbarbuttonhandler"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonProviding/backButton": {
      "abstract": [
        {
          "text": "A button to display as the Back button on the navigation bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPBarButton",
          "text": "CPBarButton"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonProviding/backButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backButton"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "backButton",
      "type": "topic",
      "url": "/documentation/carplay/cpbarbuttonproviding/backbutton"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonProviding/leadingNavigationBarButtons": {
      "abstract": [
        {
          "text": "An array of bar buttons to display on the leading side of the navigation bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leadingNavigationBarButtons"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPBarButton",
          "text": "CPBarButton"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonProviding/leadingNavigationBarButtons",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leadingNavigationBarButtons"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "leadingNavigationBarButtons",
      "type": "topic",
      "url": "/documentation/carplay/cpbarbuttonproviding/leadingnavigationbarbuttons"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonProviding/trailingNavigationBarButtons": {
      "abstract": [
        {
          "text": "An array of bar buttons to display on the trailing side of the navigation bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailingNavigationBarButtons"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPBarButton",
          "text": "CPBarButton"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonProviding/trailingNavigationBarButtons",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trailingNavigationBarButtons"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "trailingNavigationBarButtons",
      "type": "topic",
      "url": "/documentation/carplay/cpbarbuttonproviding/trailingnavigationbarbuttons"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonStyle": {
      "abstract": [
        {
          "text": "The display style of a bar button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPBarButtonStyle"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPBarButtonStyle"
        }
      ],
      "role": "symbol",
      "title": "CPBarButtonStyle",
      "type": "topic",
      "url": "/documentation/carplay/cpbarbuttonstyle"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMessageComposeBarButton": {
      "abstract": [
        {
          "text": "A button that activates Siri and initiates the compose message flow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPMessageComposeBarButton"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMessageComposeBarButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPMessageComposeBarButton"
        }
      ],
      "role": "symbol",
      "title": "CPMessageComposeBarButton",
      "type": "topic",
      "url": "/documentation/carplay/cpmessagecomposebarbutton"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPMessageComposeBarButton"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Providing-Navigation-Bar-Buttons",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonProviding/backButton",
        "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonProviding/leadingNavigationBarButtons",
        "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonProviding/trailingNavigationBarButtons",
        "doc://com.apple.carplay/documentation/CarPlay/CPMessageComposeBarButton"
      ],
      "title": "Providing Navigation Bar Buttons"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-CarPlay-Bar-Button",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/init(coder:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/init(type:handler:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/init(image:handler:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/init(title:handler:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/Type",
        "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonHandler"
      ],
      "title": "Creating a CarPlay Bar Button"
    },
    {
      "anchor": "Configuring-the-Button",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/isEnabled",
        "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/image",
        "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/title"
      ],
      "title": "Configuring the Button"
    },
    {
      "anchor": "Getting-the-Button-Style",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/buttonType",
        "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/buttonStyle",
        "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonStyle"
      ],
      "title": "Getting the Button Style"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CPBarButton"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPBarButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPBarButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-CarPlay-Bar-Button",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/init(type:handler:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/init(image:handler:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/init(title:handler:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/Type",
                "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonHandler"
              ],
              "title": "Creating a CarPlay Bar Button"
            },
            {
              "anchor": "Configuring-the-Button",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/isEnabled",
                "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/image",
                "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/title"
              ],
              "title": "Configuring the Button"
            },
            {
              "anchor": "Getting-the-Button-Style",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/buttonType",
                "doc://com.apple.carplay/documentation/CarPlay/CPBarButton/buttonStyle",
                "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonStyle"
              ],
              "title": "Getting the Button Style"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPMessageComposeBarButton"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Providing-Navigation-Bar-Buttons",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonProviding/backButton",
                "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonProviding/leadingNavigationBarButtons",
                "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonProviding/trailingNavigationBarButtons",
                "doc://com.apple.carplay/documentation/CarPlay/CPMessageComposeBarButton"
              ],
              "title": "Providing Navigation Bar Buttons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CPBarButton"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton~1init(image:handler:)/title",
          "value": "initWithImage:handler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton~1init(image:handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithImage:handler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButtonProviding~1leadingNavigationBarButtons/title",
          "value": "leadingNavigationBarButtons"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButtonProviding~1leadingNavigationBarButtons/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leadingNavigationBarButtons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton/title",
          "value": "CPBarButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPBarButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPBarButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton~1buttonType/title",
          "value": "buttonType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton~1buttonType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "buttonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageComposeBarButton/title",
          "value": "CPMessageComposeBarButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageComposeBarButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMessageComposeBarButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageComposeBarButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMessageComposeBarButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton~1Type/title",
          "value": "CPBarButtonType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton~1Type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPBarButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton~1Type/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPBarButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton~1image/title",
          "value": "image"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton~1image/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "image"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton~1init(type:handler:)/title",
          "value": "initWithType:handler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton~1init(type:handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithType:handler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButtonStyle/title",
          "value": "CPBarButtonStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButtonStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPBarButtonStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButtonStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPBarButtonStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButtonProviding~1backButton/title",
          "value": "backButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButtonProviding~1backButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton~1buttonStyle/title",
          "value": "buttonStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton~1buttonStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "buttonStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton~1init(title:handler:)/title",
          "value": "initWithTitle:handler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton~1init(title:handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTitle:handler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButtonHandler/title",
          "value": "CPBarButtonHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButtonHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPBarButtonHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButtonHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPBarButtonHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton~1isEnabled/title",
          "value": "enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButton~1isEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButtonProviding~1trailingNavigationBarButtons/title",
          "value": "trailingNavigationBarButtons"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButtonProviding~1trailingNavigationBarButtons/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trailingNavigationBarButtons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpbarbutton"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpbarbutton"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
