{
  "abstract": [
    {
      "text": "A template that provides information for a point of interest, food order, parking location, or charging location.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CPInformationTemplate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CPInformationTemplate"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CPInformationTemplate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CPInformationTemplate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CPInformationTemplate"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An information template displays a list of items, and up to three actions the user can perform.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You use an information template to display informative, actionable content to the user. For example, you might display a summary of the user’s food order, and provide actions to place or cancel the order.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When creating an information template, you populate the list with an array of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInformationItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects, and provide any contextual actions as an array of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTextButton",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects. The template then arranges the list’s items using your choice of layout — see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplateLayout",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To display an information template, call your interface controller’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInterfaceController/pushTemplate(_:animated:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to push it onto the navigation hierarchy, or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInterfaceController/presentTemplate(_:animated:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to present it modally.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You can’t use ",
                  "type": "text"
                },
                {
                  "code": "CPInformationTemplate",
                  "type": "codeVoice"
                },
                {
                  "text": " in apps with the audio entitlement.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonProviding": {
      "abstract": [
        {
          "text": "The methods that templates use to provide buttons for the navigation bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPBarButtonProviding"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPBarButtonProviding"
        }
      ],
      "role": "symbol",
      "title": "CPBarButtonProviding",
      "type": "topic",
      "url": "/documentation/carplay/cpbarbuttonproviding"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInformationItem": {
      "abstract": [
        {
          "text": "A data object that provides content for an information template.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPInformationItem"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInformationItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPInformationItem"
        }
      ],
      "role": "symbol",
      "title": "CPInformationItem",
      "type": "topic",
      "url": "/documentation/carplay/cpinformationitem"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInformationRatingItem": {
      "abstract": [
        {
          "text": "A data object that provides rated content for an information template.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPInformationRatingItem"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInformationRatingItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPInformationRatingItem"
        }
      ],
      "role": "symbol",
      "title": "CPInformationRatingItem",
      "type": "topic",
      "url": "/documentation/carplay/cpinformationratingitem"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate": {
      "abstract": [
        {
          "text": "A template that provides information for a point of interest, food order, parking location, or charging location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPInformationTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPInformationTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPInformationTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cpinformationtemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate/actions": {
      "abstract": [
        {
          "text": "The actions that the template displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTextButton",
          "text": "CPTextButton"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate/actions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "actions"
        }
      ],
      "role": "symbol",
      "title": "actions",
      "type": "topic",
      "url": "/documentation/carplay/cpinformationtemplate/actions"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate/init(title:layout:items:actions:)": {
      "abstract": [
        {
          "text": "Creates an information template that displays the provided items using the chosen layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "layout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPInformationTemplateLayout",
          "text": "CPInformationTemplateLayout"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "items"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPInformationItem",
          "text": "CPInformationItem"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "actions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTextButton",
          "text": "CPTextButton"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate/init(title:layout:items:actions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTitle:layout:items:actions:"
        }
      ],
      "role": "symbol",
      "title": "init(title:layout:items:actions:)",
      "type": "topic",
      "url": "/documentation/carplay/cpinformationtemplate/init(title:layout:items:actions:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate/items": {
      "abstract": [
        {
          "text": "The items that the template displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "items"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPInformationItem",
          "text": "CPInformationItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate/items",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "items"
        }
      ],
      "role": "symbol",
      "title": "items",
      "type": "topic",
      "url": "/documentation/carplay/cpinformationtemplate/items"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate/layout": {
      "abstract": [
        {
          "text": "The layout that the template uses to arrange its items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPInformationTemplateLayout",
          "text": "CPInformationTemplateLayout"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate/layout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layout"
        }
      ],
      "role": "symbol",
      "title": "layout",
      "type": "topic",
      "url": "/documentation/carplay/cpinformationtemplate/layout"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate/title": {
      "abstract": [
        {
          "text": "The template’s title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/carplay/cpinformationtemplate/title"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplateLayout": {
      "abstract": [
        {
          "text": "The layout that an information template uses to arrange its items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPInformationTemplateLayout"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplateLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPInformationTemplateLayout"
        }
      ],
      "role": "symbol",
      "title": "CPInformationTemplateLayout",
      "type": "topic",
      "url": "/documentation/carplay/cpinformationtemplatelayout"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInterfaceController/presentTemplate(_:animated:completion:)": {
      "abstract": [
        {
          "text": "Presents a template modally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTemplate",
          "text": "CPTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInterfaceController/presentTemplate(_:animated:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentTemplate:animated:completion:"
        }
      ],
      "role": "symbol",
      "title": "presentTemplate(_:animated:completion:)",
      "type": "topic",
      "url": "/documentation/carplay/cpinterfacecontroller/presenttemplate(_:animated:completion:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInterfaceController/pushTemplate(_:animated:completion:)": {
      "abstract": [
        {
          "text": "Adds the specified template to the navigation hierarchy and displays it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pushTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTemplate",
          "text": "CPTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInterfaceController/pushTemplate(_:animated:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pushTemplate:animated:completion:"
        }
      ],
      "role": "symbol",
      "title": "pushTemplate(_:animated:completion:)",
      "type": "topic",
      "url": "/documentation/carplay/cpinterfacecontroller/pushtemplate(_:animated:completion:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterestTemplate": {
      "abstract": [
        {
          "text": "A template that displays a map with selectable points of interest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPPointOfInterestTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterestTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPPointOfInterestTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPPointOfInterestTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cppointofinteresttemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplate": {
      "abstract": [
        {
          "text": "An abstract base class for interface templates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cptemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTextButton": {
      "abstract": [
        {
          "text": "A button that displays a stylized title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTextButton"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTextButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTextButton"
        }
      ],
      "role": "symbol",
      "title": "CPTextButton",
      "type": "topic",
      "url": "/documentation/carplay/cptextbutton"
    },
    "doc://com.apple.carplay/documentation/CarPlay/integrating-carplay-with-your-quick-ordering-app": {
      "abstract": [
        {
          "text": "Configure your food-ordering app to work with CarPlay.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/integrating-carplay-with-your-quick-ordering-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Integrating CarPlay with your quick-ordering app",
      "type": "topic",
      "url": "/documentation/carplay/integrating-carplay-with-your-quick-ordering-app"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPTemplate"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonProviding",
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Location-and-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterestTemplate",
        "doc://com.apple.carplay/documentation/CarPlay/CPTextButton",
        "doc://com.apple.carplay/documentation/CarPlay/integrating-carplay-with-your-quick-ordering-app"
      ],
      "title": "Location and Information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-Information-Template",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate/init(title:layout:items:actions:)"
      ],
      "title": "Creating an Information Template"
    },
    {
      "anchor": "Accessing-the-Layout",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate/layout",
        "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplateLayout"
      ],
      "title": "Accessing the Layout"
    },
    {
      "anchor": "Managing-the-Title",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate/title"
      ],
      "title": "Managing the Title"
    },
    {
      "anchor": "Managing-the-Items",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate/items",
        "doc://com.apple.carplay/documentation/CarPlay/CPInformationItem",
        "doc://com.apple.carplay/documentation/CarPlay/CPInformationRatingItem"
      ],
      "title": "Managing the Items"
    },
    {
      "anchor": "Managing-the-Actions",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate/actions"
      ],
      "title": "Managing the Actions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CPInformationTemplate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInformationTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInformationTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-an-Information-Template",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate/init(title:layout:items:actions:)"
              ],
              "title": "Creating an Information Template"
            },
            {
              "anchor": "Accessing-the-Layout",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate/layout",
                "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplateLayout"
              ],
              "title": "Accessing the Layout"
            },
            {
              "anchor": "Managing-the-Title",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate/title"
              ],
              "title": "Managing the Title"
            },
            {
              "anchor": "Managing-the-Items",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate/items",
                "doc://com.apple.carplay/documentation/CarPlay/CPInformationItem",
                "doc://com.apple.carplay/documentation/CarPlay/CPInformationRatingItem"
              ],
              "title": "Managing the Items"
            },
            {
              "anchor": "Managing-the-Actions",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate/actions"
              ],
              "title": "Managing the Actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPTemplate"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonProviding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Location-and-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterestTemplate",
                "doc://com.apple.carplay/documentation/CarPlay/CPTextButton",
                "doc://com.apple.carplay/documentation/CarPlay/integrating-carplay-with-your-quick-ordering-app"
              ],
              "title": "Location and Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CPInformationTemplate"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CPTemplate",
                    "text": "CPTemplate"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationRatingItem/title",
          "value": "CPInformationRatingItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationRatingItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInformationRatingItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationRatingItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInformationRatingItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInterfaceController~1presentTemplate(_:animated:completion:)/title",
          "value": "presentTemplate:animated:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInterfaceController~1presentTemplate(_:animated:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentTemplate:animated:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate/title",
          "value": "CPTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationTemplate~1layout/title",
          "value": "layout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationTemplate~1layout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "layout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInterfaceController~1pushTemplate(_:animated:completion:)/title",
          "value": "pushTemplate:animated:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInterfaceController~1pushTemplate(_:animated:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pushTemplate:animated:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationItem/title",
          "value": "CPInformationItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInformationItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInformationItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTextButton/title",
          "value": "CPTextButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTextButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTextButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTextButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTextButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationTemplate~1actions/title",
          "value": "actions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationTemplate~1actions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationTemplate~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationTemplate~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationTemplateLayout/title",
          "value": "CPInformationTemplateLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationTemplateLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInformationTemplateLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationTemplateLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInformationTemplateLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationTemplate/title",
          "value": "CPInformationTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInformationTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInformationTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButtonProviding/title",
          "value": "CPBarButtonProviding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButtonProviding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPBarButtonProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButtonProviding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPBarButtonProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationTemplate~1items/title",
          "value": "items"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationTemplate~1items/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "items"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPPointOfInterestTemplate/title",
          "value": "CPPointOfInterestTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPPointOfInterestTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPointOfInterestTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPPointOfInterestTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPointOfInterestTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationTemplate~1init(title:layout:items:actions:)/title",
          "value": "initWithTitle:layout:items:actions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationTemplate~1init(title:layout:items:actions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTitle:layout:items:actions:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpinformationtemplate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpinformationtemplate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
