{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CPInstrumentClusterSetting",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CPInstrumentClusterSetting"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CPInstrumentClusterSetting"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CPInstrumentClusterSetting"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterSetting"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPInstrumentClusterSetting"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPInstrumentClusterSetting"
        }
      ],
      "role": "symbol",
      "title": "CPInstrumentClusterSetting",
      "type": "topic",
      "url": "/documentation/carplay/cpinstrumentclustersetting"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/disabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disabled"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/disabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPInstrumentClusterSettingDisabled"
        }
      ],
      "role": "symbol",
      "title": "CPInstrumentClusterSetting.disabled",
      "type": "topic",
      "url": "/documentation/carplay/cpinstrumentclustersetting/disabled"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/enabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enabled"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/enabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPInstrumentClusterSettingEnabled"
        }
      ],
      "role": "symbol",
      "title": "CPInstrumentClusterSetting.enabled",
      "type": "topic",
      "url": "/documentation/carplay/cpinstrumentclustersetting/enabled"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/carplay/cpinstrumentclustersetting/init(rawvalue:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/unspecified": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPInstrumentClusterSettingUnspecified"
        }
      ],
      "role": "symbol",
      "title": "CPInstrumentClusterSetting.unspecified",
      "type": "topic",
      "url": "/documentation/carplay/cpinstrumentclustersetting/unspecified"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/userPreference": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userPreference"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/userPreference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPInstrumentClusterSettingUserPreference"
        }
      ],
      "role": "symbol",
      "title": "CPInstrumentClusterSetting.userPreference",
      "type": "topic",
      "url": "/documentation/carplay/cpinstrumentclustersetting/userpreference"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPJunctionType": {
      "abstract": [
        {
          "text": "Values that represent types of roadway junctions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPJunctionType"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPJunctionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPJunctionType"
        }
      ],
      "role": "symbol",
      "title": "CPJunctionType",
      "type": "topic",
      "url": "/documentation/carplay/cpjunctiontype"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPLaneStatus": {
      "abstract": [
        {
          "text": "Values that describe the status or preferability of a lane.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPLaneStatus"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPLaneStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPLaneStatus"
        }
      ],
      "role": "symbol",
      "title": "CPLaneStatus",
      "type": "topic",
      "url": "/documentation/carplay/cplanestatus"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverState": {
      "abstract": [
        {
          "text": "Values that describe the state of a maneuver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPManeuverState"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverState"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverState",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuverstate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType": {
      "abstract": [
        {
          "text": "Values that describe types of navigation maneuvers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPManeuverType"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverType"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverType",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuvertype"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTrafficSide": {
      "abstract": [
        {
          "text": "Values that represent which side of the road the traffic drives on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTrafficSide"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTrafficSide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTrafficSide"
        }
      ],
      "role": "symbol",
      "title": "CPTrafficSide",
      "type": "topic",
      "url": "/documentation/carplay/cptrafficside"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPJunctionType",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverState",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType",
        "doc://com.apple.carplay/documentation/CarPlay/CPLaneStatus",
        "doc://com.apple.carplay/documentation/CarPlay/CPTrafficSide"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/disabled",
        "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/enabled",
        "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/unspecified",
        "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/userPreference"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.4",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CPInstrumentClusterSetting"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/disabled",
                "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/enabled",
                "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/unspecified",
                "doc://com.apple.carplay/documentation/CarPlay/CPInstrumentClusterSetting/userPreference"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPJunctionType",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverState",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType",
                "doc://com.apple.carplay/documentation/CarPlay/CPLaneStatus",
                "doc://com.apple.carplay/documentation/CarPlay/CPTrafficSide"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CPInstrumentClusterSetting"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType/title",
          "value": "CPManeuverType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting~1disabled/title",
          "value": "CPInstrumentClusterSettingDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting~1disabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterSettingDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting~1unspecified/title",
          "value": "CPInstrumentClusterSettingUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterSettingUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting~1enabled/title",
          "value": "CPInstrumentClusterSettingEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting~1enabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterSettingEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverState/title",
          "value": "CPManeuverState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting/title",
          "value": "CPInstrumentClusterSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPJunctionType/title",
          "value": "CPJunctionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPJunctionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPJunctionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPJunctionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPJunctionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTrafficSide/title",
          "value": "CPTrafficSide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTrafficSide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTrafficSide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTrafficSide/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTrafficSide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPLaneStatus/title",
          "value": "CPLaneStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPLaneStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPLaneStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPLaneStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPLaneStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting~1userPreference/title",
          "value": "CPInstrumentClusterSettingUserPreference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInstrumentClusterSetting~1userPreference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInstrumentClusterSettingUserPreference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpinstrumentclustersetting"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpinstrumentclustersetting"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
