{
  "abstract": [
    {
      "text": "The accessory types that a list item can display.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPListItemAccessoryType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CPListItemAccessoryType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CPListItemAccessoryType"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CPListItemAccessoryType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CPListItemAccessoryType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CPListItemAccessoryType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these constants to set the value of a list item’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItem/accessoryType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. An accessory can provide additional context for a list item’s contents, or help communicate its behavior.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListItem/accessoryImage": {
      "abstract": [
        {
          "text": "The image that the list item displays in its trailing region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItem/accessoryImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessoryImage"
        }
      ],
      "role": "symbol",
      "title": "accessoryImage",
      "type": "topic",
      "url": "/documentation/carplay/cplistitem/accessoryimage"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListItem/accessoryType": {
      "abstract": [
        {
          "text": "The accessory that the list item displays in its trailing region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPListItemAccessoryType",
          "text": "CPListItemAccessoryType"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItem/accessoryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessoryType"
        }
      ],
      "role": "symbol",
      "title": "accessoryType",
      "type": "topic",
      "url": "/documentation/carplay/cplistitem/accessorytype"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListItem/setAccessoryImage(_:)": {
      "abstract": [
        {
          "text": "Updates the list item’s accessory image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAccessoryImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItem/setAccessoryImage(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAccessoryImage:"
        }
      ],
      "role": "symbol",
      "title": "setAccessoryImage(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cplistitem/setaccessoryimage(_:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListItemAccessoryType": {
      "abstract": [
        {
          "text": "The accessory types that a list item can display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPListItemAccessoryType"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItemAccessoryType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPListItemAccessoryType"
        }
      ],
      "role": "symbol",
      "title": "CPListItemAccessoryType",
      "type": "topic",
      "url": "/documentation/carplay/cplistitemaccessorytype"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListItemAccessoryType/cloud": {
      "abstract": [
        {
          "text": "Show a cloud icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloud"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItemAccessoryType/cloud",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPListItemAccessoryTypeCloud"
        }
      ],
      "role": "symbol",
      "title": "CPListItemAccessoryType.cloud",
      "type": "topic",
      "url": "/documentation/carplay/cplistitemaccessorytype/cloud"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListItemAccessoryType/disclosureIndicator": {
      "abstract": [
        {
          "text": "Show a chevron icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disclosureIndicator"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItemAccessoryType/disclosureIndicator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPListItemAccessoryTypeDisclosureIndicator"
        }
      ],
      "role": "symbol",
      "title": "CPListItemAccessoryType.disclosureIndicator",
      "type": "topic",
      "url": "/documentation/carplay/cplistitemaccessorytype/disclosureindicator"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListItemAccessoryType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItemAccessoryType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/carplay/cplistitemaccessorytype/init(rawvalue:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListItemAccessoryType/none": {
      "abstract": [
        {
          "text": "Don’t show an accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItemAccessoryType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPListItemAccessoryTypeNone"
        }
      ],
      "role": "symbol",
      "title": "CPListItemAccessoryType.none",
      "type": "topic",
      "url": "/documentation/carplay/cplistitemaccessorytype/none"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Accessories",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPListItem/accessoryType",
        "doc://com.apple.carplay/documentation/CarPlay/CPListItem/accessoryImage",
        "doc://com.apple.carplay/documentation/CarPlay/CPListItem/setAccessoryImage(_:)"
      ],
      "title": "Managing Accessories"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessory-Types",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPListItemAccessoryType/none",
        "doc://com.apple.carplay/documentation/CarPlay/CPListItemAccessoryType/disclosureIndicator",
        "doc://com.apple.carplay/documentation/CarPlay/CPListItemAccessoryType/cloud"
      ],
      "title": "Accessory Types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPListItemAccessoryType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CPListItemAccessoryType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListItemAccessoryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListItemAccessoryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessory-Types",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPListItemAccessoryType/none",
                "doc://com.apple.carplay/documentation/CarPlay/CPListItemAccessoryType/disclosureIndicator",
                "doc://com.apple.carplay/documentation/CarPlay/CPListItemAccessoryType/cloud"
              ],
              "title": "Accessory Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Accessories",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPListItem/accessoryType",
                "doc://com.apple.carplay/documentation/CarPlay/CPListItem/accessoryImage",
                "doc://com.apple.carplay/documentation/CarPlay/CPListItem/setAccessoryImage(_:)"
              ],
              "title": "Managing Accessories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CPListItemAccessoryType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItemAccessoryType/title",
          "value": "CPListItemAccessoryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItemAccessoryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListItemAccessoryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItemAccessoryType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListItemAccessoryType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItemAccessoryType~1cloud/title",
          "value": "CPListItemAccessoryTypeCloud"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItemAccessoryType~1cloud/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListItemAccessoryTypeCloud"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItemAccessoryType~1disclosureIndicator/title",
          "value": "CPListItemAccessoryTypeDisclosureIndicator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItemAccessoryType~1disclosureIndicator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListItemAccessoryTypeDisclosureIndicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem~1setAccessoryImage(_:)/title",
          "value": "setAccessoryImage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem~1setAccessoryImage(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setAccessoryImage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItemAccessoryType~1none/title",
          "value": "CPListItemAccessoryTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItemAccessoryType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListItemAccessoryTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem~1accessoryImage/title",
          "value": "accessoryImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem~1accessoryImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accessoryImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem~1accessoryType/title",
          "value": "accessoryType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem~1accessoryType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accessoryType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cplistitemaccessorytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cplistitemaccessorytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
