{
  "abstract": [
    {
      "text": "An object that describes a single navigation instruction.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CPManeuver",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CPManeuver"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CPManeuver"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CPManeuver"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CPManeuver"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You use maneuvers to provide turn-by-turn guidance in navigation apps. Each maneuver represents a single navigation instruction and can include a symbol, an instruction, and estimates for remaining time and distance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You supply an instruction as an array of variants, each with a different length. CarPlay chooses the longest variant that best fits the available space on the screen. You can optionally provide attributed variants that embed images using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/NSTextAttachment",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/attributedInstructionVariants",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In addition to the route guidance panel, you can show maneuvers on the CarPlay dashboard or in notification banners. Use the relevant properties to provide context-specific instructions and images.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver": {
      "abstract": [
        {
          "text": "An object that describes a single navigation instruction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPManeuver"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuver"
        }
      ],
      "role": "symbol",
      "title": "CPManeuver",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/attributedInstructionVariants": {
      "abstract": [
        {
          "text": "An array of attributed instruction variants for the maneuver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedInstructionVariants"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/attributedInstructionVariants",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributedInstructionVariants"
        }
      ],
      "role": "symbol",
      "title": "attributedInstructionVariants",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/attributedinstructionvariants"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/cardBackgroundColor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cardBackgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/cardBackgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cardBackgroundColor"
        }
      ],
      "role": "symbol",
      "title": "cardBackgroundColor",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/cardbackgroundcolor"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/dashboardAttributedInstructionVariants": {
      "abstract": [
        {
          "text": "An array of attributed instruction variants for the CarPlay dashboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dashboardAttributedInstructionVariants"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/dashboardAttributedInstructionVariants",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dashboardAttributedInstructionVariants"
        }
      ],
      "role": "symbol",
      "title": "dashboardAttributedInstructionVariants",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/dashboardattributedinstructionvariants"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/dashboardInstructionVariants": {
      "abstract": [
        {
          "text": "An array of instruction variants for the CarPlay dashboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dashboardInstructionVariants"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/dashboardInstructionVariants",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dashboardInstructionVariants"
        }
      ],
      "role": "symbol",
      "title": "dashboardInstructionVariants",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/dashboardinstructionvariants"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/dashboardJunctionImage": {
      "abstract": [
        {
          "text": "An image for the CarPlay dashboard that represents an upcoming junction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dashboardJunctionImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/dashboardJunctionImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dashboardJunctionImage"
        }
      ],
      "role": "symbol",
      "title": "dashboardJunctionImage",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/dashboardjunctionimage"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/dashboardSymbolImage": {
      "abstract": [
        {
          "text": "An image for the CarPlay dashboard that represents the maneuver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dashboardSymbolImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/dashboardSymbolImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dashboardSymbolImage"
        }
      ],
      "role": "symbol",
      "title": "dashboardSymbolImage",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/dashboardsymbolimage"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/highwayExitLabel": {
      "abstract": [
        {
          "text": "A string that describes a highway exit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highwayExitLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/highwayExitLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "highwayExitLabel"
        }
      ],
      "role": "symbol",
      "title": "highwayExitLabel",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/highwayexitlabel"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/initialTravelEstimates": {
      "abstract": [
        {
          "text": "An object that describes the distance and time remaining before the maneuver completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initialTravelEstimates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTravelEstimates",
          "text": "CPTravelEstimates"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/initialTravelEstimates",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initialTravelEstimates"
        }
      ],
      "role": "symbol",
      "title": "initialTravelEstimates",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/initialtravelestimates"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/instructionVariants": {
      "abstract": [
        {
          "text": "An array of instruction variants for the maneuver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instructionVariants"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/instructionVariants",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "instructionVariants"
        }
      ],
      "role": "symbol",
      "title": "instructionVariants",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/instructionvariants"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/junctionElementAngles": {
      "abstract": [
        {
          "text": "A set of angles for the rest of the roads of this junction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "junctionElementAngles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitAngle",
          "text": "UnitAngle"
        },
        {
          "kind": "text",
          "text": ">>?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/junctionElementAngles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "junctionElementAngles"
        }
      ],
      "role": "symbol",
      "title": "junctionElementAngles",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/junctionelementangles"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/junctionExitAngle": {
      "abstract": [
        {
          "text": "The angle of the exit road of this junction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "junctionExitAngle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation11MeasurementV",
          "text": "Measurement"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUnitAngle",
          "text": "UnitAngle"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/junctionExitAngle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "junctionExitAngle"
        }
      ],
      "role": "symbol",
      "title": "junctionExitAngle",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/junctionexitangle"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/junctionImage": {
      "abstract": [
        {
          "text": "An image that represents an upcoming junction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "junctionImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/junctionImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "junctionImage"
        }
      ],
      "role": "symbol",
      "title": "junctionImage",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/junctionimage"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/junctionType": {
      "abstract": [
        {
          "text": "A value that represents the type of junction associated with this maneuver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "junctionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPJunctionType",
          "text": "CPJunctionType"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/junctionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "junctionType"
        }
      ],
      "role": "symbol",
      "title": "junctionType",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/junctiontype"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/linkedLaneGuidance": {
      "abstract": [
        {
          "text": "A value that represents lane guidance associated with this maneuver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linkedLaneGuidance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPLaneGuidance",
          "text": "CPLaneGuidance"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/linkedLaneGuidance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "linkedLaneGuidance"
        }
      ],
      "role": "symbol",
      "title": "linkedLaneGuidance",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/linkedlaneguidance"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/maneuverType": {
      "abstract": [
        {
          "text": "A value that represents the type of maneuver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maneuverType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPManeuverType",
          "text": "CPManeuverType"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/maneuverType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maneuverType"
        }
      ],
      "role": "symbol",
      "title": "maneuverType",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/maneuvertype"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/notificationAttributedInstructionVariants": {
      "abstract": [
        {
          "text": "An array of attributed instruction variants for notification banners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationAttributedInstructionVariants"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/notificationAttributedInstructionVariants",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notificationAttributedInstructionVariants"
        }
      ],
      "role": "symbol",
      "title": "notificationAttributedInstructionVariants",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/notificationattributedinstructionvariants"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/notificationInstructionVariants": {
      "abstract": [
        {
          "text": "An array of instruction variants for notification banners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationInstructionVariants"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/notificationInstructionVariants",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notificationInstructionVariants"
        }
      ],
      "role": "symbol",
      "title": "notificationInstructionVariants",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/notificationinstructionvariants"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/notificationSymbolImage": {
      "abstract": [
        {
          "text": "An image for notification banners that represents the maneuver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationSymbolImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/notificationSymbolImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notificationSymbolImage"
        }
      ],
      "role": "symbol",
      "title": "notificationSymbolImage",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/notificationsymbolimage"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/roadFollowingManeuverVariants": {
      "abstract": [
        {
          "text": "An array of strings that represent the names of the road following this maneuver, arranged from most to least preferred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "roadFollowingManeuverVariants"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/roadFollowingManeuverVariants",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "roadFollowingManeuverVariants"
        }
      ],
      "role": "symbol",
      "title": "roadFollowingManeuverVariants",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/roadfollowingmaneuvervariants"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/symbolImage": {
      "abstract": [
        {
          "text": "An image that represents the maneuver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "symbolImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/symbolImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "symbolImage"
        }
      ],
      "role": "symbol",
      "title": "symbolImage",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/symbolimage"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/symbolSet": {
      "abstract": [
        {
          "text": "An image set that represents the maneuver.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "symbolSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPImageSet",
          "text": "CPImageSet"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/symbolSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "symbolSet"
        }
      ],
      "role": "symbol",
      "title": "symbolSet",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/symbolset"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/trafficSide": {
      "abstract": [
        {
          "text": "A value that represents which side of the road the traffic drives on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trafficSide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPTrafficSide",
          "text": "CPTrafficSide"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/trafficSide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trafficSide"
        }
      ],
      "role": "symbol",
      "title": "trafficSide",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/trafficside"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/userInfo": {
      "abstract": [
        {
          "text": "A custom object associated with the maneuver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/userInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userInfo"
        }
      ],
      "role": "symbol",
      "title": "userInfo",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuver/userinfo"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverState": {
      "abstract": [
        {
          "text": "Values that describe the state of a maneuver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPManeuverState"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverState"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverState",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuverstate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType": {
      "abstract": [
        {
          "text": "Values that describe types of navigation maneuvers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPManeuverType"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverType"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverType",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuvertype"
    },
    "doc://com.apple.documentation/documentation/UIKit/NSTextAttachment": {
      "abstract": [
        {
          "text": "The values for the attachment characteristics of attributed strings and related objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextAttachment"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/NSTextAttachment",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextAttachment",
      "type": "topic",
      "url": "/documentation/UIKit/NSTextAttachment"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Maneuvers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverState",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType"
      ],
      "title": "Maneuvers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Providing-instructions",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/instructionVariants",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/dashboardInstructionVariants",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/notificationInstructionVariants"
      ],
      "title": "Providing instructions"
    },
    {
      "anchor": "Providing-attributed-instructions",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/attributedInstructionVariants",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/dashboardAttributedInstructionVariants",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/notificationAttributedInstructionVariants"
      ],
      "title": "Providing attributed instructions"
    },
    {
      "anchor": "Providing-travel-estimates",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/initialTravelEstimates"
      ],
      "title": "Providing travel estimates"
    },
    {
      "anchor": "Providing-symbol-images",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/symbolImage",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/dashboardSymbolImage",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/notificationSymbolImage",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/symbolSet"
      ],
      "title": "Providing symbol images"
    },
    {
      "anchor": "Providing-junction-images",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/junctionImage",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/dashboardJunctionImage"
      ],
      "title": "Providing junction images"
    },
    {
      "anchor": "Providing-junction-information",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/junctionType",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/junctionExitAngle",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/junctionElementAngles"
      ],
      "title": "Providing junction information"
    },
    {
      "anchor": "Providing-maneuver-information",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/maneuverType",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/roadFollowingManeuverVariants",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/linkedLaneGuidance",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/highwayExitLabel",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/trafficSide"
      ],
      "title": "Providing maneuver information"
    },
    {
      "anchor": "Providing-additional-information",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/userInfo"
      ],
      "title": "Providing additional information"
    },
    {
      "anchor": "Instance-properties",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/cardBackgroundColor"
      ],
      "title": "Instance properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CPManeuver"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Providing-instructions",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/instructionVariants",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/dashboardInstructionVariants",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/notificationInstructionVariants"
              ],
              "title": "Providing instructions"
            },
            {
              "anchor": "Providing-attributed-instructions",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/attributedInstructionVariants",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/dashboardAttributedInstructionVariants",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/notificationAttributedInstructionVariants"
              ],
              "title": "Providing attributed instructions"
            },
            {
              "anchor": "Providing-travel-estimates",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/initialTravelEstimates"
              ],
              "title": "Providing travel estimates"
            },
            {
              "anchor": "Providing-symbol-images",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/symbolImage",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/dashboardSymbolImage",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/notificationSymbolImage",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/symbolSet"
              ],
              "title": "Providing symbol images"
            },
            {
              "anchor": "Providing-junction-images",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/junctionImage",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/dashboardJunctionImage"
              ],
              "title": "Providing junction images"
            },
            {
              "anchor": "Providing-junction-information",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/junctionType",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/junctionExitAngle",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/junctionElementAngles"
              ],
              "title": "Providing junction information"
            },
            {
              "anchor": "Providing-maneuver-information",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/maneuverType",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/roadFollowingManeuverVariants",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/linkedLaneGuidance",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/highwayExitLabel",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/trafficSide"
              ],
              "title": "Providing maneuver information"
            },
            {
              "anchor": "Providing-additional-information",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/userInfo"
              ],
              "title": "Providing additional information"
            },
            {
              "anchor": "Instance-properties",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuver/cardBackgroundColor"
              ],
              "title": "Instance properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Maneuvers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverState",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverType"
              ],
              "title": "Maneuvers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CPManeuver"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1highwayExitLabel/title",
          "value": "highwayExitLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1highwayExitLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "highwayExitLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1notificationInstructionVariants/title",
          "value": "notificationInstructionVariants"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1notificationInstructionVariants/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "notificationInstructionVariants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1cardBackgroundColor/title",
          "value": "cardBackgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1cardBackgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cardBackgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver/title",
          "value": "CPManeuver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1instructionVariants/title",
          "value": "instructionVariants"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1instructionVariants/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "instructionVariants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType/title",
          "value": "CPManeuverType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1linkedLaneGuidance/title",
          "value": "linkedLaneGuidance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1linkedLaneGuidance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "linkedLaneGuidance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1symbolSet/title",
          "value": "symbolSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1symbolSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "symbolSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1attributedInstructionVariants/title",
          "value": "attributedInstructionVariants"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1attributedInstructionVariants/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attributedInstructionVariants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1userInfo/title",
          "value": "userInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1userInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1junctionExitAngle/title",
          "value": "junctionExitAngle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1junctionExitAngle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "junctionExitAngle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1notificationSymbolImage/title",
          "value": "notificationSymbolImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1notificationSymbolImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "notificationSymbolImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1junctionElementAngles/title",
          "value": "junctionElementAngles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1junctionElementAngles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "junctionElementAngles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1junctionType/title",
          "value": "junctionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1junctionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "junctionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1trafficSide/title",
          "value": "trafficSide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1trafficSide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trafficSide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1notificationAttributedInstructionVariants/title",
          "value": "notificationAttributedInstructionVariants"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1notificationAttributedInstructionVariants/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "notificationAttributedInstructionVariants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1symbolImage/title",
          "value": "symbolImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1symbolImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "symbolImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1initialTravelEstimates/title",
          "value": "initialTravelEstimates"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1initialTravelEstimates/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "initialTravelEstimates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverState/title",
          "value": "CPManeuverState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1dashboardInstructionVariants/title",
          "value": "dashboardInstructionVariants"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1dashboardInstructionVariants/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dashboardInstructionVariants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1dashboardSymbolImage/title",
          "value": "dashboardSymbolImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1dashboardSymbolImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dashboardSymbolImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1maneuverType/title",
          "value": "maneuverType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1maneuverType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maneuverType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1dashboardAttributedInstructionVariants/title",
          "value": "dashboardAttributedInstructionVariants"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1dashboardAttributedInstructionVariants/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dashboardAttributedInstructionVariants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1NSTextAttachment/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTextAttachment"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1junctionImage/title",
          "value": "junctionImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1junctionImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "junctionImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1roadFollowingManeuverVariants/title",
          "value": "roadFollowingManeuverVariants"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1roadFollowingManeuverVariants/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "roadFollowingManeuverVariants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1dashboardJunctionImage/title",
          "value": "dashboardJunctionImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuver~1dashboardJunctionImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dashboardJunctionImage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpmaneuver"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpmaneuver"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
