{
  "abstract": [
    {
      "text": "The protocol an object implements to handle events from a map template.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CPMapTemplateDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CPMapTemplateDelegate"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CPMapTemplateDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "CPMapTemplateDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CPMapTemplateDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPManeuverDisplayStyle": {
      "abstract": [
        {
          "text": "A display style that determines the visual layout for a maneuver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPManeuverDisplayStyle"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPManeuverDisplayStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPManeuverDisplayStyle"
        }
      ],
      "role": "symbol",
      "title": "CPManeuverDisplayStyle",
      "type": "topic",
      "url": "/documentation/carplay/cpmaneuverdisplaystyle"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection": {
      "abstract": [
        {
          "text": "The directions a user can pan (or move) a map displayed on the CarPlay screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PanDirection"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PanDirection"
        }
      ],
      "role": "symbol",
      "title": "CPMapTemplate.PanDirection",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/pandirection"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/mapDelegate": {
      "abstract": [
        {
          "text": "The object that serves as the delegate of the map template.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapDelegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CPMapTemplateDelegate",
          "text": "CPMapTemplateDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/mapDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapDelegate"
        }
      ],
      "role": "symbol",
      "title": "mapDelegate",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/mapdelegate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate": {
      "abstract": [
        {
          "text": "The protocol an object implements to handle events from a map template.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPMapTemplateDelegate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPMapTemplateDelegate"
        }
      ],
      "role": "symbol",
      "title": "CPMapTemplateDelegate",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didDismiss:dismissalContext:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the system dismissed the navigation alert.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didDismiss"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNavigationAlert",
          "text": "CPNavigationAlert"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dismissalContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNavigationAlert",
          "text": "CPNavigationAlert"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPNavigationAlertDismissalContext",
          "text": "DismissalContext"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didDismiss:dismissalContext:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:didDismissNavigationAlert:dismissalContext:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:didDismiss:dismissalContext:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:diddismiss:dismissalcontext:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didEndPanGestureWithVelocity:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the pan gesture ended with the specified velocity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didEndPanGestureWithVelocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didEndPanGestureWithVelocity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:didEndPanGestureWithVelocity:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:didEndPanGestureWithVelocity:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:didendpangesturewithvelocity:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didShow:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the system showed the navigation alert.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didShow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNavigationAlert",
          "text": "CPNavigationAlert"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didShow:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:didShowNavigationAlert:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:didShow:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:didshow:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didUpdatePanGestureWithTranslation:velocity:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the pan gesture changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdatePanGestureWithTranslation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "velocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didUpdatePanGestureWithTranslation:velocity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:didUpdatePanGestureWithTranslation:velocity:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:didUpdatePanGestureWithTranslation:velocity:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:didupdatepangesturewithtranslation:velocity:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:displayStyleFor:)": {
      "abstract": [
        {
          "text": "Asks the delegate for the maneuver’s display style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "displayStyleFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPManeuver",
          "text": "CPManeuver"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPManeuverDisplayStyle",
          "text": "CPManeuverDisplayStyle"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:displayStyleFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:displayStyleForManeuver:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:displayStyleFor:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:displaystylefor:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panBeganWith:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user is starting to pan the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "panBeganWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPPanDirection",
          "text": "PanDirection"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panBeganWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:panBeganWithDirection:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:panBeganWith:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:panbeganwith:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panEndedWith:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user stopped panning the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "panEndedWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPPanDirection",
          "text": "PanDirection"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panEndedWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:panEndedWithDirection:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:panEndedWith:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:panendedwith:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panWith:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user is panning in a certain direction on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "panWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPPanDirection",
          "text": "PanDirection"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:panWithDirection:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:panWith:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:panwith:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:selectedPreviewFor:using:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user selected a trip and route choice to preview.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "selectedPreviewFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTrip",
          "text": "CPTrip"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPRouteChoice",
          "text": "CPRouteChoice"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:selectedPreviewFor:using:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:selectedPreviewForTrip:usingRouteChoice:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:selectedPreviewFor:using:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:selectedpreviewfor:using:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:shouldShowNotificationFor:)-4mnm1": {
      "abstract": [
        {
          "text": "Asks the delegate whether the system should display the maneuver as a notification when the app is in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldShowNotificationFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPManeuver",
          "text": "CPManeuver"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:shouldShowNotificationFor:)-4mnm1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:shouldShowNotificationForManeuver:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:shouldShowNotificationFor:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:shouldshownotificationfor:)-4mnm1"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:shouldShowNotificationFor:)-5lu8a": {
      "abstract": [
        {
          "text": "Asks the delegate whether the system should display the navigation alert as a notification when the app is in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldShowNotificationFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNavigationAlert",
          "text": "CPNavigationAlert"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:shouldShowNotificationFor:)-5lu8a",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:shouldShowNotificationForNavigationAlert:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:shouldShowNotificationFor:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:shouldshownotificationfor:)-5lu8a"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:shouldUpdateNotificationFor:with:)": {
      "abstract": [
        {
          "text": "Asks the delegate whether the system should display the maneuver with updated travel estimates as a notification when the app is in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldUpdateNotificationFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPManeuver",
          "text": "CPManeuver"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTravelEstimates",
          "text": "CPTravelEstimates"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:shouldUpdateNotificationFor:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:shouldUpdateNotificationForManeuver:withTravelEstimates:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:shouldUpdateNotificationFor:with:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:shouldupdatenotificationfor:with:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:startedTrip:using:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user selected a trip and route choice to navigate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "startedTrip"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTrip",
          "text": "CPTrip"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPRouteChoice",
          "text": "CPRouteChoice"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:startedTrip:using:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:startedTrip:usingRouteChoice:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:startedTrip:using:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:startedtrip:using:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:willDismiss:dismissalContext:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the system is preparing to dismiss the navigation alert.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willDismiss"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNavigationAlert",
          "text": "CPNavigationAlert"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dismissalContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNavigationAlert",
          "text": "CPNavigationAlert"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPNavigationAlertDismissalContext",
          "text": "DismissalContext"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:willDismiss:dismissalContext:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:willDismissNavigationAlert:dismissalContext:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:willDismiss:dismissalContext:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:willdismiss:dismissalcontext:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:willShow:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the system will show the navigation alert.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willShow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNavigationAlert",
          "text": "CPNavigationAlert"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:willShow:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:willShowNavigationAlert:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:willShow:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:willshow:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidBeginPanGesture(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the pan gesture has started.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplateDidBeginPanGesture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidBeginPanGesture(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplateDidBeginPanGesture:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplateDidBeginPanGesture(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplatedidbeginpangesture(_:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidCancelNavigation(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the system canceled the navigation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplateDidCancelNavigation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidCancelNavigation(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplateDidCancelNavigation:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplateDidCancelNavigation(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplatedidcancelnavigation(_:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidDismissPanningInterface(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the panning interface is no longer visible on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplateDidDismissPanningInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidDismissPanningInterface(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplateDidDismissPanningInterface:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplateDidDismissPanningInterface(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplatediddismisspanninginterface(_:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidShowPanningInterface(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the panning interface is visible on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplateDidShowPanningInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidShowPanningInterface(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplateDidShowPanningInterface:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplateDidShowPanningInterface(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplatedidshowpanninginterface(_:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateShouldProvideNavigationMetadata(_:)": {
      "abstract": [
        {
          "text": "Asks the delegate whether the template should provide navigation metadata",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplateShouldProvideNavigationMetadata"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateShouldProvideNavigationMetadata(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplateShouldProvideNavigationMetadata:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplateShouldProvideNavigationMetadata(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplateshouldprovidenavigationmetadata(_:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateWillDismissPanningInterface(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the panning interface will disappear from the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplateWillDismissPanningInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateWillDismissPanningInterface(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplateWillDismissPanningInterface:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplateWillDismissPanningInterface(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplatewilldismisspanninginterface(_:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/DismissalContext": {
      "abstract": [
        {
          "text": "A set of reasons for dismissing a navigation alert.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DismissalContext"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/DismissalContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DismissalContext"
        }
      ],
      "role": "symbol",
      "title": "CPNavigationAlert.DismissalContext",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationalert/dismissalcontext"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-Map-Template-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/mapDelegate"
      ],
      "title": "Handling Map Template Events"
    }
  ],
  "topicSections": [
    {
      "anchor": "Setting-the-Display-Style",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:displayStyleFor:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPManeuverDisplayStyle"
      ],
      "title": "Setting the Display Style"
    },
    {
      "anchor": "Handling-Navigation-Events",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:selectedPreviewFor:using:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:startedTrip:using:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidCancelNavigation(_:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateShouldProvideNavigationMetadata(_:)"
      ],
      "title": "Handling Navigation Events"
    },
    {
      "anchor": "Displaying-Notifications",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:shouldShowNotificationFor:)-4mnm1",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:shouldUpdateNotificationFor:with:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:shouldShowNotificationFor:)-5lu8a"
      ],
      "title": "Displaying Notifications"
    },
    {
      "anchor": "Handling-Navigation-Alerts",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:willShow:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didShow:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:willDismiss:dismissalContext:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didDismiss:dismissalContext:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/DismissalContext"
      ],
      "title": "Handling Navigation Alerts"
    },
    {
      "anchor": "Panning-the-Map",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidShowPanningInterface(_:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateWillDismissPanningInterface(_:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidDismissPanningInterface(_:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidBeginPanGesture(_:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panBeganWith:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panWith:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panEndedWith:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didEndPanGestureWithVelocity:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didUpdatePanGestureWithTranslation:velocity:)"
      ],
      "title": "Panning the Map"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CPMapTemplateDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMapTemplateDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMapTemplateDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Setting-the-Display-Style",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:displayStyleFor:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPManeuverDisplayStyle"
              ],
              "title": "Setting the Display Style"
            },
            {
              "anchor": "Handling-Navigation-Events",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:selectedPreviewFor:using:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:startedTrip:using:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidCancelNavigation(_:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateShouldProvideNavigationMetadata(_:)"
              ],
              "title": "Handling Navigation Events"
            },
            {
              "anchor": "Displaying-Notifications",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:shouldShowNotificationFor:)-4mnm1",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:shouldUpdateNotificationFor:with:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:shouldShowNotificationFor:)-5lu8a"
              ],
              "title": "Displaying Notifications"
            },
            {
              "anchor": "Handling-Navigation-Alerts",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:willShow:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didShow:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:willDismiss:dismissalContext:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didDismiss:dismissalContext:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/DismissalContext"
              ],
              "title": "Handling Navigation Alerts"
            },
            {
              "anchor": "Panning-the-Map",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidShowPanningInterface(_:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateWillDismissPanningInterface(_:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidDismissPanningInterface(_:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidBeginPanGesture(_:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panBeganWith:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panWith:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panEndedWith:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didEndPanGestureWithVelocity:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didUpdatePanGestureWithTranslation:velocity:)"
              ],
              "title": "Panning the Map"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-Map-Template-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/mapDelegate"
              ],
              "title": "Handling Map Template Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CPMapTemplateDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:selectedPreviewFor:using:)/title",
          "value": "mapTemplate:selectedPreviewForTrip:usingRouteChoice:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:selectedPreviewFor:using:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:selectedPreviewForTrip:usingRouteChoice:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1DismissalContext/title",
          "value": "CPNavigationAlertDismissalContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1DismissalContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNavigationAlertDismissalContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1DismissalContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNavigationAlertDismissalContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:panBeganWith:)/title",
          "value": "mapTemplate:panBeganWithDirection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:panBeganWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:panBeganWithDirection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:displayStyleFor:)/title",
          "value": "mapTemplate:displayStyleForManeuver:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:displayStyleFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:displayStyleForManeuver:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateWillDismissPanningInterface(_:)/title",
          "value": "mapTemplateWillDismissPanningInterface:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateWillDismissPanningInterface(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplateWillDismissPanningInterface:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateDidBeginPanGesture(_:)/title",
          "value": "mapTemplateDidBeginPanGesture:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateDidBeginPanGesture(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplateDidBeginPanGesture:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:shouldShowNotificationFor:)-5lu8a/title",
          "value": "mapTemplate:shouldShowNotificationForNavigationAlert:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:shouldShowNotificationFor:)-5lu8a/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:shouldShowNotificationForNavigationAlert:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:didUpdatePanGestureWithTranslation:velocity:)/title",
          "value": "mapTemplate:didUpdatePanGestureWithTranslation:velocity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:didUpdatePanGestureWithTranslation:velocity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:didUpdatePanGestureWithTranslation:velocity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:didEndPanGestureWithVelocity:)/title",
          "value": "mapTemplate:didEndPanGestureWithVelocity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:didEndPanGestureWithVelocity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:didEndPanGestureWithVelocity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateDidShowPanningInterface(_:)/title",
          "value": "mapTemplateDidShowPanningInterface:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateDidShowPanningInterface(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplateDidShowPanningInterface:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:willShow:)/title",
          "value": "mapTemplate:willShowNavigationAlert:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:willShow:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:willShowNavigationAlert:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverDisplayStyle/title",
          "value": "CPManeuverDisplayStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverDisplayStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverDisplayStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPManeuverDisplayStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPManeuverDisplayStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:didDismiss:dismissalContext:)/title",
          "value": "mapTemplate:didDismissNavigationAlert:dismissalContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:didDismiss:dismissalContext:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:didDismissNavigationAlert:dismissalContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:shouldShowNotificationFor:)-4mnm1/title",
          "value": "mapTemplate:shouldShowNotificationForManeuver:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:shouldShowNotificationFor:)-4mnm1/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:shouldShowNotificationForManeuver:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateShouldProvideNavigationMetadata(_:)/title",
          "value": "mapTemplateShouldProvideNavigationMetadata:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateShouldProvideNavigationMetadata(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplateShouldProvideNavigationMetadata:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:willDismiss:dismissalContext:)/title",
          "value": "mapTemplate:willDismissNavigationAlert:dismissalContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:willDismiss:dismissalContext:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:willDismissNavigationAlert:dismissalContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:panWith:)/title",
          "value": "mapTemplate:panWithDirection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:panWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:panWithDirection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateDidCancelNavigation(_:)/title",
          "value": "mapTemplateDidCancelNavigation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateDidCancelNavigation(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplateDidCancelNavigation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:didShow:)/title",
          "value": "mapTemplate:didShowNavigationAlert:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:didShow:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:didShowNavigationAlert:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:startedTrip:using:)/title",
          "value": "mapTemplate:startedTrip:usingRouteChoice:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:startedTrip:using:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:startedTrip:usingRouteChoice:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:panEndedWith:)/title",
          "value": "mapTemplate:panEndedWithDirection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:panEndedWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:panEndedWithDirection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:shouldUpdateNotificationFor:with:)/title",
          "value": "mapTemplate:shouldUpdateNotificationForManeuver:withTravelEstimates:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:shouldUpdateNotificationFor:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:shouldUpdateNotificationForManeuver:withTravelEstimates:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection/title",
          "value": "CPPanDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPanDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPanDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateDidDismissPanningInterface(_:)/title",
          "value": "mapTemplateDidDismissPanningInterface:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateDidDismissPanningInterface(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplateDidDismissPanningInterface:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1mapDelegate/title",
          "value": "mapDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1mapDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mapDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate/title",
          "value": "CPMapTemplateDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMapTemplateDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMapTemplateDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpmaptemplatedelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpmaptemplatedelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
