{
  "abstract": [
    {
      "text": "A list template row that represents a conversation or contact.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CPMessageListItem",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CPMessageListItem"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CPMessageListItem"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CPMessageListItem"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CPMessageListItem"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "code": "CPMessageListItem",
              "type": "codeVoice"
            },
            {
              "text": " to display information about a conversation or a contact in a list template. Unlike ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you don’t provide a selection handler. Instead, when the user selects the row, CarPlay invokes Siri using the parameters you provide and begins a message compose, read, or reply flow.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The behavior of the list item when the user selects it depends on how you initialize or configure it. If the item has a phone number or email address, Siri launches the message compose flow. If the list item has an unread indicator, Siri launches the message read flow. Otherwise, Siri launches the message reply flow.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "CPMessageListItem",
              "type": "codeVoice"
            },
            {
              "text": " can display various auxiliary items in its leading and trailing regions. You describe these using a configuration object for each region. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/leadingConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/trailingConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "CarPlay doesn’t support custom list item types. Instead, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/userInfo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to attach a value to the list item that provides additional context, such as specifying  a model object that corresponds to the item.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "code": "CPMessageListItem",
                  "type": "codeVoice"
                },
                {
                  "text": " is available only in apps that have the communication entitlement.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListImageRowItem": {
      "abstract": [
        {
          "text": "A list template row that displays a series of images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPListImageRowItem"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListImageRowItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPListImageRowItem"
        }
      ],
      "role": "symbol",
      "title": "CPListImageRowItem",
      "type": "topic",
      "url": "/documentation/carplay/cplistimagerowitem"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListItem": {
      "abstract": [
        {
          "text": "A selectable row in a list template.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPListItem"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPListItem"
        }
      ],
      "role": "symbol",
      "title": "CPListItem",
      "type": "topic",
      "url": "/documentation/carplay/cplistitem"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListSection/init(items:header:headerSubtitle:headerImage:headerButton:sectionIndexTitle:)": {
      "abstract": [
        {
          "text": "Creates a section with list items, a header, a section index title, and section header details.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "items"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CPListTemplateItem",
          "text": "CPListTemplateItem"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "header"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "headerSubtitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "headerImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "headerButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPButton",
          "text": "CPButton"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "sectionIndexTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListSection/init(items:header:headerSubtitle:headerImage:headerButton:sectionIndexTitle:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithItems:header:headerSubtitle:headerImage:headerButton:sectionIndexTitle:"
        }
      ],
      "role": "symbol",
      "title": "init(items:header:headerSubtitle:headerImage:headerButton:sectionIndexTitle:)",
      "type": "topic",
      "url": "/documentation/carplay/cplistsection/init(items:header:headersubtitle:headerimage:headerbutton:sectionindextitle:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListSection/initWithItems:": {
      "abstract": [
        {
          "text": "Creates a section with list items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithItems:"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListSection/initWithItems:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithItems:"
        }
      ],
      "role": "symbol",
      "title": "initWithItems:",
      "type": "topic",
      "url": "/documentation/carplay/cplistsection/initwithitems:"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListSection/initWithItems:header:sectionIndexTitle:": {
      "abstract": [
        {
          "text": "Creates a section with list items, a header, and a section index title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithItems:header:sectionIndexTitle:"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListSection/initWithItems:header:sectionIndexTitle:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithItems:header:sectionIndexTitle:"
        }
      ],
      "role": "symbol",
      "title": "initWithItems:header:sectionIndexTitle:",
      "type": "topic",
      "url": "/documentation/carplay/cplistsection/initwithitems:header:sectionindextitle:"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListTemplateItem": {
      "abstract": [
        {
          "text": "A description of the common properties of all list item types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPListTemplateItem"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListTemplateItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPListTemplateItem"
        }
      ],
      "role": "symbol",
      "title": "CPListTemplateItem",
      "type": "topic",
      "url": "/documentation/carplay/cplisttemplateitem"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem": {
      "abstract": [
        {
          "text": "A list template row that represents a conversation or contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPMessageListItem"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPMessageListItem"
        }
      ],
      "role": "symbol",
      "title": "CPMessageListItem",
      "type": "topic",
      "url": "/documentation/carplay/cpmessagelistitem"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/conversationIdentifier": {
      "abstract": [
        {
          "text": "The conversation’s unique identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conversationIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/conversationIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "conversationIdentifier"
        }
      ],
      "role": "symbol",
      "title": "conversationIdentifier",
      "type": "topic",
      "url": "/documentation/carplay/cpmessagelistitem/conversationidentifier"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/detailText": {
      "abstract": [
        {
          "text": "The list item’s secondary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detailText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/detailText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "detailText"
        }
      ],
      "role": "symbol",
      "title": "detailText",
      "type": "topic",
      "url": "/documentation/carplay/cpmessagelistitem/detailtext"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/init(conversationIdentifier:text:leadingConfiguration:trailingConfiguration:detailText:trailingText:)": {
      "abstract": [
        {
          "text": "Creates a list item that represents an existing conversation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "conversationIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "text"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "leadingConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMessageListItemLeadingConfiguration",
          "text": "CPMessageListItemLeadingConfiguration"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "trailingConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMessageListItemTrailingConfiguration",
          "text": "CPMessageListItemTrailingConfiguration"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "detailText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "trailingText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/init(conversationIdentifier:text:leadingConfiguration:trailingConfiguration:detailText:trailingText:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithConversationIdentifier:text:leadingConfiguration:trailingConfiguration:detailText:trailingText:"
        }
      ],
      "role": "symbol",
      "title": "init(conversationIdentifier:text:leadingConfiguration:trailingConfiguration:detailText:trailingText:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmessagelistitem/init(conversationidentifier:text:leadingconfiguration:trailingconfiguration:detailtext:trailingtext:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/init(fullName:phoneOrEmailAddress:leadingConfiguration:trailingConfiguration:detailText:trailingText:)": {
      "abstract": [
        {
          "text": "Creates a list item that represents a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "fullName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "phoneOrEmailAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "leadingConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMessageListItemLeadingConfiguration",
          "text": "CPMessageListItemLeadingConfiguration"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "trailingConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMessageListItemTrailingConfiguration",
          "text": "CPMessageListItemTrailingConfiguration"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "detailText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "trailingText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/init(fullName:phoneOrEmailAddress:leadingConfiguration:trailingConfiguration:detailText:trailingText:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithFullName:phoneOrEmailAddress:leadingConfiguration:trailingConfiguration:detailText:trailingText:"
        }
      ],
      "role": "symbol",
      "title": "init(fullName:phoneOrEmailAddress:leadingConfiguration:trailingConfiguration:detailText:trailingText:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmessagelistitem/init(fullname:phoneoremailaddress:leadingconfiguration:trailingconfiguration:detailtext:trailingtext:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/isEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates if the item is enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/isEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enabled"
        }
      ],
      "role": "symbol",
      "title": "isEnabled",
      "type": "topic",
      "url": "/documentation/carplay/cpmessagelistitem/isenabled"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/leadingConfiguration": {
      "abstract": [
        {
          "text": "The configuration of the list item’s leading region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leadingConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMessageListItemLeadingConfiguration",
          "text": "CPMessageListItemLeadingConfiguration"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/leadingConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leadingConfiguration"
        }
      ],
      "role": "symbol",
      "title": "leadingConfiguration",
      "type": "topic",
      "url": "/documentation/carplay/cpmessagelistitem/leadingconfiguration"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/phoneOrEmailAddress": {
      "abstract": [
        {
          "text": "The contact’s phone number or email address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "phoneOrEmailAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/phoneOrEmailAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "phoneOrEmailAddress"
        }
      ],
      "role": "symbol",
      "title": "phoneOrEmailAddress",
      "type": "topic",
      "url": "/documentation/carplay/cpmessagelistitem/phoneoremailaddress"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/text": {
      "abstract": [
        {
          "text": "The list item’s primary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "text"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/text",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "text"
        }
      ],
      "role": "symbol",
      "title": "text",
      "type": "topic",
      "url": "/documentation/carplay/cpmessagelistitem/text"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/trailingConfiguration": {
      "abstract": [
        {
          "text": "The configuration of the list item’s trailing region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailingConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMessageListItemTrailingConfiguration",
          "text": "CPMessageListItemTrailingConfiguration"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/trailingConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trailingConfiguration"
        }
      ],
      "role": "symbol",
      "title": "trailingConfiguration",
      "type": "topic",
      "url": "/documentation/carplay/cpmessagelistitem/trailingconfiguration"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/trailingText": {
      "abstract": [
        {
          "text": "The list item’s supplementary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailingText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/trailingText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trailingText"
        }
      ],
      "role": "symbol",
      "title": "trailingText",
      "type": "topic",
      "url": "/documentation/carplay/cpmessagelistitem/trailingtext"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/userInfo": {
      "abstract": [
        {
          "text": "An opaque value for the list item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/userInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userInfo"
        }
      ],
      "role": "symbol",
      "title": "userInfo",
      "type": "topic",
      "url": "/documentation/carplay/cpmessagelistitem/userinfo"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItemLeadingConfiguration": {
      "abstract": [
        {
          "text": "An object that describes the appearance of a message list item’s leading region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPMessageListItemLeadingConfiguration"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItemLeadingConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPMessageListItemLeadingConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CPMessageListItemLeadingConfiguration",
      "type": "topic",
      "url": "/documentation/carplay/cpmessagelistitemleadingconfiguration"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItemTrailingConfiguration": {
      "abstract": [
        {
          "text": "An object that describes the appearance of a message list item’s trailing region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPMessageListItemTrailingConfiguration"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItemTrailingConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPMessageListItemTrailingConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CPMessageListItemTrailingConfiguration",
      "type": "topic",
      "url": "/documentation/carplay/cpmessagelistitemtrailingconfiguration"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPSelectableListItem": {
      "abstract": [
        {
          "text": "A description of a selectable list item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPSelectableListItem"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPSelectableListItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPSelectableListItem"
        }
      ],
      "role": "symbol",
      "title": "CPSelectableListItem",
      "type": "topic",
      "url": "/documentation/carplay/cpselectablelistitem"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPListTemplateItem",
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Section",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPListSection/init(items:header:headerSubtitle:headerImage:headerButton:sectionIndexTitle:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPListTemplateItem",
        "doc://com.apple.carplay/documentation/CarPlay/CPSelectableListItem",
        "doc://com.apple.carplay/documentation/CarPlay/CPListItem",
        "doc://com.apple.carplay/documentation/CarPlay/CPListImageRowItem"
      ],
      "title": "Creating a Section"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Message-List-Item",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/init(conversationIdentifier:text:leadingConfiguration:trailingConfiguration:detailText:trailingText:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/init(fullName:phoneOrEmailAddress:leadingConfiguration:trailingConfiguration:detailText:trailingText:)"
      ],
      "title": "Creating a Message List Item"
    },
    {
      "anchor": "Managing-the-Message-Context",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/conversationIdentifier",
        "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/phoneOrEmailAddress"
      ],
      "title": "Managing the Message Context"
    },
    {
      "anchor": "Managing-Content",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/text",
        "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/detailText",
        "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/trailingText"
      ],
      "title": "Managing Content"
    },
    {
      "anchor": "Managing-Leading-and-Trailing-Configurations",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/leadingConfiguration",
        "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItemLeadingConfiguration",
        "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/trailingConfiguration",
        "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItemTrailingConfiguration"
      ],
      "title": "Managing Leading and Trailing Configurations"
    },
    {
      "anchor": "Managing-Supplementary-Information",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/userInfo"
      ],
      "title": "Managing Supplementary Information"
    },
    {
      "anchor": "Enabling-Items",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/isEnabled"
      ],
      "title": "Enabling Items"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CPMessageListItem"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMessageListItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMessageListItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Message-List-Item",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/init(conversationIdentifier:text:leadingConfiguration:trailingConfiguration:detailText:trailingText:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/init(fullName:phoneOrEmailAddress:leadingConfiguration:trailingConfiguration:detailText:trailingText:)"
              ],
              "title": "Creating a Message List Item"
            },
            {
              "anchor": "Managing-the-Message-Context",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/conversationIdentifier",
                "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/phoneOrEmailAddress"
              ],
              "title": "Managing the Message Context"
            },
            {
              "anchor": "Managing-Content",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/text",
                "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/detailText",
                "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/trailingText"
              ],
              "title": "Managing Content"
            },
            {
              "anchor": "Managing-Leading-and-Trailing-Configurations",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/leadingConfiguration",
                "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItemLeadingConfiguration",
                "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/trailingConfiguration",
                "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItemTrailingConfiguration"
              ],
              "title": "Managing Leading and Trailing Configurations"
            },
            {
              "anchor": "Managing-Supplementary-Information",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/userInfo"
              ],
              "title": "Managing Supplementary Information"
            },
            {
              "anchor": "Enabling-Items",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPMessageListItem/isEnabled"
              ],
              "title": "Enabling Items"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPListTemplateItem"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Section",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPListSection/initWithItems:",
                "doc://com.apple.carplay/documentation/CarPlay/CPListSection/initWithItems:header:sectionIndexTitle:",
                "doc://com.apple.carplay/documentation/CarPlay/CPListSection/init(items:header:headerSubtitle:headerImage:headerButton:sectionIndexTitle:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPListTemplateItem",
                "doc://com.apple.carplay/documentation/CarPlay/CPSelectableListItem",
                "doc://com.apple.carplay/documentation/CarPlay/CPListItem",
                "doc://com.apple.carplay/documentation/CarPlay/CPListImageRowItem"
              ],
              "title": "Creating a Section"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CPMessageListItem"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItemTrailingConfiguration/title",
          "value": "CPMessageListItemTrailingConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItemTrailingConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMessageListItemTrailingConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItemTrailingConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMessageListItemTrailingConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1trailingConfiguration/title",
          "value": "trailingConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1trailingConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trailingConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem/title",
          "value": "CPListItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1userInfo/title",
          "value": "userInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1userInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListTemplateItem/title",
          "value": "CPListTemplateItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListTemplateItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListTemplateItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListTemplateItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListTemplateItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1init(conversationIdentifier:text:leadingConfiguration:trailingConfiguration:detailText:trailingText:)/title",
          "value": "initWithConversationIdentifier:text:leadingConfiguration:trailingConfiguration:detailText:trailingText:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1init(conversationIdentifier:text:leadingConfiguration:trailingConfiguration:detailText:trailingText:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithConversationIdentifier:text:leadingConfiguration:trailingConfiguration:detailText:trailingText:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1detailText/title",
          "value": "detailText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1detailText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "detailText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1trailingText/title",
          "value": "trailingText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1trailingText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trailingText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1text/title",
          "value": "text"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1text/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1init(fullName:phoneOrEmailAddress:leadingConfiguration:trailingConfiguration:detailText:trailingText:)/title",
          "value": "initWithFullName:phoneOrEmailAddress:leadingConfiguration:trailingConfiguration:detailText:trailingText:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1init(fullName:phoneOrEmailAddress:leadingConfiguration:trailingConfiguration:detailText:trailingText:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithFullName:phoneOrEmailAddress:leadingConfiguration:trailingConfiguration:detailText:trailingText:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem/title",
          "value": "CPMessageListItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMessageListItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMessageListItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1conversationIdentifier/title",
          "value": "conversationIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1conversationIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "conversationIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1phoneOrEmailAddress/title",
          "value": "phoneOrEmailAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1phoneOrEmailAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "phoneOrEmailAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1isEnabled/title",
          "value": "enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1isEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1leadingConfiguration/title",
          "value": "leadingConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItem~1leadingConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leadingConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListSection~1init(items:header:headerSubtitle:headerImage:headerButton:sectionIndexTitle:)/title",
          "value": "initWithItems:header:headerSubtitle:headerImage:headerButton:sectionIndexTitle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListSection~1init(items:header:headerSubtitle:headerImage:headerButton:sectionIndexTitle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithItems:header:headerSubtitle:headerImage:headerButton:sectionIndexTitle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListImageRowItem/title",
          "value": "CPListImageRowItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListImageRowItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListImageRowItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListImageRowItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListImageRowItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItemLeadingConfiguration/title",
          "value": "CPMessageListItemLeadingConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItemLeadingConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMessageListItemLeadingConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMessageListItemLeadingConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMessageListItemLeadingConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSelectableListItem/title",
          "value": "CPSelectableListItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSelectableListItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPSelectableListItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSelectableListItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPSelectableListItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpmessagelistitem"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpmessagelistitem"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
