{
  "abstract": [
    {
      "text": "An alert that displays map- or navigation-related information to the user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CPNavigationAlert",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CPNavigationAlert"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CPNavigationAlert"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CPNavigationAlert"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CPNavigationAlert"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To display a navigation alert, create an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and pass it to the map template’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/present(navigationAlert:animated:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. When creating an alert, you must provide a title, action, and duration. The duration tells the system how long to show the alert before automatically dismissing it. You can also include a subtitle and secondary action when needed.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The system displays the primary and secondary actions as buttons on the alert. After the user taps the button, the system calls the action’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPAlertAction/handler",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " block, which is where your app performs the requested action. The system also dismisses the alert after the user taps the button. However, your app can dismiss the alert without any user interaction by calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/dismissNavigationAlert(animated:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPAlertAction/handler": {
      "abstract": [
        {
          "text": "The closure that CarPlay invokes after the user taps the action button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CPAlertActionHandler",
          "text": "CPAlertActionHandler"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPAlertAction/handler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handler"
        }
      ],
      "role": "symbol",
      "title": "handler",
      "type": "topic",
      "url": "/documentation/carplay/cpalertaction/handler"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/currentNavigationAlert": {
      "abstract": [
        {
          "text": "The visible navigation alert.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentNavigationAlert"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNavigationAlert",
          "text": "CPNavigationAlert"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/currentNavigationAlert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentNavigationAlert"
        }
      ],
      "role": "symbol",
      "title": "currentNavigationAlert",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/currentnavigationalert"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/dismissNavigationAlert(animated:completion:)": {
      "abstract": [
        {
          "text": "Tells the map template to dismiss the visable navigation alert.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dismissNavigationAlert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/dismissNavigationAlert(animated:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dismissNavigationAlertAnimated:completion:"
        }
      ],
      "role": "symbol",
      "title": "dismissNavigationAlert(animated:completion:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/dismissnavigationalert(animated:completion:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/present(navigationAlert:animated:)": {
      "abstract": [
        {
          "text": "Displays a navigation alert on the map template.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "present"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "navigationAlert"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNavigationAlert",
          "text": "CPNavigationAlert"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/present(navigationAlert:animated:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentNavigationAlert:animated:"
        }
      ],
      "role": "symbol",
      "title": "present(navigationAlert:animated:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/present(navigationalert:animated:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert": {
      "abstract": [
        {
          "text": "An alert that displays map- or navigation-related information to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNavigationAlert"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNavigationAlert"
        }
      ],
      "role": "symbol",
      "title": "CPNavigationAlert",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationalert"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/DismissalContext": {
      "abstract": [
        {
          "text": "A set of reasons for dismissing a navigation alert.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DismissalContext"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/DismissalContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DismissalContext"
        }
      ],
      "role": "symbol",
      "title": "CPNavigationAlert.DismissalContext",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationalert/dismissalcontext"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/duration": {
      "abstract": [
        {
          "text": "The amount of time, in seconds, that the alert is visible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/duration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "duration"
        }
      ],
      "role": "symbol",
      "title": "duration",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationalert/duration"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/image": {
      "abstract": [
        {
          "text": "An image displayed in the navigation alert.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/image",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "image"
        }
      ],
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationalert/image"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/imageSet": {
      "abstract": [
        {
          "text": "An image set displayed in the navigation alert.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPImageSet",
          "text": "CPImageSet"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/imageSet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageSet"
        }
      ],
      "role": "symbol",
      "title": "imageSet",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationalert/imageset"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/init(titleVariants:subtitleVariants:image:primaryAction:secondaryAction:duration:)": {
      "abstract": [
        {
          "text": "Creates a navigation alert.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "titleVariants"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "subtitleVariants"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "primaryAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPAlertAction",
          "text": "CPAlertAction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "secondaryAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPAlertAction",
          "text": "CPAlertAction"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/init(titleVariants:subtitleVariants:image:primaryAction:secondaryAction:duration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTitleVariants:subtitleVariants:image:primaryAction:secondaryAction:duration:"
        }
      ],
      "role": "symbol",
      "title": "init(titleVariants:subtitleVariants:image:primaryAction:secondaryAction:duration:)",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationalert/init(titlevariants:subtitlevariants:image:primaryaction:secondaryaction:duration:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/init(titleVariants:subtitleVariants:imageSet:primaryAction:secondaryAction:duration:)": {
      "abstract": [
        {
          "text": "Creates a navigation alert.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "titleVariants"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "subtitleVariants"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "imageSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPImageSet",
          "text": "CPImageSet"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "primaryAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPAlertAction",
          "text": "CPAlertAction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "secondaryAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPAlertAction",
          "text": "CPAlertAction"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/init(titleVariants:subtitleVariants:imageSet:primaryAction:secondaryAction:duration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTitleVariants:subtitleVariants:imageSet:primaryAction:secondaryAction:duration:"
        }
      ],
      "role": "symbol",
      "title": "init(titleVariants:subtitleVariants:imageSet:primaryAction:secondaryAction:duration:)",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationalert/init(titlevariants:subtitlevariants:imageset:primaryaction:secondaryaction:duration:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/primaryAction": {
      "abstract": [
        {
          "text": "The primary action, and button, for the navigation alert.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPAlertAction",
          "text": "CPAlertAction"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/primaryAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "primaryAction"
        }
      ],
      "role": "symbol",
      "title": "primaryAction",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationalert/primaryaction"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/secondaryAction": {
      "abstract": [
        {
          "text": "An optional secondary action, and button, for the navigation alert.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondaryAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPAlertAction",
          "text": "CPAlertAction"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/secondaryAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "secondaryAction"
        }
      ],
      "role": "symbol",
      "title": "secondaryAction",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationalert/secondaryaction"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/subtitleVariants": {
      "abstract": [
        {
          "text": "An array of subtitle strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtitleVariants"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/subtitleVariants",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subtitleVariants"
        }
      ],
      "role": "symbol",
      "title": "subtitleVariants",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationalert/subtitlevariants"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/titleVariants": {
      "abstract": [
        {
          "text": "An array of title strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleVariants"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/titleVariants",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleVariants"
        }
      ],
      "role": "symbol",
      "title": "titleVariants",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationalert/titlevariants"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/updateTitleVariants(_:subtitleVariants:)": {
      "abstract": [
        {
          "text": "Updates title and subtitle variants.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateTitleVariants"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "subtitleVariants"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/updateTitleVariants(_:subtitleVariants:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateTitleVariants:subtitleVariants:"
        }
      ],
      "role": "symbol",
      "title": "updateTitleVariants(_:subtitleVariants:)",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationalert/updatetitlevariants(_:subtitlevariants:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlertMinimumDuration": {
      "abstract": [
        {
          "text": "A constant that defines the minimum amount of time that an alert is visible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNavigationAlertMinimumDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlertMinimumDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNavigationAlertMinimumDuration"
        }
      ],
      "role": "symbol",
      "title": "CPNavigationAlertMinimumDuration",
      "type": "topic",
      "url": "/documentation/carplay/cpnavigationalertminimumduration"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Displaying-a-Navigation-Alert",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/present(navigationAlert:animated:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/dismissNavigationAlert(animated:completion:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/currentNavigationAlert"
      ],
      "title": "Displaying a Navigation Alert"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Navigation-Alert",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/init(titleVariants:subtitleVariants:image:primaryAction:secondaryAction:duration:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/init(titleVariants:subtitleVariants:imageSet:primaryAction:secondaryAction:duration:)"
      ],
      "title": "Creating a Navigation Alert"
    },
    {
      "anchor": "Getting-Titles",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/titleVariants",
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/subtitleVariants",
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/updateTitleVariants(_:subtitleVariants:)"
      ],
      "title": "Getting Titles"
    },
    {
      "anchor": "Getting-the-Alert-Image",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/image",
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/imageSet"
      ],
      "title": "Getting the Alert Image"
    },
    {
      "anchor": "Getting-the-Actions",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/primaryAction",
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/secondaryAction"
      ],
      "title": "Getting the Actions"
    },
    {
      "anchor": "Getting-the-Alert-Duration",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/duration",
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlertMinimumDuration"
      ],
      "title": "Getting the Alert Duration"
    },
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/DismissalContext"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CPNavigationAlert"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNavigationAlert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNavigationAlert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Navigation-Alert",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/init(titleVariants:subtitleVariants:image:primaryAction:secondaryAction:duration:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/init(titleVariants:subtitleVariants:imageSet:primaryAction:secondaryAction:duration:)"
              ],
              "title": "Creating a Navigation Alert"
            },
            {
              "anchor": "Getting-Titles",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/titleVariants",
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/subtitleVariants",
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/updateTitleVariants(_:subtitleVariants:)"
              ],
              "title": "Getting Titles"
            },
            {
              "anchor": "Getting-the-Alert-Image",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/image",
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/imageSet"
              ],
              "title": "Getting the Alert Image"
            },
            {
              "anchor": "Getting-the-Actions",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/primaryAction",
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/secondaryAction"
              ],
              "title": "Getting the Actions"
            },
            {
              "anchor": "Getting-the-Alert-Duration",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/duration",
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlertMinimumDuration"
              ],
              "title": "Getting the Alert Duration"
            },
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPNavigationAlert/DismissalContext"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Displaying-a-Navigation-Alert",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/present(navigationAlert:animated:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/dismissNavigationAlert(animated:completion:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/currentNavigationAlert"
              ],
              "title": "Displaying a Navigation Alert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CPNavigationAlert"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1updateTitleVariants(_:subtitleVariants:)/title",
          "value": "updateTitleVariants:subtitleVariants:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1updateTitleVariants(_:subtitleVariants:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateTitleVariants:subtitleVariants:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1secondaryAction/title",
          "value": "secondaryAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1secondaryAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "secondaryAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1present(navigationAlert:animated:)/title",
          "value": "presentNavigationAlert:animated:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1present(navigationAlert:animated:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentNavigationAlert:animated:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1primaryAction/title",
          "value": "primaryAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1primaryAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "primaryAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1dismissNavigationAlert(animated:completion:)/title",
          "value": "dismissNavigationAlertAnimated:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1dismissNavigationAlert(animated:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dismissNavigationAlertAnimated:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1init(titleVariants:subtitleVariants:image:primaryAction:secondaryAction:duration:)/title",
          "value": "initWithTitleVariants:subtitleVariants:image:primaryAction:secondaryAction:duration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1init(titleVariants:subtitleVariants:image:primaryAction:secondaryAction:duration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTitleVariants:subtitleVariants:image:primaryAction:secondaryAction:duration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlertMinimumDuration/title",
          "value": "CPNavigationAlertMinimumDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlertMinimumDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNavigationAlertMinimumDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1duration/title",
          "value": "duration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1duration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "duration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1imageSet/title",
          "value": "imageSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1imageSet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1DismissalContext/title",
          "value": "CPNavigationAlertDismissalContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1DismissalContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNavigationAlertDismissalContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1DismissalContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNavigationAlertDismissalContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1image/title",
          "value": "image"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1image/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "image"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1currentNavigationAlert/title",
          "value": "currentNavigationAlert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1currentNavigationAlert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentNavigationAlert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert/title",
          "value": "CPNavigationAlert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNavigationAlert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNavigationAlert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1titleVariants/title",
          "value": "titleVariants"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1titleVariants/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "titleVariants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPAlertAction~1handler/title",
          "value": "handler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPAlertAction~1handler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "handler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1init(titleVariants:subtitleVariants:imageSet:primaryAction:secondaryAction:duration:)/title",
          "value": "initWithTitleVariants:subtitleVariants:imageSet:primaryAction:secondaryAction:duration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1init(titleVariants:subtitleVariants:imageSet:primaryAction:secondaryAction:duration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTitleVariants:subtitleVariants:imageSet:primaryAction:secondaryAction:duration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1subtitleVariants/title",
          "value": "subtitleVariants"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNavigationAlert~1subtitleVariants/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subtitleVariants"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpnavigationalert"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpnavigationalert"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
