{
  "abstract": [
    {
      "text": "A shared system template that displays Now Playing information.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CPNowPlayingTemplate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CPNowPlayingTemplate"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CPNowPlayingTemplate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CPNowPlayingTemplate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CPNowPlayingTemplate"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Now Playing template displays information from ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MediaPlayer/MPNowPlayingInfoCenter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MediaPlayer/MPNowPlayingSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Instead of instantiating your own Now Playing template, CarPlay provides a shared instance that you configure. The template displays a series of playback control buttons, as well as information about the current album and artist, and what’s coming up next.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When enabling your Now Playing template’s Album-Artist and Up Next buttons, you must create an object that implements the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplateObserver",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol and register it as an observer by calling the template’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/add(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To display the Now Playing template, call your interface controller’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInterfaceController/pushTemplate(_:animated:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to push it onto your navigation hierarchy. You can’t display the Now Playing template modally.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When CarPlay presents Now Playing information for your app, it uses the shared instance of this template.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "code": "CPNowPlayingTemplate",
                  "type": "codeVoice"
                },
                {
                  "text": " is only available in apps with the audio entitlement.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInterfaceController/pushTemplate(_:animated:completion:)": {
      "abstract": [
        {
          "text": "Adds the specified template to the navigation hierarchy and displays it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pushTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTemplate",
          "text": "CPTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInterfaceController/pushTemplate(_:animated:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pushTemplate:animated:completion:"
        }
      ],
      "role": "symbol",
      "title": "pushTemplate(_:animated:completion:)",
      "type": "topic",
      "url": "/documentation/carplay/cpinterfacecontroller/pushtemplate(_:animated:completion:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingAddToLibraryButton": {
      "abstract": [
        {
          "text": "A button for adding the current playing item to a collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingAddToLibraryButton"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingAddToLibraryButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNowPlayingAddToLibraryButton"
        }
      ],
      "role": "symbol",
      "title": "CPNowPlayingAddToLibraryButton",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingaddtolibrarybutton"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingButton": {
      "abstract": [
        {
          "text": "The abstract base class that Now Playing template buttons use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingButton"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNowPlayingButton"
        }
      ],
      "role": "symbol",
      "title": "CPNowPlayingButton",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingbutton"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingImageButton": {
      "abstract": [
        {
          "text": "A button that displays an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingImageButton"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingImageButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNowPlayingImageButton"
        }
      ],
      "role": "symbol",
      "title": "CPNowPlayingImageButton",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingimagebutton"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingMoreButton": {
      "abstract": [
        {
          "text": "A button for presenting more options to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingMoreButton"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingMoreButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNowPlayingMoreButton"
        }
      ],
      "role": "symbol",
      "title": "CPNowPlayingMoreButton",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingmorebutton"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingPlaybackRateButton": {
      "abstract": [
        {
          "text": "A button for cycling through the available playback rates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingPlaybackRateButton"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingPlaybackRateButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNowPlayingPlaybackRateButton"
        }
      ],
      "role": "symbol",
      "title": "CPNowPlayingPlaybackRateButton",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingplaybackratebutton"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingRepeatButton": {
      "abstract": [
        {
          "text": "A button for cycling through the available repeat modes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingRepeatButton"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingRepeatButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNowPlayingRepeatButton"
        }
      ],
      "role": "symbol",
      "title": "CPNowPlayingRepeatButton",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingrepeatbutton"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingShuffleButton": {
      "abstract": [
        {
          "text": "A button for cycling through the available shuffle modes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingShuffleButton"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingShuffleButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNowPlayingShuffleButton"
        }
      ],
      "role": "symbol",
      "title": "CPNowPlayingShuffleButton",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingshufflebutton"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate": {
      "abstract": [
        {
          "text": "A shared system template that displays Now Playing information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNowPlayingTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPNowPlayingTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingtemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/add(_:)": {
      "abstract": [
        {
          "text": "Registers an observer that receives Now Playing template events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CPNowPlayingTemplateObserver",
          "text": "CPNowPlayingTemplateObserver"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/add(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addObserver:"
        }
      ],
      "role": "symbol",
      "title": "add(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingtemplate/add(_:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/isAlbumArtistButtonEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the album and artist string is a button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAlbumArtistButtonEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/isAlbumArtistButtonEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "albumArtistButtonEnabled"
        }
      ],
      "role": "symbol",
      "title": "isAlbumArtistButtonEnabled",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingtemplate/isalbumartistbuttonenabled"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/isUpNextButtonEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that manages the display of the Up Next button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isUpNextButtonEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/isUpNextButtonEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "upNextButtonEnabled"
        }
      ],
      "role": "symbol",
      "title": "isUpNextButtonEnabled",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingtemplate/isupnextbuttonenabled"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/nowPlayingButtons": {
      "abstract": [
        {
          "text": "The Now Playing template’s playback control buttons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nowPlayingButtons"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNowPlayingButton",
          "text": "CPNowPlayingButton"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/nowPlayingButtons",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nowPlayingButtons"
        }
      ],
      "role": "symbol",
      "title": "nowPlayingButtons",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingtemplate/nowplayingbuttons"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/nowPlayingMode": {
      "abstract": [
        {
          "text": "The currently-active now playing mode. See @c CPNowPlayingMode.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nowPlayingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNowPlayingMode",
          "text": "CPNowPlayingMode"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/nowPlayingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nowPlayingMode"
        }
      ],
      "role": "symbol",
      "title": "nowPlayingMode",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingtemplate/nowplayingmode"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/remove(_:)": {
      "abstract": [
        {
          "text": "Removes an observer from receiving Now Playing template events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "remove"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CPNowPlayingTemplateObserver",
          "text": "CPNowPlayingTemplateObserver"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/remove(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeObserver:"
        }
      ],
      "role": "symbol",
      "title": "remove(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingtemplate/remove(_:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/shared": {
      "abstract": [
        {
          "text": "The Now Playing template the system provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shared"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNowPlayingTemplate",
          "text": "CPNowPlayingTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/shared",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sharedTemplate"
        }
      ],
      "role": "symbol",
      "title": "shared",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingtemplate/shared"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/upNextTitle": {
      "abstract": [
        {
          "text": "The title for the Up Next button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "upNextTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/upNextTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "upNextTitle"
        }
      ],
      "role": "symbol",
      "title": "upNextTitle",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingtemplate/upnexttitle"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/updateNowPlayingButtons(_:)": {
      "abstract": [
        {
          "text": "Updates the playback control buttons the template displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateNowPlayingButtons"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNowPlayingButton",
          "text": "CPNowPlayingButton"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/updateNowPlayingButtons(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateNowPlayingButtons:"
        }
      ],
      "role": "symbol",
      "title": "updateNowPlayingButtons(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingtemplate/updatenowplayingbuttons(_:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplateObserver": {
      "abstract": [
        {
          "text": "The methods for responding to the user interacting with the Now Playing template.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingTemplateObserver"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplateObserver",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNowPlayingTemplateObserver"
        }
      ],
      "role": "symbol",
      "title": "CPNowPlayingTemplateObserver",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingtemplateobserver"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplate": {
      "abstract": [
        {
          "text": "An abstract base class for interface templates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cptemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/integrating-carplay-with-your-music-app": {
      "abstract": [
        {
          "text": "Configure your music app to work with CarPlay by displaying a custom UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/integrating-carplay-with-your-music-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Integrating CarPlay with Your Music App",
      "type": "topic",
      "url": "/documentation/carplay/integrating-carplay-with-your-music-app"
    },
    "doc://com.apple.documentation/documentation/MediaPlayer/MPNowPlayingInfoCenter": {
      "abstract": [
        {
          "text": "An object for setting the Now Playing information for media that your app plays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingInfoCenter"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MediaPlayer/MPNowPlayingInfoCenter",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPNowPlayingInfoCenter",
      "type": "topic",
      "url": "/documentation/MediaPlayer/MPNowPlayingInfoCenter"
    },
    "doc://com.apple.documentation/documentation/MediaPlayer/MPNowPlayingSession": {
      "abstract": [
        {
          "text": "An object that manages Now Playing information and remote commands for multiple players.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPNowPlayingSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MediaPlayer/MPNowPlayingSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPNowPlayingSession",
      "type": "topic",
      "url": "/documentation/MediaPlayer/MPNowPlayingSession"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPTemplate"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/integrating-carplay-with-your-music-app"
      ],
      "title": "Audio"
    }
  ],
  "topicSections": [
    {
      "anchor": "Managing-the-Shared-Template",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/shared"
      ],
      "title": "Managing the Shared Template"
    },
    {
      "anchor": "Managing-the-Templates-Buttons",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/nowPlayingButtons",
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/updateNowPlayingButtons(_:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingButton",
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingImageButton",
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingAddToLibraryButton",
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingMoreButton",
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingPlaybackRateButton",
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingRepeatButton",
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingShuffleButton"
      ],
      "title": "Managing the Template’s Buttons"
    },
    {
      "anchor": "Managing-Albums-Artists-and-Up-Next",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/isAlbumArtistButtonEnabled",
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/isUpNextButtonEnabled",
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/upNextTitle"
      ],
      "title": "Managing Albums, Artists, and Up Next"
    },
    {
      "anchor": "Observing-Now-Playing-Events",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/add(_:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/remove(_:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplateObserver"
      ],
      "title": "Observing Now Playing Events"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/nowPlayingMode"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CPNowPlayingTemplate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-the-Shared-Template",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/shared"
              ],
              "title": "Managing the Shared Template"
            },
            {
              "anchor": "Managing-the-Templates-Buttons",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/nowPlayingButtons",
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/updateNowPlayingButtons(_:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingButton",
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingImageButton",
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingAddToLibraryButton",
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingMoreButton",
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingPlaybackRateButton",
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingRepeatButton",
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingShuffleButton"
              ],
              "title": "Managing the Template’s Buttons"
            },
            {
              "anchor": "Managing-Albums-Artists-and-Up-Next",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/isAlbumArtistButtonEnabled",
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/isUpNextButtonEnabled",
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/upNextTitle"
              ],
              "title": "Managing Albums, Artists, and Up Next"
            },
            {
              "anchor": "Observing-Now-Playing-Events",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/add(_:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/remove(_:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplateObserver"
              ],
              "title": "Observing Now Playing Events"
            },
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/nowPlayingMode"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPTemplate"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/integrating-carplay-with-your-music-app"
              ],
              "title": "Audio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CPNowPlayingTemplate"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CPTemplate",
                    "text": "CPTemplate"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingImageButton/title",
          "value": "CPNowPlayingImageButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingImageButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingImageButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingImageButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingImageButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingAddToLibraryButton/title",
          "value": "CPNowPlayingAddToLibraryButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingAddToLibraryButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingAddToLibraryButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingAddToLibraryButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingAddToLibraryButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingButton/title",
          "value": "CPNowPlayingButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingPlaybackRateButton/title",
          "value": "CPNowPlayingPlaybackRateButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingPlaybackRateButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingPlaybackRateButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingPlaybackRateButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingPlaybackRateButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingShuffleButton/title",
          "value": "CPNowPlayingShuffleButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingShuffleButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingShuffleButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingShuffleButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingShuffleButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInterfaceController~1pushTemplate(_:animated:completion:)/title",
          "value": "pushTemplate:animated:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInterfaceController~1pushTemplate(_:animated:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pushTemplate:animated:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1add(_:)/title",
          "value": "addObserver:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1add(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addObserver:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingMoreButton/title",
          "value": "CPNowPlayingMoreButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingMoreButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingMoreButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingMoreButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingMoreButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1shared/title",
          "value": "sharedTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1shared/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sharedTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1upNextTitle/title",
          "value": "upNextTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1upNextTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "upNextTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1nowPlayingMode/title",
          "value": "nowPlayingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1nowPlayingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nowPlayingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1isUpNextButtonEnabled/title",
          "value": "upNextButtonEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1isUpNextButtonEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "upNextButtonEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplateObserver/title",
          "value": "CPNowPlayingTemplateObserver"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplateObserver/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingTemplateObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplateObserver/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingTemplateObserver"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MediaPlayer~1MPNowPlayingInfoCenter/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MPNowPlayingInfoCenter"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1remove(_:)/title",
          "value": "removeObserver:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1remove(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeObserver:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate/title",
          "value": "CPNowPlayingTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1updateNowPlayingButtons(_:)/title",
          "value": "updateNowPlayingButtons:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1updateNowPlayingButtons(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateNowPlayingButtons:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1nowPlayingButtons/title",
          "value": "nowPlayingButtons"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1nowPlayingButtons/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nowPlayingButtons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MediaPlayer~1MPNowPlayingSession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MPNowPlayingSession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate/title",
          "value": "CPTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingRepeatButton/title",
          "value": "CPNowPlayingRepeatButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingRepeatButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingRepeatButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingRepeatButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingRepeatButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1isAlbumArtistButtonEnabled/title",
          "value": "albumArtistButtonEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1isAlbumArtistButtonEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "albumArtistButtonEnabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpnowplayingtemplate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpnowplayingtemplate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
