{
  "abstract": [
    {
      "text": "A button for cycling through the available repeat modes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingRepeatButton"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CPNowPlayingRepeatButton",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CPNowPlayingRepeatButton"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CPNowPlayingRepeatButton"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CPNowPlayingRepeatButton"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CPNowPlayingRepeatButton"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "CPNowPlayingRepeatButton",
              "type": "codeVoice"
            },
            {
              "text": " is a concrete subclass of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingButton",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Use the button’s handler to invoke your existing functionality for cycling through repeat modes, using the same ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MediaPlayer/MPChangeRepeatModeCommand",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that you provide to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/MediaPlayer/MPRemoteCommandCenter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "CarPlay uses ",
              "type": "text"
            },
            {
              "code": "MPRemoteCommandCenter",
              "type": "codeVoice"
            },
            {
              "text": " to observe changes to the repeat mode and updates the button’s appearance accordingly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingAddToLibraryButton": {
      "abstract": [
        {
          "text": "A button for adding the current playing item to a collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingAddToLibraryButton"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingAddToLibraryButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNowPlayingAddToLibraryButton"
        }
      ],
      "role": "symbol",
      "title": "CPNowPlayingAddToLibraryButton",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingaddtolibrarybutton"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingButton": {
      "abstract": [
        {
          "text": "The abstract base class that Now Playing template buttons use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingButton"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNowPlayingButton"
        }
      ],
      "role": "symbol",
      "title": "CPNowPlayingButton",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingbutton"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingImageButton": {
      "abstract": [
        {
          "text": "A button that displays an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingImageButton"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingImageButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNowPlayingImageButton"
        }
      ],
      "role": "symbol",
      "title": "CPNowPlayingImageButton",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingimagebutton"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingMoreButton": {
      "abstract": [
        {
          "text": "A button for presenting more options to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingMoreButton"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingMoreButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNowPlayingMoreButton"
        }
      ],
      "role": "symbol",
      "title": "CPNowPlayingMoreButton",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingmorebutton"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingPlaybackRateButton": {
      "abstract": [
        {
          "text": "A button for cycling through the available playback rates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingPlaybackRateButton"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingPlaybackRateButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNowPlayingPlaybackRateButton"
        }
      ],
      "role": "symbol",
      "title": "CPNowPlayingPlaybackRateButton",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingplaybackratebutton"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingRepeatButton": {
      "abstract": [
        {
          "text": "A button for cycling through the available repeat modes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingRepeatButton"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingRepeatButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNowPlayingRepeatButton"
        }
      ],
      "role": "symbol",
      "title": "CPNowPlayingRepeatButton",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingrepeatbutton"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingShuffleButton": {
      "abstract": [
        {
          "text": "A button for cycling through the available shuffle modes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingShuffleButton"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingShuffleButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNowPlayingShuffleButton"
        }
      ],
      "role": "symbol",
      "title": "CPNowPlayingShuffleButton",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingshufflebutton"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/nowPlayingButtons": {
      "abstract": [
        {
          "text": "The Now Playing template’s playback control buttons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nowPlayingButtons"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNowPlayingButton",
          "text": "CPNowPlayingButton"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/nowPlayingButtons",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nowPlayingButtons"
        }
      ],
      "role": "symbol",
      "title": "nowPlayingButtons",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingtemplate/nowplayingbuttons"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/updateNowPlayingButtons(_:)": {
      "abstract": [
        {
          "text": "Updates the playback control buttons the template displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateNowPlayingButtons"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNowPlayingButton",
          "text": "CPNowPlayingButton"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/updateNowPlayingButtons(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateNowPlayingButtons:"
        }
      ],
      "role": "symbol",
      "title": "updateNowPlayingButtons(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingtemplate/updatenowplayingbuttons(_:)"
    },
    "doc://com.apple.documentation/documentation/MediaPlayer/MPChangeRepeatModeCommand": {
      "abstract": [
        {
          "text": "An object that responds to requests to change the current repeat mode used during playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPChangeRepeatModeCommand"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MediaPlayer/MPChangeRepeatModeCommand",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPChangeRepeatModeCommand",
      "type": "topic",
      "url": "/documentation/MediaPlayer/MPChangeRepeatModeCommand"
    },
    "doc://com.apple.documentation/documentation/MediaPlayer/MPRemoteCommandCenter": {
      "abstract": [
        {
          "text": "An object that responds to remote control events sent by external accessories and system controls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MPRemoteCommandCenter"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/MediaPlayer/MPRemoteCommandCenter",
      "kind": "symbol",
      "role": "symbol",
      "title": "MPRemoteCommandCenter",
      "type": "topic",
      "url": "/documentation/MediaPlayer/MPRemoteCommandCenter"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingButton"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-Templates-Buttons",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/nowPlayingButtons",
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/updateNowPlayingButtons(_:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingButton",
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingImageButton",
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingAddToLibraryButton",
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingMoreButton",
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingPlaybackRateButton",
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingShuffleButton"
      ],
      "title": "Managing the Template’s Buttons"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CPNowPlayingRepeatButton"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingRepeatButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingRepeatButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingButton"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-the-Templates-Buttons",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/nowPlayingButtons",
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate/updateNowPlayingButtons(_:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingButton",
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingImageButton",
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingAddToLibraryButton",
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingMoreButton",
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingPlaybackRateButton",
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingShuffleButton"
              ],
              "title": "Managing the Template’s Buttons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CPNowPlayingRepeatButton"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingButton",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CPNowPlayingButton",
                    "text": "CPNowPlayingButton"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingRepeatButton/title",
          "value": "CPNowPlayingRepeatButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingRepeatButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingRepeatButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingRepeatButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingRepeatButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1updateNowPlayingButtons(_:)/title",
          "value": "updateNowPlayingButtons:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1updateNowPlayingButtons(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateNowPlayingButtons:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingShuffleButton/title",
          "value": "CPNowPlayingShuffleButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingShuffleButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingShuffleButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingShuffleButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingShuffleButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MediaPlayer~1MPRemoteCommandCenter/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MPRemoteCommandCenter"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1MediaPlayer~1MPChangeRepeatModeCommand/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MPChangeRepeatModeCommand"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MPRemoteCommand",
              "text": "MPRemoteCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1nowPlayingButtons/title",
          "value": "nowPlayingButtons"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate~1nowPlayingButtons/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nowPlayingButtons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingPlaybackRateButton/title",
          "value": "CPNowPlayingPlaybackRateButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingPlaybackRateButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingPlaybackRateButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingPlaybackRateButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingPlaybackRateButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingImageButton/title",
          "value": "CPNowPlayingImageButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingImageButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingImageButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingImageButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingImageButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingAddToLibraryButton/title",
          "value": "CPNowPlayingAddToLibraryButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingAddToLibraryButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingAddToLibraryButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingAddToLibraryButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingAddToLibraryButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingMoreButton/title",
          "value": "CPNowPlayingMoreButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingMoreButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingMoreButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingMoreButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingMoreButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingButton/title",
          "value": "CPNowPlayingButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingButton"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpnowplayingrepeatbutton"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpnowplayingrepeatbutton"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
