{
  "abstract": [
    {
      "text": "A template that provides the ability to search for a destination and see a list of search results.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CPSearchTemplate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CPSearchTemplate"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CPSearchTemplate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CPSearchTemplate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CPSearchTemplate"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this template to provide the ability to search for a destination. When CarPlay displays the template, the user sees a search field, a Cancel button, and a localized keyboard. The template also shows the list of search results after your app completes the search request.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Some vehicles may limit the display of the keyboard. Check the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPSessionConfiguration/limitedUserInterfaces",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property to determine whether there are limits.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "To use a search template, create an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and set its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplate/delegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to an object that conforms to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplateDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol. Push the template onto the navigation hierarchy by calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInterfaceController/pushTemplate(_:animated:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on the interface controller. This presents the search template to the user.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "As the user enters text into the search field, the system calls the delegate method ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplateDelegate/searchTemplate(_:updatedSearchText:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", indicating that your app should retrieve the search result. After retrieving the results, call ",
              "type": "text"
            },
            {
              "code": "completionHandler",
              "type": "codeVoice"
            },
            {
              "text": " to return an array of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects—one list item for each search result item.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When the user selects an item from the search result, the system calls the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplateDelegate/searchTemplate(_:selectedResult:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method on the delegate object. The delegate performs any necessary operations to process the selected item, then calls the completion handler to let the system know it can continue.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInterfaceController/pushTemplate(_:animated:completion:)": {
      "abstract": [
        {
          "text": "Adds the specified template to the navigation hierarchy and displays it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pushTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTemplate",
          "text": "CPTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInterfaceController/pushTemplate(_:animated:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pushTemplate:animated:completion:"
        }
      ],
      "role": "symbol",
      "title": "pushTemplate(_:animated:completion:)",
      "type": "topic",
      "url": "/documentation/carplay/cpinterfacecontroller/pushtemplate(_:animated:completion:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListItem": {
      "abstract": [
        {
          "text": "A selectable row in a list template.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPListItem"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPListItem"
        }
      ],
      "role": "symbol",
      "title": "CPListItem",
      "type": "topic",
      "url": "/documentation/carplay/cplistitem"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate": {
      "abstract": [
        {
          "text": "A template that displays a navigation overlay that your app draws on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPMapTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPMapTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPMapTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplate": {
      "abstract": [
        {
          "text": "A template that provides the ability to search for a destination and see a list of search results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPSearchTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPSearchTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPSearchTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cpsearchtemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplate/delegate": {
      "abstract": [
        {
          "text": "The object that serves as the search template’s delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)CPSearchTemplateDelegate",
          "text": "CPSearchTemplateDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplate/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/carplay/cpsearchtemplate/delegate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplateDelegate": {
      "abstract": [
        {
          "text": "The interface for an object that serves as the search template’s delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPSearchTemplateDelegate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplateDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPSearchTemplateDelegate"
        }
      ],
      "role": "symbol",
      "title": "CPSearchTemplateDelegate",
      "type": "topic",
      "url": "/documentation/carplay/cpsearchtemplatedelegate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplateDelegate/searchTemplate(_:selectedResult:completionHandler:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user selected an item from the search result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPSearchTemplate",
          "text": "CPSearchTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "selectedResult"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPListItem",
          "text": "CPListItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplateDelegate/searchTemplate(_:selectedResult:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchTemplate:selectedResult:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "searchTemplate(_:selectedResult:completionHandler:)",
      "type": "topic",
      "url": "/documentation/carplay/cpsearchtemplatedelegate/searchtemplate(_:selectedresult:completionhandler:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplateDelegate/searchTemplate(_:updatedSearchText:completionHandler:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user updated the search criteria text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPSearchTemplate",
          "text": "CPSearchTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "updatedSearchText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPListItem",
          "text": "CPListItem"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplateDelegate/searchTemplate(_:updatedSearchText:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchTemplate:updatedSearchText:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "searchTemplate(_:updatedSearchText:completionHandler:)",
      "type": "topic",
      "url": "/documentation/carplay/cpsearchtemplatedelegate/searchtemplate(_:updatedsearchtext:completionhandler:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPSessionConfiguration/limitedUserInterfaces": {
      "abstract": [
        {
          "text": "A bit mask value that indicates the user interface limits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "limitedUserInterfaces"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPLimitableUserInterface",
          "text": "CPLimitableUserInterface"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPSessionConfiguration/limitedUserInterfaces",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "limitedUserInterfaces"
        }
      ],
      "role": "symbol",
      "title": "limitedUserInterfaces",
      "type": "topic",
      "url": "/documentation/carplay/cpsessionconfiguration/limiteduserinterfaces"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplate": {
      "abstract": [
        {
          "text": "An abstract base class for interface templates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cptemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationDashboardScene": {
      "abstract": [
        {
          "text": "A CarPlay scene that controls your app’s dashboard navigation window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTemplateApplicationDashboardScene"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationDashboardScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTemplateApplicationDashboardScene"
        }
      ],
      "role": "symbol",
      "title": "CPTemplateApplicationDashboardScene",
      "type": "topic",
      "url": "/documentation/carplay/cptemplateapplicationdashboardscene"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationDashboardSceneDelegate": {
      "abstract": [
        {
          "text": "The methods for responding to the life-cycle events of your navigation app’s dashboard scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTemplateApplicationDashboardSceneDelegate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationDashboardSceneDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTemplateApplicationDashboardSceneDelegate"
        }
      ],
      "role": "symbol",
      "title": "CPTemplateApplicationDashboardSceneDelegate",
      "type": "topic",
      "url": "/documentation/carplay/cptemplateapplicationdashboardscenedelegate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPVoiceControlTemplate": {
      "abstract": [
        {
          "text": "A template that displays a voice control indicator during audio input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPVoiceControlTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPVoiceControlTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPVoiceControlTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPVoiceControlTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cpvoicecontroltemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/integrating-carplay-with-your-navigation-app": {
      "abstract": [
        {
          "text": "Configure your navigation app to work with CarPlay by displaying your custom map and directions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/integrating-carplay-with-your-navigation-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Integrating CarPlay with Your Navigation App",
      "type": "topic",
      "url": "/documentation/carplay/integrating-carplay-with-your-navigation-app"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPTemplate"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Navigation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/integrating-carplay-with-your-navigation-app",
        "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationDashboardScene",
        "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationDashboardSceneDelegate",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate",
        "doc://com.apple.carplay/documentation/CarPlay/CPVoiceControlTemplate"
      ],
      "title": "Navigation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Providing-a-Search-Template-Delegate",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplate/delegate",
        "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplateDelegate"
      ],
      "title": "Providing a Search Template Delegate"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CPSearchTemplate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPSearchTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPSearchTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Providing-a-Search-Template-Delegate",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplate/delegate",
                "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplateDelegate"
              ],
              "title": "Providing a Search Template Delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPTemplate"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Navigation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/integrating-carplay-with-your-navigation-app",
                "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationDashboardScene",
                "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationDashboardSceneDelegate",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate",
                "doc://com.apple.carplay/documentation/CarPlay/CPVoiceControlTemplate"
              ],
              "title": "Navigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CPSearchTemplate"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CPTemplate",
                    "text": "CPTemplate"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate/title",
          "value": "CPTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSearchTemplate/title",
          "value": "CPSearchTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSearchTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPSearchTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSearchTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPSearchTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate/title",
          "value": "CPMapTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMapTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMapTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem/title",
          "value": "CPListItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSearchTemplateDelegate~1searchTemplate(_:updatedSearchText:completionHandler:)/title",
          "value": "searchTemplate:updatedSearchText:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSearchTemplateDelegate~1searchTemplate(_:updatedSearchText:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchTemplate:updatedSearchText:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSearchTemplateDelegate/title",
          "value": "CPSearchTemplateDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSearchTemplateDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPSearchTemplateDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSearchTemplateDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPSearchTemplateDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPVoiceControlTemplate/title",
          "value": "CPVoiceControlTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPVoiceControlTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPVoiceControlTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPVoiceControlTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPVoiceControlTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationDashboardSceneDelegate/title",
          "value": "CPTemplateApplicationDashboardSceneDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationDashboardSceneDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplateApplicationDashboardSceneDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationDashboardSceneDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplateApplicationDashboardSceneDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationDashboardScene/title",
          "value": "CPTemplateApplicationDashboardScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationDashboardScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplateApplicationDashboardScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationDashboardScene/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplateApplicationDashboardScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSessionConfiguration~1limitedUserInterfaces/title",
          "value": "limitedUserInterfaces"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSessionConfiguration~1limitedUserInterfaces/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "limitedUserInterfaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSearchTemplateDelegate~1searchTemplate(_:selectedResult:completionHandler:)/title",
          "value": "searchTemplate:selectedResult:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSearchTemplateDelegate~1searchTemplate(_:selectedResult:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchTemplate:selectedResult:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInterfaceController~1pushTemplate(_:animated:completion:)/title",
          "value": "pushTemplate:animated:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInterfaceController~1pushTemplate(_:animated:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pushTemplate:animated:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSearchTemplate~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSearchTemplate~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpsearchtemplate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpsearchtemplate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
